### ISSUE TITLE
Issues with hub.rb

### ISSUE THREAD

**Issue by denpatin** [caskroom/homebrew-cask#10005]
Hello guys,

My **first** report is, that I wanted to install the github's hub utility but it failed.

Firstly because of the incorrect link:
![screen shot 2015-03-12 at 12 52 09 am](https://cloud.githubusercontent.com/assets/1271040/6607872/5465899c-c853-11e4-9553-4af570048368.png)

Then I have changed the link and the archive has been downloaded but then the process failed:
![screen shot 2015-03-12 at 12 59 37 am](https://cloud.githubusercontent.com/assets/1271040/6607893/87d9b924-c853-11e4-857d-6b7da7554071.png)

The **second** question is: There's already a new version of this utility, that means, that the RC finally became v2.2.0. But, now there isn't a version for 32 bit systems. I presume then, that there isn't any necessity to perform a check whether the target machine is 23- or 64-bit, is it? To think logically, no Macs (from 2012?) are 32-bit. But if this check is actual, so how can I indicate that only 64-bit machines fit? I have an alternative: for 64-bit machines give the possibility to download v2.2.0, and for 32-bit only v2.2.0-rc. But, anyway, it is more a dog-nail than something useful.

Thanks!

**Comment by vitorgalvao** [comment]
Thank you for the report. Should be fixed now.

**Comment by denpatin** [comment]
Great, now works! Thanks!
