### ISSUE TITLE
Add zap stanza for vagrant to remove ~/.vagrant.d

### ISSUE THREAD

**Issue by RogerThiede** [caskroom/homebrew-cask#10008]
homebrew-cask/Casks@cf23ebeb66acaa860fc30b40fc4d1e1a5b0d2460 vagrant.rb doesn't currently have a zap stanza and leaves a ~/.vagrant.d folder after `brew cask uninstall vagrant`.
~/.vagrant.d stores [Vagrant Boxes](http://docs.vagrantup.com/v2/boxes.html) and/or full Virtual Machine images.

I can provide a pull request but it's not yet clear to me whether or not this folder location is configurable and/or if this is an accepted usage of the zap stanza given this folder contains user created data.

**Comment by vitorgalvao** [comment]
> it's not yet clear to me (…) if this is an accepted usage of the zap stanza given this folder contains user created data.

Neither to us. Care to [voice your opinion](https://github.com/caskroom/homebrew-cask/issues/10156)?

**Comment by vitorgalvao** [comment]
[A decision has been made](https://github.com/caskroom/homebrew-cask/issues/10156#issuecomment-124555469). Care to submit the PR to add those directories?
