### ISSUE TITLE
code.google.com sunset?

### ISSUE THREAD

**Issue by HughP** [caskroom/homebrew-cask#10055]
It is my understanding that code.google.com is being sunset. Is this true? If it is do maintainers here have a method for moving references to projects? I mean there are a lot of references still to repos at code.google.com https://github.com/caskroom/homebrew-cask/search?utf8=%E2%9C%93&q=code.google.com

**Comment by vitorgalvao** [comment]
Yes, [it is true](http://google-opensource.blogspot.se/2015/03/farewell-to-google-code.html).

>  do maintainers here have a method for moving references to projects?

Only links that are officially supported are carried in this repo, so we can’t just start moving stuff wherever we please. Apps still in Google Code that move away to new homes will be getting updates in casks (if they’re used, which this will provide some insight into) as time passes, while the other ones; the abandoned ones the developer doesn’t move and no one forks will simply die and have to be removed.
