### ISSUE TITLE
bitcoin-core 0.10.0 cask - failed command xattr

### ISSUE THREAD

**Issue by SuperHenkie** [caskroom/homebrew-cask#10059]
When trying to install Bitcoin Core using `brew cask install bitcoin-core` I'm getting this error:

> ==> Failed command:
["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\\\"Bitcoin Core.app\\\")", "#<Pathname:/Users/Rog/Applications/Bitcoin Core.app>"]
> 
> ==> Output of failed command:
> 
> ==> Exit status of failed command:
> #<Process::Status: pid 24815 exit 1>

I already tried updating + upgrading + cleaning up brew and cask, and `brew doctor` says "Your system is ready to brew."

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/9667.
