### ISSUE TITLE
Cask request: boot2docker-status

### ISSUE THREAD

**Issue by andreineculau** [caskroom/homebrew-cask#10071]
http://boot2docker-status.nickgartmann.com/

**Comment by vitorgalvao** [comment]
When making a request, please make it clear in the issue’s title.

**Comment by andreineculau** [comment]
didn't know. got it.

On Mon, Mar 16, 2015 at 6:45 PM, Vítor Galvão <notifications@github.com>
wrote:

> When making a request, please make it clear in the issue’s title.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caskroom/homebrew-cask/issues/10071#issuecomment-81835826>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>
