### ISSUE TITLE
brew cask install <app> - Staged installation

### ISSUE THREAD

**Issue by ladislas** [caskroom/homebrew-cask#10089]
Hi there! :)

I'm kinda reopening @dschinkel's issue https://github.com/caskroom/homebrew-cask/issues/9974 about the staged installation.

I've been having this issue for the last 10 casks I've been trying to install. Most notorious are Mailbox App, Skype, Sublime-Text and Spotify.

Here after are screenshots of the Mailbox installation. For every app it's the same, the message says the installation stagged and when I `cd` to the app folder, I find a symlink of the `Applications` folder.

![screenshot 2015-03-15 16 19 03](https://cloud.githubusercontent.com/assets/2206544/6656611/1ead7786-cb2f-11e4-9360-d560ffad4e84.png)

![screenshot 2015-03-15 16 18 54](https://cloud.githubusercontent.com/assets/2206544/6656613/2461513e-cb2f-11e4-8f6c-86bc3622a7c4.png)

This happens on a brand new Macbook Pro, `brew doctor` says that everything is fine.

And here is the output of `brew cask doctor`: https://gist.github.com/ladislas/097d87cbe98b7b33dd19

**Comment by ndr-qef** [comment]
Everything appears to be working normally, but there may be some confusion about what “staging” and “installation” mean in homebrew-cask.

The staging process merely extracts the contents of a package as downloaded. Many dmg packages include an `/Applications` symlink for ease of manual installation, causing it to appear in the staging location.

Afterward, `brew cask install` symlinks the desired artifacts (in this case, `Mailbox (Beta).app`) to your application folder, `/Applications`.

**Comment by ladislas** [comment]
so if I understand correctly, the the last message with the beer means that everything went well?

![screenshot 2015-03-17 10 03 03](https://cloud.githubusercontent.com/assets/2206544/6683989/06396034-cc8d-11e4-8831-35651318c41e.png)

**Comment by vitorgalvao** [comment]
> the last message with the beer means that everything went well?

Yes.

Just a clarification, though. The symlinks will, by default, be placed in `~/Applications`. To set them in `/Applications` you need to set the [`—appdir` option](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options). [This will be reversed in the future](https://github.com/caskroom/homebrew-cask/pull/9178).

Closing as solved.

**Comment by ladislas** [comment]
Okay thank you very much! :)

Yes, I know about the `--appdir` option and I'm using it. Great to see it will become the default behavior.
