### ISSUE TITLE
brew cask install from local packages

### ISSUE THREAD

**Issue by rhacker** [caskroom/homebrew-cask#10090]
Firstly, I would like to thanks for the great work. 
Secondly, is there anyway we can setup to install a cask with the source from local storage instead of an url ? 

Thanks

**Comment by vitorgalvao** [comment]
There is not. I also doubt there’d be much demand for the feature. What’s the use case?

**Comment by phinze** [comment]
hi @rhacker thanks for the kinds words!

Maybe I'm missing a step here, but there's no reason a URL can't be `file:///path/to/some/app.dmg` no?

And if that's the case - theoretically you could make a private / custom tap that included casks and the relevant binaries?

Maybe I'm missing something though. :grin:

**Comment by vitorgalvao** [comment]
Thought about that, but though `curl` might choke on such a case. Just goes to show I should’ve tested it. Apologies for the wrong information, @rhacker, and thank you @phinze for the correction.

Closing as solved.

**Comment by Amorymeltzer** [comment]
If you're using a `.dmg`, is there any reason not to skip the the hassle of a custom tap and just dump the dmg in `/Library/Caches/Homebrew`?  Feels simpler to just `mv && brew cask install xyz.rb`.  You'll need to ensure the file is named appropriately (cask-version) but should work just fine.

**Comment by phinze** [comment]
@Amorymeltzer Yeah depends on if the use case is "I don't want to publish my DMG at a public URL" or "I want to short circuit the download". If it's the latter, then your approach works AOK as well. :ok_hand:

**Comment by Amorymeltzer** [comment]
Good point.   Figured it was wanting to download a bunch of files on a high speed connection but installing later without internet/on a slow connection/different machine.  I've been guilty of that.

**Comment by rhacker** [comment]
@phinze awesome to point it out the file protocol.
@Amorymeltzer exactly what I'm trying to do
