### ISSUE TITLE
add tags to the list of stanzas

### ISSUE THREAD

**Issue by tcarlsen** [caskroom/homebrew-cask#10103]
at the moment you need to know what exact application you want to install for using homebrew-cask,  adding `tags` to the list of stanzas will make the `brew cask search` function more useful.

Example for the [Atom](https://github.com/caskroom/homebrew-cask/blob/master/Casks/atom.rb) cask
```ruby
tags: [
    'ide',
    'editor'
]
```

**Comment by vitorgalvao** [comment]
The suggestion is welcome, but [we don’t intend to become a discoverability service](https://github.com/caskroom/homebrew-cask/issues/4323#issuecomment-67257513). This has been [discussed and refused multiple times](https://github.com/caskroom/homebrew-cask/issues/5425#issuecomment-49512837), as [it is not part of the goals of homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/3817#issuecomment-39868330). Amongst other things, the logistics are unsustainable.
