### ISSUE TITLE
Sandbox Apps cannot use input method installed by cask

### ISSUE THREAD

**Issue by linc01n** [caskroom/homebrew-cask#10115]
`input_method` is `Hbc::Artifact::Symlinked` class. So under `~/Library/Input Methods` we symlink the input method to `/opt/homebrew-cask/Caskroom/...`

If the application is using sandboxing, the cask input method will not work correctly.

> 19/3/15 11:10:05.654 am sandboxd[406]: ([277]) Telegram(277) deny file-read-data /opt/homebrew-cask/Caskroom/openvanilla/1.0.11/OpenVanillaInstaller.app/Contents/Resources/OpenVanilla.app

**Comment by linc01n** [comment]
To solve this problem is to copy the Input Methods to `~/Library/Input Methods` instead of soft linking it. But the only cask using `input_method` santza is the one I submitted call `openvanilla`

It seems I am the only user for this cask and I implemented the original `input_method` santza in the first place.

**Comment by vitorgalvao** [comment]
Well, lets change its behaviour to move instead of linking, then: #13201.
