### ISSUE TITLE
Add Syncthing Cask

### ISSUE THREAD

**Issue by pablocrivella** [caskroom/homebrew-cask#10182]
https://syncthing.net/

**Comment by bcomnes** [comment]
This is already in [homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/syncthing.rb), is this one different somehow?

**Comment by pablocrivella** [comment]
It appears to be the same, but since i couldn't find it using ```brew cask search``` command i assumed it wasn't present.

**Comment by bcomnes** [comment]
I'm not exactly sure what cask wants in terms of duplication, just pointing this out.

**Comment by phinze** [comment]
Generally a Cask is a binary install and a Formula is a source build. Will have to investigate Syncthing's distribution further to determine what to do. :+1:

**Comment by DomT4** [comment]
> Formula is a source build

Although worth noting that formulae have their own binary builds generated by Homebrew, so although its a source build, most people never actually build from source per se.

**Comment by phinze** [comment]
Yup yup. Conceptually what I said is still true, but that's a good detail to point out.
