### ISSUE TITLE
Tinyumbrella deprecated: Use new Umbrella

### ISSUE THREAD

**Issue by Miladiir** [caskroom/homebrew-cask#10221]
http://blog.firmwareumbrella.com/2015/03/tinyumbrella-a7a8-fetch-shsh-from-device/

The new beta (that is just as un-/stable as the previous version) replaces the old Tinyumbrella and introduces shsh fetching from some devices.

This is a reminder for myself to create a new recipe.

**Comment by CraftThatBlock** [comment]
@vitorgalvao Fixed in #10282

**Comment by designorant** [comment]
This is misleading.

7.12 has not been deprecated, and it is still listed as an official version.

8.x, while providing *one* extra functionality, lacks on every single other level. See: http://blog.firmwareumbrella.com/page/6/ for explanation on its limited capabilities (ie. does not come with 'kick out of DFU' option).

I suggest that 8.x in kept in https://github.com/caskroom/homebrew-versions

**Comment by vitorgalvao** [comment]
@designorant The beta is flaunted all over the homepage, though. The developer’s clearly incentivising it.

**Comment by designorant** [comment]
Well, that does not change the fact that the beta functionality is very limited. If you search for "iPhone DFU loop", TinyUmbrella is mentioned in pretty much every single article. Kicking the phone out of DFU is something that the 8.x does not provide (stability aside). What TU 8.x provides is purely theoretical as far as I understand the topic (downgrading A7/A8 devices without signed SHSH blobs).

[We do have rules](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#latest-stable-versions) when it comes to things like that, and I believe there is a big difference in between fully featured unstable and a very limited unstable versions.

Furthermore, the beta version of iTerm2 2.0 has been widely used by the majority of iTerm2 users, yet it never got out of versions tap AFAIR (even though the stable app by itself has the 'prompt for test-release builds' option checked by default).

Whether this is reversed or not, I thought this should be pointed out for the sake of consistency, if such thing exists at all.

**Comment by vitorgalvao** [comment]
To be clear, I’m not disagreeing with you, here, quite the contrary. Submit a PR and I’ll accept it.

**Comment by designorant** [comment]
@Miladiir Would you mind sharing your thoughts on this?

**Comment by Miladiir** [comment]
As far as I know, the old stable only provides more features than the new beta version. However those features don't work anymore. Kicking devices out of boot loop might be the only that still works.Restoring with unsigned devices does not work yet, however the developer revealed that he and ih8snOw are working on bringing back that functionality (needs citation).Furthermore this one actually grabs SHSH keys from newer devices, the old one just fails. The old one also cannot restore them, as iTunes cannot be spoofed anymore by the Tiny umbrella SHSH key signing server. Not sure, but submitting to Cydia was broken on the old one when I last tried that.
There is not much to compare the two. The new one is simply for getting the keys out of every currently known device and firmware version, whereas the old one worked up to iOS 7 ( I think) and only A4 ( at least definitely not for my iPad mini 2).
Sorry for spelling, replying from mobile. 





On Wed, Jun 3, 2015 at 5:59 PM -0700, "Michał Ordon" <notifications@github.com> wrote:












@Miladiir Would you mind sharing your thoughts on this?
