### ISSUE TITLE
Make installation case insensitive

### ISSUE THREAD

**Issue by jansauer** [caskroom/homebrew-cask#10240]
If you just copy paste a app name to see if you can install it with cask you can't install it by pasting.

Example:

```
$ brew cask search LiteIcon
==> Exact match
liteicon
$ brew cask install LiteIcon
Error: Cask 'LiteIcon' definition is invalid: Bad header line: 'liteicon' does not match file name
```

If cask tells me that it has a exact match for my search term I should be able to install the app with that search term.

**Comment by phinze** [comment]
Hi there!

This wouldn't work in every case, since sometimes Cask names have hyphens and such, but it's easy enough to downcase incoming args that it seems like we might as well. :+1:

**Comment by jansauer** [comment]
Thx for the fast feedback.

What is the problem with hyphens? Can you give me an example?

**Comment by phinze** [comment]
> What is the problem with hyphens? Can you give me an example?

I was just referring to the fact that spaces become hyphens in a cask's name, so this doesn't get us all the way to "copy/paste an app name" for _every_ app.

Example:

```
$ brew cask search "SSH Tunnel Manager"
==> Exact match
ssh-tunnel-manager
$ brew cask install "SSH Tunnel Manager"
Error: No available Cask for SSH Tunnel Manager. Did you mean:
ssh-tunnel-manager
Error: nothing to install
```

We could still try and make that work for users, but it'd be more complicated that a simple arg-downcase.

**Comment by jawshooah** [comment]
Couldn't we just downcase and search modulo hyphens and spaces?

**Comment by phinze** [comment]
I just looked over the code - and we can lean on the search code for this so it's not that bad. Gotta run for now but will finish up linked PR soon. :+1:

**Comment by vitorgalvao** [comment]
Marking as `ready to implement`.

**Comment by Dorian** [comment]
@victorpopkov I guess this should be implemented directly into `brew`. I'm not sure where to do it though:

- On the `ARGV.named` method: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/ARGV.rb#L2-L4
- Near the `tap.install`: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/install.rb#L75-L79
- In the brew cask install file: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/install.rb

Personnaly I think `name.strip.trim.downcase.gsub(/[ _]/, '-')` would be enough for most cases (mine was just going from camelcase to lowercase with `ShiftIt`).

**Comment by jawshooah** [comment]
@Dorian feel free to open a pull request on Homebrew/brew.

**Comment by muescha** [comment]
just lowercase the app name would be sufficient for the most cases


fun fact: the app name is written in camelcase in `brew cask info`
```
$ brew cask search AccessMenuBarApps
==> Exact match
accessmenubarapps

$ brew cask info AccessMenuBarApps
Error: Cask 'AccessMenuBarApps' definition is invalid: Bad header line: 'accessmenubarapps' does not match file name

$ brew cask info accessmenubarapps
accessmenubarapps: 2.4
http://www.ortisoft.de/accessmenubarapps/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/accessmenubarapps.rb
==> Name
AccessMenuBarApps
==> Artifacts
AccessMenuBarApps.app (app)
```

**Comment by vitorgalvao** [comment]
> fun fact: the app name is written in camelcase in `brew cask info`

No. It is written [like in its artifact](https://github.com/caskroom/homebrew-cask/blob/3ddd13fed9e62e2f23320cc7639e8c5d12ffcc10/Casks/accessmenubarapps.rb#L11).

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/30140
