### ISSUE TITLE
Support metalinks

### ISSUE THREAD

**Issue by w-hive** [caskroom/homebrew-cask#10264]
https://en.wikipedia.org/wiki/Metalink

It would be great to support metalink (which is supported f.e. by aria2), because it allows many sources of great variety to be searched for a given file/hash. For example, you could get part of a file from an HTTP source and part from BitTorrent and it would still work.

This would be ideal especially if cask ever supports multiple versions of an application, or for situations when hosts move things around unexpectedly.

**Comment by vitorgalvao** [comment]
Closing. See https://github.com/caskroom/homebrew-cask/issues/10241#issuecomment-87387608 (first paragraph).
