### ISSUE TITLE
"brew cask info" to print release date too.

### ISSUE THREAD

**Issue by hansgru** [caskroom/homebrew-cask#10266]
There are many cask projects (very useful) but I'm really missing the "release date" from the ```info``` command.

I mean the version information is useful, but when exploring new projects it's not saying much for most of them. A release date would be much more helpful.

**Comment by vitorgalvao** [comment]
You mean the release date for the projects themselves?

That is outside the goals of this project, as [we don’t intend to become a discoverability service](https://github.com/caskroom/homebrew-cask/issues/4323#issuecomment-67257513). This has been [discussed and refused multiple times](https://github.com/caskroom/homebrew-cask/issues/5425#issuecomment-49512837), as [it is not part of the goals of homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/3817#issuecomment-39868330). Amongst other things, the logistics are unsustainable.
