### ISSUE TITLE
Add names to Casks that are missing them

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#10370]
There are hundreds of Casks that currently have no `name` stanza. Adding these would greatly improve the utility of `brew cask search`.

Casks that remain unnamed will be tallied and uploaded [here](http://vitorgalvao.com/pending/casks-missing-names.txt) on a daily basis for reference (thanks, @vitorgalvao!)

**Comment by vitorgalvao** [comment]
Wouldn’t it make more sense to add these as bullets points and update those regularly via a script?

These are usually updated in batches (and in my case, out of order), so ticking them one by one would be a pain.

**Comment by vitorgalvao** [comment]
For now, we can use [this](http://vitorgalvao.com/pending/casks-missing-names.txt). Feel free to update your top post with that link if you so wish, in whatever manner you’d like, and I’ll delete this comment (if you tag me, so I remember to come back).

Not the greatest solution, but it works well enough for curious user to have a rough idea how many casks are still missing `name`. The file will be updated daily.

**Comment by jawshooah** [comment]
Awesome! I've updated the original post with the link and tagged you.

**Comment by vitorgalvao** [comment]
Oh, I meant tagging in the sense of “please reply to the issue so I get an email warning”, no need for credit on the top post. Will delete all these extra posts since only your first one matters to the issue. Feel free to edit it at will.

**Comment by anantshri** [comment]
link says 1 missing and lists - 

is this still valid.

**Comment by vitorgalvao** [comment]
@anantshri Yes, it’s just some weirdness with the server; it sometimes misses. It’s working for now.

**Comment by mauricerkelly** [comment]
I’d be happy to help out with this chore, though the server is still showing “1 missing”. Is there a script I could run locally for the same effect?

**Comment by vitorgalvao** [comment]
That’s a mistake. They’re all done; I just forgot to close this.

I was simply doing `ack --files-without-matches "name '"` (with a few extra commands to handle proper updates and the file creation).
