### ISSUE TITLE
update all sourceforce link to https

### ISSUE THREAD

**Issue by FinalDes** [caskroom/homebrew-cask#10383]
here is the command to search all the file need to replace:
grep -r url $Casks/Casks | grep sourceforge | grep http://

**Comment by FinalDes** [comment]
I use this follow bash script to replace the string  
grep -Erl "url.*http://.*sourceforge" $Casks/Casks |xargs sed -il "s,http://downloads.sourceforge,https://downloads.sourceforge/,"

need to test individual casks

**Comment by vitorgalvao** [comment]
This [is already being taken care of](https://github.com/caskroom/homebrew-cask/pull/10379). They should not be changed, though, as per the developing discussion in https://github.com/caskroom/homebrew-cask/issues/10377.
