### ISSUE TITLE
Cask seems to 'forget' installed software?

### ISSUE THREAD

**Issue by SuperHenkie** [caskroom/homebrew-cask#10388]
I installed several apps through brew and brew cask. Occasionally, I noticed that when I do `brew cask info programxyz` it says "Not installed", even though I most certainly did install that particular program through brew cask earlier.

For example, I have installed Firefox a while ago using `brew cask install firefox`.
Now if I do `brew cask info firefox` it says "Not installed". Note that the alias and the .app are still there, and Firefox works fine (I'm typing this in the cask-installed Firefox as we speak, actually).

I frequently do `brew update`, `brew upgrade`, `brew cask update`, `brew cleanup` etc. 

Is this an issue in brew or cask, or in the particular app, or am I mistaken or doing someting wrong?

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/2988.
