### ISSUE TITLE
doc/hacking.md doesn't contain information on how to install Gemfile dependencies

### ISSUE THREAD

**Issue by tghs** [caskroom/homebrew-cask#10425]
doc/hacking.md doesn't contain information on how to install the dependencies in the Gemfile, such as those required to run the tests (the invocation of which is documented). Did I miss documentation for this elsewhere?

Including this information would be _really_ helpful for new contributors who have never worked with Ruby projects before and have no idea how to pull in dependencies.

**Comment by radeksimko** [comment]
Hi,
sorry for being negative here, but I'm :-1: on this.

Any Ruby dev, even beginner IMO needs to know Bundler and if (s)he doesn't, it's literally [1 Google search away](https://www.google.co.uk/search?q=gemfile&oq=gemfile&aqs=chrome..69i57j69i60l2j69i59.669j0j1&sourceid=chrome&es_sm=91&ie=UTF-8).

Can you give an example of any popular Ruby project that is giving some more hints in its own docs?

**Comment by radeksimko** [comment]
In fact, after re-reading the docs, we may fit in something **very brief** as it's not mentioned there at all...

https://github.com/caskroom/homebrew-cask/blob/master/doc/hacking.md#setup

It's sometimes hard to find the balance between duplicating docs from elsewhere (and cluttering our own docs) and being actually useful, which is my concern.

**Comment by tghs** [comment]
I give Jekyll's approach a :+1:: http://jekyllrb.com/docs/contributing/#test-dependencies

I'm not a Ruby developer at all. Searching online for _gemfile_ will indeed point you to bundler. But, I had no idea that the gemfile had anything to do with installing dependencies, so I did not think to search using that term. From years of just cursory looks at Ruby project structures, I had at some point made the assumption that gemfiles were just manifests for this project as a gem.

Say we had an example such as this:

```bash
$ bundle # Install dependencies
$ rake test
```

This clearly gives the command you have to run, and also a search term to find and install it. Searching online for _bundle command_ or _bundle ruby_ take you straight to bundler.

With this project in particular, I think it's important to remember that not everyone contributing is a Ruby developer or is interested in becoming one. Someone who only wants to maintain a Cask should not have to care about Ruby much beyond the Cask DSL itself. :-)

**Comment by radeksimko** [comment]
> Someone who only wants to maintain a Cask should not have to care about Ruby much beyond the Cask DSL itself.

Don't you only need Bundler to install test tools for testing the core? I believe you should not need it when only maintaining casks - am I wrong?

Agreed with all other points though. I like Jekyll's approach, sending a PR to docs will be much appreciated. :wink:

**Comment by jawshooah** [comment]
@radeksimko It's also useful for running `rake rubocop` to check for style errors before submitting a PR.
