### ISSUE TITLE
Generally avoid latest as version

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#10437]
Hello,

Whilst I know that currently, homebrew-cask is not able to automatically manage updates of installed casks (and that people are actively thinking of how to implement it) I wonder if systematically avoid the use of `:latest` as version number in formulae wouldn't be a first "good practice".

In fact, I observed that `brew cask install`\``already-installed-formula`\` is quite useful to get a new version when availaible:
- you get a warning telling you it's already installed (if the version has not been updated)
- or you download and install the new version (if updated)

So this is a way to easily maintain our installed software up-to-date.
But this nice behavior seems impossible if the formula updates keep always `:latest` as version number instead of the real software version number. Moreover, most of the time this version number really exists for the original software and it would be logical to write this original version number in the formula, even if the download link does not contain a version number.

Wouldn't it be a good idea to remove those `:latest` as often as possible?

**Comment by vitorgalvao** [comment]
For some casks, this is downright impossible without having the cask break constantly. Those are the casks that have an unversioned url, such as [`zooom`](https://github.com/caskroom/homebrew-cask/blob/6e4eb6ba58ca0d9e6d42a1d78856cc8a35cf5fce/Casks/zooom.rb#L5)

For all the others, yes, we’re currently shifting to remove `:latest` as often as possible.

This has all been discussed in https://github.com/caskroom/homebrew-cask/issues/1021. See https://github.com/caskroom/homebrew-cask/issues/1021#issuecomment-45493255 for a succinct conclusion.
