### ISSUE TITLE
Keep app symlinks in user-defined subfolders of Applications?

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#10444]
I wonder if a convenient feature could be added.

- Managing software with homebrew-cask is very simple, and soon the automatic update will come and make it even simpler.
- Nevertheless I liked to sort my stuff in subfolders like "Net" or "Multimedia" or "Editors" and so on, which is no longer possible since homebrew-cask stores all the applications symlinks at the root of my personal ~/Applications folder.

When homebrew-cask updates the symlink like that:
```
==> Downloading https://download.documentfoundation.org/libreoffice/stable/4.4.2/mac/x86_64/LibreOffice_4.4.2_MacOS_x86-64.dmg
######################################################################## 100,0%
==> Symlinking App 'LibreOffice.app' to '/Users/me/Applications/LibreOffice.app'
🍺  libreoffice staged at '/opt/homebrew-cask/Caskroom/libreoffice/4.4.2' (10225 files, 646M)
```
wouldn't it be possible to perform a search in ~/Applications and to update the existing symlink at the same place the user has moved it before (for his convenience) instead of creating a new one at the root?

**Comment by vitorgalvao** [comment]
Not really, since not everyone stores symlinks in the same directory, and that can be changed on a per-install basis, which makes this not really viable. It's also not a terribly useful or requested feature.

You also seem to be misunderstanding upgrades. They won’t be automatic, they’ll work like they do in homebrew.

**Comment by Yann-R** [comment]
Yes, you are right:
- by default (not me) homebrew-cask decides to put the symlinks in ~/Applications
- as a user, I could change this each time I install a software with `--appdir` 

But what I suggested was a way to make it "more convenient" (i.e. more user-friendly) for a usual way of using applications on Mac OS:
- when you begin to have more and more applications
- you start preferring to sort them, and to store them to a few thematic subfolders to help you in your everyday life.

This is not the same for homebrew (that is command-line oriented, and therefore tends to place every binary in the same path since the user will invoke them manually from the prompt as in any Unix system).

And, currently, if you want to "sort" your graphical applications from homebrew-cask
1. either you have to re-install each one with `brew cask install --appdir` as you suggested
(the best but long way)
2. either you manually move and sort the symlinks as you want (since it is natural on Mac OS for apps) 
(this is the fast but bad way) 

We say a bad way since obvioulsy, at least currently, in the second case, each time you "update" an application to the new version (as recently `brew cask install libreoffice` installed version 4.4.2 when you already had version 4.4.1) then your former symlink manually moved in "Editor" (for instance) is no longer the right one, and a new one (also named Libreoffice.app) is created at the root of ~/Applications. That's normal as this is what `brew cask` is supposed to do currently.

What I was proposing was a compromise of the two approaches (a bit of freedom for the user, and a bit of automation for brew cask):
- I guess it is natural for a user to get his applications sorted to avoid having all of them at the root.
- I guess it is more user-friendly to let him move the symlinks of applications after installing (whereas he could have thought of it before and have used the `--appdir` option)

=> then I imagined this "smart update" of the symlink created by `brew cask`: when the same source name (e.g. Libreoffice.app) is automatically created, if there is already another one with the same name somewhere at a deeper level from that place of symlink creation, then replace it in its subfolder instead of creating a new one at an upper lever.

But I may understand you don't find it useful.
