### ISSUE TITLE
Dropbox Encore doesn't work if Dropbox is installed with cask

### ISSUE THREAD

**Issue by basnijholt** [caskroom/homebrew-cask#10499]
Dropbox Encore doesn't work if Dropbox is installed with cask, because Dropbox Encore requires Dropbox to be in the default Applications folder.

**Comment by basnijholt** [comment]
https://github.com/caskroom/homebrew-cask/pull/9178 would fix this

**Comment by vitorgalvao** [comment]
Closing as there are some planned ideas that should fix this.
