### ISSUE TITLE
Problem with `ditto`

### ISSUE THREAD

**Issue by webpro** [caskroom/homebrew-cask#10493]
Trying to contribute a new package.

Here's the config:

```
cask :v1 => 'hiarcs-chess-explorer' do
  version '1.8'
  sha256 '53dc3f7db266c1400dc2d5aab3a05eb8c503a50b4cdbc18e57d3d6d9ae0ce129'

  url 'http://www.hiarcs.com/mhce/HIARCS-Chess-Explorer-Installer-v1.8e.pkg'
  pkg 'HIARCS-Chess-Explorer-Installer-v1.8e.pkg'
  name '(Deep) HIARCS Chess Explorer'
  homepage 'http://www.hiarcs.com/mac-chess-explorer.htm'
  license :commercial

  app 'HIARCS Chess Explorer.app'
end
```

When I try to install this, I'm getting this:

```
==> SHA256 checksums match
==> Downloaded to -> /Library/Caches/Homebrew/hiarcs-chess-explorer-1.8.pkg
==> SHA256 checksums match
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Executing: ["/usr/bin/file", "-Izb", "--", "#<Pathname:/Library/Caches/Homebrew/hiarcs-chess-explorer-1.8.pkg>"]
==> Using container class Hbc::Container::Pkg for /Library/Caches/Homebrew/hiarcs-chess-explorer-1.8.pkg
==> Executing: ["/usr/bin/ditto", "--", "#<Pathname:/Library/Caches/Homebrew/hiarcs-chess-explorer-1.8.pkg>", "#<Pathname:/opt/homebrew-cask/Caskroom/hiarcs-chess-explorer/1.8/HIARCS-Chess-Explorer-Installer-v1.8e.pkg>"]
==> Installing artifacts
[...]
==> Purging files for version 1.8 of Cask hiarcs-chess-explorer
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/hiarcs-chess-explorer/1.8/HIARCS Chess Explorer.app'
```

The problem seems to be with ditto, since it seems to do nothing. I could manually run it, but then it just copies the `pkg` file to the destination (instead of extracting the `App`).

```
/usr/bin/ditto -- /Library/Caches/Homebrew/hiarcs-chess-explorer-1.8.pkg /opt/homebrew-cask/Caskroom/hiarcs-chess-explorer/1.8/HIARCS-Chess-Explorer-Installer-v1.8e.pkg
```

It should be possible to install from a `pkg` file, right? Any idea what I'm doing wrong here?

**Comment by radeksimko** [comment]
I believe that `ditto` is doing what it is supposed to do, we generally don't extract `pkg` to a location, it's an installation package with absolute paths, so the `app` should get generated by the installation process ([`installer`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/artifact/pkg.rb)).

There should be no need to specify `app` stanza which is usually used when the app is distributed as `dmg ~> app` or `zip ~> app`.

Have a look at `pkg` stanza: https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#pkg-stanza-details and let me know if that does the job for you.

**Comment by radeksimko** [comment]
Ah, actually you already use the `pkg` stanza, so just remove the `app` and you should be pretty much good to go.

**Comment by radeksimko** [comment]
Maybe just a small note:
```ruby
  version '1.8'

  url 'http://www.hiarcs.com/mhce/HIARCS-Chess-Explorer-Installer-v1.8e.pkg'
  pkg 'HIARCS-Chess-Explorer-Installer-v1.8e.pkg'
```
the version stanza can be reused (when you use double quotes):
```
  version '1.8e'

  url "http://www.hiarcs.com/mhce/HIARCS-Chess-Explorer-Installer-v#{version}.pkg"
  pkg "HIARCS-Chess-Explorer-Installer-v#{version}.pkg"
```

**Comment by webpro** [comment]
Indeed, it's working without the `app` stanza. Thanks!

I didn't use the version variable, because of the "e" in it, but I'll use it anyway.

**Comment by radeksimko** [comment]
> I didn't use the version variable, because of the "e" in it, but I'll use it anyway.

The `version` stanza has no explicit validation/limit, so you should not be worried about `e`.
