### ISSUE TITLE
Icon change does not show in Launchpad on Mac

### ISSUE THREAD

**Issue by bucaran** [caskroom/homebrew-cask#10515]
If you change the icon the app inside `Caskroom/` directory it will update the app on the Dock when it's open, but it continue to use the old icon in Launchpad.

**Comment by radeksimko** [comment]
Hi, could you please give us a more specific example/use case (mentioning specific cask name) where you need/may want to change the icon and how you do it (mentioning specific steps)?

**Comment by bucaran** [comment]
Hi. I remember having the same issue with `MacVim` a few months ago.

1. `brew cask install sublime-text` 
> This install Sublime Text 2

2. Download a cool Sublime icon replacement.
3. Go to `/opt/homebrew-cask/Caskroom/sublime-text/{VERSION}/`
> Now, I could simply copy the icon image to my clipboard and then right-click the Sublime Text app, paste and done or as described in \#4.

4. Show Package Contents of Sublime Text app.
5. Go to `Contents/Resources` and replace the `Sublime Text 2.icns` with my icon pack.

After this and relaunching the Dock I can verify the icon replacement process was completely succesfuly. But if I open [Launchpad](https://support.apple.com/en-us/HT202635) the icon change is not reflected.

Thanks.

**Comment by radeksimko** [comment]
Thanks for detailed description.

1. Is this happening too when you install Sublime Text outside of Cask?
    - if yes, then it may be because of the installation mechanism when we symlink `.app`
2. _"Download a cool Sublime icon replacement."_
    - can we get to the bottom of this? What's the motivation behind it? Is it just because you don't like the original icon or you're trying to fix something that doesn't work well?

**Comment by bucaran** [comment]
1. No. If I don't use Cask to install (like just putting the binary myself under `Applications/`) I can work it out. 

2. I don't know how common is this practice, but I usually download icon replacements for some of my favorite apps. [MacVim](https://www.google.co.jp/search?q=macvim+replacement+icon&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ei=a7UsVfrHFYG_mwW8roCoBw&ved=0CAcQ_AUoAQ&biw=1276&bih=715), [SublimeText](https://www.google.co.jp/search?q=Sublime+text&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ei=e7UsVYbjEMKhmQW8woCIDQ&ved=0CAcQ_AUoAQ&biw=1276&bih=715#rls=en&tbm=isch&q=Sublime+text+icon) [Chrome](https://www.google.co.jp/search?q=chrome+replace+icon&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ei=lLUsVcnvM4TImwXzmoCoAg&ved=0CAcQ_AUoAQ&biw=1276&bih=715#rls=en&tbm=isch&q=chrome+icon), etc.

> if yes, then it may be because of the installation mechanism when we symlink .app

Where does this occur? I would be happy to take a look at this and see if I could come up with a fix.

**Comment by bucaran** [comment]
I just confirmed that changing the icon and symlinking an app to `~/Applications` brings the icon with it, so Cask is probably the culprit here.

**Comment by bucaran** [comment]
Finally, I just confirmed this is a not a Cask problem.

It seems that icon changes do not follow symlinks on OS X. If I create a symlink in `~/my.app` to `~/Applications/my.app` Launchpad will show the icon as it was when the symlink was created. Deleting Launchpad's cache/db at `~/Library/Application\ Support/Dock/*.db` and resetting the Dock `killall Dock` does not help either.

**So, a solution is to unlink Sublime (change the icon) and symlink again.**
