### ISSUE TITLE
tunnelblick is not working

### ISSUE THREAD

**Issue by troydm** [caskroom/homebrew-cask#10519]
after installing tunnelblick with cask It's not starting up as it's assuming a security incident because
it's detecting that application is actually a symlink and not the actual .app folder

**Comment by radeksimko** [comment]
Which version you're trying to install?

Tunnelblick should ask you for moving itself to `/Applications`.
See https://github.com/caskroom/homebrew-cask/issues/9371 and https://github.com/caskroom/homebrew-cask/pull/9178 (which may be at some point definitive solution)

**Comment by troydm** [comment]
@radeksimko I'm trying latest version. I have export HOMEBREW_CASK_OPTS="--appdir=/Applications" however the application is not installing there as it just symlinks itself there so when I try running it it reports potential security incident and refuses to run. How do I make it install there instead of just doing symlink?

**Comment by vitorgalvao** [comment]
> How do I make it install there instead of just doing symlink?

You don’t with homebrew-cask. We don’t support that yet. You must do it manually.

**Comment by troydm** [comment]
@vitorgalvao ic, thx

**Comment by vitorgalvao** [comment]
Closed in favour of https://github.com/caskroom/homebrew-cask/issues/12858.
