### ISSUE TITLE
Failed to install XQuartz

### ISSUE THREAD

**Issue by Jomaf** [caskroom/homebrew-cask#10510]
MAC OS version Yosemite 10..2.2 Errors during the installation : Most likely, this means you have an outdated version of homebrew-cask. But the installed version 0.53.3 is up-to-date.

**Comment by radeksimko** [comment]
Hi!
I'm unable to replicate this issue.
Could you please state the cask version (latest XQuartz is `2.7.7`) you have problem with and more importantly paste the exact error you're getting?

**Comment by Jomaf** [comment]
Thanks a lot, the problem has been solved!
