### ISSUE TITLE
"charles" recipe uses outdated version?

### ISSUE THREAD

**Issue by cowboy** [caskroom/homebrew-cask#10522]
The [charles.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/charles.rb) cask currently uses the `applejava` version, which per the [charles download page](http://www.charlesproxy.com/latest-release/download.do) is the "Alternative for older Mac OS X versions (uses Apple Java 6)" and requires that Java 6 be installed separately via [Java for OS X 2014-001](https://support.apple.com/kb/DL1572?locale=en_US).

Would it be possible to use the main download url instead?
`http://www.charlesproxy.com/assets/release/#{version}/charles-proxy-#{version}.dmg`

I've installed manually from there, and wasn't required to install anything else to get it to run.

**Comment by anantshri** [comment]
I have updated the cask however i think we also need to make some note or a dependecy call to install or check if java is installed otherwise inform user to install java.

https://github.com/caskroom/homebrew-cask/pull/10552

**Comment by radeksimko** [comment]
#10552 merged.
