### ISSUE TITLE
Token Collision

### ISSUE THREAD

**Issue by vinkla** [caskroom/homebrew-cask#10539]
Since Facebook announced the website version of messenger there has been a lot of new Mac integrations. Now we've a problem. This new [Messenger for mac](http://messengerfordesktop.com/) has the same name as an existing cask. I'm curious, how do we deal with this? Should we rename them both or should we just skip this new one?

**Comment by ndr-qef** [comment]
It is a good thing you found and contributed many such apps, thus noticing the collision.

Our current convention is to prefix the new token with the name of the developer, as described in the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md#simplified-names-of-apps):

> If the result conflicts with the name of an existing Cask, make yours unique by prepending the name of the vendor or developer, followed by a hyphen. Example: unison.rb and panic-unison.rb.

**Comment by vinkla** [comment]
Great. Then I know for future PRs. Thanks!
