### ISSUE TITLE
Google Chrome doesn't work with 1Password extension if it's not in the /Applications folder.

### ISSUE THREAD

**Issue by basnijholt** [caskroom/homebrew-cask#10556]
Google Chrome doesn't work with 1Password extension if it's not in the /Applications folder.

**Comment by basnijholt** [comment]
https://github.com/caskroom/homebrew-cask/issues/1351

**Comment by radeksimko** [comment]
Also related: https://github.com/caskroom/homebrew-cask/pull/9178

**Comment by vitorgalvao** [comment]
We’re aware of it, we can’t solve it, and the cask warns you of such a limitation and suggests solutions when you install it.
