### ISSUE TITLE
Failure while executing: git clone

### ISSUE THREAD

**Issue by JimiSpire** [caskroom/homebrew-cask#10571]
Calling that command: brew install brew-cask
Trying to install on osx 10.8 and it gives this error:

Error: Failed to download resource "brew-cask"
Failure while executing: git clone --depth 1 --branch v0.53.3 https://github.com/caskroom/homebrew-cask.git /Library/Caches/Homebrew/brew-cask--git

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/10041.
