### ISSUE TITLE
Suspicious Package Weirdness?

### ISSUE THREAD

**Issue by ybham6** [caskroom/homebrew-cask#10576]
When I installed suspicious-package using "brew cask install suspicious-package" it seemed to install fine, except it threw a weird error near the end. When I installed this happened : 
![image](https://cloud.githubusercontent.com/assets/10470872/7115019/c49f6bde-e1b1-11e4-9459-6b8937dad78a.png)
It seems to have installed fine but the weird "Sorry, try again" might be a bug. This was after updating to the newest version of brew cask and running "brew upgrade brew-cask && brew cleanup && brew cask cleanup"

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/7000
