### ISSUE TITLE
cDock version bump 

### ISSUE THREAD

**Issue by rtgibbons** [caskroom/homebrew-cask#10570]
Latest version is 7.3 with sha256 sum of `88aeadaa446241970bd96685ef9ddb53220b493f321ac0e579d0e7653ef6d984`

**Comment by rtgibbons** [comment]
Eh, looks like it might need a small edit; it installs fine; but then when running i get the following window

![screenshot 2015-04-12 19 59 58](https://cloud.githubusercontent.com/assets/8000/7108516/aaa16ce0-e14e-11e4-8466-4cadd45fd002.png)

**Comment by vitorgalvao** [comment]
These are separate issues. The version bump has been addressed. Could you open a new issue regarding the other one?
