### ISSUE TITLE
Add suppress_move_to_applications to flashlight.rb

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#10590]
[flashlight.rb](../tree/master/Casks/flashlight.rb)
![](http://i.imgur.com/PrGFktv.png)

**Comment by winkelsdorf** [comment]
Can be closed, included in my PR https://github.com/caskroom/homebrew-cask/commit/f63383852460ff06c08944dbcbf10f7efef7415d which was accepted.
