### ISSUE TITLE
update java to 1.8.0_45

### ISSUE THREAD

**Issue by jab** [caskroom/homebrew-cask#10634]
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
http://www.oracle.com/technetwork/java/javase/8u45-relnotes-2494160.html

**Comment by jab** [comment]
Looks like this was fixed by @nremond in 4d31a21d7fab2a0e89cb44a326e138327a98efe7 and can be closed when #10644 is merged.

**Comment by jab** [comment]
thanks @nremond!

**Comment by jab** [comment]
Oh, merged already, closing.

**Comment by nremond** [comment]
@jab you're welcome ;)
