### ISSUE TITLE
Cannot upgrade atom

### ISSUE THREAD

**Issue by nils-werner** [caskroom/homebrew-cask#10660]
Atom downloads from the URL `https://atom.io/download/mac` to the file `/Library/Caches/Homebrew/atom-latest`, my guess is cask can't deduce the version number from the URL or the cache and thinkg the cache is up to date, while it isn't.

As a result I can never upgrade Atom using `brew cask install --upgrade atom`.

**Comment by vitorgalvao** [comment]
You can’t upgrade any cask. The feature isn’t implemented, yet.

Atom should self-update, though.

**Comment by nils-werner** [comment]
Weird, because [USAGE.md says you sort of can](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks). And even when I do this, the cache is not invalidated.

**Comment by vitorgalvao** [comment]
Not really, because you’re forcing another install, not upgrading. Do `brew cask cleanup` first, and it’ll work.
