### ISSUE TITLE
Something went wrong with Vagrant.app

### ISSUE THREAD

**Issue by denpatin** [caskroom/homebrew-cask#10675]
The vagrant cask has been successfully installed but at the very last stage it has written the following weird line:
![screen shot 2015-04-16 at 8 57 56 pm](https://cloud.githubusercontent.com/assets/1271040/7187720/58a44612-e47b-11e4-97c0-b075dec52f80.png)

Is that normal?

**Comment by phinze** [comment]
@denpatin I think that's just an output oddity from when your password was mistyped above.

If `installer` reports successful, you should be good to go.

**Comment by denpatin** [comment]
@phinze Yeah, everything works well. But I got a bit confused with this last line. So ok, maybe it is because the first unsuccessful password try. Thanks for comment on this! But still I think (of course it isn't that important) the last line shouldn't appear in such cases.

**Comment by phinze** [comment]
Yeah we may just need to handle stderr piping somewhere. Will leave open to investigate.

**Comment by vitorgalvao** [comment]
[Already being tracked](https://github.com/caskroom/homebrew-cask/issues/7000).
