### ISSUE TITLE
Should there be an explicit 32-bit REAPER cask?

### ISSUE THREAD

**Issue by cowboy** [caskroom/homebrew-cask#10680]
Per the [official download instructions](http://www.reaper.fm/download.php):

> 32 bit? 64 bit?

> Most users will likely want to download a 32-bit version of REAPER. All versions of REAPER have a full-resolution 64-bit internal audio signal path from end to end, on all operating systems.

> Your decision of which installer to download depends primarily on the plug-ins you wish to use with REAPER and your operating system, and not on any audio quality considerations.

Unlike most other apps, the choice of the 64- vs 32-bit version of REAPER isn't based solely on the system architecture; there are other factors. There are legitimate reasons for wanting to download the 32-bit version even if your system has a 64-bit architecture. For example, I use a number of 32-bit-only VST plugins, and have no 64-bit-only plugins. With the current REAPER cask, I need to run my plugins in bridged mode, which is unfortunate.

Would it be possible to either:

1. Modify the existing `reaper` cask to install only the (generally recommended) 32-bit version
1. Modify the existing `reaper` cask to allow some kind of command-line selection of the 32-bit version or to utilize an officially-implement "variant" system
1. Create a `reaper32` (or similarly-named cask) that explicitly installs the 32-bit version (a corresponding `reaper64` version might be good and the current `reaper` could be deprecated)

There was some discussion going on in #5311 (I didn't find it in `caskroom/versions`) but I wanted to elevate it to its own issue, because the current cask limits how REAPER can be used.

/ccing other people who have contributed to this cask or related issues in case they have an opinion: @stonerl @GooseYArd @Dremora @cfillion

**Comment by cfillion** [comment]
Most of my REAPER projects need more than 4GB of RAM (which is more than what a single 32-bit process can use) because of heavy virtual instrument plugins like Kontakt. Having only the 32-bit version of REAPER installed would require each instance of these plugins to be launched in their own dedicated process, which would be annoying just like a 32-to-64bit bridge.

For my use case, the only acceptable options are 2 and 3.

**Comment by vitorgalvao** [comment]
To keep consistency with other cases, the cask in the main repo should be the 64-bit one, and keep being called `reaper`, and a `reaper32` should be created in [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by radeksimko** [comment]
@cowboy I agree w/ @vitorgalvao , keep 64bit in this repo and add 32-bit version into `caskroom/versions`.

**Comment by cowboy** [comment]
Is there a way to programmatically generate the cask for `caskroom/versions`, to keep it in sync with this cask?

**Comment by vitorgalvao** [comment]
Well, yes, you could in theory cook something up. From our side, no. I made [a script to quickly and easily update casks](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair) (including making different branches for the update and pushing them for submission) which may help if you decide to build something custom.
