### ISSUE TITLE
Cask For Textual?

### ISSUE THREAD

**Issue by RandomDSdevel** [caskroom/homebrew-cask#10697]
Can a cask for the [Textual IRC client](https://github.com/Codeux-Software/Textual) be created?  I'd like to install it, but the build/install process sounds a little daunting from what I've seen so far.

**Comment by phinze** [comment]
Hi there!

Unfortunately we can't do this for a couple of reasons.

(1) We're not a project that builds stuff from source, we just make it easy to install existing binaries  
(2) It would be against the wishes of the author, as stated in the README:

> Please do not abuse the power to build Textual in order to freely distribute it to hundreds of users. The copy of Textual in the Mac App Store helps fund the project. Therefore, what is asked, is asked out of respect so that the project can continue to thrive.

**Comment by RandomDSdevel** [comment]
Well, I guess that makes it so that this couldn't even go upstream, where stuff _can_ be built from source!  That…kind of stinks.  Guess I'll have to wade through the build/install process myself, won't I?  Sigh…

**Comment by vitorgalvao** [comment]
@RandomDSdevel It’s extremely easy, though. Just clone the repo, `cd` into it’s directory, and `xcodebuild CODE_SIGN_IDENTITY=""`. You’ll find yourself with a built app bundle inside `Build Results/Release/Textual 5.app`.

**Comment by RandomDSdevel** [comment]
Thanks!  Guess I don't need this any more though, cause I switched to using Irssi instead after deciding that managing a self-built application like this without automation of some sort might drive me crazy.
