### ISSUE TITLE
Jetbrains' packages installed via HTTPS fail with cert error

### ISSUE THREAD

**Issue by sundeer** [caskroom/homebrew-cask#10707]
pycharm.rb, pycharm-ce.rb, and clion.rb pull from https://download.jetbrains.com and fail on Mavericks with:

     $ curl -O https://download.jetbrains.com/python/pycharm-professional-4.0.6.dmg
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    curl: (60) SSL certificate problem: Invalid certificate chain
    More details here: http://curl.haxx.se/docs/sslcerts.html
    ...

... this works:

    curl -O http://download-cf.jetbrains.com/python/pycharm-professional-4.0.6.dmg

**Comment by radeksimko** [comment]
This doesn't happen in my environment - OSX `10.10.3`.

```
$ curl --version
```
```
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz
```

```
$ curl -I -L https://download.jetbrains.com/python/pycharm-professional-4.0.6.dmg
```
```
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Sun, 26 Apr 2015 14:17:26 GMT
Content-Type: text/html
Content-Length: 154
Connection: keep-alive
Location: https://d1opms6zj7jotq.cloudfront.net/python/pycharm-professional-4.0.6.dmg

HTTP/1.1 200 OK
Content-Type: binary/octet-stream
Content-Length: 158245803
Connection: keep-alive
Date: Sat, 25 Apr 2015 11:44:16 GMT
Content-Encoding: ANSI_X3.4-1968
x-amz-meta-s3cmd-attrs: uid:572/gname:cds/uname:cds/gid:574/mode:33188/mtime:1428022296/atime:1428022769/md5:4507e163ad3e3e4dc05bbd322d30b984/ctime:1428022296
Last-Modified: Fri, 03 Apr 2015 01:04:47 GMT
ETag: "8233cf31a6b6e55c48dcebfacbbcb983-11"
Accept-Ranges: bytes
Server: AmazonS3
Age: 6386
X-Cache: Hit from cloudfront
Via: 1.1 fb928518aa1bc79700a4469d37971903.cloudfront.net (CloudFront)
X-Amz-Cf-Id: NJhuZiDLtExJZXqFO_glYGxFNvfEm9ALRiAiwBO7Y5caexdwxIPypg==
```

@sundeer Could you please provide OSX version + curl version?

**Comment by sundeer** [comment]
Running 10.9 and 

    $ curl --version                                                                                                               
    curl 7.30.0 (x86_64-apple-darwin13.0) libcurl/7.30.0 SecureTransport zlib/1.2.5
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
    Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz

I initially encountered the issue while trying to get pycharm via hb-cask. I poked at a few other domains and all worked, so I thought there might be a problem with the download.jetbrains.com cert. I just now tried a few other domains and found that I get the same cert error with nyt.com as well. Looks like I've got some weird TLS problem unique to my system. Sorry for jumping the gun, should have dug deeper.
