### ISSUE TITLE
keepassx is actually keepassx2

### ISSUE THREAD

**Issue by justin8** [caskroom/homebrew-cask#10815]
With the change to keepassx2 (which is still in alpha) it no longer supports the old file formats at all and requires you to convert it to the new version. Most linux distros have them packaged as keepassx and keepassx2 for this reason. Even if keepassx v1.x is not going to be supported it would be nice to make this distinction.

**Comment by vitorgalvao** [comment]
`2` is a version number, [hence not included](https://github.com/caskroom/homebrew-versions/blob/master/Casks/keepassx0.rb). Version 0 is [included in another repo](https://github.com/caskroom/homebrew-versions/blob/master/Casks/keepassx0.rb); you may do the same for version 1, if you so wish.

**Comment by justin8** [comment]
I would point out python 2 is python in brew, yet python 3 is python 3 even though it is a newer version, mostly due to the backwards incompatible nature. Why is keepassX a different case?

**Comment by vitorgalvao** [comment]
We are a different project from homebrew, and follow different rules. We decided it makes sense for keepassx to be named like this, and there haven’t been major objections in all this time, so users seems to not be bothered at all by it. In addition, python is a poor example, as most tools that require such differentiation use that naming scheme, not just homebrew — it is expected.

“Alpha” is just a name, and as far as I'm aware, [that is actually the best version to use currently, as all the others were discontinued](https://github.com/caskroom/homebrew-cask/pull/3681). Exceptions to having only the stable version in this repo [are clearly documented](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#but-there-is-no-stable-version).
