### ISSUE TITLE
List available casks in the http://caskroom.io/

### ISSUE THREAD

**Issue by drtaglia** [caskroom/homebrew-cask#10858]
Something that is missing though is **which applications are available in cask**. Having a page with a dynamically assembled list, or specifying a command to see available software on http://caskroom.io would be very useful.

By the way, in all honestly, it wasn't immediately clear to me what cask was when I first read your homepage.

**Comment by vitorgalvao** [comment]
[There is a search](http://caskroom.io/search). `brew cask search` should also give a complete list.

Submit an issue (or even better, a PR), [to the appropriate repo](https://github.com/caskroom/caskroom.github.io) to clarify the message.

**Comment by drtaglia** [comment]
I am saying that as a new user it's very unclear what is available in cask.
You can take that feedback and discard it, or you can look at caskroom.io and notice that a search doesn't give you the full list... and you don't even mention to look under search to see what is available...

**Comment by vitorgalvao** [comment]
> You can take that feedback and discard it

No one is discarding it. I'm saying your feedback is in the wrong place. Please submit it [to the appropriate repo](https://github.com/caskroom/caskroom.github.io), where it should be discussed, and the appropriate people will see it.

In addition, by submitting an issue or a PR, we can properly discuss what changes need to be made to make it clear. Simply saying “I couldn't understand the website” doesn’t help at all, we need you to clarify at length (or, once more, submit a PR) that will address the issue of it not being understandable. *Why* isn’t it understandable? What exactly could’ve been done to make it better? Those are the kinds of insights we need from you.

To do it, lets do it right; open an issue in the appropriate place.

**Comment by vitorgalvao** [comment]
> You can take that feedback and discard it

No one is discarding it. I'm saying your feedback is in the wrong place. Please submit it [to the appropriate repo](https://github.com/caskroom/caskroom.github.io), where it should be discussed, and the appropriate people will see it.

In addition, by submitting an issue or a PR, we can properly discuss what changes need to be made to make it clear. Simply saying “I couldn't understand the website” doesn’t help at all; we need you to clarify at length (or, once more, submit a PR) what will address the issue of it not being understandable. *Why* isn’t it understandable? What exactly could’ve been done to make it better? Those are the kinds of insights we need from you.

To do it, lets do it right; open an issue in the appropriate place.

In addition [we're not a discoverability service](https://github.com/caskroom/homebrew-cask/issues/4323#issuecomment-67257513). This has been [discussed multiple times](https://github.com/caskroom/homebrew-cask/issues/5425#issuecomment-49512837), as [it is not part of the goals of homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/3817#issuecomment-39868330). Amongst other things, the logistics are unsustainable. This is to say you’re not supposed to see all casks available — the goal is to have them all; you’re supposed to install what you want, not shop around.
