### ISSUE TITLE
Is there a way to suppress the asking for a password during the initial install?

### ISSUE THREAD

**Issue by dwkns** [caskroom/homebrew-cask#10852]
I'm installing Homebrew and Cask among other things in bash script to set up a machine. 

My script has `sudo -v` at the top, my plan being that you only had to enter your password once. 

Cask however asks for you password which interrupts the script half way through. Is there any way to suppress this?

**Comment by phinze** [comment]
Interesting - I wonder why the `sudo -v` isn't catching. At which step do you get the sudo password request?

Perhaps here? https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc.rb#L59-L79

**Comment by dwkns** [comment]
Yeah, I'm pretty sure that's where it is. The last few lines from my console are :

    ==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
    ==> We'll set permissions properly so we won't need sudo in the future
    Password:

Here is my script :

    #!/bin/bash

    ############ Set up ############
    sudo -v # ask for sudo upfront

    ############ Make Sure Homebrew & Cask are gone ############
    sudo rm -rf "/usr/local"
    sudo rm -rf "/Library/Caches/Homebrew"
    sudo rm -rf  "/opt/homebrew-cask"

    ############ Install Homebrew ############
    # supress the need to press 'return' when in the install script runs.
    yes '' | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    ############ Install some packages ############
    brew install "wget"
    brew install "git"

    ############ Install cask ############
    brew install caskroom/cask/brew-cask

    ############ Tap up some caskrooms  ############
    brew tap caskroom/versions
    brew tap caskroom/fonts

    ############ Install some cask apps ############
    brew cask install  --appdir='/Applications' 'dropbox'
    brew cask install  --appdir='/Applications' 'sublime-text3'
    brew cask install  --appdir='/Applications' 'things'
    brew cask install  --appdir='/Applications' 'font-source-code-pro'

    echo "And done..."

**Comment by radeksimko** [comment]
@dwkns Do you get the password prompt immediately or after x minutes - i.e. at some point in the middle of the whole installation process?

I guess it can be the sudo timeout (default 5 mins). `sudo -v` only extends the timeout.
http://apple.stackexchange.com/questions/10139/how-do-i-increase-sudo-password-remember-timeout

**Comment by dwkns** [comment]
No I don't believe it's that. I've tried this ... 

    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

Which is supposed to extend sudo until the script ends. With or without it I get the same.

Also I've timestamped the above script with `echo date +"%T"`. From start (20:32:41) to when it asks for the password (20:33:37) to the end of the script (20:34:21) is only two minutes.

**Comment by phinze** [comment]
I guess we'll have to dig into how the "sudo session" mechanism works - seems like it must be breaking down for subshells or something like that.

**Comment by dwkns** [comment]
I've seen something similar before when a shell script running under `sudo -v` calls another script using `source <script name>`. If in that second script there is a command that doesn't require sudo to be specified but it has been `sudo rm -rf ~/Desktop/<some folder>` for instance, you will be asked for the password. 

I'll try and put something together to show this behaviour in action. It may help you track the problem down.

**Comment by aaronbwcollins** [comment]
I also would love to see a solution to this problem, as we have much longer bash script and its a pain to have have both brew and cask installations ask for a password during the install.

**Comment by vitorgalvao** [comment]
Closing for lack of implementation. There are plans to change how installs are done in the future and this won’t be an issue.

**Comment by andyincali** [comment]
Was this issue ever addressed? I am trying to write a fully-automated script that installs homebrew and then `brew-cask`, but the script pauses here and prompts for password:

`We'll set permissions properly so we won't need sudo in the future`

This is still an issue as far as I'm concerned. Not sure why it was closed...

**Comment by vitorgalvao** [comment]
@andyincali Give it the `--caskroom` flag and point to a location where you have permissions to write and do not need `sudo`.

**Comment by jawshooah** [comment]
And if you do use `--caskroom=/path/to/Caskroom`, you should add that to your `HOMEBREW_CASK_OPTS` environment variable.

**Comment by andyincali** [comment]
This doesn't seem to work for me @vitorgalvao @jawshooah. Here's what I see:

`+ su - admin -c '/usr/local/bin/brew install --caskroom=/tmp/ caskroom/cask/brew-cask'

==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3488, done.
remote: Compressing objects: 100% (3470/3470), done.
remote: Total 3488 (delta 32), reused 75 (delta 13), pack-reused 0
Receiving objects: 100% (3488/3488), 1.12 MiB | 0 bytes/s, done.
Resolving deltas: 100% (32/32), done.
Checking connectivity... done.
Tapped 0 formulae (3,496 files, 3.5M)
==> brew cask install caskroom/cask/brew-cask
+ su - admin -c '/usr/local/bin/brew cask install --caskroom=/tmp/ docker-toolbox'
==> Downloading https://github.com/docker/toolbox/releases/download/v1.12.1/DockerToolbox-1.12.1.pkg
######################################################################## 100.0%
==> Verifying checksum for Cask docker-toolbox
==> Running installer for docker-toolbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:`

Am I doing something wrong, or do `brew cask` installations ignore the `--caskroom` flag?

**Comment by vitorgalvao** [comment]
You don’t install `brew-cask` anymore, you just run any `brew cask` command and it is installed automatically for you, so that command can (and should) be gone.

As for the second part, it says right there:

```
==> Running installer for docker-toolbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
```

That’s not the initial install, you’re installing a `pkg` casks. Those need `sudo`, and there’s nothing we can do about it.

**Comment by andyincali** [comment]
Got it! Since my script was running as root, I was able to simply run:

`/usr/local/bin/brew cask install docker-toolbox`

Which installed without prompting for password. Thanks very much for your help!
