### ISSUE TITLE
(homebrew cask) 1Password does not work for (homebrew cask) Firefox (but for homebrew cask Chrome) 

### ISSUE THREAD

**Issue by Januzz** [caskroom/homebrew-cask#10864]
related to: https://github.com/caskroom/homebrew-cask/issues/5674

But:
- my apps get linked to /Applications
- the problem only occurs for Firefox, not for (also with homebrew cask installed) Google Chrome

Although the 1Password Firefox extension is installed, when I activate the 1P window, it always offers me to install it... With Firefox installed without homebrew cask, I did not have this problem.

Any thoughts?

**Comment by vitorgalvao** [comment]
It shouldn’t be working with Chrome — it’s an anomaly that it is. 1Password shouldn’t work with symlinked browsers to `/Applications`, and there is nothing we can do to fix that.

**Comment by phinze** [comment]
FWIW I happily use cask-installed 1password w/ chrome and firefox. it's the Mac App Store installed 1password that has trouble.

I believe you might be able to work around this by unchecking this option:

![preferences](https://cloud.githubusercontent.com/assets/37534/7339864/c2e5d7c4-ec42-11e4-91fc-04cc44ee2634.png)

**Comment by vitorgalvao** [comment]
Ah, yes should’ve specified that. It’s on [Chrome’s caveat](https://github.com/caskroom/homebrew-cask/blob/8184b3a2359f51e4b9010f08ede617fd96a301a4/Casks/google-chrome.rb#L29-32).
