### ISSUE TITLE
Cask request: Protonet

### ISSUE THREAD

**Issue by andreis** [caskroom/homebrew-cask#10934]
My company has a Protonet server, and it would automate setting up new computers by a small margin if I were able to do `brew cask install protonet`.

App available here: http://clients.protonet.info/

Sorry, I know it's simple to add a formula, I'm just too busy right now. If this doesn't get picked up by someone in 1 week (and I remember) I'll do it myself.

**Comment by andreis** [comment]
Thank you @vitorgalvao 
:+1:

**Comment by vitorgalvao** [comment]
You should thank @CraftThatBlock instead, who worked on it most. I just helped with a few corrections and merged it.

**Comment by CraftThatBlock** [comment]
Thanks @vitorgalvao :)
