### ISSUE TITLE
BBedit cask does not work

### ISSUE THREAD

**Issue by stevehoffman** [caskroom/homebrew-cask#10966]
Here's the output:

==> Downloading http://pine.barebones.com/files/BBEdit_11.0.2.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'bbedit' with message: Download failed: http://pine.barebones.com/files/BBEdit_11.0.2.dmg

**Comment by vitorgalvao** [comment]
Fixed.

**Comment by stevehoffman** [comment]
Awesome!

- SH
