### ISSUE TITLE
Make `name` mandatory in audit and tests

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#10997]
All casks in the main repo now have `name`s, so this should be done.

**Comment by radeksimko** [comment]
:+1: agreed, some docs explaining why it's mandatory, i.e. where do we use this (mostly in search I assume) should be part of that PR.

**Comment by adityadalal924** [comment]
Is this already implemented? Not sure if it was and the issue never got closed, because I haven't seen a Cask without a `name` in forever.

**Comment by vitorgalvao** [comment]
Nope, not yet implemented.

**Comment by adityadalal924** [comment]
Was looking at this.

Just needs an update of `_check_required_stanzas` in https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/audit.rb

This brings up a question though - what should be covered in this audit vs. @jawshooah's new https://github.com/jawshooah/rubocop-cask ?

(Specifically thinking about string interpolation in url etc)

**Comment by Amorymeltzer** [comment]
I figure `audit` should handle anything that would break operation, as it's shipped with brew-cask.  Style guidelines and preferences (i.e. unnecessary interpolation) can be left for a more discerning eye.

**Comment by jawshooah** [comment]
Basically what @Amorymeltzer said. We don't have access to the AST (or even the raw source, at the moment) in `audit`, so we can only check the components of the already-loaded cask.

With the RuboCop plugin, we can inspect the source as it is parsed in and detect errors in style and structure.
