### ISSUE TITLE
Spyder --> Error: It seems the symlink source is not there

### ISSUE THREAD

**Issue by cclauss** [caskroom/homebrew-cask#11004]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/spyder.rb is giving me troubles...

$ `brew cask install spyder` # generates...

```
==> Downloading https://bitbucket.org/spyder-ide/spyderlib/downloads/spyder-2.3.4-py2.7.dmg
######################################################################## 100.0%
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/spyder/2.3.4/Spyder.app'
```
I did the usual `brew cask cleanup` and `brew cask doctor` but still no success.  It is just me?

@ccordoba12 mentioned in https://github.com/caskroom/homebrew-cask/pull/8130 that Spyder is released in both Python2 and Python3 versions but Cask only seems to have a formula for the Python2 version.

**Comment by ndr-qef** [comment]
The most recent release appears to be 2.7-only. I am not sure whether future versions will remain so; we could use feedback from the Spyder maintainers to decide on a course of action.

**Comment by ccordoba12** [comment]
I'm sorry for not releasing more dmg's for Python 3. They are only working correctly on 10.7, which is where I generate them.

On other Mac versions, it's not possible to start Python nor IPython consoles, which is a major drawback for our users.

We think that's caused by a bug in py2app, but we're still investigating about it :-)

**Comment by cclauss** [comment]
@ndr-qef The fix above did not solve the problem when I made that change to `/usr/local/Cellar/brew-cask/0.53.3/Casks/spyder.rb` and tried the install again.

@ccordoba12 An alternative to py2app is [`PyInstaller`](https://github.com/pyinstaller/pyinstaller) which makes .exe on Windows and .app on Macs.

**Comment by ndr-qef** [comment]
@ccordoba12, thanks for your reply. It is certainly sensible to only provide releases which work on recent OS X versions.

We will keep our package on Python 2 for the near future; later on, we can reconsider the problem according to your recommendations.

@cclauss, the cask works on my machine. Could you run `brew update` and attempt the conventional `brew cask install spyder`?

**Comment by cclauss** [comment]
That works!  Thanks much!

**Comment by ccordoba12** [comment]
Hey guys, I released a new dmg for Python 3 which, according to two different sources, is working correctly now.

But I'd like to ask you to demand for this one a Mac version higher than or at least equal to **10.9**. It **won't** work on older versions, so I don't want to deal with bug reports for them :-)

However, our Python 2.7 dmg works with **10.7** and higher :-)

Thanks.
