### ISSUE TITLE
CDock forces move to /Applications before it will run

### ISSUE THREAD

**Issue by rtgibbons** [caskroom/homebrew-cask#11030]
![aaa16ce0-e14e-11e4-8466-4cadd45fd002](https://cloud.githubusercontent.com/assets/8000/7475041/e8ec73d2-f30a-11e4-8fa5-1fda857ca718.png)

**Comment by vitorgalvao** [comment]
Just to be clear, is it impossible to run this without it being in `/Applications`?

**Comment by rtgibbons** [comment]
I didn't try too hard, but running pops up that error message. Which hitting `Continue` moves it to /Applications, or you can `Quit`

**Comment by vitorgalvao** [comment]
Alright, not much we can do about this other than warn the user. Will be done in #11032. Thank you.
