### ISSUE TITLE
"brew upgrade brew-cask" returns "Error: brew-cask 0.53.3 already installed"

### ISSUE THREAD

**Issue by koick** [caskroom/homebrew-cask#11047]
```
$brew upgrade brew-cask
Error: brew-cask 0.53.3 already installed
```

Why does this throw an error rather than a warning or silently drop? When I'm chaining a series of commands this error doesn't allow the next command to execute. For example, the last command here ("brew cask cleanup") doesn't get run.
```
brew -v update && brew -v upgrade --all && brew cleanup && brew -v upgrade brew-cask && brew cask cleanup
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/8475
