### ISSUE TITLE
Env Vars intellij-idea cask

### ISSUE THREAD

**Issue by j-walker23** [caskroom/homebrew-cask#11044]
First, thanks for the software, i am new to it and love it.

This is mostly a question that i can not find the answer to so i figure i would go to src.

When running maven in intellij, i can not get it to use my M2_HOME from brew. It always points to built in maven bundled in the cask.

Yosemite
i use zsh
I have set the env var in .zshrc, .profile, .bash_profile, .MacOSX/environment.plist and /etc/launchd.conf.

Is there another place i should so all my intellij projects will use the correct one by default?

Thanks

**Comment by ndr-qef** [comment]
I am not very familiar with IDEA, but I would venture that the locations it checks for environmental vars are not affected by the installation method. When installed manually, does IDEA use the correct M2_HOME?

**Comment by vitorgalvao** [comment]
Closing on account of no reply.

**Comment by j-walker23** [comment]
Damn, not sure how i missed this. I was never able to figure it out. Had to set settings in my intellij projects
