### ISSUE TITLE
Permission denied @ dir_s_mkdir - /opt/homebrew-cask

### ISSUE THREAD

**Issue by johnish** [caskroom/homebrew-cask#11067]
==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-macosx-x64.dmg
######################################################################## 100.0%
Error: Permission denied @ dir_s_mkdir - /opt/homebrew-cask

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

When the above was ran it shows this:
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: brew-cask 0.53.3 already installed

**Comment by vitorgalvao** [comment]
What’s the output of `ls -l /opt`?

**Comment by johnish** [comment]
Sorry I ended up getting past this by using the directions at https://lastzero.net/2013/08/howto-install-php-5-5-and-phpunit-on-os-x-via-homebrew/


However - not to be rude it is 
total 0
drwxr-xr-x 8 root     wheel 272 Sep 28  2012 X11
drwxrwxr-x 5 root     wheel 170 Oct  7  2014 cisco
drwxr-xr-x 3 jwetsel1 staff 102 May  7 21:05 homebrew-cask
[05:42:13][jwetsel1@Thor ~]$

homebrew-cask - I installed this today but had to create the directory myself due to the above error.

**Comment by vitorgalvao** [comment]
> However - not to be rude

Not at all. Good to know you got it fixed — less time we waste tracking the issue down. Closing as solved, then.
