### ISSUE TITLE
Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by howenkakao** [caskroom/homebrew-cask#11076]
It report a bug with following,please help me solve it, thank you.

$ brew install caskroom/cask/brew-cask
==> Installing brew-cask from caskroom/homebrew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Updating /Library/Caches/Homebrew/brew-cask--git
==> Checking out tag v0.53.3
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:481:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by DomT4** [comment]
There's now a `brew doctor` check for this. Essentially: Use `Repair Disk Permissions` in the Disk Utility application.

**Comment by vitorgalvao** [comment]
Thank you, @DomT4. Did that solve it, @howenkakao?
