### ISSUE TITLE
Clean up .pkg files

### ISSUE THREAD

**Issue by kermit666** [caskroom/homebrew-cask#11099]
Was hoping to clean up some space by doing

    brew cask cleanup

but I see that some of the apps installed through homebrew-cask (MacTeX, JDK, Vagrant) still have their .pkg files in the Caskroom. Now, if these are installer files, I was hoping they would be cleaned as well. Can this be done by the cleanup subcommand or are these files needed for running the apps?

**Comment by vitorgalvao** [comment]
All the files downloaded from the packaged are saved in the Caskroom, many times because they might be needed later. To remove them, you have to do so manually.

**Comment by kermit666** [comment]
OK, thanks for the explanation.

**Comment by fgimian** [comment]
I just came across this too and am a little confused by the behaviour.  Can you perhaps elaborate on why the installers could be required later on?

File lists for pkgutil uninstalls are available in `/var/db/receipts`.

These installers do take a good amount of space 😄 

Thanks so much! 😄 
Fotis

**Comment by mxl** [comment]
I agree with @fgimian. Installers are typically removed by users after doing manual installation (without homebrew). I do not think that in case of automatic installation we should keep them. Could we reopen this? Or at least could we get a full explanation of "many times because they might be needed later"?

**Comment by vitorgalvao** [comment]
> Installers are typically removed by users after doing manual installation (without homebrew).

Normal users open apps directly from the dmgs and unpack apps to Desktop and call them from there. I doubt most know to delete the installers *but that is not the point*.

> Or at least could we get a full explanation of "many times because they might be needed later"?

Casks with `uninstall script`, for example, like [`virtualbox`](https://github.com/caskroom/homebrew-cask/blob/72f2e94b197e2ea2b4605c31f187ec08d1d12442/Casks/virtualbox.rb#L19L20). That script comes with the download, it’s not installed after.

So we can’t simply get rid of everything that comes with the download after the install. And we’re also not going to have yet another stanza to reference what can be deleted or not; we have enough work as it is.

No one is saying this will never be done, but at the moment is so low priority as not being on the radar of priorities at all.

**Comment by reitermarkus** [comment]
> Getting rid of only the pkg might be acceptable.

They will be needed for `upgrade`. I.e when. the upgrade fails, and the old `pkg` is reinstalled.

**Comment by vitorgalvao** [comment]
> They will be needed for `upgrade`. I.e when. the upgrade fails, and the old `pkg` is reinstalled.

Ah right, I had a feeling I was forgetting something.
