### ISSUE TITLE
flash-player-debugger doesn't install

### ISSUE THREAD

**Issue by ydesgagn** [caskroom/homebrew-cask#11127]
Hi,

flash-player-debugger doesn't install on Yosemite.

brew cask install flash-player-debugger
==> Downloading https://fpdownload.macromedia.com/pub/flashplayer/updaters/17/fl
######################################################################## 100.0%
==> Symlinking App 'Flash Player.app' to '/Users/yves/Applications/Flash Player 
Error: Command failed to execute!

==> Failed command:
["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\\\"Flash Player Debugger.app\\\")", "#<Pathname:/Users/yves/Applications/Flash Player Debugger.app>"]

==> Output of failed command:

==> Exit status of failed command:
#<Process::Status: pid 7355 exit 1>

Thanks

**Comment by vitorgalvao** [comment]
You already opened an issue for this.
