### ISSUE TITLE
Unexpected method 'discontinued' when installing Panic Unison

### ISSUE THREAD

**Issue by lauritzsh** [caskroom/homebrew-cask#11132]
Hi, I'm getting the following error message trying to install the panic-unison cask.

```
Warning: Unexpected method 'discontinued' called during caveats on Cask panic-unison.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues
```

I'm already on the latest version of `brew-cask`:
`Error: brew-cask 0.53.3 already installed` so it's not an outdated version of `homebrew-cask` I have. Seems to be only related for that cask.

Edit: I see now that Unison has been discontinued and that explains the `discontinued` method. I'm not clear whether the warning message is intended or not but it's not very clear. Is the unexpected part intended behaviour or a bug?

**Comment by radeksimko** [comment]
Thanks for reporting this.

@caskroom/owners We may need to release the caveat additions @vitorgalvao recently put into the DSL ...

**Comment by vitorgalvao** [comment]
Ah, crap, just the other day while falling asleep I suddenly remembered “wait, don’t we need a new release for the changes to go into effect?”, then fell asleep and forgot about it. Apologies on that. @phinze Would you care to cut the new release?

**Comment by radeksimko** [comment]
@vitorgalvao I realised we both seem to have push access (`git tag` + `git push origin master --tags`) + access to releases, so I reckon you can do it to. It's just about synchronizing.

This may be useful:
https://github.com/caskroom/homebrew-cask/blob/master/developer/bin/bump_version
https://github.com/caskroom/homebrew-cask/blob/master/developer/bin/generate_changelog
https://github.com/caskroom/homebrew-cask/blob/master/developer/bin/get_release_tag

not sure if there's any particular part of docs which describes the whole workflow, but I reckon it's just about creating the tag w/ annotation + pushing that tag and then creating a release.

**Comment by phinze** [comment]
Happy to do it this morning - I'll be online in 10m or so.

For future reference, I believe there should be a RELEASING.md doc somewhere in here. :)

**Comment by phinze** [comment]
Alrighty! v0.54.0 is hot off the presses - @lauritzsh can you upgrade and verify that it solves your issue?

**Comment by lauritzsh** [comment]
Wow, that was fast! It's working great and the (warning) message is clear.

```
$ brew cask install panic-unison
==> Caveats
panic-unison has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of OS X.
```

Thanks, appreciate the fast bug fix.
