### ISSUE TITLE
Could "brew cask cleanup" remove older versions? #9586

### ISSUE THREAD

**Issue by johntdyer** [caskroom/homebrew-cask#11133]
Reopening to track the issue brought up originally in #9586.  In short, `brew cask cleanup` should remove old versions

**Comment by vitorgalvao** [comment]
And [as said in that issue](https://github.com/caskroom/homebrew-cask/issues/9586#issuecomment-74789041), there are already two issues open concerning this. Opening yet another one serves no purpose, and is detrimental.

**Comment by johntdyer** [comment]
Damn, I am sorry, I am not sure how I missed that there were two other open issues.  My apologizes, I certainly wouldn't have opened this had I seen that. Sorry for the extra noise
