### ISSUE TITLE
Is the debug instructions still accurate?

### ISSUE THREAD

**Issue by docwhat** [caskroom/homebrew-cask#11184]
When I got a crash, I got this message:

```
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues
```

However, when I ran `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` I got this error:

```
Already up-to-date.
Error: No available formula for brew-cask
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do
```

I thought `brew-cask` is now `caskroom/cask/brew-cask` instead?

BTW: The `README` has the same text at the bottom.

PS: I know why I got the error, I removed a directory it was scanning with `rmdir -p` and it got grumpy. So don't worry about that.

**Comment by vitorgalvao** [comment]
Yes, it is still accurate.

> I thought `brew-cask` is now `caskroom/cask/brew-cask` instead?

Same thing. `caskroom/cask/` refers to the repo.

**Comment by docwhat** [comment]
Then why did I get an error about it not existing? Just curious.

**Comment by vitorgalvao** [comment]
I don’t have enough information to answer that. If it is causing an issue, [try this first](https://github.com/caskroom/homebrew-cask/issues/6179). Only if it persists, please open a new issue, and [follow the procedure](https://github.com/caskroom/homebrew-cask#reporting-bugs).
