### ISSUE TITLE
`log` subcommand

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#11194]
Would the maintainers be interested in a PR implementing a `log` subcommand, similar to `brew log`, which prints the Git log for a given Cask? The syntax would be `brew cask log [git-log-options] cask`.

For example:

```bash
$ brew cask log spotify

commit 1c27f26cd29f59e65c2573a7618e018f0e448395
Author: Josh Hagins <hagins.josh@gmail.com>
Date:   Tue Dec 30 09:07:05 2014 -0600

    spotify: add launchctl to uninstall

commit 5b2cf2deb0416b749957b3f18e8d2197c94259ed
Author: Kirill Korolyov <kirill.korolyov@gmail.com>
Date:   Tue Dec 30 00:07:01 2014 +0000

    Add spotify name stanza, expand zap stanza

...
```

**Comment by vitorgalvao** [comment]
I’m neutral, here. I wouldn’t be opposed to it, but I’m also not interested in it.

**Comment by jawshooah** [comment]
My particular use case would be to check for updates, or new uninstall/zap
logic.

**Comment by vitorgalvao** [comment]
Like I said, I would not be a opposed at all; I just don’t care about you either. My guess is most will be either on the “neutral” or “do it” camps, so adding it is probably a good idea. No harm in waiting for a couple more opinions, naturally.

**Comment by radeksimko** [comment]
I'm neutral here as well, which means it may be nice to have, but I won't likely spend any time implementing it, although if @jawshooah comes with a PR, I will happily give feedback & eventually merge.

**Comment by vitorgalvao** [comment]
Everyone is neutral but @jawshooah that sees value in this being added, so you have total freedom to do so. Changed issue labels to reflect this.

**Comment by vitorgalvao** [comment]
Is this still something you’re interested in, @jawshooah?

**Comment by jawshooah** [comment]
Not particularly. Let's close for now, and if there's any interest later on we can re-open.
