### ISSUE TITLE
Could you add cask songbird?

### ISSUE THREAD

**Issue by lolgear** [caskroom/homebrew-cask#11221]
Could you add cask songbird to repos?

I know that this project closed, but player is really great.

Maybe other closed projects could be added to casks for their outstanding features?

Thanks!

**Comment by vitorgalvao** [comment]
We do have other discontinued software here, but there doesn’t seem to be an official download url for songbird, so no, we won’t add it.

[Nightingale](http://en.wikipedia.org/wiki/Nightingale_(software)) is a fork, so you might want to try that.
