### ISSUE TITLE
Launch Rocket Installation error

### ISSUE THREAD

**Issue by noinfo** [caskroom/homebrew-cask#11284]
I just tried to install Launch Rocket using:

	brew cask install launchrocket

As instructed on https://github.com/jimbojsb/launchrocket. It gave me the following error which I should report here, so I am. ;-)

	Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/launchrocket.rb'
	Please report this bug:
	    https://github.com/caskroom/homebrew-cask/issues
	<main>:6:in `name'
	<main>:6:in `<class:Launchrocket>'
	<main>:in `<main>'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/source/path_base.rb:55:in `eval'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/source/path_base.rb:52:in `load'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/source/tapped.rb:28:in `load'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask.rb:125:in `load'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/cli/install.rb:17:in `each'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/cli/install.rb:17:in `install_casks'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/cli/install.rb:6:in `run'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/cli.rb:80:in `run_command'
	/usr/local/Cellar/brew-cask/0.38.0/rubylib/cask/cli.rb:120:in `process'
	/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/Library/brew.rb:58:in `require?'
	/usr/local/Library/brew.rb:146:in `<main>'

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

See also #10224.

**Comment by noinfo** [comment]
Thanks for the tip. Sorry to bother you needlessly. I have not been using casks that much so I forgot to upgrade them (only double checked `brew update` and `brew doctor`) prior to installing.
