### ISSUE TITLE
Install command-line interface when installing NoSleep

### ISSUE THREAD

**Issue by szhu** [caskroom/homebrew-cask#11280]
Is there a way to have Cask install this subpackage? It's unchecked by default when I open the installer.

![screen shot 2015-05-20 at 12 34 03 am](https://cloud.githubusercontent.com/assets/1570168/7720979/ed47b3d2-fe87-11e4-9b69-ce94b0cbbc77.png)

For reference: https://github.com/caskroom/homebrew-cask/blob/master/Casks/nosleep.rb

**Comment by vitorgalvao** [comment]
I don’t think there is, unless there’s a command-line option to do it. Do we support that in `pkg`, @phinze @ndr-qef?

**Comment by szhu** [comment]
Relevant: [virtualbox.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox.rb) installs the command line utilities manually, even though the package installer has an option to install them.

**Comment by vitorgalvao** [comment]
Related to https://github.com/caskroom/homebrew-cask/issues/2751.
