### ISSUE TITLE
Request: Biicode update to v3.2

### ISSUE THREAD

**Issue by raquel-ucl** [caskroom/homebrew-cask#11296]
Hi, could you update https://github.com/caskroom/homebrew-cask/blob/master/Casks/biicode.rb
for homebrew to upgrade from biicode 3.1.1, please?

Thanks!

**Comment by mauricerkelly** [comment]
@raquel-ucl This has been updated. Enjoy!

**Comment by raquel-ucl** [comment]
Thanks! :)
