### ISSUE TITLE
Support for .tar.xz in the url stanza

### ISSUE THREAD

**Issue by rednoah** [caskroom/homebrew-cask#11309]
I'd like support for .tar.xz (and maybe .tar.bz2)  archives in the url stanza.

Newer versions of the `tar` command implicitly support `xz` compression so it may already be supported. In which case the url stanza manual should be update to reflect that fact.

**Comment by SeanSith** [comment]
@rednoah The default tar implementation on MacOS X (even in Yosemite) does not currently support XZ compression. I've updated the documentation to show .tbz2 support, but I'm leaving a decision on the XZ support up to Core.

**Comment by tjnycum** [comment]
What about supporting .tar.xz however homebrew does? (They're working with the same tar, right?)

**Comment by DomT4** [comment]
We use a [Homebrew-delivered](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/download_strategy.rb#L58-L60) `xz`.

**Comment by tjnycum** [comment]
Ah, that's right. I remember learning about that on-the-fly addition of an xz dependency a few months ago.

So how about `unxz`ing the .tar.xz's before calling `tar`? Whenever a .tar.xz will have to be unpacked (e.g. `brew cask install`ing a cask that has a such an URL), check for xz in the path. If it's not there, `brew install xz` and proceed (or display an error about it requiring xz if that fails). Yes, it represents an additional dependency, but it would only affect users who actually needed it for a cask they tried to install and who didn't already have it installed anyway.

**Comment by vitorgalvao** [comment]
@rednoah Have you tried [unar](https://github.com/caskroom/homebrew-cask/blob/56feb3f501ed3496c96c12c116fa8d51ca06af80/Casks/parse.rb#L10#L12)? Doesn’t that work?

**Comment by vitorgalvao** [comment]
Closing on account on no reply, since one is needed to proceed.
