### ISSUE TITLE
sudo on 10.5 has no `-E` option

### ISSUE THREAD

**Issue by mfrasca** [caskroom/homebrew-cask#11304]
possibly related to #954, I am trying to install Caskroom/cask/xquartz on a machine running MacOSX 10.5. it fails as described at mistydemeo/tigerbrew#329.

in particular:

    ==> sudo: illegal option `-E'

**Comment by vitorgalvao** [comment]
PRs are welcome, but I doubt any of the core maintainers will want to fix this. I don”t even think we should support anything under 10.6.

**Comment by mfrasca** [comment]
is there anything one can do, either me myself or the tigerbrew people?
I mean, other than telling the owner of the 10.5 machine to buy a new apple license?

**Comment by vitorgalvao** [comment]
> is there anything one can do, either me myself or the tigerbrew people?

Submit said PR.

> other than telling the owner of the 10.5 machine to buy a new apple license?

It can still be installed manually; not supporting it in homebrew-cask doesn’t suddenly make it impossible to install.

I sincerely doubt any time investment from the core maintainers into adding this would be worth it. Like I said, I believe we shouldn’t even be supporting as much stuff as we are now. There’s a reason I’ve tagged the issue seriously, instead of closing it: perhaps I’m wrong an someone will want to take on the task.

**Comment by mfrasca** [comment]
I am not a mac user, and I'm used to debian/ubuntu. if I install a package manually, what will happen with the dependecies? Caskroom/cask/xquartz was required in order to install pygtk.

**Comment by vitorgalvao** [comment]
Not sure, but I’ll ping @ndr-qef since he did the work on the `depends_on` code.

**Comment by mfrasca** [comment]
I was considering it again: the dependency to Caskroom/cask/xquartz is not solved within tigerbrew, so I suppose if I install it otherwise, tigerbrew will find it and it might declare itself satisfied. 

but I am not going to check:
the owner of the 10.5 machine gave feedback which boils down to "never mind".

**Comment by vitorgalvao** [comment]
Alright, let’s close this, then.

**Comment by ndr-qef** [comment]
A late response to the previous question:

> if I install a package manually, what will happen with the dependecies?

Currently, homebrew-cask must control its dependencies, and cannot use independent installations. If you install XQuartz manually, `brew cask install` will fail to identify that the software is available on the machine, and interrupt the process at the dependencies step.

As for the underlying sudo issues, I am not sure whether the `E` flag is useful beyond #954: `brew cask` itself is configured via ENV, but we currently offer no options for sudo-requiring packages.

**Comment by mfrasca** [comment]
I could remove the `-E` option by hand, and see what follows.
can you help me find the file containing the option?
