### ISSUE TITLE
Enhancement: add a "brew --prefix formula" equivalent to cask

### ISSUE THREAD

**Issue by zmwangx** [caskroom/homebrew-cask#11329]
It would be nice if the prefix to which the latest version of a cask is installed is exposed via a subcommand, just like

    brew --prefix formula

exposes the path to the cellar of a formula in `brew`. Currently I get this path with

```bash
shopt -s nullglob
paths=( /opt/homebrew-cask/Caskroom/$caskname/* )
[[ -n $paths ]] && prefix=${paths[-1]} || echo "not found" >&2
```

But this looks awful and is error-prone (there's no guarantee that the latest version will show up as the last one in the glob). Or I can parse the output of `brew cask list cask`, but there's no guarantee on output format, and random parsing code would make a script look even worse.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/8679
