### ISSUE TITLE
Request: bump boot2docker-status version to 1.1.0

### ISSUE THREAD

**Issue by rogeriopradoj** [caskroom/homebrew-cask#11340]
https://github.com/nickgartmann/boot2docker-status/releases/tag/1.1.0

**Comment by rogeriopradoj** [comment]
@vitorgalvao , I'm sorry for this PR #11341 , I've broken the Cask...

I saw know that vendor is not providing v1.1.0 in his website, just in GitHub (https://github.com/nickgartmann/boot2docker-status/releases/download/1.1.0/Boot2Docker.Status-v1.1.0.beta2.zip)

And, as you see, it's v1.1.0.beta2.

Please say to me which is correct for me fixing my mess:

- revert this PR #11341  (and maybe send the beta version to https://github.com/caskroom/homebrew-versions);
- or just fixing the url here in this PR #11341 

P.S.: I'll be more careful about it next versions, ok? Thanks

**Comment by vitorgalvao** [comment]
It’s preferable to just revert the version (not the whole PR, since you added the version, and that’s useful).

**Comment by rogeriopradoj** [comment]
Sorry, not totally clear what I should do. Which of these do you think I should go:
- https://gist.github.com/rogeriopradoj/6b2c477019bbef8c34ec#file-option1_1-0-0_url_out_of_github-rb
- https://gist.github.com/rogeriopradoj/6b2c477019bbef8c34ec#file-option2_1-0-0_url_on_github-rb
- https://gist.github.com/rogeriopradoj/6b2c477019bbef8c34ec#file-option3_1-1-0_url_on_github-rb

**Comment by rogeriopradoj** [comment]
?

**Comment by vitorgalvao** [comment]
[This one](https://gist.github.com/rogeriopradoj/6b2c477019bbef8c34ec#file-option2_1-0-0_url_on_github-rb-L5).
