### ISSUE TITLE
Bump boot2docker version to 1.6.2

### ISSUE THREAD

**Issue by rogeriopradoj** [caskroom/homebrew-cask#11342]
https://github.com/boot2docker/osx-installer/releases/tag/v1.6.2

**Comment by vitorgalvao** [comment]
Please don’t open issues if you’re going to submit a PR right after. It serves no purpose.

**Comment by rogeriopradoj** [comment]
Alright! Thanks for pointing me.

**Comment by vitorgalvao** [comment]
No problem. Appreciate the PRs, though.
