### ISSUE TITLE
Managing application settings

### ISSUE THREAD

**Issue by matthewmueller** [caskroom/homebrew-cask#1135]
Basically merging cask with: https://github.com/lra/mackup. It'd be pretty easy to add a `settings` key to the formula that would have a list of all the settings and preference files.

Then when you want to run the backup, `brew cask backup`. To restore, `brew cask restore`.

**Comment by vitorgalvao** [comment]
Closing. The feature makes no sense for now, and it strays a lot from the “one thing well” philosophy. Lets work on other pressing matters first, and revisit at a later date.
