### ISSUE TITLE
navicat premium sha256 mismatch

### ISSUE THREAD

**Issue by re661b** [caskroom/homebrew-cask#11353]
failed to install navicat premium
Error: sha256 mismatch
Expected: f0d5f93972bd39e9a174d70f897c14afeda17db7390b15de2c417e48084b2ccf
Actual: a20731c590c75a04795c4f5993b0dc68e204482c43e7ce025661f401da6a67e7

**Comment by vitorgalvao** [comment]
In the future, please be more specific in the issue’s title.
