### ISSUE TITLE
Discussion on support for staged_path and Signal in Installer Stanza, alternative: Name in Preflight

### ISSUE THREAD

**Issue by winkelsdorf** [caskroom/homebrew-cask#11366]
I need several workarounds to get Adobe Installations working with Cask.

See: https://github.com/caskroom/homebrew-versions/pull/296#issuecomment-105187458

1) Something like this does *not* work, due to staged_path not being available in Install/Uninstall Stanzas:
```ruby
  installer :script => 'Adobe CS6 Design and Web Premium/Install.app/Contents/MacOS/Install',
            :args   => ['--mode=silent', "--deploymentFile=#{staged_path}/deploy/install-en_US.xml"],
            :sudo   => true
```

There's a PR for this: https://github.com/caskroom/homebrew-cask/pull/8887

2) As I need to terminate a likely running conflicting process, I tried to run this in the Install/Uninstall Stanza:
```ruby
  uninstall :signal => [['KILL', 'SafariNotificationAgent']],
```

Can support for Signal be implemented in Install too? i.e.

```ruby
  install :signal => [['KILL', 'SafariNotificationAgent']],
```

3) My current workaround for the two above is to use Preflights:

```ruby
  preflight do
    system '/usr/bin/killall', '-kill', 'SafariNotificationAgent'
    system '/usr/bin/sudo', '-E', '--', "#{staged_path}/Adobe CS6 Design and Web Premium/Install.app/Contents/MacOS/Install", '--mode=silent', "--deploymentFile=#{staged_path}/Adobe CS6 Design and Web Premium/deploy/install-en_US.xml"
  end

  uninstall_preflight do
    system '/usr/bin/killall', '-kill', 'SafariNotificationAgent'
    system '/usr/bin/sudo', '-E', '--', "#{staged_path}/Adobe CS6 Design and Web Premium/Install.app/Contents/MacOS/Install", '--mode=silent', "--deploymentFile=#{staged_path}/Adobe CS6 Design and Web Premium/deploy/uninstall-en_US.xml"
  end
```

As you can see there's a lot of repeating. Keeping it dry I want to replace 'Adobe CS6 Design and Web Premium' and probably 'en_US' with a local variable.

For the first I was thinking of using the name of the cask. Sadly it is not available as 
```ruby
#{name}
```

in Preflights.

**Question 1: Any way to access the Name property in Preflights?**
**Question 2: Is it allowed to define another variable next to Name, Version, URL, SHA256, etc? i.e. Locale?** and use it in Preflight and/or Installer Stanzas later on?

My experimental cask is working. But I like to keep it dry, currently the text "Adobe CS6 Design and Web Premium" is 5 times in the Cask. Likely error-prone..

**Comment by winkelsdorf** [comment]
Yesterday I created a set of 27 casks for all the Adobe Collections and their Language Editions.

Please consider the above, as the casks only differ in some minor parts. Due to the lack of features mentioned it is really a mess to maintain them correctly, as there are many repetitions which make it easy to omit a needed adjustment.

Simple math:
9 edits (including filename) per Cask are required for one of my Adobe Casks to adjust it for another Product/Language Version. With 27 casks I needed to adjust **243 places** manually.

With my proposed changes these would have been 4 edits per Casks which makes **108 edits**.

That's 45% less work to maintain them and would be dry!

**Comment by vitorgalvao** [comment]
`staged_path` should now be supported in `installer` stanzas.

**Comment by vitorgalvao** [comment]
`staged_path` should now be supported in `installer` stanzas. Is `:signal` in installers still needed?

**Comment by vitorgalvao** [comment]
> Is `:signal` in installers still needed?

If it is, please report back. Closing for now.

**Comment by winkelsdorf** [comment]
Sorry for the late reply. I'll have a look at this as soon as possible. The related casks are quite complicated (nearly all are our Adobe casks), so changing and testing really takes some time. We have too many Adobe casks ;)

Regarding ```:signal```: Yes, still needed. SafariNotificationAgent needs to be closed, otherwise we would move just half of the pre/postflight into the correct DSL sections while the kill signal would be left in the pre/postflights. 

Leave it closed for now, I put it on my todo list.

On the other hand, as we are all somehow short on time, would you mind leaving the current casks as is and implement new ones with the correct Installer stanzas? I see no benefit right now, except for cleaner casks.

**Comment by vitorgalvao** [comment]
> On the other hand, as we are all somehow short on time, would you mind leaving the current casks as is and implement new ones with the correct Installer stanzas? 

Not at all. They can be fixed as time allows (or when new versions are released, or something).

**Comment by winkelsdorf** [comment]
@vitorgalvao I am currently testing the string interpolation in the Installer stanza. Working fine when using e.g. ```#{name.join}``` for ```name``` and ```#{staged_path.join}``` for ```staged_path``` :+1: 

To answer your question: Yes, the Safari Notification Agent is still a problem. As soon as Safari is used on a fresh system and a website asks for displaying notifications it's running (and automatically restarted on system reboot). I really need to kill it, as it's an obvious source of trouble for the users.

**To sum it up, please discuss implementing ```:signal``` for Installer/Uninstall stanzas.**

My working draft, of course Cask warns about unsupported ```:signal``` but does not fail:

```
  installer :signal => [['KILL', 'SafariNotificationAgent']],
            :script => "#{name.join}/Install.app/Contents/MacOS/Install",
            :args   => ['--mode=silent', "--deploymentFile=#{staged_path.join}/#{name.join}/deploy/install-de_DE.xml"],
            :sudo   => true

  uninstall :signal => [['KILL', 'SafariNotificationAgent']],
            :script => "#{name.join}/Install.app/Contents/MacOS/Install",
            :args   => ['--mode=silent', "--deploymentFile=#{staged_path.join}/#{name.join}/deploy/uninstall-de_DE.xml"],
            :sudo   => true
```

This is already way cleaner than previous preflight/postflight.

One question regarding my VM tests: I have to test the casks extensively. Is there a way to prevent redownload of the url and use the local cached copy? Would save a lot of time with this ~> 4 GB Adobe dmgs.

Cheers,
Frederik

**Comment by vitorgalvao** [comment]
Would you mind opening a new issue pertaining just to `:signal`?

The cached version should be used automatically, not sure why it isn’t in this case.

**Comment by adidalal** [comment]
`--force` will wipe out the cached copy, AFAIK

**Comment by winkelsdorf** [comment]
@vitorgalvao not at all, I'll create a new issue

@adidalal I want the opposite, use cached copy instead of redownloading..

**Comment by winkelsdorf** [comment]
@vitorgalvao imo with https://github.com/caskroom/homebrew-cask/issues/17399 open, this can be closed to clean the open issues up a bit. Discussion is referenced from open issue, too.
