### ISSUE TITLE
Reinstall error

### ISSUE THREAD

**Issue by bjm88** [caskroom/homebrew-cask#11374]
Benjamins-MacBook-Pro:T Ben$ brew cask install pdftk
Error: Cask for pdftk (!) is already installed. Add the "--force" option to force re-install.
Benjamins-MacBook-Pro:T Ben$ brew cask install pdftk --force
Error: undefined method `using' for nil:NilClass
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/download.rb:11:in `perform'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/installer.rb:58:in `download'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/installer.rb:35:in `install'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:146:in `<main>'

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

See also #10224.

**Comment by vitorgalvao** [comment]
pdftk also was [removed due to issues](https://github.com/caskroom/homebrew-cask/issues/7707). Please always do a search before opening issues.
