### ISSUE TITLE
gpgtools uninstall missed a couple of directories

### ISSUE THREAD

**Issue by acdha** [caskroom/homebrew-cask#11490]
On my system `brew cask install gpgtools; brew cask uninstall gpgtools` left behind a couple of directories:

```
~/Library/Caches/org.gpgtools.gpg*
/usr/local/MacGPG2/
/Applications/GPG Keychain.app
```

It also left behind a couple of preference and log files but those seem more reasonable since someone might want to do an uninstall/reinstall without losing things.

**Comment by vitorgalvao** [comment]
The first line and the logs belong in `zap`, not `uninstall`.

**Comment by SeanSith** [comment]
@acdha Could you point out where the preferences and log files might live so that I can add them to the cask? Thanks!

**Comment by acdha** [comment]
I believe this was the full list:

```
~/Library/Logs/gpg-home-fixer.log
~/Library/Logs/gpgmail-uuid-patcher.log
~/Library/Logs/shutdown-gpg-agent.log
~/Library/Preferences/org.gpgtools.gpgmail.plist
~/Library/Preferences/org.gpgtools.gpgmail.updater.plist
~/Library/Preferences/org.gpgtools.macgpg2.updater.plist
```

**Comment by vitorgalvao** [comment]
Closing in favour of #11994.
