### ISSUE TITLE
Move casks to external repo

### ISSUE THREAD

**Issue by kubenstein** [caskroom/homebrew-cask#1155]
Hi,
when I started to watch this repo, I quickly realised that, most of issues are related with adding casks, I would prefer to put casks list in external repo keeping 'engine' and 'data' nicely separated. What do you think?

**Comment by hkdobrev** [comment]
Bump.

Homebrew did this:
- https://github.com/Homebrew/homebrew-core
- https://github.com/Homebrew/brew

https://github.com/Homebrew/legacy-homebrew/pull/50659

**Comment by vitorgalvao** [comment]
It was a long time coming, just like ours is. The fact that they’ve done it in no way influences our ability to do so.
