### ISSUE TITLE
Cask request: Pushbullet

### ISSUE THREAD

**Issue by OmgImAlexis** [caskroom/homebrew-cask#11589]
I've contacted the [Pushbullet](http://pushbullet.com) team about this, if they get back to me they'll be adding it themselves otherwise I'll add it in within the next few days.

**Comment by SeanSith** [comment]
@OmgImAlexis Can you ask the Pushbullet team for a link to a public download of the MacOS client and I'll start work on this.

**Comment by gabrielizaias** [comment]
Any news on this?

**Comment by vitorgalvao** [comment]
@OmgImAlexis Will you add it, then?

**Comment by OmgImAlexis** [comment]
I've contacted them multiple times and gotten no response. The link I found before for the "public" version doesn't seem to work anymore. Guess this will need to be closed for now as their only version is on the AppStore now.
