### ISSUE TITLE
java6 pkg installer fail on El Capitan

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#11669]
brew cask install java6 --force
==> Downloading http://support.apple.com/downloads/DL1572/en_US/JavaForOSX2014-001.dmg
######################################################################## 100.0%
==> Running installer for java6; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Cannot install on volume / because it is disabled.
==> installer: A newer version of this package is already installed.
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/java6/1.6.0_65/JavaForOSX.pkg>", "-target", "/"]

==> Output of failed command:
installer: Cannot install on volume / because it is disabled.
installer: A newer version of this package is already installed.

**Comment by vitorgalvao** [comment]
> installer: A newer version of this package is already installed.

You should check that.

It’s too soon for El Capitan issues. We have no clue if they’re OS or package related. Unless you can do the research and come back with a reasoning as to why something is broken, this will just pile up.

**Comment by yurikoles** [comment]
But I can successfully reinstall java package with --force

**Comment by yurikoles** [comment]
Ok it looks like El Capitan does not support this package.

**Comment by vitorgalvao** [comment]
That would be my guess. Looks like the cask might need a `depends_on :macos => '<= :yosemite`.
