### ISSUE TITLE
Same issue, two different casks, two totally different computers/networks

### ISSUE THREAD

**Issue by dmhnorth** [caskroom/homebrew-cask#11685]
I have had this issue today for both installing open office and something else (I'm sorry I can't remember what it was but it wasn't open office, I can check tomorrow) at work today. Two totally different computers on different networks, both MAC OSX Yosemite. 
Having run the command it asks then redoing a brew install, I have the same issue again. I assumed at work today there was a Cask issue, but as I say, this is totally different, but the same issue. 

![screen shot 2015-06-09 at 19 42 40](https://cloud.githubusercontent.com/assets/5593784/8066461/bd4bf810-0edf-11e5-9d03-2bfdc9ce05df.png)

Thanks!

**Comment by vitorgalvao** [comment]
See the `Error` line? Seems like some permissions got screwed. Try `sudo chown -R ${USER}:staff /opt/homebrew-cask`.

**Comment by dmhnorth** [comment]
@vitorgalvao fair enough. Yes thank you this worked!
