### ISSUE TITLE
"brew-cask-0.54.0 already installed, it's just not linked" How do I link it?

### ISSUE THREAD

**Issue by Arcrammer** [caskroom/homebrew-cask#11839]
My installation was successful but I had an issue with linking. Now when I try to install cask I see this message, and when I try to use cask I'm told it wasn't installed:

![screen shot 2015-06-11 at 11 53 59](https://cloud.githubusercontent.com/assets/8358956/8111568/a1634174-1030-11e5-899f-251aff6ac0c8.png)

**Comment by vitorgalvao** [comment]
`brew link brew-cask`. This is more of a homebrew issue, than homebrew-cask.

**Comment by Arcrammer** [comment]
@vitorgalvao I've `brew link brew-cask`ed and I can't write to the directory.
![screen shot 2015-06-11 at 13 30 20](https://cloud.githubusercontent.com/assets/8358956/8113764/29f7c7dc-103e-11e5-8721-a1062c98fffb.png)

**Comment by vitorgalvao** [comment]
Your permissions must’ve gotten screwed someway. `chmod 755 /usr/local/bin`.

**Comment by Arcrammer** [comment]
Ah! I made `/usr/local/bin` 777 and I was able to make the symlinks. Thanks!

**Comment by vitorgalvao** [comment]
Make them `755`, if you can. Really. No reason to give write permissions to others.

**Comment by Arcrammer** [comment]
They're 755 now. Thanks! 😄
