### ISSUE TITLE
Cask request: retab

### ISSUE THREAD

**Issue by fgimian** [caskroom/homebrew-cask#11891]
Would it be possible to please support adding this cool little Safari extension via cask?  It's called [retab](https://github.com/bucaran/retab) and allows you to re-open multiple closed tabs in Safari much like Chrome does.

Thanks heaps
Fotis

**Comment by vitorgalvao** [comment]
We don’t support browser extensions.

**Comment by fgimian** [comment]
Ah, no problem.  Thanks for your reply :smile:
