### ISSUE TITLE
brew cask install infinit broken

### ISSUE THREAD

**Issue by wcarlsen** [caskroom/homebrew-cask#11894]
Launching Infinit.app after install with brew cask, you run into the problem showed in the attached picture below. I worked around it by opening the disk image downloaded by brew cask in the /Library/Caches/Homebrew folder. But if this work around is need for this application, I see no need for this particular piece of software to be included into brew cask. It defy the purpose of brew cask being easy and smart.

![infinit_error](https://cloud.githubusercontent.com/assets/2537399/8149072/17fab522-12b8-11e5-8f3e-4a9c578bfad5.png)

**Comment by vitorgalvao** [comment]
Agreed. Will remove it.
