### ISSUE TITLE
Update Caskroom/cask/cocoapods to version 0.37.2

### ISSUE THREAD

**Issue by mstallone** [caskroom/homebrew-cask#11918]
The Cocoapods cask is outdated and it would be appreciated if the cask could be updates from 0.37.0 to 0.37.2. Thanks!

**Comment by vitorgalvao** [comment]
A PR is welcome. It’s an extremely easy change, and we’re here to help.

**Comment by yurikoles** [comment]
it is latest version as you can see here https://github.com/CocoaPods/CocoaPods-app/releases
