### ISSUE TITLE
Request: Upgrade HandBrake to 0.10.2

### ISSUE THREAD

**Issue by adius** [caskroom/homebrew-cask#11916]

**Comment by vitorgalvao** [comment]
A PR is welcome. It’s an extremely easy change, and we’re here to help.

**Comment by mstallone** [comment]
Made a pull request with the updated version and sha256 here: https://github.com/caskroom/homebrew-cask/pull/11920. (Hope I am doing this right(?)). Cheers

**Comment by fanquake** [comment]
Fixed in #11920

**Comment by adius** [comment]
Thanks!
