### ISSUE TITLE
MacTeX broken

### ISSUE THREAD

**Issue by wcarlsen** [caskroom/homebrew-cask#11931]
Trying to install mactex yields this checksum error, due to mismatch.

###################################################################################

❯ brew cask install mactex
==> Caveats
To use mactex, zsh users may need to add the following line to their
~/.zprofile.  (Among other effects, /usr/texbin will be added to the
PATH environment variable):

  eval `/usr/libexec/path_helper -s`

==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20150613.pkg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 42122a9fa665655369139a109af7a60bbcc26bc58889d2a8b96dd2d8d7aefd32
Actual: c5f5b0fd853a17dab6e844fb5e893804af78d938fa18ee94ec3b257611a95c12
File: /Library/Caches/Homebrew/mactex-20150613.pkg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
A PR is welcome. It’s an extremely easy fix, and we’re here to help.
