### ISSUE TITLE
FreeSMUG Chromium

### ISSUE THREAD

**Issue by rhendric** [caskroom/homebrew-cask#12026]
I'd like to get the stable version of Chromium published by http://www.freesmug.org/chromium into a cask. The existing cask for Chromium is an unstable nightly build published by Google. Which is the better way forward here?

* Move existing `chromium` to `caskroom/homebrew-versions/chromium-nightly`, and replace it with a `chromium` that uses the FreeSMUG drop. This seems more consistent with the way `homebrew-versions` is currently used, and probably less surprising to new adopters of Chromium.
* Leave `chromium` as-is, add a `chromium-stable` or `chromium-freesmug` (or `caskroom/homebrew-versions/chromium-*`?) that points to the FreeSMUG drop. Less disruptive to existing users of the Chromium cask.

I'm happy to contribute all relevant pull requests; just want to know what the maintainers think is the best direction.

**Comment by vitorgalvao** [comment]
[freesmug-chromium.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/freesmug-chromium.rb). Forks get the prepended name.

**Comment by rhendric** [comment]
<facepalm> Yup, I'm an idiot. Sorry!
