### ISSUE TITLE
Add documentation on newline-at-end handling in sublime-text

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#12035]
My pull request of new casks was rejected due to absence of new line at end. Finally I have figured out why my commits had no new line at end. It's caused by Sublime Text. I need to put 2 new lines at end for git to see it as one new line.

**Comment by vitorgalvao** [comment]
It makes no sense to create documentation on every quirk of every editor. It is perfectly possible to make Sublime Text behave in that regard, and that requirement is not specific to homebrew-cask.
