### ISSUE TITLE
Microsoft Office Installer wasting 1 GB of space.

### ISSUE THREAD

**Issue by reitermarkus** [caskroom/homebrew-cask#12034]
I just checked the free space on my 64 GB Macbook Air and found that the `Office Installer.pkg` is taking up 1.02 GB. Isn't it safe to generally delete PKG installers after a successful Installation?

**Comment by vitorgalvao** [comment]
Yes.

**Comment by reitermarkus** [comment]
Why is it needed?

**Comment by vitorgalvao** [comment]
To make the installation possible, and because it is usually useful to keep what the cask downloads.

**Comment by reitermarkus** [comment]
Yes, of course you need it for the installation, but when it is installed successfully, what is it used for?

**Comment by vitorgalvao** [comment]
Nothing. It is done for every cask. For some it is useful, for others it is not.

**Comment by reitermarkus** [comment]
Could you give an example of when it might be useful to keep? I can't think of a reason.

**Comment by vitorgalvao** [comment]
It is needed to making linking possible (so, in most casks, and every one that is a non-pkg). On pkg casks it is useful for when it includes an uninstaller, for example.

**Comment by jawshooah** [comment]
Not sure about the uninstaller point. `uninstall :pkgutil` does not require the original `pkg`, as it just uses the system registry.

There really isn't a good reason for keeping the `pkg` installer around other than for consistency with non-`pkg` casks, as far as I can see. @reitermarkus, you can safely delete it if you're low on space.

**Comment by vitorgalvao** [comment]
I meant in the sense of keeping everything downloaded, not just the `pkg` itself. Casks like virtualbox provide an uninstaller.
