### ISSUE TITLE
Provide symlinks to binaries for command-line launch for all casks

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#12030]
Redouble of #12028. 
It will be good to have symlinks for binaries for launching from command-line launch. As with `subl` for sublime-text* cask.

**Comment by vitorgalvao** [comment]
This is too broad. Unless you provide a list of the ones missing, there’s no way to track progress.

**Comment by yurikoles** [comment]
It's *all* casks except sublime-text ones and java as I know.

**Comment by vitorgalvao** [comment]
Ah, I see what you mean. Definitely no. Sublime Text is a specific case: that method is not only supported, but officially recommended. We’re not just going to start spamming user’s `/usr/bin` with every app under the sun.
