### ISSUE TITLE
libreoffice-beta won't download

### ISSUE THREAD

**Issue by penetrance** [caskroom/homebrew-cask#12039]
brew cask install --appdir="/Applications" libreoffice-beta
==> Downloading https://download.documentfoundation.org/libreoffice/testing/5.0.0/mac/x86_64/LibreOfficeDev_5.0.0.0

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'libreoffice-beta' with message: Download failed: https://download.documentfoundation.org/libreoffice/testing/5.0.0/mac/x86_64/LibreOfficeDev_5.0.0.0.beta1_MacOS_x86-64.dmg

Here is the download site: https://www.libreoffice.org/download/libreoffice-fresh/?version=5.0.0

**Comment by vitorgalvao** [comment]
You need to `brew update`.

**Comment by erkkimon** [comment]
I'm experiencing exactly the same problem. Unfortunately "brew update" doesn't help.

`$ brew update && brew cask install libreoffice-beta
Already up-to-date.
==> Downloading https://download.documentfoundation.org/libreoffice/testing/5.1.

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'libreoffice-beta' with message: Download failed: https://download.documentfoundation.org/libreoffice/testing/5.1.2/mac/x86_64/LibreOffice_5.1.2.1_MacOS_x86-64.dmg`

**Comment by erkkimon** [comment]
Thanks! Good to know, I'll keep that possibility in mind next time I bump into an unexisting package.
