### ISSUE TITLE
cask ignores --appdir=/Applications on 10.11

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#12031]
```bash
Hack-yurikoles:Library yurikoles$ echo $HOMEBREW_CASK_OPTS
--appdir=/Applications
Hack-yurikoles:Library yurikoles$ sudo brew cask install qbittorrent --force
==> Downloading http://downloads.sourceforge.net/sourceforge/qbittorrent/qbittorrent-3.2.0.dmg
Already downloaded: /Library/Caches/Homebrew/qbittorrent-3.2.0.dmg
==> Symlinking App 'qBittorrent.app' to '/Users/yurikoles/Applications/qBittorrent.app'
🍺  qbittorrent staged at '/opt/homebrew-cask/Caskroom/qbittorrent/3.2.0' (51 files, 42M)
```

**Comment by yurikoles** [comment]
Sorry, invalid issue, since I'm running from sudo. I need to set same variable for root.

**Comment by vitorgalvao** [comment]
What about at runtime: `brew cask install --appdir='/Applications' qbittorrent`? Like I said before though (I believe it was to you), it is too soon for El Capitan issues. Unless you can narrow the issue to its cause, we’d be stabbing blindly at something that might get fixed soon.

**Comment by yurikoles** [comment]
It is caused by upstream issue https://github.com/Homebrew/homebrew/issues/40956
In two words: it's required to run brew with sudo on 10.11.

**Comment by DomT4** [comment]
> In two words: it's required to run brew with sudo on 10.11.

In case anyone else stumbles on this issue - This hasn't been true of other users so far, and isn't generally recommended.
