### ISSUE TITLE
Best way to upgrade boot2docker ?

### ISSUE THREAD

**Issue by kuno** [caskroom/homebrew-cask#12032]
Currenlty, I have old boot2docker was installed through `brew cask`, but when I try to upgrade it I alwasy got this error:

```
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/boot2docker/1.7.0/Boot2Docker-1.7.0.pkg>", "-target", "/"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 65923 exit 1>
```

cask seems to failed to manage the uninstallation of old version.

So, what I have to do every time I want to upgrade boot2docker is manually delete the app, then restart the computer. Only after that I can use `brew cask install boot2docker` to upgrade it. Kind painful.

Any better way to hanlde this issue ?

**Comment by vitorgalvao** [comment]
Why manually? Why not just `brew cask uninstall boot2docker && brew cask install boot2docker`? Upgrading is not implemented yet.

For posting issues, though, please [follow the procedure](https://github.com/caskroom/homebrew-cask#reporting-bugs).
