### ISSUE TITLE
Brew cask list shows packages which can't be uninstalled

### ISSUE THREAD

**Issue by jcrben** [caskroom/homebrew-cask#12041]
I wouldn't be surprised if I'm missing something simple here; couldn't find anything similar in the issues. I did a brew update and brew upgrade after encountering this. I may do a clean reinstall but would like to work a little more at figuring out what went wrong.  `Brew cask doctor` report is [here](https://gist.github.com/jcrben/e3025a1b78ce6de7daa6). I tried the --verbose flag and it didn't show me anything different. 

My brew cask list looks like this:
```
anki			   handbrake		      the-unarchiver
appcleaner		   iterm2		      transmission
apptivate		   ngrok		      vagrant
atom			   qt-creator		      virtualbox
avidemux		   scroll-reverser	      vlc
backblaze		   shiftit		      xquartz
firefoxdeveloperedition	   skype		      xtrafinder
gimp			   slack
google-chrome		   sublime-text3
```
When I try to uninstall, say, handbrake, I get this:
```
Terminal$ brew cask uninstall handbrake
Error: handbrake is not installed
```
Same applies to iterm2. But I uninstalled another package after I was getting these errors, so it doesn't affect all of them. I haven't tried an

Weird things that could have caused the issue:
1. I played with the`homebrew-versions` tap . I have the following iterm2 cask: `/opt/homebrew-cask/Caskroom/iterm2`.
2. I manually edited the pinta formula (to download test versions for debugging) and that caused some errors, but I copied the clean formula over and those seem to be gone.

**Comment by vitorgalvao** [comment]
`list` is deeply broken. There’s an issue about this and https://github.com/caskroom/homebrew-cask/pull/12042, which is the most common? Because that one can be merged, but the other must go to [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by jcrben** [comment]
Looks like I didn't notice #2988.
