### ISSUE TITLE
wkhtmltopdf alters directory ownership breaking homebrew

### ISSUE THREAD

**Issue by scottjacobsen** [caskroom/homebrew-cask#12093]
Installing wkhtmltopdf changes the owner of `/usr/local` to `root:wheel`. It should be `scott:admin`. Several subdirectories under `/usr/local` also had their ownership changed to `root:wheel` (`bin`, `include`, `share`, `lib`, `man`)

All this causes `brew update` to fail. To fix it I did
* `brew cask uninstall wkhtmltopdf`
* `chown -R scott:admin /usr/local`

Then cleanup the homebrew git repo with `git checkout .` and `git clean -f`

**Comment by vitorgalvao** [comment]
This is similar to [pdftk](https://github.com/caskroom/homebrew-cask/issues/7707). Could you contact the developer about this?

In the meantime, the cask should be removed. Thank you for the heads-up.

**Comment by scottjacobsen** [comment]
Fixed in master, but not released yet https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2252

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue.

**Comment by scottjacobsen** [comment]
I installed the test release and verified it did no change ownership of
the directories. :+1:

`brew doctor` does product this output:

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libwkhtmltox.0.12.3.dylib
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/wkhtmltox/image.h
    /usr/local/include/wkhtmltox/pdf.h

```

But I think that is brew's issue, and not wkhtmltopdf's problem.

**Comment by vitorgalvao** [comment]
Added back in https://github.com/caskroom/homebrew-cask/issues/12647.

**Comment by 7Moses** [comment]
Oh dear, this appears not to be fixed, I get similar issues to the report by @scottjacobsen, with brew doctor:

https://www.evernote.com/l/AAckZvkLB_NE-rYNfJ5CY4C6gckLkiVHqqo

Warning: /usr/local/bin isn't writable.

You should probably change the ownership and permissions of /usr/local/bin
back to your user account.
  sudo chown -R $(whoami) /usr/local/bin 

Etc,

**Comment by vitorgalvao** [comment]
@7Moses Please [open a new issue](https://github.com/caskroom/homebrew-cask/issues/new?title=Bug%20report%3A&body=%28Remember%20to%20run%20%60brew%20update%3B%20brew%20cleanup%3B%20brew%20cask%20cleanup%60%20before%20reporting%20your%20issue.%20It%20usually%20fixes%20things%21%29%0A%0A%23%23%23%20Description%20of%20issue%0A%0A%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20%3Ccommand%3E%20--verbose%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A%0A%23%23%23%20Output%20of%20%60brew%20doctor%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20doctor%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A).
