### ISSUE TITLE
Is there a way to relink programs?

### ISSUE THREAD

**Issue by reitermarkus** [caskroom/homebrew-cask#12103]
Is there a `brew cask` equivalent to `brew unlink` and `brew link`?

**Comment by vitorgalvao** [comment]
No.

**Comment by john-kurkowski** [comment]
For posterity, what's the workaround?

**Comment by john-kurkowski** [comment]
I have a lot of Casks now symlinked to the wrong location, after homebrew-cask's migration from `/opt/homebrew-cask/Caskroom/` to `/usr/local/Caskroom/`. [This comment](https://github.com/caskroom/homebrew-cask/issues/21913#issuecomment-226314382) from #21913 describes my issue and seems to offer a solution.

**Comment by jawshooah** [comment]
There's no easy re-linking solution that will work in all situations since we can't search your whole filesystem for symlinks back to the old Caskroom location. I'd recommend the following:

```bash
CASKS=$(brew cask list)
for cask in "${CASKS[@]}"; do
  brew cask install $cask
done
```
