### ISSUE TITLE
Protocol preference?

### ISSUE THREAD

**Issue by scribblemaniac** [caskroom/homebrew-cask#12136]
Is https preferred over http for download or homepage urls? I noticed a few http urls for sites that do provide valid certificates. Would it be beneficial to change these links to https? I didn't see anything indicating that one should be favored over the other, but from a security standpoint I think it would be better if we used encryption when it is available.

**Comment by vitorgalvao** [comment]
`https` is preferred. However, some `https` url simply redirect to `http`, and those we prefer to keep as `http`, so as to not give a false sense of security.

**Comment by scribblemaniac** [comment]
Okay, thanks for the info!
