### ISSUE TITLE
How to clean unnecessary temporary files?

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#12148]
While installing the new version of eclipse-ide (whose file to be downloaded is currently very large and very long) I noticed something with the file cleanup:
=> if I abort `brew cask install eclipse-ide` during the download, and even if I enter `brew cask cleanup`, then re-entering `brew cask install eclipse-ide` resumes from the the previous downloaded amount.

So, it seems that the cleanup did not remove the partially downloaded file, and that it would remain definitely on the hard disk if I had never resumed and finished the installation.

Then, my questions:
1. where is this partial and temporary file located?
2. is it really normal to keep those files after cleanup request?

**Comment by vitorgalvao** [comment]
1. `echo $(brew --cache)`.
2. Yes.

`rm -rf $(brew --cache)` gets rid of everything.
