### ISSUE TITLE
Error when trying to install CorsixTH

### ISSUE THREAD

**Issue by anunez** [caskroom/homebrew-cask#12159]
Can't install CorsixTH 4.0 due to this error:
```
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/corsixth/0.40/CorsixTH.app'
```

![screen shot 2015-06-28 at 20 35 52](https://cloud.githubusercontent.com/assets/144149/8397731/8c887be0-1dd5-11e5-9f55-89cb1f1781dc.png)

@Ngrd

**Comment by Ngrd** [comment]
Yes, thank you for noticing.
