### ISSUE TITLE
Duplicate: prolific-usb-serial-driver - pl2303

### ISSUE THREAD

**Issue by porcoesphino** [caskroom/homebrew-cask#12169]
These appear to be duplicates:

- https://github.com/caskroom/homebrew-cask/blob/master/Casks/prolific-usb-serial-driver.rb
- https://github.com/caskroom/homebrew-cask/blob/master/Casks/pl2303.rb

If they are different then `brew cask info` should provide that information. It's also likely that these installs should be aware of each other. Is there a better way for me to be bringing this up?

**Comment by vitorgalvao** [comment]
Thank you for the report. Will remove one of them.
