### ISSUE TITLE
airvpn won't install 

### ISSUE THREAD

**Issue by penetrance** [caskroom/homebrew-cask#12167]
~: brew cask install airvpn
==> Downloading https://airvpn.org/repository/2.9/airvpn_osx_x64_installer.pkg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: d7bc9fc8d2f944a3e63f0ec0a86900952ee96bf28a6cd0293d6f53a510024f4a
Actual: 06c49f4d2b8754e7eec7687445631b36fd3352418e466b2f571dda3a3c37827b
File: /Library/Caches/Homebrew/airvpn-2.9.pkg
To retry an incomplete download, remove the file above.

doesn't work after brew update either

**Comment by vitorgalvao** [comment]
Care to try and submit a PR? It’s an easy fix.
