### ISSUE TITLE
Amazon Music won't launch after install

### ISSUE THREAD

**Issue by robwilkerson** [caskroom/homebrew-cask#12173]
Installed the Cask on a brand new Mac (Yosemite) and get the following:

    $ brew cask install amazon-music                                                                                                                                    0s
    ==> Downloading https://images-na.ssl-images-amazon.com/images/G/01/digital/music/morpho/installers/20150507/190803093e/AmazonMusicInstaller.dmg
    ######################################################################## 100.0%
    ==> Running installer script Amazon Music Installer.app/Contents/MacOS/osx-intel
    ==> Error running launchctl remove com.amazon.music : child process exited abnormally
    ==> Error running launchctl remove com.amazon.cloud-player : child process exited abnormally
    🍺  amazon-music staged at '/opt/homebrew-cask/Caskroom/amazon-music/3.9.5.543' (12 files, 54M)

The app won't launch after the install is complete. I haven't had a chance to dig much deeper, but thought I'd drop this just in case someone else has any thoughts.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask#reporting-bugs.

**Comment by robwilkerson** [comment]
Ok, point taken. :-) I've had a chance to do a little more with this and even after downloading the app directly does not launch properly. I'm not sure what's going on with this app on this computer, but it's not specific to the cask.

**Comment by stevenqzhang** [comment]
@robwilkerson did you ever get this resolved?

**Comment by robwilkerson** [comment]
I did. Delete the application data directory and relaunch.

    $ rm -rf ~/Library/Application Support/Amazon Music

**Comment by kkrauss-gpsw** [comment]
> `$ rm -rf ~/Library/Application Support/Amazon Music`

Should be 

`$ rm -rf ~/Library/Application\ Support/Amazon\ Music`
