### ISSUE TITLE
Add a 'prefix' command

### ISSUE THREAD

**Issue by jfelchner** [caskroom/homebrew-cask#12195]
It's often necessary in scripts to be able to know where homebrew installed something when you don't know what the version is that it installed.

Homebrew proper has the `--prefix` flag which lets you specify a package.

```
$ brew --prefix macvim
/usr/local/Cellar/macvim/7.4-76
```

It would be nice if `homebrew-cask` had the same type of feature.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/8679, https://github.com/caskroom/homebrew-cask/pull/8679.
