### ISSUE TITLE
Renaming the Target Based on System Language

### ISSUE THREAD

**Issue by githubutilities** [caskroom/homebrew-cask#12217]
Can it be possible for `homebrew-cask` to rename target based on system language?

**Comment by vitorgalvao** [comment]
Most users won’t want to be surprised in that manner. Our installations should have as few surprises as possible.

**Comment by githubutilities** [comment]
Why users will be surprised by this? 
On 07/01/2015 00:52, Vítor Galvão wrote:

Most users won’t want to be surprised in that manner. Our installations should have as few surprises as possible.

**Comment by githubutilities** [comment]
Why users will be surprised by this?

**Comment by vitorgalvao** [comment]
Because a package’s name should not be changed without warning, especially if you do not want it to, which many users won’t.

**Comment by githubutilities** [comment]
OK.
