### ISSUE TITLE
Webstorm for OSX 10.10 use a different download (Bundled JVM)

### ISSUE THREAD

**Issue by victorhooi** [caskroom/homebrew-cask#12287]
OSX 10.10 (Yosemite) and upwards require a different version of Yosemite, with the Java 1.8 bundled.

Download link is:
* http://download.jetbrains.com/webstorm/WebStorm-10.0.4-custom-jdk-bundled.dmg
* https://download.jetbrains.com/webstorm/WebStorm-10.0.4-custom-jdk-bundled.dmg

Any chance this can be integrated somehow into the existing Webstorm formula?

**Comment by victorhooi** [comment]
Aha, it seems homebrew-versions (https://github.com/caskroom/homebrew-versions) has one - hmm, is that the better place for it, rather than trying to integrate it into the mainline Webstorm formula?

**Comment by vitorgalvao** [comment]
[Work is being done with unification](https://github.com/caskroom/homebrew-versions/issues/879).
