### ISSUE TITLE
brew cask update atom does not install Atom v1.0

### ISSUE THREAD

**Issue by cclauss** [caskroom/homebrew-cask#12286]
Atom went v1.0 one week ago: http://blog.atom.io

Yet `brew cask update atom`leaves me with Atom v0.209.0.

The .rb file looks good to me but I am not an expert in such things.

**Comment by vitorgalvao** [comment]
`update` doesn’t exist yet. You have to `install --force` it.

**Comment by cclauss** [comment]
Thx.  That works!

Is there an easy way to find our which currently installed casks are out of date?

**Comment by vitorgalvao** [comment]
You’ll find some workarounds on [#4678: Draft Roadmap: `brew cask upgrade`](https://github.com/caskroom/homebrew-cask/issues/4678).
