### ISSUE TITLE
itunesproducer.rb is missing uninstall

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#12343]
[iTunes Producer cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/itunes-producer.rb) is missing a needed `uninstall`. No `pkg` cask should be without it.

**Comment by scribblemaniac** [comment]
While I did manage to find the package id, I had to go through all of my packages with `pkgutil --pkgs`. For some it does not show up when running `./developer/bin/list_recent_pkg_ids`, even right after installing with cask. I'm thinking that there's a bug with the list_recent_pkg_ids script that this should perhaps been made into an new issue and investigated further.
