### ISSUE TITLE
obs error

### ISSUE THREAD

**Issue by wildeyes** [caskroom/homebrew-cask#12356]
If I `brew cask install obs`, I get an error. If I use the same with sudo, I don't and it installs correctly, why doesn't it prompt for sudo?
```
[1] > brew cask install obs                                           ~
==> Downloading https://github.com/jp9000/obs-studio/releases/download/0.9.1/obs
Already downloaded: /Library/Caches/Homebrew/obs-0.9.1.dmg
==> This subcommand requires root privileges: bsexec
Error: Empty plist input
```

**Comment by vitorgalvao** [comment]
You’re likely using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

Either way, related to https://github.com/caskroom/homebrew-cask/issues/9364.
