### ISSUE TITLE
CalcService.zip not unzipping to Caskroom/calcservice

### ISSUE THREAD

**Issue by leoj3n** [caskroom/homebrew-cask#12415]
~~~
~ ❯❯❯ brew cask install calcservice                                                                                                                                                   
==> Downloading https://s3.amazonaws.com/DTWebsiteSupport/download/freeware/calcservice/3.4.1/CalcService.zip
Already downloaded: /Library/Caches/Homebrew/calcservice-3.4.1.zip
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/calcservice/3.4.1/CalcService/CalcService.service'
~~~

Is this a problem with `service`?

**Comment by vitorgalvao** [comment]
It means whatever was inside that directory either has a different name of under a different directory structure.

Care to try and fix it? You’ll need to download it manually and check.

**Comment by leoj3n** [comment]
The URL works...

<https://s3.amazonaws.com/DTWebsiteSupport/download/freeware/calcservice/3.4.1/CalcService.zip> 

In Cache I see `CalcService.zip`. Extracting that results in `CalcService.app`... So I don't know.

**Comment by leoj3n** [comment]
Seems cask isn't creating the calcservice directory at all in the first place.

**Comment by vitorgalvao** [comment]
> Extracting that results in `CalcService.app`

There’s the problem. The cask expects [`CalcService.service`](https://github.com/caskroom/homebrew-cask/blob/73fb32d74129218939842beb1fd43c4d309427a1/Casks/calcservice.rb#L11).

**Comment by leoj3n** [comment]
I see, so `service` cannot handle `.app`... How to proceed?

**Comment by vitorgalvao** [comment]
Change `service` to `app`.

**Comment by vitorgalvao** [comment]
Fixed.
