### ISSUE TITLE
hr download link broken

### ISSUE THREAD

**Issue by leoj3n** [caskroom/homebrew-cask#12429]
The download link in [hr.rb](https://github.com/caskroom/homebrew-cask/blob/325b4dd13020b197ef7a858f50581504280350f6/Casks/hr.rb) is no longer working and I can't find a replacement on their [website](http://www.hrmacapp.com).

Looks like it's only available on the app store now.

**Comment by vitorgalvao** [comment]
Looks like it. We’ll have to remove it. Thank you.
