### ISSUE TITLE
foxtel-go url broken

### ISSUE THREAD

**Issue by scribblemaniac** [caskroom/homebrew-cask#12428]
I'm getting a 403 error when attempting to download this cask. Can someone please confirm this behavior?

I can't seem to find another download link so if this doesn't work for others than we'll probably have to remove this cask altogether.

Pinging @joshuakelly

**Comment by joshuakelly** [comment]
http://download.foxtel.com.au/go/1.5/Foxtel-Go.pkg

The link definitely works. I'm not sure why it's broken.

**Comment by scribblemaniac** [comment]
It still doesn't work for me. Can you perhaps try clearing your cookies for that website and checking to see if the url still works?

**Comment by joshuakelly** [comment]
I'm using a brand new machine. The link still works.

**Comment by joshuakelly** [comment]
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/foxtel-go/1.5/Foxtel Go.app'

This is the error i'm getting when trying to brew cask install though.

**Comment by vitorgalvao** [comment]
I get the `403` as well.

**Comment by joshuakelly** [comment]
http://download.foxtel.com.au/go/1.5/Foxtel-Go.pkg

I can confirm this is the link i was given from Foxtel themselves.

**Comment by vitorgalvao** [comment]
No one is doubting you, but the fact is by either trying to download it with `curl` or clicking that link in a browser, I still get a `403`. If it continues, we need to remove the cask. I did find a [foxtelplay](https://www.foxtel.com.au/foxtelplay/how-it-works/pc-mac.html); perhaps it renamed?

**Comment by joshuakelly** [comment]
Foxtel Play is a different application provided by them. Has the cask ever worked? Strange that it would stop now. I'll look further into it.

**Comment by vitorgalvao** [comment]
Thank you.

**Comment by vitorgalvao** [comment]
Any news, @joshuakelly?

**Comment by joshuakelly** [comment]
Is there something wrong with my config?

**Comment by vitorgalvao** [comment]
Still broken. Lets remove the cask.
