### ISSUE TITLE
subcommand requires root privileges

### ISSUE THREAD

**Issue by ccorcos** [caskroom/homebrew-cask#12481]
```
~ ❯❯❯ brew cask install meshlab
==> Downloading http://downloads.sourceforge.net/project/meshlab/meshlab/MeshLab
######################################################################## 100.0%
==> This subcommand requires root privileges: bsexec
```

**Comment by vitorgalvao** [comment]
[Reporing bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by ccorcos** [comment]
Hmm. I updated brew... I installed with sudo just for the heck of it, but its not supposed to require sudo is it?

**Comment by vitorgalvao** [comment]
No. Actually, installing with sudo is not recommended and is likely the source of the issue.

**Comment by ccorcos** [comment]
hmm. so what do you want me to do? `remove meshlab`, then add with `--verbose` so you can see why it says it required sudo?

**Comment by vitorgalvao** [comment]
Ideally, you’d install homebrew without sudo altogether (why have you done that?), but yes, I need the details that I linked to, to be able to see anything.

**Comment by ccorcos** [comment]
I installed home-brew without sudo.
