### ISSUE TITLE
remote-desktop-connection is not supported in OSX 10.10

### ISSUE THREAD

**Issue by wuj21** [caskroom/homebrew-cask#12488]
$ brew cask install remote-desktop-connection
==> Caveats
remote-desktop-connection has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of OS X.

==> Satisfying dependencies
Error: Cask remote-desktop-connection depends on OS X release <= 10.6, but you are running release 10.10.

**Comment by vitorgalvao** [comment]
Everything is working as expected.
