### ISSUE TITLE
Add support for custom options/flags

### ISSUE THREAD

**Issue by mkouhia** [caskroom/homebrew-cask#125]
Take Firefox cask for an example; `brew cask install firefox` will install en-US version of Firefox by default. Could there be some switch to install different version of the program?

To install the British English version user could do something like
```sh
brew cask install firefox --lang en-GB
```

**Comment by phinze** [comment]
We've matured well beyond this point - we have plenty of solutions for the various cases that would cause a Cask author to want to add a flag. A general facility for Cask-specific flags is unlikely to make it in because of the difficulty in maintaining Casks with that much variance.

So given that, I'm closing this for now - anybody that feels strongly can feel free to petition for reopening. :ok_hand: :ear:

**Comment by vitorgalvao** [comment]
Well, in regards to language flags, I do see them as useful. Maintaining separate casks in [caskroom/versions](https://github.com/caskroom/homebrew-versions) is cumbersome and requires a bunch of work that sometimes even leaves some of the versions outdated. Consolidation into a single cask could really help with this.

**Comment by phinze** [comment]
@vitorgalvao ah good call - agreed. I think we should either open a fresh thread for that feature or rename this issue before reopening; I've always tracked this one as "Casks get to define their own flags". I think if we want to support a new flag we should do it first-class in core.

**Comment by vitorgalvao** [comment]
Sounds good. I always find it better to open new issues, as we can start with an explanation of what we already know/decided without the baggage of the discussion about how we got there. Would you care to do it?

**Comment by Januzz** [comment]
sorry, so is there already a mechanism to select a different language for Firefox than en-US?

**Comment by radeksimko** [comment]
@Januzz See `homebrew-versions` and 26 versions of Firefox:
https://github.com/caskroom/homebrew-versions/search?utf8=%E2%9C%93&q=firefox

Available for installation via `brew cask install caskroom/homebrew-versions/%CASK_NAME%`
