### ISSUE TITLE
Move FontForge.app to /Applications?

### ISSUE THREAD

**Issue by davelab6** [caskroom/homebrew-cask#12517]
FontForge.app needs to be moved to `/Applications` to run; when it is installed with cask and first run, it pops up a [CocoaDialog](http://mstratman.github.io/cocoadialog/) message asking the user to do this, and then opens the `pwd` of the app's current location. It would be better for the cask script to do this directly.

A symlink will not work.

Is that allowed?

cc @DomT4

**Comment by DomT4** [comment]
Afraid I have no control over the Cask's choices. It's possible to do, easily, but I don't know how it'll square with the Cask removal/installation process.

Usually Homebrew will not override a target that already exists, which would make reinstalls or future updates break without removing the application first; I don't know about the Cask. Their `zap :delete` implementation is nifty and I suspect capable of handling that, but I don't know their boundaries on what they find acceptable.

There's an ongoing discussion on this sort of topic in #3888.

**Comment by vitorgalvao** [comment]
To be clear, the user has to move it manually, FontoForge won’t offer to do it, correct?

**Comment by davelab6** [comment]
> To be clear, the user has to move it manually, FontForge won’t offer to do it, correct?

Yes, at the moment. 

In the next release there will be a DMG, so cask will have to move the app out of the dmg, and thus that could be a good moment to do this.

cc @larsenwork

**Comment by vitorgalvao** [comment]
> Is it possible for FontForge to do itself on first run?

Yes, multiple apps do it. It isn’t related to us but the app itself, though.

> In the next release there will be a DMG, so cask will have to move the app out of the dmg, and thus that could be a good moment to do this.

No, not really. The container it is in has nothing to do with it.

**Comment by davelab6** [comment]
Okay cool - can you name any of those apps that are libre licensed so we
can take a look? :)

**Comment by vitorgalvao** [comment]
Check [casks with `suppress_move_to_applications`](https://github.com/caskroom/homebrew-cask/search?utf8=%E2%9C%93&q=postflight+do+suppress_move_to_applications&type=Code). It’s a very common technique, and the message usually looks [like this](https://github.com/caskroom/homebrew-cask/issues/10590#issue-68178000).

**Comment by larsenwork** [comment]
@davelab6 not sure how this is related to the dmg that we'll use once we get the building working again? The new installer in the dmg already copies FontForge.app to /Applications

**Comment by davelab6** [comment]
On 10 July 2015 at 12:48, Andreas Larsen <notifications@github.com> wrote:

> The new installer in the dmg already copies FontForge.app to /Applications


The user has to do that by hand though, right?

**Comment by larsenwork** [comment]
No, double click on the installer that automatically copies ff to /app

**Comment by davelab6** [comment]
Will the installer run okay via cask?

**Comment by larsenwork** [comment]
dunno - what is cask used for (I've never used it)?

**Comment by jawshooah** [comment]
Is it a `.pkg` installer? If so, then yes, Cask can handle that just fine.

**Comment by vitorgalvao** [comment]
@jawshooah Testing it now, it’s an `app` that does something on first launch. It also requires X11, so we need to add that dependency.

@larsenwork Command-line package manager for GUI apps.

**Comment by jawshooah** [comment]
@vitorgalvao Right, but from the discussion above it sounded like they were changing the installer format. Is that the case, @davelab6, @larsenwork?

**Comment by n370** [comment]
![screen shot 2015-08-02 at 11 22 08](https://cloud.githubusercontent.com/assets/1547648/9026541/befaf5be-3908-11e5-8c61-1936ad71fecc.png)

**Comment by vitorgalvao** [comment]
Being tracked in https://github.com/caskroom/homebrew-cask/issues/12858.

Will no longer be an issue after #13201.

**Comment by tjnycum** [comment]
> FontForge.app needs to be moved to /Applications to run

Why is that? That seems like rather bad behavior.

**Comment by scribblemaniac** [comment]
@tjnycum Nobody here developed the application, so nobody here could possibly answer your question.

**Comment by tjnycum** [comment]
@scribblemaniac: davelab6, the OP, seems to be heavily involved in that project.

**Comment by scribblemaniac** [comment]
Yes sorry, my bad.

**Comment by davelab6** [comment]
@tjnycum Fontforge is 100% bad behaviour. It is a 15 year old C application with its own python, and it is brimming with magic to make it run on Mac OS X. One of the consequences is hardcoded paths that begin `/Applications/FontForge.app/...` 

If you want to fix it, you are welcome, but you'll be working full time for a year.

**Comment by davelab6** [comment]
> they were changing the installer format

Believe it when you see it :)

**Comment by n370** [comment]
Thanks @vitorgalvao. I'll be following the discussion on #12858 and #13201. Good luck.
