### ISSUE TITLE
How can I fix this cask?

### ISSUE THREAD

**Issue by vicugna** [caskroom/homebrew-cask#12545]
I created a auWifiConnectForMac.rb file using 'brew cask create'.
And , did ' brew cask install auWifiConnectForMac' .

So , I succeed download file , but I got this error message .

``` errormessage
Error: No such file or directory - /opt/homebrew-cask/Caskroom/auwificonnectformac/latest/auWifiConnectForMac.dmg
```

Could you tell me the way to fix this cask ?

```auWifiConnectForMac.rb
cask :v1 => 'auWifiConnectForMac' do
  sha256 :no_check
  version :latest

  url 'https://service.wi2.ne.jp/sw/auwifi/autoLogin/MacOSX/auWifiConnectForMac.dmg.gz'
  homepage 'http://www.au.kddi.com/mobile/service/smartphone/wifi/wifi-spot/usage/mac/'

  container :nested => 'auWifiConnectForMac.dmg'
  link './au\ Wi-Fi接続ツール.app'
end
```

**Comment by vitorgalvao** [comment]
Plenty is wrong. You should go read the documentation or at least look at other cask. `link`, for example, doesn’t exist anymore (and haven’t for a long while). It is also missing required extensions, like `license`, and the token (the first line, and cask name) is wrong: camel-case isn’t supported, the name should be separated by hyphens.

**Comment by vitorgalvao** [comment]
Plenty is wrong. You should go read the documentation or at least look at other casks. link, for example, doesn’t exist anymore (and haven’t for a long while). It is also missing required extensions, like license, and the token (the first line, and cask name) is wrong: camel-case isn’t supported, the name should be separated by hyphens.

After you look into other casks and the documentation, please come back so we can help with your progress.

**Comment by vicugna** [comment]
thank you.
I read the document again.

**Comment by vitorgalvao** [comment]
For the name and token, read [the token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md). For the cask itself, start by looking at other small casks, like [abyss](https://github.com/caskroom/homebrew-cask/blob/master/Casks/abyss.rb) and see what you’re missing. Refer to [the cask language reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md) for the lines you don’t understand.

Don’t be afraid to submit a PR for review, where we can discuss line by line. Will close this until then.

**Comment by vicugna** [comment]
I have just finished fixing some problem, and I confirmed that the script work fine in my environment.

I want you to confirm whether may be a Japanese app name.

```
cask :v1 => 'au-wifi-connect' do
  version :latest
  sha256 :no_check
  url 'https://service.wi2.ne.jp/sw/auwifi/autoLogin/MacOSX/auWifiConnectForMac.dmg.gz'
  homepage 'http://www.au.kddi.com/mobile/service/smartphone/wifi/wifi-spot/usage/mac/'
  license :unknown

  container :nested => 'au-wifi-connect-latest'
  app 'au Wi-Fi接続ツール.app'
end
```

**Comment by vitorgalvao** [comment]
Good work! It works, but it still needs some fixes before it can be accepted (blank lines are part of it). Care to submit a PR?

```bash
cask :v1 => 'au-wifi-connect' do
  version :latest
  sha256 :no_check

  url 'https://service.wi2.ne.jp/sw/auwifi/autoLogin/MacOSX/auWifiConnectForMac.dmg.gz'
  name 'au Wi-Fi接続ツール'
  name 'au Wi-Fi SPOT'
  homepage 'http://www.au.kddi.com/mobile/service/smartphone/wifi/wifi-spot/usage/mac/'
  license :gratis

  container :nested => 'au-wifi-connect-latest'

  app 'au Wi-Fi接続ツール.app'
end
```

Feel free to ask about any of the changes.

**Comment by vitorgalvao** [comment]
Good work! It works, but it still needs some fixes before it can be accepted (blank lines are part of it). Care to submit a PR?

```bash
cask :v1 => 'au-wifi-spot' do
  version :latest
  sha256 :no_check

  url 'https://service.wi2.ne.jp/sw/auwifi/autoLogin/MacOSX/auWifiConnectForMac.dmg.gz'
  name 'au Wi-Fi接続ツール'
  name 'au Wi-Fi connect'
  homepage 'http://www.au.kddi.com/mobile/service/smartphone/wifi/wifi-spot/usage/mac/'
  license :gratis

  container :nested => 'au-wifi-connect-latest'

  app 'au Wi-Fi接続ツール.app'
end
```

Feel free to ask about any of the changes.

**Comment by vitorgalvao** [comment]
Good work! It works, but it still needs some fixes before it can be accepted (blank lines are part of it). Care to submit a PR?

```bash
cask :v1 => 'au-wifi-connect' do
  version :latest
  sha256 :no_check

  # wi2.ne.jp is the official download host per the vendor homepage
  url 'https://service.wi2.ne.jp/sw/auwifi/autoLogin/MacOSX/auWifiConnectForMac.dmg.gz'
  name 'au Wi-Fi接続ツール'
  name 'au Wi-Fi connect'
  homepage 'http://www.au.kddi.com/mobile/service/smartphone/wifi/wifi-spot/usage/mac/'
  license :gratis

  container :nested => 'au-wifi-connect-latest'

  app 'au Wi-Fi接続ツール.app'
end
```

Feel free to ask about any of the changes.

**Comment by vicugna** [comment]
thank you very much.

 # wi2.ne.jp is the official download host per the vendor homepage

This issue cannot solve to me , Because the vendor of KDDI provide only link below.
https://service.wi2.ne.jp/sw/auwifi/autoLogin/MacOSX/auWifiConnectForMac.dmg.gz

You can confirm it ,if you access "http://www.au.kddi.com/mobile/service/smartphone/wifi/wifi-spot/usage/mac/'.

OK, I can delete blank line , like this.
```
cask :v1 => 'au-wifi-connect' do
  version :latest
  sha256 :no_check
  url 'https://service.wi2.ne.jp/sw/auwifi/autoLogin/MacOSX/auWifiConnectForMac.dmg.gz'
  name 'au Wi-Fi接続ツール'
  name 'au Wi-Fi connect'
  homepage 'http://www.au.kddi.com/mobile/service/smartphone/wifi/wifi-spot/usage/mac/'
  license :gratis
  container :nested => 'au-wifi-connect-latest'
  app 'au Wi-Fi接続ツール.app'
end
```

**Comment by vitorgalvao** [comment]
No, you didn’t understand. The code I’ve posted **including the blank lines and the comment** is how it should look in the end. You can just copy and paste that for a submission.

**Comment by vicugna** [comment]
I have done pull&request . 
thank you!!
