### ISSUE TITLE
Is there any chance to create cask for weka-dev ?

### ISSUE THREAD

**Issue by vicugna** [caskroom/homebrew-cask#12553]
Already there is cask for "weka"(2.6). But I used Weka 2.7 to study by book.

> Weka 3.6 is the latest stable version of Weka, and the one described in the 3rd edition of the data mining book. This branch of Weka receives bug fixes only (for new features in Weka see the developer version). There are different options for downloading and installing it on your system:
http://www.cs.waikato.ac.nz/ml/weka/downloading.html

Is there any chance to create cask for "weka-dev" (2.7) ?

I read this document . 

> Remove from the end: version numbers or incremental release designations such as "alpha", "beta", or "release candidate".
https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md

**Comment by vitorgalvao** [comment]
Unstable versions [belong in a different repo](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#unstable-development-or-legacy-versions).

**Comment by vitorgalvao** [comment]
Done. Run `brew cask install caskroom/versions/weka-dev`.

**Comment by vicugna** [comment]
thank you very mush
