### ISSUE TITLE
brew cask for puppet fail

### ISSUE THREAD

**Issue by hanxue** [caskroom/homebrew-cask#1257]
I am trying to create a cask for `Puppet` - cask formula at https://github.com/hanxue/homebrew-cask/blob/puppet/Casks/puppet.rb. The .pkg gets installed, but when I run puppet (from `/usr/bin/puppet`), it produces this error

```
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- puppet/util/command_line (LoadError)
	from /usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/bin/puppet:3:in `<main>'
```

This is the content of the script:

```
$ cat /usr/bin/puppet
#!/usr/bin/env ruby

require 'puppet/util/command_line'
Puppet::Util::CommandLine.new.execute
```

Am I missing anything?

**Comment by ndr-qef** [comment]
Closing as outdated:
- a [`puppet` Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/puppet.rb) has been in master for a while.
- the `uninstall` stanza takes care of other issues.
