### ISSUE TITLE
isyncr v5.0.8

### ISSUE THREAD

**Issue by ydesgagn** [caskroom/homebrew-cask#12575]
Current version of isyncr is v5.0.3 but v5.0.8 is now available. Can you please update to the latest?

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t difficult, and we’re here to help.

**Comment by ydesgagn** [comment]
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'isyncr' with message: Download failed: http://www.jrtstudio.com/files/iSyncr%205.0.8.pkg
