### ISSUE TITLE
Unifi-controller 4.6.6: Unable to create database

### ISSUE THREAD

**Issue by crmne** [caskroom/homebrew-cask#12604]
Hi,

I just installed unifi-controller 4.6.6 from Cask for the first time in my system. When I run it I get this error message:

![screenshot 2015-07-14 15 10 06](https://cloud.githubusercontent.com/assets/106617/8673908/b317a0ee-2a3a-11e5-9a7c-d2e2782e22cb.png)

Any ideas?

**Comment by vitorgalvao** [comment]
Unrelated to homebrew-cask. Contact the developers.

**Comment by crmne** [comment]
How's this unrelated to cask if it works when I don't use cask to install it?

**Comment by vitorgalvao** [comment]
You haven’t specified that. Also, which cask is that? I can’t find it in the repo.

**Comment by crmne** [comment]
Ok, I thought it was implied since I'm reporting to cask. Next time I'll specify it from the first report.

$ brew cask info unifi-controller
unifi-controller: 4.6.6
Unifi Controller
https://www.ubnt.com/download/?platform=unifi
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/unifi-controller.rb
==> Contents
  Unifi.pkg (pkg)

**Comment by vitorgalvao** [comment]
> I thought it was implied since I'm reporting to cask.

It isn’t. In most issues of this nature, the user never tried it manually. We can’t assume anything as we have no clue what is causing a certain issue for a user. If we assume a simple step has been done, and it hasn’t, we’ll waste a lot of time.

This is a weird one, though. This is a `pkg`, which means we simply leave it to its own devices, we just run it, so installing from homebrew-cask should offer the same result. I was able to reproduce your issue, though. @mauricerkelly, can you?

**Comment by mauricerkelly** [comment]
I’ve actually seen this before. I encountered it when I was trying the beta version of the software - I had been creating a versions cask for that beta and actually gave up at the time because of the consistent failure to run.

However, on my machines (I tried 2) I encountered it with both direct install and cask install.

When this version went from beta to official release, I tested again and on both machines I was able to install correctly, so I felt that it was safe to update the cask. Note that I’ve seen mentioned of an error like this in the UniFi forums, unrelated to installing from Cask.

I’m happy to back out the change and revert back to 3.2.10, however, I am sceptical that it’s anything to do with the cask install method, purely since I’ve seen it before with direct install.

I also apologise if I was trigger happy in updating the cask; I installed it on two machines without problem so I figured it was good to include.

**Comment by scribblemaniac** [comment]
I'm getting the same behavior. It seems to be an issue with the permissions of `~/Library/Application Support/UniFi/data/`, which change for me between direct and cask installs.

**Comment by mauricerkelly** [comment]
@scribblemaniac that’s really useful info. @vitorgalvao are those permissions something we can control with cask?

I wonder is the fact that I was using an “upgraded” install masking the issue? My permissions may already have been suitable.

**Comment by vitorgalvao** [comment]
We should check the pkg install code from homebrew-cask to see if it’s causing the issue. In the meantime, a `postflight` block to fix permissions should suffice.

**Comment by mauricerkelly** [comment]
Sorry for the radio silence on this - day job has been too busy to let me dig into it further.

@vitorgalvao my tests show that a direct install creates the entire `~/Library/Application Support/UniFi` directory (and the `data` subdirectory among others) with the ownership `mortal_user:staff`. When running under brew cask it creates the same structure with the ownership `root:staff`. Hope that's of some help to figuring out why there's a difference.

Looking at other casks I'm thinking I need to put in something like the following:

```ruby
postflight do
  system '/usr/bin/sudo', '--',
    '/usr/sbin/chown', '-R', '--', "#{current_user}:staff", '~/Library/Application Support/UniFi'
end
```

Any problems with the above, and are there any environment variables that would give `~/Library/Application Support` for a bit more neatness?

**Comment by vitorgalvao** [comment]
Your solution looks fine, @mauricerkelly. Care for a PR?

**Comment by mauricerkelly** [comment]
Working on it, though in testing I'm getting these errors: 

`Warning: Unexpected method 'current_user' called during postflight on Cask unifi-controller.`

and: `chown: ~/Library/Application Support/UniFi: No such file or directory` - I've also tried escaping the space in `Application\ Support` but still not happening. Is there a timing issue?

**Comment by vitorgalvao** [comment]
Try instead:

```ruby
postflight do
  system '/usr/bin/sudo', '-E', '--',
         '/usr/sbin/chown', '-R', '--', "#{Etc.getpwuid(Process.euid).name}:staff", Pathname.new(File.expand_path('~')).join('Library/Application Support/UniFi')
end
```

**Comment by jawshooah** [comment]
We should probably add `set_ownership` and `current_user` helpers, since this problem seems to come up fairly frequently.

**Comment by vitorgalvao** [comment]
Agreed. Care to open the issue, or do you want me to do it?

**Comment by jawshooah** [comment]
Doing it right now.

**Comment by mauricerkelly** [comment]
@vitorgalvao thanks for this, and sorry for not getting back to it quicker.
