### ISSUE TITLE
Should Travis verify sha256 hashes of Casks added/changed by incoming PRs?

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#12631]
Following up on a brief discussion in caskroom/homebrew-versions#1120. I think we could fairly easily configure Travis to grab Casks whose `sha256` or `url` stanzas were modified in an incoming PR and verify that they are correct.

This would cut down on the number of PRs like  #12000, #12073, etc. that just fix an error in a previous submission.

**Comment by vitorgalvao** [comment]
Marking my stance as “no strong feelings either way”.

**Comment by scribblemaniac** [comment]
Seems like a good idea to me

**Comment by jawshooah** [comment]
Implemented in #12785.
