### ISSUE TITLE
Scala IDE 4.1.0

### ISSUE THREAD

**Issue by pcastellazzi** [caskroom/homebrew-cask#12632]
Scala IDE 4.1.0 is available. Can you please update the cask?

**Comment by vitorgalvao** [comment]
Care to submit a PR? It’s a pretty straightforward change, and we’re here to help.

**Comment by pcastellazzi** [comment]
No problem. Take a  look at:
https://github.com/caskroom/homebrew-cask/pull/12692

On Wed, Jul 15, 2015 at 4:35 PM, Vítor Galvão <notifications@github.com>
wrote:

> Care to submit a PR? It’s a pretty straightforward change, and we’re here
> to help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caskroom/homebrew-cask/issues/12632#issuecomment-121722548>
> .
>



-- 
The lights then came up and the crowd erupted in applause, because that's
what the crowd does after it watches destruction on a large screen. -- Ben
Kuchera, Modern Warfare 3 review.
