### ISSUE TITLE
Dia SHA256 mismatch?

### ISSUE THREAD

**Issue by tjl** [caskroom/homebrew-cask#12640]
There appears to be a SHA256 mismatch for Dia. When I try and install it, I get
```
==> Downloading http://downloads.sourceforge.net/dia-installer/dia/0.97.2/Dia-0.97.2-7.dmg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 9d3038c01347716800688830eaf52204deb78affe74a5f0c6e0a48fd414d44be
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
```
I've run ```brew update``` but I still have the issue.

**Comment by vitorgalvao** [comment]
Care to submit a PR? It’s a quick fix.

**Comment by zacs** [comment]
This seems to be systemic on SourceForge due to [ongoing site issues starting ~5hrs ago](https://twitter.com/sfnet_ops/status/621702261685686272). It's happening for `media-converter.rb` as well. Seems like we should wait until SF stabilizes before fixing formulae.

**Comment by DomT4** [comment]
Yeah, we're getting whacked at Homebrew [as well](https://github.com/Homebrew/homebrew/issues/41778). SF has been down on-and-off for ~12 hours or so now.
