### ISSUE TITLE
Add wkhtmltopdf

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#12647]
Previously looked [like this](https://raw.githubusercontent.com/caskroom/homebrew-cask/9d1761cbbde957a8969c530e1cd301733918c1d3/Casks/wkhtmltopdf.rb), but [was removed](https://github.com/caskroom/homebrew-cask/pull/12094) due to [a problem](https://github.com/caskroom/homebrew-cask/issues/12093) that seems to [have been fixed](https://github.com/caskroom/homebrew-cask/issues/12093#issuecomment-121105700).

**Comment by scribblemaniac** [comment]
Shouldn't this wait until there is a stable release that includes the fix?

**Comment by vitorgalvao** [comment]
[No](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#but-there-is-no-stable-version). Some users want this. If it works now, it should be included.

**Comment by scribblemaniac** [comment]
Okay, assign this to me, I'll give it a shot later today.
