### ISSUE TITLE
SHA256 mismatch Mongodb

### ISSUE THREAD

**Issue by chrisburgin95** [caskroom/homebrew-cask#12667]
Expected: 8a8993e1914801ace5ce83c92bf4c43127669750e9dec8eb93574e57729e9c42
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Library/Caches/Homebrew/scons-2.3.5.tar.gz
To retry an incomplete download, remove the file above.

brew update did not fix

**Comment by aleksandrs-ledovskis** [comment]
Judging by hash and error message, I think that you are experiencing problem with vanilla Homebrew (not Cask) [scons](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/scons.rb) formula and not Mongo. Currently SourceForge download site is in "Disaster Recovery mode, and currently requires the use of javascript to function" - and that is why when `brew` tool tries to download [the package](https://downloads.sourceforge.net/scons/scons-2.3.5.tar.gz), but gets HTML page with different SHA checksum instead.

**Comment by aleksandrs-ledovskis** [comment]
Would suggest following this issue for ETA and workarounds - https://github.com/Homebrew/homebrew/issues/41778

**Comment by vitorgalvao** [comment]
Yep, nothing we can do.

**Comment by say2joe** [comment]
Thanks for this post. Same issue.
