### ISSUE TITLE
security risk -- memumeters has no hash check

### ISSUE THREAD

**Issue by kristian-hermansen** [caskroom/homebrew-cask#12749]
"sha256 :no_check"

"""
$ curl -s 'https://raw.githubusercontent.com/caskroom/homebrew-cask/master/Casks/menumeters.rb' | egrep -i 'sha[0-9]'
  sha256 :no_check
"""

And because this blob is downloaded over plaintext HTTP, potential for meddling the download is easy and elevates the security threat.

**Comment by vitorgalvao** [comment]
Many casks have no check. We can’t check them when the url is unversioned, or the cask would constantly break.

**Comment by kristian-hermansen** [comment]
Have you asked the distributor to version them? If not let's start there.

**Comment by vitorgalvao** [comment]
Please do.

**Comment by kristian-hermansen** [comment]
If I understand correctly, the publisher would need to move from:

http://www.ragingmenace.com/software/download/MenuMeters.dmg

to something like:

http://www.ragingmenace.com/software/download/MenuMeters-v1.8.1.dmg

To resolve the issues so that versioning can be performed for the cask. If the author does not respond or does not accommodate homebrew for Mac users in this manner, I propose that versioning can still be done by HTML scraping, since the version is there. Is there a reason why that is not being done?

"""
$ curl -s 'http://www.ragingmenace.com/software/menumeters/index.html' | egrep 'MenuMeters\ .*dmg'
					<a href="../download/MenuMeters.dmg">MenuMeters 1.8.1 compressed disk image (dmg)</a>
"""

**Comment by kristian-hermansen** [comment]
<script>alert(1)</script>

**Comment by kristian-hermansen** [comment]
<textarea><script>alert(1);</script>

**Comment by kristian-hermansen** [comment]
</textarea><script>alert(1);</script>

**Comment by vitorgalvao** [comment]
> If I understand correctly

You do, that’s it.

>  versioning can still be done by HTML scraping

No.

> Is there a reason why that is not being done?

Yes, because it’s crazily inefficient and extremely prone to breakage. We’re [not going to parse HTML in such a manner](http://stackoverflow.com/a/1732454/1661012).

In addition, you’re thinking backwards. It’s not the version that matters, the download `url` is. `version` follows from that, not the reverse.

**Comment by kristian-hermansen** [comment]
Seems like homebrew could sha256 hash the binary and have a small lookup table of recent versions to compare against, but yes, I understand this creates more issues...

**Comment by vitorgalvao** [comment]
Again, no. Are you suggesting we download it every day and check the hash? That’s unreal. Not only would we be hammering the developer’s servers, we don’t have the money or the resources for such an operation.

**Comment by kristian-hermansen** [comment]
No, I was suggesting using something less wasteful like...

"""
$ curl -s -I -X HEAD 'http://www.ragingmenace.com/software/download/MenuMeters.dmg'
HTTP/1.1 200 OK
Date: Mon, 27 Jul 2015 17:03:17 GMT
Server: Apache
Last-Modified: Thu, 23 Oct 2014 03:43:12 GMT
ETag: "12170a-5060edd19d6cd"
Accept-Ranges: bytes
Content-Length: 1185546
Content-Type: application/octet-stream
"""

You don't download unless Last-Modified / ETag / Content-Length are outdated...

**Comment by vitorgalvao** [comment]
For code blocks use triple backticks, not `"""`.

That’s better, but we’d still need a server (or someone) to do the checks regularly.

**Comment by kristian-hermansen** [comment]
Author says it will be too much effort and not guarantee much anyway. The author suggests the following instead using the DMG signature:

"I'd suggest investigating signature verification in HomeBrew using SecCodeCheckValidity()"

**Comment by magicgoose** [comment]
> Many casks have no check. We can’t check them when the url is unversioned, or the cask would constantly break.
Then why not remove these casks by default, or issue a warning when user attempts to install such package?
Silently leaving the security hole open is the worst that can happen…

**Comment by vitorgalvao** [comment]
Because they’re still useful and many people don’t mind. Breaking the experience for everyone makes no sense. Regardig showing a warning, there’s an open issue discussing that (search for it, I’m on a phone).
