### ISSUE TITLE
rake test wipes out the current Caskroom! Not documented in hacking.md

### ISSUE THREAD

**Issue by bgandon** [caskroom/homebrew-cask#12741]
`hacking.md` just invites people to run `rake test`. So did I.

`rake test` is usually safe. I ran that directly in the `/usr/local/Library/Taps/caskroom/homebrew-cask` because I was hacking an improvement on the `brew cask info` report, which is buggy when a new version of the cask is remotely available.

Then I figured out that all my staged cask had been deleted from my caskroom directory!
(Btw, I have an `export HOMEBREW_CASK_OPTS="--caskroom=/usr/local/Caskroom"` customization in my `~/.profile`.)

Actually all my staged casks had been deleted, except those with new versions remotely available, that are (wrongly) reported as “Not installed” by `brew cask info`.

So, I'd just like to state that `rake test` should be safe to run, or at least properly documented in `hacking.md`!

**Comment by vitorgalvao** [comment]
Pinging @ndr-qef @radeksimko.

**Comment by vitorgalvao** [comment]
Is this still an issue?

**Comment by jawshooah** [comment]
I'll check it out. It's possible that our test suite isn't overriding `HOMEBREW_CASK_OPTS`.

**Comment by jawshooah** [comment]
Wasn't able to reproduce, but addressed in #16294 anyway.
