### ISSUE TITLE
flash-player is not installed error

### ISSUE THREAD

**Issue by amarendra** [caskroom/homebrew-cask#12760]
I was moving cask installed apps to `/Applications` and then uninstalling them from `Caskroom`[1]. I got this error even though flash-player is installed:

````
amar@mac:driver_app_v2$ brew cask uninstall android-studio
==> Removing App symlink: '/Users/amar/Applications/Android Studio.app'

amar@mac:driver_app_v2$ brew cask uninstall flash-player
Error: flash-player is not installed

amar@mac:driver_app_v2$ brew cask list
anvil		    intel-haxm		noizio		    superduper
atom		    iterm2-borderless	onyx		    tagger
awareness	    java		picasa		    the-unarchiver
battery-guardian    kdiff3		qlvideo		    transmission
cakebrew	    keepingyouawake	recordit	    tunnelblick
cheatsheet	    launchrocket	rowanj-gitx	    vienna
flash-player	    loading		shuttle		    vimr
flashlight	    mac2imgur		slack		    vlc
google-chrome	    macvim		sourcetree	    xld
hexchat		    monolingual		subtitles

amar@mac:driver_app_v2$ brew cask uninstall flash-player
Error: flash-player is not installed
````

Since other apps' uninstalls went smooth I reported this.

[1] Leaving only those which don't install in versioned folders to avoid any issues (#12738) and also being a little apprehensive about a w.i.p app to handle all my apps (or most) on a daily use machine

**Comment by vitorgalvao** [comment]
`brew cask list` is broken, and we’re aware of the issue. Will be performing some restructuring that should fix this.

**Comment by jcrben** [comment]
@vitorgalvao, are you sure  `brew cask list` is broken? This seems like a typical [case of the uninstall issue described in the FAQ](https://github.com/caskroom/homebrew-cask/blob/master/doc/FAQ.md#brew-cask-list-shows-that-a-package-is-installed-but-when-i-try-to-do-brew-cask-uninstall-it-tells-me-that-the-package-is-not-installed-help): "For now, use the brew cask uninstall --force to uninstall these packages." My pull request #12076 basically points people to that immediately and explains why it happens.

`brew cask list`, as far as I can tell, works fine, but uninstall is a bit broken.

**Comment by vitorgalvao** [comment]
Yes, I am sure. There is an issue about that (on a phone now, so won’t look for it).
