### ISSUE TITLE
Announcing new Lead Maintainer: @vitorgalvao

### ISSUE THREAD

**Issue by phinze** [caskroom/homebrew-cask#12775]
Making this issue as a marker to announce that @vitorgalvao is officially taking the title of Lead Maintainer for this project.

Anybody who has interacted with Homebrew Cask will understand that this is an easy move to make - this project would not be anywhere near where it is without Vítor's countless hours of hard work.

By taking on this role, Vítor will be able to make decisions and continue to move the project forward, without having to wait on any other slow-to-respond maintainers like that @phinze guy. :wink: 

Congratulations @vitorgalvao, this is more than well deserved - it's long overdue! On behalf of the entire community of Homebrew Cask users - thanks for all you do. :green_heart:

**Comment by vitorgalvao** [comment]
Thank you, @phinze!

For anyone reading this issue and wondering what that means in practice, there are many ideas in store, including some functional changes (““To install, drag this icon…” no more!” is still the goal, naturally).

More updates on this should come, perhaps with a link from the README to an always up-to-date document detailing everything, but I’m still thinking if that’s the best (most effective) way. Right now, the priority is to integrate some of the current contributors into the team, that you should be seeing soon.
