### ISSUE TITLE
Cask request: Thesaurus

### ISSUE THREAD

**Issue by andreis** [caskroom/homebrew-cask#12787]
http://nisus.com/Thesaurus/download.php

Thank you!

**Comment by andreis** [comment]
For what it's worth, you can also find it on the Mac App Store: https://itunes.apple.com/us/app/nisus-thesaurus/id471448642?mt=12

**Comment by jawshooah** [comment]
Closed in #12789.

**Comment by andreis** [comment]
Thank you @scribblemaniac @jawshooah :+1:

**Comment by scribblemaniac** [comment]
No problem, thanks for submitting the suggestion :+1:
