### ISSUE TITLE
Chromium from FreeSMUG, new version

### ISSUE THREAD

**Issue by wickedsp1d3r** [caskroom/homebrew-cask#12807]
An update from [FreeSMUG](http://www.freesmug.org/chromium) states:

> Chromium 44.0.2403.89 with Flash v. 18.0.0.209 is ready. As @sfnet_ops is down get it [here](https://drive.google.com/file/d/0B2-BVXbmeRD1ZS1lT0hiYXgxVms/view).

This is a special case. Usually new versions have been released at SourceForge.

**Comment by vitorgalvao** [comment]
Thank you. Care to submit a PR? Easy change, and we’re here to help.

**Comment by stullig** [comment]
Just got mail from FreeSMUG, Sourceforge seems to be back up (although they didn't officially announce it), the repo is updated to the latest version, looks like things should be back to normal soon.

**Comment by vitorgalvao** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/commit/900e486e78d3a239512958122dc2c4f4151d11b7.
