### ISSUE TITLE
update mongo-management-studio to 1.8.1

### ISSUE THREAD

**Issue by oaoit** [caskroom/homebrew-cask#12803]
version '1.8.1'
  sha256 '4CE78980A3EB362F37F80B8A69DF60441C664BD10F7378466A35A7BD74BEFE5A'

**Comment by jawshooah** [comment]
You could make the change yourself and submit a [pull request](https://help.github.com/articles/using-pull-requests/). Never a bad time to learn!

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/commit/bca23edf71c1b8abdd1f0b5a45026019b4dac958.
