### ISSUE TITLE
update beaker to v1.3.3

### ISSUE THREAD

**Issue by scottdraves** [caskroom/homebrew-cask#12802]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/beaker.rb
is at 1.3.1

1.3.3 has an important bug fix for safari.

thanks for making beaker easy to install!

**Comment by jawshooah** [comment]
Thanks for letting us know. Care to make the change and submit a PR?

**Comment by vitorgalvao** [comment]
Fixing it now, will be available shortly.
