### ISSUE TITLE
Read the version stanza into a version object instead of a string

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#12827]
As per https://github.com/caskroom/homebrew-cask/issues/6347:

> The purpose of the version object would be to provide more readable methods for manipulating the version number.  This would allow us to write eg `"#{version.underscorify}"` and `"#{version.major}"`.  String manipulation with `sub`/`gsub` works well enough, but is hard to read, and surely presents a barrier for first-time Cask authors and people without Ruby knowledge.  We could still use `sub`/`gsub` for corner cases.

---

Table in progress (feel free to update<sup>1</sup> at will as we agree on things). Initial version taken from the next comment, from @adityadalal924.

| Method Name         | Sample Input | Sample Output | Original Function                                        |
|---------------------|--------------|---------------|----------------------------------------------------------|
| dots_to_underscores | 4.3.2        | 4_3_2         | `#{version.gsub('.','_')}`                               |
| dots_to_hyphens     | 4.3.2        | 4-3-2         | `#{version.gsub('.', '-')}`                              |
| no_dots             | 4.3.2        | 432           | `#{version.gsub('.', '')}` and  `#{version.delete('.')}` |
| major               | 4.3.2        | 4             | `#{version.to_i}`                                        |
| major_minor         | 4.3.2        | 4.3           | `#{version.to_f}`                                        |
|                     | 4.3.2-1337   | 4.3.2         | `#{version.sub(%r{-.*$}, '')}`                           |
|                     | 4.3.2-1337   | 1337          | `#{version.sub(%r{.*?-}, '')}`                           |

----------------------

<sup>1</sup> (Editing is easiest with [Markdown Tables generator](http://www.tablesgenerator.com/markdown_tables) - use File > Paste table data...)

**Comment by adityadalal924** [comment]
Here are some common ones I've seen. Update at will - coming up with intuitive names is hard.

| Method Name  	| Sample Input 	| Sample Output 	| Original Function                                       	|
|--------------	|--------------	|---------------	|---------------------------------------------------------	|
| underscorify 	| 4.3.2        	| 4_3_2         	| `#{version.gsub('.','_')}`                              	|
|              	| 4.3.2        	| 4-3-2         	| `#{version.gsub('.', '-')}`                             	|
|              	| 4.3.2        	| 432           	| `#{version.gsub('.','')}` and  `#{version.delete('.')}` 	|
|              	| 4.3.2        	| 4             	| `#{version.to_i}`                                       	|
|              	| 4.3.2        	| 4.3           	| `#{version.to_f}`                                       	|


(Editing is easiest with [Markdown Tables generator](http://www.tablesgenerator.com/markdown_tables) - use File > Paste table data...)

**Comment by vitorgalvao** [comment]
Names like `underscorify` seem like they could cause some confusion. What it the version is `4.3.2-10567`? Will the `-` also be converted to `_` or not?

We probably should make these (at least at first) be very explicit about what they do (`underscorify` → `dots_to_underscores`) and only later start to simplify names.

Also added table to top comment (we should always keep these types of things on the top comment, so no one has to scroll to see the current state of decisions).

**Comment by vitorgalvao** [comment]
Proposal:

We introduce the word `divider` to mean (at once) `.`, `-`, and `_`. That way, `dividers_to_underscores` does `4.3.2-ffd76_build39` → `4_3_2_ffd76_build39`, while (for instance) `dots_to_underscores` would do `4.3.2-ffd76_build39` → `4_3_2-ffd76_build39`.

**Comment by adityadalal924** [comment]
Left method name blank and added two more cases - these are really common in appcasts, and look terrible (to the first-time user).

If nothing else, maybe we can codify some guidelines for "preferred" version string manipulations (and put the reference table in documentation), if only to make maintaining easier in the long run.

**Comment by adityadalal924** [comment]
Some other fun(ky) ones:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/xamarin-jdk.rb
https://github.com/caskroom/homebrew-cask/blob/master/Casks/xslimmer.rb
https://github.com/caskroom/homebrew-cask/blob/master/Casks/navicat-premium.rb

(remove from here as they are added to main table...)

**Comment by vitorgalvao** [comment]
+ `xamarin-jdk` looks like it could use with an update to `version` itself, since the substitution actually introduces a letter `u`, and that is not a case we can really prepare for.
+ `xslimmer` looks like it can already be simplified with `to_f`.
+ `navicat-premium` looks like a prime example for chaining, since it requires two changes: `to_f` (or equivalent) and removing dots. In the end, we could have something like `#{version.major_minor.no_dividers}`.

The top table should likely be updated to have the same complex version (like `1.2.3-aa45_build67) number across it so it is absolutely clear how proposed changes would work.

**Comment by jawshooah** [comment]
@vitorgalvao @adityadalal924 feel free to take a look at #16205 and provide feedback. I'm sure there are plenty more helpers that would be of use.

**Comment by vitorgalvao** [comment]
In the case of `1.2.3-aa45_build67`, would patch be `3`, or `3-aa45_build67`?

I was thinking not every app uses semantic versioning so I’m not sure we can be as precise as to have `patch`, but then I remembered we actually set `version` to whatever is convenient for us to interpolate, and with that in mind we’d likely also benefit from something that could clearly divide `version` in two.

Case like `http://example.com/efacbeedfewwer/1.2.3.dmg` where we can’t use interpolation due to the string in the middle could have `version '1.2.3/efacbeedfewwer'` and `url "http://example.com/#{version.after_slash}/#{version.before_slash}.dmg"`.

**Comment by vitorgalvao** [comment]
It could also make cases like [`unity`](https://github.com/caskroom/homebrew-cask/blob/d7248c8e5640db8322d1f04fa7fb55612a8483e4/Casks/unity.rb#L5) clearer. There isn’t a version in `url`, but it is versioned. However, setting that weird string in `version` would start to be more detrimental than beneficial. In that case:

```ruby
version '5.3.1f1/cc9cbbcc37b4'
url "http://netstorage.unity3d.com/unity/#{version.after_slash}/MacEditorInstaller/Unity.pkg"
```

**Comment by vitorgalvao** [comment]
For example ([`unity-ios-support-for-editor.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/unity-ios-support-for-editor.rb), shortened). From

```ruby
version '5.3.1f1'
url 'http://netstorage.unity3d.com/unity/cc9cbbcc37b4/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor-5.3.1f1.pkg'
pkg "UnitySetup-iOS-Support-for-Editor-#{version}.pkg"
```

to

```ruby
version '5.3.1f1/cc9cbbcc37b4'
url 'http://netstorage.unity3d.com/unity/#{version.after_slash}/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor-#{version.before_slash}.pkg'
pkg "UnitySetup-iOS-Support-for-Editor-#{version.before_slash}.pkg"
```

**Comment by jawshooah** [comment]
> In the case of `1.2.3-aa45_build67`, would `patch` be `3`, or `3-aa45_build67`?

`patch` would be 3. We could add another helper for `build` to capture the `aa45_build67` (or `after_hyphen`, in the spirit of your next suggestion).

> Cases like `http://example.com/efacbeedfewwer/1.2.3.dmg` where we can’t use interpolation due to the hash in the middle could have `version '1.2.3/efacbeedfewwer'` and `url "http://example.com/#{version.after_slash}/#{version.before_slash}.dmg"`.

I like that idea. There are quite a few casks that could benefit from it.

One thing to keep in mind during this discussion, though, is that the number of special-case helpers could quickly get out of hand. That's why I've extended `::String`, so that we can still fall back on `gsub` and friends when we need to.

**Comment by vitorgalvao** [comment]
> We could add another helper for `build` to capture the `aa45_build67` (or `after_hyphen`, in the spirit of your next suggestion).

`build` is likely not clear enough for now, since there are too many common patterns to account for (`1.2-3`, `1.2_3`, `1.2b3`).

> One thing to keep in mind during this discussion, though, is that the number of special-case helpers could quickly get out of hand. That's why I've extended `String`, so that we can still fall back on `gsub` and friends when we need to.

Very much agreed. That’s why I think being very specific with naming is key at the start, so there are no confusions and we can narrow down options later if need be.

On a different note, the [aforementioned](https://github.com/caskroom/homebrew-cask/issues/12827#issuecomment-167598773) [`navicat-premium`](https://github.com/caskroom/homebrew-cask/blob/e3fe101f9dc6f5808c0b25fd9fa5af1169c79cad/Casks/navicat-premium.rb) is indeed a prime example for chaining. With what we can do now, we could simplify it (somewhat weirdly) with `#{version.to_f.to_s.delete('.')}`.

**Comment by adityadalal924** [comment]
I would say having the `.before_slash` and `.after_slash` functions are reasonable, but we should stop there and push the implemented changes. After seeing the reaction/usage, we can always add more as needed.

**Comment by vitorgalvao** [comment]
Agreed.

**Comment by jawshooah** [comment]
@adityadalal924 @vitorgalvao [Done.](https://github.com/jawshooah/homebrew-cask/blob/d8f07aed9294d7a51bcd8e14d44395e527295daf/spec/cask/dsl/version_spec.rb#L114-L132)

**Comment by vitorgalvao** [comment]
Looks great, to me. Final consideration, though, should `/` be considered a `divider` as well?

Logically, I’d say yes. We don’t lose anything by making it one, even, since we can always chain them like `#{version.before_slash.no_dividers}`, if needed.

**Comment by jawshooah** [comment]
Done. Slashes are now dividers and have all the deletion and conversion methods associated therewith. Good to merge?

**Comment by adityadalal924** [comment]
LGTM. Extending `String` was a nice touch!

**Comment by vitorgalvao** [comment]
> Good to merge?

Yep.

**Comment by jawshooah** [comment]
Closed in #16205.

**Comment by metyl** [comment]
Hi, will You add another helper for `build` or `after_hyphen`, in the spirit of current implementation?

**Comment by vitorgalvao** [comment]
@metyl No, this is mostly done. Any more than we have would start to be too much.
