### ISSUE TITLE
Postgres.app: packaged binaries and app must be moved to /Applications

### ISSUE THREAD

**Issue by NathanJang** [caskroom/homebrew-cask#12857]
I've been looking into [the Postgres cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/postgres.rb).
On every run, it prompts to move itself to `/Applications`; if not, it quits itself. I've tried `postflight do suppress_move_to_applications` but it does nothing to this prompt. What should be done?
In addition, many binaries are packaged in `Postgres.app/Contents/Versions/9.4/bin` (in the latest version), so many that it would be ugly (but possible) to `binary` all of them in the cask. The official guides suggest adding this directory to the PATH. Is this possible?

**Comment by vitorgalvao** [comment]
The current model is broken and there are plans to fix it. I’ll close this issue, but keep track of it in another one.

As for adding a directory to PATH, I’d be wary of that. We shouldn’t really be imposing that on users. There is [a nice solution](https://github.com/caskroom/homebrew-cask/issues/3597) that is minimally intrusive, but it appears to not work (by default) with zsh.

**Comment by NathanJang** [comment]
:+1:
