### ISSUE TITLE
Allow tilde expansion in `uninstall :delete`

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#12864]
Currently, tilde expansion is only allowed in `zap :delete`. I don't see a need for this restriction, and the consensus in #11530 seems to be that we should get rid of it.

Before I dive into the code though, I'd like to confirm with @caskroom/maintainers that this is the right thing to do.

**Comment by vitorgalvao** [comment]
This is the right thing to do, yes. Like you said, there’s no need for the restriction, and it actually impairs some cases. Go for it.
