### ISSUE TITLE
mplayerx broken

### ISSUE THREAD

**Issue by ponychicken** [caskroom/homebrew-cask#12877]
I can't create a PR atm, sorry. mplayerx version should be updated to 1.1.0 , the older version is a 404 on sourceforge.

**Comment by Ngrd** [comment]
There is nothing wrong with [mplayerx.rb](https://github.com/caskroom/homebrew-cask/blob/14502f087d9529a92cbfe7d3a83b462992c39519/Casks/mplayerx.rb). The latest version is 1.1.0, and the URL is working. Feel free to reopen this issue if this problem persists.
