### ISSUE TITLE
Unrelated commits included when auditing modified casks during Travis builds

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#12903]
The commit range provided by Travis in the enrivonment variable `TRAVIS_COMMIT_RANGE` does not appear to include only those commits to be merged in a pull request, as evidenced by [this spurious build failure](https://travis-ci.org/caskroom/homebrew-cask/jobs/73390525) (#12899).

We may want to hard-code the commit range in `.travis.yml` as `refs/remotes/origin/HEAD..HEAD` to ensure that only commits relevant to the pull request are considered when auditing modified Casks.

**Comment by vitorgalvao** [comment]
Go for whatever solution you find best. You have been finding a lot of areas where our Travis checks can be improved, and have been fast and efficient in patching those. Feel free to proceed as you like, with Travis.
