### ISSUE TITLE
Support glob (or regex) expansion in `zap :delete` and `uninstall :delete`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#12991]
Currently not supported, but many casks would benefit from it.

**Comment by jawshooah** [comment]
Would this apply to `uninstall :delete` as well? If so, I believe this overrides #12864.

**Comment by vitorgalvao** [comment]
Well, yes, it could also apply to `uninstall :delete`. Actually, looking at it, [it is even mentioned in the docs as a desirable feature](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-key-delete) (last bullet).

Why would it override #12864, though? Isn’t that pertaining to paths in `~`?

Those same docs need to be revised when #12864 is taken care of, since some of the rules there will be changed. They contradict themselves, actually: you can’t have both “static, absolute paths” and allow globs.

**Comment by jawshooah** [comment]
You're right, I was thinking that glob expansion entailed tilde expansion.

**Comment by mxl** [comment]
@jawshooah Do you plan to implement this feature?

**Comment by vitorgalvao** [comment]
@mxl If you’re asking so you can go ahead and submit a PR, I’d say go for it. @jawshooah has been pretty busy lately, and I doubt he’d object.

**Comment by jawshooah** [comment]
@mxl Not in the near future, no. Please go ahead and submit a PR at your leisure :+1:

**Comment by mxl** [comment]
@jawshooah @vitorgalvao https://github.com/Homebrew/brew/pull/2042
