### ISSUE TITLE
Global install with "-g" flag

### ISSUE THREAD

**Issue by pensierinmusica** [caskroom/homebrew-cask#12995]
Hi,

Would it be possible to add a `-g` flag when performing a Cask install, such that the app gets automatically symlinked to the global app folder, instead of the user app folder?

For example, to install Google Chrome globally I think it'd be much more convenient to type `brew cask install -g google-chrome`, than `brew cask install --appdir="/Applications" google-chrome`.

It should be pretty easy to implement and it sorts of follow a "standard" too (think other package managers like [npm](https://www.npmjs.org/)).

Do you think this could be implemented? Would you like me to create a PR?

Cheers!

**Comment by vitorgalvao** [comment]
No. [/Applications should be the default, anyway](https://github.com/caskroom/homebrew-cask/pull/9178), and linking behaviour should change to copying in the future, so it’d be useless to implement this.

**Comment by pensierinmusica** [comment]
I see, thanks! When is this going to be part of the `master` branch / included in the next release?

**Comment by vitorgalvao** [comment]
No time frame yet.
