### ISSUE TITLE
Firefox formula language support

### ISSUE THREAD

**Issue by f0und3r** [caskroom/homebrew-cask#13010]
Hello!

You can add support for language selection at installation for https://github.com/caskroom/homebrew-cask/blob/master/Casks/firefox.rb?

Example: brew cask install firefox --lang ru-RU

**Comment by jawshooah** [comment]
Language variants are available in the [versions tap](https://github.com/caskroom/homebrew-versions).

**Comment by f0und3r** [comment]
@jawshooah Thank you!
