### ISSUE TITLE
Libre Office

### ISSUE THREAD

**Issue by jehoshua02** [caskroom/homebrew-cask#13027]
Libre Office links have changed:

```
$ brew cask install --verbose libreoffice
==> Downloading https://download.documentfoundation.org/libreoffice/stable/4.4.3/mac/x86_64/LibreOffice_4.4.3_MacOS_x86-64.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-481) https://download.documentfoundation.org/libreoffice/stable/4.4.3/mac/x86_64/LibreOffice_4.4.3_MacOS_x86-64.dmg -C 0 -o /Library/Caches/Homebrew/libreoffice-4.4.3.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'libreoffice' with message: Download failed: https://download.documentfoundation.org/libreoffice/stable/4.4.3/mac/x86_64/LibreOffice_4.4.3_MacOS_x86-64.dmg
```

When you download manually through their site they push you through a donation page. I looked at my download history and the download came from this:

http://mirror.dacentec.com/tdf/libreoffice/stable/4.4.5/mac/x86_64/LibreOffice_4.4.5_MacOS_x86-64.dmg

I'm not comfortable yet adding or updating casks, or if some LibreOffice license clause prevents this from being fixed, so I was hoping someone could help me.

/cc @rolandwalker @jawshooah @ianwalter @vitorgalvao @martinlindhe @gcapizzi @ndr-qef @Ngrd @DomT4 @SeanTAllen

**Comment by vitorgalvao** [comment]
Please don’t @mention so many people, especially for such a simple issue. It’s bad form, and you’re even @mentioning non-collaborators that might have no interest whatsoever in looking at this.

No, there’s likely no license clause preventing this from being fixed. You should also just take a stab at editing it. It’s not like you could do any damage, and we’re available to help with any questions.

**Comment by jehoshua02** [comment]
@vitorgalvao Thanks. I'll give it a go when I have time.

**Comment by martinlindhe** [comment]
@jehoshua02 you should begin by updating your homebrew-cask.
see https://github.com/caskroom/homebrew-cask/commit/9df13781ea97becf532a6fecf618adb507f7de46

**Comment by vitorgalvao** [comment]
Nice catch, @martinlindhe, thank you.

Confirmed the cask as working. Closing. @jehoshua02 Run `brew update` and try again. [You should always do that before opening issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by scribblemaniac** [comment]
How come I didn't get invited to this party? :stuck_out_tongue:
