### ISSUE TITLE
Truncated output

### ISSUE THREAD

**Issue by pdark** [caskroom/homebrew-cask#13077]
When I was installing an app, I noticed the output being truncated as shown in the screenshot below (notice lines 1 and 4). As referenced in the Terminal window title, I'm using a window with dimensions 80x24 (default size) so I think this behaviour shouldn't be expected.

EDIT: Even after enlarging the window, the output stays the same.

![screen shot 2015-08-08 at 00 41 27](https://cloud.githubusercontent.com/assets/3199157/9147907/3d5842ac-3d66-11e5-927c-fd73d95e26fd.png)

**Comment by vitorgalvao** [comment]
Also happens when just downloading from homebrew, so the issue comes from there.
