### ISSUE TITLE
Update haskell-platform to 7.10.2-a

### ISSUE THREAD

**Issue by fboyer** [caskroom/homebrew-cask#13075]
A bunch of fixes were packaged in a quick subsequent release to the 7.10.2 release last week.

See:
* https://www.haskell.org/platform/
* https://github.com/haskell/haskell-platform/releases

**Comment by vitorgalvao** [comment]
Care to submit a PR? It’s not hard, and we’re here to help.

**Comment by vitorgalvao** [comment]
[Done](https://github.com/caskroom/homebrew-cask/commit/d1f7078c6d560e46fde0c9ed19c9ea855309de40).
