### ISSUE TITLE
Rust lang 1.2

### ISSUE THREAD

**Issue by offero** [caskroom/homebrew-cask#13098]
Rust 1.2 is stable. Current cask is 1.1.

https://github.com/caskroom/homebrew-cask/blob/master/Casks/rust.rb

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.

**Comment by offero** [comment]
Sure thing, will do!

**Comment by vitorgalvao** [comment]
Ended up being commit in https://github.com/caskroom/homebrew-cask/commit/053f1da3fcce1ae33bfd6667f3bdb86aef745e41. Next time.
