### ISSUE TITLE
Add VPaint

### ISSUE THREAD

**Issue by nikolay** [caskroom/homebrew-cask#13121]
Homepage: http://www.vpaint.org/
GitHub Home: https://github.com/dalboris/vpaint
Binary: http://sourceforge.net/projects/vpaint/files/v1.5/vpaint.dmg/download

**Comment by Ngrd** [comment]
We already have it: [vpaint.rb](https://github.com/caskroom/homebrew-cask/blob/ab3241e5f23c161863c6b0fc8d4c72b8cefc883e/Casks/). Was added yesterday.

**Comment by scribblemaniac** [comment]
@nikolay I'm one step ahead of you :wink:

**Comment by nikolay** [comment]
Thanks, guys!
