### ISSUE TITLE
Jenkins fails with sha256 mistmatch

### ISSUE THREAD

**Issue by olpie101** [caskroom/homebrew-cask#13155]
Tried to install Jenkins. The sha256 checksums match however the cases are different like so:

```zsh
==> Downloading http://mirrors.jenkins-ci.org/osx/jenkins-1.619.pkg
Already downloaded: /Library/Caches/Homebrew/jenkins-1.619.pkg
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 660F85B7D24133B60972127B42308369B65C971CDBA0D9883F99270306901003
Actual: 660f85b7d24133b60972127b42308369b65c971cdba0d9883f99270306901003
File: /Library/Caches/Homebrew/jenkins-1.619.pkg
To retry an incomplete download, remove the file above.
```

Any idea on how to continue installation? I have tried to use `--force` to install, doesn't work.

**Comment by Ngrd** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/13157. Should be good now. Before trying the installation again run the `brew update`. Feel free to reopen this issue if the problem persists.

**Comment by olpie101** [comment]
Thank you.
