### ISSUE TITLE
What does (!) next to a cask mean? 

### ISSUE THREAD

**Issue by thibmaek** [caskroom/homebrew-cask#13160]
I used `brew cask list` and noticed that one cask (infinit) had an exclamation mark next to it: (!)
Does this have any particular meaning? --help did not make me any wiser :(

<img width="887" alt="screen shot 2015-08-11 at 17 35 51" src="https://cloud.githubusercontent.com/assets/6213695/9202106/800afaf8-4050-11e5-8452-03f97194b39d.png">

**Comment by vitorgalvao** [comment]
It means the cask no longer exists. You installed it when it did. Search for it now, and it won’t find it.

**Comment by michahell** [comment]
Nice terminal color scheme @thibmaek ! get where? :)

**Comment by thibmaek** [comment]
@michahell It's Toy Chest :)

**Comment by fpedroza** [comment]
How can a cask with a (!) be uninstalled at this point?

**Comment by miccal** [comment]
Use `brew cask uninstall --force`.

**Comment by karstenwolniak** [comment]
That doesn't work for me, miccal.

```
brew cask uninstall --force send-to-kindle
==> Running uninstall process for send-to-kindle; your password may be necessary
==> Removing launchctl service com.amazon.sendtokindle.launcher
==> Removing files from pkgutil Bill-of-Materials
==> chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /bin/chmod -- 777 #<Pathname:/usr/libexec/cups>

==> Standard Output of failed command:


==> Standard Error of failed command:
chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 7390 exit 1>
```

**Comment by thibmaek** [comment]
@karstenwolniak that seems like it is more of an issue with the cask than with cask though.

**Comment by miccal** [comment]
This error was why `send-to-kindle` was removed - you will have to remove it manually.
