### ISSUE TITLE
Never use cached download when cask uses `:latest`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#13206]
Refs #6087.

**Comment by adityadalal924** [comment]
Started taking a look at implementing this, even though my Ruby knowledge is pretty minimal.

The file to change is [`lib/hbc/download.rb`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/download.rb)

Under the `perform` def, add in a simple conditional check above the existing code.

```ruby
  def perform(force=false)
    downloader.clear_cache if cask.version == :latest
    {snip... rest of code as already exists)
  end
```

**Comment by vitorgalvao** [comment]
Sounds about right. Actually, we could [make the change further down](https://github.com/caskroom/homebrew-cask/blob/3ddc3cd9b0fd944fb33371a6c9bc3128e282409f/lib/hbc/download.rb#L21) to `downloader.clear_cache if force || cask.version == :latest`.

**Comment by adityadalal924** [comment]
Opened up a PR, do any tests need to be written?

**Comment by vitorgalvao** [comment]
Shouldn’t be needed, but always a good idea to let @jawshooah have a look.
