### ISSUE TITLE
`:optional` and `:recommended` installs

### ISSUE THREAD

**Issue by joeyhoer** [caskroom/homebrew-cask#13230]
Some applications provide optional binary installs (e.g. [Kaleidoscope's `ksdiff`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/kaleidoscope.rb), [Github Desktop's `github`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/github-desktop.rb)), while others install multiple GUI apps (e.g. [NanoStudio](https://github.com/caskroom/homebrew-cask/blob/master/Casks/nanostudio.rb)).

Cask provides `--no-binaries` which will skip symlinking *all* executable binaries into `/usr/local/bin`. But offers no other methods to specify if any of these additional apps/binaries/tools should be installed.

Homebrew uses `:optional` and `:required` to denote special build actions, available via `--with-` and `--without-`. It would be great if Cask could reproduce this functionality, giving a little more control over what is installed.

Possibly related to #2992.

**Comment by vitorgalvao** [comment]
#2992 already covers most of this. As for using only some of a type of artifact, definitely not, at least for now. First we’ll need to [fix how we install stuff](https://github.com/caskroom/homebrew-cask/issues/13201), and only then we can think of something like this. It is a very niche request, though, and I’ve never seen any interest whatsoever from the core team or any user, so even in the future it’s unlikely it’ll be done without a PR.
