### ISSUE TITLE
/usr/local/bin/brew-cask: line 13: set pipefail: invalid option name

### ISSUE THREAD

**Issue by enviousvanity** [caskroom/homebrew-cask#13238]
Please help:

```
elinda:~ Mom$ brew cask
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ brew uninstall brew-cask
Uninstalling /usr/local/Cellar/brew-cask/0.56.0... (2802 files, 11M)
Belinda:~ Mom$ brew install caskroom/cask/brew-cask
==> Installing brew-cask from caskroom/homebrew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Updating /Library/Caches/Homebrew/brew-cask--git
==> Checking out tag v0.56.0
/usr/local/Cellar/brew-cask/0.56.0: 2802 files, 11M, built in 16 seconds
Belinda:~ Mom$ brew cask install wine
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ brew cask help
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ brew cask list
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ brew cask options
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ brew cask
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ brew brew cask
Error: Unknown command: brew
Belinda:~ Mom$ brew brew cask options
Error: Unknown command: brew
Belinda:~ Mom$ cask options
  File "/usr/local/bin/cask", line 101
    return tuple(int(part) for part in version_string.split('.'))
                             ^
SyntaxError: invalid syntax
Belinda:~ Mom$ brew cask doctor
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ echo $HOMEBREW_CASK_OPTS

Belinda:~ Mom$ brew cask list
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$    
```

**Comment by scribblemaniac** [comment]
There's quite a few things wrong here. Here's a few to start you off:
1. You need to have [homebrew](http://brew.sh/) installed for homebrew cask to work.
2. Once you have finished 1, run `brew install caskroom/cask/brew-cask` to install homebrew cask. Don't try and build it from source.
3. Use `brew help` and `brew cask help` to see what kind of commands you can run.

**Comment by enviousvanity** [comment]
i have homebrew installed i believe. not a super current version...i only have mac os x 10.4

Belinda:~ Mom$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew
HEAD: 322c5261dae73268826789d82bb0f79e9e2e01e7
Last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 32-bit g4e
OS X: 10.4.11-Power Macintosh
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
Clang: N/A
X11: N/A
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.3/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
Java: N/A
Belinda:~ Mom$

**Comment by scribblemaniac** [comment]
This is probably an issue with the fact that you have a PPC computer or that your OS is really out of date. Perhaps someone else will have some suggestions for you.

**Comment by enviousvanity** [comment]
X11: N/A
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.3/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
Java: N/A
Belinda:~ Mom$ brew cask help
/usr/local/bin/brew-cask: line 13: set: pipefail: invalid option name
Belinda:~ Mom$ brew brew cask help
Error: Unknown command: brew
Belinda:~ Mom$ brew install caskroom/cask/brew-cask
Warning: caskroom/cask/brew-cask-0.56.0 already installed
Belinda:~ Mom$

**Comment by enviousvanity** [comment]
Yeah i was assuming soo...all this just to install wine =P

**Comment by scribblemaniac** [comment]
If that is your end goal, you can try building it with `homebrew install wine`

**Comment by scribblemaniac** [comment]
In fact, we don't even have a wine cask here.

**Comment by vitorgalvao** [comment]
@enviousvanity Please follow [this](https://github.com/caskroom/homebrew-cask#reporting-bugs) when posting bugs. Posting so much in a row and without enclosing your code makes it really hard to help you.

@scribblemaniac is correct, so closing this.
