### ISSUE TITLE
Support external commands

### ISSUE THREAD

**Issue by szhu** [caskroom/homebrew-cask#13262]
It would be nice if Homebrew Cask could support external commands, so that a command named `brew-cask-extcommand` can be invoked using `brew cask extcommand`.

This is something that Git and [Homebrew](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/External-Commands.md) support.

Some previous discussion of this is starting at https://github.com/caskroom/homebrew-cask/issues/13256#issuecomment-130907865.

**Comment by jawshooah** [comment]
This functionality is [already available](https://github.com/caskroom/homebrew-cask/blob/22009279693c55d7eb00f0b85b8b2f8b062fcd21/doc/hacking.md#external-commands) ([example](https://github.com/caskroom/homebrew-cask/blob/22009279693c55d7eb00f0b85b8b2f8b062fcd21/developer/examples/brewcask-doutdated.rb))

**Comment by szhu** [comment]
Oh, I see. Why `brewcask` and not `brew-cask`? I think having them prefixed with `brew-cask` will make them more discoverable, since `brew cask` itself is `brew-cask`.

**Comment by scribblemaniac** [comment]
It's probably so that it's unambiguous whether something like `brew-cask-command` is referring to `brew cask-command` or `brew cask command`.

**Comment by szhu** [comment]
That makes sense. Thanks!
