### ISSUE TITLE
Force checksums by default and explicitly force users to agree to insecure install

### ISSUE THREAD

**Issue by pydolan** [caskroom/homebrew-cask#13319]
I noticed that some of the software I'm installing with Cask is downloaded over HTTP, so that got me curious about checksumming of downloads.  I was relieved to see that sha256 checksumming is recommended for downloads, but I am worried about this `:no_check` feature that, assuming my understanding is correct, allows packagers to skip the checksumming of downloaded files.

I understand that there is a use case for this `:no_check` feature and that using checksums is the Cask recommended process, but this still seems like something that should be more transparent to the Cask users. 

Assuming my understanding above is correct and that there is not already an explicit opt-in to doing the install, I suggest forcing users to agree to the installation (e.g., "Warning: you are about to install a package that lacks a checksum from the developer. This can be a problem for reasons X, Y and Z; Are you sure you want to continue? y/n (default: n):").

Thoughts?

**Comment by vitorgalvao** [comment]
There’s already an issue on this. Apologies for not linking you to it, but I’m on a phone.
