### ISSUE TITLE
Install iexplorer but curl error

### ISSUE THREAD

**Issue by JohnHwee** [caskroom/homebrew-cask#13318]
```
 ~/ brew cask install iexplorer
==> Satisfying dependencies
complete
==> Downloading https://www.macroplant.com/release/iExplorer-3.7.7.0.dmg

curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Error: Download failed on Cask 'iexplorer' with message: Download failed: https://www.macroplant.com/release/iExplorer-3.7.7.0.dmg
```

**Comment by adityadalal924** [comment]
Do a `brew cask update` and `brew doctor`, I see no errors:

    [~] > brew cask install iexplorer
    ==> Satisfying dependencies
    complete
    ==> Downloading https://www.macroplant.com/release/iExplorer-3.7.7.0.dmg
    ######################################################################## 100.0%
    ==> Symlinking App 'iExplorer.app' to '/Users/aditya/Applications/iExplorer.app'
    🍺  iexplorer staged at '/opt/homebrew-cask/Caskroom/iexplorer/3.7.7.0' (641 files, 22M)


Also my curl (`brew install curl`) version is: `curl 7.43.0 (x86_64-apple-darwin14.0) libcurl/7.43.0 SecureTransport zlib/1.2.5`

**Comment by vitorgalvao** [comment]
@Johnhwee If the issue persists, please open a new issue but [follow the procedure](https://github.com/caskroom/homebrew-cask/blob/master/README.md#reporting-bugs).

Also, if you have a custom `.curlrc`, that is likely the cause of the issue.
