### ISSUE TITLE
Switch Calibre download host to main

### ISSUE THREAD

**Issue by 1zaman** [caskroom/homebrew-cask#13321]
Because of a [report](https://github.com/caskroom/homebrew-cask/issues/9934) of extremely slow download speed from the main download host for Calibre (calibre-ebook.com), the Cask was [switched](https://github.com/caskroom/homebrew-cask/issues/9942) to use the Github mirror, which uses a versioned URL. Unfortunately, Github invalidates previous URLs as soon as a new update is posted (each week), so it [breaks regularly](https://github.com/caskroom/homebrew-cask/issues/10039) until the Cask is updated.

While testing the main download host now, I did not encounter any issues. It loads at full speed for me. It may be that the issues have been fixed. This should be verified, and until the appcast feature can be implemented, we should revert back to the main unversioned host URL. I can open a pull request on this pending verification if desired.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/commit/918a5a259545cdd33b4aed0a393092a3fd36c7e7,
