### ISSUE TITLE
github-desktop fails to install

### ISSUE THREAD

**Issue by fculpo** [caskroom/homebrew-cask#13322]
Tried to install the Github-Desktop cask recently, and here is the result :

> brew cask install github-desktop                                                                                                                                                            [10:11:44]
==> Downloading https://d4hwcs1zqtwzs.cloudfront.net/mac/GitHub%20Desktop%20210.zip
######################################################################## 100.0%
==> Symlinking App 'GitHub Desktop.app' to '/Users/fabien/Applications/GitHub Desktop.app'
==> Symlinking Binary 'github_cli' to '/usr/local/bin/github'
Error: Permission denied - /usr/local

**Comment by adityadalal924** [comment]
Do a `brew cask update` and `brew doctor`, I see no errors:

    [~] > brew cask install github-desktop
    ==> Downloading https://d4hwcs1zqtwzs.cloudfront.net/mac/GitHub%20Desktop%20210.
    ######################################################################## 100.0%
    ==> Symlinking App 'GitHub Desktop.app' to '/Users/aditya/Applications/GitHub De
    ==> Symlinking Binary 'github_cli' to '/usr/local/bin/github'
    🍺  github-desktop staged at '/opt/homebrew-cask/Caskroom/github-desktop/210' (1405 files, 59M)

**Comment by vitorgalvao** [comment]
@fculpo If the issue persists, please open a new issue but [follow the procedure](https://github.com/caskroom/homebrew-cask/blob/master/README.md#reporting-bugs).

**Comment by cfont** [comment]
I has not having this exact problem but was getting errors trying to install github-desktop today. After brew update && brew upgrade && brew doctor then the install worked fine for me tonight. More of an FYI than useful, helpful information for your issue probably.
