### ISSUE TITLE
Firefox and unverified add-ons, esp 1Password

### ISSUE THREAD

**Issue by slambert** [caskroom/homebrew-cask#13351]
Hi, I’ve got Firefox and 1Password installed with cask. I’ve unchecked the “Verify browser code signature” option in 1password and things are mostly working well. 

My issues is that every time I restart my machine, Firefox seems to not recognize the 1password extension. When I look at my installed add ons is shows many are “unverified” and I have been experiencing some weirdness there. If I re-install everything is good.

I looked through the issues and did some searches online, but haven’t found anything. Any ideas?

**Comment by vitorgalvao** [comment]
Look at the `google-chrome` cask: the `caveat` is the same as the issue here. #13201 will fix this, though.
