### ISSUE TITLE
Heads-Up: Current VirtualBox version (5.0.2-102096) has a known issue with starting certain VM's

### ISSUE THREAD

**Issue by rye** [caskroom/homebrew-cask#13364]
I ran into this problem yesterday evening.  Installing VirtualBox via the following command works fine,

```bash
$ brew cask install virtualbox
```

but a known issue with version 5.0.2 prevents certain VM's from being launched.  I'm unsure as to which types specifically are affected, but all of my headless VM's (installed through Vagrant) are unable to be launched, as they produce the following error on startup:

```
Failed to load VMMR0.r0 (VERR_VMM_SMAP_BUT_AC_CLEAR).


Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}
```

This is a known issue with version 5.0.2, and has been reported as [ticket #14412](https://www.virtualbox.org/ticket/14412) at VirtualBox.  Evidently, this has been fixed in the latest SVN, and should be released with version 5.0.3.

I'm not sure if there's anything we can do to remedy the problem right now, but, at least, when 5.0.3 is released, updating the formula ASAP would be nice.

**Comment by vitorgalvao** [comment]
This is a virtualbox bug, not a homebrew-cask one.
