### ISSUE TITLE
callnote-premium formulae error

### ISSUE THREAD

**Issue by Drewshg312** [caskroom/homebrew-cask#13380]
Hi! While installing callnote-premium getting this:

    $ brew cask install callnote-premium
    ==> Downloading http://callnote.kandasoft.com/callnote-premium-install-2.3.7.pkg
    Already downloaded: /Library/Caches/Homebrew/callnote-premium-2.3.7.pkg
    ==> Running installer for callnote-premium; your password may be necessary.
    ==> Package installers may write to any location; options such as --appdir are ignored.
    ==> installer: Package name is Callnote
    ==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
    Error: Command failed to execute!
    
    ==> Failed command:
    ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/usr/local/Caskroom/callnote-premium/2.3.7/callnote-premium-install-2.3.7.pkg>", "-target", "/"]
    
    ==> Output of failed command:
    installer: Package name is Callnote
    installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
    
    
    ==> Exit status of failed command:
    #<Process::Status: pid 15308 exit 1>

Any ideas?

**Comment by vitorgalvao** [comment]
[Reporting bugs](https://github.com/caskroom/homebrew-cask/blob/master/README.md#reporting-bugs).

**Comment by Ngrd** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/13381. Feel free to reopen this issue if the problem persists.
