### ISSUE TITLE
Error installing nomacs

### ISSUE THREAD

**Issue by samspo** [caskroom/homebrew-cask#13415]
Not able to install nomacs

> brew cask install nomacs
> ==> Downloading http://downloads.sourceforge.net/sourceforge/nomacs/nomacs-2.4.5
######################################################################## 100,0%
> Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/nomacs/2.4.5/nomacs.app'

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/13499.
