### ISSUE TITLE
displaylink cask broken

### ISSUE THREAD

**Issue by greygore** [caskroom/homebrew-cask#13432]
Apparently the download page changed, because the file I've downloaded is `/Library/Caches/Homebrew/displaylink-2.3.php`.

According to [the cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/displaylink.rb), it's trying to download:
```
  url 'http://www.displaylink.com/support/file.php',
      :data => {
        'file' => "DisplayLink_Mac_#{version}.dmg",
        'folder' => 'publicsoftware'
      },
      :using => :post
```
But it looks like they've changed [their download page](http://www.displaylink.com/downloads/mac_downloads.php) to pull from:
```
  url 'http://www.displaylink.com/downloads/file.php',
      :data => {
        'file' => "DisplayLink_OSX_#{version}.dmg",
        'folder' => 'publicsoftware',
        'id' => '420'
      },
      :using => :post
```

Additionally the version has been bumped up to version 2.4 from 2.3. I don't have the new sha handy or I would put that here as well.

**Comment by greygore** [comment]
I was able to get the Cask to work locally by making the changes above, bumping the version to `2.4` and using the sha `e3972ca00836c5a7ae03f85f0e43b7069673b3f3d9d30d6c68175ea077045637`

**Comment by Ngrd** [comment]
Also got it working but it seems that you were one step ahead of me and also solved the issue by yourself. Well done. The fix however already was submitted in PR https://github.com/caskroom/homebrew-cask/pull/13433.
