### ISSUE TITLE
osxfuse cask installs unstable beta release

### ISSUE THREAD

**Issue by fd0** [caskroom/homebrew-cask#13441]
in https://github.com/caskroom/homebrew-cask/commit/e1f8d0cdb64d0c01f0f90d6992976d857e668c18, the osxfuse version was updated from 2.8.0 (the latest stable) to 3.0.4 which has severe bugs, e.g. https://github.com/osxfuse/osxfuse/issues/229 and might even have data loss. Is there any chance you can roll back to version 2.8.0?

ping @Ngrd

**Comment by Ngrd** [comment]
Thank you. I also fully agree with you, so it was rolled back to v2.8.0 in https://github.com/caskroom/homebrew-cask/pull/13442. Let's hold the v3.0.4 until it becomes more stable.

**Comment by fd0** [comment]
cool, thanks!
