### ISSUE TITLE
uninitialized constant Requirement

### ISSUE THREAD

**Issue by bigtunacan** [caskroom/homebrew-cask#13459]
Receiving an error trying to install on Mac OSX Mavericks.

    brew install caskroom/cask/brew-cask                                                                                  
    Error: uninitialized constant Requirement
    Please report this bug:
        https://github.com/Homebrew/homebrew/wiki/troubleshooting
        /usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:10:in `<main>'

**Comment by vitorgalvao** [comment]
Have you done the steps in https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting?

This isn’t a homebrew-cask problem, it isn’t even installed yet.
