### ISSUE TITLE
Navicat checksums need to be updated

### ISSUE THREAD

**Issue by underyx** [caskroom/homebrew-cask#13511]
`brew cask install navicat-for-postgresql` gave me

```
Error: sha256 mismatch
Expected: ddc4dda1d15bc45550e10fc80c6a86f147dab8485198488f90ea3000045d5c79
Actual: b0050f2bb7cd583749fa5abfc155a2df6f6ed24378b3c69cab00e5e14c3032be
File: /Library/Caches/Homebrew/navicat-for-postgresql-11.1.13.dmg
```

on two separate times. They probably updated the hosted binaries without bumping their version. I'll send a PR for this in a day or two if no one else will update the checksums by then.

**Comment by vitorgalvao** [comment]
@underyx Still planning on sending the PR?

**Comment by underyx** [comment]
Yep, up at #13574 now.
