### ISSUE TITLE
Alfred compatibility: suggest resetting search scopes

### ISSUE THREAD

**Issue by olivierlefloch** [caskroom/homebrew-cask#13519]
Hi, I'm a long time Alfred user and a recent `brew cask` user, and couldn't figure out why Alfred didn't see the `brew cask` apps. I then ran `brew cask help`, followed by `brew cask alfred`, which suggested that Alfred now had default search scopes for this.

I think I updated search scopes in the past though, and I had to Reset Search Scopes for the automatic discovery to work. You may want to add that to the output of `brew cask alfred`.

**Comment by vitorgalvao** [comment]
No. `brew cask alfred` is deprecated. This will become less of an issue as time passes, so we won’t build workarounds for it.
