### ISSUE TITLE
`brew cask list` in a dir containing installed cask file(s) results in file does not exist error

### ISSUE THREAD

**Issue by IshmaelYavitz** [caskroom/homebrew-cask#13525]
I try to use homebrew-cask to install all software.  So I create cask files locally.

If I do a `brew cask list` from a directory containing one of those files, and the cask is still installed, it fails.  If do it from a directory that doesn't contain any cask files for installed programs, it succeeds.

In the failure case, `brew cask` appears to be looking for a file with the correct name but without the `.rb` extension.

Demo:

     »  (729) 2015-08-31@21:25:46 ishmael@ishcomp-mbp ~/ish-casks> brew cask list
     Error: File '/Users/ishmael/ish-casks/messenger_for_mac_0_1_4' does not exist
    
     »  (730) 2015-08-31@21:26:13 ishmael@ishcomp-mbp ~/ish-casks> ls -la Messenger*
     -rw-r--r--  1 ishmael  staff  458 Aug 30 16:46 Messenger_for_Mac_0_1_4.rb
    
     »  (737) 2015-08-31@21:28:00 ishmael@ishcomp-mbp ~/ish-casks> cat Messenger_for_Mac_0_1_4.rb
     cask :v1 => 'Messenger_for_Mac_0_1_4' do
       version '0.1.4'
       sha256 '1b8ea3554aff8a632eb4e39c1b1a2b04e92dfb3a2cc53a805218c3074fac240f'
    
       url "http://fbmacmessenger.rsms.me/dist/Messenger-0.1.4.1440786644-f3436781b1e02ea1.zip"
     # appcast 'http://brawersoftware.com/appcasts/feeds/ubar/ubar2.xml'
       name 'Messenger for Mac'
       homepage 'http://fbmacmessenger.rsms.me/'
     # license :commercial
    
       app 'Messenger.app'
    
     # depends_on :macos => '>= :mavericks'
    end
    
    #eof
    
     »  (731) 2015-08-31@21:26:19 ishmael@ishcomp-mbp ~/ish-casks> cd ..
    
     »  (732) 2015-08-31@21:26:21 ishmael@ishcomp-mbp ~> brew cask list
    bettertouchtool
    java6
    paintbrush
    dterm
    karabiner
    sizeup
    emacs-mac
    keyremap4macbook-mountainlion
    sourcetree
    firefox
    macintosh-explorer
    steam
    honer
    messenger_for_mac_0_1_4(!)
    sublime-text3
    hyperdock
    microsoft-intellitype
    ubar_2_4_9(!)
    intellij-idea-cenumlock_1_0_3(!)
    vlc
    
     »  (733) 2015-08-31@21:26:25 ishmael@ishcomp-mbp ~>
     

(I doctored the successful output of `brew cask list` to put individual casks on their on line.)

Output of `brew cask list --debug`: https://gist.github.com/IshmaelYavitz/bc360e9baade3651a6af

**Comment by vitorgalvao** [comment]
Closing as I’ll link to it in a single issue pointing out `brew cask list` bugs.
