### ISSUE TITLE
Wrong sha256 for freesmug-chromium

### ISSUE THREAD

**Issue by aziz** [caskroom/homebrew-cask#13576]
```
brew cask install freesmug-chromium
==> Downloading http://downloads.sourceforge.net/sourceforge/osxportableapps/Chromium_OSX_45.0.2454.85.dmg
Already downloaded: /Library/Caches/Homebrew/freesmug-chromium-45.0.2454.85.dmg
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 489f42d85e9a173dfe7b2c2e2c6ff94a85e34292034f196657f8c1cd7a61bd92
Actual: e2645febaec8a7f23e3e1cf7a95fb9134f91d93efdc6ca2bd9ef00292cc16977
File: /Library/Caches/Homebrew/freesmug-chromium-45.0.2454.85.dmg
To retry an incomplete download, remove the file above.
```

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.

**Comment by aziz** [comment]
I just need some confirmation that it's not my own issue. I can definitely send a pull request.
Just confirm that the sha you see when trying to download it the same as I submitted above: 
`e2645febaec8a7f23e3e1cf7a95fb9134f91d93efdc6ca2bd9ef00292cc16977`

**Comment by Ngrd** [comment]
There is nothing wrong with the cask. The current cheksum for *Chromium_OSX_45.0.2454.85.dmg* is:
```
489f42d85e9a173dfe7b2c2e2c6ff94a85e34292034f196657f8c1cd7a61bd92
```

**Comment by vitorgalvao** [comment]
Thank you for checking, @Ngrd.

@aziz In these cases, just send the PR: it’s faster than having an extra issue and going back and forth. Discussing with the PR open is always better. Making the PR is also faster than writing the issue.
