### ISSUE TITLE
Fail to install squirrel

### ISSUE THREAD

**Issue by Q-E-D** [caskroom/homebrew-cask#13584]
* Command: `brew install`
* Output:

        Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/squirrel.rb'
        Please report this bug:
            https://github.com/caskroom/homebrew-cask/issues
        <main>:6:in `name'
        <main>:6:in `<class:Squirrel>'
        <main>:in `<main>'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:55:in `eval'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:52:in `load'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/tapped.rb:28:in `load'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask.rb:123:in `load'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:17:in `each'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:17:in `install_casks'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:6:in `run'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:81:in `run_command'
        /usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:121:in `process'
        /usr/local/bin/brew-cask.rb:42:in `<top (required)>'

* System: OSX 0.10.5
* Ruby: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
* squirrel.rb:

        cask :v1 => 'squirrel' do
            version '0.9.26.2'
            sha256 '7ba8f934f8d4fe1d42c944ea0771f1a54ed558dd65ea558c4ba4d203505bc130'

            # bintray.com is the official download host per the vendor homepage
            url "https://dl.bintray.com/lotem/rime/Squirrel-#{version}.zip"
            name 'Squirrel'
            homepage 'http://rime.im/download/'
            license :gpl

            depends_on :macos => '>= :lion'

            pkg 'Squirrel.pkg'

            uninstall :pkgutil => 'com.googlecode.rimeime.Squirrel.pkg',
                :delete => '/Library/Input Methods/Squirrel.app'
        end

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

See also #10224.
