### ISSUE TITLE
Caskroom/cask/retroarch version number is out of date

### ISSUE THREAD

**Issue by sylverpyro** [caskroom/homebrew-cask#13596]
In Casks/retroarch.rb :

version '1.0.0.2' is no longer the latest stable.  
The URL schema in the cask also appears in need of updating: 
url "http://buildbot.libretro.com/stable/osx-x86_64/RetroArch-OSX10.7-x86_64-v#{version}.zip"

Current stable is at http://buildbot.libretro.com/stable/1.2.2/osx-x86_64/RetroArch-OSX10.7-x86_64-v1.2.2.zip

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.

**Comment by vitorgalvao** [comment]
Will be fixed soon.
