### ISSUE TITLE
Failure while executing: git clone --depth 1 --branch v0.56.0 https://github.com/caskroom/homebrew-cask.git /Library/Caches/Homebrew/brew-cask--git

### ISSUE THREAD

**Issue by dhawal55** [caskroom/homebrew-cask#13598]
brew install brew-cask                   
==> Installing brew-cask from caskroom/homebrew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Error: Failed to download resource "brew-cask"
Failure while executing: git clone --depth 1 --branch v0.56.0 https://github.com/caskroom/homebrew-cask.git /Library/Caches/Homebrew/brew-cask--git

I'm using OS X Yosemite and rbenv to manage my ruby versions. Ruby version is set to 2.2.2

**Comment by dhawal55** [comment]
Executing the git clone command directly works fine. I think brew is using ruby to run the git clone and somehow erroring out.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/10041.

**Comment by dhawal55** [comment]
Thank you. The solution mentioned by swyckoff in #10041 worked.
