### ISSUE TITLE
installer :script should make its target executable in advance

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#13607]
Just came across this while working on [anaconda](https://github.com/caskroom/homebrew-cask/pull/13362). The `installer :script` target wouldn’t run due to it not having permission to execute. [`set_permissions`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#flight-mini-dsl) doesn’t work to fix this because the soonest it’s available is `postflight`, and this needed to be `preflight`. [The old way had to be used](https://github.com/caskroom/homebrew-cask/blob/a5e7b4345a2c947a198db21448c4e600a7c0a567/Casks/anaconda.rb#L13#L15).

Either way, it should be the responsibility of `installer :script` to make sure its target can be run.

**Comment by jawshooah** [comment]
While I agree with making installer scripts executable by default, I think the `set_permissions` and `set_ownership` methods should be available in the `preflight` block regardless. PR incoming.
