### ISSUE TITLE
Make `:sudo` in `installer/uninstall :script` 'false' by default

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#13608]
Currently [`installer :script`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#installer-script) uses `sudo` by default. This seems wrong, as contributors will likely set as few options as possible to have the cask work (as they should) and hence scripts that could otherwise be run without extended privileges will be anyway. The reverse should be true: if a contributor notices the installations breaks and sees extended privileges are needed, those should be set then.

`sudo` should be set when needed, not unset when not needed.

---

Lists of casks ([from the next post](https://github.com/caskroom/homebrew-cask/issues/13608#issuecomment-137973136), with fixes) with an (un)install :script, but no sudo line explicitly defined. Should be ticked as they are verified.
- [x] [`amazon-cloud-drive`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/amazon-cloud-drive.rb)
- [x] [`amazon-music`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/amazon-music.rb)
- [x] [`ax88179`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ax88179.rb)
- [x] [`ax88772`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ax88772.rb)
- [x] [`blast2go`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/blast2go.rb)
- [x] [`cacoo-ninja`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cacoo-ninja.rb)
- [x] [`drobo-dashboard`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/drobo-dashboard.rb)
- [x] [`fitbit-connect`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fitbit-connect.rb)
- [x] [`gobbler`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/gobbler.rb)
- [x] [`jenkins`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jenkins.rb)
- [x] [`lastpass`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/lastpass.rb)
- [x] [`logitech-control-center`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-control-center.rb)
- [x] [`logitech-options`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-options.rb)
- [x] [`logmein-hamachi`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logmein-hamachi.rb)
- [x] [`paye-tools`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/paye-tools.rb)
- [x] [`private-internet-access`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/private-internet-access.rb)
- [x] [`scratch`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/scratch.rb)
- [x] [`sencha`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sencha.rb)
- [x] [`sophos-anti-virus-home-edition`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sophos-anti-virus-home-edition.rb)
- [x] [`totalspaces`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/totalspaces.rb)
- [x] [`vuze`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vuze.rb)
- [x] [`xampp`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/xampp.rb)

---

To verify:

To check their need for it now, you’d need to change each cask to _explicitly_ use `:sudo => false`, and install/uninstall that. If everything goes right, `:sudo => false` should stay; if something goes wrong, it should be changed to `:sudo => true` and installed/uninstalled again (to make sure the error was really due to `sudo`, and not some change in the package, since the last time).

---

Roadmap:
- [x] Make every cask with this use case use `:sudo` explicitly (no matter if `true` or `false`).
- [x] Change the rule in the core to make `false` the default.
- [x] Delete `:sudo => false` from the casks that have it.

**Comment by adityadalal924** [comment]
Lists of casks that would need to be modified (casks with no sudo line)

```text
acquia-dev-desktop
amazon-cloud-drive
amazon-music
ax88179
ax88772
blast2go
cacoo-ninja
drobo-dashboard
fitbit-connect
gobbler
google-cloud-sdk
jdownloader
jenkins
lastpass
logitech-control-enter
logitech-options
logmein-hamachi
paye-tools
private-internet-access
scratch
sencha
sophos-anti-virus-home-edition
splice
totalspaces
vuze
xampp
```

**Comment by Miladiir** [comment]
I want to highlight this problem further. Especially jdownloader previously bundled malware/adware on windows. Elevated privileges seems like a really bad idea for that program.

**Comment by vitorgalvao** [comment]
@adityadalal924 Changed “would” to “could”, and copied your list to the top post (thank you for making it).

**Comment by adityadalal924** [comment]
@vitorgalvao How would I go about verifying that sudo is (or isn't) required?

**Comment by vitorgalvao** [comment]
@adityadalal924 We should implement this in three phases:

1. Make every cask with this use case use `:sudo` explicitly (no matter if `true` or `false`).
2. Change the rule in the core to make `false` the default.
3. Delete `:sudo => false` from the casks that have it.

To check their need for it now, you’d need to change each cask to *explicitly* use `:sudo => false`, and install/uninstall that. If everything goes right, `:sudo => false` should stay; if something goes wrong, it should be changed to `:sudo => true` and installed/uninstalled again (to make sure the error was really due to `sudo`, and not some change in the package, since the last time).

**Comment by adityadalal924** [comment]
@vitorgalvao I've done a few - care to take a quick look and make sure everything looks okay?

**Comment by vitorgalvao** [comment]
Everything looks fine.

It’s clear why `true` is the default, since most need it. Making sure we don’t use `sudo` needlessly still trumps that, I’d say.

**Comment by adityadalal924** [comment]
I've used the

```
  uninstall :script => { :executable => 'Uninstall.app/Contents/Resources/Scripts/__name__.sh',
                         :sudo => true },
```
construct a bit - would https://github.com/caskroom/homebrew-cask/issues/13607 fix that? (if and when it's fixed?)

**Comment by vitorgalvao** [comment]
In what manner? They aren’t related.

**Comment by adityadalal924** [comment]
As in, it shouldn't be necessary for me to always use the `:executable` block for a script, they should automatically be executable.

(I saw it in one Cask, so I've been using that style - but I'm not sure if it's *actually* required.)

**Comment by vitorgalvao** [comment]
Ah, I see where the confusion is. `executable` does not make scripts executable. It just says “this is the script to run”, and needs to be used when the script needs [extra commands](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#summary-of-keys). It has nothing to do with permissions.

**Comment by vitorgalvao** [comment]
All casks on the list are now checked and done.

**Comment by Eitot** [comment]
@vitorgalvao: Does this behaviour also apply to `brew cask zap`? It seems that this command always requires sudo, regardless whether the files to be zapped can be deleted with just user permissions (e.g. files in `~/Library`).

**Comment by vitorgalvao** [comment]
This has nothing to do with `zap`. This is only for things where `sudo` is given through a flag.

**Comment by vitorgalvao** [comment]
All PRs to finish this already open.

**Comment by sebastienbarre** [comment]
I believe this is breaking `google-cloud-sdk`.
 
I'm getting dozens and dozens of:
```
==> chmod: Unable to change file mode on /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/th...
==> chmod: Unable to change file mode on /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/VERSION: Operation
==> Using sudo to gain ownership of path '/usr/local/Caskroom/google-cloud-sdk/latest'
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames (\"git-credential-gcloud\") /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/git-credential-gcloud.sh

==> Standard Output of failed command:


==> Standard Error of failed command:
xattr: [Errno 13] Permission denied: '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/git-credential-gcloud.sh'


==> Exit status of failed command:
#<Process::Status: pid 69886 exit 1>
Error: nothing to install
```
