### ISSUE TITLE
PhpStorm for OS X 10 Yosemite

### ISSUE THREAD

**Issue by hugoboos** [caskroom/homebrew-cask#13625]
Hi,

JetBrains provides a special build of PhpStorm for OS X 10 Yosemite, which includes Java 1.8.
See: https://www.jetbrains.com/phpstorm/download/.

Are there any plans to support this version?

**Comment by cprecioso** [comment]
It's already there, `brew cask install phpstorm-bundled-jdk`

**Comment by hugoboos** [comment]
I see, it is in the versions tap, that is why I didn't see it. My bad.

Thanks!
