### ISSUE TITLE
@path and unpack_dir in container code

### ISSUE THREAD

**Issue by cprecioso** [caskroom/homebrew-cask#13621]
Hi, I'm taking a look at the `gzip` container code, as I'm trying to get it to work without the `.gz` extension (so the `parse` cask doesn't make users install `unar`).

I'm trying to debug the `@path` and `unpack_dir` variables but `puts` in the `extract` block is not printing anything in the terminal when I try to install `parse`. These two variables are obvious at what they point, but if I need to debug other variables, how should I do it?

**Comment by cprecioso** [comment]
No one?

**Comment by vitorgalvao** [comment]
Pinging @jawshooah @ndr-qef @radeksimko.

**Comment by vitorgalvao** [comment]
@cprecioso Do you still have interest in this?

I’ll ping someone else that might help if you do, close if you don’t.
