### ISSUE TITLE
/usr/local/* isn't writeable after installing osxfuse

### ISSUE THREAD

**Issue by cprecioso** [caskroom/homebrew-cask#13631]
After installing osxfuse, `brew doctor` complains that
```
Warning: /usr/local/include isn't writable.

This can happen if you "sudo make install" software that isn't managed by
by Homebrew. If a formula tries to write a file to this directory, the
install will fail during the link step.

You should probably `chown` /usr/local/include

Warning: /usr/local/lib isn't writable.

This can happen if you "sudo make install" software that isn't managed by
by Homebrew. If a formula tries to write a file to this directory, the
install will fail during the link step.

You should probably `chown` /usr/local/lib

Warning: /usr/local/lib/pkgconfig isn't writable.

This can happen if you "sudo make install" software that isn't managed by
by Homebrew. If a formula tries to write a file to this directory, the
install will fail during the link step.

You should probably `chown` /usr/local/lib/pkgconfig
```

It seems to be the installer's fault. Is there any way to correct this after installing?

**Comment by cprecioso** [comment]
Edit: Also, the installer asks for a reboot, maybe that could be added as a `caveat`?

**Comment by cprecioso** [comment]
Edit 2: `sudo chown -R $(whoami) /usr/local` solves the problem

**Comment by vitorgalvao** [comment]
> Also, the installer asks for a reboot, maybe that could be added as a `caveat`?

[Can do](https://github.com/caskroom/homebrew-cask/blob/7fb617c0b96ebdaa932f76c118d518b4ba193c7a/Casks/eye-one-profiler.rb#L14#L16).

>  `sudo chown -R $(whoami) /usr/local` solves the problem

[Also prepared, there](https://github.com/caskroom/homebrew-cask/blob/c14a7940edc4f5e05cb45e498cb5fd798590c0cf/Casks/onlabs.rb#L15#L17).

Care to submit the PR?

**Comment by cprecioso** [comment]
`set_permissions` does `chmod`, is there an equivalent for `chown` or should I just `system "chown" ...`?

**Comment by vitorgalvao** [comment]
Apologies, I meant [this](https://github.com/caskroom/homebrew-cask/blob/56feb3f501ed3496c96c12c116fa8d51ca06af80/Casks/unifi-controller.rb#L12#L14).

[They’re all documented](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#flight-mini-dsl).

**Comment by vitorgalvao** [comment]
Closing in favour of #13632.
