### ISSUE TITLE
Google chrome autoupdate dos'nt work

### ISSUE THREAD

**Issue by ilyaskorik** [caskroom/homebrew-cask#13680]
I installed Chrome by Cask and noticed that it did not show it's new version in the "about application" page. Command "brew "update" also do not update this program automatically.

**Comment by vitorgalvao** [comment]
`brew update` updates cask (and formula) definitions, not applications themselves, we don’t have upgrade functionality yet. In addition, the only thing we do to Chrome is download it, if it is not updating correctly, the problem is in your setup, and unrelated to us.

**Comment by cebor** [comment]
same issue here, since i installed chrome via `brew cask` the autoupdate from chrome itself does not work anymore ...

**Comment by vitorgalvao** [comment]
Like I said before, we don’t do anything to Chrome, so the problem is in your setup.

Check your permissions. Perhaps their messed up and Chrome can’t download/write to the directory.
