### ISSUE TITLE
"Macupdate desktop" application can not see application installed through the cask

### ISSUE THREAD

**Issue by ilyaskorik** [caskroom/homebrew-cask#13681]
"Macupdate desktop" application can not see application installed through the cask. This is a big problem with the updates of installed software.

**Comment by vitorgalvao** [comment]
[Won’t be a problem in the future](https://github.com/caskroom/homebrew-cask/issues/13201). Also, why would you use both? If you’re using two package managers at the same time to manage the same time of programs, expect incompatibilities.

**Comment by ilyaskorik** [comment]
Because updating via the cask now are not working. 

I prefer to install a programs through the cask, I can automate this and use install script on different devices. However, auto-update, which does not work - making cask unnecessary.

It is sad.
