### ISSUE TITLE
Formula request: Sheepshaver

### ISSUE THREAD

**Issue by andreis** [caskroom/homebrew-cask#13712]
http://sheepshaver.cebix.net/

> SheepShaver
> An Open Source PowerMac Emulator

> What is SheepShaver?

> SheepShaver is a MacOS run-time environment for BeOS and Linux that allows you to run classic MacOS applications inside the BeOS/Linux multitasking environment. This means that both BeOS/Linux and MacOS applications can run at the same time (usually in a window on the BeOS/Linux desktop) and data can be exchanged between them. If you are using a PowerPC-based system, applications will run at native speed (i.e. with no emulation involved). There is also a built-in PowerPC emulator for non-PowerPC systems.

> SheepShaver is distributed under the terms of the GNU General Public License (GPL). However, you still need a copy of MacOS and a PowerMac ROM image to use SheepShaver. If you're planning to run SheepShaver on a PowerMac, you probably already have these two items.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-unofficial/pull/51
