### ISSUE TITLE
Devtools Tap

### ISSUE THREAD

**Issue by sagikazarmark** [caskroom/homebrew-cask#13726]
Hey there,

I created a custom tap for some sort of devtools. It can be found here:

https://github.com/sagikazarmark/homebrew-devtools

**Comment by vitorgalvao** [comment]
Appreciate the effort, but this is not the place to publicise it, particularly when the tap has only two apps *and* we have both in [caskroom/versions](https://github.com/caskroom/homebrew-versions), so I do not really see the point.

**Comment by sagikazarmark** [comment]
I pasted it based on https://github.com/caskroom/homebrew-cask/blob/master/doc/alternate_cask_taps.md#instructions.

I wasn't aware of the versions tap.

**Comment by vitorgalvao** [comment]
Again, appreciate the effort, but as you can see from the page, taps publicised there are there exactly because they could not be accepted in ours, which is far from the case here.

**Comment by sagikazarmark** [comment]
Already removed the tap, as it really makes no sense. However I feel the phpstorm bundle might be accepted in the "main" tap, as it is a first class sitizen fron JetBrains.

**Comment by vitorgalvao** [comment]
No. [The other version sits on the main tap](https://github.com/caskroom/homebrew-cask/blob/master/Casks/phpstorm.rb).
