### ISSUE TITLE
Formula update request: MacTex

### ISSUE THREAD

**Issue by DelightRun** [caskroom/homebrew-cask#13728]
MacTex's download url has been changed, use `brew cask install mactex` will get a 404 error. Please update the download url of `MacTex`

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.

**Comment by adityadalal924** [comment]
The download url hasn't been changed, there are just [multiple mirrors](https://tug.org/mactex/mirrorpage.html). Not sure if one is preferred over the other, but `brew cask install mactex` works fine for me. 

It downloads from `http://mirror.ctan.org/systems/mac/mactex/mactex-#{version}.pkg`, which seems like a meta URL that automatically handles redirection/load balancing.

**Comment by vitorgalvao** [comment]
Can also confirm it works for me. Thank you for looking into it, @adityadalal924.
