### ISSUE TITLE
GPGTools download failed

### ISSUE THREAD

**Issue by sagikazarmark** [caskroom/homebrew-cask#13727]
GPGTools install fails with the following message:

curl: (22) The requested URL returned error: 503 Service Unavailable
Error: Download failed on Cask 'gpgtools' with message: Download failed: https://releases.gpgtools.org/GPG_Suite-2015.08.dmg

**Comment by sagikazarmark** [comment]
There might be an issue with the server, after the 10th try it worked.

**Comment by vitorgalvao** [comment]
Seems like that’s the case. Working for me as well.
