### ISSUE TITLE
Error uninstalling XQuartz

### ISSUE THREAD

**Issue by wkschwartz** [caskroom/homebrew-cask#13814]
I had installed xquartz from sudo because I couldn't get it to work without sudo from either my non-admin or my admin account. Now when I try to uninstall I keep getting the following error. I couldn't find anything on Google about this.

If I can't get Homebrew Cask to do the uninstall for me, should I follow these instructions? https://xquartz.macosforge.org/trac/wiki/X11-UsersFAQ#UninstallSnowLeopardorLater

```
admin$ brew cask uninstall xquartz
==> Running uninstall process for xquartz; your password may be necessary
==> Removing launchctl service org.macosforge.xquartz.startx
Password:
==> Quitting application ID org.macosforge.xquartz.X11
==> 36:107: execution error: An error of type -10810 has occurred. (-10810)
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/bin/osascript", "-e", "tell application \\\"System Events\\\" to count processes whose bundle identifier is \\\"org.macosforge.xquartz.X11\\\""]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 4385 exit 1>
```

**Comment by vitorgalvao** [comment]
If you want to just uninstall it now, then yes, you can use that process.

I can’t reproduce your issue, so please follow [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) and open a new issue (following the instructions) if the problem persists.
