### ISSUE TITLE
Help adding a new cask.

### ISSUE THREAD

**Issue by chrisRidgers** [caskroom/homebrew-cask#13874]

**Comment by chrisRidgers** [comment]
Well as I can't cancel this issue:

I want to add a new cask, but I'm not sure of the process to do so.  Can someone please advise?

**Comment by victorpopkov** [comment]
Thank you for the willing to contribute. You can follow this article: [Contributing to Open Source on GitHub](https://guides.github.com/activities/contributing-to-open-source/), especially the "Pull Request" part at the end. Feel free to ask any additional questions if they occur. We are all here to help and you can always open a new PR if something goes wrong.

**Comment by chrisRidgers** [comment]
Hi,

The application / cask I want to add is the minecraft-server application.  I'm using the minecraft.rb as a guide, and have changed the link to point at the server apps .jar archive.

I'm guessing that when installed it will download the .jar archive into my home/Applications directory.

From here what kind of control do I have over the application?  As part of the initial run process the app will usually create some conf files for editing, but I'd rather it not have those spawn in my applications directory.

Can I configure the download to relocate to home folder/Applications/Minecraft Server/minecraft-server.jar ?

Ideally I'd then configure the install to run the app once it has finished downloading to generate the conf files: or I'd provide a caveat warning explaining the process.

**Comment by victorpopkov** [comment]
For this case you most likely will need to use a little bit hackish workaround by creating the run script in `postflight` or `preflight` stanzas and link it to `binary`. Take a look at [jenkins.rb](https://github.com/caskroom/homebrew-cask/tree/86ab84d6a970ec6e5f790af1a3198c71f9dab6bd/Casks/jenkins.rb) and [handy-outliner.rb](https://github.com/caskroom/homebrew-cask/blob/86ab84d6a970ec6e5f790af1a3198c71f9dab6bd/Casks/handy-outliner.rb) as a reference. It's really hard to tell at the moment what approach could be used to achieve your goal and you should open a PR even if there is no working solution yet. It will be easier to suggest different approaches there.

**Comment by chrisRidgers** [comment]
Got an issue with the download.

Everything appears to be downloading find and being staged under /opt/foo/bar

In addition my binary is successfully created and linked under /usr/local/bin

However, java complains that my it must be used with a .jar file.  Within my staged directory, it appears that my .jar has been unpacked into individual class files.

Does homebrew-cask handle .jars in a particular manner that might cause this?

**Comment by victorpopkov** [comment]
> Does homebrew-cask handle .jars in a particular manner that might cause this?

Nope, it doesn't. HBC doesn't handle .jar files in any other specific way. Only the cask author decides how it should handle them and it should be done manually at the moment.

**Comment by chrisRidgers** [comment]
So if my URL points to a jar archive, and that downloads to /Library/Caches/Homebrew/minecraft-server-1.8.8.jar, and my cask links a binary like this

```ruby
 cask :v1 => 'minecraft-server' do
  version '1.8.8'
  sha256 :no_check

  url 'https://s3.amazonaws.com/Minecraft.Download/versions/1.8.8/minecraft_server.1.8.8.jar'
  name 'Minecraft Server'
  homepage 'https://minecraft.net'
  license :unknown    # todo: change license and remove this comment; ':unknown' is a machine-generated placeholder

  preflight do
    FileUtils.touch "#{staged_path}/minecraft-server"
    minecraft_server = File.open "#{staged_path}/minecraft-server", 'w'
    minecraft_server.puts '#!/bin/bash'
    minecraft_server.puts 'BASEDIR=$(dirname "$(readlink -n $0)")'
    minecraft_server.puts 'java -Xmx1024M -Xms1024M -jar #{BASEDIR}/minecraft_server.1.8.8.jar nogui'
    minecraft_server.close
  end

  binary 'minecraft-server'

  postflight do
    set_permissions "#{staged_path}/minecraft-server", '+x'
    %x(minecraft-server)
    %x(sed s/false/true/ <#{staged_path}/EULA.txt >#{staged_path}/EULA.txt)
  end

  caveats do
    puts 'To run this app, type "minecraft-server" in terminal.'
  end
end
```

And the end result is that the .jar is unpacked into /opt/homebrew-cask/Caskroom/minecraft-server/1.8.8/

Can you spot anything in there that looks amiss?

**Comment by victorpopkov** [comment]
The issue here is that HBC tries to determine the container to use based on the filetype `.jar` and uses `Hbc::Container::Zip` by default. For this case you have to manually specify the container `:naked`:
```ruby
  container :type => :naked
```

**Comment by chrisRidgers** [comment]
Yeh I initially was cd'ing into the directory as part of script, but then changed it while i tried to figure out what wasn't working.

Cool shout on the string substitution, Ruby's not my primary language.  I'll add it in but once it's working I'll submit a PR request for review and make other improvements then.

Cheers for the help.
