### ISSUE TITLE
Inconsistent state of real-vnc; not actually installed, but registered and can't uninstall.

### ISSUE THREAD

**Issue by CodeGnome** [caskroom/homebrew-cask#13939]
If real-vnc installation is aborted (e.g. by hitting CTRL-C when prompted for a sudo password) it can leave the cask in an inconsistent state where cask thinks the app is installed but can't uninstall it. For example:

    $ brew cask list real-vnc
    ==> Staged content:
    /opt/homebrew-cask/Caskroom/real-vnc/5.2.3 (1 files)

    $ brew cask uninstall real-vnc
    ==> Running uninstall process for real-vnc; your password may be necessary
    ==> Running uninstall script /Applications/RealVNC/Advanced.localized/Uninstall 
    Password:
    Password:
    ==> Sorry, try again.
    ==> sudo: /Applications/RealVNC/Advanced.localized/Uninstall VNC Server.app/Cont
    Error: Command failed to execute!

    ==> Failed command:
    ["/usr/bin/sudo", "-E", "--", "#<Pathname:/Applications/RealVNC/Advanced.localized/Uninstall VNC Server.app/Contents/Resources/uninstaller.sh>"]

    ==> Output of failed command:

    ==> Exit status of failed command:
    #<Process::Status: pid 82755 exit 1>

The uninstall script (and in fact the directory itself) was never installed. Consider:

    $ ls /Applications/RealVNC
    ls: cannot access /Applications/RealVNC: No such file or directory

There should be a more robust way to deal with this situation.

**Comment by vitorgalvao** [comment]
`brew cask list` is broken. We’re well aware of the issue.

In the meantime, simply remove the `/opt/homebrew-cask/Caskroom/real-vnc/`, and it should fix it.
