### ISSUE TITLE
DiffMerge Resources references /Applications

### ISSUE THREAD

**Issue by darkn3rd** [caskroom/homebrew-cask#13934]
I just installed DiffMerge (brew cask install diffmerge), which places it in `/opt/homebrew-cask/Caskroom/diffmerge/4.2.0.697/DiffMerge.app`.  

This normally would not be a problem, but internal shell script, `DiffMerge.app/Contents/Resources/diffmerge.sh`, as well as the one in the Extras folder refers to its executable as:

```
DIFFMERGE_PATH=/Applications/DiffMerge.app
DIFFMERGE_EXE=${DIFFMERGE_PATH}/Contents/MacOS/DiffMerge
```
**EXPECTED BEHAVIOR**:  If this application lives somewhere else, then the support scripts should be updated to refer to the correct location of the application.  Thus `DIFFMERGE_PATH=/opt/homebrew-cask/Caskroom/diffmerge/4.2.0.697/DiffMerge.app`.

**Comment by darkn3rd** [comment]
Current with DiffMerge, this is the behavior:

```
/build/sgdm400/Apple/intel/Release_patched/wxWidgets-3.0.0-rc1/src/common/arrstr.cpp(368): assert "nIndex < m_nCount" failed in RemoveAt(): bad index in wxArrayString::Remove

Call stack:
[00] wxFileName::RemoveLastDir()             
[01] dlg_paid::~dlg_paid()                   
[02] dlg_paid::~dlg_paid()                   
[03] wxURI::~wxURI()                         
[04] wxHashTable::~wxHashTable()             
[05] dlg_paid::~dlg_paid()                   
[06] wxLogger::DoLogTrace(wxString const&, wchar_t const*, ...) 
[07] 0x00000001              
```

**Comment by vitorgalvao** [comment]
Ideally, that should be fixed upstream. Not like the script can’t know it’s own location, and hardcoding the path assuming every user installs to the same location is lazy and leads to these types of issues. We shouldn’t be altering the script, since that is a recipe for disaster when it changes.

Labelled as upstream, and added to https://github.com/caskroom/homebrew-cask/issues/12858 for fixing later.

**Comment by darkn3rd** [comment]
I think this can be fixed now:

```bash
curl -O http://download-us.sourcegear.com/DiffMerge/4.2.0/DiffMerge.4.2.0.697.intel.stable.pkg
sudo installer -pkg ~/Downloads/DiffMerge.4.2.0.697.intel.stable.pkg -target /
```

**Comment by darkn3rd** [comment]
Until the upstream fix, the broken package should be removed.

Workaround: 

```bash
curl -O http://download-us.sourcegear.com/DiffMerge/4.2.0/DiffMerge.4.2.0.697.intel.stable.pkg
sudo installer -pkg ~/Downloads/DiffMerge.4.2.0.697.intel.stable.pkg -target /
```
