### ISSUE TITLE
Error messages on update/upgrade 

### ISSUE THREAD

**Issue by mcnesium** [caskroom/homebrew-cask#13948]
mcnesium@mcobst:~$ brew update
    Already up-to-date.
    mcnesium@mcobst:~$ brew upgrade brew-cask
    Error: caskroom/cask/brew-cask 0.56.0 already installed
    mcnesium@mcobst:~$

It's hard to expose the severeness of that red underlined "Error:" in markdown but I kind of feel like this is not really an error, right? Shouldn't this be more like an "Info:" label?

**Comment by vitorgalvao** [comment]
Unless your command starts with `brew cask`, it isn’t ours. You want [homebrew](https://github.com/Homebrew/homebrew), not homebrew-cask.
