### ISSUE TITLE
QQ should be updated

### ISSUE THREAD

**Issue by Nappp** [caskroom/homebrew-cask#13978]
| Key | Value |
| :---: | :---: |
| version | 4.0.4 |
| sha256 | c0db5ee1d19532e8be16a5e6b3e57e09296ce8677f9b2728c7740a38217ff307 |
| download | http://dldir1.qq.com/qqfile/QQforMac/QQ_V4.0.4.dmg |

**Comment by vitorgalvao** [comment]
Done.
