### ISSUE TITLE
Set up code climate for PRs

### ISSUE THREAD

**Issue by mwean** [caskroom/homebrew-cask#13971]
It would be nice to see how PRs affect code quality before merging them in. Instructions are here: http://docs.codeclimate.com/article/213-github-pull-request-integration

**Comment by adityadalal924** [comment]
Seems to already be implemented. From README.md

```
[![Code Climate](https://img.shields.io/codeclimate/github/caskroom/homebrew-cask.svg)](https://codeclimate.com/github/caskroom/homebrew-cask)
```

**Comment by jawshooah** [comment]
@adityadalal924 Not quite. That badge tracks code quality on `master`, but we don't currently have Code Climate analyzing PRs.

I wouldn't mind adding PR integration as long as we don't have to deal with noisy auto-comments.

**Comment by jawshooah** [comment]
@vitorgalvao, thoughts?

**Comment by Amorymeltzer** [comment]
>as long as we don't have to deal with noisy auto-comments.

:100:

**Comment by adityadalal924** [comment]
If there is a setting which would only run this on PRs with the tag "core", it makes sense and I'd be for it. Otherwise, seems a bit unnecessary to me.

**Comment by vitorgalvao** [comment]
> >as long as we don't have to deal with noisy auto-comments.

> :100: 

Yep.

**Comment by reitermarkus** [comment]
Closing this, as this doesn't make sense anymore without a core.
