### ISSUE TITLE
Some updated casks show up as "not installed"

### ISSUE THREAD

**Issue by wzxu** [caskroom/homebrew-cask#14017]
I've noticed this from time to time. Sometimes when there's a new version comes out for an app, I do a `brew update` expecting to see it updated, but then there's nothing, and when I `brew cask info` that app I'd discover that the cask was indeed updated, but the app somehow shows up as "not installed". I then have to manually `brew cask install` that app again, and manually remove the old version. Happened just then with iMazing, and a while back with Firefox and others.

Any ideas?

**Comment by vitorgalvao** [comment]
Know issue. `brew cask list` is broken.

**Comment by wzxu** [comment]
Thanks. I searched for “brew cask list” and there are a few of them. Not sure which issue is the main one about this?

**Comment by vitorgalvao** [comment]
There isn’t a single main one, since there are different things that are broken with it. I’ll create a main one, though.
