### ISSUE TITLE
Apps installed through Cask cannot be added to Dock in El Capitan

### ISSUE THREAD

**Issue by sodle** [caskroom/homebrew-cask#14129]
The Dock pinning behavior seems to have changed slightly in ElCap. Though aliased apps (like those installed through Cask) still appear in Launchpad, they can't be added to the application area of the Dock. Instead the system offers to add them to the right side of the Dock containing your folder stacks and Trash.

**Comment by vitorgalvao** [comment]
Will be made irrelevant by https://github.com/caskroom/homebrew-cask/issues/13201.

**Comment by ckujau** [comment]
Hm, #13201 is still open and no fix in sight. Is there a workaround to add symlinked applications to the Dock?

**Comment by sthornington** [comment]
Old issue, but one can always just follow the symlink in the terminal (to /usr/local/opt/app), then do an `open .` and drag the actual Program.app to the dock...

**Comment by vitorgalvao** [comment]
@sthornington This issue is so old, those instructions don’t even apply anymore. We haven’t symlinked apps in months.

**Comment by sthornington** [comment]
That's odd, I had to linkapps last night during a fresh install, and it was a symlink.






On Sat, Nov 26, 2016 at 3:59 AM -0800, "Vítor Galvão" <notifications@github.com> wrote:












@sthornington This issue is so old, those instructions don’t even apply anymore. We haven’t symlinked apps in months.

**Comment by vitorgalvao** [comment]
> That's odd, I had to linkapps last night during a fresh install, and it was a symlink.

That’s Homebrew, not Homebrew-Cask.
