### ISSUE TITLE
installation loop

### ISSUE THREAD

**Issue by danielb2** [caskroom/homebrew-cask#14148]
```
[~]$ brew install caskroom/cask/brew-cask

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
```

OK, fine ...

```
[~]$ sudo brew install caskroom/cask/brew-cask
Error: Cowardly refusing to `sudo brew install`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```

Arrrgh ...

So now what?

Ref: https://github.com/Homebrew/homebrew/issues/44518

**Comment by vitorgalvao** [comment]
Open Xcode manually (via GUI) and accept the license. It’ll fix itself.

**Comment by danielb2** [comment]
Yes, while I figured this out, it's a bit of a silly loop to find yourself in. Maybe it should be fix in some way by suggesting to the user on how to do it in the actual text?

**Comment by vitorgalvao** [comment]
I’d like for this to happen again, before. Xcode was updated before and I don’t remember having this problem (but I did have it recently, as well), so I’d first like to make sure it wasn’t an isolated incident with this version.

**Comment by vitorgalvao** [comment]
Also, this only happened as a weird coincidence between homebrew and homebrew-cask. Both our messages were correct, it was just that one didn’t know enough about your actions to be able to point you in the right direction, so this can’t be solved with a simple message, because we wouldn’t be able to tell it was needed to fix this.

**Comment by danielb2** [comment]
I just updated xcode and had it happen one more time, fyi ;)

I just ran `sudo xcodebuild` this time to accept it via commandline
