### ISSUE TITLE
command line length?

### ISSUE THREAD

**Issue by gaming-hacker** [caskroom/homebrew-cask#14169]
why is the command line so long to have to string together commands?

also it's not clear where cask is storing formula.  i installed kid3 but it's outdated and i wanted to modify the formula to latest version.

**Comment by vitorgalvao** [comment]
> why is the command line so long to have to string together commands?

I don’t get your question.

> also it's not clear where cask is storing formula.

[CONTRIBUTING.md](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md).
