### ISSUE TITLE
microsoft-lync URL invalid

### ISSUE THREAD

**Issue by yrral86** [caskroom/homebrew-cask#14167]
==> Downloading http://download.microsoft.com/download/5/0/0/500C7E1F-3235-47D4-BC11-95A71A1BA3ED/lync_14.1.1_150716.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'microsoft-lync' with message: Download failed: http://download.microsoft.com/download/5/0/0/500C7E1F-3235-47D4-BC11-95A71A1BA3ED/lync_14.1.1_150716.dmg

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/14168
