### ISSUE TITLE
Name mangling (or something?) causing issues?

### ISSUE THREAD

**Issue by MrJoy** [caskroom/homebrew-cask#14177]
I've installed the `microsoft-office-365` cask, and I'm noticing that at some points various parts of Homebrew and/or Caskroom are treating it as `microsoft-office365` instead.  This is causing some issues with Brewdler-esque tools.

What, specifically, can I do to help you determine the nature of this problem and get it sorted out?

**Comment by vitorgalvao** [comment]
Actually, `microsoft-office365` is correct. There shouldn’t be any `-` before numbers (and they are ignored in certain situations, which is why you’re seeing the confusion). Will fix briefly.
