### ISSUE TITLE
Allow for more flexibility with multiple versions of the same app

### ISSUE THREAD

**Issue by passcod** [caskroom/homebrew-cask#142]
In #114, I hinted at this, and #41 is the original issue. We need some way to support apps that have multiple concurrent builds/versions/channels. Here are the various situations in the Casks library at the moment:

- Firefox has four "channels": [Stable], [Beta], [Aurora], and [Nightly]. Currently we have two casks: [firefox] and [firefox-aurora].

- We have both [Chrome], [Canary] \(which is the equivalent of Aurora for Firefox), and [Chromium] \(which is Chrome without the Google in it).

These are just multiple stable/beta/alpha/nightlies, though. IntelliJ presents a different (but no less worthy) use-case: we currently has a cask each for the [Community] and [Ultimate] editions. It would be interesting to combine these!

[Stable]: www.mozilla.org/firefox
[Beta]: https://www.mozilla.org/firefox/beta/
[Aurora]: https://www.mozilla.org/firefox/aurora/
[Nightly]: http://nightly.mozilla.org/
[firefox]: https://github.com/phinze/homebrew-cask/blob/master/Casks/firefox.rb
[firefox-aurora]: https://github.com/phinze/homebrew-cask/blob/master/Casks/firefox-aurora.rb

[Chrome]: https://github.com/phinze/homebrew-cask/blob/master/Casks/google-chrome.rb
[Canary]: https://github.com/phinze/homebrew-cask/blob/master/Casks/google-chrome-canary.rb
[Chromium]: https://github.com/phinze/homebrew-cask/blob/master/Casks/chromium.rb

[Community]: https://github.com/phinze/homebrew-cask/blob/master/Casks/intellij-community.rb
[Ultimate]: https://github.com/phinze/homebrew-cask/blob/master/Casks/intellij-ultimate.rb

- - - - - - - -

My current proposal would have the formulae look like this:

```ruby
class SomeCask < Cask
  url 'http://example.com/thing-1.0.0.dmg'
  homepage 'http://example.com'
  version '1.0.0'
  sha1 '...'

  # The devel spec has a version but no checksum
  # (useful when the file changes frequently and w/o warning).
  devel do
    url 'http://example.com/thing-1.1.0-beta.dmg'
    version '1.1.0-beta'
  end

  # The edge spec has no version nor checksum
  # (e.g. nightly builds). Will be installed under `EDGE`
  # as version-path.
  edge do
    url 'http://example.com/nightly.dmg'
  end

  # Specs can be customised (see below for more).
  # Can be useful for e.g. community/closed-source
  # alternates, or unbranded builds.
  spec :alternate do
    url 'http://example.com/thing-1.0.0-alternate.dmg'
    version '1.0.0'
    sha1 '...'
  end
end
```

Here's how the Firefox cask would be done:

```ruby
class Firefox < Cask
  url 'http://download.cdn.mozilla.net/pub/mozilla.org/firefox/releases/17.0.1/mac/en-US/Firefox%2017.0.1.dmg'
  homepage 'http://www.mozilla.org/en-US/firefox/'
  version '17.0.1'
  sha1 'a9888ce69440574fabff712549c8ff503fd1acb7'

  # By default, both checksums and versions are required / checked…
  spec :beta do
    url 'http://download.cdn.mozilla.net/pub/mozilla.org/firefox/releases/18.0b3/mac/en-US/Firefox%2018.0b3.dmg'
    version '18.0b3'
    sha1 '31e383782b4fbbcbf3a1ef578d82cbf6861912cb'
  end

  # …and you can disable each separately…
  spec :aurora, :checksum => false do
    url 'https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-mozilla-aurora/firefox-19.0a2.en-US.mac.dmg'
    version '19.0a2'
  end

  # …and also set aliases for ease-of-use / familiarity
  spec :nightly, :checksum => false, :version => false, :alias => :edge do
    url 'http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/firefox-20.0a1.en-US.mac.dmg'
  end
end
```

With options looking like this:

```shell
# Predefined specs have predefined switches:
--stable
--devel
--edge

# Custom specs use a more generic syntax:
--spec=aurora

# Aliased specs can be accessed through any name:
--spec=nightly
--edge

# The generic syntax is also valid for predefined specs:
--spec=devel
--spec=stable
```

- - - - -

Please comment! with any ideas, criticisms, completely different proposals, or whatever else. This is quite a rough draft of an idea :)

**Comment by webavant** [comment]
#4332 worked for me.

**Comment by cherrot** [comment]
#4332 works:

```
$ brew tap caskroom/versions
$ brew cask install google-chrome-dev
```

**Comment by vitorgalvao** [comment]
Different repos is likely the best we have, and will continue to be for a long while, until/unless we revamp the system.
