### ISSUE TITLE
Sublime Text Unistall

### ISSUE THREAD

**Issue by viniciusbig** [caskroom/homebrew-cask#14209]
I got an error trying to uninstall sublime text with the following command:

brew cask uninstall sublime-text

Permission denied - /Users/myuseraccount/Applications/Sublime Text 2.app

How can I fix the permission problems with Cask?
Thanks in advance

**Comment by vitorgalvao** [comment]
[Reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs). If the issue persists, please report back, and edit the top post.
