### ISSUE TITLE
The application "Caprine" can't be opened

### ISSUE THREAD

**Issue by kevindurb** [caskroom/homebrew-cask#14217]
installed caprine via:

    brew cask install caprine

now im getting popup everytime i try to open it saying:

    The application "caprine" can't be opened

Anyone else gotten this error before?

**Comment by adityadalal924** [comment]
Before reporting a bug, make sure you have the latest versions of homebrew, homebrew-cask, and all Taps by running the following command:

`$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`

If the issue persists, please run the problematic command with the --verbose flag and post its and brew cask doctor’s outputs in distinct fenced code blocks.

------------

Anyway, no errors here.

```
[~/Downloads] > brew cask install caprine
==> Downloading https://github.com/sindresorhus/caprine/releases/download/0.1.2/
######################################################################## 100.0%
==> Symlinking App 'Caprine.app' to '/Applications/Caprine.app'
🍺  caprine staged at '/opt/homebrew-cask/Caskroom/caprine/0.1.2' (141 files, 99M)
```

----------------------

You can also try `messenger` or `messenger-native` or `aluxian-messenger` - all of them do approximately the same thing.

**Comment by victorpopkov** [comment]
Also don't see any problems here. The cask works fine.

Thank you, @adityadalal924, for your recommendations and explanations in this issue. You are awesome!
