### ISSUE TITLE
Why use hokeyapp as the download source for Slack?

### ISSUE THREAD

**Issue by taboularasa** [caskroom/homebrew-cask#14219]
When I try to download Slack from their website I'm directed to this link:
https://slack.com/ssb/download-osx

When I try to install Slack via Cask the app is downloaded from an alternate host:

> hockeyapp.net is the official download host per the app cast feed

https://github.com/caskroom/homebrew-cask/blob/ade085316096d9e57ee28203f75cffdb842cba03/Casks/slack.rb#L6

**Comment by victorpopkov** [comment]
This is not a mistake and the download URL from the official appcast source is used. Most likely that in the past the download URL was completely different and now has changed to use the new host instead (slack-ssb-updates.global.ssl.fastly.net).

However, I also agree that it would be better to use the one from the vendor homepage with the appropriate comment:
```ruby
  # fastly.net is the official download host per the vendor homepage
  url "https://slack-ssb-updates.global.ssl.fastly.net/mac_public_releases/slack-#{version}.zip"
```

Care submitting a PR?

**Comment by taboularasa** [comment]
@victorpopkov I'd be happy to, is the sha a required attribute of a cask definition? because the Slack download page does not list any for it's downloads.

**Comment by victorpopkov** [comment]
For versioned cask, it's a required value, so it should be specified. You can easily find out the sha246 checksum by simply running `shasum` on the downloaded file:
```bash
shasum -a 256 ~/Downloads/slack-1.1.4.zip
```

**Comment by taboularasa** [comment]
I could do that, but that would mean that I am electing to be the authority of the app's authenticity.

**Comment by victorpopkov** [comment]
The sha256 checksum provided with the version is only used to make sure that the downloaded file is the same. There is no need to be the app authority to retrieve the checksum. You only have to be sure that it matches the downloaded file.

**Comment by taboularasa** [comment]
https://github.com/caskroom/homebrew-cask/pull/14232
