### ISSUE TITLE
DJV update

### ISSUE THREAD

**Issue by NNois** [caskroom/homebrew-cask#14236]
Hi,
I'm very pleased to thank you all for this repository, it's invaluable.
However some formulas are out of date and i haven't found how to update them manually...

One of them is DJV and it's updated to Version 1.1 (Released 2015/06/02)
http://sourceforge.net/projects/djv/files/djv-stable/1.1.0/djv-1.1.0-OSX-64.dmg/download

Can this be updated ?
How can I deal with that without bothering you ? do i need to fork cask ?

**Comment by victorpopkov** [comment]
Done in https://github.com/caskroom/homebrew-cask/pull/14249.

You can simply fork the whole [caskroom/homebrew-cask](https://github.com/caskroom/homebrew-cask) project and then make there all the required changes in a separate branch. Afer that you have to just submit a PR of your branch.

**Comment by adityadalal924** [comment]
@NNois here's my cask update cheat sheet for reference. Hope this helps

https://gist.github.com/adityadalal924/9e6dd7630f62ec737685

**Comment by vitorgalvao** [comment]
I also have [a script](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair) which aims to make cask update contributions easier: all you need is to know which cask to update and to what version.

You can install it with `brew install vitorgalvao/tinyscripts/cask-repair`. After that, simply `cd` into your local fork and run `cask-repair {{whatever cask name here}}` and it’ll guide you through the process. It’ll do all the boring work for you: getting the shasum, creating a branch, updating the cask, and even pushing.
