### ISSUE TITLE
brew requests filing a bug

### ISSUE THREAD

**Issue by sbenario** [caskroom/homebrew-cask#14259]
|2.1.1| NewlyImaged in ~
○ → brew cask install cord
Error: undefined method `cask' for main:Object
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/cord.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/source/path_base.rb:22:in `load'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask.rb:119:in `load'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/cli.rb:57:in `run_command'
/usr/local/Cellar/brew-cask/0.36.1/rubylib/cask/cli.rb:72:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:60:in `require?'
/usr/local/Library/brew.rb:139:in `<main>'

**Comment by vitorgalvao** [comment]
[Reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

Follow the command there. You’re using an old version.
