### ISSUE TITLE
OpenZFS needs a caveat about El Capitan installation.

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#14256]
See https://github.com/caskroom/homebrew-cask/issues/14182#issuecomment-146029731.

**Comment by ilovezfs** [comment]
SIP compliant now. Thanks for your patience.
https://github.com/ilovezfs/openzfsonosx-installer/commit/fe930aa0add6cb4c709cbab4d828101ceed13889
https://twitter.com/openzfsonosx/status/656095561490132994
https://openzfsonosx.org/wiki/Downloads
https://openzfsonosx.org/forum/viewtopic.php?f=20&t=2353
