### ISSUE TITLE
Error: library not found for class Digest::SHA2 -- digest/sha2

### ISSUE THREAD

**Issue by taa1** [caskroom/homebrew-cask#14274]
Help! I broke my cask! :D

Mac OS X 10.7.5 (Lion)
Xcode 4.2.1 (I can't update to latest yet because it might break an open source package I help maintain)

Preliminary bug report info I believe you [need](https://github.com/caskroom/homebrew-cask/blob/master/README.md#reporting-bugs):

~~~~
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: caskroom/cask/brew-cask 0.57.0 already installed
~~~~

~~~~
$ brew doctor
(stripped '... please don't worry...' warning)
Warning: Your Xcode (4.2.1) is outdated
Please update to Xcode 4.6.3.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/
$ 
~~~~

HERE'S THE INFO ON THE ISSUE I'M REPORTING

~~~~
$ brew cask install python3 --verbose
==> Downloading https://www.python.org/ftp/python/3.5.0/python-3.5.0-macosx10.6.pkg
Already downloaded: /Library/Caches/Homebrew/python3-3.5.0.pkg
Error: library not found for class Digest::SHA2 -- digest/sha2

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/digest.rb:15:in `const_missing'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/verify.rb:14:in `checksum'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/download.rb:33:in `perform'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/installer.rb:89:in `download'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/installer.rb:63:in `install'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.57.0/rubylib/brew-cask-cmd.rb:19:in `<main>'
~~~~

**Comment by vitorgalvao** [comment]
> Please update to Xcode 4.6.3.

Have you done so?

**Comment by taa1** [comment]
I'm not sure why you're asking if I have already done so because I thought I already explained why I couldn't.

**Comment by jawshooah** [comment]
I don't think this problem is related to an outdated XCode. Upon Googling your error, it seems like this is probably a problem with your Ruby installation. Have you tried `brew update && brew uninstall ruby && brew install ruby`?

**Comment by jawshooah** [comment]
Alternatively, you could try using system Ruby. Just `brew unlink ruby && brew cask install python3`

**Comment by taa1** [comment]
I didn't know I was supposed to try an uninstall/reinstall of ruby.
~~~~
$ brew update && brew uninstall ruby && brew install ruby
~~~~

This uninstalled Ruby 2.2.2 and installed 2.2.3.

When I then try: 
~~~~
brew cask install python3 --verbose
~~~~

It ends with:

~~~~
==> installer:PHASE:Finishing the Installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:The software was successfully installed.
==> installer: The upgrade was successful.
🍺  python3 staged at '/opt/homebrew-cask/Caskroom/python3/3.5.0' (23M)
~~~~

So it looks like I'm OK now.

For my own knowledge, could you let me know when it would be appropriate to try your alternate suggestion (`brew unlink ruby && brew cask install python3`)?

**Comment by jawshooah** [comment]
I'd never seen your particular error before, but I deduced from the context that your Ruby installation was somehow faulty. The error was thrown from an internal Ruby library (`/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/digest.rb`), and search results seemed to associate the error message with a faulty install.

Uninstalling and reinstalling Ruby isn't a standard procedure for debugging issues with Homebrew-cask, it just seemed like a solid course of action given your specific problem.

I actually would have tried `brew unlink ruby` first, since it's non-destructive and much less time consuming than the un/reinstall. All it does is remove the symlinks that Homebrew creates for your Ruby installation, which leaves only the system Ruby in your PATH. If the problem persisted with system Ruby, we'd have to think of something else.

**Comment by jawshooah** [comment]
In any case, looks like you've got everything working, so I'll close this.

**Comment by taa1** [comment]
Thank you very much for the detailed explanation, and for your help!
