### ISSUE TITLE
Doc request: notification of when to expect #13201 to be implemented

### ISSUE THREAD

**Issue by brandondrew** [caskroom/homebrew-cask#14300]
It would be very useful the README included some mention of when to expect #13201 to be implemented, *even if that is simply to say "we have no idea"*.  The issue's discussion is *very* long, and no one who is not already dedicated to the project is likely to read through it all.  If there isn't even a rough date, that's still useful to know.

Thanks! (and by the way #13201 is a welcome change)

**Comment by vitorgalvao** [comment]
I agree people won’t read through it all, but usually in these cases they scroll to the bottom, where they will find [this](https://github.com/caskroom/homebrew-cask/issues/13201#issuecomment-146145297) (and nothing else, since the discussion is now locked).
