### ISSUE TITLE
Can't add apps to dock from launchpad

### ISSUE THREAD

**Issue by lolgear** [caskroom/homebrew-cask#14315]
I have trouble with launchpad and dock interaction

Apps can't be added to dock from launchpad by drag'n'drop

Well, I thought about permissions and fix them for homebrew and homebrew cask

Install problem fixed, but drag'n'drop launchpad dock interaction problem still exists

**Comment by vitorgalvao** [comment]
[Like I said](https://github.com/caskroom/homebrew-cask/issues/13201#issuecomment-146143424), this has nothing to do with homebrew or homebrew-cask.

Please ask [somewhere else](http://apple.stackexchange.com/).
