### ISSUE TITLE
install cask  failed

### ISSUE THREAD

**Issue by DukeLee1989** [caskroom/homebrew-cask#14360]
> brew install caskroom/cask/brew-cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3203, done.
remote: Compressing objects: 100% (3128/3128), done.
remote: Total 3203 (delta 79), reused 691 (delta 58), pack-reused 0
Receiving objects: 100% (3203/3203), 5.81 MiB | 6.00 KiB/s, done.
Resolving deltas: 100% (79/79), done.
Checking connectivity... done.
Tapped 1 formula (3182 files, 24M)
Error: Cannot write to /usr/local/Cellar

**Comment by jawshooah** [comment]
Are you able to install any other Homebrew formulae? If not, you should report this issue on [their repo](https://github.com/homebrew/homebrew), as it has nothing to do with us.

**Comment by DukeLee1989** [comment]
I'm sorry to reply to the late,I have already installed Homebrew.

**Comment by vitorgalvao** [comment]
> I'm sorry to reply to the late,I have already installed Homebrew.

That was not @jawshooah’s question. He was asking if you can install anything else. Run `brew install z`<sup>1</sup>, for example, does it succeed? If it does, then the issue isn’t ours, and it very much looks like it isn’t.

---
<sup>1</sup> Run `brew uninstall z` later, if you do not want it.
