### ISSUE TITLE
Installing into /Applications on OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by nwinkler** [caskroom/homebrew-cask#14382]
What's the recommended way to install apps into `/Applications` these days?

With Yosemite, I've used the following (my user is not in the machine's admin group):

* Set `HOMEBREW_CASK_OPTS=--appdir=/Applications` in my `~/.bash_profile`
* Before an install, I ran `sudo chown root:staff /Applications`
* Run `brew cask install ...`
* After the installation, I ran `sudo chown root:admin /Applications` to reset the permissions

With El Capitan, this does not work anymore, since you're not allowed to change permissions for `/Applications` (rootless feature).

What's the recommended way of doing this? I prefer installing apps into `/Applications` instead of `$HOME/Applications`.

How does everybody handle this?

**Comment by vitorgalvao** [comment]
Why are you changing permissions? Most people link to `/Applications`, and this is the first time I’ve ever heard of changing and resetting permissions. It was never needed.

**Comment by nwinkler** [comment]
Well, like I explained above, my user is not an admin on the machine.

The `/Applications` folder is owned by `root:admin` and is not writable for the rest of the world.

My user is a member of `staff everyone localaccounts` and thus does not have write permissions to `/Applications`.

Temporarily changing ownership is one of doing this, I could also run the command using `sudo`, but I want to avoid doing that.

Is your user part of the `admin` group?

**Comment by jawshooah** [comment]
My user is part of the `admin` group, so I've never encountered this problem.

If you don't want to add your user to the `admin` group, and you absolutely must use `/Applications`, all you can do is change the permissions. Thanks to Apple's infinite wisdom, you'll have to boot into Recovery mode and [manually disable SIP](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md#if-usrlocal-does-not-exist) to get this to work.

**Comment by vitorgalvao** [comment]
Closing as answered.
