### ISSUE TITLE
FontForge hard Cask-XQuartz dep?

### ISSUE THREAD

**Issue by DomT4** [caskroom/homebrew-cask#14389]
Hey Folks,

Was wondering why the FontForge Cask has a `depends_on :cask => 'xquartz'` line instead of the more flexible `depends_on :x11 => true` line?

My understanding is the latter checks if a user already has X11 available and installed, whereas the `depends_on :cask` syntax seems to be trying to force me to install the Cask's XQuartz on top of my already existing XQuartz non-brewed installation.

There wasn't any explanation in https://github.com/caskroom/homebrew-cask/commit/dc122dc64b5af4a9a8e8b5a9be9dcef16664deab, but apologies if I'm missing something previously documented.

Cheers.

**Comment by vitorgalvao** [comment]
Why is that indeed? Truth be told, I don’t remember. Perhaps `depends_on :x11` wasn’t yet done? Perhaps I was fixing a bunch of casks at once and forgot about it?

Either way, seems like there’s no reason to keep it that way, yes. Would you care to submit the change?

**Comment by DomT4** [comment]
> Perhaps depends_on :x11 wasn’t yet done? 

Yeah. This was my bad, I forgot to include it when I first submitted the FF cask.

> Would you care to submit the change?

Happy to! Will do that in a minute.
