### ISSUE TITLE
How to allow HTTP AUTH for curl/wget

### ISSUE THREAD

**Issue by fzakaria** [caskroom/homebrew-cask#14406]
Hello,

I'm trying to install a private tap where the application is stored behind a server that is restricted via HTTP AUTH (username/password).
I was wondering if there is anything in the stanza or somehow I can specify for the user to supply the credentials (similar to sudo) so that the application could be downloaded.

**Comment by vitorgalvao** [comment]
[Documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#additional-https-url-parameters). What we can do, you’ll find there.

**Comment by fzakaria** [comment]
For anyone who seems this I included this in my formula

    require 'io/console' 
    require "uri" 
    print "Password: "
    password = URI.encode(STDIN.noecho(&:gets))
    username = URI.encode(ENV['USER'])
    url "#{username}:#{password}@https://my-auth-protected-website.com/MyFakeApp.app.zip"
