### ISSUE TITLE
Request: Aurous

### ISSUE THREAD

**Issue by andreis** [caskroom/homebrew-cask#14411]
https://aurous.me/

**Comment by vitorgalvao** [comment]
No.

As a headsup to all @caskroom/maintainers, lets keep this app out of homebrew-cask, for the same reason we keep popcorn-time out.

[More info on TorrentFreak](https://torrentfreak.com/riaa-sues-popcorn-time-for-music-151013/). As soon as it was released, a lawsuit came.

**Comment by vitorgalvao** [comment]
[That was fast](https://torrentfreak.com/aurous-offers-to-shutdown-but-riaa-isnt-interested-151027/).

**Comment by andreis** [comment]
Hahaha :+1:
