### ISSUE TITLE
403 Forbidden for balsamiq-mockups

### ISSUE THREAD

**Issue by Dorian** [caskroom/homebrew-cask#14412]
The new URL is https://builds.balsamiq.com/mockups-desktop/Balsamiq_Mockups_3.2.3.dmg

```
% brew cask install balsamiq-mockups
==> Downloading https://s3.amazonaws.com/build_production/mockups-desktop/Balsamiq_Mockups_3.1.7.dmg

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'balsamiq-mockups' with message: Download failed: https://s3.amazonaws.com/build_production/mockups-desktop/Balsamiq_Mockups_3.1.7.dmg
```

**Comment by aaronmcadam** [comment]
Updating the Casks doesn't fix the issue either. The latest version on their site is 3.2.3, so  `https://builds.balsamiq.com/mockups-desktop/Balsamiq_Mockups_3.2.3.dmg` works, but `https://builds.balsamiq.com/mockups-desktop/Balsamiq_Mockups_3.2.2.dmg` doesn't.

Is there a directory Cask uses to put the downloaded files? It would be good if we could just download the file ourselves and have Cask find it.

**Comment by vitorgalvao** [comment]
Yes, balsamiq always removed the old version.

homebew-cask (and homebrew) download to `/Library/Caches/Homebrew`.

**Comment by adityadalal924** [comment]
Fixed, issue can be closed @Dorian (cc @vitorgalvao)

**Comment by Dorian** [comment]
Cool, awesome work guys!
