### ISSUE TITLE
iTerm2 cask: download fails, even though URL is correct?

### ISSUE THREAD

**Issue by SuperHenkie** [caskroom/homebrew-cask#14413]
Fully updated brew and cask, `brew cask install iterm2` says:

> ==> Downloading https://iterm2.com/downloads/stable/iTerm2-2_1_4.zip
> 
> curl: (7) Couldn't connect to server
> Error: Download failed on Cask 'iterm2' with message: Download failed: https://iterm2.com/downloads/stable/iTerm2-2_1_4.zip

However if I manually download that same URL in Firefox or Chrome, it downloads just fine.

Note that the download link also works with http instead of https, so maybe the issue is SSL related somehow? Although in either browser, it works fine with https without any warning or SSL notifications whatsoever.

**Comment by adityadalal924** [comment]
Seems to be a bug or a fluke, no issues here:

```
[~] > brew cask install iterm2
==> Downloading https://iterm2.com/downloads/stable/iTerm2-2_1_4.zip
######################################################################## 100.0%
==> Symlinking App 'iTerm.app' to '/Applications/iTerm.app'
🍺  iterm2 staged at '/opt/homebrew-cask/Caskroom/iterm2/2.1.4' (185 files, 8.4M)
[~] > 
```

Does `brew doctor` throw up any errors (i.e. broken .curlrc)?

**Comment by SuperHenkie** [comment]
Nope, nothing, `brew doctor` only says "Your system is ready to brew."
And `brew cask doctor` gives me a whole bunch of paths and version numbers, but no errors or warnings.

**Comment by adityadalal924** [comment]
Can you run `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and see if that helps?

If the issue persists, please run the problematic command with the `--verbose` flag and post its and `brew cask doctor`’s outputs in distinct fenced code blocks here.

**Comment by genjusz** [comment]
I think that this is problem with http://iterm2.com, because it's impossible to download App from their site.

**Comment by vitorgalvao** [comment]
Can confirm problem is not related to us. Usually this happens due to a `.curlrc` with custom options.
