### ISSUE TITLE
MathType.app cask fails

### ISSUE THREAD

**Issue by DannyNemer** [caskroom/homebrew-cask#14419]
This cask installation of [`mathtype.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mathtype.rb) fails. I believe this application requires using `installer :manual`, which does not fail, in place of `pkg`. However, we have been [told](https://github.com/caskroom/homebrew-cask/pull/13118#issuecomment-129167022):
> `installer :manual` is exclusively for cases with app installers. If `pkg` doesn’t work here, we fix that.

The following error occurs when attempting to open `MathType.app` following this cask's installation. Selecting "OK" closes the application. (Reinstallation does not fix this error as it suggests.)
<img width="450" src="https://cloud.githubusercontent.com/assets/170023/10491699/e3dc421a-7275-11e5-9ceb-1f37f19c0fda.png">

The missing "configuration file" is `/Applications/MathType 6/.MT6.dsc`. This file is normally created by the following manual installation step:
<img width="500" src="https://cloud.githubusercontent.com/assets/170023/10491751/3449ab2a-7276-11e5-855e-e1c5f33c1a8d.png">

**Comment by adityadalal924** [comment]
Looks like that's an encrypted license file, which can't simply be created. You *have* to copy it from an existing license or use the manual installer to generate a 30-day trial lic.

More info: https://jdmsysadmin.wordpress.com/2015/05/06/deploying-the-mathtype-license/

So, `installer: manual` might be the only way to not break things with cask - in which case, there really is little benefit to using ask for the app anyway, in my opinion.

**Comment by DannyNemer** [comment]
I agree, `installer: manual` is likely required.

If so, then why use Cask at all? Answer: the benefits of easily downloading the installation package and easily uninstalling the application (which works correctly). Also, the cask is useful if you have a script to install all of your system's applications (as I do).

I understand, however, if the community feels it is best to omit this package from Cask because it requires launching the manual installer.

**Comment by jawshooah** [comment]
Why exclude it? `installer :manual` is there for a reason :wink:
