### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by xyb** [caskroom/homebrew-cask#14436]
@vitorgalvao @jawshooah, follow your suggestions on #13785, [Homebrew/homebrew-completions](https://github.com/Homebrew/homebrew-completions) have included my brew-cask bash completion, you can `brew install homebrew/completions/brew-cask-completion` now. Again, it's works for `brew-cask` only.

I think may it's time add it to README. After that, I'll work on homebrew's bash completion to support `brew cask`.

**Comment by vitorgalvao** [comment]
Sounds good. Would you care to submit a first draft to the documentation?

**Comment by xyb** [comment]
@vitorgalvao #14610 attached.
