### ISSUE TITLE
flash needs update?

### ISSUE THREAD

**Issue by psibre** [caskroom/homebrew-cask#14456]
I'm getting:
```
$ brew cask install flash
==> Downloading https://fpdownload.macromedia.com/get/flashplayer/current/licensing/mac/install_flash_player_19_osx_pkg.dmg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: e2bb972aab13886622caabf87fec86f65d1c9c77744465190c6a99517be717b1
Actual: a0a1f72b7df6c056892a614ed28e26641315428917d0b8d54a3bcebb5c7d4cba
File: /Library/Caches/Homebrew/flash-19.0.0.205.dmg
To retry an incomplete download, remove the file above.
```
I *did* just `brew update`. Does the `flash` cask need another update?

**Comment by vitorgalvao** [comment]
Likely needs an update, yes. On another note, [perhaps you should uninstall it entirely](http://bgr.com/2015/10/15/adobe-flash-player-security-vulnerability-warning/).

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/14458

**Comment by psibre** [comment]
@vitorgalvao thanks for the quick fix!
For the record, the *only* reason I even have it installed is to play [embedded multimedia in my PDF presentations](https://www.ctan.org/pkg/media9).

**Comment by vitorgalvao** [comment]
> @vitorgalvao thanks for the quick fix!

Thank @andyli instead, I only merged the contribution.

**Comment by andyli** [comment]
I didn't updated the flash formula. But since you've mentioned me so I go ahead and updated the other flash formulae in #14464 ;)
