### ISSUE TITLE
homebrew dont get the linked python

### ISSUE THREAD

**Issue by stepstein** [caskroom/homebrew-cask#14462]
I try to install librsvg. then brew halt at gobject-introspection

==> ./configure --prefix=/usr/local/Cellar/gobject-introspection/1.46.0
Last 15 lines from /Users/stephensteiner/Library/Logs/Homebrew/gobject-introspection/01.configure:
..................
checking for a Python interpreter with version >= 2.7... none
configure: error: no suitable Python interpreter found

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
gobject-introspection: depend on python https://github.com/Homebrew/homebrew/pull/44673
.................
If I ask info for my brewed python, brew ask me to symlink. but if i want to symlink it is allready symlinked?? 

$ brew info python
..................
They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python` to symlink these to /Applications.
links-2.12 $ brew link -force python
Warning: Already linked: /usr/local/Cellar/python/2.7.10_2
To relink: brew unlink python && brew link python
................
what point I am missing?
Thanks for ideas.
st

**Comment by vitorgalvao** [comment]
Wrong project. You’re looking for (Homebrew](https://github.com/Homebrew/homebrew/).
