### ISSUE TITLE
Touch .localized when creating ~/Applications

### ISSUE THREAD

**Issue by Crazor** [caskroom/homebrew-cask#14477]
When I use homebrew-cask on a new machine, it automatically creates ~/Applications for the symlinks. It should also touch ~/Applications/.localized afterwards, to make the folder show up with the localized name in Finder (e.g. "Programme" on german systems).

**Comment by vitorgalvao** [comment]
[We’re dumping `~/Applications`](https://github.com/caskroom/homebrew-cask/issues/13201), so no point on band-aiding this.
