### ISSUE TITLE
qlcolorcode could use an update

### ISSUE THREAD

**Issue by aw1621107** [caskroom/homebrew-cask#14478]
The plugin seems to be compiled from a different source tree than the source on github. I noticed were missing themes; don't know if something else was also changed.

The maintainer doesn't seem to be responding to PRs (see [this](https://github.com/n8gray/QLColorCode/pull/2)), so maybe a patch from that guy's fork is necessary?

If there are any changes work making I'll be happy to make them.

**Comment by vitorgalvao** [comment]
We don’t compile anything, which means we also don’t apply patches. The plugin is just being downloaded from its home, at google code. You can change it’s home and download url to github, but I’m not sure it will make much difference, it does appear to be abandoned.

**Comment by aw1621107** [comment]
Hmmm... I'll take a look at turning this into a brew formula then

**Comment by niksy** [comment]
Yeah, this could really use an upgrade, looking at the forks of the project, there are some contenders for modern version, but I’m not sure which is compiled against latests Xcode features. This one looks promising: https://github.com/bitst0rm/QLColorCode
