### ISSUE TITLE
Tuxera: Invalid pref. file & can't uninstall

### ISSUE THREAD

**Issue by sambostock** [caskroom/homebrew-cask#14601]
After running `brew cask install tuxera-ntfs`, I get an 'Invalid Preference File' error in the preference pane, which prevents from authenticating the license key.  In addition, `brew cask uninstall tuxera-ntfs` doesn't work.

```
$ brew cask uninstall tuxera-ntfs
==> Running uninstall process for tuxera-ntfs; your password may be necessary
==> sudo: /System/Library/Filesystems/fusefs_txantfs.fs/Support/uninstall-packag
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "#<Pathname:/System/Library/Filesystems/fusefs_txantfs.fs/Support/uninstall-package.sh>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 2020 exit 1>
```

I suspect this must relate to the 2014 -> 2015 update?  The SHA also isn't being checked in the formula, so perhaps a change went unnoticed?

**Comment by vitorgalvao** [comment]
Seems like that file doesn’t exist anymore. Fixed `uninstall`. `brew update` and try again.
