### ISSUE TITLE
Dia.app requires XQuartz but it is not listed as dependency

### ISSUE THREAD

**Issue by kirichkov** [caskroom/homebrew-cask#14613]
Dia.app (package name: *dia*) requires XQuartz (package name: *xquartz*) to work. If XQuartz is not installed a dialog is opened when starting the app suggesting the installation of it.

Isn't it better if XQuartz was listed as a dependency of Dia, instead of the app suggesting a manual install?

**Comment by vitorgalvao** [comment]
Done.
