### ISSUE TITLE
brew install tree failed  

### ISSUE THREAD

**Issue by woodjuice** [caskroom/homebrew-cask#14640]
OSX 10.11.1
Homebrew 0.9.5

When I tried to "brew install tree"

>
$ brew install tree
==> Downloading http://mama.indstate.edu/users/ice/tree/src/tree-1.7.0.tgz
Already downloaded: /Library/Caches/Homebrew/tree-1.7.0.tgz
==> make prefix=/usr/local/Cellar/tree/1.7.0 MANDIR=/usr/local/Cellar/tree/1.7.0
make: *** [xml.o] Error 1
1 error generated.
make: *** [tree.o] Error 1
1 error generated.
make: *** [html.o] Error 1

**Comment by vitorgalvao** [comment]
Wrong project. You’re looking for [homebrew](https://github.com/homebrew/homebrew). If it doesn’t start with `brew cask`, it has nothing to do with us.

**Comment by woodjuice** [comment]
oh, I am sorry for that. 
Thx
