### ISSUE TITLE
DrRacket does not show up in the Applications folder

### ISSUE THREAD

**Issue by samvv** [caskroom/homebrew-cask#14644]
I installed drracket using `brew cask install racket`, but the application does not show up in the Applications folder.

Output of `brew linkapps`:

````
Linking /usr/local/opt/macvim/MacVim.app to /Applications.
Error: /Applications/MacVim.app already exists, skipping.
Linking /usr/local/opt/python/IDLE.app to /Applications.
Linking /usr/local/opt/python/Python Launcher.app to /Applications.
````

DrRacket is not there.

**Comment by vitorgalvao** [comment]
`brew linkapps` isn’t related to us.

`racket` links a directory, not an app. [We need more details](https://github.com/caskroom/homebrew-cask#reporting-bugs).
