### ISSUE TITLE
qgis warning gives wrong info

### ISSUE THREAD

**Issue by kastork** [caskroom/homebrew-cask#14668]
The warning produced when installing qgis says that the caveats in pyqt will explain about the PYTHON_PATH, but they don't.  The only Caveat in pyqt is that "Phonon support is broken".

**Comment by vitorgalvao** [comment]
Wrong project. You’re looking for [homebrew](https://github.com/homebrew/homebrew). If it doesn’t start with `brew cask`, it has nothing to do with us.
