### ISSUE TITLE
Aquamacs URL broken: 404

### ISSUE THREAD

**Issue by mnetzwur** [caskroom/homebrew-cask#14692]
It seems that the folder https://github.com/davidswelt/aquamacs-emacs/releases was removed.

admin@homeless:/Users/david$ brew cask install aquamacs
==> Downloading https://github.com/davidswelt/aquamacs-emacs/releases/download/Aquamacs-3.

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'aquamacs' with message: Download failed: https://github.com/davidswelt/aquamacs-emacs/releases/download/Aquamacs-3.2/Aquamacs-Emacs-3.2.dmg

**Comment by adityadalal924** [comment]
I see a latest version of `emacs-24.5-rc3-fixed`[here](https://github.com/davidswelt/aquamacs-emacs/releases), can you confirm that is correct (just seems like a large jump in version from 3.2 -> 24.x).

**Comment by mnetzwur** [comment]
Yes, you’re right about the URL being there, but while Aquamacs is based on GNU emacs, it is not the same thing. The Aquamacs packages seem to be missing.

**Comment by adityadalal924** [comment]
Fixed with #14714
