### ISSUE TITLE
Add instructions to run Rubocop locally

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#14713]
It would be nice to have instructions to run `rubocop` (style checking) locally before submitting a PR.

Adding to `CONTRIBUTING.md` would probably be ideal - it would give contributors a chance to make sure their PR won't fail due to styling, as well as reducing maintainer overhead.

**Comment by vitorgalvao** [comment]
First draft at https://github.com/caskroom/homebrew-cask/pull/14715/files.

Better than this, though, would be to have `audit` also run `rubocop` if it is available, and warn if not available:

```
audit for my-new-cask: passed

However, you do not have the `rubocop` gem installed, so there are stylistic details we weren’t able to check.
```

What do you think? Also pinging @jawshooah. Think that’d be a quick change?

**Comment by adityadalal924** [comment]
Looks good to me, though agreed, adding it to audit would be the best option

**Comment by jawshooah** [comment]
I believe Homebrew has integrated their Rubocop checks into `brew audit`. We could take a look at their implementation for hints.

**Comment by vitorgalvao** [comment]
Closing, since https://github.com/caskroom/homebrew-cask/pull/14715 and https://github.com/caskroom/homebrew-cask/issues/14736 cover this.
