### ISSUE TITLE
4k-video-downloader sha256 mismatch error

### ISSUE THREAD

**Issue by WilliamBradshaw** [caskroom/homebrew-cask#14720]
When attempting to download 4k-video-downloader I get the error:

==> Downloading http://downloads.4kdownload.com/app/4kvideodownloader_3.6.dmg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: c298303cae1a50b381f45b8ca64f3cd1455c92558d28f1f79a2d2f5ea9fdc58e
Actual: 9adac4eaff8478be06dacd995e54c70bddc1571795e095003a298e52479aea21
File: /Library/Caches/Homebrew/4k-video-downloader-3.6.dmg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.
