### ISSUE TITLE
Launchctl uninstall do not clean-up users LaunchAgents .plist files

### ISSUE THREAD

**Issue by forkbomber** [caskroom/homebrew-cask#14728]
(moving discussion from #14723)

launchctl uninstall seems to be designed to delete LaunchAgents .plist files as well, but it does not work on users LaunchAgents.
[/lib/hbc/artifact/uninstall_base.rb#L215-L223](../blob/c0ed120631bd6ab5607d99dfa0efff82b7398959/lib/hbc/artifact/uninstall_base.rb#L215-L223):
```ruby
if result.success?
  paths = ["/Library/LaunchAgents/#{service}.plist",
           "/Library/LaunchDaemons/#{service}.plist"]
  paths.each { |elt| elt.prepend('~') } unless with_sudo
  paths = paths.map { |elt| Pathname(elt) }.select(&:exist?)
  paths.each do |path|
    @command.run!('/bin/rm', :args => ['-f', '--', path], :sudo => with_sudo)
  end
end
```

Issue seems to be related to FileTest.exist not supporting tilde:
```ruby
irb(main):001:0> FileTest.exist?('./')
=> true
irb(main):002:0> FileTest.exist?('~/')
=> false
```

CC @vitorgalvao, @jawshooah

**Comment by kainjow** [comment]
Could use `ENV['HOME']`

**Comment by jawshooah** [comment]
@kainjow has the right idea. I'll push up a fix shortly.

**Comment by forkbomber** [comment]
Another separate issue is that until .plist was loaded - it wouldn't be shown by launchctl list, so .plist deletion code would not be entered.

**Comment by jawshooah** [comment]
It should also be noted that currently, these files are only removed if the launchjob is loaded at the time of uninstall. This may not be the case if the user has not logged out and logged in since installation.

We should probably remove the launchjob definitions before checking to see if any are loaded.

**Comment by jawshooah** [comment]
Ah, @forkbomber beat me to the punch.
