### ISSUE TITLE
suppress_move_to_applications directive not working in clamxav.

### ISSUE THREAD

**Issue by morganestes** [caskroom/homebrew-cask#14813]
I just installed the latest ClamXav Cask (2.8.5) and was prompted to move it to `/Applications` even though it has the [`suppress_move_to_applications` directive](https://github.com/caskroom/homebrew-cask/blob/master/Casks/clamxav.rb#L24). 

I don't know if it's a problem with the directive itself, or in the implementation of it by the Cask installer.

**Comment by adityadalal924** [comment]
The directive likely needs a custom key to work in this specific case.

Closing, as https://github.com/caskroom/homebrew-cask/issues/13201 will remove the need for this altogether.
