### ISSUE TITLE
publish statistics regarding cask popularity

### ISSUE THREAD

**Issue by ssbarnea** [caskroom/homebrew-cask#14826]
I think that it would be of great help to publish statistics regarding cask popularity as we already have lots of casks and we would like to discover what else people are using. Now we reached a point where is impossible to browser all casks in order to see them but if we would know how many installs each one has we could look for the more popular ones.

**Comment by vitorgalvao** [comment]
[We don’t intend to become a discoverability service](https://github.com/caskroom/homebrew-cask/issues/4323#issuecomment-67257513). Similar requests [have been discussed and refused multiple times](https://github.com/caskroom/homebrew-cask/issues/5425#issuecomment-49512837), as [it is not part of the goals of homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/3817#issuecomment-39868330). Amongst other things, the logistics are unsustainable.

[This particular request has also been made](https://github.com/caskroom/homebrew-cask/issues/4323).

The answer is a final “no”.
