### ISSUE TITLE
invalid 'depends_on :macos' value: ":el_capitan"

### ISSUE THREAD

**Issue by mAAdhaTTah** [caskroom/homebrew-cask#14827]
@vitorgalvao I'm still seeing this after upgrading to the latest version of homebrew-cask:

> Error: caskroom/cask/brew-cask HEAD already installed

> ○ → brew cask list
> Error: Cask 'onyx' definition is invalid: invalid 'depends_on :macos' value: ":el_capitan"

Had this problem on Yosemite; still seeing it after upgrading to El Capitan.

**Comment by vitorgalvao** [comment]
There’s your problem. Don’t use `HEAD`. Uninstall that and install again, and it should fix it.

Also, [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by mAAdhaTTah** [comment]
Thanks for your help; don't know how that happened.
