### ISSUE TITLE
Install fails on OSX Yosemite

### ISSUE THREAD

**Issue by nterry** [caskroom/homebrew-cask#14835]
Here is my verbose output:

nicholasterry:~ nicholasterry$ brew install Caskroom/cask/tuntap -v
==> brew cask install Caskroom/cask/tuntap --verbose
brew cask install Caskroom/cask/tuntap --verbose
==> Downloading http://downloads.sourceforge.net/project/tuntaposx/tuntap/20150118/tuntap_20150118.tar.gz
Already downloaded: /Library/Caches/Homebrew/tuntap-20150118.gz
==> Running installer for tuntap; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is TunTap Installer package
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing TunTap Installer package…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%56.796736
==> installer:PHASE:Registering updated components…
==> installer:%58.187072
==> installer:PHASE:Registering updated components…
==> installer:%59.576703
==> installer:PHASE:Registering updated components…
==> installer:%60.966544
==> installer:PHASE:Registering updated components…
==> installer:%62.357034
==> installer:PHASE:Registering updated components…
==> installer:%63.742410
==> installer:PHASE:Registering updated components…
==> installer:%65.131296
==> installer:PHASE:Registering updated components…
==> installer:%66.526311
==> installer:PHASE:Registering updated components…
==> installer:%67.913189
==> installer:PHASE:Registering updated components…
==> installer:%69.307240
==> installer:PHASE:Registering updated components…
==> installer:%70.695180
==> installer:PHASE:Registering updated components…
==> installer:%72.087037
==> installer:PHASE:Registering updated components…
==> installer:%73.476645
==> installer:PHASE:Registering updated components…
==> installer:%74.862950
==> installer:PHASE:Registering updated components…
==> installer:%76.251427
==> installer:PHASE:Registering updated components…
==> installer:%77.646848
==> installer:PHASE:Registering updated components…
==> installer:%79.032480
==> installer:PHASE:Registering updated components…
==> installer:%80.430084
==> installer:PHASE:Registering updated components…
==> installer:%81.817101
==> installer:PHASE:Registering updated components…
==> installer:%83.207257
==> installer:PHASE:Registering updated components…
==> installer:%83.832457
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:%84.049230
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/tuntap/20150118/tuntap_20150118.pkg>", "-target", "/", "-verboseR"]

No reccomendations or workarounds mentioned... What do i do? 

I do hope this is the right place to ask this... If not, I apologize... Can anyone direct me to where I can ask this...

**Comment by vitorgalvao** [comment]
Wrong command. You need to first `brew install caskroom/cask/brew-cask`, and then to install software you need to `brew cask install`, so `brew cask install tuntap`, in this case.

**Comment by nterry** [comment]
`brew install caskroom/cask/brew-cask` returns  brew-cask-0.54.1 already installed. Ran `brew cask install tuntap`. Same error

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by nterry** [comment]
Sorry.... I guess i deserve that RTFM like a n00b ;)
Ill do that and hopefully it'll fix the issue

**Comment by nterry** [comment]
Nope... Still erroring out:

Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/tuntap/20150118/tuntap_20150118.pkg>", "-target", "/", "-verboseR"]

==> Output of failed command:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing TunTap Installer package…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%56.586536
installer:PHASE:Registering updated components…
installer:%57.982560
installer:PHASE:Registering updated components…
installer:%59.366683
installer:PHASE:Registering updated components…
installer:%60.756419
installer:PHASE:Registering updated components…
installer:%62.152797
installer:PHASE:Registering updated components…
installer:%63.536739
installer:PHASE:Registering updated components…
installer:%64.926736
installer:PHASE:Registering updated components…
installer:%66.322730
installer:PHASE:Registering updated components…
installer:%67.706383
installer:PHASE:Registering updated components…
installer:%69.096720
installer:PHASE:Registering updated components…
installer:%70.492933
installer:PHASE:Registering updated components…
installer:%71.876647
installer:PHASE:Registering updated components…
installer:%73.266711
installer:PHASE:Registering updated components…
installer:%74.663053
installer:PHASE:Registering updated components…
installer:%76.047014
installer:PHASE:Registering updated components…
installer:%77.436714
installer:PHASE:Registering updated components…
installer:%78.832936
installer:PHASE:Registering updated components…
installer:%80.216948
installer:PHASE:Registering updated components…
installer:%81.606998
installer:PHASE:Registering updated components…
installer:%83.003003
installer:PHASE:Registering updated components…
installer:%83.832457
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)


==> Exit status of failed command:
#<Process::Status: pid 3077 exit 1>

**Comment by nterry** [comment]
And my doctor outout:

```
==> OS X Release:
10.10
==> OS X Release with Patchlevel:
10.10.4
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5 (git revision 5347f5; last commit 2015-11-02)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew.git
==> Homebrew-cask Version:
0.59.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.59.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files (warning: run "brew cask cleanup")
0.12 megs (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2840
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.59.0/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/nicholasterry/.rvm/gems/ruby-1.9.3-p551/bin:/Users/nicholasterry/.rvm/gems/ruby-1.9.3-p551@global/bin:/Users/nicholasterry/.rvm/rubies/ruby-1.9.3-p551/bin:/opt/sonar/sonar-runner-2.4/bin:/opt/sonar/sonarqube-5.1.2/binmacosx-universal-64:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nicholasterry/bin:/Users/nicholasterry/.rvm/bin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```

**Comment by vitorgalvao** [comment]
Next step: run the installer manually. Does it work?

**Comment by nterry** [comment]
@vitorgalvao By 'manual' do you mean download and build from sources?

**Comment by vitorgalvao** [comment]
No, I mean download and double clicking the `pkg`. Installing just as you would if homebrew-cask didn’t exist.

**Comment by nterry** [comment]
Nope, same error....

**Comment by vitorgalvao** [comment]
Then we can’t do anything. The problem isn’t related to us, and you’ll have to contact them directly.

**Comment by nterry** [comment]
Ok. Thanks
