### ISSUE TITLE
add support for Login Items removal during uninstallation

### ISSUE THREAD

**Issue by forkbomber** [caskroom/homebrew-cask#14854]
Majority of GUI clients persist their autostart preference inside users Login Items list.
A few examples of such applications are [dropbox.rb](../blob/master/Casks/dropbox.rb), [spotify.rb](../blob/master/Casks/spotify.rb) and [flux.rb](../blob/master/Casks/flux.rb).

Configuration files are located at `~/Library/Preferences/com.apple.loginitems.plist` and items can be removed from there.
A nicer option would be to use `osascript`:
`osascript -e 'tell application "System Events" to delete every login item whose name is "AppName"'`
This not only removes every matching Login Item, but also it would continue normally if there aren't any matches.

I'd like to see a helper dedicated to deal with Login Items within HBC so that 
```ruby
uninstall_postflight do
  system '/usr/bin/osascript', '-e', %Q{tell application "System Events" to delete every \
    login item whose name is "#{token.gsub(/\w+/, &:capitalize).gsub('-', ' ')}"}
end
```
can be replaced with something like
```ruby
uninstall :login_item => 'Turbo Boost Switcher'
```

---

Incomplete list of apps that would benefit from this:

- [ ] [dropbox.rb](../blob/master/Casks/dropbox.rb)
- [ ] [flux.rb](../blob/master/Casks/flux.rb).
- [ ] [spotify.rb](../blob/master/Casks/spotify.rb)
- [ ] [turbo-boost-switcher.rb](../blob/master/Casks/turbo-boost-switcher.rb)

**Comment by vitorgalvao** [comment]
The idea is great, but we should change it to use the apps’s bundle ID instead. Could we change `login item whose name is` to `login item whose id is` directly, or do we need something more?

**Comment by vitorgalvao** [comment]
I’ve also edited you post to add at the end a list of apps that would benefit from it.

**Comment by forkbomber** [comment]
IDs only occasionally mentioned inside `com.apple.LSSharedFileList.Binding` property, we cannot reliably use (or access) them.
See it yourself: `/usr/libexec/PlistBuddy -c Print ~/Library/Preferences/com.apple.loginitems.plist`

Standard attributies are `name`, `path`, `class`, `kind` and `hidden`:
```
$ osascript -e 'tell application "System Events" to get properties of login item "Turbo Boost Switcher"'
name:Turbo Boost Switcher, path:/opt/homebrew-cask/Caskroom/turbo-boost-switcher/1.2.0/Turbo Boost Switcher.app, class:login item, kind:Application, hidden:false
```

Among them `path` sounds very interesting.
We already know all cask's links, along with Caskroom directory.
Why don't we check if any cask's files are referenced in Login Items, and remove them judging by their path?

This wouldn't require any extra metadata to keep track and should be safe to make it on by default as it match users expectations.

**Comment by vitorgalvao** [comment]
> We already know all cask's links, along with Caskroom directory.

Not really, since they can be changed, even on an install-by-install basis. That means we can’t really trust we know those values.

Looks like we’ll stick with `name`, then. Thank you for the research.

**Comment by vitorgalvao** [comment]
@forkbomber Would you be interested in working on implementing this? I see you use a “noreply” email address for commits, so I can’t contact you, but would you mind [contacting me](https://github.com/caskroom/homebrew-cask/blob/aab7cc77bb6f09eda7e8ba65b2ba11853fb82028/developer/bin/the_long_tail#L46) so we can briefly talk about it?
