### ISSUE TITLE
reference #{name} inside uninstall_postflight

### ISSUE THREAD

**Issue by forkbomber** [caskroom/homebrew-cask#14853]
`name` doesn't seems to be accessible within `uninstall_postflight` block.
Can we expose it as a list?

For example see e182b36:
```ruby
system '/usr/bin/osascript', '-e', %Q{tell application "System Events" to delete every \
  login item whose name is "#{token.gsub(/\w+/, &:capitalize).gsub('-', ' ')}"}
```
I would be beneficial to be able to replace `#{token.gsub(/\w+/, &:capitalize).gsub('-', ' ')}` with just `#{name.first}`.

**Comment by vitorgalvao** [comment]
We should do this better. Instead of name, the bundle ID should be used. And this is a helpful thing for other casks, so we should have a new `:remove_login_item` (or whatever) for `uninstall`.

**Comment by vitorgalvao** [comment]
I see you have already made an issue about that at https://github.com/caskroom/homebrew-cask/issues/14854.

I’ll close this in favour of that one. Since `name` can be anything and isn’t too strict, relying on it for actual code execution isn’t good.
