### ISSUE TITLE
download gauge causes scrolling storm in narrow windows

### ISSUE THREAD

**Issue by megahall** [caskroom/homebrew-cask#14897]
This is somewhat related to Issue #13077 .

The download gauge for the Cask install files:

`##############################################                            64.9%`

Starts to cause a screen-scrolling storm, if the width of the window is set somewhat narrowly, such as 80 columns, or any other size narrower than the minimum size of the download indicator.

**Comment by vitorgalvao** [comment]
This also happens with `homebrew`, and to some extent even just with `curl`, so it isn’t directly related to us and must be fixed somewhere else (at which point it’ll be solved on our side).
