### ISSUE TITLE
Issue with Symlinking to Applications

### ISSUE THREAD

**Issue by bretterer** [caskroom/homebrew-cask#14912]
So, this has been an issue since I have started using homebrew-cask.

Using PHP Storm as an example, if I run `brew cask install phpstorm` one of the steps is `Symlinking App 'PhpStorm.app' to '/Users/bretterer/Applications/PhpStorm.app`, however, it does not link PhpStorm.app in the Applications folder.  Instead, it makes a symlink TO applications from the 10.0 folder of PhpStorm.

<img width="262" alt="screen shot 2015-11-03 at 12 58 18 pm" src="https://cloud.githubusercontent.com/assets/1906920/10916686/9e39c056-822a-11e5-841e-84409d7d2a75.png">

In my opinion, it should create a symlink in my applications folder to the cask folder.

It does this for more than just the one application.  Any application I install with this has the same thing.

**Comment by vitorgalvao** [comment]
> it makes a symlink TO applications from the 10.0 folder of PhpStorm.

No, it does not. What you are seeing is the common practice of app makers placing a link to `/Applications` inside the dmg for the app. We simply unpacked it, we did not create that link.

**Comment by bretterer** [comment]
Then, shouldn't homebrew cask NOT say the following line.  To me it makes it seem like you are symlinking the application in my Applicaitons folder

<img width="698" alt="screen shot 2015-11-03 at 3 04 29 pm" src="https://cloud.githubusercontent.com/assets/1906920/10920078/4c448bca-823c-11e5-855c-2742f2107a07.png">

**Comment by vitorgalvao** [comment]
And we are.

**Comment by bretterer** [comment]
@vitorgalvao "we are" what?   symlinking the app into the Applications folder?    if that is the case... where is my app?  I can only find it at `/opt/homebrew-cask/Caskroom/phpstorm/10.0`
<img width="165" alt="screen shot 2015-11-03 at 3 07 20 pm" src="https://cloud.githubusercontent.com/assets/1906920/10920138/9d3f3bf6-823c-11e5-9c49-2e7b79a4cbd4.png">

**Comment by vitorgalvao** [comment]
Read the command. It says it symlinked to `/Users/bretteter/Applications`. What you’re showing now is `/Applications`. They are different directories.

Read the [README](https://github.com/caskroom/homebrew-cask/blob/master/README.md). If you want to link to `/Applications`, read [USAGE](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md), you’re looking for the [`--appdir`](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options) option.

**Comment by bretterer** [comment]
@vitorgalvao: Ugh... Im sorry.   

Thank you for that!

**Comment by vitorgalvao** [comment]
You may also want to set

```bash
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
```

in your shell’s startup files. Keep in mind [we’ll stop liking apps when we can](https://github.com/caskroom/homebrew-cask/issues/13201).
