### ISSUE TITLE
Remove boot2docker, docker-machine, and docker-compose?

### ISSUE THREAD

**Issue by SeanSith** [caskroom/homebrew-cask#14949]
As Homebrew has its own packages of these applications, and as they are command line to begin with, is there any reason for these to have what seem to be equivalent packages in homebrew-cask? Can they be removed in favor of the Homebrew version?

**Comment by vitorgalvao** [comment]
For the moment, we’re still different projects with different needs ([that might change, though](https://github.com/caskroom/homebrew-cask/issues/14384)), so some overlap is expected (some people prefer to install through us).

When we merge, we can start removing duplicates across the board.

**Comment by gato-omega** [comment]
Hi guys, I would like to know then... is installing via "brew" or "brew cask" **exactly** the same in this case?

**Comment by adityadalal924** [comment]
In this case, brew will build from source, while brew cask uses prebuilt packages.

Looks like homebrew-cask's docker-machine is a point version ahead as of this moment, but really it's up to you which method of install you prefer.
