### ISSUE TITLE
Add Microsoft Office 2016

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#14945]
Office 2016 for Mac is now officially released and should be installed by the `microsoft-office` cask.

Making an issue as it's quite an involved installer and will likely need some help/discussion.

Information:

Current Latest version: [15.16.0](https://support.microsoft.com/en-us/kb/3097264)

Info: https://jamfnation.jamfsoftware.com/viewProduct.html?id=383&view=info

**Comment by adityadalal924** [comment]
@vitorgalvao I see you created https://github.com/caskroom/homebrew-cask/blob/master/Casks/microsoft-office365.rb which is actually microsoft office 2016 for mac

Is a token rename in order? (`microsoft-office365` -> `microsoft-office` (and the old one can be `microsoft-office-2011`, if need be)

**Comment by vitorgalvao** [comment]
I haven’t created it, [just renamed it](https://github.com/caskroom/homebrew-cask/pull/14186/files). As for the name, see https://github.com/caskroom/homebrew-cask/pull/13372.

@victorpopkov [recommended this course of action](https://github.com/caskroom/homebrew-cask/pull/13372#issuecomment-135800348), and [knows more about it than I do](https://github.com/caskroom/homebrew-cask/pull/13372#issuecomment-135918017), so I trust you two can work out what the best solution is, here.

**Comment by adityadalal924** [comment]
Created two PRs that encompass what I would do (and seems to match the thinking in the earlier issues)

@victorpopkov if that looks good to you, I can merge and resolve
