### ISSUE TITLE
Cannot uninstall cask after `brew update && brew upgrade` brings down a newer version of the cask

### ISSUE THREAD

**Issue by IshmaelYavitz** [caskroom/homebrew-cask#14961]
Is this the expected behavior?

If so, how do I now uninstall the now-outdated `intellij-idea-ce` cask?

     »  (507) 2015-11-04@20:10:57 ishmael@ishcomp-mbp ~/brew update
    Updated Homebrew from 13968e86 to ad955fe0.
    Updated 4 taps (caskroom/cask, caskroom/versions, homebrew/dupes, railwaycat/emacsmacport).
    ==> New Formulae
    <snip>
    ==> Updated Formulae
    <snip>
    ==> Renamed Formulae
    <snip>
    ==> Deleted Formulae
    <snip>
    
     »  (508) 2015-11-04@22:28:25 ishmael@ishcomp-mbp ~/brew outdated
    caskroom/cask/brew-cask (0.56.0, 0.58.0 < 0.59.0)
    glib (2.44.1, 2.46.1 < 2.46.1_1)
    pkg-config (0.28 < 0.29)
    sbcl (1.2.15, 1.2.16 < 1.3.0)
    
     »  (509) 2015-11-04@22:30:40 ishmael@ishcomp-mbp ~/brew upgrade
    ==> Upgrading 4 outdated packages, with result:
    caskroom/cask/brew-cask 0.59.0, glib 2.46.1_1, pkg-config 0.29, sbcl 1.3.0
    ==> Upgrading caskroom/cask/brew-cask
    ==> Cloning https://github.com/caskroom/homebrew-cask.git
    Updating /Library/Caches/Homebrew/brew-cask--git
    ==> Checking out tag v0.59.0
    ??  /usr/local/Cellar/brew-cask/0.59.0: 2976 files, 12M, built in 6 seconds
    ==> Upgrading glib
    ==> Downloading https://homebrew.bintray.com/bottles/glib-2.46.1_1.yosemite.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring glib-2.46.1_1.yosemite.bottle.tar.gz
    ??  /usr/local/Cellar/glib/2.46.1_1: 421 files, 23M
    ==> Upgrading pkg-config
    ==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.yosemite.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring pkg-config-0.29.yosemite.bottle.tar.gz
    ??  /usr/local/Cellar/pkg-config/0.29: 10 files, 648K
    ==> Upgrading sbcl
    ==> Downloading https://homebrew.bintray.com/bottles/sbcl-1.3.0.yosemite.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring sbcl-1.3.0.yosemite.bottle.tar.gz
    ??  /usr/local/Cellar/sbcl/1.3.0: 48 files, 51M
    
     »  (522) 2015-11-04@22:51:42 ishmael@ishcomp-mbp ~/brew cask list -1
    <snip>
    intellij-idea-ce
    <snip>
    
     »  (523) 2015-11-04@22:51:45 ishmael@ishcomp-mbp ~/brew cask uninstall intellij-idea-ce
    Error: intellij-idea-ce is not installed
    
     »  (524) 2015-11-04@22:51:55 ishmael@ishcomp-mbp ~/brew cask list intellij-idea-ce
    Warning: intellij-idea-ce is not installed
    Error: nothing to list
    
     »  (525) 2015-11-04@22:52:00 ishmael@ishcomp-mbp ~/brew cask info intellij-idea-ce
    intellij-idea-ce: 15.0
    IntelliJ IDEA Community Edition
    https://www.jetbrains.com/idea/
    Not installed
    https://github.com/caskroom/homebrew-cask/blob/master/Casks/intellij-idea-ce.rb
    ==> Contents
      IntelliJ IDEA 15 CE.app (app)
    
     »  (526) 2015-11-04@22:52:03 ishmael@ishcomp-mbp ~/ls -la /opt/homebrew-cask/Caskroom/intellij-idea-ce/
    total 0
    drwxr-xr-x   4 ishmael  staff   136 Jul 22 18:13 .
    drwxr-xr-x  37 ishmael  staff  1258 Oct 21 00:11 ..
    drwxr-xr-x   3 ishmael  staff   102 Jul 22 18:13 .metadata
    drwxr-xr-x   8 ishmael  staff   272 Jul 22 18:13 14.1.4
    
     »  (527) 2015-11-04@22:52:07 ishmael@ishcomp-mbp ~/

**Comment by reitermarkus** [comment]
You have to uninstall all existing versions using `--force`, I don't think there is another way.

    brew cask uninstall intellij-idea-ce --force
