### ISSUE TITLE
Update JavaFX Scene Builder to 8.0.0

### ISSUE THREAD

**Issue by SebastianOsinski** [caskroom/homebrew-cask#14973]
Current cask for JavaFX Scene Builder is outdated. The problem is that since Java SE 8u40 Oracle does not provide updated binaries for it. Whole project is open source and there is another source where up-to-date binaries can be found: http://gluonhq.com/open-source/scene-builder/. Yet, I'm not really sure it's place is here as an update to the JavaFX Scene Builder cask or maybe as a new cask in homebrew-unofficial.

**Comment by adityadalal924** [comment]
Existing cask should be removed and a new one can be created in `homebrew-unofficial` pointing to the GluonHQ links.

Care to submit a PR? We can help if you have questions along the way.

**Comment by SebastianOsinski** [comment]
Yes, I will submit both PRs.

**Comment by vitorgalvao** [comment]
Closes in favour of the new PRs.
