### ISSUE TITLE
Blender symlink is not working.

### ISSUE THREAD

**Issue by SushiDude** [caskroom/homebrew-cask#14982]
Blender published a wrong version on their mirrors. The Blender cask was then updated. Blender then published the correct version, causing a sha256 mismatch.

After correcting the sha256sum, I get the following error:
>Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/blender/2.76b/Blender.app'

However, the file layout of the Blender ZIP has not changed from the previous version.

I am not sure what is wrong in this situation.

**Comment by victorpopkov** [comment]
Fixed in 25265b16e7f3928f5ce9996f9ee7dc86169bfa84 and fe00d2b70d41fc37b853beb6d232f3eb9004f359.
