### ISSUE TITLE
Incorrect "official download host" for Audacity

### ISSUE THREAD

**Issue by SteveDaulton** [caskroom/homebrew-cask#15057]
https://github.com/caskroom/homebrew-cask/blob/8a623c23deba478d300428c355d1d547dc096a9d/Casks/audacity.rb 

Incorrect information in comment on line 5:
"oldfoss.com is the official download host per the vendor homepage"
and incorrect URL on line 6:
"url "http://app.oldfoss.com:81/download/Audacity/audacity-macosx-ub-#{version}.dmg""

The official download host is fosshub.com (same people, but different site from oldfoss.com).
The official URL for Audacity 2.1.1 DMG download is:
http://www.fosshub.com/Audacity.html/audacity-macosx-ub-2.1.1.dmg

**Comment by SteveDaulton** [comment]
Corrected file text:

    cask :v1 => 'audacity' do
      version '2.1.1'
      sha256 '266fa1b2f3aff3894730a8b0e9fcf5c24c93e726f15180855d2516c5c44de10e'

      # fosshub.com is the official download host per the vendor homepage
      url "http://www.fosshub.com/Audacity.html/audacity-macosx-ub-#{version}.dmg"
      name 'Audacity'
      homepage 'http://audacityteam.org'
      license :gpl

      app 'Audacity/Audacity.app'
    end

**Comment by vitorgalvao** [comment]
Thank you. But if you know how to correct the cask, why not submit the PR? Do you need help making one?

**Comment by SteveDaulton** [comment]
I don't use homebrew-cask, or even OS X and I don't have a fork of homebrew-cask. I stumbled across your project via a Google search result, and as a member of the Audacity team the error in the audacity.rb file leapt out at me. I assumed that it would be helpful to bring the error to your attention.

**Comment by adityadalal924** [comment]
Some hosting providers actively block command-line HTTP clients (example: FossHub). Such URLs cannot be used in Casks.

Ref: [CONTRIBUTING.md](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#some-providers-block-command-line-downloads)

**Comment by vitorgalvao** [comment]
@SteveDaulton Ah, right. Thank you anyway, though. I was just trying to understand your reasoning. I was expecting you to be a user, and helping you submit a PR would be better than just outright fixing it.

Had actually forgotten about the FossHub issue. Since you’re part of the Audacity team, perhaps you can relay the issue and consider hosting on a more CLI-friendly platform.

**Comment by SteveDaulton** [comment]
I understand that you may need to use oldfoss,com rather than fosshub.com, but it is still incorrect to say that oldfoss.com is the official download host. The official download host for Audacity is fosshub.com.

**Comment by vitorgalvao** [comment]
> but it is still incorrect to say that oldfoss.com is the official download host.

That is a technicality. You still link to it from the official website, and that is what matters.

We will not change that message. It is standard, and we keep those kinds of recurring comments exact to a rule. Makes it way easier (makes it possible at all) to parse them if needed, and that is way more important.
