### ISSUE TITLE
orange hash

### ISSUE THREAD

**Issue by mhemeryck** [caskroom/homebrew-cask#15058]
Did try to install [orange], but had a conflicting sha256 hash.

Proposed fix:

    diff --git a/Casks/orange.rb b/Casks/orange.rb
    index 22f2827..96cee33 100644
    --- a/Casks/orange.rb
    +++ b/Casks/orange.rb
    @@ -1,6 +1,6 @@
     cask :v1 => 'orange' do
       version '2.7.8-7887ad2'
    -  sha256 '312274a81c510227696dd655cc14a1fedd7029f58b67118a97ac7526af18608d'
    +  sha256 '4bcf78dc289a891e188cf61018e177e3006d592e8183f68540d000d0b3b0c48e'
     
       url "http://orange.biolab.si/download/files/Orange-#{version}.dmg"
       name 'Orange'

Looking through its [history], this seems to be a recurring issue. I can update the hash, but has anybody any clue why this keeps on occurring?

[orange]: https://github.com/caskroom/homebrew-cask/blob/master/Casks/orange.rb
[history]: https://github.com/caskroom/homebrew-cask/commits/master/Casks/orange.rb

**Comment by vitorgalvao** [comment]
> but has anybody any clue why this keeps on occurring?

Usually when this happens the package is being updated in place. With such a long version number that seems unlikely here, though. However, it seems the cask is pretty outdated. Will update soon.
