### ISSUE TITLE
Allow brew cask applications as default programs to open certain filetypes

### ISSUE THREAD

**Issue by M4urice** [caskroom/homebrew-cask#15061]
The OS X "Choose Application" dialog (see screenshot) ignores any symlinks created by brew cask. 

*For example:* If I want to assign the `.cfg` filetype to Sublime Text (which I installed with brew cask), I have to navigate to `/opt/homebrew-cask/...`, which might not even be possible if I don't have "show hidden files" enabled.
![screenshot_2015-11-09_16_22_46](https://cloud.githubusercontent.com/assets/1615089/11037635/fe51de50-86fe-11e5-9f3d-f0cd589584c1.png)

**Comment by vitorgalvao** [comment]
There’s nothing we can do, here. This is controlled by the OS.

> I have to navigate to `/opt/homebrew-cask/...`, which might not even be possible if I don't have "show hidden files" enabled.

I don’t see why not. Those shouldn’t be hidden. Either way, you can <kbd>⌘</kbd><kbd>⇧</kbd><kbd>G</kbd> to move to any directory.

This will be made irrelevant by the implementation of https://github.com/caskroom/homebrew-cask/issues/13201, though, so even if we could do something now, we wouldn’t.

**Comment by M4urice** [comment]
You were right about `/opt` being visible after all.
I was just about to ask why Cask doesn't move the `.app` files to `/Applications` (if possible). So I am looking forward to #13201. Thanks!
