### ISSUE TITLE
rro.rb sha256 mismatch

### ISSUE THREAD

**Issue by friendimaginary** [caskroom/homebrew-cask#15117]
The sha256 sum for RRO-3.2.2-OSX.pkg in line 3 of rro.rb should be d7d096f5e258a6b1945235aefcdf9c52b3e63daaa515d39305a864f6a3a7b640.

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.

**Comment by adityadalal924** [comment]
Fixed in #15119
