### ISSUE TITLE
manuscripts.rb sha256 mismatch

### ISSUE THREAD

**Issue by r1pp3r** [caskroom/homebrew-cask#15113]
Hi there, 

I am running OS X 10.11. When I do:

> brew cask install manuscripts

I get: 
> ==> Downloading http://updates.manuscriptsapp.com/apps/manuscripts/production/download
######################################################################## 100,0%
> ==> Note: running "brew update" may fix sha256 checksum errors
> Error: sha256 mismatch
> Expected: adc72c2a7d2c20ced73c775e3aa84e1fee0b25e488be39f12347eb7a0e393dd1
> Actual: 4410ad901b91c76c981f571f031db2e2dadf9c75cb163436e1ded244805a3c6e
> File: /Library/Caches/Homebrew/manuscripts-1.0
> To retry an incomplete download, remove the file above.

**Comment by adityadalal924** [comment]
Fixed in #15121
