### ISSUE TITLE
RapidWeaver.rb -> It seems the symlink source is not there

### ISSUE THREAD

**Issue by r1pp3r** [caskroom/homebrew-cask#15112]
Hi there, 

I am running OS X 10.11. When I do:

>brew cask install rapidweaver`

I get:

>==> Downloading http://realmacsoftware.com/redirects/rapidweaver6/direct
######################################################################## 100,0%
Error: It seems the symlink source is not there: '.../Caskroom/rapidweaver/6.2.3/RapidWeaver.app'

**Comment by adityadalal924** [comment]
Fixed in #15125
