### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#15194]
Was looking at the branches, and it seems like there's a bit of cruft. Figured I'd make an issue just to confirm instead of deleting without feedback.

Are the following branches safe to delete?

```
revert-10854-master : Updated 7 months ago by alebcay
f-https-sourceforge-urls: Updated 8 months ago by phinze
fix-alfred-preference-install: Updated 2 years ago by phinze
audit-links: Updated 3 years ago by phinze
gh-pages: Updated 3 years ago by phinze (caskroom/caskroom.github.io seems to take care of this)
```

**Comment by vitorgalvao** [comment]
Pinging the relevant creators: @alebcay @phinze 

If those branches are something you were working on but since abandoned, deleting them would be better, for organisation.

**Comment by phinze** [comment]
Cleaned up mine! :+1:

**Comment by adityadalal924** [comment]
@phinze They seem to still be there?
<img width="1003" alt="screen shot 2015-11-16 at 1 20 14 pm" src="https://cloud.githubusercontent.com/assets/2555394/11190679/e37700e0-8c64-11e5-850f-39d3ba19b69f.png">

**Comment by alebcay** [comment]
Mine can be safely deleted; I screwed up on a PR once and used GitHub's revert feature, which creates a temporary branch.
