### ISSUE TITLE
google-cloud-sdk requires `uninstall`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#15211]
[`google-cloud-sdk`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-cloud-sdk.rb) has an `installer`, so it needs an `uninstall` as well.

**Comment by jawshooah** [comment]
Shouldn't this be labeled with `cask` and `bug`?

**Comment by vitorgalvao** [comment]
It should yes, you’re right. Fixed. Thank you.

**Comment by jawshooah** [comment]
Cool. Removing this comment and those above, as they aren't pertinent to the issue.

**Comment by vitorgalvao** [comment]
Closing in favour of #6872.
