### ISSUE TITLE
Use bundle ID to generate zap stanzas

### ISSUE THREAD

**Issue by Dremora** [caskroom/homebrew-cask#15218]
Compare zap stanzas for any two apps, e.g. Sublime Text 2:
```
'~/Library/Application Support/Sublime Text 2',
'~/Library/Preferences/com.sublimetext.2.plist',
'~/Library/Caches/com.sublimetext.2',
'~/Library/Saved Application State/com.sublimetext.2.savedState'
```

and Atom:
```
'~/.atom',
'~/Library/Application Support/ShipIt_stderr.log',
'~/Library/Application Support/Atom',
'~/Library/Application Support/ShipIt_stdout.log',
'~/Library/Application Support/com.github.atom.ShipIt',
'~/Library/Caches/com.github.atom',
'~/Library/Preferences/com.github.atom.plist'
```

We can see that paths like `'~/Library/Preferences/com.github.atom.plist'` are formed by combining a well-known directory with a bundle identifier (of course, there can be more than one per package). Storing bundle IDs would allow us to automatically generate partial zap stanzas.
uninstall stanza already allows storing bundle ids, but for a different purpose — perhaps this can be unified?

The list of paths I've gathered so far:
```
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/#{bundleID}.sfl
~/Library/Cookies/#{bundleID}.binarycookies
~/Library/Caches/#{bundleID}/
~/Library/Preferences/#{bundleID}.plist
~/Library/Preferences/#{bundleID}.LSSharedFileList.plist
~/Library/Saved Application State/#{bundleId}.savedState/
```

**Comment by alebcay** [comment]
Storing the bundle ID can also help with writing barebones/boilerplate `uninstall :pkgutil` stanzas, as well as other uninstall keys that rely on bundle IDs (e.g. `:signal`, `:kext`, `:launchctl`).

**Comment by Amorymeltzer** [comment]
See also #8211

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/16339.
