### ISSUE TITLE
New Sococo app

### ISSUE THREAD

**Issue by fuadsaud** [caskroom/homebrew-cask#15238]
http://sococo.com has released a completely rewritten version of their app and have reset version numbering. It's still called sococo and the new installer can be found here: http://s.sococo.com.s3-website-us-east-1.amazonaws.com/rs/client/

The current version - the one that's already present in this repo still works and should't be removed, but I'm not sure how to add the new one (with a different name or over at the versions repo).

How should we proceed?

**Comment by vitorgalvao** [comment]
> The current version - the one that's already present in this repo still works and should't be removed

Yes it should. *At best* it should be removed to [caskroom/versions](https://github.com/caskroom/homebrew-versions) under the name `sococo-legacy`, but there needs to be a strong reason to keep it around.

**Comment by fuadsaud** [comment]
Hmm, I thought it wouldn't be a good idea to remove because it's still going to be supported for some time, but it makes sense to move to a legacy cask. I'll tackle that, thanks!

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/issues/15268 and https://github.com/caskroom/homebrew-versions/issues/1426
