### ISSUE TITLE
android-studio update is available but "brew cask update" doesn't work.

### ISSUE THREAD

**Issue by qxlab** [caskroom/homebrew-cask#15235]
Current is `1.31` and `1.41` is available, in fact even the [cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/android-studio.rb) has it.

As mentioned in the title, running `brew cask update android-studio` returns:

    Updated Homebrew from 47494569 to 53d3735b.
    No changes to formulae.

How do I upgrade a brew cask? 

I am not upgrading it from within the Android Studio app itself for fear of conflicts and breaking something.

**Comment by vitorgalvao** [comment]
> How do I upgrade a brew cask?

You don’t. Best you can currently do is `brew update && brew cask install --force {{your_app_here}}`.

`brew cask update` is just an alias to `brew update`. It takes no arguments.
