### ISSUE TITLE
clamxav 2.8.5: sha256 mismatch

### ISSUE THREAD

**Issue by megahall** [caskroom/homebrew-cask#15234]
I am getting a SHA-256 hash mismatch on this file. Since it's a security problem when hashes do not match, and this is an antivirus / antimalware tool, I wanted to see if anybody else was running into unexpected issues or not. Or is it just a stale cask formula file which was not tested?

```
$ brew cask install clamxav
==> Caveats
Cask clamxav installs files under "/usr/local".  The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in homebrew-cask.

==> Downloading https://www.clamxav.com/downloads/ClamXav_2.8.5.dmg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: d058eb5d27201ba7706c7daa9d8fe9f50597c0ce4fd4174555b60f91d097b955
Actual: 4dfa02c2daec5134ab177707ae3f3b110394f72a4b0df602c538bf31b05d082c
File: /Library/Caches/Homebrew/clamxav-2.8.5.dmg
To retry an incomplete download, remove the file above.
$ 
```

**Comment by vitorgalvao** [comment]
> Or is it just a stale cask formula file which was not tested?

They are tested automatically on submission. It’s more likely the file was updated in place.

We use shasums to check for the integrity of the download, not for security reasons. If you’re that worried, you shouldn’t be using a package manager to download it, anyway, and should be getting it manually from their website.

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/15243

**Comment by megahall** [comment]
I figured it was better to ask than assume. Since it's a security tool.
