### ISSUE TITLE
Rubocop throws an error for extra whitespace at end of comment...

### ISSUE THREAD

**Issue by liljenstolpe** [caskroom/homebrew-cask#15288]
Why is it even looking at comments?  Mildly annoying.

**Comment by vitorgalvao** [comment]
Why are you leaving whitespace at the end of lines? We don’t want that. This is not a bug, it is working as intended.

**Comment by liljenstolpe** [comment]
````

Offenses:
Casks/nanobox.rb:5:43: C: Trailing whitespace detected.
# nanbox just installs the nanobox binary.  
                                          ^^
2860 files inspected, 1 offense detected
RuboCop failed!
The command "/System/Library/Frameworks/Ruby.framework/Versions/"${CASK_RUBY_TEST_VERSION}"/usr/bin/bundle exec "/System/Library/Frameworks/Ruby.framework/Versions/${CASK_RUBY_TEST_VERSION}/usr/bin/rake" rubocop" exited with 1.
0.00s$ developer/bin/audit_modified_casks "${TRAVIS_BRANCH}..${TRAVIS_COMMIT}"
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
audit for nanobox: passed
The command "developer/bin/audit_modified_casks "${TRAVIS_BRANCH}..${TRAVIS_COMMIT}"" exited with 0.
Done. Your build exited with 1.
````

**Comment by liljenstolpe** [comment]
It was unintentional.  I understand in code blocks, but comments?

**Comment by vitorgalvao** [comment]
What does it matter if it was unintentional? It should still not be there. It is not annoying to be warned about it, it is annoying it is there. Amongst other things, it can make automatic parsing of stuff harder. We have to be rigid about structure, and we even have an [.editorconfig](https://github.com/caskroom/homebrew-cask/blob/master/.editorconfig) that supports this as a requisite.

We’re not going to change it.

**Comment by liljenstolpe** [comment]
That's fine.  Accept the decision.
