### ISSUE TITLE
error installing freefilesync

### ISSUE THREAD

**Issue by stalker8exe** [caskroom/homebrew-cask#15320]
brew cask install freefilesync
==> Downloading http://www.freefilesync.org/download/m9fd99e69p2a6j6/FreeFileSync_7.5_Mac_OS_X_64-bit.zip
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 3da2b42915733d0da4ba53a059cfb7c191a9a3a1d6c656c66965111da70776cc
Actual: 580af14cbdead14a944bea183616b5581cb7e6d017c1ee071d8ea8111b2171e3
File: /Library/Caches/Homebrew/freefilesync-7.5.zip
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.

**Comment by adityadalal924** [comment]
Fixed by https://github.com/caskroom/homebrew-cask/issues/15321
