### ISSUE TITLE
running cask from cron

### ISSUE THREAD

**Issue by famousj** [caskroom/homebrew-cask#15356]
I'm trying to maintain a list of all the casks I have installed, by running this from cron:

`/usr/local/bin/brew cask list > $HOME/blahblahblah/cask_packages.txt`

Cron then errors out thusly:

`Error: Unknown command: cask`

I'm guessing cron doesn't have the environment setup correctly, so I need to do some kind of homebrew witchcraft to run the cask ruby script directly and/or tell homebrew where to find cask.  Anyone have any ideas?

**Comment by adityadalal924** [comment]
Try using `brew-cask` instead of `brew cask` - just a suggestion, as I haven't played around with cron (I use aliases and a ruby gem to do upgrades)

**Comment by vitorgalvao** [comment]
Closing for lack of reply.
