### ISSUE TITLE
QGIS installer fails

### ISSUE THREAD

**Issue by emilbayes** [caskroom/homebrew-cask#15421]
When installing `QGIS-2.12.0-1.dmg` after having installed `homebrew/python/matplotlib` I get the following output:

```sh
$ brew cask install qgis
==> Caveats
qgis requires matplotlib in a specific location. Please run the following to finish install:

  sudo ln -s /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python /Library/Python/2.7/site-packages/matplotlib-override

==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
matplotlib ... already installed
==> Installing Cask dependencies: gdal-framework
gdal-framework ...
already installed
complete
==> Downloading http://www.kyngchaos.com/files/software/qgis/QGIS-2.12.0-1.dmg
Already downloaded: /Library/Caches/Homebrew/qgis-2.12.0-1.dmg
==> Running installer for qgis; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Error - QGIS requires the Matplotlib python module (kyngchaos build).
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/qgis/2.12.0-1/Install QGIS.pkg>", "-target", "/"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 63464 exit 1>
```

This seems to be related to issue #15131.
However #13359 seems to indicate that the homebrew version of matplotlib is pretty outdated and I tried installing through `pip`. Then the formula fails:

```sh
$ brew cask install qgis
==> Caveats
qgis requires matplotlib in a specific location. Please run the following to finish install:

  sudo ln -s /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python /Library/Python/2.7/site-packages/matplotlib-override

==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
matplotlib ... ==> Error: You must `brew link numpy` before homebrew/python/matplotlib can be installed
Error: Command failed to execute!

==> Failed command:
["#<Pathname:/usr/local/bin/brew>", "install", "matplotlib"]

==> Output of failed command:
==> Installing matplotlib from homebrew/homebrew-python


==> Exit status of failed command:
#<Process::Status: pid 72575 exit 1>
```

**Comment by vitorgalvao** [comment]
```
matplotlib ... ==> Error: You must `brew link numpy` before homebrew/python/matplotlib can be installed
Error: Command failed to execute!
```

Have you done so?

Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by emilbayes** [comment]
Thanks for the help, that was the issue! Sorry for any inconvenience

**Comment by zmpeg** [comment]
I received this error also, it is clearly due to some part of the install process that does not symlink a file. I manually ran that symlink and then restarted the install and everything worked. Before that, the message I get is:

    mz-mbp~/projects/tesera/geocoder(master|✔) % brew cask install qgis
    ==> Caveats
    qgis requires matplotlib in a specific location. Please run the following to finish install:
        sudo ln -s /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/Library/Python/2.7/site-packages/matplotlib-override

**Comment by vitorgalvao** [comment]
@zmpeg That’s not an error, it’s a message we always output. Do `brew cask info qgis` and you’ll see.
