### ISSUE TITLE
qtox cask URL needs updating

### ISSUE THREAD

**Issue by wfdd** [caskroom/homebrew-cask#15420]
The qTox team is not in possession of the `tox.im` domain since July; please refer to tux3/qTox#2033 and [this](https://blog.tox.chat/2015/07/current-situation-3/) blog post. In addition, Tox no longer provide a link to a qTox build on their [website](https://www.tox.chat/) and suggest OS X users download μTox, though there appears to be an official OS X qTox fork at [RowenStipe/qTox-OSX](https://github.com/RowenStipe/qTox-OSX).

Paging @tux3 and @RowenStipe for their input.

**Comment by adityadalal924** [comment]
I've gone ahead and removed `qtox.rb` as it is currently defunct (and apparently also a security issue). Based on the input from upstream, a new cask for uTox or qTox can be created.

**Comment by adityadalal924** [comment]
@wfdd Added in uTox cask, and as there's no upstream input I'm closing the issue.

**Comment by wfdd** [comment]
Thanks, Aditya.

**Comment by vitorgalvao** [comment]
Looks like [qTox is back alive](https://github.com/tux3/qTox), and has [a website of its own](https://qtox.github.io/).

Getting a PR at https://github.com/caskroom/homebrew-cask/pull/21774.
