### ISSUE TITLE
Gateblu won't symlink after being downloaded

### ISSUE THREAD

**Issue by n370** [caskroom/homebrew-cask#15440]
I'm not sure why this is happening but here it is.

Homebrew 0.9.5 (git revision 8f39d; last commit 2015-11-25)

```bash
dylson-macosx:~ n370$ brew cask install gateblu
==> Downloading https://s3-us-west-2.amazonaws.com/gateblu/gateblu-ui/latest/Gateblu.d
######################################################################## 100.0%
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/gateblu/latest/Gateblu.app'
```

```bash
dylson-macosx:~ n370$ brew cask install gateblu --vebose
==> Downloading https://s3-us-west-2.amazonaws.com/gateblu/gateblu-ui/latest/Gateblu.d
Already downloaded: /Library/Caches/Homebrew/gateblu-latest.dmg
==> hdiutil: mount failed - Resource busy
Error: Empty plist input
```

I finally installed it manually using the downloaded DMG

```bash
dylson-macosx:~ n370$ open /Library/Caches/Homebrew/gateblu-latest.dmg 
```

Then I searched for help a little bit more but still got the issue.

```bash
dylson-macosx:~ n370$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: caskroom/cask/brew-cask 0.59.0 already installed
dylson-macosx:~ n370$ brew cask install --verbose gateblu
==> Downloading https://s3-us-west-2.amazonaws.com/gateblu/gateblu-ui/latest/Gateblu.dmg
Already downloaded: /Library/Caches/Homebrew/gateblu-latest.dmg
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/gateblu/latest/Gateblu.app'
dylson-macosx:~ n370$ brew -v
Homebrew 0.9.5 (git revision 82f27; last commit 2015-11-26)
dylson-macosx:~ n370$ 
```

I'm going to try to use the the gateblu I installed from the downloaded binary which is now on Service Version: 5.0.6, UI Version: 3.4.8

**Comment by n370** [comment]
@adityadalal924 I followed your instructions here #11457 and forked the repo to fix it myself. Could you point me out where I should look for in order to make the recipe work with a .pkg instead of a .app? Thank you!

**Comment by adityadalal924** [comment]
Sure.

You want to start out by replacing the app stanza with a pkg stanza -> See https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#pkg-stanza-details

Additionally, we require all Casks with a package installer to come with an uninstall, see https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-key-pkgutil

Finally, if you are so inclined, you can add in a zap stanza, which will clean-up leftover files (You can use something like AppCleaner or UninstallPKG to poke around) - but this is not required.

Feel free to post additional questions here if you get stuck - we're here to help and love seeing people contribute!

**Comment by n370** [comment]
Hey @adityadalal924 please have a look here #15450. Thank you!

**Comment by vitorgalvao** [comment]
Closing in favour of #15450.
