### ISSUE TITLE
Formula request: weidu

### ISSUE THREAD

**Issue by andreis** [caskroom/homebrew-cask#15449]
http://www.weidu.org/~thebigg/

> WeiDU is designed to make it easier to write and distribute modifications to Infinity Engine games. It can load and modify Infinity Engine resources according to instructions you provide. WeiDU is ideal for packaging modifications that include dialogue or that want to be compatible with other modifications.

from the [readme](http://www.weidu.org/~thebigg/README-WeiDU.html)

**Comment by andreis** [comment]
Actually, it might not be that useful to `brew cask install` this after all.

https://forums.beamdog.com/discussion/31155/the-hitchhikers-guide-to-installing-mods-on-osx

**Comment by vitorgalvao** [comment]
Should we close this, then?

**Comment by andreis** [comment]
Yeah, sorry about that.
