### ISSUE TITLE
Update qlmarkdown to v1.3.4

### ISSUE THREAD

**Issue by JaHIY** [caskroom/homebrew-cask#15455]
Please checkout it!
https://github.com/toland/qlmarkdown/releases

**Comment by vitorgalvao** [comment]
Care to submit a PR? It isn’t a complex fix, and we’re here to help.

**Comment by Caf** [comment]
I don't know how to do it but I'm interested as well. ;)

**Comment by JaHIY** [comment]
@vitorgalvao please checkout #15459
