### ISSUE TITLE
Adobe Reader SSL Error

### ISSUE THREAD

**Issue by thehouseorgan** [caskroom/homebrew-cask#15480]
Hi,

Having problems installing adobe-reader:
```
==> Downloading https://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/1500

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Download failed on Cask 'adobe-reader' with message: Download failed: https://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/1500920069/AcroRdrDC_1500920069_MUI.dmg
```

If you try downloading in a browser you get a security warning. Basically the SSL certificate is only valid for "a248.e.akamai.net, *.akamaihd.net, *.akamaihd-staging.net, *.akamaized.net, *.akamaized-staging.net" which is presumably the content delivery service adobe are using.

This seems to be triggered by the update to https 5 days ago in the adobe-reader.rb
If I manually edit back to http it installs fine (though I'm not suggesting this is a permanent solution).

This isn't a cask bug per se but thought I'd highlight the problem.

Thanks

**Comment by adityadalal924** [comment]
Based on a script found on [JAMF Nation](https://jamfnation.jamfsoftware.com/discussion.html?id=12042), it seems that `http` is currently in use. (`https` also throws up an error for me)

Updating the cask accordingly.

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/15493
