### ISSUE TITLE
Firealpaca failed to be installed

### ISSUE THREAD

**Issue by ninjahoahong** [caskroom/homebrew-cask#15512]
When I install Firealpaca with brew-cask. I got this problem: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/firealpaca/latest/FireAlpaca.app'.  The .zip file is already downloaded successfully. What is a possible problem here? Thanks for your help.

**Comment by vitorgalvao** [comment]
Usually this happens because the name of the app changed, or it was put inside a subdirectory of something similar. Basically, inside its package it is no longer exactly where it used to be.

The solution is to download the package manually and check how it is structured now.

**Comment by ninjahoahong** [comment]
Thank you. I will try so.

**Comment by vitorgalvao** [comment]
Let us know if you get stuck.

**Comment by ninjahoahong** [comment]
I checked the folder of installation. I changed it from 'latest' to the current version '1.5.2', and it worked for me. I make a pull request to fix the problem. Thank you for helping.

**Comment by vitorgalvao** [comment]
Thank you. Closing this in favour of https://github.com/caskroom/homebrew-cask/pull/15538.
