### ISSUE TITLE
Add Issue template

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#15578]
Ran into this cool little feature while searching for something. Looks useful for prefilling in fenced code blocks and other niceties.

http://archetyped.com/know/guided-github-reports/

Opening this issue to get some feedback & to track progress.

**Comment by vitorgalvao** [comment]
What a nice feature.

I wonder if it’d be useful for us, tough. We don’t have a lot of requirements for reporting bugs, and the people this would be useful for are exactly the people who do not read those instructions, which means they likely wouldn’t find the link, anyway.

What I mean is I see this as a great feature when people are outside the github page and we invite them to submit. However, if you’re already on the github page (which I’d wager is the majority of people, though I have no data on this), you likely won’t click the link anyway.

However, this answer is filled with “likelies” and assumptions without supporting evidence, so no harm in trying it out if you think it’s valuable. You’ll have my interested support and reviews for this, as with everything else, if deciding to go this route.

**Comment by jawshooah** [comment]
Perhaps we could feature the link more prominently in the README, near the top?

**Comment by vitorgalvao** [comment]
No objections there.

**Comment by jawshooah** [comment]
Here are a few samples I whipped up. Let me know what you think:

* [Issue](https://github.com/caskroom/homebrew-cask/issues/new?title=Issue:%20&body=%23%23%23%20Description%20of%20issue%0A%0A%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20%3Ccommand%3E%20--verbose%60%0A%0A%60%60%60%0A%3Cpaste%20output%20here%3E%0A%60%60%60%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20doctor%60%0A%0A%60%60%60%0A%3Cpaste%20output%20here%3E%0A%60%60%60%0A)
* [Feature request](https://github.com/caskroom/homebrew-cask/issues/new?title=Feature%20request:%20&body=%23%23%23%20Description%20of%20feature/enhancement%0A%0A%0A%0A%23%23%23%20Justification%0A%0A%0A%0A%23%23%23%20Example%20use%20case%0A)
* [Cask request](https://github.com/caskroom/homebrew-cask/issues/new?title=Cask%20request:%20&body=%23%23%23%20Cask%20details%0A%0A**Name**%20-%0A**Homepage**%20-%0A**Description**%20-%0A)

**Comment by adityadalal924** [comment]
For the issue template - adding in a reminder to run `brew update ; brew cleanup ; brew cask cleanup` at the top would be good.

Feature request looks good.

Cask request - Possibly add a line (Please fill out as much as possible), and then add in lines for license and download URL.

**Comment by jawshooah** [comment]
Maybe something like this at the top of the issue template:

```md
### The Issue Reporter's Pledge

I have run `brew update ; brew cleanup ; brew cask cleanup`, and the issue persists.
```

I'm only half-joking.

**Comment by adityadalal924** [comment]
I rather like it, though chances are people who use the correct link would likely have actually read things :laughing: 

I'm a proponent of delegating the "important" notice (about linking -> moving) apps, and the badges as well. (Maybe also removing the freenode chat bullet and removing the "open chrome" bash line), but that is probably a discussion for another day...

**Comment by jawshooah** [comment]
Here are the current templates, with @adityadalal924's additions:

### Issue:

    Remember to run `brew update ; brew cleanup ; brew cask cleanup` before reporting your issue. It usually fixes things!

    ### Description of issue



    ### Output of `brew cask <command> --verbose`

    ```
    <paste output here>
    ```

    ### Output of `brew cask doctor`

    ```
    <paste output here>
    ```

### Feature request:

    ### Description of feature/enhancement



    ### Justification



    ### Example use case

### Cask request:

    ### Cask details

    (Please fill out as much as possible)

    **Name** - 
    **Homepage** - 
    **License** - 
    **Download URL** - 
    **Description** -

**Comment by vitorgalvao** [comment]
Thumbs up to those. The cask request one may actually encourage people to try and submit the cask file.
