### ISSUE TITLE
hashcat installation problem

### ISSUE THREAD

**Issue by gothicpurple** [caskroom/homebrew-cask#15597]
$ brew cask install hashcat
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
unar ... already installed
complete
==> Downloading https://hashcat.net/files/hashcat-0.50.7z
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: ecbe4300306e929397f4e721f7b8476208e1be079caa2cd3c2a819fa225ca415
Actual: 6dfc180d716d2db4b844885de7dc835369f3b101c340ee29ab3039179beaf01c
File: /Library/Caches/Homebrew/hashcat-0.50.7z
To retry an incomplete download, remove the file above.

I tried:
- installing using --force
- uninstall and reinstall
- brew update && brew upgrade
- "cleanup" in both homebrew and cask and tried again

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/15598. cleanup and try installing again. 

The version in cask was quite outdated (0.5 vs 2.00).

Feel free to check out CONTRIBUTING.md and submit a fix next time you run into an outdated Cask, we're here to help!
