### ISSUE TITLE
navicat-for-postgresql sha256 mismatch

### ISSUE THREAD

**Issue by atipugin** [caskroom/homebrew-cask#15609]
Can't install `navicat-for-postgresql`, it fails with following:

```shell
==> Downloading http://download.navicat.com/download/navicat111_pgsql_en.dmg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: b0f0bf0a70f4399bdf66d683a83749aa85a1e17b183249ac690d32be9e9c4500
Actual: 825ac85ecbe2d1df43dd2b7ba94fea625ae3468fc73459cc56bab0206472affd
File: /Library/Caches/Homebrew/navicat-for-postgresql-11.1.15.dmg
To retry an incomplete download, remove the file above.
```

Tried updating `brew`/`brew cask`, removing cache and re-installing it - didn't help ;(

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/15614. Update and remove cache and you should be good to go.

You're more than welcome to open a PR next time, program updates like this are generally a very quick fix and we're here to help if you get stuck!

**Comment by atipugin** [comment]
Thanks, i'll next time ;)
