### ISSUE TITLE
install flag: don't continue if .app directory already exists

### ISSUE THREAD

**Issue by bradynpoulsen** [caskroom/homebrew-cask#15627]
I'm loving cask but would find this feature VERY useful.

I would like to provide `brew cask install` a flag/argument that indicates it should either prompt me or fail if any `/Applications/*.app` directories already exist that the cask would overwrite. ie,

```
$ brew cask install --safe google-chrome
```

Use Case: I have a development environment setup script for my personal and work environments. If I decide to share my script, I don't want applications that were already installed manually to be overwritten by cask.

**Comment by vitorgalvao** [comment]
We already abort in such a case. We’re conservative about breaking environments.
