### ISSUE TITLE
Hide /opt

### ISSUE THREAD

**Issue by pierrickrouxel** [caskroom/homebrew-cask#15649]
I think it could be better to hide /opt to the finder. It's more compliant with OS design.

You can add `chflags hidden /opt` to install.

What do you think about that?

**Comment by vitorgalvao** [comment]
> It's more compliant with OS design.

No, it is not. `/opt` is part of the system [and has a clear purpose](http://www.pathname.com/fhs/pub/fhs-2.3.html#OPTADDONAPPLICATIONSOFTWAREPACKAGES), it’s not created by us.

Hiding things without user knowledge or permission is precisely the type of things we won’t do.

**Comment by pierrickrouxel** [comment]
Ok thanks, I don't know why but this folder wasn't present on my system before the caskroom installation and It has been created visible.
