### ISSUE TITLE
FontForge download missing

### ISSUE THREAD

**Issue by sscotth** [caskroom/homebrew-cask#15689]
```bash
$ brew cask install fontforge
==> Satisfying dependencies
complete
==> Downloading https://github.com/fontforge/fontforge/releases/download/20150824/FontForge-20150824.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'fontforge' with message: Download failed: https://github.com/fontforge/fontforge/releases/download/20150824/FontForge-20150824.dmg
```

I tried to look for the an updated release, but couldn't find one. [Their website](https://fontforge.github.io/en-US/downloads/mac/) still references the URL, but I don't see it under [Github Releases](https://github.com/fontforge/fontforge/releases)

**Comment by Amorymeltzer** [comment]
I don't know, but just perusing their page it looks like they had a serious unknown error, and most likely renamed `FontForge-20150824.dmg` to `FontForge-20150824-Terminal_only.dmg` to warn people.  The cask file could be updated with a new dl link and a caveat, but IMO this is an upstream error that needs fixing on their end.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/16020.
