### ISSUE TITLE
Cask Request: Import.io

### ISSUE THREAD

**Issue by codeapps** [caskroom/homebrew-cask#15704]
### Cask details

(Please fill out as much as possible)

**Name** - Import.io

**Homepage** - https://import.io/

**License** - Free

**Download URL** - https://import.io/download

**Description** - Create custom APIs or crawl entire websites using Import.io desktop app

**Comment by codeapps** [comment]
Download Site https://import.io/download

**Comment by adityadalal924** [comment]
Care to open a PR? [Making a new cask isn't hard](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md), and we're here to help!

**Comment by adityadalal924** [comment]
@codeapps I updated your first post with our new Cask request template.

Leaving this issue open, but you're always welcome to [make the Cask yourself](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md) and submit it.
