### ISSUE TITLE
therein cask error:  It seems the symlink source is not there

### ISSUE THREAD

**Issue by oillio** [caskroom/homebrew-cask#15717]
I am trying to install thebrain, on El Cap.

> brew cask install thebrain
==> Downloading http://assets.thebrain.com/downloads/TheBrain_macos_JRE_8_0_1_8.dmg
Already downloaded: /Library/Caches/Homebrew/thebrain-8.0.1.8.dmg
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/thebrain/8.0.1.8/TheBrain.app'

**Comment by adityadalal924** [comment]
Version 8.0.2.1 changed to an install4j installer, so the Cask needs to be updated. 

Care to make a PR? You can take a look at the jdownloader cask, I think it uses a similar install method.

**Comment by oillio** [comment]
Yeah, I'll take a crack at it in a bit.

**Comment by oillio** [comment]
Done. PR #15728
