### ISSUE TITLE
Failed to download resource "brew-cask"

### ISSUE THREAD

**Issue by erow80** [caskroom/homebrew-cask#15730]
I've been using Caskroom for awhile now but ran into an issue today, so I uninstalled it and now cannot seem to reinstall:

```
$ brew install caskroom/cask/brew-cask
==> Installing brew-cask from caskroom/cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Updating /Library/Caches/Homebrew/brew-cask--git
fatal: Couldn't find remote ref refs/tags/v0.60.0
Error: Failed to download resource "brew-cask"
Failure while executing: git fetch -q origin
```

**Comment by jawshooah** [comment]
Wow, you must have tried that within the 5 minutes between merging #15381 and tagging v0.60.0!

`brew update` and try again. Then check the `caveats` :wink:

**Comment by adityadalal924** [comment]
Additionally, to reinstall, you need to use `brew tap caskroom/cask` to (re)install now, I believe.

**Comment by jawshooah** [comment]
You `brew tap caskroom/cask` if you've never done so before, yeah. Then `brew update` takes care of the rest forever after.

**Comment by erow80** [comment]
Thanks guys. I will try tomorrow when I'm back at work and post the result here.

**Comment by jawshooah** [comment]
Actually, even that is no longer necessary. Homebrew now auto-taps us for you (and runs `brew install brew-cask`, but that should change after Homebrew/homebrew#46845).

**Comment by jawshooah** [comment]
@erow80 Just to be clear, I was being cute in my initial comment. There's no need to `brew install brew-cask` anymore. Just `brew tap caskroom/cask` as @adityadalal924 said and you'll be good to go.

**Comment by erow80** [comment]
@jawshooah Oh yeah, totally got the joke 👀

**Comment by ryankask** [comment]
I had an issue this morning when I ran `brew update`:

```
$ brew update
Updated Homebrew from 0763b866 to dcb3cf09.
Updated 1 tap (caskroom/cask).
Error: Could not link caskroom/cask manpages to:
  /usr/local/share/man/man1/brew-cask.1

Please delete these files and run `brew tap --repair`.
```

I then ran

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have external commands with conflicting names.

Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb

These commands didn't work. Eventually I just did:

```
$ brew untap caskroom/cask
$ brew rm brew-cask
$ brew cask
```

And everything seems fine now

**Comment by jawshooah** [comment]
@ryankask points out an issue that @DomT4 previously brought up in [#15381 (comment)](https://github.com/caskroom/homebrew-cask/pull/15381#issuecomment-163386787).

The easiest way to get around this is to `brew uninstall --force brew-cask; brew update`. @vitorgalvao, @adityadalal924, should we add a section to the README on upgrading from legacy versions?

**Comment by ryankask** [comment]
Thanks for the quick response.

I first checked the issues and saw this one listed first. Had I read the changelog I wouldn't have had the issue.

**Comment by vitorgalvao** [comment]
> @vitorgalvao, @adityadalal924, should we add a section to the README on upgrading from legacy versions?

We should, yes. At the moment, that is even more important than the “going away from linking comment”.

**Comment by erow80** [comment]
`brew update` resolved my original issue. Thanks.
