### ISSUE TITLE
wch-ch34x-usb-serial-driver: Mirror; Yosemite & El Capitan compatibility

### ISSUE THREAD

**Issue by tjanson** [caskroom/homebrew-cask#15753]
The [WCH CH34x USB Serial driver cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wch-ch34x-usb-serial-driver.rb) has two problems:

1. The website from which the pkg is downloaded is often slow or entirely unavailable, and has been for months. I suppose this is one of those cases where a mirror would be appropriate (like [this one](http://kiguino.moos.io/downloads/CH341SER_MAC.ZIP) on @kigster's blog), right?

2. The driver does not work "out of the cask" on either Yosemite or El Capitan, apparently because it is unsigned. The typical workaround is [disabling the signature check (or using an alternative, signed driver)](http://kiguino.moos.io/2014/12/31/how-to-use-arduino-nano-mini-pro-with-CH340G-on-mac-osx-yosemite.html) (again @kigster's blog).
That doesn’t sound like something this cask should do, but neither should the install essentially fail silently. Maybe we should add a notice to the `caveats`?

**Comment by adityadalal924** [comment]
We can pull this cask from the main repo and put it into `caskroom/unofficial` with the changes you have suggested. Then, you could `brew cask install caskroom/unofficial/wch-ch34x-usb-serial-driver` and have things work with no further issues.

Ideally, all Casks in this repo should work out of the box on the latest OS X, so it might make sense to tombstone this cask, anyway.

**Comment by adityadalal924** [comment]
@xyb I see you originally created the Cask, thoughts on the above discussion?

**Comment by tjanson** [comment]
To be honest, I’m not sure that "Please disable kernel extension signature check" should *ever* be part of a cask. (I have no idea what the security implications are.) But I’ve added `caveats` to the cask that at least mention that this is the problem (see PR above).

As for the signed driver that’s making the rounds: It works fine, but there is no official download. (Apparently is was obtained via email from one of the involved companies but never officially published.) It might be a fit for `caskroom/unofficial`, though it still makes me uncomfortable considering that we’re talking about a kext from an unknown source.

Also, I don’t know how to write a formula. [Here’s an attempt, but I’m 90% sure the uninstall stanza is wrong.](https://gist.github.com/tjanson/e1b52d2218782998589c)

**Comment by xyb** [comment]
@adityadalal924, I think neither unsigned kernel extension nor the 'looks like' official signed driver is suitable for main repo. I agree with put it into unofficial repo until WCH release signed driver officially.

@tjanson, I don't know which choose is better. But I like the pretty new driver. I have commented on your gist.

**Comment by adityadalal924** [comment]
@xyb Thank you for the info about the Cask.

@tjanson Please make a PR (what you currently have in the gist is fine as a starting point) in `caskroom/unofficial` and we can continue the conversation there.

**Comment by kigster** [comment]
Hey guys – I am the author of the [blog post](http://kiguino.moos.io/2014/12/31/how-to-use-arduino-nano-mini-pro-with-CH340G-on-mac-osx-yosemite.html), that talks about various options for installing it.

As of a few weeks ago a new driver was circulated, which apparently was sent directly by the developer to someone in Germany.  This driver is apparently signed, and seems to work.  I had to install it twice for some reason, but it does seem to work.

The new driver is here: [CH34x_Install.zip](http://kiguino.moos.io/downloads/CH34x_Install.zip)

It would indeed be very nice to have this installed via homebrew. 

Let me know if I can help.

**Comment by adityadalal924** [comment]
@kigster Thanks for dropping into the conversation.

It can now be installed with the command `brew cask install caskroom/unofficial/wch-ch34x-usb-serial-driver`. (You can add this to the blog post if you want - as long as users have a working Homebrew (Cask), this command will work).

We can't put it into the main repository as it's not an official release, but the above command will allow it to be installed from our `homebrew-unofficial` tap

**Comment by cefn** [comment]
This cask fails when trying to access the removed 'unofficial' caskroom on github, (in my case spuriously triggering an authentication request). 

In fact the proper way to invoke this install for a CH340, given the new location of unofficial is...

    brew cask install alehouse/unofficial/wch-ch34x-usb-serial-driver

...which worked on my el Capitan system, although it seemed to be picky about which USB ports to work on (didn't work on an unpowered hub, but that may be for power draw issues from the ESP8266 module attached to my CH34x).
