### ISSUE TITLE
Additional files

### ISSUE THREAD

**Issue by liborw** [caskroom/homebrew-cask#15764]
Hi,

I'm trying to update cask for KiCad, however, the installation require some files to be copied into `Application Support` directory, is there some way how to do this? Thanks.

**Comment by adityadalal924** [comment]
PR is here github.com/caskroom/homebrew-cask/pull/15692

Waiting on a method to ensure that the kicad folder is created, so that kicad-extras installs successfully. 

Feel free to add to the conversation there
