### ISSUE TITLE
Should we deprecate cask DSL versions?

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#15782]
With #15381 out of the way, casks should no longer be out of sync with the core library. From here on out, no cask should ever be using a DSL that's newer than the one in core (since updating casks requires running `brew update`, which will update core as well).

So what's the point of maintaining a DSL version? Keep in mind that if we do so, every time a cask update includes a new DSL element, we'll need to remember to bump the header as well.

/cc @caskroom/maintainers

**Comment by jawshooah** [comment]
The way I see it, these are the problem scenarios:

- We make breaking changes to the DSL, and:
  - we forget to update a cask in one of our repos
  - an external tap maintainer is slow to catch up

In either case, we would error out regardless of whether we checked the cask's DSL version. So I don't see the point in the added maintenance burden.

@mikemcquaid, I'm curious to hear your take on this. How does Homebrew handle breaking DSL changes?

**Comment by vitorgalvao** [comment]
I’m all in favour of this.

**Comment by adityadalal924** [comment]
Also in favor of this. Would also encourage contributions like https://github.com/caskroom/homebrew-cask/pull/15643 as they purely add functionality - and we should make that contribution process as easy as possible.

**Comment by mikemcquaid** [comment]
@jawshooah We basically never (intentionally) break backwards compatibility and just tell people to `brew update` if they hit forwards compatibility issues. When we're deprecating parts of our API we never actually remove the API method but make them print warnings on use and then eventually fail (which means the `Formula` parses but fails at audit or run time).

**Comment by jawshooah** [comment]
@mikemcquaid That sounds like a good strategy going forward.

Closing this, since it seems we have a consensus. Maintainers, feel free to re-open if you think this requires more discussion.
