### ISSUE TITLE
info subcommand could do with a --verbose option

### ISSUE THREAD

**Issue by paul-hammant** [caskroom/homebrew-cask#15785]
--verbose would print the location of the ruby formula on the local system (Googling isn't finding it for me)

    $ brew cask info --verbose pycharm-ce
    pycharm-ce: 5.0.2
    PyCharm, PyCharm Community Edition, PyCharm CE
    https://www.jetbrains.com/pycharm
    Not installed
    https://github.com/caskroom/homebrew-cask/blob/master/Casks/pycharm-ce.rb
    ==> Contents
      PyCharm CE.app (app)
    Kernel.exit

As it happens I'm trying to work out if Homebrew has updated to Pycharm 5.0.2 (seems formula has) .. yet when I open it it is 5.0.1. Yes, I've checked I'm opening ~/Applications/PyCharm\ CE.app and that there's no /Applications/PyCharm\ CE.app lurking there at a previous version.

**Comment by tsparber** [comment]
To update a installed cask you need to reinstall using `brew cask install --force pycharm-ce` (To view a cask you can use `brew cask cat pycharm-ce` or to edit use `edit` instead of cat)
