### ISSUE TITLE
uTorrent installs adware, can we do something about it ?

### ISSUE THREAD

**Issue by diimdeep** [caskroom/homebrew-cask#15799]
So I installed uTorrent but totally forgot about bundled adware that installs to all browsers on system (extensions, changing homepage and default search engine) at first launch. Use Caveats to warn user or maybe remove it from caskroom ?

**Comment by vitorgalvao** [comment]
I’d have no quarrel with removing it. I’d also have no quarrel with removing Adobe software, though.

We had the discussion at the time utorrent started doing this. We’re not a discoverability service, so users should know what they are installing before installing it. some users do indeed want utorrent no matter what, so this is an upstream matter, not something we can fix.

Having said all that, though user-hostility might be debatable (Adobe), bundling adware is fact, so we could indeed take a stance here. That would, however, also mean we should take a stance against every sourceforge cask, as they’re becoming shadier and shadier, and we know they’re starting to bundle adware with their downloads. This is something I’ve though about before.

For the moment, I’m more inclined to leave this here. I’d like to see opinions from other maintainers and users as well, though, so lets leave the discussion open a while longer.

**Comment by vitorgalvao** [comment]
We won’t do it with caveats, though. For one, their not meant for such messages, but since their shown after the software is installed, it’d be pretty much useless, anyway.

**Comment by diimdeep** [comment]
Actually in this case, adware installed only at first launch, so message
might help.

**Comment by adityadalal924** [comment]
@diimdeep May I recommend Transmission, as an alternative?

I think we should remove `utorrent` if an ad-free installer isn't available. (JDownloader also installs adware, but we used a clean DL link)

**Comment by vitorgalvao** [comment]
> I think we should remove `utorrent` if an ad-free installer isn't available.

Keep in mind any decision in this direction also means weeding out sourceforge casks, and there are many of those. When we’re talking about removing `utorrent`, here, we’re also talking about removing a bunch of other casks.

Like I said, many people do still want `utorrent` either way (as want `jdownloader`, in whatever form) and us not being a discoverability service and users needing to be aware of what they are installing was always (and should continue to be) a major point of HBC, so in addition to opinions on *whether* `utorrent` should be removed, we also need strong reasoning as to *why* it should be removed, and how that affects other casks in a similar situation.

**Comment by Amorymeltzer** [comment]
I'd support keeping it, and leaving the caskroom a neutral carrier.  The minute we start making executive decisions on what should/shouldn't be available through hbc is the moment its value goes away.  hbc doesn't need to facilitate illegal or malicious software, but if a user wants *bad* software then so be it, that's their call.  We're a service, not a decision-making enterprise.

I'm not opposed to caveats (even for sf), but I think I take a more liberal stance on them in general.

**Comment by adityadalal924** [comment]
Hmm, adding a caveat for adware-bundled Casks would also go against our current policy of keeping caveats strictly for installation-related purposes.

If we do decide to allow that caveat, a "standard" format like the `files_in_usr_local` shortcut would be best, to keep the phrasing consistent.

**Comment by vitorgalvao** [comment]
> I'd support keeping it, and leaving the caskroom a neutral carrier.

My stance, but in fewer words. 

> The minute we start making executive decisions on what should/shouldn't be available through hbc is the moment its value goes away.

I mostly<sup>1</sup> agree, with the explicit exceptions of what is harmful to HBC itself. For example, direct piracy software<sup>2</sup> that we have justified reason to believe could cause issues for the project as a whole (`popcorn-time`’s repo was deleted by github) and keeping a whole bunch of old versions that no one uses (makes it harder to maintain and manage, makes repos a mess, makes relevant stuff harder to find, makes the project worse with no clear benefits).

> I'm not opposed to caveats (even for sf), but I think I take a more liberal stance on them in general.

We had an issue around that (you might’ve been part of it, even, but may not be recalling it at the moment). The conclusion was that too many irrelevant messages might make users start ignoring them altogether, so we should strive to only output those that are important to the installation of application itself (i.e. “if I ignore this message, there’s a chance things won’t work”.

---

<sup>1</sup> I say “mostly” because the core itself is still valuable. Even if all the casks were removed from the project, the core would allow someone else to make the repos to host all the casks and still provide immense value.

<sup>2</sup> Something like `utorrent` can be used for piracy, but it’s not necessarily meant for it. Contrast that with `popcorn-time`, whose whole point is piracy.

**Comment by plessbd** [comment]
instead of caveats what about doing something like a suffix on the cask name of ones that are known to install adwware something like ```utorrent-adware``` or something similar?

**Comment by vitorgalvao** [comment]
@plessbd No way, as that’d be a sure fire way of causing confusion and starting to get duplicates. There’s a reason we have a strict [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md), and adding arbitrary suffixes to casks would make everything harder to manage.

**Comment by adityadalal924** [comment]
Looks like this (and other related casks) are pending a decision to either:

- do nothing
- ~~remove the Cask~~ (not an option as then we become non-neutral)
- ~~rename Cask~~ (not an option; see above)
- add a new caveat

**Comment by vitorgalvao** [comment]
Well, adding a new caveat is also not an option, as we’ve decided we should keep messages to a minimum, so I’d say we’re at

- do nothing
- ~~remove the Cask~~ (not an option as then we become non-neutral)
- ~~rename Cask~~ (not an option; see above)
- ~~add a new caveat~~
- something else (what?)

**Comment by Eitot** [comment]
Why not just add a stanza? It could be integrated into `brew cask info` for those casks that have it. That way users can inspect this before installation. Maybe a even preference could be added that prevents the user from installing such flagged software, with a manual override in the form of an argument for `brew cask install`.

**Comment by vitorgalvao** [comment]
@Eitot That’s not really a better solution than adding a caveat (it’s worse, since it’ll require more work and implementation) and doesn’t answer the concerns in the rest of the issue.

Seems like we don’t have a great solution for this, and it’s not really worth pursuing inside the goals of the project. Closing for now.

**Comment by vitorgalvao** [comment]
[Here’s an interesting development](https://torrentfreak.com/utorrent-ad-free-client-for-4-95-per-year-160212).

> The uTorrent team has introduced a new ad-free version of the popular file-sharing client. Users can now buy a yearly $4.95 subscription to download the latest torrents without being subjected to ads. The new client is part of **an experiment to optimize the user experience**.

(emphasis mine)

Sounds like a great plan. “Let’s make the experience suck, and them make people pay to have it back to normal”.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/22383/

@diimdeep We’re still discussing the approach, but if approved, you’ll need to do the outlined steps, including reporting the app to Apple. You may wish to do that either way.

**Comment by jmgarnier** [comment]
To clean up the mess if you install without reading, http://www.thesafemac.com/arg-spigot/ helps. I also had to:

```bash
rm -Rf /Users/<YOUR USER NAME HER>/Library/Application\ Support/Spigot/ApplicationManager
```

Also check `~/Library/Application Support` content
