### ISSUE TITLE
`brew cask install` is very slow when installing large dmg

### ISSUE THREAD

**Issue by cybertk** [caskroom/homebrew-cask#15868]
I'm using Homebrew Cask to install a 5G dmg. `brew cask install` takes almost 30min while installing from dmg directly (open then drag to `/Applications`) takes 10min

**Comment by adityadalal924** [comment]
You need to give us more details for us to be able to help! 

Please go through the [bug report](https://github.com/caskroom/homebrew-cask/issues/new?title=Bug%20report%3A&body=%28Remember%20to%20run%20%60brew%20update%3B%20brew%20cleanup%3B%20brew%20cask%20cleanup%60%20before%20reporting%20your%20issue.%20It%20usually%20fixes%20things%21%29%0A%0A%23%23%23%20Description%20of%20issue%0A%0A%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20%3Ccommand%3E%20--verbose%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A%0A%23%23%23%20Output%20of%20%60brew%20doctor%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20doctor%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A) link to get a nice template of information we need.

Closing this issue, please open up a new one using the above link.

Thanks!
