### ISSUE TITLE
Add third-party application restrictions to caskroom

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#15879]
There's no meta repo, but I saw that while joining gitter.im that access to `caskroom` was allowed.

Ideally, [third party application restrictions](https://help.github.com/articles/about-third-party-application-restrictions/) should be set up so that apps don't get access to `caskroom` when maintainers are connecting apps to their Github account.

**Comment by vitorgalvao** [comment]
Sounds reasonable. Thank you for looking into this. Done.

**Comment by adityadalal924** [comment]
Excellent, thanks. 

The authorization screen now looks like this:
<img width="888" alt="screen shot 2015-12-16 at 5 02 54 pm" src="https://cloud.githubusercontent.com/assets/2555394/11855229/f26cba1c-a416-11e5-8aee-12dca600bc2c.png">
