### ISSUE TITLE
#wkhtmltopdf Issues, “brew install Caskroom/cask/wkhtmltopdf” Changes Ownership Permissions

### ISSUE THREAD

**Issue by 7Moses** [caskroom/homebrew-cask#15875]
`brew install Caskroom/cask/wkhtmltopdf` Changes Ownership Permissions

Installing wkhtmltopdf changes the owner of /usr/local 

See, https://www.evernote.com/l/AAckZvkLB_NE-rYNfJ5CY4C6gckLkiVHqqo

E.g., 

```
Warning: /usr/local/bin isn't writable.
You should probably change the ownership and permissions of /usr/local/bin  back to your user account. sudo chown -R $(whoami) /usr/local/bin
```

Etc,

It appears to be a recurring issue, see https://github.com/caskroom/homebrew-cask/issues/12093

I used the above and brew doctor to uninstall and clean up. Save 40 minutes, do not do this install at present.

**Comment by vitorgalvao** [comment]
What’s the output of `brew cask info wkhtmltopdf`?

**Comment by 7Moses** [comment]
Thanks for replying so quickly:

moses@MosesMoses ~ $ brew cask info wkhtmltopdf                                 [2.2.2]
wkhtmltopdf: 0.12.3-dev-79ff51e
wkhtmltopdf
http://wkhtmltopdf.org/
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/wkhtmltopdf.rb
==> Contents
  wkhtmltox-0.12.3-dev-79ff51e_osx-cocoa-x86-64.pkg (pkg)
==> Caveats
Cask wkhtmltopdf installs files under "/usr/local".  The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in homebrew-cask.

moses@MosesMoses ~ $

**Comment by vitorgalvao** [comment]
That’s precisely the version that should have the fix, and was reported to work.

I tested it now on a VM, and the results are weird. The VM was in a state where I had done other irrelevant installations before, for testing purposes. I kept that state and installed `wkhtmltopdf`, and was able to reproduce. I forgot to check the values of the directories beforehand, though, so for good measure I reverted the VM to back to a clean state and tried again. I was no longer able to reproduce. Did it a few more times, always reverting back the VM, and I’m no longer able to reproduce.

Unless another maintainer or user can reproduce, it seems like it was a freak occurrence. Lets wait and see.

**Comment by adityadalal924** [comment]
Went through the installer `.pkg` and I don't see anything that would cause this issue to occur, unfortunately.

**Comment by vitorgalvao** [comment]
Thank you for checking as well, @adityadalal924. Unless we get someone that can replicate issue by the end of the year, we should close this and keep an eye on the cask.

**Comment by adityadalal924** [comment]
Closing as discussed above.

**Comment by 7Moses** [comment]
Thanks for sharing info.

**Comment by dstack4273** [comment]
For what it is worth I had the same issue when I installed on Thursday, but it isn't that bad to reset the directory permissions.

**Comment by 7Moses** [comment]
@dstack4273 Thanks for confirming the initial observation,
