### ISSUE TITLE
Cask request: TokenLock

### ISSUE THREAD

**Issue by jaspham** [caskroom/homebrew-cask#15888]
**Name** - TokenLock

**Homepage** - https://www.map-pin.com/tokenlock-home/

**Company** - MacPin Software

**License** - Mac App Store - $4.99

**Download URL** - http://uploaded.net/file/wffen97s

**Description** - This app will lock and optionally unlock your Mac automatically, using it's own lock screen, the built-in screen saver for OSX, or by sleeping your Mac display.

**Comment by adityadalal924** [comment]
Unfortunately, we can not add Mac App Store only apps, which TokenLock seems to be, based on the homepage.

**Comment by jawshooah** [comment]
Please note, however, that you are completely free to create an [alternate tap](https://github.com/caskroom/homebrew-cask/blob/ccaf00a189cdbe50109ba6bf294c2b72aecba784/doc/alternate_cask_taps.md#alternate-cask-taps) and scratch your own itch.

**Comment by vitorgalvao** [comment]
I’ll also add that URL appears to point to a pirated version of the software, which we definitely do not approve.

Apart from the (should be) clear reason we’re in no way related or want to be related to piracy, that URL is for a file locker, which means we wouldn’t be able to get the direct URL, even if we wanted, and we don’t use non-official URLs, as they’re potentially harmful.
