### ISSUE TITLE
Cask request: Bitcoin XT

### ISSUE THREAD

**Issue by calummaciver** [caskroom/homebrew-cask#15902]
### Cask details

**Name** - Bitcoin XT

**Homepage** - https://bitcoinxt.software

**License** - MIT License

**Download URL** - https://github.com/bitcoinxt/bitcoinxt/releases/download/v0.11D/Bitcoin-XT.0.11D.dmg

**Description** - Bitcoin XT is an implementation of a Bitcoin full node that embraces Bitcoin's original vision of simple, reliable, low-cost transactions for everyone in the world. It is based upon the source code of Bitcoin Core, and is built by taking the latest stable Core release, applying a series of patches, and then doing deterministic builds so anyone can check the downloads correspond to the source code.

**Comment by vitorgalvao** [comment]
Will be merged later on https://github.com/caskroom/homebrew-cask/pull/15903.

**Comment by vitorgalvao** [comment]
We can’t seem to be able to get this to download with `curl`, for some unknown reason (https://github.com/caskroom/homebrew-cask/pull/15903).

Without figuring it out, we won’t be able to add this cask.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/20090.
