### ISSUE TITLE
Cask 'pycharm' definition is invalid: Bad header line: parse failed

### ISSUE THREAD

**Issue by jbspeakr** [caskroom/homebrew-cask#15930]
```
$ brew-cask search pycharm
==> Exact match
pycharm
==> Partial matches
pycharm-ce   pycharm-edu

$ brew-cask install pycharm
Error: Cask 'pycharm' definition is invalid: Bad header line: parse failed
```

any hint on how to fix this?!

**Comment by ipmb** [comment]
I had a similar issue with a different package. `brew doctor` reported this:

```
Warning: You have external commands with conflicting names.

Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb
```

I removed the first one (`rm /usr/local/bin/brew-cask`) and things seem to work now.

**Comment by adityadalal924** [comment]
Run:
```
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

and retry.

**Comment by vitorgalvao** [comment]
Also, [do this](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

**Comment by kassadin** [comment]
```
brew cask list
Error: Cask 'atom' definition is invalid: Bad header line: parse failed
```
It seems the same problem

**Comment by vitorgalvao** [comment]
> It seems the same problem

It is, we know the cause. It’s not a bug, it’s an update to how we do things. Just run what @adityadalal924 said, and it’ll be fine. Details [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

**Comment by adityadalal924** [comment]
@vitorgalvao We're might get a lot of issues about this because of the combination of moving to `tap cmd` and the cask header update (if people don't read).

Here's a copy pastable reply:

----------------------

This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by vitorgalvao** [comment]
Good call. Added as a textexpander snippet.

**Comment by jbspeakr** [comment]
top, thx!

**Comment by RobertGrantEllis** [comment]
I'm still having problems getting brew cask to work. I've done all of the above but the issue is still there. Any help would be much appreciated! See my capture below.

BadApple$ brew update; brew cleanup; brew cask cleanup; brew uninstall --force brew-cask; brew update
Already up-to-date.
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do
Already up-to-date.
BadApple$ brew cask install vagrant
Error: Cask 'vagrant' definition is invalid: Bad header line: parse failed

**Comment by jawshooah** [comment]
@RobertGrantEllis I have a hunch. Try this:

```
brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; 
cask install vagrant
```

**Comment by adityadalal924** [comment]
The "nuclear" option, also, if wanted:

Not sure if order particularly matters, compared to @jawshooah's above. Both do the same thing, essentially.

```bash
# untap all cask repositories
brew untap caskroom/homebrew-cask
brew untap phinze/homebrew-cask
# remove all remaining pieces
rm -rf $(brew --prefix)/Library/Taps/phinze-cask
rm $(brew --prefix)/Library/Formula/brew-cask.rb
rm -rf $(brew --prefix)/Library/Taps/caskroom
# finish up
brew uninstall --force brew-cask
brew update; brew cleanup; brew cask cleanup
```

**Comment by RobertGrantEllis** [comment]
@jawshooah I tried your commands, capture below. After performing those steps, it (incorrectly) stated that Vagrant was installed, then I tried with --force as suggested in the output, and I got a different error... thoughts?

grant@Mini $ brew uninstall --force brew-cask                                                                                
grant@Mini $ brew untap phinze/cask
Error: No available tap phinze/cask.
grant@Mini $ brew untap caskroom/cask
Untapping caskroom/cask... (3,338 files, 13.3M)
Untapped 1 formula
grant@Mini $ brew cask install vagrant
Warning: A Cask for vagrant (!) is already installed. Add the "--force" option to force re-install.
grant@Mini $ brew cask install --force vagrant
Error: undefined method `using' for nil:NilClass

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/download.rb:14:in `perform'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:89:in `download'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:63:in `install'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/brew-cask-cmd.rb:19:in `<main>'

**Comment by vitorgalvao** [comment]
@RobertGrantEllis Do `brew update` (you haven’t in a while) and then try installing `vagrant` again.

**Comment by RobertGrantEllis** [comment]
@adityadalal924 I also tried the "nuclear option", with the same outcome. That one included a brew update. In case this is relevant, my homebrew prefix is actually non-standard, in /Users/grant/homebrew. Capture below.

grant@Mini $ brew untap caskroom/homebrew-cask
Error: No available tap caskroom/cask.
grant@Mini $ brew untap phinze/homebrew-cask
Error: No available tap phinze/cask.
grant@Mini $ brew --prefix
/Users/grant/homebrew                                                                            
grant@Mini $ rm -rf /Users/grant/homebrew/Library/Taps/phinze-cask
grant@Mini $ rm /Users/grant/homebrew/Library/Formula/brew-cask.rb
rm: /Users/grant/homebrew/Library/Formula/brew-cask.rb: No such file or directory
grant@Mini $ rm -rf /Users/grant/homebrew/Library/Taps/caskroom
grant@Mini $ brew uninstall --force brew-cask
grant@Mini $ brew update
Updated Homebrew from d91900b2 to af880585.
==> New Formulae
libgig
==> Updated Formulae
docker-machine-parallels   signing-party              sqlitebrowser            
fzf                        sourcekitten             
grant@Mini $ brew cleanup
grant@Mini $ brew cask cleanup
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do
grant@Mini $ brew cask install vagrant
Warning: A Cask for vagrant (!) is already installed. Add the "--force" option to force re-install.
grant@Mini $ brew cask install --force vagrant
Error: undefined method `using' for nil:NilClass

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/download.rb:14:in `perform'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:89:in `download'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:63:in `install'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/brew-cask-cmd.rb:19:in `<main>'

**Comment by vitorgalvao** [comment]
@RobertGrantEllis Please enclose your code in [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), as otherwise it is hard to read.

Your `brew update` isn’t updating homebrew-cask, which is the problem.

**Comment by RobertGrantEllis** [comment]
@vitorgalvao OK, I've updated the prior comments- sorry about that. I did a brew cask update and the behavior has changed again- now it can't seem to find the formula. Interestingly, brew search still finds the relevant formulas:

```bash
grant@Mini $ brew cask update
Already up-to-date.

grant@Mini $ brew cask install vagrant
Error: No available Cask for vagrant
Error: nothing to install

grant@Mini $ brew cask install --force vagrant
Error: No available Cask for vagrant
Error: nothing to install

grant@Mini $ brew search vagrant
homebrew/completions/vagrant-completion  Caskroom/cask/vagrant-manager          
Caskroom/cask/vagrant-bar                Caskroom/cask/vagrant
```

**Comment by jawshooah** [comment]
Ah, the custom prefix should probably have been mentioned sooner. Even the Homebrew guys say it's inadvisable :wink:

You somehow wound up with `brew-cask` installed in the default Homebrew Cellar (must have been a while ago, 0.58.0 is rather old now). Try this:
```
rm -rf /usr/local/Cellar/brew-cask
rm -rf /usr/local/Library/Taps/caskroom
rm -rf /usr/local/Library/Taps/phinze*
rm -f /usr/local/bin/brew-cask
rm -rf /Users/grant/homebrew/Cellar/brew-cask
rm -rf /Users/grant/homebrew/Library/Taps/caskroom
rm -rf /Users/grant/homebrew/Library/Taps/phinze*
rm -f /Users/grant/bin/brew-cask
brew update
brew cask install --force vagrant
```

**Comment by RobertGrantEllis** [comment]
@jawshooah That worked-- Thanks so much for your help! out of curiosity, what tipped you off that there was homebrew installed also in /usr/local?

Also, one more thing: Interestingly, even with the homebrew prefix set to /Users/grant/homebrew, the installed casks go into /opt/<caskname> and then get symlinked into /usr/local/bin anyways. Any way to override the latter behavior? That is, can we symlink them into /Users/grant/homebrew/bin (the installed 
homebrew prefix) instead of /usr/local/bin?

**Comment by jawshooah** [comment]
> what tipped you off that there was homebrew installed also in /usr/local?

Check the stack trace under the ``Error: undefined method `using' for nil:NilClass``.

> Interestingly, even with the homebrew prefix set to /Users/grant/homebrew, the installed casks go into /opt/ and then get symlinked into /usr/local/bin anyways. Any way to override the latter behavior? That is, can we symlink them into /Users/grant/homebrew/bin (the installed 
homebrew prefix) instead of /usr/local/bin?

[USAGE.md](https://github.com/caskroom/homebrew-cask/blob/e766cba9d6a45202b226914c8a8b55f267d7391f/USAGE.md#options).

**Comment by RobertGrantEllis** [comment]
@jawshooah @vitorgalvao Thank you both so much for your help!

**Comment by jawshooah** [comment]
@RobertGrantEllis No problem.

Next time, though, please open a new issue instead of commenting on a closed one :wink:

And consider just using the default Homebrew prefix of `/usr/local`. From their [install docs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md#alternative-installs):

> However do yourself a favor and install to `/usr/local`. Some things may
not build when installed elsewhere. One of the reasons Homebrew just
works relative to the competition is **because** we recommend installing
to `/usr/local`. *Pick another prefix at your peril!*

**Comment by itsNikolay** [comment]
`brew uninstall --force brew-cask; brew update` and install package again! :+1:

**Comment by huguiqi** [comment]
very good way!!!

**Comment by huguiqi** [comment]
samdeMBP:~ sam$ brew update; brew cleanup; brew cask cleanup; brew uninstall --force brew-cask; brew update
Already up-to-date.
Error: Could not link phinze/cask manpages to:
  /usr/local/share/man/man1/brew-cask.1

Please delete these files and run `brew tap --repair`.
Warning: Skipping phinze/cask/brew-cask: most recent version 0.60.0 not installed
Warning: Skipping docker-compose: most recent version 1.5.2 not installed
Warning: Skipping docker-machine: most recent version 0.5.4 not installed
Warning: Skipping go: most recent version 1.5.2 not installed
Warning: Skipping libgpg-error: most recent version 1.21 not installed
Warning: Skipping openssl: most recent version 1.0.2e not installed
Warning: Skipping pkg-config: most recent version 0.29 not installed
Warning: Skipping scons: most recent version 2.4.1 not installed
Warning: Skipping sqlite: most recent version 3.9.2 not installed
Warning: Skipping subversion: most recent version 1.9.2 not installed
Warning: Skipping wget: most recent version 1.17.1 not installed
Warning: Skipping xz: most recent version 5.2.2 not installed
Removing: /Library/Caches/Homebrew/docker-compose-1.5.1.el_capitan.bottle.tar.gz... (876K)
Removing: /Library/Caches/Homebrew/docker-compose-1.5.1.tar.gz... (184K)
Removing: /Library/Caches/Homebrew/docker-machine-0.5.1.el_capitan.bottle.tar.gz... (39M)
Removing: /Library/Caches/Homebrew/dockertoolbox-1.8.1.pkg.incomplete... (16K)
Removing: /Library/Caches/Homebrew/go-1.5.1.el_capitan.bottle.tar.gz... (66M)
Removing: /Library/Caches/Homebrew/go-1.5.1.tar.gz... (11M)
Removing: /Users/sam/Library/Logs/Homebrew/docker-compose... (9 files, 100K)
Removing: /Users/sam/Library/Logs/Homebrew/go... (4 files, 220K)
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do
Uninstalling brew-cask... (2634 files, 10M)
Already up-to-date.

samdeMBP:~ sam$ brew cask list
baiducloud   betterzip	  flash	       qqmusic	    virtualbox	 xiami

**Comment by adityadalal924** [comment]
@huguiqi You also have the old cask tap installed. Run 

$ brew untap phinze/cask; brew untap caskroom/cask; brew update

Also locking this issue. Please open up a new one if there are any further problems.
