### ISSUE TITLE
cask problem: GIMP 2.8.16

### ISSUE THREAD

**Issue by dfpoon** [caskroom/homebrew-cask#15968]
General users (i.e. non-admin users) encountered this permission problem after I installed GIMP.app. 

"LSOpenURLsWithRole() failed with error -10658 for the file /Applications/GIMP.app"
-> GIMP.app cannot be opened.

In the contrast, Administrator has no problem.

Fix: I follow the instruction is this thread:
https://apple.stackexchange.com/questions/81330/downloaded-apps-does-not-start-error-10658

$>  sudo chmod a+x /opt/homebrew-cask/Caskroom/gimp/2.8.16-x86_64/GIMP.app/Contents/MacOS/GIMP

Please help to fix the GIMP.app package. Thanks a lot!

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by vitorgalvao** [comment]
I ask that just to be sure, because likely it is just a permissions issue with GIMP. We could fix it with a `set_permissions`, but that isn’t the best fix.

You should report this to GIMP, not us, it’s an issue they should be the ones to fix, this isn’t related to homebrew-cask.

**Comment by dfpoon** [comment]
Thanks. I think it is permissions issue with GIMP too. Let me report that to GIMP project instead.

**Comment by dfpoon** [comment]
I've reported my problem to GIMP. The maintainer there consider it should be a homebrew problem. Could you kindly tell me whom should I approach to report this problem?

You may refer to my GIMP bug report here:
https://bugzilla.gnome.org/show_bug.cgi?id=759684

**Comment by vitorgalvao** [comment]
The mistake there was you referenced doing the installation via a tool, which isn’t at all related to the problem. Please report back in that issue where the developer is wrong:

We’re not homebrew, we’re homebrew-cask. We don’t use `make` like they’re assuming, we just download their prebuilt package and move the application, nothing else.

Before doing so, though, please uninstall GIMP woth homebrew cask, download the prebuilt package manually, move it to you `/Applications` directory youself, and see if your issue persists.

Report that as well.
