### ISSUE TITLE
Error: Could not link phinze/cask manpages to

### ISSUE THREAD

**Issue by leroyg** [caskroom/homebrew-cask#15975]
When I run `brew cask update` 

I get the following error: `==> Error: Could not link phinze/cask manpages to:
==>   /usr/local/share/man/man1/brew-cask.1` 

I've tried to rm that file. I've navigated to the dir and checked if it was gone, it was. I run `brew tap --repair` as instructed. No dice. 

Anyone have any experience with this error?

**Comment by jawshooah** [comment]
Please always follow the guidelines for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs). If the problem persists, use the linked template to open a new issue.

**Comment by vitorgalvao** [comment]
`phinze/cask`. Wow, how long have you been without updating homebrew-cask? Or did you tap the wrong repo? Run `brew uninstall --force brew-cask; brew update` once.

**Comment by CSerxy** [comment]
I have meet the same problem. Do you have found any solutions?

**Comment by adityadalal924** [comment]
@CSerxy 


To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by CSerxy** [comment]
Thanks for your help, but it seems useless for my situation.
Wind:~ cserxy$ brew update; brew cleanup; brew cask cleanup
Already up-to-date.
Error: Could not link phinze/cask manpages to:
  /usr/local/share/man/man1/brew-cask.1

Please delete these files and run `brew tap --repair`.
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do
Wind:~ cserxy$ brew uninstall --force brew-cask; brew update
Already up-to-date.
Error: Could not link phinze/cask manpages to:
  /usr/local/share/man/man1/brew-cask.1

Please delete these files and run `brew tap --repair`.

And I delete these files, it still prompts:

Wind:~ cserxy$ rm /usr/local/share/man/man1/brew-cask.1 
Wind:~ cserxy$ brew tap --repair
Error: Could not link phinze/cask manpages to:
  /usr/local/share/man/man1/brew-cask.1

Please delete these files and run `brew tap --repair`.

**Comment by adityadalal924** [comment]
@CSerxy https://github.com/caskroom/homebrew-cask/issues/16094
