### ISSUE TITLE
Error on Cask Installation

### ISSUE THREAD

**Issue by greenstick** [caskroom/homebrew-cask#15995]
Attempting to install Julia:

    user@server:~$ brew doctor
    Your system is ready to brew.
    user@server:~$ brew cask install julia
    Error: Permission denied @ dir_s_mkdir - /Library
    
    Most likely, this means you have an outdated version of homebrew-cask. Please run:
    
    brew update; brew cleanup; brew cask cleanup
    
    If this doesn’t fix the problem, please report this bug:
    
    https://github.com/caskroom/homebrew-cask#reporting-bugs
    
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:210:in `each'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/pathname.rb:564:in `mkpath'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:18:in `mkpath'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:57:in `init'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:114:in `process'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /home/user/.linuxbrew/Library/brew.rb:72:in `require?'
    /home/user/.linuxbrew/Library/brew.rb:151:in `<main>'

    user@server:~$ brew update; brew cleanup; brew cask cleanup
    Already up-to-date.
    Error: Permission denied @ dir_s_mkdir - /Library
    
    Most likely, this means you have an outdated version of homebrew-cask. Please run:
    
    brew update; brew cleanup; brew cask cleanup
    
    If this doesn’t fix the problem, please report this bug:
    
    https://github.com/caskroom/homebrew-cask#reporting-bugs
    
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:210:in `each'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/pathname.rb:564:in `mkpath'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:18:in `mkpath'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:57:in `init'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:114:in `process'
    /home/user/.linuxbrew/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /home/user/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /home/user/.linuxbrew/Library/brew.rb:72:in `require?'
    /home/user/.linuxbrew/Library/brew.rb:151:in `<main>'

**Comment by jawshooah** [comment]
Homebrew-cask is for OSX, not Linux. You'll have to use whatever package manager comes with your distro.

**Comment by greenstick** [comment]
Ah unfortunate, are you guys planning on implementing a linuxbrew version? Thanks

**Comment by jawshooah** [comment]
Nope, it's way out of scope for us. OSX gives us plenty of headaches already.
