### ISSUE TITLE
Cask Request: Log File Navigator

### ISSUE THREAD

**Issue by sagikazarmark** [caskroom/homebrew-cask#16005]
### Cask details

**Name** - The Log File Navigator

**Homepage** - http://lnav.org

**License** - `:oss`

**Download URL** - `"https://github.com/tstack/lnav/releases/download/v#{version}/lnav-#{version}-os-x.zip"`

**Description** - An advanced log file viewer for the commad line.

**Comment by adityadalal924** [comment]
@sagikazarmark sagikazarmark I updated your first post with our new Cask request template.

Leaving this issue open, but you're always welcome to [make the Cask yourself](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md) and submit it. We're here to help if you have questions.

[This Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/gephi.rb) should be a solid starting point if you need a model.

**Comment by reitermarkus** [comment]
This is available in the main Homebrew repo (`brew install lnav`).

**Comment by jawshooah** [comment]
`lnav` is already present in [Homebrew](https://github.com/Homebrew/homebrew), and we are [trying to reduce duplication](https://github.com/caskroom/homebrew-cask/issues/15603).

**Comment by sagikazarmark** [comment]
Wow, thanks for the feedback.
