### ISSUE TITLE
Other homepage for libreoffice-beta

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#16045]
Hello,
Wouldn't it be better to define directly https://www.libreoffice.org/download/pre-releases/ as specific homepage in `libreoffice-beta` formula, instead of current general URL https://www.libreoffice.org/ like in `libreoffice` formula ?

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-versions/pull/1513

Issue should have been made in `caskroom/homebrew-versions`, by the way.

**Comment by Yann-R** [comment]
> Issue should have been made in caskroom/homebrew-versions, by the way.
Oops, my mistake!

> Fixed in caskroom/homebrew-versions#1513
Many thanks!
