### ISSUE TITLE
Casks orphaned after upgrade

### ISSUE THREAD

**Issue by craibuc** [caskroom/homebrew-cask#16056]
I upgraded to new system: `brew uninstall --force brew-cask; brew update`
I attempted to remove an unused Cask: 
~~~bash
$ brew cask uninstall eyetv
Error: eyetv is not installed
~~~
The cask is present in `/opt/homebrew-cask/Caskroom/eyetv/3.6.5`
Attempting to re-install cask:

~~~bash
$ brew cask install eyetv
~~~
Results in a second cask located at `/opt/homebrew-cask/Caskroom/eyetv/3.6.8_7407`

Version:
~~~
$ brew -v
Homebrew 0.9.5 (git revision 1b5d07; last commit 2015-12-22)
~~~

**Comment by adityadalal924** [comment]
Yep, [it's a known issue](https://github.com/caskroom/homebrew-cask/issues/2988)

The (admittedly bad) solution at this point is to use the `--force` flag while uninstalling and clean up old versions from `/opt/homebrew-cask/Caskroom/` manually. If you have a list of applications handy, it might be faster to wipe the entire directory and reinstall all of them.
