### ISSUE TITLE
Cask request: Telegram (not the Telegram Desktop version)

### ISSUE THREAD

**Issue by eligiblekeng** [caskroom/homebrew-cask#16066]
### Cask details

(Please fill out as much as possible)

**Name** - Telegram

**Homepage** - https://itunes.apple.com/us/app/telegram/id747648890?mt=12

**License** - 

**Download URL** - https://itunes.apple.com/us/app/telegram/id747648890?mt=12

**Description** - There are 2 versions of telegram on the Mac Appstore. There already exists a Cask for the `Telegram Desktop` version, but not the `Telegram` version, even though the Cask is called Telegram. Perhaps call this other `Telegram Mac` in the Cask?

**Comment by vitorgalvao** [comment]
We can’t add Mac App Store apps. There’s no way to get them.
