### ISSUE TITLE
Proposal: remove support for Subversion urls

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16116]
[Subversion urls](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#subversion-urls) are implemented but not in use. We don’t have a single cask that needs it, nor do I remember such a cask ever existing.

If we’re in agreement, we’ll also be able to close https://github.com/caskroom/homebrew-cask/issues/8594.

**Comment by jawshooah** [comment]
Completely agree. No idea why it was implemented in the first place, seems like it would only be useful when building from source. Which we've never done and never will.

**Comment by adityadalal924** [comment]
I ran into one here:
https://github.com/caskroom/homebrew-fonts/blob/d942d136e441e1d8ef7e711c9b4d6868b48ef0ff/Casks/font-source-code-pro-for-powerline.rb

(but the font was outdated so I killed it anyway (https://github.com/caskroom/homebrew-fonts/pull/426)

**Comment by Amorymeltzer** [comment]
:+1:
