### ISSUE TITLE
Cask request: shortcuts

### ISSUE THREAD

**Issue by openingnow** [caskroom/homebrew-cask#16151]
### Cask details

**Name** - shortcuts

**Homepage** - https://github.com/siong1987/shortcuts

**License** - MIT

**Download URL** - 
https://github.com/siong1987/shortcuts/releases

https://github.com/siong1987/shortcuts/releases/download/1.0.0/restart.sleep.shutdown.logout.lock.zip
served as .zip file

**Description** - Five simple apps - that serve five simple purposes: restart, sleep, logout, shutdown, lock.

**Comment by adityadalal924** [comment]
Added in https://github.com/caskroom/homebrew-cask/issues/16249

**Comment by openingnow** [comment]
Thank you!
