### ISSUE TITLE
brew cask open <appname>

### ISSUE THREAD

**Issue by declanqian** [caskroom/homebrew-cask#16162]
Does it make sense to add a command, may be 'open to open a Application using cask command: brew cask open <appname>. I am unhappy when I hava to open an Application using Mac os open command, and then go through the long pathname if Alfred is unavailable.  Since cask gets all the infos to open an application. I am just thinking may be as an enhancement?

**Comment by vitorgalvao** [comment]
There was already an issue for this that was recently closed. Not enough interest, basically.

**Comment by Amorymeltzer** [comment]
@declanqian Maybe I'm misunderstanding, but `open -a application_name` should essentially do what you want.  So, `open -a firefox` or `open -a vlc`.  Alias `o` or `op` or something for easy access.

**Comment by declanqian** [comment]
Yeah, `open -a` does the trick. Thanks:)
