### ISSUE TITLE
Enable Travis caching

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#16204]
As seen on https://docs.travis-ci.com/user/caching#Caching-directories-(Bundler%2C-dependencies)

Looks like the new container-based infrastructure has to be used, which means no sudo.

Not sure if it's feasible, but if so, would speed up Travis checks considerably.

**Comment by jawshooah** [comment]
It isn't feasible unfortunately, as we need sudo in order to run our tests using system Ruby.
