### ISSUE TITLE
lastpass installed is not the Library

### ISSUE THREAD

**Issue by kengz** [caskroom/homebrew-cask#16234]
The lastpass installed does not include the Library, as stated when launching the app's preference it warns `please install the Lastpass Library for Safari to enable automatic logout after idle`. Besides, the copy-password features seem to be absent from this installation.

One has to then click on the link to install Lastpass again.

**Comment by vitorgalvao** [comment]
Please be more specific about the issue and how to solve it. We simply download [what they give us](https://lastpass.com/simpledownload.php) and tell you to run the installer.

**Comment by adityadalal924** [comment]
It's an upstream issue, unfortunately. (We don't modify any files that LastPass gives us, in fact, in this case, we just download a zip file and run the .app)

See https://forums.lastpass.com/viewtopic.php?f=12&t=181845&start=10 for more info and a possible alternative (Install LastPass from the Safari Extensions page)

**Comment by kengz** [comment]
I see, so for now we have to manually do that after installation then. Thanks.
