### ISSUE TITLE
Better solution than subversion for fonts?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16231]
From https://github.com/caskroom/homebrew-cask/pull/16215#issue-124228698.

> The reason we’re doing it this way is `svn`, unlike `git`, allows us to checkout a single directory from the repo, making for a smaller download.

> Download size in itself isn’t that big a deal, I’d say, since worst case scenario the download of a full fonts repo should be ≈250MBs (Google Fonts) and there are bigger apps. With caching, and since users likely don’t install fonts all the time, that wouldn’t be a huge deal, except that since we need to separate apps by directory before linking (moving, in the future) we’d leave users with a bunch of copies of those uncompressed repos, and that is not good.

> However, using subversion in this manner is in itself bad for casks, I’d argue, since it requires [an important additional value](https://github.com/caskroom/homebrew-fonts/blob/ab1e0df2005278a6b132b1b8a5d4dc55cd0ff233/Casks/font-sauce-code-powerline.rb#L8) to `url`s. This [subversion revision](https://github.com/caskroom/homebrew-cask/pull/16118/files#diff-eb6c53cc0d6eb7ed0964481ed17f8624L300) value is (seems like) an obtuse parameter to get in the context of a github repo, and I’m not even sure there’s an easy way for contributors to know when to updated it and to what value. It also makes the cask somewhat more difficult to understand in the sense that [its `url` value](https://github.com/caskroom/homebrew-fonts/blob/ab1e0df2005278a6b132b1b8a5d4dc55cd0ff233/Casks/font-sauce-code-powerline.rb#L6) will seem to lead nowhere.

> In light of all this, I’d rather have yet a different solution. I briefly considered a sibling project, like [our sister](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#unofficial-vendorless-and-walled-builds) [alehouse](https://github.com/alehouse) to host these multiple-fonts-per-repo fonts. I was envisioning a script that regularly would download those repos, package fonts as individual zip files, and push them to a github repo. Corresponding cask font files would then be set to `:latest` (fonts is one case where you absolutely always want the latest) and download from there. Those wouldn’t really be official links, though, and there may be other things I’m also not predicting there.

> Any ideas?

**Comment by adityadalal924** [comment]
`https://github.com/user/repository/raw/branch/filename` works per-se, but it's not great - you need to do one download per `font` file.

ie:
alef

https://github.com/google/fonts/blob/master/ofl/alef/Alef-Regular.ttf => https://github.com/google/fonts/raw/master/ofl/alef/Alef-Regular.ttf
https://github.com/google/fonts/blob/master/ofl/alef/Alef-Bold.ttf => https://github.com/google/fonts/raw/master/ofl/alef/Alef-Bold.ttf

The `raw` url also works:  https://raw.githubusercontent.com/google/fonts/master/ofl/alef/Alef-Bold.ttf

**Comment by jawshooah** [comment]
That would require [multiple URLs per cask](https://github.com/caskroom/homebrew-cask/pull/3043), which we don't support at the moment, and would probably require a good bit of refactoring.

**Comment by adityadalal924** [comment]
I never said that it was a good idea :wink: 

I'm actually surprised there is isn't a better solution for fonts - i would expect Google to have at least a downloadable zip per font *somewhere*....

**Comment by vitorgalvao** [comment]
> I'm actually surprised there is isn't a better solution for fonts - i would expect Google to have at least a downloadable zip per font *somewhere*....

They do, on the [Google Fonts directory](https://www.google.com/fonts) but we’d have to go and grab them one by one since each has a different hash in the download link, and I’m not even sure they aren’t temporary.

There are other repos with multiple fonts, however, so doing that wouldn’t in itself solve the problem.
