### ISSUE TITLE
Cask cannot continue downloading packages after network is reconnected

### ISSUE THREAD

**Issue by xiehao** [caskroom/homebrew-cask#16288]
Recently, when I download chrome by `brew cask install --verbose google-chrome`, it always stops after downloading a small part of it, due to network problem (You know the Chinese network). When I repeat the command later, it just goes from the beginning, instead of continuing from the last place like before times.

**Comment by vitorgalvao** [comment]
That depends on the server (if they allow resuming or not), not us. Do it with `p5`, for example, and you’ll see it works.
