### ISSUE TITLE
Rodeo 1.2.1 sha256 mismatch

### ISSUE THREAD

**Issue by sauravrt** [caskroom/homebrew-cask#16281]
Cask for Rodeo needs to be updated to have the correct sha256 checksum. Currently, I get following error.

=> Verifying checksum for Cask rodeo
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
**Expected: f5b6c2cdf5ed6c42f5726c4c40512bf6a5bd63bbb124f8cf9420175969f5be54**
**Actual: 0d9bfac3ede8d7f1f1f4c10c5fdf7cb2be37bdc46c2b43a2e9f3f4b400ea75fe**
File: /Library/Caches/Homebrew/rodeo-1.2.1.dmg

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/16282
