### ISSUE TITLE
`after_colon` or `after_comma` instead of `after_slash`? What about `field()`?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16283]
[Here](https://github.com/caskroom/homebrew-cask/pull/16276/files) we have an example of a cask in which slashes could be made as part of `version`.

[We can still do it](https://github.com/caskroom/homebrew-cask/pull/16276#issuecomment-168336495) (and we likely should, since it’s still fairly clear), and there shouldn’t be many casks like this, but what if we forget `after_slash` (and `before_slash`) and use instead `,` or `:`, as separators? We won’t see those in `url`s, and it frees up `/` to be used casually.

And what if in addition to those, we also add a `field()` method? For example, in `version '1.2.3,4b5,67'` or `version '1.2.3:4b5:67'`, `#{version.field(2)}` would be `4b5`.

That’s likely a bit too much, but am still throwing the idea out there. Two fields (i.e. `before_` and `after_`) should be enough. If we allow for three or more fields, we may be allowing for such complexity, the cask would become unreadable anyway and hard to decipher when trying to update.

However, changing the character for the separator might be a good idea.

**Comment by jawshooah** [comment]
I'm fine with this. Just FYI though, `before_slash` and `after_slash` would work fine for  the cases you list. It uses the *first* slash in the string as the delimiter, so you could do `version '1.2.4/3/2015/08'` and it would work as expected.

**Comment by jawshooah** [comment]
It's also important to note that, for the purposes of eventually implementing `upgrade`, we should try to keep version numbers strictly increasing over time (preferably parseable by `Gem::Version.new`)

So maybe something like this:

```rb
version '1.2.4-2015.3.08'
url "https://support.griffintechnology.com/wp-content/uploads/sites/#{version.after_hyphen.dots_to_slashes}/PowerMate_v#{version.release}.zip"
```

where `release` is defined as it is on `Gem::Version`: anything before a letter or a hyphen. Or just use `before_hyphen`, either way.

**Comment by jawshooah** [comment]
Or we could just assume that whatever is listed in the cask file is the latest version, anything different is outdated, and skip any actual comparison of version numbers.

**Comment by vitorgalvao** [comment]
> Just FYI though, `before_slash` and `after_slash` would work fine for  the cases you list. It uses the *first* slash in the string as the delimiter

I thought it might but wasn’t sure, and that made me question if it wouldn’t be confusing for users. I feel `before_*` and `after_*` are powerful statements that should mostly mean “there’s only of of those and it divides the string in two parts at this clear point”.

I’d be fine with either `colon` or `comma`, but I think we should retire `before_slash` and `after_slash` if/when introducing those.

As yet another idea that just occurred, we could have *both* the `comma` and `colon` variants, and by doing so have two clear ways of dividing the string that allowed for more complex divisions without making reading the cases confusing (but still retiring the `*_slash` variants). I think that might be the best option.

> Or we could just assume that whatever is listed in the cask file is the latest version, anything different is outdated, and skip any actual comparison of version numbers.

I’m vehemently in favour of this approach. Way easier to maintain.

**Comment by jawshooah** [comment]
> I think we should retire `before_slash` and `after_slash` if/when introducing those.

Sure, though we should probably just mark them as deprecated. Who knows, someone may have used them in a custom tap in the last few days. I like @mikemcquaid's [suggestion](https://github.com/caskroom/homebrew-cask/issues/15782#issuecomment-164397057) of deprecating old DSL elements instead of removing them completely (should probably have done the same for `tags`).

> Way easier to maintain.

Definitely. Just take a look at Homebrew's [custom version parsing code](https://github.com/Homebrew/homebrew/blob/f43c681b5e07c6fa640fa3647bc619a679a27aaf/Library/Homebrew/version.rb). It's brutal.

**Comment by adityadalal924** [comment]
The only cask I saw that ever implemented either of the two methods was https://github.com/caskroom/homebrew-cask/blob/master/Casks/gcc-arm-embedded.rb, FYI

**Comment by jawshooah** [comment]
@adityadalal924 And it looks like [nobody else is using them](https://github.com/search?utf8=%E2%9C%93&q=language%3Aruby+before_slash+after_slash&type=Code&ref=searchresults), so it's probably safe to toss them I suppose.

**Comment by vitorgalvao** [comment]
> And it looks like nobody else is using them, so it's probably safe to toss them I suppose.

Agreed. Though I also agree that for changes that have been around longer and are in use, @mikemcquaid’s suggestion is the way to go.

So we need:

+ [ ] add `before_comma` and `after_comma`.
+ [ ] add `before_colon` and `after_colon`.
+ [ ] remove `before_slash` and `after_slash`.
+ [ ] fix [`gcc-arm-embedded`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/gcc-arm-embedded.rb).

Do we agree on all of those?

**Comment by vitorgalvao** [comment]
First try at the first four points at https://github.com/caskroom/homebrew-cask/pull/16314.
