### ISSUE TITLE
Removing preferences cache

### ISSUE THREAD

**Issue by niksy** [caskroom/homebrew-cask#16305]
Does Cask runs any special commands for "killing" preferences cache when you zap application's plist files? Since Mavericks, OSX has some aggresive options regarding caching app preferences so just removing plist wont remove preferences if user tries to reinstall app and wants to have clean state. The problem, with proposed solutions, is [described for Moom](https://manytricks.com/blog/?p=3049).

Is this something that could be implemented for app zapping? Has anybody encountered something similar?

**Comment by vitorgalvao** [comment]
There hasn’t yet been a single complaint (I know of/remember) in this regard.

`zap` isn’t exactly meant to reset preferences, but to delete remnants (files) of the app. I don’t see why we couldn’t do both, though.

Closing in favour of https://github.com/caskroom/homebrew-cask/issues/16339.
