### ISSUE TITLE
Cask request: Gear Player for Google Play and Youtube

### ISSUE THREAD

**Issue by Derimagia** [caskroom/homebrew-cask#16307]
### Cask details

(Please fill out as much as possible)

**Name** -
Gear Player for Google Play and Youtube

**Homepage** -
https://www.gearmusicplayer.com/

**License** -
Commercial

**Download URL** -
https://dl.gearmusicplayer.com/gear.zip

**Description** -
Google Play Music native application. Also plays music from YouTube. The best Native Google Play Music application I've seen. Free 14 day trial.

**Comment by adityadalal924** [comment]
Some more information for creating the Cask:

Appcast URL: `dl.gearmusicplayer.com/gearcast.xml`
App Name: `app: Gear Player.app`

`auto_updates`

version :latest/shasum :no_check

**Comment by SirDap** [comment]
i could take this up!

**Comment by adityadalal924** [comment]
Added in https://github.com/caskroom/homebrew-cask/issues/16307

Enjoy!

------

@SirDap Just finished it, unfortunately :p

**Comment by SirDap** [comment]
Haha all good yo
