### ISSUE TITLE
Revert `rubocop` to latest tagged release in Gemfile

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#16318]
Go back to tracking latest release instead of `bbatsov/rubocop/master`

To be done after v0.36 is released

Ref: https://github.com/caskroom/homebrew-cask/pull/16317 (specifically https://github.com/jawshooah/homebrew-cask/commit/b03bfcdb1105cfedac4b468a446739e5f82fc2e7)

**Comment by adityadalal924** [comment]
ping @jawshooah It's out!
https://github.com/bbatsov/rubocop/releases

**Comment by jawshooah** [comment]
It is! Just need to clean up some stuff in rubocop-cask before we update
here.

**Comment by jawshooah** [comment]
Done in #16377.
