### ISSUE TITLE
Can't update brew

### ISSUE THREAD

**Issue by dipu** [caskroom/homebrew-cask#16350]
brew update gives me this error:

elasticsearch-0.20.rb: unmerged (1342018fee546ea9bd5cd25f66e2e389cbd776d9)
elasticsearch-0.20.rb: unmerged (1342018fee546ea9bd5cd25f66e2e389cbd776d9)
elasticsearch090.rb: unmerged (01a1658f00affc4c9e2ff902d9f2192e701c8522)
elasticsearch090.rb: unmerged (01a1658f00affc4c9e2ff902d9f2192e701c8522)
elasticsearch11.rb: unmerged (c4b88e838a578108f55274399b570107a2f5e169)
elasticsearch11.rb: unmerged (c4b88e838a578108f55274399b570107a2f5e169)
elasticsearch12.rb: unmerged (97ff2fe1ded06f209ebf11c8258a305814d6d8c1)
elasticsearch12.rb: unmerged (97ff2fe1ded06f209ebf11c8258a305814d6d8c1)
elasticsearch14.rb: unmerged (3a3272248768f2bd56f9d96cedd9113701cecc5d)
elasticsearch14.rb: unmerged (3a3272248768f2bd56f9d96cedd9113701cecc5d)
fatal: git-write-tree: error building trees
Cannot save the current index state
Error: Failed to update tap: homebrew/versions

I installed cask and and after that brew update is giving this error.

Edit: I also tried to uninstall elasticsearch but it did not work.

Thanks in advance

**Comment by vitorgalvao** [comment]
> I installed cask

How? We’re not installable anymore (homebrew takes care of that).

**Comment by dipu** [comment]
Yes, I saw in the doc that cask is not separately installable currently and I have installed cask earlier not now. I needed cask to install 'packer'. But did not see this error messages before. So, not sure if cask is causing the issue.

**Comment by vitorgalvao** [comment]
> So, not sure if cask is causing the issue.

Likely not. There’s nothing in your report that suggests we are. Either way, run `brew uninstall --force brew-cask; brew update`.

If your issue persists, open the issue with homebrew.
