### ISSUE TITLE
Cask request: ColorSnapper 2

### ISSUE THREAD

**Issue by erichyland** [caskroom/homebrew-cask#16352]
### Cask details

(Please fill out as much as possible)

**Name** - ColorSnapper 2

**Homepage** - http://colorsnapper.com/

**License** - commercial

**Download URL** - https://s3.amazonaws.com/cs2-binaries/ColorSnapper2.dmg

**Description** - The Mac OS X color picker app for designers & developers which makes it easy to collect, adjust, organize and export colors of any pixel on the screen.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/colorsnapper.rb
