### ISSUE TITLE
CONTRIBUTING: Simplify and shorten docs

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#16373]
Right now, [CONTRIBUTING.md](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md) is excellent, but long.

Thoughts I had:

 - Remove second cask example (`genymotion`) - yes, it shows multiple artifact stanzas...but that's about it
 - Promote `appcast`/`shasum` stanzas to "Other commonly-used stanzas" - maybe also auto_updates?
 - Put special use-case stanzas in Cask Language Reference (leave pkg and binary) - the rest can be pretty specialized and just lengthen the document
 - "SourceForge/OSDN URLs" should go...somewhere... It doesn't particularly feel like this is the best spot for it
 - Add `rubocop-cask` mention (again) to Style guide section
 - Add in note about not having extraneous comments in Style section

**Comment by vitorgalvao** [comment]
Agreed on everything, except

> "SourceForge/OSDN URLs" should go...somewhere... It doesn't particularly feel like this is the best spot for it

I don’t think we have a better spot for it, and it is indeed something to be aware of at contribution time.

> Put special use-case stanzas in Cask Language Reference

They should already all be there.

**Comment by adityadalal924** [comment]
I meant remove the rest of the artifacts from CONtRIBUTING
