### ISSUE TITLE
Cask request: Oracle SQL Developer

### ISSUE THREAD

**Issue by elle24** [caskroom/homebrew-cask#16454]
### Cask details

(Please fill out as much as possible)

**Name** - Oracle SQL Developer

**Homepage** - http://www.oracle.com/technetwork/developer-tools/sql-developer/overview/index.html

**License** - free

**Download URL** - http://download.oracle.com/otn/java/sqldeveloper/sqldeveloper-4.1.3.20.78-macosx.app.zip

**Description** - "Oracle SQL Developer is a free integrated development environment that simplifies the development and management of Oracle Database in both traditional and Cloud deployments."

**Comment by bdhess** [comment]
How timely-- I need this right now too.  I'll pump out a cask.

**Comment by adityadalal924** [comment]
FYI, Oracle download links (might) need the `cookie` workaround (as seen in the [Java cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb).

```ruby
  url "http://download.oracle.com/___________",
      :cookies => {
                    'oraclelicense' => 'accept-securebackup-cookie'
                  }
```

**Comment by jawshooah** [comment]
Small style note: for a single-element hash, just leave it on one line.

**Comment by adityadalal924** [comment]
Updated, I was just copying from the existing Cask.

**Comment by bdhess** [comment]
That was my first try, but it doesn't seem to be working - they're using a different license agreement mechanism here, grumble.

**Comment by adityadalal924** [comment]
@bdhess Got it:

```ruby
  url "http://download.oracle.com/___________",
      :cookies => { 'oraclelicense' => 'accept-sqldev-cookie' }
```

**Comment by bdhess** [comment]
Did you actually test that?  I tried that too and it doesn't seem to work.  Trying the combos of cookies I see in my browser.

**Comment by adityadalal924** [comment]
Unfortunately I haven't, just what I saw with a quick glance through the page source.

**Comment by bdhess** [comment]
If I kill my Oracle SSO session, the `oraclelicense` cookie remains, so the download links remain enabled, but I still get redirected to an OTN logon if I follow the download link.  This doesn't look promising. :(

**Comment by bdhess** [comment]
Now I'm seeing that this has already been visited in #9463

**Comment by adityadalal924** [comment]
Even with the cookie enabled, after a few failed tries, it kicks you to an Oracle login. Might need to put this in `unofficial`, if anything
