### ISSUE TITLE
Mention updating `appcast`’s `sha256` in contributing.md

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16464]
I’m currently updating a bunch of casks to their latest versions. In some cases, that means updating simply the `appcast`’s `:sha256` (as everything else is fine, though I am checking every one of them individually).

Some of them have versionless URLs, and some others (so far, just one), were switched from a versioned to a versionless URL (since we can take advantage of CDN like that). Since those casks have `appcast`s, that is actually a good thing since we can still keep the advantages of versions.

After updating all of them, I’ll start working on [the script to check `appcast`s](https://github.com/caskroom/homebrew-cask/issues/15908#issue-122825690) (that will open issues automatically).

@caskroom/maintainers This means that (finally) from now on **updates to casks must include updates to `appcast`’s `:sha256`** as well, and we must ask contributors do so/fix the PRs when they miss it. This also means there should be a short description in CONTRIBUTING.md to explain why and how to do it.

**Comment by adityadalal924** [comment]
I can take care of it as part of https://github.com/caskroom/homebrew-cask/issues/16373

Will be working on that over the next day or so.

**Comment by vitorgalvao** [comment]
Thank you for doing so. Closing in favour of #16373.
