### ISSUE TITLE
Wordpresscom SHA mismatch

### ISSUE THREAD

**Issue by chrisopedia** [caskroom/homebrew-cask#16467]
```sh
#3609: $ brew cask install wordpresscom
==> Downloading https://public-api.wordpress.com/rest/v1.1/desktop/osx/download?type=dmg
Already downloaded: /Library/Caches/Homebrew/wordpresscom-1.1
==> Verifying checksum for Cask wordpresscom
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 300154133f3acda34a4db631cab9f6a5cffa0a7103fffabfd4b96d4f3defa740
Actual: 1a10ba45287e6e3a6cc2c128aed4358e7e6efb1a624f80f6b9fd0cc71528489b
File: /Library/Caches/Homebrew/wordpresscom-1.1
To retry an incomplete download, remove the file above.
```

**Comment by adityadalal924** [comment]
Ah, I see.

`1.1` is the REST endpoint version, not the app version (which is actually `1.2.1`).
I can't find an `appcast` url or a versioned download so we may have to resort to making this cask unversioned.

Pinging @vitorgalvao for thoughts as well.

**Comment by vitorgalvao** [comment]
They indeed use an `appcast` (looking through the code, we can see references to [`auto-updater`](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md) and other clues). But [there’s an easy one we can latch on to](https://github.com/Automattic/wp-desktop/releases).

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/16476.

**Comment by adityadalal924** [comment]
Ah, didn't see the source. Nice catch
