### ISSUE TITLE
Java cask fails to install

### ISSUE THREAD

**Issue by danieljimenez** [caskroom/homebrew-cask#16475]
### Description of issue

Java cask will not install.

### Output of `brew cask install java --verbose`

```
$ brew cask install java --verbose
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-macosx-x64.dmg
Already downloaded: /Library/Caches/Homebrew/java-1.8.0_66-b17.dmg
Error: Permission denied - (/Library/Caches/Homebrew/java-1.8.0_66-b17.dmg, /Library/Caches/Homebrew/Casks/java-1.8.0_66-b17.dmg)

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:347:in `ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:370:in `ln_sf'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:45:in `create_cache_symlink'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:94:in `download'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:68:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:6:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:78:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:116:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:69:in `require?'
/usr/local/Library/brew.rb:149:in `<main>'
Error: Kernel.exit
```

### Output of `brew doctor`

```
$ brew doctor
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
$ brew cask doctor
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 3f86; last commit 2016-01-07)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision a595; last commit 41 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2941
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```

**Comment by adityadalal924** [comment]
`Error: Permission denied - (/Library/Caches/Homebrew/java-1.8.0_66-b17.dmg, /Library/Caches/Homebrew/Casks/java-1.8.0_66-b17.dmg)`

Seems to be the issue, can you list ownerships for Caskroom and the cache folder?

**Comment by danieljimenez** [comment]
Which directories exactly? FWIW I've reproduced this on several machines, and triple checked the permissions to `/Library/Caches/Homebrew/java-1.8.0_66-b17.dmg`.

**Comment by adityadalal924** [comment]
@vitorgalvao Any suggestions? I haven't run into too many permissions issues so I'm not sure where to go from here.

**Comment by danieljimenez** [comment]
Have there been any changes to this cask recently? It was working in El Cap okay at one point.

**Comment by danieljimenez** [comment]
Doing `sudo brew cask install java` works, not sure if that provides any insight.

**Comment by vitorgalvao** [comment]
There’s nothing wrong with the cask itself. It can’t even begin to install since it can’t get the permissions to access the dmg. Have you tried with other apps?

**Comment by danieljimenez** [comment]
@vitorgalvao, All other casks work great. I just tried this on a brand new fresh from Apple Mac after a fresh homebrew install, and it fails.

**Comment by vitorgalvao** [comment]
> I just tried this on a brand new fresh from Apple Mac after a fresh homebrew install, and it fails.

I can’t reproduce on a clean VM.

**Comment by danieljimenez** [comment]
So we're at a deadlock?

**Comment by danieljimenez** [comment]
I deleted that file, ran `brew cask zap java`. Now I'm getting this:

```
Error: File exists - (/Library/Caches/Homebrew/java-1.8.0_66-b17.dmg, /Library/Caches/Homebrew/Casks/java-1.8.0_66-b17.dmg)
```

**Comment by vitorgalvao** [comment]
> So we're at a deadlock?

Unfortunately, yes. Currently, you’re the only experiencing this, so unless someone comes up with an insight or is able to reproduce, not much we can do. Will leave it open for a while.

**Comment by danieljimenez** [comment]
I can easily reproduce. How can I show you? VagrantFile?

**Comment by vitorgalvao** [comment]
I don’t use Vagrant. You need to pay to use it with VMware, don’t you? And I can’t do it with Virtualbox since it doesn’t work on my computer to virtualise OS X (it did on my previous one).

In addition, like I said, you seem to be the only one experiencing this, which suggests something in your configuration, and not homebrew-cask itself. Though I’d like to have this fixed for you, if it isn’t caused by us, I won’t spend a huge amount of time trying to configure stuff just to see if I can reproduce, just to see if I can fix it. That part has to be left to you, I’m afraid. Clearly there’s a way for that issue not to happen, and it’s far easier to make than the reverse.

Again, I’ll gladly leave this open a few more days to see if some insight comes along, but there are many things left to do in homebrew-cask, and debugging the unreproducible error of a single user is not a good use of time.

**Comment by danieljimenez** [comment]
> I don’t use Vagrant. You need to pay to use it with VMware, don’t you? And I can’t do it with Virtualbox since it doesn’t work on my computer to virtualise OS X (it did on my previous one).

Virtualizing OS X works great with Virtualbox. I do it on literally a dozen machines for integration testing of Chef cookbooks. That's how I discovered this very issue actually, an integration test that was once passing, no longer passes. 

> ...and debugging the unreproducible error of a single user...
I just said it's reproducible. How would you like me to prove that to you? Do you think I'm making this up?

I'll close this issue find a more reliable way to get packages installed other than `homebrew-cask`.

**Comment by vitorgalvao** [comment]
> Virtualizing OS X works great with Virtualbox.

Not on a retina MacBook Pro, it doesn’t. When I got it it wasn’t possible at all (not sure how everything evolved since).

> I just said it's reproducible. How would you like me to prove that to you? Do you think I'm making this up?
> I'll close this issue find a more reliable way to get packages installed other than `homebrew-cask`.

I’m not doubting you. Like I said, *I* can’t reproduce it, and *I* won’t spend **hours of my own free time** setting up a purposefully failing system just so I can reproduce your own failing issue, while you sit idly.

It’s always the users like you who never contributed jack shit to homebrew-cask who act the more entitled. Let me be clear: no one in this team owes you anything, and your usage didn’t advance the project in the slightest.

Good riddance.
