### ISSUE TITLE
`audit --download` should check appcast as well

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16529]
This is a typical version bump PR:

![image](https://cloud.githubusercontent.com/assets/1699443/12183357/41519dde-b586-11e5-9986-3f279537ae8c.png)

Which means something (now) important and (currently) unchecked might be lurking under.

![image](https://cloud.githubusercontent.com/assets/1699443/12183280/df6bd170-b585-11e5-9f2b-c9b8454646d6.png)

Having to do this for every PR will likely makes us miss some.

Solution: make Travis check for it. Better solution: make `audit` do the work, since it seems appropriate. Also, we’ll get [`audit_modified_casks`](https://github.com/caskroom/homebrew-cask/blob/master/developer/bin/audit_modified_casks) for free.

It makes sense to only check for it on `audit --download`, since otherwise the cask might be correct. It should do three checks:

+ [ ] Does `appcast` return a 200 HTTP response code?
+ [x] Is `checkpoint:` different than `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (empty string)?
+ [ ] Is `checkpoint:` correct?

**Comment by adityadalal924** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/audit.rb

(2) is already checked for.

(1) and (3) could be done by extending `check_download`, as technically the same thing is already done for `url`
