### ISSUE TITLE
Better formula tracking

### ISSUE THREAD

**Issue by shrx** [caskroom/homebrew-cask#1654]
When you rename a formula, it should be aware of its previous name. For example, when you removed hyphens from `j-downloader` and `command-q`, instead of recognizing the new appropriate names, I get an error message that the casks are not available.

**Comment by vitorgalvao** [comment]
This is connected with other issues (like `list` being broken), and something that is not forgotten, but should be solved when some restructuring is done, which is part of the near-future goals.
