### ISSUE TITLE
Speeding up Travis Builds

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-cask#16566]
More of a brainstorming issue, but since Travis takes ~30 minutes/PR now:

> `Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.`

Can we use a newer gem version?

Based on https://docs.travis-ci.com/user/speeding-up-the-build/ we can split up "core" tests and "audit" tests. That, combined with "fail-fast", could speed things up.

Should we cut down on the testing matrix? (ie only test 10.11?)

**Comment by jawshooah** [comment]
> Travis takes ~30 minutes/PR now

Not quite. That's the *total* duration, i.e. the sum of the durations of each of the parallelized builds. Unfortunately they don't provide something like `max(end_time) - min(start_time)`, though [it continues to be discussed](https://github.com/travis-ci/travis-ci/issues/1486).

> Can we use a newer gem version?

Yes, but that would require `sudo`, which we don't want if we want caching to ([eventually](https://github.com/travis-ci/travis-ci/issues/4011)) work.

> Based on https://docs.travis-ci.com/user/speeding-up-the-build/ we can split up "core" tests and "audit" tests. That, combined with "fail-fast", could speed things up.

We could do that, or we could be smart about which checks we run for each build. For example, if only casks have changed, skip the test suite.

> Should we cut down on the testing matrix? (ie only test 10.11?)

10.10 and 10.9 still have significant market share, so I think we should continue to ensure we don't break them.

**Comment by jawshooah** [comment]
If you look at the difference in finish time between builds, you'll see they average around 6 minutes:

![build timestamps](https://www.dropbox.com/s/o26wa7td1bodwe2/Screenshot%202016-01-08%2001.21.42.png?raw=1)

**Comment by jawshooah** [comment]
@adityadalal924 does #16570 seem sufficient to close this?

**Comment by adityadalal924** [comment]
Yep, that works well
