### ISSUE TITLE
`depends_on_java` followups

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16591]
Refs https://github.com/caskroom/homebrew-cask/pull/16385

> we can start fixing:

> + [x] https://github.com/caskroom/homebrew-cask/issues/4885
> + [x] https://github.com/caskroom/homebrew-cask/search?utf8=%E2%9C%93&q=brew+cask+install+java

> And others as we notice them.

**Comment by adityadalal924** [comment]
We don't want to lose (minimum) version information - how should that be handled?
ie. https://github.com/caskroom/homebrew-cask/blob/master/Casks/panoply.rb requires java 7+, but only an integer can be used.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/16594.

**Comment by vitorgalvao** [comment]
Closing. All done, just pending audit and merge.
