### ISSUE TITLE
Office 2011 for Mac should remain as separate cask

### ISSUE THREAD

**Issue by atais** [caskroom/homebrew-cask#16617]
https://github.com/caskroom/homebrew-cask/commit/980a41121cfcf0aa605d653b2d32a3cb2923cb18#diff-0d158b112acef010cf12aa697463a3f3

Here Office for Mac was updated to 2016 version. 
However I still have only 2011 version and I am not going to upgrade right now.

I wish to install it with cask, but it is not possible.
Could it be restored and maintained separately?

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-versions/blob/master/Casks/microsoft-office-2011.rb.

`brew cask install caskroom/versions/microsoft-office-2011`.
