### ISSUE TITLE
Cask request: Pycharm community edition

### ISSUE THREAD

**Issue by nyanchan** [caskroom/homebrew-cask#16677]
### Cask details

(Please fill out as much as possible)

**Name** - pycharm-ce

**Homepage** - https://www.jetbrains.com/pycharm/

**License** - ?

**Download URL** - https://www.jetbrains.com/pycharm/download/download-thanks.html?platform=mac&code=PCC

**Description** - Pycharm (Python IDE) community edition. The professional edition and the edu edition are already available but not the community edition.

**Comment by vitorgalvao** [comment]
In [caskroom/versions](https://github.com/caskroom/homebrew-versions)

**Comment by nyanchan** [comment]
Sorry, didn't know about caskroom/versions. Thanks!
