### ISSUE TITLE
Cask request: https://www.jetbrains.com/idea/

### ISSUE THREAD

**Issue by nyanchan** [caskroom/homebrew-cask#16678]
### Cask details

(Please fill out as much as possible)

**Name** - intellij-idea-ce

**Homepage** - https://www.jetbrains.com/idea/

**License** - ?

**Download URL** - https://www.jetbrains.com/idea/download/download-thanks.html?code=IIC

**Description** - Intellij Community Edition. At the moment only professional version is available. Intellij Community Edition was once available as 'intellij-idea-ce' but as of 9.1.20116 it is not available anymore.

**Comment by vitorgalvao** [comment]
In [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by nyanchan** [comment]
Sorry, didn't know about caskroom/versions. Thanks!
