### ISSUE TITLE
brew cask autocompletion not working

### ISSUE THREAD

**Issue by faxotherapy** [caskroom/homebrew-cask#16679]
Hello,

I have done ``brew install `zsh-completions``, set ``fpath=(/usr/local/share/zsh-completions $fpath)`` in Z shell config file and ``.zcompdump``. I have even rehashed. When I type in ``brew cask info mpl`` followed by [TAB] in the hope completion will be made up to ``ayer``, it doesn't work.

It still perfectly works when I input ``brew info mpl`` followed by [TAB]

Thanks for your help,

Faxo

**Comment by faxotherapy** [comment]
(I have removed all ``zcompdump`` files) but with no effect.

**Comment by vitorgalvao** [comment]
We have no affiliation with those completions. You’ll have to report that to their developers (`brew home zsh-completions`).
