### ISSUE TITLE
Add appcast to sourceforge casks

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16685]
Refs https://github.com/caskroom/homebrew-cask/pull/16683#issuecomment-170348241.

Sourceforge projects seem to have simple and predictable appcasts, just like github projects: `http://downloads.sourceforge.net/projects/{{project_name}}/rss`. A more specific rss can be used as needed, pointing to a specific directory structure: `http://sourceforge.net/projects/{{project_name}}/rss?path=/{{path_here}}`.

---

List of casks in [caskroom/cask](https://github.com/caskroom/homebrew-cask) missing `appcast`

```bash
for cask in $(grep --files-with-matches "url ['\"].*sourceforge.*" "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks/"*); do
  appcast="$(brew cask _stanza appcast "${cask}")"
  if [[ -z "${appcast}" ]]; then
    cask_filename="$(basename "${cask}")"
    cask_name="${cask_filename%.*}"
    echo "- [ ] [${cask_name}](../blob/master/Casks/${cask_filename})"
  fi
done | pbcopy
```

- [ ] [aquaterm](../blob/master/Casks/aquaterm.rb)
- [ ] [aria-maestosa](../blob/master/Casks/aria-maestosa.rb)
- [ ] [arrsync](../blob/master/Casks/arrsync.rb)
- [ ] [art-of-illusion](../blob/master/Casks/art-of-illusion.rb)
- [ ] [audioslicer](../blob/master/Casks/audioslicer.rb)
- [ ] [avidemux](../blob/master/Casks/avidemux.rb)
- [ ] [avogadro](../blob/master/Casks/avogadro.rb)
- [ ] [bitpim](../blob/master/Casks/bitpim.rb)
- [ ] [brain-workshop](../blob/master/Casks/brain-workshop.rb)
- [ ] [breakaway](../blob/master/Casks/breakaway.rb)
- [ ] [brushviewql](../blob/master/Casks/brushviewql.rb)
- [ ] [burn](../blob/master/Casks/burn.rb)
- [ ] [butt](../blob/master/Casks/butt.rb)
- [ ] [camed](../blob/master/Casks/camed.rb)
- [ ] [celestia](../blob/master/Casks/celestia.rb)
- [ ] [chessx](../blob/master/Casks/chessx.rb)
- [ ] [codeblocks](../blob/master/Casks/codeblocks.rb)
- [ ] [cuda-z](../blob/master/Casks/cuda-z.rb)
- [ ] [cutesdr](../blob/master/Casks/cutesdr.rb)
- [ ] [data-integration](../blob/master/Casks/data-integration.rb)
- [ ] [davmail](../blob/master/Casks/davmail.rb)
- [ ] [desmume](../blob/master/Casks/desmume.rb)
- [ ] [dia](../blob/master/Casks/dia.rb)
- [ ] [diashapes](../blob/master/Casks/diashapes.rb)
- [ ] [djv](../blob/master/Casks/djv.rb)
- [ ] [djview](../blob/master/Casks/djview.rb)
- [ ] [doomsday-engine](../blob/master/Casks/doomsday-engine.rb)
- [ ] [dosbox](../blob/master/Casks/dosbox.rb)
- [ ] [double-commander](../blob/master/Casks/double-commander.rb)
- [ ] [doublecommand](../blob/master/Casks/doublecommand.rb)
- [ ] [dukto](../blob/master/Casks/dukto.rb)
- [ ] [dvdstyler](../blob/master/Casks/dvdstyler.rb)
- [ ] [eiskaltdcpp](../blob/master/Casks/eiskaltdcpp.rb)
- [ ] [excalibur](../blob/master/Casks/excalibur.rb)
- [ ] [filebot](../blob/master/Casks/filebot.rb)
- [ ] [filezilla](../blob/master/Casks/filezilla.rb)
- [ ] [fldigi](../blob/master/Casks/fldigi.rb)
- [ ] [fpc](../blob/master/Casks/fpc.rb)
- [ ] [fpcsrc](../blob/master/Casks/fpcsrc.rb)
- [ ] [freac](../blob/master/Casks/freac.rb)
- [ ] [fredm-fuse](../blob/master/Casks/fredm-fuse.rb)
- [ ] [freecad](../blob/master/Casks/freecad.rb)
- [ ] [freecol](../blob/master/Casks/freecol.rb)
- [ ] [freelib](../blob/master/Casks/freelib.rb)
- [ ] [freemind](../blob/master/Casks/freemind.rb)
- [ ] [freeplane](../blob/master/Casks/freeplane.rb)
- [ ] [fugenschnitzer](../blob/master/Casks/fugenschnitzer.rb)
- [ ] [fugu](../blob/master/Casks/fugu.rb)
- [ ] [fwbuilder](../blob/master/Casks/fwbuilder.rb)
- [ ] [git](../blob/master/Casks/git.rb)
- [ ] [glcplayer](../blob/master/Casks/glcplayer.rb)
- [ ] [golly](../blob/master/Casks/golly.rb)
- [ ] [gpodder](../blob/master/Casks/gpodder.rb)
- [ ] [handy-outliner](../blob/master/Casks/handy-outliner.rb)
- [ ] [hugin](../blob/master/Casks/hugin.rb)
- [ ] [instead](../blob/master/Casks/instead.rb)
- [ ] [jahshaka](../blob/master/Casks/jahshaka.rb)
- [ ] [jaspersoft-studio](../blob/master/Casks/jaspersoft-studio.rb)
- [ ] [jedit](../blob/master/Casks/jedit.rb)
- [ ] [jin](../blob/master/Casks/jin.rb)
- [ ] [jubler](../blob/master/Casks/jubler.rb)
- [ ] [jxplorer](../blob/master/Casks/jxplorer.rb)
- [ ] [kdiff3](../blob/master/Casks/kdiff3.rb)
- [ ] [keystore-explorer](../blob/master/Casks/keystore-explorer.rb)
- [ ] [kid3](../blob/master/Casks/kid3.rb)
- [ ] [kiwix](../blob/master/Casks/kiwix.rb)
- [ ] [kompozer](../blob/master/Casks/kompozer.rb)
- [ ] [lazarus](../blob/master/Casks/lazarus.rb)
- [ ] [lazpaint](../blob/master/Casks/lazpaint.rb)
- [ ] [letterfix](../blob/master/Casks/letterfix.rb)
- [ ] [librecad](../blob/master/Casks/librecad.rb)
- [ ] [lisanet-gimp](../blob/master/Casks/lisanet-gimp.rb)
- [ ] [liteide](../blob/master/Casks/liteide.rb)
- [ ] [logisim](../blob/master/Casks/logisim.rb)
- [ ] [luminance-hdr](../blob/master/Casks/luminance-hdr.rb)
- [ ] [lynkeos](../blob/master/Casks/lynkeos.rb)
- [ ] [maciasl](../blob/master/Casks/maciasl.rb)
- [ ] [mame](../blob/master/Casks/mame.rb)
- [ ] [media-converter](../blob/master/Casks/media-converter.rb)
- [ ] [mediathekview](../blob/master/Casks/mediathekview.rb)
- [ ] [meshlab](../blob/master/Casks/meshlab.rb)
- [ ] [meteorologist](../blob/master/Casks/meteorologist.rb)
- [ ] [miditrail](../blob/master/Casks/miditrail.rb)
- [ ] [mmex](../blob/master/Casks/mmex.rb)
- [ ] [moreamp](../blob/master/Casks/moreamp.rb)
- [ ] [mozart](../blob/master/Casks/mozart.rb)
- [ ] [nightingale](../blob/master/Casks/nightingale.rb)
- [ ] [nodeclipse](../blob/master/Casks/nodeclipse.rb)
- [ ] [ntfs-free](../blob/master/Casks/ntfs-free.rb)
- [ ] [octave](../blob/master/Casks/octave.rb)
- [ ] [openmsx](../blob/master/Casks/openmsx.rb)
- [ ] [opennx](../blob/master/Casks/opennx.rb)
- [ ] [openoffice](../blob/master/Casks/openoffice.rb)
- [ ] [opensong](../blob/master/Casks/opensong.rb)
- [ ] [osxfuse](../blob/master/Casks/osxfuse.rb)
- [ ] [panini](../blob/master/Casks/panini.rb)
- [ ] [pd-extended](../blob/master/Casks/pd-extended.rb)
- [ ] [plotdigitizer](../blob/master/Casks/plotdigitizer.rb)
- [ ] [polyphone](../blob/master/Casks/polyphone.rb)
- [ ] [projectlibre](../blob/master/Casks/projectlibre.rb)
- [ ] [psi](../blob/master/Casks/psi.rb)
- [ ] [pullover](../blob/master/Casks/pullover.rb)
- [ ] [qbittorrent](../blob/master/Casks/qbittorrent.rb)
- [ ] [qtspim](../blob/master/Casks/qtspim.rb)
- [ ] [relaunch64](../blob/master/Casks/relaunch64.rb)
- [ ] [rssowl](../blob/master/Casks/rssowl.rb)
- [ ] [sabnzbd](../blob/master/Casks/sabnzbd.rb)
- [ ] [sauerbraten](../blob/master/Casks/sauerbraten.rb)
- [ ] [scribus](../blob/master/Casks/scribus.rb)
- [ ] [simpletag](../blob/master/Casks/simpletag.rb)
- [ ] [sqlexplorer](../blob/master/Casks/sqlexplorer.rb)
- [ ] [stella](../blob/master/Casks/stella.rb)
- [ ] [stellarium](../blob/master/Casks/stellarium.rb)
- [ ] [supercollider](../blob/master/Casks/supercollider.rb)
- [x] [supertuxkart](../blob/master/Casks/supertuxkart.rb)
- [ ] [svgcleaner](../blob/master/Casks/svgcleaner.rb)
- [ ] [sweet-home3d](../blob/master/Casks/sweet-home3d.rb)
- [ ] [tag](../blob/master/Casks/tag.rb)
- [ ] [texstudio](../blob/master/Casks/texstudio.rb)
- [ ] [timeedition](../blob/master/Casks/timeedition.rb)
- [ ] [transmission-remote-gui](../blob/master/Casks/transmission-remote-gui.rb)
- [ ] [tuntap](../blob/master/Casks/tuntap.rb)
- [ ] [tuxguitar](../blob/master/Casks/tuxguitar.rb)
- [ ] [tv-browser](../blob/master/Casks/tv-browser.rb)
- [ ] [ultrastardeluxe](../blob/master/Casks/ultrastardeluxe.rb)
- [ ] [universal-media-server](../blob/master/Casks/universal-media-server.rb)
- [ ] [upm](../blob/master/Casks/upm.rb)
- [ ] [vassal](../blob/master/Casks/vassal.rb)
- [ ] [virtaal](../blob/master/Casks/virtaal.rb)
- [ ] [vistrails](../blob/master/Casks/vistrails.rb)
- [ ] [weka](../blob/master/Casks/weka.rb)
- [ ] [wesnoth](../blob/master/Casks/wesnoth.rb)
- [ ] [wineskin-winery](../blob/master/Casks/wineskin-winery.rb)
- [ ] [wings3d](../blob/master/Casks/wings3d.rb)
- [ ] [xampp](../blob/master/Casks/xampp.rb)
- [ ] [xaos](../blob/master/Casks/xaos.rb)
- [ ] [xca](../blob/master/Casks/xca.rb)
- [ ] [zeroinstall](../blob/master/Casks/zeroinstall.rb)

---

List of casks in [caskroom/versions](https://github.com/caskroom/homebrew-versions) missing `appcast`

```bash
for cask in $(grep --files-with-matches "url ['\"].*sourceforge.*" "$(brew --repository)/Library/Taps/caskroom/homebrew-versions/Casks/"*); do
  appcast="$(brew cask _stanza appcast "${cask}")"
  if [[ -z "${appcast}" ]]; then
    cask_filename="$(basename "${cask}")"
    cask_name="${cask_filename%.*}"
    echo "- [ ] [${cask_name}](../blob/master/Casks/${cask_filename})"
  fi
done | pbcopy
```

- [ ] [cuda-z-beta](../blob/master/Casks/cuda-z-beta.rb)
- [ ] [openoffice-fr](../blob/master/Casks/openoffice-fr.rb)
- [ ] [openoffice-gl](../blob/master/Casks/openoffice-gl.rb)
- [ ] [openoffice-pt-pt](../blob/master/Casks/openoffice-pt-pt.rb)
- [ ] [weka-dev](../blob/master/Casks/weka-dev.rb)

**Comment by adityadalal924** [comment]
Based on https://github.com/caskroom/homebrew-cask/issues/16949, issue can be reopened

**Comment by elnappo** [comment]
sabnzbd is no longer hosted on sourceforge, see #19887

**Comment by vitorgalvao** [comment]
@elnappo Updated list. Thank you.

**Comment by reitermarkus** [comment]
Closing this, as there are no SourceForge casks left without an `appcast`.
