### ISSUE TITLE
Shourtcuts in ~/Applications instead of /Applications

### ISSUE THREAD

**Issue by atais** [caskroom/homebrew-cask#16686]
Hi, I am actually using Polish version of MacOS 10.11 but I do not think that is the problem.

Basically when I install any application with ```brew cask``` the shortcut is being created in ```~/Applications```. It would be nothing wrong, the application is easily reachable and working with *Spotlight* **but** when I install an app in traditional way, the ```.app``` file is in ```/Applications```.

**The only moment it matters is**, when I want to change a default program to run something, or well - basically I want to find the **.app** file, I need to check both directories if I am not sure how I have downloaded the app.

So what is the reasoning behind it, why the shortcuts are in local folder?
I do not know how to mark it, it is kind of a question, not issue exactly.

Should I move the shortcuts manually to global folder?

**Comment by vitorgalvao** [comment]
> So what is the reasoning behind it, why the shortcuts are in local folder?

That was an old decision that has never been fixed, but will change with https://github.com/caskroom/homebrew-cask/issues/13201.

You can [change that directory yourself](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options), though.
