### ISSUE TITLE
CONTRIBUTING: explain how to add appcasts

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16689]
Expands on https://github.com/caskroom/homebrew-cask/issues/16464. That one was about updating, this is about creating.

There are some [doubts as to how to create `appcast`s](https://github.com/caskroom/homebrew-cask/pull/16683#issue-125811449). That is merely an example of someone that expressed it, though, as I also see new contributions that could easily have an `appcast` added (github releases), but don’t. We should really add a how to add them.

+ [x] Explain how to find them:
  + [x] If the cask uses the `app` stanza, look inside its `Info.plist` for the `SUFeedURL`.
    + [x] Make `/developer/bin` script for it.
  + [x] If the app is distributed via gitub releases, `appcast` will be of the form `https://github.com/{{user}}/{{project}}/releases.atom`.
  + [x] An `appcast` can be any URL hosted by the app’s developer that changes every time a new release is out (e.g. a changelog).
+ [x] Explain how to find its `:checkpoint` (`curl --compressed '{{appcast_url}} | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{print $1}'`).
+ [x] Add documentation from https://github.com/caskroom/homebrew-cask/issues/16689#issuecomment-170583701 to live docs.

**Comment by adityadalal924** [comment]
I can tackle this as part of an upcoming (further) rewrite of CONTRIBUTING

**Comment by vitorgalvao** [comment]
@adityadalal924 Will leave the documentation to you, then.

As for the script, adding it in https://github.com/caskroom/homebrew-cask/pull/16701.

**Comment by adityadalal924** [comment]
This is getting quite a bit of usage already - I'll draft up something that can be added to the relevant documentation soon.

**Comment by adityadalal924** [comment]
## Appcasts

Appcasts provide a mechanism for updates to applications. There are a few different ways these can be determined:

 - If the app is distributed via GitHub releases, the `appcast` will be of the form `https://github.com/{{user}}/{{project}}/releases.atom`. [Example of Cask]()
 - A popular update framework, [Sparkle](http://sparkle-project.org) generally uses the `SUFeedURL` property inside `Contents/Info.plist`. You can use the script `developer/bin/find_sparkle_appcast` to add this automatically. [Example of Cask]()
- An appcast can be any URL hosted by the app’s developer that changes every time a new release is out (e.g. a changelog RSS feed). [Example of Cask]()


Appcasts have a required `:sha256` property. You can use  `(curl '{{appcast_url}} | shasum --algorithm 256)` to get the shasum for the appcast.

If the application has a `Check for Updates...` option in its menu, you should also add 'auto_updates true` to the Cask.

**Comment by adityadalal924** [comment]
@vitorgalvao Documentation above should now be ready, according to recent updates.

**Comment by vitorgalvao** [comment]
@adityadalal924 I saw. I was editing your post (after editing the top one) and github warned me “the content you’re trying to edit has changed”.

**Comment by vitorgalvao** [comment]
@adityadalal924 Oh, you called it `:checkpoint` already, even. That I hadn’t noticed.

**Comment by adityadalal924** [comment]
Still undecided about `{{appcast_url}}` vs `$appcast_url` styling for user-replaced variables. If you like that then CONTRIBUTING.MD should also use that style - whatever we decide, it should be consistent (We can always add a footnote about this format and what it means as extra clarification)

**Comment by vitorgalvao** [comment]
> Still undecided about `{{appcast_url}}` vs `$appcast_url` styling for user-replaced variables.

Whatever you prefer. You’ve been working more on CONTRIBUTING, so I trust the decision to you.

I somewhat prefer `${appcast_url}` to `$appcast_url`, though (same with other variables) as it’s clearer where it begins and ends.

**Comment by vitorgalvao** [comment]
Made another change (addition) to the command. `curl` now uses `--compressed`. It doesn’t change anything in the ones that were already set, but it lets us use the ones that are gzipped on transfer.

**Comment by adityadalal924** [comment]
Will update as script is updated in `cask-repair` (I'm using that as "ground truth" for the documentation for now)

**Comment by vitorgalvao** [comment]
`curl --silent 'https://raw.githubusercontent.com/vitorgalvao/tiny-scripts/master/cask-repair' | grep 'pubDate'` should be a quick way to see how it currently works in `cask-repair`. It’s unlikely there’ll be more changes, though.
