### ISSUE TITLE
trying to install Private-Internet-Access, getting "LSOpenURLsWithRole() failed with error -10810"

### ISSUE THREAD

**Issue by tconroy** [caskroom/homebrew-cask#16694]
```
$ brew cask install private-internet-access
==> Downloading https://www.privateinternetaccess.com/installer/installer_osx.dmg
######################################################################## 100.0%
==> No checksum defined for Cask private-internet-access, skipping verification
==> Running installer script Private Internet Access Installer.app/Contents/MacOS/runner.sh
Password:
==>
==> No matching processes were found
==> LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Private Internet Access.app.
🍺  private-internet-access staged at '/opt/homebrew-cask/Caskroom/private-internet-access/latest' (74 files, 21M)
```

Any ideas?

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by adityadalal924** [comment]
Looks like an upstream issue, anyway

**Comment by tconroy** [comment]
Hey there!
Apologies. I've gone through the guide and did the steps, and fortunate for me the app downloaded (seemingly) just fine after removing the old system (I haven't used homebrew/cask in awhile). 

However, I can't seem to actually launch the app. It's a VPN client, and when I try and connect to the VPN within the App I just repeatedly get this system prompt: "networksetup is trying to modify the system network configuration. Type your password to allow this." 

screenshot: http://i.imgur.com/uCk3LqF.png

No matter how many times I enter my login credentials, the prompt just instantly re-opens and I never connect to the VPN.


Probably not a question you fine folks can answer for me unfortunately but I'm at my wits end and the PIA support is absolutely terrible and has been of no help. If anyone has any ideas how I could confirm this prompt for good I'd be eternally grateful. :+1:

**Comment by vitorgalvao** [comment]
Yep, this is out of our domain, you’ll have to ask them.

**Comment by jawshooah** [comment]
I actually had the same problem when I tried installing PIA a year ago, but never found a fix. I think we'll have to demote this one to `installer :manual`, unfortunately.

**Comment by tconroy** [comment]
@jawshooah bouncing around online it seems like a decent number of people have had this issue, but no working resolution. I've tried to install the app from the PIA website as well (after attempting install with cask) and still get the same error.

If I create a new account profile, I'm able to install the app from their website.. right now I don't really care how I install it as long as I can install it on the profile I actually use :\

**Comment by jawshooah** [comment]
@tconroy I remember having some trouble getting a proper uninstall working, but If I recall correctly this worked:

```bash
brew install psgrep
psgrep -a pia | tail -n+2 | awk '{print $2}' | xargs kill
rm -rf ~/.pia_manager
rm -rf '/Applications/Private Internet Access.app'
rm -f /private/tmp/pia_*
```

Then download and run the installer again and it should work. If not, repeat the above steps, restart, and try again.

PIA really is a PITA :wink:
