### ISSUE TITLE
aliases for more JetBrains products

### ISSUE THREAD

**Issue by mcandre** [caskroom/homebrew-cask#16704]
Please create aliases so that JetBrains IDEs like WebStorm can be installed as `webstorm`, etc. Some JetBrains products like IntelliJ already have the appropriate aliases.

**Comment by tsparber** [comment]
`brew cask install webstorm` exists.

There are already many jetbrains products.
See [caskroom/homebrew-cask](https://github.com/caskroom/homebrew-cask/search?utf8=%E2%9C%93&q=jetbrains) and more in [caskroom/homebrew-versions](https://github.com/caskroom/homebrew-versions/search?utf8=%E2%9C%93&q=jetbrains).

If you know a missing app you are free to contribute it either as [a cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask) or as a [cask request](https://github.com/caskroom/homebrew-cask/issues/new?title=Cask%20request%3A&body=%23%23%23%20Cask%20details%0A%0A%28Please%20fill%20out%20as%20much%20as%20possible%29%0A%0A**Name**%20-%0A%0A**Homepage**%20-%0A%0A**License**%20-%0A%0A**Download%20URL**%20-%0A%0A**Description**%20-%0A).
