### ISSUE TITLE
Editorial Issues With `brew-cask` v0.60.1

### ISSUE THREAD

**Issue by RandomDSdevel** [caskroom/homebrew-cask#16751]
Something seems to have gone wrong when you guys pushed PR #16699.  It isn't marked as the latest release on your ['Releases' page](https://github.com/caskroom/homebrew-cask/releases), and it also doesn't have any release notes.  I assume you just forgot to make those changes when you pushed the PR, right?

**Comment by adityadalal924** [comment]
It's a bug fix release to fix issues with Homebrew, not sure that's there's any need for actual release notes. The tag just needed to be incremented

**Comment by RandomDSdevel** [comment]
@adityadalal924:  Sorry; the inconsistency with all of the other release tags just bugged me.  The last minor Cask release (v0.54.1) had proper release notes, so I thought v0.60.1 might need some as well.  If that's not the case, then we can close this issue and move on.

**Comment by adityadalal924** [comment]
@jawshooah Thoughts?

Maybe just a line like `This is a bugfix release, all notes from 0.60 apply)`

**Comment by RandomDSdevel** [comment]
@adityadalal924, @jawshooah:  I agree, but you might also want to include a note about the fact that PR #16699 making Cask take the results of [Homebrew PR #47887](https://github.com/Homebrew/homebrew/pull/47887) into account in order to prevent problems from happening as well.

**Comment by adityadalal924** [comment]
Added some release notes which should clear things up.

If it looks fine, feel free to close this issue, else, let us know.

**Comment by RandomDSdevel** [comment]
Thanks, as that addresses my concern.  I do have one more editorial comment, though:  shouldn't 'This is a purely bugfix release…' be 'This is purely a bugfix release…?'

**Comment by adityadalal924** [comment]
Got rid of the word purely, it seemed unneeded after all.

**Comment by RandomDSdevel** [comment]
That settles that, then.  See you on the flip side.
