### ISSUE TITLE
kicad.rb adds symlink to wrong folder

### ISSUE THREAD

**Issue by adzenith** [caskroom/homebrew-cask#16775]
`brew cask install kicad` adds a symlink called "Kicad" to my Applications folder. This symlink goes to an empty folder. If I go up a directory, there's a sibling folder which contains KiCad.app. The incorrect folder is called "Kicad-apps", whereas the correct folder is called "Kicad".

Thanks!

[`cask doctor` output](https://gist.github.com/adzenith/9160c51ef157f100f88f)

**Comment by adzenith** [comment]
[`cask doctor output`](https://gist.github.com/adzenith/9160c51ef157f100f88f)

**Comment by adityadalal924** [comment]
Ah, `kicad` was a "fun" one - they packaged things really poorly so we had to use a (terrible) workaround.
See https://github.com/caskroom/homebrew-cask/pull/15692 for details.

**Comment by adityadalal924** [comment]
So, what *should* happen is:

 - Make a new folder called `Kicad-apps`
 - Move `*.app` into `Kicad-apps`
 - Symlink `Kicad-apps` to `Kicad` (folder) - this is what you should see in `/Applications`
 - Symlink `kicad` (from the `.dmg`) `{ENV['HOME']}/Library/Application Support/kicad`

Jus to clarify - can you confirm which steps are failing?

**Comment by adityadalal924** [comment]
Please also post the full output of `brew cask install kicad --verbose`

**Comment by adzenith** [comment]
```
09:59:24 ~ (master)$ brew cask install kicad --verbose
==> Downloading http://downloads.kicad-pcb.org/osx/stable/kicad-4.0.1.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-645) http://downloads.kicad-pcb.org/osx/stable/kicad-4.0.1.dmg -C 0 -o /Library/Caches/Homebrew/kicad-4.0.1.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  184M  100  184M    0     0   933k      0  0:03:22  0:03:22 --:--:-- 1208k
==> Verifying checksum for Cask kicad
mv: rename /opt/homebrew-cask/Caskroom/kicad/4.0.1/Kicad/*.app to /opt/homebrew-cask/Caskroom/kicad/4.0.1/Kicad-apps/*.app: No such file or directory
==> Symlinking App Suite 'Kicad-apps' to '/Applications/Kicad'
==> Symlinking Generic artifact 'kicad' to '/Users/nikolaus/Library/Application Support/kicad'
🍺  kicad staged at '/opt/homebrew-cask/Caskroom/kicad/4.0.1' (5457 files, 723M)
```
But when I check what's in the Kicad folder:
```
10:03:25 ~ (master)$ ls /opt/homebrew-cask/Caskroom/kicad/4.0.1/Kicad/
bitmap2component.app	gerbview.app		library			pcb_calculator.app	template
demos			help			modules			pcbnew.app
eeschema.app		kicad.app		packages3d		pl_editor.app
```

**Comment by adityadalal924** [comment]
@jawshooah I think you suggested the final kicad workaround - any thoughts?

**Comment by jawshooah** [comment]
Oversight on my part; `Kernel#system` [doesn't expand globs](http://ruby-doc.org/core-2.0.0/Kernel.html#method-i-system) in arguments after the first. Fixed in #16964

**Comment by jawshooah** [comment]
@adzenith `brew cask uninstall --force kicad; brew update; brew cask install kicad`

**Comment by adzenith** [comment]
Sweet, thanks! Looks great! :space_invader:
