### ISSUE TITLE
Asked whether or not to close terminal window when installing or uninstalling TotalTerminal cask

### ISSUE THREAD

**Issue by jsmitley** [caskroom/homebrew-cask#1682]
The following popup shows up when clean installing TotalTerminal:

![image](https://f.cloud.github.com/assets/1516891/1513145/9cd6dbb8-4adc-11e3-856b-36f693983b89.png)

As long as it doesn't require a password to function, it appears to install/uninstall whether I choose close or cancel.

The following popup shows up when uninstalling TotalTerminal:

![image](https://f.cloud.github.com/assets/1516891/1513168/fb9291ce-4adc-11e3-8b6e-244dabd8cca7.png)

I have to 'cancel' in order for the uninstall to complete.

**Comment by vitorgalvao** [comment]
Has anyone contacted upstream about this? Alternatively, is it still an issue?

**Comment by darwin** [comment]
This is still an issue.

TotalTerminal won't work under El Capitan. So, this problem will get resolved on its own with time :)

**Comment by vitorgalvao** [comment]
I’m confused. [You seem to say it still works](http://discuss.binaryage.com/t/totalfinder-status-under-os-x-10-11-el-capitan/3858).

To be clear, are you saying Apple is introducing security features with El Capitan that will break TotalTerminal, hence it won’t be able to work there?

**Comment by darwin** [comment]
Since last developer update (10.11-15A226f), TotalTerminal does not work anymore.

Ok, I'm going to update that forum post. Thanks for pointing it out.

**Comment by darwin** [comment]
More context here: http://blog.binaryage.com/el-capitan-update

**Comment by vitorgalvao** [comment]
Ah, thank you for the link to the blog post. Will be closing this for now, then.
