### ISSUE TITLE
Document `_stanza`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#17007]
[`_stanza`](https://github.com/caskroom/homebrew-cask/blob/b390b68a970bea99dc13692e668c44b79e02f59c/lib/hbc/cli/internal_stanza.rb) is an incredibly useful command to whoever wants to build a tool that leans on the information from homebrew-cask, and should be documented.

**Comment by adityadalal924** [comment]
Could be useful for the script in https://github.com/caskroom/homebrew-cask/issues/15908

**Comment by vitorgalvao** [comment]
It will be. I already use it extensively for `cask-repair` (also in `find_sparkle_appcast`).

**Comment by Amorymeltzer** [comment]
Discovered this through `cask-repair` and damn, awesome little thing.  Just wrote it into my `cask` completion today.

**Comment by miccal** [comment]
This is now complete - information about `_stanza` has been added to `hacking.md` and the `man` page.
