### ISSUE TITLE
"could not identify primary container" is not very clear

### ISSUE THREAD

**Issue by Blaisorblade** [caskroom/homebrew-cask#17016]
It might already be better "could not figure out how to unpack downloaded archive" or "could not figure out how format of downloaded archive". But I'd like sth. better yet; please read on.

In many cases, when a source changes their distribution format, this will trigger "could not identify primary container" — as in #17015. But as a user, at least I had no idea what that message was about until seeing other issues; "primary container" is not very specific (in terms of what the user knows).

Since this error will keep showing up, a good error message should also suggest appropriate action to users, whatever that is — is that filing an issue, or sth. else?

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/17023
