### ISSUE TITLE
CONTRIBUTING: tell user to search homebrew first, to see if an app exists

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#17025]
When adding a new cask, in the spirit of https://github.com/caskroom/homebrew-cask/issues/15603, users should always run `brew search …` to make sure an app doesn’t already exist in homebrew.

@adidalal Assigning you since you’ve been taking care of CONTRIBUTING, but feel free to remove the assignment if you so wish. I should soon start working on breaking up the docs, so we can free up what is needed for your changes already in place.

**Comment by adityadalal924** [comment]
A better idea is to make search do that for the user, ie, 

```
 [.../homebrew-cask/Casks] > brew cask install docker-machine
Error: No available Cask for docker-machine
Error: nothing to install
```

is terrible and unintuitive

**Comment by adityadalal924** [comment]
In the same vein as https://github.com/caskroom/homebrew-cask/issues/16732

**Comment by vitorgalvao** [comment]
That’s a matter for search, though, and entirely separate issue. Who know when that’ll be implemented.

**Comment by nickhammond** [comment]
Is this still an issue? I feel as though the suggestions here are pretty helpful.

``` shell
➜  homebrew-cask git:(master) brew cask install github
Error: No available Cask for github. Did you mean one of:
github-desktop	 githubpulse

Error: nothing to install

**Comment by vitorgalvao** [comment]
@nickhammond I guess that covers the point mentioned by @adidalal, yes.

The issue still stands as needing to document the need for searching if something is in homebrew, though.
