### ISSUE TITLE
Update manytricks casks

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#17098]
I can’t access https://manytricks.com/ (and haven’t been able to do so in many days), but http://downforeveryoneorjustme.com/ says it’s just me.

All their casks need fixing:

+ `:checkpoint` needs to be updated.
+ `version` needs to be set (instead of `:latest`) where it isn’t.
+ Apps that use a `_do_not_hotlink_` `url` need to be changed to use the `latest` url (but still keeping a `version` and `sha256`).

----------------

- [x] [butler.rb](../blob/master/Casks/butler.rb)
- [x] [displaperture.rb](../blob/master/Casks/displaperture.rb)
- [x] [key-codes.rb](../blob/master/Casks/key-codes.rb)
- [x] [keymo.rb](../blob/master/Casks/keymo.rb)
- [x] [leech.rb](../blob/master/Casks/leech.rb)
- [x] [moom.rb](../blob/master/Casks/moom.rb)
- [x] [name-mangler.rb](../blob/master/Casks/name-mangler.rb)
- [x] [resolutionator.rb](../blob/master/Casks/resolutionator.rb)
- [x] [time-sink.rb](../blob/master/Casks/time-sink.rb)
- [x] [witch.rb](../blob/master/Casks/witch.rb)

**Comment by adidalal** [comment]
The `appcast` also uses the `http://manytricks.com/download/_do_not_hotlink_/` url format.

**Comment by adidalal** [comment]
@vitorgalvao Do you prefer links with the interpolated version, or of the form in https://github.com/caskroom/homebrew-cask/blob/master/Casks/key-codes.rb?

**Comment by vitorgalvao** [comment]
Since they have `appcast`s (just noticed some of them don’t, it should be added), it won’t make much of a difference. A bit torn on using `_do_not_hotlink_` or not. They should all be consistent, though.

Do you have a preference?

**Comment by adidalal** [comment]
Yeah, been adding the appcasts (and a few have old appcasts, will fix accordingly). No particular preference on URLs - I think in other Casks we prefer the appcast URL over the website url when it gives us versioning, though. Don't remember any Casks with a no hotlinking in the URL, though.

**Comment by vitorgalvao** [comment]
> I think in other Casks we prefer the appcast URL over the website url when it gives us versioning, though.

We do, yes.

> Don't remember any Casks with a no hotlinking in the URL, though.

Neither do I.

I say we can go with the always up to date URLs, to conform to the wishes of the developer, but if you disagree, feel free to do it the other way. Whatever’s more convenient.

**Comment by adidalal** [comment]
Will use the unversioned URL, a version and shasum, and the appcast for all of them - a change in checkpoint should notify us of an update, anyway.

**Comment by vitorgalvao** [comment]
Sounds good. Thank you for working on this.

I still can’t access the site. No idea why.

**Comment by adidalal** [comment]
Can't access page for witch, for some reason.
Rest are done.

**Comment by vitorgalvao** [comment]
Thank you!
