### ISSUE TITLE
RuboCop: Trailing comma after last element in multiline array/hash literal

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#17149]
@caskroom/maintainers What do you guys think about the trailing comma after the last element in a multiline array or hash literal? I think it makes updating and reordering elements easier, but it doesn't exactly look pretty, especially for single-element literals like this:

```rb
  url 'http://www.tweaking4all.com/downloads/raspberrypi/ApplePi-Baker.zip',
      :cookies => {
                    'gdbbx_session_activity' => '0',
                  }
```

FYI [here](https://github.com/bbatsov/rubocop/blob/v0.36.0/config/default.yml#L873-L882) is the relevant cop config.

**Comment by adidalal** [comment]
Why would elements need to be reordered? That being said, I like it because it makes parsing easier, in general (thinking of JSON here, but same idea).

I say enable the cop, even though it doesn't look great.

**Comment by jawshooah** [comment]
> Why would elements need to be reordered?

I prefer to keep, for example, `zap :delete` elements in lexicographical order. If new ones are added in an update, existing elements (potentially including the last) will likely need to be reordered to preserve that ordering.

> I say enable the cop, even though it doesn't look great.

It's enabled already, just checking to see if anyone thinks it shouldn't be.

I don't care much either way as long as it's consistent (and it will be regardless, since we're enforcing it with RuboCop).

**Comment by vitorgalvao** [comment]
I’m ambivalent. I also don’t really like it but see its usefulness. Fine by me if it stays.

Unless someone disagrees, I’d say next maintainer who agrees can just close the issue.
