### ISSUE TITLE
RuboCop: Ruby 1.9 vs 1.8 hash syntax (colons vs hashrockets)

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#17161]
Currently we use hashrockets (`:foo => 'bar'`) everywhere in casks. This syntax has been superseded by the more concise colon syntax (`foo: 'bar'`) since Ruby 1.9, which is already so old that it's been EOL'd as of February 2015.

We don't even support 1.8 anymore, so I see no reason to continue to use the old hashrocket syntax. What do you guys think about converting hashrockets to colons where possible?

**Comment by adidalal** [comment]
LGTM - it's a big documentation change so may want to hold off on the change until the initial splitting-up is done.

**Comment by vitorgalvao** [comment]
Sounds good to me as well.
