### ISSUE TITLE
Wordpresscom SHA mismatch v.1.2.1

### ISSUE THREAD

**Issue by chrisopedia** [caskroom/homebrew-cask#17277]
```
#517: $ brew cask install wordpresscom
==> Downloading https://public-api.wordpress.com/rest/v1.1/desktop/osx/download?type=dmg
Already downloaded: /Library/Caches/Homebrew/wordpresscom-1.2.1
==> Verifying checksum for Cask wordpresscom
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 1a10ba45287e6e3a6cc2c128aed4358e7e6efb1a624f80f6b9fd0cc71528489b
Actual: e01ecdbb63b9bf2abb0d6dc7b2ffabe82e085ef02101b8dd8c9c794185f6f99b
File: /Library/Caches/Homebrew/wordpresscom-1.2.1
To retry an incomplete download, remove the file above.
```

**Comment by jawshooah** [comment]
Looks like the offending commit is bfac62583fcfa7541b68529ff52d3fa55a2aa68a. I'm not sure what's going on there; the version is updated from `1.1` to `1.2.1`, but the `url` is left with `1.1`. @vitorgalvao, care to explain?

**Comment by tsparber** [comment]
#17288

**Comment by vitorgalvao** [comment]
@jawshooah [`1.1` (confusingly) isn’t an app version](https://github.com/caskroom/homebrew-cask/issues/16467#issuecomment-169686183).

**Comment by adidalal** [comment]
@chrisopedia Fixed the Cask for (hopefully) the last time - the appcast is now more robust, and we get a versioned URL
