### ISSUE TITLE
brew cask create --interactive

### ISSUE THREAD

**Issue by joshka** [caskroom/homebrew-cask#17322]
I've created a few casks recently. I'm not really that hugely into the cask management game, but I like the ease of managing several macs by simple commands.

I'd like to propose that for these sorts of simple apps something along the lines of the following:
```
brew cask create --interactive
App Name some app
'Some App' looks like 'Some Other App' is this a new app? [Y/n] y
... other checks on whether the app looks coherent ...
Proposed cask name: some-app. Is this good? [Y/n] y
Homepage? http://vendor.com
Download? http://vendor.com/download/v1.2.3.dmg
Version [1.2.3]? 1.2.3
License [...] 
```
Script then downloads file, calculates the shasum, plugs an app or pkg stanza in as required (and if it is only a single file), opens the file in $EDITOR, creates a branch in the local repo, prints commands to push to your fork / repo, etc. E.g. the following output:
```
Check your changes in the editor, then run the following commands:
git branch feature/some-app-1-2-3
git commit -m 'Add Some App 1.2.3'
git push joshka feature/some-app-1-2-3

After that, go to your repo https://github.com/joshka/homebrew-cask/tree/feature/some-app-1-2-3 and create a pull request.
```

Presently, the act of downloading, checksum checking, ensuring that I'm putting app vs. pkg, getting all the ducks in order (shasum etc.) takes a little time. It would be nice if this was almost as easy as installing an existing cask.

**Comment by vitorgalvao** [comment]
Making a new cask isn’t a common task. However, implementing what you mean would be considerable work.

It has also been discussed in the past and closed, as there was absolutely no interest. We can look at a PR, but this is so far down on the list of necessities/priorities, it’s unlikely we’ll ever get to it officially.

**Comment by joshka** [comment]
This was my cognitive bias I guess. I'm a new user and use a bunch of music software that's not in the repo. I guess the need for this goes down as familiarity with writing casks broadens. I might just scribble up a script for my own use and chuck it up somewhere similar to the update cask script.
