### ISSUE TITLE
Proposal: incorporate pull requests into `brew cask search`

### ISSUE THREAD

**Issue by joshka** [caskroom/homebrew-cask#17343]
`brew search` falls back to pull requests. It may be nice to make `brew cask search` do the same.

**Comment by adidalal** [comment]
Seems like more improvements, similar to https://github.com/caskroom/homebrew-cask/issues/16732

Don't think searching prs is a priority because we try to be pretty quick to add Casks

**Comment by vitorgalvao** [comment]
> Don't think searching prs is a priority because we try to be pretty quick to add Casks

Agreed. This was also never an issue. Homebrew has good reason to need that feature, but we don’t really. In that spirit, might as well save it for when we join.

**Comment by joshka** [comment]
Fair points :)
