### ISSUE TITLE
Proposal: check for uninstall stanza in brew cask audit

### ISSUE THREAD

**Issue by joshka** [caskroom/homebrew-cask#17344]
Note the suggestion here by @vitorgalvao https://github.com/caskroom/homebrew-cask/pull/17342#issuecomment-172948903 "All of these are missing uninstall. There are scripts and documentation geared for that."

**Comment by vitorgalvao** [comment]
Already covered in https://github.com/caskroom/homebrew-cask/issues/7683.

Not every cask requires `uninstall`.

**Comment by jawshooah** [comment]
@joshka To clarify, casks which contain a `pkg` or `installer` stanza *must* have an accompanying `uninstall`.

**Comment by joshka** [comment]
Gotcha. Makes sense that you guys have thought of it already.
