### ISSUE TITLE
how to install intellij-idea-ce formula?

### ISSUE THREAD

**Issue by jamesongithub** [caskroom/homebrew-cask#17360]
not sure if this is the place to ask.

was wondering what happened to the intellij idea community edition formula?

```
$ brew cask search intellij
==> Partial matches
intellij-idea
```

This one seems to be the ultimate edition. Used to be both `intellij-idea` and `intellij-idea-ce` I think.

**Comment by vitorgalvao** [comment]
Moved to [caskroom/versions](https://github.com/caskroom/homebrew-versions).
