### ISSUE TITLE
powermate won't actually install

### ISSUE THREAD

**Issue by boneskull** [caskroom/homebrew-cask#17380]
```shell
$ brew cask install --force powermate
==> Downloading https://support.griffintechnology.com/wp-content/uploads/sites/3/2015/08/PowerMate_v1.2.4.zip
Warning: Failed to create the file
Warning: /Library/Caches/Homebrew/powermate-1.2.4,3/2015/08.zip.incomplete: No
Warning: such file or directory

curl: (23) Failed writing body (0 != 15360)
Error: Download failed on Cask 'powermate' with message: Download failed: https://support.griffintechnology.com/wp-content/uploads/sites/3/2015/08/PowerMate_v1.2.4.zip
```

**Comment by jawshooah** [comment]
Ah, @vitorgalvao looks like we made a pretty stupid mistake; we didn't realize that slashes in `version` would translate to subdirectories in the filesystem.

There's no way to escape slashes in filenames, so we'll either have to forbid them in version strings or replace them somehow when creating a cask's cache file and staging directory.

**Comment by vitorgalvao** [comment]
This is somewhat funny. How could we forget that?!

We should outright remove `slashes` `version` methods, I’d say. This is the only cask that uses them, and its unlikely an user tap is using those methods anyway, since it’d also break for them.

**Comment by jawshooah** [comment]
What do you propose we use instead for `powermate`? We could keep the `*_to_slashes` methods around and use `version.after_comma.dots_to_slashes`

**Comment by vitorgalvao** [comment]
> We could keep the `*_to_slashes` methods

I wonder if having one of the `dividers` with fewer methods than the others won’t cause some confusion due to the inconsistency (“it worked with the other one, why not this one?”).

Since this is the only cask that benefits from it, I wouldn’t be opposed to

```ruby
version '1.2.4,3.2015.08'
url "https://support.griffintechnology.com/wp-content/uploads/sites/#{version.after_comma.gsub('.','/')}/PowerMate_v#{version.before_comma}.zip"
```

After all, `version` methods don’t work for every case, nor are they supposed to.

**Comment by jawshooah** [comment]
Sorry, should have been clearer. What I meant to say was, why bother removing *any* of the methods that deal with slashes? All we need to do is add an audit step that checks for slashes in `version`.

**Comment by jawshooah** [comment]
And the `2015/3/08` pattern is fairly common in URLs from what I've seen, so the `slashes` methods could continue to come in handy.

**Comment by vitorgalvao** [comment]
Ah, yes, that sounds fine, then.

**Comment by adidalal** [comment]
Issue fixed for this specific Cask in https://github.com/caskroom/homebrew-cask/issues/17418
