### ISSUE TITLE
Cask request: Yandex Disk

### ISSUE THREAD

**Issue by a-x-** [caskroom/homebrew-cask#17385]
### Cask details

Yandex's Disk is cloud storage like dropbox

**Name** Yandex.Disk

**Homepage**
https://disk.yandex.com
(ru: https://disk.yandex.ru)

**License** 
https://yandex.ru/support/legal/desktop_software_agreement/?ncrnd=2659
(ru: https://yandex.ru/support/legal/desktop_software_agreement/)

**Download URL** 
now working:
https://downloader-default12g.disk.yandex.net/rshare/c54c32e86952d97147f7fd693b619f44fe32b3051ff1fbfc9814fe36a22b8a6c/56a03bfd/O88bhFrg2ZFOJUBBXgQXpe8EjlSjKc62Cb7RKz0RipDoOrqges66S_BifZntv1gFlsg4VIaLrfRKbQetv4dueQ==?uid=0&filename=Yandex.Disk.Mac.dmg&disposition=attachment&hash=&limit=0&content_type=application%2Fx-apple-diskimage&fsize=33057966&hid=280e6fafb605d07c2707733cfa8f9f27&media_type=compressed&tknv=v2&etag=41f310347e494e60bf21d3417dfa4203&rtoken=fd5549498f190361bc7d9173bb16eeec&force_default=no&ycrid=na-d57db95db2f8ed1d72e8210a0fe8d940-downloader12g

**Description** -

**Comment by vitorgalvao** [comment]
We had it, but [had to remove it](https://github.com/caskroom/homebrew-cask/pull/13068).

@victorpopkov Is it fixed? If not, feel free to close the issue.

**Comment by victorpopkov** [comment]
Nope, the official direct download link still doesn't exist. So closing this for now.
