### ISSUE TITLE
Cask request: Firefox Developer Edition

### ISSUE THREAD

**Issue by mrkev** [caskroom/homebrew-cask#17391]
### Cask details

**Name** - Firefox Developer Edition

**Homepage** - https://www.mozilla.org/en-US/firefox/developer/

**License** - Mozilla Public License 2.0 

**Download URL** - https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=osx&lang=en-US

**Description** - "Firefox Developer Edition brings your core dev tools together with some powerful new ones that will extend your ability to work across multiple platforms from one place. It’s everything you’re used to, only better. And only from Firefox." - from their website

**Comment by jawshooah** [comment]
Already in [caskroom/versions](https://github.com/caskroom/homebrew-versions). Also has been requested [many times before](https://github.com/caskroom/homebrew-cask/search?utf8=%E2%9C%93&q=firefox+developer+edition&type=Issues), with the same response each time. Please use GitHub's search feature before creating a new issue.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefoxdeveloperedition.rb

**Comment by mrkev** [comment]
Sweet. Seeng how it's a recurring issue, I'll suggest adding that note (*Please use GitHub's search feature before creating a new issue.*) to the readme right besides the Cask Request link. ¯\\_(ツ)_/¯

**Comment by vitorgalvao** [comment]
> Seeng how it's a recurring issue, I'll suggest adding that note (*Please use GitHub's search feature before creating a new issue.*) to the readme right besides the Cask Request link.

Without meaning to sound rude (I truly don’t) searching before posting is just common curtesy. From the dawn of the web forum (and probably even before) people have been saying “search before posting”. The venn diagram of people who don’t search before posting and people who don’t read instructions before posting is pretty close to a circle.

Case in point, *[we already tell you to always search before posting](https://github.com/caskroom/homebrew-cask#reporting-bugs)*.

**Comment by mrkev** [comment]
Totally with you on that. I want to emphasise that it was a *suggestion*, and that I *suggested* it because it was pointed out I'm not the first one. The internet is full of fools like me, who multitask, get distracted and/or don't bother reading the Reporting Bugs section when not reporting a bug. You're on your full right to get mad at us fools who forget about common courtesy, and clutter your issues, but if the current readme isn't fully working out, is suggesting to make it foolproof really not worth the effort?

As any with suggestion, feel free to take it or ignore it (if you think this **will** be the last time this happens). Once more, \*srug\*.  ¯\\(ツ)/¯

**Comment by vitorgalvao** [comment]
That’s my point (most of your post). By that reasoning, we’d need to have a “search before posting” warning on seventeen different places. I’m exaggerating with that number, but not really, as we have multiple places with instructions that if read and searched, would not make more issues. Without looking at our small README, I can already think of three different cases in only in it.

The solution is not to plaster the same message all over the place. If people don’t read, it doesn’t matter how many times we write. If a solution for this issue had been found, I have no doubt it’d be used in most issue trackers and forums in existence.

To be even clearer, not only am I not trying to sound rude, I’m not even judging you. I understand why people do it, and why they do it so often. My point is that telling people to search before posting is useless. Either you understand you should *always* search before posting and do it, or you don’t and you don’t. That isn’t specific to this case and homebrew cask, it’s applicable to nearly every issue in nearly every project and forum.

**Comment by mrkev** [comment]
And yet StackOverflow not only reminds you, but performs the search for you in case you forgot to search beforehand. (: Look, I feel you, and I see you have very strong feelings about this.  Friendly reminders are never required, you're right and on your full right to manage this however you want.

**Comment by vitorgalvao** [comment]
> And yet StackOverflow not only reminds you, but performs the search for you in case you forgot to search beforehand.

That’s a good idea, and one that we can ask for but is ultimately up to Github to implement, not us. We can’t make that ourselves, because we’re on their closed platform. The comparison doesn’t apply.

> I see you have very strong feelings about this.

That’s where you seem to be (repeatedly) misunderstanding me. I have no idea how many more ways I can tell you so. My repeated caveats are there precisely because I understand why you haven’t searched beforehand *and* because I know it’s hard to talk about this without sounding like I’m complaining, and I’m not. I’m merely pointing out why your initial idea of posting yet another warning to search before posting is not only flawed, but would be deeply ineffective.
