### ISSUE TITLE
Deprecate `license`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#17437]
Refs https://github.com/caskroom/homebrew-cask/issues/16692.

+ [x] Deprecate `license` from core.
+ [x] Remove `license` documentation.
+ [x] Remove `license` from all official taps.

**Comment by jawshooah** [comment]
> Remove license tests.

I don't think this is necessary. As long as it's just deprecated, and not completely removed, there should be tests for it.

**Comment by vitorgalvao** [comment]
Why keep the tests, though? Ideally (or, as I see it), it being deprecated means using casks that use it won’t blow up in your face, but auditing and testing for it will. I.e., if you’re “simply a user”, everything will work as expected, but if you’re developing at all, you should be actively informed and discouraged about something deprecated.

**Comment by jawshooah** [comment]
> if you’re developing at all, you should be actively informed and discouraged about something deprecated

That's fine, and usually how it works in software development when working with languages that support API deprecation as a feature (e.g. Java). But generally, or at least in my experience, the tests remain until the deprecated API is removed in the next major release.

I'm fine with `audit` producing a warning for casks which use deprecated APIs, but the tests should remain until support is completely removed from the core. This ensures that the feature still works, despite being deprecated.

**Comment by vitorgalvao** [comment]
Sounds fair. Remove that point from the top post

**Comment by adidalal** [comment]
Agreed with @jawshooah

**Comment by adamo57** [comment]
what do you mean when you say, "Remove license from all official taps."?

**Comment by reitermarkus** [comment]
Every cask has a [`license` stanza](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/license.md), which is, and never was, used for anything.

"Remove license from all official taps." means removing the `license` stanza from all casks in the official taps (currently only two: `caskroom/cask` and `caskroom/versions`).

**Comment by adamo57** [comment]
So is this supposed to be a PR for both caskroom/cask and caskroom/versions repos? I'm having a little difficulty understanding how this is supposed to work under the same branch.

**Comment by reitermarkus** [comment]
These are basically three separate tasks that will have to be completed in this order:

1. Deprecate `license` in core code, which is now located in [Homebrew/brew](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/cask).
2. Remove `license` from documentation, here in this repo.
3. Remove `license` from all casks, here in this repo and `caskroom/versions`.

**Comment by vitorgalvao** [comment]
There’s also [casroom/eid](https://github.com/caskroom/homebrew-eid) and [caskroom/fonts](https://github.com/caskroom/homebrew-fonts) (the latter being the causer of the `license` stanza).

Removing stanzas is easily done with a simple script, though. Deprecating `license` from the core is what really matters.

**Comment by adidalal** [comment]
`cask style` needs to be updated, also, to not add in an empty blank line

**Comment by vitorgalvao** [comment]
@adidalal Already on it: https://github.com/caskroom/rubocop-cask/commit/05089851bee1366990bfd457f75935e4536c40fb and https://github.com/caskroom/rubocop-cask/commit/c7556c92cf729abd6d60b5fa162b44a3b6f81ed3.

**Comment by vitorgalvao** [comment]
Done! Thank you, @abookyun.
