### ISSUE TITLE
Caskroom/cask/fing

### ISSUE THREAD

**Issue by berot3** [caskroom/homebrew-cask#17458]
new download-link:
https://www.fingbox.com/download?plat=osx

**Comment by vitorgalvao** [comment]
Going to the official webpage from the cask, I still see the exact same download URL. There is a different website with that domain and download URL, yes, but I don’t know it they’re related.

Please provide more information, don’t just dump links with no context.

**Comment by berot3** [comment]
sry, ur right. i tried to "brew install Caskroom/cask/fing", but got this error:
```bash
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'fing' with message: Download failed: http://www.overlooksoft.com/packages/download?plat=osx
```

so i manually downloaded and installed from said link

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/17460.
