### ISSUE TITLE
Cask request: Autodesk Maya 2016

### ISSUE THREAD

**Issue by rsimsek-tgm** [caskroom/homebrew-cask#17469]
Autodesk Maya is a 3D Modelling tool, which is free to use for students, but closed source and commercial.
As I have no idea how to write a cask with an installer .app instead of a .pkg or alike I would love for somebody else to make this happen.
![installer](https://cloud.githubusercontent.com/assets/6803630/12541171/525387c4-c313-11e5-863b-b3017ea50cbc.png)

**Name** - Autodesk Maya 2016

**Homepage** - http://www.autodesk.com/education/free-software/maya 
http://www.autodesk.de/products/maya/free-trial

**License** - commercial

**Download URL** - http://edutrial.autodesk.com/NET16SWDLD/2016/MAYA/ESD/Autodesk_Maya_2016_EN_JP_ZH_MAC_OSX.dmg 

**Description** - 3D Modelling tool

**Comment by adidalal** [comment]
See https://knowledge.autodesk.com/support/maya/troubleshooting/caas/CloudHelp/cloudhelp/2016/ENU/Installation-Maya/files/GUID-10885D2B-D900-4DD6-BB14-B82920C2D294-htm.html for command lne installs.

Unfortunately, this needs a serial AFAIK, and wouldn't be scriptable as they are user-unique.

You can make a Cask and host it privately, but in this case a bash script might be your easiest option.

**Comment by rsimsek-tgm** [comment]
Would it not be possible to have the user input the serial number and the product key instantly after the installation?
Thank you for the command line install link.

**Comment by adidalal** [comment]
Cask defaults to a no further user interaction needed interface, especially because it's very often used in scripts. 

This Cask is definitely doable, but you would want to host it on your own private tap, because we can't auto fill in the serial for you (we do have command line parameter support for installers, and that should be enough to automate things on a personal level)

**Comment by rsimsek-tgm** [comment]
I see, thank you very much. I get that cask usage is often automated, but personally I always read the info before installing straight away, but I surely get where you're coming from and will try to set this up in a private tap.

Thank you
