### ISSUE TITLE
TextWrangler 5+ requires OSX 10.8.5, breaking cask on older OSX version

### ISSUE THREAD

**Issue by psibre** [caskroom/homebrew-cask#17482]
OSX Snow Leopard and Lion can use TextWrangler 4.5, as per the [vendor's download page](http://www.barebones.com/support/textwrangler/updates.html), but the cask doesn't handle this.

**Comment by psibre** [comment]
@vitorgalvao you beat me to it, but I like my solution #17484 better :grin:

**Comment by vitorgalvao** [comment]
Why did you open an issue if you were going to submit a fix?

**Comment by psibre** [comment]
Sorry, I thought that was the recommended workflow... I guess there are different ways of using GitHub.

**Comment by vitorgalvao** [comment]
No, that’s just confusing and wasteful. If you intend to submit a fix, just submit it and we can discuss it in the PR, no need to clutter the issues section.

I’ve seen other people do it before, but never actually saw the point. We have over 17000 issues, so it’s not like it helps us track of what was done, or anything.

**Comment by psibre** [comment]
Fair enough, sorry for the noise. Will do just the PR in the future.
