### ISSUE TITLE
Cask request: GoPanda2

### ISSUE THREAD

**Issue by danielb2** [caskroom/homebrew-cask#17506]
### Cask details

(Please fill out as much as possible)
``` ruby
cask 'gopanda2' do
  version '2.5'
  sha256 'b932a76a513ba9ef4b2fe6179f27644316e4f848e593731f9b91ce43ef6598c2'

  url 'http://pandanet-igs.com/gopanda2/installer/stable/osx-32/gopanda2-osx-32.zip'
  name 'GoPanda2'
  homepage 'http://pandanet-igs.com/communities/gopanda2'
  license :unknown

  app 'GoPanda2.app/'
end
```

**Comment by danielb2** [comment]
It should be noted that the installed version does say 2.4 after the install, but the website says this is the 2.5 version.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/gopanda.rb.

**Comment by danielb2** [comment]
:+1: @vitorgalvao

**Comment by danielb2** [comment]
although I do wonder if gopanda2 isn't the better name for the cask

**Comment by vitorgalvao** [comment]
No, because we follow a strict token reference to avoid duplicates.

**Comment by danielb2** [comment]
Then why is there an `iterm2` app ?

**Comment by vitorgalvao** [comment]
It’s explained right there in the cask. Open the file. `iterm2` has no relation to `iterm`, they’re completely different apps by different authors, one is mot the continuation of the other.

Please search a bit and read the documentation before posting. All of this is easily found out by searching in less time than it takes us to have this conversation. The creation of this issue itself as well as your two questions would have been avoided by searching. And if I recall correctly, it is not the first issue of yours where this happens.

The search is there, the documention is there. Please use them.

**Comment by danielb2** [comment]
This is the first time I post an issue here. A search would have told you that ...

The first app for gopanda was an app written in a different language, and the authors decided to call the followup gopanda2, and make a clear distinction themselves which you can see if you look (it has a separate page for the app too).  I didn't just randomly suggest that a version number be included in the app-name.

**Comment by vitorgalvao** [comment]
> This is the first time I post an issue here. A search would have told you that ...

That was since deleted (because you noticed that wasn’t the case), but I point that out not to shame you, but to point out that your snark isn’t appreciated. I was on my phone when I replied to that (so searching is way harder to do), and due to that I’ve clearly stated “if I recall correctly”, exactly because I couldn’t confirm it. But that didn’t even matter to the point.

I repeatedly *asked* you to *please* use the search function and read the documentation. If you chose to be insulted by my *request* that was done politely, that is your own problem, and I would appreciate you didn’t bring it here.

As for the `gopanda` matter, since you stubbornly seem to just want to be able to “catch me” in some case where I haven’t done a search, I’ll say that I did look (and that is the truth). The app is still made by the same people, and its naming is also covered by our documentation.

You posted a duplicate cask because you didn’t search and opened the unnecessary issue, there’s no blame to turn around here. In fact, there’s no blame to assign at all. We appreciate when users search before posting. You didn’t, three consecutive times in the same issue, so I asked you to do so in the future. That’s it.

**Comment by danielb2** [comment]
"This isn't the first time... "   was not polite and set the tone for the discussion. Your request was initially polite, but bringing up a past incident in which documentation was flawed was unnecessary.

I did do a search before I commented it was my first issue, and I thought the search was showing up this thread, but on a second look, it was a different one. I think it goes to show how petty you are to bring this up, however, even after I removed it.

As for why it can't be gopanda2, I haven't found that in the documentation.  I don't see it in the https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md  section, and i'm not sure where in the documentation the cask name is covered. 

Given that the authors refer to it as gopanda2 everywhere, and not gopanda, I thought it was worth commenting.

**Comment by danielb2** [comment]
This isn't worth it and it's affecting my mood too much. I'll do a better job of searching next time. I must have searched for gopanda2 the first time and not found it.

**Comment by jawshooah** [comment]
> As for why it can't be gopanda2, I haven't found that in the documentation. I don't see it in the https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md section, and i'm not sure where in the documentation the cask name is covered.

[This](https://github.com/caskroom/homebrew-cask/blob/438de2c7f8891e03d51569e9f9fc04e9bfc27984/doc/development/adding_a_cask.md#generating-a-token-for-the-cask) is the relevant section in that document.

**Comment by vitorgalvao** [comment]
> "This isn't the first time... " was not polite and set the tone for the discussion. Your request was initially polite, but bringing up a past incident in which documentation was flawed was unnecessary.

“Unnecessary” perhaps, but not impolite. Even after mentioning that, I still *asked* you to *please* search. If you decided to take that as a confrontational tone (which it was not at all), that is your issue. I do usually apologise when by rereading I see how my tone could have been misinterpreted, but I don’t think my writing was at fault, in this particular situation.

> I think it goes to show how petty you are to bring this up, however, even after I removed it.

Are you being serious?

> That was since deleted (because you noticed that wasn’t the case), but **I point that out not to shame you**, but to point out that your snark isn’t appreciated.

Emphasis added. I’m actually considering you might just want to argue, despite your claims. **You have been specifically told my reasoning, and that it was given in good terms**.

You seem to be under the impression I’m out to get you. I’m not.

> As for why it can't be gopanda2, I haven't found that in the documentation. I don't see it in the https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md section

It’s [here](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#generating-a-token-for-the-cask) (as @jawshooah mentioned), and [here](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#cask-token-details). Also, the full document with all the details is [here](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md), and is linked to from that document.

> Given that the authors refer to it as gopanda2 everywhere, and not gopanda, I thought it was worth commenting.

Not much issue with that. However

> Then why is there an `iterm2` app ?

By actually looking at the cask (no need to search, for that), or *any* other cask in this repo with a number in the name, you’ll see a comment explaining why the number is there. Not a single one is in a similar position.

It’s a shame you’ve decided to distort my tone, but your following snark and repeated comments trying to “catch me” in the rules I’ve mentioned was pretty frankly ridiculous.

This conversation has clearly outlasted it’s usefulness, so I’m locking it. Tones can be hard to gauge in written conversation, granted, and retractions/clarifications are in order when the tone was indeed ambiguous. However, I don’t write to insult, and if you always read my posts in an amicable tone, you’ll be closer to the true intentions.

**Even in this very post, I’m writing calmly and politely.** Bolding that part so it is clear.

In this case, the ambiguity wasn’t there. There’s a difference between being assertive and being rude. I’m often the former, but strive to never be the latter.
