### ISSUE TITLE
Sophos-anti-virus-home-edition no checksum and failed command

### ISSUE THREAD

**Issue by kingtak** [caskroom/homebrew-cask#17501]
Initially, I had sophos installed on my computer but after the Sweep issues located [here](https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/17/t/10029), I deleted it from the applications folder and then tried to reinstall it via homebrew-cask. However, I then recieved this error at the end:

It seems that the checksum needs to be redone and that the command needs to be rebuilt.

    ==> No checksum defined for Cask sophos-anti-virus-home-edition, skipping
    ==> Running installer script Sophos Anti-Virus Home Edition.app/Contents/
    ==> An incompatible product is installed.
    Error: Command failed to execute!

    ==> Failed command:
    ["/usr/bin/sudo", "-E", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/sophos-anti-virus-home-edition/latest/Sophos Anti-Virus Home Edition.app/Contents/MacOS/tools/InstallationDeployer>", "--install"]

    ==> Output of failed command:

    ==> Exit status of failed command:
    #<Process::Status: pid 10926 exit 3>

Could this get addressed?

Thanks!

**Comment by adidalal** [comment]
Cask download link is now behind a registration paywall. If you can find a publicly accessible, static link, please comment back.

Otherwise, we'll have to remove the Cask.

**Comment by kingtak** [comment]
Oh okay, thanks! I'll see if I can find a download link but upon casual inspection it might not be possible... they have a hash link on the account itself, I'll contact Sophos Home Support and see if they can provide one or if it'll only be a registration that will allow you to do it. Thanks!
