### ISSUE TITLE
Feature requst: add retry mechanism

### ISSUE THREAD

**Issue by huanzhang** [caskroom/homebrew-cask#17537]
When installing apps with brew cask, it sometimes fails with download error after having some progress(for example 5%). I have to manually resume the download for many times to finish the installation.(I believe this is very common for people in China.)

I hope we can pass an argument such as -R to the command that the download can auto resume.

**Comment by vitorgalvao** [comment]
That kind of basic feature (downloading) we get from [homebrew](https://github.com/Homebrew/homebrew). Also, since we’re in talks to merge the codebases even further, this is really something you should ask them, as that will benefit more people.
