### ISSUE TITLE
brackets.rb did not remove the older version when updating from 1.5 to 1.6

### ISSUE THREAD

**Issue by rvarbanov** [caskroom/homebrew-cask#17590]
Today I updated my Brackets from 1.5 to 1.6 but noticed that the formula did not remove the old version (1.5)

**Comment by vitorgalvao** [comment]
It’s not supposed to. You’re supposed to uninstall it yourself.

Also, we call them casks, not formulas. They’re very different in every aspect.

**Comment by rvarbanov** [comment]
Even if I installed 1.5 with cask? Do I still need to uninstall it myself outside of cask?

Clearly I am new to casks and just want to learn it better and make sure I am not going to break something by deleting an app outside of cask.

**Comment by adidalal** [comment]
Yep, anything inside an old version subfolder is safe to delete.
Alternatively, `brew cask uninstall brackets --force && brew cask install brackets`

**Comment by vitorgalvao** [comment]
Short answer: we don’t implicitly uninstall, you need to do so explicitly. You don’t need to uninstall outside of cask, though. If you do something like `brew cask uninstall --force brackets`, you’ll uninstall all versions.

This will all be [handled better in the future](https://github.com/caskroom/homebrew-cask/issues/13201).

**Comment by rvarbanov** [comment]
That is good to know.

One last question: 
If I am to run `brew cask uninstall --force brackets` will that also remove my brackets extensions? If it will what would be the best way to remove the older version without removing my brackets extensions?

**Comment by jawshooah** [comment]
> If I am to run brew cask uninstall --force brackets will that also remove my brackets extensions?

No. The `--force` just means that all installed versions of `brackets` will be uninstalled.

**Comment by rvarbanov** [comment]
So, I should do:
`brew cask uninstall --force brackets`
`brew cask install brackets`
and that should keep all my brackets extensions and remove older versions of brackets?

**Comment by jawshooah** [comment]
Yes.

**Comment by rvarbanov** [comment]
It worked! :smile: 

That brings me to my last question :innocent: 
What should I do if I would like to remove all brackets versions with all expansions and leave no trace of it?

**Comment by jawshooah** [comment]
`brew cask zap brackets`

We have plenty of [helpful documentation](https://github.com/caskroom/homebrew-cask/tree/master/doc/cask_language_reference) along with `man brew-cask` so that you don't have to ask these questions in issues (and we don't have to answer them again and again :wink:)
