### ISSUE TITLE
Simlink source is not there…

### ISSUE THREAD

**Issue by napaxton** [caskroom/homebrew-cask#17668]
I'm trying to make a new cask for PanConvert (a gui wrapper for pandoc). (PanConvert is not my software, but I'd like to make it available.)

Here's my panconvert.rb file:

```
cask 'panconvert' do
  version :latest
  sha256 :no_check

  url "http://sourceforge.net/projects/panconvert/files/latest/download?source=files"
  appcast 'https://github.com/apaeffgen/PanConvert/blob/master/docs/changelog.md',
      checkpoint: 'e2333a9cd663739863c8306193960401977aaa88'
      
  name 'PanConvert'
  homepage 'http://panconvert.sourceforge.net'
  license :gpl
  
  app 'PanConvert.app'
end
```

When one does a Drag-and-drop install of the program, it *does* have a version number attached to the app bundle (e.g., 'PanConverter-0.1.5.app'). I'm not sure if that's a possible cause.

```
$ brew cask install panconvert
==> Downloading http://sourceforge.net/projects/panconvert/files/latest/download
######################################################################## 100.0%
==> No checksum defined for Cask panconvert, skipping verification
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/panconvert/latest/PanConvert.app'
```

Any help you all can give would be great.

**Comment by vitorgalvao** [comment]
That `url` won’t work, it’s just downloading the source, not the binary. Try `http://downloads.sourceforge.net/sourceforge/panconvert/PanConvert-0.1.5.dmg` instead.

Also, don’t be afraid to open a PR with what you already have. We prefer that to issues, since it’s easy to work with and test.
