### ISSUE TITLE
Outdated cask: blueharvest

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#17694]
Outdated cask: [`blueharvest`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/blueharvest.rb).

Info:
+ version: `6.3.4`.
+ appcast url: https://cp37.ezyreg.com/~zeroonet/downloads/versioninfo/sparkle/blueharvest6.xml.

Full appcast:
```text

```

This issue was automatically opened with the `find_outdated_appcasts` script.

**Comment by jawshooah** [comment]
Looks like there was a problem fetching this one. In addition, Chrome warns me that the domain is a known Malware risk (though it does the same for sourceforge, so who knows).

**Comment by vitorgalvao** [comment]
> Looks like there was a problem fetching this one.

Thanks for the catch. Looks like it was just a temporary error, though.

**Comment by vitorgalvao** [comment]
> Looks like there was a problem fetching this one.

Thanks for the catch. Looks like it was just a temporary error, though.

> though it does the same for sourceforge

They’re [not wrong there](https://en.wikipedia.org/wiki/SourceForge#Project_hijackings_and_bundled_malware).

**Comment by vitorgalvao** [comment]
Closing in favour of #17700.
