### ISSUE TITLE
'brew cask install navicat-premium' leads to SHA256 mismatch

### ISSUE THREAD

**Issue by allanjamesvestal** [caskroom/homebrew-cask#18130]
Hello,

I got a checksum mismatch when trying to install navicat-premium today:

```
Expected: 3789d07443c90d162ed12a91a7c90bc53c3b87487e95eafead7df6fdef7f6dc9
Actual: c17b3ea6ce58f5ecd3dc20fff8eed54d5fd99d7ead0033332e5b73a76f1c16c1
File: /Library/Caches/Homebrew/navicat-premium-11.2.6.dmg
```

I've run `shasum -a 256 /Library/Caches/Homebrew/navicat-premium-11.2.6.dmg` on the file downloaded within Homebrew-cask, and the output was also `c17b3ea6ce58f5ecd3dc20fff8eed54d5fd99d7ead0033332e5b73a76f1c16c1`.

I've included the newer checksum in a pull request I'll be submitting shortly. Please let me know if there's a different way I should be addressing my issue.

(I did try and follow the guide [here](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md), but the `cask-repair` command didn't like the `--pull` and `--push` flags, nor did replacing them with `-l` and `-p` work using zsh. This ought to approximate what would have been pushed in an automated commit, though.)

**Comment by adidalal** [comment]
version is now `11.2.7`, PRs incoming across the board.
`cask-repair` should work, leaving open for @vitorgalvao

**Comment by adidalal** [comment]
@allanjamesvestal Fixed in https://github.com/caskroom/homebrew-cask/pull/18132

**Comment by vitorgalvao** [comment]
```bash
for cask in $(ls | grep 'navicat' | grep --invert-match 'data-modeler'); do
cask-repair --blind-submit --cask-version '11.2.7' "${i}"
done
```

Sit back and relax. How I enjoy scripting.

Closing since it’s now being fixed. However, you (@allanjamesvestal) said

> the `cask-repair` command didn't like the `--pull` and `--push` flags, nor did replacing them with `-l` and `-p` work using zsh

What exactly does that mean? You need to be more specific about what happened.

**Comment by vitorgalvao** [comment]
Ah, sorry, @adidalal, didn’t realise you would be submitting the fixes. Will close mine.

**Comment by adidalal** [comment]
@vitorgalvao I did a similar thing, though didn't use invert match, that's cool
