### ISSUE TITLE
user experience when installing casks should provide security information and controls

### ISSUE THREAD

**Issue by skivvies** [caskroom/homebrew-cask#1824]
I just installed the virtualbox cask and this was my ux:

```
_pants@qux ~> brew cask install virtualbox
==> Downloading http://download.virtualbox.org/virtualbox/4.3.2/VirtualBox-4.3.2-90405-OSX.dmg
######################################################################## 100.0%
==> Running installer for virtualbox; your password may be necessary.
Password:
==> installer: Package name is Oracle VM VirtualBox
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
==> Success! virtualbox installed to /opt/homebrew-cask/Caskroom/virtualbox/4.3.2-90405
```

1. I'm shown that the installer is being downloaded over http rather than https, making it possible for the connection to be man-in-the-middled
1. After the download is complete, I'm not shown whether the file is checked against a secure checksum (i.e. not md5) obtained over an authenticated connection. Inside knowledge of how cask works is required to find https://github.com/phinze/homebrew-cask/blob/master/Casks/virtualbox.rb, see that it has a sha1 defined, and assume that cask is using it.
1. I'm prompted for my administrator password
1. OS X shows a scary warning that a kernel extension is being installed from an unidentified developer. If the download was indeed not tampered with, this is on Oracle to fix. But I was not shown any evidence the download wasn't tampered with.

It would be a huge ux improvement if cask actually showed if and when it's verifying the integrity and authenticity of files downloaded over http, and if verification is not possible, warned the user and prompted her before continuing. As of [three months ago](https://github.com/phinze/homebrew-cask/issues/204#issuecomment-23310123), 35% of casks had no checksum, which IMO is too high a percentage to let users install without giving them a fighting chance of even being aware that they were not verified.

If and when #164 is implemented, gpg signature verification (instead of or in addition to checksum verification) could be shown during installation for casks that provide signatures (e.g. tor-browser). (Props to @ioerror on opening that issue. Nice docs on verifying signatures published at https://www.torproject.org/docs/verifying-signatures.html.en).

**Comment by vitorgalvao** [comment]
@skivvies Your second point has already been address.

Closing in favour of https://github.com/caskroom/homebrew-cask/issues/10380.
