### ISSUE TITLE
Cask request: Craft

### ISSUE THREAD

**Issue by erichyland** [caskroom/homebrew-cask#18247]
### Cask details

(Please fill out as much as possible)

**Name** - 
Craft

**Homepage** -
http://labs.invisionapp.com/craft

**License** -
Freeware

**Download URL** -
https://s3.amazonaws.com/www-assets.invisionapp.com/labs/CraftInstaller-osx.zip

**Description** -
Craft is a plugin suite for Sketch and Photoshop that lets you design with real data in mind.

**Comment by adidalal** [comment]
The installer, if you can call it that, doesn't work particularly well with HBC. 

@sbdchd has opened up a PR that fulfills this request, but it's pending further feedback.

**Comment by vitorgalvao** [comment]
Closing in favour of #18278.
