### ISSUE TITLE
update sagemath to 7.0

### ISSUE THREAD

**Issue by mcandre** [caskroom/homebrew-cask#18280]
A new major is available:

http://www.sagemath.org/

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/18287

**Comment by jdfm** [comment]
@vitorgalvao The cask created to resolve this issue doesn't work. The url to the file doesn't exist.

**Comment by vitorgalvao** [comment]
@jdfm You’re right, I forgot to readd it (first time the connection went down). Will fix shortly.
