### ISSUE TITLE
brew cask list --versions - listing all versions of installed casks?

### ISSUE THREAD

**Issue by mirfilip** [caskroom/homebrew-cask#18291]
Hi, after updating the cask with `brew cask install <cask> --force` I wanted to check on old versions of particular cask. According to `man brew-cask`, the closest thing I could use was `brew cask list` which lists all the casks installed.

After I couldn't find the particular command, I went to `man brew` for similarities - the approach that used to work, especially in infancy days of brew cask. For brew itself `brew list --versions` shows all the installed packages **with all the versions**. Although undocumented, `brew cask list --versions` seems to work but it only lists the newest version for every installed cask.

Are there any reasons for this not to work the way it does in brew world?

**Comment by adidalal** [comment]
We're not the same code base, and I suspect that code was never added to HBC, so the two commands don't have the same output (nor should they, I think).

**Comment by adidalal** [comment]
Also list itself needs a major rewrite, as it's often broken

**Comment by mirfilip** [comment]
@adidalal Surely, both are not the same. HBC is still not final, that's why I'm here with a question on how to do the particular thing. If not present, consider my question a feature request :)

**Comment by adidalal** [comment]
Merged into https://github.com/caskroom/homebrew-cask/issues/14058
