### ISSUE TITLE
`brew cask install fish` installs different version from `brew install fish`

### ISSUE THREAD

**Issue by bucaran** [caskroom/homebrew-cask#18429]
It seems the first installs fish `2.1.2` and the second the latest version `2.2.0`.

Please see [here](https://github.com/fisherman/fisherman/issues/86) for an example in the wild.

/cc @colstrom

**Comment by adidalal** [comment]
We're not the same project, but eventually we'll remove duplication between Homebrew/HBC. 

For now, fixed in https://github.com/caskroom/homebrew-cask/pull/18430, though.
