### ISSUE TITLE
Wrong URL for cask: Robomongo

### ISSUE THREAD

**Issue by GoranGozo** [caskroom/homebrew-cask#18446]
Seems the current URL in the cask doesn't work anymore. It does for HTTP but not for HTTPS.
After looking at the original website the URL structure seems to have changed.
Reference: https://robomongo.org/download 

Cask: [robomongo](https://github.com/caskroom/homebrew-cask/blob/master/Casks/robomongo.rb)

**Comment by GoranGozo** [comment]
Fixed in #18447

**Comment by adidalal** [comment]
Thank you. FYI it's totally fine to just submit a PR to fix an issue - you don't need to submit both as long as the PR has an explanation for the problem/fix

**Comment by GoranGozo** [comment]
Good to know :) Thanks!
