### ISSUE TITLE
Specify desired app name for symlink: feature request

### ISSUE THREAD

**Issue by IanEdington** [caskroom/homebrew-cask#18448]
Before Cask, I often renamed applications, for ease of use and aesthetic appeal. 
'Google Chrome.app' -> 'Chrome.app' 
'Alfred 2.app' -> 'Alfred.app' 
'1Password 6.app' -> '1Password.app'

A 'nice to have' feature would be to specify the desired name of the application as an argument.

**Comment by adidalal** [comment]
You can always edit the Cask formula to your needs - local taps/files will always be preferred over Caskroom ones if explicitly installed. All of the apps you mentioned have automatic updates as well, so I don't know if you're losing anything by not using caskroom for those, anyway.

**Comment by vitorgalvao** [comment]
See https://github.com/caskroom/homebrew-cask/issues/5101.

This garnered no interest whatsoever. We might entertain a PR, but otherwise, there’s simply no interest.

**Comment by IanEdington** [comment]
Thank you @adidalal.
