### ISSUE TITLE
Bug report: Java appears at not installed if update is available

### ISSUE THREAD

**Issue by gothicpurple** [caskroom/homebrew-cask#18462]
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Description of issue
I installed Java using Cask and that's simply great.
However when an update for Java is available I try, for example, `brew cask search java` and it says it not installed but by typing `brew cask list` java appears.
When running `brew cask install java`, the download procedure starts normally.
This is just a minor bug but I reckon it works with other Casks as well such as Macdown.

Regards

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/issues/14058

To fix in this case `brew cask uninstall java --force && brew cask install java`

Could also use a script like https://github.com/atika/brew-cask-upgrade or https://github.com/buo/brew-cask-upgrade

**Comment by gothicpurple** [comment]
This will  reinstall java. As soon as a new update comes out, the problem I reckon will still be there. I don't mind anyways

**Comment by adidalal** [comment]
@gothicpurple It's because the "listing" function is broken, that's the "main" issue I linked to.

If you have a bunch of old javas installed, you might want to manually uninstall those old packages (with an app like uninstallpkg)
