### ISSUE TITLE
Horos link is down

### ISSUE THREAD

**Issue by merqurio** [caskroom/homebrew-cask#18497]
Hi all, 

I just tried to install [horos](http://www.horosproject.org/) via homebrew but the download url  is not working anymore. I've tried modifying the url but nothing. The link is: [this](http://dev-horos-project.pantheon.io/wp-content/uploads/downloads/Horos1.1.6.dmg)

should I make simply an update of the cask ? the origin now is different and no MD5 checksum is provided by them, even after the registration:

<img width="675" alt="screen shot 2016-02-10 at 16 56 50" src="https://cloud.githubusercontent.com/assets/1485056/12952627/615c9b14-d017-11e5-9430-aeba42a6ef71.png">

Thanks !

**Comment by adidalal** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/18498

**Comment by merqurio** [comment]
Thanks for that quick update, just to clarify for the next time, if the url is not from their site, how can I do a PR and verify it ?  :v:

**Comment by vitorgalvao** [comment]
> if the url is not from their site, how can I do a PR and verify it ?

You need to [add a line](https://github.com/caskroom/homebrew-cask/blob/cb487ad405f74cb1f26b93e3f3e8412c82a22e34/Casks/0ad.rb#L5), whose [rules are changing a bit](https://github.com/caskroom/homebrew-cask/pull/18051).

Maintainers still need to do verify it, though.

**Comment by merqurio** [comment]
Ok, thanks, next time I'll do a PR and wait for a maintainers, thanks guys
you're awesome !

**Comment by vitorgalvao** [comment]
@merqurio To be clear, you can add the comment yourself. I’m just saying a maintainer will still need to go to the website and verify the comment is correct (to protect from malicious additions).
