### ISSUE TITLE
citrix-receiver requires custom referrer for download

### ISSUE THREAD

**Issue by mcnichol** [caskroom/homebrew-cask#18780]
Getting an error 403 when trying to pull down citrix-receiver
```bash
$ brew cask install citrix-receiver
==> Downloading https://downloads.citrix.com/10820/CitrixReceiver12.1.dmg?__gda__=1455232474_2e6dd1faf0ad4d99a5361e3ea75af357

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'citrix-receiver' with message: Download failed: https://downloads.citrix.com/10820/CitrixReceiver12.1.dmg?__gda__=1455232474_2e6dd1faf0ad4d99a5361e3ea75af357
```

**Comment by mcnichol** [comment]
Was looking at Citrix site and found what appears to be different checksums and links to 12.1....although I'm not familiar with how these are linked so I could be adding chaos to the mix.  Just wanted to bring it here if it were helpful.

<b>Download URL</b>
<code>
//downloads.citrix.com/10820/CitrixReceiver12.1.dmg?__gda__=1455255545_f4b86657c76a0ee8322783b45966f15e
</code>
<b>Checksum</b>
<code>MD5 - 8e360ada443551cddb89bf1df20e7c46</code>

**Comment by adidalal** [comment]
Unfortunately that "gda" value expires - not sure if it will consistently work (that seems to be the problem, in this case anyway)

**Comment by adidalal** [comment]
Fixed (temporarily) in https://github.com/caskroom/homebrew-cask/pull/18781

Leaving open if another maintainer has a better idea to fake the referrer

**Comment by vitorgalvao** [comment]
My fault (kind of). [I changed the working `url`](https://github.com/caskroom/homebrew-cask/commit/fb109581755cde9b1d5b8d2529381837b9be1741) while [working on the comment rules](https://github.com/caskroom/homebrew-cask/pull/18051).

I thought this issue might occur, but I did not find that previous URL on the website. Either we can find it again and mark it as official, or we remove the cask.

**Comment by adidalal** [comment]
They're official, and mostly used for standalone deployments in corporate environments.

http://discussions.citrix.com/topic/362401-deploy-receiver-from-receivercitrixcom/

Also used by autopkg recipes, so seems to be a common URL: https://github.com/autopkg/hjuutilainen-recipes/blob/master/CitrixReceiver/CitrixReceiver.download.recipe

**Comment by vitorgalvao** [comment]
Thank you for looking into it.

Fixed.
