### ISSUE TITLE
Implement `--require-sha` flag

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#18831]
Refs https://github.com/caskroom/homebrew-cask/issues/10380.

When using `--require-sha` on the command line (or `HOMEBREW_CASK_OPTS`) during an `install`, before starting the download HBC must check if the cask in question uses `sha256 :no_check`. If it does, installation will abort for that specific cask and an explanatory message be given.

Steps for implementation ([from the next post](https://github.com/caskroom/homebrew-cask/issues/18831#issuecomment-184514730)):

- [x] Add test for `--require-sha` to [`test/cask/cli/options_test.rb`](https://github.com/caskroom/homebrew-cask/blob/master/test/cask/cli/options_test.rb)
- [x] Add option `--require-sha` to [`lib/hbc/cli.rb`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/cli.rb#L147)
- [x] Add new error `Hbc::CaskNoShasumError` to [`lib/hbc/exceptions.rb`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/exceptions.rb)
- [x] Check if `sha256 :no_check` in [`lib/hbc/cli/install.rb`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/cli/install.rb), and abort if `--require-sha` is present
- [x] Update documentation ([USAGE.md](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options), at a minimum)
- [x] Update man page

**Comment by adidalal** [comment]
Steps for implementation:

- [ ] Add test for `--require-sha` to [`test/cask/cli/options_test.rb`](https://github.com/caskroom/homebrew-cask/blob/master/test/cask/cli/options_test.rb)
- [ ] Add option `--require-sha` to [`lib/hbc/cli.rb`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/cli.rb#L147)
- [ ] Check if `sha256 :no_check` in [`lib/hbc/cli/install.rb`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/cli/install.rb), and abort if `--require-sha` is present
- [ ] Update documentation ([USAGE.md](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options), at a minimum)

**Comment by jawshooah** [comment]
The man page will also need to be updated. Other than that, I believe that should be sufficient.

**Comment by magicgoose** [comment]
+1, this is very important thing

**Comment by vitorgalvao** [comment]
Please don’t “+1” this issue (or any other, for that matter), as it only adds noise. We want this implemented, it’s not a vote.

Will remove comments that don’t add to the discussion, to keep the issue focused.

**Comment by fuzzyroddis** [comment]
Could we change it to a slight but important difference:
...before starting the download HBC must check if the cask in question uses *contains a sha256 hash and the value is not :no_check. Else, installation will abort for that specific cask and an explanatory message be given.

**Comment by vitorgalvao** [comment]
@fuzzyroddis What’s the difference?

**Comment by fuzzyroddis** [comment]
It's a nitpick, but in the original if a cask does not contain any `sha256` line rather than `sha256 :no_check` then the installation would continue even though it's equivalent to `:no_check`

**Comment by vitorgalvao** [comment]
There’s no such thing as a cask without a `sha256`. It’s mandatory, and casks don’t pass audit without it.

**Comment by fuzzyroddis** [comment]
I understand that an audit would catch such a cask, but it's still possible for a cask to exist without a `sha256` eg. if it is merged ignoring results of an audit.

**Comment by vitorgalvao** [comment]
Unless I’m misremembering, a cask that does not pass audit will also refuse to install. `audit` isn’t just for Travis, it is also a part of HBC.

**Comment by fuzzyroddis** [comment]
Wouldn't it be safer to require a `sha256` with length 64? Is there a reason you want to only check for `:no_check`?

**Comment by vitorgalvao** [comment]
We only do that for casks that have unversioned `url`s and hence would break constantly.

Please search our issues and documentation for further questions on this. Everything has already been explained at length multiple times.

**Comment by fuzzyroddis** [comment]
Perhaps you misunderstand me, I'm not talking about the use of `:no_check` rather this issue which is about `--require-sha`. I'm saying that if `--require-sha` is used it should check for the existence of a sha256 hash and if there isn't one then fail. Where OP is asking to check for `:no_check` instead and fail if it finds it.

Type | hash | :no_check | no sha256 line
--- | --- | --- | ---
Failing if no hash | ❎ | ✅ | ✅ 
Failing if :no_check | ❎ | ✅ | 🔴 

This isn't an issue of what :no_check does nor how audit works, its about ensuring the behaviour of `--require-sha` never pulls a url without a hash.

Sure it might double up, that audit checks for a hash and then `--require-sha` checks again, but I'd say that's the safer way.

**Comment by vitorgalvao** [comment]
Again, **there are no casks with no `sha256`. `:no_check` exists precisely because of that.**

Try it. Make a cask with no `sha256` and try to install it. HBC will blow up in your face and will not proceed. In the very unlikely and never before heard of even of a cask slipping through with no `sha256`, HBC will refuse to install it anyway. This is not an issue. You’re arguing for a case that will never happen.

**Comment by jawshooah** [comment]
Done in #22398, and refined in #22404.
