### ISSUE TITLE
Error: Cask 'libreoffice' definition is invalid: Bad header line: parse failed

### ISSUE THREAD

**Issue by emmanuelrosa** [caskroom/homebrew-cask#18876]
When I try to install libreoffice I get **Error: Cask 'libreoffice' definition is invalid: Bad header line: parse failed**

## Debugging info

brew install -vd Caskroom/cask/libreoffice
==> brew cask install Caskroom/cask/libreoffice --debug --verbose
brew cask install Caskroom/cask/libreoffice --debug --verbose
==> Creating directories
==> Loading Cask definitions
==> Translating 'Caskroom/cask/libreoffice' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> [user, repo, token] might be [caskroom, cask, libreoffice]
==> [user, repo, token] might be [caskroom, cask, libreoffice]
==> Success! Using source class Hbc::Source::TappedQualified
==> [user, repo, token] might be [caskroom, cask, libreoffice]
==> Resolved Cask URI or file source to '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/libreoffice.rb'
==> [user, repo, token] might be [caskroom, cask, libreoffice]
Error: Cask 'libreoffice' definition is invalid: Bad header line: parse failed
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/source/path_base.rb:65:in `load'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc.rb:85:in `load'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/brew-cask-cmd.rb:18:in `<main>'

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have external commands with conflicting names.

Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb

Warning: Your Xcode (7.0) is outdated
Please update to Xcode 7.2.1.
Xcode can be updated from the App Store.

**Comment by DomT4** [comment]
Try:
```
brew uninstall --force brew-cask && brew update
```

**Comment by adidalal** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by emmanuelrosa** [comment]
Yep, that was it. Thank you.
