### ISSUE TITLE
freesmug chromium 48.0.2564.109

### ISSUE THREAD

**Issue by p-s-** [caskroom/homebrew-cask#18888]
I just wanted to contribute and edit homebrew-cask/Casks/freesmug-chromium.rb as I think there's a new version available.

I'm a newbie here - as you might already tell - but I managed to edit the file anyway; but then I couldn't find the correct sha256 for the new version. On Sourceforge I can only get sha1 and md5 ...

Sorry for the newbie question, but it would be great for me to know, for the next time ...

**Comment by vitorgalvao** [comment]
You don’t look for it, but instead calculate it yourself (`shasum -a 256 {{downloaded_file}}`.

You may also wish to [use `cask-repair`](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#getting-set-up-to-contribute) that will automate most of the process for you.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/18893.

**Comment by p-s-** [comment]
Ah, and CONTRIBUTING.md ...  :flushed:
Thank you for teaching me this!!!
(and for updating Chromium : )

**Comment by vitorgalvao** [comment]
> Thank you for teaching me this!!!

You’re very welcome. Looking forward to future contributions.
