### ISSUE TITLE
cask mactex fails to retrieve pkg file

### ISSUE THREAD

**Issue by th122** [caskroom/homebrew-cask#18905]
Error thrown:

    brew cask install mactex
    ==> Downloading http://tug.org/cgi-bin/mactex-download/MacTeX.pkg
    ######################################################################## 100.0%
    ==> No checksum defined for Cask mactex, skipping verification
    Error: Uh oh, could not figure out how to unpack '/Library/Caches/Homebrew/mactex-latest.pkg'

File found:
    cat /Library/Caches/Homebrew/mactex-latest.pkg
    mactex-download: non-http[s] url ftp://ftp.mpi-sb.mpg.de/pub/tex/mirror/ftp.dante.de/pub/tex/systems/mac/mactex/mactex-20150613.pkg in HEAD line: HEAD ftp://ftp.mpi-sb.mpg.de/pub/tex/mirror/ftp.dante.de/pub/tex/systems/mac/mactex/mactex-20150613.pkg --&gt; 200 OK<br>

**Comment by th122** [comment]
On the next try, adding --verbose, the correct file was downloaded:

    brew cask install --verbose mactex
    ==> Downloading http://tug.org/cgi-bin/mactex-download/MacTeX.pkg
    /usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-645) http://tug.org/cgi-bin/mactex-download/MacTeX.pkg -C 0 -o /Library/Caches/Homebrew/mactex-latest.pkg.incomplete 
...

Unfortunately the filesystem underneath isn't zfs, so there's no rollback to "before".

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/18908 adds back shasum verification, FWIW
