### ISSUE TITLE
Add kdenlive cask

### ISSUE THREAD

**Issue by ydesgagn** [caskroom/homebrew-cask#18929]
Hi,

It would be really nice if someone could add kdenlive and melt cask.

Not sure if this may help but some build scripts are available here:

http://www.mltframework.org/bin/view/MLT/BuildScripts

Thanks

**Comment by vitorgalvao** [comment]
Please open one issue per cask request and [follow the template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat).

The more details you provide, the more likely someone will take up your request.

**Comment by ydesgagn** [comment]
It is a single cask. Mlt is a library used by Kdenlive. This should all be compiled at once and packaged together.

**Comment by vitorgalvao** [comment]
Alright. Even so, please follow the template.
