### ISSUE TITLE
Bug report: add kdenlive cask

### ISSUE THREAD

**Issue by ydesgagn** [caskroom/homebrew-cask#18930]
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Description of issue

It would be really nice if someone could add kdenlive cask.

Not sure if this may help but some build scripts are available here:

http://www.mltframework.org/bin/view/MLT/BuildScripts

### Output of `brew cask <command> --verbose`

```
(paste output here)
```

### Output of `brew doctor`

```
(paste output here)
```

### Output of `brew cask doctor`

```
(paste output here)
```

**Comment by adidalal** [comment]
Can you open one with the [Cask request template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)?

**Comment by adidalal** [comment]
I see:

Kdenlive and MLT can compile and run under Mac OS X. Packages are available from the MacPorts project.

MacPorts is a source-based system - there is not a binary app bundle for Kdenlive. Therefore, Kdenlive and all of its numerous dependencies including multimedia libraries, KDE, and Qt must be compiled. This can take a long time and much disk space! Furthermore, it is not unusual for something not to build correctly; it is definitely not something for the novice, impatient, or "faint of heart."
