### ISSUE TITLE
Bug report: bug in cask cleanup

### ISSUE THREAD

**Issue by gothicpurple** [caskroom/homebrew-cask#18975]
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Description of issue
When running `brew cask cleanup` the following error appears:

> Error: No such file or directory - /Library/Caches/Homebrew/Casks
>   Most likely, this means you have an outdated version of homebrew-cask. Please run:
> 
>       brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
> 

Strange though, my cask is updated. I tried the suggested commands, didn't fix it.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/issues/18606
