### ISSUE TITLE
Enpass SHA-256 Mismatch 

### ISSUE THREAD

**Issue by bao3** [caskroom/homebrew-cask#19048]
> I have pulled a git pull request to correct the error
>

Error: sha256 mismatch
Expected: 7d3e611bbe62dfd0b70e704cebe73158718bedb5f7bce1b0a5fc5901edaded22
Actual: 36eca6011870a74f032430c48b46d5f85c15a00c4f716c9d2d98275dd286d26d
File: /Library/Caches/Homebrew/enpass-5.0.3.dmg

Then I download Enpass-5.0.3.dmg manually , and got sha256 like below

```
$ wget http://dl.sinew.in/mac/setup/Enpass-5.0.3.dmg  ; shasum -a 256 Enpass-5.0.3.dmg

36eca6011870a74f032430c48b46d5f85c15a00c4f716c9d2d98275dd286d26d  Enpass-5.0.3.dmg

``` 

What I did shows below : 
$ brew cask install enpass
==> Satisfying dependencies
complete
==> Downloading http://dl.sinew.in/mac/setup/Enpass-5.0.3.dmg
Already downloaded: /Library/Caches/Homebrew/enpass-5.0.3.dmg
==> Verifying checksum for Cask enpass
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 7d3e611bbe62dfd0b70e704cebe73158718bedb5f7bce1b0a5fc5901edaded22
Actual: 36eca6011870a74f032430c48b46d5f85c15a00c4f716c9d2d98275dd286d26d
File: /Library/Caches/Homebrew/enpass-5.0.3.dmg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
No need to open an issue if you’re going to submit a PR.
