### ISSUE TITLE
Request for BlueJ Cask

### ISSUE THREAD

**Issue by codeapps** [caskroom/homebrew-cask#19050]
```bash
Please add a BlueJ Cask 
```

```bash 
http://www.bluej.org/download/files/bluej-316.msi
```

**Comment by vitorgalvao** [comment]
[It already exists](https://github.com/caskroom/homebrew-cask/blob/master/Casks/bluej.rb).

Please search before requesting, and when making a request, [follow the template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat).
