### ISSUE TITLE
Feature request: Updating a cask using Travis CI deployment

### ISSUE THREAD

**Issue by iosdeveloper** [caskroom/homebrew-cask#19080]
Is it possible to update a cask using Travis CI deployment on tag?
I.e. performing the steps listed in CONTRIBUTING.md under Updating a cask in a non-interactive way.
https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

There is an example how to push to GitHub in the Travis CI documentation. I would prefer to use the `script` provider for conditional deployment.
https://docs.travis-ci.com/user/deployment/custom/#Git

**Comment by iosdeveloper** [comment]
Cross posted in the Travis CI dpl repo: https://github.com/travis-ci/dpl/issues/405

**Comment by vitorgalvao** [comment]
No, because you still need to manually check and specify the new version, that can’t be automated.

**Comment by iosdeveloper** [comment]
What if you use the tag as version? `$TRAVIS_TAG` contains that.

**Comment by vitorgalvao** [comment]
I don’t think you’re getting my point. There’s no way automatically figure out when an app is released and its correct new version, hence this can’t be automated. We have [some scripts](https://github.com/caskroom/homebrew-cask/pull/18237) to make the whole affair easier, but you’ll always need a human to identify new versions for apps.

**Comment by iosdeveloper** [comment]
I'm not talking about automating it from your side but from the contributor side where the app is released on GitHub and every release needs to update the Cask. On your side the PR would still be checked by a human.

**Comment by vitorgalvao** [comment]
What’s the point, then? If you have `cask-repair` (mentioned in the update instructions) and you want to auto-submit the update whenever you release/build, simply add that to your build script (or whatever).

If you’re talking about Travis actually getting the automated appcast release by github when you release, we can’t use those as well. For one, it’s not infrequent that new releases have a slightly different URL that needs to be fixed, but even if they were consistent, that appcast bundles every release (stable and unstable) meaning we can’t trust them.

Either way you look at it, **we** can’t automate the process. Either the developer does it, or no one does.

**Comment by iosdeveloper** [comment]
Understood. Thank you. :)

**Comment by vitorgalvao** [comment]
For further context, initially `appcast` was meant exactly for this. We envisioned a system where we could eventually parse appcasts automatically (based on some rules and common appcast formats, such as sparkle feeds), but that turned out to be too much. Even amongst common formats, there’s too much variance. `appcast` is still useful, but it helps with making manual corrections, it doesn’t replace it.

**Comment by adidalal** [comment]
@iosdeveloper `cask-repair` gets you a good part of the way there.
ie, `cask-repair -v {version} -b bitbar` will automatically update the required version/shasum/appcast/checkpoint values and open up a PR here.

If you have a *push new GitHub release/tag script*, you can just add that to the end.
