### ISSUE TITLE
Unable to add cask with name duplicates the name of cask in caskroom/homebrew-cask in private tap repository

### ISSUE THREAD

**Issue by Genetty** [caskroom/homebrew-cask#19114]
**Observed behaviour**

1. Add `java` cask in a private Tap `/usr/local/Library/Taps/speechkey/homebrew-tap/Casks/java.rb`

2. Search cask `brew cask search java`
    ```
    ==> Exact match
    caskroom/cask/java
    ==> Partial matches
    charles-applejava	 eclipse-java		  java6			   java9-beta
    charles-beta-applejava	 java-beta		  java7			   yourkit-java-profiler
    ```
    => added cask not found, but found the `caskroom/cask/java` one, which probably shadows the private one.

3. Remove `caskroom`  cask to unshadow the private one `rm -rf /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/java.rb`

4. Search one more time `brew cask search java`

    ```
    ==> Exact match
    java
    ==> Partial matches
    eclipse-java		 yourkit-java-profiler

    $ brew cask info java
    java: 1.8.0_66-b17
    Java Standard Edition Development Kit
    http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
    Not installed
    https://github.com/speechkey/homebrew-tap/blob/master/Casks/java.rb
    ```

**Expected**

`brew cask search java` finds casks from all taps.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/7906
