### ISSUE TITLE
Should the Java cask use CPU (Critical Patch Update) or PSU (Patch Set Update)?

### ISSUE THREAD

**Issue by imgx64** [caskroom/homebrew-cask#19140]
Oracle sometimes releases two Java versions simultaneously. One is called CPU, Critical Patch Update (for example: 8u73, 8u71, 8u65) and the other is called PSU, Patch Set Update (for example: 8u74, 8u72, 8u66). The difference is minor and consists of a few non-critical bug fixes that Oracle thinks are not well-tested yet.

Currently the Java cask installs the PSU release, but Oracle recommends the CPU release for all users unless they're affected by the bug fixes (highly unlikely). From [this article](http://www.oracle.com/technetwork/java/javase/downloads/cpu-psu-explained-2331472.html): 
> Oracle strongly recommends that all Java SE users upgrade to the latest CPU release available for a release family. Most users should choose the CPU release.
> Users should only use the corresponding PSU release if they are being impacted by one of the additional bugs fixed in that version as noted in the release notes.

Was there a conscious decision to use PSU releases or was it simply because their version number is higher? I'd be happy with either one, as long as it's an intentional decision and not just random choice.

**Comment by adidalal** [comment]
I don't remember a conscious decision either way - maybe @bdhess or @vitorgalvao has some insight?

I wouldn't mind switching back to CPU releases, but not change it until the next patch lands; going backwards feels a bit odd. I'm assuming the next one would be `8u75`?

**Comment by vitorgalvao** [comment]
Yeah, this is random. I’m not a java user, so if someone submits a higher version, as long as it doesn’t look like a beta, fine by me.

No quarrel whatsoever with using CPU versions exclusively. Is there any quick way to identify them from the version numbers?

**Comment by imgx64** [comment]
I wish Oracle marked them clearly, but I couldn't find any easy way to tell them apart. The only clue I could find is both being mentioned in the [Downloads page](http://www.oracle.com/technetwork/java/javase/downloads/index.html) at the same time (for example: Java SE 8u73 / 8u74). The lower version number is the CPU and the higher version number is the PSU.

**Comment by vitorgalvao** [comment]
Alright, then it is noted. Thank you for reporting this.

@caskroom/maintainers When reviewing `java` updates in the main repo, we should make sure they’re the CPU (stable) release. There are a lot of people that submit updates to that cask, but hopefully after a few refusals (and explanation why), we can get it to a point where we’ll no longer need to keep checking.
