### ISSUE TITLE
DBus gives error and crashes after trying to connect to session

### ISSUE THREAD

**Issue by atemple84** [caskroom/homebrew-cask#19248]
This is on OSX El Capitan 10.11.3.

I can no longer use dbus from brew ever since I updated it (d-bus-1.10.6.el_capitan.bottle.tar.gz).  After commenting out the ServiceIPC items from the plist file, it starts fine without errors. After tracing the /var/log/system.log file, I see this error whenever I run my program (Qt) that tries to establish an interface with the session dbus:

`Feb 26 15:53:45 MacBook-Pro com.apple.xpc.launchd[1] (org.freedesktop.dbus-session[5297]): Could not activate socket group: unix_domain_listener: 37: Operation already in progress
Feb 26 15:53:45 MacBook-Pro com.apple.xpc.launchd[1] (org.freedesktop.dbus-session[5297]): Service exited with abnormal code: 1`

So when I do a launchctl list on the dbus process, it changes from 0 to 1. This was working fine before I updated brew (so before el capitan?).

**Comment by vitorgalvao** [comment]
Hello, @atemple84. You’re in the wrong place. You’re looking for [homebrew](https://github.com/homebrew/homebrew) (we’re homebrew-cask, different thing).

Best of luck fixing the problem.
