### ISSUE TITLE
Cask request: Rocket.Chat

### ISSUE THREAD

**Issue by kxxoling** [caskroom/homebrew-cask#19275]
#### Cask details

**Name** - Rocket.Chat

**Homepage** - https://rocket.chat/

**GitHub** - https://github.com/RocketChat/Rocket.Chat.Electron

**License** - MIT

**Download URL** - 
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/v1.0.0/rocketchat-1.0.0-mac.dmg

**Description** - "The ultimate Free Open Source Solution for team communications. Have your own Slack like online chat, built with Meteor."

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/19277

**Comment by kxxoling** [comment]
@victorpopkov 👍

**Comment by vitorgalvao** [comment]
@kxxoling Wrong person.

**Comment by kxxoling** [comment]
@vitorgalvao = =||| Sorry...

**Comment by vitorgalvao** [comment]
No problem. PR has already been merged, so you can already use the cask.

**Comment by kxxoling** [comment]
Really thanks!
