### ISSUE TITLE
Outdated Cask - daemon-tools-lite

### ISSUE THREAD

**Issue by chrisRidgers** [caskroom/homebrew-cask#19325]
Not really sure what the fix is as I'm not sure how the download source for the cask has been sourced.

The daemon-tools-lite hash check currently fails.  Whether theres a new version that's been released at the same location or theres something else going on I'm not sure.

What's the process for validating the source and hash value?

**Comment by vitorgalvao** [comment]
[CONTRIBUTING.md](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md).

**Comment by adidalal** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/19333
