### ISSUE TITLE
Cask request: Dr Cleaner

### ISSUE THREAD

**Issue by remisharrock** [caskroom/homebrew-cask#19331]
### Cask details

(Please fill out as much as possible)

**Name** -
Dr Cleaner
**Homepage** -
http://appletuner.trendmicro.com/DrCleaner
**License** -
don't know
**Download URL** -
https://itunes.apple.com/app/id921458519?mt=12&at=1000l6jv&ct=appletunercom
**Description** -
The ONLY free App that offers Memory Optimization and Disk Cleaning
Now it can also scan duplicate files in your Mac

**Comment by adidalal** [comment]
We can't add mac app store apps

**Comment by remisharrock** [comment]
oh god, that Apple app store is awful :-(   indeed, it's impossible to find the direct links for Apple CDN , so sad ...
