### ISSUE TITLE
retroarch cask is unfortunately out of date

### ISSUE THREAD

**Issue by fooness** [caskroom/homebrew-cask#19405]
Hello there,

could someone please update the retroarch cask? Sorry for creating this issue, but I didn’t figure out who’s maintaining this cask.

Is there any beginner friendly tutorial for updating casks?

Thanks a lot!

**Comment by vitorgalvao** [comment]
> but I didn’t figure out who’s maintaining this cask.

There are no maintainers for specific casks. Anyone can update one.

> Is there any beginner friendly tutorial for updating casks?

[Yes](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md). Not only instructions, but a whole script geared for it.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/19406
