### ISSUE TITLE
Feature request: Add Firefox Developer Edition

### ISSUE THREAD

**Issue by j-mes** [caskroom/homebrew-cask#19409]
### Description of feature/enhancement

Add Firefox Developer Edition to Casks.

### Justification

I did a quick search via caskroom.io to find if there was Firefox Developer Edition listed, and found it not to be part of the list. If I've read correctly that Firefox, nightly builds of Firefox and "Mutlifirefox" is included then surely the developer edition could be part of that as well.

**Comment by vitorgalvao** [comment]
It’s on [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by j-mes** [comment]
Thanks @vitorgalvao for steering me in the right direction. :+1:
