### ISSUE TITLE
Cask request:

### ISSUE THREAD

**Issue by robsonsnjr** [caskroom/homebrew-cask#19457]
### Cask details

**Name** -
Franz

**Homepage** -
http://meetfranz.com

**License** -

**Download URL** -
https://storage.googleapis.com/meetfranz/v0.9.6/Franz.dmg

**Description** -
Franz is a free messaging app/former Emperor of Austria and combines chat & messaging services into one application. He currently supports Slack, HipChat, Facebook Messenger, Telegram, WhatsApp, Google Hangouts, Skype and Grape. 
Franz allows you to add every service several times. This makes Franz the perfect tool to manage multiple business and private accounts at the same time. You can even use Facebook Messenger with five different accounts at once if some inexplicable reason urges you to do so.

**Comment by vitorgalvao** [comment]
[Already present](https://github.com/caskroom/homebrew-cask/blob/master/Casks/franz.rb).

Also, you’re supposed to fill in the title.

**Comment by robsonsnjr** [comment]
I should have done a "brew cask update" before. Sorry about that.
