### ISSUE TITLE
Fix remaining vendor comments

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#19450]
This is a continuation of https://github.com/caskroom/homebrew-cask/pull/18051. The only missing point (as soon as it is achieved this issue can be closed) is:

+ [ ] Verify and improve all current `… is the official download host per the vendor homepage` comments in [caskroom/cask](https://github.com/caskroom/homebrew-cask).

---

#### How to help (needs to be made by maintainers):

1. Pick any (or many) cask from the list at the bottom of the post.
2. Go to its website, and verify the download URL.
3. Update it’s vendor comment above the `url` stanza appropriately. That may mean removing it entirely (in case the URL is now updated and from the same host as `homepage`), or updating it with the new rules introduced in #18051.
4. When you wish to stop, regenerate the list and update it on this post.

---

#### How to regenerate the list:

List will be copied to clipboard. Should be done only after you merge your fixes.

```bash
brew update
cd "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks"
grep --files-with-matches 'is the official download host per the vendor homepage' * | sed 's/^/+ /' | pbcopy
cd -
```

---

#### List

+ kylo.rb
+ league-of-legends.rb
+ metanota.rb
+ mypaint.rb
+ qbittorrent.rb

**Comment by vitorgalvao** [comment]
Pinging @victorpopkov since you’ve worked a lot on this as well.

Almost done. The ones left are the ones I couldn’t finish at the time for one reason or another (like not finding the download URL, or website being down).

**Comment by victorpopkov** [comment]
This can be closed after merging https://github.com/caskroom/homebrew-cask/issues/22264.

**Comment by vitorgalvao** [comment]
Great news! Thank you.
