### ISSUE TITLE
Update Haskell platform to 7.10.3

### ISSUE THREAD

**Issue by maroselo** [caskroom/homebrew-cask#19467]
Can be the Haskell platform cask updated to v 7.10.3 (current 7.10.2)?
Thanx

**Comment by adidalal** [comment]
It's super easy to do yourself, check out [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md) - we have a `cask-repair` script that automates away the pain :)

Feel free to ask if you need help or have questions!

**Comment by vitorgalvao** [comment]
@maroselo I’m doing it now (though you should take up @adidalal on that suggestion). The cask actually needed a small edit, since `url` changed slightly.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/19469

**Comment by maroselo** [comment]
Thanx, guys!
