### ISSUE TITLE
Transmission.app Possible Malware

### ISSUE THREAD

**Issue by lukeadams** [caskroom/homebrew-cask#19504]
See [here](https://news.ycombinator.com/item?id=11234589).
I'm about to send a PR with the 2.91 url and SHA, but we should have somebody else check it to be safe.

**Comment by lukeadams** [comment]
Yay, seems like somebody else submitted one already. 
Fixed by #19502

**Comment by adidalal** [comment]
People who installed via HBC should not be affected - we verify the shasum.
Updated in https://github.com/caskroom/homebrew-cask/pull/19505

**Comment by Matt3o12** [comment]
@adidalal how can you be sure the hash sum in Transmission[1] was not the affected one? 

[1]: [29a27fa1905c7a52d76f1ce96ae45a736786cd0230e0bd9413508bcf52af7794](https://github.com/caskroom/homebrew-cask/blob/6c56da53fe4d8f859adfc64c54fbab3a9863b192/Casks/transmission.rb)

**Comment by adidalal** [comment]
@Matt3o12 There were only reports of people getting infected from the download button on the website, not via the in-app update (which dl link we used, AFAIK). 2.90 was not *always* compromised, and looking at this history, the checksum was only updated for the 2.84 -> 2.90 bump once.

> Users who have directly downloaded Transmission installer from official website after 11:00am PST, March 4, 2016 and before 7:00pm PST, March 5, 2016, may be been infected by KeRanger.
from https://news.ycombinator.com/item?id=11234589 / official website
