### ISSUE TITLE
Please provide us with a arm-linux-gnueabihf-raspbian formular

### ISSUE THREAD

**Issue by MikeMitterer** [caskroom/homebrew-cask#19523]
I'm not sure if it's the right place to ask but I tried build it by my own (via crosstool-ng)
but finally I got a ld-error and I had to give up. 

I know there is the arm-none-eabi formula but this bear metal version just overcomplicates things - I don't want to develop a kernel - just a simple cpp program.

**Comment by vitorgalvao** [comment]
Closing for several reasons:

+ We don’t do formulas, but casks, so you may be looking for [homebrew](https://github.com/homebrew/homebrew).
+ I can’t find the formula you’re talking about, so I have no idea if you’re in the right place or not.
+ Cask requests must [follow the template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat).
