### ISSUE TITLE
Trying to install an older version of Arduino

### ISSUE THREAD

**Issue by Arctyros** [caskroom/homebrew-cask#19530]
When trying to install https://downloads.arduino.cc/arduino-1.6.0-macosx.zip I got this.

`$ brew cask install --verbose https://downloads.arduino.cc/arduino-1.6.0-macosx.zip
/usr/local/bin/brew tap caskroom/cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3502, done.
remote: Compressing objects: 100% (3446/3446), done.
remote: Total 3502 (delta 55), reused 765 (delta 34), pack-reused 0
Receiving objects: 100% (3502/3502), 5.90 MiB | 3.57 MiB/s, done.
Resolving deltas: 100% (55/55), done.
Checking connectivity... done.
Tapped 1 formula (3,468 files, 13.4M)
==> Downloading https://downloads.arduino.cc/arduino-1.6.0-macosx.zip
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-645) https://downloads.arduino.cc/arduino-1.6.0-macosx.zip -o /Library/Caches/Homebrew/Casks/arduino-1.6.0-macosx.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  134M  100  134M    0     0  3518k      0  0:00:39  0:00:39 --:--:-- 3844k
Error: /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:34: Invalid char `\x03' in expression while loading '/Library/Caches/Homebrew/Casks/arduino-1.6.0-macosx.zip'
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:37:in `rescue in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:34:in `load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:23:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/uri.rb:22:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:82:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:19:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:6:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:21:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'
Error: Kernel.exit
$ brew doctor
Your system is ready to brew.`

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
