### ISSUE TITLE
Cannot unpack Jdownloader

### ISSUE THREAD

**Issue by franatieu** [caskroom/homebrew-cask#19544]
## Issue

Cannot install Jdownloader. After running `brew cask install jdownloader`, that's what I get below.

```
jdownloader requires Java. You can install the latest version with

  brew cask install java

==> Downloading http://installer.jdownloader.org/JD2Setup.dmg
######################################################################## 100.0%
==> No checksum defined for Cask jdownloader, skipping verification
Error: Uh oh, could not figure out how to unpack '/Library/Caches/Homebrew/jdownloader-latest.dmg'
```

Java is already installed according to `java -version` though.

## Here's the output of `brew doctor` if that helps

`Your system is ready to brew.`

## Here's the output of `brew cask doctor` if that helps

```
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 277f; last commit 2016-03-09)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision 35bb6; last commit 3 hours ago)
Error: undefined method `join' for "/usr/local/Cellar":String
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/doctor.rb:186:in `render_install_location'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/doctor.rb:15:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:21:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'
```

Thank you for the help

**Comment by adidalal** [comment]
Create the folder.

"I was able to resolve the issue by creating the the folder Cellar in /usr/local/ since this is a fresh install /usr/local/Cellar did not exist." - from the last time this was an issue

**Comment by franatieu** [comment]
Thank you for the response. Unfortunately, it didn't solve this issue.

Here's the created folder located in `/usr/local/`.
` 0 drwxr-xr-x   2 master  wheel       68  9 Mar 07:21 Cellar`

However the `brew cask doctor` command gives more information:

```
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 277f; last commit 2016-03-09)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision 35bb6; last commit 13 hours ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/Users/master/Casks
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3005
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/master/.rvm/gems/ruby-2.1.4/bin:/Users/master/.rvm/gems/ruby-2.1.4@global/bin:/Users/master/.rvm/rubies/ruby-2.1.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/master/bin:/Users/master/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/master/.rvm/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_CA.UTF-8"
==> Running As Privileged User:
No
```

**Comment by volchub** [comment]
Same here.

It seems that the correct file can not be downloaded. 
The JD2setup.dmg file is just 2kb in size, but should be at least 5.6mb i guess ..

<img width="657" alt="jd2setup-file-too-small" src="https://cloud.githubusercontent.com/assets/3018221/13651364/57e1706e-e647-11e5-9978-db6fdaa6b44b.png">

**Comment by adidalal** [comment]
Looks like the download link changed

**Comment by adidalal** [comment]
Download link based on homepage is still - "http://installer.jdownloader.org/JD2Setup.dmg"
Can you check if that direct link works for you?

**Comment by franatieu** [comment]
Yes it does work. However, all download links from [this page](http://jdownloader.org/download/index) points to mega.nz.

**Comment by adidalal** [comment]
Seems like that's not the case

```html
<td class="col2"> <a id="mac0" href="http://installer.jdownloader.org/JD2Setup.dmg" class="urlextern" target="_blank" title="http://installer.jdownloader.org/JD2Setup.dmg" >Download Installer Mac OS X Version 10.7 or higher</a></td>
```

**Comment by franatieu** [comment]
That's weird

`<td class="col2"> <a id="mac2" href="http://mega.nz/#!aYc2GLLA!0yW5XNlUlIOHWpNRTiv6gUae1GM-RH2feFvOPb-Gqf0" class="urlextern" target="_blank" title="http://mega.nz/#!aYc2GLLA!0yW5XNlUlIOHWpNRTiv6gUae1GM-RH2feFvOPb-Gqf0">Download Installer Mac OS X Version 10.7 or higher</a></td>`

**Comment by adidalal** [comment]
@volchub @franatieu I can't seem to reproduce - is this still an issue?

**Comment by franatieu** [comment]
Yes I still get the same error. I think it could be a java related issue. Like mentioned above, whenever I `brew cask install jdownloader`, I get this message:

```
jdownloader requires Java. You can install the latest version with

brew cask install java
```

Even though I run the command `brew cask install java`, I still get the message every single time.

**Comment by adidalal** [comment]
Hmm, can't currently spin up a clean test environment.
Pinging @vitorgalvao, if you could take a look when you're available.

In the meantime, does a manual install work?

**Comment by franatieu** [comment]
> In the meantime, does a manual install work?

Yes it works

**Comment by vitorgalvao** [comment]
That message appearing every time is normal.

I can reproduce the error.

**Comment by tsparber** [comment]
This is sad news. As far as I see every download redirects to mega. Downloading from mega using command line does not look easy (at least it is not possible using a normal curl request).

https://github.com/tonikelope/megadown looks promising, but my openssl does not include the required features.

@winkelsdorf You also worked on this this cask and stated you where in contact with the devs. What do you think about asking them to provide an extra/alternate download option?

**Comment by vitorgalvao** [comment]
If we can’t fix it, we’ll have to [remove the cask](https://github.com/caskroom/homebrew-cask/pull/19995).

**Comment by winkelsdorf** [comment]
Sad news about their change to use Mega as only available CDN..

@tsparber: I have no other contact as mailing the support. They check the support tickets internally with their dev team. But today I contacted their support asking for another official download link, if any.

I'll let you know as soon as I receive a response. But honestly I wouldn't expect other download links being available, the reason for picking a CDN is obvious.

Right now removing the cask was the right way. We can restore it from history if something changes.

**Comment by winkelsdorf** [comment]
@tsparber Can you please give me feedback if the JDownload cask previously had shown a GUI with progress during it's installation (just for a few seconds)? I received feedback from their team and am currently doing some tests..

**Comment by tsparber** [comment]
@winkelsdorf Sorry, I'm not sure if there's been a GUI. Maybe for a short period (splash screen), but certainly there was no user interaction required. As far as I remember there was also no progress output while the installer is downloading the required files. With a slow internet connection the `brew cask install ` might seem to stuck.

**Comment by winkelsdorf** [comment]
@tsparber Thanks for the quick reply! Yes, that's what I though too, iirc there previously was some kind of a short splash screen, too. The progress is only visible if java is previously not installed (I am testing this on a clean VM). But no user interaction is required. 

Anyway, the cask is now working again :) PR created https://github.com/caskroom/homebrew-cask/pull/20333

Thanks to Appwork and the JDownloader Team :+1:

**Comment by tsparber** [comment]
Thank you for caring :+1:

**Comment by winkelsdorf** [comment]
@tsparber You're welcome :)

@vitorgalvao Cleaned the mess with my repo up, sorry about that. New PR added.

**Comment by adidalal** [comment]
To all following the issue, `jdownloader` is now available (again) - Thanks to everyone for their contributions!
