### ISSUE TITLE
Mimic homebrew submission templates

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#19557]
Actions:

- [x] New issues template:
  - [x] caskroom/cask.
  - [x] caskroom/versions.
  - [x] caskroom/fonts.
  - [x] caskroom/eid.
- [x] New PRs template:
  - [x] caskroom/cask.
  - [x] caskroom/versions.
  - [x] caskroom/fonts.
  - [x] caskroom/eid.
- [ ] Remove our old templates (?)

---

Homebrew has an interesting approach. Here’s what I was met with when submitting a PR:

```
### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

_You can erase any parts of this template not applicable to your Pull Request._

### New Formulae Submissions:

- [ ] Does your submission pass
`brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### Changes to Homebrew's Core:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031) if you'd like one.
- [ ] Have you successfully ran `brew tests` with your changes locally?
```

And for an Issue:

```
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Feature/Formula Requests:

**Please note by far the quickest way to get a new feature or formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.
```

Having boxes you specifically need to tick seems like a great way to ensure people have actually read what’s in them (which doesn’t always happen with us).

Also, take a look at their [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document. A quick steps-based document that links to others depending on what you need to know more about seems like a great solution.

Pinging @caskroom/maintainers. @adidalal might be particularly interested.

**Comment by adidalal** [comment]
Am interested, but will likely be pending for a bit as I am not around to implement currently

**Comment by vitorgalvao** [comment]
Updated with the issue template as well.

**Comment by adidalal** [comment]
Not a huge fan of their CONTRIBUTING - I like our current layout, honestly. The most common thing (updating a Cask) is easily visible, and (luckily) cask-repair automates away most of the pain after that. Adding a cask is alrady a step-by-step doc, and links to core/hacking are also there.

If anything, the issue templates could be merged into as appropriate/revamped, and our FAQ expanded (ie "where's brew cask upgrade" is getting a bit repetitive)

**Comment by vitorgalvao** [comment]
Fair point on the CONTRIBUTING, though for adding a cask I’d like to see clear guidelines to run `brew cask audit` and `brew cask style --fix` before submitting. That should be part of the PR template, though. In that regard, I believe they’ve done the right thing: not only making each step clear, making you tick the boxes of what you’ve done, thus making it less likely to skim.

**Comment by adidalal** [comment]
Still aware of this but it's on the back burner priority-wise. If there's a huge uptick in errant issue requests I'll try to do it ASAP, but I'd like to roll it into a slightly more comprehensive issue template revamp incorporating https://github.com/blog/2111-issue-and-pull-request-templates instead of our current hack-ish workaround.

**Comment by vitorgalvao** [comment]
Sure, take your time.

**Comment by vitorgalvao** [comment]
First draft/suggestion for new PRs:

```
# Instructions:

- Delete every part of this placeholder text irrelevant to your submission, including these instructions.
- `{{cask_file}}` is used a placeholder to the actual cask you’re submitting/editing (if applicable)
- If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do it.

### Changes to a cask
#### Editing an existing cask

- [ ] `brew cask audit {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

#### Adding a new cask

- [ ] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same change.
- [ ] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [ ] When naming my cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask zap {{cask_file}}` worked successfully.

### Changes to the core

- [ ] Followed [hacking.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/hacking.md).
```

**Comment by vitorgalvao** [comment]
This is now complete.
