### ISSUE TITLE
Bug report: Can not uninstall puppet

### ISSUE THREAD

**Issue by nexussafe** [caskroom/homebrew-cask#19661]
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Description of issue

Can not uninstall puppet

### Output of `brew cask <command> --verbose`

    % brew cask uninstall puppet --verbose
    ==> Running uninstall process for puppet; your password may be necessary
    ==> Removing files from pkgutil Bill-of-Materials
    Password:
    ==> chmod: Unable to change file mode on /usr/share/doc: Operation not permitted
    Error: Command failed to execute!

    ==> Failed command:
    ["/usr/bin/sudo", "-E", "--", "/bin/chmod", "--", "777", "#<Pathname:/usr/share/doc>"]

    ==> Output of failed command:

    ==> Exit status of failed command:
    #<Process::Status: pid 25801 exit 1>
    Error: Kernel.exit

### Output of `brew doctor`

    % brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: Some keg-only formula are linked into the Cellar.
    Linking a keg-only formula, such as gettext, into the cellar with
    `brew link <formula>` will cause other formulae to detect them during
    the `./configure` step. This may cause problems when compiling those
    other formulae.
    
    Binaries provided by keg-only formulae may override system binaries
    with other strange results.
    
    You may wish to `brew unlink` these brews:
        gettext

### Output of `brew cask doctor`

    % brew cask doctor
    ==> OS X Release:
    10.11
    ==> OS X Release with Patchlevel:
    10.11.3
    ==> Hardware Architecture:
    intel-64
    ==> Ruby Version:
    2.0.0-p645
    ==> Ruby Path:
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    ==> Homebrew Version:
    Homebrew 0.9.5 (git revision ef4c; last commit 2016-03-10)
    ==> Homebrew Executable Path:
    /usr/local/bin/brew
    ==> Homebrew Cellar Path:
    /usr/local/Cellar
    ==> Homebrew Repository Path:
    /usr/local
    ==> Homebrew Origin:
    https://github.com/Homebrew/homebrew
    ==> Homebrew-cask Version:
    0.60.0 (git revision c33d; last commit 9 minutes ago)
    ==> Homebrew-cask Install Location:
    <NONE>
    ==> Homebrew-cask Staging Location:
    /opt/homebrew-cask/Caskroom
    ==> Homebrew-cask Cached Downloads:
    /Library/Caches/Homebrew
    /Library/Caches/Homebrew/Casks
    0 files, 0B
    ==> Homebrew-cask Default Tap Path:
    /usr/local/Library/Taps/caskroom/homebrew-cask
    ==> Homebrew-cask Alternate Cask Taps:
    /usr/local/Library/Taps/caskroom/homebrew-versions
    ==> Homebrew-cask Default Tap Cask Count:
    3007
    ==> Contents of $LOAD_PATH:
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib
    /usr/local/Library/Homebrew
    /Library/Ruby/Site/2.0.0
    /Library/Ruby/Site/2.0.0/x86_64-darwin15
    /Library/Ruby/Site/2.0.0/universal-darwin15
    /Library/Ruby/Site
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
    ==> Contents of $RUBYLIB Environment Variable:
    <NONE>
    ==> Contents of $RUBYOPT Environment Variable:
    <NONE>
    ==> Contents of $RUBYPATH Environment Variable:
    <NONE>
    ==> Contents of $RBENV_VERSION Environment Variable:
    <NONE>
    ==> Contents of $CHRUBY_VERSION Environment Variable:
    <NONE>
    ==> Contents of $GEM_HOME Environment Variable:
    <NONE>
    ==> Contents of $GEM_PATH Environment Variable:
    <NONE>
    ==> Contents of $BUNDLE_PATH Environment Variable:
    <NONE>
    ==> Contents of $PATH Environment Variable:
    PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/puppetlabs/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
    ==> Contents of $SHELL Environment Variable:
    SHELL="/usr/local/bin/zsh"
    ==> Contents of Locale Environment Variables:
    LC_CTYPE="UTF-8"
    ==> Running As Privileged User:
    No

**Comment by adidalal** [comment]
Looks like the puppet (un)installer is failing.

May also be a `sudo` error because
```
==> Running As Privileged User:
No
```

Try https://ask.puppetlabs.com/question/802/how-do-i-uninstall-puppet-from-a-mac/ (as it doesn't seem to be related to HBC - can't reproduce)

**Comment by josephfrazier** [comment]
I just ran into this as well. My best guess is that OS X 10.11's [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection) is preventing the `chmod` from working.
