### ISSUE TITLE
First time contributor. When testing install returns Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/luxrender/1.5.1/LuxRender.app'

### ISSUE THREAD

**Issue by TimothyStiles** [caskroom/homebrew-cask#19742]
So I carefully followed these [instructions] (https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#cask-token-details) on how to add a cask and compared my new [cask](https://github.com/TimothyStiles/homebrew-cask/blob/master/Casks/luxrender.rb) for [luxrender](http://www.luxrender.net/en_GB/index) to that of [another cask](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/luxmark.rb) for luxmark.

The only difference I can immediately see between these two casks are that luxrender is a .dmg and luxmark is a .zip. 

Luxmark installs through hbc just fine on my computer but when I test my cask with:

<code>brew cask install luxrender</code> 

I get the following:

![screen shot 2016-03-11 at 1 36 43 pm](https://cloud.githubusercontent.com/assets/7042260/13712040/85722746-e78f-11e5-9284-2b73bdf1e91f.png)

Could anyone help me figure out how to write the correct stanza(s) or tell me what I may be doing wrong? I am new to the whole process and would appreciate the help!

**Comment by victorpopkov** [comment]
This usually means that the app locations is different within the dmg image file. And if you open the dmg file manually for this app, you can find that this is located in `LuxRender` directory. Try this instead:
```ruby
  app 'LuxRender/LuxRender.app'
```

**Comment by TimothyStiles** [comment]
@victorpopkov. Your suggestion worked perfectly! Thanks for the help.
