### ISSUE TITLE
dispcalgui now called DisplayCAL

### ISSUE THREAD

**Issue by shonjir** [caskroom/homebrew-cask#19745]
Source for cask [dispcalgui](https://github.com/caskroom/homebrew-cask/master/Casks/dispcalgui.rb) has been renamed to "DisplayCAL" and the distribution site has changed.

Current version is 3.1.2.0.

The current cask homepage redirects to the new homepage here: [http://displaycal.net/](http://displaycal.net/)

Disk image location is here: [download] (http://displaycal.net/download/standalone/DisplayCAL.dmg)

There's a Sourceforge distribution here:  [sourceforge] (https://sourceforge.net/projects/dispcalgui/files/release/)
The "latest" version link is a bit outdated, but this could be used to capture a versioned release.

**Comment by adidalal** [comment]
Mind opening up a PR?
CONTRIBUTING walks you through the basics, and we're here to help if you have questions!

**Comment by shonjir** [comment]
3.1.2 download link for mac redirects to sourceforge which only has 3.1.1.0 at this time
