### ISSUE TITLE
Cask request: Franz

### ISSUE THREAD

**Issue by codeapps** [caskroom/homebrew-cask#19791]
### Cask details

**Name** - Franz

**Homepage** - http://meetfranz.com/

**License** - Free

**Download URL** - https://storage.googleapis.com/meetfranz/v0.9.8/Franz.dmg

**Description** - Franz is a free messaging app/former Emperor of Austria and combines chat & messaging services into one application. He currently supports Slack, HipChat, Facebook Messenger, Telegram, WhatsApp, Google Hangouts, Skype and Grape.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/franz.rb

**Comment by vitorgalvao** [comment]
[Again](https://github.com/caskroom/homebrew-cask/issues/19554)?
