### ISSUE TITLE
Cask request: Visual Paradigm CE 13.0

### ISSUE THREAD

**Issue by codeapps** [caskroom/homebrew-cask#19790]
### Cask details

**Name** - Visual Paradigm

**Homepage** - https://www.visual-paradigm.com/

**License** - FREE for non-commercial use only

**Download URL** - https://www.visual-paradigm.com/download/community.jsp?platform=macosx&arch=jre

**Description** - Visual Paradigm, a software design tool tailored for agile software projects.

**Comment by victorpopkov** [comment]
Added in https://github.com/caskroom/homebrew-cask/issues/19849 and CE in https://github.com/caskroom/homebrew-versions/pull/1832.
