### ISSUE TITLE
suspicious-package: Why a qlplugin stanza pointing to plugin inside app bundle?

### ISSUE THREAD

**Issue by rsaldinger** [caskroom/homebrew-cask#19813]
In #19558, suspicious-package.rb was updated to reference the new app, but the qlplugin stanza was changed to reference the Quick Look plugin within the app bundle:

    qlplugin 'Suspicious Package.app/Contents/Library/QuickLook/Suspicious Package.qlgenerator'

The resulting symlink in ~/Library/QuickLook is redundant (quicklookd will find the plugin embedded in the app bundle, as is standard). More importantly, it causes Suspicious Package.app to generate a confusing alert about cleaning up an old version of the standalone plugin. (Since Suspicious Package was changed from a standalone plugin to an app, it tries to be helpful and offer to clean up the old plugin, since the bundled one is newer and will be used by QL anyway. However, it doesn't expect to find a symlink pointing back at its own bundle, so doesn't handle this situation properly. As a result, it tells the user that the "old" version is the same as the new version, and "cleanup" just trashes the symlink -- not fatal but confusing.)

Yes, Suspicious Package should be smarter about this, but what purpose does this separate symlink even serve? [Sorry if this is a dumb question; I am not a big Cask user myself, but am the developer of Suspicious Package...]

**Comment by vitorgalvao** [comment]
Pinging @russellhancox as to why.

If there’s no reason, we’ll remove that line.

**Comment by russellhancox** [comment]
I didn't realize quicklookd would find the one inside the app bundle automatically, you can remove that line. The cask had been failing to install because the referenced qlplugin didn't exist to create a symlink from.

**Comment by vitorgalvao** [comment]
[Done](https://github.com/caskroom/homebrew-cask/blob/790491e79f82fe89aa849eb20eaaa6efb31d0163/Casks/suspicious-package.rb). Thank you @russellhancox for the fast reply (and original fix) and @rsaldinger for pointing out the mistake.

**Comment by rsaldinger** [comment]
Awesome. Thanks for the speedy fix!
