### ISSUE TITLE
Latest screens Cask request:

### ISSUE THREAD

**Issue by vincent-zhu** [caskroom/homebrew-cask#19839]
### Cask details

(Please fill out as much as possible)

**Screens** -

**https://edovia.com/screens/#mac** -

**Commercial** -

**https://download.edovia.com/screens/Screens%203.6.11b4828.zip** -

**Screens is a beautiful, yet powerful Screen Sharing and VNC client that lets you connect back to your Mac, Windows or Linux PC from the comfort of your living room, the corner coffee shop or anywhere in the world.** -

**Comment by vitorgalvao** [comment]
Doing it now.
