### ISSUE TITLE
Cask request: Brave

### ISSUE THREAD

**Issue by kamida** [caskroom/homebrew-cask#19834]
### Cask details

(Please fill out as much as possible)

**Name** - Brave

**Homepage** - https://www.brave.com

**License** - Mozilla Public License

**Download URL** - https://laptop-updates.brave.com/latest/osx

**Description** - Brave web browser.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/brave.rb

Please search before opening issues.
