### ISSUE TITLE
LINPHONE compile issue

### ISSUE THREAD

**Issue by sivasys** [caskroom/homebrew-cask#19842]
Team, I'm facing issue with linphone compiling. I'm getting the below error while running 'grunt develop' please help us.

Running "oversprite:uiCSS" (oversprite) task
TAP version 13
not ok 1 - TypeError: Cannot read property 'height' of undefined
  ---
  at:
    line: 137
    column: 23
    file: node_modules/gmsmith/lib/gmsmith.js
    function: saveImgSize
  stack: >
    saveImgSize (node_modules/gmsmith/lib/gmsmith.js:137:23)

    fn (node_modules/gmsmith/node_modules/async/lib/async.js:582:34)

    Immediate._onImmediate
    (node_modules/gmsmith/node_modules/async/lib/async.js:498:34)
  test: TAP
  message: "TypeError: Cannot read property 'height' of undefined"
  source: |
    'height': size.height,
  ...
1..1
# failed 1 of 1 tests
# time=3218.64ms
Fatal error: Cannot read property 'height' of undefined

**Comment by vitorgalvao** [comment]
You posted this to the wrong repo.
