### ISSUE TITLE
Please change license for find-any-file.rb

### ISSUE THREAD

**Issue by tempelmann** [caskroom/homebrew-cask#19885]
Hi,
Author of Find Any File here.
The find-any-file.rb specifies that the license is "commercial". It's actually shareware. Do you have such a license type? If so, please update the rb file. Thanks.
Or shall I create a pull request for that?

**Comment by adidalal** [comment]
No shareware license, would be considered commercial.
https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/license.md
