### ISSUE TITLE
cask github-desktop is outdated

### ISSUE THREAD

**Issue by zhuyuesut** [caskroom/homebrew-cask#19928]
now cask github-desktop is v216
new cask github-desktop is v217

**Comment by zhuyuesut** [comment]
November 10th 2015 v216
March 2nd 2016 v217

**Comment by vitorgalvao** [comment]
It has been updated to `217` [12 days ago](https://github.com/caskroom/homebrew-cask/commit/34f634b40aa96a27f38ae13d3a88984f7fd2402c). Your setup is the one outdated. You need to `brew update`,
