### ISSUE TITLE
Am I missing something about the release process?

### ISSUE THREAD

**Issue by pquodling** [caskroom/homebrew-cask#19987]
So, I have a brew cask installed app.  
IN this case - astropad.  I currently have V1.3.6 on my computer
I have a look at https://github.com/caskroom/homebrew-cask/search?utf8=%E2%9C%93&q=astropad
and it says that the current version is 1.4

but if I "brew cask info astropad" - it says 1.3.6
ANd even if I "Brew cask install --force astropad it says 1.3.6

Just to be sure, if I "brew cask uninstall astropad" then "brew cask install astropad" -it's still the old version... 

Am I missing a step?

**Comment by vitorgalvao** [comment]
Yes, you’re missing `brew update` to update the cask definitions.
