### ISSUE TITLE
Cask request: TeamCity

### ISSUE THREAD

**Issue by codeapps** [caskroom/homebrew-cask#19984]
### Cask details

**Name** - TeamCity

**Homepage** - https://www.jetbrains.com/teamcity/

**License** - Free

**Download URL** - https://www.jetbrains.com/teamcity/download/download-thanks.html?platform=mac

**Description** - Powerful Continuous Integration out of the box.

**Comment by samshadwell** [comment]
This appears to be a server application, not a GUI app. It's probably best suited for homebrew, see Homebrew/homebrew#46959

**Comment by vitorgalvao** [comment]
Agreed with @samshadwell. Closing.

On another note, it’s fine to ask for a few casks here and there, but when you ask for so many, we’d really prefer if you tried it, @codeapps. Next time, please try submitting a PR.
