### ISSUE TITLE
Binary executable can't find its data

### ISSUE THREAD

**Issue by cprecioso** [caskroom/homebrew-cask#19999]
Hi, I'm working in a Cask for [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD). You can [see it in my fork](https://github.com/cprecioso/homebrew-cask/blob/steam/Casks/steamcmd.rb); it's almost copied from [`parse`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/parse.rb).
However, when installed, it gives this error:
```sh
$ steamcmd
/usr/local/bin/steamcmd: line 32: /usr/local/bin/osx32/steamcmd: No such file or directory
```
Basically, the entry point is a .sh file that has this in its first line
```sh
STEAMROOT="$(cd "${0%/*}" && echo $PWD)"
```
So, it tries to find its accompanying files in `/usr/local/bin`, instead of realizing it is symlinked.
What should I do in this case? Do I patch it in a `postflight` stanza?

**Comment by vitorgalvao** [comment]
> What should I do in this case? Do I patch it in a `postflight` stanza?

Pretty much, yes, until we [get something better](https://github.com/caskroom/homebrew-cask/issues/18809).

Unrelated question: does that tool allow to redeem steam wallet codes?

**Comment by cprecioso** [comment]
Nope, only downloading the games. It doesn't even let you play them unless you have Steam installed (or if it is a DRM-free game).
