### ISSUE TITLE
Cask request: Todoist

### ISSUE THREAD

**Issue by jERCle** [caskroom/homebrew-cask#20024]
### Cask details

(Please fill out as much as possible)

**Name** - Todoist

**Homepage** - https://itunes.apple.com/au/app/todoist-to-do-list-task-list/id585829637?mt=12&ign-mpt=uo%3D4

**License** - Free

**Download URL** - https://itunes.apple.com/au/app/todoist-to-do-list-task-list/id585829637?mt=12&ign-mpt=uo%3D4

**Description** -

Join the 6 million+ people around the world who are accomplishing amazing things with Todoist – the beautifully simple to-do list built to help you do more and stress less. Whether you need to collaborate with your team, keep track of your most important projects, or just remember to pay the rent, Todoist is there to give you peace of mind.

**Comment by adidalal** [comment]
Mac App Store-only
https://github.com/caskroom/homebrew-cask/pull/15244
