### ISSUE TITLE
Feature request: Offline support

### ISSUE THREAD

**Issue by pacav69** [caskroom/homebrew-cask#20069]
### Description of feature/enhancement

The ability to have offline support so that apps can be installed to another mac that doesn't have internet access or on a new install of the operating system. Perhaps have it run from an external hard drive or a network drive that has all the apps.  

### Justification
Not everyone has a fast internet connection and some apps are large. A single source for all users on a network.

### Example use case
A person gets a new MAC but has no internet connection but a support person could have already downloaded the users required apps, uses an external hard drive to plugin and install the apps for the new user.

An administrator has setup a server that has the required software for users on the network to install, the user logs in and a script is run to launch the offline installer thus allowing the administrator to download once and ensure that all users on the network are at the same version level. If an update occurs then the administrator downloads it once to the server and when the user logs in the next time the script will automagically update the users computer.

**Comment by vitorgalvao** [comment]
Copy over the `/Library/Caches/Homebrew` directory.

**Comment by pacav69** [comment]
yes i'm aware of that but how to setup so that it runs from an external drive so there is no need to copy files to the users computer.

**Comment by vitorgalvao** [comment]
[Change the cache directory](http://stackoverflow.com/a/27893296/1661012).

**Comment by pacav69** [comment]
so the scenario is an administrator has downloaded apps an stored them to an external drive and then plugs this drive in a users computer that is not connected to the internet. A script is run that points to the cache on the hard drive and then installs to the users computer.

**Comment by vitorgalvao** [comment]
Yes.

**Comment by pacav69** [comment]
Ok i will experiment with the HOMEBREW_CACHE setting and see if i can get it to work the way i think it should work as i think it will be useful in my support role.

**Comment by pacav69** [comment]
Can the rb files support external scripts or copy files once the app has been installed?

**Comment by vitorgalvao** [comment]
Look into casks with `postflight`. You can run any arbitrary command you want.

**Comment by pacav69** [comment]
I've created offline install scripts here https://github.com/pacav69/caskroom-offline-install
