### ISSUE TITLE
sha256 mismatch when installing yEd 3.15.0.1

### ISSUE THREAD

**Issue by villim** [caskroom/homebrew-cask#20061]
➜  ~ brew cask install yed
==> Satisfying dependencies
complete
==> Downloading https://www.yworks.com/products/yed/demo/yEd-3.15.0.1_with-JRE8.dmg
Already downloaded: /Library/Caches/Homebrew/yed-3.15.0.1.dmg
==> Verifying checksum for Cask yed
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 7bfdea8092e01be8fe21f5d45cb7c127bf684d7ccf3228a82c39af8e52b98eeb
Actual: 4fa8723c46d2cab39c35f49d1171c816aa82d620bebc4d6a587d4f956735405d
File: /Library/Caches/Homebrew/yed-3.15.0.1.dmg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/20062
