### ISSUE TITLE
Feature request: alternative download or mirror setting

### ISSUE THREAD

**Issue by pacav69** [caskroom/homebrew-cask#20071]
### Description of feature/enhancement
Have an alternative download or mirror sometimes the original file is unavailable either it is unreachable or that it is blocked due to firewalls or sometimes ISP blocked sites such is the case in china where anytime the word 'google' appears it will never be reached. Have an additional setup that will allow the user to set a proxy for all downloads. Have as part of the script a mirror setting like it is used in brew.

Plus in the case of offline support if mirror setting is available then it could be used for it

eg

url "www.myapp.com/myfile.dmg"
mirror: "/myoffline/cache/myfile.dmg"

if the url fails it will look at the mirror.

### Justification
Firewalls or ISPs block certain keywords and mirror setting is not available yet.

### Example use case
Behind the great firewall of china (GFC) the word 'google' is block the only way around it to use a VPN and set the proxy as part of the command line.

A mirror setting could be used for offline location of an alternative download.

**Comment by vitorgalvao** [comment]
[Discussed and refused already](https://github.com/caskroom/homebrew-cask/issues/10241).

There’s no user interest, and the overhead doesn’t justify the work.

**Comment by vitorgalvao** [comment]
Nonetheless, even if I’m closing the issues, rest assured I’ve been reading and do appreciate you’re filling them in detail.
