### ISSUE TITLE
Feature request: add-in comment of the use of editor

### ISSUE THREAD

**Issue by pacav69** [caskroom/homebrew-cask#20074]
### Description of feature/enhancement
add in a comment of adding this to users profile as what is done in brew

Add this to your .bash_profile or .zsh
export HOMEBREW_EDITOR="subl"

### Justification
not everyone can use the default editor

### Example use case
easy to use sublime then the emacs or vi editor

**Comment by vitorgalvao** [comment]
Not sure what you want, there. Homebrew-cask understands and uses `HOMEBREW_EDITOR`.

**Comment by pacav69** [comment]
Feature request HOMEBREW_EDITOR warning

When there is no HOMEBREW_EDITOR set

Using brew edit <token> it will open up vim and upon exit it
will display this message.

Warning: Using vim because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR, VISUAL,
or HOMEBREW_EDITOR to your preferred text editor.

Using brew cask edit <token> it will open up vim and upon exit it
displays NO message.

My suggestion is upon exit of vim, after using brew cask edit <token>, the following message should appear...

Warning: Using vim because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR, VISUAL,
or HOMEBREW_EDITOR to your preferred text editor.

Suggest adding this to your .bash_profile or .zsh
for use with sublime text
export HOMEBREW_EDITOR="subl"

**Comment by vitorgalvao** [comment]
Sounds reasonable. It is extremely low priority, though, so it will go faster if we have a PR.

**Comment by pacav69** [comment]
Once i work out where it is located i will look into it.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/22338

**Comment by vitorgalvao** [comment]
Done.
