### ISSUE TITLE
sourcetree 

### ISSUE THREAD

**Issue by lightzero** [caskroom/homebrew-cask#20101]
Cask sourcetree installs files under "/usr/local".  The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in homebrew-cask.

brew --version
Homebrew 0.9.5 (git revision 11b1; last commit 2016-03-26)

**Comment by vitorgalvao** [comment]
There’s nothing abnormal, there. We’re the ones outputting that message.

**Comment by lightzero** [comment]
maybe GFW。。。
