### ISSUE TITLE
Automatically generate casks?

### ISSUE THREAD

**Issue by mishari** [caskroom/homebrew-cask#20112]
There are several casks I'm using which I feel could be automatically generated. The one I would like to start off with JOSM. I plan on

1. Pulling the cask
2. checking version number in cask file
3. checking version number of application from website
4. downloading the distribution file
5. performing a checksum
6. re-generating the entire rb file with a comment that says to the effect of: "This cask is automatically generated, if you have a problem with this please contact mishari on github"
6. Creating a pull request

But before I do automatic edits like this, I would like to get some sort of ok from the community first.

**Comment by vitorgalvao** [comment]
Whatever method you chose to submit casks is fine, as long as they’re correct.

We’d prefer for you to check them before submitting, but if they are good, they are good. If there are too many constant bad mistakes that actually make the work of maintainers harder, then we may ask you to stop doing it, but if it continues to get better, there’s no reason not to accept them.

Don’t forget to `brew cask audit` and `brew cask style --fix` casks. That’s an absolute must for submissions. If your auto-generated casks don’t successfully pass those (the second one also does automatic fixes, if capable), do not auto-submit them.

We could even include the script (if you so wish) [in our tools](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin).
