### ISSUE TITLE
Messenger

### ISSUE THREAD

**Issue by FMassin** [caskroom/homebrew-cask#20163]
When trying `brew cask install messenger` the app doesn't work (it starts with a gray window but nothing happens).

Any help ?

**Comment by vitorgalvao** [comment]
We only download and move the app, we don’t modify it. You need to contact the developer.

**Comment by FMassin** [comment]
I was hoping that changing the version in the recipe could help. But as usual, asking the question triggered the instantaneous self-resolution of the issue. Sorry for the mess

**Comment by adidalal** [comment]
https://github.com/rsms/fb-mac-messenger/issues/273 looks to be the relevant issue. Anyways, upstream problem :)
