### ISSUE TITLE
Octave fails to install

### ISSUE THREAD

**Issue by ramsrib** [caskroom/homebrew-cask#20205]
Octave installation failed with the following error.

```
$ brew cask install octave
==> Downloading https://downloads.sourceforge.net/sourceforge/octave/GNU_Octave_3.8.2-1.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask octave
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: a7a1e11038665a56df9282531873c1bffaa65872069ac914377b8c910f3b1fd8
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
File: /Library/Caches/Homebrew/octave-3.8.2-1.dmg
To retry an incomplete download, remove the file above.

```
- I tried running "brew update", but that didn't fix the problem.
- I tried to download the package using the above url. But that package isn't available in that url.

**Comment by vitorgalvao** [comment]
Looks like [we should be removing the cask anyway](http://wiki.octave.org/Octave_for_MacOS_X#Installing_a_Mac_OS_X_Bundle).

Try homebrew (`brew install homebrew/science/octave`).

**Comment by ramsrib** [comment]
Thanks.. It worked!...
