### ISSUE TITLE
Error: No available Cask for caskroom/cask/brew-cask

### ISSUE THREAD

**Issue by Huiee** [caskroom/homebrew-cask#20214]
Hello guys,

Recently I've wanted to try Deep Learning on Torch. But I had a trouble when installing brew-cask as follows:

`DHCP-23112:torch Huiee$ brew cask install caskroom/cask/brew-cask`
`Error: No available Cask for caskroom/cask/brew-cask`
`Error: nothing to install`

I've tried almost every way in the issue forum to solve it, but it remains as the same error message.

Could anyone tell me how to solve it. Thanks!

**Comment by adidalal** [comment]
..why are you trying to install brew-cask with Homebrew cask? Just install Homebrew as normal (their website is brew.sh if you have problems), and then just `brew cask install $whatever-cask-you-need`

**Comment by hanxue** [comment]
@Huiee if you are looking at installing `Torch`, there is detailed instruction at https://github.com/torch/torch7/wiki/Cheatsheet#installing-and-running-torch 

Have someone help you to pull the Torch docker image to your machine, instead of trying to install each individual component of Torch. 

Here's an example of installing `Docker` using homebrew:

```
$ brew update 
$ brew install docker
```

**Comment by terryrabinowitz** [comment]
Hello there.  I am having the same result as the original poster which is the direct result of following the installation instructions: http://torch.ch/docs/getting-started.html#

@hanxue I would like to try that docker method but how do you get someone to permit the pull.  When I type: 
docker pull kaixhin/cuda-torch
I get "Cannot connect to the Docker daemon. Is the docker daemon running on this host?? ".  Thank you for the help - I am new to this Mac and just want to get Torch running.

**Comment by jawshooah** [comment]
This is not a problem on our side. Use [their issue tracker](https://github.com/torch/distro/issues) for support.

**Comment by montogeek** [comment]
@adidalal The command does not make any sense but it is in the official instructions https://github.com/Sonarr/Sonarr/wiki/Installation#os-x

**Comment by jawshooah** [comment]
Why are you commenting on this issue? Why are you contacting us at all? We are not affiliated with Sonarr in any way. Their wiki is publicly editable; you are free to correct it, or ask them to do so.
