### ISSUE TITLE
Question: Inconsistent new cask url versioning

### ISSUE THREAD

**Issue by Jerzerak** [caskroom/homebrew-cask#20210]
I was just wondering what I would do if I have a new cask with a version `0.2.0` and a url of `https://github.com/author/software/releases/download/0.2/software_0.2.0.zip` but the previous version of the cask was `0.1.6` with a url of `https://github.com/author/software/releases/download/0.1.6/software_0.1.6.zip`. It seems like the author has been inconsistent with his versioning schema...or am I just completely missing something here?

**Comment by vitorgalvao** [comment]
Nothing we can do about authors being inconsistent, we just need to fix them as they come.

Another common one with github releases is adding/removing a `v` to the url ([example from earlier today](https://github.com/caskroom/homebrew-cask/commit/cd23b61ae16b32b97e562df7b651c7b6b4b21e56)).
