### ISSUE TITLE
Feature request: add latest as a link

### ISSUE THREAD

**Issue by pvtmert** [caskroom/homebrew-cask#20271]
### Description of feature/enhancement
adding link 'latest' or linking stuff inside latest directory to fix conflicts with dashboard or internal update mechanisms
### Justification
    /opt/homebrew-cask/Caskroom
        - atom-beta
            - latest -> 1.7.0-beta4
            - 1.7.0-beta4
        .
        .
        .
### Example use case
so link in ~/Applications should point to /opt/homebrew-cask/Caskroom/atom-beta/latest/Atom.app

when symlink 'latest' changed to other version, we can easily remove it

OR

you can handle things as google-chrome cask does, just latest folder...

**Comment by vitorgalvao** [comment]
It shouldn’t. It works exactly as intended. This behaviour will change in the future. Read https://github.com/caskroom/homebrew-cask/issues/13201.
