### ISSUE TITLE
`list` does not show installed casks

### ISSUE THREAD

**Issue by hanxue** [caskroom/homebrew-cask#20283]
I am using `hombrew-cask` version `0.60.0` and the `brew cask list` command does not work correctly on some installed casks. I installed `vivaldi` using homebrew-cask in the past, and it does not show up

```
$ brew cask --version
0.60.0 (git revision fcbf; last commit 6 days ago)
$ brew cask list vivaldi
Warning: vivaldi is not installed
Error: nothing to list
```

If I just run `brew cask list` without an argument, `vivaldi` is listed
```
$ brew cask list|grep vivaldi
vivaldi
```

The cask is installed and exist in `/opt/homebrew-cask/Caskroom`
```
$ ls /opt/homebrew-cask/Caskroom/vivaldi/
1.0.83.38	1.0.94.2
```

I guess it's obvious uninstall does not work
```
$ brew cask uninstall vivaldi
Error: vivaldi is not installed
```

Is this a bug or am I missing something?

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/14058
