### ISSUE TITLE
cocoapods(1.0.0.beta.5) is beta version

### ISSUE THREAD

**Issue by m8x** [caskroom/homebrew-cask#20290]
#19808
why sudden change to the version?

this repository supposed to be for the stable version, and I don't understand why sudden change to the version when there is a proper place for beta at [caskroom/homebrew-versions](https://github.com/caskroom/homebrew-versions)

**Comment by vitorgalvao** [comment]
You’re right. Must’ve been one of those times when I was updating a bunch of casks at once, and it slipped through. Will revert.

**Comment by m8x** [comment]
Thank you.
