### ISSUE TITLE
Cask request: Firefox Developer Edition

### ISSUE THREAD

**Issue by Rido** [caskroom/homebrew-cask#20357]
### Cask details

**Name** - Firefox Developer Edition

**Homepage** - https://www.mozilla.org/nl/firefox/developer/

**License** - Creative Commons-licentie

**Download URL** - https://download.mozilla.org/?product=firefox-aurora-latest-l10n&os=osx

**Description** - Special Firefox edition for Developers

**Comment by miccal** [comment]
[Already in homebrew-versions.](https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefoxdeveloperedition.rb)
