### ISSUE TITLE
Plug for Mac OSX 10.9.5

### ISSUE THREAD

**Issue by cameronroe** [caskroom/homebrew-cask#20364]
I'm running Mavericks. I used to have Plug for Mac, it's great. I tried to reinstall it recently with brew cask and the cask is only version 2.0.9. Is there any way to get the older version for Mac OSX 10.9.5. I'm not going to be upgrading my OS anytime soon.

**Comment by vitorgalvao** [comment]
You can introduce a conditional. See https://github.com/caskroom/homebrew-cask/blob/4372f55460706a24cdfcbd71062560a2dc4691b6/Casks/calibre.rb#L2L10 for an example.

**Comment by cameronroe** [comment]
Thanks. I'll try to submit a PR.

**Comment by vitorgalvao** [comment]
Closing in favour of the PR.
