### ISSUE TITLE
No available Cask for caskroom/cask/brew-cask.  nothing to install.

### ISSUE THREAD

**Issue by vanbasten23** [caskroom/homebrew-cask#20375]
I know this issue had been asked in https://github.com/caskroom/homebrew-cask/issues/20214. But, the problem was not solved before it was closed.
I was trying to install Torch by following its tutorial: http://torch.ch/docs/getting-started.html#_
Then after execute this line:
`cd ~/torch; bash install-deps;` 
I got error:
`==> brew cask install caskroom/cask/brew-cask
Error: No available Cask for caskroom/cask/brew-cask
Error: nothing to install
`
`brew cask install caskroom/cask/brew-cask` may not make sense but it is the Torch that executes this command. As a result, Torch may or may not function well. Currently I can't find a solution.

**Comment by jawshooah** [comment]
This is not a problem on our side. Use [their issue tracker](https://github.com/torch/distro/issues) for support.
