### ISSUE TITLE
Cask request: VeraCrypt

### ISSUE THREAD

**Issue by rebootd** [caskroom/homebrew-cask#20447]
### Cask details
Tried creating this myself but having trouble getting the download right. Below is the cask I was using.

(Please fill out as much as possible)

**Name** - 
VeraCrypt

**Homepage** -
https://veracrypt.codeplex.com/

**License** -
:apache

**Download URL** -
http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=veracrypt&DownloadId=1537180&FileTime=130999181375130000&Build=21031

**Description** -

cask 'veracrypt' do
  version '21031'
  sha256 :no_check

  url "http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=veracrypt&DownloadId=1537180&FileTime=130999181375130000&Build=#{version}"
  name 'VeraCrypt'
  homepage 'https://veracrypt.codeplex.com/'
  license :apache

  app 'VeraCrypt.app'
  pkg 'VeraCrypt_Installer.pkg'

  zap delete: '/Applications/VeraCrypt.app'
end

**Comment by vitorgalvao** [comment]
[Cask already exists](https://github.com/caskroom/homebrew-cask/blob/master/Casks/veracrypt.rb).

**Comment by rebootd** [comment]
Ha!  I just got it working too. I'll update and use that one. Thanks.
