### ISSUE TITLE
Issues after trying to update

### ISSUE THREAD

**Issue by matt-jay** [caskroom/homebrew-cask#20443]
I tried updating a single application (Dash), but something appears to have gone wrong.

I started with ```brew cask update dash```

I got the follwing messages

```
==> Error: Failed to update tap: caskroom/fonts
==> Error: Failed to update tap: caskroom/versions
==> warning: no common commits
==> From https://github.com/Homebrew/brew
==>  + 53c5089...116075d master     -> origin/master  (forced update)
==> Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
==> Error: Could not link caskroom/cask manpages to:
==>   /usr/local/share/man/man1/brew-cask.1
==>
==> Please delete these files and run `brew tap --repair`.
Updated Homebrew from a6dbfc20 to 53c50891.
HEAD is now at 116075d Remove advice on bad Python linking

[<various merge conflict messages>]

Error: Failed to update tap: caskroom/fonts
Error: Failed to update tap: caskroom/versions
warning: no common commits
From https://github.com/Homebrew/brew
 + 53c5089...116075d master     -> origin/master  (forced update)
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
Error: Could not link caskroom/cask manpages to:
  /usr/local/share/man/man1/brew-cask.1

Please delete these files and run `brew tap --repair`.
```

I ran

```
sudo rm /usr/local/share/man/man1/brew-cask.1
brew tap --repair
```

I ran again and got the follwing:

```
Auto-merging README.md
[<various merge conflict messages>]
Automatic merge failed; fix conflicts and then commit the result.
To restore the stashed changes to /usr/local/Library/Taps/caskroom/homebrew-versions run:
  'cd /usr/local/Library/Taps/caskroom/homebrew-versions && git stash pop'
Already up-to-date.
```

Now, as imple command such as ```brew cask list```results in bad header errors:

```
Error: Cask 'adobe-air' definition is invalid: Bad header line: parse failed
```

What went wrong here?

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

Either way, it looks like you’re using an old version of homebrew-cask, and are having that problem *exactly because you haven’t followed that guide*. Please search before posting.

**Comment by woozyking** [comment]
I had similar issue just now. After following _exactly_ the guide that @vitorgalvao mentioned, I ended up doing this:

```bash
$ cd /usr/local/Library/Taps/caskroom/homebrew-versions
$ git fetch origin master
$ git reset --hard origin/master
$ brew update
```

I think this may have been a left over issue of us initial cask adopters before it got integrated with standard `homebrew` installation. Either way, this resolved the issue for me, along with some weird cask errors that have been haunting me for over a year that the guide couldn't  _exactly_  solve for me.

**Comment by matt-jay** [comment]
Thanks so much for the hint and instructions, @woozyking. This also appears to have solved it for me.

**Comment by jprokos** [comment]
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
