### ISSUE TITLE
Keyfinder (by Ibrahim Sha'ath) cask broken

### ISSUE THREAD

**Issue by Blendrix** [caskroom/homebrew-cask#20440]
Here's the cask that is currently broken:
https://github.com/caskroom/homebrew-cask/blob/master/Casks/keyfinder.rb

Here's the existing code:
```
cask 'keyfinder' do
  version :latest
  sha256 :no_check

  url 'http://www.ibrahimshaath.co.uk/keyfinder/bins/KeyFinder-OSX.zip'
  name 'KeyFinder'
  homepage 'http://www.ibrahimshaath.co.uk/keyfinder/'
  license :gpl

  app 'KeyFinder-OSX/KeyFinder.app'
end
```

The code is currently broken, because the link to download the latest version is currently:
http://www.ibrahimshaath.co.uk/keyfinder/bins/KeyFinder-OSX-2-1.zip

So the code should look like this:
```
cask 'keyfinder' do
  version :latest
  sha256 :no_check

  url 'http://www.ibrahimshaath.co.uk/keyfinder/bins/KeyFinder-OSX-2-1.zip'
  name 'KeyFinder'
  homepage 'http://www.ibrahimshaath.co.uk/keyfinder/'
  license :gpl

  app 'KeyFinder-OSX/KeyFinder.app'
end
```

Or, and this would actually be a much better solution, if [Ibrahim Sha'ath](https://github.com/ibsh) wants to change the link on his website so that the link in the existing code (http://www.ibrahimshaath.co.uk/keyfinder/bins/KeyFinder-OSX.zip) always points to the latest version, that would ensure that the cask doesn't break again the next time he releases an update. 

I'm a little new to this github thing, so if anyone knows how to tag him so he sees this, that would be very helpful.

**Comment by vitorgalvao** [comment]
We prefer versioned downloads, so we’ll solve this another way.

**Comment by vitorgalvao** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/20444.
