### ISSUE TITLE
question: how to do cleanup like homebrew does it?

### ISSUE THREAD

**Issue by danielb2** [caskroom/homebrew-cask#20481]
```
brew cleanup [--prune=<days>] [--dry-run] [-s] [<formulae>]:
    For all installed or specific formulae, **remove any older versions** from the
    cellar. In addition, old downloads from the Homebrew download-cache are deleted.
```
`**` emphasis mine

for brew cask cleanup, it only removes cached version, but I'm ending up with many old versions of software.

What's the way in cask to accomplish what brew cleanup does? i.e. removing old versions (What's the point in keeping those anyway?)

**Comment by vitorgalvao** [comment]
> What's the way in cask to accomplish what brew cleanup does?

You need to `brew cask uninstall --force` (yes, that will remove *all* of them).

> What's the point in keeping those anyway?

Absolutely none. You’re going to like https://github.com/caskroom/homebrew-cask/issues/13201.
