### ISSUE TITLE
Cask request: IntelliJ IDEA Community Edition

### ISSUE THREAD

**Issue by Noffica** [caskroom/homebrew-cask#20509]
### Cask details

(Please fill out as much as possible)

**Name** - IntelliJ IDEA Community

**Homepage** - https://www.jetbrains.com/idea/

**License** - 

**Download URL** - https://www.jetbrains.com/idea/download/download-thanks.html?platform=mac&code=IIC

**Description** - This is the free edition of IntelliJ IDEA for Mac OS X.

> IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by vitorgalvao** [comment]
In [caskroom/versions](https://github.com/caskroom/homebrew-versions).
