### ISSUE TITLE
hbuilder is outdated

### ISSUE THREAD

**Issue by hchuanqi** [caskroom/homebrew-cask#20563]
HBuilder current version is 7.0 officially.
And the download url of older version (in current hbuilder.rb) is invalid then.

`brew cask install hbuilder.rb` gets error:
>curl: (22) The requested URL returned error: 404 Not Found
>Error: Download failed on Cask 'hbuilder' with message: Download failed: http://download.dcloud.net.cn/HBuilder.6.8.2.macosx_64.tar.gz

**Comment by adidalal** [comment]
@hchuanqi You can submit an update yourself!

Check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

For example, this will be `cask-repair -v 7.0.0 hbuilder`

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/20565
