### ISSUE TITLE
Cask request: Surge

### ISSUE THREAD

**Issue by tonyseek** [caskroom/homebrew-cask#20566]
### Cask details

**Name** - Surge

**Homepage** - https://surge.run/manual/

**License** - commercial

**Download URL** - https://surge.run/Surge-Mac.zip

**Description** - Surge is a web developer tool and proxy utility for iOS and OS X.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/20097.

Please search before posting.

**Comment by tonyseek** [comment]
Sorry...
