### ISSUE TITLE
Cask request: ppduck

### ISSUE THREAD

**Issue by Ficapy** [caskroom/homebrew-cask#20568]
### Cask details

**Name** - ppduck

**Homepage** - http://ppduck.com/

**License** - commercial

**Download URL** - http://7xloqu.dl1.z0.glb.clouddn.com/PPDuck.dmg

**Description** -  PP duck - help your image lose some weight

**Comment by vitorgalvao** [comment]
Looks like no one is stepping up to contribute this one. The site’s language and the fact it’s so slow (if you’re not in the region) doesn’t probably doesn’t help.

You can [take a crack at it yourself](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md). We’re here to help with questions.

**Comment by adidalal** [comment]
I would recommend [Crunch](https://github.com/chrissimpkins/Crunch), if others stumble upon this thread and want something similar.

Just found out about it yesterday, and it's been quite effective on the few test images I've thrown at it.

**Comment by Ficapy** [comment]
@adidalal Crunch only support png, ppduck also supports jpeg format
