### ISSUE TITLE
Symbolic links to texdistmgr and texbin

### ISSUE THREAD

**Issue by jm4rc05** [caskroom/homebrew-cask#20592]
I'm not sure if this is a issue of the cask or something else from the package, but I had to fix some broken links:

`cd  ~/Library/TeX/Distributions/Programs`
`rm texdistmgr `
`ln -s /Library/PreferencePanes/TeXDistPrefPane.prefPane/Contents/Executables/texdistmgr .`
`rm texbin`
`ln -s /Library/TeX/texbin .`

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. It isn’t even clear which cask you’re installing. I’m guessing it’s `mactex`, and with that we only run the `pkg`, nothing else, so this looks like it might be an upstream problem.
