### ISSUE TITLE
Commander One: sha256 mismatch

### ISSUE THREAD

**Issue by Blendrix** [caskroom/homebrew-cask#20610]
Issue pertains to [cask for Commander One](https://github.com/caskroom/homebrew-cask/blob/master/Casks/commander-one.rb).

The following output results from attempting to install Commander One via homebrew cask:
`brew cask install commander-one
==> Downloading http://mac.eltima.com/download/commander.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask commander-one
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 76b7b4e877bf2cfef92439741bf63f00d9aa151a9b99101c9e2db985c24d6abc
Actual: b6c1759887ae9081395a9f437a415f52a9adcaa4f62cd273bd4b38c775ebf12d
File: /Library/Caches/Homebrew/commander-one-1.5.dmg
To retry an incomplete download, remove the file above.
`
I have already tried deleting the cached version and re-downloading. The error persists. 
Additionally, I downloaded the .dmg directly from the app developer's website, and ran an md5sum comparison between it and the .dmg downloaded by homebrew cask:
`monolith:~ blendrix$ md5 /Library/Caches/Homebrew/commander.dmg 
MD5 (/Library/Caches/Homebrew/commander.dmg) = 4fb8668292d2d57e8257792b87ecae7c  
monolith:~ blendrix$ md5 /Library/Caches/Homebrew/commander-one-1.5.dmg 
MD5 (/Library/Caches/Homebrew/commander-one-1.5.dmg) = 4fb8668292d2d57e8257792b87ecae7c`
The checksums match.

**Comment by adidalal** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by adidalal** [comment]
Was updated to 1.5.1
Fixed in https://github.com/caskroom/homebrew-cask/pull/20611
