### ISSUE TITLE
`brew cask list` should check arguments individually

### ISSUE THREAD

**Issue by Dillon-Benson** [caskroom/homebrew-cask#2063]
$ brew cask list foo
shows: Error: No available cask for foo
However listing multiple unavailable casks like

    $ brew cask list foo bar
shows: Error: No available cask for foo
It would be better if it showed all unavailable casks given like:
Error: No available cask for foo
Error: No available cask for bar

**Comment by vitorgalvao** [comment]
Closing as I’ll link to it in a single issue pointing out `brew cask list` bugs.
