### ISSUE TITLE
Broken cask install: Toad

### ISSUE THREAD

**Issue by saschabratton** [caskroom/homebrew-cask#20662]
Running command `brew cask install toad` returns:
```bash
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/toad/2.3.6/Toad.app'
```
The app is not installed 😞

**Comment by saschabratton** [comment]
#20663 proposed solution.

**Comment by victorpopkov** [comment]
Thank you for submitting a PR with the fix. Merged https://github.com/caskroom/homebrew-cask/pull/20663.
