### ISSUE TITLE
Bug report: joinme breaks symlink after automatic self-update

### ISSUE THREAD

**Issue by maxromanovsky** [caskroom/homebrew-cask#20678]
### Description of issue
[join.me](http://join.me) application (https://github.com/caskroom/homebrew-cask/blob/master/Casks/joinme.rb) contains self-update functionality (cannot be turned off). After the first launch (even right away after `brew cask install joinme`) it performs self-update and replaces symlink-ed version with installed in-place. Moreover, if app is installed into `~/Applications` instead of `Applications` it installs updated version into `Applications`. 

This behaviour is consistent even if `--appdir=/Applications` is provided which makes this cask pretty useless.

**Comment by vitorgalvao** [comment]
No cask is useless from the point it can download the app automatically. This even installs correctly, so it’s far from useless.

Furthermore, links won’t even be a thing in the future. #13201 pretty much invalidates this.
