### ISSUE TITLE
Any timeline for shift to moving behavior re: issue 13201 ?

### ISSUE THREAD

**Issue by edrozenberg** [caskroom/homebrew-cask#20681]
Would love to start using Cask at our company but waiting on the shift to moving behavior that is planned according to https://github.com/caskroom/homebrew-cask/issues/13201. Is there any approximate timeline for this shift?

**Comment by vitorgalvao** [comment]
No timeline. It’ll be implemented when it’s done.

If you want to help, there’s a PR now (on a phone, so won’t link you) in need of further review and some extra fixes.

**Comment by edrozenberg** [comment]
Happy to help with testing/documentation, thanks. Will test on 2-3 Macs.

**Comment by edrozenberg** [comment]
Bump - happy to help. Cheers, Ed

**Comment by vitorgalvao** [comment]
From your previous comment, I had the impression you were going to merge it into you tap and use it to see how it worked.

**Comment by edrozenberg** [comment]
Sorry kinda newbie to git, will have to figure out where to merge it from.

Thanks,
--Ed
