### ISSUE TITLE
Bug report: veracrypt fails to install

### ISSUE THREAD

**Issue by ndtaylor** [caskroom/homebrew-cask#20726]
### Description of issue

Veracrypt fails to install. Also, I find the url from which the file is being downloaded suspicious. The dmg on the veracrypt website is located at https://veracrypt.codeplex.com/downloads/get/1537180. The list of downloads is available at https://veracrypt.codeplex.com/releases/

### Output of `brew cask install veracrypt --verbose`

```
==> Downloading https://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=veracrypt&DownloadId=1537180&FileTime=130999181375130000&Build=21031
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-648) https://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=veracrypt&DownloadId=1537180&FileTime=130999181375130000&Build=21031 -C 0 -o /Library/Caches/Homebrew/veracrypt-1.17.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8757k  100 8757k    0     0  6280k      0  0:00:01  0:00:01 --:--:-- 6282k
==> Verifying checksum for Cask veracrypt
==> Running installer for veracrypt; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Error -  
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/veracrypt/1.17/VeraCrypt_Installer.pkg>", "-target", "/", "-verboseR"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 3392 exit 1>
Error: Kernel.exit
```

### Output of `brew doctor`

```
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.4
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 1451; last commit 2016-04-23)
Homebrew/homebrew-core (git revision 263e; last commit 2016-04-23)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-cask Version:
0.60.0 (git revision 32f6; last commit 37 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files, 17.1M (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3094
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/ndtaylor/bin:/usr/local/bin:/usr/local/sbin:/Users/ndtaylor/.dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```
(note the two cached files are the ones just downloaded from the failed install command)

**Comment by adidalal** [comment]
The URL is fine, just expired - will update it shortly

**Comment by adidalal** [comment]
Nevermind, url was fine - looks like a permissions problem running the installer. You need to type in your password for pkg installers

**Comment by mgax** [comment]
I've experienced the same failure. It was caused by osxfuse: first it was missing, then it was installed without the macfuse compatibility layer. Once I manually installed osxfuse, the cask install for veracrypt worked. osxfuse as installed by caskroom didn't work because it didn't have the macfuse compatibility layer.

**Comment by adidalal** [comment]
Should osxfuse be a dependency for veracrypt, in that case?

**Comment by kortaggio** [comment]
I ran into the same problem and resolved it via the following steps:

1. Completely remove any existing installations of VeraCrypt or OSXFUSE
2. `brew cask install osxfuse`
3. Reboot
4. `brew cask install veracrypt`

Looks like OSXFUSE must fully complete installation before attempting to install VeraCrypt or else VeraCrypt's package file refuses to install.

**Comment by carldavis** [comment]
Installing osxfuse first did not work for me (same error). I did not have VeraCrypt of OSXFUSE installed previously so I didn't have anything to remove.

**Comment by victorpopkov** [comment]
> Should osxfuse be a dependency for veracrypt, in that case?

Yes. The dependency is required now so the PR is needed.

Also had the same issue but completely reinstalling VeraCrypt and OSXFUSE from the system worked for me even without reboot:
```bash
brew cask zap veracrypt osxfuse
brew cask install osxfuse veracrypt
```

**Comment by vitorgalvao** [comment]
Is this still an issue, or can it be closed?

**Comment by pabranch** [comment]
I'm having the same issue. I cask installed OSXFUSE independently and rebooted. Here's what fails:

```
==> Running installer for veracrypt; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Error -
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/usr/local/Caskroom/veracrypt/1.17/VeraCrypt_Installer.pkg>", "-target", "/", "-verboseR"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 8224 exit 1>
Error: Kernel.exit
```

As you can see, there is no output from the failed `sudo installer` command. Should the `VeraCrypt_Installer.pkg` file exist in the `/usr/local/Caskroom/veracrypt/1.17/` directory? It does not. In fact there IS NO `/usr/local/Caskroom/veracrypt` directory at all.

I tried running the command "by hand" and get the following:

```
sudo -E -- /usr/sbin/installer -verbose -pkg /usr/local/Caskroom/veracrypt/1.17/VeraCrypt_Installer.pkg -target /

installer: Error the package path specified was invalid: '/usr/local/Caskroom/veracrypt/1.17/VeraCrypt_Installer.pkg'.
```

That makes sense given that the `pkg` file doesn't even exist.

Thoughts?

**Comment by vitorgalvao** [comment]
> In fact there IS NO `/usr/local/Caskroom/veracrypt` directory at all.

Because after the install fails, homebrew-cask removes it.

Found the cause of the issue and the solution. Unfortunately, it requires some manual intervention on your part. https://github.com/caskroom/homebrew-cask/pull/22028/files.

**Comment by AndyIbanez** [comment]
I want to bump this because I run into this problem everytime I install macOS from scratch, and I always forget what the solution is.

I'm just posting more clear instructions for those who bump into this problem often.

1. `brew cask install osxfuse` first
2. Open a Terminal window and go to `/usr/local/Caskroom/osxfuse/{VERSION}` (at the time of this writing, the version is `3.5.0`, but go to the current version you have). You can just go to `/usr/local/Caskroom/osxfuse/` and do `ls` there to see what version you have installed.
3. Type `open .`. This will open the `/usr/local/Caskroom/osxfuse/{VERSION}` directory in a new finder window.
4. Double click `FUSE for macOS` to start the OS X Fuse installation.
5. You can now `brew cask install veracrypt` and it should succeed.
