### ISSUE TITLE
Cask request: Dwarf Fortress Lazy Newb Pack

### ISSUE THREAD

**Issue by timvisher** [caskroom/homebrew-cask#20783]
### Cask details

**Name** - Dwarf Fortress Lazy Newb Pack

**Homepage** - http://lazynewbpack.com/ or http://www.bay12forums.com/smf/index.php?topic=128960.0

**License** - n/a?

**Download URL** - Current https://dl.orangedox.com/szqcolfuOZSNoHr1YI/Macnewbie_0.9.18.dmg or http://dffd.wimbli.com/file.php?id=7922

**Description** - This is an easy way to get started playing Dwarf Fortress on Macs. It includes a bunch of plugins/fixes/utilities.

As a caveat, there are many utilities included that all are marked as _unsafe_ for opening. It would be nice if they all got marked as safe without user intervention. Most of them can be found in `LNP/utilities/**/*` although one of them is top level called `dfhack`

**Comment by adidalal** [comment]
FYI to fix the quarantine: `xattr -dr com.apple.quarantine /opt/homebrew-cask/Caskroom/LNP/utilities/*` should do the trick

**Comment by SirWindfield** [comment]
I can make a cask for it. Got some spare time.

**Comment by brewingcode** [comment]
@timvisher give `brew update && brew cask install dwarf-fortress-lnp` a try. I was able to immediately fire up the game without any complaints about unsafe binaries.
