### ISSUE TITLE
Missing field: 'head_sha', 'base_sha'

### ISSUE THREAD

**Issue by chrisfinazzo** [caskroom/homebrew-cask#20818]
It's my first time trying to update a Cask and I've run into this issue a few times when I try to submit...

Do I need to create these fields (If they don't exist) or add keys to my account?
<img width="697" alt="screen shot 2016-04-26 at 12 28 28 pm" src="https://cloud.githubusercontent.com/assets/1534882/14826251/05220580-0bab-11e6-9106-6cddfc279c79.png">

To the best of my knowledge, the remote (e.g, GitHub username) already exists.

**Comment by vitorgalvao** [comment]
Do [this](https://github.com/vitorgalvao/tiny-scripts/issues/18#issuecomment-200582465) and [this](https://github.com/vitorgalvao/tiny-scripts/issues/18#issuecomment-212214402).

**Comment by vitorgalvao** [comment]
Looks like [the issue was resolved](https://github.com/caskroom/homebrew-cask/pull/20821).

**Comment by chrisfinazzo** [comment]
Yeah, this was my mistake. Cask's setup process is a bit different than other things I've worked on, but after reinstalling the helper scripts and configuring, it seems good to go.
