### ISSUE TITLE
Feature request: Add user definition to HOMEBREW_CASK_OPTS

### ISSUE THREAD

**Issue by lashomb** [caskroom/homebrew-cask#20838]
I recently tried to automate some developer setups and wanted to use cask, but couldn't get around it needing to be run as the end user. I can easily discover and provide that user, but my scripts run as root. It would be immensely useful if a user could be defined in the HOMEBREW_CASK_OPTS variable and then set permissions that way so that it can be provisioned without user interaction.

**Comment by vitorgalvao** [comment]
Running a command as another user is precisely what [`su`](https://en.wikipedia.org/wiki/Su_(Unix)) is for. `man su` will give you the details.

**Comment by lashomb** [comment]
We have been using Python and the subprocess module, trying to use preexec_fn in a similar way to the su command, and it seemed like a lot of hoops to jump through as you can't switch back to root once you've given it up. Would be easier if it was just a variable. But regardless, we ended up not using cask because of this.

**Comment by vitorgalvao** [comment]
> Would be easier if it was just a variable.

Agreed. On the other hand, we’re dangerously short on core contributors, and this is a feature that is simply not worth spending time on. If you want to take a look at how to implement it and do the legwork, then we can discuss it further. Otherwise, it won’t be done.
