### ISSUE TITLE
Builtin signature check?

### ISSUE THREAD

**Issue by netheril96** [caskroom/homebrew-cask#20923]
Currently cask seems to do its own hash check, and it is not available for all packages. However, most applications for OS X already come with digital signatures, signed by a developer certificate that is in turn signed by Apple. For `pkg` files, we can verify with `pkgutil --check-signature`. For `.app` bundles, we can verify with `codesign -v`. Will `homebrew cask` support these builtin security checks in the future?

**Comment by vitorgalvao** [comment]
There are no plans for it. There are so many more things that need to be done first, and we have such a lack of contributions to the core, it’s unlikely to be done soon.

I’m not opposed to it in the slightest, but we need to keep in mind that some apps are not signed for legitimate reasons (like not wanting to pay to do it).

**Comment by vitorgalvao** [comment]
Seems like there isn’t much interest in this for now. With so much more stuff with higher priorities, I’ll close it. We can always revisit this later.
