### ISSUE TITLE
Radio Silence Cask url change

### ISSUE THREAD

**Issue by OmgImAlexis** [caskroom/homebrew-cask#20966]
The current URL listed is `http://radiosilenceapp.com/downloads/Radio_Silence_for_OS_X_10.9_and_later.pkg` and the new URL is `https://radiosilenceapp.com/downloads/Radio_Silence_2.0.pkg`. I found the new link on [their site](https://radiosilenceapp.com/) under "Download free trial".

Ref: https://github.com/caskroom/homebrew-cask/blob/master/Casks/radio-silence.rb

**Comment by adidalal** [comment]
Feel free to take a crack at a PR. It's a pretty simple fix, and we're here to help if you have questions!

[CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)

**Comment by OmgImAlexis** [comment]
I'm getting errors while trying to update. https://github.com/vitorgalvao/tiny-scripts/issues/20#issuecomment-216760294

**Comment by vitorgalvao** [comment]
[Replied there](https://github.com/vitorgalvao/tiny-scripts/issues/20#issuecomment-216909156).

However, this isn’t a good case for `cask-repair`. It seems like a new major version, which means `uninstall` must be rechecked, as it might have changes.
