### ISSUE TITLE
Hazel v4 is now available

### ISSUE THREAD

**Issue by nikolay** [caskroom/homebrew-cask#21000]
https://www.noodlesoft.com/release_notes

**Comment by adidalal** [comment]
Feel free to take a crack at a PR. We're here to help if you have questions!

[CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)

**Comment by nikolay** [comment]
@adidalal https://github.com/caskroom/homebrew-cask/pull/21004

**Comment by nikolay** [comment]
@adidalal The build for Xcode 7.2 failed for some other reason: https://travis-ci.org/caskroom/homebrew-cask/jobs/127956695

**Comment by vitorgalvao** [comment]
@nikolay We’re aware of it. It’s been happening a lot, and the issue seems to be on Travis’ side. @adidalal is in contact with them and trying to resolve the issue.

**Comment by nikolay** [comment]
@vitorgalvao @adidalal Unfortunately, it's broken now:

```
$ brew cask install --force hazel
==> Downloading https://s3.amazonaws.com/Noodlesoft/Hazel-4.0.dmg
Already downloaded: /Library/Caches/Homebrew/hazel-4.0.dmg
==> Verifying checksum for Cask hazel
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/hazel/4.0/Hazel.prefPane'
$ brew cask zap hazel
==> Implied "brew cask uninstall hazel"
==> Dispatching zap stanza
==> Running zap process for hazel; your password may be necessary
==> Removing files: ["~/Library/Application Support/Hazel", "~/Library/Preferenc
==> Removing all staged versions of Cask 'hazel'
$ brew cask install --force hazel
==> Downloading https://s3.amazonaws.com/Noodlesoft/Hazel-4.0.dmg
Already downloaded: /Library/Caches/Homebrew/hazel-4.0.dmg
==> Verifying checksum for Cask hazel
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/hazel/4.0/Hazel.prefPane'
```

**Comment by vitorgalvao** [comment]
@nikolay It means something in the `dmg`s structure changed and needs to be fixed.

**Comment by mwarkentin** [comment]
I'm unable to install hazel v4 as well with the same error. Any documentation on what might need to be updated? When I open the .dmg, this is what's there:

![](https://mwarkentin-snaps.s3.amazonaws.com/Hazel_2016-05-04_23-34-43.png)

**Comment by vitorgalvao** [comment]
[Fixed](https://github.com/caskroom/homebrew-cask/commit/119fd7ffd87d65ca1cadd85634c72c949e2c9020).

**Comment by mwarkentin** [comment]
@vitorgalvao Confirmed working for me.. thanks!
