### ISSUE TITLE
heroku-toolbelt downlads package using insecure HTTP

### ISSUE THREAD

**Issue by inglesp** [caskroom/homebrew-cask#21012]
The heroku-toolbelt formula uses HTTP to download the package.  (See https://github.com/caskroom/homebrew-cask/blob/master/Casks/heroku-toolbelt.rb#L5.)

Accessing the same URL via HTTPS gives a certificate error, but I note that https://toolbelt.heroku.com/ downloads the package from https://toolbelt.heroku.com/download/osx.

Would you accept a patch to use https://toolbelt.heroku.com/download/osx as the URL?

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/issues/21013

Please use `brew install heroku-toolbelt`
