### ISSUE TITLE
heroku-toolbelt should not be in here

### ISSUE THREAD

**Issue by dickeyxxx** [caskroom/homebrew-cask#21013]
Users should be using this instead: https://github.com/Homebrew/homebrew-core/blob/master/Formula/heroku-toolbelt.rb

**Comment by adidalal** [comment]
Done, FYI users will *not* be prompted to switch over to the formula, they'll just see a (!) next to the package name until they `brew cask uninstall heroku-toolbel; brew install heroku-toolbelt`, we don't share package lists

**Comment by dickeyxxx** [comment]
This cask version will autoupdate, so it's likely not an issue.

**Comment by adidalal** [comment]
Excellent, thanks for the heads-up.
