### ISSUE TITLE
Travis: Failing Builds

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#21041]
Looks like Travis builds are still failing - 10.11 builds exit properly but still show up as a failure.

Additionally, caching is not working properly.

Made a few changes to `.travis.yml` as directed by support, but doesn't seem to have the desired effect.

**Comment by vitorgalvao** [comment]
Pinging @jawshooah directly, since he worked a lot with those. I’m at a loss as to why those are failing.

**Comment by adidalal** [comment]
I think I fixed it with https://github.com/caskroom/homebrew-cask/commit/1f074c0e0ba08bed6588288b83cb751251b73229 - will keep an eye out but caching works properly now.

**Comment by vitorgalvao** [comment]
Great work! Looks like you fixed it. Want to go ahead and fix the other repos, or you’d rather I do it?

**Comment by adidalal** [comment]
Won't be on a computer for a bit, you can go ahead and fix the other repos (and close the issue)

Thanks

**Comment by vitorgalvao** [comment]
Done.
