### ISSUE TITLE
I was told to report this error

### ISSUE THREAD

**Issue by boatmaker** [caskroom/homebrew-cask#21062]
Error: undefined method `clang_version' for OS::Mac:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:32:in `<class:Octave>'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:171:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/formulary.rb:230:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1141:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1139:in `map'
/usr/local/Library/Homebrew/formula.rb:1139:in `installed'
/usr/local/Library/Homebrew/diagnostic.rb:886:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'

**Comment by adidalal** [comment]
Wrong homebrew (We're cask, not science).
Open an issue at https://github.com/Homebrew/homebrew-science and follow their guidelines for reporting bugs.

**Comment by boatmaker** [comment]
Thank you! My apologies
