### ISSUE TITLE
Cask request:

### ISSUE THREAD

**Issue by LesTR** [caskroom/homebrew-cask#21071]
### Cask details

I need install ODBC driver for Hive from Hortoworks (I am preparing PR)

**Name** - Hortonworks ODBC Driver for Apache Hive (v2.1.2)

**Homepage** - http://hortonworks.com/downloads/

**License** - Hive ODBC Driver License Agreement ("Agreement") is made by Hortonworks (details in http://hortonworks.com/licenses/ )

**Download URL** - http://public-repo-1.hortonworks.com/HDP/hive-odbc/2.1.2.1002/Mac_OS_X/hive-odbc-native.dmg

**Description** - Hive ODBC driver

**Comment by LesTR** [comment]
Sended PR https://github.com/caskroom/homebrew-cask/pull/21072

Please review and merge my request. Thanks!

**Comment by vitorgalvao** [comment]
> I am preparing PR

Please don’t open issues when making the PR yourself, simply submit it.
