### ISSUE TITLE
Cask request: WhatsApp

### ISSUE THREAD

**Issue by designorant** [caskroom/homebrew-cask#21108]
### Cask details

**Name** - WhatsApp

**Homepage** - https://www.whatsapp.com/download/

**License** - :unknown

**Download URL** - https://web.whatsapp.com/desktop/mac/files/WhatsApp.zip

**Description** - Simple. Personal. Real Time Messaging.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/commit/24e4fecf92a4c97dc783d681167d83a4fc5a2483
