### ISSUE TITLE
WhatsApp official prompts to be moved to /Applications

### ISSUE THREAD

**Issue by monchote** [caskroom/homebrew-cask#21115]
I'm not sure there's much that can be done here but I thought I'd raise it.
![screen shot 2016-05-11 at 11 44 44](https://cloud.githubusercontent.com/assets/1186808/15178815/cf07a4e8-176f-11e6-8f9a-f9f7e9ac2f90.png)

**Comment by adidalal** [comment]
Yes, suppress_move_to_applications. I'm on mobile but just search the repo for an example cask and if you make a PR I can merge

**Comment by adidalal** [comment]
You can tag me in the PR so I'll get a notification

**Comment by monchote** [comment]
@adidalal Thanks. I'm going to give it a go now.

**Comment by monchote** [comment]
@adidalal It looks like the app is not using NSUserDefaults to save that flag so suppress_move_to_applications doesn't work. They're not using a custom key for it either.

This flag is stored in `~/Library/Application\ Support/WhatsApp/settings.json` as `"hasLoaded":true`

Do Cask support executing a small script to write this value in postflight?

**Comment by adidalal** [comment]
Yes, we support shim scripts.
https://github.com/caskroom/homebrew-cask/blob/master/Casks/minecraft-server.rb is an example of the general style used

**Comment by tsparber** [comment]
Obsoleted by #13966
