### ISSUE TITLE
Screenhero cask has incorrect sha256 checksum

### ISSUE THREAD

**Issue by diclophis** [caskroom/homebrew-cask#21136]
Hello,

It appears that the official dmg for Screenhero version `2.3.7.0` has been mutated somehow on the remote server: `https://secure.screenhero.com/update/screenhero/Screenhero-2.3.7.0.dmg` ... the new checksum appears to be: `59d5800f420b9174703ba30342635e023f55b3fd7d11bb31ad9976e2ed7c0e50`

I am not sure how we want to address this, obviously there is something fishy going on in terms of, why would they publish a different package with the same version, hopefully they just have a misunderstanding of how to correctly version and package their application... or there might be some malicious activity that has mutated the remote resource as part of a cyber attack

**Comment by diclophis** [comment]
@victorpopkov @jawshooah @vitorgalvao any help figuring this out would be appreciated...

**Comment by vitorgalvao** [comment]
Next step would be contacting them via twitter/email to confirm. Mind doing so?

**Comment by frk2** [comment]
We made a small mistake during pushing a security update out yesterday which may have caused this. Nothing too fishy except human error. Also I didn't know we have a homebrew cask! Thanks for that :)

**Comment by vitorgalvao** [comment]
Thank you for the quick reply, @frk2.

Either way, `2.3.8.0` is out, so lets use that.

**Comment by diclophis** [comment]
@frk2 thanks for the quick reply... this is important to use because we make use of `homebrew` to automate workstation installation for on-boarding new engineers and we have a whole team of people we need to get setup today and this was a blocking bug... @vitorgalvao also thanks for the quick response

**Comment by frk2** [comment]
ofcourse! Also make sure to use the latest (2.3.8.0) which has a security fix.
