### ISSUE TITLE
Bug report: To Contribute still fail - creating pull request: Unprocessable Entity (HTTP 422)

### ISSUE THREAD

**Issue by howie** [caskroom/homebrew-cask#21149]
### Description of issue
Hi just like issue  #18320
When I try to update tableau , I got fail message below

cask-repair --pull origin --push $github_user $outdated_cask
fatal: A branch named 'cask-repair_update-tableau-public' already exists.
---------------------------------------------------------------------------------------------------------------------------------------
cask 'tableau-public' do
  version :latest
  sha256 :no_check

  url 'https://downloads.tableausoftware.com/public/TableauPublic.dmg'
  name 'Tableau Public'
  homepage 'https://www.tableausoftware.com/public'
  license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

  app 'Tableau Public.app'
end
---------------------------------------------------------------------------------------------------------------------------------------
Type the new version (or leave blank to use the current one)
> 9.3
Paste the new URL (or leave blank to use the current one)
> https://public.tableau.com/s/download/public/mac
==> Downloading external files for Cask ./tableau-public.rb
==> Downloading https://public.tableau.com/s/download/public/mac
######################################################################## 100.0%
==> No checksum defined for Cask tableau-public, skipping verification
==> Success! Downloaded to -> /Library/Caches/Homebrew/tableau-public-9.3
diff --git i/Casks/tableau-public.rb w/Casks/tableau-public.rb
index cf85ad2..a2c357d 100644
--- i/Casks/tableau-public.rb
+++ w/Casks/tableau-public.rb
@@ -1,8 +1,8 @@
 cask 'tableau-public' do
-  version :latest
-  sha256 :no_check
+  version '9.3'
+  sha256 '73f82fb7eac3f99a52ed53f48457b031db2d38b9cf1a30462dffa655a4618012'

-  url 'https://downloads.tableausoftware.com/public/TableauPublic.dmg'
+  url 'https://public.tableau.com/s/download/public/mac'
   name 'Tableau Public'
   homepage 'https://www.tableausoftware.com/public'
   license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder
---------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? You can also make further manual edits (y/n/e) y
Submitting…
To git@github.com:howie/homebrew-cask.git
 ! [rejected]        cask-repair_update-tableau-public -> cask-repair_update-tableau-public (non-fast-forward)
error: failed to push some refs to 'git@github.com:howie/homebrew-cask.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error creating pull request: Unprocessable Entity (HTTP 422)
No commits between master and master
Error creating pull request: Unprocessable Entity (HTTP 422)
No commits between master and master

There was an error submitting the pull request. Have you forked the repo and made sure the pull and push remotes exist?

#### git remote --verbose
howie	git@github.com:howie/homebrew-cask.git (fetch)
howie	git@github.com:howie/homebrew-cask.git (push)
origin	https://github.com/caskroom/homebrew-cask (fetch)
origin	https://github.com/caskroom/homebrew-cask (push)

#### brew info cask-repair
vitorgalvao/tiny-scripts/cask-repair: stable 0.23.1
Script to quickly repair outdated/broken Casks from homebrew-cask
https://github.com/vitorgalvao/tiny-scripts
/usr/local/Cellar/cask-repair/0.23.1 (4 files, 17.4K) *
  Built from source on 2016-04-20 at 09:20:15
From: https://github.com/vitorgalvao/homebrew-tiny-scripts/blob/master/cask-repair.rb
==> Dependencies
Required: hub ✔
Recommended: hr ✔
==> Options
--without-hr
	Build without hr support

#### brew info hub
hub: stable 2.2.3 (bottled), HEAD
Add GitHub support to git on the command-line
https://hub.github.com/
/usr/local/Cellar/hub/2.2.3 (9 files, 10.3M) *
  Poured from bottle on 2016-01-24 at 22:33:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb
==> Dependencies
Build: go ✔
==> Options
--without-completions
	Disable bash/zsh completions
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

### Output of `brew cask doctor`

brew cask doctor
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.4
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 745a1; last commit 2016-05-12)
Homebrew/homebrew-core (git revision 4001; last commit 2016-05-12)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision af0851; last commit 10 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-fonts
/usr/local/Library/Taps/caskroom/homebrew-versions
==> Homebrew-cask Default Tap Cask Count:
3139
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/howie/.jenv/shims:/Users/howie/.jenv/bin://usr/local/opt/postgresql/bin:/usr/local/opt/go/bin:/usr/local/opt/gradle/libexec/bin:/Users/howie/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/howie/.yadr/bin:/Users/howie/.yadr/bin/yadr:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="zh_TW.UTF-8"
==> Running As Privileged User:
No

**Comment by vitorgalvao** [comment]
Follow [these](https://github.com/vitorgalvao/tiny-scripts/issues/20#issuecomment-215190014) and [this](https://github.com/vitorgalvao/tiny-scripts/issues/20#issuecomment-218273333), and reply on that issue.
