### ISSUE TITLE
macfusion > sshfs > osxfuse{,beta}

### ISSUE THREAD

**Issue by pvtmert** [caskroom/homebrew-cask#21194]
installing osxfuse-beta then installing sshfs overwrites it with osxfuse (nonbeta)

if its possible, changing depends_on: x or y style should be sufficent.

if its not i have to live with it :)

**Comment by vitorgalvao** [comment]
They’re both `pkg`s, so we have no control over that.

Next time, though, please be more thorough with the issue. Posts the casks themselves or at the very least link to them. Maintainers shouldn’t need to plow through the repo to find these to fix your personal issue.

Not a complaint, just a note for the future. It helps us (and consequently you) when you do that.
