### ISSUE TITLE
Upgrade function for casks

### ISSUE THREAD

**Issue by chuchana** [caskroom/homebrew-cask#21205]
Inspired by [this answer on Ask Different](http://apple.stackexchange.com/a/231020/151759), I hacked together some functionality to check for updated casks and upgrade them selectively in [fish](http://fishshell.com). I started to translate it to Ruby, but I have no idea how this should be integrated into homebrew:

    casks = `brew cask list`.split
    outdated_casks = []

    casks.each do |cask|
      current_version = `#{"brew cask info #{cask} | sed -n '1p' | sed -n 's/^.*: \\(.*\\)$/\\1/p'"}`
      installed_version = `#{"ls /opt/homebrew-cask/Caskroom/#{cask}"}`
      unless installed_version == current_version
        puts "#{cask} #{installed_version} --> #{current_version}\n"
        outdated_casks.push("#{cask}")
      end
    end

    puts outdated_casks

 

    casks.each do |cask|
      `#{"brew cask uninstall --force #{cask}"}`
      `#{"brew cask   install --force #{cask}"}`
    end

**Comment by vitorgalvao** [comment]
Thank you, but as has been explained multiple times in multiple places, [relying on `brew cask list` won’t work](https://github.com/caskroom/homebrew-cask/issues/14058).

**Comment by chuchana** [comment]
I did not now about that. But isn't it better to have it work for most casks than not for any? Or is another implementation planned?

**Comment by vitorgalvao** [comment]
> But isn't it better to have it work for most casks than not for any?

No, not at all. An inconsistent implementation does no one any good, Especially us maintainers, that would spend all day answering those bug reports.

> Or is another implementation planned?

Yes, a proper implementation is planned, naturally, but not in the works.

**Comment by chuchana** [comment]
That makes sense.

Any objection to using `ls /opt/homebrew-cask/Caskroom/`instead of `brew cask list`?

**Comment by vitorgalvao** [comment]
Yes. That will break with #13201.
