### ISSUE TITLE
Cask fails to symlink/install to protected areas

### ISSUE THREAD

**Issue by alexchandel** [caskroom/homebrew-cask#21238]
Say I want to install things to the global domain instead of `~`. A reasonable desire, given that homebrew-cask is global. homebrew-cask has no `--rootdir=/` option for some reason, so I pass `--appdir=/Applications --prefpanedir=/Library/PreferencePanes --qlplugindir=/Library/QuickLook --fontdir=/Library/Fonts --input_methoddir="/Library/Input Methods" --screen_saverdir="/Library/Screen Savers"`. If a cask with a QuickLook plugin is installed, cask then produces an error like
```sh
==> Downloading https://github.com/whomwah/qlstephen/releases/download/1.4.3/QLStephen.qlgenerator.1.4.3.zip
Already downloaded: /Library/Caches/Homebrew/qlstephen-1.4.3.zip
==> Verifying checksum for Cask qlstephen
==> Symlinking QuickLook Plugin 'QLStephen.qlgenerator' to '/Library/QuickLook/QLStephen.qlgenerator'
==> ln: /Library/QuickLook/QLStephen.qlgenerator: Permission denied
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hfs", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/qlstephen/1.4.3/QLStephen.qlgenerator>", "#<Pathname:/Library/QuickLook/QLStephen.qlgenerator>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 5868 exit 1>
```

This shouldn't happen.

**Comment by vitorgalvao** [comment]
This is an atypical request, and low priority due to that. Like many other low priority issues that no other user cares for, this will be closed to make issue tracking tennable. It may be revisited in the future, but certainly not soon by the core team.

A PR may be looked at and discussed, but currently we’re slow on core maintainers to even look at those.

**Comment by alexchandel** [comment]
@vitorgalvao Isn't this necessary to implement #13201 though? Since most of library probably (but not necessarily) requires sudo-ing?

**Comment by vitorgalvao** [comment]
Not really. We will continue to avoid `sudo` whenever possible. #13201 says that the goal is to emulate regular manual installs. The recommended way to install QLPlugins and the like is under `~/Library`, not `/Library`. Similarly, the recommended way to install apps is in `/Applications`, not `~/Applications`.

We have seen many issues with apps requiring the use of `~/Applications`, but few (if any) regarding the use of `~/Library`. When the pater occurs, it’s usually a `pkg` anyway, and it takes care of it itself.

**Comment by alexchandel** [comment]
@vitorgalvao But I'd like to install casks for all users, just like I use homebrew to install CLT packages for all users. (also still studying 13966)

**Comment by jawshooah** [comment]
I'm not sure I understand why this is a problem with HBC. You want to install to a location that requires root access. We can't give you root access, so you must either chown the directory you wish to install to, or use sudo with cask.
