### ISSUE TITLE
Syncthing cask out of date (404 not found)

### ISSUE THREAD

**Issue by remisharrock** [caskroom/homebrew-cask#21240]
Syncthing cask out of date:
```
brew cask install syncthing
==> Downloading https://github.com/syncthing/syncthing/releases/download/v0.12.22/syncthing-macosx-amd64-v0.12.22.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'syncthing' with message: Download failed: https://github.com/syncthing/syncthing/releases/download/v0.12.22/syncthing-macosx-amd64-v0.12.22.tar.gz
```

latest release:

https://github.com/syncthing/syncthing/releases/download/v0.12.24/syncthing-macosx-amd64-v0.12.24.tar.gz

**Comment by vitorgalvao** [comment]
See [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md). I’ve generated https://github.com/caskroom/homebrew-cask/pull/21242 simply with `cask-repair -v 0.12.24 -b syncthing`.

**Comment by remisharrock** [comment]
@vitorgalvao  Nice, thanks ; There should be a link for those (like me) rg

https://github.com/caskroom/homebrew-cask#reporting-bugs

https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md 
here:
