### ISSUE TITLE
ax88179 URL broken

### ISSUE THREAD

**Issue by mattzago** [caskroom/homebrew-cask#21279]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/ax88179.rb

Is out of date because of a newer driver version. I have a fork that I'm prepping a PR for with the following changes:

```
--- a/Casks/ax88179.rb
+++ b/Casks/ax88179.rb
@@ -1,6 +1,6 @@
 cask 'ax88179' do
-  version '2.7.0'
-  sha256 '8b12ecad1407e65a2bd89f055cfe7f2be102b3623b0b207b55f7f9eac54253e9'
+  version '2.8.0'
+  sha256 '4231136a1756f864dfad506497703dd48a2d95503a91914d98f9a12c129ef3a1'` 
```

But I get the (truncated) error below using the homebrew user. I don't get the .pkg path error when running via sudo. Seems like the ditto is failing to copy files from the mounted disk image in /private/tmp to /opt/homebrew-cask/Caskroom/ax88179/2.8.0, but I'm failing to see the issue, and guessing it's something silly.

```
==> Executing: ["/usr/bin/ditto", "--", "/private/tmp/dmg.sb3nUC", "/opt/homebrew-cask/Caskroom/ax88179/2.8.0"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.sb3nUC"]
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for ax88179; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Purging files for version 2.8.0 of Cask ax88179
Error: pkg source file not found: '/opt/homebrew-cask/Caskroom/ax88179/2.8.0/AX88179_178A_v2.8.0.pkg'/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/pkg.rb:43:in `run_installer'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/pkg.rb:30:in `block in install_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/pkg.rb:30:in `install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:124:in `block in install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:122:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:122:in `install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:71:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:6:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:126:in `exit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:126:in `rescue in process'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:117:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
```

**Comment by vitorgalvao** [comment]
Post your cask together with the error.

**Comment by mattzago** [comment]
The cask here is here:

https://github.com/mattzago/homebrew-cask/blob/master/Casks/ax88179.rb

The full error debug output is above, but the short output using my cask is here:

> zagomacbook:~ zago$ brew cask install ax88179
> ==> Downloading http://www.asix.com.tw/FrootAttach/driver/AX88179_178A_Macintosh_
> ######################################################################## 100.0%
> ==> Verifying checksum for Cask ax88179
> ==> Extracting nested container AX88179_178A.dmg
> ==> Running installer for ax88179; your password may be necessary.
> ==> Package installers may write to any location; options such as --appdir are ig
> Error: pkg source file not found: '/opt/homebrew-cask/Caskroom/ax88179/2.8.0/AX88179_178A_v2.8.0.pkg'
>

**Comment by vitorgalvao** [comment]
That just means the `pkg` file inside the zip now has a different name, and it needs to be updated accordingly.

**Comment by fanquake** [comment]
Was this fixed by #21309?

**Comment by vitorgalvao** [comment]
@fanquake No, merely version bumped.

**Comment by mattzago** [comment]
Hmm is the `pkg` really the wrong name though? 

> > macbook:local zago$ brew cask install ax88179
> ==> Downloading http://www.asix.com.tw/FrootAttach/driver/AX88179_178A_Macintosh
> Already downloaded: /Library/Caches/Homebrew/ax88179-2.8.0.zip
> ==> Verifying checksum for Cask ax88179
> ==> Extracting nested container AX88179_178A.dmg
> ==> Running installer for ax88179; your password may be necessary.
> ==> Package installers may write to any location; options such as --appdir are i
> Error: pkg source file not found: '/opt/homebrew-cask/Caskroom/ax88179/2.8.0/AX88179_178A_v2.8.0.pkg'
> macbook:local zago$ ls /Volumes/AX88179/AX88179_178A_v2.8.0.pkg
> /Volumes/AX88179/AX88179_178A_v2.8.0.pkg

In this case I opened the .zip and nested .dmg in /Library/Caches/Homebrew to see that AX88179_178A_v2.8.0.pkg was the name of the package (vs the cask name). And it is.

A `sudo brew cask install ax88179` does work. Which is why I originally asked why it seems like the ditto of the pkg from the mounted disk image doesn't seem to be working. I'll spin up a 10.11.5 VM while I'm at it to see if I can reproduce again outside my normal setup.

**Comment by mattzago** [comment]
I can reproduce in a fresh 10.11.5 VM. Maybe this is an El Capitan bug or something with ditto, but it seems like ditto can't copy items from this vendors disk image without sudo. The vendor seemed to have left some extended attributes and .fsevents and .Trashes items in the disk image.

So I'm curious what's correct here. Working around the bug (assuming others can reproduce), or trying to get a normal disk image from the vendor?

**Comment by adidalal** [comment]
Ideally, it should be fixed upstream. Unlike homebrew occasionally does, we don't apply "patches" or work-arounds to get an app working (though shim scripts may fall past that line, depending on purpose)

**Comment by vitorgalvao** [comment]
> or trying to get a normal disk image from the vendor

That is **always** the best option and the one that should be tried first. Workarounds pile up. Correct behaviour reduces problems for everyone.

**Comment by vitorgalvao** [comment]
@mattzago Any luck contacting them?

**Comment by mattzago** [comment]
I have a query out, but I haven't heard back yet. Might be a while because getting to the person who is creating the disk image at a taiwanese company could be a bit difficult.

I have worked around this issue with manual installs. If opinions change about workarounds it seems like after more testing that ditto dir/* works inside this dmg where ditto dir doesn't. It seems like an issue because the dmg is MBR with a fat partition instead of GUID with hfs.

**Comment by vitorgalvao** [comment]
@mattzago Make the workaround as long as it just modifies the cask and submit it, so we can discuss it.

**Comment by vitorgalvao** [comment]
Closing since there has been no resolution and there seems to not be much interest anyway. Will remove the cask unless there are any developments in a few days. No point in keeping a broken cask.

**Comment by franklouwers** [comment]
I am willing to maintain this cask. I just need help regarding uninstalling: there is an uninstall script in the .dmg, but that isn't installed using the pkg it seems. Can you point me to a link how to handle this?

**Comment by vitorgalvao** [comment]
@franklouwers [Both ax* drivers were removed](https://github.com/caskroom/homebrew-cask/pull/24292/files) (in case you care for both).

We keep everything from the dmg, so you can just reference them. Look at how these formulas were, they used said scripts.

**Comment by franklouwers** [comment]
Ah thanks. I'll create a pull request for the 88179 one  (I use that driver), and have a look at the other one, but won't be able to verify much, as I don't own such a device.

**Comment by franklouwers** [comment]
See https://github.com/caskroom/homebrew-cask/pull/24421
