### ISSUE TITLE
Sketch sha256 mismatch

### ISSUE THREAD

**Issue by hiddenindians** [caskroom/homebrew-cask#21319]
Error: sha256 mismatch
Expected: cf07466d5c8aaffb3e0c6d6242c3f2367b4f84d293d01064e1a7ee1a503c3429
Actual: 150afb85c8ddd0574e9ccc26d09bad6bf085ce628466a81b9ca60f9652a8b75a
File: /Library/Caches/Homebrew/sketch-3.7.2.zip

I've verified, by downloading it directly from Sketch on another machine, that the sha256 sum is actually "150afb85c8ddd0574e9ccc26d09bad6bf085ce628466a81b9ca60f9652a8b75a"

**Comment by vitorgalvao** [comment]
Please don’t open issues if you’re going to submit the PR.
