### ISSUE TITLE
安装时下载失败，可以从本地安装

### ISSUE THREAD

**Issue by l5oo00** [caskroom/homebrew-cask#21346]
安装时因为网络原因， 经常下载失败，可以先用其他下载工具下载好， 然后放到brew的缓存目录(运行`brew --cache`可得， 一般是`/Library/Caches/Homebrew`)里

注意将文件名称改为brew [期望的名称](https://github.com/caskroom/homebrew-cask/blob/master/lib/vendor/homebrew-fork/download_strategy.rb#L41)， 一般有以下两点（不一定准确）：

- 文件名字母全部改为小写
- 下划线改为"-"

实在不清楚的， 可以修改本地文件：
`/usr/local/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/download_strategy.rb`
[fetch](https://github.com/caskroom/homebrew-cask/blob/master/lib/vendor/homebrew-fork/download_strategy.rb#L60)函数， 在第一行加一句`puts "Hope downloaded: #{tarball_path}"`

重新运行安装命令， 即可看到实际的缓存地址。

![image](https://cloud.githubusercontent.com/assets/1233234/15446992/6bd345b6-1f63-11e6-80e3-a7493b8dcdb5.png)

 将下载好的安装包改成相应的名称放入缓存目录， 重新安装即可。

![image](https://cloud.githubusercontent.com/assets/1233234/15447007/b04aedd4-1f63-11e6-8c95-10d294737290.png)

**Comment by l5oo00** [comment]
Error: Download failed on Cask

**Comment by fanhefan** [comment]
下载时报 curl: (35) Server aborted the SSL handshake
也可以用这种方法搞定~~
