### ISSUE TITLE
Add bash completion

### ISSUE THREAD

**Issue by cc941201** [caskroom/homebrew-cask#2134]
Tab completion for formula names is very convenient in Homebrew.

Also aliases for commands are also welcomed. (ls for list, rm for uninstall, reinstall, log, etc)

**Comment by tonglil** [comment]
Anyone have progress on this? I'm not very familiar with writing completions but I can give it a try as a project this weekend and see where I get to.

**Comment by cc941201** [comment]
@tonglil that would be great.

**Comment by paulirish** [comment]
I wanted to describe my two primary usecases for completion.

* I will search: `brew cask search sketch` for looking for SketchUp
* I will then install whichever match makes most sense.

```sh
$ cask search sketch
* ==> Exact match
sketch
==> Partial matches
graphsketcher	sketch-beta	sketch-tool	sketch-toolbox	sketchup	sketchup-pro	sketchupviewer

$ cask install sketchup
==> Downloading https://dl.trimble.com/sketchup/SketchUpMake-en.dmg
```


I ideally would like completion for both

1. the command `install`
1.  matching package names from the respository 
  * even better, packages returned by previous search have higher weighting


<hr>

That said I'm just eager for anyone to give this a go, even if the result is quite basic. Cheers.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This isn’t even related to the core itself, and like with zsh, a solution should come from the outside.

**Comment by vitorgalvao** [comment]
For those interested in this, see https://github.com/caskroom/homebrew-cask/issues/14436, as @xyb made it happen.
