### ISSUE TITLE
Discard `binary` dir and use what your Homebrew install uses?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#21372]
Since we will be [merging with Homebrew](https://github.com/caskroom/homebrew-cask/issues/14384) rather then separating further, keeping a separate `binary` directory starts to become nonsensical.

I propose we get rid of [`binarydir`](https://github.com/caskroom/homebrew-cask/blob/58fef4f3e63488418a09ab1bb4a201b2fa01b528/USAGE.md#options), and for CLI binaries we read directly from the user’s Homebrew installation and use whatever they use.

---

If accepted, we should close https://github.com/caskroom/homebrew-cask/issues/7750.

**Comment by adidalal** [comment]
Agreed

**Comment by MikeMcQuaid** [comment]
Seems like a great idea 👍

**Comment by blogabe** [comment]
FWIW frequent user of both, infrequent contributor to both, and I agree.

**Comment by reitermarkus** [comment]
Seems like we all agree on this, so I went ahead and implemented it: https://github.com/caskroom/homebrew-cask/pull/23238
