### ISSUE TITLE
I want to switch back to alfred 2

### ISSUE THREAD

**Issue by huanzhang** [caskroom/homebrew-cask#21390]
As I could no use my old alfred 2 licence for alfred 3, I want to reinstall alfred 2 and uninstall alfred 3 with brew cask.

**Comment by vitorgalvao** [comment]
You’ll have to do it manually, not through homebrew-cask.

**Comment by caleb531** [comment]
@huanzhang: I have heard you and have submitted a pull request for Alfred 2 on `caskroom/homebrew-versions`. It has just been merged in (see caskroom/homebrew-versions#2502) under the name `alfred2`.

To install, first run `brew update` and then run:

```
brew cask install caskroom/homebrew-versions/alfred2
```
