### ISSUE TITLE
Cask request:

### ISSUE THREAD

**Issue by erichyland** [caskroom/homebrew-cask#21412]
### Cask details

(Please fill out as much as possible)

**Name** - Alfred 3

**Homepage** - https://www.alfredapp.com/

**License** - 

**Download URL** - https://cachefly.alfredapp.com/Alfred_3.0_652.zip

**Description** - Alfred is an award-winning app for Mac OS X which boosts your efficiency with hotkeys, keywords, text expansion and more. Search your Mac and the web, and be more productive with custom actions to control your Mac.

**Comment by vitorgalvao** [comment]
Please search before making a request.

This cask was already added 5 days ago.

**Comment by erichyland** [comment]
Sorry about that. I didn't do a 'brew update'
