### ISSUE TITLE
removing atom

### ISSUE THREAD

**Issue by ahundt** [caskroom/homebrew-cask#21432]
I'm seeming to have trouble completely removing `atom`, it installs launchd services and such. My searching for a solution hasn't found anything and I'm having trouble locating where things are installed. brew cask uninstall atom doesn't seem to have done everything I need. Any advice? Thanks!

**Comment by adidalal** [comment]
Use `brew cask zap atom`

```
  zap delete: [
                '~/.atom',
                '~/Library/Application Support/ShipIt_stderr.log',
                '~/Library/Application Support/Atom',
                '~/Library/Application Support/ShipIt_stdout.log',
                '~/Library/Application Support/com.github.atom.ShipIt',
                '~/Library/Caches/com.github.atom',
                '~/Library/Preferences/com.github.atom.plist',
              ]
```
