### ISSUE TITLE
Can't uninstall cask for atom

### ISSUE THREAD

**Issue by heyarne** [caskroom/homebrew-cask#21462]
I installed `atom` yesterday, v 1.7.3. It since then updated to 1.7.4 and not I can't uninstall it:
```
$ brew cask rm atom
Error: atom is not installed

$ brew cask list   
atom				 …
```

What can I do to resolve this? `brew doctor` does not ouptut anything related to atom, neither does `brew cask doctor`. I am on Mac OSX 10.11.5.

**Comment by adidalal** [comment]
It's `brew cask uninstall atom (--force)` or `brew cask zap atom` for a full cleanup
