### ISSUE TITLE
password-gorilla 1.5.3.7.3 doesn't require 32-bit mode

### ISSUE THREAD

**Issue by dspruell** [caskroom/homebrew-cask#21519]
homebrew-cask/Casks/password-gorilla.rb indicates in caveats that:

> Password Gorilla must be run in 32-bit mode

This should no longer be the case as it was related to an older issue that I believe was resolved in a previous update. The application runs correctly without the 32-bit mode limitation.

Also in caveats:

> Gatekeeper may need to be temporarily disabled for the first launch

Note https://github.com/zdia/gorilla/issues/154 - a known Gatekeeper workaround for allowing unsigned apps to run (CTRL+click, Open) was found to **not** work in at least some cases, and another workaround was identified to allow the program to run without working around Gatekeeper (clearing the com.apple.quarantine extended attribute from the bundle using _xattr(1)_). I don't know if this is of value for the formula, as I notice that none of the installed files in `/opt/homebrew-cask/Caskroom/password-gorilla` have extended attributes and it launches without problem on my system (OS X 10.10.5) with Gatekeeper enabled. Perhaps after testing, this caveat could be removed also.

**Comment by vitorgalvao** [comment]
Sounds good. Care to submit the modifications?

**Comment by dspruell** [comment]
I've got some breakage in my system I'm working through... someone else able to for now?

**Comment by vitorgalvao** [comment]
You can submit the fixes anyway. It’ll be easier for us to test and discuss, having a central point of discussion.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/21528
