### ISSUE TITLE
Some casks here, some casks there... 

### ISSUE THREAD

**Issue by pquodling** [caskroom/homebrew-cask#21532]
I went looking to upgrade some cask apps (still not clear if there is a "best way" to do that), and something didn't seem right - Digging further, I find that about half of my cask apps sitting in /Applications point to /usr/local/Caskroom/Appname/  and half point to /opt/homebrew-cask/Caskroom/Appname/.

Is this right/expected? Is there a way to "fix this"?

**Comment by vitorgalvao** [comment]
There’s no automated way to fix that, no.

That wasn’t on us, though, and has never been reported before. The only reason for that to happen was if you messed with the [`caskroom` option](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options).

**Comment by pquodling** [comment]
I messed up? I just followed the basic instructions to install - so, if there is no automated way, is there a manual way? I am guessing uninstalling all apps in the /usr/Local/Caskroom directory, doing a "cleanup" and then re-installing them, should put them where they should be, which as I read it, is /opt/homebrew-cask/Caskroom/appname/

**Comment by vitorgalvao** [comment]
I didn’t say you messed *up*, I said you messed *with* an option. The difference in meaning is huge.

Yes, the manual way is by doing what you said.

Be sure to check https://github.com/caskroom/homebrew-cask/issues/13201 and https://github.com/caskroom/homebrew-cask/pull/13966 beforehand, though. The way we install will be changing soon.
