### ISSUE TITLE
Puppet Version Bump

### ISSUE THREAD

**Issue by kstanley-contec** [caskroom/homebrew-cask#21554]
The current version available by tap is 3.8.7, but puppet is up to version 4.5. I would like to request an update to the puppet tap that would allow for newer versions of the software. If updating 'Caskroom/cask/puppet' is not feasible, maybe doing something like apache and php where there are multiple versions simultaneously would be a nice compromise. Thank you.

**Comment by adidalal** [comment]
Feel free to take a crack at a PR. It's a pretty simple fix, and we're here to help if you have questions!

[CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)

**Comment by MerelyAPseudonym** [comment]
@kstanley-contec take a look at [the `puppet-agent` cask](https://github.com/caskroom/homebrew-cask/blob/ebbeea4cad0199baf8c44e084f1df4a72dc5faed/Casks/puppet-agent.rb); it bundles a bunch of stuff, [including Puppet 4.5](https://docs.puppet.com/puppet/4.5/reference/about_agent.html). (I don't mean to stifle any policy discussion though! I just saw an opportunity to be helpful.)

**Comment by adidalal** [comment]
Looks like puppet 4.x is installed as puppet-agent

https://docs.puppet.com/puppet/4.0/reference/release_notes.html

That being said, if it makes more sense to move puppet to -legacy, that can be done. I don't exactly know where a standalone 4.5 install can be found, as I don't use the software.

@Jerzerak looks like you did the last puppet update, any thoughts?

**Comment by vitorgalvao** [comment]
Since we have no solution, [getting ready to delete `puppet`](https://github.com/caskroom/homebrew-cask/pull/21882).
