### ISSUE TITLE
Apps never showed in finder's Applications folder but in ~/Applications

### ISSUE THREAD

**Issue by leafiy** [caskroom/homebrew-cask#21551]
brew --version
Homebrew 0.9.9 (git revision f129; last commit 2016-05-30)
Homebrew/homebrew-core (git revision 08fc; last commit 2016-05-31)

brew doctor
Your system is ready to brew

osx 11.5

**Comment by leafiy** [comment]
brew cask doctor                                                                                      
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision f129; last commit 2016-05-30)
Homebrew/homebrew-core (git revision 08fc; last commit 2016-05-31)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-cask Version:
0.60.0 (git revision 7e98; last commit 34 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3182
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
==> Running As Privileged User:
No

**Comment by leafiy** [comment]
brew cask install qq  
==> Downloading http://dldir1.qq.com/qqfile/QQforMac/QQ_V4.2.1.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask qq
==> Symlinking App 'QQ.app' to '/Users/leafiy/Applications/QQ.app'
🍺  qq staged at '/opt/homebrew-cask/Caskroom/qq/4.2.1' (3567 files, 76M)

I can find qq in launchpad
**BUT NO QQ IN FINDER's APPLICATIONS FOLDER**

**Comment by vitorgalvao** [comment]
That’s expected and [well documented](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md) (also, how to change that). There are also multiple issues on it.

#13966 will change that.
