### ISSUE TITLE
Cask request: Electron Markdownify

### ISSUE THREAD

**Issue by wingsuitist** [caskroom/homebrew-cask#21582]
### Cask details

(Please fill out as much as possible)

**Name** - Electron Markdownify

**Homepage** - http://www.amitmerchant.com/electron-markdownify/

**License** - MIT

**Download URL** - https://github.com/amitmerchant1990/electron-markdownify/releases/download/v1.1.3/Markdownify-darwin-x64.zip

**Description** - This is a minimal Markdown Editor desktop app based on Electron.

**Comment by wingsuitist** [comment]
I added a first version here - but it seams the .app is broken from the original source.
https://github.com/wingsuitist/homebrew-cask/commit/f36cc4406f51b423c5d5c28b5e9666eac9eec374

**Comment by vitorgalvao** [comment]
> it seams the .app is broken from the original source

What do you mean? Broken how?

Submit it anyway, so we can all check the PR and comment/help.

**Comment by vitorgalvao** [comment]
Closing due to no reply and apparently no further interest in this cask.
