### ISSUE TITLE
Some `app`s should be `suite`s now.

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#21626]
As reported in https://github.com/caskroom/homebrew-cask/issues/21622. Making a new issue for better tracking. Current `app`s that need to become `suite`s (please comment about any others):

- [ ] [audacity](https://github.com/caskroom/homebrew-cask/blob/master/Casks/audacity.rb)
- [ ] [blender](https://github.com/caskroom/homebrew-cask/blob/master/Casks/blender.rb)

**Comment by vitorgalvao** [comment]
Looking further at it, seems like in the `blender` case there are only a bunch of `txt`s, and in `audacity` there are a few plugins that might or might not be needed, and perhaps can even be loaded from the Caskroom.

Closing, but pinging @wfdd in case there is something I’m missing.

**Comment by wfdd** [comment]
Blender also creates a `blenderwrapper` executable, though I've never personally used it.  The Audacity installation instructions say (`install.txt`), 'To install or reinstall Audacity, drag the "Audacity" folder icon in the DMG window to the /Applications folder ... Do not move the Audacity application or its support folders outside the "Audacity" folder'.  It's probably sensible to follow their heed - even if all of the stuff in there is operationally optional, if someone were to look for it, would they know where to find it?

**Comment by vitorgalvao** [comment]
> Blender also creates a `blenderwrapper` executable

[We make that one](https://github.com/caskroom/homebrew-cask/blob/master/Casks/blender.rb#L14L25). But now that I look at it, do we still need this @psibre, since we now move apps instead of linking them?

> Audacity … It's probably sensible to follow their heed

Agreed. Will change that one.

**Comment by wfdd** [comment]
> We make that one ...

Ah, well then, probably no point in using a suite with Blender.
