### ISSUE TITLE
Don't pick out apps from inside bundles anymore

### ISSUE THREAD

**Issue by wfdd** [caskroom/homebrew-cask#21622]
Some apps, like Audacity and Blender, come in folders ('suites') alongside other goodies.  These should now be moved to the `appdir` the way they are 'cause (a) leaving the extra resources behind breaks expectations and (b) relative paths will stop working.

**Comment by vitorgalvao** [comment]
Good point. Tracking in https://github.com/caskroom/homebrew-cask/issues/21626.
