### ISSUE TITLE
Cannot reinstall blender

### ISSUE THREAD

**Issue by scribblemaniac** [caskroom/homebrew-cask#21638]
I run `brew cask install --force blender` and it freezes during or after verifying the checksum. Here's what the verbose output looks like:
```
==> Downloading https://download.blender.org/release/Blender2.77/blender-2.77-OSX_10.6-x86_64.zip
Already downloaded: /Users/name/Library/Caches/Homebrew/blender-2.77.zip
==> Verifying checksum for Cask blender
```
And then it does nothing after this. Brew doctor is fine. Since running `brew cask audit --download blender` works fine, I would be inclined to say that that this is an issue occuring after the checksum verification.

----

(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Output of `brew cask <command> --verbose`

```
(paste output here)
```

### Output of `brew doctor`

```
(paste output here)
```

### Output of `brew cask doctor`

```
(paste output here)
```

**Comment by adidalal** [comment]
I've pasted in the reporting bugs template - please fill it out so we can have all the relevant details.

Comment back when it's filled out so I get a ping to reopen the issue.

**Comment by adidalal** [comment]
Use  `--debug` for an even more verbose output, fyi

**Comment by scribblemaniac** [comment]
Hmmm, works if I manually delete /opt/homebrew-cask/Caskroom/blender/2.77.

> Use `--debug` for an even more verbose output, fyi

Thanks for the tip!

**Comment by vitorgalvao** [comment]
> Hmmm, works if I manually delete /opt/homebrew-cask/Caskroom/blender/2.77

Does this mean you issue is fixed now, and we can close this?

**Comment by scribblemaniac** [comment]
Yes
