### ISSUE TITLE
Cask request: Smart Converter

### ISSUE THREAD

**Issue by andygrunwald** [caskroom/homebrew-cask#21660]
### Cask details

**Name** Smart Converter

**Homepage** http://shedworx.com/smart-converter-pro

**License** -

**Download URL** http://download.shedworx.com/smartconverter/SmartConverter-2.2.3.dmg

**Description**
Smart Converter is the fastest, easiest to use video converter on the App Store, thanks to it's Smart Conversion technology.

Personally i use it in the free version to convert a few videos to format like DivX

**Comment by vitorgalvao** [comment]
We can’t install Mac App Store apps.

**Comment by andygrunwald** [comment]
@vitorgalvao Sorry. I missed a link.
You can download SmartConverter here: http://www.shedworx.com/smartconverter
More in detail here: http://download.shedworx.com/smartconverter/SmartConverter-2.2.3.dmg

Would you be so nice to reopen this task again?

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/21678
