### ISSUE TITLE
Blender Cask fails install

### ISSUE THREAD

**Issue by BJTerry** [caskroom/homebrew-cask#21667]
A couple days ago I contributed PR #21580, which included Hbc.appdir, today @vitorgalvao contributed a00f4be3fdb42c22bcc0af05b22578e27ec0dbc0 which replaced `Hbc.appdir` with plain `appdir`. With this change I receive the following when trying to install:

```
==> Downloading https://download.blender.org/release/Blender2.77/blender-2.77-OSX_10.6-x86_64.zip
######################################################################## 100.0%
==> Verifying checksum for Cask blender
Warning: Unexpected method 'appdir' called during preflight on Cask blender.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

Warning: Unexpected method 'appdir' called during preflight on Cask blender.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

==> Moving App 'blender.app' to '/Applications/Blender.app'
==> Moving App 'blenderplayer.app' to '/Applications/Blenderplayer.app'
==> Symlinking Binary 'blenderwrapper' to '/usr/local/bin/blender'
```

Which breaks the shim script. I changed it back to my PR and it seemed to install fine. I'm raising this as an issue because I don't know why it breaks or how it's supposed to work. I also tried running that command and it had no effect.

I am running the following versions:

brew cask: 0.60.0 (git revision 557eae5; last commit 87 minutes ago)
Homebrew 0.9.9 (git revision 656c7; last commit 2016-06-03)
Homebrew/homebrew-core (git revision 237c; last commit 2016-06-03)

**Comment by vitorgalvao** [comment]
Ah, definitely my fault. I was changing a bunch of casks with `staged_path` and got some with this change without thinking. `appdir` isn’t available inside `preflight` (and others) like `staged_path`. Apologies for the breakage, will fix now.

**Comment by vitorgalvao** [comment]
Fixed. Thank you for the report.

**Comment by BJTerry** [comment]
Thanks!
