### ISSUE TITLE
filebot symlink source is not there

### ISSUE THREAD

**Issue by ajc85** [caskroom/homebrew-cask#21672]
following instructions at: https://www.filebot.net/forums/viewtopic.php?f=4&t=2049

When I run 'brew cask install filebot'

==> Downloading http://downloads.sourceforge.net/project/filebot/filebot/FileBot
######################################################################## 100.0%
==> Verifying checksum for Cask filebot
==> It seems there is already an App at '/Applications/FileBot.app'; not moving.
Error: It seems the symlink source is not there: '/Applications/FileBot.app/Contents/MacOS/filebot.sh'

How to resolve this error?

**Comment by vitorgalvao** [comment]
> It seems there is already an App at

Run it with `--force`.

**Comment by vitorgalvao** [comment]
> It seems there is already an App at

Run it with `--force`.

> Error: It seems the symlink source is not there: '/Applications/FileBot.app/Contents/MacOS/filebot.sh'

Perhaps the file no longer exists in newer versions. Is that the case, @rednoah?

**Comment by rednoah** [comment]
`/Applications/FileBot.app` is probably a manual install, or a Mac App Store install. Not sure how brew cask should deal with that ideally.

Ideally I'd like to have the "brew app" moved to something like `/Applications/FileBot-brew.app` but that pull request was rejected.

**Comment by vitorgalvao** [comment]
Thank you for the quick reply @rednoah.

If installed with `--force`, the behaviour is to overwrite the existing one (not sure we escalate to `sudo`, but I do remember discussing it).

If this is indeed a case of MAS and not-MAS app, then removing the existing one and installing again will fix it. Closing.

**Comment by ajc85** [comment]
Thanks guys - uninstalling MAS version and installing through brew cask fixed this issue.
