### ISSUE TITLE
New --prefix option for brew cask

### ISSUE THREAD

**Issue by drizt** [caskroom/homebrew-cask#21679]
I need to get full path to `Sparkle.framework` from `sparkle` package. For example for `qt5` brew package for this I can do `brew --prefix qt5` and got `/usr/local/opt/qt5`. So for `sparkle` I want to do 'brew cask --prefix sparkle' and get `/opt/homebrew-cask/Caskroom/sparkle/1.14.0`.

This feature will be useful for automatic build scripts. For example my application requires Sparkle.framework on OS X. And now I want to add OS X build checking to Travis CL. Problem that atm I can't get full path for Sparkle.framework and I need to use a workaround.

**Comment by vitorgalvao** [comment]
Since we now [move apps instead of linking](https://github.com/caskroom/homebrew-cask#important-homebrew-cask-changed-its-behaviour-from-linking-apps-to-moving-them-see-the-relevant-issue-and-pull-request-for-details), the concept of a prefix no longer applies.
