### ISSUE TITLE
Update MacTex

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#21725]
I would like to open a pull request to update [MacTex](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mactex.rb) to the latest version, but I am not sure how to find the latest version. Any help would be appreciated, thanks.

**Comment by arbourd** [comment]
According to the formula (https://github.com/caskroom/homebrew-cask/blob/master/Casks/mactex.rb), it looks like the package uses a "date" as a release number. 

You can find information about the newest release here: http://www.tug.org/mactex/downloading.html#checksum (04 June 2016)

To update:
- [ ] Update the version with the late release date
- [ ] Update the sha256 checksum
- [ ] Update the appcast checkpoint

Good luck!

**Comment by miccal** [comment]
Thanks, I will give it a try.
