### ISSUE TITLE
Suggestion: Add Mac OS X version check to AppCleaner

### ISSUE THREAD

**Issue by My2ndAngelic** [caskroom/homebrew-cask#21755]
As you may know, [AppCleaner](https://freemacsoft.net/appcleaner/) has 3 official releases, 1.2.2, 2.3 and 3.3 (up to now).

Ver 1 supports 10.4 to 10.5
Ver 2 supports 10.6 to 10.10
Ver 3 supports 10.10 and so on

Therefore, if you can add OS check to this app to specify which version brew should install, it would be wonderful, since they are not backward compatible.

**Comment by adidalal** [comment]
Example Cask, if you want to try it out yourself! 
https://github.com/caskroom/homebrew-cask/blob/master/Casks/graphviz.rb

Feel free to take a crack at a PR. We're here to help if you have questions!
[CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/21906.
