### ISSUE TITLE
Fail when passing arguments to cleanup

### ISSUE THREAD

**Issue by wfdd** [caskroom/homebrew-cask#21763]
I thought I could clear out the cache of a specific cask but it seems not:

```sh
$ brew cask cleanup atom-beta
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
/Users/.../Library/Caches/Homebrew/vlc-2.2.4.dmg
/Users/.../Library/Caches/Homebrew/atom-beta-1.9.0-beta0.zip
/Users/.../Library/Caches/Homebrew/basictex-20160523.pkg
/Users/.../Library/Caches/Homebrew/Casks/basictex-20160523.pkg
/Users/.../Library/Caches/Homebrew/Casks/vlc-2.2.4.dmg
/Users/.../Library/Caches/Homebrew/Casks/atom-beta-1.9.0-beta0.zip
==> This operation has freed approximately 486.3M of disk space.
```

Rather than deleting everything, `cask` should warn the `cleanup` command doesn't take any arguments.  I think that'd be better from a usability perspective.

**Comment by jawshooah** [comment]
Alternatively, `cleanup` could actually take cask token arguments and work as you expect. I believe there was an old issue requesting this behavior, but I'm on mobile so I can't verify.

**Comment by vitorgalvao** [comment]
@jawshooah Could this perhaps be something we inherit from HB with the merger?

**Comment by reitermarkus** [comment]
Closing this in favour of https://github.com/caskroom/homebrew-cask/issues/23398.
