### ISSUE TITLE
Is this a good way to solve 'XXX is not installed', after new policy that all apps are installed to /Applications

### ISSUE THREAD

**Issue by newton108** [caskroom/homebrew-cask#21785]
Related to #13201. After atom.app auto-updated to version 1.8.0, the directory name in `Caskroom/atom/1.7.4` is still the old version number. In this case brew cask seems not able to recognize that the application has been updated. Then I simply rename the directory to 1.8.0, and everything seems to work fine. Is this a valid solution for all other apps?

**Comment by vitorgalvao** [comment]
This isn’t related to that issue. We don’t have upgrade functionality, so any way you decide to upgrade is both fine an unsupported. This would have happened before the change to moving anyway. You’d need to change the directory’s name, you can just leave it be and it will work just as well.
