### ISSUE TITLE
Wireshark installation fails

### ISSUE THREAD

**Issue by kpashka** [caskroom/homebrew-cask#21794]
Looks like that Wireshark is using CDN now:

```
➜  ~ brew cask install wireshark
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.0.3%20Intel%2064.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'wireshark' with message: Download failed: https://www.wireshark.org/download/osx/Wireshark%202.0.3%20Intel%2064.dmg
```

Fresh download links from their website:
https://1.eu.dl.wireshark.org/osx/Wireshark%202.0.4%20Intel%2064.dmg
https://1.eu.dl.wireshark.org/osx/Wireshark%202.0.4%20Intel%2032.dmg

Are you guys handling region substitution in other casks somehow? E.g. if user is in US it would be inefficient to download from european server.

**Comment by victorpopkov** [comment]
Fixed by https://github.com/caskroom/homebrew-cask/pull/21792. Should be ok now.

> Are you guys handling region substitution in other casks somehow? E.g. if user is in US it would be inefficient to download from european server.

Nope.
