### ISSUE TITLE
brew cask can not uninstall

### ISSUE THREAD

**Issue by gogotanc** [caskroom/homebrew-cask#21859]
i want to uninstall dash 

```shell
$ brew cask uninstall dash
```

but it print `ERROR : dash is not installed`

<img width="296" alt="1" src="https://cloud.githubusercontent.com/assets/7715122/15985852/fa48ca1c-302c-11e6-815b-c5aba588938c.png">

**Comment by vitorgalvao** [comment]
We know. It’s related to https://github.com/caskroom/homebrew-cask/issues/14058.

Delete it manually. For that cask, it’s the same thing.
