### ISSUE TITLE
Broken download link for Audacity

### ISSUE THREAD

**Issue by AlessioXM** [caskroom/homebrew-cask#21898]
As in the title, the Audacity download link is broken.

Output for `brew cask info audacity`:  
```
audacity: 2.1.2-1453294898
Audacity
http://audacityteam.org
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/audacity.rb
==> Contents
  Audacity (suite)
```
Output for `brew cask install audacity`:
```
==> Downloading http://app.oldfoss.com:81/download/Audacity/audacity_macosx_ub_2_1_2-1453294898.dmg  
curl: (22) The requested URL returned error: 504 Gateway Time-out
Error: Download failed on Cask 'audacity' with message: Download failed: http://app.oldfoss.com:81/download/Audacity/audacity_macosx_ub_2_1_2-1453294898.dmg
The incomplete download is cached at /Users/User/Library/Caches/Homebrew/audacity-2.1.2-1453294898.dmg
```

**Comment by vitorgalvao** [comment]
Went to the site and tried to download, also didn’t work.

Problem is on their server, likely temporary.

**Comment by claui** [comment]
@AlessioXM Just as a heads up: this issue has been fixed today. It should work now.

**Comment by AlessioXM** [comment]
@claui yes indeed. I was able to download it again today. Apparently the broken link has been fixed today (I tried it yesterday with no luck). Cheers!
