### ISSUE TITLE
keeweb url broken

### ISSUE THREAD

**Issue by gulymaestro** [caskroom/homebrew-cask#21914]
$ brew cask install keeweb
==> Downloading https://github.com/antelle/keeweb/releases/download/v1.1.4/KeeWe

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'keeweb' with message: Download failed: https://github.com/antelle/keeweb/releases/download/v1.1.4/KeeWeb.mac.dmg
The incomplete download is cached at /Users/master/Library/Caches/Homebrew/keeweb-1.1.4.dmg

**Comment by IPconfig** [comment]
This project has been moved from github.com/antelle/keeweb to github.com/keeweb/keeweb.
Latest release can be found here: https://github.com/keeweb/keeweb/releases/download/v1.1.4/KeeWeb.mac.dmg

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/21916
