### ISSUE TITLE
How to migrate to the new location?

### ISSUE THREAD

**Issue by mattfelsen** [caskroom/homebrew-cask#21913]
Good morning! Since the location change and https://github.com/caskroom/homebrew-cask/pull/21901, I'm now seeing the warning about migrating Casks, as expected. I've searched around a bit but don't understand what I need to do as an end-user. Is there a command for migrating? Is it simply a move of the `/opt/homebrew-cask/Caskroom/` directory to `/usr/local/Caskroom/`? A bit more info would be helpful as I don't want to muck anything up. Thanks!

**Comment by jawshooah** [comment]
Yes, the simplest thing would be to `mv /opt/homebrew-cask/Caskroom /usr/local`. However, any casks installed prior to #13966 were symlinked rather than moved to their destinations, so you'll need to re-install those manually.

If we do wind up [phasing out `--caskroom`](https://github.com/caskroom/homebrew-cask/issues/21858), it won't be for a while, so you have plenty of time to find old casks and `brew cask install --force` them.

**Comment by vitorgalvao** [comment]
Closing the issue as it has been answered, but [making it the default to answer the questions that arise](https://github.com/caskroom/homebrew-cask/pull/21915).

If new questions come up, we should edit @jawshooah’s comment to make it clearer.

**Comment by tehmaspc** [comment]
I just re-installed one of my Caskroom apps and noticed that it was still installed to /opt/homebrew-cask/Caskroom? Doesn't seem like homebrew-cask is properly defaulting? I don't have any HOMEBREW_CASK_OPTS options set.

**Comment by msridhar** [comment]
@tehmaspc same for me; it was the `eclipse-java` app.  Re-installing other apps hasn't had the same problem thus far.

**Comment by tehmaspc** [comment]
Ah. I tested my `sonos` app. So there are individual casks that must be expecting /opt/homebrew-cask/Caskroom then.

**Comment by jawshooah** [comment]
#21901 changed the behavior to default to the old location if it still exists and print a warning about the new default, to mitigate the issues brought about by the original change. No need to change `HOMEBREW_CASK_OPTS` if you delete `/opt/homebrew-cask/Caskroom`.

**Comment by grootknol** [comment]
After receiving the warning, I've moved my Caskroom to `/usr/local/Caskroom`. Now `brew cask list` lists the installed casks but `brew cask uninstall` can't remove them.

```
➜  Casks git:(master) brew cask list
hazel					textmate
iterm2					the-unarchiver
java					transmission
jettison (!)				vagrant
macports				virtual box
mplayerx				virtualbox-extension-pack
source tree				vlc
stremio
➜  Casks git:(master) brew cask uninstall hazel
Error: hazel is not installed
➜  Casks git:(master) brew cask uninstall mplayerx
Error: mplayerx is not installed
```

**Comment by madsem** [comment]
@grootknol you have to brew cask install APP_NAME --force

**Comment by jawshooah** [comment]
@grootknol This is a result of a known issue with `brew cask list` (#14058). You have to `brew cask uninstall --force mplayerx`

**Comment by chrisfinazzo** [comment]
Good to know, I just hit this. Currently have no Casks installed, but will open a PR when BBEdit 11.6 gets released. Assuming that @jawshooah is correct in how this should be handled, is it worth adding a line to the output of `brew cask list` just to tell people 'here's what you need to do?'

**Comment by grootknol** [comment]
Could I just do `for cask in $(brew cask list) do; brew cask install $cask --force;` after moving Caskroom to the new directory?

**Comment by zanderzhng** [comment]
for me I did `find /usr/local/Caskroom -name "*.app" -maxdepth 3 -exec mv {} ~/Applications \;` after moving cask room and removing all the alias.

**Comment by herrbischoff** [comment]
@grootknol: Even simpler... `brew cask install --force $(brew cask list)`

**Comment by suhsteve** [comment]
something like this should work ```mv /opt/homebrew-cask/Caskroom /usr/local && find ~/Applications -type l -exec ls -l {} \; | grep "Caskroom" | sed -e 's/opt\/homebrew-cask/usr\/local/g' | tr -s '[:space:]' | cut -d' ' -f9- | awk 'BEGIN { FS = " -> " } ; { system("ln -sf \"" $2 "\" \"" $1 "\"") } '```

**Comment by n8henrie** [comment]
I had a *ton* of Casks that were still symlinked from `~/Applications` to `/opt/homebrew-cask/Caskroom`, so I first moved my Caskroom using the command above `mv /opt/homebrew-cask/Caskroom /usr/local` then changed all the symlinks to match the new location:

```bash
for f in ~/Applications/*.app; do oldloc="$(readlink "$f")"; [[ -e $oldloc ]] || ln -sf "/usr/local${oldloc#/opt/homebrew-cask}" "$f"; done
```

**Comment by jawshooah** [comment]
The solutions presented in this thread should work equally well for other symlinked artifacts, so I'm locking it. Feel free to open a new issue if you have trouble.
