### ISSUE TITLE
gamesalad fails to install

### ISSUE THREAD

**Issue by jhheider** [caskroom/homebrew-cask#21942]
GameSalad-Creator-1.24.42.dmg errors in Homebrew. Downloading the current 1.25.54 from gamesalad.com installs fine. The suggested fix doesn't change the issue. Output below.

`==> Downloading http://releases.gamesalad.com/creator/1.24.42/GameSalad-Creator-1.24.42.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask gamesalad
Error: invalid byte sequence in UTF-8
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/system_command.rb:151:in `_parse_plist'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/system_command.rb:126:in `plist'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/container/dmg.rb:38:in `mount!'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/container/dmg.rb:13:in `extract'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:119:in `extract_primary_container'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:74:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'`

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
