### ISSUE TITLE
Cask request: 4K Stogram 

### ISSUE THREAD

**Issue by kylesimmons** [caskroom/homebrew-cask#21943]
### Cask details

(Please fill out as much as possible)

**Name** - 4K Stogram

**Homepage** - https://www.4kdownload.com/products/product-stogram

**License** - Free

**Download URL** - https://downloads.4kdownload.com/app/4kstogram_2.0.dmg

**Description** - 4K Stogram is an Instagram Downloader for PC, Mac, and Linux. The program allows you to download and backup Instagram photos and videos, even from private accounts. Just enter an Instagram username or photo link and press 'Follow user' button. Open up wide new vistas of imagery all from your desktop. Try it!

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/21962
