### ISSUE TITLE
[Sierra] Installing apps distributed as zip does not work

### ISSUE THREAD

**Issue by roderik** [caskroom/homebrew-cask#21950]
I know it's beta1, and i know it's not supported, but i would however like to report it, seeing if someone might know a solution for the early adopters :)

```
Uh oh, could not figure out how to unpack '/Users/roderik/Library/Caches/Homebrew/keepingyouawake-1.4.0.zip'
Uh oh, could not figure out how to unpack '/Users/roderik/Library/Caches/Homebrew/atom-1.8.0.zip'
```

**Comment by droid-Q** [comment]
same issues,
`Error: Uh oh, could not figure out how to unpack '/Library/Caches/Homebrew/alcatraz-1.1.18.tar.gz'`

**Comment by vitorgalvao** [comment]
It’s still a developer preview. Until Sierra is at least a customer beta, it’s not worth wasting time on debugging it.

**Comment by zsprackett** [comment]
This hack worked for me:

diff --git a/lib/hbc/container/zip.rb b/lib/hbc/container/zip.rb
index 5425d7f..2d59064 100644
--- a/lib/hbc/container/zip.rb
+++ b/lib/hbc/container/zip.rb
@@ -1,6 +1,6 @@
 class Hbc::Container::Zip < Hbc::Container::Base
   def self.me?(criteria)
-    criteria.file.include? 'compressed-encoding=application/zip;'
+    criteria.file.include? 'compressed-encoding=application/zip;' or 'application/zip; charset=binary'
   end
 
   def extract

**Comment by claui** [comment]
@zsprackett Thanks for the pointer!
In the meantime, PR #22002 has emerged; it covers various cases, including the one handled in your Gist.
