### ISSUE TITLE
Can not Uncompress Zip or Tar files on macOS Sierra

### ISSUE THREAD

**Issue by jellyfishcoder** [caskroom/homebrew-cask#21969]
After installing macOS Sierra and migrating my cask room to /usr/local, when trying to install non-dmg apps, I get the following error: 
`Error: 
Uh oh, could not figure out how to unpack '/Users/Alexander/Library/Caches/Homebrew/atom-1.8.0.zip'`
Right after it says `==> Verifying checksum for Cask atom`
This happens on all zip and tar apps.

**Comment by jawshooah** [comment]
See #21950 (and please use the guidelines for reporting bugs in the readme next time :wink:)
