### ISSUE TITLE
What's the preferred method to upgrade apps with the recent changes?

### ISSUE THREAD

**Issue by blogabe** [caskroom/homebrew-cask#21966]
Trying not to re-start the upgrade conversation, but looking for some guidance given the recent changes.

I'm used to upgrading my versioned casks using:
```
for c in `brew cask list`; do ! brew cask info $c | grep -qF "Not installed" || brew cask install $c; done
```

All i had to do after that was delete the old version from `/opt/homebrew-cask/Caskroom/<Cask>/<Old Version>`

I've noticed this is no longer valie with the recent changes and moving the Cask to `/Applications`.

Is there a preferred method to upgrade versioned - read, not 'latest' - Casks?

Thank you!

**Comment by vitorgalvao** [comment]
As always, there is no official method to upgrade. Methods using `list` are particularly frowned upon.

Nothing changed in that regard.
