### ISSUE TITLE
Files left in Caskroom directories

### ISSUE THREAD

**Issue by ryankask** [caskroom/homebrew-cask#21983]
I've noticed that many casks leave what appear to be "junk" files in their Caskroom directories.

For example, after installing `intellij-idea`, I see the following files:

```
$ ls -la /opt/homebrew-cask/Caskroom/intellij-idea/2016.1.3
total 16
drwxr-xr-x 7 ryan staff  238 Jun 14 18:49 .
drwxr-xr-x 4 ryan staff  136 Jun 14 18:49 ..
drwx-wx-wx 2 ryan staff   68 Jun 14 18:49 .Trashes
drwxr-xr-x 3 ryan staff  102 Jun  3 18:14 .background
drwx------ 5 ryan staff  170 Jun  3 18:14 .fseventsd
lrwxr-xr-x 1 ryan staff   13 Jun 14 18:49 ' ' -> /Applications
-rw-r--r-- 1 ryan staff 8196 Jun  3 18:14 .DS_Store
```

google-chrome and firefox, for example, also have these files.

Are these leftovers after mounting a DMG? Should they be there or should homebrew-cask be cleaning them up?

**Comment by vitorgalvao** [comment]
> Are these leftovers after mounting a DMG?

Yes.

> Should they be there or should homebrew-cask be cleaning them up?

They should be there. Sometimes you might need them, and sometimes we might (uninstall scripts provided with the apps, for example).
