### ISSUE TITLE
Cask request: RDM

### ISSUE THREAD

**Issue by patresi** [caskroom/homebrew-cask#21986]
### Cask details

**Name** - RDM

**Homepage** - https://github.com/avibrazil/RDM

**License** - ???

**Download URL** - http://avi.alkalay.net/software/RDM/RDM-2.1.pkg

**Description** -  A tool that lets you use MacBook Pro Retina's highest and unsupported resolutions

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/22058
