### ISSUE TITLE
Error downloading carbon-copy-cloner (404)

### ISSUE THREAD

**Issue by mnetzwur** [caskroom/homebrew-cask#21987]
Hi there,

It appears that the carbon-copy-cloner cask is broken:

user@foobar:/Users/user$ brew cask install carbon-copy-cloner
==> Downloading http://bombich.com/software/files/ccc-4.1.8.4360.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'carbon-copy-cloner' with message: Download failed: http://bombich.com/software/files/ccc-4.1.8.4360.zip
The incomplete download is cached at /Users/user/Library/Caches/Homebrew/carbon-copy-cloner-4.1.8,4360.zip

It appears the most recent version is 4.1.9.4365.zip.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/21989
