### ISSUE TITLE
Feature request: Parallel downloads

### ISSUE THREAD

**Issue by jdfm** [caskroom/homebrew-cask#21992]
### Description of feature/enhancement

Currently brew-cask downloads packages one at a time, why not allow the downloads to run in parallel? Unless packages have dependencies on other packages, they could even be installed after they finish downloading while other downloads are still running as well.

### Justification

Some packages are very small, others are very large, the small packages, depending on the order they are specified, will be held up by the larger packages. Packages do not have central repositories, calibre, blender, and mactex, are all downloaded from different servers, so their download speeds will also vary between them, some slower, some faster. Being able to download the packages in parallel should save a lot of time in the end.

### Example use case

```sh
brew cask install mactex calibre blender
```

mactex is a very large package, like 5GB. Under the current version of brew-cask we have to wait until mactex finishes not only downloading but also installing for it to finally allow for the other packages to download, install, download and install. Here's what it looks like:

mactex starts downloading
mactex finishes downloading
mactex starts installing
mactex finishes installing
calibre starts downloading
calibre finishes downloading
calibre starts installing
calibre finishes installing
blender starts downloading
blender finishes downloading
blender starts installing
blender finishes installing

total_time = sum(download_times) + sum(install_times)

If we had parallel downloads:

```sh
brew cask install --parallel-download=2 mactex calibre blender
```

mactex starts downloading
calibre starts downloading
calibre finishes downloading
blender starts downloading
calibre starts installing
blender finishes downloading
calibre finishes installing
blender starts installing
mactex finishes downloading
blender finishes installing
maxtex starts installing
mactex finishes installing

total_time < sum(download_times) + sum(install_times)

**Comment by vitorgalvao** [comment]
Thank you for the detailed feature request. It is very much appreciated. However, I’ll have to close it. Reason we lean on homebrew a lot for our code, and [will do so more and more](https://github.com/caskroom/homebrew-cask/issues/14384). Translation: downloading isn’t exactly our domain. If you want this, it needs to be in homebrew, not homebrew-cask.

**Comment by ELLIOTTCABLE** [comment]
For anybody coming across this in the future: note homebrew/brew#1865 discusses adding this precise feature to Homebrew itself (which presumably, then, filter downstream to the Cask code.)
