### ISSUE TITLE
Error installing memoryanalyzer

### ISSUE THREAD

**Issue by sibelius** [caskroom/homebrew-cask#22011]
`brew cask install memoryanalyzer` works fine, but I receive this alert

The MemoryAnalyzer executable launcher was unable to locate its companion shared library.

**Comment by vitorgalvao** [comment]
We don’t alter the app, so the error is now related to us. Contact the developers of the app.

**Comment by angryz** [comment]
@sibelius  Same thing happens to me. Have you found how to resolve it?

**Comment by sibelius** [comment]
@angryz I've downloaded from eclipse website and it worked

**Comment by angryz** [comment]
@sibelius Thx :)
