### ISSUE TITLE
can not install audacity

### ISSUE THREAD

**Issue by zfbp** [caskroom/homebrew-cask#22021]
curl: (52) Empty reply from server
Error: Download failed on Cask 'audacity' with message: Download failed: http://app.oldfoss.com:81/download/Audacity/audacity_macosx_ub_2_1_2-1453294898.dmg

**Comment by claui** [comment]
Thank you for reporting.
That issue is already covered in #21952 and #22014. A fix is implemented and will be rolled out soon.

**Comment by claui** [comment]
@zfbp FYI – the fix has just been rolled out.
