### ISSUE TITLE
Make appdir available inside blocks

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#22024]
Currently we cannot use `appdir` inside [`*flight` blocks](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md). This leads to a messy mix of `appdir` and `Hbc.appdir`.

`appdir` should work everywhere inside casks.

Pinging @mwean since he made `appdir` available at first, but anyone should feel free to do it.

**Comment by mwean** [comment]
I'll take a look tonight
