### ISSUE TITLE
Use RuboCop to clean up core code

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#22038]
There have [been](https://github.com/caskroom/homebrew-cask/pull/22030/files/e9c070aa66948520cad3691f4329e520f4235121#r67411393) [some](https://github.com/caskroom/homebrew-cask/pull/22002/files#r67367740) [discussions](https://github.com/caskroom/homebrew-cask/pull/22002#issuecomment-226288282) [recently](https://github.com/caskroom/homebrew-cask/pull/16090/files#r67381226) regarding code style in the core, which is way past due for a cleanup. We already use RuboCop to enforce consistent style in Casks; we should do the same for our core code.

**Comment by reitermarkus** [comment]
I don't know if this is a RuboCop option, but [as you already mentioned](https://github.com/caskroom/homebrew-cask/pull/22002#issuecomment-226330849), `and` and `or` are confusing:

https://github.com/bbatsov/ruby-style-guide#no-and-or-or

**Comment by jawshooah** [comment]
It is indeed an option. We need to be careful about auto-correcting those though, since it could change the semantics.

**Comment by reitermarkus** [comment]
Should we also use RuboCop on test directories? Otherwise this issue could be closed, I think.

**Comment by jawshooah** [comment]
Yes, I'd like to run RuboCop on all Ruby sources in the repo ideally.

**Comment by jawshooah** [comment]
Done in #22041, #22464 and #22855.
