### ISSUE TITLE
Error: Uh oh, could not figure out how to unpack '/Library/Caches/Homebrew/malwarebytes-anti-malware-1.2.4.zip'

### ISSUE THREAD

**Issue by gjmveloso** [caskroom/homebrew-cask#22054]
Hi,

I'm trying to install MalwareBytes Anti-Malware on macOS Sierra Preview and I'm get the following error:

➜  ~ brew cask install malwarebytes-anti-malware 
==> Satisfying dependencies
complete
==> Downloading https://data-cdn.mbamupdates.com/v1/mbam-mac/data/mbam-mac-1.2.4
######################################################################## 100.0%
==> Verifying checksum for Cask malwarebytes-anti-malware
Error: Uh oh, could not figure out how to unpack '/Library/Caches/Homebrew/malwarebytes-anti-malware-1.2.4.zip'

**Comment by vitorgalvao** [comment]
[Multiple issues on this and a PR is being worked on](https://github.com/caskroom/homebrew-cask/search?q=sierra&type=Issues&utf8=%E2%9C%93).
