### ISSUE TITLE
Installation of Alfred 3.0.2_676 failed

### ISSUE THREAD

**Issue by teliatko** [caskroom/homebrew-cask#22056]
I'm getting following error when trying to install new version of Alfred:

```
$ brew cask install alfred
==> Downloading https://cachefly.alfredapp.com/Alfred_3.0.2_676.zip
Already downloaded: /Users/michal.bigos/Library/Caches/Homebrew/alfred-3.0.2_676.zip
==> Verifying checksum for Cask alfred
==> It seems there is already an App at '/Applications/Alfred 3.app'; not moving.
==> Enabling accessibility access
==> Print: Entry, "CFBundleIdentifier", Does Not Exist
Error: alfred: 'bundle_identifier' failed with: Command failed to execute!

==> Failed command:
["/usr/libexec/PlistBuddy", "-c", "Print CFBundleIdentifier", "#<Pathname:/Applications/Alfred 3.app/Contents/Info.plist>"]

==> Output of failed command:
File Doesn't Exist, Will Create: /Applications/Alfred 3.app/Contents/Info.plist


==> Exit status of failed command:
#<Process::Status: pid 86430 exit 1>
```

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by teliatko** [comment]
@vitorgalvao I've edited issue to be in compliance with *reporting bugs* template. Any other wishes?

**Comment by vitorgalvao** [comment]
Try with `--force`.

**Comment by teliatko** [comment]
It works.

**Comment by vitorgalvao** [comment]
Good to know. Thank you for reporting back.

**Comment by teliatko** [comment]
Off record, how did you analysed that issue. I just want to avoid to spam
in the future. If there is any rule of thumb as "always use -- force" it is
acceptable, but one just have to know.

On Mon, Jun 20, 2016 at 11:05 PM, Vítor Galvão <notifications@github.com>
wrote:

> Good to know. Thank you for reporting back.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/caskroom/homebrew-cask/issues/22056#issuecomment-227269322>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAOzcFoC4P1fUXptbbmutDLqAH5JdNrkks5qNwCdgaJpZM4I4XPs>
> .
>



-- 
'(")'~

**Comment by vitorgalvao** [comment]
From your top post:

```
==> It seems there is already an App at '/Applications/Alfred 3.app'; not moving.
```

That was the problem. By default we don’t overwrite, but with `--force` we do.
