### ISSUE TITLE
Widget installation doesn’t work

### ISSUE THREAD

**Issue by niksy** [caskroom/homebrew-cask#2206]
As I can see, there is currently only one widget available in the list of casks (Delivery Status) so I can’t say if this is related to only Delivery Status.

There are currently two errors regarding widget installation which I’ve encountered:

* If there is no Widgets directory in users Library folder, installation will fail—this was already reported in #2133 .
* If the widget gets installed, it isn’t available in the list of all widgets and when you try to manually add it by activating .wdgt file via standard procedure (e.g. double click on icon), OSX reports that there is already newer version of this widget and offers you to cancel installation or replace it. If you replace it, widget gets installed, but it replaces symlink inside Widgets folder. My thinking is that OSX thinks symlink and original file are same files and replaces the other one with the one you activated. Maybe symlinking is not ideal in this situation? Maybe just activate widget upon installation?

**Comment by vitorgalvao** [comment]
Widgets [have been removed](https://github.com/caskroom/homebrew-cask/pull/8736) as per #7826. Does anyone care about widgets, really, or can we remove support for them from homebrew-cask?

cc @caskroom/maintainers.

**Comment by nanoxd** [comment]
At this point, with the lack of focus on current OS's, it makes sense to remove it entirely.

**Comment by phinze** [comment]
Agreed. Let's rip it out and then we can close this out. :+1:

**Comment by phinze** [comment]
(p.s. I just want to acknowledge that I accidentally typed "out" twice in a row and it sounded weird. :penguin: )
