### ISSUE TITLE
kext artifact stanza

### ISSUE THREAD

**Issue by benwa** [caskroom/homebrew-cask#22159]
I'm writing a [HWSensors](http://hwsensors.com) formula and currently using the `artifact` stanza to copy kexts to `/System/Library/Extensions/`.  In order to properly install a kext, you must also perform some system commands.
It would be nice if there was a `kext` artifact stanza to handle this similar to the `kext` uninstall stanza.

On a sidenote, HWSensors is another good use case for #10137.

**Comment by vitorgalvao** [comment]
Thank you for the request, but next time please [use the template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat).

Adding a new artifact for a single cask is not at all a good use case. Copying kexts is definitely not common behaviour. Does that even work in El Capitan? Why is it not implemented as a `pkg`?

Either way, install stanzas also don’t include further install options, so you’re asking for us to make a new stanza for a single cask that has extra functionality compared to its siblings.

There’s no point to it.

**Comment by benwa** [comment]
Sorry about the template, I've updated the post.

Just copying the kext isn't enough no, there is more processing required after.  HWSensors in particular does also have a `pkg`, however it is optional to do so (which it should be).  Since it isn't yet possible to pass `-applyChoiceChangesXML` to `installer`, this was a sort of workaround idea.

I agree this is pretty edge casey, there are only a handful of projects that I can think of that ship kexts without a `pkg`.
