### ISSUE TITLE
Unable to complete installation of racket

### ISSUE THREAD

**Issue by koyedele** [caskroom/homebrew-cask#22152]
I moved my Caskroom location as suggested by @jawshooah in https://github.com/caskroom/homebrew-cask/issues/21913#issuecomment-225585378 and it worked for a number of my apps. Doing an `install --force` fixed the rest, but racket has been quite a pain.  
First, I didn't realize that racket files were symlinked into `/usr/local/bin` and after `mv`ing `/opt/homebrew-cask/Caskroom` to `/usr/local`, I ended up with a bunch of broken symlinks which I didn't notice for about 30 minutes (that's my fault though).  
Anyways, the current issue is that I removed racket completely from my computer and tried to reinstall. Here's what I get:  
```
$ brew cask install racket --verbose
 ==> Downloading https://mirror.racket-lang.org/releases/6.5/installers/racket-6.5-x86_64-macosx.dmg
 Already downloaded: /Users/kunle/Library/Caches/Homebrew/racket-6.5.dmg
 ==> Verifying checksum for Cask racket
 ==> Moving App Suite 'Racket v6.5' to '/Applications/Racket v6.5'
 Error: It seems the symlink source is not there: '/usr/local/Caskroom/racket/6.5/Racket v6.5/bin/drracket'
 Error: Kernel.exit
```  
In truth, when I go to `/usr/local/Caskroom`, there is no `racket`. This leads me to believe that the download and unpacking of the installer is happening somewhere other than `/usr/local/Caskroom/racket`. Any ideas on how to proceed? For completeness, the `Racket v6.5` folder shows up in my `Applications` folder but I can't access any of the commands from the command line.

**Comment by jawshooah** [comment]
> In truth, when I go to `/usr/local/Caskroom`, there is no `racket`

This is expected. When the install fails, we back out and remove all staged files (downloaded files remain cached, though).

#22153 will fix the broken symlinks.

**Comment by koyedele** [comment]
Thanks! You guys rock! :)
