### ISSUE TITLE
Get rid of `$(brew --cache)/Casks` dir and symlinks?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#22168]
Currently, we download the target of `url` to `$(brew --cache)` and also set a symlink to it in `$(brew --cache)/Caskroom`. That last directory and symlink seem a bit useless. Furthermore, the interaction is broken, since if `$(brew --cache)/Casks` does not exist (somewhat common if you `rm "$(brew --cache)"` regularly) HBC blows up and gives an error about the file not being there, since we’re not creating the directory.

Steps to reproduce the error:

1. `rm -rf "$(brew --cache)/Casks"`
2. `brew cask fetch alfred`
3. Boom (`Error: No such file or directory` …)

Even if not getting rid of the interaction, we need to be sure to always create `$(brew --cache)/Casks` when downloading a cask.

**Comment by reitermarkus** [comment]
I agree that this is useless, as the symlinks only link to a file in the parent directory. Are these symlinks even used for anything?

**Comment by vitorgalvao** [comment]
> Are these symlinks even used for anything?

I’m not sure if we use them internally for something. If not, it’ll be a simple matter to get rid of them.

**Comment by reitermarkus** [comment]
You have a typo in the post above, it is actually `$(brew --cache)/Casks`.

**Comment by vitorgalvao** [comment]
You’re right. Fixed.

**Comment by reitermarkus** [comment]
In `Hbc::Download`, there is this comment:

```ruby
# this symlink helps track which downloads are ours
```

And indeed, this is true. In addition, the symlink is used to check for `.incomplete` cache files.

**Comment by vitorgalvao** [comment]
> # this symlink helps track which downloads are ours

Ah, yes, I remember seeing that in the past.

On the other hand, is it really necessary? Homebrew doesn’t check which downloads are exclusively theirs nor needs symlinks, and they do just fine.

**Comment by reitermarkus** [comment]
Well, as long as there are no Formulas and Casks with exactly the same name, version and file extension, we don't need the symlinks. And even if, it's *just* a cache directory, so I think people shouldn't depend on it.

**Comment by adidalal** [comment]
I'm fine with blowing it away. Maybe `brew cask list` might rely on it, but that's quite a broken mess, anyway.

**Comment by vitorgalvao** [comment]
Seems like there are no problems with getting rid of the directory. No longer a discussion but something to implement. Closing in favour of https://github.com/caskroom/homebrew-cask/issues/22727.
