### ISSUE TITLE
xquartz install doesnt work.

### ISSUE THREAD

**Issue by armandology** [caskroom/homebrew-cask#22204]
fluid:Caskroom armando$ brew cask install xquartz
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.9.dmg

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'xquartz' with message: Download failed: https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.9.dmg
The incomplete download is cached at /Users/armando/Library/Caches/Homebrew/xquartz-2.7.9.dmg

**Comment by vitorgalvao** [comment]
Same thing happens [on the website](https://www.xquartz.org/). Please contact them.

**Comment by armandology** [comment]
it works now, I guess they fixed the download issues on their website.

Thanks
