### ISSUE TITLE
Verify sling `url` (need maintainer in the US)

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#22210]
As part of https://github.com/caskroom/homebrew-cask/issues/19450, I’m trying to verify [`sling`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sling.rb).

However, I can’t:
![image](https://cloud.githubusercontent.com/assets/1699443/16178708/e1e550dc-3647-11e6-9694-2cfde21de53f.png)

Need a maintainer in the US to please do that.

**Comment by claui** [comment]
![image](https://cloud.githubusercontent.com/assets/1239874/16179638/8d304c80-366b-11e6-92e0-0f9ef670304c.png)

Not from the US, but thanks to _Private Tunnel_ I was able to verify that

> http://webapp.movetv.com/player/osx/slingtv.dmg

is indeed the official download URL.

**Comment by vitorgalvao** [comment]
Thank you! Updated the cask.
