### ISSUE TITLE
borg: permission issue on OS X

### ISSUE THREAD

**Issue by ctourner** [caskroom/homebrew-cask#22266]
When installing the borgbackup cask, the borg binary is installed with permissions 0744. As a result, other users on the system can't use borg.

I don't see any permission being set in `borgbackup.rb`. So could this be an issue while building or packaging borg?

OS X: 10.11.5, borg: 1.0.3

**Comment by vitorgalvao** [comment]
We don’t change permissions. I means the package comes with those. I see no reason to change them if the developer set them that way, as it does not hinder our ability to install.

You either change them yourself or ask the developer to change them upstream.

**Comment by ctourner** [comment]
When installing borg "manually" the permissions are always 0755. I tried borg v1.0.3 using pip (source and binary packages), and directly from the git repository.

So it may be a packaging issue while creating the cask. Maybe a umask set on the machine used to create it. Is the cask done by someone on the homebrew team or the borg backup team?

**Comment by vitorgalvao** [comment]
There’s no “machine set to create the cask”, the cask directly downloads the git release and makes no changes to it. Just checked it, and the permissions were the same.
