### ISSUE TITLE
Error: Permission denied - (/usr/local/Caskroom/vienna/3.1.5/Vienna.app, /Applications/Vienna.app)

### ISSUE THREAD

**Issue by faxotherapy** [caskroom/homebrew-cask#22274]
Hello,
I just write to let you know that there still exists people who do not use the admin session and are logged under a regular account. So, would it be possible to no longer have such a message and allow users to link in an elegant fashion way from, say, the local app folder. Otherwise, I keep getting this message. Or, just ask my admin password so I can interact with the root app folder… I would prefer not to use `sudo` when (force) upgrading a package: `brew cask install --force vienna`

Thank you.

**Comment by faxotherapy** [comment]
It seems that I am now unable to upgrade my package. I keep getting this message. I did the following command: `brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup` but with no effect. Should I run it from my admin account? Is this the problem? With previous version of Cask, I was able to upgrade from my regular account and link to the local app folder with no problem?
```
★  brew cask install --force vienna
==> Downloading https://dl.bintray.com/viennarss/vienna-rss/Vienna3.1.5.tar.gz
Already downloaded: /Users/Nathalie/Library/Caches/Homebrew/vienna-3.1.5.tar.gz
==> Verifying checksum for Cask vienna
==> Moving App 'Vienna.app' to '/Applications/Vienna.app'
Error: Permission denied - (/usr/local/Caskroom/vienna/3.1.5/Vienna.app, /Applications/Vienna.app)
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:50:in `move'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:26:in `block in install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:43:in `block in each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:22:in `install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:129:in `block in install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
```

**Comment by vitorgalvao** [comment]
We no longer link. For your problem, see the linked issue in your duplicate post.

**Comment by faxotherapy** [comment]
After check, I realised that I have to `sudo` a package upgrade. It's quite a bit strange that Homebrew is laid out so we don't need to enter `sudo` every time, but in the case of Cas, we have to `sudo` ; there's a bit of inconsistency. The package upgrade should be run as `brew cask install --force vienna` without the need to `sudo`.

**Comment by vitorgalvao** [comment]
You don’t have to `sudo`. Check your permissions.

**Comment by faxotherapy** [comment]
OK, then. Could you please tell my the permissions so I can compare. Thanks for your help.

**Comment by vitorgalvao** [comment]
If you can’t install to that directory, there’s nothing we can do. Use [`—appdir`](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options) to install somewhere else.

**Comment by claui** [comment]
> With previous version of Cask, I was able to upgrade from my regular account and link to the local app folder with no problem.

@faxotherapy Previous versions of Homebrew-Cask used the `~/Applications` folder by default (below your home directory). You can use `--appdir=~/Applications` to bring back that old behavior.

To make this option permanent, [follow the _Options_ section in USAGE.md](https://github.com/caskroom/homebrew-cask/blob/1de4657a0ed35463602b31061b0c16dc9078b8a0/USAGE.md#options).

**Comment by faxotherapy** [comment]
OK. Fixed thanks to your suggestions. Thanks very much for your prompt support. Have a great day.

**Comment by BevisssLiu** [comment]
change the permission of /Users/username/Library/Caches/Homebrew/Cask by GUI.
1. open this folder 
2. right click and chose "get info"
3. go to "Sharing & Permissions"
4. change Privilige to "Read & Write"
5. do again

**Comment by claui** [comment]
@BevisssLiu Thanks for sharing this tip. Please mind that this thread is about **an unrelated issue** – what you wrote is therefore likely not going to be noticed much.

We [do have documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) in place [for troubleshooting](https://github.com/caskroom/homebrew-cask/blob/master/README.md#reporting-bugs) that has stood the test of time; it is also supposed to fix any cache-related problem. In case it doesn’t work for you, feel free to open a separate issue.
