### ISSUE TITLE
Cask "Flux" does not pass checksum

### ISSUE THREAD

**Issue by sgsunder** [caskroom/homebrew-cask#22288]
Result of attempting to install flux (`brew cask install flux`):

`Error: sha256 mismatch`
`Expected: 4fdcbf481b96e1bcda637956269c61791158183c3e0c035460a091eb3d3219d3`
`Actual: aaa1bc7533d487993f8b5ade5de2fd85adf7f398a0800c456286d11d88753752`

The error reoccurs even after running `brew update` and deleting the existing download.

**Comment by gsmoraes** [comment]
Manually downloading and running the sha256sum yields the same result: `aaa1bc7533d487993f8b5ade5de2fd85adf7f398a0800c456286d11d88753752`

Seems like the version was updated to 37.1, according to https://justgetflux.com/mac/macflux.xml.

**Comment by victorpopkov** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/22290.
