### ISSUE TITLE
Cask request: Docker for Mac

### ISSUE THREAD

**Issue by SimenB** [caskroom/homebrew-cask#22281]
### Cask details

A version of Docker much more integrated into the OS than the normal Docker Toolbox, not requiring VirtualBox.

See https://blog.docker.com/2016/06/docker-mac-windows-public-beta/
https://www.docker.com/products/docker#/mac

**Name** -
Docker for Mac public beta

**Homepage** -
https://www.docker.com/

**License** -
Apache License 2.0

**Download URL** -
https://download.docker.com/mac/beta/Docker.dmg

**Description** -

**Comment by vitorgalvao** [comment]
Does it still require a beta key?

**Comment by SimenB** [comment]
Nope, public beta (as per included blog post from today)

**Comment by metyl** [comment]
Since it is still beta maybe it should go to [caskroom/versions](https://github.com/caskroom/homebrew-versions) ?

**Comment by vitorgalvao** [comment]
@metyl [No](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/22282.
