### ISSUE TITLE
Spelling dictionaries support?

### ISSUE THREAD

**Issue by niksy** [caskroom/homebrew-cask#2229]
Anyone has experience with installing custom spelling dictionaries? According to this [StackExhange answer](http://apple.stackexchange.com/a/11842/26182), it’s a simple c/p to `~/Library/Spelling` folder and dictionary should be available. So, symlink should probably work.

And apparently OpenOffice dictionaries are perfectly supported ([list of available dictionaries](http://extensions.services.openoffice.org/en/search?f[0]=field_project_tags%3A157)).

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. We’ll entertain a PR, though.
