### ISSUE TITLE
About Spotlight

### ISSUE THREAD

**Issue by senpng** [caskroom/homebrew-cask#22317]
I opened the App are using Spotlight.
I moved /opt/homebrew-caskroom to /usr/local/caskroom，After，I rebuild the Spotlight index.
Spotlight can not search cask installed app。I tried a lot of methods are useless。
Is there any solution?

In addition to modifying caskroom

**Comment by vitorgalvao** [comment]
Spotlight doesn’t index `/usr/local/`, that why we started using `/opt` in the first place. Reinstall your apps with `--force` and they’ll be moved (our new behaviour). Spotlight will see them then.

**Comment by cd-rum** [comment]
This should be included in the `README.md` _for sure_.

**Comment by cd-rum** [comment]
@vitorgalvao For my clarification how is it no longer relevant? I'd all but given up on this repo solely because Spotlight couldn't find the apps it installs.

**Comment by vitorgalvao** [comment]
@cd-rum Apps are moved by default directly to `/Applications`, as if you’d done it manually.

If they’re not or they are and Spotlight isn’t seeing them, the issue is on your side.

**Comment by cd-rum** [comment]
@vitorgalvao Ah, that's fair. Thanks for the info.
