### ISSUE TITLE
Still installing to /opt/homebrew-cask/Caskroom

### ISSUE THREAD

**Issue by timmolter** [caskroom/homebrew-cask#22359]
After seeing the warning, I migrated all apps to ` /usr/local`.
```
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location, or if you would like to keep your
Caskroom at /opt/homebrew-cask/Caskroom, add the following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom
```
But installing new apps is still installing in the old location.

    libreoffice staged at '/opt/homebrew-cask/Caskroom/libreoffice/5.1.4

Either this is a bug or I'm too dumb to update homebrew properly. Any ideas?

**Comment by vitorgalvao** [comment]
That means `/opt/homebrew-cask` still exists. It’s the only check that is made. Delete that directory completely.

**Comment by timmolter** [comment]
You might want to add that to the message about migrating.
