### ISSUE TITLE
Tuneup installs malware

### ISSUE THREAD

**Issue by decorate** [caskroom/homebrew-cask#22375]
`brew cask install tuneup`

While it does not automatically install the .dmg, the downloaded installer will install malware even if the embedded offer is declined. It automatically opens browsers (Safari, Chrome at least) to change the start page and install an extension called "Internet Assistant 81".

I ended up resetting Safari and Chrome as I was unsure what it changed. Could this cask be considered for removal.

**Comment by adidalal** [comment]
See adware-laden cask discussion at https://github.com/caskroom/homebrew-cask/issues/21399.

Feel free to add thoughts there or here

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/22383/

@decorate We’re still discussing the approach, but if approved, you’ll need to do the outlined steps, including reporting the app to Apple. You may wish to do that either way.

**Comment by decorate** [comment]
@vitorgalvao Thank you so much for the follow-up. I am now reporting the app in question. Your approach to solving the problem is excellent and saves the burden of policing from the cask community while still taking some direct action to solve the problem upstream.

**Comment by decorate** [comment]
https://openradar.appspot.com/27013246
