### ISSUE TITLE
launchpad have no iterm2

### ISSUE THREAD

**Issue by zdrjson** [caskroom/homebrew-cask#22377]
➜  ~ brew cask install iterm2 --force
==> Satisfying dependencies
complete
==> Downloading https://iterm2.com/downloads/stable/iTerm2-2_1_4.zip
Already downloaded: /Users/json/Library/Caches/Homebrew/iterm2-2.1.4.zip
==> Verifying checksum for Cask iterm2
==> It seems there is already an App at '/Applications/iTerm.app'; overwriting.
==> Removing App: '/Applications/iTerm.app'
==> Moving App 'iTerm.app' to '/Applications/iTerm.app'
🍺  iterm2 staged at '/usr/local/Caskroom/iterm2/2.1.4' (0B)

It seems to be OK，I try lots of times,Finder have it.
but launchpad have no iterm2 icon,other app don't have this problem,
hey guys,how I can fix it?

**Comment by vitorgalvao** [comment]
We don’t touch Launchpad at all, we just move the app. You’ll need to find the answer somewhere else.
