### ISSUE TITLE
brew search doesn't use HOMEBREW_GITHUB_API_TOKEN when searching casks

### ISSUE THREAD

**Issue by patresi** [caskroom/homebrew-cask#22417]
When using simply ```brew search something```, brew automatically also searches available casks. The problem is that sometimes an error occurs when it gets to the searching casks part:
```
$ brew search something
No formula found for "something".
==> Searching pull requests...
Error: GitHub API Error: API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 55 minutes 9 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
```
This happens even though the HOMEBREW_GITHUB_API_TOKEN variable is set.

Using ```brew cask search something``` has no problem searching through the available casks.

**Comment by adidalal** [comment]
Should be reported to homebrew, not us
