### ISSUE TITLE
[request] Update FromScratch

### ISSUE THREAD

**Issue by Kilian** [caskroom/homebrew-cask#22424]
Hi guys, FromScratch is currently at 1.1.1, but homebrew cask still has 1.0.1: https://github.com/caskroom/homebrew-cask/blob/master/Casks/fromscratch.rb I'd update it myself, but I'm on linux so can not run the appropriate scripts.

### Cask details

**Name** - FromScratch

**Homepage** - https://fromscratch.rocks/

**License** - MIT

**Download URL** - https://github.com/Kilian/fromscratch/releases/download/v1.1.1/FromScratch-darwin-x64-1.1.1.zip

**Description** - Auto-saving scratchpad

**Appcast** https://github.com/Kilian/fromscratch/releases.atom

**Comment by victorpopkov** [comment]
Done in https://github.com/caskroom/homebrew-cask/pull/22426.
