### ISSUE TITLE
Move Brew Cask ZSH Completions between projects

### ISSUE THREAD

**Issue by joshka** [caskroom/homebrew-cask#22434]
Hiya,

Currently the zsh completions for brew cask are [a plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/brew-cask) for oh-my-zsh. I use [pretzo](https://github.com/sorin-ionescu/prezto) rather than oh-my-zsh. Hence I've moved the zsh completions over to the [zsh-completions](https://github.com/zsh-users/zsh-completions) project.

I also updated the available commands, based on the current version of brew-cask and simplified the existing completion script.

See related PRs:
https://github.com/zsh-users/zsh-completions/pull/430
https://github.com/robbyrussell/oh-my-zsh/pull/5191
https://github.com/Homebrew/brew/pull/407

Now, it's possible that perhaps the completions belong in this repo (homebrew-cask), but I couldn't think of an easy way to install them when you install homebrew cask. If there's an obvious way that this can work please someone point it out.

**Comment by joshka** [comment]
Also of note is that originally, this did exist in zsh-completions in the _brew completion, but that got deprecated in favor of the installed version in homebrew (that didn't contain the brew cask completions).

**Comment by vitorgalvao** [comment]
Completions belong in other projects. We purposefully do things this way. This does not mean we don’t contribute to those projects (I’ve personally done corrections in the past) but we don’t host them.

See https://github.com/caskroom/homebrew-cask/pull/13785#issuecomment-141844184.

**Comment by joshka** [comment]
Thanks. I didn't know about the homebrew completions repository. Perhaps that's the best place for this? This was mostly a FYI issue btw / an ask on sanity check.

**Comment by vitorgalvao** [comment]
We used to tell you how to install completions at install time, before we were auto-installed by homebrew.
