### ISSUE TITLE
Cask request:

### ISSUE THREAD

**Issue by senpng** [caskroom/homebrew-cask#22440]
### Cask details

(Please fill out as much as possible)

**Name** - Docker

**Homepage** - https://docs.docker.com/

**License** -

**Download URL** - https://download.docker.com/mac/beta/Docker.dmg

**Description** -

**Comment by vitorgalvao** [comment]
Docker is already present: [docker.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/docker.rb).
