### ISSUE TITLE
Package appears as installed but it is not

### ISSUE THREAD

**Issue by jommgoncalves** [caskroom/homebrew-cask#22487]
> bash-3.2$ brew cask list
> flash-player		    iterm2-beta			mou			    sublime-text		vlc
> google-chrome		    java			pgweb			    virtualbox			xquartz
> intellij-idea-ce	    libreoffice			pycharm-ce		    virtualbox-extension-pack

> bash-3.2$ brew cask info pycharm-ce
> pycharm-ce: 2016.1.4
> Jetbrains PyCharm Community Edition, PyCharm CE
> https://www.jetbrains.com/pycharm
> Not installed
> https://github.com/caskroom/homebrew-versions/blob/master/Casks/pycharm-ce.rb
> ==> Contents
>   PyCharm CE.app (app)

> bash-3.2$ brew cask remove pycharm-ce
> Error: pycharm-ce is not installed

**Comment by blogabe** [comment]
try ```brew cask remove --force pycharm-ce```

**Comment by jommgoncalves** [comment]
It works! Thanks a lot!
