### ISSUE TITLE
Can find brew cask on github but not brew cask install or search

### ISSUE THREAD

**Issue by sigurdurb** [caskroom/homebrew-cask#22504]
I can find the newest version of "keypassx" on the master github https://github.com/caskroom/homebrew-cask/blob/master/Casks/keepassx.rb

but when I try

```sh
~$ brew cask search keypassx
No Cask found for "keypassx".

~$ brew cask install keypassx
Error: No available Cask for keypassx
Error: nothing to install
```
I already tried update and brew uninstall --force brew-cask && brew tap caskroom/cask
I can only get this ancient version of keypassx that I found by googling https://github.com/caskroom/homebrew-cask/blob/master/Casks/dwihn0r-keepassx.rb

Does anybody know the issue?

**Comment by vitorgalvao** [comment]
It’s `keepassx`. You’re writing `keypassx`.
