### ISSUE TITLE
Cask request: DrawBot

### ISSUE THREAD

**Issue by johndjameson** [caskroom/homebrew-cask#22503]
### Cask details

**Name** - DrawBot

**Homepage** - http://www.drawbot.com/

**License** - [The BSD License](https://github.com/typemytype/drawbot/blob/master/license.txt)

**Download URL** - http://static.typemytype.com/drawBot/DrawBot.dmg

**Description** - “DrawBot is a powerful, free application for MacOSX that invites you to write simple Python scripts to generate two-dimensional graphics. The builtin graphics primitives support rectangles, ovals, (bezier) paths, polygons, text objects and transparency.”

**Comment by adidalal** [comment]
version: `3.82`

appcast: `https://raw.githubusercontent.com/typemytype/drawbot/master/drawBotSettings.py`

**Comment by adidalal** [comment]
Closed in https://github.com/caskroom/homebrew-cask/issues/22519
