### ISSUE TITLE
New install directory, is the vagrant install working properly?

### ISSUE THREAD

**Issue by badlydrawnrob** [caskroom/homebrew-cask#22513]
I've been following the [directions here](https://github.com/caskroom/homebrew-cask/issues/21913) to migrate to the new install location, but want to make it's doing what it should. Performed a `brew cask uninstall --force vagrant; brew cask install --force vagrant`, as well as the [pre bug reporting](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) commands.

I'm seeing vagrant files in both `/opt` and `/usr/local`:

     opt/
       vagrant/
          bin/   embedded/

     usr/local/
        Caskroom/
           vagrant/
              1.8.4/

I expected everything to be migrated over into `usr/local`, or is that not the case?

**Comment by vitorgalvao** [comment]
Notice how you’re seeing `/opt/vagrant` and not `/opt/homebrew-cask/Caskroom/vagrant`. `/opt/vagrant` is created by the `vagrant` installation, and unrelated to us.

**Comment by badlydrawnrob** [comment]
Ah, ok @vitorgalvao ... that's good to hear!! I hadn't dug around the file system before the move to the new `/opt/homebrew-cask` location. Thanks for clearing that up 👍
