### ISSUE TITLE
Cannot uninstall sublime-text3 (!)

### ISSUE THREAD

**Issue by laris** [caskroom/homebrew-cask#22518]
laris@bogon:~|⇒  brew cask list|grep sublime
sublime-text3 (!)
laris@bogon:~|⇒  brew cask uninstall "sublime-text3 (!)"
zsh: event not found: )
laris@bogon:~|⇒  brew cask uninstall 'sublime-text3 (!)'
Error: No available Cask for sublime-text3 (!)
laris@bogon:~|⇒  brew cask uninstall sublime-text3\ \(\!\)       
Error: No available Cask for sublime-text3 (!)
laris@bogon:~|⇒ brew cask uninstall `brew cask list|grep sublim`
Error: No available Cask for (!)

laris@bogon:~|⇒ brew cask info sublime-text                     
sublime-text: 3114
Sublime Text
https://www.sublimetext.com/3
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/sublime-text.rb
==> Contents
  Sublime Text.app (app)
  /Applications/Sublime Text.app/Contents/SharedSupport/bin/subl (binary)
==> Caveats
Cask sublime-text installs files under "/usr/local".  The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in homebrew-cask.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/issues/2988

Use --force

Follow reporting bugs guide, next time
