### ISSUE TITLE
Unable to unpack blender-2.77a.zip

### ISSUE THREAD

**Issue by lytzen** [caskroom/homebrew-cask#22580]
# brew cask install blender --verbose
~/> brew cask install blender --verbose
==> Downloading https://download.blender.org/release/Blender2.77/blender-2.77a-OSX_10.6-x86_64.zip
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-648) https://download.blender.org/release/Blender2.77/blender-2.77a-OSX_10.6-x86_64$
zip -C 0 -o /Users/mlh/Library/Caches/Homebrew/blender-2.77a.zip.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  158M  100  158M    0     0   320k      0  0:08:26  0:08:26 --:--:--  239k
==> Verifying checksum for Cask blender
Error: Uh oh, could not figure out how to unpack '/Users/mlh/Library/Caches/Homebrew/blender-2.77a.zip'
Error: Kernel.exit

# brew doctor
~/> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

# brew cask doctor
~/> brew cask doctor
==> macOS Release:
10.12
==> macOS Release with Patchlevel:
10.12
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 59074e; last commit 2016-07-04)
Homebrew/homebrew-core (git revision f8a5; last commit 2016-07-04)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision 825b5; last commit 38 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/usr/local/Caskroom
==> Homebrew-cask Cached Downloads:
/Users/mlh/Library/Caches/Homebrew
/Users/mlh/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3217
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/psych-2.0.17/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/mlh/Library/Haskell/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/sbin:/usr/
local/opt/ruby/bin:/Users/mlh/scripts:/usr/local/opt/fzf/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/s
cm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_GB.UTF-8"
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No

# Comment
I hope this issue will be addressed, even though I am running an unsupported version of OSX. If not, I understand.

**Comment by vitorgalvao** [comment]
You need to follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide.

More importantly, you need to search. [This is being addressed](https://github.com/caskroom/homebrew-cask/pull/22002).
