### ISSUE TITLE
Cask request: MJML

### ISSUE THREAD

**Issue by blaugueux** [caskroom/homebrew-cask#22602]
### Cask details

**Name** - MJML

**Homepage** - https://mjml.io/

**License** - MIT

**Download URL** - https://mjmlio.github.io/mjml-app/ (https://github.com/mjmlio/mjml-app/releases/download/1.4.0/mjml-app-osx.dmg)

**Description** - Tool to create responsive email.

**Comment by adidalal** [comment]
There's no Mac binary I can see linked from the download page.

Install with `npm install mjml`

**Comment by blaugueux** [comment]
Sorry, wrong link https://mjmlio.github.io/mjml-app/

**Comment by adidalal** [comment]
`brew cask install mjml`

**Comment by blaugueux** [comment]
Thanks 👍
