### ISSUE TITLE
flux - sha256 mismatch

### ISSUE THREAD

**Issue by alias1** [caskroom/homebrew-cask#22618]
```
devalias@nyxaevum:~/Applications|⇒  brew cask install flux
==> Downloading https://justgetflux.com/mac/Flux.zip
######################################################################## 100.0%
==> Verifying checksum for Cask flux
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: db2093498c916f315b6fada84fc85a0713329907367a9227f7f959e44790c700
Actual: 8dd9cac699146971616817f1c8866ed26c8fde7724deb81ed63b406372ad93e3
File: /Library/Caches/Homebrew/flux-37.2.zip
To retry an incomplete download, remove the file above.
```

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide.

When you opened this issue, the template in place even urged you to do so and gave you the relevant links.

If you will not spend the time to open an issue correctly, we will not spend the time to look at it. We spend hours every day to deal with non-trivial amounts of issues and pull requests and improve this project you use for free; the least you can do is spend a few minutes to make a correct report. Please respect our time.

This is pre-written text, and it is in no way said in anger. If I made a mistake in closing the issue, I ask that you correct me. I will reopen it and we can continue the discussion.

If, however, you have indeed not paid the due attention to the guide, go back and do. We will be waiting for your new properly formatted issue that will have most (if not all) the necessary details required for us to help you. With a little luck, you won’t even need to open a new issue (the instructions to report bugs include a lot of fixes for common problems).

Finally, if it was the guide itself that was unclear, make a new pull request with your suggestions on how to improve it.

Thank you. Have a good day.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/22621
