### ISSUE TITLE
Install both 'rstudio' and 'rstudio-preview'?

### ISSUE THREAD

**Issue by kenahoo-windlogics** [caskroom/homebrew-cask#22611]
Previously I've had both `rstudio` and `rstudio-preview` casks installed on my machine and I could switch back & forth between them at will (e.g. by having 2 aliases in my dock) or run both at once.  The apps themselves don't mind this setup at all.

I just updated my setup and noticed that the `rstudio-preview` cask is now moving 'RStudio.app' to `/Applications`, rather than symlinking it to `~/Applications` (which I understand is on purpose, having seen [but not necessarily understood!  It's so long!] issue #13201).  The problem is that the `rstudio` cask is also going to try to occupy that same `/Applications/RStudio.app` real estate.

What would be a good strategy for managing these two casks now?  For example, can I get `rstudio` to install to `/Applications`, and `rstudio-preview` to install to `~/Applications`?  Is that even a good idea?  What will happen when I do upgrades?

Thanks.

**Comment by adidalal** [comment]
To do what you wanted:

```
brew cask install rstudio
brew cask install --appdir="~/Applications" rstudio-preview
```

Up to you whether it's a good idea 😉 

*Upgrades* aren't technically supported by Homebrew-Cask, but if you use the above (with the `--force` flag as needed), things will stay where you originally installed them.

You could also create your own tap with a copy of the cask and use `:target` to rename the `.app` bundle - but at that point might as well rename the app yourself after the brew command.

**Comment by vitorgalvao** [comment]
Closing as solved.

**Comment by kenahoo-windlogics** [comment]
Fantastic, thanks @adidalal !
