### ISSUE TITLE
Services (i.e. workflows) installation doesn’t work

### ISSUE THREAD

**Issue by niksy** [caskroom/homebrew-cask#2264]
Similar to #2206, simply symlinking Automator created service (with `.workflow` extension) doesn’t work. Symlinked service is shown inside Services menu, but activating it doesn’t do anything.

It will work only if you explictly confirm that you want to install service (by activating workflow file and pressing "Install").

Maybe create something similar to pull request #2216 (@miguelfrde)?

**Comment by vitorgalvao** [comment]
Linking is a mess, and has proven to not be the best solution. That should be changed, and we’ll be working towards that.
