### ISSUE TITLE
Deleting /opt/homebrew-cask/Caskroom (post-migration)

### ISSUE THREAD

**Issue by chrisfinazzo** [caskroom/homebrew-cask#22663]
Following the instructions in #21913, I ran the `mv` command, but am unable to delete `/opt/homebrew-cask/Caskroom` because (obviously) a portion of the directory tree is gone.

In this case, shouldn't the command be `rm /opt/homebrew-cask`?

<img width="697" alt="screen shot 2016-07-08 at 10 09 32 am" src="https://cloud.githubusercontent.com/assets/1534882/16690242/fa5ca956-44f4-11e6-8420-dd2e8b737512.png">

**Comment by adidalal** [comment]
`sudo rm -rf /opt/homebrew-cask` should do the trick.
Use this only *after* migrating Casks/reinstalling as needed, obviously.
