### ISSUE TITLE
Plotdevice, Error: Uh oh, could not figure out how to unpack

### ISSUE THREAD

**Issue by dimitre** [caskroom/homebrew-cask#22677]
Installing on 10.12 Beta 16A239j (I'll soon investigate on 10.11)

Command
```
brew cask install plotdevice
```

Result
```
==> Downloading http://plotdevice.io/app/PlotDevice_app-0.10.0.zip
Already downloaded: /Users/dimitre/Library/Caches/Homebrew/plotdevice-0.10.0.zip
==> Verifying checksum for Cask plotdevice
Error: Uh oh, could not figure out how to unpack '/Users/dimitre/Library/Caches/Homebrew/plotdevice-0.10.0.zip'
```

**Comment by adidalal** [comment]
You need to follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide.

More importantly, you need to search. [We know, and this is being addressed](https://github.com/caskroom/homebrew-cask/pull/22002).
