### ISSUE TITLE
Moving binary file to something other than /usr/local/

### ISSUE THREAD

**Issue by blogabe** [caskroom/homebrew-cask#22679]
Don't know if https://github.com/caskroom/homebrew-cask/issues/21372 will address my question, but is there a way to change the behavior of where a binary file, when included in an app bundle, gets copied?

My specific example is textmate.  This line ```binary "#{appdir}/TextMate.app/Contents/Resources/mate"``` copies the mate binary, by default, into /usr/local/bin.  But if I have homebrew installed under my home folder, then I'd prefer to have the mate binary get copied to ~/.homebrew/bin for example.

Is there an environmental or command line option that I've missed?

I think the binaries for cases like this should by default be installed to $(brew --prefix)/bin

**Comment by vitorgalvao** [comment]
> Is there an environmental or command line option that I've missed?

Yes, [`binarydir`](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options).

> I think the binaries for cases like this should by default be installed to $(brew --prefix)/bin

https://github.com/caskroom/homebrew-cask/issues/21372. That’s in the first page of issues, even. Please search before opening new issues.
