### ISSUE TITLE
Cask request: binary mpv?

### ISSUE THREAD

**Issue by yacoob** [caskroom/homebrew-cask#22698]
### Cask details

Given that https://github.com/caskroom/homebrew-cask/issues/15603 got put on hold, can mpv formula be brought back? The brew formula is there, but given that mpv has a lot of dependencies, it's kind of annoying to use if all you want is up to date mpv bundle in your `/Applications`. The semi-official builds [here](https://laboratory.stolendata.net/~djinn/mpv_osx/) could be used.

**Name** - mpv
**Homepage** - https://mpv.io/
**License** - GPL
**Download URL** - https://laboratory.stolendata.net/~djinn/mpv_osx/

**Comment by vitorgalvao** [comment]
We only take official builds, so no. If you can get upstream to provide official builds, we can add it back.
