### ISSUE TITLE
Get rid of `$(brew --cache)/Casks` dir and symlinks

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#22727]
Refs https://github.com/caskroom/homebrew-cask/issues/22168. Marking as `bug`, since part of the reason to implement this is to fix a bug.

Currently, we download the target of `url` to `$(brew --cache)` and also set a symlink to it in `$(brew --cache)/Caskroom`. That last directory and symlink seem to serve no purpose. Furthermore, the interaction is broken, since if `$(brew --cache)/Casks` does not exist (somewhat common if you `rm "$(brew --cache)"` regularly) HBC blows up and gives an error about the file not being there, since we’re not creating the directory.

Fix is to get rid of `$(brew --cache)/Casks` dir and symlinks altogether.

**Comment by reitermarkus** [comment]
We could probably also address https://github.com/caskroom/homebrew-cask/issues/21763 as a part of this issue.

**Comment by reitermarkus** [comment]
I have been thinking about this for a while, and I can't find an easy way to tell apart Formula downloads from Cask downloads, especially when there are still Formulae and Casks with the same name.

**Comment by vitorgalvao** [comment]
But [like you said](https://github.com/caskroom/homebrew-cask/issues/22168#issuecomment-227122524) (and I very much agree), it makes no difference. It’s a cache directory, you’re not supposed to prod around.

**Comment by Eitot** [comment]
It may be worth waiting for Homebrew/brew#568.
