### ISSUE TITLE
Bug report: could not figure out how to unpack "iterm2-3.0.4.zip"

### ISSUE THREAD

**Issue by ccdd9451** [caskroom/homebrew-cask#22816]
#### Description of issue

When I tried to install iTerm2 in a new Mac with homebrew, I got following error. I tried to unpack this zip file manually and succeeded, but I don't know how to do next.

```
==> Verifying checksum for Cask iterm2
Error: Uh oh, could not figure out how to unpack '/Users/hukaidong/Library/Caches/Homebrew/iterm2-3.0.4.zip'
Error: Kernel.exit
```
update: After that I met a lot of problem using homebrow in MacOS Sierra. Now I give up and decide to get my Mac back to EI Capitan.

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

When the the guide isn‘t followed we get the same issues over and over again. It may not seem to you like it makes a difference, but we already get a non-trivial amount of new issues and pull requests every day. Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

Also, [please search before opening issues](https://github.com/caskroom/homebrew-cask/pull/22002).
