### ISSUE TITLE
ohai command outputting wrong color

### ISSUE THREAD

**Issue by toonetown** [caskroom/homebrew-cask#22836]
For some reason, the change in #22762  change makes all cask `ohai` commands displayed as white for me - instead of bold black.  Reverting this change fixes the problem.

The `ohai` commands issued by homebrew formulas are still the correct color.  Just the cask ones.  You can see this in action by running `brew cask info zulu` (or any other cask that has "Caveats") and notice the incorrect color of the `Caveats` line.

**Comment by niksy** [comment]
Similar issue here with light Terminal theme:

![screen shot 2016-07-16 at 19 02 59](https://cloud.githubusercontent.com/assets/389286/16896039/ea9d24c0-4b87-11e6-8d74-c48ee3e90474.png)
