### ISSUE TITLE
Add TRAVIS_REPO_SLUG to all repos

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#22849]
Refs https://github.com/caskroom/homebrew-cask/pull/22847.

Too sleepy to do it now, so making the issue to not forget, or if someone wants to do it in the meantime.

**Comment by jawshooah** [comment]
Done in https://github.com/caskroom/homebrew-versions/compare/702a70afe35e1f9572c15507531a7eb306ed7983...7653abfea44db83d829f57ba8e88dc343ed1545a and https://github.com/caskroom/homebrew-fonts/compare/defbc87ecfbd86cb4cbd3da2d29f71934ebfe029...5428f9ddeabcfc7372d8abb92a835cbcd63baf02
