### ISSUE TITLE
Do you have any way to set Download mirror url like HOMEBREW_BOTTLE_DOMAIN? 

### ISSUE THREAD

**Issue by jainishshah17** [caskroom/homebrew-cask#22878]
Before writing your issue, check our instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) or [making requests](https://github.com/caskroom/homebrew-cask#requests), as appropriate. Those will walk you through the process.

If none of those is appropriate, then **delete all this pre-inserted template text** and tell us your issue in as much detail as possible.

Please note that if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review. When the guide isn‘t followed we get the same issues over and over. Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

If the guide itself was unclear, open *first* an issue or pull request stating what you found was confusing *and only then* your other issue.

Thank you for taking the time to make a correct report.

**Comment by vitorgalvao** [comment]
No.

Also, please read the template.
