### ISSUE TITLE
Cask request: QZ Tray v2.0.0

### ISSUE THREAD

**Issue by m44rt3np44uw** [caskroom/homebrew-cask#22932]
### Cask details

**Name** - QZ Tray v2.0.0

**Homepage** - https://qz.io/

**License** - LGPL - https://github.com/qzind/tray/blob/2.0/LICENSE.txt

**Download URL** - https://github.com/qzind/tray/releases/download/v2.0.0/qz-tray-2.0.0.pkg

**Description** - Print labels, barcodes, receipts and more from a webpage using HTML, JavaScript and Java.

**Comment by reitermarkus** [comment]
Added in 98e5371b0112dd71f450f9122615fea4027b4ad1.
