### ISSUE TITLE
Cask request: gretl

### ISSUE THREAD

**Issue by gabrielalmeida** [caskroom/homebrew-cask#23017]
Cask details

Name - Gretl v2016c

Homepage - http://gretl.sourceforge.net/

License - GNU General Public License

Download URL - http://downloads.sourceforge.net/project/gretl/gretl/2016c/gretl-2016c-quartz.pkg?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fgretl%2Ffiles%2F&ts=1469296202&use_mirror=ufpr

Description - Gnu Regression, Econometrics and Time-series Library. Is a cross-platform software package for econometric analysis, written in the C programming language. It is free, open-source software.

**Comment by vitorgalvao** [comment]
Closing, as there seems to be no interest in making a PR.
