### ISSUE TITLE
Cask request: DOSBox SVN

### ISSUE THREAD

**Issue by coughlanio** [caskroom/homebrew-cask#23023]
### Cask details

The current DOSBox Cask version is wildly out of date. 6 years to be exact. DOSBox has essentially stopped binary releases of the application, with the community having to take up release efforts with SVN builds. Dominus over on the vogons forums releases an up-to-date, clean, SVN build of DOSBox, as shown here on the official DOSBox wiki:

https://www.dosbox.com/wiki/SVN_Builds#Plain.2Fvanilla.2Fclean_SVN_builds

Currently, the only available version link is Dosbox-Snapshot.dmg, which doesn't lend itself well to Homebrew/Cask, but I can reach out to him and ask if he can provide specific version naming of files. I'd also be happy to implement the Cask if approved.

**Name** -

DOSBox-SVN

**Homepage** -

https://www.dosbox.com/wiki/SVN_Builds#Plain.2Fvanilla.2Fclean_SVN_builds

**License** -

GNU GPL

**Download URL** -

http://dl.dropbox.com/u/7737184/Dosbox/Dosbox-Snapshot.dmg

**Description** -

SVN builds are versions of DOSBox that people have built from the latest version of the DOSBox source code, which is stored on sourceforge.net in something called an SVN repository. SVN builds contain changes that have been made by the DOSBox developers since the latest official release. Some enhanced SVN builds also contain unofficial features and fixes that have been created by enthusiasts in the DOSBox development community.

**Comment by reitermarkus** [comment]
> I can reach out to him and ask if he can provide specific version naming of files. 

That would be great. If this isn't possible as it is “Automatically updated on changes to SVN.”, you can still use `version :latest`. 

> I'd also be happy to implement the Cask if approved.

If you do, please submit it to [caskroom/versions](http://github.com/caskroom/homebrew-versions).

**Comment by yurikoles** [comment]
closed in [2445](../../homebrew-versions/issues/2445)
