### ISSUE TITLE
Outdated URL Soundnode

### ISSUE THREAD

**Issue by PixiBixi** [caskroom/homebrew-cask#23035]
Hello,

The Soundnode URL Cask has changed https://github.com/caskroom/homebrew-cask/blob/04a02ea9ee03ba61e084481da051facc9f19f5c1/Casks/soundnode.rb

Previously, it was this link, but now, its http://www.soundnodeapp.com/downloads/mac/Soundnode.zip

Please, fix it :)

**Comment by reitermarkus** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/23037.
