### ISSUE TITLE
brew cask audit hangs on certain casks

### ISSUE THREAD

**Issue by shonjir** [caskroom/homebrew-cask#23031]
Ran across this issue when Travis failed on a simple cask-repair update for [displaycal](https://github.com/caskroom/homebrew-cask/blob/640c0036910be01c76cf8092195b7616763264d0/Casks/displaycal.rb) (PR #23020).

Investigation reveals that `brew cask audit displaycal.rb --download` was hanging when invoking `curl` to verify the appcast.

```
==> 1 modified cask: displaycal
==> git diff 3b95fac57a30b592bef5cda4fcbf509fb35da5ea...db55923e7378600faac221e64a556265a7b0d1be -- Casks/displaycal.rb
==> Auditing required stanzas
==> Verifying version :latest does not appear as a string ('latest')
==> Verifying sha256 :no_check with version :latest
==> Verifying sha256 string is a legal SHA-256 digest
==> Verifying sha256 is not a known invalid value
==> Auditing appcast
==> Verifying appcast has :checkpoint key
==> Verifying appcast :checkpoint string is a legal SHA-256 digest
==> Verifying appcast :checkpoint is not a known invalid value
==> Verifying appcast returns 200 HTTP response code
==> Executing: ["/usr/bin/curl", "--compressed", "--location", "--user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10) http://caskroom.io", "--output", "/dev/null", "--write-out", "%{http_code}", "https://sourceforge.net/projects/dispcalgui/rss?path=/release"]
==> Verifying appcast checkpoint is accurate
==> Executing: ["/usr/bin/curl", "--compressed", "--location", "--user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10) http://caskroom.io", "https://sourceforge.net/projects/dispcalgui/rss?path=/release"]
```

Manually invoking `/usr/bin/curl --location --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS Xttp://caskroom.io' 'https://sourceforge.net/projects/dispcalgui/rss?path=/release'` retrieves the appcast as expected so the issue appears to be with `brew cask audit`.

Further investigation shows that this occurs for any cask that has a sourceforge appcast containing a URI path parameter.  Other casks that do not contain this parameter are processed successfully.

A quick search and manual validation identifies the following casks that are affected by this issue.

[animated-gif-quicklook.rb](/caskroom/homebrew-cask/blob/master/Casks/animated-gif-quicklook.rb)
[displaycal.rb](/caskroom/homebrew-cask/blob/master/Casks/displaycal.rb)
[freesmug-chromium.rb](/caskroom/homebrew-cask/blob/master/Casks/freesmug-chromium.rb)
[grandperspective.rb](/caskroom/homebrew-cask/blob/master/Casks/grandperspective.rb)
[grisbi.rb](/caskroom/homebrew-cask/blob/master/Casks/grisbi.rb)
[klatexformula.rb](/caskroom/homebrew-cask/blob/master/Casks/klatexformula.rb)
[mnemosyne.rb](/caskroom/homebrew-cask/blob/master/Casks/mnemosyne.rb)
[qbittorrent.rb](/caskroom/homebrew-cask/blob/master/Casks/qbittorrent.rb)
[seashore.rb](/caskroom/homebrew-cask/blob/master/Casks/seashore.rb)
[squirrelsql.rb](/caskroom/homebrew-cask/blob/master/Casks/squirrelsql.rb)
[supertuxkart.rb](/caskroom/homebrew-cask/blob/master/Casks/supertuxkart.rb)

**Comment by reitermarkus** [comment]
Just found that adding the `--verbose` flag to the request in `audit.rb` makes it work for some reason.

**Comment by reitermarkus** [comment]
Ok, I think I found the reason this is happening: https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/system_command.rb#L90

The reason the command is stuck is because the output of `curl` is the `appcast` file. In the cases above, the file does not have an `EOF` marker, the consequence is an infinite loop.

**Comment by reitermarkus** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/issues/23050.
