### ISSUE TITLE
Use `system_command` instead of `system` in Casks

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#23070]
`system_command` was introduced way back in #5723 as an interface for Casks to run shell commands in *flight blocks without using backticks or `Kernel#system`, allowing us to capture the output and error out if the command failed.

We've had some issues in the past where Casks silently failed to install or uninstall because a `system` call in a *flight block failed but no error was raised. Using `system_command`, such failures will be made apparent to the user, and thus to us when users create bug reports.

We should also create a cop over in [rubocop-cask](https://github.com/caskroom/rubocop-cask) to check for instances of `system` and warn the user to replace them with `system_command`. We could even make it autocorrect to further reduce the burden on the user.

---

Action items:
- [X] Replace existing instances of `system` in Casks with `system_command`
- [ ] Create a cop to warn when a Cask uses `system` instead of `system_command`
  - [ ] Teach the cop to autocorrect

**Comment by tsparber** [comment]
Would it also be possible to just "overwrite" the `Kernel#system` command in a similar way as homebrew [does it](https://github.com/Homebrew/brew/blob/7a00f03c92607f65336be0285584e8351ad8a73a/Library/Homebrew/utils.rb#L224)?

**Comment by jawshooah** [comment]
[This](https://github.com/Homebrew/brew/blob/d7ee54129310de2b8b4989e6a47607fd1fb7db6c/Library/Homebrew/formula.rb#L1419) is their overridden `system` method that's exposed to Formula authors; we could potentially do something similar by exposing a `system` method on `Hbc::DSL::Base`.

**Comment by miccal** [comment]
First Action item is complete - all instances of `system` have been replaced with `system_command` in all repositories.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/rubocop-cask/issues/46.
