### ISSUE TITLE
Cask request: PokerstarsEU

### ISSUE THREAD

**Issue by dni** [caskroom/homebrew-cask#23112]
### Cask details
PokerstarsEU
(Please fill out as much as possible)

**Name** -
PokerStarsEU
**Homepage** -
https://www.pokerstars.eu/

**License** -
:freemium

**Download URL** -
https://www.pokerstars.eu/PokerStarsEU.app.zip

**Description** -

**Comment by fanquake** [comment]
This is available in the [versions repo](https://github.com/caskroom/homebrew-versions/blob/master/Casks/pokerstarseu.rb).

**Comment by dni** [comment]
ups missed that sorry ;)
