### ISSUE TITLE
navicat-for-postgresql - bad checksum

### ISSUE THREAD

**Issue by edrozenberg** [caskroom/homebrew-cask#23151]
````
$ brew cask install navicat-for-postgresql
==> Downloading http://download.navicat.com/download/navicat112_pgsql_en.dmg
Already downloaded: /Users/eduardr/Library/Caches/Homebrew/navicat-for-postgresql-11.2.11.dmg
==> Verifying checksum for Cask navicat-for-postgresql
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 30a85fafc5470dbfe67d8e15fcca71f01c50d7c78811e40495c70f61e1221a18
Actual: 84356691e65c2145a2caf07b23cf31baefbb3b994748d625a6cfb45bcabc1552
File: /Users/eduardr/Library/Caches/Homebrew/navicat-for-postgresql-11.2.11.dmg
To retry an incomplete download, remove the file above.
````

**Comment by adidalal** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide.

Specifically, the instructions explain why the error occurred and how to fix it for yourself and everyone else by submitting a PR.

**Comment by adidalal** [comment]
All the navicat casks will need an update, if I recall correctly. There's a small bash script in one of the earlier navicat issues to automate the whole process

**Comment by adidalal** [comment]
@edrozenberg 

https://github.com/caskroom/homebrew-cask/issues/18130#issuecomment-178788376

Version will be `11.2.12`, but the above should work
