### ISSUE TITLE
Cask request: blender bpy module

### ISSUE THREAD

**Issue by sirgogo** [caskroom/homebrew-cask#23261]
### Cask details

**Name** -
Blender BPY module for brew

**Homepage** -
[blender](https://www.blender.org/)
[how to compile](https://wiki.blender.org/index.php/User:Ideasman42/BlenderAsPyModule)

**License** -
GPL

**Download URL** -
[git source](http://git.blender.org/blender.git)
[svn for darwin](https://svn.blender.org/svnroot/bf-blender/trunk/lib/darwin-9.x.universal)

**Description** -
Blender bpy module allows system python3 to load blender into the background and perform operations, as outlined [here](https://wiki.blender.org/index.php/User:Ideasman42/BlenderAsPyModule). It is a fairly common to do this, especially on Linux desktops. Even after installing a slew of tools manually, the install is not seamless on OSX, even when following the instructions if you have python3 installed via brew.

```
$ cmake ../blender/
-- Detected OS X 10.11 and Xcode 7.3 at /Applications/Xcode.app
-- OSX_SYSROOT_PREFIX: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
CMake Error at CMakeLists.txt:2102 (message):
  Python executable missing:
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m
```

As such, it would be very helpful if either `brew install blender` included this module, or a separate cask which might exist as `brew install blender-bpy`.

Here is an example of some hackery that must be done: [[link](https://bordulla.wordpress.com/2016/01/11/blender-as-a-python-module/)]

Thanks in advance.

**Comment by adidalal** [comment]
We can't compile from source. If there's a place that hosts binary builds we can consider adding that as a cask.

**Comment by vitorgalvao** [comment]
Seems to be no interest/resolution.
