### ISSUE TITLE
Cask request: Java Cryptography Extension Unlimited Strength Jurisdiction Policy

### ISSUE THREAD

**Issue by sirn** [caskroom/homebrew-cask#23326]
### Cask details

**Name**:
Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files

**Homepage**:
http://www.oracle.com/technetwork/java/javase/downloads/index.html

**License**:
Gratis (Oracle Binary Code License Agreement for Java SE)

**Download URL**:
http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Description**:
This package serve as an extension to the existing [Java](https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb) Cask, and enable some of the encryption features (e.g. AES256) that were previously disabled due to [United States export ban on encryption](https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States)

----------

I'm opening this issue because I'm not sure if whether the JCE Policy Files belongs in the Cask as there is no conventional installer. Oracle only providing a package containing policy `.jar`s that need to be copied to `$(/usr/libexec/java_home)/jre/lib/security` (although Java do install the a restricted stubs by default at that location, so a backup need to be made.) 

I'm not quite sure what would be the best way to create this Cask, or even should it include in the Cask at all.

----------

For a reference, this is how I installed it.

```shell
$ # download jce_policy-8.zip from homepage.
$ export JAVA_HOME=$(/usr/libexec/java_home)
$ sudo mv $JAVA_HOME/jre/lib/security/US_export_policy.jar{,.bak}
$ sudo mv $JAVA_HOME/jre/lib/security/local_policy.jar{,.bak}
$ unzip jce_policy-8.zip
$ sudo mv UnlimitedJCEPolicyJDK8/US_export_policy.jar $JAVA_HOME/jre/lib/security/US_export_policy.jar
$ sudo mv UnlimitedJCEPolicyJDK8/local_policy.jar $JAVA_HOME/jre/lib/security/local_policy.jar
```

**Comment by vitorgalvao** [comment]
Isn’t it [this cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jce-unlimited-strength-policy.rb)?

**Comment by sirn** [comment]
@vitorgalvao oops, looks like that's the one. Was grepping for `/java/` for all along. Closing, thanks.
