### ISSUE TITLE
Can't uninstall docker-toolbox

### ISSUE THREAD

**Issue by fanquake** [caskroom/homebrew-cask#23329]
According to comments [here](https://github.com/caskroom/homebrew-cask/commit/1cfbf12dd8233f6e5720eba271e9aa8ff440a7c7), it is now impossible to uninstall the Docker Toolbox cask.

**Comment by reitermarkus** [comment]
Isn't this exactly the same bug as https://github.com/caskroom/homebrew-cask/issues/2988?

**Comment by vitorgalvao** [comment]
This is just due to the name change. The new name appears to be the correct one.
