### ISSUE TITLE
Docker Toolbox cask not working (typo in commit)

### ISSUE THREAD

**Issue by RaoOfPhysics** [caskroom/homebrew-cask#23330]
https://github.com/caskroom/homebrew-cask/commit/1cfbf12dd8233f6e5720eba271e9aa8ff440a7c7

Note that `cask 'dockertoolbox' do` has been replaced by `cask 'docker-toolbox' do`. Will submit a PR with the correction, unless it was decided to rename the cask. At the moment, `$ brew cask info dockertoolbox` gives me this message:

```bash
dockertoolbox (!):
dockertoolbox
No Homepage
/usr/local/Caskroom/dockertoolbox/.metadata (4.0K)
No GitHub URL
No Artifact Info
```

**Comment by vitorgalvao** [comment]
It’s expected, and something we’re aware of (better handling of renames).
