### ISSUE TITLE
CleanMyMac will cleanup the cache folder, which makes an error when run `brew cask doctor`

### ISSUE THREAD

**Issue by imwithye** [caskroom/homebrew-cask#23355]
By default, CleanMyMac will remove all caches in the `~/Library/Caches` folder, in which case, the `brew cask doctor` command will give an error like this:

```bash
Error: No such file or directory - ~/Library/Caches/Homebrew/Casks
  Most likely, this means you have an outdated version of homebrew-cask. Please run:
    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup
  If this doesn’t fix the problem, please report this bug:
    https://github.com/caskroom/homebrew-cask#reporting-bugs
```

Possible solution is, creating the cache directory if cask doctor cannot find the cache directory under homebrew, instead of reporting an error.

**Comment by reitermarkus** [comment]
This will be fixed when https://github.com/caskroom/homebrew-cask/pull/23265 is merged.

**Comment by imwithye** [comment]
Great! Thanks.
