### ISSUE TITLE
Cask request: osxfuse 3.4.1

### ISSUE THREAD

**Issue by wodim** [caskroom/homebrew-cask#23395]
Sorry for not using the template, but what I want to request is an update--the current Cask version of osxfuse is 2.8.3, while the latest released version is 3.4.1. It also might be appropriate to change the source from SourceForge to GitHub, now that development of osxfuse is going on here. Thank you.

https://github.com/caskroom/homebrew-cask/blob/master/Casks/osxfuse.rb

https://github.com/osxfuse/osxfuse/releases

**Comment by vitorgalvao** [comment]
`3.4.1` is a pre-release, we only take stable releases.
