### ISSUE TITLE
Cask request: Whatsie

### ISSUE THREAD

**Issue by LEI** [caskroom/homebrew-cask#23435]
### Cask details

The [unofficialwhatsapp cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/unofficialwhatsapp.rb) should be replaced by [Whatsie](https://github.com/Aluxian/Whatsie#os-x).

https://github.com/Aluxian/WhatsApp-Desktop#unofficial-whatsapp-for-desktop-deprecated

**Name** -
Whatsie

**Homepage** -
https://github.com/Aluxian/Whatsie

**License** -
MIT

**Download URL** -
https://github.com/Aluxian/Whatsie/releases `/download/vX.X.X/whatsie-X.X.X-osx.{dmg,zip}`

[Latest (2.0.19-beta)](https://github.com/Aluxian/Whatsie/releases/download/v2.0.19/whatsie-2.0.19-osx.dmg)

**Description** -
An alternative desktop client for WhatsApp Web.

**Comment by jawshooah** [comment]
Done in #23525
