### ISSUE TITLE
mactex upgrade does not remove previous installation

### ISSUE THREAD

**Issue by renard** [caskroom/homebrew-cask#23467]
By the past I installed `mactex` (version 2015) I recently upgraded to the current one (20160603) which install some new pkgs:

- `org.tug.mactex.ghostscript9.19`
- `org.tug.mactex.gui2016`
- `org.tug.mactex.texlive2016`

The 2015 version of `mactex` leave its packages:

```
pkgutil --pkgs=.*mactex.*
org.tug.mactex.ghostscript9.16
org.tug.mactex.ghostscript9.19
org.tug.mactex.gui2015
org.tug.mactex.gui2016
org.tug.mactex.texlive2015
org.tug.mactex.texlive2016

du -shc /usr/local/texlive/*
4.3G	/usr/local/texlive/2015
4.7G	/usr/local/texlive/2016
  0B	/usr/local/texlive/texmf-local
9.0G	total
```

Is there a simple way to remove all 2015 version of `mactex`? Is it `mactex` responsability to remove its previous versions? or should `mactex` be versionned (such as `mactex-2015`,  `mactex-2016` and so on...)

TIA.

**Comment by vitorgalvao** [comment]
You need to specifically uninstall what you don’t want. We don’t have upgrade functionality yet.
