### ISSUE TITLE
uTorrent & bittorrent installs spigot malware 

### ISSUE THREAD

**Issue by ramsrib** [caskroom/homebrew-cask#23491]
uTorrent and bittorrent app installed from cask has **spigot malware**. It installs firefox and chrome extensions in mac. 

Cask is one of the trusted store, So, please remove this utorrent and bittorrent from cask. 

To remove it, refer : http://www.thesafemac.com/arg-spigot/

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/apps_with_malware.md

**Comment by ramsrib** [comment]
At least, when some user reports this kind of malware bundle, we can include a warning during cask installation.

**Comment by jawshooah** [comment]
@ramsrib Did you read the documentation that @adidalal linked above? That's exactly what we do when a cask includes the `malware` caveat.

**Comment by pluskid** [comment]
@jawshooah However, I did not see any warning message mentioning potential bundled malware for utorrent. The Caveat just says I need to run the installer.

**Comment by vitorgalvao** [comment]
@pluskid Because utorrent does not have the `malware` caveat, because no one has gone through [the steps to add it](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/apps_with_malware.md).
