### ISSUE TITLE
mamp: URL broken

### ISSUE THREAD

**Issue by evansb** [caskroom/homebrew-cask#23537]
Looks like they change the URL.

New URL for 3.5.2
```
http://downloads6.mamp.info/MAMP-PRO/releases/3.5.2/MAMP_MAMP_PRO_3.5.2.pkg
```
SHA-1
```
b6cc5f46f7a9a8a0cf779aa8af03c77dc496f086
```
[Source](https://www.mamp.info/en/downloads/)

**Comment by vitorgalvao** [comment]
The current one is the correct. Refresh the page and you’ll see that one change.
