### ISSUE TITLE
Emojipedia cask enhancement?

### ISSUE THREAD

**Issue by gingerbeardman** [caskroom/homebrew-cask#23554]
Thanks for making the cask for Emojipedia!

It would be great if you could automatically activate the dictionary by writing to Dictionary preferences. 

com.apple.Dictionary.plist

excerpt:
```plist
	<key>window settings</key>
	<array>
		<dict>
			<key>dictionaries</key>
			<array>
				<dict>
					<key>disclosure opened</key>
					<true/>
					<key>path</key>
					<string>/Library/Dictionaries/Oxford Dictionary of English.dictionary</string>
					<key>user choice</key>
					<true/>
				</dict>
				<dict>
					<key>disclosure opened</key>
					<true/>
					<key>path</key>
					<string>/Library/Dictionaries/Oxford Thesaurus of English.dictionary</string>
					<key>user choice</key>
					<false/>
				</dict>
				<dict>
					<key>disclosure opened</key>
					<true/>
					<key>path</key>
					<string>/Users/matt/Library/Containers/com.apple.Dictionary/Data/Library/Dictionaries/Emojipedia.dictionary</string>
					<key>user choice</key>
					<false/>
				</dict>
				<dict>
					<key>disclosure opened</key>
					<true/>
					<key>path</key>
					<string>/System/Library/Frameworks/CoreServices.framework/Frameworks/DictionaryServices.framework/Resources/Wikipedia.wikipediadictionary</string>
					<key>sub-dictionaries</key>
					<array>
						<dict>
							<key>disclosure opened</key>
							<true/>
							<key>identifier</key>
							<string>com.apple.dictionary.Wikipedia-en</string>
							<key>user choice</key>
							<false/>
						</dict>
					</array>
					<key>user choice</key>
					<false/>
				</dict>
			</array>
			<key>image window frame</key>
			<string>{{0, 0}, {0, 0}}</string>
			<key>image window parent frame</key>
			<string>{{0, 0}, {0, 0}}</string>
			<key>index width</key>
			<integer>172</integer>
			<key>search method</key>
			<integer>1</integer>
			<key>window ID</key>
			<integer>1</integer>
		</dict>
	</array>
```

**Comment by Eitot** [comment]
Have you tried this? This doesn’t seem to work. Modifying nested arrays and dictionaries is also difficult to do with the `defaults` utility. I think the manual activation is probably the better way to do this.

**Comment by reitermarkus** [comment]
There's also `/usr/libexec/PlistBuddy`, which is a bit more versatile than `defaults`.

**Comment by Eitot** [comment]
Modifying the plist file actually breaks something in the Dictionary app. When I cleared the preferences using `defaults delete com.apple.Dictionary’, my selection was actually still there. I am guessing that this is not the only place where this preference is stored.

**Comment by reitermarkus** [comment]
Try `/usr/bin/killall cfprefsd` after changing the `.plist`, this *should* refresh the preferences cache.

**Comment by Eitot** [comment]
Doesn’t make a difference. `defaults` should normally send a signal to cfprefsd anyway. I’ve tried deleting the preference file via the bundle identifier and via the file path directly, without a difference. The window position and such is indeed reset, but the dictionary selection is not.

**Comment by vitorgalvao** [comment]
Especially with macOS apps that come with the system, this kind of change seldom works well. It’s like they ignore whatever you do unless it’s done on the GUI. I doubt we’ll be able to do this.

**Comment by gingerbeardman** [comment]
Here's an [fseventer](http://www.mediafire.com/download/ox2u6lhe5xp9xoq/fseventer.zip)\* grab of the files that are changed when Dictionary selection is changed.

\* [you'll need to tweak fseventer default settings for it to work in Yosemite/El Capitan/etc](https://www.reddit.com/r/osx/comments/3ovcq8/alternative_to_fseventer_for_el_capitan/)

![screen shot 2016-08-16 at 15 09 46](https://cloud.githubusercontent.com/assets/49612/17702082/5d2d1c76-63c4-11e6-8332-a8c883e8735d.png)

So the plist file has to be accessed at the following path:
```
~/Library/Containers/com.apple.Dictionary/Data/Library/Preferences
```

Here's my plist: http://pastebin.com/raw/m8et6jJH

And here's how it looks in Dictionary preferences:
![screen shot 2016-08-16 at 15 15 54](https://cloud.githubusercontent.com/assets/49612/17702091/6945127a-63c4-11e6-8f4b-f92eb0eb0b66.png)

Deleting the plist and then opening `Dictionary.app` will remove references to all dictionaries other than those previously selected:
```
~/Library/Dictionaries
```
Like so:
![screen shot 2016-08-16 at 15 14 18](https://cloud.githubusercontent.com/assets/49612/17702105/7276ed64-63c4-11e6-93b5-a03d23853c13.png)

Doing `/usr/bin/killall cfprefsd` makes no difference.

No idea what this all means.

**Comment by gingerbeardman** [comment]
So, https://dictionaries.io does it.

Here's the feseventer grab.

![screen shot 2016-08-16 at 15 48 00](https://cloud.githubusercontent.com/assets/49612/17703238/e4fa9c6a-63c8-11e6-90f0-8aad5fe3213b.png)

Seems to be deleting some caches? 

Getting closer.

Can you shed any light on this @vslavik ?

**Comment by vslavik** [comment]
I'm on vacation, don't remember the details off hand (it's the app's secret sauce too, but oh well ;). A bunch of processes to kill, more than one plist too IIRC. Bug me in a week if I forget to tell you the details.

**Comment by gingerbeardman** [comment]
@vslavik 👍

**Comment by adidalal** [comment]
Should definitely be able to put it in a pre/postflight stanza - but consider adding a new container type (artifact) :`dictionary` to the core code and generalizing this behavior. It would make adding other dictionaries quite easy, as well.

I can dig up an older PR where someone contributed a new artifact type if you need help.

**Comment by reitermarkus** [comment]
@gingerbeardman, feel free to re-open this if you find a solution.

**Comment by Eitot** [comment]
Just for reference: I came across another dictionary in the global defaults. I think this is where the active configuration of the Dictionary app is stored.
```
defaults read -g com.apple.DictionaryServices
```

I am guessing that the configuration is probably affected by all of these:
* `defaults read com.apple.Dictionary`
* `defaults read -g com.apple.DictionaryServices`
* ~/Library/Containers/com.apple.Dictionary/Data/Library/Preferences/com.apple.Dictionary.plist (see gingerbeardman above)
