### ISSUE TITLE
Cask request: Boostnote

### ISSUE THREAD

**Issue by km-tr** [caskroom/homebrew-cask#23552]
### Cask details

(Please fill out as much as possible)

**Name** - Boostnote

**Homepage** - https://b00st.io/jp/

**License** - GPL v3

**Download URL** - https://github.com/BoostIO/boost-releases/releases/download/v0.6.2/Boostnote-mac.dmg

**Description** - Boostnote is an open-sourced note app for programmer.

**Comment by reitermarkus** [comment]
Added in https://github.com/caskroom/homebrew-cask/issues/23563.
