### ISSUE TITLE
`brew cask info` gives `Not installed` for some installed casks (chefdk, vagrant, virtualbox)

### ISSUE THREAD

**Issue by dserodio** [caskroom/homebrew-cask#23565]
Some apps are listed with `brew cask list`, but `brew cask info $app` shows `Not installed`. I have read "[brew cask list shows wrong information](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/brew_cask_list_shows_wrong_information.md)" but AFAIK, my problem is with `cask info`.

    $ brew cask list
    betterzipql  chefdk   java         soundcleod   vagrant  virtualbox   xquartz

However:

    $ for app in chefdk vagrant virtualbox; do; echo ---- $app ----; brew cask info $app; done
    ---- chefdk ----
    chefdk: 0.16.28-1
    Chef Development Kit, ChefDK
    https://downloads.chef.io/chef-dk/
    Not installed
    https://github.com/caskroom/homebrew-cask/blob/master/Casks/chefdk.rb
    ==> Contents
      chefdk-0.16.28-1.pkg (pkg)
    ---- vagrant ----
    vagrant: 1.8.5
    Vagrant
    https://www.vagrantup.com/
    Not installed
    https://github.com/caskroom/homebrew-cask/blob/master/Casks/vagrant.rb
    ==> Contents
      Vagrant.pkg (pkg)
    ---- virtualbox ----
    virtualbox: 5.1.2-108956
    Oracle VirtualBox
    https://www.virtualbox.org
    Not installed
    https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox.rb
    ==> Contents
      VirtualBox.pkg (pkg)

**Comment by MilusW** [comment]
It also happens to me, but with different apps:
crashplan, java, tunnelblick.

I also found that brew cask is unable to update applications. I think that cask has in repository newer versions and, if we have older one installed, it states that it is not installed, so it can't update it.

As an example: I have installed java using brew cask, version `1.8.0_92-b14`.
Now, output of brew cask info java:
```
java: 1.8.0_102-b14
Java Standard Edition Development Kit
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb
==> Contents
  JDK 8 Update 102.pkg (pkg)
```

On the contrary, as VLC seems OK:
```
~ brew cask info vlc
vlc: 2.2.4
VLC media player
https://www.videolan.org/vlc/
/usr/local/Caskroom/vlc/2.2.4 (10 files, 252K)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/vlc.rb
==> Contents
  VLC.app (app)
  /usr/local/Caskroom/vlc/2.2.4/vlcwrapper (binary)
```

**Comment by reitermarkus** [comment]
Yes, this is a known problem when there is a newer version in the repo than is installed.

Hopefully most of it will be fixed in https://github.com/caskroom/homebrew-cask/pull/23328. But this is still very much a work in progress.

**Comment by adidalal** [comment]
FYI, the *not-really-a-fix* solution is `brew cask uninstall {{cask_name}} --force && brew update && brew cask install {{cask_name}}`, but follow https://github.com/caskroom/homebrew-cask/pull/23328 for updates.

**Comment by wickles** [comment]
Still errors a la https://github.com/caskroom/homebrew-cask/issues/23762 after updated with latest merge. Should that have been fixed too?

**Comment by reitermarkus** [comment]
@wickles, could you please create a separate issue with your output?

**Comment by wickles** [comment]
it's AFAIK exactly the same as the other issue, so I'll just move conversation over there.
