### ISSUE TITLE
Question: How to force overwrite without forcing reinstall?

### ISSUE THREAD

**Issue by pftbest** [caskroom/homebrew-cask#23587]
For a while I was using this script to update my casks:
```Bash
for i in $(brew cask list); do brew cask install $i; done
```
And it worked great (except for chromium), when cask was up to date it just printed `Warning: A Cask for ... is already installed...` and when it needed updating it installed a new version.

But now with this new move semantics it does things like this:
```
==> Downloading http://download.qt.io/official_releases/qtcreator/4.0/4.0.3/qt-c
######################################################################## 100.0%
==> Verifying checksum for Cask qt-creator
==> It seems there is already an App at '/Applications/Qt Creator.app'; not movi
🍺  qt-creator was successfully installed!
```
and I still get the old version, even though it says "successfully installed!"
I know I can use `--force` to force overwrite, but I can't use it my script because it will force reinstall on casks that do not need updating. So my question is, how do I force overwrite, without forcing reinstall of up-to-date casks, or how do I get a list of casks that need updating, so I could use `--force` on them?

**Comment by vitorgalvao** [comment]
[`brew cask list` is broken](https://github.com/caskroom/homebrew-cask/issues/14058), and you cannot rely on it. There is no official way to upgrade casks yet, and not method is support or encouraged by us. Whatever works for you is fine, but we won’t encourage any particular way.

Also, the [`successfully installed!` message is definitely a bug](https://github.com/caskroom/homebrew-cask/issues/23377).
