### ISSUE TITLE
Warn when a new Cask conflicts with a Formula in homebrew-core

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#23622]
In light of #15603 and the subsequent flurry of PRs from @AnastasiaSulyagina (thanks!), I think it would be helpful to add a check to `brew cask audit` which warns if a Cask conflicts with a core Formula. It could be opt-in with a flag like `--check-formula-conflicts` so that we could apply the check to new Casks during a CI run.

@caskroom/maintainers Any objections?

**Comment by vitorgalvao** [comment]
> Any objections?

None.

**Comment by adidalal** [comment]
LGTM
