### ISSUE TITLE
brew cask install qq ''error''

### ISSUE THREAD

**Issue by vinoZHU** [caskroom/homebrew-cask#23632]
Error: sha256 mismatch
Expected: 936cf4c7699d6b12d8928d31f6b4a0ad4eaf817af0ed52887b6ee60ccc0d1e60
Actual: d5b1cb5b5885aa265e8b758fb800ec8fd516076cb5346081fa462bdf241e028b

**Comment by jawshooah** [comment]
[Dude...](https://github.com/caskroom/homebrew-cask#reporting-bugs)

**Comment by cs50Mu** [comment]
same problem here, it seems that the SHA2 expected is not correct..

**Comment by vitorgalvao** [comment]
As @jawshooah pointed out, [**there’s a whole section teaching how to fix or correctly report this**](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#sha256-mismatch-error). When opening the issue **you were told to follow it or else the issue would be closed without further review**.

Please respect our time and make a correct report (we also ask for that in the template when opening the issue).

No need to comment further, I’ll fix it now. But please, next time, follow the rules we plaster everywhere.

**Comment by vitorgalvao** [comment]
Just like it did yesterday when I updated it, today the `sha256` still seems the same. Please follow the steps in those instructions to make sure the problem isn’t on your end.

**Comment by vinoZHU** [comment]
Hi,I've updated the brew cask and deleted the downloaded file,but the error still exist.And I also do the steps in those instructions,here are the result.

➜  ~ brew cask _stanza version qq
5.1.0
➜  ~ brew cask info qq
qq: 5.1.0
QQ
http://im.qq.com/macqq/
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/qq.rb
==> Contents
  QQ.app (app)
➜  ~ brew cask install qq
==> Downloading http://dldir1.qq.com/qqfile/QQforMac/QQ_V5.1.0.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask qq
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 936cf4c7699d6b12d8928d31f6b4a0ad4eaf817af0ed52887b6ee60ccc0d1e60
Actual: d5b1cb5b5885aa265e8b758fb800ec8fd516076cb5346081fa462bdf241e028b
File: /Users/vino/Library/Caches/Homebrew/Cask/qq--5.1.0.dmg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
Perhaps the final file is delivered from different CDNs and the file is different (happened with some other apps before, like Visual Studio Code). If that is the case, it needs to be fixed upstream.

@caskroom/maintainers What `sha256` do you get for this file?

**Comment by alebcay** [comment]
```
▶ brew cask audit --download qq
==> Downloading http://dldir1.qq.com/qqfile/QQforMac/QQ_V5.1.0.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask qq
audit for qq: passed
```

```
▶ cdt hash "http://dldir1.qq.com/qqfile/QQforMac/QQ_V5.1.0.dmg"
######################################################################## 100.0%

SHA256:
936cf4c7699d6b12d8928d31f6b4a0ad4eaf817af0ed52887b6ee60ccc0d1e60
```

**Comment by vinoZHU** [comment]
@alebcay it does'nt work.

**Comment by alebcay** [comment]
Well, as you can see, it worked for me. That's all I know.

**Comment by jawshooah** [comment]
@vinoZHU: Download the DMG manually and see if you can mount it and install the app. If not, there's something going on upstream that we probably can't do anything about.

**Comment by jawshooah** [comment]
It's possible that the CDN they use provides different files depending on your geographical location. If that's the case, there's nothing we can do to fix it; someone will have to report the issue upstream.

**Comment by vinoZHU** [comment]
@jawshooah @alebcay @vitorgalvao  I can mount it by downloading the DMG manually.I changed the  sha256 value in my local qq.rb just now,it worked.Although I don't know why,thanks for all of your help.

**Comment by adidalal** [comment]
Seems to be resolved.

```
[~] > brew cask audit qq --download
==> Downloading http://dldir1.qq.com/qqfile/QQforMac/QQ_V5.1.1.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask qq
audit for qq: passed
```
