### ISSUE TITLE
brew cask upgrade

### ISSUE THREAD

**Issue by voxsim** [caskroom/homebrew-cask#23658]
I recently create a script to upgrade every package in my machine installed through brew cask.

Would be interesting add this functionality to homebrew-cask? Is it already in roadmap? Would be it useful if I try to code that and make a pull request?

PS This is the script:
```shell
#!/usr/bin/env bash

# get the list of installed casks
casks=( $(brew cask list) )

for cask in ${casks[@]}; do
  current="$(brew cask info $cask | sed -n '1p' | sed -n 's/^.*: \(.*\)$/\1/p')"
  installed=( $(ls /opt/homebrew-cask/Caskroom/$cask))
  if (! [[ " ${installed[@]} " == *" $current "* ]]); then
    echo "Upgrading $cask to v$current."
    (set -x; brew cask install $cask --force;)
  else
    echo "$cask v$current is up-to-date, skipping."
  fi
done
```

thanks in advance,
voxsim

**Comment by vitorgalvao** [comment]
This has been discussed multiple times. Please search for it for details, but:

+ Yes, we want to add `brew upgrade`.
+ No, we will not add your script because:
  + It is `bash`, and not ruby.

**Comment by vitorgalvao** [comment]
This has been discussed multiple times. Please search for it for details, but:

+ Yes, we want to add `brew upgrade`.
+ No, we will not add your script because:
  + It is `bash`, and not ruby.
  + It uses `list`, which [cannot be trusted at the moment](https://github.com/caskroom/homebrew-cask/issues/14058).
  + Other lesser reasons.

**Comment by voxsim** [comment]
@vitorgalvao when I stated 

> Would be it useful if I try to code that and make a pull request?

I was meaning code that in ruby!

Btw thanks for the issue I had a similar problem.

**Comment by vitorgalvao** [comment]
> I was meaning code that in ruby!

Then yes and no. Yes, a PR would be useful, but `upgrade` needs to be discussed first and other things (like finishing #13201) need to be done before we can focus on it and discuss how it will work.

**Comment by voxsim** [comment]
ok, i will follow the thread, for now thanks for your time.
