### ISSUE TITLE
Cask request: Nucleo

### ISSUE THREAD

**Issue by johndjameson** [caskroom/homebrew-cask#23707]
### Cask details

**Name** - Nucleo

**Homepage** - https://nucleoapp.com/

**License** - [License](https://nucleoapp.com/license/), [Extended License](https://nucleoapp.com/extended-license/)

**Download URL** - https://dl.devmate.com/co.ambercreative.Nucleoapp/Nucleo.zip

**Description** - A searchable, drag & drop library of 8000+ vector icons.

(Please and thank you 😉)

**Comment by yurikoles** [comment]
closed in #23797
