### ISSUE TITLE
brew cask edit fails with "Error: stack level too deep"

### ISSUE THREAD

**Issue by telamonian** [caskroom/homebrew-cask#23757]
I tried to install a cask and ran into a problem, and then when I tried to fix it I ran into another problem:

    $ brew cask info latexit
        latexit: 2.8.1
        LaTeXiT
        http://www.chachatelier.fr/latexit
        Not installed
        https://github.com/caskroom/homebrew-cask/blob/master/Casks/latexit.rb
        ==> Contents
        LaTeXiT.app (app)

    $ brew cask install latexit
        ...
        rl: (60) SSL certificate problem: Invalid certificate chain
        ...
        Error: Download failed on Cask 'latexit' with message: Download failed: https://www.chachatelier.fr/latexit/downloads/LaTeXiT-2_8_1.dmg
    
    $ brew cask edit latexit
        Error: stack level too deep
        /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/edit.rb:18
   
What's keeping me from being able to properly use `brew cask edit` here? I tried it with other formula as well, so it's not something specific to latexit.

Also I just ran `brew update` 5 minutes ago, if that helps.

**Comment by jramnani** [comment]
Neither create nor edit commands work for me.  Create will create the Formula file, but it fails when trying to invoke my editor.

It seems like the implementation of `exec_editor` is missing.
https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/cli/edit.rb#L18

I'm assuming that `exec_editor` should be executing a system command to fire up the editor?

**Comment by jramnani** [comment]
I can confirm that if I replace the method body of [`self.exec_editor`](https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/cli/edit.rb#L18) with a call to `system("/usr/bin/vim", "#{args[0].to_s}")`, an editor is opened, and I can edit the Cask.

That's obviously not the right way to do it.  But hopefully confirms the diagnosis.

What's the preferred way to shell out in homebrew-cask?

**Comment by jawshooah** [comment]
Confirmed this is a bug. Will fix in a bit unless someone beats me to it.
