### ISSUE TITLE
Is force install work appropriately

### ISSUE THREAD

**Issue by Luavis** [caskroom/homebrew-cask#23831]
I got sha256 mismatch error when I install genymotion in currently. As I wanted to install it immediately, I run install with ```$ brew cask install --force genymotion```. but it was not work.

So I wonder is ```--force``` option is ignore file checksum appropriately.

**Comment by vitorgalvao** [comment]
`--force` does not ignore checks. It just installs if other things are in the way (overwrite files, cask already installed, and the like).

**Comment by Luavis** [comment]
Then, Is there any option that ignore checksum?

**Comment by vitorgalvao** [comment]
No. If a cask has a wrong `sha256`, it needs to be fixed, not simply bypass the error.

**Comment by Luavis** [comment]
Thanks for your answer :)
