### ISSUE TITLE
Cask request: Kakaotalk

### ISSUE THREAD

**Issue by roy9120** [caskroom/homebrew-cask#23847]
### Cask details

(Please fill out as much as possible)

**Name** - Kakaotalk

**Homepage** - http://www.kakao.com/services/8/pc

**License** -

**Download URL** - https://itunes.apple.com/en/app/kakaotog/id869223134?mt=12

**Description** - Messenger widely used available on Mac PC & mobile

**Comment by Eitot** [comment]
This seems to be Mac App Store only.

**Comment by reitermarkus** [comment]
Like @Eitot said, unless there is a non Mac App Store download available, this cannot be added.

**Comment by roy9120** [comment]
Thank you guys. I'll keep note.
