### ISSUE TITLE
Hold core PRs due to core move

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [caskroom/homebrew-cask#23853]
Cask core code is being moved to Homebrew ([#725](https://github.com/Homebrew/brew/pull/725), #23852). Please do not merge any core-related PRs until merge is finished.
Context [here](https://github.com/caskroom/homebrew-cask/issues/14384)

**Comment by jawshooah** [comment]
Pinging @caskroom/maintainers for visibility.
