### ISSUE TITLE
Execute "brew cask info intellij-idea", cannot get the latest infoamation 

### ISSUE THREAD

**Issue by hellosky806** [caskroom/homebrew-cask#23887]
I execute the command "brew cask info intellij-idea", and get the result as **follows:**
_$brew cask info intellij-idea
intellij-idea: 2016.2.1
IntelliJ IDEA
https://www.jetbrains.com/idea/
/usr/local/Caskroom/intellij-idea/2016.2.1 (0B)
https://github.com/phinze/homebrew-cask/blob/master/Casks/intellij-idea.rb
==> Contents
  IntelliJ IDEA.app (app)_

However, according to the link (https://github.com/phinze/homebrew-cask/blob/master/Casks/intellij-idea.rb)  provided in the information, the version should be 2016.2.2.
I have treid "brew update", "brew cask  update", restarted the terminal and even the PC, it still doesn't work.

**Comment by jawshooah** [comment]
Did you bother to read the Reporting Bugs section of the readme? Please go do that and follow all of the instructions. I am almost certain your issue will resolve itself. If not, feel free to re-open the issue and let us know.
