### ISSUE TITLE
Allow only a single `uninstall` and `zap` stanza.

### ISSUE THREAD

**Issue by reitermarkus** [caskroom/homebrew-cask#23885]
This came to my attention in https://github.com/caskroom/homebrew-cask/pull/23878#discussion_r75231655.

Should multiple `uninstall` and `zap` stanzas be allowed? I don't think we have a single cask that uses more than one.

**Comment by jawshooah** [comment]
We should parse and handle them properly, but warn on either `audit` or `style`. Probably the latter, since it doesn't affect usability.

**Comment by jawshooah** [comment]
Going forward, and I think the Homebrew crew agrees, I think we should strive to keep DSL changes backward compatible whenever possible, and warn the user of deprecated forms on `audit` or `style` check.

**Comment by amyspark** [comment]
Can I take this up @reitermarkus ? I think I have a working patch for this check.

**Comment by reitermarkus** [comment]
@amyspark, yes, feel free!
