### ISSUE TITLE
Cask request: Wire

### ISSUE THREAD

**Issue by amingilani** [caskroom/homebrew-cask#23884]
### Cask details

Wire is a cross platform communications tools that supports end-to-end encrypted text messages, audio calls, and other things like doodles, file transfers, and giffy.

It's open source and super awesome

**Name** - Wire

**Homepage** - Wire.com

**License** - GPL for desktop

**Download URL** - https://itunes.apple.com/app/wire/id931134707?mt=12

**Compile from source** - https://github.com/wireapp/wire-desktop

**Description** - A cross platform communications app

**Comment by reitermarkus** [comment]
Is there a non Mac App Store download available? Otherwise this cannot be added.

**Comment by amingilani** [comment]
No, there isn't. Closing this request, and referencing it to the Wire team.

**Comment by lipis** [comment]
Thank you @amingilani for opening that issue. While we currently don't have a non App Store version but since more and more users are asking for it we might change the priority of that request :) 

Cheers..

**Comment by tomick** [comment]
Seams to Wire team started providing direct link to non-MAS version at GitHub.
https://github.com/wireapp/wire-desktop/releases/tag/macos%2F2.15.2750

@lipis Can you confirm that?

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37649
