### ISSUE TITLE
Cask request: PowerShell

### ISSUE THREAD

**Issue by docwhat** [caskroom/homebrew-cask#23895]
### Cask details

**Name** - PowerShell

**Homepage** - https://github.com/powershell/powershell

**License** - MIT https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt

**Download URL** - https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.9/powershell-6.0.0-alpha.9.pkg

**Description** -

> Microsoft PowerShell for Mac.  This is the full PowerShell and can connect with Windows or other systems running PowerShell (Linux or Mac).

More links:
https://msdn.microsoft.com/powershell
https://blogs.msdn.microsoft.com/powershell/2016/08/18/powershell-on-linux-and-open-source-2/

Guys, I don't recognize this universe.  Microsoft open-sourced (MIT License?!) PowerShell and ported it to Linux and Mac.  I feel dizzy.

**Comment by Hipska** [comment]
Shouldn't this be a normal brew formula as the source is available to download, so brew can compile it on install?

**Comment by reitermarkus** [comment]
@Hipska, you're right, in the long run, a Formula will definitely be a better option. Currently though, you first need to install the `.pkg` to even be able to build from source.

**Comment by Hipska** [comment]
Indeed, I just saw that when reading the compiling instructions.
