### ISSUE TITLE
Chromium build source is out of date, likely to not be continued

### ISSUE THREAD

**Issue by kevinburke** [caskroom/homebrew-cask#23891]
There is a new version of Chromium available - version 52 - but the version installed via homebrew-cask is still version 51. The download pulls from download-chromium.appspot.com, which has not been updated.

I asked in the #chromium-support IRC channel and was told by two people that the "last known good revision" build available from download-chromium.appspot.com is now considered a bad idea, and is unlikely to be updated in the future.

**Comment by jawshooah** [comment]
It was decided to use https://download-chromium.appspot.com in https://github.com/caskroom/homebrew-cask/issues/15357 after lengthy discussion. Is there a better canonical source to pull stable binaries from?

**Comment by kevinburke** [comment]
The only other place I've heard suggested is freesmug, which is currently available as freesmug-chromium. That build is up to date.

I've pasted our conversation in IRC; I don't know any more than that about where would be a good build to pull from.

https://gist.github.com/kevinburke/50955a78020c9d6990b0d801769c8c7e

**Comment by anantshri** [comment]
the msot stable build that i have used is freesmug. but the current issue is with each new release there is a seperate PR that needs to be made to homebrew-cask and then a cask update and then only installations will work or upgrade's will happen. Is there a way by which we can may be automate this process. (auto updatation of cask when new release comes out)

**Comment by wfdd** [comment]
See also beaufortfrancois/download-chromium#19.

**Comment by vitorgalvao** [comment]
If there’s no better resolution in a few days, we’ll just [delete the cask](https://github.com/caskroom/homebrew-cask/pull/24288).

**Comment by wfdd** [comment]
Why delete it outright?  There remains the option to use continuous builds.

**Comment by vitorgalvao** [comment]
> There remains the option to use continuous builds.

Isn’t that what it [already tries to do](https://github.com/caskroom/homebrew-cask/blob/e5053b63b699606f7cfc114874bc382616916123/Casks/chromium.rb#L6)?

**Comment by wfdd** [comment]
They call them 'snapshots' instead, IIRC.

**Comment by wfdd** [comment]
@beaufortfrancois, @paulirish, would you have any input?

**Comment by beaufortfrancois** [comment]
You may want to use Snapshots builds (https://download-chromium.appspot.com/?platform=Mac&type=snapshots) instead of Continuous builds (https://download-chromium.appspot.com/?platform=Mac&type=continuous)

**Comment by vitorgalvao** [comment]
> You may want to use Snapshots builds (https://download-chromium.appspot.com/?platform=Mac&type=snapshots) instead of Continuous builds (https://download-chromium.appspot.com/?platform=Mac&type=continuous)

[PR ready](https://github.com/caskroom/homebrew-cask/pull/24290/) if there are no objections.

**Comment by paulirish** [comment]
PR lgtm. Thanks!
