### ISSUE TITLE
What a mess!

### ISSUE THREAD

**Issue by quantegy** [caskroom/homebrew-cask#23919]
`brew search qt-creator`

yields:

`Caskroom/cask/qt-creator                 Caskroom/versions/qt-creator`

`brew uninstall Caskroom/cask/qt-creator`

yields:

`Error: No available formula with the name "caskroom/cask/qt-creator"`

`brew cask list`

yields:

`qt-creator`

Very confused, and I need to uninstall this software. Any help would be appreciated.

**Comment by jawshooah** [comment]
`brew cask uninstall qt-creator`
