### ISSUE TITLE
Documentation and hacking links are returning `Page not Found`

### ISSUE THREAD

**Issue by miguelarauj1o** [caskroom/homebrew-cask#23921]
Hey, [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc) and [hacking.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/hacking.md) are returning **Page not found**.

**Comment by miguelarauj1o** [comment]
Sorry about changed issue title so many times.

**Comment by jawshooah** [comment]
Fixed in #23920.

**Comment by reitermarkus** [comment]
Should be back now.

**Comment by miguelarauj1o** [comment]
nice!
