### ISSUE TITLE
Migrate `homebrew-binary` Formulas to Casks

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#23938]
As a (further) continuation of https://github.com/caskroom/homebrew-cask/issues/15603

All formulas from https://github.com/Homebrew/homebrew-binary should have Casks created for them.

@MikeMcQuaid Is there a `migrations.json` or similar to facilitate this move?

**Comment by MikeMcQuaid** [comment]
@adidalal Yup, a file like https://github.com/Homebrew/homebrew-core/blob/master/tap_migrations.json in the homebrew-binary repo root listing where formulae are moved to in the PR in which they are deleted. That means when people `brew update` and have them installed it'll migrate them over.

**Comment by MikeMcQuaid** [comment]
> All formulas from https://github.com/Homebrew/homebrew-binary should have Casks created for them.

To save you time/help you prioritise here are the analytics for Homebrew Binary installs since records began:

<img width="789" alt="screen shot 2016-08-23 at 08 47 36" src="https://cloud.githubusercontent.com/assets/125011/17884119/51a3647e-690e-11e6-8c5e-0fa53711250f.png">

Anything with 0️⃣ installs there can probably be boneyarded instead of Casked.

**Comment by MikeMcQuaid** [comment]
@adidalal Note that once https://github.com/Homebrew/brew/pull/1682 has made it into a new tag (1.1.6) then we're able to migrate to new Homebrew Cask names when doing a tap migration. See https://github.com/Homebrew/homebrew-binary/pull/359 for an example of this.

**Comment by adidalal** [comment]
Excellent, thanks for the update

**Comment by MikeMcQuaid** [comment]
@adidalal I've merged that and you can follow that pattern to migrate anything else too.

**Comment by miccal** [comment]
This is now complete - thanks go out to @adidalal, @MikeMcQuaid and @vitorgalvao for their help in migrating the relevant formula to Cask.
