### ISSUE TITLE
Bug report: "Error: Unknown command: cask" after #23852

### ISSUE THREAD

**Issue by xinan** [caskroom/homebrew-cask#23934]
This issue seems to happen only after #23852 was merged. I did a `git reset --hard` to reset `/usr/local/Library/Taps/caskroom/homebrew-cask` to a commit just before the merge commit and everything worked well. However, if I reset it to the merge commit, it starts to have this error.

#### Description of issue
`brew cask` returns
```
Error: Unknown command: cask
```

The issue persists after trying all the commands in the "pre-bug-report":
```
$ brew update; brew cleanup; brew cask cleanup
Already up-to-date.
Removing: (...)
==> This operation has freed approximately 969.5M of disk space.
==> Removing cached downloads
(...)
==> This operation has freed approximately 401.9M of disk space.

$ brew uninstall --force brew-cask; brew update
Already up-to-date.

$ brew untap phinze/cask; brew untap caskroom/cask; brew update
Error: No available tap phinze/cask.
Untapping caskroom/cask... (3,781 files, 74.8M)
Untapped 0 formulae
Already up-to-date.

$ brew cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3379, done.
remote: Compressing objects: 100% (3361/3361), done.
remote: Total 3379 (delta 37), reused 439 (delta 12), pack-reused 0
Receiving objects: 100% (3379/3379), 1.14 MiB | 812.00 KiB/s, done.
Resolving deltas: 100% (37/37), done.
Checking connectivity... done.
Tapped 0 formulae (3,386 files, 3.5M)
Error: Unknown command: cask
```

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
Error: Unknown command: cask
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
Error: Unknown command: cask
```
</details>

**Comment by xinan** [comment]
Also, I realised that `brew update` doesn't rebase `/usr/local/Library/Taps/caskroom/homebrew-cask` to the latest master. My branch was 306 commits behind master even after `brew update`. 

So `brew cask` was working. I didn't want to update the repo manually although it seems quite outdated. 

However, I was trying to update the `flux` cask (#23933), the `cask-repair` script automatically pulls the repo and causes `brew cask` to break (which causes the script itself to break because it needs `brew cask`). So in the end I had to reset this repo to a old commit, and clone another copy of the repo elsewhere to submit the update.

**Comment by adidalal** [comment]
@jawshooah @reitermarkus I haven't been looking at the transition in too much detail but I also ran into the same issue (and I'm sure others will)

Thoughts/possible resolutions?

**Comment by jawshooah** [comment]
This likely has more to do with `brew` being unable to find `cask` than anything inherent to `cask` itself. @MikeMcQuaid any idea what could be going on here?

**Comment by adidalal** [comment]
Aha, I found the bug, it was a `brew` issue.

@xinan, try the following `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`

**Comment by xinan** [comment]
🎉 It worked! So what's the problem here?

**Comment by jawshooah** [comment]
Ah, yup, it's right at the top of Homebrew's [readme](https://github.com/Homebrew/brew/blob/master/README.md).

**Comment by adidalal** [comment]
@xinan Homebrew error, it wasn't updating, even though it reported as being up to date. Making an FAQ right now; will close this issue after I push through the README change.

**Comment by jawshooah** [comment]
@xinan There was a bad commit that screwed up `brew update` for anyone who ran it during a particular time window a week or so ago.

**Comment by xinan** [comment]
I see! Thanks for the info! I should have checked homebrew page first. 😅 

Seems that my crontask that updates brew every hour fired back at me. If I've been running it manually I would have noticed that it always says "Already up to date".

**Comment by adidalal** [comment]
Updated Reporting Bugs section!
