### ISSUE TITLE
Cask request: r-gui

### ISSUE THREAD

**Issue by strubleca** [caskroom/homebrew-cask#23954]
### Cask details

(Please fill out as much as possible)

**Name** - `r-gui`

**Homepage** -  https://cloud.r-project.org/bin/macosx/

**License** - GPL-2, plus additional in COPYRIGHTS file.

**Download URL** - https://cloud.r-project.org/bin/macosx/Mac-GUI-1.68.tar.gz

**Description** - A native Mac GUI for the R Project on OS X.

**Comment by adidalal** [comment]
How bad is the (now removed) r.rb cask? Does it need a full rewrite or is it relatively correct?

**Comment by reitermarkus** [comment]
According to https://github.com/caskroom/homebrew-cask/pull/23584 I think simply restoring the removed `r` and renaming it to `r-gui` is fine.

**Comment by strubleca** [comment]
That's not my understanding of the discussion in #23584 . The removed `r` cask contains the entire R distribution. It was removed to avoid duplication with the `r` homebrew formula. My understanding of the decision was to reinstate only the R.app GUI component as a cask.

**Comment by adidalal** [comment]
We're adding in the cask back - the pkg contains everything, plus the gui. We're keeping it as its vendor supplied, and fully supported upstream

**Comment by strubleca** [comment]
Ah, great! There was nothing wrong with the old cask, so renaming it to `r-gui` should be fine.

**Comment by pvtmert** [comment]
btw the link is (tar.gz) sources for gui, other package contains full application and other stuff (as stated) so maybe decompressing pkg and moving app out solves it (without conflict)?
