### ISSUE TITLE
CONTRIBUTING instructions incomplete

### ISSUE THREAD

**Issue by Beefalo** [caskroom/homebrew-cask#23975]
Assuming the instructions given in https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask aim to be complete and should execute correctly if followed.

If so, then a preliminary step is missing that is:
- Make sure github account has sshkeys added

**Comment by adidalal** [comment]
@Beefalo That's a git config issue, and a bit out of the scope of CONTRIBUTING. Some people do actually use username/password or the ghi helper - no need to assume sshkeys.

Thanks for the suggestion though, would adding a link to https://help.github.com/articles/set-up-git/ be better? Closing the issue, but let me know your opinion!
