### ISSUE TITLE
iPartition seems to be a pirate or commercial only software 

### ISSUE THREAD

**Issue by shayneoneill** [caskroom/homebrew-cask#24042]
It seems inappropriate that iPartition is installable via brew when it is unuseable without a serial and appears to install some sort of DRM (or at least it claims to).

Is this a violation of homebrews policy? Should at least some sort of warning be provided?

**Comment by reitermarkus** [comment]
> it is unuseable without a serial

Well, it's paid software which requires a license. I don't see why this would this be a violation of our policy.

**Comment by shayneoneill** [comment]
Ok, maybe I misunderstand then. Shouldn't paywalled software be marked as such? Its pretty much the only hit when searching homebrew for partitioning software, and then it waits until its installed before revealing that it costs money.

**Comment by jawshooah** [comment]
@shayneoneill It's only deceptive if you assume that any software available through Homebrew-Cask is free to begin with, which is not a safe assumption by any means, nor one that we have ever encouraged.

We are not a discoverability service, nor do we intend to become one. It is expected that you know what you are installing when you install it.

You can easily run `brew cask home ipartition` to visit their homepage. Had you done so, it would have been obvious that this is commercial software.
