### ISSUE TITLE
brew cask install `brew cask list` doesn't work anymore

### ISSUE THREAD

**Issue by therealprof** [caskroom/homebrew-cask#24043]
#### Description of issue

I used to do
```
brew cask install `brew cask list`
```

to check all casks for required updates.

Originally this would update all outdated casks.

After the switch from linking apps to moving them a while ago this would at least tell me that casks are outdated and I'd have to install them with --force. 

But since a week or so updates are not recognised at all anymore so I'm completely in the dark whether software needs to be updated or still is up-to-date.

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision df21e; last commit 2016-08-25)
Homebrew/homebrew-core (git revision 2674; last commit 2016-08-25)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
0.60.0 (git revision 4947; last commit 3 hours ago)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/egger/Library/Caches/Homebrew/Cask
1 files, 69.5M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3268
==> Contents of $LOAD_PATH:
/usr/local/Library/Homebrew/cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/egger/perl5/bin:/usr/local/opt/llvm36/bin:/usr/local/opt/llvm/bin:/usr/local/opt/coreutils/libexec/gnubin:/opt/local/libexec/gnubin:/usr/texbin:/usr/local/opt/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Xcode.app/Contents/Applications :/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/usr/local/opt/fzf/bin:/usr/local/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Library/Homebrew/cask/cmd:/usr/local/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="de_DE.UTF-8"
==> Running As Privileged User:
No
```
</details>

**Comment by reitermarkus** [comment]
This is because `brew cask list` was broken before and is fixed now. Your command above was relying on the fact that `brew cask list` wouldn't show a cask as installed when a newer version was available.

**Comment by therealprof** [comment]
That is not correct. `brew cask list` works exactly the same as before. The problem is that `brew cask install` does not detect that a cask is outdated anymore.

**Comment by therealprof** [comment]
For instance:
```
# brew cask install freesmug-chromium
Warning: A Cask for freesmug-chromium is already installed. Add the "--force" option to force re-install.
````

```
# brew cask info freesmug-chromium
freesmug-chromium: 52.0.2743.116
http://www.freesmug.org/chromium
...
/usr/local/Caskroom/freesmug-chromium/51.0.2704.63 (does not exist)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.79 (does not exist)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.84 (3 files, 298.6K)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.103 (3 files, 298.6K)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.106 (3 files, 298.6K)
/usr/local/Caskroom/freesmug-chromium/52.0.2743.82 (115K)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/freesmug-chromium.rb
==> Name
Chromium
==> Artifacts
Chromium.app (app)
```

As you can see it actually knows that it is outdated because the directory doesn't exist but it doesn't warn about that fact anymore (before it would download and extract it but not move it to /Applications because a binary of the same name exists already). Usually I saw the warning and then did the following step:

```
# brew cask install --force freesmug-chromium
==> Downloading https://downloads.sourceforge.net/osxportableapps/Chromium_OSX_52.0.2743.116.dmg
######################################################################## 100,0%
==> Verifying checksum for Cask freesmug-chromium
==> It seems there is already an App at '/Applications/Chromium.app'; overwriting.
==> Removing App: '/Applications/Chromium.app'
==> Moving App 'Chromium.app' to '/Applications/Chromium.app'
🍺  freesmug-chromium was successfully installed!
```

And here's the info after the forced upgrade:

```
# brew cask info freesmug-chromium
freesmug-chromium: 52.0.2743.116
http://www.freesmug.org/chromium
...
/usr/local/Caskroom/freesmug-chromium/51.0.2704.63 (does not exist)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.79 (does not exist)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.84 (3 files, 298.6K)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.103 (3 files, 298.6K)
/usr/local/Caskroom/freesmug-chromium/51.0.2704.106 (3 files, 298.6K)
/usr/local/Caskroom/freesmug-chromium/52.0.2743.82 (115K)
/usr/local/Caskroom/freesmug-chromium/52.0.2743.116 (115K)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/freesmug-chromium.rb
==> Name
Chromium
==> Artifacts
Chromium.app (app)
```

**Comment by reitermarkus** [comment]
> As you can see it actually knows that it is outdated because the directory doesn't exist but it doesn't warn about that fact anymore

This directory not existing has nothing to do with the cask being outdated. This just means that that specific version was installed at some point, but the versioned directory does not exist anymore.

I'm sorry, but there is currently no official way to upgrade casks. 

The best you could currently do is call `brew cask list --versions`, and then comparing the version of each cask with `brew cask _stanza version {cask}`.

Also, instead of `install --force`, I suggest using `uninstall --force` followed by `install`, as this will also remove the old versions from the caskroom.

**Comment by therealprof** [comment]
> This directory not existing has nothing to do with the cask being outdated. This just means that that specific version was installed at some point, but the versioned directory does not exist anymore.

I agree, but if the directory with the latest version does not exist it still means that the latest version was not installed by homebrew. In case of casks not marked as auto-update this is something that I would expect homebrew being able to flag.

> I'm sorry, but there is currently no official way to upgrade casks.

I'm sorry to hear that. But nonetheless this change  in behaviour for `install` is a **huge** regression in my eyes.

> The best you could currently do is call brew cask list --versions, and then comparing the version of each cask with brew cask _stanza version {cask}.

Ewww....

**Comment by jawshooah** [comment]
> Ewww....

We know. We have made it abundantly clear time and time again that **there is no officially supported way of upgrading Casks**. Hacky workarounds like this are all we have until `brew cask upgrade` is implemented.

**Comment by adidalal** [comment]
Try out https://github.com/buo/homebrew-cask-upgrade

**Comment by therealprof** [comment]
@adidalal Thanks a lot, that works beautifully.
