### ISSUE TITLE
Feature request: Warn and prompt users when installing from SourceForge

### ISSUE THREAD

**Issue by alfiedotwtf** [caskroom/homebrew-cask#24062]
### Description of feature/enhancement

When installing apps that are hosted on SourceForge, can a warning be shown saying SourceForge has been known to host malware? If the user is still willing to install the app, can a very verbose command line switch be used to indicate they are aware of this e.g --install-possible-malware

### Justification

Installing apps from known malware distributors could tarnish Homebrew/Caskroom's reputation.

### Example use case

brew install Caskroom/cask/freemind

**Comment by loganabbott** [comment]
Logan Abbott from SourceForge here. My company acquired SourceForge in January and immediately removed all bundled adware installers, and we now scan all projects for malware with Bitdefender and ESET. Some sources:

http://arstechnica.com/information-technology/2016/06/under-new-management-sourceforge-moves-to-put-badness-in-past/

http://fossforce.com/2016/05/sourceforge-tightens-security-bitdefender-scans/

**Comment by jawshooah** [comment]
Thanks for the info @loganabbott, good to know :+1:

@alfiedotwtf This issue has been discussed several times already. I'm on my phone at the moment so can't easily provide links, but just search the issues for "malware" or "adware" and you'll find them.

**Comment by alfiedotwtf** [comment]
@jawshooah I did search the issue tracker for "sourceforge" but found nothing, but sorry for the dup
