### ISSUE TITLE
Bug report: mysql-utilities needs update to 1.6.4

### ISSUE THREAD

**Issue by mengesb** [caskroom/homebrew-cask#24076]
#### Description of issue

mysql-utilities 1.5.6 incompatible with mac os x el capitan (10.11). Version 1.6.4 is compatible

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
==> Satisfying dependencies
Error: Cask mysql-utilities depends on macOS release <= 10.10, but you are running release 10.11.
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
[paste output here]
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libjson-c.2.dylib
    /usr/local/lib/libykclient.3.dylib
    /usr/local/lib/libykpers-1.1.dylib
    /usr/local/lib/libyubikey.0.dylib
```
</details>

**Comment by adidalal** [comment]
Closing as discussion can happen in the opened PR.
