### ISSUE TITLE
Bug report:

### ISSUE THREAD

**Issue by privettoli** [caskroom/homebrew-cask#24082]
Sorry, don't have time to fill the right form, you can delete this if it's useless.
I tried to run the script, didn't help.

Installed versions of dockertoolbox: 
1.11.2
Cask info for dockertoolbox
dockertoolbox: 
/usr/local/Caskroom/dockertoolbox/1.11.2 (178.2M)
Error: Invalid tap name '/'Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Homebrew/tap.rb:29:in `fetch'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/info.rb:53:in `github_info'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/info.rb:21:in `info'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/info.rb:9:in `block in run'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/info.rb:5:in `each'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/info.rb:5:in `run'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Library/Homebrew/brew.rb:97:in `<main>'

**Comment by adidalal** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by toddpi314** [comment]
Just started seeing this on OSX.
