### ISSUE TITLE
Cask request: (Fix) Charles

### ISSUE THREAD

**Issue by DustinVenegas** [caskroom/homebrew-cask#24144]
### Cask details

The cask in question in Charles to install [Charles Proxy](https://www.charlesproxy.com/). 

The Cask is currently broken because Charles Proxy requires a different type of URL. The new URLs require making a post to a page and parsing the data. This seems a bit brittle so in lieu of making a PR, I wanted to ask what to do first.

**Comment by adidalal** [comment]
What's wrong with the current URL?
Yes, the download page serves up `https://charles-52f.kxcdn.com/release/4.0/charles-proxy-4.0.dmg`, but the URL in the Cask still seems to be valid

**Comment by DustinVenegas** [comment]
You are correct @adidalal. It appears that older versions are not working. The latest 3x and 4x are both OK but 3.11.2 returns a 404. I believe there's nothing to do unless we want to put a warning in about updating if a 404 is detected.
