### ISSUE TITLE
run preflight script/commands?

### ISSUE THREAD

**Issue by pvinis** [caskroom/homebrew-cask#24153]
I am making my own Cask Tap, and I need to run a command on the `.app` before it's move to `/Applications`. How can I do that? I found `preflight` but it has no way to run commands. I need to `cp` some files into the `.app`.

**Comment by reitermarkus** [comment]
You can put any Ruby code you want inside `preflight`. Or use `system` to run any Terminal command you want.

**Comment by pvinis** [comment]
ah cool. didnt get it at first. thank you.
