### ISSUE TITLE
Accurate version of microsoft-office

### ISSUE THREAD

**Issue by nuomi1** [caskroom/homebrew-cask#24157]
The [file](https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_Installer.pkg) form [GitHub](https://github.com/caskroom/homebrew-cask/blob/55abc1b2401d1de5065eb2d8b020b6bb0d0d6d8f/Casks/microsoft-office.rb#L5) is inaccurate and outdated.
This [website](http://macadmins.software/) is listed many accurate versions of microsoft-office and SHA1 Hash.

```
➜  ~ curl -I https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_Installer.pkg
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Connection: keep-alive
Content-Disposition: attachment; filename=microsoft_office_2016_installer.pkg
Date: Mon, 29 Aug 2016 02:03:41 GMT
Powered-By-ChinaCache: HIT from 010123b3g3
Powered-By-ChinaCache: MISS from CHN-DJ-3-3WC
X-Powered-By: ASP.NET
Expires: Thu, 01 Sep 2016 02:03:41 GMT
X-CID: 6
Cache-Control: public, max-age=259200
Content-Length: 1469751794
Last-Modified: Tue, 15 Mar 2016 15:55:28 GMT
Accept-Ranges: bytes
Server: Microsoft-IIS/7.5
CC_CACHE: TCP_MISS

➜  ~ curl -i https://go.microsoft.com/fwlink/\?linkid\=525133
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: http://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.25.0_160817_Installer.pkg
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Content-Length: 0
Date: Tue, 30 Aug 2016 12:09:53 GMT
Connection: keep-alive

➜  ~ curl -I http://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.25.0_160817_Installer.pkg
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Connection: keep-alive
Content-Disposition: attachment; filename=microsoft_office_2016_15.25.0_160817_installer.pkg
Cache-Control: public, max-age=259200
Date: Mon, 29 Aug 2016 03:43:13 GMT
Powered-By-ChinaCache: MISS from 010123b3g2
Powered-By-ChinaCache: HIT from CHN-TH-3-3WC
Server: Microsoft-IIS/7.5
Expires: Thu, 01 Sep 2016 04:05:53 GMT
X-CID: 6
Content-Length: 1578726755
Last-Modified: Wed, 17 Aug 2016 17:56:55 GMT
Age: 116815
Accept-Ranges: bytes
X-Powered-By: ASP.NET
CC_CACHE: TCP_HIT
```

**Comment by adidalal** [comment]
`https://go.microsoft.com/fwlink/?linkid=525133` forwards to the current latest version of office, which is at `http://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_Installer.pkg`

There is nothing wrong with the Cask. You would have to use the MAU updater or clear the cache and `brew cask install microsoft-office.rb --force` to get updates.

**Comment by nuomi1** [comment]
```
https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_Installer.pkg
Content-Length: 1469751794
Last-Modified: Tue, 15 Mar 2016 15:55:28 GMT
```
```
http://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.25.0_160817_Installer.pkg Last-Modified: Wed, 17 Aug 2016 17:56:55 GMT
Content-Length: 1578726755
Last-Modified: Wed, 17 Aug 2016 17:56:55 GMT
```

**Comment by yangfan3333** [comment]
@nuomi1  大神请问现在还有什么工具可以下载爱奇艺VIP视频吗。。you-get-0.4.536-win32-full.7z 

最新的版本都下载不了。

**Comment by reitermarkus** [comment]
It's always better to have a versioned cask, in this case the versioned download even seems to be more up-to-date than the `latest` one.

**Comment by adidalal** [comment]
We'll conflict with MAU.

Changing the url to `https://go.microsoft.com/fwlink/?linkid=525133` but keeping the cask versionless seems to be a better? solution. (`auto updates true` doesn't do anything yet)

**Comment by jawshooah** [comment]
How would we conflict with MAU? Why would installing the most recent release prevent MAU from functioning properly?

**Comment by adidalal** [comment]
I believe you end up reinstalling the entire office suite, instead of just the updated app. Not sure it's a huge concern but may be, for users with limited bandwidth?

**Comment by jawshooah** [comment]
Ah, I see what you mean. An update might just include a bugfix in Word or something, but the user would have to re-download all of Office to upgrade.

Honestly, I think that's fine for now. We don't have upgrade functionality yet, so that really shouldn't be a factor here, especially with `auto_updates`. The important thing is that people running `brew cask install microsoft-office` get a recent version, not one that's almost a year old. Those who do force the upgrade once we've implemented it, or those who regularly use buo's plugin for upgrades, probably aren't overly concerned with bandwidth.

**Comment by adidalal** [comment]
Sounds good to me - won't be around a computer too much this holiday weekend but can submit the PR if no one has by Tuesday.

**Comment by adidalal** [comment]
Ah, one more issue - how best to handle regional redirects?

US - http://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.25.0_160817_Installer.pkg

Europe - http://officecdn.microsoft.com/db/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.25.0_160817_Installer.pkg

Asia - http://officecdn.microsoft.com/sg/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.25.0_160817_Installer.pkg

**Comment by reitermarkus** [comment]
Also,

> but the user would have to re-download all

really applies to every versioned cask. Of course, in this case it is particularly huge.

**Comment by vitorgalvao** [comment]
Can this be closed with https://github.com/caskroom/homebrew-cask/pull/24520?

**Comment by reitermarkus** [comment]
@vitorgalvao, yes.
