### ISSUE TITLE
Bug uninstalling Skype

### ISSUE THREAD

**Issue by ourobourbon** [caskroom/homebrew-cask#24174]
On attempting to `brew cask uninstall skype` I get this error message:

    Cask 'skype' definition is invalid: Bad header line: '{:v1=>"skype"}' does not match file name

This is odd because the formula file name is, in fact `skype.rb`.

However I was able to `brew cask install --force skype && brew cask uninstall skype` which worked fine. Not sure what the source of the bug is, but thought it might be worth reporting.

**Comment by jawshooah** [comment]
The problem is that the Cask syntax has changed in a non-backwards-compatible way since you installed Skype, and we recently changed `uninstall` to use the Cask file from the time of install rather than the most recent file.

Long story short, this is a known issue. Thanks for the report!
