### ISSUE TITLE
Cask request: re-add git-annex

### ISSUE THREAD

**Issue by MoritzFago** [caskroom/homebrew-cask#24214]
First I want to state, that i am confused, git-annex was removed from the cask with the PR #22706, because it is also available from homebrew core. I think thats not true, because the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-annex.rb) in core only installs the command line utility, where the former formula in the cask also installed the [.app](http://git-annex.branchable.com/install/OSX/).

I think the cask was useful and would link to see it re-added.
### Cask details

**Name** git-annex

P.S i omitted the rest because there is already a formula for it in the git history.

**Comment by jawshooah** [comment]
The .app is just a wrapper around the web GUI, which you can access from the CLI as `git annex webapp`. It adds no real value to the formula, so there's no reason to have both.
