### ISSUE TITLE
Apps not present in /usr/local/Caskroom/<formula>/<version>

### ISSUE THREAD

**Issue by AlessioXM** [caskroom/homebrew-cask#24243]
Hello there, I was just reinstalling (updating) Filezilla today.
Whilst everything's fine with the /Applications app, the original app in /usr/local/Caskroom/filezilla/3.21.0 does not exist.

This is not a problem with Filezilla, however. I tried the very same thing with Macdown (v0.6), still no app in the Caskroom folder

**Comment by jawshooah** [comment]
That's because we changed our installation behavior for apps and most other artifact types from linking to moving. We no longer keep app files in the Caskroom.

**Comment by AlessioXM** [comment]
Nice to know. So there will just be empty folder in order to point out which version(s) is/are installed?

**Comment by jawshooah** [comment]
Yes, and any other files that may have been bundled in the archive with the app, like a readme or other metadata.
