### ISSUE TITLE
"brew cask install <cask>" no longer updates cask

### ISSUE THREAD

**Issue by jwhite007** [caskroom/homebrew-cask#24242]
This may be intentional; however, I like being able to update my casks with a script. I simply don't want to deal with the GUI message telling me that a new update is available and asking me if I'd like to upgrade. It seems to me that the whole point of Homebrew Cask is to obviate having to deal with the GUI. I would very much like a way to upgrade the casks that I've installed using the CLI. Thanks.

**Comment by jawshooah** [comment]
Please search the issues before opening a new one. Cask upgrades have been discussed to death already. It's a desirable feature that is complicated by the particularities of all the various artifact types we handle, and has not been officially implemented yet.

An **unofficial** solution would be something like [brew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade).
