### ISSUE TITLE
Cask request: Exponent Development Environment (XDE)

### ISSUE THREAD

**Issue by designorant** [caskroom/homebrew-cask#24295]
### Cask details

**Name** - Exponent Development Environment (XDE)

**Homepage** - https://getexponent.com/

**License** - MIT - https://github.com/exponentjs/xde/blob/master/LICENSE

**Download URL** - https://xde-updates.exponentjs.com/download/mac

**Description** - Exponent is a mobile app development tool that enables you to build high quality native iOS and Android applications using JavaScript and deploy them effortlessly.

**Comment by adamo57** [comment]
is there any way that I can get assigned to this?

**Comment by jawshooah** [comment]
@adamo57 Only maintainers can be assigned to issues. But feel free to whip up a PR and we'll review it!

**Comment by adamo57** [comment]
I have a PR for this!
