### ISSUE TITLE
Cask request: UnGoogled Chromium

### ISSUE THREAD

**Issue by chovy** [caskroom/homebrew-cask#24326]
### Cask details

**Name** -

ungoogled-chromium

**Homepage** -
https://github.com/Eloston/ungoogled-chromium

**License** -

**Download URL** -

https://github.com/Eloston/ungoogled-chromium/blob/master/BUILDING.md

**Description** -

https://github.com/Eloston/ungoogled-chromium/blob/master/BUILDING.md

It's chromium with privacy patch that strips out all google related code.

**Comment by Git-Jiro** [comment]
Hi, I would like to tackle this issue for hacktoberfest!

**Comment by jawshooah** [comment]
Go right ahead! We have [documentation](https://github.com/caskroom/homebrew-cask/blob/0efc2415350ebdffc0ec2c2fbdc345de8586ff66/doc/development/adding_a_cask.md) to help you get started, and we're here if you have any questions.

**Comment by reitermarkus** [comment]
Added in https://github.com/caskroom/homebrew-cask/pull/24969.
