### ISSUE TITLE
Cask request: minishift

### ISSUE THREAD

**Issue by lburgazzoli** [caskroom/homebrew-cask#24330]
### Cask details

Notes:
- Original homebrew-cask [PR](https://github.com/caskroom/homebrew-cask/pull/24260)
- homebrew-core [discussion](https://github.com/Homebrew/homebrew-core/issues/4531)

**Name** -
minishift

**Homepage** -
https://github.com/jimmidyson/minishift

**License** -
Apache v2
https://github.com/jimmidyson/minishift/blob/master/LICENSE

**Download URL** -
https://github.com/jimmidyson/minishift/releases

**Description** -
Minishift is a tool that makes it easy to run OpenShift locally. Minishift runs a single-node OpenShift cluster inside a VM on your laptop for users looking to try out OpenShift or develop with it day-to-day.

**Comment by vitorgalvao** [comment]
Thank you for the submission to homebrew. As it was refused, simply resubmit your old PR (please link back to this issue when you do) and we will accept it.
