### ISSUE TITLE
Added mpv

### ISSUE THREAD

**Issue by avelino** [caskroom/homebrew-cask#24349]
https://mpv.io/

**Comment by vitorgalvao** [comment]
[Rejected casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md).

Also, you did not follow the [guide](https://github.com/caskroom/homebrew-cask#requests). You were specifically asked to, in the issue template. Next time, please follow the guide, or the issue will be closed without review.
