### ISSUE TITLE
Hash mismatch for helm 2.0.0-alpha.4

### ISSUE THREAD

**Issue by tback** [caskroom/homebrew-cask#24414]
A few days ago @SomeoneWeird reported this in https://github.com/caskroom/homebrew-cask/pull/24310:

> I get a different shasum when downloading this file.
> 
> ➜  /tmp gsha256sum helm-v2.0.0-alpha.4-darwin-amd64.tar.gz
> fcba539993b7b1459a5c2e02c93e87c7f2fdb5fea941b4a0bc3367e58f85c47b  helm-v2.0.0-alpha.4-darwin-amd64.tar.gz
> ➜  brew cask install helm
> ==> Downloading https://github.com/kubernetes/helm/releases/download/v2.0.0-alpha.4/helm-v2.0.0-alpha.4-darwin-amd64.tar.gz
> ######################################################################## 100.0%
> ==> Verifying checksum for Cask helm
> ==> Note: running "brew update" may fix sha256 checksum errors
> Error: sha256 mismatch
> Expected: 4e504ca7b491609e1402bf583632516ce44fddfeadf02856b440ca5a6644eeb1
> Actual: fcba539993b7b1459a5c2e02c93e87c7f2fdb5fea941b4a0bc3367e58f85c47b
> File: /Users/adam/Library/Caches/Homebrew/Cask/helm--2.0.0-alpha.4.tar.gz
> To retry an incomplete download, remove the file above.

I just asked the helm project if they changed something in https://github.com/kubernetes/helm/issues/1180 . I'll fix this as soon as I know what happened.

**Comment by vitorgalvao** [comment]
This isn’t uncommon. Usually it occurs when upstream releases a new binary but keeps the version, and it’s likely nothing to worry about. But it’s still good to check like you’re doing. Thank you.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/24416.
