### ISSUE TITLE
Cask request: Mixed in Key

### ISSUE THREAD

**Issue by danielbayley** [caskroom/homebrew-cask#24436]
### Cask details
**Name** - Mixed in Key
**Homepage** - http://mixedinkey.com
**License** - Commercial
**Download URL** - ?
**Description** - World's Best Key Detection

**Comment by adidalal** [comment]
Looks like a walled download link, sadly. Can't get one without buying a lic.

**Comment by danielbayley** [comment]
@adidalal Ok, well since I already have a license I’m instead trying to add this with `tap`. But how might I be able to use my private download link in a cask without it being publicly visible?

**Comment by jawshooah** [comment]
Why not just make a private repo and tap it?

**Comment by danielbayley** [comment]
Never mind… I ended up just using an environment variable.
