### ISSUE TITLE
Cask request: Update VMWare Fustion to 8.5.0-4352717

### ISSUE THREAD

**Issue by fuzzyroddis** [caskroom/homebrew-cask#24467]
### Cask details

vmware-fusion.rb Already exists but is not up to date.
I'm not sure if it is as simple as changing things to:
```
version '8.5.0-4352717'
sha256 '2a19b1fd294e532b6781f1ebe88b173ec22f4b76d12a467b87648cc7ff8920f1'
```

Because of all the `Binary` directives.
eg. `binary "#{appdir}/VMware Fusion.app/Contents/Library/vmnet-bridge"`

I don't want to break anything 👍 

Download URL in the Cask is still correct and should link to https://download3.vmware.com/software/fusion/file/VMware-Fusion-8.5.0-4352717.dmg

**Comment by reitermarkus** [comment]
I think if `install` works without issues, you should be fine with only changing the version, since that means all `binary` sources are still there in this version. Feel free to reopen your PR in that case.

**Comment by reitermarkus** [comment]
This was updated in https://github.com/caskroom/homebrew-cask/pull/24512.
