### ISSUE TITLE
little-snitch link changed, please update

### ISSUE THREAD

**Issue by kangni** [caskroom/homebrew-cask#24514]
the new download link: https://www.obdev.at/products/littlesnitch/download.html

**Comment by reitermarkus** [comment]
In the [Issue Template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) you were asked to provide as much detail as possible to explain your issue. What exactly is wrong with the current URL? It seems to be working and up-to-date.

**Comment by kangni** [comment]
curl: (22) The requested URL returned error: 404 Not Found
      Error: Download failed on Cask 'little-snitch' with message: Download failed: Download failed:     https://www.obdev.at/downloads/littlesnitch/LittleSnitch-3.6.3.dmg

the new link: https://www.obdev.at/downloads/littlesnitch/LittleSnitch-3.7.dmg
