### ISSUE TITLE
Disable Accessibility Access override for OSX 10.12

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#24519]
Duplicate of https://github.com/Homebrew/brew/issues/905.

> `TCC.db` is (rightfully) protected by SIP in Sierra.

> We should prevent [`enable_accessibility_access`](https://github.com/Homebrew/brew/blob/9c09f0573020e253e979af44d623ce049a4a2bd6/Library/Homebrew/cask/lib/hbc/installer.rb#L225) ` if MacOS.release >= :sierra` (throw up a caveat instead?)

Moving it here since we have other core bugs here.

@reitermarkus @jawshooah What’s your take on issues related to HBC? Here or on HB’s repo?

**Comment by adidalal** [comment]
Not sure where it goes but if no one picks it up, I can probably add in the conditional this weekend. (Interestingly, I think fixing accessibility for 10.11 was my very first core HBC contribution)

**Comment by reitermarkus** [comment]
> What’s your take on issues related to HBC? Here or on HB’s repo?

For now, I'd leave them here as there are still [quite a few](https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aopen+label%3Acore) open, and when they are down to a smaller number, migrate them to Homebrew.

**Comment by vitorgalvao** [comment]
> Also, we could add minor issues which are low priority but can be fixed relatively easily to the newly introduced `Projects` tab.

Was also thinking of adding issues with `ready to implement`, there. And perhaps even cask requests and documentation requirements.

Something to close https://github.com/caskroom/homebrew-cask/issues/17337, basically. Something we can point users to help where they can pick what to help with depending on their level of expertise.

**Comment by wickles** [comment]
Which component of SIP needs to be disabled for this to work? Should TCC.db access be disabled entirely for macOS >= Sierra, or should it check the SIP config first and handle appropriately? (Also note `disable_accessibility_access` should be prevented as well.)

**Comment by vitorgalvao** [comment]
Disabling SIP is not something we should either be trying to do or encourage users to do.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/brew/pull/1029.
