### ISSUE TITLE
Cask request: Screencast

### ISSUE THREAD

**Issue by km-tr** [caskroom/homebrew-cask#24536]
### Cask details

(Please fill out as much as possible)

**Name** - Screencast

**Homepage** - https://github.com/soh335/Screencast
 
**License** - unlicensed

**Download URL** - https://github.com/soh335/Screencast/releases/download/0.0.4/Screencast.dmg

**Description** -

**Comment by sanyer** [comment]
https://github.com/caskroom/homebrew-cask/pull/24612
