### ISSUE TITLE
Improve 'Caskroom location has moved' message

### ISSUE THREAD

**Issue by ChrisJefferson** [caskroom/homebrew-cask#24609]
So, the current 'caskroom has moved' message tells me I have 'migrate my Casks'. I can read `https://github.com/caskroom/homebrew-cask/issues/21913`, which tells me I can:

* Do a `mv`, except that won't work for casks installed before pull request #13966 (how do I find out if my casks fall under that?)

and maybe I won't be able to uninstall without a `--force`. And there is one comment with 5 hearts: `brew cask install --force $(brew cask list)`. Is that what I should actually do? Because it doesn't seem to actually do anything (I still don't have a `/usr/local/Caskroom`)

 Or `for f in ~/Applications/*.app; do oldloc="$(readlink "$f")"; [[ -e $oldloc ]] || ln -sf "/usr/local${oldloc#/opt/homebrew-cask}" "$f"; done`? is also there!

Perhaps change the message to give a suggested thing to run, which will make things work.

**Comment by matty** [comment]
I'm not sure what I need to do, I uninstalled and installed Virtualbox the other day and it didn't go into the new Caskroom folder, is this intentional? Do I need to just move the folders to the new Caskroom location as specified and will that work?

**Comment by reitermarkus** [comment]
If the old location `/opt/homebrew-cask/Caskroom` exists, it will still be used.

**Comment by matty** [comment]
What about other files related to Caskroom in /opt? e.g /opt/vagrant? Have they moved?

**Comment by reitermarkus** [comment]
`/opt/vagrant` is not related to this. It may have been installed by Homebrew Cask, but it being there is simply because the `pkg` installer installed it there.

**Comment by ChrisJefferson** [comment]
@reitermarkus : So, how do I make it go away cleanly? Uninstall everything, remove directory, reinstall everything?

I tried doing something like `CASKS=$(brew cask list); for i in $CASKS...`, but unfortunately the way it outputs doesn't seem to get split by bash properly

**Comment by jawshooah** [comment]
> I tried doing something like CASKS=$(brew cask list); for i in $CASKS..., but unfortunately the way it outputs doesn't seem to get split by bash properly

That's because you're not doing bash properly 😉 

```bash
CASKS=($(brew cask list))
for cask in "${CASKS[@]}"; do
  # whatever
done
```

**Comment by ChrisJefferson** [comment]
@jawshooah : Every time I think I've figured out bash :|

Given this new bash-power, I came up with the following, which worked on my computer. You could `rm -rf /opt/homebrew-cask/Caskroom` if anything is left behind, and `--force` the uninstall). You should do this a step at a time, not just try cutting+pasting the whole thing in one go (it might, be I don't promise anything

```
# Grab the casks you have installed
CASKS=($(brew cask list))

# Uninstall everything
for cask in "${CASKS[@]}"; do
  brew cask uninstall --force $cask
done

# Remove the old directory (which is hopefully now empty)
rmdir /opt/homebrew-cask/Caskroom

# Reinstall everything
for cask in "${CASKS[@]}"; do
  brew cask install $cask
done
```

**Comment by jawshooah** [comment]
You'll want to `--force` the uninstall to get rid of all installed versions, but yeah, that will probably do what you want.

**Comment by vitorgalvao** [comment]
Closing as solved.
