### ISSUE TITLE
Update HyperDock to v1.7

### ISSUE THREAD

**Issue by lopedever** [caskroom/homebrew-cask#24685]
https://bahoom.com/hyperdock
thx

**Comment by vitorgalvao** [comment]
Next time, [please try it yourself](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). After the initial setup it takes literally one command to update, and it helps us greatly.

**Comment by lopedever** [comment]
Sorry, I will try next time. ^_^
