### ISSUE TITLE
Bug report:

### ISSUE THREAD

**Issue by enarendar9** [caskroom/homebrew-cask#24743]
brew cask install vagrant
==> Downloading https://releases.hashicorp.com/vagrant/1.8.5/vagrant_1.8.5.dmg
Already downloaded: /home/nani/.cache/Homebrew/Cask/vagrant--1.8.5.dmg
==> Verifying checksum for Cask vagrant
Error: No such file or directory - /usr/bin/hdiutilMost likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/lib/ruby/2.3.0/open3.rb:199:in `spawn'
/usr/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
/usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/system_command.rb:74:in `each_output_line'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/system_command.rb:19:in `run!'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/system_command.rb:8:in `run'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:8:in `me?'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/container.rb:56:in `block in for_path'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/container.rb:54:in `each'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/container.rb:54:in `find'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/container.rb:54:in `for_path'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/installer.rb:118:in `extract_primary_container'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/installer.rb:73:in `install'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:24:in `block in install_casks'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:18:in `each'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:18:in `install_casks'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:9:in `run'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/cli.rb:108:in `run_command'
/home/nani/.linuxbrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/home/nani/.linuxbrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/nani/.linuxbrew/Library/Homebrew/brew.rb:23:in `require?'
/home/nani/.linuxbrew/Library/Homebrew/brew.rb:102:in `<main>'

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.

**Comment by vitorgalvao** [comment]
To be clear, here what you need to do is follow [this template](https://github.com/caskroom/homebrew-cask/issues/new?title=Bug%20report%3A&body=Remember%20to%20follow%20the%20%5Bpre%20bug%20report%5D%28https%3A%2F%2Fgithub.com%2Fcaskroom%2Fhomebrew-cask%2Fblob%2Fmaster%2Fdoc%2Freporting_bugs%2Fpre_bug_report.md%29%20guide%20beforehand.%20Failure%20to%20do%20so%20might%20get%20your%20issue%20closed.%0A%0A%23%23%23%23%20Description%20of%20issue%0A%0A%5Binsert%20a%20detailed%20description%20of%20your%20issue%20here%5D%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20cask%20%3Ccommand%3E%20--verbose%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20doctor%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20cask%20doctor%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A).

**Comment by vitorgalvao** [comment]
Wait, are you using Linuxbrew? We don’t support it. Homebrew-Cask is macOS-only.

**Comment by adidalal** [comment]
Might be worth blocking Cask on Linux entirely, hah
