### ISSUE TITLE
Implement command to calculate appcast checkpoint natively

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#24811]
Refs https://github.com/caskroom/homebrew-cask/issues/24454.

Solves a bunch of issues including having to update the code for calculating the `checkpoint:` in multiple places every time it changes.

Users would no longer run the [`curl` command](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md#required-appcast-parameters), but instead [something like](https://github.com/caskroom/homebrew-cask/issues/24454#issuecomment-246928347) `brew cask _appcast_checkpoint {{cask_file}}`.

This command would simply spit out the calculated `checkpoint:` and nothing else.

We’re not married to `_appcast_checkpoint`, so other ideas are welcome, but that seems clear enough (we already have `_stanza`, so starting with a `_` continues with the notion of an internal command.

**Comment by toonetown** [comment]
Not sure if it's helpful as a jumping off point, but I've been using [this script](https://github.com/toonetown/homebrew-extras/blob/master/bin/brewcask-appcast) as a part of a custom tap and it's been working great for me.

**Comment by vitorgalvao** [comment]
@toonetown Not really, because that won’t solve the issue. Having external scripts is exactly the problem. What we need is a native (to HBC) solution so that when we update the script, it’s done just once.
