### ISSUE TITLE
Question about license 

### ISSUE THREAD

**Issue by lanox** [caskroom/homebrew-cask#24869]
Hi. 

Sorry if this is the wrong place to ask, but didn't find what I was looking for.

I was wondering how do I deal with licensing when it comes to installing apps through cask, such as Things where there is no license, I just paid for it on App Store ? 

Thanks

**Comment by vitorgalvao** [comment]
You deal with it in exactly the same way as if you had not installed through us. We make no modifications to apps, we try to be as close to a manual install as possible.

**Comment by lanox** [comment]
@vitorgalvao well I don't know if I am missing something here, however if I install Things app from cask its only a trail version, and there is no way to enter the serial number as I don't even have it, I purchased it from app store.  ??

am I missing something ?

**Comment by reitermarkus** [comment]
Seems like the non-App Store version really is only a trial version which will redirect you to the App Store to actually buy it, so this cask is basically useless, since you will always have to use the App Store version regardless.

**Comment by lanox** [comment]
@reitermarkus that was my exact thought as well, just wanted to confirm that was the case.
thanks.
