### ISSUE TITLE
version "does not exist" with brew cask info

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#24873]
Hello,

Over last months I used to "update" a cask with `brew cask install --force formula` when I observed that a new formula for a newer version was available.

Moreover, sometimes, I cleaned up some disk space by deleting the sub-directories of previous casks in the folder `Caskroom` (typing for instance: `rm -fr Caskroom/emacs/24.4`)

I just noticed today that it seems to have side effects: `brew cask info` lists all the "older" versions that I deleted as missing:
```
brew cask info emacs
emacs: 25.1-1
https://emacsformacosx.com/
/opt/homebrew/Caskroom/emacs/24.4 (does not exist)
/opt/homebrew/Caskroom/emacs/24.5 (does not exist)
/opt/homebrew/Caskroom/emacs/24.5-1 (3,962 files, 140.8M)
/opt/homebrew/Caskroom/emacs/25.1 (5 files, 274.7K)
/opt/homebrew/Caskroom/emacs/25.1-1 (5 files, 274.7K)
```

Same thing for `java`, `flash`, `libreoffice`, `eclipse-ide`...
Then, what is the right way to clean useless versions and avoid these "red errors" in the info output?

**Comment by reitermarkus** [comment]
There is a `.metadata` directory for every corresponding version, e.g. `/opt/homebrew/Caskroom/emacs/.metadata/24.4`.

You can either remove these manually or run `brew cask uninstall --force` and `brew cask install` again for those casks. I would also suggest you use this method to "update" casks in the future, instead of `install --force`.

**Comment by Yann-R** [comment]
One last comment that I realized after this topic being closed:

Since, when a use tries to install a new version of a software with `brew cask install formula`, the result says (e.g. with flash formula):
```
Warning: A Cask for flash is already installed. Add the "--force" option to force re-install.
```
Why not
- change the resulting message to follow your suggestion?
- or changer the behavior of the --force option to seamlessly integrate your suggestion?

**Comment by reitermarkus** [comment]
> Why not change the resulting message to follow your suggestion?

Yes, that's a good idea.

**Comment by Yann-R** [comment]
Related to https://github.com/caskroom/homebrew-cask/issues/23998
