### ISSUE TITLE
Documentation about Caskroom

### ISSUE THREAD

**Issue by toonetown** [caskroom/homebrew-cask#24888]
In the documentation, it lists that the default value for `--caskroom` is `$(brew --repository)/Caskroom` - when in reality, it is now `$(brew --prefix)/Caskroom`.

Not sure all the places this needs to be changed - or else I'd just submit a PR...

**Comment by reitermarkus** [comment]
> Not sure all the places this needs to be changed - or else I'd just submit a PR...

Please feel free to open a PR even if you don't catch all the places.
