### ISSUE TITLE
Cask request: Karabiner Elements

### ISSUE THREAD

**Issue by SimenB** [caskroom/homebrew-cask#24895]
### Cask details

(Please fill out as much as possible)

**Name** -
Karabiner-Elements

**Homepage** -
https://github.com/tekezo/Karabiner-Elements

**License** -
Unlicense

**Download URL** -
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Description** -
The replacement for Seil (https://github.com/caskroom/homebrew-cask/blob/master/Casks/seil.rb) for macOS Sierra. And appearantly somewhat for Karabiner as well
https://pqrs.org/osx/karabiner/seil.html.en
![image](https://cloud.githubusercontent.com/assets/1404810/18865326/fd3b2e8c-849a-11e6-92b9-6c96af0eacc3.png)

**Comment by sidneys** [comment]
I added Elements and created a PR: 
https://github.com/caskroom/homebrew-cask/pull/24988

**Comment by chris-fa** [comment]
karabiner-elements installation is not auto updating, is this normal?

**Comment by vitorgalvao** [comment]
> karabiner-elements installation is not auto updating, is this normal?

Since we don’t have upgrade functionality, yes.
