### ISSUE TITLE
Cask request: 3MCloudLibrary

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#24905]
### Cask details

(Please fill out as much as possible)

**Name** - 3MCloudLibrary

**Homepage** - http://www.yourcloudlibrary.com/index.php/en-us/

**License** - Apache Public License

**Download URL** - http://www.yourcloudlibrary.com/index.php/downloads/software/2-3mcloudlibrary-live-version-1-50-735564/file

The URL has a seemingly random string of six digit numbers that are not consistent between versions, making it difficult to use in a Cask. I am making a request in the hope that someone smarter than me can figure it out.

**Description** - An eBook reading platform.

**Comment by adidalal** [comment]
version `1.50.735564`
URL is `"http://www.yourcloudlibrary.com/index.php/en-us/downloads/software/2-3mcloudlibrary-live-version-#{version.dots_to_hyphens}/file"`

Feel free to take a crack at a PR. We're here to help if you have questions! [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)

Also, check out `cask-repair`, it makes Cask updates (version bumps) quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))
