### ISSUE TITLE
osxfuse.rb needs to be updated to version 3.5.2

### ISSUE THREAD

**Issue by ilium007** [caskroom/homebrew-cask#24933]
### Cask details

(Please fill out as much as possible)

osxfuse

https://osxfuse.github.io/

**License** -

https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.5.2/osxfuse-3.5.2.dmg

**Description** -

**Comment by victorpopkov** [comment]
Done in https://github.com/caskroom/homebrew-cask/pull/24936.
