### ISSUE TITLE
Proposal: get rid of `Hardware::CPU.is_32_bit?` conditionals

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#24941]
Snow Leopard was the last macOS release to support 32-bit. We can’t even guarantee HBC works that far back, and we certainly shouldn’t go out of our way to support such old versions.

As such, the `Hardware::CPU.is_32_bit?` seems useless. I propose we simply get rid of those conditionals altogether.

Casks in main repo (`grep -R 'Hardware::CPU.is_32_bit' "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks" | sed -E 's|.*/(.*)\.rb.*|- [ ] [\1](../tree/master/Casks/\1.rb)|' | pbcopy`):

- [x] [ableton-live](../tree/master/Casks/ableton-live.rb)
- [x] [aquamacs](../tree/master/Casks/aquamacs.rb)
- [x] [gambit-c](../tree/master/Casks/gambit-c.rb)
- [x] [geppetto](../tree/master/Casks/geppetto.rb)
- [x] [gnubg](../tree/master/Casks/gnubg.rb)
- [x] [libreoffice](../tree/master/Casks/libreoffice.rb)
- [x] [ngrok](../tree/master/Casks/ngrok.rb)
- [x] [p4](../tree/master/Casks/p4.rb)
- [x] [pacifist](../tree/master/Casks/pacifist.rb)
- [x] [plex-home-theater](../tree/master/Casks/plex-home-theater.rb)
- [x] [praat](../tree/master/Casks/praat.rb)
- [x] [razorsql](../tree/master/Casks/razorsql.rb)
- [x] [reaper](../tree/master/Casks/reaper.rb)
- [x] [scala-ide](../tree/master/Casks/scala-ide.rb)
- [x] [story-writer](../tree/master/Casks/story-writer.rb)
- [x] [streamtools](../tree/master/Casks/streamtools.rb)
- [x] [supersync](../tree/master/Casks/supersync.rb)
- [x] [tiddlywiki](../tree/master/Casks/tiddlywiki.rb)
- [x] [vega](../tree/master/Casks/vega.rb)
- [x] [vuescan](../tree/master/Casks/vuescan.rb)
- [x] [wkhtmltopdf](../tree/master/Casks/wkhtmltopdf.rb)

Casks in [caskroom/versions](https://github.com/caskroom/homebrew-versions) (`grep -R 'Hardware::CPU.is_32_bit' "$(brew --repository)/Library/Taps/caskroom/homebrew-versions/Casks" | sed -E 's|.*/(.*)\.rb.*|- [ ] [\1](../../homebrew-versions/tree/master/Casks/\1.rb)|' | pbcopy`):

- [x] [ableton-live-beta](../../homebrew-versions/tree/master/Casks/ableton-live-beta.rb)
- [x] [ableton-live-standard](../../homebrew-versions/tree/master/Casks/ableton-live-standard.rb)
- [x] [ableton-live-suite](../../homebrew-versions/tree/master/Casks/ableton-live-suite.rb)

**Comment by jawshooah** [comment]
Fine with me. Want to make this a Hacktoberfest task as well?

**Comment by miccal** [comment]
Happy to update `libreoffice` if you like?

**Comment by vitorgalvao** [comment]
> Want to make this a Hacktoberfest task as well?

Sure, why not?

> Happy to update `libreoffice` if you like?

Lets wait a few more hours (lets say 12) to see if any maintainer has an objection. If not, go ahead.

**Comment by reitermarkus** [comment]
> Lets wait a few more hours (lets say 12) to see if any maintainer has an objection. If not, go ahead.

Nope. 👍

**Comment by vitorgalvao** [comment]
@miccal Go right ahead.

**Comment by miccal** [comment]
@vitorgalvao Done.

**Comment by miccal** [comment]
All done except for the `versions` Casks, as I have not tapped `versions`.

**Comment by vitorgalvao** [comment]
I’ll deal with the [caskroom/versions](https://github.com/caskroom/homebrew-versions) ones. Thank you, @miccal. Closing this.

**Comment by miccal** [comment]
No problem.
