### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by reitermarkus** [caskroom/homebrew-cask#24943]
# Welcome to Hacktoberfest!

If you've never made a Pull Request before, Homebrew Cask is a great place to start! We provide an easy way to manage GUI apps (known as Casks) on macOS.

Check out [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md) for help with common tasks (adding a new Cask, updating an existing Cask, etc.)
---

We appreciate every contribution, but here's a list of some issues you could help us out with (curated from the [list of issues](https://github.com/caskroom/homebrew-cask/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest)):
- [`installer` Casks should provide `uninstall` stanzas](https://github.com/caskroom/homebrew-cask/issues/6872)
- [implement a built-in command to calculate the appcast checkpoint](https://github.com/caskroom/homebrew-cask/issues/24811)
- [Fix error message if app already exists](https://github.com/caskroom/homebrew-cask/issues/23377)
- [`audit` should warn about deprecated options](https://github.com/caskroom/homebrew-cask/issues/25388)
- [`audit`: check availability of URLs and HTTPS versions](https://github.com/caskroom/homebrew-cask/issues/25403)
- [add a `reinstall` command](https://github.com/caskroom/homebrew-cask/issues/23998) - in progress
- add a cask for:
  -

**Comment by vitorgalvao** [comment]
None. @adidalal mentioned this earlier today on Gitter. [Deprecate `license:`](https://github.com/caskroom/homebrew-cask/issues/17437) seems like a good candidate, as do most `ready to implement`.

**Comment by vitorgalvao** [comment]
Made the label, with their button color.

**Comment by reitermarkus** [comment]
Updated my top post to serve as a pointer.

**Comment by Saklad5** [comment]
Wait, we aren’t supposed to be using the license stanza anymore?

**Comment by Saklad5** [comment]
I’m tackling 3MCloudLibrary now, by the way.

**Comment by vitorgalvao** [comment]
> Wait, we aren’t supposed to be using the license stanza anymore?

We still need to use it (the code isn’t yet deprecated), but the stanza itself doesn’t matter anymore (it never did, in practice).

**Comment by Saklad5** [comment]
So I basically I should just leave "unknown" there until it is finally deprecated?

**Comment by vitorgalvao** [comment]
> So I basically I should just leave "unknown" there until it is finally deprecated?

Whatever you want. If you want to make it more correct than `unknown`, no harm done, but it won’t matter in the future.

**Comment by smileytechguy** [comment]
I am trying to make my first cask, but it isn't working

**Comment by vitorgalvao** [comment]
@smileytechguy Try adding [`container type: :naked`](https://github.com/caskroom/homebrew-cask/issues/24943#issuecomment-252139060). If it does not solve it, please open a new issue, lets not mix conversations. You’ll also need to remove the comments from the cask.

**Comment by reitermarkus** [comment]
Closing this, since Hacktoberfest sadly has come to an end. Thanks to all contributors, we “won”! 😂 

![](https://cloud.githubusercontent.com/assets/1309829/19937405/6ed255aa-a121-11e6-96b7-24fda0a2f032.png)

**Comment by vitorgalvao** [comment]
@reitermarkus Where did you find those statistics? Is there any more interesting information?

**Comment by Saklad5** [comment]
https://hacktoberfest.digitalocean.com

**Comment by vitorgalvao** [comment]
@Saklad5 Thank you. I actually went to the page but jumped that section, for some reason.
