### ISSUE TITLE
Rawtherapee.rb should be updated

### ISSUE THREAD

**Issue by frhgit** [caskroom/homebrew-cask#24960]
brew cask install --force rawtherapee
==> Satisfying dependencies
complete
==> Downloading http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.11_64_4.2-876_master.zip
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'rawtherapee' with message: Download failed: http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.11_64_4.2-876_master.zip

It seems that rawtherapee was updated to 4.2.1025 and https://github.com/caskroom/homebrew-cask/blob/master/Casks/rawtherapee.rb should be modified:
version '4.2.876' -> version '4.2.1025'
and sha256 should be updated accordingly

**Comment by vitorgalvao** [comment]
Care to take a crack at it? We [make the process extremely easy](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). After a one-time initial setup, updating casks takes just one command (and that includes the submission).

**Comment by frhgit** [comment]
I tried but i couldn't pushed the rawtherapee.rb. Obviously I did something wrong with cask-repair. each time I get 
```
Submitting…
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: the requested upstream branch 'frhgit/cask-repair_update-rawtherapee' does not exist
```

So here the result and I hope someone will be able to update rawtherapee.rb:
```
diff --git a/Casks/rawtherapee.rb b/Casks/rawtherapee.rb
index 3494068..06c38fd 100644
--- a/Casks/rawtherapee.rb
+++ b/Casks/rawtherapee.rb
@@ -10,10 +10,10 @@ cask 'rawtherapee' do
 
     url "http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.10_64_#{version}.zip"
   else
-    version '4.2.876'
-    sha256 '40feb4419bab29d8e822ac5577fdcc80683ebbf5a6acce40bf51acfbc4b387f5'
+    version '4.2.1025'
+    sha256 'e3e8f4b919528884c2e51dcb0cd0b746ea1ca32cae5317495bca80807648f84b'
 
-    url "http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.11_64_#{version.sub(%r{^(\d+)\.(\d+).(\d+).*}, '\1.\2-\3')}_master.zip"
+    url "http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.11_64_#{version}.zip"
   end
 
   name 'RawTherapee'
```

**Comment by vitorgalvao** [comment]
What command are you running with `cask-repair`?

**Comment by frhgit** [comment]
`cask-repair --pull origin --push frhgit  -v 4.2.1025 -u "http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.11_64_#{version}.zip" rawtherapee`

But I'm almost sure my pb is due to bad ssh key configuration on my side

**Comment by adidalal** [comment]
@frhgit https://help.github.com/articles/error-permission-denied-publickey/ 

or just use `https` https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended and https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by miccal** [comment]
I had this problem too - see [https://github.com/vitorgalvao/tiny-scripts/issues/40](url)

**Comment by vitorgalvao** [comment]
[Updating the documentation](https://github.com/caskroom/homebrew-cask/pull/24978/files).

**Comment by frhgit** [comment]
I finally managed to submit the change :)
For information : I followed the updated documention linked above without luck. 
`git remote -v`  still gave me :
```
USER    git@github.com:USER/homebrew-cask.git (fetch)
USER    git@github.com:USER/homebrew-cask.git (push)
origin  https://github.com/caskroom/homebrew-cask (fetch)
origin  https://github.com/caskroom/homebrew-cask (push) 
```
instead of the usual
```
USER    https://github.com/USER/homebrew-cask (fetch)
USER    https://github.com/USER/homebrew-cask (push)
origin  https://github.com/caskroom/homebrew-cask (fetch)
origin  https://github.com/caskroom/homebrew-cask (push) 
```

So i used the 'fix' given by @miccal (thanks a lot)
`git remote set-url USER https://github.com/USER/homebrew-cask`

**Comment by vitorgalvao** [comment]
> For information : I followed the updated documention linked above without luck.

Because the fork was already done. The update only makes sure in the future forks are done in this way.
