### ISSUE TITLE
Karabiner needs `uninstall pkgutil:`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#24990]
The [`karabiner`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/karabiner.rb) cask is missing [`pkgutil:`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-pkgutil), and there seems to be no reason for it. It certainly could benefit from one.

VMWare Fusion is currently deciding to freeze my computer, so can’t test it on a VM as of now.

**Comment by johndavidmartinez** [comment]
I would like to tackle this issue for hacktoberfest.

**Comment by vitorgalvao** [comment]
@johndavidmartinez Go for it. No need to tell us, everyone is free to work on whatever they like.

**Comment by vitorgalvao** [comment]
@johndavidmartinez Already done by @johndbritton in https://github.com/caskroom/homebrew-cask/pull/25175.
