### ISSUE TITLE
panoply.rb:  New Version and New File Name Structure at Download Site

### ISSUE THREAD

**Issue by wjcapehart** [caskroom/homebrew-cask#25016]
NASA GIS has updated their Panoply to version 4.6.0:

New version is version '4.6.0'

New installation file is:
http://www.giss.nasa.gov/tools/panoply/PanoplyMacOS-4.6.0.dmg

They have also changed their base naming structure for the installation file:

http://www.giss.nasa.gov/tools/panoply/PanoplyMacOS-#{version}.dmg

new sha256 is "5645381fd2317bc64d4d842d9b78cf499d3d8be2bd572557a3b0d1cd55d184ae"

The previous version in the script, http://www.giss.nasa.gov/tools/panoply/PanoplyOSX-4.5.1.dmg, is no longer accessible.

**Comment by adidalal** [comment]
Feel free to take a crack at a PR. It's a pretty simple fix, and we're here to help if you have questions!

[CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/25042
