### ISSUE TITLE
istat-menus: Can we use the bundled uninstaller instead?

### ISSUE THREAD

**Issue by Numbermaniac** [caskroom/homebrew-cask#25047]
Referring to: https://github.com/caskroom/homebrew-cask/blob/master/Casks/istat-menus.rb

iStat menus includes an uninstall option in its menu, and there is an app called '/Library/Application Support/iStat Menus 5/iStat Menus Uninstaller.app' when you install iStat. Is it feasible to use that instead, since it deletes most of the files it leaves around (except, ironically, the main app itself)? Problem is, running it directly crashes it every time, so I'm not sure how you could get this working...

(If it's not possible, I'll just file a PR to add a zap stanza for everything)

**Comment by vitorgalvao** [comment]
No, it’s not possible, not until https://github.com/caskroom/homebrew-cask/issues/24377 is done, as currently we do not support GUI uninstaller.
