### ISSUE TITLE
Cask request: Slack Beta

### ISSUE THREAD

**Issue by ColeTownsend** [caskroom/homebrew-cask#25096]
### Cask details

(Please fill out as much as possible)

**Name** -slack-beta

**Homepage** -https://slack.com/beta/osx

**License** -gratis

**Download URL** -https://slack.com/ssb/download-osx-beta

**Description** -Slack's beta app

**Comment by reitermarkus** [comment]
This is already in the `caskroom/versions` tap: https://github.com/caskroom/homebrew-versions/blob/master/Casks/slack-beta.rb

```
brew tap caskroom/versions
```
