### ISSUE TITLE
Update error directions to point to Reporting Bugs section

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#25127]
Homebrew Cask should error out and point to the documentation online, instead of blindly suggesting a string of commands. This also lets us be reactive to changes and potentially catch errors and change directions on the fly, as needed.

**Comment by vitorgalvao** [comment]
Absolutely in support of this. That string of commands hasn’t been serving us as it used to for a while, now.

**Comment by narendasan** [comment]
I am interested in working on this. Is there a particular location in the source where the string of commands is located, a format for the new messages and a place to point to? I saw the docs repo but it seems a bit odd to point people to a repo of markdown files

**Comment by reitermarkus** [comment]
I think if you search the source for `UPDATE_CMD` you will find this message.

**Comment by adidalal** [comment]
@narendasan https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/utils.rb#L7
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/utils.rb#L146

Should be changed to say something like: Please follow latest commands at https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

Maybe one of the other maintainers has a shorter subset of commands they want to put there?

But personally, I'd be OK if we just pointed people to https://github.com/caskroom/homebrew-cask#reporting-bugs - you'd need an internet connection to use HBC, anyway.

**Comment by narendasan** [comment]
So I was looking around and found these references as well:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/artifact/base.rb#L52
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb#L90
Should these lines be changed as well (probably to something other than the bug reporting docs)?

**Comment by narendasan** [comment]
Also I ran ```brew cask-tests``` and the version test fails. Is this expected or am I missing something
