### ISSUE TITLE
`brew cask install utorrent` won't add anything to my Applications

### ISSUE THREAD

**Issue by lipis** [caskroom/homebrew-cask#25170]
It's been a while since I used Cask but it looks like it doesn't add anything to my Applications when I'm trying to install uTorrent. But there is nothing in my Applications.. am I missing something?

```
$ brew cask install utorrent
==> Downloading https://download-new.utorrent.com/endpoint/utmac/os/osx/track/stable/
######################################################################## 100.0%
==> No checksum defined for Cask utorrent, skipping verification
To complete the installation of Cask utorrent, you must also
run the installer at

  '/usr/local/Caskroom/utorrent/latest/uTorrent.app'

🍺  utorrent was successfully installed!
```

But when I installed VLC for example everything went smoothly and I could see the VLC in my Applications..

```
$ brew cask install vlc
==> Downloading https://get.videolan.org/vlc/2.2.4/macosx/vlc-2.2.4.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask vlc
==> Moving App 'VLC.app' to '/Applications/VLC.app'
==> Symlinking Binary 'vlc.wrapper.sh' to '/usr/local/bin/vlc'
🍺  vlc was successfully installed!
```

**Comment by vitorgalvao** [comment]
It says right there in the message:

> To complete the installation of Cask utorrent, you must also
run the installer at

>  '/usr/local/Caskroom/utorrent/latest/uTorrent.app'

**Comment by lipis** [comment]
![cwzneru](https://cloud.githubusercontent.com/assets/125676/19070062/d2fdcbcc-8a29-11e6-9c89-bbdd40c6014f.gif)

**Comment by emelier** [comment]
Yeah kind of unclear reply there. 

I had the same 'issue'. I just updated homebrew (it said in the console I have to update it) and then installed uTorrent again the same way, successfully.

**Comment by jlp78** [comment]
Did you try "open /usr/local/Caskroom/utorrent/latest/uTorrent.app" (typed at a shell) or browsing to /usr/local/Caskroom/utorrent/latest with the Finder and then clicking on uTorrent?
