### ISSUE TITLE
Widget linking on fresh Mavericks install fails

### ISSUE THREAD

**Issue by vmrob** [caskroom/homebrew-cask#2520]
If the Widgets directory has not been created for a user, the linking of a widget installed via homebrew-cask fails:

    Error: Command failed to execute!

    ==> Failed command:
    /bin/ln '-hfs' '/opt/homebrew-cask/Caskroom/pemdas-widget/3.0/PEMDAS.wdgt' '/Users/vmrob/Library/Widgets/PEMDAS.wdgt' 2>&1

Likewise, it doesn't seem that Mavericks' Dashboard recognizes symlinks to begin with.

**Comment by vitorgalvao** [comment]
Closed as duplicate.
