### ISSUE TITLE
Cask request: go 16.10

### ISSUE THREAD

**Issue by DrStrangepork** [caskroom/homebrew-cask#25256]
### Cask details

**Name** - go-server and go-agent

**Download URL** - https://www.go.cd/download/

**Description** -
Not sure if this is the correct format for this request, but go 16.10 has been out for a while, cask needs update. I am about to submit a PR with the update.

**Comment by reitermarkus** [comment]
Thanks, but if you are going to submit a pull request anyways, there is no need to also create an issue.

**Comment by DrStrangepork** [comment]
My first time, didn't know the process.
