### ISSUE TITLE
How to install vagrant version 1.8.4

### ISSUE THREAD

**Issue by DeChrish** [caskroom/homebrew-cask#25305]
brew cask install vagrant --version=1.8.4
Error: needless argument: --version=1.8.4Most likely, this means you have an outdated version of Homebrew-Cask. Please run:
  brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:217:in `process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:142:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

**Comment by jawshooah** [comment]
We have never taken a `--version` flag. If you want to install a legacy version of vagrant, you'll need to create a custom tap.

**Comment by antontarasenko** [comment]
## Downgrade an application installed with Brew Cask

* https://www.jverdeyen.be/mac/downgrade-brew-cask-application/

My example how to install Vagrant 1.9.1:

Open the log:

```
cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
git log master -- Casks/vagrant.rb
```

Find `Update vagrant to 1.9.1 (#27487)` line in commits. It's `3279b728b3fa2303c0cb638d8b1f42e2e73d40a4`. Find the raw file on GitHub:

* https://raw.githubusercontent.com/caskroom/homebrew-cask/3279b728b3fa2303c0cb638d8b1f42e2e73d40a4/Casks/vagrant.rb

Then install it with `brew`:

```
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/3279b728b3fa2303c0cb638d8b1f42e2e73d40a4/Casks/vagrant.rb
```

So you get:

```
$ brew cask info vagrant
vagrant: 2.0.1
https://www.vagrantup.com/
/usr/local/Caskroom/vagrant/1.9.1 (3 files, 80.3MB)
$ vagrant --version
Vagrant 1.9.1
```

**Comment by vitorgalvao** [comment]
@antontarasenko That method is error prone and *we will not consider bugs resulting from it*. If anyone decides to follow that method, they do so at their own risk.

Also, please don’t revive such old posts. No one will see this except for the maintainers (who don’t need it).
