### ISSUE TITLE
Download slow and soon hangs indefinitely when other downloading process

### ISSUE THREAD

**Issue by OJFord** [caskroom/homebrew-cask#25337]
I've noticed that if Google Drive is performing a sync large enough for it to be in some way "ongoing", a `cask install` will download extraordinarily slowly, and very quickly (usually at <1%) hang indefinitely - even if the Drive synchronisation is subsequently paused or completes.

The expected behaviour would either be for Drive to slow, and each to progress slowly but steadily - or for Drive to slow to a crawl as it is a background sync operation, and the foreground `cask install` to progress at a near-usual (no other download) rate.

Of course, the speed issue is possibly a problem with Drive doing something to request a higher priority from the OS than it ought to, but Cask certainly shouldn't hang and require <C-c> and restart.

OS: macOS 10.12
Drive: 1.31.2873.2758
Homebrew: 1.0.6-63-g0546d90
core SHA: ac62
cask SHA: 299d77

**Comment by adidalal** [comment]
80% sure this is Drive taking up all the outbound bandwidth, and unfortunately, not something we can fix, as we don't touch (nor do we want to), OS priorities.

I normally kill Drive/Dropbox/sync apps when they're not actively used, because they'll watch *every* file operation and slow things down.
