### ISSUE TITLE
Brew Cask List returning error message. 

### ISSUE THREAD

**Issue by pquodling** [caskroom/homebrew-cask#25331]
a Brew cask list is returning 

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:208:in `license'

Does this about 50 or so times...

**Comment by jawshooah** [comment]
#25214. Please search for your issue before creating a new one.
