### ISSUE TITLE
Feature request: Profiles

### ISSUE THREAD

**Issue by cgerke** [caskroom/homebrew-cask#25353]
I'm new to homebrew so forgive me if I have missed it. I was looking at creating my first tap that would allow someone to generate .mobileconfig files. Is this already a feature available natively or by a 3rd party tap somewhere?

### Justification
Because osx server profilemanager simply isn't good enough.

### Example use case
A profile could be deployed rather than postflight "defaults" commands to configure an application that is deployed via a cask.

Or simply to configure and operating system.

**Comment by vitorgalvao** [comment]
As far as I know, there’s no third-party tap for it. We don’t plan on implementing it (too many higher priority things, though we never specifically discussed it).
