### ISSUE TITLE
Cask request: OneDrive App

### ISSUE THREAD

**Issue by michaelhearn06** [caskroom/homebrew-cask#25356]
### Cask details

(Please fill out as much as possible)

**Microsoft OneDrive** -

**https://onedrive.live.com/about/en-au/** -

**Don't need one as it is linked to your MS email account.** -

**https://onedrive.live.com/about/en-au/download/** -

**MS OneDrive app** -

**Comment by vitorgalvao** [comment]
It’s only available on the MAS, we cannot add it.

**Comment by fubarhouse** [comment]
I've just come across this one.

Thanks to @vitorgalvao for responding, you've helped solve my dilemma.

@michaelhearn06 you may want to check out `https://github.com/mas-cli/mas` for a command-line installation of mac store products.

**Comment by michaelhearn06** [comment]
Hi @vitorgalvao  @fubarhouse  thanks for the comments. Yeh I did the installation via MAS a couple of weeks ago. Thanks for the info though. :)
