### ISSUE TITLE
SafeSign Identity Client license issue by AET

### ISSUE THREAD

**Issue by rogeriopradoj** [caskroom/homebrew-cask#25364]
Hi, I'd like the help of community to have this issue solved.

## History - 1

I have contacted AET (Oct 5th) for supporting with macOS Sierra and the software issues. In October 7th they answered and partially helped (saying that I should contact their partners instead of them directly)  but they pointed problems with listing `safesign-identity-client` in HBC because of the current license:

![franz](https://cloud.githubusercontent.com/assets/443391/19241112/7dfb0aea-8ee3-11e6-906a-19340b914c43.png)

## History - 2

So I re-contacted them, asking which license they would prefer:

![franz](https://cloud.githubusercontent.com/assets/443391/19241217/e38cd096-8ee3-11e6-9ac6-e8ebf2279faf.png)

...

![franz](https://cloud.githubusercontent.com/assets/443391/19241386/ce03bdec-8ee4-11e6-887d-fa4e2b9501da.png)

## History - 3

And then they answered this way today Oct 10th:

![franz](https://cloud.githubusercontent.com/assets/443391/19241669/0abe6c5e-8ee6-11e6-88bb-d1f60fe491c3.png)

## Question

- Should we change the license of safesign-identity-client for **:commercial** (or **:closed**)?
- Or should we just remove the cask from HBC?

My vote:

Change the license for **:commercial**, because they provided this option in their Oct 7th message:

> [...] we protest to your statement "License - :gratis" on Github.
> [...] SafeSign is by no means freeware
> [...] We urge you to remove **or correct** these statements from github/internet.

Also provided the best choice according to them in their Oct 10th message:

> Related to Github these are the categories to be used for our (SafeSign) Software [...]
> :closed
> :commercial

**Comment by vitorgalvao** [comment]
We no longer support `license`. It was always useless and is being deprecated today (yes, really).

So they either agree to have it in HBC without an explicit license, which seems like they might (emphasis mine: “We urge you to **remove** or correct **these statements** from github/internet”), or we remove the cask entirely. I don’t really care which.

That said, this isn’t exactly a popular piece of software for our users (I’ve stated before I actually believe you might be the only one) and if they take such a tone with demands and bring out the legalese for something as simple as this, I’m betting they won’t be worth possible future headaches. In all honesty, I’m for removing the cask.

**Comment by vitorgalvao** [comment]
`license` has now been removed from all casks. Please recontact them and ask if it is OK like this. If not, we’ll remove the cask.

**Comment by rogeriopradoj** [comment]
@vitorgalvao I'm not going to recontact them about this issue. I'm sending a PR in order to remove the cask.

**Comment by vitorgalvao** [comment]
Alright. Like I said, if you recontact them and they say it’s OK, we can keep (readd) the cask. Otherwise, `license` is deprecated and if they take so much issue with it, we won’t add it back unless they are OK with it, as they’re definitely not worth the trouble.
