### ISSUE TITLE
Document `language` stanza

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#25370]
@reitermarkus Care to make the first draft? Can be a really rough one just with the details, so we at least have something for now.

Also, just remembered, we haven’t even decided its position in the stanza order (and hence have no cop), have we?

**Comment by reitermarkus** [comment]
> Also, just remembered, we haven’t even decided its position in the stanza order (and hence have no cop), have we?

I put them all between `sha256` and `url` for now. Actually, it needs to be there because `url` is the first stanza that can call `language`.

**Comment by vitorgalvao** [comment]
Just saw [this doubt](https://github.com/caskroom/homebrew-versions/pull/2737#issuecomment-252771436):

> How to verify download of specific language of the cask?

We should also add details on it
