### ISSUE TITLE
`audit` should warn about deprecated options

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#25388]
Noticed it doesn’t because users keep (understandably) submitting casks with `license`. It’d make sense for `audit` to print deprecation warnings as well.

**Comment by reitermarkus** [comment]
> users keep (understandably) submitting casks with `license`

I think the main problem is that `cask-repair` doesn't pull from `master`, so people are actually repairing an outdated cask which still has the `license` stanza.

**Comment by vitorgalvao** [comment]
> Another problem is that `cask-repair` doesn't pull from `master`

[It does](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair#L292) (and has done so since very early, if not the first version).

**Comment by reitermarkus** [comment]
Huh, then I don't get why so many `Updated … to …` PRs still have `license`.

**Comment by amyspark** [comment]
If one audits a cask with the `license` stanza, Homebrew returns
```
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:36:in `block in load'
```
I believe there is no way to detect it after that warning.

**Comment by reitermarkus** [comment]
We would have to undeprecate `license` again just to be able to audit it, which wouldn't make much sense now that it's been deprecated for over a year.
