### ISSUE TITLE
Changing Cask Token

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25489]
One of the Casks I submitted, 3mcloudlibrary, has changed its primary name to “cloudLibrary”. Older versions, however, are still called 3MCloudLibrary on the website. I feel that the token should be updated to reflect the current release’s name, but I am not sure how to make that change properly. Is it as simple as renaming the file and the first line of the cask with the new token?

**Comment by vitorgalvao** [comment]
> Is it as simple as renaming the file and the first line of the cask with the new token?

Yes.
