### ISSUE TITLE
Casks for application plugins, e.g. vagrant-berkshelf

### ISSUE THREAD

**Issue by gdavison** [caskroom/homebrew-cask#25532]
I'm not sure if this is a request for a new cask, a modification to an existing cask, or new functionality for the cask tool.

Specifically, what I'm looking to do is install the `vagrant-berkshelf` vagrant plugin through Cask. I want to be able to distribute a development environment configuration using `brew bundle`, and right now, users need to run an additional command.

This plugin depends on both `vagrant`, and `berkshelf` (installed via `chefdk`).

The installation command is `vagrant plugin install vagrant-berskshelf`, so there's no binary to download directly, which doesn't seem to fit the Cask model.

Is there a mechanism for installing application plugins, similar to the `options` settings for homebrew packages? If there is, this plugin could be added to the `vagrant` cask as an option? This would also mean there is a dependency on `chefdk` only if the plugin is installed.

**Comment by vitorgalvao** [comment]
Nope, we don’t support such a system. Seems like, from your explanation, that everything can be installed via a simple script, though.

**Comment by gdavison** [comment]
Yes, a script could definitely do it. Would adding such a feature to cask be worthwhile? I'm not sure how broadly applicable it would be.

If you'd like, I could make an attempt at writing something up.

**Comment by vitorgalvao** [comment]
> Would adding such a feature to cask be worthwhile?

No. We’re talking about a singular case, here. Not only do we not support specific install flags for casks, adding now the full plugin system for an app inside its cask would be a logistic nightmare and nonsensical.

I was saying that *you* can simply add the commands in a script.

**Comment by gdavison** [comment]
> >  > Seems like, from your explanation, that everything can be installed via a simple script, though.

> > **Yes, a script could definitely do it.**

> I was saying that _you_ can simply add the commands in a script.

Yup, I got that :)

> No. We’re talking about a singular case, here. Not only do we not support specific install flags for casks, adding now the full plugin system for an app inside its cask would be a logistic nightmare and nonsensical.

Hmm, no, that's not really what I was looking for. I obviously haven't explained it clearly, so that means it's not clear enough to me yet.
