### ISSUE TITLE
cleanmymac asks to be moved to /Applications

### ISSUE THREAD

**Issue by Numbermaniac** [caskroom/homebrew-cask#25538]
Similar to #21115, but this time it's already in /Applications and `suppress_move_to_applications` appears to already be there in the code.

![screen shot 2016-10-16 at 15 16 12](https://cloud.githubusercontent.com/assets/5206120/19415200/60871c4e-93b4-11e6-8888-7f233f4cb2ea.png)

https://github.com/caskroom/homebrew-cask/blob/master/Casks/cleanmymac.rb

**Comment by adidalal** [comment]
How is this popup even showing up? HBC literally moves applications now, not symlinks.
Do you have a different directory set in HBC options possibly?

If not, I'd mark it as a CleanMyMac bug (I refuse to install the app to troubleshoot, as it screams useless)

**Comment by Numbermaniac** [comment]
Yeah, I don't get it either. The app is already in /Applications. Caskroom's installation directory is /usr/local/Caskroom, should it be something else?

**Comment by vitorgalvao** [comment]
> Caskroom's installation directory is /usr/local/Caskroom

That’s just a staging directory.

I cannot reproduce this issue, and it seems like it might be something in your setup. Will close but keep an eye out for other reports of this.
