### ISSUE TITLE
it's another permission bug

### ISSUE THREAD

**Issue by palindrom615** [caskroom/homebrew-cask#25547]

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

Closing, since this issue doesn’t even contain any information.

**Comment by palindrom615** [comment]
I'm so sorry about that. I pressed enter mistakenly.

**Comment by vitorgalvao** [comment]
What’s the output of `ls -la "${HOME}/Library/Caches/Homebrew"`?

**Comment by palindrom615** [comment]
This is some part of output of  `ls -la "${HOME}/Library/Caches/Homebrew"`.  Maybe no need to paste all of them...
```
total 855248
drwxrwxr-x  78 palindrom615  staff       2652 10 17 00:40 .
drwx------+ 69 palindrom615  staff       2346 10 17 00:47 ..
drwxr-xr-x  12 root          staff        408  8 15 00:15 Cask
-rw-r--r--   1 root          staff      11263  9 27 00:04 archey-1.6.0.tar.gz
-rw-r--r--   1 root          staff      16148  4  9  2016 bchunk-1.2.0.el_capitan.bottle.tar.gz
-rw-r--r--   1 palindrom615  staff     668343  9 11 11:41 bison-3.0.4.sierra.bottle.tar.gz
-rw-r--r--   1 root          staff    1687396  2 16  2016 cairo-1.14.6_1.el_capitan.bottle.tar.gz
-rw-r--r--   1 palindrom615  staff    1687906  9 10 09:30 cairo-1.14.6_1.sierra.bottle.tar.gz
-rw-r--r--   1 palindrom615  staff     310628 10 17 00:40 cask-0.8.0.tar.gz
-rw-r--r--   1 palindrom615  staff   10572591  9 10 01:22 cmake-3.6.2.sierra.bottle.tar.gz
-rw-r--r--   1 root          staff      31961 10 10 01:49 cowsay-3.04.tar.gz
...
```

**Comment by jawshooah** [comment]
> `drwxr-xr-x  12 root          staff        408  8 15 00:15 Cask`

There's your problem. Why is this directory owned by `root`? For that matter, why are several of your Homebrew bottles owned by `root`?

Just `sudo chown -R "${USER}:staff" "${HOME}/Library/Caches/Homebrew"` and try again.

**Comment by palindrom615** [comment]
I sometimes used brew as su and maybe that's why. It solved! Thanks very much!

**Comment by jawshooah** [comment]
> I sometimes used brew as su and maybe that's why.

Yup, that's why. Don't do that! :wink:
