### ISSUE TITLE
Bug report: OverSight uninstall stanza is not correct

### ISSUE THREAD

**Issue by kergoth** [caskroom/homebrew-cask#25585]
#### Description of issue

The uninstall stanza for oversight.rb attempts to quit `com.objective-see.OverSight` and remove a login item for `Oversight`, but the actual running process is `com.objective-see.OverSightHelper` and the login item is `OverSight Helper`.

**Comment by themsay** [comment]
Adding --force still get the same result.

`$ brew cask uninstall oversight`
<pre>
==> Uninstalling Cask oversight
==> Running uninstall process for oversight; your password may be necessary
==> Quitting application ID com.objective-see.OverSightHelper
==> Removing login item OverSight Helper
==> 36:92: 
==> execution error: An error of type -10810 has occurred. (-10810)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e tell application \"System Events\" to delete every login item whose name is \"OverSight Helper\"

==> Standard Output of failed command:

==> Standard Error of failed command:
36:92: execution error: An error of type -10810 has occurred. (-10810)

==> Exit status of failed command:
#< Process::Status: pid 86644 exit 1>
</pre>

After that oversight still show up.
`$ brew cask list`
<pre>oversight</pre>
