### ISSUE TITLE
Outdated cask: protege

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25828]
Outdated cask: [`protege`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/protege.rb).

Info:
+ version: `5.0.0`.
+ appcast url: https://github.com/protegeproject/protege-distribution/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
