### ISSUE TITLE
Outdated cask: protonet

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25829]
Outdated cask: [`protonet`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/protonet.rb).

Info:
+ version: `1.6.3023`.
+ appcast url: http://clients.protonet.info/osx/stable/appcast.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
