### ISSUE TITLE
Outdated cask: qsyncthingtray

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25837]
Outdated cask: [`qsyncthingtray`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qsyncthingtray.rb).

Info:
+ version: `0.5.2`.
+ appcast url: https://github.com/sieren/QSyncthingTray/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
