### ISSUE TITLE
Outdated cask: qlab

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25836]
Outdated cask: [`qlab`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qlab.rb).

Info:
+ version: `3.1.23`.
+ appcast url: https://figure53.com/qlab/downloads/appcast-v3.php.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
