### ISSUE TITLE
Outdated cask: qtpass

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25839]
Outdated cask: [`qtpass`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qtpass.rb).

Info:
+ version: `1.1.4`.
+ appcast url: https://github.com/IJHack/qtpass/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
