### ISSUE TITLE
Outdated cask: pyzo

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25833]
Outdated cask: [`pyzo`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pyzo.rb).

Info:
+ version: `4.1`.
+ appcast url: https://github.com/pyzo/pyzo/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
