### ISSUE TITLE
Outdated cask: qcma

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25835]
Outdated cask: [`qcma`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qcma.rb).

Info:
+ version: `0.3.10`.
+ appcast url: https://github.com/codestation/qcma/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
