### ISSUE TITLE
Outdated cask: qbittorrent

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25834]
Outdated cask: [`qbittorrent`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qbittorrent.rb).

Info:
+ version: `3.3.6`.
+ appcast url: https://sourceforge.net/projects/qbittorrent/rss?path=/qbittorrent-mac.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
