### ISSUE TITLE
Outdated cask: proxpn

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25830]
Outdated cask: [`proxpn`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/proxpn.rb).

Info:
+ version: `4.3.6.5`.
+ appcast url: https://www.proxpn.com/updater/appcast.rss.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
