### ISSUE TITLE
Outdated cask: pyfa

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25832]
Outdated cask: [`pyfa`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pyfa.rb).

Info:
+ version: `1.23.1,yc.118.7-1.4`.
+ appcast url: https://github.com/pyfa-org/Pyfa/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
