### ISSUE TITLE
Outdated cask: qtox

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25838]
Outdated cask: [`qtox`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qtox.rb).

Info:
+ version: `1.4.1.1`.
+ appcast url: https://github.com/tux3/qtox/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
