### ISSUE TITLE
Outdated cask: psychopy

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25831]
Outdated cask: [`psychopy`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/psychopy.rb).

Info:
+ version: `1.83.04`.
+ appcast url: https://github.com/psychopy/psychopy/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
