### ISSUE TITLE
Outdated cask: quotefix

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25841]
Outdated cask: [`quotefix`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/quotefix.rb).

Info:
+ version: `2.7.4,120155`.
+ appcast url: https://github.com/robertklep/quotefixformac/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
