### ISSUE TITLE
Outdated cask: qutebrowser

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25842]
Outdated cask: [`qutebrowser`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qutebrowser.rb).

Info:
+ version: `0.8.1`.
+ appcast url: https://github.com/The-Compiler/qutebrowser/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
