### ISSUE TITLE
Outdated cask: radio-silence

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25843]
Outdated cask: [`radio-silence`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/radio-silence.rb).

Info:
+ version: `2.1`.
+ appcast url: https://radiosilenceapp.com/update.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
