### ISSUE TITLE
Outdated cask: querious

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25840]
Outdated cask: [`querious`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/querious.rb).

Info:
+ version: `2.0_beta46`.
+ appcast url: https://arweb-assets.s3.amazonaws.com/downloads/querious/prerelease-updates.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
