### ISSUE TITLE
Outdated cask: ramme

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25844]
Outdated cask: [`ramme`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ramme.rb).

Info:
+ version: `2.3.0`.
+ appcast url: https://github.com/terkelg/ramme/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
