### ISSUE TITLE
Outdated cask: realm-browser

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25846]
Outdated cask: [`realm-browser`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/realm-browser.rb).

Info:
+ version: `2.0.0`.
+ appcast url: https://github.com/realm/realm-browser-osx/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
