### ISSUE TITLE
Outdated cask: rdm

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25845]
Outdated cask: [`rdm`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rdm.rb).

Info:
+ version: `0.8.3-2550`.
+ appcast url: https://github.com/uglide/RedisDesktopManager/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
