### ISSUE TITLE
Outdated cask: retroshare

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25849]
Outdated cask: [`retroshare`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/retroshare.rb).

Info:
+ version: `0.6.0,20160209-4033f35f`.
+ appcast url: https://github.com/RetroShare/RetroShare/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
