### ISSUE TITLE
Outdated cask: rocket-chat

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25852]
Outdated cask: [`rocket-chat`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rocket-chat.rb).

Info:
+ version: `1.3.1`.
+ appcast url: https://github.com/RocketChat/Rocket.Chat.Electron/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
