### ISSUE TITLE
Outdated cask: rhinoceros

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25851]
Outdated cask: [`rhinoceros`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rhinoceros.rb).

Info:
+ version: `5.2.1`.
+ appcast url: https://files.mcneel.com/rhino/5.0/mac/5CcommercialUpdates.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
