### ISSUE TITLE
Outdated cask: rubitrack

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25855]
Outdated cask: [`rubitrack`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rubitrack.rb).

Info:
+ version: `4.3.3`.
+ appcast url: https://www.rubitrack.com/autoupdate/sparkle4.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
