### ISSUE TITLE
Outdated cask: royal-tsx

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25854]
Outdated cask: [`royal-tsx`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/royal-tsx.rb).

Info:
+ version: `2.2.6.1000`.
+ appcast url: https://royaltsx-v2.royalapplications.com/updates_stable.php.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
