### ISSUE TITLE
Outdated cask: sabnzbd

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25856]
Outdated cask: [`sabnzbd`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sabnzbd.rb).

Info:
+ version: `1.1.0`.
+ appcast url: https://github.com/sabnzbd/sabnzbd/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
