### ISSUE TITLE
Outdated cask: safe-launcher

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25857]
Outdated cask: [`safe-launcher`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/safe-launcher.rb).

Info:
+ version: `0.8.1`.
+ appcast url: https://github.com/maidsafe/safe_launcher/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
