### ISSUE TITLE
Outdated cask: rodeo

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25853]
Outdated cask: [`rodeo`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rodeo.rb).

Info:
+ version: `2.4.2`.
+ appcast url: https://github.com/yhat/rodeo/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
