### ISSUE TITLE
Outdated cask: reveal

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25850]
Outdated cask: [`reveal`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/reveal.rb).

Info:
+ version: `1.6.3`.
+ appcast url: https://download.revealapp.com/reveal-release.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
