### ISSUE TITLE
Outdated cask: sassquatch

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25859]
Outdated cask: [`sassquatch`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sassquatch.rb).

Info:
+ version: `1.5.0`.
+ appcast url: https://thoughtbot.github.io/sassquatch/feed.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
