### ISSUE TITLE
Outdated cask: screenmailer

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25862]
Outdated cask: [`screenmailer`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/screenmailer.rb).

Info:
+ version: `2.0.5`.
+ appcast url: https://www.screenmailer.com/releases/current/releases.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
