### ISSUE TITLE
Outdated cask: screencat

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25861]
Outdated cask: [`screencat`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/screencat.rb).

Info:
+ version: `2.0.0`.
+ appcast url: https://github.com/maxogden/screencat/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
