### ISSUE TITLE
Outdated cask: shuttle

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25867]
Outdated cask: [`shuttle`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/shuttle.rb).

Info:
+ version: `1.2.7`.
+ appcast url: https://github.com/fitztrev/shuttle/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
