### ISSUE TITLE
Outdated cask: scribus

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25863]
Outdated cask: [`scribus`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/scribus.rb).

Info:
+ version: `1.4.6`.
+ appcast url: https://sourceforge.net/projects/scribus/rss?path=/scribus.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
