### ISSUE TITLE
Outdated cask: scap-workbench

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25860]
Outdated cask: [`scap-workbench`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/scap-workbench.rb).

Info:
+ version: `1.1.1`.
+ appcast url: https://github.com/OpenSCAP/scap-workbench/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
