### ISSUE TITLE
Outdated cask: snapz-pro-x

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25869]
Outdated cask: [`snapz-pro-x`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/snapz-pro-x.rb).

Info:
+ version: `2.6.0`.
+ appcast url: https://www.ambrosiasw.com/updates/profile.php/snapz_pro_x/release.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
