### ISSUE TITLE
Outdated cask: shadowsocksx-ng

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25865]
Outdated cask: [`shadowsocksx-ng`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/shadowsocksx-ng.rb).

Info:
+ version: `1.2`.
+ appcast url: https://github.com/shadowsocks/ShadowsocksX-NG/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
