### ISSUE TITLE
Outdated cask: security-growler

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25864]
Outdated cask: [`security-growler`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/security-growler.rb).

Info:
+ version: `2.2`.
+ appcast url: https://github.com/pirate/security-growler/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
