### ISSUE TITLE
Outdated cask: shiba

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25866]
Outdated cask: [`shiba`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/shiba.rb).

Info:
+ version: `1.0.0`.
+ appcast url: https://github.com/rhysd/Shiba/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
