### ISSUE TITLE
Outdated cask: simpholders

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25868]
Outdated cask: [`simpholders`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/simpholders.rb).

Info:
+ version: `2.2`.
+ appcast url: https://simpholders.com/updates/releases.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
