### ISSUE TITLE
Outdated cask: solvespace

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25870]
Outdated cask: [`solvespace`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/solvespace.rb).

Info:
+ version: `2.1`.
+ appcast url: https://github.com/solvespace/solvespace/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
