### ISSUE TITLE
Outdated cask: sparkle

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25874]
Outdated cask: [`sparkle`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sparkle.rb).

Info:
+ version: `1.14.0`.
+ appcast url: https://github.com/sparkle-project/Sparkle/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
