### ISSUE TITLE
Outdated cask: splitshow

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25875]
Outdated cask: [`splitshow`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/splitshow.rb).

Info:
+ version: `0.9.6-alpha`.
+ appcast url: https://github.com/mpflanzer/splitshow/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
