### ISSUE TITLE
Outdated cask: soundcleod

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25871]
Outdated cask: [`soundcleod`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/soundcleod.rb).

Info:
+ version: `1.1.0`.
+ appcast url: https://github.com/salomvary/soundcleod/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
