### ISSUE TITLE
Outdated cask: sqlectron

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25878]
Outdated cask: [`sqlectron`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sqlectron.rb).

Info:
+ version: `1.15.0`.
+ appcast url: https://github.com/sqlectron/sqlectron-gui/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
