### ISSUE TITLE
Outdated cask: spyder

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25877]
Outdated cask: [`spyder`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/spyder.rb).

Info:
+ version: `2.3.8`.
+ appcast url: https://github.com/spyder-ide/spyder/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
