### ISSUE TITLE
Outdated cask: soundflowerbed

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25873]
Outdated cask: [`soundflowerbed`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/soundflowerbed.rb).

Info:
+ version: `2.0.0`.
+ appcast url: https://github.com/mLupine/SoundflowerBed/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
