### ISSUE TITLE
Outdated cask: spriteilluminator

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25876]
Outdated cask: [`spriteilluminator`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/spriteilluminator.rb).

Info:
+ version: `1.3.0`.
+ appcast url: https://www.codeandweb.com/releases/SpriteIlluminator/appcast-mac-release.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
