### ISSUE TITLE
Outdated cask: sqleditor

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25879]
Outdated cask: [`sqleditor`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sqleditor.rb).

Info:
+ version: `3.0.2`.
+ appcast url: https://www.malcolmhardie.com/sqleditor/appcast/sq2release.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
