### ISSUE TITLE
Outdated cask: soundflower

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25872]
Outdated cask: [`soundflower`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/soundflower.rb).

Info:
+ version: `2.0b2`.
+ appcast url: https://github.com/mattingalls/Soundflower/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
