### ISSUE TITLE
Outdated cask: swiftybeaver

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25889]
Outdated cask: [`swiftybeaver`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/swiftybeaver.rb).

Info:
+ version: `1.0.3`.
+ appcast url: https://cdn.swiftybeaver.com/sbmac-appcast.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
