### ISSUE TITLE
Outdated cask: subsmarine

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25885]
Outdated cask: [`subsmarine`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/subsmarine.rb).

Info:
+ version: `1.2.3`.
+ appcast url: https://www.cocoawithchurros.com/shine/appcast.php?id=7.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
