### ISSUE TITLE
Outdated cask: stepmania

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25882]
Outdated cask: [`stepmania`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/stepmania.rb).

Info:
+ version: `5.0.10`.
+ appcast url: https://github.com/stepmania/stepmania/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
