### ISSUE TITLE
Outdated cask: stellarium

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25881]
Outdated cask: [`stellarium`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/stellarium.rb).

Info:
+ version: `0.14.3`.
+ appcast url: https://sourceforge.net/projects/stellarium/rss.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
