### ISSUE TITLE
Outdated cask: studiolinkstandalone

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25884]
Outdated cask: [`studiolinkstandalone`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/studiolinkstandalone.rb).

Info:
+ version: `16.02.2-beta`.
+ appcast url: https://github.com/Studio-Link-v2/backend/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
