### ISSUE TITLE
Outdated cask: supercollider

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25886]
Outdated cask: [`supercollider`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/supercollider.rb).

Info:
+ version: `3.7.1`.
+ appcast url: https://github.com/supercollider/supercollider/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
