### ISSUE TITLE
Outdated cask: svgcleaner

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25887]
Outdated cask: [`svgcleaner`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/svgcleaner.rb).

Info:
+ version: `0.6.2`.
+ appcast url: https://sourceforge.net/projects/svgcleaner/rss.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
