### ISSUE TITLE
Outdated cask: sqlitebrowser

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25880]
Outdated cask: [`sqlitebrowser`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sqlitebrowser.rb).

Info:
+ version: `3.9.1`.
+ appcast url: https://github.com/sqlitebrowser/sqlitebrowser/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
