### ISSUE TITLE
Outdated cask: tabula

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25891]
Outdated cask: [`tabula`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/tabula.rb).

Info:
+ version: `1.0.1`.
+ appcast url: https://github.com/tabulapdf/tabula/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
