### ISSUE TITLE
Outdated cask: torguard

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25897]
Outdated cask: [`torguard`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/torguard.rb).

Info:
+ version: `0.3.54`.
+ appcast url: https://updates.torguard.biz/Software/MacOSX/checksums.sha256.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
