### ISSUE TITLE
Outdated cask: table-tool

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25890]
Outdated cask: [`table-tool`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/table-tool.rb).

Info:
+ version: `1.1.1`.
+ appcast url: https://github.com/jakob/TableTool/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
