### ISSUE TITLE
Outdated cask: tagspaces

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25892]
Outdated cask: [`tagspaces`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/tagspaces.rb).

Info:
+ version: `2.4.0`.
+ appcast url: https://github.com/tagspaces/tagspaces/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
