### ISSUE TITLE
Outdated cask: tower

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25898]
Outdated cask: [`tower`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/tower.rb).

Info:
+ version: `2.5.1-329-2d945c27`.
+ appcast url: https://updates.fournova.com/updates/tower2-mac/stable.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
