### ISSUE TITLE
Outdated cask: together

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25896]
Outdated cask: [`together`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/together.rb).

Info:
+ version: `3.5.14`.
+ appcast url: https://reinventedsoftware.com/together/downloads/Together3.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
