### ISSUE TITLE
Outdated cask: traktable

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25899]
Outdated cask: [`traktable`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/traktable.rb).

Info:
+ version: `0.5.2`.
+ appcast url: https://github.com/yo-han/Traktable/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
