### ISSUE TITLE
Outdated cask: themeengine

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25895]
Outdated cask: [`themeengine`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/themeengine.rb).

Info:
+ version: `1.0.0(111)`.
+ appcast url: https://github.com/alexzielenski/ThemeEngine/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
