### ISSUE TITLE
Outdated cask: texturepacker

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25894]
Outdated cask: [`texturepacker`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/texturepacker.rb).

Info:
+ version: `4.2.3`.
+ appcast url: https://www.codeandweb.com/releases/TexturePacker/appcast-mac-release.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
