### ISSUE TITLE
Outdated cask: texstudio

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25893]
Outdated cask: [`texstudio`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/texstudio.rb).

Info:
+ version: `2.11.2`.
+ appcast url: https://sourceforge.net/projects/texstudio/rss.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
