### ISSUE TITLE
Outdated cask: vagrant-manager

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25905]
Outdated cask: [`vagrant-manager`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vagrant-manager.rb).

Info:
+ version: `2.5.4`.
+ appcast url: https://github.com/lanayotech/vagrant-manager/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
