### ISSUE TITLE
Outdated cask: vivaldi

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25909]
Outdated cask: [`vivaldi`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vivaldi.rb).

Info:
+ version: `1.4.589.38`.
+ appcast url: https://update.vivaldi.com/update/1.0/mac/appcast.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
