### ISSUE TITLE
Outdated cask: ultrastardeluxe

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25903]
Outdated cask: [`ultrastardeluxe`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ultrastardeluxe.rb).

Info:
+ version: `1.1`.
+ appcast url: https://sourceforge.net/projects/ultrastardx/rss.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
