### ISSUE TITLE
Outdated cask: virtaal

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25908]
Outdated cask: [`virtaal`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtaal.rb).

Info:
+ version: `0.7.1b2`.
+ appcast url: https://sourceforge.net/projects/translate/rss?path=/Virtaal.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
