### ISSUE TITLE
Outdated cask: vimr

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25907]
Outdated cask: [`vimr`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vimr.rb).

Info:
+ version: `0.8.0-32`.
+ appcast url: https://github.com/qvacua/vimr/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
