### ISSUE TITLE
Outdated cask: vassal

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25906]
Outdated cask: [`vassal`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vassal.rb).

Info:
+ version: `3.2.16`.
+ appcast url: https://sourceforge.net/projects/vassalengine/rss?path=/VASSAL-current.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
