### ISSUE TITLE
Outdated cask: tunnelbear

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25901]
Outdated cask: [`tunnelbear`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/tunnelbear.rb).

Info:
+ version: `3.0.2`.
+ appcast url: https://s3.amazonaws.com/tunnelbear/downloads/mac/appcast.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
