### ISSUE TITLE
Outdated cask: tribler

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25900]
Outdated cask: [`tribler`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/tribler.rb).

Info:
+ version: `6.5.2`.
+ appcast url: https://github.com/Tribler/tribler/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
