### ISSUE TITLE
Outdated cask: tv-browser

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25902]
Outdated cask: [`tv-browser`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/tv-browser.rb).

Info:
+ version: `3.4.4`.
+ appcast url: https://sourceforge.net/projects/tvbrowser/rss.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
