### ISSUE TITLE
Outdated cask: wmail

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25915]
Outdated cask: [`wmail`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wmail.rb).

Info:
+ version: `1.3.1`.
+ appcast url: https://github.com/Thomas101/wmail/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
