### ISSUE TITLE
Outdated cask: webarchiveplayer

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25910]
Outdated cask: [`webarchiveplayer`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/webarchiveplayer.rb).

Info:
+ version: `1.4.1`.
+ appcast url: https://github.com/ikreymer/webarchiveplayer/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
