### ISSUE TITLE
Outdated cask: wordmark

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25916]
Outdated cask: [`wordmark`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wordmark.rb).

Info:
+ version: `2.1.7`.
+ appcast url: https://github.com/wordmark/wordmark/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
