### ISSUE TITLE
Outdated cask: wesnoth

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25913]
Outdated cask: [`wesnoth`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wesnoth.rb).

Info:
+ version: `1.12.4`.
+ appcast url: https://sourceforge.net/projects/wesnoth/rss.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
