### ISSUE TITLE
Outdated cask: wowza-streaming-engine

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25917]
Outdated cask: [`wowza-streaming-engine`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wowza-streaming-engine.rb).

Info:
+ version: `4.5.0`.
+ appcast url: https://www.wowza.com/rss/wowzastreamingengineupdates.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
