### ISSUE TITLE
Outdated cask: webuildsg

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25911]
Outdated cask: [`webuildsg`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/webuildsg.rb).

Info:
+ version: `1.1.0`.
+ appcast url: https://github.com/webuildsg/osx/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
