### ISSUE TITLE
Outdated cask: xamarin-android

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25918]
Outdated cask: [`xamarin-android`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/xamarin-android.rb).

Info:
+ version: `7.0.0-18`.
+ appcast url: https://static.xamarin.com/installer_assets/v3/Mac/Universal/InstallationManifest.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
