### ISSUE TITLE
Outdated cask: xamarin-jdk

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25919]
Outdated cask: [`xamarin-jdk`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/xamarin-jdk.rb).

Info:
+ version: `7.71`.
+ appcast url: https://static.xamarin.com/installer_assets/v3/Mac/Universal/InstallationManifest.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
