### ISSUE TITLE
Outdated cask: zotero

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25922]
Outdated cask: [`zotero`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/zotero.rb).

Info:
+ version: `4.0.29.14`.
+ appcast url: https://github.com/zotero/zotero/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
