### ISSUE TITLE
{find,fix,merge}_outdated_appcasts: prevent non-maintainers from spamming the repo

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#25926]
It was an absolutely *terrible* idea to expose user-facing scripts that automatically generate GitHub issues and PRs for outdated casks. These scripts were [always intended](https://github.com/caskroom/homebrew-cask/pull/18237) to be run only by maintainers, and even then only until we had the means to automate them, but no safeguards were ever put in place to ensure that non-maintainers did not run them and spam the repo with issues.

The recent spate of ["outdated cask" issues](https://github.com/caskroom/homebrew-cask/issues?utf8=%E2%9C%93&q=is%3Aissue%20outdated%20cask) across this repo, homebrew-versions, and homebrew-fonts have made it clear that we need to either build these safeguards into the scripts, or abandon them completely. As far as I can tell, they haven't been run in months, so I don't think it would be a great loss to remove them, at least until we have a better scheme in place to automatically update casks based on appcast.

@caskroom/maintainers, thoughts?

---

Side note, if you're interested, here's the script I used to remediate this:

```bash
outdated_cask_issues=($(
  ghi list --creator Saklad5 --no-labels --no-pulls \
  | grep --ignore-case 'Outdated cask' \
  | awk '{print $1}'
))
printf "Close issues generated by find_outdated_appcasts\n\n" > close_issues_msg
for issue in "${outdated_cask_issues[@]}"; do
  echo "Closes #${issue}" >> close_issues_msg
done
git commit --allow-empty --file close_issues_msg
git push upstream master
```

**Comment by vitorgalvao** [comment]
I’m fine with removing them. Now they have been in place for so long — and due to their usage *and* lack of usage — we have a better grasp for what needs to change about them.

I have for some time in my head a forming system for this, but it’ll take some time and work to flesh out.

In the meantime, I think having a single `find_and_fix` script that will only generate PRs and can be run by maintainers and users alike might be a good fit.

**Comment by vitorgalvao** [comment]
Done in https://github.com/caskroom/homebrew-cask/pull/25936.
