### ISSUE TITLE
Outdated cask: zxpinstaller

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25923]
Outdated cask: [`zxpinstaller`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/zxpinstaller.rb).

Info:
+ version: `1.5.0`.
+ appcast url: https://github.com/CreativeDo/ZXPInstaller/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
