### ISSUE TITLE
Outdated cask: xtrafinder

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25920]
Outdated cask: [`xtrafinder`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/xtrafinder.rb).

Info:
+ version: `0.25.9`.
+ appcast url: https://www.trankynam.com/xtrafinder/XtraFinder-Appcast.xml.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
