### ISSUE TITLE
Outdated cask: yakyak

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25921]
Outdated cask: [`yakyak`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yakyak.rb).

Info:
+ version: `1.3.2`.
+ appcast url: https://github.com/yakyak/yakyak/releases.atom.

**Comment by jawshooah** [comment]
Please do not run `find_outdated_appcasts` unless you are a maintainer.
