### ISSUE TITLE
wkhtmltopdf (Unbrewed dylibs were found)

### ISSUE THREAD

**Issue by YerlenZhubangaliyev** [caskroom/homebrew-cask#25989]
After install wkhtmltopdf package I've got error on any other packages installation or upgrading 

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.3.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

**Comment by miccal** [comment]
You must follow the [reporting bugs guide](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by jawshooah** [comment]
https://github.com/caskroom/homebrew-cask/issues/24720

As @miccal said, please follow the guide and search for your issue before creating a new one.
