### ISSUE TITLE
Make all eclipse Casks consistent

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#25986]
All `eclipse-` Casks should use the version scheme similar to the one defined in [`eclipse-jee.`](https://github.com/caskroom/homebrew-cask/blob/1f01157560921a05df94e75b1436898888a336ac/Casks/eclipse-jee.rb)

Should help reduce inconsistency.

**Comment by miccal** [comment]
[Like this?](https://github.com/caskroom/homebrew-cask/pull/25988)

**Comment by vitorgalvao** [comment]
Thank you (as always) @miccal. If you do them all (as you seem to perhaps be doing), please comment back after so we know to close this.

**Comment by miccal** [comment]
All done except for `eclipse-platform`, I think that one may no longer be available?

**Comment by vitorgalvao** [comment]
> I think that one may no longer be available?

Why do you think that? I can still `brew cask fetch eclipse-platform`.

**Comment by miccal** [comment]
Poor choice of words - I mean that on the list of [current version downloads](https://www.eclipse.org/downloads/eclipse-packages/) I cannot see one with `platform` in the name.

**Comment by vitorgalvao** [comment]
@miccal I see what you mean. @toolbear Can you shed some light?

**Comment by toolbear** [comment]
@vitorgalvao @miccal IIRC the download link for `eclipse-platform` is buried and might also follow a different pattern than the others. Away from computer ATM, will try and follow up with a link tomorrow.

**Comment by adidalal** [comment]
Finished in https://github.com/caskroom/homebrew-cask/pull/26039
