### ISSUE TITLE
Parse Sparkle appcasts to detect need for Cask updates

### ISSUE THREAD

**Issue by phinze** [caskroom/homebrew-cask#260]
Many mac apps use the Sparkle update framework:

http://sparkle.andymatuschak.org/

It's got a standardized "publish an update" format:

https://github.com/andymatuschak/Sparkle/wiki/publishing-an-update

We could leverage this to detect when an app might need an update.

That would be pretty cool yeah? :sunglasses:

**Comment by jm3** [comment]
Hi, is this still being worked on? Anything I can help test or document?

**Comment by vitorgalvao** [comment]
@jm3 Many casks have the proper stanza, but the feature is completely non-working yet. We don’t even have the proper idea of how we should be about doing it.

**Comment by adityadalal924** [comment]
Closing based on discussion in  https://github.com/caskroom/homebrew-cask/issues/15908 (`:format`has been removed for the time being)
