### ISSUE TITLE
Cask request: spot

### ISSUE THREAD

**Issue by mhinz** [caskroom/homebrew-cask#26076]
### Cask details

**Name**: spot

**Homepage**: https://github.com/mhinz/spotlight-cli

**Download URL**: https://github.com/mhinz/spotlight-cli/archive/1.0.0.tar.gz

**Description**: Command-line tool for Spotlight

---

This command-line tool is a convenience wrapper around Apple-shipped tools like `mdimport`, `mdls`, `mdfind`, etc.

**Comment by vitorgalvao** [comment]
This is a CLI-only open-source tool. Please submit it first to [Homebrew](https://github.com/Homebrew/homebrew-core) and only if they don’t accept it, submit here (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew](https://github.com/Homebrew/homebrew). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).

All that said, this tool is self-submitted and has too few stars, so it will likely be refused right off the bat. Though we (Homebrew-Cask) don’t frown upon that as much, there are limits. For the moment, this does not seem to be popular enough to merit inclusion. Especially if you’re asking for someone else to submit it (and likely maintain it), that’s a recipe for an abandoned cask.

Thank you for the interest, but this one is a refusal. If you wish, you can still have the cask in your own repo and direct users to use that.
