### ISSUE TITLE
Cask request: Ghost Desktop

### ISSUE THREAD

**Issue by barryanders** [caskroom/homebrew-cask#26147]
### Cask details

Ghost Desktop - Manage your Ghost blogs natively
Not familiar with Ghost? [See here](https://ghost.org), a publishing platform for professional bloggers.

**Name**: Ghost Desktop

**Homepage**: https://github.com/TryGhost/Ghost-Desktop

**Download URL**: https://github.com/TryGhost/Ghost-Desktop/releases/download/v0.7.0/ghost-desktop-0.7.0-osx.dmg

**Description**: Ghost Desktop - Manage your Ghost blogs natively

**Comment by miccal** [comment]
[Already available](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ghost.rb)

**Comment by miccal** [comment]
[@26150](https://github.com/caskroom/homebrew-cask/pull/26150)
