### ISSUE TITLE
Cask request: ICQ for macOS

### ISSUE THREAD

**Issue by ruslangallo** [caskroom/homebrew-cask#26172]
### Cask details

**Name**: ICQ for macOS

**Homepage**: https://icq.com/mac/en

**Download URL**: https://r.mail.ru/clo12053316/ftp.icq.com/pub/ICQ_Mac/ICQ.dmg

**Description**: Simple way to communicate and nothing extra. New design, free sound and video calls, group chats and much more.

**Comment by rafaelgaspar** [comment]
Working on it
