### ISSUE TITLE
Feature request: Bridge to mas for installing Mac App Store apps too.

### ISSUE THREAD

**Issue by joshmanders** [caskroom/homebrew-cask#26174]
### Description of feature/enhancement

Recently came across [mas](https://github.com/argon/mas) and it allows installing of apps in the app store and keeping them updates. Maybe a bridge to this app so that `brew cask install <app>` will check the app store if not found in any cask and install it from there too.

It does require installing via an ID and not the name, but it could possibly be searched and installed to override that. `cask install irvue` will try the cask, if not found under the hood do `mas search irvue` and get the id and then run `mas install 1039633667`

### Justification

Just a way to unify all app installs on macOS.

### Example use case

`brew cask install irvue` -> `Error: No available Cask for irvue`

`mas install 1039633667` -> `Installing Irvue - Unsplash Wallpapers`

**Comment by jawshooah** [comment]
Sorry, but we won't be implementing this. `mas` works just fine on its own, and I don't believe we gain anything my shimming around it.

If you want to keep all of your dependencies tracked in one place, [homebrew-bundle](https://github.com/Homebrew/homebrew-bundle) allows you to specify `mas` apps alongside Casks and Formulae.

**Comment by joshmanders** [comment]
Ah that's good to know, thanks, @jawshooah
