### ISSUE TITLE
Feature request: cask for unison 2.40.69 (not 2.48)

### ISSUE THREAD

**Issue by sebastienbarre** [caskroom/homebrew-cask#26206]
Unison is both a client and a server. Unfortunately, the choice of client is dictated by the server *version* -- client and server versions *have* to match on both sides.

Right now the [unison cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/unison.rb) provides 2.48 (unless you have an old OSX).

```
 if MacOS.version <= :mountain_lion
    version '2.40.69'
    sha256 '2bcc460511f2b43fa1613cc5f9ba4dd59bb12d40b5b9fb2e9f21adaf854bcf3b'
    url "http://unison-binaries.inria.fr/files/Unison-#{version}_x64.dmg"
  else
    version '2.48.15'
    sha256 '89894d14c9ff3c4d6195cb6a8065a2849e6ad55951799eedf8879e1a257d3e11'
    url "http://unison-binaries.inria.fr/files/Unison-OS-X-#{version}.zip"
```

But I need to install 2.40 on an new/recent OSX, because I talk to a server that runs 2.40. Is there a way to install 2.40 so from the current cask? I'm not sure. Can we have an alternate cask for 2.40?

Thanks

**Comment by adidalal** [comment]
We only track the latest release, not versions. That being said, this sounds like a great use of a custom tap (ie. git repo with the .rb file modified with your needs). You could also just `brew cask install modified_file.rb` locally.

**Comment by sebastienbarre** [comment]
Do you think it would be a good candidate for [caskroom/homebrew-versions: Alternate versions of casks](https://github.com/caskroom/homebrew-versions)?
