### ISSUE TITLE
Cask update request: [Polymail] (Needs Update)

### ISSUE THREAD

**Issue by jtvhk** [caskroom/homebrew-cask#26211]
### Cask details

**Name**: Polymail

**Homepage**: https://polymail.io

**Download URL**: https://sparkle-updater.polymail.io/osx/builds/Polymail-v#{version.major_minor.no_dots}.zip

**Description**: This Cask is one release behind. The current release is Polymail 1.12.

Thanks!

**Comment by miccal** [comment]
[26214](https://github.com/caskroom/homebrew-cask/pull/26214)
