### ISSUE TITLE
Feature request: brew cask info should show remote file size

### ISSUE THREAD

**Issue by muescha** [caskroom/homebrew-cask#26227]
### Description of feature/enhancement

 brew cask info (maybe a verbose info) should show file size
### Justification

i would like to see how big would be the app
### Example use case

```
$ brew cask info atom -verbose

atom: 1.11.2
https://atom.io/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/atom.rb
==> Name
Github Atom
==> Artifacts
Atom.app (app)
/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm (binary)
/Applications/Atom.app/Contents/Resources/app/atom.sh (binary)
==> Check Remote Binaries
https://github.com/atom/atom/releases/download/v1.11.2/atom-mac.zip
binary available: yes
File Size: 86.5 MB
```

**Comment by vitorgalvao** [comment]
That would require network connectivity and pinging the app server every time `info` is run. It would also be imperfect and likely not work with some server. It also means that suddenly a fast command becomes slow, since it’s checking external stuff.

Will leave open for other maintainers to chime in, but I’m a “no” on this.

**Comment by adidalal** [comment]
There are a bunch of servers that stream the file (ie. total file size can't be known). Seems finicky and a bit gimmicky, imo.

**Comment by muescha** [comment]
ok - then the only moment when we have the current file size is when we calculate the checksum for a cask. then it would go in the workflow to add a filesize to the cask which could be printed out for `info`.

**Comment by vitorgalvao** [comment]
We’re not going to add size information to casks. That would serve only to bloat them. This is definitely not a popular request (in all this years, I don’t recall it having been made before) and even so it wouldn’t work and be wrong in `:latest` casks.
