### ISSUE TITLE
navicat-for-postgresql sha256 mismatch 

### ISSUE THREAD

**Issue by snagasawa** [caskroom/homebrew-cask#26320]
I tried to install navicat-for-postgresql, but I got the error of sha256 mismatch.

```console
$ brew cask install navicat-for-postgresql
==> Downloading http://download.navicat.com/download/navicat112_pgsql_en.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask navicat-for-postgresql
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 36433d22ddfc9e463abe7b72ac4fb5a2e61e4e77c4a033e9f0365a8ca1ef6b5e
Actual: b627e9d24e6eb3fead7b9cf7bad2285725051854558a5d2f0e41e90bbd56f1c1
File: /Users/snagasawa/Library/Caches/Homebrew/Cask/navicat-for-postgresql--11.2.15.dmg
To retry an incomplete download, remove the file above.
```

I confirmed that navicat-for-postgresql was updated recently. #26105 
It seems to be the latest.
https://www.navicat.com/products/navicat-for-postgresql-release-note#mac-os-x

I updated brew.
```console
$ brew update
Already up-to-date.
$ brew cask update
Already up-to-date.
```

I deleted the downloaded file to see a lower link.
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/sha256_mismatch_error_fix_icomplete.md
> First, lets see if the problem was with your download. Delete the downloaded file (its location will be pointed out right under the Actual shasum line) and try again.
```console
$ rm -f /Users/snagasawa/Library/Caches/Homebrew/Cask/navicat-for-postgresql--11.2.15.dmg
$ ls /Users/snagasawa/Library/Caches/Homebrew/Cask/navicat-for-postgresql--11.2.15.dmg
ls: /Users/snagasawa/Library/Caches/Homebrew/Cask/navicat-for-postgresql--11.2.15.dmg: No such file or directory
```
I tried to install it again, but the problem persists.
Actual sha256 had no change.

**Comment by miccal** [comment]
[#26321](https://github.com/caskroom/homebrew-cask/pull/26321)
