### ISSUE TITLE
Cask request: microsoft-azure-storage-explorer

### ISSUE THREAD

**Issue by DustinVenegas** [caskroom/homebrew-cask#26355]
### Cask details

This cask already exists, but I'm curious about a modification.

**Currently**:
This cask does not use a SHA checksum. It also only downloads the "latest" version so updating involves either an uninstall/reinstall or forcefully reinstalling. 

**Proposal**:
I'd like to update the cask so it depends on a version, includes a SHA sum, and downloads from the final URL. Would this be an issue or is it preferred to use "current" and force reinstall packages?

**Comment by adidalal** [comment]
We always prefer versioned Casks, so this change is welcomed (assuming you can actually find a stable download url. Hashes that change per version aren't an issue, FYI. (ie. see visual-studio-code).

Closing, as the question was answered, but more than happy to answer technical/implementation questions on the PR.
