### ISSUE TITLE
Why does downloaded package's name have an extra dash?

### ISSUE THREAD

**Issue by yangnw** [caskroom/homebrew-cask#26369]
I was trying to `brew cask install mactex` from a local package by moving it to `brew --cache`/Cask, but it didn't work until I added an extra dash to its name so that brew-cask recognize it.

==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20161009.pkg
Already downloaded: /Users/Yang/Library/Caches/Homebrew/Cask/mactex--20161009.pkg

This may not be a bug at all, it's just that I don't get it. `brew cask cat mactex` shows no such syntax either. As a side note, I have curl and wget installed, but not aria2.

**Comment by jawshooah** [comment]
It's to make it easier to distinguish the cask token from the version number. Totally intentional.
