### ISSUE TITLE
Adding new casks always fails in Travis

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#26371]
Example of a correct PR: https://github.com/caskroom/homebrew-cask/pull/26342
Corresponding failure: https://travis-ci.org/caskroom/homebrew-cask/jobs/172810548

Seems to be happening (always similar errors) on all recent new cask submissions.

**Comment by adidalal** [comment]
I think audit_modified cask is breaking.... 

```
brew cask _audit_modified_casks 7f142945bca3bc11a9e2ee1e39b121e87347d053...e97a58003bfcb3cf02d3e889649fa7dfcd1e4918
````
is the wrong commit range, for example.

@reitermarkus Maybe https://github.com/caskroom/homebrew-cask/commit/7df9e9c8b13cb30562953d6e5976662cb2f9928d was needed, after all?

**Comment by Numbermaniac** [comment]
Not just new casks, in #26495 the error was `No available Cask for Casks/e-tax2014.rb`, but I was adding a zap to a completely unrelated cask.

**Comment by reitermarkus** [comment]
> @reitermarkus Maybe https://github.com/caskroom/homebrew-cask/commit/7df9e9c8b13cb30562953d6e5976662cb2f9928d was needed, after all?

Reverted it for now, couldn't find a way to make travis fail to test this, though. So I'll leave this open.
