### ISSUE TITLE
Cask request: [Gluon-scene_builder]

### ISSUE THREAD

**Issue by Clumsy-Coder** [caskroom/homebrew-cask#26374]
### Cask details

(Please fill out as much as possible)

**Gluon Scene Builder**:

**http://gluonhq.com/labs/scene-builder/**:

**http://gluonhq.com/download/scene-builder-mac/**:

**JavaFX scene builder. Drag & Drop Rapid Application Development**:

**Comment by miccal** [comment]
[26391](https://github.com/caskroom/homebrew-cask/pull/26391)
