### ISSUE TITLE
Suggestion to restore pgadmin3 in addition to pgadmin4

### ISSUE THREAD

**Issue by edrozenberg** [caskroom/homebrew-cask#26385]
These two versions of pagmin (3 and 4) are very different implementations based on different UI toolkits. Personally find pgAdmin4 ugly as heck and not pleasant to use.

Suggest to bring back the pgadmin3 cask for those of us who want to continue using it. Since the apps are called pgadmin3 and pgadmin4 it will not cause any name conflicts to keep both around.

**Comment by vitorgalvao** [comment]
It’s in [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by edrozenberg** [comment]
Thanks! I had homebrew/versions tapped but not caskroom/versions.
