### ISSUE TITLE
Non-administrator brew cask default behaviour

### ISSUE THREAD

**Issue by bertjwregeer** [caskroom/homebrew-cask#26396]
I run as a non-administrator account, and sudo is locked down to only allowing a couple of commands. The default of `/Applications` means I just get the error about brew cask being out of date and needing to re-install.

If `/Applications` is not write-able by the current user, is a fall-back to `~/Applications` a possibility, the error messages I get right now are just confusing.

I did end up setting the defaults in an environment variable and that solves the issue for the time being.

**Comment by vitorgalvao** [comment]
Use `--appdir`. This is documented in at least two places. One of them: https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/permission_denied_error_fix_appdir.md

**Comment by bertjwregeer** [comment]
Yes, I am using --appdir (which BTW is not very discoverable when every single last cask using project just says "brew cask install <blah> and doesn't mention --appdir), as I stated.

I was simply suggesting a fall-back in case `/Applications` is not writeable by the current user.

**Comment by vitorgalvao** [comment]
We’re not going to make that fallback because (unfortunately) many apps do not work at all if not in `/Applications`. Having that automatic fallback is just a new point of entry for bugs and harder debugging. `--appdir` is the official workaround and it works fine.
