### ISSUE TITLE
Outdated cask (ish): openoffice 4.1.3

### ISSUE THREAD

**Issue by aboutte** [caskroom/homebrew-cask#26445]
I am having trouble installing openoffice 4.1.3.  I am getting the following error:

```
==> Downloading https://downloads.sourceforge.net/openofficeorg.mirror/Apache_OpenOffice_4.1.3_MacOS_x86-64_install_en-US.dmg
Error: sha256 mismatch
Expected: 2eac3c6630ddbd6be771337001c8f877c2ff811620042e6071ef396788d480d8
Actual: 693681e1133f88374aa0143c7cdb67bb02ed8dbcafd4a062c97bd44f26398d12
File: /Users/aboutte/Library/Caches/Homebrew/Cask/openoffice--4.1.3.dmg
To retry an incomplete download, remove the file above.
==> Verifying checksum for Cask openoffice
==> Note: running "brew update" may fix sha256 checksum errors
```

Using the provided URL from the message I have manually downloaded the dmg and verified the cask sha256 is still accurate:

```
aboutte@: ~/Downloads
$ wget https://downloads.sourceforge.net/openofficeorg.mirror/Apache_OpenOffice_4.1.3_MacOS_x86-64_install_en-US.dmg
aboutte@: ~/Downloads
$ shasum -a 256 Apache_OpenOffice_4.1.3_MacOS_x86-64_install_en-US.dmg
2eac3c6630ddbd6be771337001c8f877c2ff811620042e6071ef396788d480d8  Apache_OpenOffice_4.1.3_MacOS_x86-64_install_en-US.dmg
```

The "dmg" file that was downloaded to `/Users/aboutte/Library/Caches/Homebrew/Cask/openoffice--4.1.3.dmg` is really just a sourceforge html page (attached as zip).  

I am happy to create a PR but will need some guidance....I did not find anything similar in issue queue or documentation. 

[openoffice--4.1.3.dmg.zip](https://github.com/caskroom/homebrew-cask/files/573061/openoffice--4.1.3.dmg.zip)

**Comment by vitorgalvao** [comment]
Can’t reproduce. Do you by any chance have a custom `.curlrc`?

**Comment by aboutte** [comment]
Thanks @vitorgalvao.  I had the following in my `.curlrc` which was causing the issue:

```
referer = ";auto"
```
