### ISSUE TITLE
Cask codebug possibly dead

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#26510]
The Cask for [`codebug`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/codebug.rb) is failing as the [homepage](http://www.codebugapp.com/) is currently down.

I propose to wait a bit, and if the website remains down this Cask should maybe be removed.

**Comment by Numbermaniac** [comment]
Is [this](http://www.codebug.org.uk/) the same thing? Seems like the URL might have changed.

**Comment by miccal** [comment]
I am not sure - I cannot see any app available?

**Comment by reitermarkus** [comment]
> Is this the same thing, by any chance?

Nope: http://www.codebug.org.uk/whatiscodebug/
