### ISSUE TITLE
Installing updating cask locally without waiting for upstream

### ISSUE THREAD

**Issue by wamatt** [caskroom/homebrew-cask#26529]
Ok so lets say you come across and old cask. You update it using the super handy `cask-repair` tool. However now you want to use this new shinyness straight away, because like me you're an impatient bastard.  🍟

Doing a `brew cask install <x>` installs the previous version because the PR is still appending approval. That's no good, so lets do this instead:

![image](https://cloud.githubusercontent.com/assets/1271434/20041869/92e224e2-a424-11e6-98d1-ca1ca2bfe0cb.png)

While that works, how is everyone else achieving this goal? It's seems highly likely I'm going about this wrong, but as a fairly new contributor this particular function appears to be non-obvious.

**Comment by vitorgalvao** [comment]
Your sequence of commands seems efficient and could easily be made into a script or shell function.

That said, I do understand this is suboptimal. I’m planning some major changes to `cask-repair` and I’ll make sure to add a `--install` flag (or something like that) to also install the cask before or right after submitting the PR. I’d say that would fix your use case nicely.

I’ll leave the issue open for a few days anyway, in case some other non-maintainers want to chime in.

**Comment by wamatt** [comment]
sounds great. good luck with the changes 👍

**Comment by jawshooah** [comment]
Alternatively, you could go to the open PR, click "Files changed", click "View", click "Raw", copy the URL and `brew cask install` that. For example, for your recent PR:

```
brew cask install https://raw.githubusercontent.com/wamatt/homebrew-cask/dc93dae6aead3d312b789954d0671b18073baec7/Casks/keycue.rb
```
