### ISSUE TITLE
can't install cask and terminal has no response to command line. 

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [caskroom/homebrew-cask#26548]
==> Creating Caskroom at /usr/local/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
Password:==> Sorry, try again.

Password:==> Sorry, try again.

==> sudo: 3 incorrect password attempts
Password:
==> chmod: /usr/local/Caskroom: No such file or directory
==> chown: /usr/local/Caskroom: No such file or directory
==> chgrp: /usr/local/Caskroom: No such file or directory
==> Downloading https://dl.smilesoftware.com/com.smileonmymac.textexpander/514.0
brew install caskroom
brew doctor 
brew cask install jumpcut
what is wrong with you
brew tap --repair
brew update

curl: (56) SSLRead() return error -36
Error: Download failed on Cask 'textexpander' with message: Download failed: https://dl.smilesoftware.com/com.smileonmymac.textexpander/514.0/1456193896/TextExpander-514.0.zip
The incomplete download is cached at /Users/zhangshiying/Library/Caches/Homebrew/Cask/textexpander--514.0-1456193896.zip.incomplete
zhangshiyingdeMacBook-Air:~ zhangshiying$ brew install caskroom
brew doctor
brew cask install jumpcut
what is wrong with you
brew tap --repair
brew update
brew install caskroom
 
brew doctor

**Does anyone know what is wrong with my terminal? why there is no response to command line?**

**Comment by vitorgalvao** [comment]
This bug report makes no sense. Please clean it up. Add proper [code blocks](https://help.github.com/enterprise/11.10.340/user/articles/github-flavored-markdown/#syntax-highlighting) and make clear what it a command you called vs a response to the command.

`brew install caskroom` does not make sense, neither does `what is wrong with you` neither a whole lot of things. It just looks like you input your password wrongly and nothing was installed.

Please clean up the bug report and report back, and I’ll reopen.

**Comment by zhangshiyinrunwithcc** [comment]
sure!
thx a lot!
i ll do the clean up and then report the condition.
