### ISSUE TITLE
pkg uninstall script fails when removing protected files

### ISSUE THREAD

**Issue by vmrob** [caskroom/homebrew-cask#2655]
I'm attempting to write a cask for Wacom's Intuous Drivers and am encountering problems with the uninstall behavior.  The script does its job in uninstalling the software from the system, and, in fact does this properly when called via `brew cask uninstall wacom-intuous-driver`.  The issues is that after the script has finished executing, during the purge_files method of installer.rb, it can't successfully remove the installed files from the Caskroom due to insufficient privileges.  Is there a way to ensure that the files are removed with elevated permissions?

cask below:

	class WacomIntuousDriver < Cask
	  url 'http://cdn.wacom.com/u/drivers/mac/pro/WacomTablet_6.3.7-3.dmg'
	  homepage 'http://us.wacom.com/en/support/drivers'
	  version '6.3.7-3'
	  sha1 '09f6232ad200de159f3bf204a18f3d978cb9e9ea'
	  install 'Install Wacom Tablet.pkg'
	  uninstall :script => '/Applications/Wacom Tablet.localized/Wacom Tablet Utility.app/Contents/Resources/uninstall.pl'
	end

**Comment by vitorgalvao** [comment]
This is likely fixed. If not, it will resurface.
