### ISSUE TITLE
Cask nsregextester: download link is dead

### ISSUE THREAD

**Issue by eccstartup** [caskroom/homebrew-cask#26572]
Check [here](https://github.com/caskroom/homebrew-cask/commit/13047a62cb66d51cd804e93f80abc0989df0fef8), the [link](http://vegh.ca/nsregextester/NSRegexTester.zip) cannot be reached. 

Please update this Cask.

**Comment by miccal** [comment]
[#26574](https://github.com/caskroom/homebrew-cask/pull/26574).
