### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by a59** [caskroom/homebrew-cask#26618]
### Description of feature/enhancement

Using 

brew cask install --local libreoffice

I would like to install libreoffice into ~/Applications in a similar way that 

brew linkapps [--local] [formulae]:
    Find installed formulae that provide .app-style macOS apps and symlink them
    into /Applications, allowing for easier access.

    If no formulae are provided, all of them will have their apps symlinked.

    If provided, --local will symlink them into the user's ~/Applications
    directory instead of the system directory.

does

### Justification

I don't have admin access to /Applications

### Example use case

brew cask install --local libreoffice

**Comment by vitorgalvao** [comment]
Use [`--appdir`](https://github.com/caskroom/homebrew-cask/blob/1de4657a0ed35463602b31061b0c16dc9078b8a0/USAGE.md#options).

**Comment by a59** [comment]
Thanks
