### ISSUE TITLE
Bug report: Unable to uninstall pacage eclipse-jee due to malformed URL to its metadata

### ISSUE THREAD

**Issue by pjedruszuk** [caskroom/homebrew-cask#26630]
#### Description of issue

Cask fails to uninstall eclipse-jee, probably due to special characters in the the metadata path. This path seems to be generated with Eclipse version, which apparently contains some path-breaking characters (comma and colon). At the time of writing this bug report, Cask is trying to resolve Eclipse metadata from:
```
/usr/local/Caskroom/eclipse-jee/.metadata/4.6.1,neon:1a/20161109225059.162/
```

Adding `--force` flag does not change the outcome.
 
Steps to reproduce:
- install package eclipse-jee 
- try to uninstall package eclipse-jee

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
==> Downloading /usr/local/Caskroom/eclipse-jee/.metadata/4.6.1,neon:1a/20161109225059.162/Casks/eclipse-jee.rb
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.0-17-gf802c55 (Macintosh; Intel macOS 10.12.1) curl/7.49.1 /usr/local/Caskroom/eclipse-jee/.metadata/4.6.1,neon:1a/20161109225059.162/Casks/eclipse-jee.rb -o /Users/piotrjedruszuk/Library/Caches/Homebrew/Cask/eclipse-jee.rb
curl: (3) <url> malformed
Error: No available Cask for /usr/local/Caskroom/eclipse-jee/.metadata/4.6.1,neon:1a/20161109225059.162/Casks/eclipse-jee.rb
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated.
Please install XQuartz 2.7.9 (or delete it):
  https://xquartz.macosforge.org

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.12.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.0-17-gf802c55
Homebrew/homebrew-core (git revision 6b5a2; last commit 2016-11-09)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.0-17-gf802c55
caskroom/homebrew-cask (git revision 8dcc; last commit 2016-11-09)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/piotrjedruszuk/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3431
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/piotrjedruszuk/bin:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="pl_PL.UTF-8"
==> Running As Privileged User:
No
```
</details>

**Comment by adidalal** [comment]
Never thought about metadata dir. all casks that use before colon will have the issue, I think

**Comment by miccal** [comment]
There are 9 `eclipse-*` Casks and the Cask `scala-ide` that use a colon in the `version` stanza.

**Comment by miccal** [comment]
Could we possible replace the colon with a semicolon, so change `before_colon` and `after_colon` with `before_semicolon` and `after_semicolon` in the [`version`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md) stanza? I believe that would fix this problem.

I think the files [`version.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/dsl/version.rb) and [`version_spec`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/spec/cask/dsl/version_spec.rb) would need to be updated.

**Comment by vitorgalvao** [comment]
The `semicolon` option is fine by me. Pinging @jawshooah.

**Comment by reitermarkus** [comment]
Basically the problem here is that `/` and `:` are kinda ambiguous. Try `touch \:` and look at it in the Finder. It will be a `/`.

Seems like `curl` cannot handle this. But also it shouldn't. Apparently the cask file in the `.metadata` directory is downloaded to `Hbc.cache` before being opened instead of simply being loaded directly.

**Comment by vitorgalvao** [comment]
The issue here is HFS+ using colons as path separators, which works mostly fine in day to day use, even though it [looks like a mess in writing](http://www.wsanchez.net/papers/USENIX_2000/):

> Another obvious problem is the different path separators between HFS+ (colon, ':') and UFS (slash, '/'). This also means that HFS+ file names may contain the slash character and not colons, while the opposite is true for UFS file names. This was easy to address, though it involves transforming strings back and forth. The HFS+ implementation in the kernel's VFS layer converts colon to slash and vice versa when reading from and writing to the on-disk format. So on disk the separator is a colon, but at the VFS layer (and therefore anything above it and the kernel, such as libc) it's a slash. However, the traditional Mac OS toolkits expect colons, so above the BSD layer, the core Carbon toolkit does yet another translation. The result is that Carbon applications see colons, and everyone else sees slashes. This can create a user-visible schizophrenia in the rare cases of file names containing colon characters, which appear to Carbon applications as slash characters, but to BSD programs and Cocoa applications as colons.

I wonder what [APFS](https://en.wikipedia.org/wiki/Apple_File_System) does.

I’d like to get @jawshooah’s opinion here as well since he implemented the version methods and we both discussed them extensively. It does seem clear we might get rid of the `*_colon` methods, though.

Related: https://github.com/caskroom/homebrew-cask/issues/26747.

**Comment by jawshooah** [comment]
@vitorgalvao It looks like https://github.com/Homebrew/brew/pull/1502/commits/a799a3979f907307657ef9baddede51fba7d4d18 should be sufficient to fix this particular issue. I don't think we need to ban colons from version strings, at least not until we see bug reports actually caused by them. This particular report just exposed a place where we were using `curl` unnecessarily, and incorrectly to boot (prepend `file://` to the path containing colons and you won't have any problems).

**Comment by vitorgalvao** [comment]
> I don't think we need to ban colons from version strings, at least not until we see bug reports actually caused by them.

If colons themselves are no longer an issue, I’ll update #26747. We did already have some bug reports regarding slashes, though, so those should still be detected in `audit`, no?

**Comment by jawshooah** [comment]
Yes, we should definitely still disallow slashes.
