### ISSUE TITLE
Feature request: specify cask download location

### ISSUE THREAD

**Issue by edrozenberg** [caskroom/homebrew-cask#26650]
### Description of feature/enhancement

Would like a parameter to be able to override the download location of a cask with a different download location.

### Justification

We're automating setting up multiple machines and would like to be able to download all the software to a local server once, then have each machine download and install from that local server instead of each machine having to slowly download each time from the original url's.

### Example use case

```brew cask install --download-url='http://myserver.mydomain/software' firefox```

This would have the effect of telling the brew cask installer to use a different url:

Normal:

```https://ftp.mozilla.org/pub/firefox/releases/#{version}/mac/#{language}/Firefox%20#{version}.dmg"```

With --download-url parameter:

```http://myserver.mydomain/software/firefox/releases/#{version}/mac/#{language}/Firefox%20#{version}.dmg"```

Or more simply could be:

```http://myserver.mydomain/software/Firefox%20#{version}.dmg"```
(makes it easier for the user, no need to create the proper dir hierarchy, but assumes only one language will be available, in this specific example of firefox)

**Comment by adidalal** [comment]
This sounds like attacking the problem at potentially the wrong point - a caching proxy should serve the same purpose, right? Alternatively, I would suggest what you're already doing, copying the cache directory.

**Comment by edrozenberg** [comment]
Another possible implementation, which seems simpler would be:

```brew cask install --cache-url='http://myserver.mydomain/software' firefox```

Which tells brew cask to use that url when looking for cached items, instead of looking in ```~/Library/Caches/Homebrew/Cask```

This would have the advantage of making it pretty simple to maintain the cache server - just install/remove casks on that machine, and its cache stays updated - and all other machines can use that same cache by pointing to it.

**Comment by edrozenberg** [comment]
@adidalal Thanks, a caching proxy could also work, downside being everyone has to use a proxy - currently we're not running any local proxies.

**Comment by adidalal** [comment]
I like the second idea significantly more - will let some others comment as well.

**Comment by vitorgalvao** [comment]
Almost no one would have a use for this, so I see little point on spending time on this officially. If you want special URLs, you can always make a tap. It would take as much time for you to set all `--download-url=` flags as it would to change all urls in all casks in your tap.

There’s even an easier solution. If it’s a local server and all the machines can access it, why not have a common mount point and set `HOMEBREW_CACHE` to it? HB is not designed for such a setup, but it might work.

**Comment by edrozenberg** [comment]
I'll probably wind up rsyncing a cache dir to each of the target machines. Mounting is prone to problems and requires additional work to initiate the mount and then unmounting while making sure nothing is locking the mounted volume and preventing the unmount.

**Comment by Numbermaniac** [comment]
Could it be possible for you to go into the `firefox.rb` file on each machine and change the URL to your server there? Copying the cached download is probably the easiest solution though.

**Comment by edrozenberg** [comment]
@Numbermaniac Thanks but that won't scale, it's dozens of brews or more across a number of machines.

**Comment by vitorgalvao** [comment]
> Thanks but that won't scale, it's dozens of brews or more across a number of machines.

Make your own tap and make the change there.
