### ISSUE TITLE
Sketchup is outdated, it is 2017 already.

### ISSUE THREAD

**Issue by empewoow** [caskroom/homebrew-cask#26707]
I tried:

```
brew install Caskroom/cask/sketchup

```
But it returned:

```
==> brew cask install Caskroom/cask/sketchup
==> Downloading https://dl.trimble.com/sketchup/SketchUpMake-en.dmg
######################################################################## 100,0%
==> No checksum defined for Cask sketchup, skipping verification
Error: It seems the App Suite source is not there: '/usr/local/Caskroom/sketchup/latest/SketchUp 2016'
```

It seems it is just outdated. In the source of [homebrew-cask/Casks/sketchup.rb](https://github.com/caskroom/homebrew-cask/blob/60531a2812005dd5f17dc92f3ce7419af3c5d019/Casks/sketchup.rb) it says suite 'SketchUp 2016', while it downloaded the latest 2017 version. Therefore it cannot complete the install.

Should something like this be reported here or somewhere else?

**Comment by victorpopkov** [comment]
> Should something like this be reported here or somewhere else?

Yes, this should be reported here and thank you for your report.

Fixed in https://github.com/caskroom/homebrew-cask/issues/26709, so it should be good now.
