### ISSUE TITLE
Unity include Standard Assets

### ISSUE THREAD

**Issue by kimegede** [caskroom/homebrew-cask#26719]
Would it somehow be possible to add the download of "Stadard Assets"?
Or make flags when installing (like `brew cask install unity --include-standard-assets` (maybe a bad name)).

<img width="928" alt="unity_-_standard_assets" src="https://cloud.githubusercontent.com/assets/870013/20242595/13ed2b7c-a934-11e6-8153-a43989db9599.png">

**Comment by miccal** [comment]
I don't think so, but maybe you could create a new Cask called `unity-standardassets` or something like that?

**Comment by kimegede** [comment]
Cool, PR is made: https://github.com/caskroom/homebrew-cask/pull/26721
