### ISSUE TITLE
Bug report: brew cask style reports 'Block has too many lines' (macOS 12)

### ISSUE THREAD

**Issue by mvermaes** [caskroom/homebrew-cask#26764]
#### Description of issue

I was trying to submit a simple version update to the vmware-fusion cask, but the style check failed with the message that `Block has too many lines`. After investigating further, I found that I get this message with both `brew style` and `brew cask style` (I'm not sure if this was occurring with these commands previously to installing `cask-repair`).

I was able to get `brew style` running again by uninstalling `rubocop` and `rubocop-cask` and re-running `brew style`. But subsequently running `brew cask style` results in 96 files reporting errors again.

Since I haven't found any other people reporting similar issues, it seems like it's probably something specific to my environment, but hopefully someone can point me in the right direction to track down the issue.

`brew config/doctor` and other output is at https://gist.github.com/mvermaes/5271e659e7f67b08bb8c60d4014ef569

Thanks a lot for your help.

**Comment by miccal** [comment]
I am not sure if it is relevant or even related, but I had a weird issue with `rubocop-cask` a few weeks ago - see [here](https://github.com/vitorgalvao/tiny-scripts/issues/50).

**Comment by mvermaes** [comment]
Thanks for the suggestion. I actually did see your report, but it seemed slightly different since you were getting SSL messages when reinstalling rubocop-cask. I have a feeling the actual problem is probably similar though - something to do with my Ruby environment.

Did you manage to resolve your issue or find a workaround?

**Comment by miccal** [comment]
No, my attempts to fix my problem made it much worse, and I gave up and reinstalled my OS.

**Comment by miccal** [comment]
Strange, Travis has failed on the PR [#26778](https://github.com/caskroom/homebrew-cask/pull/26778) with the same error - `C:  1:  1: Block has too many lines. [29/25]`.

**Comment by vitorgalvao** [comment]
There’s nothing wrong with your setup. I can reproduce this as well.

However, `brew style` has nothing to do with this, and you’re not supposed to just run `brew cask style` (or `brew style`, even) without arguments. This has also nothing to do with `cask-repair`, that only runs the commands.

Issue here seems to be that `rubocop` (which `rubocop-cask` uses) now has a cop to check for block length and defaults to `25`. We need to turn that off in `rubocop-cask`.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/rubocop-cask/issues/44.

**Comment by vitorgalvao** [comment]
Fixed in https://github.com/caskroom/rubocop-cask/commit/58481ef6222964a7952c95e4b9245333a488baf1. Thank you for the report.
