### ISSUE TITLE
Error: Uh oh, could not figure out how to unpack '/Users/bishwa/Library/Caches/Homebrew/Cask/startninja--latest.dmg' [Error][cask]

### ISSUE THREAD

**Issue by thapabishwa** [caskroom/homebrew-cask#26831]
Error: Uh oh, could not figure out how to unpack '/Users/bishwa/Library/Caches/Homebrew/Cask/startninja--latest.dmg'

Possible fix: Renew the link  to http://files.downloadnow.com/s/software/13/00/72/92/StartNinjaInstaller.dmg?token=1479363175_45c89e54769bc29135134efcdffb93ab&fileName=StartNinjaInstaller.dmg. At this point it looks like the downloaded file is corrupted.
<img width="730" alt="startninja" src="https://cloud.githubusercontent.com/assets/15176360/20364099/30c61752-ac42-11e6-926e-d2583372b4bd.png">

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/26832.

Next time, please [follow the guide](https://github.com/caskroom/homebrew-cask#reporting-bugs) or the issue might be closed without review.
