### ISSUE TITLE
Feature request: emacs console command

### ISSUE THREAD

**Issue by edrex** [caskroom/homebrew-cask#26835]
### Description of feature/enhancement

The `emacs` cask doesn't include a terminal mode `emacs` command. Provide a terminal mode command with the cask.

One option would be a wrapper which calls the main executable for the .app with the `-nw` (no windowing) flag:

```
❯ cat "$(HOME)/bin/emacs"
#!/bin/sh

# Launch the cask Emacs in console mode
/Applications/Emacs.app/Contents/MacOS/Emacs -nw "$@"
```

### Justification

It is surprising to get the OS bundled terminal emacs after having installed the emacs cask.

Is there some policy like *Casks shouldn't provide console commands duplicating commands provided by `brew` formulas*?

### Example use case

Edit text files from the terminal, eg

```
brew cask install emacs
emacs ~/Journal/$(date +%Y-%m-%d).org
```

**Comment by vitorgalvao** [comment]
> Is there some policy like *Casks shouldn't provide console commands duplicating commands provided by `brew` formulas*?

There’s a policy to “be as close as possible to a manual installation and not make up wrappers unless they are absolutely necessary or encouraged by the developer”.

This app includes four CLI binaries in it. If none of them does what you want, it appears the developer did not want to provide such functionality as a binary.

You also gave a very simple command that could just as easily be added to your shell’s startup files, so I suggest you do just that.

*If however* you can find any official documentation encouraging users to make such a wrapper for this app, we can discuss including it in the cask.

**Comment by phs75** [comment]
I second the feature request. And find it surprising/dangerous that "one get(s) the OS bundled terminal emacs after having installed the emacs cask" as mentioned above.

Emacs is often used in batch mode (see its -batch option), whether run from scripts or from the terminal. The current setting does not work ok for me and I've had to create a link /usr/local/bin/emacs -> /Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_9 for my scripts to work. Much better if this was done by homebrew cask, perhaps optionally.
