### ISSUE TITLE
Cask request: visual-studio-mac

### ISSUE THREAD

**Issue by km-tr** [caskroom/homebrew-cask#26882]
### Cask details

(Please fill out as much as possible)

**Name**:visual-studio-mac

**Homepage**: https://www.visualstudio.com/vs/visual-studio-mac/

**Download URL**:https://www.visualstudio.com/thank-downloading-visual-studio-mac/?sku=vsmac

**Description**:A mobile-first, cloud-first IDE. Made for the Mac.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/26837
