### ISSUE TITLE
helm version mismatch

### ISSUE THREAD

**Issue by mcandre** [caskroom/homebrew-cask#26901]
brew cask has a formula "helm@2.0.0", that actually installs 2.0.0-rc.2. When connecting to the helm server, the client reports a version mismatch.

```
$ brew cask info helm
helm: 2.0.0
https://github.com/kubernetes/helm
/usr/local/Caskroom/helm/2.0.0-rc.2 (3 files, 60.9M)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/helm.rb
==> Name
Helm
==> Artifacts
darwin-amd64/helm (binary)
```

Now that the final 2.0.0 release is available, we could update the brew cask formula for helm to drop the rc:

https://github.com/kubernetes/helm/releases

**Comment by vitorgalvao** [comment]
Error is on your setup. You need to `reinstall` the cask. `info` is telling you the latest version of the cask and where you have it installed (older version).
