### ISSUE TITLE
Feature request: URLs with credentials

### ISSUE THREAD

**Issue by montge** [caskroom/homebrew-cask#26913]
### Description of feature/enhancement

The request is for providing ability for URL's that have username and passwords in them.   Basically support basic authentication.  There may be a need to support custom PKI CA's for organizations with internal certificate authorities.

### Justification

This is designed to support scenarios where organizations have private repositories (e.g. maven/nexus) repositories that require username and passwords.  Certain vendors (e.g. Oracle) don't provide public download of all files (e.g. PSU's) that require username and password to download.

### Example use case

url: 'https://myinternalrepo/file.dmg'
url_username: 'myusername'
url_password: 'mypassword'

**Comment by vitorgalvao** [comment]
We already support [various parameters in `url`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#additional-https-url-parameters) that may fit your needs.

I don’t recall encountering casks with the limitations you’re describing. Either way, we’re not going to add usernames and passwords to casks for what I hope are obvious reasons: login details are private, and casks are public.

If you want those options to add to your own private tap, then I don’t see that happening either as it wouldn’t benefit many people.
