### ISSUE TITLE
Deprecate `brew cask update`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#26921]
`brew cask update` is simply an alias to `brew update`. Even so, it’s somewhat common for me to see people recommend `brew cask upgrade`, or even worse, `brew update && brew cask update`.

Especially now that two projects are integrated, I think we should just scrape `brew cask update` altogether, having a transitional period where it will encourage users to simply `brew update` instead.

Pinging @caskroom/maintainers @MikeMcquaid.

**Comment by claui** [comment]
Pretty much in favor of the suggestion! I feel the current behavior blatantly violates [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

@vitorgalvao Picking up on your suggestion, I could imagine a transition as follows:

- during the transitional period, we want to print a **friendly warning** while `brew cask update` continues to “work”,

- (optionally) towards the end of the transitional period, we might want to **add a deadline** to the warning – given the number of bad scripts that appear to be out there, not only would such a warning convey a proper sense of urgency to our users; it would also protect maintainers from non-productive complaints wasting their time post-shutoff,

- finally, **remove** the `brew cask update` command altogether the night after the deadline without additional notice.

**Comment by MikeMcQuaid** [comment]
@claui's plan sounds great to me.
