### ISSUE TITLE
Cask request: Sequel Pro

### ISSUE THREAD

**Issue by thapabishwa** [caskroom/homebrew-cask#26959]
### Description of feature/enhancement

Adding Sequel Pro to the homebrew cask 

### Justification
MySQL database management for Mac OS X
Link to the content: http://www.sequelpro.com

### Example use case

brew cask install sequel-pro

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/sequel-pro.rb

Please search before making requests. It even has the *exact* name you wrote.
