### ISSUE TITLE
Bug report: [microsoft-lync-plugin has been officially discontinued upstream]

### ISSUE THREAD

**Issue by ChristopheChirat** [caskroom/homebrew-cask#26996]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

microsoft-lync-plugin has been officially discontinued upstream

MacBook-Pro:~ christophechirat$ brew install Caskroom/cask/microsoft-lync-plugin
==> brew cask install Caskroom/cask/microsoft-lync-plugin
==> Caveats
microsoft-lync-plugin has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of macOS.

==> Downloading https://lync12.lyncweb.microsoft.com/lwa/Plugins/LWAPluginInstaller.pkg

curl: (6) Could not resolve host: lync12.lyncweb.microsoft.com
Error: Download failed on Cask 'microsoft-lync-plugin' with message: Download failed: https://lync12.lyncweb.microsoft.com/lwa/Plugins/LWAPluginInstaller.pkg
The incomplete download is cached at /Users/christophechirat/Library/Caches/Homebrew/Cask/microsoft-lync-plugin--latest.pkg.incomplete

**Comment by vitorgalvao** [comment]
Home page doesn’t even exist anymore. I’ll just remove the cask altogether.
