### ISSUE TITLE
Cask request: Google Chrome Canary

### ISSUE THREAD

**Issue by wxmn** [caskroom/homebrew-cask#27000]
### Cask details

(Please fill out as much as possible)

**Name**: Google Chrome Canary

**Homepage**: https://www.google.com/chrome/browser/canary.html

**Download URL**: https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg

**Description**: Google Chrome Canary has the newest of the new Chrome features.

**Comment by vitorgalvao** [comment]
[caskroom/versions](https://github.com/caskroom/homebrew-versions)
