### ISSUE TITLE
Feature request: On `cask reinstall`, `fetch` before `uninstall`

### ISSUE THREAD

**Issue by rwanyoike** [caskroom/homebrew-cask#27075]
### Description of feature/enhancement

`cask reinstall` to run the uninstall process after the download process.

### Justification

`cask reinstall` runs the uninstall process before the download process. 

If the download fails you end up without an app 😐:

```
$ brew cask reinstall intellij-idea-ce
==> Removing App: '/Applications/IntelliJ IDEA CE.app'
==> Running uninstall process for intellij-idea-ce; your password may be necessary
==> Removing files: ["/usr/local/bin/idea"]
Password:
==> Downloading https://download.jetbrains.com/idea/ideaIC-2016.3.dmg
######################################################################## 100.0%
curl: (52) Empty reply from server
Error: Download failed on Cask 'intellij-idea-ce' with message: Download failed: https://download.jetbrains.com/idea/ideaIC-2016.3.dmg
...
```

**Comment by vitorgalvao** [comment]
Sounds reasonable. Updated the title.

**Comment by adidalal** [comment]
Should be a fairly straightforward change to [`hbc/cli/reinstall.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb), if you want to take a crack at it!
