### ISSUE TITLE
Remove mplayerx because it includes malware and/or adware

### ISSUE THREAD

**Issue by therealmarv** [caskroom/homebrew-cask#27105]
After installing MPlayerX with homebrew cask "malwarebytes anti malware" detects malware behaviour because of MPlayerX installation.

More background information:
https://blog.malwarebytes.com/threat-analysis/2016/09/pup-friday-mplayerx/

**Comment by vitorgalvao** [comment]
We won’t remove it. This has been discussed at length before. However, there is something we will do. You need to [follow these steps](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/apps_with_malware.md).
