### ISSUE TITLE
Update not working as expected

### ISSUE THREAD

**Issue by CiraciNicolo** [caskroom/homebrew-cask#27107]
The update command on cask is not working, I've installed through cask virtualbox version 5.0.20r106931 but when I do "brew cask info virtualbox" I get that the current version is 5.1.10-112026 and "brew cask update virtualbox" give me "Already up-to-date.".

Is not update <name> meant to update the specified cask?

**Comment by vitorgalvao** [comment]
> Is not update meant to update the specified cask?

No. Read the man page or search for it. This has been discussed ad-nauseam and there are many issues on it. We do not have upgrade functionality yet.
