### ISSUE TITLE
Bug report: [cask uninstall failing due to AppleEvent time out]

### ISSUE THREAD

**Issue by JamesMcMahon** [caskroom/homebrew-cask#27116]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

I'm hitting an issue uninstalling some cask installs, I've tried two different uninstalls and they both fail with:

> ==> Standard Error of failed command:
36:109: execution error: System Events got an error: AppleEvent timed out. (-1712)

Full output for Java:

```
⋊> ~ brew cask uninstall java                                                                                                        12:02:19
Warning: Calling MacOS.release is deprecated!
Use MacOS.version instead.
/Users/jamie/.brew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:73:in `block in load'

==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
Password:
==> Removing launchctl service com.oracle.java.Java-Updater
==> Quitting application ID com.oracle.java.Java-Updater
==> 36:109:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/osascript -e tell application \"System Events\" to count processes whose bundle identifier is \"com.oracle.java.Java-Updater\"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:109: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 50723 exit 1>
```

Full output for Amethyst:

```
⋊> ~ brew cask uninstall amethyst                                                                                                    11:55:36
Warning: Accessibility access cannot be disabled automatically on this version of macOS.
See System Preferences to disable it manually.
==> Running uninstall process for amethyst; your password may be necessary
==> Removing login item Amethyst
==> 36:84:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e tell application \"System Events\" to delete every login item whose name is \"Amethyst\"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:84: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 50569 exit 1>
```

Any suggestions?

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
⋊> ~ brew cask uninstall amethyst --verbose                                                                                          12:07:45
Warning: Accessibility access cannot be disabled automatically on this version of macOS.
See System Preferences to disable it manually.
==> Running uninstall process for amethyst; your password may be necessary
==> Removing login item Amethyst
==> 36:84:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e tell application \"System Events\" to delete every login item whose name is \"Amethyst\"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:84: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 50870 exit 1>
Error: Kernel.exit
```

```
⋊> ~ brew cask uninstall java --verbose                                                                                              12:09:50
Warning: Calling MacOS.release is deprecated!
Use MacOS.version instead.
/Users/jamie/.brew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:73:in `block in load'

==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
Password:
==> Removing launchctl service com.oracle.java.Java-Updater
==> Quitting application ID com.oracle.java.Java-Updater
==> 36:109:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/osascript -e tell application \"System Events\" to count processes whose bundle identifier is \"com.oracle.java.Java-Updater\"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:109: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 51006 exit 1>
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
⋊> ~ brew doctor                                                                                                                     12:11:24
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
⋊> ~ brew cask doctor                                                                                                                12:11:35
==> macOS Release:
10.12.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.1-68-g949a3b6
Homebrew/homebrew-core (git revision fa0bf; last commit 2016-11-24)
==> Homebrew Executable Path:
/Users/jamie/.brew/bin/brew
==> Homebrew Cellar Path:
/Users/jamie/.brew/Cellar
==> Homebrew Repository Path:
/Users/jamie/.brew
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.1-68-g949a3b6
caskroom/homebrew-cask (git revision b10c; last commit 2016-11-24)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/Users/jamie/.brew/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/jamie/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/Users/jamie/.brew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3456
==> Contents of $LOAD_PATH:
/Users/jamie/.brew/Library/Homebrew/cask/lib
/Users/jamie/.brew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/jamie/.rbenv/shims:/Users/jamie/.go/bin:/Users/jamie/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/jamie/bin:/Users/jamie/.brew/Library/Taps/homebrew/homebrew-services/cmd:/Users/jamie/.brew/Library/Homebrew/cask/cmd:/Users/jamie/.brew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/Users/jamie/.brew/bin/fish"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
```
</details>

**Comment by adidalal** [comment]
Hmm, are you a non-admin user and prevented AppleScript access to System preferences in the past? Almost looks like it can't get permissions to do the uninstall and then just times out.

**Comment by JamesMcMahon** [comment]
I am running as a non-admin user and I'm essentially trying to clean up cask packages because I've been struggling with them post Homebrew blocking `sudo`.

I've also tried revert https://github.com/Homebrew/brew/commit/a0f9963391ee1062304f2ddabce84ec0aa2b7df7#diff-9252bdaacb30cce70aba1177ed9bc9ba locally, to see if running with `sudo` does the full uninstall, but I get the same errors.

**Comment by adidalal** [comment]
That makes sense. Though not recommended, you can try [adding yourself to `/etc/sudoers`](https://github.com/reitermarkus/dotfiles/blob/f104a8a7a592204a66646810ae8fbd956023c988/.sh#L43-L60), and then using `brew cask uninstall --force` to clean up.

After that, a normal `brew cask install` should work correctly

**Comment by JamesMcMahon** [comment]
I am in sudoers. Maybe not the most secure thing but it allows me to actually run things as this user, in the connivence vs security scale, concessions were made.

If I revert the commit that prevents `sudo` (temporarily of course) with `git revert a0f9963391ee1062304f2ddabce84ec0aa2b7df7` and I rerun the uninstall I get the same error sadly.

```
⋊> ~/.brew on stable  sudo brew cask uninstall --force --verbose amethyst                                                            13:16:36
Password:
Warning: Accessibility access cannot be disabled automatically on this version of macOS.
See System Preferences to disable it manually.
==> Running uninstall process for amethyst; your password may be necessary
==> Removing login item Amethyst
==> 36:84:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e tell application \"System Events\" to delete every login item whose name is \"Amethyst\"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:84: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 54170 exit 1>
Error: Kernel.exit
```

To give you the big picture my goal is actually to uninstall everything homebrew-cask installed and essentially blow it away. It's just not working for my setup with some of the security changes that Homebrew made lately. So my goal is to clean up away in the neatest way possible.

**Comment by JamesMcMahon** [comment]
Actually if I install things in `~/Applications` versus `/Applications` it could still work for me, I'd need to figure that out.

**Comment by vitorgalvao** [comment]
@JamesMcMahon That error is unimportant if you’re trying to blow everything. Most apps don’t need such action.

Uninstall what you can via HBC, and for the rest, do it manually.

**Comment by JamesMcMahon** [comment]
My concern is that I don't know all the places that the Java package is installed in. I am assuming everything is symlinked into my Homebrew cask directory.

Is there a way to track down all the symlinks that Homebrew cask is making?

**Comment by reitermarkus** [comment]
Since Java uses a `pkg` installer, Homebrew Cask will just use `installer` to install it.

You will have to use `pkgutil` and the package id to find all the things that were installed.

**Comment by vitorgalvao** [comment]
> I am assuming everything is symlinked into my Homebrew cask directory.

You’re assuming wrongly. We mimic manual installations as close as possible, so we seldom make symlinks and you can install/uninstall using regular instructions.

And as @reitermarkus mentioned, `pkg` casks have free reign and they act as if you had double clicked the installer and proceeded manually. That means that if you find a good resource online on how to uninstall java, you can follow it. HBC won’t make it different.

**Comment by adidalal** [comment]
@JamesMcMahon https://www.corecode.io/uninstallpkg/ is your best best for "complete" pkg uninstalls

**Comment by JamesMcMahon** [comment]
How does HBC keep track of how to uninstall pkgs?

**Comment by vitorgalvao** [comment]
@JamesMcMahon It’s in the casks themselves.

**Comment by adidalal** [comment]
Check the package id in the uninstall stanza

**Comment by JamesMcMahon** [comment]
So if I understand correctly, if I leave these packages lying around it would be like if I had just installed them without Homebrew Cask?

**Comment by vitorgalvao** [comment]
> So if I understand correctly, if I leave these packages lying around it would be like if I had just installed them without Homebrew Cask?

Pretty much, yes, we specifically strive for it to be so.

**Comment by JamesMcMahon** [comment]
Ok I think I will just [try and figure out how to remove the remaining Java pkgs](http://superuser.com/questions/36567/how-do-i-uninstall-any-apple-pkg-package-file) then (if I decide I want to kill them). It's crazy to me that there isn't a built in tool to uninstall pkgs, it seems like if there was you guys could simplify your recipes quite a bit.

Post sudo restrictions, Homebrew Cask as it stand right now won't work for non-admin users. Apps could potentially be installed locally with `brew cask install --appdir=~/Applications` but pkgs wouldn't be installable for non-admins. This may be something that you want to bring to the attention of your users. While I appreciate all the hard work everyone in the project is putting in, removing sudo support (while smart overall) makes Cask unusable for my system, so I'll be uninstalling it and looking for other solutions.

We also never got to the cause of the AppleEvent timed out errors. I'll hold off on uninstall for a day or two just in case anyone needs anything from my setup for debugging purposes. If you are not concerned with that issue feel free to close this issue.

I appreciate all the help from everyone.
