### ISSUE TITLE
cask uninstall failing due to AppleEvent time out

### ISSUE THREAD

**Issue by JamesMcMahon** [caskroom/homebrew-cask#27113]
I'm hitting an issue uninstalling some cask installs, I've tried two different uninstalls and they both fail with:

>==> Standard Error of failed command:
36:109: execution error: System Events got an error: AppleEvent timed out. (-1712)

Full output for Java:

```
⋊> ~ brew cask uninstall java                                                                                                   11:09:48
Warning: Calling MacOS.release is deprecated!
Use MacOS.version instead.
/Users/jamie/.brew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:73:in `block in load'

==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
==> Removing launchctl service com.oracle.java.Java-Updater
==> Quitting application ID com.oracle.java.Java-Updater
==> 36:109:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/osascript -e tell application \"System Events\" to count processes whose bundle identifier is \"com.oracle.java.Java-Updater\"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:109: execution error: System Events got an error: AppleEvent timed out. (-1712)

==> Exit status of failed command:
#<Process::Status: pid 45720 exit 1>
```

Full output for Amethyst:

```
⋊> ~ brew cask uninstall amethyst                                                                                               10:34:30
Warning: Accessibility access cannot be disabled automatically on this version of macOS.
See System Preferences to disable it manually.
==> Running uninstall process for amethyst; your password may be necessary
==> Removing login item Amethyst
==> 36:84:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e tell application \"System Events\" to delete every login item whose name is \"Amethyst\"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:84: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 45459 exit 1>
```

Any suggestions?

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.

> (…)

> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.

**Comment by vitorgalvao** [comment]
I’ll also say that the single fact you got this error:

> Warning: Calling MacOS.release is deprecated!
Use MacOS.version instead.

Means there’s somethign seriously outdated or wrong in your setup.

**Comment by JamesMcMahon** [comment]
Ah yeah, sorry I missed that part with all the commands to run. (I actually look at the template but missed the guide link) I run them all and I still seem the same error, sans the `Warning: Calling MacOS.release is deprecated!` line.

**Comment by JamesMcMahon** [comment]
Reopened as https://github.com/caskroom/homebrew-cask/issues/27116
