### ISSUE TITLE
HyperDither outdated/file not there

### ISSUE THREAD

**Issue by pedromaltez** [caskroom/homebrew-cask#27147]
The [HyperDither cask](https://github.com/caskroom/homebrew-cask/blob/beaa41bf34a2f50fc8e331ba8d17aa91213f2c68/Casks/hyperdither.rb) is outdated.

I don't know where the file can be downloaded anymore. It looks like it's only distributed on the Mac App Store. The cask downloads the webpage that the url redirects to, instead of the app file that is presumably meant to be there.

I'm unsure what the fix for this should be, and I didn't want to submit a PR deleting the cask without asking about it first.

**Comment by vitorgalvao** [comment]
Looks like you’re correct. Making a PR to delete it now.
