### ISSUE TITLE
Share your work with Mattermost community?

### ISSUE THREAD

**Issue by jasonblais** [caskroom/homebrew-cask#27171]
Thanks for including Mattermost Desktop App in the Homebrew Cask manager :)  https://github.com/caskroom/homebrew-cask/blob/master/Casks/mattermost.rb

![image](https://cloud.githubusercontent.com/assets/13119842/20644185/87b217c2-b3fa-11e6-831f-6e929880a237.png)

We'd love to help share it with the Mattermost community. Are there any specific guidelines we should follow to appropriately promote your project?

**Comment by vitorgalvao** [comment]
If you ever mention the cask file (the file in your screenshot), be sure to call it a cask, not a formula (different things). It’s also “Homebrew-Cask”, not “Homebrew Cask”. “homebrew-cask” is also fine.

Those are just for correctness, though, we don’t really have any mandatory requirements or guidelines. However you want to do it is fine.

**Comment by jasonblais** [comment]
Got it, will do. Thanks @vitorgalvao!
