### ISSUE TITLE
Adding Language Packs for LibreOffice

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#27181]
I have had a request via email to add the language packs for [LibreOffice](https://github.com/caskroom/homebrew-cask/blob/master/Casks/libreoffice.rb). According to the instructions [here](http://www.libreoffice.org/get-help/install-howto/os-x/):

> If needed, you may now download and install the language pack(s) of your choice and built-in help by downloading the .DMG file of your choice. The installation steps are the same than the ones described above but you must have downloaded the main LibreOffice .DMG file beforehand.

Once Libreoffice and the language pack are installed, you can then [select the document language](https://help.libreoffice.org/Common/Selecting_the_Document_Language). I am not sure if this can be accomplished automatically via a `preflight` or `postflight` stanza?

I have created the following template for a new Cask called `libreoffice-langpack`:
```
cask 'libreoffice-langpack' do
  version '5.2.3'

  language 'en-GB', default: true do
    sha256 '82df20bdfc602a92019d8a404a2ab8980f751304bd19331d2e71f7b2c5284ff6'
    'en-GB'
  end

  # documentfoundation.org was verified as official when first introduced to the cask
  url "https://download.documentfoundation.org/libreoffice/stable/#{version}/mac/x86_64/LibreOffice_#{version}_MacOS_x86-64_langpack_#{language}.dmg"
  name 'LibreOffice'
  homepage 'https://www.libreoffice.org/'
  gpg "#{url}.asc",
      key_id: 'c2839ecad9408fbe9531c3e9f434a1efafeeaea3'

  depends_on cask: 'libreoffice'

  app 'LibreOffice Language Pack.app'
end
```

I plan to make the language `en-GB` the default, but which other languages should I add? There are a total of [110 languages](http://www.libreoffice.org/download/libreoffice-fresh/?lang=pick), and I certainly do not want to do them all!

They are all available on the [mirror list](https://download.documentfoundation.org/libreoffice/stable/5.2.3/mac/x86_64/), and clicking on the `Details` link shows the [SHA-256 hash for each file](https://download.documentfoundation.org/libreoffice/stable/5.2.3/mac/x86_64/LibreOffice_5.2.3_MacOS_x86-64_langpack_en-GB.dmg.mirrorlist), so at least one would not have to download them all to find the `sha256`.

Any advice on which languages to add, and the actual Cask file to be created, would be appreciated.

**Comment by bunam** [comment]
i have made a script that build recipes for libreoffice all language packs

i could be
http://pastebin.com/W5LsvG2e

**Comment by vitorgalvao** [comment]
@miccal Token should be `libreoffice-language-pack`, not `libreoffice-langpack`.

Ideally, all the languages would be added. Seeing as it is a language pack, completeness seems even more important than in other casks.

If you can’t do all of them, use your best judgement. `en-US`, if it exists, should be the default, though, for consistency.

**Comment by bunam** [comment]
@vitorgalvao have you read my script ?
it search trough the libreoffice website and create a recipe for each language it found :
libreoffice-fr
libreoffice-uk
...
it could generate 110 actually  
you can install individually one or more language

**Comment by vitorgalvao** [comment]
@bunam Doesn’t that create one cask for each language? Because the goal here is to have them all in the same cask.

**Comment by bunam** [comment]
i can build a cask recipe for all language with a script, but i think it's better to have one by language
user will install libreoffice-fr that depend libreoffice and what's ok

**Comment by vitorgalvao** [comment]
> but i think it's better to have one by language
user will install libreoffice-fr that depend libreoffice and what's ok

The `language` feature was introduced exactly so that wouldn’t happen again. You’re suggesting 110 near identical casks cluttering the repo. No way it would make sense for us to go back to that.

**Comment by bunam** [comment]
so if i ask for the future cask : libreoffice-language-pack 
brew will do a DDOS on the libreoffice mirrors whit 110 http requests ?
there is not an full language pack...

**Comment by vitorgalvao** [comment]
No, that would be ridiculous. It will just get either the language of your system, or the one you specifically ask for.

[Read the documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/language.md).

**Comment by bunam** [comment]
ha i'm new to cask formula !
I see now what you are saying, i could update how the script work to do like the doc said and produce a unique recipe...

there will be 110 sections almost like that
```

  language 'en-GB', default: true do
    sha256 '82df20bdfc602a92019d8a404a2ab8980f751304bd19331d2e71f7b2c5284ff6'
    'en-GB'
  end

```

**Comment by miccal** [comment]
@vitorgalvao there is no `en-US` language pack, as that is the default for LibreOffice itself. That is why I suggested making `en-GB` the default.

**Comment by bunam** [comment]
what do you think of : http://pastebin.com/Qgv7BvMt 

installed in 
`.../homebrew/Library/Taps/caskroom/homebrew-cask/Casks/libreoffice-languages.rb`

tested with 
`brew cask install libreoffice-languages --language=fr`

you have to note there is a exclusion for **ca-valencia** because of :

`Error: 'ca-valencia' cannot be parsed to a Locale while loading 'libreoffice-languages' from '/opt/homebrew/Library/Taps/caskroom/homebrew-cask/Casks/libreoffice-languages.rb'`

if you think it's ok i will give the script

**Comment by vitorgalvao** [comment]
That cask has multiple problems, but those cannot be discussed in pastebin. Please submit a PR so we can properly discuss it.

**Comment by bunam** [comment]
Is there any place I (on anyone) can PR my script ?
before it had to be adapted to :
https://github.com/caskroom/homebrew-cask/blob/master/Casks/libreoffice-language-pack.rb

**Comment by miccal** [comment]
@bunam I am not sure what you are asking for exactly?

**Comment by bunam** [comment]
I think the script should be played at any time there is an update so it should be anywhere in the https://github.com/caskroom/ repo so it can be maintained ?

**Comment by miccal** [comment]
I see - I think that we would only add _general_ scripts that can be applied to any relevant Casks, as opposed to a script specifically for one Cask, but thank you for the offer.
