### ISSUE TITLE
Cask request: Google Chrome for multiple release channels

### ISSUE THREAD

**Issue by moonfruit** [caskroom/homebrew-cask#27195]
### Cask details

(Please fill out as much as possible)

**Name**:
Google Chrome for multiple release channels

**Homepage**:
https://www.chromium.org/getting-involved/dev-channel

**Download URL**:
https://dl.google.com/chrome/mac/beta/GoogleChrome.dmg
https://dl.google.com/chrome/mac/dev/GoogleChrome.dmg
https://dl.google.com/release2/q/canary/googlechrome.dmg

**Description**:
Request for a option to specify channel for Chrome, I means beta or dev channels.
And request for another Cask for Google Chrome Canary.

**Comment by vitorgalvao** [comment]
[caskroom/versions](https://github.com/caskroom/homebrew-versions)
