### ISSUE TITLE
Cask request: Oscilloscope

### ISSUE THREAD

**Issue by sgsunder** [caskroom/homebrew-cask#27273]
### Cask details

**Name**: Oscilloscope

**Homepage**: https://github.com/kritzikratzi/Oscilloscope

**Download URL**: https://github.com/kritzikratzi/Oscilloscope/releases

**Description**: A software oscilloscope attempting to mimic the aesthetic of old school ray oscilloscopes

**Comment by vitorgalvao** [comment]
#27279.
