### ISSUE TITLE
Feature request: aax_plugin (similar to audio_unit_plugin, vst_plugin and vst3_plugin)

### ISSUE THREAD

**Issue by fgimian** [caskroom/homebrew-cask#27282]
### Description of feature/enhancement

It would be awesome if we also had a stanza for the Pro Tools AAX plugin format. Such files have the extension `*.aaxplugin` and are to be copied to `/Library/Application Support/Avid/Audio/Plug-Ins`

### Justification

This will allow installation of ProTools AAX plugins and complete support for all major audio plugin formats on Mac.

### Example use case

[Voxengo SPAN](https://github.com/caskroom/homebrew-cask/blob/60531a2812005dd5f17dc92f3ce7419af3c5d019/Casks/voxengo-span-au.rb) is actually missing the AAX version of the plugin which you'll see is available on the [product site](http://www.voxengo.com/product/span/) in the bundle with the AU version 😄

**Comment by adidalal** [comment]
If you need a model PR to try implementing it yourself, check out https://github.com/caskroom/homebrew-cask/pull/20787. Core code is now in homebrew/brew, but everything else is the same

**Comment by vitorgalvao** [comment]
We’ll take a PR for this, but likely not do it ourselves (too few users to justify it).

Following @adidalal’s link, this should be pretty straightforward.

**Comment by fgimian** [comment]
Thanks guys! 😄
