### ISSUE TITLE
mount_osxfuse: the OSXFUSE file system is not available (255) fuse: failed to mount file system: Undefined error: 0

### ISSUE THREAD

**Issue by harobed** [caskroom/homebrew-cask#27293]
Hi,

I have this message when I use `sshfs`:

```
mount_osxfuse: the OSXFUSE file system is not available (255)
fuse: failed to mount file system: Undefined error: 0
```

My system:

* OSX 10.12.1

```
$ sshfs  --version
SSHFS version 2.8
OSXFUSE 3.5.3
FUSE library version: 2.9.7
fuse: no mount point
```

I have installed sshfs and OSFuse like this:

```
$ brew cask install osxfuse
$ brew install sshfs
```

Original post on OSXFUSE Google groups: https://groups.google.com/forum/#!topic/osxfuse-group/mfMuhwKPZOA

I have fixed my issue with official OSXFUSE versions available from http://osxfuse.github.io

Why `osxfuse` from `brew cask` don't work on my host?

Best regards,
Stéphane

**Comment by adidalal** [comment]
I think the osxfuse Cask needs a reboot after install, but not 100% sure. I see the issue https://github.com/osxfuse/osxfuse/issues/315#issuecomment-250893876 potentially?

We use the same installer as the official osxfuse version.

See also macfusion2 - https://github.com/ElDeveloper/macfusion2 (`eldeveloper-macfusion`)

**Comment by harobed** [comment]
> I think the osxfuse Cask needs a reboot after install, but not 100% sure. I see the issue osxfuse/osxfuse#315 (comment) potentially?

I have rebooted.

**Comment by delian** [comment]
There is a kind of limitation in OSX to the amount of kernel modules that can be loaded with the same function. For example, if OSX Fuse, VMWare Fusion, VirtualBox, OpenVPN TAP (or other VPN clients like ZeroTier) do not load, and give you a similar error, it is all related to the same problem. However, I personally do not know how to resolve it. I do reboot and when I change the order of starting the apps I usually choose which to work and which not to work this time.
I have to look for a permanent solution (I guess some kernel parameter increasing some property) but I don't have it yet
