### ISSUE TITLE
Deadbeef sha256 checksum error

### ISSUE THREAD

**Issue by levimot** [caskroom/homebrew-cask#27359]
Hi all,

Not sure if this is a bug or something wrong on my end. I'm trying to understand why attempting to install deadbeef with homebrew cask gives me this checksum error:

```
Mac-Pro:~ [username]$ brew cask install deadbeef

==> Downloading https://downloads.sourceforge.net/deadbeef/deadbeef-devel-osx-x86_64.zip

Already downloaded: [my comp]/Library/Caches/Homebrew/Cask/deadbeef--0.7.2.zip

==> Verifying checksum for Cask deadbeef

==> Note: running "brew update" may fix sha256 checksum errors

Error: sha256 mismatch

Expected: 8da871c4f8ab19515bb85119a85b32ed3917a8c01074afb8861a00debd3bb38e

Actual: 7dc688cca32bf1ef2efbfb4f93c7464b1f935ad71e3d2e35fb06513a615bd7e8

File: [my comp]/Library/Caches/Homebrew/Cask/deadbeef--0.7.2.zip

To retry an incomplete download, remove the file above.

Mac-Pro:~ [username]$ 
```

I'm running Mac OS X Yosemite and an older version of Xcode (the newest supported by Yosemite). I have run 'brew update' and I am indeed up to date.

Thanks for any help.

**Comment by adidalal** [comment]
The cask is probably outdated. You can fix it easily, though!

See https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/sha256_mismatch_error_fix_outdated.md

Next time, please follow the reporting bugs guide next time, it would have pointed you to the fix ^^

**Comment by levimot** [comment]
Hi, apologies

**Comment by adidalal** [comment]
Looks like download URL changed to -http://downloads.sourceforge.net/project/deadbeef/travis/osx/master/deadbeef-devel-osx-x86_64.zip

**Comment by adidalal** [comment]
Use`cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

Comment here if you have further issues

**Comment by levimot** [comment]
hello,

I followed the instructions for cask-repair, pasting the URL you provided in place of the old one. I received an audit from deadbeef:

```
audit for deadbeef: warning
 - SourceForge URL format incorrect. See https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#sourceforgeosdn-urls
```

It has the correct checksum but will not allow me to use that URL in cask-repair...

I also tried 'brew cask install [URL YOU PROVIDED] and I got an error.

**Comment by levimot** [comment]
I figured out how to overcome that error in cask-repair, however upon second look it seems that the URL you provided is providing the wrong checksum.. 

```
@@ -1,10 +1,10 @@
 cask 'deadbeef' do
   version '0.7.2'
-  sha256 '8da871c4f8ab19515bb85119a85b32ed3917a8c01074afb8861a00debd3bb38e'
+  sha256 '7dc688cca32bf1ef2efbfb4f93c7464b1f935ad71e3d2e35fb06513a615bd7e8'
 
   url 'https://downloads.sourceforge.net/deadbeef/deadbeef-devel-osx-x86_64.zip'
   appcast 'https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master',
-          checkpoint: '34fb1506fb9797148a3191583ddd33c7279336876c6823a4c23e40431811e190'
+          checkpoint: 'ed8178e68dd11ce0d03d31f8864e4eaa95cf45112764691f0b82793fcbd4dcb2'
   name 'DeaDBeeF'
   homepage 'http://deadbeef.sourceforge.net/'
 
--------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? You can also make further manual edits (y/n/e)
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/27361

**Comment by levimot** [comment]
forgive me, but following your link, vitorgalvao, I see:

```
After making all changes to the cask:
 brew cask audit --download {{cask_file}} is error-free.
```

but the audit fails when I perform it.

What am I doing wrong?
