### ISSUE TITLE
brew cask list fails with Error: No available formula with the name "brew-cask"

### ISSUE THREAD

**Issue by moreaki** [caskroom/homebrew-cask#27380]
**Preamble**: I have read and tried to follow the following guides:

https://github.com/caskroom/homebrew-cask#reporting-bugs
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/brew_cask_list_shows_wrong_information.md
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/uninstall_wrongly_reports_cask_as_not_installed.md
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/error_unknown_command_cask.md

**Problem description**: `brew cask list` fails with Error: No available formula with the name "brew-cask"

Even though it's claimed to be broken, I believe in the interest of confusing people less, this ought to be fixed:

```
$ brew cask list
Error: No available formula with the name "brew-cask"
android-file-transfer
```
**Expectation**: I can call `brew cask list` and do not get an error message.

Here is a log of what I have done before I opened this issue report:

```
@0x4B6169:/Users/moreaki$ brew cask list
Error: No available formula with the name "brew-cask"
android-file-transfer
@0x4B6169:/Users/moreaki$ brew info
76 kegs, 24,081 files, 636.9M
@0x4B6169:/Users/moreaki$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated.
Please install XQuartz 2.7.9 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz
@0x4B6169:/Users/moreaki$ cd $(brew --repo); git fetch; git reset --hard origin/master; brew update
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 4), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/Homebrew/brew
 * [new branch]          revert-1567-fix-diagnostic-conditonal -> origin/revert-1567-fix-diagnostic-conditonal
HEAD is now at 88d0e8c2e Merge pull request #1612 from MikeMcQuaid/travis-xcode-8.1
Updated 1 tap (caskroom/cask).
No changes to formulae.
@0x4B6169:/usr/local/Homebrew$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated.
Please install XQuartz 2.7.9 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz
@0x4B6169:/usr/local/Homebrew$ brew cask list
Error: No available formula with the name "brew-cask"
android-file-transfer
@0x4B6169:/usr/local/Homebrew$ brew cask uninstall xquartz --force
Error: No available formula with the name "brew-cask"
==> Running uninstall process for xquartz; your password may be necessary
==> Removing launchctl service org.macosforge.xquartz.startx
Password:
==> Quitting application ID org.macosforge.xquartz.X11
==> Removing files from pkgutil Bill-of-Materials
==> Removing files: ["/opt/X11/"]
@0x4B6169:/usr/local/Homebrew$ brew cask list
Error: No available formula with the name "brew-cask"
android-file-transfer
@0x4B6169:/usr/local/Homebrew$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated.
Please install XQuartz 2.7.9 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz
@0x4B6169:/usr/local/Homebrew$ cd $(brew --repo); git fetch; git reset --hard origin/master
HEAD is now at 88d0e8c2e Merge pull request #1612 from MikeMcQuaid/travis-xcode-8.1
@0x4B6169:/usr/local/Homebrew$ brew untap phinze/cask; brew untap caskroom/cask; brew uninstall --force brew-cask
Error: No available tap phinze/cask.
Untapping caskroom/cask... (3,919 files, 83.2M)
Untapped 0 formulae
Error: No available formula with the name "brew-cask"
@0x4B6169:/usr/local/Homebrew$ brew cleanup; brew cask cleanup; brew update
Removing: /usr/local/Cellar/cmake/3.7.0... (2,140 files, 29M)
Removing: /usr/local/Cellar/coreutils/8.25... (425 files, 8.3M)
Removing: /usr/local/Cellar/git/2.10.2... (1,445 files, 31.8M)
Removing: /usr/local/Cellar/libunistring/0.9.6... (52 files, 4.2M)
Removing: /usr/local/Cellar/readline/7.0... (45 files, 2M)
Removing: /usr/local/Cellar/sqlite/3.15.1... (11 files, 2.9M)
Removing: /usr/local/Cellar/subversion/1.9.4... (148 files, 11.1M)
==> This operation has freed approximately 89.6M of disk space.
Error: No available formula with the name "brew-cask"
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3580, done.
remote: Compressing objects: 100% (3566/3566), done.
remote: Total 3580 (delta 32), reused 190 (delta 10), pack-reused 0
Receiving objects: 100% (3580/3580), 1.16 MiB | 535.00 KiB/s, done.
Resolving deltas: 100% (32/32), done.
Tapped 0 formulae (3,589 files, 3.6M)
==> Removing cached downloads
/Users/moreaki/Library/Caches/Homebrew/Cask/android-file-transfer--latest.dmg
/Users/moreaki/Library/Caches/Homebrew/Cask/xquartz--2.7.11.dmg
==> This operation has freed approximately 78.9M of disk space.
Already up-to-date.
@0x4B6169:/usr/local/Homebrew$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated.
Please install XQuartz 2.7.9 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz
@0x4B6169:/usr/local/Homebrew$ brew cask list
Error: No available formula with the name "brew-cask"
android-file-transfer
```

**Comment by st-f** [comment]
After typing:  brew install fastlane

Error: No available formula with the name "fastlane" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/fastlane
To install it, run:
  brew install Caskroom/cask/fastlane
stf-macbook:~ stf$ brew install Caskroom/cask/fastlane
==> brew cask install Caskroom/cask/fastlane


Then:

brew install Caskroom/cask/fastlane

Doesn't install, output:

==> brew cask install Caskroom/cask/fastlane
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom

For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
Error: Tap caskroom/cask already tapped.

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:196:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/untapped_qualified.rb:9:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:28:in `block in for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by vitorgalvao** [comment]
@moreaki You’re outputting a wall of text with multiple commands in. That’s close to unreadable. And *still* does have the information we ask for (such as `brew cask doctor`).

Please, follow [this](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) and *then* [this template](https://github.com/caskroom/homebrew-cask/issues/new?title=Bug%20report%3A%20%5Bsummarise%20the%20issue%20here%5D&body=Remember%20to%20follow%20the%20%5Bpre%20bug%20report%5D%28https%3A%2F%2Fgithub.com%2Fcaskroom%2Fhomebrew-cask%2Fblob%2Fmaster%2Fdoc%2Freporting_bugs%2Fpre_bug_report.md%29%20guide%20beforehand.%20Failure%20to%20do%20so%20might%20get%20your%20issue%20closed.%0A%0A%23%23%23%23%20Description%20of%20issue%0A%0A%5Binsert%20a%20detailed%20description%20of%20your%20issue%20here%5D%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20cask%20%3Ccommand%3E%20--verbose%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20doctor%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20cask%20doctor%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A).

**Comment by moreaki** [comment]
@vitorgalvao : Done
