### ISSUE TITLE
Bug report: wireshark install fails on macOS Sierra

### ISSUE THREAD

**Issue by cmdcolin** [caskroom/homebrew-cask#27437]
#### Description of issue

I tried `brew cask install wireshark` on macOS Sierra and it failed. The actual GUI installer for wireshark failed by default too.

It might be related to this link, and following it's advice, I made the directory /etc/manpaths.d/ on my computer, and it made the install work https://ask.wireshark.org/questions/57446/wireshark-installation-issue-in-sierra

I can post brew doctor/verbose logs other things if interested, but the fix seems available in that link. Not sure if that could be added to cask or if it would be recommended to fix upstream.

**Comment by miccal** [comment]
See the related issues [here](https://github.com/caskroom/homebrew-cask/issues/27070) and [here](https://github.com/caskroom/homebrew-cask/issues/27200). It seems this issue will be fixed in the next release of Wireshark.

**Comment by cmdcolin** [comment]
Ah good to know. Thanks for the follow up. Guess we can close this and hope for a swift release :)
