### ISSUE TITLE
How to properly install casks as a non-admin user?

### ISSUE THREAD

**Issue by mingsai** [caskroom/homebrew-cask#27431]
**Given the following:**
Never operate OS as an admin user when doing daily tasks
Never operate brew (and by extension brew cask) as an admin user (due to security risks)

> NB - My assumptions here are that these are appropriate best practices. I've noted that homebrew recently modified folder storage locations to adjust for Apple locking access to it's system folders. This leads to the presumption that the tools should work within the context of a secured infrastructure.

**Then**
Installations will always fail when attempting to install as non-admin user on MacOS 10.12

For example:
Running `brew cask install charles`

Results in:
==> Downloading https://www.charlesproxy.com/assets/release/4.0.2/charles-proxy-
######################################################################## 100.0%
==> Verifying checksum for Cask charles
==> Moving App 'Charles.app' to '/Applications/Charles.app'
Error: Permission denied - (/usr/local/Caskroom/charles/4.0.2/Charles.app, /Applications/Charles.app)

What then am I missing about using this tool?

> NB - I can still access the downloaded file at `~/Library/Caches/Homebrew/Cask/charles--4.0.2.dmg` from **Finder**, double-click the installer (.dmg), **(at which point I am prompted for my admin login credentials**), and perform the install after I login as an admin user.

**Comment by miccal** [comment]
See [here](https://github.com/caskroom/homebrew-cask/issues/26618) for a possible solution.

**Comment by mingsai** [comment]
@miccal I've taken a peek but I still believe there is a significant issue here because using `--appdir` by default will attempt to perform the install to /Applications where I lack access as a non-admin user.  

I do understand that I might also redirect to a different directory. However, a preferred solution might be one that allows users to insert the appropriate admin credentials from the command line. I think that such a resolution might be a useful way for the utility to perform all of it's background work while dealing with a secured environment. 

I may have missed something in my evaluation so please feel free to provide an alternate resolution.

**Comment by miccal** [comment]
Sorry, I am not following - using your example above, if you run `brew cask install --appdir=~/Applications charles`, `Charles.app` will be installed in `~/Applications` (which you can write to) instead of `/Applications` (which you cannot write to without admin privaleges.

**Comment by vitorgalvao** [comment]
@miccal is correct. Use `--appdir=~/Applications` and it’s done.

For some casks (the ones that use `pkg` installers), this won’t work. But that’s something you need to take up with the developers of said apps, as we can’t do anything about it.

**Comment by mingsai** [comment]
Just wanted to close the circle on this issue. I did get the correct behavior for cask installations after adding the following to my bash profile. 

> export HOMEBREW_CASK_OPTS="--appdir=~/Applications"

I also had to add my non-admin user to the sudoer's file to successfully install a package:

> username ALL=(ALL) ALL
