### ISSUE TITLE
Bug report: basictex uninstall deletes wrong folder

### ISSUE THREAD

**Issue by halmi** [caskroom/homebrew-cask#27475]
When performing `brew cask uninstall basictex`, the folder `/usr/local/texlive/2016`gets deleted (this is where the regular mactex would be installed).

The correct folder would be `/usr/local/texlive/2016basic` as stated in http://tug.org/mactex/morepackages.html

I think the same applies for `~/Library/texlive/2016`vs `~/Library/texlive/2016basic`.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/27479
