### ISSUE TITLE
Audacity Download Link broken

### ISSUE THREAD

**Issue by shivno** [caskroom/homebrew-cask#27504]
==> Downloading https://download.fosshub.com/Protected/expiretime=1481210357;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/9cc13511ea3db4dad27114e3baa5c2c79368232e552188ef9a76c3bd4918c9f1/Audacity/audacity-macosx-ub-2.1.2.dmg

curl: (22) The requested URL returned error: 403
Error: Download failed on Cask 'audacity' with message: Download failed: https://download.fosshub.com/Protected/expiretime=1481210357;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/9cc13511ea3db4dad27114e3baa5c2c79368232e552188ef9a76c3bd4918c9f1/Audacity/audacity-macosx-ub-2.1.2.dmg
The incomplete download is cached at /Users/admin/Library/Caches/Homebrew/Cask/audacity--2.1.2.dmg.incomplete

Maybe fosshub changed something and it could affect other casks. I dont know why they have this protected URL scheme anyway, could we ask them to change it?

**Comment by shivno** [comment]
https://www.fosshub.com/faq.html "Please note: Hotlinking is Not Allowed"

**Comment by vitorgalvao** [comment]
> Maybe fosshub changed something and it could affect other casks.

This is the only cask that uses it.

> I dont know why they have this protected URL scheme anyway

They explain it in FAQ you linked to.

> could we ask them to change it?

You can, but I bet you’d be wasting your time. It would be easier to get Audacity to their distribution model it, but I doubt they’re going to do it (you’re free to ask, though).

Following up in https://github.com/caskroom/homebrew-cask/pull/27517.
