### ISSUE TITLE
Optional PKG components, such as OSXFuse Compatibility Layer

### ISSUE THREAD

**Issue by AlJohri** [caskroom/homebrew-cask#2751]
https://github.com/phinze/homebrew-cask/blob/master/Casks/osxfuse.rb

Is there anyway an option for installing the compatibility layer can be added to the cask? 

CC: @rolandwalker @tlvince @oldskool73

**Comment by miccal** [comment]
Could this be considered complete now that we have the [`pkg choices:`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md#pkg-choices) option?

**Comment by vitorgalvao** [comment]
I’d say so.
