### ISSUE TITLE
0ad.rb: SSL certificate mismatch

### ISSUE THREAD

**Issue by gaurav** [caskroom/homebrew-cask#27524]
When I try to install [0ad](https://github.com/caskroom/homebrew-cask/blob/master/Casks/0ad.rb) using Homebrew, I get the following error:

> Aurelian-2:~ vaidyagi$ brew install Caskroom/cask/0ad
> ==> brew cask install Caskroom/cask/0ad
> ==> Downloading https://releases.wildfiregames.com/0ad-0.0.21-alpha-osx64.dmg
> 
> curl: (60) SSL certificate problem: Invalid certificate chain
> More details here: http://curl.haxx.se/docs/sslcerts.html

It looks like the SSL certificate is for "wildfiregames.com" and so doesn't cover "releases.wildfiregames.com". However, it's not clear to me why this Cask uses 'https' in the first place. Replacing the URL with an 'http' URL (which is what http://releases.wildfiregames.com/ uses) will probably suffice; otherwise, I can report this bug to wildfiregames.com and see if they can fix it at their end.

**Comment by vitorgalvao** [comment]
Yes, please contact them to fix on their end.
