### ISSUE TITLE
Cask update request: update Calibre to 2.74.0

### ISSUE THREAD

**Issue by tkothe** [caskroom/homebrew-cask#27542]
### Cask details

Calibre has been updated to 2.74.0 today. 
https://calibre-ebook.com/whats-new

**Name**: Calibre

**Homepage**: https://calibre-ebook.com/

**Download URL**: https://download.calibre-ebook.com/2.74.0/calibre-2.74.0.dmg

**Comment by tkothe** [comment]
I just found these excellent instructions and will try to take care of it myself: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

**Comment by vitorgalvao** [comment]
Done in #27543.
