### ISSUE TITLE
GIMP translation for italian QUIT functionality is wrong in the binary distribution

### ISSUE THREAD

**Issue by robbetto** [caskroom/homebrew-cask#27568]
Hi all,

In the mac app the translation for "Quit GIMP", see the attached image, is wrong and should be "Esci da GIMP" instead. 
I've checked the .po translation and is correct, so maybe is the formula that point to a (i guess) old branch? 
(cfr. [gimp.gimp-2-8.it.po:10415](https://l10n.gnome.org/POT/gimp.gimp-2-8/gimp.gimp-2-8.it.po))

![schermata 2016-12-10 alle 11 05 17](https://cloud.githubusercontent.com/assets/12015775/21073596/2bbe356a-bee3-11e6-9616-9274e62d3756.png)

**Comment by miccal** [comment]
The Cask file for [Gimp](https://github.com/caskroom/homebrew-cask/blob/master/Casks/gimp.rb) does not have a `language` stanza, so you will have to report this too the maintainers of Gimp.
