### ISSUE TITLE
Bug report: `brew install hex-fiend` prompts for sudo password

### ISSUE THREAD

**Issue by rkhmelichek** [caskroom/homebrew-cask#27637]
#### Description of issue

This is not necessarily a bug, but I have a question about the behavior of this cask.

`brew install hex-fiend` prompts for my sudo password. There is no real reason to do that since the /Applications/Hex Fiend.app/ folder is already owned by me.

I see the reason is because there is a call to `set_permissions` in the Cask:
```ruby
  postflight do
    set_permissions "#{appdir}/Hex Fiend.app/Contents/Frameworks/Sparkle.framework", 'a+rx'
  end
```

Is there a way to do this without using sudo? I was trying to automate the install of a bunch of apps, and it's the only one that has this issue.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
Romans-Mac:homebrew-cask roman$ brew cask  install --verbose hex-fiend
==> Downloading https://github.com/ridiculousfish/HexFiend/releases/download/v2.4.0/Hex_Fiend_2.4.dmg
Already downloaded: /Users/roman/Library/Caches/Homebrew/Cask/hex-fiend--2.4.0.dmg
==> Verifying checksum for Cask hex-fiend

==> Moving App 'Hex Fiend.app' to '/Applications/Hex Fiend.app'
Password:
```
</details>

**Comment by vitorgalvao** [comment]
[Looks like we may not need that anymore](https://github.com/ridiculousfish/HexFiend/issues/52#issuecomment-260499083). Will remove it from the cask and lets see if the problem resurfaces.

**Comment by rkhmelichek** [comment]
Thanks - can confirm works without the set_permissions.
