### ISSUE TITLE
Feature request: Allow casks to be searchable by their names specified by `name`

### ISSUE THREAD

**Issue by Numbermaniac** [caskroom/homebrew-cask#27658]
### Description of feature/enhancement
Sometimes, a cask has multiple names, all of which are used in the `name` stanza in its cask file. However, only the file name is searchable. Additional names in the `name` stanza should also be searchable.
### Justification
This would certainly be helpful for programs with multiple names, or even multiple version, since the cask file names tend to be all abbreviated versions of each one's full name.
### Example use case
Sometimes, a program's file name is its well-known acronym, but that means `cask search` for its full name returns no results, even if the full name is listed as an additional `name`. For example, the BOINC cask would not be found in `cask search` if you searched for "Berkeley" or any other of the full words of the name. Similarly, for the many different versions of PyCharm, `cask search pycharm` returns abbreviated suffixes for all 4 versions. I know I could `cask info` each, but it would probably be helpful if i could just search for part of the full name and get the right one immediately.

**Comment by miccal** [comment]
I believe this request would fall under the [not a discoverability service](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md)-heading?

**Comment by reitermarkus** [comment]
> I believe this request would fall under the not a discoverability service-heading?

Not really, since a user has to at least know the name of the application to be able to find it.

**Comment by vitorgalvao** [comment]
This was always the point of `name`, just not implemented yet.

See https://github.com/caskroom/homebrew-cask/issues/17323.
