### ISSUE TITLE
YakYak

### ISSUE THREAD

**Issue by l00mi** [caskroom/homebrew-cask#27681]
### Cask details

**Name**: YakYak

**Homepage**: https://github.com/yakyak/yakyak/

**Download URL**: https://github.com/yakyak/yakyak/releases/download/v1.4.1/yakyak-1.4.1-osx.zip

**Description**: Desktop client for Google Hangouts

For reference, cross link https://github.com/yakyak/yakyak/issues/176

**Comment by miccal** [comment]
[Already available.](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yakyak.rb)

**Comment by l00mi** [comment]
Hmm, not sure how I was able to miss that. Sorry for the noise.
