### ISSUE TITLE
Remove pastebot Cask?

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#27945]
The homepage for the [pastebot Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pastebot.rb) redirects to [here](http://tapbots.com/pastebot/) with a link to the non-beta version available only via the MAS.

Thoughts on removal?

**Comment by vitorgalvao** [comment]
Should be removed, yes. I don’t think Tapbots ever sold an app outside the App Stores.
