### ISSUE TITLE
Remove elasticwolf Cask?

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#27942]
The homepage for the [elasticwolf Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/elasticwolf.rb) redirects to [here](https://aws.amazon.com/tools/) which makes no mention of the ElasticWolf Client Console. There is a [link](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html) to something called AWS Elastic Beanstalk (I have no idea if this is related to elasticwolf) which suggests to [install](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install-osx.html) via `brew install awsebcli`.

Thoughts on removal?

**Comment by vitorgalvao** [comment]
Fine by me with the removal as well.
