### ISSUE TITLE
Remove capture-one Cask?

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#27941]
The Cask for [capture-one](https://github.com/caskroom/homebrew-cask/blob/master/Casks/capture-one.rb) is for version 9.1.0. The [homepage](https://www.phaseone.com/en/Products/Software/Capture-One-Pro/Whats-new.aspx) redirects to version 10, but the download appears to be [walled](https://www.phaseone.com/en/Profile/Login.aspx?CT=DOWNLOAD&rurl=%2fen%2fDownloadModule%2fDownloadController.aspx%3flangid%3d2776733f-13f6-4887-ba49-d4a9168a79d0%26itemcode%3dc667101f-541d-4488-90ac-fb3cdb8bbfeb%26cpu%3d%2fen%2fDownloadModule%2fConfirmPages%2fCaptureOneConfirmationPage.aspx&burl=%2fen%2fDownload.aspx).

Even their [archive page](https://www.phaseone.com/en/Download/Software-Archive/COArchiveMac.aspx) requires an email address.

Thoughts on removal?

**Comment by vitorgalvao** [comment]
Small note on walled downloads, a download is only considered walled if **both** of these are true:

+ The download URL is behind a login/registration form.
+ The origin of `url` and `homepage` differ.

In this case, the first point is true, but the second one is not. The walled downloads rule is to protect users from malicious links in `url` (by allowing them to easily verify them). When `url` comes from the same place as the `homepage`, though, then you know you can trust the source to be legitimate (unless the website itself as been compromised, but that’s not something we can account for).

**Comment by miccal** [comment]
Thanks for the clarification @vitorgalvao.

The download link is provided only after you register with a valid email address and activate an account, which is not something I am prepared to do, so I will leave it to someone else to update this Cask.
