### ISSUE TITLE
Cask request: FortiClient

### ISSUE THREAD

**Issue by jpawlowski** [caskroom/homebrew-cask#28023]
### Cask details

**Name**: FortiClient

**Homepage**: http://forticlient.com

**Download URL**: http://fortinetweb.s3.amazonaws.com/forticlient/downloads/FortiClientOnlineInstaller.dmg

**Description**: FortiClient extends the power of FortiGate's Unified threat management to endpoints on your network. Desktops, laptops, tablets & smartphones, FortiClient enables every device - local or remote, stationary or mobile - to integrate with your FortiGate. With no per-seat license fees, FortiClient takes the headaches out of managing multiple endpoints so your users & guests can work efficiently anywhere, without compromising your security. It's the end-point solution for your FortiGate network.

**Comment by miccal** [comment]
This app looks difficult to install via Cask - the download url fetched an online installer, that you run to download the actual app [which doesn't;t always work with Sierra](http://superuser.com/questions/1127715/is-it-possible-to-install-forticlient-5-4-1-on-mac-os-sierra). Downloading the full version requires [logging into their support page][(https://forum.fortinet.com/tm.aspx?m=115822) or [signing up to be sent a direct link](https://www.fortinet.com/demand/gated/forticlient-mac-download.html).

**Comment by jpawlowski** [comment]
I was able to install it with the online installer on Sierra. However, the kernel extension for endpoint security is not compatible at the moment but this is something that can be left out of the installation using the advanced tab in the setup wizard. At least the VPN is fully functional which might be the main use case for most of the people.
I am not familiar with handling pkg files via command line so not sure if unattended setup can be fulfilled here. However, would interactive setup be a real showstopper here? I saw other setups asking for some user interaction as well which I find to be just fine as in combination with brew bundle a cask for FortiClient would be still useful to have.

**Comment by vitorgalvao** [comment]
I’m with @miccal. Downloading an installer that downloads an app is just a crappy experience.

On top of that it’s an app whose installation will break unless you disable an option in the advanced tab of the setup wizard. Even writing that is complicated. That’s just asking for users to open bug reports with us when there’s nothing we can do.

On top of that, I’m unconvinced we can find the appropriate uninstall mechanism to properly and completely remove this cask. If you can at least do that, then we can consider it for installation. Otherwise

I’m for refusal.

**Comment by adidalal** [comment]
Might be more suitable for [autopkg](https://github.com/autopkg/autopkg) or slipstreaming into a custom dmg installler - looks enterprise anyway.

**Comment by miccal** [comment]
@jpawlowski thank you for your Cask request, but this will not be added at this stage.
