### ISSUE TITLE
Cask not automatically extracting tgz file in URL

### ISSUE THREAD

**Issue by msavy** [caskroom/homebrew-cask#28089]
Given the following formula (clipped for brevity):

```
cask 'minishift' do
  version '1.0.0-beta.1'
  sha256 '2d4020615bd86b814c678fedbf6072488101c26298a90fb081904c6913d88497'

  url "https://github.com/minishift/minishift/releases/download/v#{version}/minishift-#{version}-darwin-amd64.tgz"
  name 'Minishift'
  homepage 'https://github.com/minishift/minishift'

  depends_on arch: :x86_64
  container type: :naked

  binary 'minishift'

  postflight do
    set_permissions "#{staged_path}/minishift", '0755'
  end
end
```

Note that the TGZ file is not being automatically extracted as I would have expected. Debug log: https://gist.github.com/msavy/d44ba81d8700f471b95ea3632660a872

See particularly: https://gist.github.com/msavy/d44ba81d8700f471b95ea3632660a872#file-gistfile1-txt-L123

I'm not sure whether this is intentional behaviour for the `binary` type or whether it's a bug (the latter seems most likely?).

Any clarity appreciated :-).

/cc @tenfourty

**Comment by tenfourty** [comment]
Also ran into this issue while working on what will become a PR for `homebrew-versions` for the `minishift-unstable` cask, the source code is here https://github.com/tenfourty/homebrew-versions/blob/master/Casks/minishift-unstable.rb

**Comment by miccal** [comment]
I think the `binary` stanza should read:
```
binary "minishift-#{version}-darwin-amd64/minishift"
```

**Comment by miccal** [comment]
@tenfourty you need double quotes for the interpolation to work, like so:
```
binary "minishift-#{version}-darwin-amd64/minishift", target: 'minishift'
```

**Comment by msavy** [comment]
@miccal Doesn't seem to make any difference. As far as I can see and understand from the debug logs it still isn't actually extracting the archive (see the OP).

**Comment by msavy** [comment]
Unless extraction doesn't show on the debug logs? I'll try using pry perhaps.

**Comment by msavy** [comment]
@miccal I used pry to halt at the different phases which seems to show that the tgz is never actually extracted. Hand extracting it makes it work, which I hope offers some reasonably strong evidence that something is awry with auto-extraction.

Here's a more concrete example for you (purely as an exemplar).

```
cask 'minishift' do
  version '1.0.0-beta.1'
  sha256 '2d4020615bd86b814c678fedbf6072488101c26298a90fb081904c6913d88497'

  url "https://github.com/minishift/minishift/releases/download/v#{version}/minishift-#{version}-darwin-amd64.tgz"
  name 'Minishift'
  homepage 'https://github.com/minishift/minishift'

  container type: :naked

  preflight do
    # binding.pry
    `tar xvvzf #{staged_path}/minishift-1.0.0-beta.1-darwin-amd64.tgz --directory #{staged_path}`
    # binding.pry
  end

  binary "minishift"

  postflight do
    set_permissions "#{staged_path}/minishift", '0755'
  end
end
```
As per:
https://gist.github.com/msavy/6a3e2c7d492c5a1967ff10e5ba67b90b#file-gistfile1-txt-L146-L158

**Comment by miccal** [comment]
I do not have my testing machine available at the moment - if you are willing, can you attempt to install [iloc.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/iloc.rb) and see if that works? It seems like a similar style of Cask.

**Comment by msavy** [comment]
> I do not have my testing machine available at the moment - if you are willing, can you attempt to install iloc.rb and see if that works? It seems like a similar style of Cask.

Aha.

It does work, and in the case of iloc the file *does* seem to be detected and extracted automatically as one would expect (https://gist.github.com/msavy/09fb9a6c9184dbfc7743d833df03cd45#file-gistfile1-txt-L94).

That prompted me to look into `container type: :naked` which I'd not touched from the previous revision. It seems this causes the extraction to be skipped. Looking up the docs for this I now see why 😃 .

I had misunderstood the purpose of that function. I thought this was referring to the container technology in the project being installed.  It's referring to the compression and container type of the URL, which should seem obvious in retrospect. Whoopsie.

Anyway, mystery solved. Thanks!

**Comment by miccal** [comment]
Glad you got it solved.

**Comment by msavy** [comment]
@tenfourty Just remove the `container type: :naked` part and you should be able to use the above formula verbatim.

@miccal Cheers. Your response put me immediately onto the right track. Trivial issue in the end, but appreciate it. :

**Comment by tenfourty** [comment]
Great stuff, I've fixed the formula - what a simple mistake! and have created a PR for `minishift-unstable` in `homebrew-versions` https://github.com/caskroom/homebrew-versions/pull/3046
