### ISSUE TITLE
Add a flag to search to not install demo/trial app

### ISSUE THREAD

**Issue by sudomakesandwich** [caskroom/homebrew-cask#2812]
It would be awesome to add a flag to search, and maybe to other commands to, so that it doesn't show paid apps. By paid apps I mean apps that need to be purchased after several days or otherwise they don't work anymore (trail versions).  
As I'm aware of that not being automatically each cask should have a field containing  *free*  to be found.

**Comment by vitorgalvao** [comment]
I’m for closing this. There hasn’t been much support for this option in this issue or on the project as a whole (I don’t recall seeing a duplicate for this).

Circling back (once again) to the “we’re not a discoverability service” argument, you should have reasonable knowledge of the software before trying to install it. Will leave the final decision to @rolandwalker, but I see minimal value in this.

**Comment by rolandwalker** [comment]
As to the exact title of the issue (affecting `install`), no problem with closing.

What we *are* in the process of doing is making that info available in `search` or `list`.  The process is going well; nearly half of Casks have license info.  It's time to start displaying it soon.

**Comment by vitorgalvao** [comment]
> What we *are* in the process of doing is making that info available in `search` or `list`.

No issues there; I agree.

> As to the exact title of the issue (affecting `install`), no problem with closing.

Closing, then.
