### ISSUE TITLE
OpenArena cask is unusable

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#28170]
It seems like cask must copy `baseoa` directory from the source archive into the app `Contents/MacOS` but I'm not sure how to do this myself.

**Comment by miccal** [comment]
@yurikoles your issue does not make sense - please fill out the [bug report template](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/doc/issue_templates/bug_report.md) in full.

**Comment by yurikoles** [comment]
The archive from upstream contains baseoa folder, that has all the game content inside, and set of binaries. The corresponding cask just makes a copy of one of the binaries inside /Applications, avoiding the game content. 

```
/Applications/OpenArena.app/Contents/MacOS/openarena.ub 
ioq3+oa 1.35 macosx-i386 Oct 20 2008
----- FS_Startup -----
Current search path:
/Users/yurikoles/Library/Application Support/OpenArena/baseoa
/Applications/OpenArena.app/Contents/MacOS/baseoa
/Applications/baseoa

----------------------
0 files in pk3 files
Couldn't load default.cfg
```
The app is 11 MB vs 406MB source archive.

**Comment by miccal** [comment]
From the information [here](http://openarena.wikia.com/wiki/Manual/Install#Mac) I have updated the Cask in [#28173](https://github.com/caskroom/homebrew-cask/pull/28173).

**Comment by vitorgalvao** [comment]
@yurikoles `brew cask edit openarena` and make [this modification](https://github.com/caskroom/homebrew-cask/pull/28174/files).

Does that fix it?

**Comment by yurikoles** [comment]
@miccal, you just move use another binary leaving content untouched.
@vitorgalvao 
```
brew cask reinstall openarena
==> Downloading http://openarena.ws/request.php?4
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/Cask/openarena--0.8.8.php?4
==> Verifying checksum for Cask openarena
==> Moving App 'OpenArena.app' to '/Applications/OpenArena.app'
==> mv: /usr/local/Caskroom/openarena/0.8.8/baseoa: No such file or directory
==> Removing App: '/Applications/OpenArena.app'
Error: Command failed to execute!

==> Failed command:
/bin/mv /usr/local/Caskroom/openarena/0.8.8/baseoa /Applications/OpenArena.app/Contents/MacOS

==> Standard Output of failed command:


==> Standard Error of failed command:
mv: /usr/local/Caskroom/openarena/0.8.8/baseoa: No such file or directory


==> Exit status of failed command:
#<Process::Status: pid 26478 exit 1>
```

**Comment by yurikoles** [comment]
@vitorgalvao, I had added `openarena-0.8.8` to mv, it fixes issue

**Comment by vitorgalvao** [comment]
[Fixed](https://github.com/caskroom/homebrew-cask/pull/28174/files#diff-11d2b15178a26347d8ad102437a09b1a).

**Comment by miccal** [comment]
@yurikoles the website I linked states:

> 0.8.8 Mac binaries are those in "OpenArena 0.8.8 r28.app". Those in "OpenArena.app" are previous 0.8.1 binaries instead: they may be used (after chmod-ing them!), but do not include GLSL support and some other fixes.

**Comment by vitorgalvao** [comment]
@miccal I also saw that. Just finished downloading it from the website (took a good while), and can confirm:

![image](https://cloud.githubusercontent.com/assets/1699443/21433038/1d7c96ae-c866-11e6-9e63-f217b5c047d5.png)

Your change makes sense.
