### ISSUE TITLE
Bug report: Operation not permitted when trying to uninstall send-to-kindle

### ISSUE THREAD

**Issue by kevinwaddle** [caskroom/homebrew-cask#28191]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

I am trying to install cask send-to-kindle. But it says it is already installed (I had uninstalled it awhile back) and that I must reinstall it. Then I get this error message.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
0 0 $ brew cask reinstall send-to-kindle --verbose
==> Downloading https://s3.amazonaws.com/sendtokindle/SendToKindleForMac-installer.pkg
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.5-33-g8f85eb64 (Macintosh; Intel macOS 10.12.2) curl/7.51.0 https://s3.amazonaws.com/sendtokindle/SendToKindleForMac-installer.pkg -C 0 -o /Users/kevin/Library/Caches/Homebrew/Cask/send-to-kindle--latest.pkg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.4M  100 25.4M    0     0  6509k      0  0:00:04  0:00:04 --:--:-- 6510k
==> No checksum defined for Cask send-to-kindle, skipping verification
==> Running uninstall process for send-to-kindle; your password may be necessary
==> Removing launchctl service com.amazon.sendtokindle.launcher
==> Removing files from pkgutil Bill-of-Materials
==> chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /bin/chmod -- 777 #<Pathname:/usr/libexec/cups>

==> Standard Output of failed command:


==> Standard Error of failed command:
chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 46045 exit 1>
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
0 0 $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install doxygen

Run `brew missing` for more details.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.12.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.5-33-g8f85eb64
Homebrew/homebrew-core (git revision 4cfb; last commit 2016-12-22)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.5-33-g8f85eb64
caskroom/homebrew-cask (git revision 1326; last commit 2016-12-22)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/kevin/Library/Caches/Homebrew/Cask
1 files, 25.5M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3486
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/kevin/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kevin/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
```
</details>

**Comment by miccal** [comment]
I can reproduce this while running `brew cask uninstall pens-to-kindle`:
```
==> Running uninstall process for send-to-kindle; your password may be necessary
==> Removing launchctl service com.amazon.sendtokindle.launcher
==> Removing files from pkgutil Bill-of-Materials
==> chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /bin/chmod -- 777 #<Pathname:/usr/libexec/cups>

==> Standard Output of failed command:

==> Standard Error of failed command:
chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted

==> Exit status of failed command:
#<Process::Status: pid 7754 exit 1>
```

I get a similar error when running `brew cask reinstall send-to-kindle` and `brew cask zap send-to-kindle`.

However, reinstalling via `brew cask install --force send-to-kindle` does install successfully.

I am not sure what the problem is here.

**Comment by miccal** [comment]
@kevinwaddle can you run `brew cask install --force send-to-kindle` and confirm it works?

**Comment by kevinwaddle** [comment]
Yes this worked for me as well. Thank you.

```
0 0 $ brew cask install --force send-to-kindle
==> Downloading https://s3.amazonaws.com/sendtokindle/SendToKindleForMac-installer.pkg
######################################################################## 100.0%
==> No checksum defined for Cask send-to-kindle, skipping verification
==> Running installer for send-to-kindle; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is Send to Kindle for Mac
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  send-to-kindle was successfully installed!
```

**Comment by miccal** [comment]
@kevinwaddle thanks for letting me know.

We still need to investigate why it cannot be uninstalled, though.

**Comment by miccal** [comment]
[Link to the Cask in question.](https://github.com/caskroom/homebrew-cask/blob/master/Casks/send-to-kindle.rb)

**Comment by miccal** [comment]
After investigating the further, I believe I have found the problem. Notice that the system requirements on the homepage state:

> Mac OS X v10.6 (Snow Leopard) or Mac OS X v10.7 (Lion) or Mac OS X v10.8 (Mountain Lion)

I believe that Amazon (or whoever) have not updated then `.pkg` for macOS's that use SIP, hence why the `uninstall pkgutil:` is failing.

Ping @vitorgalvao - should we possibly consider this for removal (assuming I am correct)?

**Comment by vitorgalvao** [comment]
Since they’re latest supported version is four versions behind, and we officially only support the current SO version and one behind (two at the most), I’m up for removal.

It would be different if it were just discontinued, but this one seems to be discontinued *and* broken.

**Comment by miccal** [comment]
Agreed.

**Comment by karstenwolniak** [comment]
I'm having the same issue, however, "brew cask install --force send-to-kindle" throws another error:

$ brew cask install --force send-to-kindle
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by miccal** [comment]
`send-to-kindle` has been removed from Homebrew Cask.

**Comment by honzajavorek** [comment]
How can I remove it from my system now? I had previous installation, but I cannot uninstall it now, getting the errors above.

**Comment by vitorgalvao** [comment]
@honzajavorek Use `--force`.

**Comment by honzajavorek** [comment]
@victorpopkov Thanks, but as I wrote, that doesn't work:

```
$ brew cask uninstall send-to-kindle --force
==> Running uninstall process for send-to-kindle; your password may be necessary
==> Removing launchctl service com.amazon.sendtokindle.launcher
Password:
==> Removing files from pkgutil Bill-of-Materials
==> chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /bin/chmod -- 777 #<Pathname:/usr/libexec/cups>

==> Standard Output of failed command:


==> Standard Error of failed command:
chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 69324 exit 1>
```

----

macOS Sierra, 10.12.3 (16D32)

**Comment by vitorgalvao** [comment]
@honzajavorek Try to remove `$(brew --prefix)/Caskroom/send-to-kindle` now.

**Comment by honzajavorek** [comment]
That helped, thanks! I still had to go and also to delete respective directory in my Applications directory for it to disappear from launchpad etc.
