### ISSUE TITLE
Write rules for refusal of unpopular casks

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#28220]
We never had hard rules for refusal of software, like Homebrew does. However, as our popularity grows, so does the need for such rules. Twice in the last two days (https://github.com/caskroom/homebrew-cask/pull/28103, https://github.com/caskroom/homebrew-cask/pull/28197) we had submissions for casks that we refused due to being unknowns. It’s time to think about refusal rules and make them official.

[Homebrew’s rules](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#niche-or-self-submitted-stuff) seem like a fine starting point (though I don’t actually get the difference between “known” and “used”). It’s of note that their CI detects unpopular repos (< 50 stars) automatically and fails, perhaps we could leverage that.

First ideas for rules for software refusal:

+ Unmaintained (no releases in the last year, or explicitly discontinued).
+ Too obscure (< 50 stars, or equivalent).
+ What maintainers feel is too much overhead for the value.

While HB frowns upon self-submitted work, I don’t think we should. Most times there’s a CLI tool I want to try that is not already in HB, I find in its repo an open issue about adding a formula and how the author cannot really do it because it’s self-submitted. We want people to self-submit! By doing so, they’re going to add HBC as an install option to their repos and feel a bigger sense to keep the cask up-to-date. What we don’t want is people self-submitting every little tool they make that is only useful to them.

After deciding on them, at the very least we should add our rules to [faq/rejected casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md).

**Comment by miccal** [comment]
I support this idea, except that I think Homebrew's `too obscure` rule is a little harsh - I would suggest < 10 stars (or equivalent).

**Comment by vitorgalvao** [comment]
10 stars seems too low, to me. That doesn’t even mean that 10 people actually use the software. The “equivalent” part already seems forgiving enough.

**Comment by vitorgalvao** [comment]
10 stars seems too low, to me. That doesn’t even mean that 10 people actually use the software. The “equivalent” part already seems forgiving enough.

That said, I’m not necessarily suggesting we make the number public in the FAQ. We could be discretionary on a case-by-case basis.

**Comment by adidalal** [comment]
10 sounds more reasonable imo - but agreed we can put in a rough draft and refine as needed.

**Comment by vitorgalvao** [comment]
Alright, if you both find 10 fairer, then 10 it is.
