### ISSUE TITLE
How is our git different from Homebrew’s?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#28260]
In https://github.com/caskroom/homebrew-cask/issues/15603, we conclude `git` [the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb) and `git` [the cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/git.rb) are different things.

However, I’ve been trying to recall why, and can’t do it. @AnastasiaSulyagina @jawshooah can you remind me? It was likely explained in @AnastasiaSulyagina’s research (the initial Google Docs file).

**Comment by miccal** [comment]
After investigating, I cannot see a difference other than how they are installed.

**Comment by vitorgalvao** [comment]
@miccal Thank you for looking into it. Since we have no other clues, lets just remove it. If it is indeed important, it will be resubmitted.
