### ISSUE TITLE
Guidance for contributing new entries for eXist

### ISSUE THREAD

**Issue by joewiz** [caskroom/homebrew-cask#28284]
I'd like to contribute a few entries for [eXist](http://exist-db.org), a popular XML database package. It already has one entry for the current stable version, 2.2 https://github.com/caskroom/homebrew-cask/blob/master/Casks/exist-db.rb, but not the 3.0 release candidate (3.0-RC1). Since the release candidate solves tons of issues in 2.2, I'd like to be able to let my students install it easily, but how best to do this without messing up the people who want to stick with the "stable" version (2.2)? 

Also, I'd also like to be able to offer a way to install the nightly builds (from http://static.adamretter.org.uk/exist-nightly/). 

So ideally I'd somehow support:

1. Current stable release (2.2) - should be the default and the easiest to install
2. Current release candidate / beta (3.0RC1) - should still be easy to install, but shouldn't be the default
3. Nightly builds - okay if this requires some additional hoops. 

I'm aware of https://github.com/caskroom/homebrew-versions, but what is the convention for such an assortment? 

And for the nightlies, the URL changes each night, but I don't want to submit changes all the time; how to avoid this?

Thanks!

**Comment by vitorgalvao** [comment]
> And for the nightlies, the URL changes each night, but I don't want to submit changes all the time; how to avoid this?

You can’t avoid it.

As to the rest, yes, [caskroom/versions](https://github.com/caskroom/homebrew-versions) is the way to go. Submit it there with the token `exist-db3`.

**Comment by joewiz** [comment]
Thanks @vitorgalvao, I'll give it a try!
