### ISSUE TITLE
Battle for Wesnoth updated to the development version

### ISSUE THREAD

**Issue by bosyi** [caskroom/homebrew-cask#28355]
Steps to reproduce:
Go to https://www.wesnoth.org
Explore that version 1.13.6 is development version and stable is 1.12.6.
Expected result: Rollback to stable version, if needed add separate dev version installed with param (--dev for example)

**Comment by bosyi** [comment]
@colindunn Seems you made update..

**Comment by vitorgalvao** [comment]
Confirmed. Reverting now. Thank you for the notice.

**Comment by colindunn** [comment]
Very sorry about that, must have only checked the appcast. Thanks for pointing it out.
