### ISSUE TITLE
Cask ezeep.rb needs modification 

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#28401]
The Cask for [`ezeep.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ezeep.rb) currently fails as the `url` and `app` are no longer valid. The `url` is now `https://www.ezeep.com/wp-content/uploads/packages/osx/stable/ezeepInstaller.dmg` which downloads a `.dmg` containing an `.app` called `ezeep Installer.app`.

Running this `.app` calls a GUI requiring a user's password, which downloads _something_ and then installs an `.app` called `ezeep.app`. There is an `uninstall.sh` included with the `ezeep Installer.app` which is a little weird, in particular it requires `sudo` and to be called with a parameter `debug` or `production`, with no explanation given as to what these parameters actually mean. 

Even stranger, there is no similar uninstall script included with the `ezeep.app` that is actually installed.

I am at a loss as to what to do with this Cask, and need some advice please.

**Comment by reitermarkus** [comment]
```
installer manual: 'ezeep Installer.app'

uninstall script:  { executable: 'ezeep Installer.app/uninstall.sh', args: ["production"], 
                     sudo: true }
```

**Comment by reitermarkus** [comment]
> with no explanation given as to what these parameters actually mean.

If it's a simple shell script it should be easy to see where the parameter is used.

**Comment by miccal** [comment]
So with `installer manual:` a copy of the `ezeep Installer.app` is kept in the cache, and thus needs to be preceded by #{staged_path} in the `uninstall script:`?

Of course reading the `.sh` script tells where the parameters are used - what I meant was that `debug` means that keychain passwords are kept, while `production` means they are deleted, which is not at all obvious from their names.

**Comment by miccal** [comment]
Thanks for your help @reitermarkus.
