### ISSUE TITLE
Is it ok to auto-accept EULAs for Java, CUDA, etc.?

### ISSUE THREAD

**Issue by tgamblin** [caskroom/homebrew-cask#28428]
I noticed that the [Java](https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb) and [CUDA](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cuda.rb) casks auto-accept license agreements for the user. 

Is that ok?  I doubt it.  I know of no other distributions that do it. With [Debian](https://askubuntu.com/questions/190582/installing-java-automatically-with-silent-option) and [Gentoo](https://wiki.gentoo.org/wiki/Java#Installing_a_JRE.2FJDK) the user has to take some action to indicate what types of licenses they will accept, and only *then* do they allow silent mode.

Note that I'm asking because I have the same problem with [Spack](github.com/llnl/spack).  There is some relevant discussion in LLNL/spack#1298 and LLNL/spack#2621.

I am leaning towards what Gentoo and Debian do, described best [in the Gentoo docs](https://wiki.gentoo.org/wiki/Handbook:X86/Working/Portage#Licenses).

**Comment by vitorgalvao** [comment]
No, it is not OK, and [there is an issue for it](https://github.com/caskroom/homebrew-cask/issues/13593). PRs welcome.
