### ISSUE TITLE
Tracking problem Casks

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#28426]
While checking the `homepage` and `url` stanzas of all Casks, I have identified the following issues:

### Casks where the `homepage` is down but the `url` is functional:

- [droid4x.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/droid4x.rb)
- [letter.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/letter.rb)

### Casks where the download links from the `homepage` (and hence the `url`'s) are down:

- [~~appfresh.rb~~](https://github.com/caskroom/homebrew-cask/blob/master/Casks/appfresh.rb) - Removed Cask.
- [bitcasa.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitcasa.rb)
- [ionu.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ionu.rb)

### Casks where both the `homepage` and `url` are down:

- [keytouch.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/keytouch.rb)
- [lucidor.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/lucidor.rb)

Assistance from anyone familiar with these Casks/apps is appreciated.

**Comment by reitermarkus** [comment]
I think we can remove AppFresh, it has been down for at least half a year.

**Comment by miccal** [comment]
Thanks (yet again) @reitermarkus.

**Comment by vitorgalvao** [comment]
By putting each homepage into https://archive.org/, we might get a sense if they have been down for a long time or not.

**Comment by reitermarkus** [comment]
> By putting each homepage into https://archive.org/, we might get a sense if they have been down for a long time or not.

Already did this with `lucidor` before. Seems like the webhosting has expired, it was last online sometime in November.

**Comment by miccal** [comment]
According to https://archive.org/, for the `homepage`'s:

- http://www.droid4x.com/ was last online [Nov 5, 2016](http://web.archive.org/web/20161105062045/http://www.droid4x.com/);
- http://theletterapp.com/ was last online [Oct 6, 2016](http://web.archive.org/web/20161006222502/http://theletterapp.com/);
- http://usekeytouch.com/ was last online [Oct 9, 2016](http://web.archive.org/web/20161009030833/http://usekeytouch.com/);
- http://lucidor.org/lucidor/ was last online [Nov 18, 2016](http://web.archive.org/web/20161118002642/http://lucidor.org/lucidor/).

For the `url`'s:

- http://dist.bitcasa.com/update/InstallBitcasa.3.0.1.12.pkg was last online [Dec 8, 2015](http://web.archive.org/web/*/https://dist.bitcasa.com/update/*);
- https://prod1.ionu.com/release/OSX/IONU.dmg was last online [Mar 28, 2016](http://web.archive.org/web/*/https://prod1.ionu.com/release/OSX/*).

**Comment by vitorgalvao** [comment]
I’m fine with removing them all.
