### ISSUE TITLE
Feature request: Ability to specify that installers may be deleted from /usr/local/Caskroom

### ISSUE THREAD

**Issue by fgimian** [caskroom/homebrew-cask#28528]
### Description of feature/enhancement

Currently, a large amount of software installed via Cask appears to retain its installers and such in /usr/local/Caskroom

e.g.

```bash
Fotiss-MBP:~ fots$ ls -lh /usr/local/Caskroom/microsoft-office/15.29.16120900/
total 3276488
-rw-r--r--  1 fots  staff   1.6G 10 Dec 01:48 Microsoft_Office_2016_15.29.16120900_Installer.pkg
```

In most cases where an uninstaller is not present, keeping these packages around is not required and can waste a lot of space.

I suggest that an additional call is added which Cask writers can make that specifies that the contents of the original package can be purged after installation has completed.  The default would be the current behaviour as to not break existing Casks.

### Justification

Even today, storage on Macs is extremely expensive and in lower end MacBooks and MacBook Pros with 256 GB storage, this can really eat up a person's disk with no benefit.

### Example use case

e.g. in my case with many of my own casks added too

```bash
Fotiss-MBP:~ fots$ du -sh /usr/local/Caskroom
 32G	/usr/local/Caskroom
```

**Comment by fgimian** [comment]
Could potentially be solved by https://github.com/caskroom/homebrew-cask/issues/22647 although I do believe that Cask writers will need to specify if contents could be cleaned up, as some (albeit few) Casks depend on uninstallers.

**Comment by vitorgalvao** [comment]
> I suggest that an additional call is added which Cask writers can make that specifies that the contents of the original package can be purged after installation has completed

A lot of overhead and complications to cask files with little gain.

Simply having casks that use `pkg` delete their `pkg` would already cover most of the cases and require no added complexity and maintenance to cask files.

**Comment by fgimian** [comment]
Thanks for your reply @vitorgalvao, anything that can save extra lines in Cask definitions is of course ideal.

I suppose the complication is that some pieces of software using a pkg file have additional files extracted that must also be deleted.  And of course, there are cases where certain files are needed for uninstall:

e.g.

```
Fotiss-MacBook-Pro:~ fots$ brew cask cat virtualbox
cask 'virtualbox' do
  if MacOS.version <= :lion
    version '4.3.40-110317'
    sha256 'eb70fc0f36844ced6dc7deeb30397866fbaffb4a8dfb6071b047e943cae6a312'
  elsif MacOS.version == :mountain_lion
    version '5.0.30-112061'
    sha256 '030a054e49bf4edde7730fd7f5bbbc8be47d6ab06c345da70e1b5a124414f5d0'
  else
    version '5.1.12-112440'
    sha256 '74b10d9af01b8eb7d987088ffe52c74646a479a27cba4f98dc5149f1f6b93c76'
  end

  url "http://download.virtualbox.org/virtualbox/#{version.sub(%r{-.*}, '')}/VirtualBox-#{version}-OSX.dmg"
  appcast 'http://download.virtualbox.org/virtualbox/LATEST.TXT',
          checkpoint: 'be267ff5adb254acf71b9e2dab4de6bd16d4b0e5bf085edd9156c2d7be1f585f'
  name 'Oracle VirtualBox'
  homepage 'https://www.virtualbox.org/'

  pkg 'VirtualBox.pkg'

  uninstall script:  {
                       executable: 'VirtualBox_Uninstall.tool',
                       args:       %w[--unattended],
                     },
            pkgutil: 'org.virtualbox.pkg.*'

  zap delete: [
                '/Library/Application Support/VirtualBox',
                '~/Library/VirtualBox',
                '~/Library/Preferences/org.virtualbox.app.VirtualBox.plist',
                '~/Library/Preferences/org.virtualbox.app.VirtualBoxVM.plist',
                '~/Library/Saved Application State/org.virtualbox.app.VirtualBox.savedState',
                '~/Library/Saved Application State/org.virtualbox.app.VirtualBoxVM.savedState',
              ],
      rmdir:  '~/VirtualBox VMs'
end
Fotiss-MacBook-Pro:~ fots$ ls -l /usr/local/Caskroom/virtualbox/5.1.12-112440/
total 183208
-rwxr-xr-x  1 fots  staff   4357657 21 Dec 02:56 UserManual.pdf
-rw-r--r--  1 fots  staff  89426407 21 Dec 02:56 VirtualBox.pkg
-rwxr-xr-x@ 1 fots  staff     12307 21 Dec 02:56 VirtualBox_Uninstall.tool
```

**Comment by vitorgalvao** [comment]
> some pieces of software using a pkg file have additional files extracted that must also be deleted

No additional files **must** be deleted. They *might be* to save space, but none is mandatory. `pkg`s are often huge and useless after the installation is done, and are already referenced in casks, so I see no issue with removing those.

Adding a new feature and maintaining a list of files to delete after install is worse than bikeshedding In your example, there are three files: one is the installer (which we already established can be removed), other is an uninstaller, which is very much needed, and the third one is a pdf which may not be of use *to you* but might very well be of use to someone else. We’re not going to start making decisions on what is useful to users, that is not our goal.

**Comment by miccal** [comment]
Also remember that there Casks that use [`#{staged_path}`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats-as-a-string) (about 80 of them, actually) that may or may not require the install files to be kept.

I think it is best to leave the deletion to the user - for example, after running `brew cask install mactex` I then `cd /usr/local/Caskroom/; rm -r mactex;` because I know that the huge `.pkg` :smirk: is not required to be kept.

**Comment by reitermarkus** [comment]
Keep in mind that once we have `upgrade` functionality, we might need the installer in this scenario:

If the upgrade fails, revert to the previously installed version using the previous installer.

**Comment by miccal** [comment]
I think that with the issues raised, and in light of https://github.com/caskroom/homebrew-cask/issues/29301, at this stage it is best left to the user to clean up `/usr/local/Caskroom` if they wish.
