### ISSUE TITLE
Cask request: [Pritunel Client]

### ISSUE THREAD

**Issue by Tecnico1931** [caskroom/homebrew-cask#28571]
### Cask details

(Please fill out as much as possible)

**Name**:  Pritunel Client

**Homepage**: http://client.pritunl.com/

**Download URL**: https://github.com/pritunl/pritunl-client-electron/releases/download/1.0.1210.1/Pritunl.pkg.zip

**Description**: Free and open source cross platform OpenVPN client

**Comment by miccal** [comment]
[This is already available.](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pritunl.rb)
