### ISSUE TITLE
Cask request: [rar]

### ISSUE THREAD

**Issue by delcypher** [caskroom/homebrew-cask#28611]
### Cask details

In the [Homebrew/homebrew-binary](https://github.com/Homebrew/homebrew-binary/) repository there was a [rar formula](https://github.com/Homebrew/homebrew-binary/blob/master/rar.rb). It has not been ported over to homebrew-cask.

Right now I have to do

```bash
brew install Homebrew/homebrew-binary/rar
```

which probably isn't a good idea because `homebrew-binary` appears to be dead

**Name**: rar

**Homepage**: http://www.rarlab.com/

**Download URL**: http://www.rarlab.com/rar/rarosx-5.4.0.tar.gz

**Description**:

RAR is a powerful archive manager. It can backup your data and reduce the size of email attachments, decompress RAR, ZIP and other files downloaded from Internet and create new archives in RAR and ZIP file format.

**Comment by miccal** [comment]
[We are working on it](https://github.com/caskroom/homebrew-cask/issues/23938) but would welcome a pull request if you would like to attempt it yourself.

**Comment by vitorgalvao** [comment]
As @miccal said, already being tracked in another issue, and PRs are welcome. Closing.

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/28823
