### ISSUE TITLE
Outdated cask: Mamp

### ISSUE THREAD

**Issue by PrintHelloWorld** [caskroom/homebrew-cask#28614]
Mamp: [`mamp`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mamp.rb).
New Version is 4.1

New Download link:
http://downloads.mamp.info/MAMP-PRO/releases/4.1/MAMP_MAMP_PRO_4.1.pkg

The current version of the cask in 4.0.5 has curl errors because the url no longer exists

**Comment by miccal** [comment]
The current version of the Cask you linked to is 4.1 - did you run `brew update` before attempting the install?

**Comment by PrintHelloWorld** [comment]
Sorry, that's just dumb on my part. Thanks for the quick help though.
