### ISSUE TITLE
Bug report: devonthink-pro-office installs but doesn't receive "print to devonthink" submissions

### ISSUE THREAD

**Issue by pacificera** [caskroom/homebrew-cask#28618]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

Had previous version of Devonthink pro installed.  Reinstalled devonthink-pro-office 2.9.8 via cask.  Used it for a few day without noticing any issues.  My workflow is to use the devonthink "print to devonthink" service to get pdfs into dt.  This option is present and seems to work, but the pdfs never appear in the dt inbox.  

I reinstalled dt from the vendor site, and this feature works again.

**Comment by miccal** [comment]
To help me troubleshoot this, can you please provide the download url of the one you installed manually?

**Comment by miccal** [comment]
That is the `url` for the Cask [devonthink-pro](https://github.com/caskroom/homebrew-cask/blob/master/Casks/devonthink-pro.rb), not [devonthink-pro-office](https://github.com/caskroom/homebrew-cask/blob/master/Casks/devonthink-pro-office.rb).

Which one do you believe there is a problem with?

**Comment by miccal** [comment]
Closing due to lack of response.
