### ISSUE TITLE
RStudio requires Homebrew R even if the cask version is installed

### ISSUE THREAD

**Issue by gwerbin** [caskroom/homebrew-cask#28714]
I already have the `r-app` cask installed, but the `rstudio` cask has a hard-coded dependency on the `homebrew/science/r` package. The R GUI app is perfectly suitable as an RStudio backend, and I don't want to use the Homebrew R version.

Can there at least be a check for an existing R executable that short-circuits this dependency?

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/28717.
