### ISSUE TITLE
Cask request: Spark (email)

### ISSUE THREAD

**Issue by SamHH** [caskroom/homebrew-cask#28737]
### Cask details

**Name**: Spark

**Homepage**: https://sparkmailapp.com/

**Download URL**: https://itunes.apple.com/app/id1176895641

**Description**: Email client.

Thanks!

**Comment by vitorgalvao** [comment]
MAS-only.

**Comment by mcansky** [comment]
MAS ? Mac App Store ?

**Comment by vitorgalvao** [comment]
> Mac App Store ?

Yes.
