### ISSUE TITLE
Cask request: Alacritty

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#28733]
### Cask details

**Name**: Alacritty

**Homepage**: https://github.com/jwilm/alacritty

**Download URL**: No packaged releases yet, hence the issue instead of making the cask.

**Description**: “the fastest terminal emulator in existence. Using the GPU for rendering enables optimizations that simply aren't possible in other emulators”.

**Comment by Numbermaniac** [comment]
Interesting. I'd have thought rendering simple 2D text on a window wasn't that slow. Didn't think using a GPU to draw the text could apparently make a big difference!

**Comment by sneak** [comment]
Further: It doesn't even have an .app bundle yet AFAIK.  It might be a better choice for Homebrew itself instead of Caskroom.

**Comment by vitorgalvao** [comment]
> Further: It doesn't even have an .app bundle yet AFAIK.

That’s the whole point of the waiting request. I mention that in the **Download** of the top post.

> It might be a better choice for Homebrew itself instead of Caskroom.

No, because it’s an app and a GUI, hence belongs here.

**Comment by mscharley** [comment]
They have an `.app` bundle as part of their build, but they don't publish packages or releases yet.

See also https://github.com/mscharley/homebrew-homebrew/blob/master/alacritty.rb

/via jwilm/alacritty#495

**Comment by gmile** [comment]
@vitorgalvao your wrote:

> No packaged releases yet, hence the issue instead of making the cask.

But it is prohibited to add formulas for apps that are yet to be packaged? I briefly looked at the [style guide](https://github.com/caskroom/homebrew-cask/blob/aaf918df65103802962bb2a4075d414843d03b87/CONTRIBUTING.md#style-guide) for contributing new casks, there was no mention / requirement for apps to be packaged.

There were additions that indeed allow `alactitty` to be packaged automatically, specifically mentioned in this issue – https://github.com/jwilm/alacritty/pull/462.

The steps to be wrapped into a Cask are:

```
git clone https://github.com/jwilm/alacritty.git
cargo build --release
make app
cp -r target/release/oss/Alacritty.app /Applications/Alacritty.app
```

**Comment by vitorgalvao** [comment]
@gmile Seeing as HBC cannot build software, yes, having it packaged is a must.

**Comment by vitorgalvao** [comment]
Looks like it’s going to take a while for releases to appear. No point in keeping the issue open, especially since until launch, some of us will no longer care (I don’t, as they don’t intend to support basic features like tabs and scrolling).

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/54950
