### ISSUE TITLE
Error: Failure while executing: git clone [...]

### ISSUE THREAD

**Issue by brunokoga** [caskroom/homebrew-cask#2880]
I'm having an issue installing brew-cask. I have no idea why I'm having this error. I've been using homebrew for a while and have never seen this error before.

`$ brew tap phinze/cask`
Cloning into '/usr/local/Library/Taps/phinze-cask'...
remote: Reusing existing pack: 20740, done.
remote: Counting objects: 21, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 20761 (delta 10), reused 4 (delta 0)
Receiving objects: 100% (20761/20761), 8.57 MiB | 222.00 KiB/s, done.
Resolving deltas: 100% (10964/10964), done.
Checking connectivity... done
Tapped 1 formula

`$ brew install brew-cask`
==> Cloning https://github.com/phinze/homebrew-cask.git
**Error: Failure while executing: git clone --depth 1 --branch v0.28.0 https://github.com/phinze/homebrew-cask.git /Library/Caches/Homebrew/brew-cask--git**

**Comment by tiagonbotelho** [comment]
Having the same error any help would be appreciated

**Comment by webdevel** [comment]
I was having this same issue on a clean OS X Yosemite 10.10.2 with fresh install of brew. I did not execute brew as sudo.

In case this helps someone else, I was able to work around this issue by simply changing the ownership of the Homebrew cache directory.

The ownership was:

```
$ ll /Library/Caches/

drwxrwxr-x     root             admin          204 Apr  5 12:08 Homebrew
```
I changed the ownership to:
```
$ chown -R steven:admin /Library/Caches/Homebrew

drwxrwxr-x     steven         admin          204 Apr  5 12:08 Homebrew
```
Steven is the user I am using brew as.

I re-ran the command to install `brew install Caskroom/cask/xquartz` and it installed successfully.

I hope that helps.

**Comment by vitorgalvao** [comment]
Some have fixed the issues, others haven’t, and this is now a mess. If someone is still experiencing this, please open a new issue.

**Comment by jjoos** [comment]
Had a similar issue to @singron my `/usr/bin/ruby` missed an execute bit which resulted in the same error. `sudo chmod +x /usr/bin/ruby`

@vitorgalvao sorry for not filing a new issue, but wanted to share this with people Google-ing this error and finding this issue. (@singron's comment lead me in the right direction).

**Comment by thebenjy** [comment]
i was using ruby via rvm and had not /usr/bin/ruby. i created a /usr/bin/ruby simlink to my rvm installed rvm instance and it worked
