### ISSUE TITLE
autoffi.rb broken

### ISSUE THREAD

**Issue by colindunn** [caskroom/homebrew-cask#28865]
autoffi currently had no available download because its github repository no longer has any releases.

I've raised an issue there to confirm a course of action with the maintainer:
https://github.com/AutoFFI/AutoFFI/issues/2

Just noting here in case someone else comes across the cask.

**Comment by miccal** [comment]
Thank you @colindunn.

**Comment by samvv** [comment]
Thanks, fixing it now.

**Comment by colindunn** [comment]
Thanks @samvv

**Comment by colindunn** [comment]
Any update on this @samvv ?

**Comment by vitorgalvao** [comment]
I think at this point it’s best to just remove the cask. When/if it gets fixed upstream, we can readd it.

**Comment by vitorgalvao** [comment]
On second though, lets keep it removed. Just noticed the cask is open-source and binary-only, even, so it doesn’t even belong in HBC. From [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).
