### ISSUE TITLE
Question: discovered appcast urls

### ISSUE THREAD

**Issue by colindunn** [caskroom/homebrew-cask#28873]
I have managed to find a number of appcast urls during my trawling of casks but haven't added them yet as they were either:
- not known for sure that they would work at the time of updating a cask; or
- known good, but the cask didn't require an update

I'm going to assume that anything that hasn't changed checkpoint in over a week is good and would like to add them.

I don't really want to do them all individually, but I'm concerned that a single failure when updating a lot of casks will make travis ci go mental.

What's the best way to perform the update? Any advice that you can give?

**Comment by miccal** [comment]
@colindunn roughy how many are we talking about here?

**Comment by colindunn** [comment]
Maybe 20-30 @miccal. Might be a few more than that. I need to go through a lot manually because I didn't have this use-case in mind when I started storing the data :-)

I could always limit it to small runs?

**Comment by miccal** [comment]
@colindunn let start doing it in small runs, 10 Casks at a time, and then when checked and merged you can add another run of 10.

Sound good?

**Comment by colindunn** [comment]
No problem, I'll do that then @miccal 

Leave the issue open and I'll note in each PR as I go?

**Comment by miccal** [comment]
Sure, thanks @colindunn.

**Comment by colindunn** [comment]
I may have more than I suspect, first 10 doesn't make it out of A yet. We'll see how it goes with the first lot anyway @miccal

**Comment by colindunn** [comment]
So I'm at 40 now and up to G. I've definitely underestimated how many I've collected.

I doubt I will get any more done today so will continue tomorrow.

**Comment by miccal** [comment]
@colindunn Can you please stop here for now, as I am starting to thing that some of your `appcast` url's are not suitable.

Ping @caskroom/maintainers.

**Comment by colindunn** [comment]
No problem @miccal happy to wait for further feedback

**Comment by colindunn** [comment]
Here are the next 3 as well if it helps with review:
* https://github.com/colindunn/homebrew-cask/commit/660a9fdc31a81e68157d4841771c85a090b7984e
* https://github.com/colindunn/homebrew-cask/commit/5dfff309b256b817639668dccf3a63cd3e7250bf
* https://github.com/colindunn/homebrew-cask/commit/6af631966f435aafafd88fcfb460f86138a31b1b

Regarding anything that is a html page/copy of a homepage, the majority of the checkpoints were collected before the new year, so those pages have survived date issue including page copyright updates so should be stable.

**Comment by miccal** [comment]
[Possibly relevant](https://github.com/caskroom/homebrew-cask/issues/19103).

**Comment by vitorgalvao** [comment]
Something important about this.

When you add a github releases `appcast`, then the `url` should also be changed to the get the package they provide in that releases page. That makes it more consistent, since they are updated at exactly the same time, leads to less errors.

The (rare) exception is when a github releases `appcast` exists but they don’t share compiled packages there.

**Comment by vitorgalvao** [comment]
Don’t worry about those already merged, I’ll take care of them. Warning so we don’t duplicate work. Just keep that in mind for the next PRs.

**Comment by miccal** [comment]
Sorry about that @vitorgalvao, I should have looked more carefully before I merged them.

Would you like me to give you a hand?

**Comment by vitorgalvao** [comment]
> Sorry about that @vitorgalvao, I should have looked more carefully before I merged them.

Not to worry. It’s another of those unwritten rules.

> Would you like me to give you a hand?

No need, thank you. Almost done. They’re relatively few and most of them are the exception, actually, so they’re good as they are.

**Comment by colindunn** [comment]
So you guys are happy for me to proceed with what I'm doing here and the appcast urls I'm finding @vitorgalvao @miccal ?

Aside from changing the github links where possible

**Comment by vitorgalvao** [comment]
@colindunn Yes, go for it. Appcasts are always welcome. I’d eventually (not near future, since it’s quite a big task) like to setup a system to make the cask files themselves auto-update, and that depends on them having appcasts.

**Comment by colindunn** [comment]
I underestimated how many of these I have very badly it seems, I now have about 110 and still going.

Out of interest, what do people do when an appcast gets updated but there isn't a release becase either:
- there wasn't an osx release for the particular version
- it's a pre-release or beta and shouldn't be added until there is an official release

I am noting the new appcast checkpoint but not updating the cask and ignoring it until it changes again, but what is the method used by others or the recommended path?

**Comment by vitorgalvao** [comment]
@colindunn In those cases, do not worry, you can just leave it as is.

We had at one point a semi-automated system I built, but scraped it. I’ve learned a lot when it was in use and will make a new one that fixes the previous flaws. In that semi-automated system, the `checkpoint:` will also be updated in those cases, but otherwise, don’t go out of your way to do it, it isn’t worth it. The `appcast` is for specific use of those systems.

How are you finding so many, by the way? Are you just going through them all and looking for it?

**Comment by colindunn** [comment]
I have very rough script for going through all the casks in random order and then recording what I find. I manually choose what I think would work (in some cases the html page is obviously static, or I actually find a json call etc) and then I record the checkpoint along with it plus the date added. If it survives a few checks then it looks good.

I've collected a fair bit of data with all this cask trawling. Once I have these appcasts in I will create another issue to show how I'm keeping track of casks where I can't find appcast values to start a discussion around how that might be integrated if it's useful.

I can continue with the tool and/or share it, but I'd prefer to use the collected data to feed back in to the project rather than have a separate tool.

**Comment by adidalal** [comment]
This is fantastic work - when I added appcasts, they were generally a manual process (record traffic with Charles)

**Comment by colindunn** [comment]
It's still definitely manual @adidalal it's just the recording of the checkpoint and date added that's helping here. I'm up to 130 now, shouldn't be many more than that. Very sorry about the gross underestimation @miccal !

**Comment by miccal** [comment]
No problem @colindunn your efforts here a greatly appreciated by myself and I am sure of all the maintainers.

**Comment by colindunn** [comment]
173 total. Just waiting for the last one to pass and the remaining to be merged and I'll close the issue

**Comment by miccal** [comment]
Fantastic work @colindunn!

**Comment by colindunn** [comment]
Happy to help :-)
