### ISSUE TITLE
Outdated information in hacking.md

### ISSUE THREAD

**Issue by scribblemaniac** [caskroom/homebrew-cask#28934]
In `doc/development/hacking.md` under the "Goals, Design, and Philosophy" heading, it says:

> We manage installed files via the “symlink farm” method, like GNU Stow and Homebrew.

If I'm not mistaken, this is no longer the case, so that bit of the documentation should be updated.

**Comment by vitorgalvao** [comment]
Agreed. That document needs a huge overhaul, even, so https://github.com/caskroom/homebrew-cask/issues/28964.
