### ISSUE TITLE
Feature request: cask-repair should automatically navigate to the correct directory.

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#28961]
### Description of feature/enhancement

Using cask-repair should automatically move to the correct working directory.

### Justification

Every time someone wants to update a Cask using the cask-repair script, they have to go to the Contributing page and find the correct directory to use it in. Since the command listed already accounts for someone moving the repository, I see no reason not to include it in the script itself.

### Example use case

Use cask-repair from the Home directory or wherever, and it will automatically run `cd “$(brew —repository)/Library/Taps/caskroom/homebrew-cask/Casks”` so you don’t have to go to [CONTRIBUTING.md](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)
again.

**Comment by miccal** [comment]
`cask-repair` is designed to be used in any of the four repositories (casks, versions, fonts, eid) so it is better for the user to manually change to which directory they want.

**Comment by Saklad5** [comment]
I wasn’t aware of that. Still, a command-line argument to navigate to a repository would be handy.

**Comment by vitorgalvao** [comment]
`cask-repair` [lives in another repo](https://github.com/vitorgalvao/tiny-scripts). Requests and bugs reports are to made there.

You don’t have to keep coming back to CONTRIBUTING.md. It’s not like the command is changing, you can easily include it in your shell as an alias or function.

All that said, I have an update in the works that’ll address this. No ETA, though.
