### ISSUE TITLE
Readd mpv

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#28988]
As [Homebrew deprecates `linkapps`](https://github.com/Homebrew/brew/pull/1808) and [mpv once again has macOS builds](https://mpv.io/installation/), it seems like we should readd it.

If we do, we need to remove it as an example on https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md.

**Comment by miccal** [comment]
The macOS builds are by a third-party, though?

**Comment by vitorgalvao** [comment]
> The macOS builds are by a third-party, though?

Yes, but they are officially approved. They’re advertised on the site as trustworthy downloads.

**Comment by miccal** [comment]
Ok - does that mean that `mpv` should be named `mpv-app` in Cask, as I assume it is not being removed from the Core?

**Comment by vitorgalvao** [comment]
No, that one does not warrant the suffix. It’s an app with a graphical output as its main goal.

**Comment by BenjaminHCCarr** [comment]
@vitorgalvao, I use `mpv` as command line, and wife uses .app.

I haven't looked, is there a way to deep symlink `mpv` in `MPV.app` to `/usr/local/bin`? Otherwise I imagine there will be many of us who have an SO who uses the GUI while we use the CLI. Also the GUI is only able to load one file/stream, while you can run as many CLI as you want until you run out of RAM.

**Comment by BenjaminHCCarr** [comment]
Okay, a second post, as this is totally unrelated to MPV, I build the IDEs for `-core` projects as well:
```
Warning: `brew linkapps` has been deprecated and will eventually be removed!

Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
bundles that can be relocated. Instead, please consider using `brew cask` and
migrate formulae using `.app`s to casks.
Linking: /usr/local/opt/mpv/mpv.app
Linking: /usr/local/opt/python/IDLE.app
Linking: /usr/local/opt/python/Python Launcher.app
Linking: /usr/local/opt/python3/IDLE 3.app
Linking: /usr/local/opt/python3/Python Launcher 3.app
Linking: /usr/local/opt/qt5/libexec/Assistant-qt5.app
Linking: /usr/local/opt/qt5/libexec/Designer-qt5.app
Linking: /usr/local/opt/qt5/libexec/Linguist-qt5.app
Linking: /usr/local/opt/qt5/libexec/pixeltool-qt5.app
Linking: /usr/local/opt/qt5/libexec/qml-qt5.app
Linked 10 apps to /Applications
```

Does this mean that for `PythonX` and `QT` I will need to install the environment from `-core` and the IDE's from `Cask`? Or will the formulas now actually move the `.app` instead of linking?

Sorry, the warning give a lot of detail, it might be helpful to throw a page up about what is going on that is printed in the warning.

Sorry to jump on this I just brewed and got the warning for the first time.

**Comment by miccal** [comment]
> I use mpv as command line, and wife uses .app.

Same here!

**Comment by vitorgalvao** [comment]
@BenjaminHCCarr Nothing changed in the `mpv` formula. It can still build the app bundle. This makes no difference to the way we build things. Regarding the warning, you need to direct your comments to the HB core.

**Comment by miccal** [comment]
@vitorgalvao so if it can be built with the `--with-bundle` option, then why would we also add it to Cask, especially after the whole de-duplication process?

**Comment by BenjaminHCCarr** [comment]
sorry @vitorgalvao this is the only thread that comes up when you search the warning.

I did comment in Homebrew/brew#1808

If you can point me somewhere else I am happy to take it there as well.

**Comment by adidalal** [comment]
@miccal I think I've brought up this point before, but basically comes down to vendor-built bs. Homebrew built .apps - I personally prefer vendor built, and so it may make sense to have some sort of overlap there (really a small subset - open source apps that also have a GUI)

**Comment by vitorgalvao** [comment]
@miccal I missed your question before.

In addition to what @adidalal said, HB builds are also less flexible. `--with-bundle` builds the app every time (as opposed to downloading from a bottle), which means more time and resources on your machine. With the end of linking, it also makes it difficult for some users to find the GUI app. Finally, HB builds are not portable, meaning their app bundles are tightly built against the binaries and you can’t just move everything around.

**Comment by miccal** [comment]
Thanks for the explanation @adidalal and @vitorgalvao - I will add this to Cask later today.
