### ISSUE TITLE
Add explanation for exclamation point in `man brew-cask`

### ISSUE THREAD

**Issue by kenahoo** [caskroom/homebrew-cask#29010]
As per https://github.com/caskroom/homebrew-cask/issues/13160 , there's no explanation in the official docs for what an exclamation point means in the output of `brew cask list`.  It would be great to get that added.

**Comment by miccal** [comment]
This issue will be looked at once https://github.com/caskroom/homebrew-cask/issues/14058 is completed.

Thank you for your suggestion, though.
