### ISSUE TITLE
develop_brew_cask is removed but hacking doc still refers to this

### ISSUE THREAD

**Issue by SevenHong** [caskroom/homebrew-cask#29033]
It looks like script /developer/bin/develop_brew_cask was removed in b737a5e2ef709836687f114aaee3e0cc8cb4c9b6 but [hacking doc](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/hacking.md) still refers to this script. Maybe someone wanna update the doc? Was trying to investigate the bug #29032 I just reported..

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/28964
