### ISSUE TITLE
Bug report: Error: Invalid tap name '/' for some casks

### ISSUE THREAD

**Issue by SuperHenkie** [caskroom/homebrew-cask#29060]
Followed the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) steps. As far as I can tell, everything is up to date.

**Problem:** when I do `brew cask info xxxx` for some casks I'm getting this output:
> Error: Invalid tap name '/'

This doesn't happen with all casks, only a few (for example: audacity, sshfs). 
If I try `brew cask home xxxx` for these casks, same problem.

`brew doctor` says "Your system is ready to brew".

`brew cask doctor` says a whole lot of things, but NO warnings or errors whatsoever. In case it's relevant, here are some version numbers and stuff:

> ==> macOS Release:
> 10.12.2
> ==> Hardware Architecture:
> intel-64
> ==> Ruby Version:
> 2.0.0-p648
> ==> Ruby Path:
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
> ==> Homebrew Version:
> Homebrew 1.1.7-23-gc6d7c85
> Homebrew/homebrew-core (git revision f5fa2; last commit 2017-01-15)
> ==> Homebrew Executable Path:
> /usr/local/bin/brew
> ==> Homebrew Cellar Path:
> /usr/local/Cellar
> ==> Homebrew Repository Path:
> /usr/local/Homebrew
> ==> Homebrew Origin:
> https://github.com/Homebrew/brew.git
> ==> Homebrew-Cask Version:
> Homebrew-Cask 1.1.7-23-gc6d7c85
> caskroom/homebrew-cask (git revision 751e; last commit 2017-01-16)

**Comment by vitorgalvao** [comment]
> This doesn't happen with all casks, only a few (for example: audacity, sshfs).

Those casks no longer exist.
