### ISSUE TITLE
Cask request: Ukrainian Typographic Keyboard

### ISSUE THREAD

**Issue by denysdovhan** [caskroom/homebrew-cask#29109]
### Cask details

**Name**: Ukrainian Typographic Keyboard

**Homepage**: https://github.com/denysdovhan/ukrainian-typographic-keyboard

**Download URL**: https://github.com/denysdovhan/ukrainian-typographic-keyboard/releases/download/v1.0.0/ukrainian-typographic-keyboard.dmg

**Description**: Combined Ukrainian keyboard layout with typographic symbols

---

Related issue: https://github.com/denysdovhan/ukrainian-typographic-keyboard/issues/4#issuecomment-272422771

**Comment by denysdovhan** [comment]
@miccal may I ask, when I publish new version, should I make a PR in this repo with updating cask's version too? Can I do it automatically?

**Comment by vitorgalvao** [comment]
> I ask, when I publish new version, should I make a PR in this repo with updating cask's version too?

Yes.

> Can I do it automatically?

[Yes](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). Those instruction will be [even simpler soon](https://github.com/caskroom/homebrew-cask/pull/29079/files).

**Comment by denysdovhan** [comment]
@vitorgalvao wow, thanks ;)
