### ISSUE TITLE
Cask request: Nylas Mail

### ISSUE THREAD

**Issue by pmbenjamin** [caskroom/homebrew-cask#29114]
### Cask details

Although we already have [Nylas N1](https://github.com/caskroom/homebrew-cask/blob/master/Casks/nylas-n1.rb) cask, it is currently at v0.4.

Nylas released a v1.0 and renamed the app to **Nylas Mail**.

**Name**: Nylas Mail

**Homepage**: https://nylas.com/

**Download URL**: https://billing.nylas.com/download

**Description**: The best free email app for Mac and Windows.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/29113

**Comment by pmbenjamin** [comment]
@vitorgalvao Thank you. I apologize for this duplicate. I searched GitHub Issues for Nylas, but didn't search PRs.
