### ISSUE TITLE
Cask request: Cloudapp

### ISSUE THREAD

**Issue by ryantology** [caskroom/homebrew-cask#29130]
### Cask details

**Name**:
CloudApp

**Homepage**:
https://www.getcloudapp.com/

**Download URL**:
https://www.getcloudapp.com/download/mac

**Description**:

Screen shot and video sharing software.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/cloud.rb
