### ISSUE TITLE
Cask request: Wunderlist

### ISSUE THREAD

**Issue by ryantology** [caskroom/homebrew-cask#29131]
### Cask details

**Name**:
Wunderlist

**Homepage**:
https://www.wunderlist.com/

**Download URL**:
https://itunes.apple.com/app/wunderlist-to-do-list-tasks/id410628904
App store link ... likely unsupported?

**Description**:

Task / todo list manager

**Comment by miccal** [comment]
> App store link ... likely unsupported?

Yes, MAS is not supported.
