### ISSUE TITLE
Allow an option to call programs from the command line.

### ISSUE THREAD

**Issue by shurane** [caskroom/homebrew-cask#2914]
For example, `google-chrome` can take additional arguments, like `--allow-running-insecure-content` or `--ignore-gpu-blacklist`. But the Caskroom isn't on `$PATH`, so that makes this somewhat inconvenient. 

Something like `brew cask open google-chrome --allow-running-insecure-content` would get the job done.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. We can revisit this later.
