### ISSUE TITLE
Cask request: Spark Mail App

### ISSUE THREAD

**Issue by barryanders** [caskroom/homebrew-cask#29175]
### Cask details

**Name**: Spark Mail App

**Homepage**: https://sparkmailapp.com

**Download URL**: https://itunes.apple.com/app/id1176895641?mt=12

**Description**: Beautiful & Intelligent Email App

**Comment by miccal** [comment]
Sorry, MAS apps are not supported by Cask.

**Comment by barryanders** [comment]
Ah, my bad.
