### ISSUE TITLE
Cask request: libspotify

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#29275]
### Cask details

Name: libspotify

Homepage: https://developer.spotify.com/technologies/libspotify/

Download URL: Removed from homebrew-binary with https://github.com/Homebrew/homebrew-binary/commit/f3bfb367e3102a4f1d230635d303b4d8a0154983

Description: C interface to Spotify

@miccal, Any reason for this removal, or just deleting stragglers from the binary repo?

**Comment by miccal** [comment]
@adidalal the reason I suggested removal in homebrew/binary was because the homepage for [`libspotify`](https://developer.spotify.com/technologies/libspotify/) states:

> Important! LibSpotify and CocoaLibSpotify are no longer under active development on any platform and are considered deprecated. If you are building applications for iOS or Android, please use the iOS SDK or Android SDK. We hope to be able to provide you with a new library for other platforms.

**Comment by adidalal** [comment]
Got it. I still happen to use it, so will write up a Cask as I find some time. Doesn't look super complicated.

**Comment by miccal** [comment]
@adidial I am happy to do it of you like?

**Comment by adidalal** [comment]
That would be great! This does have a decent volume of users (all python scripts that interact with Spotify basically rely on it) but it's an install once sort of Formula, which might explain the low number of analytics hits.

**Comment by miccal** [comment]
Hmm, I don't think I can:

<img width="870" alt="screen shot 2017-01-22 at 09 09 13" src="https://cloud.githubusercontent.com/assets/6127163/22179027/89d1bc92-e082-11e6-93b8-a8ac4919f08d.png">

**Comment by adidalal** [comment]
Gotcha, thanks for looking into it anyway.

**Comment by miccal** [comment]
You're welcome.

**Comment by adidalal** [comment]
```ruby
class Libspotify < Formula
  desc "C interface to Spotify"
  homepage "http://developer.spotify.com/en/libspotify/overview/"
  url "https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Darwin-universal.zip"
  sha256 "80053f0779f6192a8052732904d88b91acc62a350831f6b585a3c6ac10cb8fbd"

  bottle :unneeded

  def install
    (include/"libspotify").install "libspotify.framework/Versions/12.1.51/Headers/api.h"
    lib.install "libspotify.framework/Versions/12.1.51/libspotify" => "libspotify.12.1.51.dylib"
    doc.install Dir["docs/*"]
    doc.install %w[licenses.xhtml examples]
    man3.install Dir["man3/*"]
    lib.install_symlink "libspotify.12.1.51.dylib" => "libspotify.dylib"
    lib.install_symlink "libspotify.12.1.51.dylib" => "libspotify.12.dylib"
    (lib/"pkgconfig/libspotify.pc").write pc_file
  end

  def pc_file; <<-EOS.undent
    prefix=#{opt_prefix}
    exec_prefix=${prefix}
    libdir=${exec_prefix}/lib
    includedir=${prefix}/include

    Name: libspotify
    Description: Spotify client library
    Version: #{version}
    Libs: -L${libdir} -lspotify
    Cflags: -I${includedir}
    EOS
  end
end
```

Will add it in as a cask with the `discontinued` caveat - the download link still works.

**Comment by vitorgalvao** [comment]
@adidalal As a cask? That’s a formula.

**Comment by adidalal** [comment]
Pasted in the contents of the Formula just to have quick access to the download URL, but will convert it to a Cask when making the PR.

**Comment by vitorgalvao** [comment]
Still interested in this, @adidalal?
