### ISSUE TITLE
Cask request: KeePassXC

### ISSUE THREAD

**Issue by Peilun0912** [caskroom/homebrew-cask#29336]
Name: KeePassXC

Homepage: https://keepassxreboot.github.io/

Download URL: https://github.com/keepassxreboot/keepassxc/releases/download/2.1.0/KeePassXC-2.1.0.dmg

Description:

> KeePassXC is a community fork of KeePassX which aims to incorporate stalled pull requests, features, and bug fixes that have never made it into the main KeePassX repository.

**Comment by joschi** [comment]
Refs keepassxreboot/keepassxc#182

**Comment by TheZ3ro** [comment]
KeePassXC maintainer here,

the previously released dmg only support macOS > 10.12.

I need to re-upload a new dmg with the same version number (`2.1.0`) that support MacOS X > 10.7
 but this will obviously have a different sha256 hash
Can you please fix the `Casks/keepassxc.rb` file with the new hash once I update the release with the new files?

KeePassXC issue here https://github.com/keepassxreboot/keepassxc/issues/181#issuecomment-275113864

**Comment by miccal** [comment]
No problem @TheZ3ro, just let us know when you have updated the release.

**Comment by TheZ3ro** [comment]
So the new dmg is online (at the previous link, [KeePassXC-2.1.0.dmg](https://github.com/keepassxreboot/keepassxc/releases/download/2.1.0/KeePassXC-2.1.0.dmg))

The new sha256 is `44f126aebd0993a8c2b200595c37ee0d864eacc7cb3a61abd4ecd89a546e81d6` and can be retrived from here [KeePassXC-2.1.0.dmg.DIGEST](https://github.com/keepassxreboot/keepassxc/releases/download/2.1.0/KeePassXC-2.1.0.dmg.DIGEST)

Can I ask you a question? When a new version is released (2.1.1 for example) how it's the hash updated? 
Thanks

**Comment by miccal** [comment]
Any user can update any Cask themselves via opening a PR, and the lead maintainer @vitorgalvao has created a handy tool called `cask-repair` which makes the process very easy, as you can see [here](https://github.com/caskroom/homebrew-cask/pull/29402).

**Comment by TheZ3ro** [comment]
Ok very nice :+1: Thanks
