### ISSUE TITLE
Suggestion (keka): replace URL to Github's or add it as mirror

### ISSUE THREAD

**Issue by magicgoose** [caskroom/homebrew-cask#29338]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/keka.rb

New builds are hosted [here](https://github.com/aonez/Keka/releases), and old location will probably be gone sooner than later.

Last stable (1.0.7) build: https://github.com/aonez/Keka/releases/download/1.0.7/Keka-1.0.7.dmg
I checked SHA256, it matches to the one in cask.

Old URL also doesn't support HTTPS.

**Comment by vitorgalvao** [comment]
We don’t support mirrors.

But agreed on the rest. https://github.com/caskroom/homebrew-cask/pull/29342.
