### ISSUE TITLE
Cask request: Pianobar

### ISSUE THREAD

**Issue by cortneytaylor** [caskroom/homebrew-cask#29438]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Pianobar

Homepage: https://github.com/PromyLOPh/pianobar

Download URL: https://github.com/PromyLOPh/pianobar.git

Description: Command line Pandora player

**Comment by vitorgalvao** [comment]
This seems to be a CLI-only open-source tool. It belongs in [Homebrew](https://github.com/Homebrew/homebrew-core).

This policy is documented in [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew](https://github.com/Homebrew/homebrew). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).
