### ISSUE TITLE
I can't install freefilesync 

### ISSUE THREAD

**Issue by xingezhang** [caskroom/homebrew-cask#29459]
Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) or [making requests](https://github.com/caskroom/homebrew-cask#requests), as appropriate. Note the former has several links to help diagnose and fix common issues.

If none of those guides is appropriate, delete this template and explain your issue in detail.

Please note that **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**. Dealing with the same solved and documented problems leads to maintainer burnout and wasted hours. Those would be better spent improving Homebrew-Cask itself and fixing real bugs.

If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

Thank you for taking the time to make a correct report. The whole team appreciates it.

Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: f8a9878fed6b88eb7f0f48a105d2da771f2c203fae865776a3d581481b9a1f52
Actual: 82b6fa36b9ae2f5c420811f2b450d0048e333bc725a7c0228512aeaa0b3d517d

**Comment by vitorgalvao** [comment]
You clearly haven’t followed the instructions. Also, I can’t reproduce. Clear your cache (`rm -rf "$(brew --cache)"`) and try again.

**Comment by xingezhang** [comment]
i tried,same error.

**Comment by miccal** [comment]
Working for me:
```
-bash-4.4.5- /Users/miccal [> brew cask fetch freefilesync
==> Downloading external files for Cask freefilesync
==> Downloading http://www.freefilesync.org/download/FreeFileSync_8.8_macOS.zip
######################################################################## 100.0%
==> Verifying checksum for Cask freefilesync
==> Success! Downloaded to -> /Users/miccal/Library/Caches/Homebrew/Cask/freefilesync--8.8.zip
```
