### ISSUE TITLE
Recent migration from homebrew-gui has broken/downgraded Inkscape

### ISSUE THREAD

**Issue by julianrendell** [caskroom/homebrew-cask#29460]
I had successfully installed Inkscape 0.92 using Homebrew ~1.5 weeks ago.

Did a brew update, and the package was forcefully migrated to the cask version, which is older, missing features, and has some issues that were fixed in 0.92.

This change has been *destructive* to my system and my workflow.

What's worse, the brew files are no longer available...

Is there an ETA for a 0.92 version of the cask?

**Comment by vitorgalvao** [comment]
You need to ask them, not us. We can only install it when they provide a compiled download, which does not seem to be the case right now.

If you find a (**official**) link, [submit it](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by julianrendell** [comment]
The *MIGRATION* from from a source-code capable brew file top a cask-only (binary download) *IS* your responsibility.

Inkscape 0.92 compiled from source with the supplied brew file no problem.

*You* removed the brew file and have effectively removed Inkscape from the Homebrew system.

Upstream not providing a binary is a different issue to what I have raised.

I'm requesting the working build-it-from source brew file be restored.

**Comment by miccal** [comment]
@julianrendell first of, check your tone! 

Secondly, you have a fundamental misunderstanding of the difference between Home-brew and Homebrew and Homebrew-Cask, which I cannot be bothered to explain to you.

Thirdly, read these:

https://github.com/Homebrew/homebrew-core/pull/9355

https://github.com/Homebrew/homebrew-core/issues/9316

https://github.com/Homebrew/homebrew-gui/issues/53

**Comment by vitorgalvao** [comment]
@julian-poidevin I’ll add the small note that you must really read [this comment](https://github.com/Homebrew/homebrew-core/issues/9316#issuecomment-275924031) (from one of @miccal’s links).

I hope it’s clear *we* (as you liked to emphasise) do not, under any circumstance, owe you anything. When I encounter an entitled attitude, I always remember [this comment](https://github.com/wpeterson/emoji/issues/23#issuecomment-63175206). It’s not our responsibility to cater to your desires. If anything, it’s our responsibility to not succumb to the whims of entitled users, burnout, and stop being useful to everybody else.

And I’ll mention again what I tend to: it’s telling (and bit depressing) how the most entitled users are overwhelmingly the ones that have never contributed to the project before — either with code or by participating in discussions — and have a github contribution graph with only a handful of contributions (if any) in total.

I won’t block you from this repository. Anyone can have a bad day, and it’s important to realise that. But I will ask that you do not make me regret this decision, ensuring the next time you intervene you respect that on the other side of your words there are people.

Finally, if you want the formula as it was before, get it and host it in your own tap. Problem solved.
