### ISSUE TITLE
Feature request: dry-run of cask zap

### ISSUE THREAD

**Issue by HazCod** [caskroom/homebrew-cask#29480]
### Description of feature/enhancement

 ~~Functionality comparable to AppCleaner: this searches the filesystem for directories with the same name/containing the application name, and offers to remove them for you when deleting the app. ~~

Seems like `brew cask zap` does this. I would like a dry run option.

### Justification

Need to see what directories will be removed.

### Example use case

```
$ brew cask zap openarena --dry-run
/Library/openarena-8.8/
/Applications/openarena.app/
```

**Comment by miccal** [comment]
You can already inspect what files `zap` will remove by looking at the Cask itself. Note that [openarena.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/openarena.rb) does not actually have a `zap` stanza.

Note that `zap` _does not_ search and delete, it needs to be added to the Cask. See [dropbox.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/dropbox.rb) for an example.

**Comment by vitorgalvao** [comment]
`brew cask cat {{cask-name}}` or `brew cask _stanza --yaml zap {{cask-name}}`.

`zap` doesn’t only delete things; it can do everything `uninstall` does.
