### ISSUE TITLE
Cask request: [Cocos]

### ISSUE THREAD

**Issue by inazou** [caskroom/homebrew-cask#29488]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Cocos

Homepage: http://www.cocos2d-x.org/

Download URL: http://cocos2d-x.org/filedown/CocosForMac-v3.10.dmg

Description: Cocos is a free and professional game-development toolkit, that enables developers to quickly create game content and remove the tedious work by simplifying it with straightforward GUI editors.

Cocos includes: the Cocos2d-x game engine, a game development environment and project management tool. With this suite, developers can focus on their roles and enjoy a better streamlined workflow. This saves game studios time and money by allowing them to collaborate with ease, and focus on what they do best to achieve better quality and faster turnaround time.

**Comment by miccal** [comment]
Is this the same thing or an update to the existing Casks [cocos-code-ide.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cocos-code-ide.rb) or [cocoscreator.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cocoscreator.rb)?

**Comment by inazou** [comment]
This is something different. Please see this page. http://www.cocos2d-x.org/products

**Comment by miccal** [comment]
@inazou thanks for that - I do not see a mention of [cocos-code-ide.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cocos-code-ide.rb), do you know if this is deprecated?

In regards to your request, the file you linked `CocosForMac-v3.10.dmg` contains an `Installer.app`, which means this Cask will require an `installer :manual` artifact, which means it will also require an [`uninstall`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-is-required-for-casks-that-install-a-pkg-or-installer-manual) stanza. My testing machine is unavailable at the moment, so if you are familiar with this app are you able to shed any light on how to uninstall it; for example is there an uninstall `.app` or an uninstall `script`?
