### ISSUE TITLE
Help - running `brew cask style` fails to build/install rubocop-cask native extensions

### ISSUE THREAD

**Issue by tallpsmith** [caskroom/homebrew-cask#29587]
I recognize in advance that what I'm facing is almost certainly a local environment issue for me, but I've run out of options.  I've tried some local Ruby experts here, but no-one can work out why this does not work for me. I've read as much as I can about `homebrew-cask` around contributing a new Cask.  I've successfully created a new fork+branch to add a cask for PCP (see [1] below).

`brew cask audit Casks/pcp.rb` passes ok, which is good. However, `brew cask style Casks/pcp.rb` fails to install `rubocop-cask' gem:

```
[ homebrew-cask ](master)$ brew cask style Casks/pcp.rb
==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
ERROR:  Error installing rubocop-cask:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby mkrf_conf.rb

"/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby" -rubygems /Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1/lib RUBYLIBDIR=/Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1/lib
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: No such file or directory -- /Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/bin/rake (LoadError)


Gem files will remain installed in /Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1 for inspection.
Results logged to /Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1/ext/gem_make.out
Error: Failed to install/update the 'rubocop-cask' gem.
```

It appears that my underlying system Ruby isn't able to install these gems for some reason.  I _do_ use `rbenv` but I'm pretty confident that Homebrew is _not_ being influenced by `rbenv` at all.  I've tried setting/removing `rbenv global|local|shell` to more modern Ruby versions but I don't get any further.  It does appear to always refer back to the underlying mac OS System Ruby (which I believe is what you'd expect).

I'm not sure what has happened to my environment to pollute it, so if anyone has any pointers I would appreciate it.

I have captured my `brew cask doctor` state in this gist:  https://gist.github.com/tallpsmith/7a065a723895ae1a59d1a85af765f4ff

---
[1] - My new Cask (only 1 commit so far) - https://github.com/tallpsmith/homebrew-cask/commit/8bb88ddc1c191780f1c49b7fd2d2d4a453c6287c

**Comment by miccal** [comment]
The first thing I notice is that the first entry in your $PATH is `/Users/psmith/.rbenv/shims` - perhaps that has something to do with the error you are experiencing?

**Comment by vitorgalvao** [comment]
What about `brew style` does it work?

Keep in mind that, as you notice, this isn’t an issue with HB, so we may not waste too much time on it. We have extremely limited resources.

**Comment by tallpsmith** [comment]
@vitorgalvao `brew style` fails with practically the same output:

```[ homebrew-cask ](master)$ brew style
==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby mkrf_conf.rb

"/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby" -rubygems /Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1/lib RUBYLIBDIR=/Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1/lib
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: No such file or directory -- /Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/bin/rake (LoadError)


Gem files will remain installed in /Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1 for inspection.
Results logged to /Users/psmith/.gem/ruby/2.0.0/gems/rainbow-2.2.1/ext/gem_make.out
Error: Failed to install/update the 'rubocop' gem.```

:( I will try removing the `rbenv` path shims that @miccal mentioned above.

**Comment by tallpsmith** [comment]
@miccal removing the `rbenv` shim `PATH` segment seems to have no effect either, still errors the same.  Additionally it looks like from the error message that the System Ruby is being used based on the path.

It feels like the System Ruby gem path hasn't got `rake` installed, but I can't even work out manually how to install that...

**Comment by miccal** [comment]
@tallpsmith OK, since `brew style` also fails it might be worth submissions this issue to [homebrew](https://github.com/Homebrew/brew).

**Comment by tallpsmith** [comment]
some progress, I _swear_ I tried this yesterday, but perhaps there was some combination of `rbenv` still going on (perhaps at the `rbenv global` level), but I have managed to manually install rake using the System ruby manually by:

```sudo gem install rake```

Perhaps dues to macOS System Integrity Protection (SIP) requiring `sudo` to install that in the System ruby area.

Now `brew style` works, but `brew cask style` fails with a different error.  

```[ ~ ]$ brew cask style
==> Installing or updating 'rubocop-cask' gem
Fetching: rubocop-cask-0.10.6.gem (100%)
Successfully installed rubocop-cask-0.10.6
1 gem installed
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- public_suffix (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-cask-0.10.6/lib/rubocop/cop/cask/homepage_matches_url.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-cask-0.10.6/lib/rubocop-cask.rb:15:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-0.45.0/lib/rubocop/options.rb:56:in `block (2 levels) in define_options'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-0.45.0/lib/rubocop/options.rb:163:in `block in option'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `block in parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1345:in `order!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1437:in `permute!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1459:in `parse!'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-0.45.0/lib/rubocop/options.rb:19:in `parse'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-0.45.0/lib/rubocop/cli.rb:23:in `run'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-0.45.0/bin/rubocop:13:in `block in <top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
	from /Users/psmith/.gem/ruby/2.0.0/gems/rubocop-0.45.0/bin/rubocop:12:in `<top (required)>'
	from /Users/psmith/.gem/ruby/2.0.0/bin/rubocop:23:in `load'
	from /Users/psmith/.gem/ruby/2.0.0/bin/rubocop:23:in ````

I'll keep hacking now I've made some progress, appreciate the eyeballs guys.

**Comment by tallpsmith** [comment]
ok, I think I've got it now.  I uninstalled a version of `public_suffix` from my System Ruby with `sudo gem uninstall public_suffix rubocop-cask` and then manually installed with `sudo gem install public_suffix` and now the `style` command works!

[ homebrew-cask ](pcp)$ sudo gem install public_suffix
Password:
Fetching: public_suffix-2.0.5.gem (100%)
Successfully installed public_suffix-2.0.5
Parsing documentation for public_suffix-2.0.5
Installing ri documentation for public_suffix-2.0.5
1 gem installed
[ homebrew-cask ](pcp)$ brew cask style Casks/pcp.rb
==> Installing or updating 'rubocop-cask' gem
Fetching: rubocop-cask-0.10.6.gem (100%)
Successfully installed rubocop-cask-0.10.6
1 gem installed
== Casks/pcp.rb ==
C: 12:  1: Extra blank line detected.
C: 13:  5: Annotation keywords like TODO should be all upper case, followed by a colon, and a space, then a note describing the problem.
C: 13:145: Trailing whitespace detected.
C: 14: 16: Space inside square brackets detected.
C: 14: 44: Space inside square brackets detected.
C: 15:  1: stanza groups should be separated by a single empty line
C: 15:  1: Trailing whitespace detected.

1 file inspected, 7 offenses detected
Error: style check failed

**Comment by tallpsmith** [comment]
So, in summary for anyone else batting at home that runs into this:

* Check your system Ruby - confirm `rbenv` is not affecting things with a `rbenv global` environment.  
* `sudo gem uninstall rake public_suffix` - just in case..
* `sudo gem install rake public_suffix`
* `brew cask style` - should now install `rubocop-cask` correctly and then you're in business.

hope that helps someone else one day... *phew*  Thanks for all those that took the time to read & help, appreciate it.

**Comment by miccal** [comment]
Glad you got it sorted @tallpsmith.
