### ISSUE TITLE
paragon-ntfs fails to uninstall

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#29588]
This cask need to be installed manually via app `/usr/local/Caskroom/paragon-ntfs/14/FSInstaller.app/`. But I had decided to not install and now it fails to 
uninstall because cask calls another app to uninstall it. I think the uninstall script should check if this app is **really** installed before trying to uninstall it 
```
$ cask uninstall paragon-ntfs
==> Running uninstall process for paragon-ntfs; your password may be necessary
==> Removing launchctl service com.paragon.ntfs*
==> Removing launchctl service com.paragon.updater
==> Running uninstall script Uninstall.app/Contents/Resources/uninstallNTFS.sh
==> No receipt for 'com.paragon-software.filesystems.NTFS.pkg' found at '/'.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- #<Pathname:/usr/local/Caskroom/paragon-ntfs/14/Uninstall.app/Contents/Resources/uninstallNTFS.sh>

==> Standard Output of failed command:


==> Standard Error of failed command:
No receipt for 'com.paragon-software.filesystems.NTFS.pkg' found at '/'.


==> Exit status of failed command:
#<Process::Status: pid 5879 exit 1>
```

**Comment by miccal** [comment]
I assume that this is related to [`brew cask list` being broken](https://github.com/caskroom/homebrew-cask/issues/14058).

**Comment by vitorgalvao** [comment]
@yurikoles Do it with `--force`. It’s there precisely for cases like this.

There’s no reasonable way to check if an `installer manual:` cask is really installed.

**Comment by yurikoles** [comment]
@vitorgalvao thank you for your suggestion, I didn't know about that flag for `uninstall`. But unfortunately it didn't work. Please reopen.

**Comment by vitorgalvao** [comment]
> But unfortunately it didn't work.

What’s the output? And does it show in `brew cask list`?

**Comment by yurikoles** [comment]
@vitorgalvao sorry for confusing, I meant that error is the same. And yes, it listed there.

**Comment by vitorgalvao** [comment]
What if you delete the directory in `$(brew --prefix)/Caskroom/paragon-ntfs`?

**Comment by yurikoles** [comment]
It solves the problem, but I feel weird doing such intrusion.
