### ISSUE TITLE
Cask request: Audacity

### ISSUE THREAD

**Issue by IVXCVI** [caskroom/homebrew-cask#29581]
Name: Audacity

Homepage: http://www.audacityteam.org/

Download URL: https://www.fosshub.com/Audacity.html/audacity-macosx-ub-2.1.2.dmg

Description: Audacity can record live audio through a microphone or mixer, or digitize recordings from other media.

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md

> The cask is so difficult to maintain, it constantly breaks. Happened only once so far, with Audacity, because it uses fosshub as a distribution site.
