### ISSUE TITLE
sublime-text* and other formulaes have files_in_usr_local

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#29593]
It seems to be no issue now or it just with `/usr/local/bin`? That caveats was used from times when we generally did not symlink binaries to `/usr/local/bin`. Today many formulas install binaries there (#12030) and I think we can safely remove it from sublime-tex* and formulas that installs only in `/usr/local/bin` but no other places?

**Comment by vitorgalvao** [comment]
> That caveats was used from times when we generally did not symlink binaries to `/usr/local/bin`.

That was never the case. We always symlinked there by default.

**Comment by vitorgalvao** [comment]
For testing, need someone with a VM to test various casks with `files_in_usr_local` but not the ones that have just `binary`. Install them, reboot and try `brew doctor` to see if there are errors.

Good casks to test:

+ [authbuddy.rb](../blob/master/Casks/authbuddy.rb)
+ [carlson-minot.rb](../blob/master/Casks/carlson-minot.rb)
+ [clamxav.rb](../blob/master/Casks/clamxav.rb)
+ [crosspack-avr.rb](../blob/master/Casks/crosspack-avr.rb)
+ [flavours.rb](../blob/master/Casks/flavours.rb)
+ [gpgtools.rb](../blob/master/Casks/gpgtools.rb)
+ [microsoft-r-open.rb](../blob/master/Casks/microsoft-r-open.rb)
+ [prince.rb](../blob/master/Casks/prince.rb)
+ [r-app.rb](../blob/master/Casks/r-app.rb)
+ [wkhtmltopdf.rb](../blob/master/Casks/wkhtmltopdf.rb)
+ [zendserver.rb](../blob/master/Casks/zendserver.rb)

**Comment by miccal** [comment]
@vitorgalvao I installed `r-app` on a relatively clean machine. Beforehand `brew doctor` reported `Your system is ready to brew`. After installing and rebooting, running `brew doctor` outputted:
```
-bash-4.4.12- /Users/raesy [> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
```

After running `brew zap r-app` and `brew doctor` again, it reported
```
-bash-4.4.12- /Users/raesy [> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/R
  /usr/local/bin/Rscript
```

So it seems the `caveat` is still required.

**Comment by vitorgalvao** [comment]
Thank you, @miccal.

Taking care of the others in https://github.com/caskroom/homebrew-cask/pull/29623 and https://github.com/caskroom/homebrew-versions/pull/3243.

**Comment by miccal** [comment]
@vitorgalvao you do realise I only tested the one, right? I did not test them all.

**Comment by miccal** [comment]
I see, I should have looked more carefully at your PR.

I just picked one off your list that had a more-or-less complete `uninstall` and `zap` stanza to test, so I could easily clean up after.
