### ISSUE TITLE
installation of vlc in home directory requires sudo for no apparent reason

### ISSUE THREAD

**Issue by sneak** [caskroom/homebrew-cask#29600]
I install a bunch of apps into ~/Applications using cask on new system init.  Almost all of my other apps install fine but installing vlc hangs the script on a `Password:` sudo prompt.  I can't imagine any good reason why installing a video player in my home directory requires administrative access.

**Comment by miccal** [comment]
It is because the vlc Cask has a [shim script](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vlc.rb#L15#L25), which currently requires `sudo`, but this will be changed once https://github.com/Homebrew/brew/pull/1930#issuecomment-275859665 is complete.
