### ISSUE TITLE
Cask request: Remove Inkscape

### ISSUE THREAD

**Issue by julianrendell** [caskroom/homebrew-cask#29684]
### Cask details

The current [cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/inkscape.rb) version of Inkscape is very old (0.91).

There has been a recent official release of 0.92. 

Unfortunately there is not an official build available for OS X, and it doesn't look likely that there will be one for a while.

There is now a brew tap (<https://github.com/caskformula/homebrew-caskformula>) that has an updated brew file that was pulled from the now defunct homebrew-gui repo and updated to successfully compile 0.92.

I suggest this Inkscape cask is removed, and reinstated if/when a (regularly updated) binary build becomes available.

Thanks!

**Comment by miccal** [comment]
It is clear that Homebrew are not going to [reinstate Inkscape as a formula](https://github.com/Homebrew/homebrew-gui/pull/54), and I do not consider version 0.91 as "too old" to have in Cask in reference to the [rejected cask documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md), so it will not be removed. 

To quote directly @ilovezfs from https://github.com/Homebrew/homebrew-gui/pull/54:

> Your efforts are best directed at convincing upstream to reverse course on their decision to stop publishing new binaries for macOS, so that Cask can get the new version.

**Comment by vitorgalvao** [comment]
@julianrendell While you are correct we’d rather not have casks that point to old versions, they are best removed when we are sure they were never again going to provide the releases.

It’s my understanding they haven’t stopped supporting macOS builds, they’re just lower priority and hence being built later on. For now it’s just a single point release. If it does become a bigger problem in the future, we will reconsider removing it.

Thank you for the suggestion anyway, I also thought about it yesterday.

**Comment by miccal** [comment]
If you follow the discussion on the [inkscape-devel mailing list](https://sourceforge.net/p/inkscape/mailman/inkscape-devel/) it seems that the Inkscape developers are aware of the issue and there are people working on packaging a `dmg` version for 0.92.1.

**Comment by julianrendell** [comment]
Fair enough. The caskformula tap now exists, so brew/cask users can find a recent version.

For reference:

- the official release notes for 0.91 is dated 2015-01-28: https://inkscape.org/en/release/0.91/
- the last official build for OS X is dated Jan. 30, 2016: https://inkscape.org/en/release/0.91/platforms/
- the development binary builds for OS X are not from the official team, and are released via DropBox. They are 0.91 releases; last build, 9 months ago.  See https://inkscape.org/en/download/development-versions/ and https://www.dropbox.com/sh/2n7aim2wcrn6l3h/AADjQQ_484Z_Po1X3RSqa29na?dl=0
  - Aside: privately built and hosted on dropbox seems a little sketchy compared to an "official" build. Not at all suggesting the person doing the work is intending any malware or other wrong-doing, but if there is a problem, it may be harder to contact them and have the hacked binaries dropped.
- the official Mac OS X installation docs specify to use MacPorts: https://inkscape.org/en/download/mac-os/. 
  - The reference on that page to packaged installers are for MacPorts, not Inkscape.
  - There is no mention of looking for volunteers to create Mac binary builds. I read that as the Inkscape team being happy with delivery via MacPorts.
- when I've searched the inkscape-devel email list, I see a couple of users (not core-dev team) trying to figure out the packaging scripts, and making some private builds available via file sharing sites. I've seen support for the efforts, but no indication that they're actively seeking to include these builds (e.g. comments re how to integrate such a package into CI or release process, or how to get the binary hosted on Inkscape.org) I may well have missed threads that contradict what I've just written; I'm a user and don't have the capacity to follow the inkscape-devel email list; my searches may not be exhaustive.
- the 0.01 difference in versions belies a lot of new features and fixes.

**Comment by julianrendell** [comment]
Follow up, from the Inkscape dev list.

Trying to summarize, errors and inaccuracies mine: 

The MacOS packaging scripts have been "de-maintained", they don't have the people to get it working again. They're hoping someone(s) will step in and help out; possibly for inclusion in the 0.93 release which is very tentatively targeting the end of 2017. 

I read that as builds (from source) are actively maintained, but Mac binary packages have been dropped until further notice.

Ref: https://sourceforge.net/p/inkscape/mailman/inkscape-devel/thread/20170201214930.GB8691%40bryceharrington.org/#msg35641083

**Comment by MikeMcQuaid** [comment]
> I read that as builds (from source) are actively maintained, but Mac binary packages have been dropped until further notice.

I'd suggest that people who care about Inkscape on macOS consider trying to help out there. Requiring this be built from source is not a nice experience.
