### ISSUE TITLE
supply sudo pw as env var

### ISSUE THREAD

**Issue by shivno** [caskroom/homebrew-cask#29683]
To be able to use cask headless, it would be great to be able to supply the sudo pw as env var e.g, as one should not use cask as root. thanks :)

**Comment by miccal** [comment]
Storing your `sudo` password as an environment variable is incredibly insecure since the password would be stored as plain text, and as such it is something we would not recommend.

**Comment by shivno** [comment]
what about stdin? i dont know if this is readable from other processes without dtrace

**Comment by miccal** [comment]
Maybe I am not understanding what you are asking - what exactly are you trying to do?

**Comment by shivno** [comment]
Writing an non-interactive shellscript to install packages on multiple machines. Some require sudo and i see no possibility to do this at the moment. Starting brew cask as root is non-discouraged (and does not work i think).

**Comment by vitorgalvao** [comment]
@shivno `sudo` itself has `--stdin`/`-S` and `--validate`/`-v` (check the `man` page), which will work for your script.

I use the technique in [my own dotfiles repo](https://github.com/vitorgalvao/dotfiles/) to great success.

**Comment by shivno** [comment]
Ah great! sorry to spam your issue tracker then. irc was unresponsive about that. i will do that. Thanks.
