### ISSUE TITLE
vox download fails - sha256 mismatch

### ISSUE THREAD

**Issue by palerdot** [caskroom/homebrew-cask#29699]
`brew cask install fails`

Following are the details. Also **brew update** fails to fix this issue.

`==> Downloading https://dl.devmate.com/com.coppertino.Vox/Vox.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask vox
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: e7b63f52e4a2e977266a360b6a9f08a1d2f9e7e9638628d522f35d26a9548d73
Actual: 52d5bd6903675e1afc7163af36f05a231efc48804c8273a109990bf830714db3`

**Comment by miccal** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/29661.
