### ISSUE TITLE
Cask request: Anaconda 4.3

### ISSUE THREAD

**Issue by vincent-zhu** [caskroom/homebrew-cask#29736]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Anaconda

Homepage: https://www.continuum.io/

Download URL: https://repo.continuum.io/archive/Anaconda3-4.3.0-MacOSX-x86_64.sh

Description: new version for anaconda, current version of anaconda on brew cask is outdated.

**Comment by dlei** [comment]
why is it requiring password to install anaconda? it shouldn't require sudo isn't it? 

Password:
