### ISSUE TITLE
Inclusion of Firefox Unbranded Versions

### ISSUE THREAD

**Issue by SainteCelery** [caskroom/homebrew-cask#29750]
Can the unbranded builds of firefox be included in the upcoming Firefox subfolder (or however versions are going to be handled now)?

Official links to unbranded, unbranded beta, treeherder & treehearder beta releases - https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds

**Comment by vitorgalvao** [comment]
> upcoming Firefox subfolder (or however versions are going to be handled now)?

You’re confusing this (Homebrew-Cask) with Homebrew. We haven’t changed our versioning methodology as of yet.

To be blunt, I don’t see much point/demand in adding those casks. Those are for such specific cases, they’re not worth the overhead and seem better suited for a tap.
