### ISSUE TITLE
`brew cask uninstall --force` should also clean file associated with the given distributions from the download cache

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#29805]
Refs only remaining item in https://github.com/caskroom/homebrew-cask/issues/7571.

**Comment by reitermarkus** [comment]
I am actually against this behaviour. I can already see myself running into something like this:

- uninstall stage fails in `brew cask reinstall some-huge-cask`
- try `brew cask uninstall --force some-huge-cask`
- `brew cask install some-huge-cask` now re-downloads the whole thing

**Comment by vitorgalvao** [comment]
@reitermarkus Agreed.
