### ISSUE TITLE
Link/unlink support

### ISSUE THREAD

**Issue by szekelyisz** [caskroom/homebrew-cask#29870]
### Description of feature/enhancement

Please provide a link/unlink feature similar to that in Homebrew.

### Justification

These commands are critical when different versions of the same software are required to coexist. One can always uninstall the version not needed at the moment, but this is not very elegant and as Cask doesn't cache downloads, it makes switching impossible when one's offline.

### Example use case

As an embedded software developer I need both `px4/px4/gcc-arm-none-eabi-49` and `Caskroom/cask/gcc-arm-embedded` installed (which both provide `/usr/local/bin/arm-none-eabi-gcc`, for example) since different microcontrollers require different versions of GCC to compile firmware. If these commands were implemented, I could just `brew cask unlink gcc-arm-embedded` followed by `brew link gcc-arm-none-eabi-49` or the other way around to switch.

**Comment by vitorgalvao** [comment]
We used to link. It doesn’t work and only leads to problems. Also, most users prefer it this way.

https://github.com/caskroom/homebrew-cask/issues/13201.
