### ISSUE TITLE
Uninstall cask report the cask is not installed while it is

### ISSUE THREAD

**Issue by ngocphamm** [caskroom/homebrew-cask#2988]
This is the commands and its output

```bash
~ ❯❯❯  brew cask list
...omitted...
launchrocket
...omitted...
~ ❯❯❯  brew cask uninstall launchrocket
Error: launchrocket is not installed
~ ❯❯❯  brew cask edit launchrocket
```

That's I cannot uninstall and reinstall to update `launchrocket` to its latest release.

**Comment by smackesey** [comment]
+1. Just ran into this with `fantastical` package.

**Comment by myoung34** [comment]
This is still an issue for me as well. ``--force`` works, but I didn't know until I came here.

**Comment by vitorgalvao** [comment]
No need to keep bumping the issue. We know it still happens, that’s why it is still open. Bumping it won’t make it happen faster. PRs are very much welcome.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/14058.
