### ISSUE TITLE
--binary-only or --artifact-include= flags

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#2992]
Per the discussion in #2921, since Casks can support multiple artifacts of different types, it would be desirable to give the user a way to control which artifacts are installed.

Currently we have a `--no-binaries` option.  This could perhaps be generalized to `--artifact-include=` and `--artifact-exclude=`.

The use-case discussed in #2921 is: installing only symlinks to executables (`binary` artifact) when the App itself is already installed via the App Store.  For that particular use-case, the `binary` artifact would also need to be extended to check multiple locations for the symlink source.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation.
