### ISSUE TITLE
caskroom.io blocked by ASUS Routers

### ISSUE THREAD

**Issue by Sevyls** [caskroom/homebrew-cask#29947]
Hi,

I am using an ASUS Router - why is it telling me that you're website is containing malware?
It builds upon TrendMicro Malware Databases. 

``Malicious Domain or website, Domains that host malicious payloads.``

![image](https://cloud.githubusercontent.com/assets/547842/22746577/7dc6aeb2-ee24-11e6-821c-5c8b3c7dbf2d.png)

KR Michael

**Comment by vitorgalvao** [comment]
Thank you, @Sevyls. Are you going to https://caskroom.github.io/ or https://caskroom.io/? Does it show the same thing on both?

What about other github-hosted pages, do they work fine? Try https://awvessel.github.io/ or https://unetbootin.github.io/.

**Comment by Sevyls** [comment]
the github pages are fine, thanks!

**Comment by vitorgalvao** [comment]
Pinging @phinze. You might want to check this with the domain name provider.

**Comment by ihorzenich** [comment]
The same problem for https://caskroom.io/ but not for https://caskroom.github.io/
Can't access it at work with message "This domain is blocked due to a security threat". 

Our IT Security team said:
> Cisco umbrella is categorized as malware and it is blocked.
> I propose to inform the owner of this website to check his asset for malware because their site is categorized of Cisco OpenDNS as malware.
![image008](https://cloud.githubusercontent.com/assets/1684521/23308806/099799c8-fab5-11e6-830a-375266ec8a98.jpg)

**Comment by phinze** [comment]
@vitorgalvao Seems like caskroom.io is causing more trouble than it's worth... perhaps we should just retire it and make caskroom.github.io the official website?

**Comment by vitorgalvao** [comment]
@phinze I was thinking the same. Let’s do it.
