### ISSUE TITLE
Test drive CircleCI

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#29995]
Travis CI has had a great run but seems to be lagging fairly regularly recently.

Maybe it's time to switch CI providers? (or revisit our build/test scripts)

**Comment by reitermarkus** [comment]
> or revisit our build/test scripts

Not really the problem here I think. The problem is that the backlog peaks at a ratio > 10, wich pretty much takes half a day to clear up.

I even wrote a script to check if it's worth waiting for a PR to be tested. 😂 

```bash
$ ./travis-backlog 
✅  128.0 active / 21.0 scheduled (0.1640625)
```

**Comment by miccal** [comment]
I have always wondered why the maximum is set at 128 builds for macOS, but the maximum number of linux builds is _huge_.

**Comment by miccal** [comment]
> I even wrote a script to check if it's worth waiting for a PR to be tested.

@reitermarkus would you mind sharing your script?

**Comment by reitermarkus** [comment]
```ruby
#!/usr/bin/env ruby

require 'json'
require 'open-uri'
require 'uri'

OSX_BUILDS = 'https://www.traviscistatus.com/metrics-display/tkg1p3c6qg8x/day.json'.freeze
OSX_BACKLOG= 'https://www.traviscistatus.com/metrics-display/7cl94r33fvsg/day.json'.freeze

builds = JSON.parse(open(URI(OSX_BUILDS)).read)
backlog = JSON.parse(open(URI(OSX_BACKLOG)).read)

h = {}

builds['metrics'][0]['data'].each do |d|
  h[d["timestamp"]] = {
    builds: d["value"].to_f
  }
end

backlog['metrics'][0]['data'].each do |d|
  h[d["timestamp"]] ||= {}
  h[d["timestamp"]][:backlog] = d["value"].to_f
end

h = h.select { |k, v|
  v.key?(:builds) && v.key?(:backlog)
}

latest = h[h.keys.sort.last]

ratio = latest[:backlog]/latest[:builds]

symbol = case ratio
when 0...1.0
  "✅"
when 1...2
  "⚠️"
else
  "🛑"
end

puts "#{symbol}  #{latest[:builds]} active / #{latest[:backlog]} scheduled (#{ratio})"

```

**Comment by adidalal** [comment]
I'm going to try to reach out to CircleCI this weekend.
https://circleci.com/pricing/#faq-section-os-x

**Comment by miccal** [comment]
@adidalal it seems [Linuxbrew uses CircleCI](https://github.com/Linuxbrew/brew/wiki/Continuous-Integration) - perhaps the [maintainers of Linuxbrew](https://github.com/Linuxbrew/brew#who-are-you) can offer some advice.

**Comment by adidalal** [comment]
@vitorgalvao Can you authorize CircleCI for caskroom "Organization Access"?

**Comment by vitorgalvao** [comment]
@adidalal Done. I’m guessing you already contacted them, then.

**Comment by adidalal** [comment]
Got a response - they're happy to set us up with a trial run of containers to check out performance.
Will try to put it on my plate for next weekend or the one after.
(Though, if someone else is interested and available, happy to pass along contact info)

**Comment by reitermarkus** [comment]
FYI, not sure since when, but seems like Travis now has 205 macOS machines.

**Comment by miccal** [comment]
> FYI, not sure since when, but seems like Travis now has 205 macOS machines.

Yes, happened in the last 48 hours.

**Comment by vitorgalvao** [comment]
> FYI, not sure since when, but seems like Travis now has 205 macOS machines.

Not sure they added more since your last comment, but they’re up to 224, now (found out initially due to your script).

And just now I was reading up to make a Twitter bot to post the ratio every hour! Saved some work.

**Comment by vitorgalvao** [comment]
Anyone opposed to closing this and removing CircleCI, and reopening/readding if we get into trouble again?

**Comment by adidalal** [comment]
Yeah that's fine!

**Comment by reitermarkus** [comment]
> And just now I was reading up to make a Twitter bot to post the ratio every hour!

Would have loved to see that. 😂
