### ISSUE TITLE
Source not there and cannot find it: jaspersoft-studio

### ISSUE THREAD

**Issue by ubermanl** [caskroom/homebrew-cask#30044]
[`jaspersoft-studio`]( homebrew-cask/Casks/jaspersoft-studio.rb).

`It seems the App source is not there: '/usr/local/Caskroom/jaspersoft-studio/6.3.1/Jaspersoft Studio 6.3.1.final.app'`

It fails to install because it's looking for an app in '/usr/local/Caskroom/jaspersoft-studio/6.3.1/Jaspersoft Studio 6.3.1.final.app' which has been renamed to TIBCO Jaspersoft Studio 6.3.1.final.app so following the tutorials on this subject i came up with the following:

brew cask edit jaspersoft-studio 

and changed the line:
`app "Jaspersoft Studio #{version}.final.app"`

to
`app "TIBCO Jaspersoft Studio #{version}.final.app"`

and now it works.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/30045
