### ISSUE TITLE
animated-gif-quicklook?

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#30099]
Using cask `animated-gif-quicklook` (version 1, installed weeks ago under macOS 10.12.3) I just observed that I get not animation at all when previewing an animated GIF with quicklook.

On the opposite, this official Apple web page of september 2016 claims that standard quicklook already displays animated GIF: [see here](https://support.apple.com/kb/PH20212?locale=en_US)

And indeed, it works natively after removing the cask: `brew cask zap animated-gif-quicklook`.

Is this version really working? (otherwise could be dismissed)
Is this software only suitable for older macOS versions? (if yes, it would be great if the cask formula could prevent the install).

**Comment by miccal** [comment]
It seems macOS has had a native .gif quicklook since Mavericks - might be best to remove this Cask.

**Comment by SainteCelery** [comment]
I noticed the same thing yesterday, @Yann-R.

**Comment by vitorgalvao** [comment]
Yes, this is only for old macOS versions. It even says so on the page. It’s pretty old, no no problem with removal.

**Comment by Yann-R** [comment]
Yes, it's written on the page, but since the last update was in 2014, it was not so clear that it was useless for a newer macOS (until I discover that now the Finder natively supports animated GIF, Apple said).

see https://sourceforge.net/projects/animgifqlgen/
> Last Update: 2014-12-17
> Description
> 
> This is a QuickLook plugin for MacOS-X 10.5/10.6 that allows QuickLook preview of Animated GIFs. The current GIF support in the Finder doesn't show animations. This plugin extends the Finder to allow QuickLook to display the GIF in its animated form.

Better to delete it indeed 👍
