### ISSUE TITLE
Cask request: Paste

### ISSUE THREAD

**Issue by sholladay** [caskroom/homebrew-cask#30149]
### Cask details

Name: Paste

Homepage: http://pasteapp.me/

Download URL: http://pasteapp.me/trial

Description: Smart and beautiful clipboard manager, with search and unlimited history.

**Comment by adidalal** [comment]
That download is only a trial, and there's no easily visible store to buy the full version from (haven't run the app, if there's some in-app purchase capability please post a screenshot and we can reopen).
So it looks like this app is MAS only and thus can't be added.

**Comment by sholladay** [comment]
Hi @adidalal, this app can be purchased and run completely without the Mac App Store. Its trial is a feature-complete full trial and doesn't even need email sign up. The binary is the same, it simply unlocks post-trial. Its activation process is very easy, can't post screenshots because I'd have to wait a week (can't activate early).

You have casks like `ableton-live` that are very expensive and don't have in-app purchase capability. In both cases, the purchase process is pretty easy, however. In Ableton's case, you activate it with a license key that you acquire through their website.

**Comment by sholladay** [comment]
Thanks all! This is one of my favorite apps ever, I think it's a great addition.
