### ISSUE TITLE
Cask tokens on the CLI should be lowercased before being interpreted by the commands

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#30140]
Refs https://github.com/caskroom/homebrew-cask/issues/10240 and https://github.com/caskroom/homebrew-cask/issues/30136.

Those are pertaining to `install` and `info`, but all commands should be case-insensitive.

**Comment by reitermarkus** [comment]
This has been implemented as a by-product of my Cask-loading refactoring.
