### ISSUE TITLE
Moving App  Applications folder

### ISSUE THREAD

**Issue by valeriyvan** [caskroom/homebrew-cask#30184]
brew cask install sqlitebrowser
...
>==> Moving App 'DB Browser for SQLite.app' to '/Applications/DB Browser for SQLite.app'
>Error: Permission denied - (/usr/local/Caskroom/sqlitebrowser/3.9.1v2/DB Browser for SQLite.app, /Applications/DB Browser for SQLite.app)

On my believe attempt to write to Applications folder is fundamental design flaw as it needs administrator rights. `brew` designed not to need administrator rights whenever  `brew cask install sqlitebrowser` need this rights to accomplish.

**Comment by vitorgalvao** [comment]
No, it is not a design flaw. Homebrew and Homebrew-Cask have different needs. We used to link to `~/Applications` and it sucked. A ton of apps would not work that way. Also, most users prefer it to work this way. The fact you don’t like it doesn’t make it wrong.

There are a buttload of issues on this, including #13201.

To change where it moves to, use [`--appdir`](https://github.com/caskroom/homebrew-cask/blob/4bd79034e22913bb988a5fdd6ae8b511e37da556/USAGE.md#options).
