### ISSUE TITLE
How to check whether the homebrew-cask is installed on my computer?

### ISSUE THREAD

**Issue by DeveloperLx** [caskroom/homebrew-cask#30181]
Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) or [making requests](https://github.com/caskroom/homebrew-cask#requests), as appropriate. Note the former has several links to help diagnose and fix common issues.

If none of those guides is appropriate, delete this template and explain your issue in detail.

Please note that **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**. Dealing with the same solved and documented problems leads to maintainer burnout and wasted hours. Those would be better spent improving Homebrew-Cask itself and fixing real bugs.

If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

Thank you for taking the time to make a correct report. The whole team appreciates it.

**Comment by vitorgalvao** [comment]
Homebrew-Cask is now a close part of Homebrew’s core. You have one, you have the other. It downloads on demand the taps and runs the commands it needs to be setup the first time you run any `brew cask` command.

Next time please read the template and substitute it for your message.
