### ISSUE TITLE
mGBA cask broken: invalid file downloaded

### ISSUE THREAD

**Issue by smileytechguy** [caskroom/homebrew-cask#30191]
I followed the instructions in the bug reporting guide, to no avail.

Here is what I get: 

```bash
$ cask install mgba
==> Downloading https://github.com/mgba-emu/mgba/releases/download/0.5.2/mGBA-0.
######################################################################## 100.0%
==> Verifying checksum for Cask mgba
Error: It seems the App source is not there: '/usr/local/Caskroom/mgba/0.5.2/mGBA-0.5.2--osx/mGBA.app'
Error: nothing to install
```

Looking in /usr/local/Caskroom/mgba/0.5.2/ is a 12.5 mb invalid .xz file which "extracts" into a cpgz

**Comment by miccal** [comment]
I can confirm this issue - downloading the `tar.xz` manually and decompressing gives a `tar.xz.cpgz` file, leading to an endless loop of `tar.xz` to `tar.xz.cpgz` - this is usually an indication of a corrupt file, and may need to be reported upstream.
