### ISSUE TITLE
install sketchup fail because outdated (sha265 mismatch)

### ISSUE THREAD

**Issue by clakech** [caskroom/homebrew-cask#30199]
brew cask install sketchup
==> Downloading https://dl.trimble.com/sketchup/SketchUpMake-en.dmg
######################################################################## 100,0%
==> Verifying checksum for Cask sketchup
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: a61e7e55b42e8d2e4735c4e45f0d53435c8dfd4f6aaca7187b4f945a58acc858
Actual: 9a515fac2a3a4c0d32c90c2570e887395ae5c79511310d183624f24a6e436efa
File: /Users/cyril.lakech/Library/Caches/Homebrew/Cask/sketchup--2017.dmg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

[It’s right there](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#sha256-mismatch-error). Next time, please follow it.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/30201
