### ISSUE TITLE
broken cask, Kindle for Mac cannot be installed

### ISSUE THREAD

**Issue by agh** [caskroom/homebrew-cask#30244]
Looks like Amazon has moved this and it is no longer possible to install, should this be updated to point at a new URL or possibly removed?

```
boo:~ agh$ brew cask install kindle
==> Downloading http://kindleformac.amazon.com/46083/KindleForMac-46083.dmg

curl: (6) Could not resolve host: kindleformac.amazon.com
Error: Download failed on Cask 'kindle' with message: Download failed: http://kindleformac.amazon.com/46083/KindleForMac-46083.dmg
The incomplete download is cached at /Users/agh/Library/Caches/Homebrew/Cask/kindle--46083.dmg.incomplete
Error: nothing to install
```

**Comment by agh** [comment]
Appears to have moved to -

> https://s3.amazonaws.com/kindleformac/46083/KindleForMac-46083.dmg

**Comment by agh** [comment]
Closing out, please review the Pull Request which fixes this. 👍

**Comment by Dimpagger** [comment]
brew cask install kindle
==> Downloading https://s3.amazonaws.com/kindleformac/46083/KindleForMac-46083.dmg

curl: (7) Failed to connect to s3.amazonaws.com port 443: Operation timed out
Error: Download failed on Cask 'kindle' with message: Download failed: https://s3.amazonaws.com/kindleformac/46083/KindleForMac-46083.dmg
The incomplete download is cached at /Users/dingpeng/Library/Caches/Homebrew/Cask/kindle--46083.dmg.incomplete
Error: nothing to install

**Comment by gobinathm** [comment]
@Dimpagger Guess its a network issue from your side. This works.
```
==> Downloading external files for Cask ./kindle.rb
==> Downloading https://s3.amazonaws.com/kindleformac/46083/KindleForMac-46083.dmg
######################################################################## 100.0%
==> No checksum defined for Cask kindle, skipping verification
==> Success! Downloaded to -> /Users/gobinathm/Library/Caches/Homebrew/Cask/kindle--46083.dmg
```
