### ISSUE TITLE
glob expansion in `zap :delete` and `uninstall :delete`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#30256]
Done in https://github.com/Homebrew/brew/pull/2042. We now need to:

- [x] Add it to the documentation.
- [x] Add it to casks (many have it in a commented TODO).

**Comment by miccal** [comment]
Hello @vitorgalvao I would like to get stuck into this, but I am not 100 % certain what is required.

For example, looking at the [balsamiq-mockups Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/balsamiq-mockups.rb), it what you have on mind as simple as it states?

Finally, would it be better to have glob expansions everywhere where possible, like in an `uninstall :pkgutil` for example?

**Comment by vitorgalvao** [comment]
> I would like to get stuck into this, but I am not 100 % certain what is required.

You mean you want to get assigned? Done. You should also be able to self-assign (or unassign) with the options to the right of the conversation.

> For example, looking at the [balsamiq-mockups Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/balsamiq-mockups.rb), is what you have on mind as simple as it states in the commented TODO?

Yes. In those cases, removing the `# TODO: expand/glob for ` should suffice.

> Finally, would it be better to have glob expansions everywhere where possible, like in an `uninstall :pkgutil` for example?

No. If we can accurately pinpoint the files and there’s only a few of them, we should spell them out. When there are too many/we don’t know them all *and* we can target them specifically with a glob, without catching what we shouldn’t, we use the glob.

**Comment by miccal** [comment]
@vitorgalvao all done except for the [hipchat Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/hipchat.rb), which states:
```
# TODO: expand/glob for '~/Library/<userid>/HipChat/'
```
I am not sure this makes sense?

**Comment by vitorgalvao** [comment]
@miccal `'~/Library/*/HipChat/'` might work, but it’d have to be tested.

**Comment by miccal** [comment]
@vitorgalvao thanks for that - I do not have a testing machine at the moment, but I can test it in a few days.

**Comment by neutric** [comment]
```
# TODO: expand/glob for '~/Library/<userid>/HipChat/'
```
does not make sense to me either. These files were present after installing, starting, but not really doing anything, and then stopping HipChat:
```bash
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hipchat.hipchat.sfl
~/Library/Application Support/com.hipchat.HipChat
~/Library/Caches/com.crashlytics.data/com.hipchat.HipChat
~/Library/Caches/com.hipchat.HipChat
~/Library/Caches/Homebrew/Cask/hipchat--4.29.0-732.zip
~/Library/Logs/HipChat
~/Library/Preferences/com.hipchat.HipChat.plist
```

While `'~/Library/*/HipChat/'` works fine (removes e.g. `~/Library/Logs/HipChat`, which I had removed from the zaplist before testing), it is not needed.

**Comment by miccal** [comment]
@neutric by "stopping" to you mean just quitting the app, for something more? 

Do you mean that `~/Library/<userid>/HipChat/` was created while the app is running, and deleted when stopped?

**Comment by neutric** [comment]
By stopping I mean quitting, yes. What I wanted to say is that all I did was install, start the app so it can create its files, and then quit it. It is possible that more files are created once you really use the app, which I didn't. Then I searched with `find . -iname "*hipchat*"` which produced the above list of files. Nothing that matches `~/Library/<userid>/HipChat/`, so a `'~/Library/*/HipChat/'` in the zap list is probably not necessary.

**Comment by miccal** [comment]
Ah OK - I guess that the `<userid>` is a user's login name. You did not create an account and log into the app, I assume?

**Comment by neutric** [comment]
Correct. But why on earth would it create a folder `<userid>/HipChat/` under `~/Library`? `HipChat/<userid>` would make sense to me, but the other way around?

**Comment by vitorgalvao** [comment]
> But why on earth would it create a folder `<userid>/HipChat/` under `~/Library/`? 

Bad design?

**Comment by neutric** [comment]
-.-

**Comment by miccal** [comment]
I can conform @neutric's finding - there is no `~/Library/<userid>/HipChat/` created when installing, and creating a login is too complicated.

@Tenzer, @chaseroden, @cliffcotino you have all updated this Cask in the past - are you able to shed any light on this?

**Comment by Tenzer** [comment]
```
[jeppe@reventon ~/Library]$ find . -iname '*hipchat*'
./Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hipchat.hipchat.sfl
./Application Support/com.hipchat.HipChat
./Application Support/Google/Chrome/Default/Local Storage/<website>_0.localstorage
./Application Support/Google/Chrome/Default/Local Storage/<website>_0.localstorage-journal
./Caches/com.apple.nsurlsessiond/Downloads/com.hipchat.HipChat
./Caches/com.crashlytics.data/com.hipchat.HipChat
./Caches/com.hipchat.HipChat
./Caches/HipChat
./Caches/io.fabric.sdk.mac.data/com.hipchat.HipChat
./HipChat
./Logs/HipChat
./Preferences/com.hipchat.HipChat.plist
./WebKit/com.hipchat.HipChat
./WebKit/com.hipchat.HipChat/WebsiteData/LocalStorage/<website>._0.localstorage
./WebKit/com.hipchat.HipChat/WebsiteData/LocalStorage/<website>._0.localstorage-shm
./WebKit/com.hipchat.HipChat/WebsiteData/LocalStorage/<website>._0.localstorage-wal
```

Note that I have normalised the lines which contain `<website>`. They originally contained the URL of the internal, self hosted HipChat instance we use at work, and I don't want to make the hostname of that public.

**Comment by miccal** [comment]
Thank you @Tenzer for your help.

@vitorgalvao it seems that there is no glob expansion required for the hipchat Cask, so I think we can call this completed?

**Comment by vitorgalvao** [comment]
Thank you @miccal!

**Comment by miccal** [comment]
You're welcome as always @vitorgalvao.
