### ISSUE TITLE
Feature request: icon themes

### ISSUE THREAD

**Issue by dbkaplun** [caskroom/homebrew-cask#30263]
Would be great if there was a way to specify a custom theme and have applications installed via cask come with a given theme's icon, if one exists for the application. It would also retain the theme's icon if an application is updated.

[Here](https://github.com/tinalatif/flat.icns/blob/47962a806b61644c351726756bd0608c0f0d1fd0/install.sh#L13) is one implementation of such a feature, and LiteIcon (`brew cask install liteicon`) does this as well.

Thanks for considering!

**Comment by vitorgalvao** [comment]
Thank you for the request, but that’s completely out of scope for homebrew-cask. Leaving it open for a while, but I don’t see it happening.

**Comment by miccal** [comment]
I agree with @vitorgalvao - this would be something that each user would customise, and it would be wrong to implement this via Cask.

**Comment by dbkaplun** [comment]
Is there a mechanism through which this can be accomplished in homebrew-cask? Maybe via post-install hook or something similar? This is something I would like to see in homebrew-cask.

**Comment by vitorgalvao** [comment]
It might be possible with `postflight`, but you’ll have to make the casks yourself and they won’t be accepted on the main repo.
