### ISSUE TITLE
Only one cersion of nwjs

### ISSUE THREAD

**Issue by cryomi** [caskroom/homebrew-cask#30303]
File nwjs.rb has only 0.19.4 vesion, could it be updated - I can download all major versions, for ex.: 0.14.5, 0.19.5, etc?

**Comment by vitorgalvao** [comment]
We’ll only take the latest version. See [Acceptable casks policy in caskroom/versions](https://github.com/caskroom/homebrew-versions#acceptable-casks).

Being updated in #30306.
