### ISSUE TITLE
Prefer HTTPS options for downloads, or always follow the appcast?

### ISSUE THREAD

**Issue by stephenwade** [caskroom/homebrew-cask#30310]
I'm working on updating the [Forklift cask] to version 3.0.

The download URL on the [Forklift website] is HTTPS, via Amazon AWS. However, the download URL in the [appcast] is HTTP-only, via their download server.

Should we use the Amazon URL because it's HTTPS, or should we prefer to match the appcast even though it's HTTP-only?

[Forklift cask]: https://github.com/caskroom/homebrew-cask/blob/master/Casks/forklift.rb
[Forklift website]: http://binarynights.com/forklift/
[appcast]: https://updates.binarynights.com/ForkLift3/update.xml

**Comment by vitorgalvao** [comment]
Depends on the case, and there isn’t a hard rule. The first thing we should try to match is the `homepage` and `url` (make sure they are on the same domain as often as possible). So in this case it should be the HTTP one because of that.
