### ISSUE TITLE
Travis-CI erroring on all builds (Ruby no env var set)

### ISSUE THREAD

**Issue by BenjaminHCCarr** [caskroom/homebrew-cask#30357]
Rravis-CI is hosed on a #Ruby error… 
even @vitorgalvao  PR’s are erroring: https://travis-ci.org/caskroom/homebrew-cask/builds/204797539
I figure if his is going sideways everyones are…
Mine is hung up too: https://travis-ci.org/caskroom/homebrew-cask/builds/204868523

The error is along the lines of ~ `error: Ruby system; no env variable set`

**Comment by miccal** [comment]
Yes, we know.
