### ISSUE TITLE
Change all occurrences of caskroom.io in the docs

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#30361]
Let’s phase out that domain and use just caskroom.github.io. See https://github.com/caskroom/homebrew-cask/issues/29947.

**Comment by Numbermaniac** [comment]
Are there any? I checked using `grep`, and it seems the only link to caskroom.io I can find in the entire repo is [in this cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jdownloader.rb).

**Comment by vitorgalvao** [comment]
There were some minor occurrences in other repos. Was on a phone at the time so couldn’t check.

All done.

**Comment by textshell** [comment]
Just noticed while looking at the borg PR for this: The [caskroom github organisation](https://github.com/caskroom/) still points to the old url.

**Comment by vitorgalvao** [comment]
@textshell Fixed. Thank you.
