### ISSUE TITLE
Cask request: SecureCRT

### ISSUE THREAD

**Issue by xavador** [caskroom/homebrew-cask#30493]
Cask details

Name: SecureCRT

Homepage: https://www.vandyke.com/products/securecrt/index.html

Download URL: generic Link (behind an login - its possible with an trail account)

Description: “SecureCRT client for Windows, Mac, and Linux provides rock-solid terminal emulation for computing professionals, raising productivity with advanced session management and a host of ways to save time and streamline repetitive tasks. SecureCRT provides secure remote access, file transfer, and data tunneling for everyone in your organization.”.

Did someone see any chance to include this into Cask?

**Comment by miccal** [comment]
Unfortunately this is a [walled build](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds) and it cannot be added to Cask.
