### ISSUE TITLE
403 Forbidden for balsamiq-mockups

### ISSUE THREAD

**Issue by gobinathm** [caskroom/homebrew-cask#30512]
The Issue #14412 is back again 

> brew cask install balsamiq-mockups
==> Downloading https://builds.balsamiq.com/mockups-desktop/Balsamiq_Mockups_3.5.7.dmg

> curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'balsamiq-mockups' with message: Download failed: https://builds.balsamiq.com/mockups-desktop/Balsamiq_Mockups_3.5.7.dmg
The incomplete download is cached at /Users/gobinathm/Library/Caches/Homebrew/Cask/balsamiq-mockups--3.5.7.dmg.incomplete

**Comment by vitorgalvao** [comment]
Hello and welcome, @gobinathm.

Please don’t open issues if you’re going to submit the PR to fix them. It only makes for unnecessary work for everyone.
