### ISSUE TITLE
Cask request: Hearthstone

### ISSUE THREAD

**Issue by kaungst** [caskroom/homebrew-cask#30533]
### Cask details

Name: Hearthstone

Homepage: http://us.battle.net/hearthstone/en/

Download URL: https://www.battle.net/download/getInstallerForGame?os=mac&locale=enUS&version=LIVE&gameProgram=HEARTHSTONE

Description:
Popular free card game said to rival magic the gathering

**Comment by gobinathm** [comment]
@kaungst @miccal @vitorgalvao I believe we already have this [CASK](https://github.com/caskroom/homebrew-cask/blob/master/Casks/battle-net.rb)

To Confirm, indeed both the app are same I just executed a test.  
* Downloaded the app from about mentioned `Download URL: https://www.battle.net/download/getInstallerForGame?os=mac&locale=enUS&version=LIVE&gameProgram=HEARTHSTONE`
* Installed it manually
* After the installation got completed i tried removing the app using APPCLEANER & here is the screen shot
![battle-net-cask](https://cloud.githubusercontent.com/assets/450222/23579893/332f30fa-00c5-11e7-91a4-f65f7a4ecdea.png)
* Now if you take a look at uninstall section of Casks/battle-net.rb , you will notice both the same

(Just observation, i might be wrong)
