### ISSUE TITLE
Feature request: brew cask search: indicate packages that are already installed

### ISSUE THREAD

**Issue by thiagowfx** [caskroom/homebrew-cask#30583]
### Description of feature/enhancement
In Homebrew (core), whenever you do a `homebrew search <pkg>`, it appends a ✔ symbol to `<pkg>` it if it is already installed in the system (which can be quickly checked with `brew list | grep <pkg>`).

Homebrew cask, however, does not implement this feature (`brew cask search <pkg>` does not seem to append ✔, at least on my system).

Note: besides appending ✔, it also makes the text bold.

**Feature request**: to implement the aforementioned feature.

### Justification
It is user-friendly and makes homebrew cask more consistent with homebrew (core).

### Example use case

    > brew cask list | grep vim
    macvim

**Current** behavior:

    > brew cask search vim
    macvim
    vimmediamanager
    vimr

**Desired behavior**:

    > brew cask search vim
    macvim ✔
    vimmediamanager
    vimr

*Note*: I searched in previous (open) issues but couldn't find anything related to that.

**Comment by vitorgalvao** [comment]
Fine by me. Absolutely reasonable.

**Comment by nath** [comment]
I've got this finished but don't actually know how to commit it. I ended up modifying files under cask in the Homebrew install folder, which isn't a repository and contains files that aren't in this repo (cli/search.rb).

**Comment by reitermarkus** [comment]
This has been implemented.
