### ISSUE TITLE
gcc-arm-embedded has colon in path

### ISSUE THREAD

**Issue by tkornack** [caskroom/homebrew-cask#30634]
I am thrilled to see gcc-arm-embedded join homebrew-cask. I have encountered a build system that get tripped up on dependencies because the path to the cask includes a colon:

/usr/local/Caskroom/gcc-arm-embedded/6.2,2016q4:20161216/gcc-arm-none-eabi-6_2-2016q4

The first build will work but the .dep files contain colons so subsequent builds fail with a "multiple targets" error. If I download the same toolchain and move it to a path without colons, the builds work great. How easy is it to eliminate the colon from the path?

**Comment by adidalal** [comment]
We can modify the version string, sure.

Have any suggestions on a clean version number?
Ref: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md

**Comment by tkornack** [comment]
I defer to your judgement. It seems the simplest thing that works would be to change the colon to a dash.
