### ISSUE TITLE
eaglefiler update

### ISSUE THREAD

**Issue by tiiiecherle** [caskroom/homebrew-cask#30668]
Hey,

first of all, thanks for this really nice project. I´m sorry I don`t know how to submit a pull request.

I just wanted to let you know that eaglefiler was updated to 1.7.4 on January 10, 2017.

Would be nice to see the cask updated and working.

Thanks a lot

**Comment by vitorgalvao** [comment]
> I´m sorry I don`t know how to submit a pull request.

It’s a single command away. See https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md.

This time being done in https://github.com/caskroom/homebrew-cask/pull/30669.
