### ISSUE TITLE
[FR] dummy cask for testing-only purposes?

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#30710]
There may be cases when some one wants to check their git setup and/or tools on some test/fixture cask. So it may be good to introduce some dummy cask with infinite version bumps.

**Comment by reitermarkus** [comment]
> cask with infinite version bumps

What does that mean?

**Comment by yurikoles** [comment]
I mean that we can just bump version of this cask and always download same file with same checksum.

**Comment by vitorgalvao** [comment]
@yurikoles Any cask that has `version` but and unversioned URL (they exist, and always have an `appcast`) fits that description.
