### ISSUE TITLE
Remove `uninstall delete:  '/Applications/…` from `pkg` casks

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#30801]
On hold until https://github.com/Homebrew/brew/pull/2303.

**Comment by commitay** [comment]
@vitorgalvao https://github.com/Homebrew/brew/pull/2303 is merged, is it okay to do this?

**Comment by reitermarkus** [comment]
@commitay, yes, feel free to get started with this. 👍

**Comment by commitay** [comment]
Looks like several of these casks require the `delete:`

- All 3 `wine` casks do not remove the .app
- safari-technology-preview removes the `app` but  fails trying to remove the `pkg` receipt with `uninstall pkgutil`
- 3 driver casks: displaylink, wacom-intuos-tablet, wacom-intuos3-tablet. 2 others are missing the download source so I'll have to update them then check.

**Comment by commitay** [comment]
This list is done except for the `netbeans` casks which I have been unable to install.

- They run __100__ (not joking) `pkg` install scripts.
- I let one run overnight to see if it did anything but it doesn't finish installing.

------

Most casks do remove the `.app` so the `uninstall delete:` has been updated or removed as required.

Some uninstall the `.app` with a corrected `uninstall pkgutil:` stanza so they have been updated.

Some of these casks do not remove the `.app` / `.apps` or do not remove an `/Applications/` folder so I have left the `uninstall delete:` intact.


A couple of exceptions:
- ~~All 3 `wine` casks do not remove the .app~~
  - As the casks are now `pkgutil` doesn't do anything during uninstall because there are no `pkg` records to "uninstall"

- `safari-technology-preview` removes the `app` with `pkgutil` but fails trying to forget the `pkg` receipt.

**Comment by vitorgalvao** [comment]
Thank you for the all the work @commitay!

@miccal Are you able to reproduce the `netbeans` hanging on your test machine?

**Comment by miccal** [comment]
@vitorgalvao I will check tomorrow.

**Comment by miccal** [comment]
@vitorgalvao confirmed:
```
-bash-4.4.12- /Users/miccal [> brew cask install java
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-macosx-x64.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask java
==> Running installer for java; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is JDK 8 Update 131
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  java was successfully installed!
```
```
-bash-4.4.12- /Users/miccal [> brew cask install netbeans
==> Downloading http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-macosx.dmg
Already downloaded: /Users/miccal/Library/Caches/Homebrew/Cask/netbeans--8.2.dmg
==> Verifying checksum for Cask netbeans
==> Running installer for netbeans; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
```
Left it for an hour, nothing happens.

**Comment by vitorgalvao** [comment]
I wonder if anyone would miss those casks.

Did any of you try installing it manually as well, or just via HBC?

**Comment by commitay** [comment]
I tried to install one manually in a VM, same results. I'll try another one.

**Comment by commitay** [comment]
Netbeans Java SE installs manually but it is the "smallest" .



![netbeans](https://cloud.githubusercontent.com/assets/26216252/25332793/28ea1da6-292b-11e7-9cb8-7c292220dbb5.png)

**Comment by vitorgalvao** [comment]
If they even hang on manual installs, perhaps we should just remove them. Nobody seems to be using them anyway (or we would’ve gotten bug reports by now).

**Comment by commitay** [comment]
> Nobody seems to be using them anyway (or we would’ve gotten bug reports by now).

If we remove them I suppose we'll find out quickly if someone is actually using them (and if they actually install via HBC.) 

`netbeans-html` was only added last month in https://github.com/caskroom/homebrew-cask/pull/30705

**Comment by vitorgalvao** [comment]
Let’s make a PR to remove them, then.

This issue can be closed. Thank you for all the work, @commitay.
