### ISSUE TITLE
Did someone forget to renew the domain caskroom.io?

### ISSUE THREAD

**Issue by mike-u** [caskroom/homebrew-cask#30833]
[The website seems to have expired.](http://i.imgur.com/WAUXDTr.png)

Apologies if caskroom.io is separate from this repo.

**Comment by vitorgalvao** [comment]
The domain was giving too many issues, so we dropped it in favour of https://caskroom.github.io. You’ll notice there are no longer mentions to that domain anywhere on the official channels.
