### ISSUE TITLE
Cask request: Transporter Desktop

### ISSUE THREAD

**Issue by relativesanity** [caskroom/homebrew-cask#30838]
### Cask details

Client application for Nexsan's Transporter private cloud appliance.

Name: Transporter Desktop

Homepage: http://helper.nexsansupport.com/tfb_downloads.html

Download URL: https://secure.connecteddata.com/download/desktop, https://secure.connecteddata.com/mac/2.5/software/Transporter_Desktop_4.2.12_22430.dmg

Description: Transporter is a versatile tool that will allow you to easily perform a range of sync and sharing activities with your private cloud storage devices

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/30839
