### ISSUE TITLE
Bug report: teamspeak-client issue with case-sensitive filesystem

### ISSUE THREAD

**Issue by cluzz** [caskroom/homebrew-cask#30844]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

There's not a lot to say, teamspeak searches for qt dylibs in `/Applications/TeamSpeak 3 Client.app/Contents/resources` but the directory is `Resources`. I made a lowercase symlink to Resrources and it works as expected, i also reported this bug to the teamspeak developers.

Maybe you could automatically fix it by detecting that the filesystem is case sensitive and symlinking the directory, as long as the TS devs haven't fixed it

**Comment by miccal** [comment]
You will need to report this upstream.
