### ISSUE TITLE
Cask request: Background Music

### ISSUE THREAD

**Issue by macklow** [caskroom/homebrew-cask#30868]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Background Music

Homepage: https://github.com/kyleneideck/BackgroundMusic

Download URL: https://github.com/kyleneideck/BackgroundMusic/archive/master.tar.gz

Description:
- Automatically pauses your music player when other audio starts playing and unpauses it afterwards
-     Per-application volume, boost quiet apps
-     Record system audio
-     No restart required to install
-     Runs entirely in userspace

**Comment by giannitm** [comment]
The installer script for this cask only works if the user has Xcode installed on their system already. However, there does not appear to be a cask for Xcode (obviously, as it is downloaded via the App Store) and I see no other way to use the `depends_on` stanza to install Xcode. Perhaps there is a command that can be executed which installs Xcode before the installer script runs (e.g. `xcode-select --install`)?

(In the README for this project, it states that Xcode is required as `xcodebuild` no longer works on its own: https://github.com/kyleneideck/BackgroundMusic#install)

**Comment by vitorgalvao** [comment]
@giannitm We (Homebrew-Cask, as opposed to Homebrew) don’t compile, so we never require Xcode. If this app has no readily available compiled apps, we’ll simply have to refuse it.

Is that the case?

**Comment by giannitm** [comment]
Indeed, the developer states that there are not (as yet) any binaries available for the software, although they are "working on it" according to the README.

For now, yes, we should refuse the cask request @vitorgalvao, I think.

**Comment by vitorgalvao** [comment]
Thank you, @giannitm.
