### ISSUE TITLE
Outdated cask: intellij-idea-eap

### ISSUE THREAD

**Issue by arvindsv** [caskroom/homebrew-cask#30873]
* Link to cask: [intellij-idea-eap](https://github.com/caskroom/homebrew-versions/blob/master/Casks/intellij-idea-eap.rb)

* New version is: 2017.1 EAP 171.3780.15

```
$ brew cask _stanza version intellij-idea-eap
2016.3.5,163.13906.16
$ brew cask install intellij-idea-eap
==> Downloading https://download.jetbrains.com/idea/ideaIU-163.13906.16.dmg
######################################################################## 100.0%
curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'intellij-idea-eap' with message: Download failed: https://download.jetbrains.com/idea/ideaIU-163.13906.16.dmg
The incomplete download is cached at /Users/aravindsv/Library/Caches/Homebrew/Cask/intellij-idea-eap--2016.3.5,163.13906.16.dmg.incomplete
Error: nothing to install
```

Some relevant links pointing to the new version:

Old (dead) EAP link: https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.3+EAP
New EAP location:    https://confluence.jetbrains.com/display/IDEADEV/EAP
New EAP landing page: https://www.jetbrains.com/idea/nextversion/
Direct download link: https://download-cf.jetbrains.com/idea/ideaIU-171.3780.15.dmg
SHA 256 checksum: 26071b76c684797a3720fbcec116c0616950ee0d42e762215ebe188c39de9277

I've followed all the instructions [here](https://github.com/caskroom/homebrew-cask#reporting-bugs), before reporting this issue.

**Comment by gobinathm** [comment]
Just Submitted a PR with update for this https://github.com/caskroom/homebrew-versions/pull/3446

**Comment by metyl** [comment]
@arvindsv First of all You reported issue to wrong repository, all EAPs lives in [caskroom/homebrew-versions](https://github.com/caskroom/homebrew-versions|) and there is `intellij-idea-next-eap` which You should use.
EAP for current release (2016.3) of IntelliJ IDEA is **not** dead until release of next version (2017.1).

**Comment by arvindsv** [comment]
Ok, thank you. Good to know.
