### ISSUE TITLE
Upgrade gcc-arm-embedded to version "6-2017-q1-update"

### ISSUE THREAD

**Issue by tkornack** [caskroom/homebrew-cask#30886]
In the current cask version of gcc-arm-embedded, there is a macOS-specific bug in gdb detailed here:

https://bugs.launchpad.net/gcc-arm-embedded/+bug/1655778

The update that resolves the issue is "6-2017-q1-update" and can be found on this page:

https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

Or directly using this link:

https://developer.arm.com/-/media/Files/downloads/gnu-rm/6_1-2017q1/gcc-arm-none-eabi-6-2017-q1-update-mac.tar.bz2?product=GNU%20ARM%20Embedded%20Toolchain,64-bit,,Mac%20OS%20X,6-2017-q1-update

Thank you!

**Comment by giannitm** [comment]
This might be a better URL to use (got this from "Downloads → Copy address (right-click)" in the Safari browser):

https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/6_1-2017q1/gcc-arm-none-eabi-6-2017-q1-update-mac.tar.bz2

**Comment by vitorgalvao** [comment]
Already done.
