### ISSUE TITLE
brew cask upgrade

### ISSUE THREAD

**Issue by shrx** [caskroom/homebrew-cask#309]
this issue currently tracks the discussion and work around adding a `brew cask upgrade` command to homebrew-cask. it started as a bug ticket, whose original contents can be found below.

any action on implementing `brew cask upgrade` functionality will happen here.

-----

(original title: Calibre is not updated automatically)

I have calibre 0.2.29 installed with cask.
`brew update; brew upgrade` does not update it to the latest version available (0.2.30 as of now).
`brew cask info Calibre` output:
```
calibre: latest
http://calibre-ebook.com/
Not installed
https://github.com/phinze/homebrew-cask/commits/master/Casks/calibre.rb
```

**Comment by vitorgalvao** [comment]
Closed in favor of #4678, since we haven’t had problems with duplicates with this.
