### ISSUE TITLE
Cask request: Virtualbox upgrade to 5.1.18

### ISSUE THREAD

**Issue by Tcharl** [caskroom/homebrew-cask#30963]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Virtualbox update to 5.1.18

Homepage: https://www.virtualbox.org/

Download URL: https://www.virtualbox.org/wiki/Downloads

Description: the actual version is 5.1.16, an upgrade could be nice.

Thank you in advance!
Best regards,

**Comment by gobinathm** [comment]
Since there is Open PR for this issue, we should be closing it.
