### ISSUE TITLE
Feature request: Don't show deprecation warnings when uninstalling

### ISSUE THREAD

**Issue by joshka** [caskroom/homebrew-cask#30968]
### Description of feature/enhancement

I'm using an old laptop tonight while my usual one is in for a screen replacement. I noticed that when uninstalling or reinstalling, deprecation warnings are intermixed with installation commands. This could make it difficult (for someone that's not intimately familiar with the installation process)  to judge whether the installation has succeeded correctly.

Perhaps hide these warnings for the uninstall process or add a more thorough explanation that avoids this confusion. Something like "The previously installed cask uses features deprecated since it was installed. These warnings are expected and should not lead to a failed install" followed by the standard bug spiel. 

```
➜  ~  brew cask reinstall google-chrome
==> Satisfying dependencies
complete
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
######################################################################## 100.0%
==> No checksum defined for Cask google-chrome, skipping verification
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:19:in `load'

Warning: Unexpected method 'tags' called on Cask google-chrome.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

==> Moving App 'Google Chrome.app' to '/Applications/Google Chrome.app'
🍺  google-chrome was successfully installed!
```

Is it? What did those warnings mean then? Let's reinstall

```
➜  ~  brew cask reinstall google-chrome
==> Satisfying dependencies
complete
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
######################################################################## 100.0%
==> No checksum defined for Cask google-chrome, skipping verification
==> Removing App: '/Applications/Google Chrome.app'
==> Moving App 'Google Chrome.app' to '/Applications/Google Chrome.app'
🍺  google-chrome was successfully installed!
```

Oh, the warnings must have been about the previous install.

### Justification

End user confusion.

**Comment by gobinathm** [comment]
@joshka You installation seems to be pretty old.  Can you try the following & post the output 

```
$ rm -r /usr/local/Caskroom/google-chrome
$ brew install Caskroom/cask/google-chrome
```

try doing an install (or) reinstall..

**Comment by joshka** [comment]
Yes. This is my backup machine that I haven't used in some time. It was running a version of cask pre-0.9.9 before I updated, which suggests it is at least a year old.

I'm extremely aware of why this occurs and how to fix it. I've raised this issue to discuss whether it should occur, not about solving my problem. This isn't a problem for me as a developer / homebrew user that contributes code to brew and cask, but it could be for a normal user that hits the same situation.

As for the reinstall suggestion, please take note of that the second reinstall command above, which ran without problems.

I'd like to also point out, I'm pleased to see how well the long term compatibility between versions of brew and cask worked out, particularly knowing how much changed over the last year.

**Comment by vitorgalvao** [comment]
Deprecation warnings should *always* be shown when using deprecated features. Deprecation warnings exist as a way of saying “you’re relying on something that is no longer used in the software itself, *and it may break at any moment, so please update as soon as you can*”.

So deprecation warnings are a way of not immediately pulling the rug from under your feet. If they did not show, they would be useless. They *need* to show every time precisely so you get the urgency of fixing your installation.

**Comment by joshka** [comment]
Hey @vitorgalvao perhaps you missed the alternative suggestion:

> add a more thorough explanation that avoids this confusion. Something like "The previously installed cask uses features deprecated since it was installed. These warnings are expected and should not lead to a failed install" followed by the standard bug spiel.

This is a problem because the warnings during reinstallation indicate that my system is in a broken state. It's not, but the message cask provides me is wrong. The warning is useful, but the message that it portrays is not.

**Comment by vitorgalvao** [comment]
Ah, got it. I don’t think this is common enough to care about, but reopening for now.

**Comment by joshka** [comment]
Thanks @vitorgalvao 

When doing a reinstall, it's also unclear  which messages are part of the uninstall and which are part of the install. Perhaps an extra message in there would help.

I'm happy to submit a PR to address this, but wanted some consensus around the messaging and a discussion of why I think it's a problem first.

**Comment by miccal** [comment]
@joshka a PR about this is always welcome.

**Comment by vitorgalvao** [comment]
@joshka I agree better messages regarding what is the uninstall and what is the install are beneficial. Even if it’s just `Uninstalling current version…` and `Installing latest version…` followed by the rest of the commands.

Regarding cleverer handling of when the messages appear, I don’t think that should be necessary. For one, this will be ever more rare as time passes, so we’re leaving old code laying around. But even if a user finds this and is unsure what to do, the messages even say “run this to fix” and “if it doesn’t work, do this instead”, so presumably they’ll run the first instructions and have it fixed.

**Comment by commitay** [comment]
Seems to be resolved with https://github.com/Homebrew/brew/issues/2362
