### ISSUE TITLE
(question) Support formula@version?

### ISSUE THREAD

**Issue by petemounce** [caskroom/homebrew-cask#30962]
Homebrew-core now supports (for example) `brew install clang@3.8`. [It requires formulae to be updated](https://github.com/Homebrew/homebrew-core/blob/master/Formula/clang-format@3.8.rb#L1).

Does homebrew-cask support this now automatically?

If so, is it reasonable to submit PRs to translate formulae that I depend on so that I can install particular versions of casks?

I remember also reading somewhere that the maintenance overhead of many different versions of formulae would be too high. Is that still the case if a formula is (hopefully basically) immutable after it has been added - the only things likely to change are the URLs & hashes...?

(I'm particularly interested in it being possible to install unity (and its optional plugins) at different versions (I remember that only 3 minor versions back would be accepted...?).)

**Comment by adidalal** [comment]
I don't think Cask gets versions for free, but I may be mistaken.

If you need a particular shrinkwrapped (set of) versions, your best bet is probably to copy the `.rb` files to your own tap - HBC will install them without any complaints. IIRC we only accept specific things into our `versions` repo.

**Comment by vitorgalvao** [comment]
Yep, [caskroom/versions](https://github.com/caskroom/homebrew-versions) remains our way of dealing with versions. For HB it’s easier to have immutable formulae since all formulae on the core **must** be open-source and tagged to be accepted in the first place. That means you can pretty much rely on a particular version to continue to be available and buildable in the same way.

For HBC, though, we accept pretty much anything, including commercial apps, and their availability is completely dependent on (many times flimsy) vendors. That means casks break frequently due to some change upstream. The system wouldn’t work as reliably with us.

**Comment by petemounce** [comment]
Thanks. So, if I have dependencies that are not my own software, I'd need to put those formulae in my tap as well, correct? At which point they would conflict with the upstream ones? So I'd have to rename them. Is there a better way I haven't seen...?

**Comment by vitorgalvao** [comment]
You don’t have to rename them, as they should not conflict.

Instead of `depends_on` on `my-software`, you make it depend on `my-username/my-tap/my-software`.

**Comment by petemounce** [comment]
Oh; good. Thank you!

How does that interact with casks that are installed via the regular caskroom tap? 

For example, if someone has done `brew cask install unity` and got `5.5.2`, and then they do `brew cask install my-thing` which depends on `my-username/my-tap/my-unity` which is version `5.5.0` of unity. Does the caskroom instance get replaced? Are they installed side by side?

(That's another thing I'm interested to find out - how to install formulae at different versions side by side - my use-case is provisioning continuous integration job runners onto server instances (as opposed to containers, since macOS doesn't have a container solution so far)).

**Comment by vitorgalvao** [comment]
We do *not* support installing multiple versions of the same app at the same time. That is not a model that works for most apps. See #13201.

**Comment by petemounce** [comment]
Thanks very much for the background! Sounds like I'll want to maintain separate pools of OSX build slaves according to the test matrix, then, rather than have the possibility of different versions of unity on the same box.
