### ISSUE TITLE
Telegram for Mac doesn't update, it is stuck in 2.9.

### ISSUE THREAD

**Issue by aristidesfl** [caskroom/homebrew-cask#30977]
#### Description of issue

Telegram for Mac doesn't update, it is stuck in 2.9.

<img width="532" alt="screen shot 2017-03-16 at 14 25 43" src="https://cloud.githubusercontent.com/assets/208149/23998527/b2f3f0a2-0a55-11e7-9cdf-54c19698fd93.png">

Newest version is 2.30.x

Even this might not be a problem caused by homebrew-cask, maybe updating the base installed version of the formula would fix this issue.

For reference: https://github.com/overtake/telegram/issues/406

Sierra 10.12.3

**Comment by overtake** [comment]
2.9 is latest version

**Comment by aristidesfl** [comment]
Not according to the App Store:
<img width="642" alt="screen shot 2017-03-16 at 14 41 25" src="https://cloud.githubusercontent.com/assets/208149/23998833/b139b340-0a56-11e7-83fb-1674255dda88.png">

**Comment by aristidesfl** [comment]
Also if you download from the [website](https://macos.telegram.org), you get 2.30

**Comment by vitorgalvao** [comment]
I’ll update the cask, but as mentioned, the fact it is not updating has nothing to do with HBC.

**Comment by vitorgalvao** [comment]
Now that I look at it, the cask is already at 2.30.

**Comment by aristidesfl** [comment]
@vitorgalvao that is strange. @overtake where did you get that number (2.9) from?

**Comment by aristidesfl** [comment]
Reinstalled the app and got this upgrade dialog. Is 2.9 the new alpha? If so, why does it have a version number smaller than 2.30?

<img width="732" alt="screen shot 2017-03-16 at 16 07 23" src="https://cloud.githubusercontent.com/assets/208149/24003059/ae328a12-0a62-11e7-9972-f6838ec44c97.png">

**Comment by vitorgalvao** [comment]
@aristidesfl You’ll have to ask them, we have nothing to do with it.

**Comment by RJHsiao** [comment]
The REAL new version number is 2.91-90072
Ref #31016

**Comment by aristidesfl** [comment]
@RJHsiao yeah, they released 2.91 yesterday. And was 2.9 was a foresight? At the same time, should the mainline app be suggesting the upgrade to a alpha version? 2.9 didn't have a preference pane.

**Comment by RJHsiao** [comment]
Hey @aristidesfl 

Any question about Telegram for macOS, please [go to ask the "Telegram for macOS" developers](https://github.com/overtake/telegram). They are the developer and they send the notification to you, not Caskroom.

Caskroom doesn't management about when a app developer release new version and should they release a buggy version or not. Caskroom won't send any notification about new version released.
Caskroom just try to help you to download and install apps with latest version, even it's a very buggy version.

**Comment by aristidesfl** [comment]
Hey @RJHsiao 

That has been mentioned a few times on this thread. Thanks ;)
