### ISSUE TITLE
Feature request: more infos about language stanza

### ISSUE THREAD

**Issue by muescha** [caskroom/homebrew-cask#31094]
## Justification

while i try to install `libreoffice-language-cask` i come over the problem that is not so much info about the language is available. just now i don't can find out before installation if the language is determinated from my current OS system or how i choose it. i read through readme's and casks a bit and also don't find the right information just with the `brew cask` command. this info should be given before i install a cask. i would suggest some (one or more) enhancements for this use case.

## Description of feature/enhancement

add more info about language option in this places:

### Missing documentation
- [ ] A: missing info in [stanzas/language.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/language.md) which language is used while installation
- [ ] B: missing option `--language=` in [man brew-cask](https://github.com/Homebrew/brew/blob/master/manpages/brew-cask.1)
- [x] C: missing option `--language=` in [USAGE.md](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md)

### `brew cask` help with languages
- [ ] D: show the used language depending on OS in `brew cask info <token>`
- [ ] E: list of possible languages of a stanza with `brew cask info <token>`
- [ ] F: show the option `--language=` in `brew cask info <token>` at section `caveats`
- [ ] G: suggest to install an language pack if an additional language pack is available `brew cask install <token>` or `brew cask info <token>`

### A: stanzas/language.md

at section `Installation` in [stanzas/language.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/language.md) add this as first paragraph:

```
when you install a cask with language stanzas It will install in this order:
1. just get either the language of your system
2. if there is no match, then the language marked with default in cask (mostly `en`)
3. or the language you specifically asked for with option `—language=<iso-language>[,<iso-language> ... ]`
```

### B: man brew-cask

add info at [manpages/brew-cask.1](https://github.com/Homebrew/brew/blob/master/manpages/brew-cask.1)

```
FREQUENTLY USED COMMANDS
       install [--force] [--skip-cask-deps] [--require-sha][--language=<iso-language>[,<iso-language> ... ]] token [ token ... ]
              Install Cask identified by token.
```

and

```
COMMANDS
       audit [--language=<iso-language>[,<iso-language> ... ]] [ token ... ]
              Check the given Casks for installability. 
              If no tokens are given on the command line, all Casks are audited.
```

and 

```
OPTIONS

       --language=<iso-language>[,<iso-language> ... ]
              Set language of the cask to install. 
              The first matching language is used otherwise the default language on the cask.
              The default value is the language of your system.

```

### C: USAGE.md

in [USAGE.md](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md) add this line in section `Options`

```
You can also modify the installed language when issuing `brew cask install`:

    - `--language=<iso-language>[,<iso-language> ... ]` changes the language of the cask to install. 
      The first matching language is used otherwise the default language on the cask.
      The default value is the language of your system.
```

### D&E: add info to `brew cask info <token>`

```
muescha$ brew cask info seamonkey
seamonkey: 2.46
http://www.seamonkey-project.org/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/seamonkey.rb
==> Name
SeaMonkey
==> Artifacts
SeaMonkey.app (app)
==>available Languages
*de* 
en-GB
en (default)
fr
it
ru
==>System Language
de
==>Installing Language
de
Note: this installing language is because of your system language
Note: you can use the option `--language=<iso-language>[,<iso-language> ... ]` to install a specific language.
      The first matching language is used otherwise the default language on the cask.
muescha$ 
```

or if it not match the system language:
```
==>System Language
zh
==>Installing Language
en
Note: this installing language is because of the default language setting in cask
      and there is no match to your system language
Note: you can use the option `--language=<iso-language>[,<iso-language> ... ]` to install a specific language.
      The first matching language is used otherwise the default language on the cask.
muescha$ 
```

### F: show in caveats

if **D&E** is not possible

```
muescha$ brew cask info seamonkey
seamonkey: 2.46
http://www.seamonkey-project.org/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/seamonkey.rb
==> Name
SeaMonkey
==> Artifacts
SeaMonkey.app (app)
==>Caveats
this cask include language stanzas. you can use the option `--language=<iso-language>[,<iso-language> ... ]`
to install a specific language or use the default language determinated by your system.
```

### G: info about additional language packs

```
muescha$ brew cask info libreoffice
[...]
==>Caveats
there exists a language pack in cask `libreoffice-language-pack`
```

**Comment by muescha** [comment]
updated first post from `<iso-language>` to `<iso-language>[,<iso-language>]` 
(see: `Mac.languages` in [mac.rb]( https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac.rb#L59) )

**Comment by muescha** [comment]
updated first post with `The first matching language is used otherwise the default language on the cask.`

(see `language_eval` in [dsl.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/dsl.rb#L126) and `Mac.languages` in [mac.rb]( https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac.rb#L59) )

**Comment by muescha** [comment]
updated fist post with at section **B** for `brew audit` 

(see `auditor#audit` in [auditor.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/auditor.rb#L24) )

**Comment by vitorgalvao** [comment]
No on **F** and **G**.

**Comment by vitorgalvao** [comment]
Closed in favour of https://github.com/caskroom/homebrew-cask/issues/31128 and https://github.com/caskroom/homebrew-cask/issues/31129.
