### ISSUE TITLE
Bug: `brew cask audit --language=<iso-language>` don't check the language

### ISSUE THREAD

**Issue by muescha** [caskroom/homebrew-cask#31114]
## Syntax

this syntax is possible (see #31094):

`audit [--language=<iso-language>[,<iso-language> ...]] [ token ... ]`

## what i do

```
$ brew cask audit seamonkey
==> Auditing language: 'de'
audit for seamonkey: passed
==> Auditing language: 'en-GB'
audit for seamonkey: passed
==> Auditing language: 'en'
audit for seamonkey: passed
==> Auditing language: 'fr'
audit for seamonkey: passed
==> Auditing language: 'it'
audit for seamonkey: passed
==> Auditing language: 'ru'
audit for seamonkey: passed
$ brew cask audit seamonkey --language=de
audit for seamonkey: passed
$ brew cask audit seamonkey --language=ru
audit for seamonkey: passed
$ brew cask audit seamonkey --language=zh
audit for seamonkey: passed
$ brew cask audit seamonkey --language=de,zh
audit for seamonkey: passed
```

## what i see

if i use the language option, then it get always an `passed`. 

## what i expected

when language is set: only the languages set by argument should be tested:

```
$ brew cask audit seamonkey --language=de
==> Auditing language: 'de'
audit for seamonkey: passed
$ brew cask audit seamonkey --language=ru
==> Auditing language: 'zh'
audit for seamonkey: passed
$ brew cask audit seamonkey --language=zh
==> Auditing language: 'zh'
audit for seamonkey: not passed: missing language
$ brew cask audit seamonkey --language=de,zh
==> Auditing language: 'de'
audit for seamonkey: passed
==> Auditing language: 'zh'
audit for seamonkey: not passed: missing language
```

(see `Aditor#audit` in [auditor.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/auditor.rb#L24))

**Comment by vitorgalvao** [comment]
I agree it should inform you of what language it’s testing and when, but I disagree you should be able to select a specific language to check. `audit` is to check for a cask’s correctness. It’s either correct or it isn’t, checking just a few particular languages is not beneficial for the health of the cask.

**Comment by vitorgalvao** [comment]
Actually, I just checked this with `--download`, and confirmed only the languages you specify are tested.

**Comment by muescha** [comment]
```
$ brew cask audit seamonkey --language=zh,si --download
==> Downloading https://ftp.mozilla.org/pub/seamonkey/releases/2.46/mac/de/SeaMonkey%202.46.dmg
######################################################################## 100,0%
==> Verifying checksum for Cask seamonkey
audit for seamonkey: passed
```
it downloads the `de` version because of my system is german

i would expect if i use `--language=zh,si` then it should audit only this language(s) (`zh` and `si`) and notify me, when this language is not available on the cask. 

PS: if you say the current behavior is by design, then i agree with closing this issue
