### ISSUE TITLE
Install location Option for Internet Plugins

### ISSUE THREAD

**Issue by jprokos** [caskroom/homebrew-cask#31115]
I installed cask vlc-webplugin. It was installed into ~/User/Library not /Library. Do we need to add a brew cask option to install Internet plugins into /Library instead of current user? Similar to the options already existing for: Prefpane, Quicklook Plugins, Dictionaries, Fonts, Input Methods, Screen Savers.

**Comment by vitorgalvao** [comment]
There is one: `--internet_plugindir`. It’s on the `man` page.

**Comment by jprokos** [comment]
Thanks, missed it. However an issue presents itself, while  running brew cask install as admin it fails to install the prePane because of Permissions.

Moving Preference Pane 'AppTrap.prefPane' to '/Library/PreferencePanes/AppTrap.prefPane'.
Error: Permission denied - (/usr/local/Caskroom/apptrap/1.2.3/AppTrap.prefPane, /Library/PreferencePanes/AppTrap.prefPane)

**Comment by jprokos** [comment]
If we can not use sudo how do we gain permission to install into /Library?
I am admin, but apparently don't have write access to that folder without using sudo.
