### ISSUE TITLE
Bug: when no stanza `language` don’t have a `default` language in a cask

### ISSUE THREAD

**Issue by muescha** [caskroom/homebrew-cask#31117]
## when

- one or more stanza `language` is used on a cask
- non of the stanzas `language` has the option `default` set
- the languages of current system (and possible given `--language` argument) not match andy of the languages
- call `brew cask install <token>`

## what i see

`default` is then not defined in `@language_blocks` and i expect an error `NoMethodError: undefined method call for nil:NilClass`:

```
@language = @language_blocks.default.call
```

( see `language_eval` in [dsl.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/dsl.rb#L136))

## what i expected

- error should be catched and display a notification to the user
- a cask checker (maybe `brew cask audit <token>`?) should inform about the missing default

**Comment by vitorgalvao** [comment]
You’ll need to be more specific and provide a testable case, because I cannot reproduce. In the only ways I can get a cask to break like this, `audit` also fails.

**Comment by miccal** [comment]
Closing due to lack of response.
