### ISSUE TITLE
Downgrade / VMWare Fusion problems

### ISSUE THREAD

**Issue by mafrosis** [caskroom/homebrew-cask#31181]
A recent VMWare Fusion update has broken all my Vagrant boxes (not for the first time!) In order to debug what happened, I'd like to install an older version of `vmware-fusion`. Is there a built in method of doing this?

I followed this method, of installing the brew recipe directly:
https://www.jverdeyen.be/mac/downgrade-brew-cask-application/

But that left me with a broken VMWare install:

    vmrun Error:
    vmrun must be set-UID root, "/Applications/VMware Fusion.app/Contents/Library/vmware-vmx" is not. Are you running /Applications/VMware Fusion.app/Contents/Library/vmware-vmx from its distribution directory? That copy of the program is not set-UID root.

Thanks

**Comment by vitorgalvao** [comment]
The method in that blog post is absolutely not officially supported, as is not at all recommended. It’s more than likely it’ll break, as it did for you.

Uninstall your current version and look for another one in [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by mafrosis** [comment]
I guessed as much by the results!

So what's the plan if the particular version is not in `caskroom/versions`?

**Comment by vitorgalvao** [comment]
> So what's the plan if the particular version is not in `caskroom/versions`?

You add it, as long as it is accepted by [the rules](https://github.com/caskroom/homebrew-versions#acceptable-casks) or you make your own tap.
