### ISSUE TITLE
docker run hello-world fails after install

### ISSUE THREAD

**Issue by mbigras** [caskroom/homebrew-cask#31205]
I'm running macOS Sierra

    ProductName:  Mac OS X
    ProductVersion: 10.12.1
    BuildVersion: 16B2657

I've successfully installed the docker cask via `brew cask install docker`

    $ docker --version
    Docker version 17.03.0-ce, build 60ccb22
    $ docker ps
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Also, I can see the whale icon in my menu-bar as shown:

<img src="https://www.dropbox.com/s/ru4dqu822mpbi47/Screenshot%202017-03-22%2015.14.40.png?dl=1" alt="Smiley face" height="200">

However, when I try to run `docker run hello-world` it fails:

    $ docker run hello-world
    docker: Error response from daemon: ContainerInspect failed.
    ERRO[0000] error getting events from daemon: net/http: request canceled

* How do I successfully run `docker run hello-world`? with the docker for mac cask?

**Comment by miccal** [comment]
This is not an issue with Cask; you will need to ask the maintainers of Docker.
