### ISSUE TITLE
[FR] allow to use pipes in `system_command`

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#31223]
Please help me figure out why echo command doesn't work
I have tried following commands and they dont work.
```
 system_command "/bin/echo", args: ["y|bash", "#{staged_path}/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;25.0.2" ]
```

```
system_command '/bin/echo', args: ["601085b94cd77f0b54ff86406957099ebe79c4d6", ">", "#{staged_path}/licenses/android-googletv-license"]
```

**Comment by vitorgalvao** [comment]
I find it unlikely that a random system command simply doesn’t work with a method that calls it. It seems more plausible `system_comand` can’t handle the pipe or the redirection in that manner, but I don’t see it having options like the `out` and `err` from `system`, so I need input from @reitermarkus there.

Also, don’t use `/bin/echo y`, use `/usr/bin/yes`, it’s what it exists for.

**Comment by yurikoles** [comment]
@vitorgalvao first of all you suggestion doesn't work with this particular command even in terminal after cask is installed. And the following command
```
system_command "/usr/bin/yes", args: ["|#{staged_path}/tools/bin/sdkmanager", 'tools', 'platform-tools', 'build-tools;25.0.2']
```

just eats 100% of one core of my CPU and doesn't finish for a while, so I think there is infinite loop.

**Comment by vitorgalvao** [comment]
> And the following command (…) just eats 100% of one core of my CPU and doesn't finish for a while

Of course, because it still has the pipe problem! You weren’t supposed to try it now, as that didn’t solve the crux of the issue.

> so I think there is infinite loop

That’s what `yes` does.

**Comment by yurikoles** [comment]
@vitorgalvao is there another way to write some data to a file in cask that is working?

**Comment by reitermarkus** [comment]
Does `system_command 'foo', input: "y\n"` work?

**Comment by yurikoles** [comment]
@reitermarkus yes, it does the trick!

**Comment by yurikoles** [comment]
please add flag `enhancement`

**Comment by vitorgalvao** [comment]
Pipes are used to send output as input of the other command. If we can control those, why shoehorn pipes in there? Might as well use `system` everywhere, then.

Closing. Feel free to reopen if you disagree, @reitermarkus.
