### ISSUE TITLE
How to better implement android-ndk and crystax-ndk packages?

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#31234]
`android-ndk` has been removed from homebrew because it's binary-only. The `crystax-ndk` is also due to migrate https://github.com/Homebrew/homebrew-core/pull/11811.

I had tried straightforward approach by unpacking and creating symlinks for binaries. But the binaries are failed to execute via symlinks. There is a workaround in brew package:

```ruby
ndk_exec = prefix+"ndk-exec.sh"
    ndk_exec.write <<-EOS.undent
      #!/bin/sh
      BASENAME=`basename $0`
      EXEC="#{prefix}/$BASENAME"
      test -f "$EXEC" && exec "$EXEC" "$@"
    EOS
    ndk_exec.chmod 0755
    %w[ndk-build ndk-depends ndk-gdb ndk-stack ndk-which].each { |app| bin.install_symlink ndk_exec => app }
```
I don't sure how to port it in cask DSL.

There is another possible approach: create fake package that will depend on `android-sdk` and use `sdkmanager` command to install ndk.

**Comment by yurikoles** [comment]
bump!

**Comment by MikeMcQuaid** [comment]
I would say just create the cask without these symlinks/wrappers and then focus on adding them later.

**Comment by yurikoles** [comment]
@MikeMcQuaid done. I had created two PR with different approaches to this cask: #31614 and #31610

**Comment by MikeMcQuaid** [comment]
Thanks @yurikoles. Once they are merged let's update the `tap_migrations` lines to point to them.

**Comment by ksperling** [comment]
In the interim, it would be nice if the migration info output by brew would point users towards installing `android-sdk` and then installing the NDK via `sdkmanager ndk-bundle`, rather than towards the as-yet non-existant `android-ndk` cask.

**Comment by yurikoles** [comment]
Please help me on this issue!

**Comment by victorpopkov** [comment]
> Please help me on this issue!

@yurikoles Sorry for waiting. I will try to help you with this issue.

**Comment by ilovezfs** [comment]
How are we doing over here?

**Comment by yurikoles** [comment]
I think we already figured it out in #31614.
