### ISSUE TITLE
Do we have a list of version.sub options somewhere?

### ISSUE THREAD

**Issue by numbermaniac** [caskroom/homebrew-cask#31342]
Is there a list of the available string-replacement options that can be used in the `url` stanza for `version`, like `#{version.before_comma}`,`#{version.dots_to_commas}` etc, somewhere in the docs?

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md is all we have I think.
