### ISSUE TITLE
Cask request: minimal Android adb and fastboot (like the old brew android-platform-tools)

### ISSUE THREAD

**Issue by bits01** [caskroom/homebrew-cask#31437]
### Cask details

Name:
Minimal adb and fastboot like brew used to provide:
http://brewformulas.org/android-platform-tool

Homepage:
https://developer.android.com/studio/releases/platform-tools.html

Download URL:
https://dl.google.com/android/repository/platform-tools-latest-darwin.zip

Description:
brew used to provide android-platform-tools which was perfect to get just adb and fastboot. Now it was removed from brew in favor of the android-sdk which comes in at 590MB of stuff that I don't need or use. Moreover, it doesn't even symlink adb and fastboot in /usr/local/bin so it's not very usable.

**Comment by gobinathm** [comment]
@bits01 all these seems to be command line tool. Those needs to go in [Core](https://github.com/Homebrew/homebrew-core) if i'm not wrong

**Comment by bits01** [comment]
There was `brew install android-platform-tools` but it got removed with a message that one should use `brew cask install android-sdk` instead but that's 20x bigger in size and not all useful symlinks are created in bin.

**Comment by bits01** [comment]
This is the core commit that removed Formula/android-platform-tools.rb:
https://github.com/Homebrew/homebrew-core/commit/706efcabf63090dc926e074d5a83ad21dc429457

**Comment by zachberger** [comment]
> This needs to go in Core if i'm not wrong.

@MikeMcQuaid seems to disagree [here](https://github.com/Homebrew/brew/issues/2402#issuecomment-289548222)

**Comment by MikeMcQuaid** [comment]
This can go in homebrew/core if it's build from source otherwise it should go in Homebrew Cask.

**Comment by Raphx** [comment]
Hi all, I created a PR for this. #31501 
The cask only symlinks `adb` and `fastboot`. I'm not sure if other executables should be symlinked as well.
