### ISSUE TITLE
android-sdk cask break my configuration

### ISSUE THREAD

**Issue by Freezystem** [caskroom/homebrew-cask#31547]
Since `android` formula has been replaced with `android-sdk` I'm running into this error when doing a `brew upgrade`:
```
Error: No available formula with the name "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/android"
```
It may be an old reference that has not been cleared but I'm not sure how to fix it.

**Comment by vitorgalvao** [comment]
That’s an error to post on [the core](https://github.com/Homebrew/brew/).
