### ISSUE TITLE
Android tools/bin/avdmanager isn't linked

### ISSUE THREAD

**Issue by bronson** [caskroom/homebrew-cask#31551]
In the android-sdk cask, is there a reason avdmanager isn't linked?  It's found in `$ANDROID_HOME/tools/bin/avdmanager`.

I suppose it would be similar to this line: https://github.com/caskroom/homebrew-cask/blob/3e8fb114a654d1788805b2327a9d997e19f5b62c/Casks/android-sdk.rb#L10

**Comment by vitorgalvao** [comment]
There’s no specific reason anything isn’t done in that cask. It’s quite new. Please PR that omission.
