### ISSUE TITLE
What should ANDROID_HOME be set to now?

### ISSUE THREAD

**Issue by bronson** [caskroom/homebrew-cask#31550]
The old package recommended putting this in your .profile: 

```
    export ANDROID_HOME=/usr/local/opt/android-sdk
    export ANDROID_NDK_HOME=/usr/local/opt/android-ndk
```

With the cask package, that doesn't work anymore.

I worked around it by manually running this:

```
    ln -s /usr/local/Caskroom/android-sdk/25.2.3 /usr/local/opt/android-sdk
```

But that certainly isn't a long term solution.  Is there a better way?

ref: https://github.com/caskroom/homebrew-cask/pull/31126#issuecomment-290027088 and @gyzerok.  And maybe related to https://github.com/caskroom/homebrew-cask/issues/31234

**Comment by gyzerok** [comment]
One way I can think about would be to symlink as @bronson suggested within formula itself. So you have `/usr/local/opt/android-sdk` pointing to the latest installation.

**Comment by yurikoles** [comment]
here is my PR #31598

**Comment by cesar-oyarzun-m** [comment]
@yurikoles Do we have a work around for this? I'm trying to create a build with circle CI and I get 
```
ANDROID_HOME=/opt/homebrew-cask/Caskroom/android-sdk/25.2.3
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /opt/homebrew-cask/Caskroom/android-sdk/25.2.3/tools/templates/gradle/wrapper```

**Comment by yurikoles** [comment]
@cesar-oyarzun-m as I see from similar [question on stackoverflow.com](http://stackoverflow.com/a/42709271/978568) `templates` directory had been removed in 25.3.x series of `android-sdk`.
