### ISSUE TITLE
brew cask create should use double quotes

### ISSUE THREAD

**Issue by waldyrious** [caskroom/homebrew-cask#31594]
While following the instructions from the [adding_a_cask.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) document, I ran into an issue due to using string interpolation inside single quotes -- namely, `#{version}` inside the `url` field.

The error was not very helpful (in terms of helping identify the solution): `Error: Cask 'manictime' definition is invalid: 'url' stanza failed with: bad URI(is not URI?): http://cdn.manictime.com/setup/mac/ManicTime-v#{version}.dmg`.

Fortunately, @Moisan kindly helped me fix the issue on Gitter; but it would be nice if the template defaulted to double quotes so that this subtle distinction doesn't catch other contributors off-guard.

Would such a change (as a PR) be considered?

**Comment by vitorgalvao** [comment]
If it were changed to double quotes, then it would fail when not using a url with interpolation. That said, I think `brew cask style --fix` would auto-fix that one, so yes, I’d be fine with a PR to change that.

**Comment by waldyrious** [comment]
@vitorgalvao thanks, I'll look into submitting one then. Along those lines, would it then make sense to remove the `[]` from the `brew cask style` command in the adding_a_cask.md document, in the [Testing Your New Cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#testing-your-new-cask) section? Currently it reads `brew cask style Casks/my-new-cask.rb [--fix]`, which would leave this issue unfixed (albeit hopefully identified?)

**Comment by gobinathm** [comment]
@waldyrious *[--fix]* is an optional parameter, if we don't pass this parameter ```brew cask style``` will only display the error and won't correct it.

**Comment by waldyrious** [comment]
> I think `brew cask style --fix` would auto-fix that one, so yes, I’d be fine with a PR to change that.

Just to be sure, what change are you talking about exactly? I would like to take a stab at that.

**Comment by vitorgalvao** [comment]
Having a string *without* interpolation and using double quotes is an error, according to our style guide. But `style --fix` corrects it automatically.

**Comment by waldyrious** [comment]
I'm not sure I understood what question you're replying. I meant to ask what exactly did you mean by "change that" in

> I’d be fine with a PR to change that.

In other words: you'd welcome a PR that did what, exactly?

**Comment by vitorgalvao** [comment]
Ah, I mean I’d be fine if you submitted the PR to make `create` use double quotes in `url` by default.

**Comment by waldyrious** [comment]
But then the fix would only be made if the style script was called with the `--fix` parameter (which is currently indicated as optional in the adding_a_cask.md document).

I think following the process described in the documentation should not leave room for such failure (see the message in the first comment of this thread, which is not very helpful), so my suggestion would be to instead add the ability for the style (or audit) script to warn about interpolation within single-quoted strings.

Doesn't that sound like a cleaner solution than changing the `create` script?

**Comment by vitorgalvao** [comment]
> But then the fix would only be made if the style script was called with the `--fix` parameter (which is currently indicated as optional in the adding_a_cask.md document).

It’s not optional, because it’s part of the pull_request_template. You have to run it to submit. It’s also checked by Travis CI.

> add the ability for the `style` (or `audit`) script to warn about interpolation within single-quoted strings.
>
> Doesn't that sound like a cleaner solution than changing the `create` script?

But teaching those about interpolation will require more logic to detect. However, if you prefer that way, I also wouldn’t oppose it. [I have no strong feeling on this particular issue](https://youtu.be/CxK_nA2iVXw).

**Comment by joewiz** [comment]
Thanks for this issue! The single quote error just bit me, and changing it to a double quote fixed the problem. I didn't see anything explicit about this at https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md, so perhaps that page would benefit from a brief mention of this single vs. double quote detail.

**Comment by vitorgalvao** [comment]
> perhaps that page would benefit from a brief mention of this single vs. double quote detail.

This is not an homebrew-cask idiosyncrasy; it’s a *basic* ruby feature shared by other languages. Even `bash` does it this way.

**Comment by joewiz** [comment]
Perhaps something like:

> By default `brew cask create` generates a stanza with single quotes surrounding all values, but if you plan to make use of interpolation for any values (e.g., using `#{version}` in a `url` stanza to refer to the `version` stanza), be sure to switch from single to double quotes. (For more on single vs. double quotes in Ruby, see https://stackoverflow.com/questions/6395288/double-vs-single-quotes.)

**Comment by vitorgalvao** [comment]
@joewiz Like I said, this is a *basic* language feature. Most people don’t have a problem with it, and when they do, they learn it once and don’t forget it. If we added every intrinsic language feature everyone has an ocasional problem with, we’d duplicate the whole Ruby documentation.

**Comment by joewiz** [comment]
@vitorgalvao Fair enough. Thanks for your help as always.
