### ISSUE TITLE
Bug report: templates directory missing from android-sdk

### ISSUE THREAD

**Issue by Whoops** [caskroom/homebrew-cask#31607]
When installing `android-sdk` for some reason it removes or does not install the `templates` directory from the source zip. Among other things this directory contains a `gradle` wrapper used by Cordova, which should be at `/usr/local/Caskroom/android-sdk/25.2.3/tools/templates/gradle/wrapper` but is missing. I've checked the zip file downloaded by the formula, and the templates are included there.

**Comment by plastiv** [comment]
Folder is removed at the recent sdk update (after unziping sdk is self update with sdkmanager). cordova should migrate or complain to google tools team for introducing non compatible update
http://stackoverflow.com/questions/42613882/error-could-not-find-gradle-wrapper-within-android-sdk-might-need-to-update-yo

**Comment by ccorcos** [comment]
@plastiv is cordova-android packages with cordova?
