### ISSUE TITLE
Cask request: QuickLookAddict

### ISSUE THREAD

**Issue by tattali** [caskroom/homebrew-cask#31629]
### Cask details

Name: QuickLookAddict

Homepage: https://github.com/tattali/QLAddict

Download URL: https://github.com/tattali/QLAddict/releases/latest

Description: A QuickLook plugin that lets you view subtitles .srt files

**Comment by gobinathm** [comment]
> > GitHub repository that is not notable enough (< 10 stars)

i believe the Cask won't be approved

**Comment by miccal** [comment]
@gobinathm is correct.

**Comment by vitorgalvao** [comment]
Serious question: why have you made the plugin, when there’s already [`QuicklookStephen`](https://github.com/whomwah/qlstephen) that does the same and more with no (obvious?) drawbacks?

**Comment by tattali** [comment]
with my plugin this is more readable that look like addic7ed presentation.
have you try it ? that obvious there are both different with QuicklookStephen

**Comment by vitorgalvao** [comment]
> have you try it ? that obvious there are both different with QuicklookStephen

I hadn’t, no, you did not have a screenshot when I asked.
