### ISSUE TITLE
Should we put latest stable version in -dev cask? 

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#31772]
For example the latest version of `telegram-destkop-dev` is `1.0.25.alpha`, stable version is higher, `1.0.27`. Should we also put the latest stable version in `telegram-desktop-dev`?

**Comment by commitay** [comment]
Duplicating casks with a different name seems go against the cask being an version. Shouldn't the cask match what the developer has released for that channel?

**Comment by reitermarkus** [comment]
We cannot really enforce this, but this seems to be in line with normal behaviour (i.e. when the app can auto-update and you can select an update channel in-app), so feel free to update those casks that are affected by this, @yurikoles.

> My apologies to the maintainers if I have misunderstood the discussion label, I will remove my comment if it is inappropriate.

No need to apologize, anyone is free to discuss.

**Comment by reitermarkus** [comment]
@caskroom/maintainers, any more input? Otherwise I think we can close this.
