### ISSUE TITLE
Casks for migration to caskroom/drivers.

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#31782]
List of casks to review for migration to `caskroom/drivers`.

Excluded android / arduino / etc casks that are SDKs and phone transfer / backup type software that isn't manufacturer branded which is probably to generic to call a `driver`.

- [x] [casio-screen-receiver.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/casio-screen-receiver.rb)
- [x] [drobo-dashboard.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/drobo-dashboard.rb)
- [x] [escritorio-movistar.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/escritorio-movistar.rb)
- [x] [eye-fi.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/eye-fi.rb)
- [x] [fender-amp-drivers.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fender-amp-drivers.rb)
- [x] [fender-fuse.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fender-fuse.rb)
- [x] [fitbit-connect.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fitbit-connect.rb)
- [x] [garmin-basecamp.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/garmin-basecamp.rb)
- [x] [garmin-communicator.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/garmin-communicator.rb)
- [x] [garmin-express.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/garmin-express.rb)
- [x] [garmin-virb-edit.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/garmin-virb-edit.rb)
- [x] [lightkey.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/lightkey.rb)
- [x] [logitech-control-center.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-control-center.rb)
- [x] [logitech-gaming-software.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-gaming-software.rb)
- [x] [logitech-harmony.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-harmony.rb)
- [x] [logitech-media-server.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-media-server.rb)
- [x] [logitech-myharmony.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-myharmony.rb)
- [x] [logitech-options.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-options.rb)
- [x] [logitech-unifying.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/logitech-unifying.rb)
- [x] [netgeargenie.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/netgeargenie.rb)
- [x] [nike-plus-connect.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/nike-plus-connect.rb)
- [x] [razer-synapse.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/razer-synapse.rb)
- [x] [steelseries-engine.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/steelseries-engine.rb)
- [x] [synology-cloud-station-backup.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/synology-cloud-station-backup.rb)
- [x] [synology-cloud-station-drive.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/synology-cloud-station-drive.rb)
- [x] [synology-photo-station-uploader.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/synology-photo-station-uploader.rb)
- [x] [verizoninhomeagent.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/verizoninhomeagent.rb)
- [x] [wd-my-cloud.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wd-my-cloud.rb)
- [x] [yubico-authenticator.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yubico-authenticator.rb)
- [x] [yubikey-neo-manager.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yubikey-neo-manager.rb)
- [x] [yubikey-personalization-gui.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yubikey-personalization-gui.rb)
- [x] [yubikey-piv-manager.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yubikey-piv-manager.rb)

### Apps
- [x] [bragi-updater.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/bragi-updater.rb)
- [x] [eyetv.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/eyetv.rb)
- [x] [htc-sync-manager.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/htc-sync-manager.rb)
- [x] [sony-ericsson-bridge.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sony-ericsson-bridge.rb)
- [x] [steelseries-exactmouse-tool.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/steelseries-exactmouse-tool.rb)
- [x] [synology-assistant.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/synology-assistant.rb)
- [x] [synologyeiauthenticator.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/synologyeiauthenticator.rb)
- [x] [wd-security.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wd-security.rb)
- [x] [wdfirmwareupdater.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wdfirmwareupdater.rb)
- [x] [yubiswitch.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yubiswitch.rb)

**Comment by vitorgalvao** [comment]
I don’t think you need a Kindle to use the Kindle app.

As a general rule, I don’t think there’s any driver that isn’t either a `pkg` or an `installer`.

**Comment by commitay** [comment]
👍 Removed `kindle` and `kobo`.

**Comment by reitermarkus** [comment]
Also `indigo` is a standalone home automation software.

**Comment by commitay** [comment]
If the list is okay I'll do this sometime during the week.

**Comment by vitorgalvao** [comment]
Thank you again, @commitay.
