### ISSUE TITLE
Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.

### ISSUE THREAD

**Issue by trojanh** [caskroom/homebrew-cask#31798]
#### General troubleshooting steps

- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

After new caskroom/android-sdk changes i was getting the following error while creating Android build,
"Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable."

check this for detailed info: 
https://circleci.com/gh/crossroads/stock.goodcity/1198

#### Output of your command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

**Comment by victorpopkov** [comment]
Try setting your ANDROID_HOME env variable to `/usr/local/share/android-sdk`:

```bash
ANDROID_HOME="/usr/local/share/android-sdk"
```

**Comment by trojanh** [comment]
Thanks @victorpopkov for checking this. I have [already tried that.](https://github.com/crossroads/stock.goodcity/commit/804e2aa3a989a4005b608bfd8a574f9826bfddd0) i also tried[ 'export ANDROID_HOME=/usr/local/Caskroom/android-sdk'](https://github.com/crossroads/stock.goodcity/commit/6687dce0c2659e48b755a4de699a9432a1e48dea) , and also ['/usr/local/android-sdk-linux' ](https://github.com/crossroads/stock.goodcity/commit/350f532808caee5c5b14110676795edd22493d05)

getting same error in all cases.

**Comment by victorpopkov** [comment]
Try in your CircleCI instead of:

```bash
echo 'export ANDROID_HOME=/usr/local/android-sdk-linux'
```

use:

```bash
export ANDROID_HOME=/usr/local/android-sdk-linux
```

Most likely this is the issue since you just echoing instead of setting the environment variable.

**Comment by trojanh** [comment]
Thanks @victorpopkov , I tried 
```
export ANDROID_HOME=/usr/local/share/android-sdk
export PATH=$ANDROID_HOME/build-tools/23.0.1:$PATH >> ~/.circlerc
```
It doesn't work . Fails with the [same error.](https://circleci.com/gh/crossroads/stock.goodcity/1209)
Check [this](https://github.com/crossroads/stock.goodcity/blob/8681e63b846483f3df97d554267f5a5422c8cfe2/circle.yml) just to make sure I am doing things correctly

**Comment by plastiv** [comment]
@trojanh issue seems to be on cordova side. please check this thread: http://stackoverflow.com/questions/42645285/cordova-android-sdk-not-found-make-sure-that-it-is-installed-if-it-is-not-at

You may need to update cordova if you want to use latest android sdk (which introduces incompatible changes, which breaks cordova scripts). Brew installs latest sdk. If you need to downgrade android sdk you shoudn't use brew for installing it then.

**Comment by trojanh** [comment]
Ok Thanks @plastiv . It is really annoying as we can't find any documentation from cordova. Also the above thread isn't helping much. I am debugging manually to find some work around. 

Really appreciate your help though the problem is from Cordova.
