### ISSUE TITLE
Hexchat outdated and --HEAD not working

### ISSUE THREAD

**Issue by Mirppc** [caskroom/homebrew-cask#31906]
First of all the latest hexchat documentation is written to use the /homebrew/homebrew-gui/ which is now a depreciated repository. This is an issue as the version of hexchat in the cask repo is 2.10 and thus is depreciated, for the current stable is 2.12.  One cannot install hexchat with the --HEAD command from homebrew cask install --HEAD hexchat --HEAD --with-python to install the latest version of hexchat. 

The 2.10 version of hexchat in the CASK repo has broken scripting including but not limited to the sysinfo command as well as the version from CASK also having issues connecting to any server.

http://hexchat.readthedocs.io/en/latest/building.html#homebrew

**Comment by miccal** [comment]
The developers are no longer providing macOS builds, so it is being [removed from Cask](https://github.com/caskroom/homebrew-cask/pull/31907).

**Comment by Mirppc** [comment]
Then why isnt the --HEAD working?  That pulls from the git and compiles it from source dealing with all the dependencies.

**Comment by miccal** [comment]
`--HEAD` is a Home-brew command, and is not supported by Cask.

**Comment by Mirppc** [comment]
which is what makes it all the more frustrating that it was pulled from /homebrew/gui to cask making it impossible to use the --HEAD command.
