### ISSUE TITLE
Firefox says Java is not installed

### ISSUE THREAD

**Issue by aristidesfl** [caskroom/homebrew-cask#31931]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Firefox says Java is not installed after `brew cask install java`

#### Output of your command with `--verbose --debug`

`brew cask reinstall java --verbose --debug`
https://gist.github.com/aristidesfl/37715f7c6578272d67f9276a89a0752a

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.11
caskroom/homebrew-cask (git revision a331; last commit 2017-03-14)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (30 files, 1.3GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3606 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="en_US.UTF-8"
PATH="~/.rbenv/shims:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:.:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by vitorgalvao** [comment]
Everything seems fine, and the installation also seemed to go correctly. Nothing indicates this is an issue with HBC.

Try reinstalling java and firefox “by hand” (download them and run the installers yourself, no HBC), but I’d bet on this being an issue from Firefox.

**Comment by aristidesfl** [comment]
Not suggesting it is an issue with HBC, but if the formula doesn't produce the same results as the normal installer, it is an issue with the formula.

**Comment by vitorgalvao** [comment]
> but if the formula doesn't produce the same results as the normal installer, ther is an issue with the formula.

Agreed. That’s why I suggested reinstalling by hand. But we only run the pkg.

**Comment by aristidesfl** [comment]
Turns out Firefox 52 [doesn't support Java anymore](https://www.java.com/en/download/help/firefox_java.xml).

> **Firefox 52 and above**
Beginning with Firefox 52 (released March 2017), plug-in support is limited to Adobe Flash, and drops support for NPAPI, impacting plugins for Java, Silverlight, and other similar NPAPI based plugins.
