### ISSUE TITLE
curl: (7) Couldn't connect to server Error: Download failed on Cask

### ISSUE THREAD

**Issue by monouser7dig** [caskroom/homebrew-cask#31940]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I tried to run 
brew cask reinstall google-chrome-canary

#### Output of your command with `--verbose --debug`
but output was 
```
==> Downloading https://dl.google.com/release2/q/canary/googlechrome.dmg

curl: (7) Couldn't connect to server
Error: Download failed on Cask 'google-chrome-canary' with message: Download failed: https://dl.google.com/release2/q/canary/googlechrome.dmg
The incomplete download is cached at /Users/~/Library/Caches/Homebrew/Cask/google-chrome-canary--latest.dmg.incomplete
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-24-gd84655ef
caskroom/homebrew-cask (git revision e8815; last commit 2017-04-05)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 0B)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3627 casks)
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade (0 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (46 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (178 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Users/~/.gem/ruby/2.0.0/gems/json-2.0.3/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="de_DE.UTF-8"
PATH="/usr/local/opt/ncurses/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

curl generally seems to work, I have the version that ships with macOS, not the dupes version installed 

thanks

**Comment by gobinathm** [comment]
This might be your local Internet connection related issue


```
$ brew cask reinstall google-chrome-canary
==> Downloading https://dl.google.com/release2/q/canary/googlechrome.dmg
######################################################################## 100.0%
==> No checksum defined for Cask google-chrome-canary, skipping verification
==> Moving App 'Google Chrome Canary.app' to '/Applications/Google Chrome Canary.app'.
🍺  google-chrome-canary was successfully installed!
```

**Comment by monouser7dig** [comment]
I can **download using safari** just fine, but the command **still** fails me.
I had this happen once before but don't remember which program it was related to.

**Comment by vitorgalvao** [comment]
Cannot reproduce. Not an issue with HBC, but likely with your setup.

Please [follow this guide](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/curl_error_fix_curlrc.md).

**Comment by monouser7dig** [comment]
well I looked but it does not match, at the end it just says I should submit an issue against the cask but the cask works well in my other machine 

since curl works outside of home-brew I guess it is a HBC issue in some form 

I did these update-reset && update steps but does not seem to save the issue 

anyway thanks

**Comment by vitorgalvao** [comment]
> but the cask works well in my other machine

That is further proof the issue is somewhere with your machine’s config (likely with `curl`), and not HBC.

Try `curl --version` and `which curl` on both. Maybe you’re using different ones (one installed via HB)?

**Comment by monouser7dig** [comment]
curl 7.51.0
>  I have the version that ships with macOS, not the dupes version installed

I also have no .curlrc
