### ISSUE TITLE
Source not there and cannot find it: owasp-zap

### ISSUE THREAD

**Issue by mcolomerp** [caskroom/homebrew-cask#31978]
An "App source" error has been found when installing owasp-zap with brew cask.

URL of the cask:
https://github.com/caskroom/homebrew-cask/blob/master/Casks/owasp-zap.rb

Details:
$ brew cask install owasp-zap --verbose
==> Downloading https://github.com/zaproxy/zaproxy/releases/download/2.6.0/ZAP_2_6_0_macos.dmg
Already downloaded: /Users/.../Library/Caches/Homebrew/Cask/owasp-zap--2.6.0.dmg
==> Verifying checksum for Cask owasp-zap
Error: It seems the App source '/usr/local/Caskroom/owasp-zap/2.6.0/OWASP ZAP.app' is not there.
Error: nothing to install
Error: Kernel.exit

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/31981
