### ISSUE TITLE
Dependent casks and versioning

### ISSUE THREAD

**Issue by sjml** [caskroom/homebrew-cask#32059]
While it is unusual, there are a few casks that are dependent on others in a fundamental way. I'm told Flash and a few others fall into this category, but my own experience is with Unity, so I'll use it for my examples. 

When Cask installs Unity, it grabs only the barest version, because the "approved" way of installing Unity is to use their Download Assistant, which lets you choose options for what to install. Each of these options grabs a different .pkg file from the web for installation; it roughly makes sense since the support packages can be multiple gigabytes and it's silly to waste bandwidth and space on them if you don't use them. 

Cask's approach to this is to make each separate .pkg into a separate cask, which also makes sense. The problem is when the subsidiary packages get out of sync with the main package. We currently have a way of indicating that unity-ios-support-for-editor `depends_on` unity, but that's where it ends. So when a new version of Unity drops, each cask has to be separately updated with the new version number. Since there's rightly no ownership of casks, there's no way to say "if you update unity, also update its dependent casks." 

It could be that this is deemed to be not widespread enough to be worth addressing. If it something worth fixing, I'm happy to prepare a PR, but don't want to do the work if it may not land. 

So question 1 is: is this something the HBC team feels is worth fixing? 

Question 2 is about the best way to solve it. I see two possible solutions, with various levels of problems: 

A. Having a way for casks that depend on another cask to get information about it, in this case the version number. That way the version could simply be updated in the unity cask and all dependent casks would get it automatically. 

B. We add options to casks so that when installing a base cask, a user could specify to *also* install some dependent packages which, as part of the same cask, could use the same versioning data. 

A is probably the simplest to implement, but may break some important rules about isolation of information in casks. 

B could be thorny both to implement and support, but would give the most flexibility going forward, so further dependents (like Unity introducing a new build target) could be added easily to the base cask instead of having to make a new cask. 

Thanks for your time, and my apologies if this is very off the mark. Love the work y'all do.

**Comment by vitorgalvao** [comment]
> It could be that this is deemed to be not widespread enough to be worth addressing.

It’s not widespread at all.

I don’t think this is worth the trouble to implement (and continue supporting). [Having said that](http://youtu.be/ENHVQ2gslp8), you’re offering to do the legwork, and @reitermarkus is currently the most involved with the core itself, so I’ll leave the final decision to him.

> Thanks for your time, and my apologies if this is very off the mark. Love the work y'all do.

Thank you for taking the time to make a good feature request.

**Comment by sjml** [comment]
Continuing the thought process out loud… Option A runs into an issue of how to match the sha256 value, which means even if the version could get pulled from a parent cask, the dependent cask still needs to be updated with the new sha256. I can't think of an easy way around that without moving into something resembling option B. 😕

**Comment by reitermarkus** [comment]
I don't really see a good way to do this. The cask `version` is not made for comparisons other than equality, so we can *reliably* only depend on the latest version of a cask, without adding semantic versioning to casks. Then of course there is the fact that we don't have `upgrade` yet, which would be needed to handle such cases where an outdated dependency is already installed.

I like the idea, but there is just too much that would have to be done in order to support this.
