### ISSUE TITLE
Cask request: [Autopano Giga]

### ISSUE THREAD

**Issue by jmbelloteau** [caskroom/homebrew-cask#32104]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: **Autopano Giga**

Homepage: **http://www.kolor.com/autopano**

Download URL: **http://download.kolor.com/apg/stable/mac**

Description: **Giga version of the famous Panorama software**

**Comment by miccal** [comment]
[What is the difference between Pro and Giga?](http://www.kolor.com/autopano/download/)

**Comment by jmbelloteau** [comment]
The answer is on the bottom of this page:

http://www.kolor.com/autopano/autopano-features/
