### ISSUE TITLE
Having ANOTHER Error (follow up on #32139) when trying to brew cask install android-sdk on mac os x

### ISSUE THREAD

**Issue by HUNTURAI** [caskroom/homebrew-cask#32157]
#### General troubleshooting steps

- [✓] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [✓] None of the templates was appropriate for my issue, or I’m not sure.
- [✓] I ran `brew update-reset && brew update` and retried my command.
- [✓] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [✓] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

this is a follow up on issue #32139 , I resolved the issue at #32139 by moving the android-sdk folder from /usr/local/Caskroom/ to /usr/local/share/, now when I tried to run $brew cask reinstall android-sdk,
I got another error as follows:

==> Verifying checksum for Cask android-sdk
**Error: Operation not permitted** - /usr/local/share/android-sdk
Follow the instructions here:
https://github.com/caskroom/homebrew-cask#reporting-bugs

this time the error is **Operation not permitted**, I have already run **chmod a+x /usr/local/share/android-sdk/** and also applied it to each preceding folder /usr/local etc..., but still getting the same error.

#### Output of your command with `--verbose --debug`

```
$ brew cask reinstall android-sdk --verbose --debug
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_HOME=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
Already downloaded: /Users/jackytsoi/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Downloaded to -> /Users/jackytsoi/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007ff909229318>
#<Hbc::Artifact::Binary:0x007ff909229250>
#<Hbc::Artifact::PostflightBlock:0x007ff9092291b0>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
Error: Operation not permitted - /usr/local/share/android-sdk
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1439:in `unlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1439:in `block in remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1444:in `platform_support'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1438:in `remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:785:in `remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:563:in `block in rm'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `rm'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `block in abstract_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:34:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:28:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:27:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask >1.1.0 (no git repository)
caskroom/homebrew-cask (git revision 009b1; last commit 2017-04-10)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 191.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3625 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Caskroom/android-sdk/tools:/usr/local/Caskroom/android-sdk/platform-tools:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by ishandutta2007** [comment]
I am facing the same issue.

**Comment by ihsanberahim** [comment]
##Temporary/Manual Solution

with `brew cask reinstall android-sdk`,
my homebrew download android-sdk into `~/Library/Caches/Homebrew/Cask/android-sdk...`
I extract the downloaded zip and replace the `tools`.

**Comment by colindunn** [comment]
I cannot reproduce this on Homebrew-Cask stable 1.1.3 (latest released) and I notice that you are on
```
Homebrew-Cask >1.1.0 (no git repository)
```

Was this the product of testing of some kind?

**Comment by HUNTURAI** [comment]
hi @colindunn, thanks for your reply, I tried your suggestion and I moved past the previous error, now I got another error that seems less severe:

brew cask reinstall android-sdk
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_HOME=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Downloading https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
Already downloaded: /Users/jackytsoi/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Verifying checksum for Cask android-sdk
==> Linking Binary 'aapt' to '/usr/local/bin/aapt'.
==> Linking Binary 'aapt2' to '/usr/local/bin/aapt2'.
==> Linking Binary 'aidl' to '/usr/local/bin/aidl'.
==> Linking Binary 'apksigner' to '/usr/local/bin/apksigner'.
==> Linking Binary 'dexdump' to '/usr/local/bin/dexdump'.
==> Linking Binary 'dx' to '/usr/local/bin/dx'.
==> Linking Binary 'llvm-rs-cc' to '/usr/local/bin/llvm-rs-cc'.
==> Linking Binary 'zipalign' to '/usr/local/bin/zipalign'.
==> Linking Binary 'emulator' to '/usr/local/bin/emulator'.
==> Linking Binary 'emulator-check' to '/usr/local/bin/emulator-check'.
==> Linking Binary 'emulator64-arm' to '/usr/local/bin/emulator64-arm'.
==> Linking Binary 'emulator64-mips' to '/usr/local/bin/emulator64-mips'.
==> Linking Binary 'emulator64-x86' to '/usr/local/bin/emulator64-x86'.
==> Linking Binary 'adb' to '/usr/local/bin/adb'.
==> Linking Binary 'dmtracedump' to '/usr/local/bin/dmtracedump'.
==> Linking Binary 'etc1tool' to '/usr/local/bin/etc1tool'.
==> Linking Binary 'fastboot' to '/usr/local/bin/fastboot'.
==> Linking Binary 'hprof-conv' to '/usr/local/bin/hprof-conv'.
==> Linking Binary 'android' to '/usr/local/bin/android'.
==> Linking Binary 'avdmanager' to '/usr/local/bin/avdmanager'.
==> Linking Binary 'lint' to '/usr/local/bin/lint'.
==> Linking Binary 'monkeyrunner' to '/usr/local/bin/monkeyrunner'.
==> Linking Binary 'sdkmanager' to '/usr/local/bin/sdkmanager'.
==> Linking Binary 'mksdcard' to '/usr/local/bin/mksdcard'.
==> Linking Binary 'monitor' to '/usr/local/bin/monitor'.
==> Unlinking Binary '/usr/local/bin/aapt'.
==> Unlinking Binary '/usr/local/bin/aapt2'.
==> Unlinking Binary '/usr/local/bin/aidl'.
==> Unlinking Binary '/usr/local/bin/apksigner'.
==> Unlinking Binary '/usr/local/bin/dexdump'.
==> Unlinking Binary '/usr/local/bin/dx'.
==> Unlinking Binary '/usr/local/bin/llvm-rs-cc'.
==> Unlinking Binary '/usr/local/bin/zipalign'.
==> Unlinking Binary '/usr/local/bin/emulator'.
==> Unlinking Binary '/usr/local/bin/emulator-check'.
==> Unlinking Binary '/usr/local/bin/emulator64-arm'.
==> Unlinking Binary '/usr/local/bin/emulator64-mips'.
==> Unlinking Binary '/usr/local/bin/emulator64-x86'.
==> Unlinking Binary '/usr/local/bin/adb'.
==> Unlinking Binary '/usr/local/bin/dmtracedump'.
==> Unlinking Binary '/usr/local/bin/etc1tool'.
==> Unlinking Binary '/usr/local/bin/fastboot'.
==> Unlinking Binary '/usr/local/bin/hprof-conv'.
==> Unlinking Binary '/usr/local/bin/android'.
==> Unlinking Binary '/usr/local/bin/avdmanager'.
==> Unlinking Binary '/usr/local/bin/lint'.
==> Unlinking Binary '/usr/local/bin/monkeyrunner'.
==> Unlinking Binary '/usr/local/bin/sdkmanager'.
==> Unlinking Binary '/usr/local/bin/mksdcard'.
==> Unlinking Binary '/usr/local/bin/monitor'.
Error: File exists - (/usr/local/Caskroom/android-sdk/25.2.3, /usr/local/share/android-sdk/25.2.3)

**Comment by HUNTURAI** [comment]
``

**Comment by CNG** [comment]
I observed no such directory `/usr/local/share/android-sdk` as the error stated:

    $ sudo find /usr -name "android-sdk"
    /usr/local/Caskroom/android-sdk

I also ran into these errors:

    Error: It seems there is already a Binary at '/usr/local/bin/adb'; not linking.
    Error: It seems there is already a Binary at '/usr/local/bin/fastboot'; not linking.

I deleted the mentioned files and then was able to install:

    $ rm -rf /usr/local/Caskroom/android-sdk
    $ rm -rf /usr/local/bin/adb
    $ rm -rf /usr/local/bin/fastboot
    $ brew cask install android-sdk
