### ISSUE TITLE
Cask request: GoToMeeting

### ISSUE THREAD

**Issue by amysyk** [caskroom/homebrew-cask#32281]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: GoToMeeting

Homepage: https://care.citrixonline.com/gotomeeting

Download URL: https://support.citrixonline.com/en_US/meeting/all_files/G2M010002

Description: online conferencing

**Comment by MTCoster** [comment]
It looks like there are offline installer packages available from [here](https://support.citrixonline.com/en_US/meeting/all_files/G2M010014), I'll make a pr shortly if that pans out

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/32283
