### ISSUE TITLE
Support for non-detached gpg signatures

### ISSUE THREAD

**Issue by rednoah** [caskroom/homebrew-cask#32391]
Do the `url` and `gpg` stanza somehow support embedded gpg signatures?

e.g.
```
gpg --output doc.sig --sign doc
```
This command would create a single file that contains both content and signature:
https://www.gnupg.org/gph/en/manual/x135.html

Verifying and copying the content would look like this:
```
gpg --output doc --decrypt doc.sig
```

**Comment by miccal** [comment]
I think you have posited this in the wrong repository.

**Comment by rednoah** [comment]
I see. brew cask development seems to have moved over to the brew repository. I've had a look at the code and I can confirm that only detached signatures are supported just in case anyone else is wondering.
