### ISSUE TITLE
why :latest ?

### ISSUE THREAD

**Issue by monouser7dig** [caskroom/homebrew-cask#32436]
Which issue is preventing certain casks from being versioned, thus only returning latest?

The documentation states that this is true for casks without a versioned url, however a version could nevertheless be maintained/ assigned?

I've searched back to find an answer but this was the only/ earliest contribution I found 
[https://github.com/caskroom/homebrew-cask/issues/21](url)

thanks

**Comment by reitermarkus** [comment]
> however a version could nevertheless be maintained/ assigned?

The issue is that there is no way we could keep this up-to-date without an `appcast`. And even with an `appcast`, we cannot know the version that will be downloaded from an unversioned URL.

**Comment by monouser7dig** [comment]
so if user would have V1 installed, V1.1 was updated in the repo and the user would perform and upgrade, thinking 1.1 was downloaded whereas in reality V1.2 could be/ is being downloaded because the app might have received yet another update?

thanks for the answer anyway!

**Comment by vitorgalvao** [comment]
> so if user would have V1 installed, V1.1 was updated in the repo and the user would perform and upgrade, thinking 1.1 was downloaded whereas in reality V1.2 could be/ is being downloaded because the app might have received yet another update?

More commonly, the user would have v1 installed and app would be updated upstream to 1.1, but we’d have no idea and not update the cask. Then when another user tried to install the cask, the wrong `sha256` would stop them from installing the cask.

That’s the big issue. With unversioned URLs and no way to check for the app version, the cask breaks constantly.

**Comment by monouser7dig** [comment]
maybe a consideration was to use versions without sha256 checksum (as "latest" does)? 

so users would maybe get more recent versions than they anticipated but at least old ones could get updated when a cask formula is updated in here online?

**Comment by vitorgalvao** [comment]
> maybe a consideration was to use versions without sha256 checksum (as "latest" does not have sha256 either)?

At that point there’s not much point in having versions anyway. Also, we’ve discussed this before and we absolutely do not want to encourage/endorse versioned casks without a checksum. We have a few of them in that position that are commented for the effect.

> so users would maybe get more recent versions than they anticipated but at least old ones could get updated when a cask formula is updated in here online?

They wouldn’t, because the casks would be left forgotten.

If you want said casks to be versioned you can either:

+ Find the versioned URL (many apps have both).
+ Find an appcast.
+ Ask the developer to provide versioned downloads.
+ Ask the developer to provide an appcast.

**Comment by monouser7dig** [comment]
ok
I'd agree casks with checksums are definitely the way to go so your approach is probably best to encourage people to work towards that 

thanks for the explanations
