### ISSUE TITLE
Cask request: [genymotion]

### ISSUE THREAD

**Issue by senpng** [caskroom/homebrew-cask#32444]
### Cask details

Name: genymontion

Homepage: https://genymotion.com

Download URL: http://dl.genymotion.com/releases/genymotion-2.9.0/genymotion-2.9.0.dmg

Description: genymontion update

**Comment by vitorgalvao** [comment]
[It’s been updated four days ago](https://github.com/caskroom/homebrew-cask/pull/32350). You need to `brew update`.
