### ISSUE TITLE
Cask request: [android-studio]

### ISSUE THREAD

**Issue by senpng** [caskroom/homebrew-cask#32443]
### Cask details

Name: android-studio

Homepage: https://developer.android.com/index.html

Download URL: https://dl.google.com/dl/android/studio/install/2.3.1.0/android-studio-ide-162.3871768-mac.dmg

Description: android-studio update

**Comment by vitorgalvao** [comment]
[Same](https://github.com/caskroom/homebrew-cask/issues/32444#issuecomment-294481371). That one has been updated 12 days ago.
