### ISSUE TITLE
sha256 mismatch in deadbeef 

### ISSUE THREAD

**Issue by wodim** [caskroom/homebrew-cask#32518]
The [deadbeef cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/deadbeef.rb) points to

https://downloads.sourceforge.net/deadbeef/travis/osx/master/deadbeef-devel-osx-x86_64.zip

Look, I may not know much about so-called computahs, but that url seems to link to a snapshot of master, which changes every time I commit is made by the developers, so it'll be outdated forever. Either change the link or just remove the checksum check.

**Comment by gobinathm** [comment]
Just wondering if we should make this cask to 
```
version: latest
sha256: no check
```

Multiple reasons

* #30607 changed the version to 1.0, but I'm not seeing any 1.0 on the official site. Not sure if I'm overlooking something
* After that we had 2 more commits which just update SHA256 & CHECKPOINT (#31221 & #31764) 

Any thoughts?  

I can update the PR if we have an agreement on this !!

**Comment by MTCoster** [comment]
The latest release version is 0.7.2, although there are no binaries available for macOS at any version other than the nightlies already used by Cask.

The reason for this is hinted at on [the wiki](https://github.com/Alexey-Yakovenko/deadbeef/wiki/FAQ#os-x-port).  Should this cask possibly be removed?

**Comment by gobinathm** [comment]
We can Take 2 approaches here

* Remove the Cask
* Change the version / sha256 so mismatch issue never occurs. 

I will defer the decision to maintainers.

**Comment by vitorgalvao** [comment]
> although there are no binaries available for macOS at any version other than the nightlies already used by Cask.
> (…)
> Should this cask possibly be removed?

I’d be fine with removal.

**Comment by yurikoles** [comment]
Why to remove? It just works.
I'll suggest move to `-versions` and change it to 

```
version: latest
sha256: no check
```

**Comment by MTCoster** [comment]
It's not been deemed 'complete enough' to be released as a binary yet. If people want to use it anyways, they can still download a nightly build or build it from source themselves as per the project's Github page.

**Comment by vitorgalvao** [comment]
> It's not been deemed 'complete enough' to be released as a binary yet.

That’s the argument that sells the removal, for me.
