### ISSUE TITLE
Remove EAP versions of Jetbrains products?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#32521]
Refs https://github.com/caskroom/homebrew-versions/issues/3630#issuecomment-294826509.

Jetbrains casks are constantly being updated. As such the EAP casks are frequently changed to the stable version and then reset to EAP again when new versions are available. We even have users that concentrate mostly on those updates, but even then it’s a non-trivial amount of work for maintainers.

Normally that alone wouldn’t be grounds for removal, *but* in Jetbrains apps you can change to the update channel you want from inside the app.

![image](https://cloud.githubusercontent.com/assets/1699443/25149257/b0b7fb28-2475-11e7-8f52-562761807d44.png)

So I’d suggest that instead of constantly playing catchup for the EAPs, we remove them and keep only the stable versions. If a user wants an EAP version, we recommend they change the channel from inside the stable version. Jetbrains casks are `auto_updates true` anyway.

**Comment by yurikoles** [comment]
I can say more: there is [Jetbrains Toolbox app](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jetbrains-toolbox.rb) that alows you to install any current branch of any app produced by Jetbrains.

**Comment by leipert** [comment]
As somewhat of a jetbrains cask janitor, I opt for the EAP removal.

**Comment by leipert** [comment]
The only problem is: how we would handle [gogland-eap](https://github.com/leipert/homebrew-versions/blob/master/Casks/gogland-eap.rb), as there is [no stable version (yet)](https://www.jetbrains.com/go/). Either:
1. move it to the normal caskroom
2. leave it in versions and move it once it is stable

**Comment by vitorgalvao** [comment]
@leipert We should move it to the main cask. [We have precedents](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

**Comment by miccal** [comment]
I agree with @vitorgalvao and @leipert.

**Comment by neutric** [comment]
I agree as well.

**Comment by leipert** [comment]
I opened two Pull-Requests:
1. Removal of jetbrains casks from homebrew-versions: https://github.com/caskroom/homebrew-versions/issues/3683
2. Move of gogland: https://github.com/caskroom/homebrew-cask/pull/32564

**Comment by vitorgalvao** [comment]
If one more maintainer agrees, I’d say we can go ahead.

**Comment by vitorgalvao** [comment]
@victorpopkov Approved on the PRs, so this is resolved.

**Comment by leipert** [comment]
Fust fyi: Added support to the @jcbot for gogland eap updates with this release: https://github.com/leipert/jetbrains-cask-bot/commit/f74139c0ad80ca0e0deebf3ace5e936d553bd27f

**Comment by metyl** [comment]
I (and probably other users) like to keep stable version and EAP as separated apps !
To quote Jetbrains: `It is important to distinguish EAP from traditional pre-release software. Please note that the quality of EAP versions may at times be way below even usual beta standards.` so pushing users to change update channel is not good suggestion.

**Comment by leipert** [comment]
Unfortunately it seams not feasible to maintain eap casks, as they break on a regular basis. (See discussion above).

I just tried the jetbrains toolbox (`brew cask install jetbrains-toolbox`) which was mentioned in https://github.com/caskroom/homebrew-cask/issues/32521#issuecomment-294959370. It seems to give a real good access to different versions (either installed via homebrew-cask or the toolbox):

<img width="445" alt="screen shot 2017-04-20 at 17 43 53" src="https://cloud.githubusercontent.com/assets/2906107/25239692/fd5e1ab2-25f0-11e7-9f99-8ffbe29b9cd8.png">

**Comment by metyl** [comment]
First of all there was a problem with **only one build** of **only one cask** (phpstorm-eap) so it is hard to say that they break on a regular basis, but the decision was to put **all** Jetbrains casks into one basket and thrown them away.
There is or rather was community around them and maintenance of these casks went quite well, now all that work and time spent is in a trash bin.

As I understand the whole idea about homebrew and casks: [“To install, drag this icon…” no more!](https://caskroom.github.io) is to make install easy, **command** away **not click** away!

Jetbrains toolbox is nice addition to Jetbrains products but it is an extra software just to install **only Jetbrains products** and it is purely GUI applications so to install any app You must click.
I prefer homebrew and casks as a way to install apps because using it I can install not only Jetbrains products and I don't need any extra software to do it.

Imagine situation that now someone heard about latest EAP of eg. IDEA and wants to install using brew cask:
```
brew cask search intellij eap
No Cask found for "intellij eap".
```
:confused:

In `Docker` You can also switch channel of updates from `stable` to `edge` so `docker-edge` and probably other casks, where You can change update channel in an app, should be removed.

Is this a path `caskroom/homebrew-cask` and `caskroom/homebrew-versions` should follow?

**Comment by vitorgalvao** [comment]
> First of all there was a problem with **only one build** of **only one cask** (phpstorm-eap) so it is hard to say that they break on a regular basis

That is incorrect. As stated on the top post (emphasis added):

> We even have users that concentrate mostly on those updates, **but even then it’s a non-trivial amount of work for maintainers**.

I’m one such maintainer and I regularly see EAP casks having to change `version` and `url` schemes and `names`, even with interpolation. They’re constantly being changed to stable versions and back.

We’ll eventually see if this is such a disruptive change that a significant number of people ask for it back.

In the meantime, you’re free to create your own tap for Jetbrains EAPs.

**Comment by vitorgalvao** [comment]
> Imagine situation that now someone heard about latest EAP of eg. IDEA and wants to install using brew cask

That argument doesn’t hold at all. Imagine someone heard about Audacity or Popcorn Time. Exact same result. Those also have reasons to not be included.

> In `Docker` You can also switch channel of updates from `stable` to `edge` so `docker-edge` and probably other casks, where You can change update channel in an app, should be removed.
>
> Is this a path `caskroom/homebrew-cask` and `caskroom/homebrew-versions` should follow?

Are those casks a maintainability strain? No? Then no.

We need to strike a balance. If a few casks take a high toll **and have a perfectly acceptable alternative to being managed**, then removal is a perfectly valid consideration, especially since taps (which I’ve stated again and again are my favourite HB feature) are a thing.

**Comment by joh-klein** [comment]
Does anyone maintain a tap for Jetbrains EAPs?

**Comment by leipert** [comment]
No, not of my knowledge @joh-klein. I could expand the @jcbot to do that pretty easily.

However I see no real benefit in doing that. I could be persuaded however if there is pizza and beer involved (See https://github.com/leipert/jetbrains-cask-bot/issues/3)
