### ISSUE TITLE
Cannot uninstall lightkey 1.6.3 - and others

### ISSUE THREAD

**Issue by colindunn** [caskroom/homebrew-cask#32537]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I have been having trouble with uninstalling a few casks which performing cask updates (lightkey being one of them) and had thought that it was due to the recent 10.12.4 update. I have finally managed to set up a clean system with 10.12.3 and the same problem exists so the issue is unrelated to the minor version upgrade.

Turns out that `plist/parser.rb` is not handling the plist, at least for 10.12.3 and 10.12.4, if the plist file ends up in ascii rather than utf8. Applying the below diff fixes uninstall but of course this is a brew issue rather than a hbc issue.

This same issue affects a few other casks that I have found as well: tableau-public, drobo-dashboard, resolume-avenue, plover.

Just wondering if anyone has advice on this issue, or should I just raise it in Homebrew?

```
diff --git a/Library/Homebrew/vendor/plist/plist/parser.rb b/Library/Homebrew/vendor/plist/plist/parser.rb
index de441fc..7bd60fd 100644
--- a/Library/Homebrew/vendor/plist/plist/parser.rb
+++ b/Library/Homebrew/vendor/plist/plist/parser.rb
@@ -86,7 +86,7 @@ module Plist

       require 'strscan'

-      @scanner = StringScanner.new( @xml )
+      @scanner = StringScanner.new( @xml.force_encoding("utf-8") )
       until @scanner.eos?
         if @scanner.scan(COMMENT_START)
           @scanner.scan(COMMENT_END)
```

#### Output of your command with `--verbose --debug`

```
$ brew cask uninstall lightkey --verbose --debug
==> Uninstalling Cask lightkey
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask lightkey
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007f8ba7019a98>
#<Hbc::Artifact::Pkg:0x007f8ba7019b10>
#<Hbc::Artifact::Zap:0x007f8ba7019a20>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for lightkey; your password may be necessary
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=de.monospc.lightkey.pkg.App"]
de.monospc.lightkey.pkg.App
==> Executing: ["/usr/sbin/pkgutil", "--export-plist", "de.monospc.lightkey.pkg.App"]
Error: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `scan'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:29:in `parse_xml'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:160:in `_parse_plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:131:in `plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:75:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:66:in `pkgutil_bom_all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:54:in `pkgutil_bom_files'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:17:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew doctor
Your system is ready to brew.
```

**Comment by commitay** [comment]
Same error as the recent `mactex` issues.

https://github.com/caskroom/homebrew-cask/issues/32371 https://github.com/caskroom/homebrew-cask/issues/32073 https://github.com/caskroom/homebrew-cask/issues/31888

And a couple of others.

https://github.com/caskroom/homebrew-cask/issues/31228 https://github.com/caskroom/homebrew-cask/issues/30901

**Comment by colindunn** [comment]
It looks like the current solution to this is to just remove the cask, but as far as I can tell there is nothing wrong with the packages having their xml in ascii as far as OSX is concerned.

What I don't get is why this hasn't come up before. I've worked on those casks previously without issue and the vendored plist hasn't changed in 8 months.

**Comment by commitay** [comment]
> but as far as I can tell there is nothing wrong with the packages having their xml in ascii as far as OSX is concerned.

Concur.

From https://github.com/caskroom/homebrew-cask/issues/31228#issuecomment-288895235 

> It's me. I was on master branch and not on tag 1.1.11. Once I switched to that tag all is well.

**Comment by colindunn** [comment]
Sorry @commitay not sure that I understand the reference to this issue with that comment reference?

**Comment by commitay** [comment]
#31228 is the same ASCII error but when they changed to a tag release from master it worked for them. I'm probably wrong be I'm wondering if something was changed since the 1.1.11 tag for this to occur.

**Comment by vitorgalvao** [comment]
There have been somewhat significant refactorings between `1.1.11` and `1.1.12`, so it‘s likely something broken there. Pinging @reitermarkus.

**Comment by colindunn** [comment]
I can confirm that changing brew to tag 1.1.11 allows lightkey to be uninstalled. Thanks @commitay I didn't get where you were going there

**Comment by reitermarkus** [comment]
It was in fact my refactoring which caused this. This seems like strange behaviour from `pkgutil`:

```bash
$ pkgutil --export-plist de.monospc.lightkey.pkg.App > /tmp/export-plist.plist
$ pkgutil --pkg-info-plist de.monospc.lightkey.pkg.App > /tmp/pkg-info-plist.plist
$ file -I /tmp/*.plist
/tmp/export-plist.plist:   application/xml; charset=utf-8
/tmp/pkg-info-plist.plist: application/xml; charset=us-ascii
```

Ruby reports the exact opposite, apparently; `--export-plist` returns an `ASCII 8-BIT` string, while `pkg-info-plist` returns `UTF-8`.

**Comment by colindunn** [comment]
Interestingly I see that the [plist gem](https://rubygems.org/gems/plist) is at 3.2.0 but the repo source only has releases to 3.1.0. master branch shows a 3.2.0 version though.

I hacked in 3.2.0 to see if it might help but no good.

**Comment by reitermarkus** [comment]
I'm working on a PR for the [upstream `plist` repo](https://github.com/patsplat/plist).
