### ISSUE TITLE
Airmail cask

### ISSUE THREAD

**Issue by danielb2** [caskroom/homebrew-cask#32597]
Ref: #5655

there seems to be several instances of casks where there's a HEAD. Does this not qualify to be in the cask system for any reason? Frankly, I want to have this beta installed, and I'm sure others do too. It's much easier to use casks for this, and it's definitely inline with the spirit of casks / homebrew where it should be easy to download the apps.

**Comment by reitermarkus** [comment]
> Does this not qualify to be in the cask system for any reason?

I'm not sure what you mean exactly, Airmail was moved to [`caskroom/versions`](https://github.com/caskroom/homebrew-versions):

https://github.com/caskroom/homebrew-versions/pull/349

**Comment by danielb2** [comment]
Oh I see now. I wasn't aware of the existence of this project. What's the reason of separating them?   It doesn't appear that the versions is publicized anywhere, so how is one supposed to know?

**Comment by vitorgalvao** [comment]
> It doesn't appear that the versions is publicized anywhere, so how is one supposed to know?

It’s in [`adding_a_cask`](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#beta-unstable-development-nightly-or-legacy), [`CONTRIBUTING`](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask), and [`USAGE`](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#additional-taps-optional).

**Comment by danielb2** [comment]
Maybe move additional taps into the README would be useful. The other versions at least really affects how it's used

**Comment by vitorgalvao** [comment]
@danielb2 Truth is most people who can’t find a particular thing in the documentation say it should be more visible elsewhere. If we did that every time, every document would have every piece of information in the project. This is not a common issue, so not worth adding to the README. If there were more people with this problem, we’d consider it.

https://github.com/caskroom/homebrew-cask/issues/16732 is a better solution, anyway.

**Comment by danielb2** [comment]
Agreed on that being a better solution. And understood about the README
