### ISSUE TITLE
Feature request: Add --installation-path option to anaconda formula

### ISSUE THREAD

**Issue by wedi** [caskroom/homebrew-cask#32699]
Hi.

### Description of feature/enhancement

Add an option to change the path the [Anaconda](https://github.com/caskroom/homebrew-cask/blob/master/Casks/anaconda.rb) installation script installs _itself_ to.

### Justification
By default the Anaconda installation script installs to ~/anaconda[3]. Users who don’t want software installed in their home directory, which is not meant to contain software, have no option to change this path atm. Luckily the install script offers to change this path by supplying a `-p PREFIX` option but it is not supported by the anaconda formula.

From Anaconda's usage message:

    -p PREFIX    install prefix, defaults to /Users/dirk/anaconda3

_Unfortunately I don’t know ruby and haven’t found documentation about adding options to formulas so I cannot do it myself._

### Example use case

Installing anaconda to `/opt/anaconda[3]` to avoid polluting one's home directory.

**Comment by vitorgalvao** [comment]
> adding options to formulas 

We don’t have formulas, we have casks. Those don’t support install flags, and there’s no plans to introduce the feature.

**Comment by vitorgalvao** [comment]
But we can make it install somewhere else by default. https://github.com/caskroom/homebrew-cask/pull/32706
