### ISSUE TITLE
jce-unlimited-strength-policy should install the policy for the JRE

### ISSUE THREAD

**Issue by yanokwa** [caskroom/homebrew-cask#32720]
#### Description of issue

Oracle Java is installed in two locations depending on if you choose to install the JRE or JDK.
* JRE: `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/`
* JDK: `/Library/Java/JavaVirtualMachines/jdk1.x.x_xxx.jdk/Contents/Home/`
  * If you install the JDK, it will also install the JRE at the JRE location listed above.

The JRE allows you to double-click to open jars from the Finder and run Java in the browser, but the JRE does not come with the `java` binary. If you want to run any of the typical Java commands, you must install the JDK.

When you run `brew cask install jce-unlimited-strength-policy`, the casks only installs the unlimited policy files for running the Java from the command line. It does not install the policy for opening jars from the Finder or running Java in the browser and I believe it should.

**Comment by miccal** [comment]
All Cask does is install the program as if you had downloaded it yourself - do you also have this issue if you install them manually?

**Comment by yanokwa** [comment]
This Cask is a little different than others, because the JCE is just two files you copy to arbitrary directories and a readme that says...
```
The standard place for JCE jurisdiction policy JAR files is:
        <java-home>/lib/security           [Unix]
        <java-home>\lib\security           [Windows]
```
So the question is, what is your `java-home` if you are installing manually. Well, it depends (see https://java.com/en/download/faq/yosemite_java.xml). On recent versions of macOS (10.10 and greater)...

* If you only have the JRE, you'd likely install the files at `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/`. The Cask does not do that and I think it should.
* If you have the JDK (and thus the JRE), you'd likely install the files at `/Library/Java/JavaVirtualMachines/jdk1.x.x_xxx.jdk/Contents/Home/` and stop there. But you'd get different behavior if you ran apps via double-click vs via the command line. You'd probably then go poking around the web and realize you should also install the JCE files in the JRE location. The Cask only installs it in the JDE location, and I'm filing this request because I think it should also install it in the JRE location.
