### ISSUE TITLE
Error: Cannot tap caskroom/cask: invalid syntax in tap!

### ISSUE THREAD

**Issue by ClementLeBihan** [caskroom/homebrew-cask#32840]
On a fresh macos Sierra install, I get the following error whenever I try to install a cask 
```
brew tap caskroom/cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3741, done.
remote: Compressing objects: 100% (3725/3725), done.
remote: Total 3741 (delta 34), reused 385 (delta 12), pack-reused 0
Receiving objects: 100% (3741/3741), 1.26 MiB | 1.75 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Checking connectivity... done.
Error: Cannot tap caskroom/cask: invalid syntax in tap!
```

**Comment by vitorgalvao** [comment]
Don’t `tap`, just run any `brew cask` command. Also:

> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by ClementLeBihan** [comment]
Thank you for your answer ! I'm following the installation guide for Yarp on OSX, and I just copied this line ...

However, I can't install Yarp, I got this message : 
```
brew install yarp
Error: No available formula with the name "yarp" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

I know it's not about cask, but do you have an idea ? I've never used brew :/

**Comment by vitorgalvao** [comment]
> brew install yarp

See how there’s no `cask` in that command? You’re in the wrong repo.

See https://github.com/Homebrew/brew/issues/2087 and https://github.com/Homebrew/brew/issues/2529.

**Comment by vitorgalvao** [comment]
[It has been fixed](https://github.com/Homebrew/brew/issues/2529#issuecomment-296400386).

**Comment by ClementLeBihan** [comment]
In my case, I still have the Error message ...

**Comment by neutric** [comment]
You ran `brew cask install yarp`, right?

**Comment by ClementLeBihan** [comment]
No, it doesn't work :/

```
brew cask install yarp
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3741, done.
remote: Compressing objects: 100% (3725/3725), done.
remote: Total 3741 (delta 34), reused 385 (delta 12), pack-reused 0
Receiving objects: 100% (3741/3741), 1.26 MiB | 1.87 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Checking connectivity... done.
Error: Cannot tap caskroom/cask: invalid syntax in tap!
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/tap.rb:239:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by vitorgalvao** [comment]
@neutric There’s no `yarp` cask. There’s a formula, and even then it’s not in the main repos, [you have to tap it from them](https://github.com/robotology/yarp#installation).

> In my case, I still have the Error message ...

@ClementLeBihan Again, **this is absolutely the wrong repo**. Please direct your messages to the issues I linked you to and stop posting here. This is not related to us!

**Comment by ClementLeBihan** [comment]
> YARP Installation
> See full instructions at http://www.yarp.it/install.html
> 
> On macOS:
> ```
> brew tap robotology/cask
> brew install yarp
> ```

This is not related to cask ?

**Comment by neutric** [comment]
@vitorgalvao Sorry for the confusion, I assumed that is what you wanted to tell Clement. Should have checked it first before recommending stuff. ☕️  overdue.

**Comment by neutric** [comment]
@ClementLeBihan Their naming is misleading, [this](https://github.com/robotology/homebrew-cask/blob/master/yarp.rb) is a formula from non-Cask Homebrew.

**Comment by vitorgalvao** [comment]
> This is not related to cask ?

No. It’s related to Hombrew, not Homebrew-Cask. [You even said you know it’s not related to Homebrew-Cask](https://github.com/caskroom/homebrew-cask/issues/32840#issuecomment-296399669).

I’ve already pointed you to the correct repo, and even the correct issues multiple times. At this point I feel like you’re doing a bit.

@neutric No worries, I also had to search for it to make sure. I also noticed their confusing naming and am now submitting issues and PRs.

**Comment by ClementLeBihan** [comment]
Ok, I give up ... I don't understand but don't want to disturb you ;)

Thank you for your help ! Best

**Comment by vitorgalvao** [comment]
@ClementLeBihan I don’t get what you don’t understand. Just click the links!

Click [here](https://github.com/Homebrew/brew/issues/2529) and expose your problem in **that** page.

**Comment by ClementLeBihan** [comment]
It's about `brew tap homebrew/bundle ` ... My issue is about `brew tap caskroom/cask`

**Comment by vitorgalvao** [comment]
> It's about `brew tap homebrew/bundle ` ... My issue is about `brew tap caskroom/cask`

No, your issue is about `brew tap`, **period**. That’s the feature breaking for you. And even if it were about `brew tap caskroom/cask`, [I’ve already told you to not run that particular command](https://github.com/caskroom/homebrew-cask/issues/32840#issuecomment-296399356).

You said [you’ve never used Homebrew before](https://github.com/caskroom/homebrew-cask/issues/32840#issuecomment-296399669), and I’m a maintainer. Don’t you think that by this time you should’ve already taken my advice to have your issue looked at?

I have no desire to spend the rest of my day [inside a Monty Python sketch](https://youtu.be/kQFKtI6gn9Y?t=1m42s), so respectfully, this is the last time I’ll tell you to **ask your question on the repo I linked you to**, as it is the correct one.

**Comment by MikeMcQuaid** [comment]
Run `brew update` if you're still experiencing this.

**Comment by ClementLeBihan** [comment]
My Homebrew is `Already up-to-date.`. I'm gonna expose my problem in the Yarp GitHub page. Thank you for your help
