### ISSUE TITLE
Skype is out of date

### ISSUE THREAD

**Issue by DIWesser** [caskroom/homebrew-cask#32906]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
~~- [ ] I ran `brew update-reset && brew update` and retried my command.~~
~~- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.~~
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The cask for skype currently set to install version 6.15.0.335. The current version is 7.50.461.

**Comment by commitay** [comment]
`skype` will only install `6.15.0.335` if you are running `mountain lion`, otherwise it installs the lastest version.

```
  if MacOS.version <= :mountain_lion
    version '6.15.0.335'
    sha256 '592abdd157df12d718576a86c8f8e62fced55292fd7e6909d53aa5eaaa9218f4'
    url "https://download.skype.com/macosx/Skype_#{version}.dmg"
  else
    version :latest
    sha256 :no_check
    url 'https://www.skype.com/go/getskype-macosx.dmg'
  end
```

**Comment by DIWesser** [comment]
So it does. My mistake.
