### ISSUE TITLE
Cask request: ClipMenu

### ISSUE THREAD

**Issue by ahmetb** [caskroom/homebrew-cask#32963]
### Cask details

Name: ClipMenu

Homepage: http://www.clipmenu.com/

Download URL: https://dl.dropbox.com/u/1140644/clipmenu/ClipMenu_0.4.3.dmg

Description: ClipMenu is a clipboard history manager.

I wonder what happened to this cask. I think it used to be present.

**Comment by commitay** [comment]
`clipmenu` cask was removed with https://github.com/caskroom/homebrew-cask/pull/30972 

Download url returns 404.

**Comment by ahmetb** [comment]
For future reference, `clipy` is the successor product and is an active fork of ClipMenu. https://github.com/Clipy/Clipy

ClipMenu maintainer has showed no online presence in the past 3 years. Good thing the code was open source and there is an active fork.
