### ISSUE TITLE
Cask request: Paint 2

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#33247]
### Cask details

Name: Paint 2

Homepage: http://trybestapps.com/paint-pro/

Download URL: https://dl.dropboxusercontent.com/u/26475986/Paint%20Pro.app.zip

Note: Paint 2 is the free version of Paint Pro.

Description: "Paint Pro is an easy-to-use paint tool and image editor which can help you to draw pictures and edit your existing photos. With it you can sketch and crop, rotate, scale images very easily. Besides, you can and text onto images as you want. The app also supports layers, so you can re-edit them freely."

**Comment by commitay** [comment]
Download URL returns 404.

**Comment by gobinathm** [comment]
There is a Mac App Store version available.
