### ISSUE TITLE
Cask request: Pastebot

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#33252]
### Cask details

Name: Pastebot

Homepage: https://tapbots.com/pastebot/

Download URL: https://tapbots.net/pastebot2/Pastebot.dmg

Description: "If copy & paste is a part of your workflow, Pastebot is an indispensible tool to improve your productivity. Quickly recall clippings that you have copied before and apply powerful text filters to format before pasting. Queue up multiple clippings to paste in sequence. Pastebot is always running and only a keyboard shortcut away to command copy & paste."

Description (Alternative): "Command Copy & Paste."

**Comment by commitay** [comment]
Previously removed https://github.com/caskroom/homebrew-cask/issues/27945

**Comment by vitorgalvao** [comment]
> Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.
