### ISSUE TITLE
Cask request: DaVinci Resolve Studio

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#33251]
### Cask details

Name: DaVinci Resolve Studio

Homepage: https://www.blackmagicdesign.com/products/davinciresolve

Download URL: http://sw.blackmagicdesign.com/DaVinciResolve/v12.5.5/DaVinci_Resolve_Studio_12.5.5_Mac.zip

Download Instructions: Go to https://www.blackmagicdesign.com/products/davinciresolve, click "Download" button, click "Mac OS X" button under DaVinci Resolve 12.5.5 Studio, click "Download Only" link on bottom left.

Description: "DaVinci Resolve 12.5 Studio combines professional video editing with the world’s most advanced color corrector and incredible new effects so now you can edit, color correct, add effects and deliver projects from start to finish, all in one single software tool! This massive new update features 1,000 enhancements and 250 new features that make editing faster and color better than ever before!"

**Comment by commitay** [comment]
Ref previous PR for this https://github.com/caskroom/homebrew-cask/pull/8753

Download URL is randomly generated and expiring.
