### ISSUE TITLE
Cask request: FontBase

### ISSUE THREAD

**Issue by maebert** [caskroom/homebrew-cask#33321]
### Cask details

| Name | FontBase |
|:-----|:------|
| **Homepage** | http://fontba.se |
| **Download URL** | http://releases.fontba.se/mac/2.0.0/FontBase-2.0.0.dmg |
| **Description** | A blazing fast, beautiful and free font manager for designers. |

![Fontbase](https://embedwistia-a.akamaihd.net/deliveries/c6e536a789654939c8a5a08222fbce80017038b3.jpg)

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/33322

I was genuinely excited for that app, but after opening it I can say it looks like one of the worst apps I’ve ever opened. I’m on a retina screen and everything is blurry, the top buttons have tooltips (what?) and those are cutoff by the window itself. I couldn’t even look at it for long. It’s flat colours and text, how is it even possible to make such a blurry mess from that? And it’s a `2.0`!

**Comment by vitorgalvao** [comment]
On another note, thank you for posting the details in a table. Way clearer! I’d change our template to use a table if I didn’t think it might trip less experienced users.

**Comment by maebert** [comment]
Thanks for adding this. I agree this app needs a lot of work - but I hope that by giving it wider distribution it might eventually get there!

**Comment by vitorgalvao** [comment]
Seems like [the blurriness might be a bug](https://twitter.com/FontBaseApp/status/859479847550300161).
