### ISSUE TITLE
Automate the installation of VirtualBox extension pack with cask

### ISSUE THREAD

**Issue by yangm97** [caskroom/homebrew-cask#3333]
It is as simple as running VBoxManage extpack install name-of-extpack

**Comment by retrography** [comment]
+1

**Comment by yanana** [comment]
+1

**Comment by delitescere** [comment]
What I do in bash after `brew cask install virtualbox`:

```bash
(
  cd /tmp;
  vbox_full_version=$(brew cask info virtualbox | head -1 | cut -d' ' -f2);
  vbox_short_version=${vbox_full_version/-*};
  curl -L -O http://download.virtualbox.org/virtualbox/${vbox_short_version}/Oracle_VM_VirtualBox_Extension_Pack-${vbox_full_version}.vbox-extpack;
  sudo VBoxManage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack-${vbox_full_version}.vbox-extpack;
  rm *.vbox-extpack;
)
```

**Comment by draistrick-fd** [comment]
@delitescere - thanks for that josh, very useful.

now any chance we can get a brew cask install virtualbox-extensionpack that does that? ;-)

**Comment by keen99** [comment]
@delitescere - thanks for that josh, very useful.

now any chance we can get a brew cask install virtualbox-extensionpack that does that? ;-)

**Comment by vitorgalvao** [comment]
Unlikely unless we get a PR, @delitescere. This is really low priority (`0`, I’d say) and no maintainer seem to have the time or inclination to work on it.

**Comment by ftc2** [comment]
yeah?
https://github.com/caskroom/homebrew-cask/pull/12806
done

**Comment by Ngrd** [comment]
Thank you, @ftc2! This cask does the job very well. I guess, this issue can be closed for now. Feel free to open it if some additional problems with the current solution will occur.
