### ISSUE TITLE
Cask request: Headset

### ISSUE THREAD

**Issue by 3zero2** [caskroom/homebrew-cask#33416]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Headset

Homepage: http://headsetapp.co

Download URL: https://github.com/headsetapp/headset-electron/releases/download/v1.5.2/Headset-1.5.2.dmg

Description: Headset is a desktop app that turns YouTube into a world class music streaming service. Listen to everything YouTube has to offer on a beautiful user interface that's built for productivity. Create collections, tune-in to a music subreddit or quickly play that song you’ve had stuck in your head all day!

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/commit/2164cd2903985d946e96fa2b18fd207e5c47594a
