### ISSUE TITLE
Cask request: Processing

### ISSUE THREAD

**Issue by kapziel** [caskroom/homebrew-cask#33430]
### Cask details

Name: Processing 

Homepage: Processing.org

Download URL: http://download.processing.org/processing-3.3.3-macosx.zip

Description: Processing is a flexible software sketchbook and a language for learning how to code within the context of the visual arts. Since 2001, Processing has promoted software literacy within the visual arts and visual literacy within technology. There are tens of thousands of students, artists, designers, researchers, and hobbyists who use Processing for learning and prototyping.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/processing.rb
