### ISSUE TITLE
Replace hardcoded path in ManOpen formula?

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#33451]
Hello,

I observed that current formula for ManOpen (`manopen.rb`) is finishing with:
``
artifact 'openman.1', target: '/usr/local/share/man/man1/openman.1'
``

Is it better to decide to put systematically this man page there, or instead to follow `HOMEBREW_PREFIX` that could turn out to be different from `/usr/local` for some users, like `jtool.rb` does?

``
artifact 'openman.1', target: "#{HOMEBREW_PREFIX}/share/man/man1/openman.1"
``

P.S. It appears that currently, more formulae use hard-coded path like `manopen.rb` than variable-based like `jtool.rb`

**Comment by vitorgalvao** [comment]
Small nitpick. They’re casks, not formulae. They’re different and behave differently, and when you mention the latter rather than the former, it makes me think you’re in the wrong repo reporting a bug over something that isn’t related to us.

As for your question, yes, they should be variable-based. Care to submit a PR?

**Comment by Yann-R** [comment]
> Small nitpick. They’re casks, not formulae.

Arg, my mistake: confused by using more frequently `brew` than `brew cask` ;-)

> they should be variable-based. Care to submit a PR?

OK, I can do my best to prepare it ASAP.

**Comment by Yann-R** [comment]
@miccal, many thanks for this really fast commit updating manopen.rb

I thought that @vitorgalvao was speaking of "all the casks" with this common modification when writing "they souble be variable-based. Care to submit a PR?"

I'm likely to prepare it (as a whole or separately) for the following casks in the next few days:
```
cargo.rb:  artifact "#{Utils.distname}/cargo/share/man/man1/cargo.1", target: '/usr/local/share/man/man1/cargo.1'
cmucl.rb:  artifact 'lib/cmucl', target: '/usr/local/lib/cmucl'
jad.rb:  artifact 'jad.1', target: '/usr/local/share/man/man1/jad.1'
ncar-ncl.rb:  artifact 'include', target: '/usr/local/ncl-6.3.0/include'
rar.rb: ...
```

**Comment by vitorgalvao** [comment]
Yes, I meant all of them.
