### ISSUE TITLE
What process change is being made to prevent infections?

### ISSUE THREAD

**Issue by christianbundy** [caskroom/homebrew-cask#33565]
From #33354:
> A mistake was made here and everyone involved has learned from it and are currently working on changing the process so it cannot happen again.

It looks like the conversation was locked, but I think as a community it's important to know which process changes are made. I'm surprised that the community isn't allowed to be involved in the discussion, but I think that we should _at least_ be told what the behind-closed-doors policy change is. Thanks for your work on this project.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/33536 and https://github.com/caskroom/homebrew-cask/pull/33538.

**Comment by vitorgalvao** [comment]
> It looks like the conversation was locked

It was locked for a specific reason that was mentioned in that issue. Either way, that PR was far from the best place to have the discussion, as few would see it.

> but I think as a community it's important to know which process changes are made.

No one disagrees with that.

> I'm surprised that the community isn't allowed to be involved in the discussion

It is, as seen by the issue. No one is stopping anyone from discussing.

> but I think that we should at least be told what the behind-closed-doors policy change is.

It’s not being done behind closed doors. It’ll be a public policy change, as seen by the PR.

> Thanks for your work on this project.

You’re welcome. Thank you for being a user and making your questions with civility (many wouldn’t).
