### ISSUE TITLE
Cask request: NoteApp

### ISSUE THREAD

**Issue by mkk** [caskroom/homebrew-cask#33655]
Name: NoteApp

Homepage: http://www.apptorium.com/noteapp

Download URL: http://www.apptorium.com/products/noteapp/download

Description: An incredibly simple text editor

**Comment by vitorgalvao** [comment]
Please don’t request your own apps. If anyone has interest in them, they’ll add them or request them. If no one has, it’ because so far they have been of no value to our users.

Also, don’t add the `?ref=cask` to the download URL. Those aren’t the official downloads on the pages.
