### ISSUE TITLE
Cask request: Expressions

### ISSUE THREAD

**Issue by mkk** [caskroom/homebrew-cask#33654]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Expressions

Homepage: http://www.apptorium.com/products/expressions

Download URL: http://www.apptorium.com/products/expressions/trial

Description: An app to play with regular expressions. Easily and nicely.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/33655#issuecomment-300018367

**Comment by mkk** [comment]
I had a request from app user (https://twitter.com/derimagia/status/859251648060952577), so I added it. 
The ref was added to have information where the user downloads the app from. Is it bad, really?

**Comment by vitorgalvao** [comment]
> The ref was added to have information where the user downloads the app from. Is it bad, really?

I never said it was bad. I asked you not to do it. We try to only use canonical download URLs that users can verify, for security reasons.

**Comment by mkk** [comment]
OK, so let it be without query. http://www.apptorium.com/products/expressions/trial is fine. Could you reopen this request?
