### ISSUE TITLE
Could brew cask introduce Microsoft Remote Desktop app?

### ISSUE THREAD

**Issue by Coresi7** [caskroom/homebrew-cask#33685]
Could brew cask introduce Microsoft Remote Desktop app for us?
https://itunes.apple.com/us/app/microsoft-remote-desktop/id715768417?mt=12
because it's only available on american store. And requires an american apple id to download it.

**Comment by miccal** [comment]
We cannot add App Store-only apps to Cask.

**Comment by rayfoss** [comment]
@miccal copyright reasons or implementation difficulties?

**Comment by reitermarkus** [comment]
The latter, but you can use [`mas`](https://github.com/mas-cli/mas) instead.

**Comment by rayfoss** [comment]
@reitermarkus Thanks for the tip... it looks promising, but you still need an Apple login to use it. That said it does looks like it could make it simpler to say... run a CI job on a free docker that generates a static site with a bunch of highly requested DMGs, then perhaps see if a free CDN such as cloudflare would be cool with it.
