### ISSUE TITLE
What about brew cask desc?

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#33725]
Hello,

I've been pleased when `brew` decided to integrate the new `desc` information in formulae, so as to give a one-line short description of the installed software. This is useful, and avoid opening the homepage most of the time.

What about adding also `desc` information in casks for such descriptions, displayed by `brew cask desc ...`. This could be optional, but working when present, and let the maintainers slowly fill these new description field in the casks ?

P.S. Didn't find another issue dealing with that point, but I may have missed it.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md

**Comment by Yann-R** [comment]
Woahhh, of course I was pretty sure I wasn't the only one thinking of it.
How my searches did not reach this discussion (and others related to it).

My mistake. Sorry for the noise.
And many thanks for the link.
