### ISSUE TITLE
cuda uninstall leaves app behind

### ISSUE THREAD

**Issue by adamlwgriffiths** [caskroom/homebrew-cask#33774]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

After uninstalling Cuda (#33278), I am still presented with the Cuda install / update dialog on each boot.

Gist of `mdfind -name cuda` before uninstall:
https://gist.github.com/adamlwgriffiths/f647f357d6ec784b4c101ca6755d16c9#file-after-brew-cask-install-cuda

and after uninstall:
https://gist.github.com/adamlwgriffiths/f647f357d6ec784b4c101ca6755d16c9#file-after-brew-cask-uninstall-cuda

#### Output of your command with `--verbose --debug`

https://gist.github.com/adamlwgriffiths/f647f357d6ec784b4c101ca6755d16c9#file-brew-cask-uninstall-cuda-verbose-debug

#### Output of `brew cask doctor`

https://gist.github.com/adamlwgriffiths/f647f357d6ec784b4c101ca6755d16c9#file-brew-cask-doctor

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/33880

**Comment by adamlwgriffiths** [comment]
Thank you, confirmed working after running `brew update-reset && brew update`
