### ISSUE TITLE
Visual Studio update

### ISSUE THREAD

**Issue by karbassi** [caskroom/homebrew-cask#33841]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - x ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Visual Studio for Mac stable has been [released today](https://blogs.msdn.microsoft.com/visualstudio/2017/05/10/visual-studio-for-mac-now-generally-available/) (May 10, 2017). 

Microsoft download urls don't follow a pattern that I know of. The download link directs to: https://aka.ms/vs/mac/download but that will redirect. 

I personally don't know how to update the cask using this pattern as it's a little confusing.

Should we just use the 'latest' pattern rather than a version number?

#### Output of your command with `--verbose --debug`

```bash
$ curl -vLI https://aka.ms/vs/mac/download 2>&1 | egrep '^(Location:|HTTP)'
HTTP/1.1 301 Moved Permanently
Location: https://dl.xamarin.com/VsMacInstaller/VisualStudioInstaller.dmg
HTTP/1.1 302 Found
Location: https://download.microsoft.com/download/5/b/c/5bc09d89-3bf4-4ab9-bda5-8bd9b0e8eb87/VisualStudioInstaller.dmg
HTTP/1.1 200 OK
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/33878
