### ISSUE TITLE
Suggestion to update Adobe Acrobat cask names

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#34037]
I'd like to suggest that the Adobe Acrobat Pro and Adobe Acrobat Reader cask names be updated for clarity.

- [ ] `adobe-acrobat` cask renamed to `adobe-acrobat-pro`
- [ ] `adobe-reader` cask renamed to `adobe-acrobat-reader`

Let me know if this would be a good suggestion.

**Comment by vitorgalvao** [comment]
No objections from me.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/34071
