### ISSUE TITLE
Cask request: Skyfonts

### ISSUE THREAD

**Issue by afdallah** [caskroom/homebrew-cask#34049]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: SkyFonts

Homepage: https://skyfonts.com/

Download URL: http://cdn1.skyfonts.com/client/Monotype_SkyFonts_Mac64_5.9.1.0.dmg

Description: SkyFonts is a handy, lightweight utility that runs in the background of your Mac or PC and allows you to temporarily install desktop fonts and sync them on up to two of your devices.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/skyfonts.rb
