### ISSUE TITLE
Cask request: Cura

### ISSUE THREAD

**Issue by Clumsy-Coder** [caskroom/homebrew-cask#34078]
### Cask details

Name: Cura 3D printing slicing software (GUI)

Homepage: https://ultimaker.com/en/products/cura-software

Download URL: https://ultimaker.com/en/products/cura-software/download-request/134

Description: Convert 3D models into Gcode for a 3D printer to print

**Comment by commitay** [comment]
[Cura](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cura.rb)

**Comment by Clumsy-Coder** [comment]
Yes, I just found out. Sorry about that.
I typed 
brew search cura
I guess it didn't search the cask section.
Ignore this issue please. Thanks

**Comment by commitay** [comment]
> Ignore this issue please. Thanks

No problem. You can close the issue yourself using the button below. ⬇️
