### ISSUE TITLE
Error: No available Cask

### ISSUE THREAD

**Issue by hanxue** [caskroom/homebrew-cask#34162]
First opened in #33520 - apologies, lost track of the issue. 

Performing and hard reset on the git repository does not help:

```shell
$ cd "$(brew --repository)"
$ pwd
/usr/local/Homebrew
$ git fetch; git reset --hard origin/master;
HEAD is now at 1e6cf8f270 Merge pull request #2635 from MikeMcQuaid/no-set-blank-vars
$ brew update
Updated 3 taps (caskroom/cask, caskroom/drivers, caskroom/versions).
$ brew cask list
Error: No available Cask for aimersoft-youtube-downloader
```

**Comment by miccal** [comment]
Have you ever installed `aimersoft-youtube-downloader` via Cask? I cannot find _any_ information about a Cask ever called `aimersoft-youtube-downloader`?

**Comment by numbermaniac** [comment]
What's the output of `cd /usr/local/Caskroom; ls`? Is there an `aimersoft-youtube-downloader` folder present?

**Comment by miccal** [comment]
Closing due to lack of response.
