### ISSUE TITLE
More intelligent AIR installations

### ISSUE THREAD

**Issue by vmrob** [caskroom/homebrew-cask#3421]
I just recently sent in #3420 and am hoping to have a more intelligent AIR installation mechanism and, as such, I would like to bounce some ideas before I start on any actual code.

Currently Adobe AIR apps require the Adobe AIR runtime environment to be installed and, currently, we have no way to detect if it is or isn't.  This is where the above mentioned redistribution helper comes in.  Conveniently, the tool allows us to determine the presence of the runtime via `arh -isRuntimeInstalled` and takes the form of an exit status.  Zero represents an installed runtime whereas non-zero (1 in my tests) represents no installed runtime.

Another great property about this tool is that it can supposedly determine the installation status of an application as well as install that application.  I assume it does so by forwarding the request to the appropriate installer.  I'm still trying to understand / use this feature.

My idea here is that the AIR application installer should first install the arh, then use that tool to determine if the runtime is installed.  Then, install the adobe-air cask if the runtime isn't present and finally use the arh utility to install the actual AIR app.

Does the functionality exist to determine if a particular cask is installed?  How about actually installing a prerequisite cask?  Finally, is there a good way to query the location of an installed cask?

**Comment by vitorgalvao** [comment]
AIR installations seem to work fine, now. Please correct me if I’m wrong.
