### ISSUE TITLE
Update postbox to 5.0.14

### ISSUE THREAD

**Issue by Zettt** [caskroom/homebrew-cask#34293]
I am unable to contribute something myself to the repository, so I write this issue. The current version of Postbox is 5.0.14. Please someone update its cask.

Thanks in advance.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/34295

**Comment by vitorgalvao** [comment]
> I am unable to contribute something myself to the repository

Why?

**Comment by Zettt** [comment]
@commitay Thank you very much!
