### ISSUE TITLE
Cask request: OpenVPN

### ISSUE THREAD

**Issue by johndjameson** [caskroom/homebrew-cask#34319]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: OpenVPN

Homepage: https://openvpn.net/

Download URL: http://swupdate.openvpn.net/privatetunnel/client/privatetunnel-mac-2.8.dmg

Description:

> OpenVPN Technologies has designed and deployed a virtual network software that provides secure, reliable, and scalable communication services, not only fulfilling the requirements of the traditional virtual private network (VPN) market, but also addressing the demands of next wave web-scale VPN services. OpenVPN, our award-winning open source VPN product, has established itself as a de-facto standard in the open source networking space, with over 3 million downloads since inception.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/privatetunnel.rb
