### ISSUE TITLE
Armitage r150813 subject to JDK-8179084, can we patch here?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [caskroom/homebrew-cask#34322]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

So, [this is an upstream bug](https://bugs.openjdk.java.net/browse/JDK-8179084); but it's one that directly affects macOS users, since macOS apparently ships with Java **1.8u131**. The [officially recommended](https://blog.cobaltstrike.com/2017/04/26/java-startup-bug-in-java-1-8u131/) solution is to [downgrade the system Java to 1.8u121](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u121-oth-JPR); I doubt that's acceptable to most users.

At the moment, the Armitage package uses the app-installer provided by the developer; in addition to the above issue, this package doesn't provide the documented `armitage`-bin artifact. If we add a custom `armitage` script to the package, we can fix this ourselves until upstream ships a new version — and tbh, this is something that should be included for parity with the Windows and Linux 
releases, *anyway*, imho:

```sh
#!/usr/bin/env sh
java '/Applications/Armitage.app/Contents/Java/armitage.jar' '-XX:ParallelGCThreads=8'
# Obviously, update the `java` path and the `Armitage.app` path to use Homebrew's settings
```

#### Output of your command with `--verbose --debug`

```
> brew cask install armitage --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading http://www.fastandeasyhacking.com/download/armitage150813.dmg
==> Calling curl with args ["http://www.fastandeasyhacking.com/download/armitage150813.dmg", "-C", "0", "-o", "#<Pathname:/Users/ec/Library/Caches/Homebrew/Cask/armitage--15.08.13.dmg.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.1-7-g2b72638 (Macintosh; Intel Mac OS X 10.12.5) curl/7.51.0 --fail http://www.fastandeasyhacking.com/download/armitage150813.dmg -C 0 -o /Users/ec/Library/Caches/Homebrew/Cask/armitage--15.08.13.dmg.incomplete
######################################################################## 100.0%
==> Downloaded to -> /Users/ec/Library/Caches/Homebrew/Cask/armitage--15.08.13.dmg
==> Verifying download
==> Determining which verifications to run for Cask armitage
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask armitage
==> SHA256 checksums match
==> Installing Cask armitage
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/ec/Library/Caches/Homebrew/Cask/armitage--15.08.13.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/ec/Library/Caches/Homebrew/Cask/armitage--15.08.13.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/ec/Library/Caches/Homebrew/Cask/armitage--15.08.13.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/xt/wm01x2h50nv993t_csb1t5qm0000gn/T/20170517-78440-csrbfa.list", "--", "/var/folders/xt/wm01x2h50nv993t_csb1t5qm0000gn/T/20170517-78440-1kllic6.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/xt/wm01x2h50nv993t_csb1t5qm0000gn/T/20170517-78440-1kllic6.bom", "--", "/private/tmp/dmg.FJv8z1", "/usr/local/Caskroom/armitage/15.08.13"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.FJv8z1"]
==> Creating metadata directory /usr/local/Caskroom/armitage/.metadata/15.08.13/20170517180550.761.
==> Creating metadata subdirectory /usr/local/Caskroom/armitage/.metadata/15.08.13/20170517180550.761/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask armitage
==> 1 artifact/s defined
#<Hbc::Artifact::App:0x007ff03b1e45f0>
==> Installing artifact of class Hbc::Artifact::App
==> Moving App 'Armitage.app' to '/Applications/Armitage.app'.
🍺  armitage was successfully installed!
```

#### Output of `brew cask doctor`

```
Warning: Your XQuartz (2.7.7) is outdated.
Please install XQuartz 2.7.9 (or delete the current version).
…

Warning: Unbrewed dylibs were found in /usr/local/lib.
…
Unexpected dylibs:
  /usr/local/lib/libSoapySDR.0.6.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
…
Unexpected header files:
  /usr/local/include/mirsdrapi-rsp.h

Warning: You have a curlrc file
…

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
…
```

**Comment by ELLIOTTCABLE** [comment]
FWIW, I know very little about Java, or how to make it work — the command-line `java -version` on my Sierra box claims `java version "1.8.0_92"`, which seems to be a different one than the system-wide one described in the “Java Control Panel” on macOS …

Meanwhile, neither do I understand how Java's flags get passed — there's the Info.plist for Armitage.app, which has a `JVMOptions` key; but my changes to that seemed to be ignored completely … nor does passing the `-XX:ParallelGCThreads=8` flag to `Contents/MacOS/JavaAppLauncher` have any effect. wtf.

**Comment by commitay** [comment]
I cannot reproduce this.
```
java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by ELLIOTTCABLE** [comment]
Isn't the command-line java is a different version, though? Is that the
same version reported by the macOS System Preferences control-panel?

**Comment by commitay** [comment]
Testing in a VM, it is the only version of java installed.
