### ISSUE TITLE
Cask request: Mockuuups Studio

### ISSUE THREAD

**Issue by skrzyszewski** [caskroom/homebrew-cask#34481]
### Cask details

Name: Mockuuups Studio

Homepage: https://mockuuups.studio/

Download URL: https://mockuuups.studio/download/mac

Description: Drag-and-drop tool for creating beautiful app previews and marketing materials.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/mockuuups-studio.rb
