### ISSUE TITLE
Cask request: Lookback

### ISSUE THREAD

**Issue by skrzyszewski** [caskroom/homebrew-cask#34493]
### Cask details

Name: Lookback

Homepage: https://lookback.io

Download URL: https://deungs2vexe3s.cloudfront.net/apps/mac/Lookback-1.88.0.31.g5e60c5a.app.zip

Description: Simple, powerful user research. Unlimited testing on any device with anyone in the world.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/34504
