### ISSUE TITLE
brew cu state ignored

### ISSUE THREAD

**Issue by alphatea** [caskroom/homebrew-cask#34533]
<img width="625" alt="qq20170520-234759 2x" src="https://cloud.githubusercontent.com/assets/27395080/26277051/e7002520-3db6-11e7-8876-64b3f6163b91.png">

I want upgrade pycharm， but the state [ignored].....

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also, `brew-cu` is an external tool. Any bugs or issues need to be reported to them.
