### ISSUE TITLE
Add virustotal codesign to documentation

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#34554]
Refs https://github.com/caskroom/homebrew-cask/pull/33570.

To add to the [updating the sha256 documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256) that another vector for proving an update is to submit the download file to [virustotal](https://www.virustotal.com/en/) and give us the link. Since the virustotal evaluation shares the sha256, we can compare it to the one in the cask to verify the user uploaded the correct file. This will only be valid if the app is codesigned (virustotal tells us the signer in the “File Detail” tab).

**Comment by commitay** [comment]
I'll do this sometime in the next couple of days. Would a screenshot be appropriate to properly illustrate the "File Detail" codesigning?

**Comment by vitorgalvao** [comment]
> Slightly off-topic question: Is it possible to have a `[awaiting verification]` label for PRs rather than using `[on hold]` and `[upstream]`?

Done.

> Would a screenshot be appropriate to properly illustrate the "File Detail" codesigning?

Yes.
