### ISSUE TITLE
Casks with (possibly) dead `homepage`'s

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#34626]
Below is a list of Casks where the `url` is valid but the `homepage` is not:

 - [x] [cctalk](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cctalk.rb)
- [x] [dterm](https://github.com/caskroom/homebrew-cask/blob/master/Casks/dterm.rb)
- [x] [idocument-plus](https://github.com/caskroom/homebrew-cask/blob/master/Casks/idocument-plus.rb)
- [x] [minerva](https://github.com/caskroom/homebrew-cask/blob/master/Casks/minerva.rb)
- [x] [sketchpacks](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sketchpacks.rb)
- [x] [snapz-pro-x](https://github.com/caskroom/homebrew-cask/blob/master/Casks/snapz-pro-x.rb)
- [x] [sparkbox](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sparkbox.rb)
- [x] [story-writer](https://github.com/caskroom/homebrew-cask/blob/master/Casks/story-writer.rb)
- [x] [time-relic](https://github.com/caskroom/homebrew-cask/blob/master/Casks/time-relic.rb)
- [x] [wiretap-studio](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wiretap-studio.rb)

Some help with alternative `homepage`'s would be appreciated.

**Comment by vitorgalvao** [comment]
Removing:

+ `dterm`. Last update was in 2011 and it does not work in Sierra.
+ `idocument-plus`. Appears to be dead (old twitter account, old MAS versions).
+ `minerva`. Already had the `discontinued` `caveat`, so no point in trying to resurrect.
+ `sparkbox`. Same developer as `idocument-plus`.
+ `timerelic`. Seemed to be very active on twitter up until May 2015, with a sudden drop off. Seems to be dead.

Back up / working for me:

+ `cctalk`.
+ `story-writer`.

Contacting:

+ `sketchpacks` ([on twitter](https://twitter.com/homebrewcask/status/866249696209235968)). https://sketchpacks.herokuapp.com/ works, but I don’t see a download link for the app itself.
+ `snapz-pro-x` ([on twitter](https://twitter.com/homebrewcask/status/866253204266389504)).
+ `wiretap-studio` (same developer as `snapz-pro-x`.

**Comment by miccal** [comment]
Thanks @vitorgalvao.

**Comment by vitorgalvao** [comment]
> Though the `cctalk` and `story-writer` `homepage`'s are (still) not working for me...

Both of those are Chinese. Not sure why that would have any relevance, but it’s something in common that might give you a clue.

**Comment by vitorgalvao** [comment]
[`sketchpack` should be fixed soon](https://twitter.com/sketchpacks/status/866347335495720960).

**Comment by miccal** [comment]
The `homepage` for `sketchpacks` is back up.

**Comment by commitay** [comment]
`cctalk` and `story-writer` are both working for me.

**Comment by miccal** [comment]
@giannitm no I do not, but I do know some Chinese websites do not work well in Australia.

**Comment by commitay** [comment]
`snapz-pro-x` and `wiretap-studio` are back up.

**Comment by miccal** [comment]
All done then, thanks to all who helped.
