### ISSUE TITLE
Cyberduck: where are bookmarks stored?

### ISSUE THREAD

**Issue by JustinTBrown** [caskroom/homebrew-cask#34684]
#### General troubleshooting steps

- [x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x ] None of the templates was appropriate for my issue, or I’m not sure.
- [x ] I ran `brew update-reset && brew update` and retried my command.
- [x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I'm wondering where bookmarks and preferences are stored. I'd like to import my bookmarks from a previous machine. After reviewing [CyberDuck's FAQ](https://trac.cyberduck.io/wiki/help/en/faq#Preferencesandapplicationsupportfileslocation) and the [source for this cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cyberduck.rb) I'm still unable to find the designated directory. I'm on Sierra 10.12.5.

#### Output of your command with `--verbose --debug`

```
N/A
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.1
caskroom/homebrew-cask (git revision feab9; last commit 2017-05-21)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (37 files, 1.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3614 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-completions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_CA.UTF-8"
PATH="~/.rvm/gems/ruby-2.3.3/bin:~/.rvm/gems/ruby-2.3.3@global/bin:~/.rvm/rubies/ruby-2.3.3/bin:~/.nvm/versions/node/v7.10.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:~/bin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:~/.rvm/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by JustinTBrown** [comment]
I figured it out. My mistake. I was looking in system `/Library` instead of the user `~/Library`. Sorry for the interruption!

**Comment by vitorgalvao** [comment]
We have no control over that anyway. This was always a question for the cyberduck devs and not us.

**Comment by JustinTBrown** [comment]
Yeah that makes sense. I wasn't sure if brew perhaps changed where preferences, etc. were usually stored so I thought I'd check.




On Sun, May 21, 2017 at 6:26pm, Vítor Galvão < notifications@github.com [notifications@github.com] > wrote:
We have no control over that anyway. This was always a question for the cyberduck devs and not us.
