### ISSUE TITLE
Cask request: Marvel

### ISSUE THREAD

**Issue by skrzyszewski** [caskroom/homebrew-cask#34788]
### Cask details

Name: Marvel

Homepage: https://marvelapp.com/prototype-with-sketch/

Download URL: https://storage.googleapis.com/sketch-plugin/Marvel.zip

Description: Sync designs. Play prototypes. Record flows. Marvel for Sketch is the ultimate companion for prototyping.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/issues/34789
