### ISSUE TITLE
The lilypond cask should use the stable version

### ISSUE THREAD

**Issue by svenax** [caskroom/homebrew-cask#34820]
The casks here should only use stable versions of programs, right?

There is a cask in `homebrew-versions` called **lilypond-dev** that was just updated and uses the development version.

**Comment by miccal** [comment]
That is what `homebrew-versions` is for.

**Comment by svenax** [comment]
Yes, exactly. So, the cask here should be changed back to the stable version (2.18.2.-1), since it now tracks the development version (2.19.61-1).

**Comment by miccal** [comment]
Ah, I see what you mean - https://github.com/caskroom/homebrew-cask/pull/34821.

Thanks for letting us know.
