### ISSUE TITLE
Camtasia is at version 3.0.6

### ISSUE THREAD

**Issue by Zettt** [caskroom/homebrew-cask#34827]
I don't understand how to update the casks myself, so here's an update to an existing cask. The version number on https://github.com/caskroom/homebrew-cask/blob/cbd7c946c5ed9282e57118faa17eaaab2f317427/Casks/camtasia.rb is 3.0.6 now.

Sorry I am unable to provide more information.

**Comment by commitay** [comment]
> https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help

# use to update <outdated_cask>
cask-repair <outdated_cask>
```

https://github.com/caskroom/homebrew-cask/pull/34829
