### ISSUE TITLE
Cask request: Authy Desktop

### ISSUE THREAD

**Issue by maartenpaauw** [caskroom/homebrew-cask#34919]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Authy Desktop

Homepage: https://authy.com/

Download URL: https://s3.amazonaws.com/authy-electron-repository-production/stable/1.0.10/darwin/x64/installer.dmg

Description: Two-Factor authentication desktop application.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/34923
