### ISSUE TITLE
Cask request: Karabiner

### ISSUE THREAD

**Issue by dnivi3** [caskroom/homebrew-cask#34939]
### Cask details

Karabiner is a powerful utility for keyboard customization.

Name: Karabiner

Homepage: https://github.com/tekezo/Karabiner

Download URL: https://github.com/tekezo/Karabiner/releases/tag/version_10.22.0

Description: Karabiner is a powerful utility for keyboard customization.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/karabiner.rb

**Comment by dnivi3** [comment]
@commitay: Thanks, for some reason it did not show up when I was searching for it. I may have misspelled the name.
