### ISSUE TITLE
Cask request: HomeBank

### ISSUE THREAD

**Issue by mhouSK** [caskroom/homebrew-cask#35015]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: HomeBank

Homepage: http://homebank.free.fr/

Download URL: homebank (already an Homebrew package)

Description: Free, easy, personal accounting for everyone

HomeBank is already an Homebrew package but not yet supported by Cask.
Application iconset could be assembled from the source code : http://bazaar.launchpad.net/~mdoyen/homebank/main/files/head:/pixmaps/

Thanks!

**Comment by vitorgalvao** [comment]
> Download URL: homebank (already an Homebrew package)

Why would we add it here, then? We strive to not have duplicates.

Either way, they don’t distribute binaries, so we couldn’t add it even if we wanted to.
