### ISSUE TITLE
Cask request: Tad

### ISSUE THREAD

**Issue by adius** [caskroom/homebrew-cask#35122]
Name: Tad
Homepage: http://tadviewer.com
Download URL: https://github.com/antonycourtney/tad/releases/download/v0.8.4/tad-0.8.4.dmg
Description: MIT Licensed desktop application for viewing and analyzing tabular data.

**Comment by vitorgalvao** [comment]
[Added almost a month ago](https://github.com/caskroom/homebrew-cask/pull/33461).

**Comment by adius** [comment]
Ups, sorry, my fault. Searched with `brew search` and not with `brew cask search`.
