### ISSUE TITLE
brew cask list produces Error: No available Cask for icon

### ISSUE THREAD

**Issue by faxotherapy** [caskroom/homebrew-cask#35140]
Hello,

for unknown reasons to me, when I type in `brew cask list` I've got the following output: `Error: No available Cask for icon` instead of showing me the list of apps installed.

Any idea?

Thanks for your help.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by faxotherapy** [comment]
I had the brilliant idea to set a beautiful colourful folder icon for the *Caskroom* folder. That's the reason for the issue. I thus removed my customised icon folder and everything is now fine.

So, mister **vitorgalvao**, it's a bug I believe that should be fixed.

Even though you decided to unilaterally close the issue without giving me the time to get back to you with what I should have been provided, I thought you'd be happy to know this. But, maybe, because I still haven't provided what I should normally provide, you will not take account of this bug!

Have a great day!
