### ISSUE TITLE
Cask request: Symantec VIP

### ISSUE THREAD

**Issue by zlotnika** [caskroom/homebrew-cask#35186]
Name: Symantec VIP

Homepage: https://m.vip.symantec.com

Download URL: https://m.vip.symantec.com/downloadsMac

Description: This is a two-factor authentication used by many corporate offices.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35187

**Comment by zlotnika** [comment]
![thanks](https://media4.giphy.com/media/3osxYdXvsGw6wT5lIY/200.gif#4-grid1)
