### ISSUE TITLE
Make Atom.app default editor for homebrew

### ISSUE THREAD

**Issue by BLCKPSTV** [caskroom/homebrew-cask#35231]
Could there be a detailed instruction in to defaulting the brew editor in for example Atom.app.

Because I create more problems with vim than I make solutions with...

**Comment by vitorgalvao** [comment]
Set `HOMEBREW_EDITOR` to `atom` in your shell’s startup files.

Also, wrong repo. You wanted https://github.com/Homebrew/brew/.
