### ISSUE TITLE
cask I have created not installing app from dmg

### ISSUE THREAD

**Issue by PortableDoor** [caskroom/homebrew-cask#35264]
Hello,

I have decided to start contributing packages (when I can) to homebrew-cask. Currently, I decided to try and add the FPS tesseract from https://tesseract.gg 
To make matters simpler, I decided to go with the latest stable build, which does date back a bit, which I know is not ideal- but I hope you can understand me by wanting to do something simpler for my first time, as the others are all nightly builds that require some form of compilation.

Currently, this is my code:
########################################
_cask 'tesseract' do
  version :latest
  sha256 'ed770d66a32ed894b0d64893d29c188c6c61922319cf3155bc4ab61292033486'

  url "http://download.tuxfamily.org/tesseract/tesseract_2014_05_11_first_edition_macosx.dmg"
  name 'Tesseract'
  homepage 'http://tesseract.gg'

  app 'Tesseract.app'
end_
########################################

As you can see, I have correctly referenced the name of the app, as I saw in the creating_a_cask(?).md, as well as closely referencing the google-chrome.rb file (ignoring the 'zap' part). However, when I test run this code, homebrew-cask only downloads the dmg (which it names correctly), and does the checksum (which succeeds)- but the actual application itself is not installed.

Thank you for any help anyone can give me.

**Comment by arilotter** [comment]
Using this exact cask file (which seems to be identical to yours), I can successfully `brew cask install tesseract`. I'm not sure what's wrong with your system configuration / your cask file explicitly.
```
cask 'tesseract' do
  version :latest
  sha256 'ed770d66a32ed894b0d64893d29c188c6c61922319cf3155bc4ab61292033486'

  url 'https://download.tuxfamily.org/tesseract/tesseract_2014_05_11_first_edition_macosx.dmg'
  name 'Tesseract'
  homepage 'http://tesseract.gg/'

  app 'Tesseract.app'
end
```

```
$ brew cask install tesseract
==> Downloading https://download.tuxfamily.org/tesseract/tesseract_2014_05_11_f
######################################################################## 100.0%
==> Verifying checksum for Cask tesseract
==> Installing Cask tesseract
==> Moving App 'Tesseract.app' to '/Applications/Tesseract.app'.
🍺  tesseract was successfully installed!
```
```
$ brew cask uninstall tesseract
==> Uninstalling Cask tesseract
==> Removing App '/Applications/Tesseract.app'.
```

**Comment by PortableDoor** [comment]
I see. That is quite strange. How exactly are you running the script. Is it through a fetch, or are you adding it to your forked repository of this page? I was using the fetch (which might be why it just installed the dmg) command because for some reason I cannot manage to set up my git fork as a remote for cask- but that's a different matter altogether. Thank you for your help though :) 👍

**Comment by arilotter** [comment]
Here's the exact steps I took

1. Downloaded the Tesseract DMG from the url in your post
1. Copied `Tesseract.app` to my `/Applications` folder
1. `$ /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/developer/bin/generate_cask_token '/Applications/Tesseract.app/'	`
1. Deleted `Tesseract.app` from my `/Applications` folder.
1. `$ shasum -a 256 ~/Downloads/tesseract_2014_05_11_first_edition_macosx.dmg | pbcopy`
1. `$ brew cask create tesseract`
1. Pasted the sha256 sum from my clipboard & filled in the rest of the cask file
1. `$ brew cask install tesseract` ✅ 

I'm sure the shasum part doesn't matter since we have the same sum, but I went through the whole process myself just to make sure I wasn't missing anything.

**Comment by PortableDoor** [comment]
Your method seems to be working fine. I had instead chosen to edit a fork of Homebrew-cask, adding my own file through an IDE. I was confused when it did not sync. However, most importantly, when manually using fetch to retrieve the file, it did not seem to work. Perhaps it was just a one time bug, or simply the nature of the 'fetch' command.

I was hence wondering if it is normal for my fork of the original git not to 'sync' itself- so that I would have access to all files I modified on it? If you feel the question is inappropriate for this issue, or there are no more problems to solve related to the original matter, please comment below, and I will close the issue.

Thank you for what you have done so far :)

**Comment by reitermarkus** [comment]
Seems to be resolved.
