### ISSUE TITLE
coyim formula has wrong sha256 value

### ISSUE THREAD

**Issue by jonnybarnes** [caskroom/homebrew-cask#35352]
```
$ brew cask reinstall coyim
==> Downloading https://dl.bintray.com/twstrike/coyim/v0.3.8/mac-bundle/coyim.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask coyim
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 80ef836252349f867cd48a2532b65505aceac480c25b02472a1416b88d3e9494
Actual: 1238d6d67087c38a003eafa54286b492342e2f62ddcb0d4a0fcacde07591fdf1
File: /Users/jonny/Library/Caches/Homebrew/Cask/coyim--0.3.8.dmg
To retry an incomplete download, remove the file above.
```

`brew update` has been retried for a couple of days now.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35359
