### ISSUE TITLE
Try to run brew cask install eclipse-java

### ISSUE THREAD

**Issue by kirykr** [caskroom/homebrew-cask#35363]
and I got this error
```curl: (7) Failed to connect to mirrors.opencas.org port 80: Operation timed out
Error: Download failed on Cask 'eclipse-java' with message: Download failed: https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/3/eclipse-java-neon-3-macosx-cocoa-x86_64.tar.gz&r=1
Error: nothing to install
---
Any idea?

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
