### ISSUE TITLE
Move plantronics-hub to homebrew-drivers?

### ISSUE THREAD

**Issue by LouisStAmour** [caskroom/homebrew-cask#35433]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I think `plantronics-hub` should be updated and moved to `homebrew-drivers`

```
$ pkgutil --payload-files /Volumes/Plantronics\ Software/Plantronics\ Software.pkg | grep 'kext'
./Contents/Resources/PlantronicsDriverShield.kext
./Contents/Resources/PlantronicsDriverShield.kext/Contents
./Contents/Resources/PlantronicsDriverShield.kext/Contents/_CodeSignature
./Contents/Resources/PlantronicsDriverShield.kext/Contents/_CodeSignature/CodeResources
./Contents/Resources/PlantronicsDriverShield.kext/Contents/Info.plist
./Contents/Resources/PlantronicsDriverShield.kext/Contents/MacOS
./Contents/Resources/PlantronicsDriverShield.kext/Contents/MacOS/PlantronicsDriverShield
./Contents/Resources/PlantronicsDriverShield.kext/Contents/Resources
./Contents/Resources/PlantronicsDriverShield.kext/Contents/Resources/en.lproj
./Contents/Resources/PlantronicsDriverShield.kext/Contents/Resources/en.lproj/InfoPlist.strings
```

I'd submit a PR but I'm not sure of the process when it spans multiple repos. Also, have yet to read up on the markup used by `homebrew-drivers` with these kext sections. I wonder if there's room to automatically look at pkg files to determine what kexts they contain, as above?

**Comment by commitay** [comment]
Migrated to `caskroom/drivers` with https://github.com/caskroom/homebrew-cask/pull/35434 and https://github.com/caskroom/homebrew-drivers/pull/72

> I think `plantronics-hub` should be updated

`version` is `:latest`

>  I wonder if there's room to automatically look at pkg files to determine what kexts they contain, as above?

[uninstall.md#uninstall-key-kext](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-kext)

**Comment by LouisStAmour** [comment]
Actually your comment indicates what I meant by "updated" -- I meant that it ships with a `kext` as I wrote above, but the kext isn't listed under the `uninstall` stanza. And as I've gotten uncomfortably familiar with the `pkgutil` command over the past few hours writing and debugging https://github.com/caskroom/homebrew-drivers/pull/73, I was wondering if it would be possible to write a test case that runs `pkgutil --payload-files` on the included `pkg` entry and if it finds `*.kext` inside, to issue a warning that `homebrew-drivers` exists and/or that the `kext` is missing from the `uninstall` if it is.
