### ISSUE TITLE
Feature request: flag to autolaunch app-installer

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#35445]
### Description of feature/enhancement
Please allow to pass a flag that will allow to autolaunch app-installer.

### Justification
It will be faster to speed-up install of example packages mentioned below by taking assumption that user **may** want to run app-installer after cask is installed.

### Example use case
Example casks `adobe-creative-cloud`, `battle-net`, `vmware-fusion`. So example command may be: 
```
brew cask install battle-net --auto-launch-installer
```

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/issues/24377
