### ISSUE TITLE
No more --language option?

### ISSUE THREAD

**Issue by fdagnat** [caskroom/homebrew-cask#35448]
`brew cask install --force libreoffice-language-pack --language=fr`

gives  an error `Error: invalid option: --language=fr`

I'm pretty sure it used to work and I'm seeing patch request for documenting it.

`brew --version` returns 
`Homebrew 1.2.2`
`Homebrew/homebrew-core (git revision a31f3; last commit 2017-06-11)`

**Comment by lanzenotter** [comment]
a few months ago my College has requestet the Language Option and the Developers has added this Feature reale quick. Now it dosent work anymore. Is it possible to fix this?

**Comment by vitorgalvao** [comment]
@lanzenotter https://github.com/Homebrew/brew/pull/2775.

**Comment by 9renpoto** [comment]
It seems that there are still problems. Advice please.

```
➜  ~ brew cask install firefox --language=en --verbose
Error: invalid option: --language=en
Error: Kernel.exit
➜  ~ brew cask --version
Homebrew-Cask 1.2.3
caskroom/homebrew-cask (git revision 9e363; last commit 2017-06-24)
➜  ~ brew --version
Homebrew 1.2.3
Homebrew/homebrew-core (git revision 6ac9; last commit 2017-06-24)
```
