### ISSUE TITLE
Cask request: Luminar

### ISSUE THREAD

**Issue by bbohling** [caskroom/homebrew-cask#35504]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Luminar

Homepage: 
https://macphun.com/luminar

Download URL: 
https://s3-us-west-1.amazonaws.com/luminarapp/Luminar_main.dmg

Description:
Luminar is the supercharged photo software that makes complex editing
easy & enjoyable. And it is as responsive and beautiful as your Mac.

**Comment by commitay** [comment]
To download this you need to register and the download link is emailed.

**Comment by bbohling** [comment]
@commitay are you sure? I was able to use the download URL I provided.

**Comment by commitay** [comment]
The direct download link is not available from https://macphun.com/luminar

**Comment by bbohling** [comment]
this is the direct download link i provided: https://s3-us-west-1.amazonaws.com/luminarapp/Luminar_main.dmg

**Comment by commitay** [comment]
Yes, I can see that. How did you get that link?

**Comment by bbohling** [comment]
I got the email with the link (as you stated above), downloaded and captured the location where it was downloaded from. I understand that it is better (more reliable) to have download URLs that are publicly displayed on an app's website, but any URL has the potential to change, right? No worries, if you don't want to add it. I get it.

**Comment by miccal** [comment]
Unfortunately we cannot add this to Cask unless the `url` is publicly available.
