### ISSUE TITLE
Feature request: Browse Packages

### ISSUE THREAD

**Issue by banzr** [caskroom/homebrew-cask#35649]
### Description of feature/enhancement
Browse Packages in browser. Currently, search is the only way to discover packages. Users cannot easily find a list of packages. Ranking packages would be awesome in providing a venue for browsing packages.

### Justification
To facilitate discovering new software.

### Example use case
https://caskroom.github.io/browse
then...
Select by category or by popularity.
click to install? Perhaps optional cask GUI app.

**Comment by commitay** [comment]
[Homebrew-Cask is not a discoverability service](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md#homebrew-cask-is-not-a-discoverability-service)
