### ISSUE TITLE
brew install caskroom/cask/brew-cask fails MacOS Sierra 

### ISSUE THREAD

**Issue by awilegal** [caskroom/homebrew-cask#35645]
$ brew install caskroom/cask/brew-cask
==> brew cask install caskroom/cask/brew-cask 
Error: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.
Error: nothing to install

Any clue? brew update or brew cleanup did not help..

**Comment by reitermarkus** [comment]
You don't need to install `brew-cask`, it is already installed if you have Homebrew. Just run the `brew cask` command you want.

**Comment by WilliamKF** [comment]
Also fails same way on MacOS High Sierra:

```
bash-3.2$ brew install caskroom/cask/brew-cask
brew install caskroom/cask/brew-cask
==> brew cask install caskroom/cask/brew-cask 
Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist. 
```
