### ISSUE TITLE
brew cask search lacks --desc

### ISSUE THREAD

**Issue by crowell** [caskroom/homebrew-cask#35671]
# feature request:

brew cask search is really difficult to find what packages are

brew normally has brew search --desc (which has issues of its own, but still, it exists).

there's currently no analog for brew cask searches.

**Comment by miccal** [comment]
[Homebrew-Cask is not a discoverability service.](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md#homebrew-cask-is-not-a-discoverability-service)

**Comment by crowell** [comment]
so, what you're saying is that if i were to add `--desc`, you'd reject the PR?
