### ISSUE TITLE
Cask request: [qqmusic] Upgrade to 5.0.0.3

### ISSUE THREAD

**Issue by twang2218** [caskroom/homebrew-cask#35676]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: QQ Music

Homepage:https://y.qq.com/download/mac.html?part=1&ADTAG=YQQ

Download URL: http://dldir1.qq.com/music/clntupate/mac/QQMusicMac5.0Build03.dmg

Description:

QQ Music has been upgraded to `5.0.0.3`, which is `5.0Build03`, and the version of qqmusic in cask is `4.2.3Build02`: https://github.com/caskroom/homebrew-cask/blob/master/Casks/qqmusic.rb

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35677
