### ISSUE TITLE
different versions osxfuse / macfuse for new OS

### ISSUE THREAD

**Issue by tiiiecherle** [caskroom/homebrew-cask#35688]
Earlier today I submitted a pull request for updating osxfuse (macfuse) but it was rejected as it is a preview.

Could you change the cask that way that every 10.12 system gets the stable one and 10.13 gets the new one? would be nice as the stable is not installing on 10.13. I think I have seen a modification of a cask like that but I don`t know how to do it.

thanks a lot

**Comment by reitermarkus** [comment]
Take a look at https://github.com/caskroom/homebrew-cask/blob/e5261c3133261688e1b7addb55e70649cdc3cf12/doc/cask_language_reference/readme.md#version-comparisons.

**Comment by commitay** [comment]
As this is a developer preview should this be in `caskroom/versions` as `osxfuse-dev`?

**Comment by tiiiecherle** [comment]
I don`t know. There does not seem to be a cask osxfuse-dev in there. Would the "normal" non developer cask veracrypt respect it as a dependency then? That was what I was thinking about when I asked about the different versions for the two different os. The real cask I need on 10.13 is veracrypt and osxfuse is the dependency.

**Comment by commitay** [comment]
> There does not seem to be a cask osxfuse-dev in there.

It does not exist, I was asking the other maintainers if it should be created.

> Would the "normal" non developer cask veracrypt respect it as a dependency then?

No, it would not.

> The real cask I need on 10.13 is veracrypt and osxfuse is the dependency.

Until there is a stable release of `osxfuse` that supports 10.13 I would suggest [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for `osxfuse` and `veracrypt` or installing them manually.

**Comment by tiiiecherle** [comment]
ok, so I will install them manually until the stable version is released. thanks
