### ISSUE TITLE
Suggested change to prefpane install behavior

### ISSUE THREAD

**Issue by jimbojsb** [caskroom/homebrew-cask#3568]
Scenario:
1. I have a preference pane already installed
2. I try to install over top of it with Homebrew Cask
3. Homebrew Cask will download the file, attempt to symlink it, but message me that is has not done so
4. Homebrew Cask marks the package installed
5. ```brew cask install --force``` will not cause a symlink to be created

I propose that:
1. If a symlink is not created, it is not counted as installed
2. ```--force``` would overwrite the existing prefpane bundle with a symlink

If people find this idea generally amenable, I'll code up a patch that changes this behavior. My main use case for this is managing LaunchRocket, which I both use daily, and develop. Debugging prefpanes basically means writing xCode build products directly into your ~/Library/PreferencePanes, which can get Homebrew Cask into somewhat of a confused state.

**Comment by vitorgalvao** [comment]
Closing there has been no progress, and installation behaviour is expected to change. We should take this into consideration then.
