### ISSUE TITLE
Cask request: [xmrouter] Upgrade to 0.9.12

### ISSUE THREAD

**Issue by twang2218** [caskroom/homebrew-cask#35728]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: xmrouter

Homepage: http://www.miwifi.com/

Download URL: http://bigota.miwifi.com/xiaoqiang/client/XMRouter-0.9.12.dmg

Description:

Current download link, http://bigota.miwifi.com/xiaoqiang/client/xqmac_client.dmg, will download `0.9.7`, and I just received the update notification for `0.9.12`, which is another link with version number in it.

**Comment by commitay** [comment]
The version available for download at http://www.miwifi.com/miwifi_download.html is `0.9.4`, is there a changelog or appcast that shows `0.9.12`?

**Comment by twang2218** [comment]
The web page has been `0.9.4` for a while. The link in the current cask file, http://bigota.miwifi.com/xiaoqiang/client/xqmac_client.dmg, is actually point to `0.9.7` right now.

I received the upgrade notification from the XMRouter app itself:

<img width="364" alt="screenshot 2017-06-25 01 37 53" src="https://user-images.githubusercontent.com/6299096/27509747-f931790a-5946-11e7-9826-baa7f3cd32e4.png">

I didn't find the appcast, however, after looked into the app, I did find how the app do the update checking.

It sends a HTTP GET request to link: 

```
http://api.miwifi.com/rs/grayupgrade/mac?s=<MD5_SIG>&time=1498316687315&locale=zh_CN&channel=release&filterID=327809&version=0.9.7
```

*I'm not sure whether `s` is a sensitive information or not, so I masked it with `<MD5_SIG>, as it's a MD5 value.*

And the server responses with a JSON data which contains whether it should be updated, the new version, the changelog, and the download link:

```json
{
    "code": "0",
    "data": {
        "changelogUrl": "",
        "description": "1. 增加了登录后自动切换为当前连接的小米路由器功能\n2. 增加了新路由器对应的图标配置",
        "hash": "DEFAULT",
        "link": "http://bigota.miwifi.com/xiaoqiang/client/XMRouter-0.9.12.dmg",
        "needUpgrade": true,
        "size": 1,
        "toVersion": "0.9.12",
        "upgradeId": "7377",
        "weight": "1"
    }
}
```

There is another information might be useful, that to check the patch version number, just download the `.dmg` file, extract the `.app` file, and check the `CFBundleVersion` value:

```
$ grep BundleVersion -A1 Contents/Info.plist
	<key>CFBundleVersion</key>
	<string>12</string>
```

The value seems to be the patch version number, in this case, it's `x.x.12`.

**Comment by commitay** [comment]
Ping @vitorgalvao (again) As this has three possible versions, should this be left as is or downgraded to `0.9.4` to match the website release?

**Comment by vitorgalvao** [comment]
We can try changing it to a versioned cask with the `…12` version. And perhaps try to get the appcast to work for us.

I’m always warier of apps whose website I cannot read.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35857

> And perhaps try to get the appcast to work for us.

http://api.miwifi.com/rs/grayupgrade/mac seems to need a login.

**Comment by twang2218** [comment]
All the arguments are required, I think.

Here are 2 links I got from JMeter, it seems working just within a certain time period:

```
http://api.miwifi.com/rs/grayupgrade/mac?s=b804f76765af063e92d2730f0eb039aa&time=1498389576388&locale=zh_CN&channel=release&filterID=327809&version=0.9.7
```

```
http://api.miwifi.com/rs/grayupgrade/mac?s=b8bc738ff6c7695daac578433b38a7a9&time=1498389388387&locale=zh_CN&channel=release&filterID=327809&version=0.9.7
```

There are 6 arguments:

* `s`: a MD5 signature for the request;
* `time`: a timestamp;
* `locale`: locale, e.g. `zh_CN`;
* `channel`: release channel, e.g., `release`;
* `filterID`: unknown;
* `version`: current installed version;

`s` seems to be some kind of signature or checksum of the request, any argument I changed will cause the `401 Unauthorized` result:

```
$ curl -i http://api.miwifi.com/rs/grayupgrade/mac\?s\=b804f76765af063e92d2730f0eb039aa\&time\=1498389576388\&locale\=zh_CN\&channel\=release\&filterID\=327809\&version\=0.9.7
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Date: Sun, 25 Jun 2017 10:56:47 GMT
Server: Tengine
Content-Length: 344
Connection: keep-alive

{"code":"0","data":{"needUpgrade":true,"size":1,"changelogUrl":"","link":"http://bigota.miwifi.com/xiaoqiang/client/XMRouter-0.9.12.dmg","description":"1. 增加了登录后自动切换为当前连接的小米路由器功能\n2. 增加了新路由器对应的图标配置","weight":"1","upgradeId":"7377","hash":"DEFAULT","toVersion":"0.9.12"}}

$ curl -i http://api.miwifi.com/rs/grayupgrade/mac\?s\=b804f76765af063e92d2730f0eb039aa\&time\=1498389576388\&locale\=zh_CN\&channel\=release\&filterID\=327809\&version\=0.9.4
HTTP/1.1 401 Unauthorized
Date: Sun, 25 Jun 2017 10:57:16 GMT
Server: Tengine
WWW-Authenticate: Basic realm="default"
Content-Length: 0
Connection: keep-alive
```

**Comment by commitay** [comment]
Thank you for the additional information @twang2218.

**Comment by twang2218** [comment]
After some analysis, and try and error, here is what I found.

The signature `s` is a calculated by following pseudo code:

```js
s = md5(base64(request);
```

And `request` is a query string, which contains all the required arguments: `channel`, `filterID`, `locale`, `time` and `version`.

`filterID` seems to be the userID of xiaomi account, and it looks like that it can be any number.

I wrote a node.js snippet to demo the procedure.

```js
const fetch = require('node-fetch');
const crypto = require('crypto');

function base64(data) {
    return Buffer.from(data).toString('base64');
}

function md5(data) {
    return crypto.createHash('md5').update(data).digest("hex");
}

const version = '0.9.7';
const salt = '8007236f-a2d6-4847-ac83-c49395ad6d65';
const time = `${Date.now()}`;
const request = `channel=release&filterID=1234567&locale=zh_CN&time=${time}&version=${version}`;
const sig = md5(base64(`${request}&${salt}`));

fetch(`http://api.miwifi.com/rs/grayupgrade/mac?s=${sig}&time=${time}&${request}`)
    .then(res => res.json())
    .then(json => console.log(json))
    .catch(console.error);
```

After install the `node-fetch` module, `npm install node-fetch`, just run it by `node xxx.js`, such as:

```bash
$ node api.js
{ code: '0',
  data:
   { needUpgrade: true,
     size: 1,
     changelogUrl: '',
     link: 'http://bigota.miwifi.com/xiaoqiang/client/XMRouter-0.9.12.dmg',
     description: '1. 增加了登录后自动切换为当前连接的小米路由器功能\n2. 增加了新路由器对应的图标配置',
     weight: '1',
     upgradeId: '7377',
     hash: 'DEFAULT',
     toVersion: '0.9.12' } }
```
