### ISSUE TITLE
brew cask update is deprecated but brew update doesn't work

### ISSUE THREAD

**Issue by revolter** [caskroom/homebrew-cask#35734]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Running `brew cask update studio-3t` prints this warning message:

> Warning: Calling `brew cask update` is deprecated and will be disabled on 2017-07-01!
Use `brew update` instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'

Running `brew update` doesn't update `studio-3t` though.

#### Output of your command with `--verbose --debug`

```
Warning: Calling `brew cask update` is deprecated and will be disabled on 2017-07-01!
Use `brew update` instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'

==> Executing: ["/usr/local/bin/brew", "update"]
==> Already up-to-date.
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli/update.rb:11:in `exit'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli/update.rb:11:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.3
caskroom/homebrew-cask (git revision 7692f; last commit 2017-06-21)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3639 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_ALL="en_US.UTF-8"
LC_CTYPE="UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/opt/local/bin:/opt/local/sbin:/usr/local/sbin:~/.local:~/.local/bin:~/Library/Python/2.7/bin:/usr/local/opt/qt/bin:~/.local/git-scripts:~/.gems/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
> Running brew update doesn't update studio-3t though.
```
$ brew update

$ brew cask reinstall studio-3t
```
Running `brew update` will update Homebrew and Homebrew-Cask *not* the casks that you have installed.

**Comment by revolter** [comment]
1) Why isn't `brew cask update studio-3t` calling `brew cask reinstall studio-3t` behind the scenes? As the semantics of the first command are much better than of the second one.
2) `brew update` updated the packages installed by `Homebrew`, not only `Homebrew` itself, so, logically, I thought `brew cask update` would update the casks installed by `Homebrew Cask`.
3) Why isn't `brew cask reinstall` mentioned in the `brew cask update`'s warning message?

**Comment by commitay** [comment]
> Why isn't `brew cask update studio-3t` calling `brew cask reinstall studio-3t`

`brew cask update` used to only update Homebrew-Cask before it merged with Homebrew

> `brew update` updated the packages installed by `Homebrew`, not only `Homebrew` itself

No, it doesn't. `brew update` will update Homebrew, `brew upgrade` will install new versions of formula. 

> Why isn't `brew cask reinstall` mentioned in the `brew cask update`'s warning message?

Because running `brew cask update` has never installed new versions of casks.

**Comment by revolter** [comment]
Oh, right, then, why isn't `brew cask update && brew cask upgrade` updating the installed casks?

**Comment by commitay** [comment]
As it said in the error message:
```
Warning: Calling `brew cask update` is deprecated and will be disabled on 2017-07-01!
Use `brew update` instead.
```
[`brew cask upgrade`](https://github.com/caskroom/homebrew-cask/issues/29301) doesn't do anything currently, it is being implemented.

**Comment by vitorgalvao** [comment]
> `brew cask update` used to only update Homebrew-Cask before it merged with Homebrew

Small correction there. `brew cask update` was always nothing more than an alias to `brew update`, meaning it updated everything<sup>1</sup>. Part of the reason `brew cask update` was deprecated was that I kept seeing people do `brew update && brew cask update`, essentially running the same command twice. Clearly is wasn’t obvious that both commands did the same and the `cask` version only existed for convenience, so we decided to scrape it.

Everything else is spot on!

---

1: Not really *everything*. When homebrew-cask was itself a formula, `brew update` updated the casks but the core itself needed to be updated with `brew upgrade brew-cask`
 or `brew upgrade`. This led to a situation where you might have casks that included features that the core didn’t understand (because you ran `update` but not `upgrade`). Casks even had different version specifications at that time due to that. Glad that time has passed.

**Comment by revolter** [comment]
Ok, understood. I would still add something along the lines of:

> If you're trying to update a cask, run `brew update && brew cask reinstall <cask-name>` instead.

to that warning message.

**Comment by commitay** [comment]
> Small correction there. `brew cask update` was always nothing more than an alias to `brew update`

Oops, thank you for the correction. 👍 

> I kept seeing people do `brew update && brew cask update`

Me (for a few months) 😆

**Comment by vitorgalvao** [comment]
> Ok, understood. I would still add something along the lines of:

> > If you're trying to update a cask, run `brew update && brew cask reinstall <cask-name>` instead.

> to that warning message.

To put it bluntly, everyone who misunderstands a message thinks we should add a correction to it according to their confusion. If we did so, every warning and notification would be the length of War and Peace. This is not a common confusion, so it does not need further clarification.

We make additions to messages when multiple people make a mistake (case in point, the aforementioned `brew cask upgrade` duplication). Otherwise we may still make messages clearer, but we’re not going to explain every use case in normal usage. That’s what `man` pages on online documentation are for.
