### ISSUE TITLE
Cask request: Dockstation

### ISSUE THREAD

**Issue by GasimGasimzada** [caskroom/homebrew-cask#35757]
### Cask details

Name: Dockstation

Homepage: https://dockstation.io

Download URL: https://dockstation.io

Description: DockStation is developer-centric application to managing projects based on Docker. Instead of lots of CLI commands you can monitor, configure, and manage services and containers using just a GUI.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35759
