### ISSUE TITLE
Cask request: Rippex

### ISSUE THREAD

**Issue by designorant** [caskroom/homebrew-cask#35763]
### Cask details

Name: Rippex

Homepage: https://rippex.net/carteira-ripple.php#/

Download URL: https://s3.amazonaws.com/static.rippex.net/client/ripple-wallet-osx64-1.4.1.zip

Description: A desktop client for the Ripple payment network built using web technologies

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35765
