### ISSUE TITLE
Cask request: [app name here]

### ISSUE THREAD

**Issue by alexozwald** [caskroom/homebrew-cask#35855]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: MegaSync

Homepage: https://mega.nz

Download URL: https://mega.nz/MEGAsyncSetup.dmg

Description: Easy automated syncing between your computers and your MEGA cloud drive.

**Also, this should probably replace the older & outdated _caskroom/cask/mega_ cask.**

**Comment by commitay** [comment]
Already exists: [`megasync`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/megasync.rb)

> Also, this should probably replace the older & outdated "mega" cask.

[`mega`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mega.rb) is not the same thing. http://megasoftware.net/

**Comment by alexozwald** [comment]
Thank you! Apologies, i also searched for "mega sync" but left it as two words :/

**Comment by alexozwald** [comment]
Thank you! Apologies, i also searched for "mega sync" but left it as two words :/
