### ISSUE TITLE
paragon-extfs new version does not install

### ISSUE THREAD

**Issue by tiiiecherle** [caskroom/homebrew-cask#35893]
Hey, I submitted the update for the paragon-extfs via casks-reapair which was merged a few minutes ago. Thanks for that. Unfortunately it does not install.

I´m sorry but I don`t know how to fix it.

Thanks for fixing in advance.

```
brew cask install --force paragon-extfs
==> Downloading http://dl.paragon-software.com/demo/trial_extfs11.dmg
######################################################################## 100,0%
==> Verifying checksum for Cask paragon-extfs
==> Installing Cask paragon-extfs
==> Running installer for paragon-extfs; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
Error: pkg source file not found: '/usr/local/Caskroom/paragon-extfs/11/FSInstaller.app/Contents/Resources/Paragon ExtFS for Mac.pkg'
Error: nothing to install
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Please read those instructions. Your case (`Error: pkg source file not found:`) is well covered there with step-by-step instructions.

**Comment by tiiiecherle** [comment]
Thanks for the hint, I´m really trying to help as good as I can, but I couldn`t find a .pkg file in the 
FSInstaller.app/Contents/ or in any subfolder. The only thing I found was an executable in FSInstaller.app/Contents/MacOS/FSInstaller.

But I don`t know if putting 
            pkg 'FSInstaller.app/Contents/MacOS/FSInstaller'
in the cask would make any sense.

Additionally there is no more 
            script:    'Uninstall.app/Contents/Resources/uninstall.sh',
but there is
            script:    'Uninstall.app/Contents/MacOS/uninstaller',

I could try to sumbit these changes with cask-repair --edit-cask if they make any sense to you.

Thanks for further help in advance.

**Comment by tiiiecherle** [comment]
ok, I tried the best I could here:

[https://github.com/caskroom/homebrew-cask/pull/35896/files](https://github.com/caskroom/homebrew-cask/pull/35896/files)

**Comment by vitorgalvao** [comment]
Thank you for the effort.

The cask won’t work like that, but the fact you tried means a lot. That’s all we ask: that users make a true effort to respect our documentation. We poured a lot of work into it.

Will open a new issue and tag you there, so you can tag along for the fixing process.
