### ISSUE TITLE
Cask request: Webrecorder Player

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#35901]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Webrecorder Player

Homepage: https://github.com/webrecorder/webrecorderplayer-electron

Download URL: https://github.com/webrecorder/webrecorderplayer-electron/releases/download/v#{version}/webrecorderplayer-electron-#{version}.dmg

Description: This is an overhaul of an existing Cask, `webarchiveplayer`, which was deprecated in favor of this. I’m not entirely sure how to proceed, so I’m filing this as an issue. I recommend moving `webarchiveplayer` to the Legacy tap, as the homepage explicitly confirms the aforementioned deprecation.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35902
