### ISSUE TITLE
GitHub Desktop cask installs the beta, not the stable release

### ISSUE THREAD

**Issue by joewiz** [caskroom/homebrew-cask#35948]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The `github-desktop` cask installs the "Desktop Beta" version, instead of the current "Official" release. According to https://desktop.github.com/, the official release should be downloaded from https://central.github.com/mac/latest. The cask (https://github.com/caskroom/homebrew-cask/blob/master/Casks/github-desktop.rb) fetches its download from the GitHub repo's releases channel, which unfortunately doesn't distinguish between beta and stable releases.

I propose that we switch over to the https://central.github.com/mac/latest URL, but I thought I'd raise this for discussion first.

**Comment by joewiz** [comment]
The "latest" URL I'm proposing provides a 302 redirect (as of the current time) to https://mac-installer.github.com/mac/GitHub%20Desktop%20223.zip. Since this "latest" URL will always redirect to the latest version, my PR would probably change to `version latest` and remove the sha256 value and appcast/checkpoint.

**Comment by vitorgalvao** [comment]
This new beta is a rewrite and the new accepted standard. As such, it qualifies. This is documented in the `adding_a_cask` document. Pretty sure this was also discussed in the PR that made this change. Search for it (I am on the phone now).

**Comment by joewiz** [comment]
@vitorgalvao Fair enough. I thought the "beta" vs. "official" labels used on the desktop.github.com homepage would've translated into the "beta" version going into homebrew-versions until it became the "official" release, but my team (who relied on some features from the "official" version that haven't yet been implemented in the "beta") can make due with the current "in-between" state.
