### ISSUE TITLE
Automatically modify $PATH with /etc/paths.d

### ISSUE THREAD

**Issue by szhu** [caskroom/homebrew-cask#3597]
MacTeX and some other software packages install binaries to non-standard locations. This necessitates caveats like the one added by #2284:

    ==> Caveats
    To use mactex, you may need to add the /usr/texbin directory
    to your PATH environment variable, eg (for bash shell):

      export PATH=/usr/texbin:"$PATH"

There's actually a really elegant solution to appending to `$PATH` on OS X: Just add a file with the path to append in `/etc/paths.d`. When shells start, they run [path_helper][], which parses `/etc/path` and the files in `/etc/paths.d` to construct the correct `$PATH`. Such a "path file" would be easy for Homebrew to install and uninstall. Or, alternatively, a Cask "path file" could be installed that would contain all the paths of the currently installed formulae.

Not only does this solution automate something that users would need to do by hand, but also it is, unlike the solution recommended by the caveat note, both auto-uninstallable and shell-agnostic. 

[path_helper]: https://developer.apple.com/library/mac/documentation/Darwin/Reference/Manpages/man8/path_helper.8.html

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is definitely non-urgent, and can be revisited later.
