### ISSUE TITLE
Cask request: WD MyCloud

### ISSUE THREAD

**Issue by marktopper** [caskroom/homebrew-cask#35976]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

**Name**: WD MyCloud

**Homepage**: http://wdc.com

**Download URL**: http://download.wdc.com/nas/WDMyCloud_mac.dmg

**Description**:
It was possible once before to download WD MyCloud via Caskroom? But seems like it was removed.
Original code: https://github.com/caskroom/homebrew-cask/blob/93e9e31a68bdcd7547f744836baf353d856f3b22/Casks/wd-my-cloud.rb

**Comment by commitay** [comment]
Migrated to [`caskroom/drivers`](https://github.com/caskroom/homebrew-drivers): [wd-my-cloud](https://github.com/caskroom/homebrew-drivers/blob/master/Casks/wd-my-cloud.rb)
