### ISSUE TITLE
Upgrade paragon-ntfs to the new v15

### ISSUE THREAD

**Issue by palavrov** [caskroom/homebrew-cask#35987]
https://www.paragon-software.com/ufsdhome/ntfs-mac/

**Comment by commitay** [comment]
[`paragon-ntfs`](https://github.com/caskroom/homebrew-cask/blob/e48b47711fae77785b3f437636243e2ffbff5bfb/Casks/paragon-ntfs.rb) `uninstall` needs to be rewritten the same as https://github.com/caskroom/homebrew-cask/pull/35896.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36009
