### ISSUE TITLE
seafile-client Download URL changed

### ISSUE THREAD

**Issue by shivno** [caskroom/homebrew-cask#36023]
atm to time for a decent patch, so just:

url "https://download.seadrive.org/seafile-client-#{version}.dmg"

also version is 6.0.7

**Comment by shivno** [comment]
sha256 aeeb6b25be731f7d95691a84ac5ead05fd3adad6738ab56d9ef1927e285b1df0 for comparison

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36025
