### ISSUE TITLE
Cask request: Soundplant

### ISSUE THREAD

**Issue by yoanmalie** [caskroom/homebrew-cask#36065]
### Cask details

Name: Soundplant

Homepage: http://soundplant.org

Download URL: http://soundplant.org/downloads/
Direct Download URL (last version) : http://soundplant.org/downloads/Soundplant45.dmg

Description:
Soundplant turns your computer keyboard into a versatile, low latency sound trigger and playable instrument.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36073
