### ISSUE TITLE
404 link for cask Java

### ISSUE THREAD

**Issue by Goffen** [caskroom/homebrew-cask#36141]
brew install Caskroom/cask/java
==> brew cask install Caskroom/cask/java
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u74-b02/jdk-8u74-macosx-x64.dmg
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/8u74-b02/jdk-8u74-macosx-x64.dmg

**Comment by commitay** [comment]
From the template:
> #### - [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
___
[curl errors](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#curl-error) are a part of the first item on the checklist.

**Comment by commitay** [comment]
Try `brew update` then `brew cask install java`

**Comment by zmt** [comment]
We are seeing this again:
```
brew cask install java
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Satisfying dependencies
==> Downloading http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_osx-x64_bin.dmg
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_osx-x64_bin.dmg
```

**Comment by Groxx** [comment]
Looks like Oracle may have changed their "to download from [url]" requirements...
<img width="609" alt="screen shot 2018-01-16 at 14 46 40" src="https://user-images.githubusercontent.com/77197/35016161-3f8ba9d0-facc-11e7-8cf1-cddf83fe57d4.png">

Is there a mirror perhaps?  Or would this need a bigger / interactive "get approval, then download" sequence of some kind?

**Comment by zmt** [comment]
Also, the current jdk is now 9.0.4: http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html, so I found my way to the archive: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html and I think I see the problem.
The 404: http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_osx-x64_bin.dmg
The new: http://download.oracle.com/otn/java/jdk/9.0.1+11/jdk-9.0.1_osx-x64_bin.dmg

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/issues/42890
