### ISSUE TITLE
Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.

### ISSUE THREAD

**Issue by garreth83** [caskroom/homebrew-cask#36169]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Tried to install Homebrew Cask with this command in Terminal: `brew install caskroom/cask/brew-cask`

However I was prompted with an error message:

Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.

When I try to locate that specific file in Finder, that particular brew-cask.rb file is missing from that folder.

`Garreths-MacBook-Pro:~ garrethalvinchan$ brew update-reset && brew update
==> Fetching /usr/local/Homebrew...

==> Resetting /usr/local/Homebrew...
Branch master set up to track remote branch master from origin.
Switched to and reset branch 'master'

==> Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...

==> Resetting /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

Already up-to-date.
Garreths-MacBook-Pro:~ garrethalvinchan$ brew install caskroom/cask/brew-cask
==> brew cask install caskroom/cask/brew-cask 
Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.
Error: Install incomplete.
Garreths-MacBook-Pro:~ garrethalvinchan$ brew doctor
Your system is ready to brew.
Garreths-MacBook-Pro:~ garrethalvinchan$ Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.
-bash: Error:: command not found
Garreths-MacBook-Pro:~ garrethalvinchan$ brew install caskroom/cask/brew-cask
Updating Homebrew...
==> brew cask install caskroom/cask/brew-cask 
Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.
Error: Install incomplete.`

What can I do in order to successfully install Homebrew Cask for my system?

I am running on MacBook Pro Late 2011, OS X El Capitan, v10.11.6.

**Comment by commitay** [comment]
> To start using Homebrew-Cask, you just need Homebrew installed.

You don't need to `brew install caskroom/cask/brew-cask`, just run any `brew cask` command (e.g. `brew cask install atom`)
