### ISSUE TITLE
Cask request: MacDown

### ISSUE THREAD

**Issue by tomasnorre** [caskroom/homebrew-cask#36200]
### Cask details
Name: MacDown

Homepage: https://macdown.uranusjr.com/

Download URL: https://github.com/MacDownApp/macdown/releases/download/v0.7.1/MacDown.app.zip

Description:
MacDown is an open source Markdown editor for macOS, released under the MIT License.

**Comment by commitay** [comment]
[macdown](https://github.com/caskroom/homebrew-cask/blob/master/Casks/macdown.rb)

**Comment by tomasnorre** [comment]
Sorry, should do my search better.
