### ISSUE TITLE
Cask request: pdf to keynote

### ISSUE THREAD

**Issue by moritzfl** [caskroom/homebrew-cask#36213]
### Cask details

Name: pdf to keynote

Homepage: https://www.cs.hmc.edu/~oneill/freesoftware/pdftokeynote.html

Download URL: https://www.cs.hmc.edu/~oneill/freesoftware/PDFtoKeynote-v1.04a.dmg

Description:
PDF to Keynote converts PDF-based presentations (e.g., made using LaTeX with Prosper, Beamer or foiltex) into Apple's Keynote format.

Once translated into Keynote format, every page of your original PDF file becomes a PDF image, properly scaled and centered on its own slide.

**Comment by commitay** [comment]
Ping @vitorgalvao This only seems to export to Keynote 5 (iWork 09), hasn't been updated for several years.

**Comment by vitorgalvao** [comment]
Definitely too outdated and not popular enough to consider inclusion.
