### ISSUE TITLE
Cask request: [YTD]

### ISSUE THREAD

**Issue by ankit-jha** [caskroom/homebrew-cask#36212]
### Cask details

Name: YouTubeDownloader

Homepage: http://www.youtubedownloadersite.com/mac/

Download URL: http://www.youtubedownloadersite.com/mac/

Description: YTD Video Downloader downloads YouTube videos onto your hard drive

**Comment by vitorgalvao** [comment]
I’ve encountered this app before. I’m going to refuse the request for several reasons:

+ The app has (had?) a non-trivial installation method (manual app installation).
+ From there it follows the app is non-trivial to uninstall.
+ This is a request, not a PR, so no work is being thrown away.
+ Everything I saw about the app is shady.
+ I have reason to believe the app distributes malware.
+ No one else is asking for it.

If you want this app installable as a cask, you’ll need to make your own tap.
