### ISSUE TITLE
Cask request: [app name here]

### ISSUE THREAD

**Issue by mlhamel** [caskroom/homebrew-cask#36314]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: 

Sonos (Controller-app)

Homepage: 

http://www.sonos.com/en-ca/controller-app

Download URL: 

http://update.sonos.com/software/mac/mdcr/SonosDesktopController73.dmg

Description:

The app that control the Sonos sound system and Picked from their website: ```
Choose what to play, where to play it, and how loud. In one room or all over your home. Track down songs across all your music services with a single search. Create playlists in an instant. The Sonos app does it all.
```

**Comment by commitay** [comment]
`caskroom/drivers`: [`sonos`](https://github.com/caskroom/homebrew-drivers/blob/master/Casks/sonos.rb)
