### ISSUE TITLE
Feature request: cask aliases

### ISSUE THREAD

**Issue by ed-flanagan** [caskroom/homebrew-cask#36341]
### Description of feature/enhancement

Is it possible to have cask aliases, similar to those in [homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core)?

I tried adding the `Aliases` directory locally, but didn't seem to have any effect.

### Justification

It's helpful when the "default" formula/cask can still be installed provided it's respective version.
Also helpful to have common, alternative names to a cask.

### Example use case

`java8` aliases to `java`.

Existing example: `node@8` aliased to `node` in [homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core).

**Comment by commitay** [comment]
I personally think that this falls under [Homebrew-Cask is not a discoverability service](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md#homebrew-cask-is-not-a-discoverability-service).
> our users are expected to have reasonable knowledge about the apps they’re installing through us before doing so

**Comment by vitorgalvao** [comment]
What you ask is already covered by [`name`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md). It provided all the disambiguation needed while searching, and is clearer than having a bunch of token aliases.

Only problem is `search` doesn’t yet take advantage of it. PRs welcome.
