### ISSUE TITLE
Outdated cask: rar

### ISSUE THREAD

**Issue by zbeekman** [caskroom/homebrew-cask#36399]
* [x] Insert the name of the cask in the title, after the `:`.
* [x] Insert the name of the cask and a link to it in the body of this issue: [`rar`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rar.rb)).
* [x] Insert the new version of the app: still at 5.5.b5

The SHA is mismatched, perhaps the app was updated in place?

- Old SHA256: `a0ae92f5cf0c16cccbc2067292396135e16477594ce026eae9120ad82769470e`
- Current SHA256: `99faff246f31f873166ea8f0c5e163408b9698637da1807c290cfc7a45497b5a`
- Download URL unchanged: http://www.rarlab.com/rar/rarosx-5.5.b5.tar.gz

I followed [the instructions for repairing a bad cask  SHAsum mismatch](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/sha256_mismatch_error_fix_outdated.md) by following the [instructions for updating a cask with `cask-repair`](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) but `cask-repair` is failing for me on Sierra. I get to the "Is everything correct?" prompt and every time I hit <kbd>y</kbd> it just brings me back to the prompt with an additional red dot on the screen.

[link to asciicast below on asciinema](https://asciinema.org/a/128643)

![cask-repair-rar](https://user-images.githubusercontent.com/279612/28122989-d18bec0a-66ed-11e7-9e65-c6f300fe6086.gif)

**Comment by commitay** [comment]
`rar` was updated to a beta version for a security fix, it seems to be updated in place frequently. https://github.com/caskroom/homebrew-cask/pull/36412

The `cask-repair` error is an open issue at https://github.com/vitorgalvao/tiny-scripts/issues/88
