### ISSUE TITLE
Cask request: Captur

### ISSUE THREAD

**Issue by stidch** [caskroom/homebrew-cask#36435]
### Cask details

**Name**: Captur

**Homepage**: http://cambhlumbulunk.blogspot.ch/p/captur.html

**Download URL**: https://www.dropbox.com/s/kip1lw5jcj6y82h/captur-3.2.zip?dl=0

**Description**:
Captur is a simple Menu Bar interface for Mac OS X screencapture command.

Features:
- snapshots your screen in many way such as full screen, window, widget, selection etc.
- change a different file format for various file size
- customize file name with date and time options

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/issues/36441
