### ISSUE TITLE
Broken package: wkhtmltopdf 0.12.4

### ISSUE THREAD

**Issue by moodh** [caskroom/homebrew-cask#36432]
#### General troubleshooting steps

- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The latest version 0.12.4 has a serious regression bug only present in mac os and the recommended version is 0.12.3. Can 0.12.4 be downgraded to 0.12.3 or can 0.12.3 be published under another cask name? Thanks!

https://wkhtmltopdf.org/downloads.html (see "has regression")

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3241
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3549

**Comment by commitay** [comment]
I'd suggest installing `0.12.3` manually.

https://github.com/wkhtmltopdf/wkhtmltopdf/releases/0.12.3/
