### ISSUE TITLE
404: ericlawrence.com/dl/InstallFiddler.dmg

### ISSUE THREAD

**Issue by aniknafs** [caskroom/homebrew-cask#36519]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

File location is giving 404 not found.
You can type it in the browser: http://ericlawrence.com/dl/InstallFiddler.dmg

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/36520
