### ISSUE TITLE
Feature request: Auto-link tad CLI

### ISSUE THREAD

**Issue by pbronez** [caskroom/homebrew-cask#36538]
### Description of feature/enhancement

When installing the [Tad CSV Viewer](http://tadviewer.com/) from the [`tad` cask](https://github.com/caskroom/homebrew-cask/blob/c3113c4b5345b1193fc721cf39869d0da0d45f33/Casks/tad.rb), `brew` should automatically link the `tad` command into the local environment. This can be done by executing `sudo ln -s /Applications/Tad.app/Contents/Resources/tad.sh /usr/local/bin/tad`

### Justification

The CLI command `tad` is an important part of Tad's functionality. By failing to execute this task, `brew` leaves the installation job half done.

### Example use case

```bash
brew cask install tad
tad my_file.csv
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36539

**Comment by pbronez** [comment]
Such service! 😍
