### ISSUE TITLE
brew cask install robomongo

### ISSUE THREAD

**Issue by GeekOnGadgets** [caskroom/homebrew-cask#36619]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Not sure what happened to installation for robomongo through cask. Was working fine when i installed month back. Now i get this error `Error: Cask 'robomongo' is unavailable: No Cask with this name exists.`

I did a search in cask room but nothing came up. 

Thanks

**Comment by commitay** [comment]
Renamed: [robo-3t](https://github.com/caskroom/homebrew-cask/blob/master/Casks/robo-3t.rb)

**Comment by freeslugs** [comment]
any way to make an alias for robomongo -> robo-3t?

**Comment by boltonmd13** [comment]
use homebrew

brew cask install robo-3t
