### ISSUE TITLE
It doesn't work when installing idisplay! How to fix it ? 

### ISSUE THREAD

**Issue by Warnier-zhang** [caskroom/homebrew-cask#36766]
Below is the error log:
brew cask install idisplay
==> Satisfying dependencies
==> Downloading https://www.shape.ag/freedownload/iDisplay/iDisplayFull_2_3_10.d
Already downloaded: /Users/snippet/Library/Caches/Homebrew/Cask/idisplay--2.3.10.dmg
==> Verifying checksum for Cask idisplay
==> Installing Cask idisplay
Error: It seems the App source '/usr/local/Caskroom/idisplay/2.3.10/iDisplay.app' is not there.
Error: Install incomplete.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36768

**Comment by vitorgalvao** [comment]
@Warnier-zhang Next time, please don’t delete and ignore the issue template, or your issue might be closed without review. Your issue and the fix is well documented.
