### ISSUE TITLE
Outdated cask: Sonic Pi

### ISSUE THREAD

**Issue by TheBaronHimself** [caskroom/homebrew-cask#36769]
[`Sonic Pi`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sonic-pi.rb)

New version can be found here: http://sonic-pi.net/files/releases/v3.0/Sonic-Pi-for-Mac-v3.0.dmg

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/36772
