### ISSUE TITLE
VS Code cask brew can't see user fonts

### ISSUE THREAD

**Issue by joedborg** [caskroom/homebrew-cask#36809]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
I had VS Code installed via the DMG from Microsoft.  Changed this to brew and now I cannot set the editor font to anything within `~/Library/Fonts`.  E.g. "Source Code Pro" or "Fira Code" (both installed via `brew`.

#### Output of your command with `--verbose --debug`
N/A

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4
caskroom/homebrew-cask (git revision ae877; last commit 2017-07-20)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (19 files, 1.2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3656 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1107 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_GB.UTF-8"
PATH="~/Library/Go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by commitay** [comment]
> now I cannot set the editor font to anything within ~/Library/Fonts.

Homebrew-Cask installs the Microsoft DMG, we don't set any options.

**Comment by joedborg** [comment]
@commitay okay but if I revert back to manual DMG and use the same config file, it works.  It's only via `brew` that this doesn't.

**Comment by commitay** [comment]
> It's only via `brew` that this doesn't.

I've tried this in a clean VM, running `brew cask install visual-studio-code` and `brew cask install font-source-code-pro`, setting `"editor.fontFamily": "SourceCodePro"` works for me.

**Comment by joedborg** [comment]
@commitay okay, thanks, must be something wrong with my brew setup then.

**Comment by joedborg** [comment]
@commitay et. al. this is why https://github.com/Microsoft/vscode/issues/13366
