### ISSUE TITLE
Uninstall github-desktop executable

### ISSUE THREAD

**Issue by adriaanzon** [caskroom/homebrew-cask#36871]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The latest release of  github-desktop allows you to [install a command line tool](https://github.com/desktop/desktop/pull/1925) from the application menu. It is saved under `/usr/local/bin/github`.

I wasn't sure if this should be added to `zap` or `uninstall`, and what uninstall method it should use, so I decided to created an issue.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36873
