### ISSUE TITLE
Cask request: KORG Gadget

### ISSUE THREAD

**Issue by johndjameson** [caskroom/homebrew-cask#36875]
### Cask details

Name: KORG Gadget

Homepage: http://www.korg.com/us/products/software/korg_gadget/

Download URL: http://www.korguser.net/gadget/installer/KORG_Gadget.dmg/

Description:

> KORG Gadget is a completely new type of music production software that provides more than 30 small synthesizers and drum machines called "gadgets," and lets you freely combine these to produce anything from powerful electronic music to rock music.

**Comment by commitay** [comment]
> Download URL: http://www.korguser.net/gadget/installer/KORG_Gadget.dmg/

@johndjameson Is there a public page with this URL?

**Comment by johndjameson** [comment]
I haven’t been able to track one down. Right now their download flow requires people to check out with the free or paid version before getting an email:

![](https://user-images.githubusercontent.com/4504978/28495860-ab961c78-6f21-11e7-9bc0-edaa37b9ee30.png)

- [Free product page](https://korg.shop/korg-gadget-le-for-mac.html)
- [Paid product page](https://korg.shop/korg-gadget-for-mac.html)

The resulting download link isn’t unique, but I don’t think it’s public elsewhere. Is that a deal breaker for Cask?

And here’s the DMG link for the Free "Le" version of the app. It looks like they might be distinct applications: http://www.korguser.net/gadget/installer/KORG_Gadget_Le.dmg/

**Comment by commitay** [comment]
Thank you for your detailed response.

> Is that a deal breaker for Cask?

Yes, as the direct download links cannot be verified.

> [Rejected Casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md#rejected-casks)
> The download URL for the app is both behind a login/registration form and from a host that differs from the homepage, meaning users can’t easily verify its authenticity.
