### ISSUE TITLE
Cask request: QLCommonMark

### ISSUE THREAD

**Issue by Alhadis** [caskroom/homebrew-cask#36890]
### Cask details

**Name:** [QLCommonMark](https://github.com/digitalmoksha/QLCommonMark)

**Type:** QuickLook generator

**Download URL:** Binary uploaded to the [latest release's page @ `v1.1`](https://github.com/digitalmoksha/QLCommonMark/releases)
 -> [`digitalmoksha/QLCommonMark/releases/download/v1.1/QLCommonMark.qlgenerator.zip`](https://github.com/digitalmoksha/QLCommonMark/releases/download/v1.1/QLCommonMark.qlgenerator.zip)

**Description:** It's a QuickLook generator for Markdown pages, but it uses CommonMark for rendering, so it guarantees parity with what's displayed on GitHub. This is 100% of the reason why I'd take this over any other Markdown generator.

There aren't any QuickLook generators which use the CommonMark library as yet; only MultiMarkdown, and another older implementation with an unambiguous engine.

**Comment by commitay** [comment]
I've made a PR for this (https://github.com/caskroom/homebrew-cask/issues/36892) but we usually have a minimum popularity for Github projects to be added to HBC. I'll let another maintainer decide if it should be added to Cask.

**Comment by Alhadis** [comment]
If it helps, one of those stars came from GitHub staff: @kivikakk

Is she worth 10 instead of 1? =)

**Comment by digitalmoksha** [comment]
Ha, just went through the process of learning how to submit a new Cask, and you guys totally beat me to it!  👍  Hope it gets added...
