### ISSUE TITLE
brew cask add tistory-editor.app

### ISSUE THREAD

**Issue by pareut** [caskroom/homebrew-cask#36922]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Tistory-editor.app

Homepage: https://joostory.github.io/tistory-editor/

Download URL: https://github.com/joostory/tistory-editor/releases/download/0.3.8/TistoryEditor-0.3.8-mac.zip

Description: This is the most used blog service management tool in Korea
I already created tistory-editor.rb and I have posted it on the pull request.
I've already run it

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/issues/36923
