### ISSUE TITLE
Cask request: [Google Drive]

### ISSUE THREAD

**Issue by gebing** [caskroom/homebrew-cask#37271]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Google Drive

Homepage:    https://www.google.com/drive/

Download URL:   https://www.google.com/drive/download/

Description: Google Drive

**Comment by commitay** [comment]
Google Drive has been replaced by: [`google-backup-and-sync`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-backup-and-sync.rb)

**Comment by drawcard** [comment]
Out of curiosity is it possible to create an alias for this particular cask? I had spent a fair while trying to figure out why Google Drive was no longer available before finding this solution :)

**Comment by commitay** [comment]
We don't have aliases in Cask.
