### ISSUE TITLE
Skype missing auto_update stanza

### ISSUE THREAD

**Issue by andrewkeithly** [caskroom/homebrew-cask#37284]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask outdated` shows skype-for-business is outdated when it updates itself. As I understand, it needs an `auto_update true` in its stanza.

#### Output of `brew cask outdated --verbose --debug`

```
==> Determining which containers to use based on 'container :type'
...
==> Checking update info of Cask skype-for-business
skype-for-business (16.6.0.333) != 16.8.0.196
```

#### Output of `brew cask _stanza auto_update skype-for-business`

```
Warning: no such stanza 'auto_update' on Cask 'skype-for-business'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.0-13-g877c911
caskroom/homebrew-cask (git revision 8137b; last commit 2017-08-01)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (15 files, 2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3670 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (159 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.jenv/shims:~/.jenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:~/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/37285

Thank you for the report and all, but wouldn’t it have taken you less work to just submit the change?

**Comment by andrewkeithly** [comment]
Cheers, @vitorgalvao. I truly thought of this as I was filing this ticket. I've never actually submitted a pull-request so I figured I would submit a low-priority issue as a placeholder to come back to. I'll check out the guide for submitting pull requests in the future.

**Comment by vitorgalvao** [comment]
Looking forward to it. We’re here to help.
