### ISSUE TITLE
istat-menus open after install / update

### ISSUE THREAD

**Issue by tiiiecherle** [caskroom/homebrew-cask#37298]
iStat Menus requires some components to be installed / updated to work correct.y after installing the app. Therefore the app has to be opened and a separate installer has to be used.

I don`t know how homebrew-cask solves this in its script language, in bash it would just be 

`open "/Applications/iStat Menus.app"`

It would be nice to see something like that added to the cask to not forget it after install or updates.

Thanks

**Comment by commitay** [comment]
> `open "/Applications/iStat Menus.app"`

We don't open GUI apps.

> Therefore the app has to be opened and a separate installer has to be used.

Can this be done using CLI without opening the app?

**Comment by tiiiecherle** [comment]
I´m sorry I don`t know. I couldn`t find a pkg inside the app package. There is an installer.nib and an InstallerBundle.bundle, but I don`t know if this are the right files and I don`t know what these two do.

**Comment by commitay** [comment]
I've had a look at trying to do this but I haven't been able to find a way.

@tiiiecherle What we would need to do this is either a binary or a script provided by `istat-menus` we can run.  See [`keybase`](https://github.com/caskroom/homebrew-cask/blob/92257cb0e17e0a70394e2099d9fcb7e1ec037a36/Casks/keybase.rb#L15-L18) and [`vmware-fusion`](https://github.com/caskroom/homebrew-cask/blob/a56c5894cc61d2bf182b7608e94128065af3e64f/Casks/vmware-fusion.rb#L39-L43) as examples. If you can find a way to do this please comment here or open a PR.

Closing as this is doesn't impact how the cask is installed / uninstalled.
