### ISSUE TITLE
brew cask outdated does not do what is described

### ISSUE THREAD

**Issue by jrwiegand** [caskroom/homebrew-cask#37294]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask outdated` does not work as described. From the help section of the client (`brew cask help`) "outdated - list the outdated installed Casks". Does this mean that it will display a list of software that is outdated? If so, then the current version is not doing that.

#### Output of your command with `--verbose --debug`
```
$ brew cask outdated --verbose --debug
==> Checking update info of Cask alfred
==> Checking update info of Cask docker
==> Checking update info of Cask docker-toolbox
==> Checking update info of Cask filezilla
==> Checking update info of Cask firefox-beta
==> Checking update info of Cask flycut
==> Checking update info of Cask gimp
==> Checking update info of Cask google-chrome-beta
==> Checking update info of Cask intellij-idea
==> Checking update info of Cask iterm2-beta
==> Checking update info of Cask itsycal
==> Checking update info of Cask java
==> Checking update info of Cask mattermost
==> Checking update info of Cask postage
==> Checking update info of Cask postgres
==> Checking update info of Cask postman
==> Checking update info of Cask sourcetree-beta
==> Checking update info of Cask the-unarchiver
==> Checking update info of Cask virtualbox-beta
==> Checking update info of Cask visual-studio-code

$ brew cask outdated
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.0-15-g2ad03b8
caskroom/homebrew-cask (git revision 43e55; last commit 2017-08-02)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (28 files, 2.2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3670 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (107 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (6 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1107 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (159 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib
/Library/Ruby/Gems/2.0.0/gems/psych-2.0.17/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Environment Variables
LC_ALL="en_US.UTF-8"
LC_CTYPE=""
PATH="/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
Please post the output of `brew cask outdated --greedy`

**Comment by vitorgalvao** [comment]
> Does this mean that it will display a list of software that is outdated?

No. It means (like it says) that it’ll show a list of outdated *casks*. I.e. it only knows if the version you installed is outdated in relation to the latest version we know about. Also, it does not check for casks that auto update themselves, unless you pass `--greedy`. That is all described in the `man` page, where we can be verbose. `help` is for quick reference only.

**Comment by jrwiegand** [comment]
@commitay @vitorgalvao This is exactly what I was looking for. I must have missed it in the man pages. I guess I did not know exactly what I was looking for. Thank you.
