### ISSUE TITLE
Cask request: NativeDisplayBrightness

### ISSUE THREAD

**Issue by kud** [caskroom/homebrew-cask#37355]
### Cask details

Name: NativeDisplayBrightness

Homepage: https://github.com/Bensge/NativeDisplayBrightness

Download URL: https://github.com/Bensge/NativeDisplayBrightness/releases

Description: macOS display brightness utility for external monitors with a native UI.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37356
