### ISSUE TITLE
Cannot add cask because of notability

### ISSUE THREAD

**Issue by imolorhe** [caskroom/homebrew-cask#37352]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I created a cask sometime ago to add the mac app of a project, [altair](https://github.com/imolorhe/altair) but the [PR](https://github.com/caskroom/homebrew-cask/pull/35443) was rejected on the grounds of notability.

I just need to understand a little better what that means, because that wasn't mentioned in the docs as far as I can tell, and it wasn't in the PR checklist either which I checked completely. So what does this mean: 

> Unfortunately we cannot accept this self-submitted Cask at this time as it is not notable enough.

If it was submitted by another user, would it count?

**Comment by imolorhe** [comment]
I guess this https://github.com/caskroom/homebrew-cask/pull/28103 explains it butI still believe it should be in the acceptance docs.

**Comment by commitay** [comment]
> I still believe it should be in the acceptance docs

It is in the docs: [`rejected_casks`](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md)

> Also if the criteria for notability is (> 10 stars), then I believe the project I tried to add qualifies now.

Yes, if you would like to add this please submit a PR.  

Looking at the previous PR, it needs to be renamed to match the [token_reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md), have an [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) and use [version](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md).
