### ISSUE TITLE
brew cask remove intellij-idea removes custom unrelated shell skript "idea"

### ISSUE THREAD

**Issue by phdoerfler** [caskroom/homebrew-cask#37371]
#### Description of issue

when running `brew cask remove intellij-idea` a custom shell script called `idea` residing in `~/bin/` gets deleted too. I wrote that shell script and had to restore it from a backup. I don't see why homebrew cask should ever feel like touching it.

```bash
% ls -la ~/bin/idea
-rwxr--r-- 1 phi staff 1813 Jan 31  2016 /Users/phi/bin/idea

% brew cask install intellij-idea
==> Satisfying dependencies
==> Downloading https://download.jetbrains.com/idea/ideaIU-2017.2.1.dmg
Already downloaded: /Users/phi/Library/Caches/Homebrew/Cask/intellij-idea--2017.2.1,172.3544.35.dmg
==> Verifying checksum for Cask intellij-idea
==> Installing Cask intellij-idea
==> Moving App 'IntelliJ IDEA.app' to '/Applications/IntelliJ IDEA.app'.
🍺  intellij-idea was successfully installed!

% ls -la ~/bin/idea
-rwxr--r-- 1 phi staff 1813 Jan 31  2016 /Users/phi/bin/idea

% brew cask remove intellij-idea --verbose --debug
==> Uninstalling Cask intellij-idea
==> Uninstalling Cask intellij-idea
==> Un-installing artifacts
==> Determining which artifacts are present in Cask intellij-idea
==> 3 artifact/s defined
#<Hbc::Artifact::App:0x007fc4b381f248>
#<Hbc::Artifact::PostflightBlock:0x007fc4b381ff68>
#<Hbc::Artifact::Zap:0x007fc4b381fec8>
==> Un-installing artifact of class Hbc::Artifact::App
==> Removing App '/Applications/IntelliJ IDEA.app'.
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
==> Purging files for version 2017.2.1,172.3544.35 of Cask intellij-idea

% ls -la ~/bin/idea
gls: cannot access '/Users/phi/bin/idea': No such file or directory
```

I'm on Mac OS X 10.10 Yosemite.

**Comment by miccal** [comment]
I believe it is due to this part of the Cask:
```
uninstall_postflight do
    ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'idea') }.each { |path| File.delete(path) if File.exist?(path) }
  end
```

**Comment by commitay** [comment]
Jetbrains allows users to chose where to place a binary but should we change the `uninstall_postflight` on the Jetbrains casks do an `uninstall delete:` in `/usr/local/bin` (the Jetbrains default location for binaries) to avoid removing files with the same name in the users PATH?

Ping @vitorgalvao @leipert

**Comment by vitorgalvao** [comment]
It‘d be a shame to lose the flexibility of this because a single user by chance has a personal script that shares a name. Maybe we can refine it to:

```ruby
ENV['PATH'].split(File::PATH_SEPARATOR).reject { |path| path.start_with?('~') || path.start_with?('/Users/') }.map { |path| File.join(path, 'idea') }.each { |path| File.delete(path) if File.exist?(path) }
```

That way we ignore it if it’s in the user’s home dir. It might still defeat the purpose, but I’m not seeing a much better solution.

**Comment by phdoerfler** [comment]
The functionality you're referring to ("Tools -> Create Launcher Script") does allow the user to both specify the *location* and the *name* of the script. It just defaults to "idea" but may be given any other name by the user.
Thus IMHO it is unwise to just delete everything in $PATH which is called "idea". I would in fact not expect homebrew to deal with this at all and leave it to the user to deal with any manually created launcher script herself.
But that's just my six cents.

**Comment by vitorgalvao** [comment]
> It just defaults to "idea" but may be given any other name by the user.

And I bet close to none changes the name.

> I would in fact not expect homebrew to deal with this at all and leave it to the user to deal with any manually created launcher script herself.

Most users wold expect this to be dealt with. Especially since we have `zap` that is supposed to deal with *every trace* of an app. There’s a reason this removal is through: exactly because users care that we remove it.

**Comment by phdoerfler** [comment]
If one assumes that almost nobody will change it, I'd be in favor of deleting /usr/local/bin/idea after briefly checking it is indeed the file created by IntelliJ IDEA (See below).
Also, would it be unreasonable to move this functionality from `brew remove` to `brew zap`? My reasoning is that this file is created outside the installation process. If that's in line with how homebrew does things normally, that is.

There are quite a few people who are using a [custom `idea` launch script](https://gist.github.com/chrisdarroch/7018927).
To prevent the worst I'd therefore suggest to check whether the following line is present in the script:

```python
# see com.intellij.idea.SocketLock for the server side of this interface
```

or maybe this one:

```python
RUN_PATH = u'/Applications/IntelliJ IDEA.app'
```

one could even check if it matches the installation path of the "intellij-idea" cask.

I hope these suggestions make sense :)
Cheers!

**Comment by reitermarkus** [comment]
> I'd therefore suggest to check whether the following line is present

I think this would be the best approach.

**Comment by vitorgalvao** [comment]
> If one assumes that almost nobody will change it

The _name_, not the location.

> would it be unreasonable to move this functionality from `brew remove` to `brew zap`?

Not unreasonable, but also not possible. `zap` does not take complex commands.

> > I'd therefore suggest to check whether the following line is present
>
> I think this would be the best approach.

Agreed.

**Comment by vitorgalvao** [comment]
Also note we need a solution that’ll work for all Intellij casks.

**Comment by commitay** [comment]
> see com.intellij.idea.SocketLock for the server side of this interface

This line is in all of the Jetbrains binaries I've checked so far.

**Comment by vitorgalvao** [comment]
This should work:

```ruby
ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'idea') }.each { |path| File.delete(path) if File.exist?(path) && File.readlines(path).grep(/# see com.intellij.idea.SocketLock for the server side of this interface/).any? }
```

**Comment by reitermarkus** [comment]
That is one hell of a one-liner. 😄

**Comment by commitay** [comment]
```
== intellij-idea.rb ==
C: 16:166: [Corrected] Use %r around regular expression.
```
```ruby
ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'idea') }.each { |path| File.delete(path) if File.exist?(path) && File.readlines(path).grep(%r{# see com.intellij.idea.SocketLock for the server side of this interface}).any? }
```

**Comment by commitay** [comment]
I'll do this tomorrow if no one else does it first. Do we want to make this consistent for all the Jetbrains casks or just the ones with "generic" binaries (idea, mine, charm)?

**Comment by vitorgalvao** [comment]
> C: 16:166: [Corrected] Use %r around regular expression.

To think that rule was introduced because of me, and I forgot it!

> Do we want to make this consistent for all the Jetbrains casks

Yes. Easier to change it the future, if we need.

**Comment by commitay** [comment]
> To think that rule was introduced because of me, and I forgot it!

`brew cask style` is great, I hate to think how many mistakes I would make without it!
_____

https://github.com/caskroom/homebrew-cask/pull/37407 and https://github.com/caskroom/homebrew-versions/pull/4244
