### ISSUE TITLE
Cask request: RapidWeaver 7

### ISSUE THREAD

**Issue by barchard** [caskroom/homebrew-cask#37403]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name:
RapidWeaver 7

Homepage:
https://www.realmacsoftware.com/rapidweaver/

Download URL:
https://dl.devmate.com/com.realmacsoftware.rapidweaver/18678/1494499886/RapidWeaver-18678.zip

Description:

Version 7.4 (updated from v6.4)

RW7 compatibility:
https://kb.realmacsoftware.com/article/53-rapidweaver-system-compatibility-notes

**Comment by SConaway** [comment]
I download 7.4.1. from https://dl.devmate.com/com.realmacsoftware.rapidweaver/RapidWeaver.zip. I will update this today.

**Comment by barchard** [comment]
The link will deliver the latest version, including major updates. This will change the checksum with each release. I don't know if that is safe?

**Comment by barchard** [comment]
https://kb.realmacsoftware.com/section/4-release-notes

Some helpful links on versions.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37404
