### ISSUE TITLE
To squash or not to squash

### ISSUE THREAD

**Issue by sepehr** [caskroom/homebrew-cask#37418]
The docs are not clear whether a contributor should squash the commits upon change requests or not. While the [contribution guidelines](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#style-guide) says:  
> _"Do not squash commits after updating a Pull Request."_  

[Adding a cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#filing-a-pull-request-on-github) docs suggests to do so:  

> _"If a maintainer suggests some changes, just make them on the my-new-cask branch locally, squash, and push."_

You might want to resolve that.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37419/files

**Comment by vitorgalvao** [comment]
> https://github.com/caskroom/homebrew-cask/pull/37419/files

A few seconds faster than me.
