### ISSUE TITLE
Cask request: Audacity

### ISSUE THREAD

**Issue by yoanmalie** [caskroom/homebrew-cask#37460]
I know the Fossub URL are bad but there other link to get Audacity.

### Cask details

Name: Audacity

Homepage: http://www.audacityteam.org/

Download URL: http://www.audacityteam.org/download/mac/
There also this URL : https://sourceforge.net/projects/audacity/files/latest/download

Description: Audacity® is free, open source, cross-platform audio software for multi-track recording and editing.

**Comment by commitay** [comment]
The sourceforge downloads haven't been updated for two years.

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md

> The cask is so difficult to maintain, it constantly breaks. Happened only once so far, with Audacity, because it uses fosshub as a distribution site.
