### ISSUE TITLE
brew cask {list|outdated} returns errors

### ISSUE THREAD

**Issue by EmilVarona** [caskroom/homebrew-cask#37489]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When running `brew cask list` or `brew cask outdated`, I get the errors shown below.

#### Output of your command with `--verbose --debug`

```
$ brew cask outdated --verbose --debug --greedy
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:20:in `block in load'

==> Checking update info of Cask android-file-transfer
android-file-transfer (latest) != latest
==> Checking update info of Cask betterzipql
betterzipql (latest) != latest
==> Checking update info of Cask beyond-compare
==> Checking update info of Cask lastpass
lastpass (latest) != latest
==> Checking update info of Cask macvim
==> Checking update info of Cask mysqlworkbench
==> Checking update info of Cask quicklook-json
quicklook-json (latest) != latest
==> Checking update info of Cask sling
==> Checking update info of Cask spotify
spotify (latest) != latest
==> Checking update info of Cask textwrangler

$ brew cask list --verbose --debug
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:20:in `block in load'

android-file-transfer         mac-vim                       textwrangler
betterzipql                   mysqlworkbench
beyond-compare                quicklook-json
lastpass                      sling
dash                          spotify

```

#### Output of `brew cask doctor`

```
$ brew cask doctor --debug --verbose
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-5-gae1986a
caskroom/homebrew-cask (git revision 8ea0a; last commit 2017-08-08)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (7 files, 147.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3675 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib
/Library/Ruby/Gems/2.0.0/gems/psych-2.0.5/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="~/.rbenv/shims:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/bin:/usr/local/lib/ruby:/usr/local/opt/ruby193/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/libexec:/usr/local/opt/groovy/libexec/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by SConaway** [comment]
Those are just warnings.

**Comment by vitorgalvao** [comment]
> Warning: Calling "cask :v1 => 'token'" is deprecated!

You have some really old casks, there.

`brew cask reinstall $(brew cask outdated)` should fix your issue.

**Comment by EmilVarona** [comment]
@vitorgalvao Thanks but that is not fixing my situation. I've tried your example. The same apps have all reinstalled successfully. I immediately run `brew cask outdated` and the same errors and new reinstalled apps, reappear.  I get the same results if I uninstall/install. Is there some other way to determine which are the "really old casks"?

**Comment by commitay** [comment]
> Is there some other way to determine which are the "really old casks"?

https://github.com/caskroom/homebrew-cask/issues/37267

**Comment by vitorgalvao** [comment]
@EmilVarona I meant `brew cask reinstall $(brew cask outdated --greedy)`. `brew cask reinstall $(brew cask list)` might also work, to reinstall everything.

**Comment by EmilVarona** [comment]
Just to follow-up, the error I was receiving was due to having TextWrangler installed originally from homebrew and later from AppStore (a co-worker had installed from there). I deleted using homebrew, waited for the AppStore cache to rebuild and reinstalled. No more errors on `brew cask outdated`.
