### ISSUE TITLE
VirusTotal needs new screenshot

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#37520]
They’ve updated their look.

https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

**Comment by commitay** [comment]
The VirusTotal look has changed and reverted to the original a few times in the last couple of weeks.

It was briefly displaying the new look for me today but has since changed back.

I'll update the screenshot once the new look is permanent.

**Comment by commitay** [comment]
I managed to get a screenshot of the new look but VirusTotal has again reverted to the original look.

https://github.com/caskroom/homebrew-cask/pull/37531
