### ISSUE TITLE
Cask request: Sonos

### ISSUE THREAD

**Issue by skrzyszewski** [caskroom/homebrew-cask#37551]
### Cask details

Name: Sonos

Homepage: http://www.sonos.com/

Download URL: https://www.sonos.com/redir/controller_software_mac

Description: Sonos is the wireless Home Sound System that sets up quickly and makes listening easy. Use the free app to connect directly to your home WiFi network and send different songs to different rooms at the same time. Or enjoy one big favourite in perfect sync all through your house. Sonos plays all the most popular music services, internet radio, audiobooks, podcasts, music downloads – you can even set it up to play your vinyl collection.

**Comment by commitay** [comment]
[`caskroom/drivers`](https://github.com/caskroom/homebrew-drivers): [sonos](https://github.com/caskroom/homebrew-drivers/blob/master/Casks/sonos.rb)
