### ISSUE TITLE
Info/Feature req: Remove cask but keep application binary

### ISSUE THREAD

**Issue by winterflags** [caskroom/homebrew-cask#37562]
According to Homebrew-Cask's [USAGE.md][1]:

>     $ brew cask uninstall google-chrome
> 
> This will both **uninstall the Cask** and **remove applications** which were
> moved to /Applications.

Is there a way to keep the application binary in `/Applications` but just delete the cask, i.e. remove it from `brew cask list` and future cask updates?

If so, could that info be added to USAGE.md? Otherwise it might be a feature request.

  [1]: https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md

**Comment by miccal** [comment]
You can run the command
```
cd /usr/local/Caskroom/; rm -r google-chrome
```
which will remove `google-chrome` from `brew cask list`.

Can I ask why you want to do this, though?

**Comment by winterflags** [comment]
Thanks @miccal!

I am using [homebrew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade) to upgrade cask applications, using the command `brew cu -facy`. It seems the flag `-f` will force update casks that don't have a version number but are only "Latest". Right now it seems that it will reinstall the cask regardless if the latest version is already installed. 

I'm not sure if this is normal behaviour for `homebrew-cask` also, but I'd like to avoid reinstalling the same applications continuously (e.g. those that doesn't have an `appcast` or versioning in the DL URL. I therefore decided to remove cask functionality from those applications. Am I doing the right thing in this regard?

I'm also wondering if there's a way to check if a Cask is version-signed or just "Latest" before installing it via `brew cask install`.

**Comment by commitay** [comment]
> I'm also wondering if there's a way to check if a Cask is version-signed or just "Latest" before installing it via brew cask install.

> https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options
> `--require-sha`: abort installation of cask if no checksum is defined

**Comment by vitorgalvao** [comment]
> If so, could that info be added to USAGE.md? Otherwise it might be a feature request.

Nope. This is atypical and counter to the goals of HBC.

> I am using [homebrew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade) to upgrade cask applications

That script is unofficial in every way and relies on unreliable features. If you use external unofficial tools, you do so at your own risk and we won’t offer support for them.

Closing as all the questions have been answered.
