### ISSUE TITLE
Cask request: focus booster

### ISSUE THREAD

**Issue by allanchau** [caskroom/homebrew-cask#37577]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name:
focusbooster

Homepage:
https://www.focusboosterapp.com/

Download URL:
https://dcwy7j973b6zk.cloudfront.net/downloads/stable/focusbooster2.2.0.dmg

Description:
Based on the pomodoro technique, focus booster will empower you to maintain focus and manage distractions. Stay focused and fresh to get more done.

```ruby
cask 'focusbooster' do
  version '2.2.0'
  sha256 :no_check

  url 'https://dcwy7j973b6zk.cloudfront.net/downloads/stable/focusbooster2.2.0.dmg'
  name 'focusbooster'
  homepage 'https://www.focusboosterapp.com/'

  app 'focus booster.app'
end
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37578
