### ISSUE TITLE
Make `only_sha_changed` work in local `audit` as well

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#37572]
Refs https://github.com/caskroom/homebrew-cask/pull/37519#issuecomment-321116436.

**Comment by harry-7** [comment]
I want to take this up . I am new to the repo . I would be glad if someone guides me on how to start working on this. Thanks :)

**Comment by reitermarkus** [comment]
@harry-7, I suggest you start by taking a look at the `Audit` class, specifically [these lines](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/audit.rb#L63-L83).

**Comment by harry-7** [comment]
@reitermarkus  is there anyway I could test these changes without having a Mac ?

**Comment by reitermarkus** [comment]
Homebrew-Cask is only supported on Mac. It might be possible that `brew cask audit` also works on Linux, but why do you want to contribute to this project if you can't use it yourself?

**Comment by harry-7** [comment]
@reitermarkus  :-p I just was browsing through repos and found yours thats all . If thats not possible then its fine I will leave this here :-)

**Comment by reitermarkus** [comment]
You should look for something you would actually like to use, nevertheless thank you for your interest. 😉

**Comment by commitay** [comment]
I've since changed my mind on how useful this would be. 

With the confusion that the PR template seems to have caused, having a warning in local `audit` about `sha256` changes will probably mean users open issues instead of PRs.

I'd like to close this and remove it from the hacktoberfest list.

**Comment by vitorgalvao** [comment]
> I'd like to close this and remove it from the hacktoberfest list.

I could be persuaded either way. *Maybe* in the local `audit` it’d work, as it’d be just that with a huge link.

@reitermarkus If you agree with closing, feel free to do so.

**Comment by reitermarkus** [comment]
I didn't care either way before, and I assume no one of us will be implementing this in the near future, so I'm closing it.
