### ISSUE TITLE
Persist installed apps to a manifest file

### ISSUE THREAD

**Issue by rafaelrinaldi** [caskroom/homebrew-cask#3763]
Hey guys, this is something I've been thinking about lately.

I use cask in my home computer and in my computer at work. I now have a somewhat big number of apps installed (30+), all of them through cask.
What if we persist all installed apps to a manifest file of some sort? In my example I would have the manifest file versioned in Dropbox or something else and to have the apps "synced" between both computers I would just run `brew cask install`.
Let me know if you guys think this is something worth implementing.

:beers:

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation.

**Comment by rafaelrinaldi** [comment]
@vitorgalvao :+1: :muscle:
