### ISSUE TITLE
Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.

### ISSUE THREAD

**Issue by Kikitious** [caskroom/homebrew-cask#37710]
DavidtekiMacBook-Air:~ du$ brew install caskroom/cask/brew-cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3797, done.
remote: Compressing objects: 100% (3771/3771), done.
remote: Total 3797 (delta 42), reused 516 (delta 22), pack-reused 0
Receiving objects: 100% (3797/3797), 1.29 MiB | 60 KiB/s, done.
Resolving deltas: 100% (42/42), done.
Tapped 0 formulae (3,804 files, 4MB)
==> brew cask install caskroom/cask/brew-cask 
==> Creating Caskroom at /usr/local/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.
Error: Install incomplete.

**Comment by commitay** [comment]
You don't need to `brew install caskroom/cask/brew-cask`

> https://github.com/caskroom/homebrew-cask#lets-try-it
> To start using Homebrew-Cask, you just need Homebrew installed.

Try `brew cask install atom`

**Comment by Kikitious** [comment]
@commitay   I already installed the Homebrew,  now  I  want to install the "brew cask" , so I  used the  
`brew install caskroom/cask/brew-cask`.      I think `brew cask install atom` is used to install the "atom".  Perhaps the "brew cask" does not need to install?

**Comment by commitay** [comment]
> Perhaps the "brew cask" does not need to install?

Correct, "brew cask" does not need to be installed. Just run any `brew cask` command.

**Comment by Kikitious** [comment]
@commitay Thanks.^_^
