### ISSUE TITLE
Cask (update) request: Tranmission Remote GUI (5.8.1)

### ISSUE THREAD

**Issue by Zialus** [caskroom/homebrew-cask#37728]
### Cask details

Name: Tranmission Remote GUI

Homepage: https://github.com/leonsoft-kras/transmisson-remote-gui/

Download URL: https://github.com/leonsoft-kras/transmisson-remote-gui/releases

Description: The version in the current formula comes from sourceforge.net and is fairly old.

**Comment by commitay** [comment]
[leonsoft-kras-transmission-remote-gui](https://github.com/caskroom/homebrew-cask/blob/master/Casks/leonsoft-kras-transmission-remote-gui.rb)
