### ISSUE TITLE
Update homebrew-cask/Casks/murus.rb zaps

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#37725]
Add the following zap delete items for murus.rb:

`/etc/murus`
`/etc/murus.sh`

I found those items that are related to Murus that were not removed.

**Comment by commitay** [comment]
Please don't open issues for adding files to `zap`. 

See [getting-set-up-to-contribute](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#getting-set-up-to-contribute) and [submitting-your-change](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#submitting-your-changes) for how to open a PR.

**Comment by daylightbrightledlight** [comment]
Okay. I will do that.
