### ISSUE TITLE
Cask request: logisim-evolution

### ISSUE THREAD

**Issue by pqm** [caskroom/homebrew-cask#37738]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: logisim-evolution

Homepage: https://github.com/reds-heig/logisim-evolution

Download URL: http://reds-data.heig-vd.ch/logisim-evolution/logisim-evolution.jar

Description: Educational tool for designing and simulating digital logic circuits

Note: logisim is already available here, but development stopped in 2011

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37740

**Comment by pqm** [comment]
@commitay No launcher icon shows up, but I can launch from Terminal, is this normal?

**Comment by commitay** [comment]
Yes, `logisism-evolution` is a `jar` file that has to be launched via CLI.
