### ISSUE TITLE
ActiveTcl 8.6.4.1.299124 no longer available

### ISSUE THREAD

**Issue by CodeGnome** [caskroom/homebrew-cask#37753]
## Cask's Version Superseded: Old Version Gone
The current version has been superseded, and the old version is no longer available for download. Attempting to install the cask results in an HTTP 404 error:

```
$ brew cask install tcl
==> Satisfying dependencies
==> Downloading https://downloads.activestate.com/ActiveTcl/releases/8.6.4.1/ActiveTcl8.6.4.1.299124-macosx10.5-i386-x86_64

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'tcl' with message: Download failed: https://downloads.activestate.com/ActiveTcl/releases/8.6.4.1/ActiveTcl8.6.4.1.299124-macosx10.5-i386-x86_64-threaded.dmg
Error: Install incomplete.
```

## New Version
According to [the download site](https://www.activestate.com/activetcl/downloads) the current version is 8.6.6.8606, and there is no longer a DMG to download. The only option for the latest version is a PKG file. Other changes include:

1. A new directory structure for downloads.
1. A new naming convention for downloads.
1. A new SHA256 for the current package (obviously).

The [latest version](https://downloads.activestate.com/ActiveTcl/releases/8.6.6.8606/ActiveTcl-8.6.6.8606-macosx10.9-x86_64-402457.pkg) appears to be 64-bit, supports Mavericks (10.9) and up, and the [new SHA256](https://downloads.activestate.com/ActiveTcl/releases/8.6.6.8606/SHA256SUM) is `83f6cd8e06832546b8a23f4821165619c47ac8ce6878e154ef8d3456039839cb`.

Changing the formula will require more than just updating the *version* and *sha256* strings in the current formula. Other changes will also be needed install the .pkg file using the new URL path and naming convention.

## See Also
https://www.activestate.com/activetcl/downloads
https://downloads.activestate.com/ActiveTcl/releases/8.6.6.8606/

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37761
