### ISSUE TITLE
Cask request: Thonny

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#37766]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Thonny

Homepage: http://thonny.org/

Download URL: https://bitbucket.org/plas/thonny/downloads/thonny-2.1.11.dmg

Description: Python IDE for beginners

**Comment by daylightbrightledlight** [comment]
I looked at (how to add a cask)[https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md] but I didn't understand how to do it in the terminal. It should look something like this:

```
cask 'thonny' do
  version '2.1.11'
  sha256 '346d5ba542d37ece44732c4b438ba0b45bc5e4323e251892457ceef4bb777ac4'

  url 'https://bitbucket.org/plas/thonny/downloads/thonny-2.1.11.dmg'
  name 'Thonny'
  homepage 'http://thonny.org/'

  app 'Thonny.app'
end
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37767
