### ISSUE TITLE
Unable to install android-sdk on a mac machine using my company proxy.

### ISSUE THREAD

**Issue by phaniteja** [caskroom/homebrew-cask#37774]
#### General troubleshooting steps

- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Unable to install android-sdk on a mac machine using my company proxy.

#### Output of your command with `--verbose --debug`

$ ALL_PROXY=http://XXX.XXX.XXX:YYYY brew cask install --verbose --debug android-sdk

==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/admin/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Downloaded to -> /Users/admin/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/admin/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/admin/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/admin/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip", "/var/folders/r9/znc2w2xs6_bdmm__sqy6qkcm0000gp/T/d20170818-44264-9cknuq"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20170818104211.134.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20170818104211.134/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007f916787ea88>
#<Hbc::Artifact::Binary:0x007f916787e998>
#<Hbc::Artifact::PostflightBlock:0x007f916787e8d0>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;26.0.1"]
==> Warning: java.net.ConnectException: Operation timed out (Connection timed out)
==> Warning: File /Users/admin/.android/repositories.cfg could not be loaded.
==> Warning: Failed to download any source lists!
==> Warning: Failed to find package tools
==> Purging files for version 3859397,26.0.1 of Cask android-sdk
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager tools platform-tools build-tools;26.0.1

==> Standard Output of failed command:

==> Standard Error of failed command:
Warning: java.net.ConnectException: Operation timed out (Connection timed out)
Warning: File /Users/admin/.android/repositories.cfg could not be loaded.
Warning: Failed to download any source lists!
Warning: Failed to find package tools

==> Exit status of failed command:
#<Process::Status: pid 44389 exit 1>
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

#### Output of `brew cask doctor`

$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1
caskroom/homebrew-cask (git revision ea02e; last commit 2017-08-18)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 82.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3698 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (164 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Cellar/maven/3.5.0//bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin.:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

**Comment by commitay** [comment]
We don't support installing with proxy options.

I'd suggest [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for `android-sdk` which would allow to you add proxy options to the cask.
