### ISSUE TITLE
There is no cask for java 7

### ISSUE THREAD

**Issue by moonfruit** [caskroom/homebrew-cask#37772]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

We have casks for `java6`, `java` (8) even `java9-beta`, but why there is no cask for java 7?

**Comment by commitay** [comment]
Oracle moved java 7 behind a login.

https://github.com/caskroom/homebrew-versions/pull/3914
