### ISSUE TITLE
Can't confirm upgrading an app

### ISSUE THREAD

**Issue by fepegar** [caskroom/homebrew-cask#37781]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I can't answer to "`Do you want to upgrade 1 app [y/N]?`". When I try to upgrade `slicer-nightly`, I am asked this confirmation question but I don't get the chance. I see a `%` after the question and the process finishes immediately. I am using `zsh` in iTerm2. I have also tried `bash` and Terminal.

#### Output of your command with `--verbose --debug`

I haven't used `--verbose` and `--debug` because I get an `invalid option` error when I try.

```
➜  ~ brew cask upgrade slicer-nightly
==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Updated 1 tap (caskroom/cask).
No changes to formulae.
==> Finding outdated apps
     Cask            Current             Latest              A/U    Result
1/1  slicer-nightly  4.7.0.26273,676538  4.7.0.26289,677302       [OUTDATED]
==> Found outdated apps
     Cask            Current             Latest              A/U    Result
1/1  slicer-nightly  4.7.0.26273,676538  4.7.0.26289,677302       [OUTDATED]

Do you want to upgrade 1 app [y/N]? %
➜  ~
```

#### Output of `brew cask doctor`

```
➜  ~ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-49-gdaa0ea4
caskroom/homebrew-cask (git revision 1ee904; last commit 2017-08-18)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (39 files, 5.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3698 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (109 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1110 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (164 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
PATH="~/fsl/bin:~/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/bin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
➜  ~
```

**Comment by commitay** [comment]
`brew cask upgrade` isn't implemented yet. https://github.com/caskroom/homebrew-cask/issues/29301

If you're using `buo/homebrew-cask-upgrade`, we don't provide support for this as it is an external tool. Any issues with it need to be reported at https://github.com/buo/homebrew-cask-upgrade
