### ISSUE TITLE
Cask request: VSCode

### ISSUE THREAD

**Issue by TGNYC** [caskroom/homebrew-cask#37822]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: VSCode

Homepage: https://code.visualstudio.com

Download URL: https://code.visualstudio.com/docs/?dv=osx

Description: Code Editor from Microsoft

**Comment by commitay** [comment]
[`visual-studio-code`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/visual-studio-code.rb)
