### ISSUE TITLE
Cask request: Softorino YouTube Converter 2

### ISSUE THREAD

**Issue by nkalvi** [caskroom/homebrew-cask#37833]
### Cask details

YT Converter. Music Downloader. Ringtones Maker.

Name:
Softorino YouTube Converter 2

Homepage:
https://softorino.com/youtube-converter-2/

Download URL:
https://dl.devmate.com/com.softorino.syc2/SYC2.dmg

Description:

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37839
