### ISSUE TITLE
Outdated Cask BetterTouchTool

### ISSUE THREAD

**Issue by quintrino** [caskroom/homebrew-cask#37841]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Outdated Checksum for Bettertouchtool cask

brew cask install bettertouchtool --verbose --debug

==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://bettertouchtool.net/releases/btt2.291.zip
Already downloaded: /Users/XXXX/Library/Caches/Homebrew/Cask/bettertouchtool--2.291.zip
==> Downloaded to -> /Users/XXXX/Library/Caches/Homebrew/Cask/bettertouchtool--2.291.zip
==> Verifying download
==> Determining which verifications to run for Cask bettertouchtool
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask bettertouchtool
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'bettertouchtool' does not match.

Expected: ff6b23d340def3fb5dd0b774c2c478e910e5e37ac4a88c90d246ee7c605df7cc
Actual:   1f8f3613212f8f2f1a21cee023559d3f79611a4b5ef5f727b2bba75d6dd0f321
File:     /Users/XXXX/Library/Caches/Homebrew/Cask/bettertouchtool--2.291.zip
```

#### Output of `brew cask doctor`

Nothing related to BetterTouchTool.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37842
