### ISSUE TITLE
Cask request: Wolfram CDF Player

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#37861]
### Cask details

Name: Wolfram CDF Player

Homepage: http://www.wolfram.com/cdf-player/

Download URL: http://www.wolfram.com/cdf-player/ or http://demonstrations.wolfram.com/download-cdf-player.html

Description: CDF Player is a Computable Document Format viewer developed by Wolfram Research.

**Comment by commitay** [comment]
> https://dl.wolframcdn.com/0036F4/CDFPlayer/11.1.1.0/CDFPlayer_11.1.1_MAC.pkg?4ae6ee529e4e0d5967853e9e61b23dfe434ce96afca382fea697fa4f397951c4e30fcd256f47d6e08213effb2c48d23928000947a54bfe097d78527bf01abe1f647203f17a52adb84c22.pkg

> https://dl.wolframcdn.com/0036F4/CDFPlayer/11.1.1.0/CDFPlayer_11.1.1_MAC.pkg?4ae6ee529e4e0d5967853e9e61b23dfe434ce96afca382fea697fa4f397858c02814b076d42e4b2960f99b71c42a9c96a22e1dd81ac30ed9b9a35793801bac54c85c0aa96e1e874edb8d.pkg

> https://dl.wolframcdn.com/0036F4/CDFPlayer/11.1.1.0/CDFPlayer_11.1.1_MAC.pkg?4ae6ee529e4e0d5967853e9e61b23dfe434ce96afca382fea697fa4f397858c6b9077f02c79fad6de45bf5ee44783f62e63bdfd8d3b94d6bc3a17b4fcdf4eb0d1d35eca276949300d522.pkg

This has a one time URL, we can't add it to HBC.
