### ISSUE TITLE
Cask request: macSVG

### ISSUE THREAD

**Issue by yuhr** [caskroom/homebrew-cask#37885]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: macSVG

Homepage: [http://macsvg.org](http://macsvg.org)

Download URL: [http://macsvg.org/download/](http://macsvg.org/download/)

Description: macSVG is a MIT-licensed open-source macOS application for designing and editing Scalable Vector Graphics (SVG) content for HTML5 web pages, mobile apps, animation design, and general graphics usage.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37888
