### ISSUE TITLE
Cask request: Shifty

### ISSUE THREAD

**Issue by guillaumebriday** [caskroom/homebrew-cask#37892]
### Cask details

Name: Shifty

Homepage: http://shifty.natethompson.io/

Download URL: https://github.com/thompsonate/Shifty/releases/download/0.2/Shifty-0.2.dmg

Description: Shifty is a macOS menu bar app that gives you more control over Night Shift.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37893

**Comment by guillaumebriday** [comment]
Great ! Thank you @commitay
