### ISSUE TITLE
Cask request: Vellum

### ISSUE THREAD

**Issue by rjstanford** [caskroom/homebrew-cask#37924]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: Vellum

Homepage: https://vellum.pub

Download URL: https://get.180g.co/download/Vellum-Installer.zip

Description:

Vellum allows you to compile a document into various eBook formats, either for personal use or for distribution through one of the commercial eBook storefronts.

**Comment by rjstanford** [comment]
NOTE: Upon download, the system prompts for an optional email address for a mailing list and then installs the actual application.  I know when installing some files such as Office that more complex workflows like this are automatable but I confess that this kind of installer scripting isn't something I'm familiar with.  I would suggest that having "brew cask install vellum" result in Vellum.app appearing in /Applications with no interstatial request on first open would make the most sense.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37937
