### ISSUE TITLE
Feature request: generate zap stanza in brew cask create template

### ISSUE THREAD

**Issue by nrlquaker** [caskroom/homebrew-cask#37948]
### Description of feature/enhancement
I've created a [simple script](https://github.com/nrlquaker/brewcask-createzap) that scans common folder for leftover files and generates zap stanza. I'm not that good with bash but maybe it can be intergrated to `brew cask create`.

### Justification
Its seems that not that much people add zap stanza into formulas. So, when uninstalling casks a lot of leftover files are present.

### Example use case

Create zap stanza automatically when using `brew cask create`.

**Comment by commitay** [comment]
A better approach is proposed in https://github.com/caskroom/homebrew-cask/issues/16339
