### ISSUE TITLE
Cask building went wrong

### ISSUE THREAD

**Issue by jledbetter460** [caskroom/homebrew-cask#37965]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I tried to upload foxit pdf reader as a cask and I dont know what I did wrong.

#### Output of your command with `--verbose --debug`

```
Error: /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:12: syntax error, unexpected tFLOAT, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
  version :2.4.1.0609
              ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:12: no .<digit> floating literal anymore; put 0 before dot
  version :2.4.1.0609
               ^
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:43:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:147:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:68:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cat.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cat.rb:14:in `cat_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cat.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/jledbetter460/anaconda/bin/curl-config
  /Users/jledbetter460/anaconda/bin/freetype-config
  /Users/jledbetter460/anaconda/bin/icu-config
  /Users/jledbetter460/anaconda/bin/libpng-config
  /Users/jledbetter460/anaconda/bin/libpng16-config
  /Users/jledbetter460/anaconda/bin/python3-config
  /Users/jledbetter460/anaconda/bin/python3.6-config
  /Users/jledbetter460/anaconda/bin/python3.6m-config
  /Users/jledbetter460/anaconda/bin/xml2-config
  /Users/jledbetter460/anaconda/bin/xslt-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
  //anaconda/bin/curl-config
  //anaconda/bin/freetype-config
  //anaconda/bin/glue-config
  //anaconda/bin/icu-config
  //anaconda/bin/libdynd-config
  //anaconda/bin/libpng-config
  //anaconda/bin/libpng16-config
  //anaconda/bin/python3-config
  //anaconda/bin/python3.5-config
  //anaconda/bin/python3.5m-config
  //anaconda/bin/xml2-config
  //anaconda/bin/xslt-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Your Xcode (8.2.1) is outdated.
Please update to Xcode 8.3.3 (or delete it).
Xcode can be updated from the App Store.```

**Comment by commitay** [comment]
> I tried to upload foxit pdf reader as a cask and I dont know what I did wrong.

I don't understand what you are trying to do here. What command did you run?

Also please post the output of `brew cask doctor` not `brew doctor.`

**Comment by jledbetter460** [comment]
I tried to run brew cask install foxitreader from local files 
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-4371-g6d393de
caskroom/homebrew-cask (git revision cd378; last commit 2017-08-24)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3710 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (113 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1112 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (166 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/anaconda/bin:~/anaconda2/bin:~/anaconda3/bin:/usr/local/opt/sqlite/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.5/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

**Comment by vitorgalvao** [comment]
> I tried to run brew cask install foxitreader from local files

What does that even mean? Please *post* your exact command; don’t describe it. We need accurate and exact information. And if you’re using a custom cask, post that as well.

Also, use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks). Your post is barely readable.

**Comment by jledbetter460** [comment]
{ brew cask install foxit-reader
==> Satisfying dependencies
==> Downloading http://cdn09.foxitsoftware.com/pub/foxit/reader/desktop/mac/2.x/
Already downloaded: /Users/jledbetter460/Library/Caches/Homebrew/Cask/foxit-reader--2.4.1.0609.pkg
==> Verifying checksum for Cask foxit-reader
==> Installing Cask foxit-reader
Error: It seems the App source '/usr/local/Caskroom/foxit-reader/2.4.1.0609/FoxitReader.app' is not there.
Error: Install incomplete.}
I fixed part of the problem with the sha256 but the app refuses to install. No custom cask. This does not happen to other casks

**Comment by vitorgalvao** [comment]
There’s no `foxit-reader` cask in any official repo. What you have is a badly made cask file. You’ll have to complain to whatever repo you got it from.

The error is pretty clear, though. It’s downloading a `pkg` but trying to locate an `app`, when it should be using [`pkg`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md).

Closing.
