### ISSUE TITLE
Cask request: [HazeOver]

### ISSUE THREAD

**Issue by vitmy0000** [caskroom/homebrew-cask#37961]
### Cask details

Please fill out as much as possible. Before you do, note **we cannot support Mac App Store-only apps**.

Name: HazeOver

Homepage: https://hazeover.com/

Download URL: https://hazeover.com/HazeOver.dmg

Description: HazeOver automatically highlights the front app window by fading out all the background windows.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37963
