### ISSUE TITLE
install success but can't find application icon

### ISSUE THREAD

**Issue by WangChangQin** [caskroom/homebrew-cask#37977]
#### General troubleshooting steps

- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I install brew with default config,and then run `brew cask install quicklook-json`, 

`==> Creating Caskroom at /usr/local/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
==> Satisfying dependencies
==> Downloading http://www.sagtau.com/media/QuickLookJSON.qlgenerator.zip
######################################################################## 100.0%
==> No checksum defined for Cask quicklook-json, skipping verification
==> Installing Cask quicklook-json
==> Moving QuickLook Plugin 'QuickLookJSON.qlgenerator' to '/Users/wangchangqin/
🍺  quicklook-json was successfully installed!

how can I find and run this app? thanks

**Comment by commitay** [comment]
`quicklook-json` isn't an `app` it's a plugin for the macOS `Preview.app`

**Comment by commitay** [comment]
[macOS Sierra: Quick Look files and folders](https://support.apple.com/kb/PH25575)
