### ISSUE TITLE
microsoft-office install leaves installer .pkg in Caskroom

### ISSUE THREAD

**Issue by edrozenberg** [caskroom/homebrew-cask#38031]
The caskroom (```/usr/local/Caskroom/```) normally contains installation artifacts - doc files and other supporting files that result from an install.

But for microsoft-office, ```/usr/local/Caskroom/microsoft-office/15.37.17081500``` contains the installer package ```Microsoft_Office_2016_15.37.17081500_Installer.pkg```.

This pkg is not an installation artifact, and it is already stored as ```/Users/<me>/Library/Caches/Homebrew/Cask/microsoft-office--15.37.17081500.pkg```

Suggestion: this pkg should not be stored in ```/usr/local/Caskroom/microsoft-office/<version>``` since it is the installer package, not an artifact resulting from the installation.

It would also save 1.6GB not having it in Caskroom unnecessarily.

**Comment by commitay** [comment]
> The caskroom (```/usr/local/Caskroom/```) normally contains installation artifacts - doc files and other supporting files that result from an install.

This folder is `{staged_path}`, not installation artifacts.

> This pkg is not an installation artifact, and it is already stored as ```/Users/eduardr/Library/Caches/Homebrew/Cask/microsoft-office--15.37.17081500.pkg```

This is a cache, not a permanent copy.

This has been requested previously (https://github.com/caskroom/homebrew-cask/issues/28528) and closed because it may be required as part of https://github.com/caskroom/homebrew-cask/issues/29301

**Comment by charlietomo** [comment]
Does this mean that in the meantime it is safe to manually remove the 1.6gb pkg file in /usr/local/Caskroom/microsoft-office/ ? Thanks in advance.

**Comment by commitay** [comment]
Yes, you can remove it.
