### ISSUE TITLE
Cask request: Dragand

### ISSUE THREAD

**Issue by lironess** [caskroom/homebrew-cask#38074]
### Cask details

Name: Dragand

Homepage: http://dragand.watch/

Download URL: http://bit.ly/1DvWSNE

Description: quickly get subtitles to any movie/series by dragging the file with the movie/series to a dropzone provided by the app. You can choose your subtitles from 41 languages ​​available and watch with VLC.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38075
