### ISSUE TITLE
Add paid_updates

### ISSUE THREAD

**Issue by Rbcafe** [caskroom/homebrew-cask#38165]
Greetings,

I have noticed that some software on the repositories are **paid_updates**.

It would be interesting to add an element inside the **casks** : 

> paid_updates true | false

Then it would be possible via 

> brew cask outdated 

to know if the update of a specific **cask** would break a previous licensed version.

Best regards

@Rbcafe

**Comment by commitay** [comment]
The main repository always has the latest version of a cask. Legacy versions can be added to [`caskroom/versions`](https://github.com/caskroom/homebrew-versions#acceptable-casks)
```
- Include the latest minor version of legacy versions of commercial and freemium software.
- Legacy versions of commercial and freemium software are restricted to a maximum of five casks.
```
