### ISSUE TITLE
Now Outdated (ableton casks)

### ISSUE THREAD

**Issue by SpaceJanitor** [caskroom/homebrew-cask#38164]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Please update script with latest:
*/9.7.4/ableton_live_suite_9.7.4_64.dmg
*/9.7.4/ableton_live_suite_9.7.4_32.dmg
*/9.7.4/ableton_live_suite_9.7.4_64.zip
*/9.7.4/ableton_live_suite_9.7.4_32.zip

**Comment by commitay** [comment]
[Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/38183

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38185
