### ISSUE TITLE
Outdated cask: Xee

### ISSUE THREAD

**Issue by carpii** [caskroom/homebrew-cask#38194]
Outdated cask: 

[`xee`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/xee.rb)

* Insert the new version of the app: 3.5.2 (checksum 094a80860ab87ca6645fe9360343906fd5aeba7fcbee9085baa1d94077d3a6a7)

Sorry if I didn't do this right, the Issue template was a little confusing.

`brew cask install xee` does download, but then aborts due to incorrect checksum

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38198
