### ISSUE TITLE
Feature request: Link app with a wrap script

### ISSUE THREAD

**Issue by pynixwang** [caskroom/homebrew-cask#38241]
### Description of feature/enhancement
cask spec has a `binary` dsl, but most of cask cant use because it needs a wrap script, can cask provide a command to wrap and link it?

### Justification
for command line user

### Example use case
`brew cask link google-chrome`
create a bash script in `/usr/local/bin` and put wrap script.
`'/Applicaiton/Google Chrome' "$@"`

now you can type `google-chrome` in command line

**Comment by commitay** [comment]
Implementing shimscripts is an open issue. https://github.com/caskroom/homebrew-cask/issues/18809

Currently we use `preflight` to write a shimscript but this discouraged and only used in specific situations.

https://github.com/caskroom/homebrew-cask/blob/534f255c7bc9eb6c8153c86fc22ed2c821c8cff2/Casks/vlc.rb#L14-L24

**Comment by pynixwang** [comment]
@commitay  I means do this wrap by user if the package maintainer does 'nt provider it in cask spec.
