### ISSUE TITLE
Making anka build available through Homebrew

### ISSUE THREAD

**Issue by medicis123** [caskroom/homebrew-cask#38251]
#### Description of issue

{{I noticed that anka flow is available for download, but anka build isn't< is it possible to make anka build also available for download through Homebrew?}}

#### Output of your command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

**Comment by commitay** [comment]
If you would like add Anka Build to Homebrew Cask please open a pull request.
