### ISSUE TITLE
Feature request: Install command-line utilities outside `/usr/local`

### ISSUE THREAD

**Issue by rudi** [caskroom/homebrew-cask#38254]
### Description of feature/enhancement

It would be great to have a parameter similar to `--appdir` but for command-line utilities.  The benefit of this enhancement is to install command-line utilities below the user home directory.

When compiling programs from source (via `./configure` / `make` / `make install` or similar), there's usually a way to specify such a path already (`./configure --prefix=/Users/myname/Library`), and many programs know to ready an environment variable to locate supporting libraries in case they're not in a standard location.

### Justification

Homebrew supports installation outside of `/usr/local`, including below the user's home directory, and this works well in my experience.  Cask supports installing applications in other locations than `/Applications` already, and puts other artifacts (fonts, dictionaries, ...) below the user's home directory by default.  Especially for users without admin access, being able to install command-line utilities in a similar way would be great.

### Example use case

To install CMU Common Lisp, which is a command-line utility and hence does not obey `--appdir`, the following command would install it in `~/Library/bin`, `~/Library/lib`, etc.:

`brew cask install cmucl --clidirprefix=/Users/myname/Library`

The user would be responsible to set up their `$PATH` and other environment variables appropriately.

**Comment by vitorgalvao** [comment]
We had such an option in the past (`--binarydir`) but have since removed it. We now install CLI tools to wherever Homebrew does as well, in your setup. Change one, you’ll change the other.

We will not reintroduce `binarydir`, as it’s not worth it.

Either way, thank you for the well made feature request.

**Comment by rudi** [comment]
Thank you for the reply!  It seems the formula for cmucl overrides this configuration (this is what started this request):

```
  binary 'bin/lisp'
  artifact 'lib/cmucl', target: '/usr/local/lib/cmucl'
  artifact 'man/man1/cmucl.1', target: '/usr/local/share/man/man1/cmucl.1'
  artifact 'man/man1/lisp.1', target: '/usr/local/share/man/man1/lisp.1'
```

I'll investigate a fix for that formula.

**Comment by vitorgalvao** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/38259/files.
