### ISSUE TITLE
Goodsync 10.5.2 checksum fail

### ISSUE THREAD

**Issue by splttingatms** [caskroom/homebrew-cask#38275]
Cannot install Goodsync because of checksum verification failure.

### Error
```
Error: Checksum for Cask 'goodsync' does not match.

Expected: ee94b9715c6f7b8785f8c24c0da8f08426c1824b27eb6a140fb81c771414d050
Actual:   98fb97a8d726dd6a5acb73f56b3edb0e499b2e54f9f2283fd281fa98449f91fb
File:     /Library/Caches/Homebrew/Cask/goodsync--10.5.2.dmg
```
### Code
https://github.com/caskroom/homebrew-cask/blob/004fd429f5f805a1cf4f809fff20ecf6d3eff5a7/Casks/goodsync.rb#L3

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/38277
