### ISSUE TITLE
Incorrect Checksum for WebEx Players

### ISSUE THREAD

**Issue by barchard** [caskroom/homebrew-cask#38279]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

```
Error: Checksum for Cask 'webex-wrf-player' does not match.

Expected: c41c01efa99afef50592acf42f91a34fe5cb18f42563bb0ec3802c2229128592
Actual:   ab7a11c78c9c0e97ea4c823efbdec97f151ff9af9d762cac9729d42fa1f821b9
```

```
==> Verifying checksum for Cask webex-nbr-player
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'webex-nbr-player' does not match.

Expected: 59fa6ad215d451ded9c5cb269aed237d02eacd639fc1e30a464725194d68af5f
Actual:   83bf06780d8fbea07ac7e7f590e7b7d9030db62524725a3a24416c0c44fbc0ea
```

This error persisted after running `brew update` and removing the file and trying again.

#### Output of your command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38283, https://github.com/caskroom/homebrew-cask/pull/38284
