### ISSUE TITLE
Cask request: LuLu (Objective-See)

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#38525]
### Cask details

Name: LuLu

Homepage: https://objective-see.com/products/lulu.html

Download URL: https://raw.githubusercontent.com/objective-see/LuLu/master/deploy/LuLu.zip

Description: LuLu is the free open-source macOS firewall that aims to block unauthorized (outgoing) network traffic
____
Currently in alpha.

Issues with installation* prevent this from being added at the moment. 

Making this a Cask request so I don't forget about it.

*Currently installing with HBC fails. Manual install is successful.

**Comment by vitorgalvao** [comment]
> Download URL: https://github.com/objective-see/LuLu/blob/master/deploy/LuLu.zip (doesn't work)

Would need to be https://raw.githubusercontent.com/objective-see/LuLu/master/deploy/LuLu.zip

**Comment by commitay** [comment]
> Would need to be https://raw.githubusercontent.com/objective-see/LuLu/master/deploy/LuLu.zip

Thanks, I always forgot that!
