### ISSUE TITLE
Feature request: `audit --download` should check if app name is correct

### ISSUE THREAD

**Issue by leipert** [caskroom/homebrew-cask#38528]
### Description of feature/enhancement

`brew cask audit --download cask` should check if a dmg contains an app like described in the Cask.

### Justification

We are already downloading the dmg to check the checksum, it should be easy to mount the dmg (the source code is there) and check if the app exists.

### Example use case

For example, in this MR the Name of the app changed:
https://github.com/caskroom/homebrew-cask/pull/37346/files

Travis would have shown a green build, if I hadn't change the app name. A "careless" merge would have broken the Cask for everyone, as the app could not be copied during install.

- - - 

I would implement it myself, but I have a real hard time to get started with ruby and I think it is a small feature for the hbc developers. Thank you, as always for your hard work.

**Comment by commitay** [comment]
I've been thinking about adding `brew cask install` to the Travis CI script. This would check that all casks can be installed without having to make changes to `audit`.

https://github.com/caskroom/homebrew-cask/blob/f94bc13844a662ac8811f703a0da6ba3174ca76b/ci/travis/script.sh#L21-L26

**Comment by reitermarkus** [comment]
Travis supports `sudo`, [which we are not currently using](https://github.com/caskroom/homebrew-cask/blob/343e374fca766f58d7215884315e814d561c71e4/.travis.yml#L3).

**Comment by commitay** [comment]
A quick Travis test (setting `sudo` and adding `brew cask install`) seems to work. https://github.com/caskroom/homebrew-cask/pull/38542/commits/08ec68088ab64fdf1b3b733005c6de8f4f4e8f38

https://travis-ci.org/caskroom/homebrew-cask/builds/274798934

https://travis-ci.org/caskroom/homebrew-cask/builds/274814795

**Comment by leipert** [comment]
While I think it installing them in Travis is good 👍 , It doesn't solve my actual problem:
I want to check if the dmg is there without installing.

I'll probably have to resort to:

```bash
brew cask audit --download rider

# find out where to the dmg is downloaded, it is prompted if i run audit twice
location=$(brew cask audit --download rider | grep -oe '/Users.*.dmg')

# get the appname (funnily it is sorrounded by brackets !?)
appname=$(brew cask _stanza app rider | sed 's/\[\["//' | sed 's/"\]\]//')

# check if the dmg contains a folder with the app name
if 7z l "{$location}" | grep -q "/${appname}/" ; then
	echo "appname fits"
else
	echo "appname mismatch"
fi
```

**Comment by vitorgalvao** [comment]
> funnily it is sorrounded by brackets !?

There can be multiple occurrences in a cask, hence it’s an array.

**Comment by leipert** [comment]
Ah, thanks 👍 

I will probably use the script I posted above for my purposes, but generally this issue can be closed once installs are tried on travis.

**Comment by reitermarkus** [comment]
> hence it’s an array

It's not just an array. It's an array of arrays, because this is also possible:

```ruby
[["AppName.app", {:target => "OtherName.app"}]]
```
