### ISSUE TITLE
Cask request: Ableton Live Intro

### ISSUE THREAD

**Issue by decorate** [caskroom/homebrew-cask#38560]
### Cask details

Name: Ableton Live Intro
Homepage: https://www.ableton.com/en/live/
Download URL: http://cdn-downloads.ableton.com/channels/9.7.4/ableton_live_intro_9.7.4_64.dmg
Description: Same as https://github.com/caskroom/homebrew-cask/blob/master/Casks/ableton-live-standard.rb but different tier.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38564
