### ISSUE TITLE
Feature request: add ability to brew install multiple times without downloading package and logging error

### ISSUE THREAD

**Issue by danielcompton** [caskroom/homebrew-cask#38703]
### Description of feature/enhancement

Add the ability to run `brew install` multiple times without downloading the entire package before emitting an error that it is already installed.

### Justification

I use a Brewfile to keep my Homebrew formulas, Casks, and MAS apps in sync between my laptop and desktop. My ideal workflow is that every now and then I run `brew bundle` on each computer and it will install any missing apps, and upgrade existing ones. 

This works great for homebrew formulas, and if there is nothing to install/upgrade then the process finishes quickly. When I include my Casks in the Brewfile, `brew bundle` will try and download each binary, then check if the app exists, and finally throw an error for each because it is already installed.

```console
==> Satisfying dependencies
==> Downloading http://updates.designheresy.com/nvalt/nvALT2.2.7126.dmg
==> Verifying checksum for Cask nvalt
==> Installing Cask nvalt
Error: It seems there is already an App at '/Applications/nvALT.app'.
Error: Install incomplete.
Installing nvalt has failed!
```

It would be great if there was a strategy/way to run this which ensures my system converges to a known good state without having to redownload every Cask? While the exact scenario where this happens is in brew bundle, I don't think bundle can do much to improve things without additional changes in cask first?

My problem looks similar to https://github.com/Homebrew/homebrew-bundle/issues/258. I think this behaviour may have been introduced (at least the error parts) in https://github.com/Homebrew/brew/pull/1590. I took a look for similar feature requests but couldn't see anything, sorry if this is a dupe.

**Comment by vitorgalvao** [comment]
We already do this.

```
$ brew cask install alfred
Warning: Cask 'alfred' is already installed.

To re-install alfred, run:
  brew cask reinstall alfred
```

Your error is happening because for HBC the app isn’t marked as installed, and there’s a good chance you’ve installed it manually. The error occurs because it finds a file it does not want to overwrite.

You can confirm if the app is already installed with `brew cask list`. If it’s not, trash the app and install HBC, or install with `--force`.

**Comment by danielcompton** [comment]
Ah, you're right. I had originally installed them with Homebrew Cask but during the migration I must have lost that info. It could be useful for the error message to explain that the file is installed 'outside' of Homebrew Cask. Maybe something like:

```
Error: It seems there is already an App at '/Applications/nvALT.app'. Did you install it manually? To re-install nvalt with Homebrew Cask, run:
  brew cask install --force
```

**Comment by vitorgalvao** [comment]
> It could be useful for the error message to explain that the file is installed 'outside' of Homebrew Cask.

That’s an incredibly specific message for a confusion that almost never happens. Not worth it to elongate the message.
