### ISSUE TITLE
[question] Why travis build is failing?

### ISSUE THREAD

**Issue by budhrg** [caskroom/homebrew-cask#38774]
This is sort of question to get idea on why travis CI is failing for PR or master commits.

On visiting the travis build, I see following error.
```
This job was cancelled because the "Auto Cancellation" feature is currently enabled, and a more recent build (#77055) for pull request #38773 came in while this job was waiting to be processed.
```

Any idea?

**Comment by commitay** [comment]
We have auto cancel enabled because we don't need to re-check every PR/build after it is merged.
