### ISSUE TITLE
Permission denied - /Applications#

### ISSUE THREAD

**Issue by hao-lh** [caskroom/homebrew-cask#38803]
I tried to updated all outdated packages on my rMPB with brew cask scripts. The error lies at it does not have permission to move downloaded packages to /Applications directory. But it worked for me two months ago. I tried to give an example by reinstalling free-download-manager and following are detailed logs.

> brew cask reinstall free-download-manager --verbose
Warning: Calling `brew cask` with the `--caskroom` flag is deprecated and will be disabled on 2017-10-31!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `call'

> ==> Satisfying dependencies
==> Downloading http://dn3.freedownloadmanager.org/5/5.1-latest/fdm.dmg
Already downloaded: /Users/Hao/Library/Caches/Homebrew/Cask/free-download-manager--5.1.dmg
==> No checksum defined for Cask free-download-manager, skipping verification
==> Installing Cask free-download-manager
==> Moving App 'Free Download Manager.app' to '/Applications#/Free Download Manager.app'.
Error: Permission denied - /Applications#
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:559:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:33:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:48:in `block in each_artifact'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:46:in `each_artifact'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:121:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:68:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit

**Anyone knows how to solve this issue instead of moving packages to ~/Applications which is not preferred currently**?

**Comment by commitay** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

**Comment by hao-lh** [comment]
Hi commitay,

1. I've checked [permission denied section](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/permission_denied_error_fix_appdir.md) before submitting this issue.
2.  Current user is an admin on macOS 10.11 El Captain.
3. I've checked app bundle with `ll` command and it does have write permission.
`drwxr-xr-x`

Thanks!

**Comment by commitay** [comment]
@hao-lh Complete all steps in the issue template and provide all the requested information.

**Comment by hao-lh** [comment]
### Cask details



Name:free-download-manager

Homepage:https://www.freedownloadmanager.org

Download URL:http://dn3.freedownloadmanager.org/5/5.1-latest/fdm.dmg

Description:
Permission denied when moving downloaded package to - /Applications
Actually updating all outdated packages on my rMBP would fail and here free-download-manager is just an example.

1. I've checked [permission denied section](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/permission_denied_error_fix_appdir.md) before submitting this issue.
2. Current user is an admin on macOS 10.11 El Captain.
3. I've checked app bundle with `ll` command and it does have write permission.
`drwxr-xr-x`

> brew cask reinstall free-download-manager --verbose
Warning: Calling `brew cask` with the `--caskroom` flag is deprecated and will be disabled on 2017-10-31!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `call'


> ==> Satisfying dependencies
==> Downloading http://dn3.freedownloadmanager.org/5/5.1-latest/fdm.dmg
Already downloaded: /Users/Hao/Library/Caches/Homebrew/Cask/free-download-manager--5.1.dmg
==> No checksum defined for Cask free-download-manager, skipping verification
==> Installing Cask free-download-manager
==> Moving App 'Free Download Manager.app' to '/Applications#/Free Download Manager.app'.
Error: Permission denied - /Applications#
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:559:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:33:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:48:in `block in each_artifact'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:46:in `each_artifact'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:121:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:68:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit

**Comment by reitermarkus** [comment]
Seems like you're setting `appdir` to `/Applications#`.

**Comment by hao-lh** [comment]
Thanks a lot, reitermarkus.

Caused by previous configuration in .zshrc
`export HOMEBREW_CASK_OPTS="--appdir=/Applications# --caskroom=/usr/local/Caskroom"`
Issue resolved by removing pound mark.
Thanks again!
