### ISSUE TITLE
Cask request: font-noto-mono-for-powerline

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#38819]
### Cask details

Name: Noto Mono for Powerline

Homepage: https://github.com/powerline/fonts/tree/master/NotoMono

Download URL: https://github.com/powerline/fonts/blob/master/NotoMono/Noto%20Mono%20for%20Powerline.ttf

Description: Noto Mono for Powerline is a patched version of the Noto Mono font to work with the Powerline status-line plugin. See #38818.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-fonts/pull/1313
