### ISSUE TITLE
Cask 'wire's url value is invalid - curl returns 404 (correct value in info)

### ISSUE THREAD

**Issue by dotWee** [caskroom/homebrew-cask#38831]
The line

https://github.com/caskroom/homebrew-cask/blob/a98dac369340c911d7ca9335d551c2124646206b/Casks/wire.rb#L6

has to be changed into `url "https://github.com/wireapp/wire-desktop/releases/download/macos%2F#{version}/wire-{version}.pkg"`.

**Comment by commitay** [comment]
Can you submit a PR to fix it?

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38834
