### ISSUE TITLE
Firefox: Zap leaves files on system

### ISSUE THREAD

**Issue by SteveJobzniak** [caskroom/homebrew-cask#38841]
I've sometimes had to install Firefox to do some quick test, but I hate that browser and always uninstall it again. I noticed that the zap-command for the firefox cask leaves lots behind.

Here are the extra files left behind, found via `sudo find -x / -iname "*firefox*" -or -iname "*mozilla*"`:

```
/Library/Logs/DiagnosticReports/firefox_2017-09-22-123349_MacBook-Pro.wakeups_resource.diag
/Library/Logs/DiagnosticReports/firefox_2017-09-22-124555_MacBook-Pro.wakeups_resource.diag
/Library/Logs/DiagnosticReports/firefox_2017-09-22-124642_MacBook-Pro.cpu_resource.diag
~/Library/Caches/Mozilla/updates/Applications/Firefox
~/Library/Preferences/org.mozilla.firefox.plist
~/Library/Application Support/Mozilla
```

For some reason Firefox always creates those 3 diagnostic reports because they've been there every time I've uninstalled it, even though the app hasn't crashed even once.

As for the "Application Support/Mozilla" folder, it contains Extensions installed into Firefox, but it may be used by other non-Firefox mozilla applications, so you may want to keep that one.

But I think zapping these makes sense:

```
/Library/Logs/DiagnosticReports/firefox_*.diag
```

`~/Library/Caches/Mozilla/updates/Applications/Firefox (and then remove the entire tree up to and including Mozilla if the other folders are empty; I think I've seen that your zapper has the rmdir command for that kind of safe removal)`

```
~/Library/Preferences/org.mozilla.firefox.plist
```

**Comment by reitermarkus** [comment]
Feel free to add those to the Cask.

**Comment by SteveJobzniak** [comment]
@reitermarkus How can I locally edit and test the updated ”brew cask zap firefox”-command to make sure it works before I make a PR?

**Comment by reitermarkus** [comment]
Use `brew cask edit firefox`, then install it and run `brew cask zap firefox` as you normally would.

**Comment by SteveJobzniak** [comment]
Thanks. PR created. :-)
https://github.com/caskroom/homebrew-cask/pull/38858

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38858
