### ISSUE TITLE
Re-add Medis

### ISSUE THREAD

**Issue by molawson** [caskroom/homebrew-cask#38857]
I see that [Medis](https://github.com/luin/medis) was removed in #36382 because it was lagging behind the MAS version.

Now that the latest version 0.6.1 is on [GitHub](https://github.com/luin/medis/releases/tag/0.6.1) is there any interest in adding the package back to this repo?  If so, I'm happy to open a PR.

**Comment by commitay** [comment]
`0.6.1` on Github is source code, the binary is MAS only.
