### ISSUE TITLE
Various Opera browsers should have auto_updates set to true

### ISSUE THREAD

**Issue by Zialus** [caskroom/homebrew-cask#38856]
Am I missing something or shouldn't the various Opera browser formulas have auto_updates set to true?

[Opera](https://github.com/caskroom/homebrew-cask/blob/master/Casks/opera.rb)
[Opera Beta](https://github.com/caskroom/homebrew-versions/blob/master/Casks/opera-beta.rb)
[Opera Developer](https://github.com/caskroom/homebrew-versions/blob/master/Casks/opera-developer.rb)

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38859
https://github.com/caskroom/homebrew-versions/pull/4482
