### ISSUE TITLE
gtkwave cask checksum mismatch

### ISSUE THREAD

**Issue by akashlevy** [caskroom/homebrew-cask#38878]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

There is a gtkwave checksum mismatch because the gtkwave cask is out of date. I have created a pull request at: https://github.com/caskroom/homebrew-cask/pull/38876

Please approve this request to fix the issue.

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.sourceforge.net/gtkwave/gtkwave-3.3.84-osx-app/gtkwave.zip
Already downloaded: /Users/akashlevy/Library/Caches/Homebrew/Cask/gtkwave--3.3.84.zip
==> Downloaded to -> /Users/akashlevy/Library/Caches/Homebrew/Cask/gtkwave--3.3.84.zip
==> Verifying download
==> Determining which verifications to run for Cask gtkwave
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask gtkwave
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'gtkwave' does not match.

Expected: c503fb140f94a433dcfdc6417110890c77938b97f4d32cd4640155585d738b7c
Actual:   a553e6d463b466a00a63842bf4a06bf0c0546e73539f3c023c1f1961729cd7b3
File:     /Users/akashlevy/Library/Caches/Homebrew/Cask/gtkwave--3.3.84.zip

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:155:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:69:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:92:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.3
caskroom/homebrew-cask (git revision 85b57; last commit 2017-09-23)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 12.0MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3741 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/opt/bison/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Library/TeX/texbin:~/Library/Android/sdk/platform-tools:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by HsuanTingLu** [comment]
appcast version shows that the url is indeed outdated (3.3.86)
which is interesting because the link in appcast suggests that it is latest version is 3.3.86, 
although the link is somewhat weird

**Comment by karim-elngr** [comment]
⇒  brew cask install gtkwave
==> Satisfying dependencies
==> Downloading https://downloads.sourceforge.net/gtkwave/gtkwave-3.3.87-osx-app
######################################################################## 100.0%
==> Verifying checksum for Cask gtkwave
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'gtkwave' does not match.

Expected: e9e3cdfd06f76ed4de8b29d55a29f9b714a68a00501b13b4741078a506d1cc8a
Actual:   27d244dd428d38c3d8e5aa498f84745516238491367929e09624cc95a3ee9f1c
File:     /Users/karim/Library/Caches/Homebrew/Cask/gtkwave--3.3.87.zip

To retry an incomplete download, remove the file above.

**Comment by denniscote** [comment]
I have exactly the same error as Karim-elngr, even the same checksums. 

==> Satisfying dependencies
==> Downloading https://downloads.sourceforge.net/gtkwave/gtkwave-3.3.87-osx-app
######################################################################## 100.0%
==> Verifying checksum for Cask gtkwave
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'gtkwave' does not match.

Expected: e9e3cdfd06f76ed4de8b29d55a29f9b714a68a00501b13b4741078a506d1cc8a
Actual:   27d244dd428d38c3d8e5aa498f84745516238491367929e09624cc95a3ee9f1c
File:     /Users/dennis/Library/Caches/Homebrew/Cask/gtkwave--3.3.87.zip

To retry an incomplete download, remove the file above.


I also noticed that the current version of gtkwave on sourceforge 3.3.89 rather than the 3.3.87 home-brew is trying to download.
