### ISSUE TITLE
ClamXAV.app name case sensitivity

### ISSUE THREAD

**Issue by llange** [caskroom/homebrew-cask#38927]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

It seems that the name for the ClamXAV.app file is not correct in the cask.
In [the cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/clamxav.rb#L11) it is written as "ClamXav.app", while in the Zip it is "ClamXAV.app".

It may be not visible for normal filesystems, but mine is case-sensitive, thus this can be the reason I found this issue.

If I try to install this cask as-is, it fails with:
```
Error: It seems the App source '/usr/local/Caskroom/clamxav/2.15.2_3471/ClamXav.app' is not there.
```

Replacing with "ClamXAV.app" fixes the install problem.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38928
