### ISSUE TITLE
Cask request: Fork

### ISSUE THREAD

**Issue by oboupo** [caskroom/homebrew-cask#38967]
### Cask details

Name:
Fork - git client
Homepage:
https://git-fork.com
Download URL:
https://git-fork.com/update/files/Fork.dmg
Description: A fast and friendly git client for Mac. (Cool SourceTree alternative)

**Comment by commitay** [comment]
[`fork`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fork.rb)
