### ISSUE TITLE
Change source of tuntap (tuntaposx) to GitHub 

### ISSUE THREAD

**Issue by deg0nz** [caskroom/homebrew-cask#39051]
This is not really an issue with Cask itself.
I just want to suggest to change the data source of the cask "tuntap". Currently it uses sourceforge as source for the tar file that is downloaded.

Since sourceforge is experiencing connectivity issues these days, the cask was not available.
Also, GitHub seems to be a more reliable source for this in general. 

Moreover, the project actually is maintained here on GitHub, so new releases seem to be published here as well:
[https://github.com/saittam/tuntaposx](https://github.com/saittam/tuntaposx)

I'd like to make a pull request for that, If you guys are OK with that suggestion.

Greetings!

**Comment by commitay** [comment]
Sourceforge is working now.

We usually prefer to have a download URL match the homepage. Also I don't see anything on the homepage about a Github mirror. We would need for the new download to be confirmed as official by upstream.
