### ISSUE TITLE
Removal mosh 

### ISSUE THREAD

**Issue by daylightbrightledlight** [caskroom/homebrew-cask#39064]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Mosh cask is a duplicate of the `mobile-shell` Homebrew formula, which is proposed to be renamed to `mosh`. See https://github.com/Homebrew/homebrew-core/pull/18636

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39065
