### ISSUE TITLE
Cask request: Caprine 2.7

### ISSUE THREAD

**Issue by stpoa** [caskroom/homebrew-cask#39104]
### Cask details

Name: Caprine

Homepage: https://sindresorhus.com/caprine/

Download URL: https://github.com/sindresorhus/caprine/releases/tag/v2.7.0

2.6 is available, 2.7 isn't

**Comment by commitay** [comment]
![caprine](https://user-images.githubusercontent.com/26216252/31009047-7ea3c66c-a549-11e7-876f-26e38be8f4be.png)

**Comment by commitay** [comment]
> [Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```
```
cask-repair -v 2.7.0 caprine
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39105
