### ISSUE TITLE
Cask request: Adobe Illustrator 21 (CC 2017)

### ISSUE THREAD

**Issue by ambroisemaupate** [caskroom/homebrew-cask#39224]
### Cask details

Name: Adobe Illustrator 21 (CC 2017)

Homepage: http://www.adobe.com/products/illustrator.html

Download URL: https://download-esd.adobeoobe.com/AdobeProducts/eca60e6c-1f05-41de-bf6b-aeef2bc46205/ILST/21.0.0/osx10-64/AdobeIllustrator21_HD.dmg (direct link seems possible without spoofing cookies or user-agent).

Description: Could you update current existing cask which is capped to version 19 (cc 2015). At first sight, I thought link domain name was not official, but after doing a `whois adobeoobe.com` it seems that it’s the official download link.

Thanks team!

**Comment by commitay** [comment]
How did you get the URL?

**Comment by adidalal** [comment]
@commitay All Adobe CC apps have direct download links at https://helpx.adobe.com/creative-cloud/kb/creative-cloud-apps-download.html.

Unfortunately the installs ask for a serial/Adobe ID sign-in, not sure that can be easily scripted away. You need to use Creative Cloud Packager and host the files somewhere (licensing issues).

It's fine to update with an `installer :manual` if wanted, though.

**Comment by commitay** [comment]
Thanks @adidalal! I'll take a look at this Cask and the other Adobe CC Casks, I think they are all have outdated versions.

**Comment by commitay** [comment]
> Unfortunately the installs ask for a serial/Adobe ID sign-in, so the deployment xml steps would need to be reviewed.

@adidalal Just to check, do you mean that it is possible to install without a login?

**Comment by adidalal** [comment]
It's my understanding that CC apps need to be packaged using "Creative Cloud Packager", which is outside the scope of HBC. ie. https://helpx.adobe.com/enterprise/package/user-guide.html

**Comment by vitorgalvao** [comment]
I wouldn’t bat an eye if the Adobe casks were removed from the main repos. Adobe is incredibly user-hostile and their apps are a pain to keep and maintain. They’re so many and so difficult to support, I’d welcome a user maintaining them in their own tap.

**Comment by commitay** [comment]
These CC Casks are all outdated.

- `adobe-after-effects-cc`
- `adobe-animate-cc`
- `adobe-bridge-cc`
- `adobe-illustrator-cc`
- `adobe-indesign-cc`
- `adobe-media-encoder-cc`
- `adobe-photoshop-cc`
- `adobe-premiere-pro-cc`
___

Users can use `adobe-creative-cloud` and `adobe-creative-cloud-cleaner-tool`  to install and uninstall CC `apps`.

**Comment by EnricoMonese** [comment]
@commitay You just need to disable internet before opening the installer and it won't ask for login

**Comment by commitay** [comment]
> You just need to disable internet before opening the installer and it won't ask for login

This won't work with Cask.

**Comment by vitorgalvao** [comment]
> You just need to disable internet before opening the installer and it won't ask for login

That’s hardly a “just”. Are you suggesting we cutoff a user’s internet access to perform an install, with no regard for what they might be doing?

There’s always *something* with Adobe. We’re not going to keep bending over backwards.

**Comment by danielbayley** [comment]
> There’s always something with Adobe.

This. 😞 

> I’d welcome a user maintaining them in their own tap.

> We’re not going to keep bending over backwards.

I will attempt to maintain these in my tap, but if it ends up being even more hassle than last time I will probably arrive at the same conclusion.

**Comment by EnricoMonese** [comment]
@vitorgalvao Of course not. I didn't intend this to be a solution for cask. Was merely pointing out that the login ins't unskippable. I agree with you, it's my bad, I wasn't really clear.
