### ISSUE TITLE
Cask request: Mailspring

### ISSUE THREAD

**Issue by zachmccormick** [caskroom/homebrew-cask#39281]
### Cask details

Name: Mailspring

Homepage: https://getmailspring.com

Download URL: https://mailspring-builds.s3.amazonaws.com/client/20839f9b/osx/Mailspring.zip

Description: A fast and maintained fork of Nylas Mail - the best free email app for Mac, Linux, and Windows.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39285
