### ISSUE TITLE
Cask request: Lando

### ISSUE THREAD

**Issue by jordan8037310** [caskroom/homebrew-cask#39296]
### Cask details

Lando is a free, open source and cross-platform local development environment and DevOps tool built on Docker container technology and developed by Tandem. It is designed to work with most major languages, frameworks and services and to provide an easy way for users to specify simple or complex development requirements for their projects.

Name: Lando

Homepage: https://docs.devwithlando.io/

Download URL: Most recent release DMG: https://github.com/lando/lando/releases/download/v3.0.0-beta.19/lando-v3.0.0-beta.19.dmg

Description: Lando is a free, open source and cross-platform local development environment and DevOps tool built on Docker container technology.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39301
