### ISSUE TITLE
can't reset Homebrew Bottles

### ISSUE THREAD

**Issue by junhunt** [caskroom/homebrew-cask#39298]
i change homebrew bottles with:
`export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles`
but it can't download any package(brew install without cask is ok, like brew install tree).

error shows:

> curl: (7) Failed to connect to mirrors.tuna.tsinghua.edu.cn port 443: Operation timed out
Error: Download failed on Cask 'iina' with message: Download failed: https://dl-portal.iina.io/IINA.v0.0.12-build37.dmg
<img width="848" alt="2017-10-05 5 37 12" src="https://user-images.githubusercontent.com/5952856/31200978-97b8a05a-a922-11e7-944f-e1629fc94b4f.png">

then i try to modify, reset or delete mirror in **.bash_profile**, but still the same issue. 

 by the way, my .bash_profile's content now is:
`export HOMEBREW_BOTTLE_DOMAIN=http://7xkcej.dl1.z0.glb.clouddn.com
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles`

restart Terminal or Mac no work. uninstall & install Homebrew no work.

how can i delete **mirrors.tuna.tsinghua.edu.cn** ?

please help!

**Comment by commitay** [comment]
`HOMEBREW_BOTTLE_DOMAIN` is for Formulas, it has nothing to do with Cask.

**Comment by junhunt** [comment]
It's success install after I'm wake up. But I still confusing. @commitay thanks for you answer.
