### ISSUE TITLE
Cask request: pgadmin4

### ISSUE THREAD

**Issue by jneuendorf** [caskroom/homebrew-cask#39378]
### Cask details

There is a new version of pgadmin4:
`2.0` is available but https://github.com/caskroom/homebrew-cask/blob/master/Casks/pgadmin4.rb still uses `1.6`.

Name:
pgadmin4

Homepage:
https://www.pgadmin.org/

Download URL:
https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v2.0/macos/pgadmin4-2.0.dmg

Description:
pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world.

**Comment by vitorgalvao** [comment]
Thank you for the report. For future reference, [updating casks is really easy](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

I only did `cask-repair -v 2.0 pgadmin4` and https://github.com/caskroom/homebrew-cask/pull/39379 was created.

**Comment by jneuendorf** [comment]
Wow, didn't know it could be that simple. Thanks! :)
