### ISSUE TITLE
Cask request: Station

### ISSUE THREAD

**Issue by izazueta** [caskroom/homebrew-cask#39380]
### Cask details

Name: Station

Homepage: https://getstation.com

Download URL: http://dl.getstation.com

Description: One app to rule them all, Station unifies all your web apps in one neat & productive interface.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/98ec959621bfca7af6ff3d53c5ff2af6e0bfcbbd/Casks/station.rb
