### ISSUE TITLE
Update to JDK 1.9,181 / JDK 9,181 breaks the kafka and cassandra formulas

### ISSUE THREAD

**Issue by marcusportmann** [caskroom/homebrew-cask#39407]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The update to JDK 1.9,181 / JDK 9,181 breaks the kafka and cassandra formulas, which are dependent on JDK 1.8.

When installing the kafka or cassandra formulas the recommendation is to install the JDK with the Homebrew-Cask:

brew cask install java

This installs JDK 9,181 which is not compatible with Apache Kafka or Apache Cassandra.

#### Output of your command with `--verbose --debug`

```
When installing Apache Kafka:

brew install kafka
kafka: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!

You can install with Homebrew-Cask:
  brew cask install java

You can download from:
  https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.

brew cask install java
Warning: Cask 'java' is already installed.

To re-install java, run:
  brew cask reinstall java

When starting Apache Cassandra:

[0.001s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/usr/local/Cellar/cassandra/3.11.0/libexec/logs/gc.log instead.
intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
Improperly specified VM option 'ThreadPriorityPolicy=42'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.4-100-g5cbf8bd
caskroom/homebrew-cask (git revision a97b5; last commit 2017-10-07)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 371.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3762 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by marcusportmann** [comment]
I managed to fix the dependencies by installing the java8 cask using:

**Comment by vitorgalvao** [comment]
Te recommendation came from Homebrew, not Homebrew-Cask (notice how your command did not start with `brew cask`).

You want https://github.com/Homebrew/brew/.

**Comment by marcusportmann** [comment]
Apologies for the confusion and for logging this against the incorrect project.

For those who might find this in future, I managed to fix this problem by uninstalling the java cask and instead installing the java8 cask using:  

brew tap caskroom/versions 

brew cask install java8
