### ISSUE TITLE
Outdated cask: wabbitemu

### ISSUE THREAD

**Issue by TGNYC** [caskroom/homebrew-cask#39426]
[wabbitemu](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wabbitemu.rb) 

Cask is outdated, but I can't figure out the new checksum and version number.

**Comment by TGNYC** [comment]
https://wabbit.codeplex.com/releases/view/44625 is the download link

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/39428

The URL was updated, yes, but the file is the same.
