### ISSUE TITLE
Checksum fails for MAMP 4.2.1

### ISSUE THREAD

**Issue by daften** [caskroom/homebrew-cask#39484]
#### General troubleshooting steps

- [ X] I have retried my command with `--force` and the issue is still present.
- [ X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ X] None of the templates was appropriate for my issue, or I’m not sure.
- [ X] I ran `brew update-reset && brew update` and retried my command.
- [ X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

```
Error: Checksum for Cask 'mamp' does not match.\n\nExpected: 808e9685153c12a50d582e5eb27badbbc0cdc0df3fd3e0bf4bcaa74c4dc6a058\nActual:   9428a3cf494d02d94ecaec302042822f54273ba9d412ecde25d1155ab07db56e
```

Verified and is correct

#### Output of your command with `--verbose --debug`

Irrelevant

#### Output of `brew cask doctor`

Irrelevant

PR incoming

**Comment by commitay** [comment]
Please don't open issues if you are going to submit a PR.
