### ISSUE TITLE
Cask request: utorrent

### ISSUE THREAD

**Issue by cassvail** [caskroom/homebrew-cask#39500]
### Cask details

uTorrent for MacOS

Name: uTorrent

Homepage: http://www.utorrent.com/

Download URL: http://download-hr.utorrent.com/track/stable/endpoint/utmac/os/osx

Description: Torrent download manager

**Comment by reitermarkus** [comment]
µTorrent was removed for a reason, see https://github.com/caskroom/homebrew-cask/pull/29748.
