### ISSUE TITLE
Cask request: Drive File Stream

### ISSUE THREAD

**Issue by jordigg** [caskroom/homebrew-cask#39538]
### Cask details

Name: Drive File Stream

Homepage: https://support.google.com/drive/answer/7329379

Download URL: https://dl.google.com/drive-file-stream/googledrivefilestream.dmg

Description: Request for a new cask for Drive File Stream is the enterprise version of Google Drive. It streams Drive files directly from the cloud to the Mac or PC, freeing up disk space and network bandwidth.

**Comment by commitay** [comment]
[google-drive-file-stream](https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-drive-file-stream.rb)
