### ISSUE TITLE
Need help with BOINC installation script

### ISSUE THREAD

**Issue by hanxue** [caskroom/homebrew-cask#3958]
Hello,

I am trying to create a cask for BOINC which consists of a custom `BOINC Installer` executable and multiple `.pkg` and `.mpkg` file. Is there a way to get Homebrew Cask to manually run the installation executable that invokes the .pkg?

This is the Cask formula that I have, and it does not work

```ruby
class Boinc < Cask
  url 'http://boinc.berkeley.edu/dl/boinc_7.2.42_macOSX_i686.zip'
  homepage 'http://boinc.berkeley.edu/'
  version '7.2.42'
  sha256 '053059703f70f64a789aa203865aba5bf87d2224a711edfd38ee47f729de104c'
  install 'BOINC Installer'
  uninstall :script => { :executable => 'Uninstall BOINC.app', :input => %w[Yes] }
end
```

Thank you in advance.

**Comment by vitorgalvao** [comment]
This cask likely changed a lot in the meantime, so please resubmit your progress in a new issue if you still wish to pursue this, and we can take it from there.
