### ISSUE TITLE
Whatsapp wrong hash

### ISSUE THREAD

**Issue by cebor** [caskroom/homebrew-cask#39612]
Getting following error when trying to install whatsapp: 

```
==> Verifying checksum for Cask whatsapp
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'whatsapp' does not match.

Expected: ab2df2067986409901cdaa8dbe59b003fcf623a18c9423e7ccdb15876c85863e
Actual:   b627184f20a8753ae7e27a6f28c9434ade1e494fe42a11e6d268d3138d3fc8c2
File:     /Users/felix/Library/Caches/Homebrew/Cask/whatsapp--0.2.6424.dmg
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/39613

**Comment by kassio** [comment]
This is happening again:
```
$ brew cask install --force whatsapp
==> Satisfying dependencies
==> Downloading https://web.whatsapp.com/desktop/mac/files/WhatsApp.dmg
Already downloaded: /Users/kborges/Library/Caches/Homebrew/Cask/whatsapp--0.2.6426.dmg
==> Verifying checksum for Cask whatsapp
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'whatsapp' does not match.

Expected: b627184f20a8753ae7e27a6f28c9434ade1e494fe42a11e6d268d3138d3fc8c2
Actual:   e9cf90d3c80dbb9787a733f6ea7d50cb9021613ca64517120e0f8d9abbfd80ef
File:     /Users/kborges/Library/Caches/Homebrew/Cask/whatsapp--0.2.6426.dmg

To retry an incomplete download, remove the file above.
```

**Comment by c-okelly** [comment]
I download the dmg directly from the whatsapp website and ran shasum -a 256 with it. It appears the checksum has changed to the actual result in the error. 
=> e9cf90d3c80dbb9787a733f6ea7d50cb9021613ca64517120e0f8d9abbfd80ef  WhatsApp.dmg
Version has been update to 0.2.6967 according to the app

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/40440
