### ISSUE TITLE
A bit more documentation, please!

### ISSUE THREAD

**Issue by gjtorikian** [caskroom/homebrew-cask#39617]
1. How can I calculate the sha256 of a file on macOS?
2. Where does the `appcast: checkpoint` value come from?

Additions for these to the README would be much appreciated!

**Comment by reitermarkus** [comment]
Did you actually search for this in the docs? We cannot put everything in the ReadMe.

- [`sha256`](https://github.com/caskroom/homebrew-cask/blob/077309dd91b7a8aaeab8661572429b42cef774da/doc/cask_language_reference/stanzas/sha256.md#calculating-the-sha256
)

- [`appcast`](https://github.com/caskroom/homebrew-cask/blob/077309dd91b7a8aaeab8661572429b42cef774da/doc/cask_language_reference/stanzas/appcast.md)

**Comment by gjtorikian** [comment]
I did; here's what [a search brings up for `appcast`](https://github.com/caskroom/homebrew-cask/search?q=appcast&type=Commits&utf8=%E2%9C%93) for example.

As someone unfamiliar with the cutesy naming conventions, even https://github.com/caskroom/homebrew-cask/tree/077309dd91b7a8aaeab8661572429b42cef774da/doc doesn't help. What's a stanza? I have to dig down four directories deep to actually get the info I need.

**Comment by commitay** [comment]
> https://github.com/caskroom/homebrew-cask/search?l=Markdown&q=appcast&type=Code&utf8=%E2%9C%93
