### ISSUE TITLE
qldds: expired certification

### ISSUE THREAD

**Issue by Yakuky** [caskroom/homebrew-cask#39727]
[qldds](https://github.com/caskroom/homebrew-cask/blob/60531a2812005dd5f17dc92f3ce7419af3c5d019/Casks/qldds.rb)

The certification has expired. I guess allow_untrusted need to be set to true?

**Comment by commitay** [comment]
@Yakuky Please report this to https://github.com/Marginal/QLdds/issues

**Comment by commitay** [comment]
https://github.com/Marginal/QLdds/issues/2

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39826
