### ISSUE TITLE
Rename casks with `Desktop` in name

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#39741]
Refs https://github.com/caskroom/homebrew-cask/pull/39708.

**Comment by commitay** [comment]
List of `*desktop*` Casks, not sure if all of them need to be renamed.

`caskroom`
- [ ] [acquia-dev-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/acquia-dev-desktop.rb)
- [ ] [authy-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/authy-desktop.rb)
- [ ] [bimedesktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/bimedesktop.rb)
- [ ] [chrome-remote-desktop-host](https://github.com/caskroom/homebrew-cask/blob/master/Casks/chrome-remote-desktop-host.rb)
- [ ] [colwiz-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/colwiz-desktop.rb)
- [ ] [desktop-log](https://github.com/caskroom/homebrew-cask/blob/master/Casks/desktop-log.rb)
- [ ] [desktoputility](https://github.com/caskroom/homebrew-cask/blob/master/Casks/desktoputility.rb)
- [ ] [freeswitch-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/freeswitch-desktop.rb)
- [ ] [github-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/github-desktop.rb)
- [ ] [google-play-music-desktop-player](https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-play-music-desktop-player.rb)
- [ ] [isyncr-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/isyncr-desktop.rb)
- [ ] [jump-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jump-desktop.rb)
- [ ] [lytro-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/lytro-desktop.rb)
- [ ] [macupdate-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/macupdate-desktop.rb)
- [ ] [mediafire-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mediafire-desktop.rb)
- [ ] [mendeley-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mendeley-desktop.rb)
- [ ] [messenger-for-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/messenger-for-desktop.rb)
- [ ] [myphonedesktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/myphonedesktop.rb)
- [ ] [parallels-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/parallels-desktop.rb)
- [ ] [pb-for-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pb-for-desktop.rb)
- [ ] [polycom-realpresence-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/polycom-realpresence-desktop.rb)
- [ ] [printer-pro-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/printer-pro-desktop.rb)
- [ ] [qdesktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qdesktop.rb)
- [ ] [qobuz-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qobuz-desktop.rb)
- [ ] [quickbooks-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/quickbooks-desktop.rb)
- [ ] [readytalk-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/readytalk-desktop.rb)
- [ ] [remote-desktop-manager](https://github.com/caskroom/homebrew-cask/blob/master/Casks/remote-desktop-manager.rb)
- [ ] [sejda-pdf-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sejda-pdf-desktop.rb)
- [ ] [slingplayer-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/slingplayer-desktop.rb)
- [ ] [telegram-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/telegram-desktop.rb)
- [ ] [toggldesktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/toggldesktop.rb)
- [ ] [transporter-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/transporter-desktop.rb)
- [ ] [veertu-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/veertu-desktop.rb)
- [ ] [vorlon-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vorlon-desktop.rb)
- [ ] [whatsdesktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/whatsdesktop.rb)

`drivers`
- [ ] [shearwater-desktop](https://github.com/caskroom/homebrew-drivers/blob/master/Casks/shearwater-desktop.rb)

`versions`
- [ ] [github-desktop-beta](https://github.com/caskroom/homebrew-versions/blob/master/Casks/github-desktop-beta.rb)
- [ ] [microsoft-remote-desktop-beta](https://github.com/caskroom/homebrew-versions/blob/master/Casks/microsoft-remote-desktop-beta.rb)
- [ ] [parallels-desktop11](https://github.com/caskroom/homebrew-versions/blob/master/Casks/parallels-desktop11.rb)
- [ ] [parallels-desktop12](https://github.com/caskroom/homebrew-versions/blob/master/Casks/parallels-desktop12.rb)
- [ ] [quickbooks-desktop2014](https://github.com/caskroom/homebrew-versions/blob/master/Casks/quickbooks-desktop2014.rb)
- [ ] [quickbooks-desktop2015](https://github.com/caskroom/homebrew-versions/blob/master/Casks/quickbooks-desktop2015.rb)
- [ ] [telegram-desktop-dev](https://github.com/caskroom/homebrew-versions/blob/master/Casks/telegram-desktop-dev.rb)
- [ ] [toggldesktop-beta](https://github.com/caskroom/homebrew-versions/blob/master/Casks/toggldesktop-beta.rb)
- [ ] [toggldesktop-dev](https://github.com/caskroom/homebrew-versions/blob/master/Casks/toggldesktop-dev.rb)

**Comment by adidalal** [comment]
Checked off Casks which shouldn't be renamed (ie. `desktop` is an integral part of the name).

**Comment by miccal** [comment]
Also checked off the `github-desktop` Casks.

**Comment by commitay** [comment]
> Remove from the end: strings such as “Desktop”, “for Desktop”.

**Comment by vitorgalvao** [comment]
Made changes to the checked casks. As a general rules, anything that *ends* in `desktop` should get changes, while everything else is to be left alone.

**Comment by tjrana** [comment]
I don't think that removing the `desktop` part at the ends of some of the casks is a good idea.

For example, `github-desktop` refers to the software, while the name `github` should refer to the service itself.

I can understand casks such as `quickbooks-desktop` renamed to `quickbooks`, as screenshots of the software show "QuickBooks" on the menu bar as the bundle display name.

@vitorgalvao What do you think? Is this a good idea?

**Comment by vitorgalvao** [comment]
> For example, `github-desktop` refers to the software, while the name `github` should refer to the service itself.

I don’t imagine anyone confused, thinking they’re going to install Github from HBC. We install apps, and that’s it. It follows that `github` is the Github app.

> HBC only works in macOS, **every app is “Desktop”**.

**Comment by commitay** [comment]
@vitorgalvao Everything on the list has a pending PR except for these 3:

- [google-play-music-desktop-player](https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-play-music-desktop-player.rb) - Not sure about removing `-desktop-`
- [qdesktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qdesktop.rb) - `q` or `qvacua-q` By the same developer: [qmind](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qmind.rb)
- [readytalk-desktop](https://github.com/caskroom/homebrew-cask/blob/master/Casks/readytalk-desktop.rb) - [`readytalk`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/readytalk.rb) conflict (launcher rule)

**Comment by vitorgalvao** [comment]
@commitay https://github.com/caskroom/homebrew-cask/pull/39923. The others may be left as are.

**Comment by RotsiserMho** [comment]
Why was `github-desktop` renamed? That's the literal name of the app. Don't bike shed things that shouldn't be; this change cost me 10 minutes trying to figure out what went wrong since apparently Github is unaware of this change; their documentation specifically says to run `brew cask install github-desktop` (https://github.com/desktop/desktop/blob/master/README.md).

**Comment by commitay** [comment]
https://github.com/desktop/desktop/pull/3139

**Comment by vitorgalvao** [comment]
> Don't bike shed things that shouldn't be

The builders are the ones that define what’s a bike shed, not random users that don’t contribute. Alas, that’s always where the entitled comments come from. I *know* before clicking the username what the contributions graph will look like.

Do you not like free things, or something? It’s not like you have to use the software. It’s unfortunate something took you ten minutes to solve, but that’s no reason to vent your frustration on us. You lost all sympathy when you did.

Every time you make an entitled comment, open source maintainers burn out a bit more. You’re part of the reason so many of us do.

**Comment by vitorgalvao** [comment]
Closing, as everything already has PRs.
