### ISSUE TITLE
Outdated cask but cannot find link: java

### ISSUE THREAD

**Issue by samnunnally** [caskroom/homebrew-cask#39761]
java
https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb

Looks like latest link is:
http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_osx-x64_bin.dmg

instead of 
http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_osx-x64_bin.dmg

$ brew cask install java
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Satisfying dependencies
==> Downloading http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_osx-x64_bin.dmg
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_osx-x64_bin.dmg

**Comment by vitorgalvao** [comment]
Thank you for following the guides. There’s already a PR to address this: https://github.com/caskroom/homebrew-cask/pull/39751.
