### ISSUE TITLE
java 9  did not work

### ISSUE THREAD

**Issue by hrstoyanov** [caskroom/homebrew-cask#39763]
brew cask reinstall java
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Satisfying dependencies
==> Downloading http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_osx-x64_bin.dmg
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_osx-x64_bin.dmg

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39751

**Comment by hrstoyanov** [comment]
... So, what should i do to get Java 9 NOW? #39751 was committed 5 hours ago ...

**Comment by hrstoyanov** [comment]
oh .. so the patch is  not merged ?
