### ISSUE TITLE
Cask request: Cardhop

### ISSUE THREAD

**Issue by elbracht** [caskroom/homebrew-cask#39787]
### Cask details

Name: Cardhop

Homepage: https://flexibits.com/cardhop

Download URL: https://flexibits.com/cardhop/download

Description: Cardhop lets you search, add, edit, and interact with your contacts in a fun and interactive way. Just type what you want and Cardhop will figure it out!

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39789
