### ISSUE TITLE
Fail to install eclipse oxygen 1a ?

### ISSUE THREAD

**Issue by hrstoyanov** [caskroom/homebrew-cask#39794]
➜  github brew cask install eclipse-jee

==> Caveats
eclipse-jee requires Java. You can install the latest version with

  brew cask install java

==> Satisfying dependencies
==> Downloading https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/1a/eclipse-jee-oxygen-1a-macosx-cocoa-x86_64.dmg&r=1
######################################################################## 100.0%
==> Verifying checksum for Cask eclipse-jee
==> Installing Cask eclipse-jee
==> Moving App 'Eclipse.app' to '/Applications/Eclipse JEE.app'.
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames ("Eclipse.app") /Applications/Eclipse JEE.app

==> Standard Output of failed command:

==> Standard Error of failed command:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by commitay** [comment]
From the issue template:

> - [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

**Comment by hrstoyanov** [comment]
Thanks awesome support!
