### ISSUE TITLE
Cask request: omdbtool

### ISSUE THREAD

**Issue by kenorb** [caskroom/homebrew-cask#39810]
## Cask details

Name: imdb-cli (`omdbtool`)

Homepage: https://github.com/bgr/imdb-cli

Download URL: https://github.com/bgr/imdb-cli

Description: Command line tool for retrieving IMDb movie information

**Comment by commitay** [comment]
> [Rejected Casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md#rejected-casks)
> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).
