### ISSUE TITLE
Cask request: BleachBit

### ISSUE THREAD

**Issue by malhobayyeb** [caskroom/homebrew-cask#39849]
### Cask details

Name:
BleachBit

Homepage:
https://www.bleachbit.org/

Download URL:
https://www.bleachbit.org/download/mac

Description:
deletes junk files to recover disk space and maintain privacy

**Comment by vraravam** [comment]
@malhobayyeb - i'll take a stab at this

**Comment by arcticbarra** [comment]
Working on it!

**Comment by commitay** [comment]
This requires building from source, we can't add it to Cask.
