### ISSUE TITLE
Vagrant does not support Virtualbox 5.2+

### ISSUE THREAD

**Issue by swmichaels** [caskroom/homebrew-cask#39858]
Hi all, looks like this PR https://github.com/caskroom/homebrew-cask/pull/39790 breaks compatibility with the latest version of Vagrant.

https://www.vagrantup.com/docs/virtualbox/

> The VirtualBox provider is compatible with VirtualBox versions 4.0.x, 4.1.x, 4.2.x, 4.3.x, 5.0.x, and 5.1.x.

Repro steps:

```
brew cask install vagrant
brew cask install virtualbox
vagrant up --provider=virtualbox
```

Note the compatibility error message. Reinstalling the last 5.1.x available fixes the issue.

```
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/e8816187ae43f52b598f15f45b3453e22727ac99/Casks/virtualbox.rb
```

**Comment by commitay** [comment]
I'll leave this open for now so we don't get duplicate reports.

A new version of `vagrant` with support for `virtualbox` `5.2.0+` should be released next week.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/40295
