### ISSUE TITLE
Rename cask `gpgtools` to `gpg-suite`

### ISSUE THREAD

**Issue by tjrana** [caskroom/homebrew-cask#39862]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I propose that the cask [`gpgtools`](https://github.com/caskroom/homebrew-cask/blob/75f9a63ef035314e47d1d5986365b6470a3dea7d/Casks/gpgtools.rb) be renamed to `gpg-suite`, with `gpgtools` as an alias. I would also like to make a similar request for [`gpgtools-beta`](https://github.com/caskroom/homebrew-versions/blob/d36d1a00a1bc6a8214ad3cbdb8eb9783a5b7e07c/Casks/gpgtools-beta.rb) and [`gpgtools-nightly`](https://github.com/caskroom/homebrew-versions/blob/d36d1a00a1bc6a8214ad3cbdb8eb9783a5b7e07c/Casks/gpgtools-nightly.rb).

"GPGTools" seems to refer to the organization, while "GPG Suite" refers to the [software bundle](https://gpgtools.org/#gpgsuite). Also see [release notes](https://gpgtools.org/releases/gpgsuite/2017.1/release-notes.html).

Website: https://gpgtools.org/#gpgsuite

GPG Suite includes:
- GPGMail
- GPG Keychain
- GPG Services
- MacGPG
- GPG Suite Preferences (formerly GPGPreferences) System Preferences pane
- Libmacgpg framework.

References to name change:

- Commit https://github.com/GPGTools/GPGTools_Installer/commit/7a5db70a885cda14a06e958520a054cd7f62cd84
- Commit https://github.com/GPGTools/GPGPreferences/commit/0b899b7ed2b45257547d122ff6ae214470efb344
- Commit message https://github.com/GPGTools/GPGPreferences/commit/7004e82fc30262a0155c2a69abb4e3d6896cbf33

**Comment by vitorgalvao** [comment]
> with `gpgtools` as an alias.

We don’t support aliases.

But I’m fine with renaming to `gpg-suite`.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39865

https://github.com/caskroom/homebrew-versions/pull/4627

**Comment by davea** [comment]
Just to note that this caused issues for me:

```
$ brew cask outdated
Error: Cask 'gpgtools' is unavailable: No Cask with this name exists.
$ brew cask list
Error: Cask 'gpgtools' is unavailable: No Cask with this name exists.
```

The output of `brew bundle dump` was also missing all casks as a side-effect.

I worked around this with `mv /usr/local/Caskroom/gpgtools /usr/local/Caskroom/gpg-suite`, which fixed the problem.

**Comment by joh-klein** [comment]
What is the update path then? Or: how do I get from cask "gpgtools" to "gpg-suite" without losing settings or keeping stale files?

**Comment by joh-klein** [comment]
What I did was renamed "/usr/local/Caskroom/gpgtools" to "/usr/local/Caskroom/gpg-suite" and then did `brew cask reinstall gpg-suite`. That seemed to have worked. Would there have been a better way?
