### ISSUE TITLE
caskroom/drivers: prefix all Casks with vendor name.

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#39867]
As we seem to be discussing naming rules I thought I'd mention another one I've been considering.

Currently most (I haven't actually counted them) Casks in `drivers` are prefixed with the vendor name, I think we should apply the vendor prefix to all Casks in `drivers`.

This would (hopefully) improve searchability and reduce duplicate submissions.

**Comment by vitorgalvao** [comment]
No objections.

I still thing the old `tags` stanza we had  is a bad idea, but the more casks we get, the more I see prepending the vendor by default as a good idea. This is also the domain of `name`, naturally, but for drivers the vendor should help tremendously.

**Comment by commitay** [comment]
Similar to https://github.com/caskroom/homebrew-cask/issues/39741, should we remove the `*driver` / `*-drivers` from Casks?

```
brotherprinterdrivers
caldigit-usb-c-dock-driver
canon-capt-printer-driver
canon-imagerunner-printer-driver-ufrii
canon-pixma-mg6200-printer-driver
canon-pixma-mx510-printer-driver
canon-pixma-mx510-scanner-driver
canon-pixma-scanner-driver-ica
dn-3023-driver
fender-amp-drivers
ftdi-vcp-driver
hewlettpackardprinterdrivers
konica-minolta-bizhub-c220-c280-c360-driver
konica-minolta-bizhub-c450-driver
nttcom-smart-card-reader-driver
nvidia-web-driver
oki-mc573series-driver
oki-postscript-drivers
ricoh-driver-aficio-sp-c240dn
samsungprinterdrivers
sbig-universal-driver
silicon-labs-vcp-driver
wch-ch34x-usb-serial-driver
xbox360-controller-driver
xerox-print-driver
```

**Comment by vitorgalvao** [comment]
I’m a bit more reluctant to remove `driver` since it might be a useful search term. Drivers have such ridiculous names that it may be a good wait the filter what you’re looking for from the cruft.

**Comment by commitay** [comment]
Casks have been renamed.

Started a PR to add `<vendor>-<token>` naming to `drivers` contributing. 

https://github.com/caskroom/homebrew-drivers/pull/216
