### ISSUE TITLE
find_sparkle_appcast

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#39866]
`find_sparkle_appcast` doesn't always find the `appcast`

Reported in https://github.com/caskroom/homebrew-cask/pull/39859

I noticed this occur with another Cask but I don't remember which one, I'll find out and update this post.

**Comment by vitorgalvao** [comment]
`find_sparkle_appcast` finds the `SUFeedURL` key in the `Info.plist` and uses that. I don’t know of a different way to get it.

The mentioned app does not have that key, nor do I see another URL on the `plist`.

**Comment by vitorgalvao** [comment]
Using `strings 'Rest Time.app/Contents/MacOS/Rest Time' | grep '.xml'` I can indeed find the `appcast` URL reported in the other issue, but looking around it there is no other useful information to say for sure that is an appcast (i.e. not scriptable).

**Comment by commitay** [comment]
I can't find anything in the sparkle docs about an alternative implementation method.

However it works, it probably not the "correct" way to use sparkle and I'd imagine it would vary between developers.

Closing.
