### ISSUE TITLE
Installation of private-internet-access cask

### ISSUE THREAD

**Issue by ondrejfuhrer** [caskroom/homebrew-cask#39878]
Hello guys, since v73 the installation through `brew cask` is not completely working for `private-internet-access`.

Here is the output:
```
==> Installing Cask private-internet-access
To complete the installation of Cask private-internet-access, you must also
run the installer at

  '/usr/local/Caskroom/private-internet-access/74/Private Internet Access Installer.app'
🍺  private-internet-access was successfully installed!
```

Is there any way how the installer can be automatically executed?

**Comment by miccal** [comment]
This Cask has an `installer manual:` stanza, so no there is no way the installer can be automatically executed.
