### ISSUE TITLE
Cask request: [BookMacster]

### ISSUE THREAD

**Issue by luisspuerto** [caskroom/homebrew-cask#39888]
### Cask details

Name: BookMacster

Homepage: http://www.sheepsystems.com/products/bookmacster.html

Download URL: http://sheepsystems.com/bookmacster/BookMacster.dmg

Description: It's a software to sync bookmarks across different browsers.

**Comment by gentlecat** [comment]
Added in #39913.

**Comment by luisspuerto** [comment]
Thanks!
