### ISSUE TITLE
'brew cask install gimp; gimp' does not launch gimp

### ISSUE THREAD

**Issue by dankegel** [caskroom/homebrew-cask#39925]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I expect installing gimp to let me run gimp via the commandline by typing gimp, but instead I have to to type open /Applicatons/GIMP.app, which is a lot more keystrokes.  It also took me 20 minutes to figure what wtf was wrong.

#### Output of your command with `--verbose --debug`

```
command not found
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-30-gce0e96c
caskroom/homebrew-cask (git revision 47d63; last commit 2017-10-22)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 55.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3764 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/oblong/g-speak3.28/bin:/opt/oblong/deps-64-11/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by vitorgalvao** [comment]
We don’t make any promises that you’ll be able to launch software by typing its name. *That is not one of our goals*.

Add this to your shell: `alias gimp='open /Applicatons/GIMP.app'` and you’re done.

**Comment by dankegel** [comment]
Hrm.   I thought brew was for commandline users coming from e.g. linux, and tried to make them feel at home.

Guess I was wrong.

**Comment by miccal** [comment]
@dankegel you are thinking of Homebrew; Homebrew Cask is for installing GUI applications.

**Comment by dankegel** [comment]
Why is there any difference?  I often run gui applications from the commandline, and so do many other linux users.

**Comment by miccal** [comment]
The difference is that Cask just installs Gimp from the `.dmg` file found on the official Gimp homepage, as if you had downloaded and installed it manually. The official `.dmg` does not include binaries by default for MacOS.

As @vitorgalvao has mentioned, you need to add an `alias` to launch the Gimp GUI from the command line.

**Comment by vitorgalvao** [comment]
@dankegel Don’t fixate on Linux. We’re not a package manager for Linux users that use macOS.

We’re a package manager for macOS users, and we act accordingly to macOS conventions and expectations. macOS’ *nix functionality isn’t tackeed on — it’s native. We don’t need to imitate Linux behaviour, we do what makes sense for macOS.

**Comment by dankegel** [comment]
This bit me again.  I already had gimp installed, but expected typing 'gimp' on the commandline to run gimp.

Would you accept a patch that made this work?

**Comment by dankegel** [comment]
And I just did it again; even after writing the above, I expected 'gimp foo.png' to open foo.png.

**Comment by vitorgalvao** [comment]
> Would you accept a patch that made this work?

No, and we’ve already explained why.

We’ve also explained [how to fix it in your install](https://github.com/caskroom/homebrew-cask/issues/39925#issuecomment-338486007). We’re not going to change our whole rules for a single user with a single use-case that can be fixed permanently with a small fix on their part.
