### ISSUE TITLE
Cask request: Gitx

### ISSUE THREAD

**Issue by MaerF0x0** [caskroom/homebrew-cask#39969]
### Cask details
The older gitx forks are out of date and unmaintained. Lets bring this forward! 
A quick look at the rowanj network lead me to this: https://github.com/gitx/gitx which has commits up to July 2017. 

Name:  gitx/gitx

Homepage: https://github.com/gitx/gitx

Download URL: https://github.com/gitx/gitx/wiki/Build-instructions

Description: gitx is a gui for git

**Comment by commitay** [comment]
@MaerF0x0 This fork doesn't have a binary distribution, we can't add it to Cask.

**Comment by MaerF0x0** [comment]
If I get them to add a binary distribution can we add it?

On Oct 23, 2017 3:28 PM, "commitay" <notifications@github.com> wrote:

@MaerF0x0 <https://github.com/maerf0x0> This fork doesn't have a binary
distribution, we can't add it to Cask.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/caskroom/homebrew-cask/issues/39969#issuecomment-338815325>,
or mute the thread

**Comment by commitay** [comment]
> If I get them to add a binary distribution can we add it?

Yes.

These are the open issues requesting pre-built binaries.

https://github.com/gitx/gitx/issues/38, https://github.com/gitx/gitx/issues/101
