### ISSUE TITLE
Update the-unarchiver Cask

### ISSUE THREAD

**Issue by ABruihler** [caskroom/homebrew-cask#39983]
The Cask for the-unarchiver needs to be updated.  The new version string which needs to be entered with cask-repair is `3.11.3,115:1507740941`.  Unfortunately, I cannot get cask-repair to create a pull request for this - although that is almost certainly because of me trying to use Github's email hiding feature and it not working properly (which I don't have enough time to troubleshoot now).  Anyone should be able to `brew cask install the-unarchiver` and then `cask-repair the-unarchiver` with the new version string `3.11.3,115:1507740941` in order to get it to work.

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/39984
