### ISSUE TITLE
Cask request: Muse

### ISSUE THREAD

**Issue by yuhr** [caskroom/homebrew-cask#39992]
### Cask details

Name: Muse

Homepage: https://github.com/xzzz9097/Muse

Download URL: https://github.com/xzzz9097/Muse/releases

Description: An open-source Spotify, iTunes and Vox controller with TouchBar support, system-wide TouchBar controls (à la iTunes) and Spotify account integration.

**Comment by pavel-sakun** [comment]
In progress.
