### ISSUE TITLE
Use versioned formulas Java@8 and Java@9

### ISSUE THREAD

**Issue by VonUniGE** [caskroom/homebrew-cask#40042]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The Java formula have been updated to Jdk9 which is fine, but the Jdk8 will is still used and will be used and updated for a few years more. Some Java framework such as the current Spring Boot (1.5.8) and other Java programs run only on Jdk8.

The solution would be to use [versioned formulas](https://docs.brew.sh/Versions.html) such as java@8 and java@9.

**Comment by commitay** [comment]
JDK8 is in `caskroom/versions`: [java8](https://github.com/caskroom/homebrew-versions/blob/master/Casks/java8.rb)
