### ISSUE TITLE
Feature request: `brew cask list/outdated` should distinguish moved and renamed casks

### ISSUE THREAD

**Issue by wickles** [caskroom/homebrew-cask#40049]
### Description of feature/enhancement

It would be great if there was some command that would alert the user of removed and moved/renamed casks. I imagine that this should be done in both `list` and `outdated` commands. I am not sure if `brew update` does this, and if it does I do not believe that is enough of a notice.

### Justification

I found recently that some of my casks were renamed, but I do not recall any notification of this in the `brew update` message, and couldn't find any `brew cask` commands that would systematically show me all moved/removed casks. I searched for documentation or issues on the subject and couldn't find anything, so I apologize if this already exists in code or discussion somewhere.

### Example use case

Currently `brew cask` commands might output something like so (asterisks denote moved or deleted casks, added for emphasis):
```
$ brew cask list
ffmpegx *
filebot
macupdate-desktop *
malwarebytes-anti-malware *
meld
mendeley-desktop *
skim
$ brew cask outdated
filebot (4.7.2, 4.7.5) != 4.7.9
```
The casks indicated actually don't have formulae anymore under those names, they were renamed or removed, but still exist in the Caskroom directory and still show the old metadata via `brew cask info`.

I would propose the following changes (or similar) to the output:
```
$ brew cask list
ffmpegx ✘
filebot
macupdate-desktop ♺
malwarebytes-anti-malware ♺
meld
mendeley-desktop ♺
skim
$ brew cask outdated
ffmpegx (x.y, x.z) -> REMOVED
filebot (4.7.2, 4.7.5) != 4.7.9
macupdate-desktop (a.b, a.c) -> macupdate
malwarebytes-anti-malware (d.e, d.f) -> malwarebytes
mendeley-desktop (g.h, g.i) -> mendeley
```
Proposed icons could be changed or have color as needed, of course. Output for `brew cask info` could also be adjusted if desired.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/29716
