### ISSUE TITLE
OpenZFS out-of-date

### ISSUE THREAD

**Issue by tomvanderlee** [caskroom/homebrew-cask#40064]
OpenZFS updated to 1.7.0.

Changelog:
-  ABD support (OpenZFS)
-  File pool import bug fix (Jorgen Lundman)
-  ABD move enhancement (Sean Doran)
-  7968 multi-threaded spa_sync (OpenZFS)
-  Native Encryption (Tom Caputi)
-  zpool scrub pause/resume (OpenZFS)
-  zfs recv of compressed streams fix (OpenZFS)
-  OS X High Sierra support (Jorgen Lundman)

See: https://openzfsonosx.org/wiki/Downloads#1.7.0

**Comment by commitay** [comment]
`1.7.0` is a separate download for High Sierra only, it doesn't package the uninstall scripts that we use to correctly uninstall this Cask.

I'd suggest installing manually for now until upstream does a full `1.7.0` release.

**Comment by OranguTech** [comment]
Is this still the case? 1.7.0 has been working fine for me,  https://openzfsonosx.org/wiki/Changelog#OpenZFS_on_OS_X_1.7.0 says it's includes HS support, don't see it as HS only.

**Comment by commitay** [comment]
https://openzfsonosx.org/forum/viewtopic.php?f=20&t=3082

![openzfs](https://user-images.githubusercontent.com/26216252/36280659-bd652cb4-12e6-11e8-8003-90fea353bcc6.png)

**Comment by commitay** [comment]
Cask has been updated to `1.7.1` 

https://github.com/caskroom/homebrew-cask/pull/44793
