### ISSUE TITLE
Dead link to the emby-server bottle

### ISSUE THREAD

**Issue by Shummy42** [caskroom/homebrew-cask#40085]
https://github.com/caskroom/homebrew-cask/blob/43c5e443d9cbb9bbcd9e6da8e80226da584ef6eb/Casks/emby-server.rb#L6

File was removed in commit: https://github.com/MediaBrowser/Emby.Releases/commit/3604f3368b3bc83e3b6eaa99538b4397ab03a363

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/40077
