### ISSUE TITLE
Cask request/update: Slack Beta Version 3.0.0

### ISSUE THREAD

**Issue by moritzsternemann** [caskroom/homebrew-cask#40177]
### Cask details

Looks like Slack changed the filename in the download url of their beta client to include some sort of hash.
I'd like to update the cask file, but I have no idea where to start. Could somebody point me in the right direction (perhaps a similar case).

Name: Slack Beta

Homepage: https://slack.com/beta/osx

Download URL: https://github.com/caskroom/homebrew-cask#reporting-bugs

Description: Beta Version of the Slack client

Current cask file: https://github.com/caskroom/homebrew-versions/blob/master/Casks/slack-beta.rb

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-versions/pull/4683

___
> [Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```
```
cask-repair -v 3.0.0-beta2638bae9 slack-beta
```
