### ISSUE TITLE
Cask 'adobe-photoshop-cc' definition is invalid: No default language specified.

### ISSUE THREAD

**Issue by mengxiangkun** [caskroom/homebrew-cask#40247]
#### General troubleshooting steps
 $ brew cask list
Error: Cask 'adobe-photoshop-cc' definition is invalid: No default language specified.

**Comment by singuerinc** [comment]
I have the same problem, how did you resolve it?

**Comment by mengxiangkun** [comment]
@singuerinc delete adobe-photoshop-cc app in brewHome lib by manual operation to prevent brew command checkout it

**Comment by rinopo** [comment]
cf. https://github.com/caskroom/homebrew-cask/pull/39153
