### ISSUE TITLE
Cask request: sciencefair

### ISSUE THREAD

**Issue by fullpipe** [caskroom/homebrew-cask#40281]
### Cask details

Name: Sciencefair

Homepage: http://sciencefair-app.com/

Download URL: https://github.com/codeforscience/sciencefair/releases/download//v1.0.6/scienceFair-1.0.6.dmg

Description: The open source p2p desktop science library that puts users in control.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/40282
