### ISSUE TITLE
Calling `brew cask` with the `--caskroom` flag is disabled!

### ISSUE THREAD

**Issue by wdongxv** [caskroom/homebrew-cask#40291]
when run `brew cask` display this message. 
```
Error: Calling `brew cask` with the `--caskroom` flag is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
Look into your shell’s startup files. You likely have `HOMEBREW_CASK_OPTS` set somewhere.

**Comment by wdongxv** [comment]
Thank you @vitorgalvao  ！
delete ‘HOMEBREW_CASK_OPTS’ in ‘~/.bash_profile’ is ok!

**Comment by ryanrishi** [comment]
Thanks, this helped me too!

**Comment by mbbroberg** [comment]
Ty as well @vitorgalvao 😅. Didn't realize I had that in my profile files until I `grep -r "HOMEBREW_CASK_OPTS" ~`.
