### ISSUE TITLE
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'

### ISSUE THREAD

**Issue by DevByStarlight** [caskroom/homebrew-cask#40299]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
Brew cask fails in `process_arguments`
All `brew cask` commands fail

- Relatively fresh install of homebrew (acquired new machine about a month ago)
- brew update is called at least weekly (I disabled automated update per command using environment HOMEBREW_NO_AUTO_UPDATE variable)
- Ran `brew update-reset && brew update` without yielding a fix

Other reported issues with somewhat similar errors:
- #38901 [-](https://github.com/caskroom/homebrew-cask/issues/37267) can't brew cask
- #37267 [-](https://github.com/caskroom/homebrew-cask/issues/37267) "block on load"

In case this is helpful (was requested info in one of the above reported issues
```
# grep -ilr --include \*.rb license $(brew --prefix)/Caskroom
/usr/local/Caskroom/java/.metadata/9,181/20171017011853.279/Casks/java.rb
```
I have not attempted uninstall/reinstall of homebrew yet. However, that is on my "will try soon" list.

#### Output of your command with `--verbose --debug`

```
# brew cask --verbose --debug list  
Error: Calling `brew cask` with the `--caskroom` flag is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
```

#### Output of `brew cask doctor`

```
# brew cask doctor
Error: Calling `brew cask` with the `--caskroom` flag is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
```

**Comment by commitay** [comment]
> Calling `brew cask` with the `--caskroom` flag is disabled

> https://github.com/caskroom/homebrew-cask/issues/40291#issuecomment-341758493
> Look into your shell’s startup files. You likely have HOMEBREW_CASK_OPTS set somewhere.
