### ISSUE TITLE
Add some description of updating to the FAQ / Usage

### ISSUE THREAD

**Issue by lucas-clemente** [caskroom/homebrew-cask#403]
I just found cask and am curious about your idea of handling app updates. Should I just normally use the app's update feature or wait for a cask update? Does it matter at all? ;)

I think a paragraph describing this should be added to the FAQ or maybe Usage, since I think many users might have that question.

**Comment by phinze** [comment]
Our [FAQ](https://github.com/caskroom/homebrew-cask/blob/master/doc/FAQ.md) has several notes about updating. :ok_woman:
