### ISSUE TITLE
Plist support question

### ISSUE THREAD

**Issue by sosedoff** [caskroom/homebrew-cask#40325]
Does homebrew-cask support `plist` definition? I know that's supported in regular homebrew formulas, but i'm not sure if the same applies to casks. I have a cask `pgweb` that i'd like to add the plist to easily manage the service.

**Comment by commitay** [comment]
No, we don't support that and AFAIK we aren't going to. Very few casks would benefit from such a feature.

If you want to add support for `brew services` I'd suggest moving `pgweb` to `homebrew/core` but that will mean that it needs to be built from source.
