### ISSUE TITLE
Calling `brew cask` with the `--caskroom` flag is disabled!

### ISSUE THREAD

**Issue by jacanchaplais** [caskroom/homebrew-cask#40334]
Homebrew Cask has recently stopped working. I am not sure as to whether this is a general bug, or an issue with my setup, but whenever "brew cask..." is used, I get the same error every time. I'm running OSX 10.12.6 on a Mid 2014 MacBook Pro. I have tried uninstalling and reinstalling homebrew, untapping a tapping caskroom/cask and `brew update-reset && brew update`, all to no avail.

#### Output of `brew cask doctor`

```
Error: Calling `brew cask` with the `--caskroom` flag is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
Look into your shell’s startup files. You likely have `HOMEBREW_CASK_OPTS` set somewhere.
