### ISSUE TITLE
Cask request: edrawmax

### ISSUE THREAD

**Issue by xuzj365** [caskroom/homebrew-cask#40384]
### Cask details

Name:EdrawMax

Homepage:http://www.edrawsoft.cn

Download URL:http://www.edrawsoft.cn/2download/edrawmax-cn.dmg

Description:EdrawMax

**Comment by xuzj365** [comment]
edrawmax-cn

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/40396
