### ISSUE TITLE
Updating the zap stanza for mactex.rb and mactex-no-ghostscript.rb

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#40452]
Ping @vitorgalvao for thoughts on this.

Installing [mactex.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mactex.rb) or [mactex-no-ghostscript.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mactex-no-ghostscript.rb) installs a number of GUI applications, namely TeXShop, BibDesk, LaTeXiT, TeX Live Utility and Excalibur, and the user also has the option to manually install cocoAspell from `/Applications/TeX/cocoAspell/cocoAspell.pkg`.

There are individual Casks for each of these, and I have recently updated all of their `zap` stanzas in https://github.com/caskroom/homebrew-cask/pull/40447, https://github.com/caskroom/homebrew-cask/pull/40443, https://github.com/caskroom/homebrew-cask/pull/40444, https://github.com/caskroom/homebrew-cask/pull/40451, https://github.com/caskroom/homebrew-cask/pull/40445 and https://github.com/caskroom/homebrew-cask/pull/40446.

Now, this also means that the `zap` stanza's for `mactex.rb` and `mactex-no-ghostscript.rb` need to be updated. At the moment, they look like this:
```
zap delete: [
                '~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/texshop.sfl*',
                '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeXShop Help*',
                '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/edu.ucsd.cs.mmccrack.bibdesk.help',
                '~/Library/Caches/edu.ucsd.cs.mmccrack.bibdesk',
                '~/Library/Caches/fr.chachatelier.pierre.LaTeXiT',
                '~/Library/Caches/TeXShop',
                '~/Library/Saved Application State/edu.bucknell.Excalibur.savedState',
                '~/Library/texlive/2017',
                '~/Library/TeXShop',
              ],
      trash:  [
                '/usr/local/texlive/texmf-local',
                '~/Library/Application Support/BibDesk',
                '~/Library/Application Support/TeXShop',
                '~/Library/Application Support/TeX Live Utility',
                '~/Library/Preferences/edu.ucsd.cs.mmccrack.bibdesk.plist',
                '~/Library/Preferences/Excalibur Preferences',
                '~/Library/Preferences/fr.chachatelier.pierre.LaTeXiT.plist',
                '~/Library/Preferences/TeXShop.plist',
              ],
      rmdir:  [
                '/usr/local/texlive',
                '~/Library/texlive',
              ]
```

I think it may be better to replace the `zap` stanza's in `mactex.rb` and `mactex-no-ghostscript.rb` with:
```
zap delete: '~/Library/texlive/2017',
    trash:  '/usr/local/texlive/texmf-local',            
    rmdir:  [
              '/usr/local/texlive',
              '~/Library/texlive',
            ]
```

and add a `caveat` explaining that to `zap` all of the corresponding GUI applications, one should run:
```
brew cask zap --force texshop
brew cask zap --force bibdesk
brew cask zap --force latexit
brew cask zap --force tex-live-utility
brew cask zap --force excalibur
```
and if the user manually installed cocoAspell then the user could also run
```
brew cask zap --force cocoaspell
```

That way, in the future one could just update the `zap` stanza's of each individual GUI application's Cask and not have to also update the `zap` stanza in `mactex.rb` and `mactex-no-ghostscript.rb`, which are _very_ big downloads.

Also, `zap`'ing MacTex and all the associated GUI applications _before_ installing a newer version of MacTex is _very_ handy, because when a new version is released every year there is no simple way to remove _everything_ the previous version installed and gain back the valuable disk space (~ 6 GB), since new versions install in parallel with any previous versions (as opposed to overwriting/uninstalling).

Thoughts?

Otherwise, I can just update the `zap`'s in `mactex.rb` and `mactex-no-ghostscript.rb`.

**Comment by miccal** [comment]
However, there is a slight issue with this idea - TeXShop, BibDesk, LaTeXiT and TeX Live Utility are installed in `/Applications/TeX` and Excalibur is installed in `/Applications/TeX/Excalibur-4.0.7` via MacTex, whereas the individual Casks just install to `/Applications`, so maybe this is not such a good idea...

**Comment by miccal** [comment]
Maybe just update the `zap` stanza for `mactex.rb` and `mactex-no-ghistscript.rb` like so, which everything separated to make future updates easier:
```
zap delete: [
              '~/Library/texlive/2017',
              # TexShop:
              '~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/texshop.sfl*',
              '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeXShop Help*',
              '~/Library/Caches/TeXShop',
              '~/Library/TeXShop',
              # BibDesk:
              '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/edu.ucsd.cs.mmccrack.bibdesk.help*',
              '~/Library/Caches/edu.ucsd.cs.mmccrack.bibdesk',
              '~/Library/Cookies/edu.ucsd.cs.mmccrack.bibdesk.binarycookies',
              # LaTeXiT:
              '~/Library/Caches/fr.chachatelier.pierre.LaTeXiT',
              '~/Library/Cookies/fr.chachatelier.pierre.LaTeXiT.binarycookies',
              # TeX Live Utility:
              '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeX Live Utility Help*',
              # Excalibur:
              '~/Library/Saved Application State/edu.bucknell.Excalibur.savedState',
            ],
    trash:  [
              '/usr/local/texlive/texmf-local',
              # TexShop:
              '~/Library/Application Support/TeXShop',
              '~/Library/Preferences/TeXShop.plist',
              # BibDesk:
              '~/Library/Application Support/BibDesk',
              '~/Library/Preferences/edu.ucsd.cs.mmccrack.bibdesk.plist',
              # LaTeXiT:
              '~/Library/Preferences/fr.chachatelier.pierre.LaTeXiT.plist',
              # TeX Live Utility:
              '~/Library/Application Support/TeX Live Utility',
              # Excalibur:
              '~/Library/Preferences/Excalibur Preferences',
            ],
    rmdir:  [
              '/usr/local/texlive',
              '~/Library/texlive',
            ]
```

**Comment by miccal** [comment]
On the other hand, the `uninstall delete:` stanza would take care of the `.app`'s since `'/Applications/TeX'` is removed:
```
uninstall pkgutil: [
                     'org.tug.mactex.ghostscript9.21',
                     'org.tug.mactex.gui2017',
                     'org.tug.mactex.texlive2017',
                   ],
          delete:  [
                     '/usr/local/texlive/2017',
                     '/Applications/TeX',
                     '/Library/PreferencePanes/TeXDistPrefPane.prefPane',
                     '/etc/paths.d/TeX',
                     '/etc/manpaths.d/TeX',
                   ]
```

**Comment by vitorgalvao** [comment]
Well researched!

I’m partial to https://github.com/caskroom/homebrew-cask/issues/40452#issuecomment-342711893 (comments), but if you have a preference, I’m fine with it. You clearly know these more intrinsically, so I trust your judgement.

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/40544 and https://github.com/caskroom/homebrew-cask/pull/40545.

**Comment by miccal** [comment]
Both PR's pass `audit` and `style`, so it might be best if a @caskroom/maintainers can merge them directly so as to not bog down Travis.
