### ISSUE TITLE
Cask request: Visitors

### ISSUE THREAD

**Issue by marktheis** [caskroom/homebrew-cask#40467]
### Cask details

Name: Visitors

Homepage: https://www.mediaatelier.com/Visitors

Download URL: https://www.mediaatelier.com/Visitors (press "version history" for a list of releases)

Description: A simple menubar app for tracking your visitors using Google Analytics in realtime.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/40468
