### ISSUE TITLE
Not able to uninstall: Failed command: /usr/sbin/dseditgroup -o delete access_bpf

### ISSUE THREAD

**Issue by xanview** [caskroom/homebrew-cask#40483]
#### Description of issue

Not able to uninstall, any ideas?

```$ brew cask uninstall  wireshark-chmodbpf --force
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:30:in `block in load'

==> Uninstalling Cask wireshark-chmodbpf
==> Running uninstall process for wireshark-chmodbpf; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Group not found.
Error: Command failed to execute!

==> Failed command:
/usr/sbin/dseditgroup -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Group not found.


==> Exit status of failed command:
#<Process::Status: pid 99128 exit 64>
$
```

#### Output of your command with `--verbose --debug`

```
$ brew cask uninstall  wireshark-chmodbpf --force --verbose --debug
==> Uninstalling Cask wireshark-chmodbpf
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:30:in `block in load'

==> Uninstalling Cask wireshark-chmodbpf
==> Un-installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x007fabcd0f9b98>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for wireshark-chmodbpf; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Executing: ["/bin/chmod", "--", "+x", "/usr/sbin/dseditgroup"]
==> Executing: ["/usr/sbin/dseditgroup", "-o", "delete", "access_bpf"]
==> Group not found.
Error: Command failed to execute!

==> Failed command:
/usr/sbin/dseditgroup -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Group not found.


==> Exit status of failed command:
#<Process::Status: pid 4765 exit 64>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:76:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:199:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:53:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:50:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:50:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:384:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:381:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:370:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
$
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6
caskroom/homebrew-cask (git revision d5480; last commit 2017-11-08)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (7 files, 800.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3803 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
PATH="~/Development/home/bin:/usr/local/Cellar/ruby/2.4.1_1/bin:./node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/nginx/sbin:/usr/local/sbin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
$
```

**Comment by commitay** [comment]
Run `brew cask install --force wireshark; brew cask uninstall wireshark`

**Comment by xanview** [comment]
I get this:

```
$ brew cask install --force wireshark; brew cask uninstall wireshark
Error: Cask 'wireshark' conflicts with 'wireshark-chmodbpf'.
Error: Cask 'wireshark' is not installed.
```

**Comment by commitay** [comment]
Sorry, I missed the that you are trying to uninstall `wireshark-chmodbpf` not `wireshark`

Please run this:
`brew cask install --force wireshark-chmodbpf; brew cask uninstall wireshark-chmodbpf`

**Comment by xanview** [comment]
$ brew cask install --force wireshark-chmodbpf; brew cask uninstall wireshark-chmodbpf
==> Caveats
You must reboot for the installation of wireshark-chmodbpf to take effect.

This cask will install only the ChmodBPF package from the current Wireshark
stable install package.
An access_bpf group will be created and its members allowed access to BPF
devices at boot to allow unprivileged packet captures.
This cask is not required if installing the Wireshark cask. It is meant to
support Wireshark installed from Homebrew or other cases where unprivileged
access to macOS packet capture devices is desired without installing the binary
distribution of Wireshark.
The user account used to install this cask will be added to the access_bpf
group automatically.

==> Satisfying dependencies
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.4.2%20Intel%2064.dmg
Already downloaded: /Users/Hackeron/Library/Caches/Homebrew/Cask/wireshark-chmodbpf--2.4.2.dmg
==> Verifying checksum for Cask wireshark-chmodbpf
==> Installing Cask wireshark-chmodbpf
==> Running installer for wireshark-chmodbpf; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Wireshark 2.4.2 Intel 64
==> installer: choices changes file '/var/folders/wv/msb2x08n4673j278hhwmlb100000gn/T/choices20171108-81579-50b7jb.xml' applied
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  wireshark-chmodbpf was successfully installed!
==> Uninstalling Cask wireshark-chmodbpf
==> Running uninstall process for wireshark-chmodbpf; your password may be necessary
==> Removing launchctl service org.wireshark.ChmodBPF
==> Running uninstall script /usr/sbin/dseditgroup
==> Group record below will be deleted:
==> dsAttrTypeStandard:GeneratedUID -
==> 		A103893F-E7F4-4265-902C-082CD6DC62A1
==> dsAttrTypeStandard:RecordName -
==> 		access_bpf
==> dsAttrTypeStandard:AppleMetaNodeLocation -
==> 		/Local/Default
==> dsAttrTypeStandard:GroupMembers -
==> 		FFFFEEEE-DDDD-CCCC-BBBB-AAAA00000000
==> 		E6E9958B-A045-4863-8E22-3A210E526B08
==> dsAttrTypeStandard:PrimaryGroupID -
==> 		501
==> dsAttrTypeStandard:RecordType -
==> 		dsRecTypeStandard:Groups
==> dsAttrTypeStandard:GroupMembership -
==> 		root
==> 		Hackeron
==> Uninstalling packages:
org.wireshark.ChmodBPF.pkg
wireshark-chmodbpf 2.0.3 is still installed.
Remove it with `brew cask uninstall --force wireshark-chmodbpf`.
$
```

So it seems after running that, it's still installed, when I try to remove, I get this:

```
$ brew cask uninstall --force wireshark-chmodbpf
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:30:in `block in load'

==> Uninstalling Cask wireshark-chmodbpf
==> Running uninstall process for wireshark-chmodbpf; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Group not found.
Error: Command failed to execute!

==> Failed command:
/usr/sbin/dseditgroup -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Group not found.


==> Exit status of failed command:
#<Process::Status: pid 83036 exit 64>
$
```

**Comment by xanview** [comment]
Ah, this worked, thank you!! <

```
$ brew cask install --force wireshark-chmodbpf; brew cask uninstall wireshark-chmodbpf --force
```
