### ISSUE TITLE
Removing same pkgutil packages in different casks

### ISSUE THREAD

**Issue by nrlquaker** [caskroom/homebrew-cask#40505]
For example [microsoft-office](https://github.com/caskroom/homebrew-cask/blob/37b0136a2098e9eb806480cf82f06e391c3db408/Casks/microsoft-office.rb) does: `uninstall pkgutil: 'com.microsoft.package.*'`.
But `com.microsoft.package.Microsoft_AutoUpdate.app` is used in [skype-for-business](https://github.com/caskroom/homebrew-cask/blob/75cd6fa66112a3077443cea72ffad9bfc352a412/Casks/skype-for-business.rb)
as well.
So removing one of those apps will remove part of the other.

Maybe it should be at least mentioned at `caveats`?

**Comment by nrlquaker** [comment]
Also [microsoft-office](https://github.com/caskroom/homebrew-cask/blob/37b0136a2098e9eb806480cf82f06e391c3db408/Casks/microsoft-office.rb) removes `launchctl: 'com.microsoft.autoupdate.helpertool'` and `Caches` etc.

**Comment by commitay** [comment]
[`zap.md`](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/doc/cask_language_reference/stanzas/zap.md)

> `zap` stanzas may remove:
>
> * Preference files and caches stored within the user’s `~/Library` directory.
> * Shared resources such as application updaters. Since shared resources may be removed, other applications may be affected by `brew cask zap`. Understanding that is the responsibility of the end user.
___

Moved `pkgutil` / `launchctl` for the updater to `zap`: https://github.com/caskroom/homebrew-cask/pull/40506
