### ISSUE TITLE
Use trash instead of delete in zap stanzas

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#40501]
PRs for `zap` stanzas account for a reasonable amount of the traffic in Caskroom. 

Sorting `zap` stanzas by what should be deleted or trashed is turning into a non-trivial amount of maintainer effort and it isn't always clear which files/folders should be trashed and what can be safely deleted.

Improving the documentation could help reduce the amount of changes that need to be made to PRs but we can't document all possible cases and not all contributors will read the documentation.

I would like for us to move the onus of this decision onto the user by trashing _**all**_ files in `zap` stanzas and allow users to decide what they want to keep.

**Comment by vitorgalvao** [comment]
Fine by me.

**Comment by commitay** [comment]
I'll wait a few days to see if the other maintainers have thoughts on this.

If no one objects I'll see about converting all `zap delete` stanzas to `zap trash`. Probably try to do it in groups by first letter of the Cask to limit the size of the diff.

I've put https://github.com/caskroom/homebrew-cask/pull/40386 on hold for now, I'll update the docs to use `trash` only for `zap` if everyone agrees.

**Comment by Xcq5678** [comment]
Matt

**Comment by commitay** [comment]
I'll do this over the weekend, less traffic and CI will be quick.

**Comment by commitay** [comment]
All `zap delete` stanzas have been changed to `zap trash`. (Possible I've missed a couple but I'll do another check.)

Updated the docs PR (https://github.com/caskroom/homebrew-cask/pull/40386) to use `zap trash`
