### ISSUE TITLE
Large zap updates

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#40557]
I have noticed (under MacOS 10.13 at least) that there has been a slight change the filenames stored in the folders
```
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/
```
and
```
~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/
```
For example, on my system:
```
-bash-4.4.12- /Users/miccal/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments (9) [> ls -l1
com.apple.ichat.sfl2
com.apple.preview.sfl2
com.apple.textedit.sfl2
com.github.atom.sfl2
org.libreoffice.script.sfl2
org.m0k.transmission.sfl2
texshop.sfl2
```
and:
```
-bash-4.4.12- /Users/miccal/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile (5) [> ls -l1
TeX Live Utility Help*1.30
TeXShop Help*3.88
Transmission Help*2.92
```

Notice that the files in 
```
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/
```
now have extension `.sfl2` instead of the usual `.sfl`, and the files in 
```
~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/
```
now have `*{version}` added to the end.

Now, looking at the `zap` stanza for `texshop`/`mactex` as an example, which originally were:
```
zap delete: [
              '~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/texshop.sfl',
              '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeXShop Help',
              [snip]
```
I recently changed them to
```
zap delete: [
              '~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/texshop.sfl*',
              '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeXShop Help*',
              [snip]
```

There are _many_ examples of these type of files in the `zap` stanzas of Casks, and in theory they would _all_ need to be updated.

Instead of a Contributor like me flooding the system with a butt-load of PR's, it might be better if a Maintainer updated all these with a clever use of `grep` and `sed`, and performed a direct merge.

@vitorgalvao a.k.a script-wiz, looking in your direction.

**Comment by miccal** [comment]
I quick search shows 155 Casks with `~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/` in their `zap` stanza, and 18 with `~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/` in their `zap` stanza.

**Comment by vitorgalvao** [comment]
Was running the script when I noticed @commitay already did it.

Closing in favour of the open PRs.
