### ISSUE TITLE
Outdated cask: omegat-dev

### ISSUE THREAD

**Issue by citroentje** [caskroom/homebrew-cask#40614]
Outdated cask: caskroom/versions/omegat-dev
Github URL: https://github.com/caskroom/homebrew-versions/blob/966a03a1735b0d9a16092e622b0770ea755c9c3e/Casks/omegat-dev.rb
Outdated version: OmegaT_4.1.2_Beta_Mac_Signed
Current version: OmegaT_4.1.2_02_Beta_Mac_Signed ('minor' release suffix _02 ignored by cask as implemented)

Value of omegat-dev over regular omegat cask: 'standard' release cycle is most conservative; 'beta' is stable enough in practice and has the features many translators will want.

2 issues with omegat-dev cask:
- Cask Formula does not take the **minor patch number** 4.1.2_02 **suffixes** **(_02)** of some releases into account, so it skips downloading those 'minor' patch releases. It seems the regular omegat cask formula does already take these into account.
- **Error:** Unpacking and moving OmegaT.app from the downloaded zip to the Mac application directory fails. Removing the subdirectory from the cask formula file seems to do the trick.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-versions/pull/4747
