### ISSUE TITLE
_audit_modified_casks: fails or audits multiple Casks

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#40648]
https://travis-ci.org/caskroom/homebrew-cask/builds/301185254
```
>>> brew cask _audit_modified_casks 6eae398988688a5f1fdf5695ea10794c3da6b4b2...76a94d96f9b2571f373874896da7c7e7aa3c6770
Error: Cask 'abgx360' is unavailable: No Cask with this name exists.
```

```
(I thought I had a couple of examples for multiple Casks saved but I can't find them)
```
These occur when the contributors fork is outdated (sometimes by only a few hours).

It's easily fixed by rebasing the branch against master but on several occasions I've had contributors inadvertently revert the rebase and also any changes that have been made.

Looking the the history of the travis scripts there have been several "commit range" workarounds added and removed previously so I not sure if this is a problem we have encountered before, thought I'd ask first before I try to come up with another workaround.

**Comment by vitorgalvao** [comment]
It sounds familiar.

But as you said, much as changed, even in Travis itself, so even old solutions may be worth retrying.

**Comment by commitay** [comment]
It just occurred to me that it would be easier to cherrypick the commits to a new branch/PR.

I might come back to this if it becomes more of a problem but for now it probably isn't worth the effort of testing workarounds.
