### ISSUE TITLE
Cask request: Mozilla Firefox 57.0

### ISSUE THREAD

**Issue by guillaumebriday** [caskroom/homebrew-cask#40678]
### Cask details

Mozilla Firefox 57.0 Final is available ! 

Name: Firefox

Homepage:  https://www.mozilla.org/en-US/firefox/new/

Download URL: https://archive.mozilla.org/pub/firefox/releases/57.0/

Description: Mozilla Firefox 57.0 Final is available !

**Comment by nathancahill** [comment]
#40700
