### ISSUE TITLE
Cask request: [Snappy]

### ISSUE THREAD

**Issue by zh0kx** [caskroom/homebrew-cask#40680]
### Cask details

Name: snappy

Homepage: http://snappy-app.com/

Download URL: http://snappy-app.com/download

Description: We call them snaps for short. A snap is always-on-top and allows you to annotate, resize, change opacity and more. 
Snappy is perfect for clipping stuff from your screen, visual note taking, reference information between windows - on top of the many creative uses you'll discover along the way.

**Comment by commitay** [comment]
App Store only.

**Comment by commitay** [comment]
From  the Cask request template:

```
Before you do, note **we cannot support Mac App Store-only apps**
```
