### ISSUE TITLE
Cask Request: TermHere

### ISSUE THREAD

**Issue by 404NetworkError** [caskroom/homebrew-cask#40711]
### Cask details

Name: TermHere

Homepage: https://hbang.ws/apps/termhere

Download URL: https://github.com/hbang/TermHere/releases/download/1.2.1/TermHere.1.2.1.dmg

Description: TermHere is a macOS Service and Finder extension that has one job – to place a “New Terminal Here” button in the Finder toolbar and in right-click context menus. Click it, and a new terminal window will open that is immediately switched to the current directory, ready for you to work in immediately.

Note: This program does require being enabled in the Extensions preference pane.

**Comment by commitay** [comment]
Are you going to submit a PR for this?

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/40718
