### ISSUE TITLE
Mattermost cask checks for validity on every boot/open

### ISSUE THREAD

**Issue by Xophmeister** [caskroom/homebrew-cask#40780]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

After installing the Mattermost cask, when opening the Mattermost application, macOS first verifies the download (which takes a few minutes), if it hasn't done so during the current session, and then prompts me with:

> "Mattermost" is an application downloaded from the Internet. Are you sure you want to open it?
> Google Chrome.app downloaded this file on 5 September 2017

The verification happens on _every_ boot and the above prompt _every_ time I open the application.

AFAIK, there's nothing wrong with Homebrew, just this cask is a bit messed up.

#### Output of your command with `--verbose --debug`

n/a

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.7
caskroom/homebrew-cask (git revision 7d44c; last commit 2017-11-13)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3815 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
PATH="/Users/ch12/perl5/bin:/usr/local/git/bin:/usr/local/bin:/Users/ch12/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/munki:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/usr/games/bin:/Users/ch12/Library/Haskell/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by commitay** [comment]
Can you reproduce this installing the `app` manually?

**Comment by Xophmeister** [comment]
If I install it manually, then macOS will do the verification and warn me about installing something downloaded from the Internet once (i.e., at install and first run time, respectively). After that, it just works without complaint.

**Comment by commitay** [comment]
I get the initial quarantine prompt but I can't reproduce it after first launch even after logging out or rebooting.

Having a look at older versions of `mattermost` they all seem to have the quarantine attribute set, so as we haven't had previous reports of this I think it may be specific to your setup somehow.

As it is not reproducible  all I can really suggest is removing the quarantine attribute manually.

```
/usr/bin/xattr -dr com.apple.quarantine /Applications/Mattermost.app
```

**Comment by Xophmeister** [comment]
Perfect: I didn't realise you could do that. Thanks 🙂
