### ISSUE TITLE
Feature request: brew cask reset (zap without uninstall)

### ISSUE THREAD

**Issue by toonetown** [caskroom/homebrew-cask#40880]
### Description of feature/enhancement
It would be nice to be able to reset a package's data directories (like `zap` does) without uninstalling the original cask.  I would suggest using the term `reset` (i.e. `brew cask reset android-studio`).  It would take al the same parameters as `zap`

### Justification
The main reason for this would be to reset the preferences for an app to its default state.

Currently, this can be achieved by a combination of `zap` and `install`...but for large applications, this can involve redownloading the application during the install phase.

It can also be achieved by `brew cask cat <token>` and deleting stuff from the `zap` stanza manually.  This, however, can be tedious as well.

### Example use case
One use case I have run into is with android-studio.  Sometimes it gets in a "wonky" state, and cleaning up the SDK directory and its preferences will get it back to a working condition.  Since the application is quite large, the second download is kind of painful.

Yes - if it's cached, it won't redownload, however, when using homebrew and homebrew-cask in an scripted environment to automate system deployment, it's nice to be able to get back to a "clean" starting point.

**Comment by commitay** [comment]
While I can see these use for this with some Casks, `zap` does not respect shared files (updaters, etc) and in some Casks completely duplicates the `uninstall`. 

I would be concerned that promoting `reset` as an option to "reset" prefs, caches, etc could lead to unexpected results for the user.

**Comment by vitorgalvao** [comment]
> and in some Casks completely duplicates the `uninstall`.

Wait, we have those? Why? `zap` always runs `uninstall` beforehand, so there’s no need for any duplication between them.

> I would be concerned that promoting `reset` as an option to "reset" prefs, caches, etc could lead to unexpected results for the user.

Agreed. While on one hand I’m fine with the feature since the user should be familiar with the possibility of screwing up files for another app, in practice I think we’d get bug reports and PRs that would make `zap` less useful, to avoid those cases. Having a third stanza just for `reset` is out of the question — too much work for too little gain.

**Comment by commitay** [comment]
> Wait, we have those? Why? 

Only two or three  Casks with "automatic" uninstallers, the `zap` is a backup. [`nomachine`](https://github.com/caskroom/homebrew-cask/blob/75a1e93e2406d2b75f3e1ad92d58ae82e1810559/Casks/nomachine.rb#L9-L27) is the only one I can think of offhand but there are a couple of others.

**Comment by commitay** [comment]
Closing as per https://github.com/caskroom/homebrew-cask/issues/40880#issuecomment-345513041

@toonetown You can perform a "reset" by piping the output of `brew cask _stanza {cask}`

Quick example:
```
$ brew cask _stanza zap android-studio | xargs -n 1 | grep -A2 trash | grep Library | tr -d ","
~/Library/Android/sdk
~/Library/Application Support/AndroidStudio3.0
~/Library/Caches/AndroidStudio3.0
~/Library/Logs/AndroidStudio3.0
~/Library/Preferences/AndroidStudio3.0
~/Library/Preferences/com.android.Emulator.plist
~/Library/Saved Application State/com.google.android.studio.savedState
```
