### ISSUE TITLE
synergy 2.0 support?

### ISSUE THREAD

**Issue by jiayihao** [caskroom/homebrew-cask#40886]
can homebrew-cask support synergy 2.0?
thx.

**Comment by commitay** [comment]
> can homebrew-cask support synergy 2.0?

I don't understand what this means?

**Comment by jiayihao** [comment]
I'd like to use brew-cask to install the app -- Synergy (version 2).
Now the version remains 1.8.8 in brew-cask

**Comment by commitay** [comment]
> [Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```
```
cask-repair -v {version}
```

**Comment by jiayihao** [comment]
thank you very much.
