### ISSUE TITLE
Cask request: ShadowsocksX-NG

### ISSUE THREAD

**Issue by MaoKwen** [caskroom/homebrew-cask#40999]
### Cask details

Name: ShadowsocksX-NG

Homepage: https://github.com/shadowsocks/ShadowsocksX-NG

Download URL: https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/v1.6.1/ShadowsocksX-NG.1.6.1.zip

Description: Next Generation - a gui shadowsocks client for macOS.

**Comment by commitay** [comment]
[shadowsocksx-ng](https://github.com/caskroom/homebrew-cask/blob/master/Casks/shadowsocksx-ng.rb)
