### ISSUE TITLE
Cask request: Manuskript

### ISSUE THREAD

**Issue by lamelas** [caskroom/homebrew-cask#41188]
### Cask details

Name: Manuskript

Homepage: http://www.theologeek.ch/manuskript/

Download URL: https://github.com/olivierkes/manuskript/releases/download/0.5.0/manuskript-0.5.0-osx.zip

Description: Open-source tool for writers

**Comment by commitay** [comment]
This will need `binary` and possibly a shimscript.

The "app" is a GUI built with pyqt.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41286
