### ISSUE TITLE
Cask Update: [ lantern ]

### ISSUE THREAD

**Issue by ListenerRi** [caskroom/homebrew-cask#41181]
Another url for cask lantern.
It is `https://getlantern.org/lantern-installer.dmg` for now , but this domain has been blocked in some areas.

This is another official url:
`https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.dmg`

**Comment by commitay** [comment]
This is somewhat against our usual policy of using the homepage download but the homepage does link to the GitHub page.

Ping @vitorgalvao

**Comment by vitorgalvao** [comment]
I’d be more inclined to change it if the github URL were a releases URL.

> but this domain has been blocked in some areas.

Please be more specific. Blocked by whom? Blocked why? And which areas exactly? If it was blocked by yourself on your own machine in a 3 meters radius in the middle of the Atlantic Ocean, the block is inconsequential. If it was blocked by a whole country, it does indeed matter, but then we need to take into account if Github itself isn’t [blocked in a bigger area](https://en.wikipedia.org/wiki/Censorship_of_GitHub).

**Comment by dainslef** [comment]
@vitorgalvao  In China, dues to GFW, when I use "brew cask install lantern", it get this:

==> Satisfying dependencies
==> Downloading https://getlantern.org/lantern-installer.dmg

curl: (7) Failed to connect to getlantern.org port 443: Connection refused
Error: Download failed on Cask 'lantern' with message: Download failed: https://getlantern.org/lantern-installer.dmg

**Comment by vitorgalvao** [comment]
Alright. I’m fine with changing the URL. If it breaks for other people, we’ll deal with it then.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41274
