### ISSUE TITLE
Bartender 3 - test builds

### ISSUE THREAD

**Issue by ondrejfuhrer** [caskroom/homebrew-cask#41211]
Hey guys,

I just noticed one think, that under the bartender cask there is actually a test build. What I got as an answer from the creators on Twitter, the current stable version is 3.0.12 which is mentioned in the appcast (https://www.macbartender.com/B2/updates/Appcast.xml). 

So what we actually now have (version 3.0.30) is a test build. Shouldn't that reflected and the versions split? So we would have `bartender` and `bartender-test` casks or similar?

**Comment by vitorgalvao** [comment]
No. We should simply revert the cask to the stable version. Thank you for the report!

https://github.com/caskroom/homebrew-cask/pull/41216
