### ISSUE TITLE
Cask request: Journey

### ISSUE THREAD

**Issue by ploum** [caskroom/homebrew-cask#41267]
### Cask details
Name: Journey

Homepage: https://2appstudio.com/journey/#mac

Download URL: https://releases-journey.2appstudio.com/download/osx?filetype=dmg

Description: 
Journey is a cross-platform diary app developed by 2appstudio.

**Comment by commitay** [comment]
> https://github.com/2-App-Studio/journey-releases

> https://github.com/2-App-Studio/journey-releases/releases/download/v2.2.11/Journey-darwin-x64-2.2.11.dmg

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41287

**Comment by ploum** [comment]
Thanks a lot :-)
