### ISSUE TITLE
Cask request: [Screenshot Designer]

### ISSUE THREAD

**Issue by RaizoCN** [caskroom/homebrew-cask#41359]
### Cask details

Name:Screenshot Designer

Homepage:http://www.screenshotdesigner.com/

Download URL:https://screenshotdesigner.com/Screenshot%20Designer.dmg

Description:The ultimate App Store screenshot toolkit!

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41385
