### ISSUE TITLE
Losing Track of Installed Casks

### ISSUE THREAD

**Issue by sonarforte** [caskroom/homebrew-cask#41350]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I'm having an issue with brew losing track of installed casks. 

E.g., I recently installed Thunderbird with `$ brew cask install thunderbird`. It moved the app directory into `/Applications/` without symlinking anything to `/usr/local/` or anything like that, and when I go to uninstall Thunderbird with `$ brew cask uninstall thunderbird`,  I get "No such keg: /usr/local/Cellar/thunderbird". 

I don't remember cask working like this in the past. Is this a new update where it installs casks to eh `/Applications/` directory and forgets about them? How can I override this behavior so that cask will still keep track of installed applications? 

#### Output of your command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
