### ISSUE TITLE
Update USAGE.md with brew cask (outdated|upgrade)

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#41377]
https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks

**Comment by joshghent** [comment]
Hey there, first timer, going to work on this tomorrow! 👍

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#other-commands

https://github.com/caskroom/homebrew-cask/pull/42004
