### ISSUE TITLE
Add `brew cask upgrade` to man page

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#41372]
Refs: https://github.com/Homebrew/brew/pull/3396

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/manpages/brew-cask.1.md

**Comment by SeanPrashad** [comment]
Hi @commitay! I'd love to work on this but I'm not sure which documentation file I'm updating since the URL you linked is in an entirely different repo - could you point me in the right direction please?

**Comment by commitay** [comment]
Hi @SeanPrashad!

The URL is correct, our core code was merged with Homebrew.

`brew-cask.1.md` can be updated, then  run `brew man` to regenerate the man page and commit the changed files.

An example of a similar manpage update and the regenerated files is https://github.com/Homebrew/brew/pull/3221

**Comment by SeanPrashad** [comment]
@commitay I've done initial changes but when I run the `brew man` command, it doesn't change anything: 
<img width="491" alt="screen shot 2017-12-29 at 6 48 53 pm" src="https://user-images.githubusercontent.com/13009507/34449683-0fd5aa94-ecc9-11e7-8077-a6cbfba9f22e.png">

I've also committed the modified source files before and after I ran that command - is there something I missed?

**Comment by commitay** [comment]
Looks like your working in a different repo to your Homebrew installation, the changes need to be made in the same repo that `brew man` will run in.
```
$ echo test > $(brew --repo)/Library/Homebrew/manpages/brew-cask.1.md

$ brew man
Writing markdown to /usr/local/Homebrew/docs/Manpage.md
Writing man page to /usr/local/Homebrew/manpages/brew.1
Writing man page to /usr/local/Homebrew/manpages/brew-cask.1

$ git -C $(brew --repo) status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Library/Homebrew/manpages/brew-cask.1.md
	modified:   manpages/brew-cask.1

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by SeanPrashad** [comment]
I never knew that! I was using Homebrew for quite some time but never realized it made it's own repository on my Mac. Good to know 👍🏽

I've opened a PR with an initial documentation proposal found [here](https://github.com/Homebrew/brew/pull/3609).

**Comment by SeanPrashad** [comment]
Hi @commitay - my changes were reviewed and merged in https://github.com/Homebrew/brew/pull/3609 - is it safe to close this issue now?

**Comment by commitay** [comment]
Thanks @SeanPrashad!
