### ISSUE TITLE
Cask request: MWeb - Pro Markdown writing, note taking and static blog generator App

### ISSUE THREAD

**Issue by oulvhai** [caskroom/homebrew-cask#41378]
### Cask details

Name: MWeb

Homepage:  <http://www.mweb.im/>

Download URL: <https://dl.devmate.com/com.coderforart.MWeb/MWeb-ProMarkdownwriting%2CnotetakingandstaticbloggeneratorApp.dmg>

Description: MWeb for Mac - Pro Markdown writing, note taking and static blog generator App

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41383
