### ISSUE TITLE
Cask Update:  darwindumper

### ISSUE THREAD

**Issue by ListenerRi** [caskroom/homebrew-cask#41397]
url: https://bitbucket.org/blackosx/darwindumper/downloads/DarwinDumper_v3.0.4.zip

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

```
cask-repair -v 3.0.4 darwindumper
```

https://github.com/caskroom/homebrew-cask/pull/41403

**Comment by ListenerRi** [comment]
@vitorgalvao 
I have changed brew's repo to `https://mirrors.ustc.edu.cn/brew.git`, because connecting to github is too slow in china
cask-repair seems to require a github repo, so it doesn't work on my computer.
```
# cd /usr/local/Homebrew
# git remote -v
origin	https://mirrors.ustc.edu.cn/brew.git (fetch)
origin	https://mirrors.ustc.edu.cn/brew.git (push)
#
# cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
# git remote -v
origin	http://mirrors.ustc.edu.cn/homebrew-cask.git (fetch)
origin	http://mirrors.ustc.edu.cn/homebrew-cask.git (push)
```
