### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by henriguy1210** [caskroom/homebrew-cask#41401]
This isn't the right place for a question, but I don't know where to post this. 

How do i completely uninstall homebrew-cask extension? Thanks.

**Comment by vitorgalvao** [comment]
When making a question, please always summarise it in the tile.

Homebrew-cask is integrated with Homebrew, so you can’t get rid of it alone. What you can do is `untap` all our repos: `HOMEBREW_NO_AUTO_UPDATE=1 brew tap | grep '^caskroom' | xargs brew untap`.
