### ISSUE TITLE
Warsow checksum mismatch

### ISSUE THREAD

**Issue by tacotexmex** [caskroom/homebrew-cask#41526]
#### Description of issue

warsow.net went offline recently. Later the website resurfaced with a basic website with download links, with files not matching checksum anymore. The domain may've had an ownership change, which is why the new files offered can't be verified (they might just be malware, haven't opened them).

Don't update the checksum before things may become clearer.

```
Error: Checksum for Cask 'warsow' does not match.

Expected: 347c47b029dc706ab43b754ec7422c3766dde2b2ed9a3ce0f40cd0d52c64f94d
Actual:   4da4e4b70725e6d903e5fe431c05e207f2e294106ee8f34eb9d0917cfd6ba889
```

**Comment by commitay** [comment]
The checksum doesn't match because the download is a 3kb html document.

**Comment by commitay** [comment]
The checksum still matches, the download URL just needs to be updated.

```
shasum -a256 warsow_21.dmg
347c47b029dc706ab43b754ec7422c3766dde2b2ed9a3ce0f40cd0d52c64f94d  warsow_21.dmg
```

https://github.com/caskroom/homebrew-cask/pull/41527

**Comment by tacotexmex** [comment]
Oh, excellent.
