### ISSUE TITLE
nanobox checksum is incorrect

### ISSUE THREAD

**Issue by tpetry** [caskroom/homebrew-cask#41589]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
```
Error: Checksum for Cask 'nanobox' does not match.

Expected: db475905b0907afdd46e03227ebd7c3df0e3270f28544f2fd16de54142656e2e
Actual:   1ab3501db17a017debbdf8e1f3cba755ec62e2cf3bec90ac7bf9703e9583477a
File:     /Users/tpetry/Library/Caches/Homebrew/Cask/nanobox--2.3.0.pkg
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41600

https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error
