### ISSUE TITLE
Vagrant 2.0.1: expired certificate

### ISSUE THREAD

**Issue by jspadafore202** [caskroom/homebrew-cask#41610]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

homebrew-cask vagrant install - "Error: Command failed to execute!, Certificate used to sign package is not trusted." on macOS 10.12.6 (Sierra)

==> installer: Package name is Vagrant
==> installer: Certificate used to sign package is not trusted. Use -allowUntr
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/vagrant/2.0.1/vagrant.pkg -target /

==> Standard Output of failed command:
installer: Package name is Vagrant
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.

#### Output of your command with `--verbose --debug`
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.dmg
Already downloaded: /Users/WalterWhite/Library/Caches/Homebrew/Cask/vagrant--2.0.1.dmg
==> Downloaded to -> /Users/WalterWhite/Library/Caches/Homebrew/Cask/vagrant--2.0.1.dmg
==> Verifying download
==> Determining which verifications to run for Cask vagrant
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask vagrant
==> SHA256 checksums match
==> Installing Cask vagrant
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/WalterWhite/Library/Caches/Homebrew/Cask/vagrant--2.0.1.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/WalterWhite/Library/Caches/Homebrew/Cask/vagrant--2.0.1.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/2w/cvtd00m933b21dxmn7dnp1yc0000gn/T/d20171203-8116-c5ji3m", "/Users/WalterWhite/Library/Caches/Homebrew/Cask/vagrant--2.0.1.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/2w/cvtd00m933b21dxmn7dnp1yc0000gn/T/20171203-8116-e6d11c.list", "--", "/var/folders/2w/cvtd00m933b21dxmn7dnp1yc0000gn/T/20171203-8116-1nvt7jc.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/2w/cvtd00m933b21dxmn7dnp1yc0000gn/T/20171203-8116-1nvt7jc.bom", "--", "/private/var/folders/2w/cvtd00m933b21dxmn7dnp1yc0000gn/T/d20171203-8116-c5ji3m/dmg.aAiapV", "/usr/local/Caskroom/vagrant/2.0.1"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/2w/cvtd00m933b21dxmn7dnp1yc0000gn/T/d20171203-8116-c5ji3m/dmg.aAiapV"]
==> Creating metadata directory /usr/local/Caskroom/vagrant/.metadata/2.0.1/20171203121402.626.
==> Creating metadata subdirectory /usr/local/Caskroom/vagrant/.metadata/2.0.1/20171203121402.626/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00000101b46610>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/vagrant/2.0.1/vagrant.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is Vagrant
==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
==> Purging files for version 2.0.1 of Cask vagrant
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/vagrant/2.0.1/vagrant.pkg -target / -verboseR

==> Standard Output of failed command:
installer: Package name is Vagrant
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.

==> Standard Error of failed command:

==> Exit status of failed command:
#<Process::Status: pid 8247 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:53:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:59:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:51:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

#### Output of `brew cask doctor`

Homebrew-Cask 1.3.8
caskroom/homebrew-cask (git revision 533a6; last commit 2017-12-03)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (10 files, 391.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3851 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/opt/macports/bin:/opt/macports/sbin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

**Comment by jspadafore202** [comment]
Cert is actually expired:
Package "vagrant.pkg":
   Status: signed by a certificate that has since expired
   Certificate Chain:
    1. Developer ID Installer: Mitchell Hashimoto
       SHA1 fingerprint: 9D 16 F7 36 D1 D9 9E A2 1D DE E3 8B 93 27 14 8C 2B CE 1C 32

**Comment by commitay** [comment]
Upstream issue https://github.com/hashicorp/vagrant/issues/9240

**Comment by frite** [comment]
The vagrant cert has expired as of yesterday.

**Comment by geerlingguy** [comment]
My mac-dev-playbook builds have been failing for a couple days due to this issue :( https://travis-ci.org/geerlingguy/mac-dev-playbook/builds/311512428#L664

I'll follow the upstream issue.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41664
