### ISSUE TITLE
clamXav crash due to install location

### ISSUE THREAD

**Issue by rinchen** [caskroom/homebrew-cask#4171]
Hi,

If you brew cask install clamxav  and attempt to launch it, it will first prompt to you to move the binary to /Applications and if you don't it will then crash with:

Process:         ClamXav [37077]
Path:            /opt/homebrew-cask/*/ClamXav.app/Contents/MacOS/ClamXav
Identifier:      uk.co.markallan.clamxav
Version:         2.6.2 (311)
Code Type:       X86-64 (Native)
Parent Process:  launchd [215]
Responsible:     ClamXav [37077]
User ID:         501

Date/Time:       2014-05-03 09:26:32.966 -0600
OS Version:      Mac OS X 10.9.2 (13C1021)
Report Version:  11
Anonymous UUID:  FA836737-05A3-A711-3B8E-95E9DB3B074A

Sleep/Wake UUID: 548F46FE-91AB-432F-932E-6891BBEBA70F

Crashed Thread:  12

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
abort() called
terminating with uncaught exception of type NSException

**Comment by vitorgalvao** [comment]
Closing. If the crash still occurs, @rinchen, please report back.

**Comment by rinchen** [comment]
gah, sorry I missed the request from you @vitorgalvao back in November.  I'm on Yosemite and don't have it installed via cask anymore. Let's leave it close and assume it was something funky with my installation since you couldn't recreate it.
