### ISSUE TITLE
Feature request: devel and head versions of Emacs

### ISSUE THREAD

**Issue by nickmccurdy** [caskroom/homebrew-cask#41886]
### Description of feature/enhancement
`--devel` or `--HEAD` options for Emacs cask (not formula) to install versions of GUI Emacs other than stable.

### Justification
Many Emacs users use "unstable" versions because development builds actually have mostly stable APIs and it takes a while for stable releases to come out. Meanwhile, only the Emacs formula supports Spotlight search, and only the cask supports development and head versions of Emacs. It would be great if we could theoretically support every version of Emacs that the formula does (or at least something newer than stable). https://emacsformacosx.com/ seems to have some unstable builds, though I'm not sure if they cover everything from the formula.

### Example use case
- `brew cask install emacs --devel`
- `brew cask install emacs --HEAD`

**Comment by commitay** [comment]
> `--devel` or `--HEAD` options

We don't support these sorts of options. All versions considers non-stable, dev, beta, etc are in `caskroom/versions`

- https://github.com/caskroom/homebrew-versions/blob/master/Casks/emacs-nightly.rb

- https://github.com/caskroom/homebrew-versions/blob/master/Casks/emacs-pretest.rb
