### ISSUE TITLE
Add cycript

### ISSUE THREAD

**Issue by szhu** [caskroom/homebrew-cask#4188]
In light of [a recent patch for GrowlVoice](https://gist.github.com/kroo/11205755), it would be nice to have a formula for [cycript](http://www.cycript.org/).

Cycript seems to be distributed to be portable. The zip expands to three items:

- `cycript`, a two-line launcher script
- `Cycript.framework/`, which appears to be for header files
- `Cycript.lib/`, for the everything else

Can these be left in the same directory for Cask?

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/9203.
