### ISSUE TITLE
Stable / development  version of Grisbi

### ISSUE THREAD

**Issue by tcrxt** [caskroom/homebrew-cask#42050]
I've read https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md but I'm not sure what is the procedure in my case.

[Grisbi](http://www.grisbi.org/) (https://github.com/grisbi/grisbi/) has a cask ( homebrew-cask/Casks/grisbi.rb ) for the stable 1.0 version. It is the recommended version according to the developers (cf. http://en.grisbi.org/post/Download ), but it is not compatible with, e.g., macOS High Sierra 10.13.2. This issue is, afaik, not documented, but exist nevertheless.

A development version (currently 1.1.90) was released, and it is compatible with the latest updates of macOS.

**Is there any policy regarding including two casks for the same software, one for the development version, and one for the stable version? If so, what should be the cask name for both versions?**

**Comment by tcrxt** [comment]
@frantzmiccoli @LudovicRousseau @RemiCardona any idea / recommendation?

**Comment by commitay** [comment]
Development / beta versions could be added to [`caskroom/versions`](https://github.com/caskroom/homebrew-versions)

`caskroom/versions` is not intended to be used for all and any old versions you personally require for xyz project; casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.

I'd suggest [creating your own tap.](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)
