### ISSUE TITLE
LiteIcon Has Two Different Downloads

### ISSUE THREAD

**Issue by TGNYC** [caskroom/homebrew-cask#42144]
If you look on the [LiteIcon](https://freemacsoft.net/liteicon/) website, you see that there is a download for High Sierra and a download for Sierra. Is there a way for `brew cask install liteicon` to see what macOS version you are using, and download the correct version?

**Comment by vitorgalvao** [comment]
Yes, with a [simple conditional](https://github.com/caskroom/homebrew-cask/blob/0a6a0aff76fb63a55d39aa2adb9f571f19ce823a/Casks/mailfollowup.rb).

Care to try a PR?

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/42147
