### ISSUE TITLE
Error: Download failed on Cask 'minikube' 

### ISSUE THREAD

**Issue by avelino** [caskroom/homebrew-cask#42183]
```
λ ~/ brew cask install minikube
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-darwin-amd64

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443
Error: Download failed on Cask 'minikube' with message: Download failed: https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-darwin-amd64
λ ~/
```

ref https://github.com/Homebrew/homebrew-core/issues/21861

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
