### ISSUE TITLE
Outdated cask but cannot find link: gotomeeting

### ISSUE THREAD

**Issue by veloxo** [caskroom/homebrew-cask#42304]
[`gotomeeting`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/gotomeeting.rb)

`brew cask install gotomeeting` yields this error:
```
Downloading https://support.citrixonline.com/servlet/fileField?entityId=ka338000000L6kiAAC&field 
curl: (22) The requested URL returned error: 503 Service Unavailable
Error: Download failed on Cask 'gotomeeting' with message: Download failed: https://support.citrixonline.com/servlet/fileField?entityId=ka338000000L6kiAAC&field=Content__Body__s
```

Visiting the above URL in a browser shows a message about a GoToMeeting/LogMeIn merger and links to new website. Following ["Join a test session"](https://global.gotomeeting.com/join/594935493) leads to the new download link hosted at [launch.getgo.com](https://launch.getgo.com/launcher2/app/GoTo%20Opener.dmg).

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/42312
