### ISSUE TITLE
Feature request: alerts

### ISSUE THREAD

**Issue by OranguTech** [caskroom/homebrew-cask#42385]
### Description of feature/enhancement

Would like (option for) cask install to alert the user (terminal bell, perhaps other method) when prompting for user password.

### Justification

When downloading takes a long time, or installing multiple apps (especially when using cask upgrade https://github.com/buo/homebrew-cask-upgrade), I often start a batch, go do something else, and come back later to see it's waiting for privileged user credentials.

### Example use case

Installing something large, with a dependency, over a slow connection. "brew install BigApp", see it's estimated to take 15 minutes to install, switch to another app/window/desktop, connection gets a burst of speed, user checks in 15 minutes to see item 1, which is tiny, has been waiting for password for 14 minutes, blocking everything else.

Better outcome is (w/ an option ENV), app emits a term bell (or 3), maybe even emits a macos-specific alert.

**Comment by adidalal** [comment]
It's already a feature, see
https://github.com/caskroom/homebrew-cask/issues/19180#issuecomment-338096450
