### ISSUE TITLE
Checksum fails for Telegram-3.7.1-111991.app.zip

### ISSUE THREAD

**Issue by cauez0rd** [caskroom/homebrew-cask#42427]
Hello! When I try to download the Telegram cask, I get the following error: 

```
$ brew cask install telegram
==> Satisfying dependencies
==> Downloading https://osx.telegram.org/updates/Telegram-3.7.1-111991.app.zip
######################################################################## 100.0%
==> Verifying checksum for Cask telegram
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'telegram' does not match.

Expected: 37c0559a24a7906a4a0a4111c5f51ec4286d614906983ed1ba751f74b30f91b4
Actual:   abd54b3724b9f71b1599851bff92f7ae7ededfa10195f07e503ef19759e41c65
```

It looks like the checksum is wrong on the `telegram.rb` file, since I get the correct "actual" one from their file:
```
$ curl -s https://osx.telegram.org/updates/Telegram-3.7.1-111991.app.zip | shasum --algorithm 256
$ abd54b3724b9f71b1599851bff92f7ae7ededfa10195f07e503ef19759e41c65  -
```

PS: running `brew update` did not fix the sha256 checksum errors.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/42426
