### ISSUE TITLE
Checksum for Cask 'gpower' does not match.

### ISSUE THREAD

**Issue by crsh** [caskroom/homebrew-cask#42448]
I just tried to install the `gpower` cask, which failed with the following error:

~~~sh
brew cask install gpower
==> Satisfying dependencies
==> Downloading http://www.gpower.hhu.de/fileadmin/redaktion/Fakultaeten/Mathema
######################################################################## 100.0%
==> Verifying checksum for Cask gpower
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'gpower' does not match.

Expected: a905bd452edd6e0618ea5ab5dd16468010a92b676415a1fe57a9d0c9a7a2ac27
Actual:   f851661a55993cacf4f255ebba79c185bd1186667345fe3b2d8aefd0436a5321
File:     /Users/frederikaust/Library/Caches/Homebrew/Cask/gpower--3.1.9.3.zip

To retry an incomplete download, remove the file above.
~~~

I have confirmed that the error is not resolved by `brew update`. I downloaded the installation file manually from the [distributor website](http://www.gpower.hhu.de/), which gives me the same checksum:

~~~sh
openssl dgst -sha256 /Users/[username]/Downloads/GPowerMac_3.1.9.3.zip
SHA256(/Users/[username]/Downloads/GPowerMac_3.1.9.3.zip)= f851661a55993cacf4f255ebba79c185bd1186667345fe3b2d8aefd0436a5321
~~~

Unfortunately, they do not provide a reference checksum. I wonder whether this is simply a matter of an outdated checksum in the Cask-file or something more serious. Maybe @gtmgianni (#40624) knows more?

https://github.com/caskroom/homebrew-cask/blob/905f8a202fff0b7dd600c8f3d2948094290383e6/Casks/gpower.rb#L3

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by crsh** [comment]
Sorry about that. I missed the instructions and opened the issue via the inline-code link, which does not come with an issue template. I have updated the issue to reflect the requested structure and added the additional information.

**Comment by vitorgalvao** [comment]
> I have updated the issue to reflect the requested structure and added the additional information.

Thank you. [I’m already on it](https://github.com/caskroom/homebrew-cask/pull/42454). Since the app is not signed and the version did not change, I contacted the developer to ensure the change was legitimate.
