### ISSUE TITLE
Feature request: implement brew cask deps

### ISSUE THREAD

**Issue by sukucorp** [caskroom/homebrew-cask#42522]
### Description of feature/enhancement
Implement brew cask deps feature - e.g.
  brew cask deps-formula <app>
  brew cask deps-cask <app>

### Justification
Users will be able to determine which formula/casks are installed because of a dependency and hence can be safely removed when uninstalling applications.

**Comment by commitay** [comment]
```
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3881 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (138 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1120 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (10 casks)
```
4205 total Casks (excluding `fonts`)

57 Casks depend on another Cask

37 Casks depend on a Formula

**Comment by vitorgalvao** [comment]
I guess we could take a PR for this, but otherwise it’s not a priority (the stats, as pointed out by @commitay, do not make it worth it).

If you’re interested in submitting a PR and want to discuss this further, let us know.

**Comment by sukucorp** [comment]
What is a PR - Pull Request?

The numbers might be small, but it is important for those who like to keep their system lean by only keeping packages that are absolutely needed.

**Comment by vitorgalvao** [comment]
> What is a PR - Pull Request?

Yes.

> The numbers might be small, but it is important for those who like to keep their system lean by only keeping packages that are absolutely needed.

And since we’re working on this for free on our spare times, we need to prioritise, and that is simply not pressing enough.
