### ISSUE TITLE
Chromium: widevine plugin

### ISSUE THREAD

**Issue by tomfloyer** [caskroom/homebrew-cask#42777]
It looks like `widevine` plugin is not included with Chromium cask, which makes this browser unusable for services like Netflix etc.

According to [this discussion](https://bugs.chromium.org/p/chromium/issues/detail?id=429452#c16), it is possible to include `libwidevinecdm.so` from Chrome. In this case, Chromium version must match proper Chrome version [(source)](https://alien.slackbook.org/blog/watch-netflix-video-in-your-chromium-browser-this-time-for-real/).

I haven't tried this solution yet and i wonder if someone else needs this DRM feature or not.

**Comment by commitay** [comment]
I'm not sure I understand the purpose of the issue?

We don't compile `chromium`, we distribute a binary provided by upstream.

**Comment by tomfloyer** [comment]
@commitay Will it be OK if I create a repo with patched Chromium and 
make new cask for it?

**Comment by commitay** [comment]
We will refuse it unless it meets our requirements.

https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md

https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

I'd suggest [creating your own tap.](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)

**Comment by tomfloyer** [comment]
Thanks!
