### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by woj-tek** [caskroom/homebrew-cask#42798]
I would like to propose a small change/improvement - when updating a formula display both version of currently installed one and version of the one that it's installed (right now only the latter is displayed)

**Comment by commitay** [comment]
Can you please be a bit more specific what you mean by display both versions?

This is the current output from `upgrade`, we show the old version being moved back to `/Caskroom` and then being purged.

```
$ brew cask upgrade
==> Upgrading 1 outdated package, with result:
autodmg 1.8
==> Satisfying dependencies
==> Downloading https://github.com/MagerValp/AutoDMG/releases/download/v1.8/AutoDMG-1.8.dmg
Already downloaded: /Users/commitay/Library/Caches/Homebrew/Cask/autodmg--1.8.dmg
==> Verifying checksum for Cask autodmg
==> Starting upgrade for Cask autodmg
==> Moving App 'AutoDMG.app' back to '/usr/local/Caskroom/autodmg/1.7.3/AutoDMG.app'.
==> Moving App 'AutoDMG.app' to '/Applications/AutoDMG.app'.
==> Purging files for version 1.7.3 of Cask autodmg
🍺  autodmg was successfully upgraded!
```

**Comment by woj-tek** [comment]
You are right, and I made an error repository-wise: this ticket should go to the main homebrew project - mea culpa.

At any rate, looking at the output - there could be some improvements:
```
==> Upgrading 1 outdated package, with result:
vfuse 2.0.0 (from 1.0.6)
```
or
```
==> Upgrading 1 outdated package, with result:
vfuse 1.0.6 -> 2.0.0
```

**Comment by commitay** [comment]
https://github.com/Homebrew/brew/issues/2739#issuecomment-358281940

`brew cask outdated`
