### ISSUE TITLE
android-platform-tools mke2fs not linked

### ISSUE THREAD

**Issue by hellobbn** [caskroom/homebrew-cask#42806]
## Problem Description
The `brew cask install android-platform-tools` command will not link `mke2fs` to `/usr.local/bin`, which will cause problems when using fastboot command `fastboot -w`
```
wiping userdata...
/usr/local/bin/mke2fs failed with status 1
error: Cannot generate image for userdata
```
## My workaround
using command 
```
ln -s /usr/local/Caskroom/android-platform-tools/27.0.1/platform-tools/mke2fs /usr/local/bin/mke2fs
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/42830
