### ISSUE TITLE
Bad checksum for Noteplan and no idea what to do

### ISSUE THREAD

**Issue by ploum** [caskroom/homebrew-cask#42814]
Since a few days, it seems that NotePlan has an invalid checksum. But, as a user, I have no idea what I could do. Maybe it should be more explicit, like : post a ticket, contact the maintainer, wait a few days, etc.

brew cask install noteplan
==> Satisfying dependencies
==> Downloading https://rink.hockeyapp.net/api/2/apps/304b4477155e428780c345bcab69b380/?format=zip
######################################################################## 100.0%
==> Verifying checksum for Cask noteplan
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'noteplan' does not match.

Expected: 0427cc19a1e4c0705d1f0c8dc8fea720f474100c5f951ef4eaf79075a1582b9d
Actual:   3ff81f6baa6bf05cd855f44f5e4a02c920abebbd2ef34a10e31a8e2bb7f1f357
File:     /Users/ploum/Library/Caches/Homebrew/Cask/noteplan--1.6.18

To retry an incomplete download, remove the file above.

**Comment by gtmgianni** [comment]
https://github.com/caskroom/homebrew-cask/pull/42816

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error
