### ISSUE TITLE
Helping with the Pull Request Backlog

### ISSUE THREAD

**Issue by leipert** [caskroom/homebrew-cask#42897]
As you might have noticed, travis has [some problems](https://www.traviscistatus.com/incidents/c1s4dlyxd4lf) right now (https://www.traviscistatus.com/).

Is there anything we could help with manually verifying PRs in the mean time?

**Comment by vitorgalvao** [comment]
> Is there anything we could help with manually verifying PRs in the mean time?

An outside user can’t do manual verification, because that’d be the perfect opportunity for a malicious actor to submit a bad update to an app and get it merged.

Still, thank you for the offer.
