### ISSUE TITLE
Failed Casks

### ISSUE THREAD

**Issue by jledbetter460** [caskroom/homebrew-cask#42947]
[x] None of the templates provided matched my issue

Travis CI has canceled a little over one page of our PRs due to an overload of the system.
So... how should we deal with all of the failed PRs?
I suggest that we have an hour by hour basis where Travis takes in a certain number of failed casks so that we don't overload it.

Other methods are welcome!

**Comment by commitay** [comment]
> I suggest that we have an hour by hour basis where Travis takes in a certain number of failed casks so that we don't overload it.

Our small number of PRs won't overload Travis but thanks nonetheless for the suggestion.
