### ISSUE TITLE
Virtualbox requires clicking "Allow" in Security & Privacy, which doesn't work over Screen Sharing

### ISSUE THREAD

**Issue by wkoszek** [caskroom/homebrew-cask#43022]
#### General troubleshooting steps

I don't have issues with Cask.

There are a lot of issues with macOS / SIP / KEXT installation on macOS. VirtualBox is punished by that. The problem I've faced is that even through `brew cask install virtualbox` causes the "Security & Privacy" to have "Allow" button for the Oracle extensions, I couldn't click it. It appears broken over Screen Sharing, and in many other conditions people have:

https://github.com/tekezo/Karabiner-Elements/issues/1017
https://twitter.com/felix_schwarz/status/908690187219283970

I've tried several hacks, and this let me to send the events fine:

https://gist.github.com/wkoszek/691f41c6ba2edfacc6903d163868b348

Maybe it'd help other people to install Virtualbox via Cask seamlessly on OSX High Sierra. I'm thinking that maybe we could try to print out a link to this hack when the installation of Virtualbox fails?

**Comment by commitay** [comment]
It would be better to file bug reports with Apple to resolve any issues rather than provide "workarounds".

**Comment by commitay** [comment]
Because of the number of edge cases (screen sharing, other apps interfering, etc) we can't cover all possible cases. 

If we are providing "workarounds" and they don't work people will file issues with us.

**Comment by wkoszek** [comment]
I think the fact we have this thing recorded here may be helpful enough. It took me 2+hrs to solve that and go through all possible hacks. Wanted to save folks some time.
