### ISSUE TITLE
Provide brew.sh/analytics alike statistics please.

### ISSUE THREAD

**Issue by UniIsland** [caskroom/homebrew-cask#43045]
https://brew.sh/analytics/

I think it could be tremendously helpful if we keep record of the most installed apps.

Thanks.

**Comment by commitay** [comment]
[Homebrew-Cask is not a discoverability service](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md#homebrew-cask-is-not-a-discoverability-service)
