### ISSUE TITLE
virtualbox-extentions-pack-5.2.6-120293 is broken on Ubuntu guest

### ISSUE THREAD

**Issue by penoknowit** [caskroom/homebrew-cask#43072]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [X] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

virtualbox-extentions-pack-5.2.6-120293 is broken on Ubuntu guest.
I rolled back to 5.2.4 but it was a problem with resolution switching when booting the Ubuntu guest OS.

When checking this link:
https://github.com/caskroom/homebrew-cask/commits/master/Casks/virtualbox-extension-pack.rb
There is a build error for the extension-pack.

#### Output of your command with `--verbose --debug`

N/A

#### Output of `brew cask doctor`

N/A

**Comment by commitay** [comment]
> Important: The Guest Additions which come with VirtualBox 5.2.6 and 5.1.32 do not work properly on Linux guests with 3D enabled. Here are updated versions for 5.2.6 and 5.1.32.

https://www.virtualbox.org/wiki/Downloads
