### ISSUE TITLE
Latest freesmug-chromium revision returns 404 on download

### ISSUE THREAD

**Issue by dnivi3** [caskroom/homebrew-cask#43166]
I have `freesmug-chromium` installed and after updating cask this morning and running `brew cask outdated` it appeared that `freesmug-chromium` is out of date. I tried upgrading, but it results in the following error:

```
curl: (22) The requested URL returned error: 404 Not Found
==> Purging files for version 64.0.3282.119 of Cask freesmug-chromium
Error: Download failed on Cask 'freesmug-chromium' with message: Download failed: https://downloads.sourceforge.net/osxportableapps/Chromium_OSX_64.0.3282.119.dmg
```

So, it seems like whoever committed the newest `freesmug-chromium` update messed up and contributed a download link that is not available. It also appears that FreeSmug has _not_ released a new version yet: http://www.freesmug.org/chromium

It appears commit #43160 by @commitay is the culprit here.

**Comment by commitay** [comment]
> ... messed up and contributed a download link that is not available.

>  by @commitay is the culprit here.

1) I think your comments are rude.

2) I'm responding to this issue using `freesmug-chromium` `64.0.3282.119`. 
 It was the current version when the PR was merged, however it seems upstream has removed it.

PR reverting to the latest release available: https://github.com/caskroom/homebrew-cask/pull/43167

**Comment by dnivi3** [comment]
1. Sorry. It was not my intention to be rude, but I realise now that I was. It won't happen again. 

2. Odd that upstream removed it, maybe there is some issue with their build or something else?

Thanks for reverting!

**Comment by commitay** [comment]
Thanks for apologising, appreciated.

IIRC this has happened with `freesmug-chromium` a couple of times before, not really sure why. They will probably re-release fairly quickly.
