### ISSUE TITLE
Issue with latest Cerebro 0.3.2

### ISSUE THREAD

**Issue by browniebroke** [caskroom/homebrew-cask#43172]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Not an issue with Homebrew itself, there is [an issue open](https://github.com/KELiON/cerebro/issues/434) on Cerebro's repo. It was first reported on Ubuntu, but I have the same problem on the version from caskroom, as it was updated in the past month in #42315 .

As the issue on the other repo seems a bit stale, may I suggest that we revert the commit from the above PR to use Cerebro 0.3.1?

**Comment by CryoRenegade** [comment]
You can make a pr with the commit message `Revert cerebro.rb to 0.3.1`
