### ISSUE TITLE
I don't have an option to execute brew cask as sudo user

### ISSUE THREAD

**Issue by xabim** [caskroom/homebrew-cask#43204]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

In order to execute silent and unattended scripts I don't have an option to pass the `password` question and my script gets paused waiting for the password. 

I want to know if there is a possibility to run `sudo brew cask` with a option like `--run-as-sudo` and maybe a warning but let the script continue without asking the sudo password

If I remove the [root check](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L262-L277) the sudo command works, maybe we can relax this option and develop the above flag.

#### Output of your command with `--verbose --debug`

```
sudo brew cask reinstall teamviewer --verbose --debug
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.2-8-g65e940f
caskroom/homebrew-cask (git revision f5732; last commit 2018-01-26)
==> macOS
10.13.3
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3902 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by vitorgalvao** [comment]
```
man -P 'less -p SUDO_ASKPASS' brew-cask
man -P 'less -p --askpass' sudo
```

**Comment by xabim** [comment]
I don't see how that solution can give me the privilege to execute the script unattended

If I execute the command line and the installation of brew as root (with or without sudo) I can't make it work,  I don't see the ability to launch it without typing the sudo password at any time. 

I use an agent to execute those scripts, and can be done with or without privileges.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/19180.

Specifically https://github.com/caskroom/homebrew-cask/issues/19180#issuecomment-188251464 and https://github.com/caskroom/homebrew-cask/issues/19180#issuecomment-338148743.

**Comment by xabim** [comment]
Ok thanks, the issue there is that you have to type the password (at least one time), and we are deploying through an MDM tool, that executes scripts in a unattended way, I mean, you don't have the opportunity to type anything, and the other option is to write the admin pass in the script, and I found a big security issue there.

I only see two options:
1. Create a user, give NOPASSWD rights with sudo and execute all the commands with that user (but I see a security issue there)
2. Fork the repo and try to delete all the sudo checks, and install brew system-wide

Thanks for your time

**Comment by vitorgalvao** [comment]
Your particular case is pretty specific, so we’re likely not going to support that more than we already do in the pointed feature.
