### ISSUE TITLE
How to write cask for an install requiring manual download?

### ISSUE THREAD

**Issue by rbrtmrtn** [caskroom/homebrew-cask#43231]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I'd like to write a cask to install [Oracle SQL Developer](http://www.oracle.com/technetwork/developer-tools/sql-developer/overview/index.html). Unfortunately, the download requires a cookie and, therefore, can't be automated AFAIK. 

There's [another tap](https://github.com/InstantClientTap/homebrew-instantclient) that installs the Oracle Instant Client which got around this by asking the user to download a ZIP file manually and place it in `~/Library/Caches/Homebrew`. Here is their [download strategy](https://github.com/InstantClientTap/homebrew-instantclient/blob/master/Strategies/cache_wo_download.rb). Can I do something like this for casks? Is there an example somewhere?

Thanks!

#### Output of your command with `--verbose --debug`

```
n/a
```

#### Output of `brew cask doctor`

```
n/a
```

**Comment by commitay** [comment]
> the download requires a cookie and, therefore, can't be automated AFAIK

https://github.com/caskroom/homebrew-cask/blob/f127f6f5fceb0dc1aee5ef51c21e84ac2d9d9ce8/Casks/java.rb#L5-L8

**Comment by rbrtmrtn** [comment]
Hi @commitay, so I tried adding the `cookies` argument and I get a `403` along with this error:

```
Error: Download failed on Cask 'sqldeveloper' with message: Download failed: http://download.oracle.com/otn/java/sqldeveloper/sqldeveloper-17.4.0.355.2349-macosx.app.zip?AuthParam=1517079071_98baab2bf06b5c9f6b4f7da2839cc546
```

It looks like [others have had issues](https://github.com/caskroom/homebrew-cask/issues/16454) working with it as well.

That's why I was asking if there's a way to support manual downloads, that is -- downloading the ZIP file by hand and dropping it in the cache.

Thanks for any advice.

**Comment by rbrtmrtn** [comment]
Derp, I left my own cookie in the URL 😇

Disregard y'all.

**Comment by rbrtmrtn** [comment]
That cookie works for downloading Java, but apparently not for SQL Developer. I'm getting a `401`.
