### ISSUE TITLE
Cask microsoft-office leaves artefacts and running processes after uninstall

### ISSUE THREAD

**Issue by jgogstad** [caskroom/homebrew-cask#43356]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I did a quick install and uninstall of microsoft-office, restarted macOS and was surprised when Little Snitch warned me that Microsoft processes were accessing the internet. To recap:

```
brew cask install microsoft-office
brew cask uninstall microsoft-office
shutdown -r now
ps -ef | grep -i microsoft
```

#### Output of your command with `--verbose --debug`
```
  501   374     1   0  9:54PM ??         0:00.26 /Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/Microsoft AU Daemon.app/Contents/MacOS/Microsoft AU Daemon -checkForUpdates
    0   511     1   0  9:54PM ??         0:00.07 /Library/PrivilegedHelperTools/com.microsoft.autoupdate.helper
```

#### Output of `brew cask doctor`

```
Your system is ready to brew.
```

**Comment by commitay** [comment]
`microsoft-office` shares the "autoupdate" with other Casks so we don't remove it as part of `uninstall`. 

You can run `brew cask zap microsoft-office` to remove the autoupdater.

https://github.com/caskroom/homebrew-cask/blob/22d0f3997381a900f6a699c48b0527a3261b7e0f/Casks/microsoft-office.rb#L76-L77

[zap.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md#zap-stanza-purpose)
> Shared resources such as application updaters. Since shared resources may be removed, other applications may be affected by brew cask zap.
