### ISSUE TITLE
how to submit PRs for casks which have changed their download URL

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#43445]
An example will help here: `firetask` cask.

The current cask is for version 3.8.1. They have a newer cask available following those version rules for the URL for version 3.8.5 (http://downloads.firetask.com/firetask-mac/Firetask-Mac-3.8.5.zip).

However if you visit the website and try to download the trial, it will take you to a URL without versioning: http://downloads.firetask.com/firetask-mac/Firetask-Pro-Trial.dmg

So it seems they have changed their product offering, or at least their URL structure (and removed versions). What should I do if I wish to submit an update to the cask?

**Comment by brianmorton** [comment]
the `harvest` cask is another example:

via website latest download URL: https://www.getharvest.com/harvest/mac/Harvest.zip (no clear version?)
from homebrew: https://www.getharvest.com/harvest/mac/Harvest.2.1.2.zip (2.1.2)

however there is a possible updated version following the cask's URL convention:
https://www.getharvest.com/harvest/mac/Harvest.2.1.3.zip (2.1.3)

**Comment by brianmorton** [comment]
If I had to guess, the answer is going to be to submit a PR with the new URL format, however we will no longer know which version it is?

**Comment by brianmorton** [comment]
I may have answered my own issue but looking at the `0xed` cask:

```
cask '0xed' do
  version :latest
  sha256 :no_check

  url 'http://www.suavetech.com/cgi-bin/download.cgi?0xED.tar.bz2'
  name '0xED'
  homepage 'http://www.suavetech.com/0xed/'

  app '0xED.app'

  zap trash: [
               '~/Library/Caches/com.suavetech.0xED',
               '~/Library/Logs/0xED.log',
             ]
end
```

So I should just switch the version to be `:lastest` and submit the URL update?

**Comment by adidalal** [comment]
`firetask` looks to be on version 4.0.5 and there is no full version on their website, it's Mac App Store only. FireTask 3 is deprecated. So it will need to be removed - you can make a PR to do this. (You can use [mas](https://github.com/mas-cli/mas) instead if you want to automate the install of FireTask Pro).

`harvest` is at 2.1.3, though it looks like the appcast hasn't been update. You can submit that update using cask-repair, details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md) if needed. (should be something like `cask-repair -v 2.1.3 harvest`)
