### ISSUE TITLE
uninstall symlink remains

### ISSUE THREAD

**Issue by nickl-** [caskroom/homebrew-cask#4359]
I had a quick glance through the 301 issues returned from a search for uninstall and couldn't spot anything that appears related. I just want to make a quick note of this issue. Unfortunately this is as much as my availability allows at this point but should I find a gap I will gladly look into the problem some more.

## Problem 

Link remains in `~/Applications` after `uninstall` for apps installed with empty `link` attribute.

## Scenario 

I created a new cask, which initially had no value specified for the `link` attribute and upon installation a link to the extracted archive folder, the version number of the app, in the caskroom was created for the app under `~/Application/{{version number}}` instead of a link to the `.app`. After discovering the purpose of said `link` attribute I fixed the descriptor and proceeded to reinstall (uninstall + install) the app again.

The link to the extracted caskroom folder remained, was broken after uninstall but linked again after fresh installation.  Uninstalling apps with their link attribute configured do get cleaned up appropriately with the symlink deleted from `~/Applications` which leads me to believe the problem is related to the absence of a link attribute.

**Comment by vitorgalvao** [comment]
No longer relevant: #13201.
