### ISSUE TITLE
appcast checkpoints inaccurate?

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#43605]
I have been working on programmatic ways to detect casks with updates. One such attempt is to compare the existing cask's appcast checkpoint (which seems to be derived from the results of a curl) with a "current" checkpoint by using the existing cask's appcast URL and running 
```
brew cask _appcast_checkpoint --calculate <appcast_url>
```
In many cases the checkpoints differ even though the version has not been updated. This leads me to think one of two things has happened:

1. The checkpoint was not updated the last time the version was (such as [here](https://github.com/caskroom/homebrew-cask/pull/41189/commits/1862d61c729672ae50498a5675831489893b7b17))

or

2. The contents of the appcast URL are different than when the version was initially published.

So far it seems that option 1 is the case in the few I have inspected by hand.

**Should I submit PRs to fix these checkpoints?**

Below is a sample of the output from the first 100 casks in the repo (at least 6 had checkpoints that did not match). Note that I am only looking at checkpoints where the final segment of the URL's path includes a `.`, in an attempt to only look at files which are really meant to be RSS feeds/appcast. Many of the appcast URLs resolve to normal webpages which was ruining my signal-to-noise ratio.

```
$ python scan-appcast_checkpoint.py
#8 - 33-rpm
#28 - abricotine
#32 - accessmenubarapps
#38 - acslogo
#41 - actprinter
#46 - adguard
#47 - adium
#60 - adventure
#63 - aerial
  homepage: https://github.com/JohnCoates/Aerial ["'1.2'"]
  appcast url: https://github.com/JohnCoates/Aerial/releases.atom
    cur_checkpoint: d0bd6cf01ee5c8330fd7e45ca543efa9234db9ffbee041e04f5640462552fa6b
    new_checkpoint: d3c4f87a1de8f8195033eeae1af72347d66cd95287c10c45de629753cb55368b
#64 - aether
  homepage: http://getaether.net/ ["'1.2.3'"]
  appcast url: https://github.com/nehbit/aether-public/releases.atom
    cur_checkpoint: cfd1eeab50243955ebb52c7710fddeb08d8cbbfef751d0108273ca58e3ccbd38
    new_checkpoint: b36b36fc83cca60814f462b857348e755514caebaa7a01ba1506291e82576f9a
#65 - affinic-debugger
#67 - agenda
#69 - air-connect
#70 - air-video-server-hd
#72 - aircall
  homepage: https://aircall.io/ ["'1.4.11'"]
  appcast url: https://electron.aircall.io/update/osx/1.1.0
    cur_checkpoint: 4814444d1ab30b98414914c5c7b98c37b57ad7b66906b94efcd6b4d0e80cd234
    new_checkpoint: 1096db8aac4db31c49ad9668e50d6b2021ff21cfe4791a0c1a27364d752d4a82
#73 - airdisplay
  homepage: https://avatron.com/applications/air-display/ ["'3.0.3'"]
  appcast url: https://avatron.com/updates/software/airdisplay/appcast.xml
    cur_checkpoint: 53595c733dda80a38d6eff64e52efb3a8b763e7824eb3185df5d0a6958fa44f4
    new_checkpoint: c4770d45aa63630922f7fbfba99d915c8b056ea00ea98f9261b93095b85f383e
#76 - airflow
#77 - airfoil
#81 - airserver
  homepage: https://www.airserver.com/ ["'7.1.4'"]
  appcast url: https://www.airserver.com/downloads/mac/appcast.xml
    cur_checkpoint: cd46aa957c9db53a884c0697f2845528d7e28bf126a45d2f74bf892bbb4edc5b
    new_checkpoint: 770062f72e97f6d12b06344b44875322771ab07e50a452eaba35fb2b57b0b872
#84 - airtool
#85 - airy
#89 - alcatraz
  homepage: http://alcatraz.io/ ["'1.2.1'"]
  appcast url: https://github.com/alcatraz/Alcatraz/releases.atom
    cur_checkpoint: 81d85c5ef11fd873f22145b9045e372a7c8bf2f50687b29b950162116439830c
    new_checkpoint: af7edb52499fc7ebed8a0da14ae771035b198b704126787728307146d1f00372
#94 - alice
#99 - altair
#100 - alternote
```

**Comment by commitay** [comment]
> Should I submit PRs to fix these checkpoints?

Short answer, no. See https://github.com/caskroom/homebrew-cask/issues/38376

> The contents of the appcast URL are different than when the version was initially published.

This is usually the cause.

> I have been working on programmatic ways to detect casks with updates. 

Also see discussion in the above issue and https://github.com/caskroom/homebrew-cask/issues/41240

**Comment by vitorgalvao** [comment]
> > The contents of the appcast URL are different than when the version was initially published.
>
> This is usually the cause.

To expand on how we know this to be the case: the `checkpoint` is verified during `audit`, and Travis runs the `audit`, so this is definitely not an oversight.

Also, are you sharing your scripts for this anywhere?

**Comment by brianmorton** [comment]
The scripts I've been using are here:
https://github.com/brianmorton/cask-automation

**Comment by brianmorton** [comment]
Well after reading the other threads (thanks @commitay) I have to come to the conclusion that the checkpoint hash is not terribly useful at serving any purpose. If it is frequently outdated and can't be trusted to correctly represent a hash of the appcast for the current version, then why have it?

**Comment by gtmgianni** [comment]
> If it is frequently outdated and can't be trusted to correctly represent a hash of the appcast for the current version, then why have it?

If a cask's appcast checkpoint frequently changes without there being a version bump, we will remove the appcast for that particular cask. There are also, however, many casks with reliable appcasts, which is why I don't think we should remove the `appcast` stanza entirely.

**Comment by vitorgalvao** [comment]
> which is why I don't think we should remove the `appcast` stanza entirely.

@gtmgianni I think @brianmorton is asking about removing the `checkpoint`, not the whole `appcast` stanza.

> If it is frequently outdated and can't be trusted to correctly represent a hash of the appcast for the current version, then why have it?

@brianmorton Because when it is outdated is because the developers decided it should be (tipycally to release updates in waves), yet a user submitted an updated to us.

A system that auto-updates casks should rely on the `appcast` whenever possible, and if the `appcast` takes a few days to be updated compared to the version on the website, so be it, it’s not a big deal. Eventually such a system could dissuade users from submitting version bumps themselves to the casks (since they’ll be done automatically), eliminating the discrepancy.

**Comment by brianmorton** [comment]
@vitorgalvao I agree, but since the checkpoints change when the versions don't you can't really use the checkpoint to determine when there is an update, without customizing the logic for each cask (as most of the appcast's don't use a unified RSS format).

**Comment by vitorgalvao** [comment]
@brianmorton You already have to customize the logic for each cask anyway. There’s no system that’ll automatically work for all of them (as pointed out in the linked issues).

The trick is in making the system good enough that each needs as little customisation as possible.

**Comment by brianmorton** [comment]
@vitorgalvao I am actually working on a way to learn to read the xml structure on each fetch to determine version numbers without having to specify for each cask... but that still doesn't fix the problem with checkpoints.

**Comment by vitorgalvao** [comment]
Casks don’t exactly follow a predictable version pattern you can latch on to. `version`s are based on what’s most convenient for interpolation, not the actual app version. Even if you introduced a system that could understand every XML structure, that wouldn’t translate to correct cask versions.

And not even counting the fact not every appcast is XML, even the one that are are wildly inconsistent between them, and sometimes even amongst themselves.

Trying to be smart with casks is a really bad idea. It got us in bloody messes in the past. Especially when you can make general fetch methods and customise them for each cask in a single line (as per my example in another linked issue), trying to do it without intervention is entering a world of pain. There are too many exceptions; everything is an edge-case.

**Comment by brianmorton** [comment]
Alright well be that as it may, getting back to the original topic: should the checkpoints be automatically updated so that they are useful, or removed?

**Comment by vitorgalvao** [comment]
If you’re read https://github.com/caskroom/homebrew-cask/issues/38376, you’ll see there’s agreement on removing `checkpoint`. It has been talked about before.

But that is to be done after we get a better system in place. No one wants to remove them prematurely in favour of another solution, only to later discover the new solution isn’t appropriate and we have to readd `checkpoint`s to everything.

**Comment by brianmorton** [comment]
OK, thanks!
