### ISSUE TITLE
hbuilder udpate available (8.1.0 -> 9.0.1)

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#43670]
There is an update to this cask (`9.0.1`), however I can't (well... won't) send a PR because downloading the cask from the servers in China would take years. I don't have a VPS or any remote box located in the region, but if somebody else does and wants to submit the PR go nuts.

Alternatively, I'm not sure if detailed stats are kept on cask downloads, but maybe just remove this cask is the way to go? It is already seriously out of date.

Maybe @miccal, the person submitting the most recent few update PRs would care to be involved.

**Comment by vitorgalvao** [comment]
It’s taking less than 3s for each 1% for me. Updating it now.
