### ISSUE TITLE
Feature request: Specify name for installed product

### ISSUE THREAD

**Issue by saagarjha** [caskroom/homebrew-cask#43891]
### Description of feature/enhancement
I'd like to see an option to customize the name of an installed application, so that I don't have to use the default name. I couldn't figure out if this already exists, so if this already a thing I can do, could you point me instructions on how to do this?

### Justification
Some casks aren't named as well as I'd like; for example, they use a different name than the standard installer so I end up with two copies when running autoupdates, or they append a version number to the app's name so I have to go and delete the old one when running upgrades. For others, I'd like to manually name it so it doesn't conflict with something I already have.

### Example use case
If I have `some-cask` which installs "SomeCask.app", I'd like to see an option when installing, such as `brew cask install some-cask --name AnotherName.app` which will name the app "AnotherName.app" instead of "SomeCask.app".

**Comment by commitay** [comment]
This isn't some you can do unless you [create your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for the Casks you wish to rename.

Allowing users to rename Casks will cause more problems then it will solve.

>they use a different name than the standard installer so I end up with two copies when running autoupdates, or they append a version number to the app's name so I have to go and delete the old one when running upgrades.

Can you elaborate further on this? Which Casks are you having issues with?

**Comment by saagarjha** [comment]
Off the top of my head, [Android Studio Preview](https://github.com/caskroom/homebrew-versions/blob/master/Casks/android-studio-preview.rb) adds a version number to the installed app, which causes it to leave the old one untouched when upgrading, and [Eclipse (for Java programmers)](https://github.com/caskroom/homebrew-cask/blob/master/Casks/eclipse-java.rb) uses the name "Eclipse Java" to prevent collisions with other Eclipses. However, since I don't use any of the other ones, I'd just like it to be called "Eclipse".

**Comment by commitay** [comment]
> Android Studio Preview adds a version number to the installed app, which causes it to leave the old one untouched when upgrading

When running `brew cask upgrade`?

> Eclipse (for Java programmers) uses the name "Eclipse Java" to prevent collisions with other Eclipses. However, since I don't use any of the other ones, I'd just like it to be called "Eclipse".

It was renamed because some users do use the other Eclipse apps. Nothing we can you about this unless you have your own tap.

**Comment by saagarjha** [comment]
> When running `brew cask upgrade`?

No, apparently. Looks like this occurred because I was running a reinstall, which would leave the old Android Studio and install a new one.

> It was renamed because some users do use the other Eclipse apps. Nothing we can you about this unless you have your own tap.

I guess…I'll just close this for now, but if I have any other issues I'll report them here.
