### ISSUE TITLE
Invalid SSL - mediathekview

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#43963]
mediathekview 13.0.6
https://mediathekview.de/

![image](https://user-images.githubusercontent.com/1434096/36178096-afdde728-10cc-11e8-8aa1-c08d05ead4ad.png)

Using Let's Encrypt / certbot and probably has the renew cert cron erroring out or something.

What's the process here? Only discovered because this was the first time my URL sniffer encountered this so I looked into it.

**Comment by commitay** [comment]
> What's the process here?

Contact them and if it isn't fixed in a couple of weeks we would delete the cask.

**Comment by brianmorton** [comment]
Cert has been fixed
![image](https://user-images.githubusercontent.com/1434096/36325535-f3a33804-130c-11e8-82c8-f68e8549c165.png)
