### ISSUE TITLE
`brew cask outdated` does not work anymore

### ISSUE THREAD

**Issue by GhostGambler** [caskroom/homebrew-cask#44028]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`$ brew cask outdated` does not work anymore.

#### Output of your command with `--verbose --debug`

```
$ brew cask outdated --verbose --debug
==> Checking update info of Cask libreoffice
==> Checking update info of Cask virtualbox
```
```
$ brew cask outdated docker --verbose --debug
==> Checking update info of Cask docker
```
```
$ brew cask info docker --verbose --debug
==> Getting info for Cask docker
docker: 17.12.0-ce-mac49,21995
https://www.docker.com/community-edition
/usr/local/Caskroom/docker/17.06.0-ce-mac19,18663 (64B)
==> [user, repo, token] might be [caskroom, cask, docker]
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/docker.rb
==> Names
Docker Community Edition
Docker CE
==> Artifacts
Docker.app (App)
==> Printing caveats
```
I guess the output of `info` shows me that 17.12 is the most recent version, but 17.06 is installed? Then I'd expect `cask outdated` to list docker as outdated package.

Docker is definitely not the current version:
```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

This problem is also not restricted to docker. I encountered the same issue with libreoffice.

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.4-40-g988e805
caskroom/homebrew-cask (git revision f6cbd1; last commit 2018-02-15)
==> macOS
10.13.3
==> SIP
Enabled
==> Java
1.8.0_112
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 224.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3917 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by gtmgianni** [comment]
@GhostGambler This is not a bug.

Casks with the `auto_updates true` stanza (e.g. `docker` and `libreoffice`) are ignored by default by the `brew cask outdated` command. If you want those casks to be outputted as well, use `brew cask outdated --greedy`.

You can also use the `--greedy` option for the `brew cask upgrade` command – it exhibits the same behaviour.

**Comment by GhostGambler** [comment]
Ah, ok. Thanks!

**Comment by Yann-R** [comment]
OK for the casks with `auto_updates true`

But, personally I often encounter cases where some Casks have specific versions newer that the ones installed, and that are not signalled by `brew cask outdated`

For instance, today:
`brew cask outdated` does not reveal `opera` nor `google-chrome` for me (see commands hereafter)
```
$ brew cask outdated opera
$ brew cask outdated google-chrome
```
Whereas there are newer cask versions ready to replace the ones installed on my system (see hereafter)
```
$ brew cask info opera
opera: 51.0.2830.40
https://www.opera.com/
/opt/homebrew/Caskroom/opera/51.0.2830.34 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/opera.rb
==> Name
Opera
==> Artifacts
Opera.app (App)

$ brew cask info google-chrome
google-chrome: 64.0.3282.186
https://www.google.com/chrome/
/opt/homebrew/Caskroom/google-chrome/64.0.3282.167 (2 files, 77.5KB)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-chrome.rb
==> Name
Google Chrome
==> Artifacts
Google Chrome.app (App)
```

**Comment by Yann-R** [comment]
1. OK for the `--greedy` option that outputs those casks as well.
2. But, then it outputs also all installed casks containing `version :latest`.

Isn't there a way to distinguish those two cases? Because they are not in the same status at all:

- case 1 is a cask where you are SURE there is a newer version (but `brew cask outdated` just ignored to tell you because of `auto_updates true`) => you can conclude that upgrading is useful.
- case 2 is a cask where there are a newer version or not => you cannot conclude anything.
