### ISSUE TITLE
Transition RDM from DMG to source build

### ISSUE THREAD

**Issue by jasonab** [caskroom/homebrew-cask#44078]
The RDM cask is currently on version 0.8.3, the last version for which a DMG was produced. Currently, RDM only provides DMGs to subscribers, and provides source code to non-subscribers.

It would be nice if brew(cask) could follow the instructions to build and install RDM without having to do this manually.

http://docs.redisdesktop.com/en/latest/install/#build-from-source

**Comment by commitay** [comment]
They do still seem to have a couple of [pre-release dmgs](https://github.com/uglide/RedisDesktopManager/releases/tag/0.9.0-alpha4) but we don't usually have pre-release stuff in the main repo when there is also a stable version (we just can't access it).

> It would be nice if brew(cask) could follow the instructions to build and install RDM without having to do this manually.

Cask doesn't build from source, we only distribute what upstream provides.

In this case as the available download is over two years old we would probably remove the Cask so users aren't stuck with an old version.

**Comment by jasonab** [comment]
Could/should this be moved to standard brew for source-based building?

**Comment by commitay** [comment]
https://docs.brew.sh/Acceptable-Formulae.html

> Stuff that builds an .app
Don’t make your formula build an .app (native macOS Application); we don’t want those things in Homebrew. Encourage upstream projects to build and support a .app that can be distributed by Homebrew Cask (and used without it, too).

**Comment by jasonab** [comment]
Ok, looks like RDM has put themselves into a netherworld then. Appreciate the response.
