### ISSUE TITLE
devonthink-pro-office should set auto_updates true

### ISSUE THREAD

**Issue by jimwise** [caskroom/homebrew-cask#44219]
#### General troubleshooting steps

- [X ] I have retried my command with `--force` and the issue is still present.
- [ X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X ] None of the templates was appropriate for my issue, or I’m not sure.
- [X ] I ran `brew update-reset && brew update` and retried my command.
- [X ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

devonthink-office-pro auto-updates, and should thus set `auto_updates true`
#### Output of your command with `--verbose --debug`

==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Checking update info of Cask blockblock
==> Checking update info of Cask chefdk
==> Checking update info of Cask citrix-receiver
==> Checking update info of Cask crashplan
==> Checking update info of Cask devonthink-pro-office
devonthink-pro-office (2.9.15) != 2.9.17
==> Checking update info of Cask emacs
==> Checking update info of Cask firefox
==> Checking update info of Cask gpgtools
==> Checking update info of Cask java
==> Checking update info of Cask little-flocker
==> Checking update info of Cask little-snitch
==> Checking update info of Cask mactex
==> Checking update info of Cask marathon
==> Checking update info of Cask marathon-infinity
==> Checking update info of Cask marathon2
==> Checking update info of Cask microsoft-office
==> Checking update info of Cask quicksilver
==> Checking update info of Cask racket
==> Checking update info of Cask scansnap-manager-ix500
==> Checking update info of Cask tex-live-utility
==> Checking update info of Cask vassal
==> Checking update info of Cask virtualbox
==> Checking update info of Cask virtualbox-extension-pack

#### Output of `brew cask doctor`

==> Homebrew-Cask Version
Homebrew-Cask 1.5.4-75-g14d54ed
caskroom/homebrew-cask (git revision 885c0; last commit 2018-02-22)
==> macOS
10.13.3
==> SIP
Enabled
==> Java
9.0.4
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (3 files, 162MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3919 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (143 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (171 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/44217
