### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by hasahmed** [caskroom/homebrew-cask#44221]
This is a feature request.

Sometimes there are multiple version of the same program, and I was thinking that it would be cool to have an --options command that would allow you to select the version. For instance [godot engine](godotengine.org) has a version with the mono C# runtime, but of course it is a different cask. --options would allow for there to be a switch between the casks without actually having to define a different cask.rb file.

**Comment by commitay** [comment]
This isn't something we want to have because of a couple of reasons.

- It would only be useful for a limited amount of Casks.

- Different "editions" of the same app often require different methods for installing and uninstalling.

- It's easier to maintain separate Casks.
