### ISSUE TITLE
VirtualBox - Download Securely?

### ISSUE THREAD

**Issue by seandenigris** [caskroom/homebrew-cask#44280]
The dmg is available via HTTPS e.g. https://download.virtualbox.org/virtualbox/5.1.32/VirtualBox-5.1.32-120294-OSX.dmg. 

Any reason not to use it?

Currently, [the cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox.rb) uses `http://download.virtualbox.org/virtualbox/#{version.sub(%r{-.*}, '')}/VirtualBox-#{version}-OSX.dmg`

**Comment by vitorgalvao** [comment]
There might’ve been a reason, like the HTTPS link redirecting to the HTTP one (in that case we’d rather keep the HTTP link directly, so as to not give a false sense of security), but I’ve tested now and see that isn’t the case at the moment.

Fixing in https://github.com/caskroom/homebrew-cask/pull/44281. Thank you for the report.

**Comment by seandenigris** [comment]
Thanks! Yes, I did check for a redirect - sorry I should've mentioned that :/
