### ISSUE TITLE
License Management

### ISSUE THREAD

**Issue by mAAdhaTTah** [caskroom/homebrew-cask#4440]
This isn't really an issue, so feel free to close if this isn't the appropriate place for this (maybe [Mackup](https://github.com/lra/mackup) is a better place to ask?).

A big part of my use of cask is to automate the set up of new machines, and I have a set of scripts that does that for me. However, the issue I'm running into now is there are a number of apps that have licenses, and I have no way of automating the license set up.

How are others handling this? Is there a way of automating the licensing step of the set up phase?

**Comment by vitorgalvao** [comment]
Closing, as we likely won’t be able to implement this.
