### ISSUE TITLE
Outdated cask: XLD

### ISSUE THREAD

**Issue by lolc** [caskroom/homebrew-cask#44451]
['XLD'] https://github.com/caskroom/homebrew-cask/blob/master/Casks/xld.rb

Cask has the latest version, 2017.07.29, but checksum fails.

> Error: Checksum for Cask 'xld' does not match.
>
>Expected: 0ef55204816e7b52fe276dccd29253947be7b14da29e4ae1a505496174eb194a
>Actual:   7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
>File:     /Users/lolc/Library/Caches/Homebrew/Cask/xld--2017.07.29.dmg

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/issues/44453#issuecomment-369418964
