### ISSUE TITLE
lastpass: invalid post-install instructions

### ISSUE THREAD

**Issue by Nowaker** [caskroom/homebrew-cask#44497]
#### General troubleshooting steps

- [ ] **N/A** I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] **N/A** I ran `brew update-reset && brew update` and retried my command.
- [ ] **N/A** I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Invalid post-install instructions. The message should read:
```
  '/usr/local/Caskroom/lastpass/latest/LastPass Installer/LastPass Installer.app'
```
It now reads:
```
  '/usr/local/Caskroom/lastpass/latest/LastPass Installer.app'
```

Details:
```
==> Downloading https://lastpass.com/download/cdn/lpmacosx.zip
######################################################################## 100.0%
==> No checksum defined for Cask lastpass, skipping verification
==> Installing Cask lastpass
To complete the installation of Cask lastpass, you must also
run the installer at

  '/usr/local/Caskroom/lastpass/latest/LastPass Installer.app'
🍺  lastpass was successfully installed!
brew cask install lastpass  12.27s user 8.64s system 22% cpu 1:34.44 total
nowaker@nwkr-mbp ~ % open '/usr/local/Caskroom/lastpass/latest/LastPass Installer.app'
The file /usr/local/Caskroom/lastpass/latest/LastPass Installer.app does not exist.
1 nowaker@nwkr-mbp ~ % ls -la /usr/local/Caskroom/lastpass/latest/                                                                                                :(
total 0
drwxr-xr-x 3 nowaker admin  96 Mar  2 10:55  .
drwxr-xr-x 4 nowaker admin 128 Mar  2 10:55  ..
drwxr-xr-x 4 nowaker staff 128 Mar  2 10:55 'LastPass Installer'
nowaker@nwkr-mbp ~ % ls -la /usr/local/Caskroom/lastpass/latest/LastPass\ Installer
total 0
drwxr-xr-x 4 nowaker staff 128 Mar  2 10:55  .
drwxr-xr-x 3 nowaker admin  96 Mar  2 10:55  ..
drwxr-xr-x 3 nowaker staff  96 Nov 16 16:35 'LastPass Installer.app'
drwxr-xr-x 3 nowaker staff  96 Nov 16 16:34  Uninstaller.app
```

#### Output of your command with `--verbose --debug`

N/A

#### Output of `brew cask doctor`

N/A

**Comment by vitorgalvao** [comment]
Thank you.

https://github.com/caskroom/homebrew-cask/pull/44506
