### ISSUE TITLE
Source not there and cannot find it: NitroShare

### ISSUE THREAD

**Issue by cesarandreu** [caskroom/homebrew-cask#44680]
NitroShare: https://github.com/caskroom/homebrew-cask/blob/master/Casks/nitroshare.rb

Trying to perform a regular install fails:

```
Error: It seems the App source '/usr/local/Caskroom/nitroshare/0.3.4/NitroShare.app' is not there.
```

Using `brew cask fetch nitroshare` I downloaded the dmg. Opening it with Finder shows `NitroShare.app`. However, navigating there there with the terminal shows `nitroshare.app`.

Using `brew cask edit nitroshare` and updating the app value to `nitroshare.app` allows the installation to succeed. However, after installation opening Applications in Finder shows `NitroShare.app`, while using the terminal shows `nitroshare.app`. That seemed weird, so I figured opening an issue would be safer.

I'm on macOS Version 10.13.3 and I'm using a case-sensitive APFS drive.

**Comment by vitorgalvao** [comment]
Next time, please fill the template. Not only does it teach you to fix this, it tells you that if you ignore it, your issue won’t be looked at.
