### ISSUE TITLE
brew cask install: 'No block given' error

### ISSUE THREAD

**Issue by stffndtz** [caskroom/homebrew-cask#44694]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Since today I am unable to install any kegs and brew cask fails with a "No blocks given" warning on my machine (macOS High Sierra /w latest updates)

#### Output of your command with `--verbose --debug`

```
$ brew cask install atom --verbose --debug
Error: no block given
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `tap'
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:123:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli.rb:15:in `block in <class:CLI>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:213:in `block in process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `select'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:136:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
Error: no block given
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `tap'
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:123:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli.rb:15:in `block in <class:CLI>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:213:in `block in process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `select'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:136:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by commitay** [comment]
Please post `brew cask doctor`

**Comment by stffndtz** [comment]
Thank you for reaching out so quickly!

Here's the output:

`
$ brew cask doctor
Error: no block given
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `tap'
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:123:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli.rb:15:in `block in <class:CLI>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:213:in `block in process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `select'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:136:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
`

I have limited knowledge about ruby but I was wondering if it might be related to rbenv oder global ruby version settings?

**Comment by vitorgalvao** [comment]
1. What is the output of `brew --version`?
2. Can you install any `brew` (not `cask`) package?

**Comment by stffndtz** [comment]
1. here it is:

```
Homebrew 1.5.9
Homebrew/homebrew-core (git revision aa619b; last commit 2018-03-09)
```

2. yes, installing brews works as expected without any issues

**Comment by commitay** [comment]
```
>>> brew update
Updated Homebrew from 83b8c6cc to df1fb59d.
Error: no block given
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `tap'
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:143:in `default_formula'
```

Looks like we have the same thing happening on CI for the last day.
https://github.com/caskroom/homebrew-cask/pull/44668 is the last PR without the error.

**Comment by stffndtz** [comment]
I just ran brew update and here's the current output of brew --version

```
$ brew --version
Homebrew 1.5.9
Homebrew/homebrew-core (git revision fba87; last commit 2018-03-09)
```

Still running into the same error.

If there is anything I can do to help - let me know. And thank you for your help so far, I really appreciate your efforts!

**Comment by atom-x** [comment]
i'm also having the same issue

`
> brew --version                                                                                                                                                                                        
Homebrew 1.5.10
Homebrew/homebrew-core (git revision 537a8; last commit 2018-03-11)

> brew cask                                                                                                                                                                                             
Error: no block given
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `tap'
/usr/local/Homebrew/Library/Homebrew/utils.rb:112:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:123:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli.rb:15:in `block in <class:CLI>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `block (3 levels) in process_arguments'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:213:in `block in process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `select'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:211:in `process_options'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:136:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
`

**Comment by commitay** [comment]
This is fixed in master by https://github.com/Homebrew/brew/pull/3909

You can run this to switch to master branch.
```
$ export HOMEBREW_DEVELOPER=1

$ brew update
```
