### ISSUE TITLE
Wrong download location for cask "chainsaw"

### ISSUE THREAD

**Issue by markus-s24** [caskroom/homebrew-cask#44738]
I tried to install the cask "chainsaw", but it complains that it cannot download "https://logging.apache.org/chainsaw/webstart/chainsaw.dmg". It seems, that the download location changed.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/44739
