### ISSUE TITLE
zpipe module request

### ISSUE THREAD

**Issue by yehgdotnet** [caskroom/homebrew-cask#44822]
Recently, I find it to difficult to unzip zlib file.   Found only two ways, 1) do python code 2)  use zpipe.c

I found this pull request before but I can't find it in brew cask. 

https://github.com/Homebrew/legacy-homebrew/pull/21947

**Comment by vitorgalvao** [comment]
Since a lot of our code is now shared with HB, this should be asked for there. I don’t really see the point, though, we don’t have casks in that situation.
