### ISSUE TITLE
Feature request: Ability to pin a cask so that it doesn't upgrade

### ISSUE THREAD

**Issue by echosa** [caskroom/homebrew-cask#44914]
### Description of feature/enhancement

With straight `brew`, we can `brew pin <formula>` in order to prevent that formula from ever upgrading until it is unpinned. It'd be great to have this same ability for `brew cask`, something like `brew cask pin <formula>`.

### Justification

Sometimes, we don't want to upgrade a particular program. Pins allow us to avoid doing so.

### Example use case

`$ brew cask pin vagrant`
`$ brew cask pin dwarf-fortress`
etc.

**Comment by usmonster** [comment]
(See also old discussion on Homebrew/brew#1523.)

**Comment by bretonics** [comment]
I agree, this needs to exist. Come casks, say mactex, are massive and it would be beneficial to pin such casks. Other times, keeping a particular version of say `java` is also desirable.

**Comment by vitorgalvao** [comment]
There’s no way we can enforce `pin`, because a considerable amount of casks auto update and we neither have control over that, nor do we want to — it’s one of the goals of HBC that the results of our installation is as similar as possible to the results of a manual installation.
