### ISSUE TITLE
Dead app: mini-vmac

### ISSUE THREAD

**Issue by tebruno99** [caskroom/homebrew-cask#44926]
['mini-vmac']
https://github.com/caskroom/homebrew-cask/blob/master/Casks/mini-vmac.rb

404 Error:
http://www.gryphel.com/d/minivmac/minivmac-3.4.1/minivmac-3.4.1-imch.bin.tgz

Correct URL & Latest Version:
http://www.gryphel.com/d/minivmac/minivmac-3.5.8/minivmac-3.5.8-mc64.bin.tgz

```brew cask install mini-vmac
==> Satisfying dependencies
==> Downloading http://www.gryphel.com/d/minivmac/minivmac-3.4.1/minivmac-3.4.1-imch.bin.tgz

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'mini-vmac' with message: Download failed: http://www.gryphel.com/d/minivmac/minivmac-3.4.1/minivmac-3.4.1-imch.bin.tgz
```

**Comment by commitay** [comment]
From the issue template:

> - [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.

https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#curl-error

https://github.com/caskroom/homebrew-cask/pull/44927

**Comment by tebruno99** [comment]
Yep, I followed the instructions that the guide sent me through. Not sure what you want from me. I even followed the template it supplied for me and removed the template text as it requestion.

Whatever, won't try this again thanks.
