### ISSUE TITLE
Outdated cask: retroarch

### ISSUE THREAD

**Issue by valepert** [caskroom/homebrew-cask#44939]
[`retroarch`] 1.7.1

https://buildbot.libretro.com/stable/1.7.1/apple/osx/x86_64/RetroArch.dmg have different sha256:

Error: Checksum for Cask 'retroarch' does not match.

Expected: c47014c9cf5f7919d6a67300c6af13e5eaa14ecdffc7cae7f68e0300413360c7
Actual:   936f658c543eeeeb822113ef224200ab41cd2b5d1d91509c232fd6e73e6294ad

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/44777
