### ISSUE TITLE
brew cask install freezes on hdiutil imageinfo

### ISSUE THREAD

**Issue by badrange** [caskroom/homebrew-cask#44969]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I wanted to use brew cask to upgrade Google Chrome, but it froze. Now I have removed it, and I am still unable to install - it freezes, and it freezes at this stage: 

`==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/bernt/Library/Caches/Homebrew/Cask/google-chrome--65.0.3325.162.dmg"]`

#### Output of your command with `--verbose --debug`

```
⇒  brew cask --verbose --debug install google-chrome
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
Already downloaded: /Users/bernt/Library/Caches/Homebrew/Cask/google-chrome--65.0.3325.162.dmg
==> Downloaded to -> /Users/bernt/Library/Caches/Homebrew/Cask/google-chrome--65.0.3325.162.dmg
==> Verifying download
==> Determining which verifications to run for Cask google-chrome
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask google-chrome
==> SHA256 checksums match
==> Installing Cask google-chrome
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/bernt/Library/Caches/Homebrew/Cask/google-chrome--65.0.3325.162.dmg"]```

#### Output of `brew cask doctor`

```
⇒  brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.10-41-g058dad6
caskroom/homebrew-cask (git revision 1efff; last commit 2018-03-19)
==> macOS
10.13.3
==> SIP
Enabled
==> Java
1.8.0_92
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 65.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3941 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
⇒  brew tap
caskroom/cask
homebrew/boneyard
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/php
homebrew/science
homebrew/services
homebrew/versions
osgeo/osgeo4mac
petere/postgresql
```

**Comment by commitay** [comment]
Please post the output of `diskutil list | grep -iB4 chrome`

**Comment by badrange** [comment]
I was also able to install Firefox. I think this issue can be closed - after somebody has seen my final comment: 

It might be worth considering adding "I have rebooted my computer" to the issue submission checklist. It is sad that it might be necessary, but it might save you guys some time..
