### ISSUE TITLE
add to DSL: conflicts_with :formula

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#4497]
as discussed in #4451 .

**Comment by vitorgalvao** [comment]
Commenting to let maintainers know [@jawshooah wishes to take a first stab at implementing this](https://github.com/caskroom/homebrew-cask/issues/9202#issuecomment-71291884).

**Comment by rolandwalker** [comment]
This issue was a todo for the DSL, and should have been closed.

It may not make much sense, but I was tracking the DSL and underlying functionality separately, as they were running on separate tracks for quite some time.
