### ISSUE TITLE
Java 10

### ISSUE THREAD

**Issue by giacgbj** [caskroom/homebrew-cask#45031]
It would be nice to have a cask for "java9" since "java" now installs Java 10.

Moreover, in my opinion, it would be better to have also a "java10" cask because I'd like to avoid a generic "java" which installs the latest one: today I risked to install Java 10 when I upgraded "java".

**Comment by commitay** [comment]
http://www.oracle.com/technetwork/java/eol-135779.html

> Java SE 9 will be a short term release, and users should immediately transition to the next release

**Comment by figuremery** [comment]
Having issues with java10 with kotlin koans / gradle. Unable to downgrade to java9 :(

**Comment by commitay** [comment]
Java 9 isn't available to download from Oracle.

http://www.oracle.com/technetwork/java/javase/overview/index.html

**Comment by mtneug** [comment]
Java 9 has moved into the archive: <http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html>.

**Comment by ldeck** [comment]
Can this be reopened? Despite Oracle's directive various systems/projects haven't been updated yet.

We still have java6 and java8 casks after all. There probably could be a java7 one too.

@mtneug shows where it can be downloaded from.

**Comment by commitay** [comment]
`java7` and `java9` require an Oracle account to access their downloads.
