### ISSUE TITLE
implement travis-buddy?

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#45091]
Automatically adds comments to PRs based on what went wrong in travis.
https://github.com/bluzi/travis-buddy

Thoughts?

**Comment by vitorgalvao** [comment]
Sounds good. [This configuration](https://github.com/bluzi/travis-buddy#disable-success-message) looks best.

**Comment by commitay** [comment]
👍 Comments on contributor PRs encouraging them to fix errors.

👎 Some errors aren't fixable and the comment may lead to the contributor trying to fix them anyway.

👎 Notification spam.

**Comment by brianmorton** [comment]
Anything I can do to help make this happen?

**Comment by vitorgalvao** [comment]
I’ll add another 👍: we (maintainers) know what’s wrong as soon as we open the issue; no need to go into the code or Travis.

I think this is worth a try. If we find it annoying, it’s just as easy to remove.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/45272
