### ISSUE TITLE
Cannot install java with brew cask

### ISSUE THREAD

**Issue by CoolTomatos** [caskroom/homebrew-cask#45147]
Running `brew cask install java` I got an error

>Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/10+46/76eac37278c24557a3c4199677f19b62/jdk-10_osx-x64_bin.dmg

**Comment by commitay** [comment]
Oracle download links for all versions of Java seem to be broken at the moment. 

Trying to download from the Oracle website will also 404.

**Comment by ggsp** [comment]
Seems like downloads are [working again](https://twitter.com/java/status/977602707291713536).

**Comment by CoolTomatos** [comment]
@ggsp yes, I will close this issue.
