### ISSUE TITLE
pkg: allow_untrusted

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#45146]
I've removed `allow_untrusted` from the Casks that did not require it:

https://github.com/caskroom/homebrew-cask/pull/45136 (Updated), https://github.com/caskroom/homebrew-cask/pull/45137, https://github.com/caskroom/homebrew-cask/pull/45138, https://github.com/caskroom/homebrew-cask/pull/45139, https://github.com/caskroom/homebrew-cask/pull/45140, https://github.com/caskroom/homebrew-cask/pull/45141, https://github.com/caskroom/homebrew-cask/pull/45143, https://github.com/caskroom/homebrew-cask/pull/45144, https://github.com/caskroom/homebrew-drivers/pull/367

Removed one that couldn't be installed: https://github.com/caskroom/homebrew-cask/pull/45142

Removed another that requires an email signup: https://github.com/caskroom/homebrew-cask/pull/45145

Remaining Casks with `allow_untrusted`:
```
homebrew-cask/Casks/nc-dns-updater.rb: download link is dead

homebrew-cask/Casks/hosts.rb
homebrew-cask/Casks/rosetta-stone-totale.rb
homebrew-cask/Casks/visualjson.rb

homebrew-drivers/Casks/canon-pixma-mx510-scanner-driver.rb
homebrew-drivers/Casks/konica-minolta-bizhub-c450-driver.rb
homebrew-drivers/Casks/wd-my-cloud.rb

homebrew-versions/Casks/adobe-photoshop-lightroom441.rb
homebrew-versions/Casks/adobe-photoshop-lightroom571.rb

```
A couple are relatively new Casks (added in the last year) that had the `allow_untrusted` option set when they were added. Most are old without the possibility of a new version that would allow us to remove the `allow_untrusted` option.

I think we should remove all of them and enforce a policy of disallowing `allow_untrusted` in Caskroom.

**Comment by vitorgalvao** [comment]
Sounds good to me.

**Comment by commitay** [comment]
Closing in favour of open PRs.
