### ISSUE TITLE
The Unarchiever cask - 404

### ISSUE THREAD

**Issue by faradaytrs** [caskroom/homebrew-cask#45289]
Trying to update: 
==> Upgrading the-unarchiver to 3.11.5,118:1522141689
==> Satisfying dependencies
==> Downloading https://dl.devmate.com/cx.c3.theunarchiver/118/1522141689/TheUnarchiver-118.zip
curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'the-unarchiver' with message: Download failed: https://dl.devmate.com/cx.c3.theunarchiver/118/1522141689/TheUnarchiver-118.zip

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/45278

**Comment by Strat1987** [comment]
I'm experiencing the same issue

**Comment by Strat1987** [comment]
Thx! the-unarchiver was successfully installed!
