### ISSUE TITLE
Update lando to 3.0.0-beta.39

### ISSUE THREAD

**Issue by philltran** [caskroom/homebrew-cask#45387]
Another bug fix has been released for  lando

**Comment by commitay** [comment]
Please don't open issues regarding Cask updates.

**Comment by philltran** [comment]
Okay, I am new to contributing. Do I submit a pull request only without the issue?

**Comment by commitay** [comment]
> Do I submit a pull request only without the issue?

Yes.

Also, there is already an open PR for this https://github.com/caskroom/homebrew-cask/pull/45384

**Comment by philltran** [comment]
Thanks for the help. I searched the Issue Queue before posting. I will look at the Pull Requests next time.
