### ISSUE TITLE
wxwork(企业版微信) have new version

### ISSUE THREAD

**Issue by TomorrowWu** [caskroom/homebrew-cask#45426]
`cask 'wxwork' do
  version '2.4.5.213'
  sha256 'e40b65b52507beacb782527e71cf62b6e13a42649e1d27a1b65c0922fd7db317'

  url "https://dldir1.qq.com/foxmail/work_weixin/WXWork_#{version}.dmg"
  name 'Wechat Enterprise Version'
  name 'WeChat Work'
  homepage 'https://work.weixin.qq.com/'

  app '企业微信.app'
end`

![image](https://user-images.githubusercontent.com/13379140/38185416-7d618190-3680-11e8-9392-a7a5e3b83610.png)

Have new version wxwork

**Comment by commitay** [comment]
> [Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```
```
cask-repair --cask-version 2.4.12.3027 wxwork
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/45427

**Comment by TomorrowWu** [comment]
thanks @commitay
