### ISSUE TITLE
Checksum for Cask 'blocs' does not match.

### ISSUE THREAD

**Issue by pablopoo** [caskroom/homebrew-cask#45491]
#### Description of issue

Checksum for Cask 'blocs' does not match.

#### Output of your command with `--verbose --debug`

brew cask install blocs
==> Satisfying dependencies
==> Downloading http://downloads.uistore.io/blocs/version-2/Blocs.zip
######################################################################## 100.0%
==> Verifying checksum for Cask blocs
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'blocs' does not match.

Expected: 5b9619925926c930efb60c0cbc40ddb5ccd127636cc7bdc0456b4907ad413d7e
Actual:   a3488866a28e8b36cc856df0de85044fa5f6975ff0f0f9f86b4e3c66f5073964
File:     /Users/user/Library/Caches/Homebrew/Cask/blocs--2.5.0.zip

To retry an incomplete download, remove the file above.

#### Issue

The blocs download url ( http://downloads.uistore.io/blocs/version-2/Blocs.zip ) is for the latest version (2.5.2 right now), but cask expects an specific version.
An url to that specific version may be used to avoid the checksum mismatch everytime the developer updates the app.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
