### ISSUE TITLE
Outdated cask: ghdl

### ISSUE THREAD

**Issue by EraYaN** [caskroom/homebrew-cask#45527]
ghdl has moved repositories.

Latest version is now: https://github.com/ghdl/ghdl/releases/tag/v0.35
The cask installs v0.34

There are llvm and mode versions.

**Comment by adidalal** [comment]
You should be able to submit a fix, please follow [this](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error_fix_outdated.md)

--------

> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
