### ISSUE TITLE
minergate

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#45664]
The current version is `8.0`, I am trying to submit a PR for`8.1`.

It seems the download URL for the current version differs from the past (and their archive).

Expected (and url for past versions): `https://download.minergate.com/mac/#{version}` (eg `8.0`)
Current: `https://download.minergate.com/mac`

Should this cask be updated to `:latest` and `:no_check`?

Contents for current cask, for reference:
```
cask 'minergate' do
  version '8.0'
  sha256 '2211c1be48c09225dcd27e6223a8243d40334932951fba6257e53220a55afbe7'

  url "https://download.minergate.com/mac/#{version}"
  name 'MinerGate'
  homepage 'https://minergate.com/downloads/gui'

  app 'MinerGate.app'

  zap trash: [
               '~/Library/Application Support/minergate',
               '/Library/Logs/DiagnosticReports/minergate_*',
             ]
end
```

**Comment by reitermarkus** [comment]
If only `https://download.minergate.com/mac` works, then it should be `:latest`.

**Comment by brianmorton** [comment]
https://github.com/caskroom/homebrew-cask/pull/45666
