### ISSUE TITLE
unable to run Parsec when installed by brew cask

### ISSUE THREAD

**Issue by lonelykid** [caskroom/homebrew-cask#45684]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

unable to run Parsec when installed by brew cask, got stuck at the loading stage in the beginning
It runs with no problem if installed manually with the pkg
The pkg file I downloaded from the website and the one brew cask download is from the same url

#### Output of your command with `--verbose --debug`

brew cask install --verbose --debug

==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://s3.amazonaws.com/parsec-build/package/parsec-macos.pkg
/usr/bin/curl --show-error --user-agent Homebrew/1.5.14-3-g94c0d83 (Macintosh; Intel Mac OS X 10.13.4) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/username/Library/Caches/Homebrew/Cask/parsec--latest.pkg.incomplete https://s3.amazonaws.com/parsec-build/package/parsec-macos.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48.9M  100 48.9M    0     0  5883k      0  0:00:08  0:00:08 --:--:-- 8457k
==> Downloaded to -> /Users/username/Library/Caches/Homebrew/Cask/parsec--latest.pkg
==> Verifying download
==> Determining which verifications to run for Cask parsec
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask parsec, skipping verification
==> 0 verifications defined
==> Installing Cask parsec
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Using container class Hbc::Container::Pkg for /Users/username/Library/Caches/Homebrew/Cask/parsec--latest.pkg
==> Executing: ["/usr/bin/ditto", "--", "/Users/username/Library/Caches/Homebrew/Cask/parsec--latest.pkg", "/usr/local/Caskroom/parsec/latest/parsec-macos.pkg"]
==> Creating metadata directory /usr/local/Caskroom/parsec/.metadata/latest/20180407070535.513.
==> Creating metadata subdirectory /usr/local/Caskroom/parsec/.metadata/latest/20180407070535.513/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00000101ad1838>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for parsec; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/parsec/latest/parsec-macos.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is parsec-macos
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing parsec-macos…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%28.381756
==> installer:PHASE:Writing files…
==> installer:%95.162142
==> installer:PHASE:Cleaning up…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer:STATUS:
==> installer:PHASE:Finishing the Installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:The software was successfully installed.
==> installer: The install was successful.
🍺  parsec was successfully installed!

#### Output of `brew cask doctor`

==> Homebrew-Cask Version
Homebrew-Cask 1.5.14-3-g94c0d83
caskroom/homebrew-cask (git revision 661d0; last commit 2018-04-07)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
10
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 56.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3956 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"

#### Output of `brew tap`

caskroom/cask
caskroom/versions
homebrew/boneyard
homebrew/core

**Comment by vitorgalvao** [comment]
Will be fixed by https://github.com/caskroom/homebrew-cask/pull/45688.

Two notes for future bug reports:
* Please keep keep the details in [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks), as they were. As they are now, they are difficult to read.
* Please give as many details as possible. I tried the install, and it shows an error `-1003`. That was crucial in understanding the problem and making the fix.
