### ISSUE TITLE
JupyterLab fails to start new kernel with Homebrew Anaconda install, still looking for old location

### ISSUE THREAD

**Issue by bobtodd** [caskroom/homebrew-cask#45825]
#### General troubleshooting steps

- [x ] I have retried my command with `--force` and the issue is still present.
- [x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x ] None of the templates was appropriate for my issue, or I’m not sure.
- [x ] I ran `brew update-reset && brew update` and retried my command.
- [x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
Howdy y'all,

Following [this thread](https://stackoverflow.com/questions/42182706/how-to-uninstall-anaconda-completely-from-macos?rq=1) I uninstalled the Anaconda setup that I had obtained directly from the project site.  That had installed into my home directory.

I reinstalled Anaconda from the Homebrew Cask (placing `export PATH=/usr/local/anaconda3/bin:"$PATH"` in my `.bashrc`).  Now when I run `jupyter-lab` and create a new notebook, selecting a Python 3 kernel, the process fails with the following output:

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '~/anaconda/bin/python': '~/anaconda/bin/python'
```

I'm a little mystified as to how this error is occurring: I specifically removed all of the `$HOME/anaconda` references from my path.  Does anyone have any suggestions as to why the program would be searching `$HOME/anaconda` (my old install location), when Homebrew installed (without error) into `/usr/local/anaconda3`?

I understand this might just as well be a JupyterLab issue, but I thought I might seek help here since

1. I thought maybe someone might have seen similar behavior before, and
2. JupyterLab was working just fine with the non-Homebrew install, until I evidently mangled everything by accident using the Cask version.

Any suggestions would be greatly appreciated.

Peace out,
Todd

#### Command that failed

```
jupyter-lab
```

#### Output of command with `--force --verbose --debug`

```
Unrecognized flag: '--force'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.0-11-gdf19f71
caskroom/homebrew-cask (git revision 98ba8; last commit 2018-04-11)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
10
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (12 files, 2.1GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3959 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1159 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
caskroom/cask
caskroom/fonts
docmunch/pdftk
homebrew/core
homebrew/headonly
homebrew/science
homebrew/services
jonchang/biology

```

**Comment by bobtodd** [comment]
I guess I should add that I've been trying to `grep` the string `~/anaconda/bin` on my system and it has so far only returned hits in `Library/Caches/com.apple.Safari/WebKitCache/Version 12/Records/`, I guess because `jupyter-lab` opens with Safari as my default browser.

Peace out,
t

**Comment by vitorgalvao** [comment]
This does not seem to be related to us, and instead to your setup, so I’ll close.

**Comment by vitorgalvao** [comment]
We have no one else with `anaconda` issues, and your issue is even referring to its interaction with a tool we don’t even provide. That means we have no reliable reproduction steps, and it’s just as likely the issue is with your configuration. With all the daily issues and PRs we get, e simply don’t have the bandwidth to spend debugging that.

This is an issue for StackOverflow, not us.

**Comment by bobtodd** [comment]
OK, fair enough.  Thanks for the suggestion.
