### ISSUE TITLE
TravisCl encounters an error when attempting to update mp4tools to version 3.7.0

### ISSUE THREAD

**Issue by forrestwparker** [caskroom/homebrew-cask#45835]
The template doesn't apply to this issue.

I am trying to update the mp4tools cask to version 3.7.0 using the provided script in the Caskroom documentation. I have used the script twice in my attempts. Both times, the script completes properly and submits a new pull request, but I later receive the following email:

"Something went wrong with the build.

TravisCI finished with status errored, which means the build failed because something unrelated to the tests, like a problem a dependency or the build process itself."

**Comment by commitay** [comment]
It errors because the PR is closed.

**Comment by forrestwparker** [comment]
Would that occur because I delete the branch from my copy of the repository before the pull request is approved?

**Comment by commitay** [comment]
Yes

**Comment by forrestwparker** [comment]
Noted. I'll resubmit and remove the branch after approval.
