### ISSUE TITLE
JAVA issue

### ISSUE THREAD

**Issue by prenfic** [caskroom/homebrew-cask#45840]
#### Description of issue

{{
For the Ordinary or Common user,
the Java v.8 which is currently keep getting update from JAVA,
is far more enough,
but thru the
```
BREW CASK INSTALL JAVA
```
or
```
BREW CASK UPDATE or UPGRADE
```
the v.10 java is pushed and install unnoticed,
until the running of first Java based application since that update,
I would like to say that,
may you,
decrease the java level from v.10 to v.8,
but not keep pushing the DEVELOPING level stuff,
this is quite disaster,
when I notice this,
I should uninstall the java from brew cask,
and then manual install it from official site
```
https://www.java.com/en/download/mac_download.jsp
```
I hope that this issue won't be closed that rapid,
at least,
let the another user have the same problem like me,
see how to solve it.
}}

**
SORRY for I miss-notice the further mail,
exactly there is better solution from @commitay 
at here
```
https://github.com/caskroom/homebrew-cask/issues/45814
https://github.com/caskroom/homebrew-cask/pull/45816
```
**

**Comment by commitay** [comment]
`brew cask install java` always installs the latest version.

**Comment by prenfic** [comment]
Is there any chance to maybe, change the "java" into "Java10" or "java8" to distinguish the difference between each of them,
besides, what about my further update,
what if I run the
```
brew cask upgrade
brew cask update
brew update
brew upgrade
```
and the java10 is pushed to me,
again?

**Comment by prenfic** [comment]
@commitay

**Comment by commitay** [comment]
If you only want Java 8:

`brew cask uninstall java` 

`brew cask install java8`

**Comment by prenfic** [comment]
Ah,
thx ya,
sorry for these tons of stupid problems im keep asking.

Thank you.

**Comment by commitay** [comment]
@prenfic Please ask questions on our Gitter chat rather than opening issues.

https://gitter.im/caskroom/homebrew-cask

**Comment by prenfic** [comment]
@commitay get it, I just fresh to know that, there is GITTER.IM.
just stepped into,
thank you.
