### ISSUE TITLE
Error on uninstall of intel-haxm

### ISSUE THREAD

**Issue by nicknezis** [caskroom/homebrew-cask#45851]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The silent_install script provided by intel-haxm 6.2.1 does not work on OSX 10.13. I have updated the intel-haxm.rb Cask to use the newer 7.1.0 which works. But I don't know how to help users who had my same issue of being stuck on the older version because I had already upgraded my OSX to 10.13. The fix is to add the 10.13 version to the list of versions in the silent_install.sh script. 
```bash
diff silent_install.sh
-for v in 10.8 10.9 10.10 10.11 10.12
+for v in 10.8 10.9 10.10 10.11 10.12 10.13
```

#### Command that failed

```
brew cask upgrade intel-haxm
```

#### Output of command with `--force --verbose --debug`

```
==> Failed command:
/usr/bin/sudo -E -- /usr/local/Caskroom/intel-haxm/6.2.1,a0:49/silent_install.sh

==> Standard Output of failed command:
HAXM silent installation only supports macOS from 10.8 to 10.12 !
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.0
caskroom/homebrew-cask (git revision 860f5; last commit 2018-04-12)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
1.8.0_131
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (6 files, 154.7MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3960 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
caskroom/cask
homebrew/core
```

**Comment by commitay** [comment]
Please don't open issues when you're going to send a PR.

**Comment by commitay** [comment]
Sorry, didn't read it properly. Reopened.

**Comment by nicknezis** [comment]
@commitay I'm new to adding back to Homebrew. Is there a way to add to "brew doctor" to assist in the uninstall of the older version? Basically the `silent_install.sh -u` will fail for the uninstall unless `10.13` is added as a valid version in the script. I would help fix the older version, but I'm not sure how best to do that. Are there other use cases in which the previously installed Cask can no longer be uninstalled due to an external change such as an OSX upgrade?

**Comment by commitay** [comment]
There isn't anything we can do to make the uninstall work correctly after it has been installed.

Easiest option is to `brew update && brew cask install --force intel-haxm` after https://github.com/caskroom/homebrew-cask/pull/45853 is merged.
