### ISSUE TITLE
Limechat is outdated

### ISSUE THREAD

**Issue by nrlquaker** [caskroom/homebrew-cask#45985]
The version in formula is [2.4.2](https://github.com/caskroom/homebrew-cask/blob/master/Casks/limechat.rb), but the latest one is 2.4.3. But it can only be downloaded from [App Store](https://itunes.apple.com/us/app/limechat/id414030210?mt=12). [Sourceforge](https://sourceforge.net/projects/limechat/files/limechat/) has 2.4.2, [GitHub](https://github.com/psychs/limechat/releases) has only sources. What should be done with such cask?

**Comment by vitorgalvao** [comment]
> What should be done with such cask?

Remove it. We have a rule that if we can’t get the latest version of an app via direct download but it exists on the MAS, we remove it here. This is to prevent people from getting stuck on an older version (that might have serious flaws).

Alternatively, you may want to contact the developer and ask. Maybe they just forgot to update the direct download.

**Comment by nrlquaker** [comment]
@vitorgalvao contacted developer. Waiting for his response.

**Comment by nrlquaker** [comment]
Satoshi said:

> Unfortunately I can't release LimeChat outside of AppStore anymore due to code signing changes made by Apple recently.
