### ISSUE TITLE
DingTalk versioning

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#46156]
I believe we have the beta version of this cask as the current in this repo, but the situation is a bit... challenging.

Screenshot from website:
![image](https://user-images.githubusercontent.com/1434096/39063669-a9f38f88-4480-11e8-941a-82c9a97bb07a.png)

The URL listed under the beta header download is `4.3.0` (which is what we currently have).

Edit: Here is the URL for the download page -> https://www.dingtalk.com/static/i18ndownload

The normal download URL, however, simply downloads a small installer file which then downloads a version of DingTalk. I have used a proxy to try and ascertain what URL/file is being downloaded by this installer, but without luck. Further, the file is about 150mb and seems to come from overseas so it goes at a snails pace for me and I have been unable to get all 150mb without a timeout occurring - thus I can't verify what version of the app would actually be installed.

Thoughts?

**Comment by vitorgalvao** [comment]
Thank you for looking into this.

If the stable version is problematic for us but the beta version isn’t, I see no problem in keeping the beta version.

**Comment by brianmorton** [comment]
@vitorgalvao If I could verify what version is installed by the stable installer, I think it would be fine to just use that. My guess is that it is `4.2.39.2`, as that was the version prior to the latest update PR... however without downloading and installing it to check the version, I can't be certain.

**Comment by vitorgalvao** [comment]
@brianmorton But that would add a significant maintenance burden, having to check the version every time.

**Comment by brianmorton** [comment]
@vitorgalvao isn't this how it was before the cask was "accidentally" updated to the beta version though?

**Comment by vitorgalvao** [comment]
> `4.3.0` is the version you get if you run the installer app.

So they’re downloading the same version? Alright, that makes it easier, then!
