### ISSUE TITLE
Bee Cask URL returning 404

### ISSUE THREAD

**Issue by barchard** [caskroom/homebrew-cask#46165]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Bee version 3 has been released. Version 2 is no longer available. 

#### Command that failed

```
brew cask install bee
==> Satisfying dependencies
==> Downloading https://bee-app.s3.amazonaws.com/public/Bee-2.4.12.zip

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'bee' with message: Download failed: https://bee-app.s3.amazonaws.com/public/Bee-2.4.12.zip
```

#### Output of command with `--force --verbose --debug`

```
n/a
```

#### Output of `brew cask doctor`

```
n/a
```

#### Output of `brew tap`

```
n/a
```

**Comment by vitorgalvao** [comment]
Fixing this is [covered in the instructions](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#curl-error).
