### ISSUE TITLE
404 error while installing solidworks-edrawings

### ISSUE THREAD

**Issue by tfeldmann** [caskroom/homebrew-cask#46221]
It seems like they moved the application to the Mac AppStore ([Download Page](http://www.edrawingsviewer.com/ed/download.htm)) and the former download location is gone.
```
Error: Download failed on Cask 'solidworks-edrawings' with message: Download failed: http://dl-ak.solidworks.com/nonsecure/edrawings/e2015sp02/macse/eDrawings%202015.dmg
```

**Comment by vitorgalvao** [comment]
There’s no such cask in the official repos. You must’ve gotten it from a tap.

Please always fill the template that was there.
