### ISSUE TITLE
Feature request: Force overwriting of application. 

### ISSUE THREAD

**Issue by chriscn** [caskroom/homebrew-cask#46412]
### Description of feature/enhancement
I recently messed up my whole brew installation and before I nuked the directory I make a backup of that directory and a Brewfile using brew bundle. Now when I went to reinstall those apps using brew cask so that I could easily update all of them (loving this feature). There should be an option that will allow me to overwrite any existing files that are already there and reinstall them using Caskroom, or as I like to call it the nuke option. So an option to force overwrite the app would be amazing and would have saved me some time.
### Justification

Allows time to be spent doing other cool things, so lets say you have 1Password already installed, and would like to install it with Brew, give an option to overwrite that previous 1Password install. Of course it could be backed up just in case. 

### Example use case

`brew cask install <token> --force` --force overwrites previous file.

**Comment by vitorgalvao** [comment]
That already exists, and the syntax is exactly that.

**Comment by chriscn** [comment]
@vitorgalvao any idea how to make that work with Brew bundle?

**Comment by vitorgalvao** [comment]
I think bundle basically just adds `brew` to the start of each command, but I don’t use it and the last time I looked at it was years ago. Adding `--force` to each line might work.
