### ISSUE TITLE
Feature request: zap even if app already deleted

### ISSUE THREAD

**Issue by sbibauw** [caskroom/homebrew-cask#46466]
### Description of enhancement

`brew cask zap formula` should work even if the application has already been deleted (and no `Formula.app` file is present in `/Applications/`).

### Justification

- If one runs `brew cask uninstall formula`, and then remembers after the `zap` command, it does not work.
- If one trashes the `Formula.app` file as he would normally remove a non-cask application, and then remembers it was installed by cask, it does not allow him to run `zap`.
- Actually, the `zap` command works quite well, emulating other "zapper" apps, even if the application was not installed nor removed by cask, it is very convenient to be able to use it.
- It can be convenient to `zap` applications that have once been there but have been removed for years, even before brew/cask was installed.

### Example use case

Currently, it fails:

    brew cask uninstall steam
    # (...)
    brew cask zap steam --force
    # ==> Implied "brew cask uninstall steam"
    # Error: It seems the App source '/Applications/Steam.app' is not there.'

**Comment by commitay** [comment]
`zap` used to work even after the Cask was uninstalled, it seems to have been broken during the implementation of `upgrade`.
