### ISSUE TITLE
Delete old versions in cleanup

### ISSUE THREAD

**Issue by j6s** [caskroom/homebrew-cask#4651]
Hi.

This somewhat ties in to the upgrade diskussion:
I just updated my applications by force installing them. This lead to multiple versions on my machine. 

I would have ```/opt/homebrew-cask/Caskroom/pycharm/3.3.x/``` and ```/opt/homebrew-cask/Caskroom/pycharm/3.4.x/```.
On a small SSD this has the potential to litter the HDD.

It would help, if cleanup would try to delete older versions (or a full fledged upgrade)

**Comment by vitorgalvao** [comment]
No longer relevant: #13201.
