### ISSUE TITLE
Request: support older version of karabiner-elements on El Capitan

### ISSUE THREAD

**Issue by adamkiss** [caskroom/homebrew-cask#46719]
Hello,

thank you for great work on this project.

Karabiner-elements, current version 12, only supports Sierra and higher, but the recent version 11.6 supported El Capitan as well. Would it be possible to include version 11.6 in the formulae either based on system, or via @ version a la `node` in brew (`brew node@8` installs node 8, regardless of current version)?

Thank you very much.

**Comment by vitorgalvao** [comment]
Older versions go in [caskroom/versions](https://github.com/caskroom/homebrew-versions). For those you’ll have to submit a PR, we don’t take requests.

If there’s no one willing to make the PR, than we can assume it’s not sufficiently desired for that repo.

**Comment by adamkiss** [comment]
@vitorgalvao Thank you, and I apologise. One question: should this be added to caskroom/versions as an older version (as you pointed out), or as an alternative version here for `MacOs.version <= :el_capitan`? Since for El Capitan users, the 11.6 is the main version, and it's done that way for e.g. [Bartender](https://github.com/caskroom/homebrew-cask/blob/92a3a31d17328b4d4c23b128eff29e7282923845/Casks/bartender.rb#L2-L8)

Thank you.

**Comment by vitorgalvao** [comment]
It can be done the `MacOs.version` way.
