### ISSUE TITLE
Calling Requirement.default_formula is disabled!

### ISSUE THREAD

**Issue by bianfeng218** [caskroom/homebrew-cask#46714]
$ brew uninstall brew-cask
Uninstalling /usr/local/Cellar/brew-cask/0.59.0... (2,976 files, 1.6MB)
Error: Calling Requirement.default_formula is disabled!
There is no replacement.
/usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:13:in `<class:Ruby20Requirement>'
Please report this to the caskroom/cask tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/caskroom/homebrew-cask/issues

**Comment by vitorgalvao** [comment]
`brew-cask` hasn˛t been a formula for years. It’s directly integrated into Homebrew. If you don’t want the tap, do `brew untap caskroom/cask`.

Also note the next time you ignore the issue template, your issue will be closed without review. Repeated infractions and you’ll be banned.
