### ISSUE TITLE
Create folders [a-z0-9] inside the "Casks" folder.

### ISSUE THREAD

**Issue by Rbcafe** [caskroom/homebrew-cask#46879]
### Description of feature/enhancement

Create folders [a-z0-9] inside the "Casks" folder.

### Justification

Because of the following message and to enhance the navigation within the repository.

> Sorry, we had to truncate this directory to 1,000 files. 2,962 entries were omitted from the list.

### Example use case

- Create folders [a-z0-9] inside the folder "Casks".
- Move each cask in each corresponding folder.
- Create the logic that goes with /cask/[a-z0-9]
- The navigation will be enhanced.

Best regards

@Rbcafe

**Comment by commitay** [comment]
This has been suggested before and it would require backend changes that aren't really justifiable as it would only benefit the use case of viewing Casks on GitHub.

**Comment by Rbcafe** [comment]
Greetings @commitay 

Thanks for the information.

Best regards.

@Rbcafe
