### ISSUE TITLE
updated mkbom breaks everything due to illegal operation

### ISSUE THREAD

**Issue by dst-mx559** [caskroom/homebrew-cask#46930]
tl;dr the answer was "restore mkbom from a backup and delete it from /usr/local/bin", any updates or fixes?

every other package breaks due to mkbom illegal options, maybe related to this:

```
**$ brew cask install alfred**
==> Installing Cask alfred
==> /usr/bin/mkbom: illegal option -- s
==> Purging files for version 3.6.1_910 of Cask alfred
Error: Command failed to execute!

==> Failed command:
/usr/bin/mkbom -s -i /var/folders/xr/fkklpv291b148xvn970sw72m0000gn/T/20180510-55926-1aw2kxt.list -- /var/folders/xr/fkklpv291b148xvn970sw72m0000gn/T/20180510-55926-vkvpoh.bom

==> Standard Output of failed command:
Usage: mkbom [i] [-u uid] [-g gid] source target-bom-file

	-i	Treat source as a file in the format generated by ls4mkbom and lsbom
	-u	Force user ID to the specified value (incompatible with -i)
	-g	Force group ID to the specified value (incompatible with -i)


==> Standard Error of failed command:
/usr/bin/mkbom: illegal option -- s

**$ brew cask install vanilla**
==> Installing Cask vanilla
==> /usr/bin/mkbom: illegal option -- s
==> Purging files for version latest of Cask vanilla
Error: Command failed to execute!

==> Failed command:
/usr/bin/mkbom -s -i /var/folders/xr/fkklpv291b148xvn970sw72m0000gn/T/20180510-56412-1fksa34.list -- /var/folders/xr/fkklpv291b148xvn970sw72m0000gn/T/20180510-56412-gbevab.bom

==> Standard Output of failed command:
Usage: mkbom [i] [-u uid] [-g gid] source target-bom-file

	-i	Treat source as a file in the format generated by ls4mkbom and lsbom
	-u	Force user ID to the specified value (incompatible with -i)
	-g	Force group ID to the specified value (incompatible with -i)


==> Standard Error of failed command:
/usr/bin/mkbom: illegal option -- s


==> Exit status of failed command:
#<Process::Status: pid 56876 exit 1>
```

I found this: [https://github.com/EmpireProject/Empire/issues/1090](https://github.com/EmpireProject/Empire/issues/1090)

> Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
> after running setup/install.sh , /usr/bin/mkbom and /usr/bin/mkbom are replaced by this binary which causes Brew to break.
> 
> /usr/bin/mkbom before install (macos version):
> 
> Usage: mkbom [-h] [-s] directory bom
>        mkbom [-s] -i filelist bom
> 
>     -h              print full usage
>     -s              create a path-only bom
>     -i filelist     a file listing in lsbom(8) format used to create the bom file
> /usr/bin/mkbom after install (hogliux version):
> 
> Usage: mkbom [i] [-u uid] [-g gid] source target-bom-file
> 
>         -i      Treat source as a file in the format generated by ls4mkbom and lsbom
>         -u      Force user ID to the specified value (incompatible with -i)
>         -g      Force group ID to the specified value (incompatible with -i)
>

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
