### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#46949]
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

> Open source projects and their build history will continue to run on travis-ci.org for now.

> However, open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018. You will receive an email when the migration for a repository is complete. 

> This is an opt-in process: to have a repository migrated over, it must first be activated on travis-ci.com.

**Comment by vitorgalvao** [comment]
I’ve already initiated the processes earlier this week. For now I see this:
![image](https://user-images.githubusercontent.com/1699443/39900193-0b46ef18-54b8-11e8-8677-3248eff01c10.png)

Which links [here](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org).

So the rest should be done automatically later.
