### ISSUE TITLE
PDFpen 10 requires at least MacOS 10.12 

### ISSUE THREAD

**Issue by dgabbe** [caskroom/homebrew-cask#46970]
Hi,

pdfpen.rb was updated for version 10 from this https://github.com/caskroom/homebrew-cask/pull/46317.   If you are running OS X 10.11, PDFpen.app is installed, but grayed out and won't run.

Smile Software lists the minimum version for PDFpen 10 as 10.12.  Reference: https://smilesoftware.com/pdfpen/download.

My request is this line be added:

  depends_on :macos '>= 10.12'

This should also be done for pdfpenpro.rb.

Thanks,

;TL,DR
I worked around this by creating my own cask which names the app as PDFpen9.app.  See https://github.com/dgabbe/homebrew/blob/master/Casks/pdfpen-9.2.3.rb for reference.

**Comment by CryoRenegade** [comment]
If you want, you can post that 9.2.3 app in caskroom/homebrew-versions because it is for old versions of casks that are still used as long as it is used by some people.

**Comment by CryoRenegade** [comment]
#46973

**Comment by vitorgalvao** [comment]
Thank you for the report, @dgabbe. But wouldn’t it have been faster and less work for you to submit the PR directly?
