### ISSUE TITLE
[cask-bug] Deco

### ISSUE THREAD

**Issue by 0xdevalias** [caskroom/homebrew-cask#46985]
It seems that the 'deco' cask is broken, as per: https://github.com/decosoftware/deco-ide/issues/131

The official recommendation on that thread seems to be to download the .pkg from the website, and just install it manually that way.

Looking at the cask, it appears to be downloading the zip file from:

* `https://github.com/decosoftware/deco-ide/releases/download/v#{version}/Deco-#{version}-osx.zip`

Looking at the releases page, they also seem to list the `.pkg`:

* https://github.com/decosoftware/deco-ide/releases/

So I think that by changing this cask to use the `.pkg`, things should JustWork. But I don't understand enough about how making casks works to just make the edits and send the PR.

**Edit1:** Weirdly enough.. manually downloading the same zip that brew is getting, extracting it, and running the .app inside seems to work fine..

**Edit2:** Actually.. that only worked after I had manually installed the pkg. Once I zapped everything and tried the app again, it doesn't work. So I feel like the 'solution' here is to use the pkg installer (which is also a smaller download) I have a WIP branch on my fork:

* https://github.com/0xdevalias/homebrew-cask/tree/update-deco

**Edit3:** It seems my WIP branch doesn't actually work though:

```
⇒  brew cask install deco
==> Satisfying dependencies
==> Downloading https://github.com/decosoftware/deco-ide/releases/download/v0.7.1/Deco-0.7.1.pkg
Already downloaded: /Users/devalias/Library/Caches/Homebrew/Cask/deco--0.7.1.pkg
==> Verifying checksum for Cask deco
==> Installing Cask deco
==> Running installer for deco; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is Deco
==> installer: Upgrading at base path /
==> installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 0.7.1 of Cask deco
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/deco/0.7.1/Deco-0.7.1.pkg -target /

==> Standard Output of failed command:
installer: Package name is Deco
installer: Upgrading at base path /
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

==> Standard Error of failed command:

==> Exit status of failed command:
#<Process::Status: pid 38580 exit 1>
```

**Comment by 0xdevalias** [comment]
Hacked my branch locally to do the 'install manual' method, and everything works after doing that (as would be expected) Obviously less ideal than a fully automated install.. but still slightly nicer than going and manually getting the pkg I suppose.

**Comment by 0xdevalias** [comment]
Hacked my branch locally to do the 'install manual' method, interestingly, while it says it completed properly (after running the pkg), I can't actually see if/where it ended up installing the app to.

**Comment by commitay** [comment]
It should be in /Applications

**Comment by 0xdevalias** [comment]
Seems so.. I re-reran it again from finder (rather than terminal with open path).. so maybe that made a difference.. *shrugs* In any case.. hopefully there is a better solution for everyone going forward :3

**Comment by commitay** [comment]
Yeah, running the installer via CLI doesn't seem to be an option.

@0xdevalias Can you please submit a PR with the changes in your branch?

**Comment by 0xdevalias** [comment]
@commitay Done: #46987
