### ISSUE TITLE
List of defunct casks that should be removed

### ISSUE THREAD

**Issue by core-code** [caskroom/homebrew-cask#47405]
hey,
some casks no longer install because the software does not exist anymore:

• covered (https://robheague.com/covered => is now only available in the MacAppStore)
• biicode (domain http://biicode.com offline, github not updated in 3 years, no valid mirror found)
• copy (https://www.copy.com => Copy was discontinued on May 1, 2016)
• dump-truck (https://www.goldenfrog.com/dumptruck => Goodbye, Dump Truck
We have discontinued our Dump Truck product.)
• process-monitor (website and download gone)
• kimono (Kimono labs, a web scraping tool popular among the big data community was shut down on February 29th, 2016)

hope that helps

**Comment by vitorgalvao** [comment]
Thank you. Removing in https://github.com/caskroom/homebrew-cask/pull/47410.

For future reference, it’s fine if you submit PRs removing dead casks.
