### ISSUE TITLE
Model Brew Messages

### ISSUE THREAD

**Issue by philoserf** [caskroom/homebrew-cask#4786]
I suggest we model the messages `brew` uses for `brew cask` actions.

An related example can be found in issue #4785 where:

Example of the difference between `brew install` vs. `brew cask install` in the case where a package is already installed:

Brew

```
brew install brew-cask
Warning: brew-cask-0.36.0 already installed
```

Brew Cask

```
brew cask install github
Error: Cask for github is already installed. Use `--force` to install anyways.
```

**Comment by vitorgalvao** [comment]
@philoserf A valid idea, but the issue is too broad. Would you care to find said incongruent messages and open issues for each one? That way we can tackle them as they are found.
