### ISSUE TITLE
refactor `uninstall` tests (Homebrew/brew/blob/master/Library/Homebrew/cask/test/cask/artifact/pkg_test.rb)

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#4806]
- At least one of the Travis glitches we see most often (false failure) is a problem in `uninstall` tests in `cask/artifact/pkg_test.rb`.
- in #4804 @NanoXD pointed out that we should test for multiple `uninstall` stanzas, which, after a quick check, it looks like we do not.
- `cask/artifact/pkg_test.rb` is kind of big/messy.  The false failure glitch is some kind of order-dependent thing.  It might be that it would just go away if we organized `pkg_test.rb` into more separate sections.

**Comment by vitorgalvao** [comment]
@reitermarkus You’ve been more in touch with the tests lately, including some refactoring. Is this (or part of it) something you still deem necessary?

**Comment by reitermarkus** [comment]
I have never seen a glitch with `pkg_test.rb`, so I think we can close this.
