### ISSUE TITLE
`uninstall` should be able to remove Dock icons

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#4815]
As mentioned in #4814.

**Comment by vitorgalvao** [comment]
Closing this one. While a nice to have, it’s extremely low priority and doesn’t actually emulate normal install/uninstall procedure. Also, it will necessarily need to rely on messing with finicky Apple configurations that are more and more protected and harder to mess with.

We can revisit this later, if interest resurfaces.
