### ISSUE TITLE
Add or correct Java `caveats`

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-cask#4885]
Inspired by #4868 knowing there's many apps that should have this caveat (until we'll have true dependency stanza):

 - [ ] [`airstream.rb`](../tree/master/Casks/airstream.rb)
 - [ ] [`arduino.rb`](../tree/master/Casks/arduino.rb)
 - [ ] [`crushftp.rb`](../tree/master/Casks/crushftp.rb)
 - [ ] [`visualvm.rb`](../tree/master/Casks/visualvm.rb)
 - [ ] [`charles.rb`](../tree/master/Casks/charles.rb)
 - [ ] [`filebot.rb`](../tree/master/Casks/filebot.rb)
 - [ ] [`xamarin.rb`](../tree/master/Casks/xamarin.rb)
 - [ ] [`gurps.rb-character-sheet`](../tree/master/Casks/gurps.rb)
 - [ ] [`eclipse.rb-ide`](../tree/master/Casks/eclipse.rb)
 - [ ] [`eclipse.rb-java`](../tree/master/Casks/eclipse.rb)
 - [ ] [`eclipse-jee`](../tree/master/Casks/eclipse-jee.rb)
 - [ ] [`eclipse.rb-platform`](../tree/master/Casks/eclipse.rb)
 - [ ] [`android.rb-studio`](../tree/master/Casks/android.rb)
 - [ ] [`android.rb-studio-bundle`](../tree/master/Casks/android.rb)
 - [ ] [`intellij-idea-ce.rb`](../tree/master/Casks/intellij-idea-ce.rb)
 - [ ] [`intellij-idea.rb`](../tree/master/Casks/intellij-idea.rb)
 - [ ] [`phpstorm.rb`](../tree/master/Casks/phpstorm.rb)
 - [ ] [`pycharm-ce.rb`](../tree/master/Casks/pycharm-ce.rb)
 - [ ] [`pycharm.rb`](../tree/master/Casks/pycharm.rb)
 - [ ] [`rubymine.rb`](../tree/master/Casks/rubymine.rb)
 - [ ] [`webstorm.rb`](../tree/master/Casks/webstorm.rb)
 - [ ] [`appcode.rb`](../tree/master/Casks/appcode.rb)
 - [ ] [`gdal.rb-framework`](../tree/master/Casks/gdal.rb)
 - [ ] [`jubler.rb`](../tree/master/Casks/jubler.rb)
 - [ ] [`tvrenamer.rb`](../tree/master/Casks/tvrenamer.rb)

It's probably not a definite list, these are just the ones I've got remembered.

**Comment by adityadalal924** [comment]
Pinging @vitorgalvao 

Is this still an issue/ what needs to be done here?

**Comment by vitorgalvao** [comment]
This is still an issue, yes, although that’s likely a very incomplete list, unfortunately. Those are all casks that either depend on java and don’t have a caveat stating so, or that have a caveat that is inconsistent with our standard one.

https://github.com/caskroom/homebrew-cask/issues/16383 should make taking care of this easier.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/16591.
