### ISSUE TITLE
more concise update command

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#4981]
#4969 (and others?) expanded the recommended update command to
```bash
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```
(adding two cleanup commands).

This definitely fixes bugs for some users (#4667).  However it would also be kinder to the user if this command line could be made more concise.

Doing so is somewhat tricky because both `brew` and `brew cask` are being called.

Since #3079, we have supported `brew cask update` as a pass-through synonym for `brew update`.  It is conceivable that we could extend `brew cask update` to run the complete recommended update sequence above.  Pro: concise.  Con: not transparent.

(The more fundamental bug should also be addressed.  Apparently Homebrew may pick up the wrong libraries in some cases without `brew cleanup`.  This is difficult to reproduce.)

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is something that should be fixed in the core anyway, and not as a workaround.
