### ISSUE TITLE
Cask cleanup command misplaced result

### ISSUE THREAD

**Issue by ngocphamm** [caskroom/homebrew-cask#4995]
Running `brew cask cleanup` results in the following result.

```
==> Removing dead symlinks
/Library/Caches/Homebrew/Casks/hr-0.3.6.zip
==> Removing cached downloads
Nothing to do
```

I think the part about hr zip should be under "Removing cached downloads".

**Comment by vitorgalvao** [comment]
If you want to submit a PR to make the documentation clearer, @ngocphamm, we can review it. This isn’t a common complaint, though (don’t remember ever seeing it repeated).
