### ISSUE TITLE
Checking for GDAL Framework Dependency

### ISSUE THREAD

**Issue by hanxue** [caskroom/homebrew-cask#5074]
I am trying to create a new cask `qgis` https://github.com/hanxue/homebrew-cask/commit/53d9acfee3a3a4d5665cd943e093618ffd4027c1

1. Why does homebrew cask allow the installation to be marked as successful when the Installer returns an error?

```
$ brew cask install ./qgis.rb 
==> Downloading http://www.kyngchaos.com/files/software/qgis/QGIS-2.2.0-10.dmg
Already downloaded: /Library/Caches/Homebrew/qgis-2.2.0-10.dmg
==> Running installer for qgis; your password may be necessary.
Password:
==> installer: Error - The GDAL 1.11 framework is required.
🍺  qgis installed to '/opt/homebrew-cask/Caskroom/qgis/2.2.0-10' (6 files, 159M)
```

As a result, `QGIS Installer.pkg` get's copied over to the caskroom. If I execute it manually I see this message. 

![screen shot 2014-06-26 at 12 04 58 pm](https://cloud.githubusercontent.com/assets/760008/3394655/1ce2bdec-fce7-11e3-8ae0-07e09097c09d.png)

GDAL Framework is actually installed

```
$ brew info gdal
gdal: stable 1.11.0 (bottled), HEAD
http://www.gdal.org/
/usr/local/Cellar/gdal/1.11.0 (228 files, 33M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gdal.rb
```

2. How can I tell the installer to look for the framework?

**Comment by ndr-qef** [comment]
Cask dependencies have been introduced in `brew-cask` version 0.52.
