### ISSUE TITLE
DSL accept `:unknown` for homepage stanza

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#5248]
And any other stanza where appropriate, for corner cases.

This is better than leaving a stanza missing, because
 - it is self-documenting
 - it is easy to grep for when trying to improve Casks
 - backend code can give a more intelligent error on eg `brew cask homepage`

References: caskroom/homebrew-unofficial#8

**Comment by vitorgalvao** [comment]
Closing as this isn’t really something that is missed, and there’s really no point in having a cask without a home except for extreme corner cases in [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial), and even for the used example we were able to find a solution.
