### ISSUE TITLE
Need to obtain headers before installing Zoiper cask

### ISSUE THREAD

**Issue by ujovlado** [caskroom/homebrew-cask#5299]
Hi there, I'm trying to install Zoiper, but its download site need some cookies before download and additional request is needed before download. I think those cookies/headers can be get through `link_checker`, but I'm not so familiar with ruby yet.

Here's what I got:
```ruby
class Zoiper < Cask

  version 'latest'
  sha256 :no_check

  url 'https://www.zoiper.com/en/voip-softphone/download/zoiper3/for/mac',
    :cookies => {
      'PHPSESSID' => '1234567890abcdef1234567890abcdef',
      'Zopier' => '1234567890abcdef1234567890abcdef'
    }

  homepage 'https://www.zoiper.com'
  container_type :dmg

  link 'Zoiper.app'

end
```
Maybe someone can continue. Thanks.

**Comment by vitorgalvao** [comment]
Old issue, and things might’ve changed. If you’re still interested, @ujovlado, please open a new issue.
