### ISSUE TITLE
brew bundle is unsupported

### ISSUE THREAD

**Issue by jloveland** [caskroom/homebrew-cask#5427]
$ brew bundle Caskfile
Warning: brew bundle is unsupported and will be replaced with another,
incompatible version at some point.
Please feel free volunteer to support it in a tap.

https://github.com/Homebrew/homebrew/issues/30815

May need to update documentation with new recommendation instead of brew bundle Caskfile:
https://github.com/caskroom/homebrew-cask/blob/master/doc/AUTOMATION.md

**Comment by vitorgalvao** [comment]
Closing in favour of #6537.
