### ISSUE TITLE
Installer packages can clobber files, unnecessarily require password

### ISSUE THREAD

**Issue by alexchandel** [caskroom/homebrew-cask#5442]
When cask installs an Installer package, like with [rust](rust.rb), it doesn't check the BOM. This results in cask potentially stomping on existing files, potentially even files installed by homebrew into `/usr/local` (as is the case for rust) .

Moreover, rust's Installer package asks for a root password, and installs as root into `/usr/local/`, even though (since cask is installed) homebrew has changed the permissions on /usr/local/.

It might be worth decompressing the archives of simple Installer packages directly into `/opt`, and linking the files in, rather than blindly running the installer package with whatever permissions it requests.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is not urgent and can be revisited at a later date.
