### ISSUE TITLE
Use .tar.gz binaries for Rust nightlies instead of .pkg

### ISSUE THREAD

**Issue by alexchandel** [caskroom/homebrew-cask#5621]
The Rust pkg installer installs as `root` directly to `/usr/local`, potentially clobbering any Homebrew files. It also doesn't install the `cargo` nightly binaries, which are only provided in .tar.gz form.

Rust also provides .tar.gz binaries for Mac, at `http://static.rust-lang.org/dist/rust-nightly-x86_64-apple-darwin.tar.gz`. These could be unarchived to `/opt/homebrew-cask/Caskroom` like any other cask, and symlinked into `/usr/local` instead. However, I'm not sure whether Cask has the machinery to symlink the contents `rust/lib` and `rust/bin` to `/usr/local/lib` and `/usr/local/bin`

Additionally, with this approach, cargo nightly binaries could also be installed. Cargo provides tarballs at `http://static.rust-lang.org/cargo-dist/cargo-nightly-x86_64-apple-darwin.tar.gz`.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. Rust 1.0 has already been released, though, so is this still an issue at all?

**Comment by alexchandel** [comment]
@vitorgalvao Actually yes (sorry for the hiatus)

Moreover, it's much easier to do now. The Rust nightlies now include cargo (see https://static.rust-lang.org/dist/rust-nightly-x86_64-apple-darwin.tar.gz and https://static.rust-lang.org/dist/rust-nightly-i686-apple-darwin.tar.gz)
