### ISSUE TITLE
Add `brew cask list --versions`

### ISSUE THREAD

**Issue by ErikEvenson** [caskroom/homebrew-cask#5682]
Would be nice if this worked the same as `brew list --versions` per https://github.com/Homebrew/homebrew/issues/245.

**Comment by n0mer** [comment]
@vitorgalvao since this release https://github.com/caskroom/homebrew-cask/releases/tag/v0.55.0 is out, can this issue be  closed ?

**Comment by vitorgalvao** [comment]
#13201 makes this irrelevant.
