### ISSUE TITLE
no longer seeing new/updated casks in brew update

### ISSUE THREAD

**Issue by tcarlsen** [caskroom/homebrew-cask#5839]
I do a `brew update`every morning to check out all the new packages and also the new casks, but in the last 6-7 days I dont see any info for casks, only brew packages

![screenshot 2014-08-20 08 10 17](https://cloud.githubusercontent.com/assets/145288/3977143/84d15d66-2832-11e4-8e24-a6d0fdb1bc70.png)

`brew cask update`does the same
any ideas?

**Comment by Amorymeltzer** [comment]
Really nice, @alebcay!

**Comment by vitorgalvao** [comment]
Closing. The core issue shall be worked on when `brew cask upgrade` is worked on.
