### ISSUE TITLE
Make even more repositories?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#5876]
This is something I’ve been thinking about on and off for about a year, and that I believe makes even more sense currently, with the amount/different types of casks and the fact this project is now an organisation. I don’t feel that strongly for or against this idea, and it was initially formulated at a time when this project was a different beast, so I’d like to gather if it warrants doing depending on the support it gets.

We have [different taps for different goals](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#finding-a-home-for-your-cask) but they’re all concerned with alternate or tangent versions of what’s already in the main tap. All except one, that is, [fonts](https://github.com/caskroom/homebrew-fonts). Why not also separate qlplugins, prefpanes, and perhaps even [binary-only casks](https://github.com/caskroom/homebrew-cask/pull/5874)?

There are two more kinds of apps I think would benefit from being separated from the main repo<sup>1</sup> (even more than the above examples): games and drivers.

Now, with me having always been vocal against steering the project in a “discoverability” direction, this might seem weird. However, discoverability is about marginal differences (genres, if you will); what I am talking about is separating entire classes of purpose. While styles/genres of apps can overlap/be hard to define (one of the biggest issues with implementing discoverability features), here we’re talking about well defined *categories* of applications — apps that have such different intents, there’s no way they could be confused, and could actually benefit from being separated.

---
<sup>1</sup> The ones that made me start to think about this idea, when they were first introduced

**Comment by radeksimko** [comment]
As mentioned on IRC, I think this is a good idea, but also agree with @rolandwalker 's concerns regarding naming clash across taps, so I'd keep this open, so we don't forget, but postpone action steps until DSL 1.0 is out?

**Comment by vitorgalvao** [comment]
Closing. Will open a new one in a few moments.
