### ISSUE TITLE
Group permissions on /opt/homebrew-cask

### ISSUE THREAD

**Issue by boneskull** [caskroom/homebrew-cask#5887]
My use case is that I have a machine with two users.  Both are in the group `brew`.  `/opt/homebrew-cask` is writable by `brew`.  Installing app Foo.app using `brew cask install` gives me `Foo.app`, but its group is not `brew`, which makes me sad.

A workaround is (apparently; haven't tried) to set the sticky bit manually on `/opt/homebrew-cask`.  

Maybe that should be the default behavior, or maybe this should be customizable somehow.  Thoughts?

**Comment by vitorgalvao** [comment]
Closing since it can currently be easily fixed with a workaround and this behaviour will be changed in the future.
