### ISSUE TITLE
Dealing with apps that insist on non-symlink unportable installation?

### ISSUE THREAD

**Issue by treyharris** [caskroom/homebrew-cask#6001]
Sorry if this is a previously-discussed issue but I can't figure out the right search terms if so.

I submitted a pull request, #5902, a couple weeks ago with an example (the Voila screen grabber). I just decided to try one of Voila's competitors, Snagit, for which there's [already a Cask](/caskroom/homebrew-cask/blob/master/Casks/snagit.rb). But when I ran `brew cask install snagit`, got a successful response, and tried to run the app, I found it suffers from the same problem I attempted to workaround with the rather kludgey cask for Voila I submitted.

These two apps require
  1. that they be installed into _/Applications_ and nowhere else (not even _~/Applications_).
  1. that they not be accessed by symlinks. Either an actual .app bundle or a Mac alias in _/Applications_ is acceptable.

There's been no action on my pull request, so I'm guessing this is a difficult problem. If y'all have any input on the best way to solve it, I'm happy to submit a patch to solve it for both of these casks (and any others that might need the same treatment).

**Comment by vitorgalvao** [comment]
Linking apps is not a great behaviour and issues like this prove how broken it makes everything as we need workarounds on top of workarounds. It’s getting ridiculous, and the behaviour needs to change, which is in the plans.
