### ISSUE TITLE
Error: It seems the symlink source is not there (Splunk cask)

### ISSUE THREAD

**Issue by indiesquidge** [caskroom/homebrew-cask#6079]
Hey there. I am trying to create a cask for Splunk and think I almost have it. I'm guessing it has something to do with my link, but I keep getting the error message 

`Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/splunk/6.1.3/Splunk.app'`

Any help on how to fix this would be fantastic! Here is my .rb file contents

``` ruby
class Splunk < Cask
  version '6.1.3'
  sha256  '9e0c1f216c5563a356636767d818adbad211e77004731e4b4b7f955c4b3b8b71'

  url      'http://download.splunk.com/products/splunk/releases/6.1.3/splunk/osx/splunk-6.1.3-220630-macosx-10.7-intel.dmg'
  homepage 'http://www.splunk.com/'

  link      'Splunk.app'
  install   'splunk.pkg'
  uninstall :pkgutil => 'splunk.pkg'
end
 ```

**Comment by vitorgalvao** [comment]
@indiesquidge Still interested in contributing the cask? Alternatively, do you want to do it, @alebcay, since you’ve done the work as well?
