### ISSUE TITLE
brew cask info should give path to resolved Cask on filesystem

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#6136]
That will be straightforward after #3066.

**Comment by vitorgalvao** [comment]
#3066 has been merged, so replying as a reminder.

**Comment by bgandon** [comment]
Hi,
I tried to hack something around this.

My first point is a minor question about the semantic of the `Cask.installed?` method. Currently it means _“is this very software in this very version currently staged on this system?”_. Whereas I would expect that it would mean _“is this software installed on my system, whatever the version?”_.
Do you guys have any plans on providing ?

Then, I looked around the `.metadata` directory of a cask. I realized this could be used to instantiate Cask objects that could be tested for being staged on the system. I created the PR #12746 to demonstrate the idea.

Third point, the `brew cask info` code states: `todo completely reformat the info report`.. Maybe it's time!

Cheers

**Comment by adityadalal924** [comment]
Closed as https://github.com/caskroom/homebrew-cask/issues/13201 will make this irrelevant
