### ISSUE TITLE
uninstall stanzas to improve

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#6222]
### currently uses `uninstall :delete`

These would clearly be improved by using `uninstall :pkgutil`.  If possible, the `:delete` directive should be removed.

 - [x] [authbuddy.rb](../tree/master/Casks/authbuddy.rb)
 - [ ] [growl-fork.rb](../tree/master/Casks/growl-fork.rb)
 - [ ] [netbeans-cpp.rb](../tree/master/Casks/netbeans-cpp.rb) [ID overlap with other Netbeans]
 - [ ] [netbeans-php.rb](../tree/master/Casks/netbeans-php.rb) [ID overlap with other Netbeans]
 - [x] [squirrel.rb](../tree/master/Casks/squirrel.rb)
 - [x] [whatpulse.rb](../tree/master/Casks/whatpulse.rb)
 - [ ] ~~[ntfs-free.rb](../tree/master/Casks/ntfs-free.rb)~~ [appears not to have any ID]
 - [ ] ~~[zoomus.rb](../tree/master/Casks/zoomus.rb)~~ [appears not to use BOMs]

### currently lacks `uninstall :delete` or `uninstall :script`

This occurred because a `:delete` directive was moved to the `zap` stanza in #6164.

 - [x] [mailfollowup.rb](../tree/master/Casks/mailfollowup.rb)

### currently uses `uninstall :script`

`uninstall :script` is fine and does not need to change.  However, these Casks would still be improved by adding a `:pkgutil` directive.  The `:pkgutil` directive would help robustness in corner cases, such as when the installation has been mangled and the expected uninstall script is missing.

 - [ ] [ax88179.rb](../tree/master/Casks/ax88179.rb)
 - [ ] [ax88772.rb](../tree/master/Casks/ax88772.rb)
 - [x] [camtwist.rb](../tree/master/Casks/camtwist.rb)
 - [ ] [cartao-de-cidadao.rb](../tree/master/Casks/cartao-de-cidadao.rb) [nonspecific ID `pt.eid.middleware`?] 
 - [x] [controllermate.rb](../tree/master/Casks/controllermate.rb)
 - [x] [doublecommand.rb](../tree/master/Casks/doublecommand.rb)
 - [x] [drobo-dashboard.rb](../tree/master/Casks/drobo-dashboard.rb)
 - [x] [fitbit-connect.rb](../tree/master/Casks/fitbit-connect.rb)
 - [x] [fluke.rb](../tree/master/Casks/fluke.rb)
 - [x] [gambit-c.rb](../tree/master/Casks/gambit-c.rb)
 - [x] [haskell-platform.rb](../tree/master/Casks/haskell-platform.rb)
 - [ ] [intel-haxm.rb](../tree/master/Casks/intel-haxm.rb) [should be `com.intel.kext.haxm.#{version}`; confirmation needed]
 - [ ] [leap-motion.rb](../tree/master/Casks/leap-motion.rb) [bad `url`; must update cask before proceeding]
 - [x] [logitech-control-center.rb](../tree/master/Casks/logitech-control-center.rb)
 - [x] [logitech-gaming-software.rb](../tree/master/Casks/logitech-gaming-software.rb)
 - [x] [nosleep.rb](../tree/master/Casks/nosleep.rb)
 - [x] [opennx.rb](../tree/master/Casks/opennx.rb)
 - [x] [pdftk.rb](../tree/master/Casks/pdftk.rb)
 - [ ] [power-manager.rb](../tree/master/Casks/power-manager.rb) [bad `pkg`; must update cask before proceeding]
 - [x] [razer-synapse.rb](../tree/master/Casks/razer-synapse.rb)
 - [x] [screens-connect.rb](../tree/master/Casks/screens-connect.rb)
 - [x] [totalfinder.rb](../tree/master/Casks/totalfinder.rb)
 - [x] [totalterminal.rb](../tree/master/Casks/totalterminal.rb)
 - [x] [vagrant.rb](../tree/master/Casks/vagrant.rb)
 - [x] [virtualbox.rb](../tree/master/Casks/virtualbox.rb)
 - [x] [zendserver.rb](../tree/master/Casks/zendserver.rb)

### References

#3322

**Comment by vitorgalvao** [comment]
Most of these are not needed or terribly outdated, `:pkgutil` isn’t perfect anyway so it shouldn’t be the standard for correctness, and others simply can’t be solved with it.
