### ISSUE TITLE
PhpStorm.app and RubyMine.app can't be verified by codesign and asks for firewall permissions repeatedly

### ISSUE THREAD

**Issue by halilim** [caskroom/homebrew-cask#6281]
Verification fails since this cask [modifies a file](https://github.com/caskroom/homebrew-cask/blob/1760ba68d23b898d79c37573b597a0171fbe333f/Casks/phpstorm.rb#L11) in the app:

    $ codesign --verify --verbose=4  /opt/homebrew-cask/Caskroom/phpstorm/8.0.1/PhpStorm.app
    -> /opt/homebrew-cask/Caskroom/phpstorm/8.0.1/PhpStorm.app: invalid Info.plist (plist or signature have been modified)
    -> In architecture: x86_64

And OS X keeps asking permission for the application firewall like the one [here](https://discussions.apple.com/message/22959493#23009190).

But after copying from the source (this is also the workaround):

    $ # Mounted from /Library/Caches/Homebrew/phpstorm-8.0.1.dmg
    $ cp /Volumes/PhpStorm/PhpStorm.app/Contents/Info.plist /opt/homebrew-cask/Caskroom/phpstorm/8.0.1/PhpStorm.app/Contents
    $ codesign --verify --verbose=4  /opt/homebrew-cask/Caskroom/phpstorm/8.0.1/PhpStorm.app
    -> ... valid on disk ... satisfies its Designated Requirement

And no firewall permission request.

It's the same for the [RubyMine cask](https://github.com/caskroom/homebrew-cask/blob/c00802633fb18360d64f4f233c81517059a92ec1/Casks/rubymine.rb#L12).

**Comment by MasterB** [comment]
@Konsi thank's

**Comment by radeksimko** [comment]
Hi @halilim 
I've been fixing this issue in 7870f7a7c55369c3ed3717f18e6cc706e93d51da for both Phpstorm & Rubymine.

Can you please confirm back to me that you've got the latest version of brew/cask?

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by radeksimko** [comment]
Ah, I've just noticed that this whole thread started in Sep 2014, so it all makes sense, closing now.
Feel free to reopen if the problem persists after upgrading to latest version.
