### ISSUE TITLE
webpquicklook and emin-webpquicklook seem to only work from /Library/QuickLook

### ISSUE THREAD

**Issue by braco** [caskroom/homebrew-cask#6448]
webp-quicklook is not maintained and doesn't work on my build of OSX.

Consider replacing with an alternative?, such as:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/emin-webpquicklook.rb

**Comment by vitorgalvao** [comment]
Closing for lack of implementation from upstream and because there is some restructuring planned that should fix this (and similar cases).

**Comment by gabrielstuff** [comment]
I've got the same issue without pixelmator installed and moving the `WebP.qlgenerator` file in `/Library/QuickLook/` did the trick ! Thanks
