### ISSUE TITLE
`brew bundle` has been removed

### ISSUE THREAD

**Issue by ndr-qef** [caskroom/homebrew-cask#6537]
The `brew bundle` command has recently been [removed from Homebrew](https://github.com/Homebrew/homebrew/issues/32952); we relied on it for automation.

Since Cask is a popular tool for provisioning personal machines, it would be desirable to seek a working alternative without external dependencies, or implement our own `bundle`-like command.

(In the future, bundle-like functionality may be provided by “metacasks” exclusively comprised of cask dependencies, but until then, it would be best to provide an interim solution.)

**Comment by vitorgalvao** [comment]
I say we move the whole discussion to [the concept of metacasks](https://github.com/caskroom/homebrew-cask/issues/8492) (and decide there if we should do it or not), as that could conceivably do the same (and possibly more) than `bundle`.

> it would be desirable to seek a working alternative without external dependencies

[Solution that fills the requisites](https://github.com/caskroom/homebrew-cask/issues/8492#issuecomment-69919686):

```bash
bundle() {
  sed '/^\s*$/d;s/^/brew /' "$1" | sh
}
```

@ndr-qef If there’s something here I’m missing, feel free to reopen for further discussion.

**Comment by mikemcquaid** [comment]
For anyone following this thread: this is the new official replacement built by @andrew: https://github.com/Homebrew/homebrew-brewdler
