### ISSUE TITLE
`brew cask list` should list file path

### ISSUE THREAD

**Issue by Whirlwind** [caskroom/homebrew-cask#6631]
Homebrew-cask is a great project, and it can install app, quicklook and so on.

when I run `brew cask list`:

```
➜   brew cask list
betterzipql	    qlprettypatch	quicklook-json
qlcolorcode	    qlstephen		suspicious-package
qlmarkdown	    quicklook-csv	webp-quicklook
```

I hope it can output more information, for example:

```
➜   brew cask list
Quick Look ( the folder path)
betterzipql	    qlprettypatch	quicklook-json
qlcolorcode	    qlstephen		suspicious-package
qlmarkdown	    quicklook-csv	webp-quicklook

App (the folder path)
xxxxxxx..
```

**Comment by vitorgalvao** [comment]
Agree with @radeksimko. This is a complex problem and doesn’t have a nice solution. It’ll only become worse when we introduce copying, and some apps couldn’t even be handled well by this system, as they put multiple files in multiple locations.
