### ISSUE TITLE
Install don't put app in the usable app when opening a file

### ISSUE THREAD

**Issue by crakjie** [caskroom/homebrew-cask#6728]
Hello after installing -> homebrew-cask / Casks / atom.rb I could not find Atom in the app list selector when opening a file with a new app ( right clic on the file , open with , other application ).

I don't if it's a problem with atom specific installation or simply with caskroom

Cheers

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is definitely non-urgent, and can be revisited later.
