### ISSUE TITLE
RubyMine EAP Build Expired

### ISSUE THREAD

**Issue by leoj3n** [caskroom/homebrew-cask#6732]
![rubymineexpired](https://cloud.githubusercontent.com/assets/990216/4678419/6288b574-55f5-11e4-800d-bdb0d9f63d57.png)

The "Download" button opens http://confluence.jetbrains.com/display/RUBYDEV/RubyMine+EAP

**Comment by vitorgalvao** [comment]
This [has been solved already](https://github.com/caskroom/homebrew-versions/commit/f81cd4ab95c25b29c316bff0d91fcec680a3d83d).
