### ISSUE TITLE
Two packages for one formula

### ISSUE THREAD

**Issue by saulshanabrook** [caskroom/homebrew-cask#6788]
I am attempting to write a cask for [ScanSnap Manager for the S300M scanner](http://www.fujitsu.com/global/support/computing/peripheral/scanners/software/s300m.html). If you look at the "Update" tab of that page, you can see that for OS X 10.8+ you need to install [V2.2L11](http://www.fujitsu.com/global/support/computing/peripheral/scanners/software/mac.html) and then [V2.2L16](http://www.fujitsu.com/global/support/computing/peripheral/scanners/software/mac-mg22-eol.html).

Do you have any ideas how to create a cask for this?

I plan to put it in homebrew-cask-versions, but I thought the question was applicable for any cask.

**Comment by vitorgalvao** [comment]
`depends_on :cask` is functional, so we can close this. Thank you, @saulshanabrook.
