### ISSUE TITLE
yosemite problem install tinkertool

### ISSUE THREAD

**Issue by AndyHoang** [caskroom/homebrew-cask#6833]
I'm using iterm2, zsh.
Installation with other few apps was fine, until tinker tool.
![screenshot 2014-10-20 20 15 10](https://cloud.githubusercontent.com/assets/7590604/4701664/58c0cf78-585b-11e4-8ff2-0db1488ec643.png)
I'm kind of new with Cask, not sure what I did wrong

**Comment by alebcay** [comment]
`tinkertool` was removed in #9082, closing this.
