### ISSUE TITLE
`installer` Casks should provide `uninstall` stanzas

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#6872]
Otherwise, `brew cask uninstall <cask>` will only remove the staged files in the Caskroom.
### `installer :manual` Casks that need `uninstall`
- [ ] [adobe-creative-cloud.rb](../tree/master/Casks/adobe-creative-cloud.rb)
- [x] [default-folder-x.rb](../tree/master/Casks/default-folder-x.rb)
- [ ] [little-snitch.rb](../tree/master/Casks/little-snitch.rb)
- [x] [omnifocus-clip-o-tron.rb](../tree/master/Casks/omnifocus-clip-o-tron.rb)
- [x] [utorrent.rb](../tree/master/Casks/utorrent.rb)
- [x] [vlc-remote.rb](../tree/master/Casks/vlc-remote.rb)
### `installer :script` Casks that need `uninstall`
- [x] [google-cloud-sdk.rb](../tree/master/Casks/google-cloud-sdk.rb)
### `pkg` Casks that need `uninstall`
- [x] [serviio.rb](../tree/master/Casks/serviio.rb)

**Comment by jawshooah** [comment]
@caskroom/maintainers I've updated the list in the top post. We should make it a priority to add `uninstall` stanzas to all Casks with `installer` and `pkg` stanzas that need them.

**Comment by vitorgalvao** [comment]
@jawshooah Last time I checked this issue, I’ve edited it (and the casks) to the last remaining ones that are popular and hard to make uninstalls for.

That said, I’d be in favour of fixing them by force: outright remove them and if/when someone misses them and wants to readd, it will need `uninstall`.

**Comment by vitorgalvao** [comment]
Remaining casks can’t be reliably uninstalled without GUI uninstaller. Closing in favour of https://github.com/caskroom/homebrew-cask/issues/24377 (added the casks there as part of the checklist).
