### ISSUE TITLE
JetBrains IDEs are altered to load with JDKs > 1.6

### ISSUE THREAD

**Issue by ctwise** [caskroom/homebrew-cask#6910]
The JetBrains IDEs (WebStorm, IntelliJ, etc.) have their plists changed to allow them to run with JDKs > 1.6. That has the side-effect of having them to run with a newer JDK if one is installed. JetBrains doesn't recommend running their IDEs with newer JDKs due to very old and still outstanding defects with newer JDKs running GUI apps on OS/X. Here is an old link to defects noted by JetBrains. Many of them are still outstanding.

https://intellij-support.jetbrains.com/entries/27854363

**Comment by radeksimko** [comment]
@ctwise Thanks for the helpful link to JetBrains site. That's something I did not know when putting in the hack for IntelliJ IDEs.

I'll prepare a patch.

**Comment by radeksimko** [comment]
Fixed via #9943
