### ISSUE TITLE
brew cask install import-io

### ISSUE THREAD

**Issue by ccorcos** [caskroom/homebrew-cask#6931]
It seems to have downloaded the installer, but hasn't installed anything...

**Comment by vitorgalvao** [comment]
Has anyone tried to contact upstream about this?

**Comment by phinze** [comment]
Reaching out to their support now - will link them to this issue.

**Comment by vitorgalvao** [comment]
No reply, the url has since changed, and it doesn’t even install correctly, even manually on a clean VM. Lets remove it, and if there’s interest in the future, it can be added then.
