### ISSUE TITLE
Improve git merge practices

### ISSUE THREAD

**Issue by federicobond** [caskroom/homebrew-cask#6958]
When comparing the commit history of `homebrew-cask` with that of the `homebrew` project, one thing that stands out a lot is the sheer amount of git merge bubbles we are generating due to our current practices.

I understand that it is easy to be able to merge commits right from the web interface, but there are several disadvantages with this method that [others](http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/) have carefully pointed out before. In our case, it also pollutes the history with lots of unnecessary cruft, wasting space in every user's computer, and makes it harder to find particular changes by obscuring genuine commits.

I would like to hear your opinions and see if there is a better way we can handle the merge process.

cc/ @caskroom/maintainers

**Comment by vitorgalvao** [comment]
Closing.

I have been following (and prefer) the “cleaner history” approach, as have @Ngrd and @jawshooah. However, I’m not opposed to merging via the web interface, and may do so myself occasionally (if on a phone, for example). Ideally github would let us have the best of both worlds, but that is currently not the case.

I also have a few custom-built scripts I use to make the work easier, depending on if the PR [can be merged as is](https://github.com/vitorgalvao/tiny-scripts/blob/master/fastmerge), or [needs fixes](https://github.com/vitorgalvao/tiny-scripts/blob/master/prfixmaster) and everyone is absolutely free to use and improve on them, if they wish.

In the (no-so-near) future it may be wise to have an agreement so we’re all consistent, but for now its important everyone does what they find works best personally, to get things moving.
