### ISSUE TITLE
Color pickers don't work?

### ISSUE THREAD

**Issue by cowboy** [caskroom/homebrew-cask#7004]
I've installed `colorpicker-developer` and `colorpicker-skalacolor` via `brew cask` and while I see the symlinks in `~/Library/ColorPickers`, they aren't recognized. I'm seeing this behavior in both 10.8 and 10.10, using TextEdit, which I have restarted numerous times.

However, if I remove the symlinks and `cp -R` the downloaded colorPicker files from `/opt/homebrew-cask/Caskroom/` into `~/Library/ColorPickers`, they work.

Is this a bug? Am I doing something wrong on my end?

**Comment by marijnvdwerf** [comment]
Would it be possible to show a message regarding this bug after installing? Like what happens after you install Google Chrome, it tells you that a symlinked install won't work with 1Password.

**Comment by vitorgalvao** [comment]
Closing for now. There is some restructuring planned that should fix this, in the future.
