### ISSUE TITLE
Warning on sha :no_check?

### ISSUE THREAD

**Issue by elliottslaughter** [caskroom/homebrew-cask#7062]
I get a little nervous whenever I am unable verify the software I download. This is mitigated somewhat by the presence of SHA sums in most cask definitions; at least I know I am getting the same versions of apps you are seeing. But many casks have no checksums at all.

I understand there are reasons for this; e.g. Calibre, with unversioned downloads and frequent updates, would break a lot if you tried to enforce checksums. Maybe there is a potential solution here somewhere, but I imagine that any solution would require significant manual effort, which is a burden I don't want to place on anyone.

What would be nice though would be if I could get a warning when I attempt to install a cask without a checksum (and over insecure http). Or maybe you could manually check signatures of apps with `spctl --assess`, though that might possibly be more pain than it's worth. I'm fine if these are optional and not enabled by default, but it would be nice if there were some option for folks who are security conscious.

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/issues/16042
