### ISSUE TITLE
Get localized-UI package for Libreoffice

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#7159]
Hello,
I'm not familiar with writing homebrew-cask formula. But wouldn't there be any solution with brew options in formula, or any other possibility, to allow users to get the desired localized installation for their use of LibreOffice.

In other words: wouldn't it be possible to add an option to the current formula that would, if defined, trigger the post-installation of the selected localized-UI package from that page (https://www.libreoffice.org/download/libreoffice-fresh/?type=mac-x86_64&version=4.3&lang=pick) after installing the main LibreOffice package?

**Comment by yurikoles** [comment]
and of course firefox will benefit!

**Comment by gmkey** [comment]
Did anyone make any progress on this package? I've been reading into it and it seems the script provided by libreOffice has a gui which - imho - would be unneeded for a homebrew-version package. 

The basic install command is:
`/usr/bin/tar -C /opt/homebrew-cask/Caskroom/libreoffice/4.4.3/LibreOffice.app -xjf /Volumes/LibreOffice\ Language\ Pack/LibreOffice\ Language\ Pack.app/Contents/tarball.tar.bz2 && touch /opt/homebrew-cask/Caskroom/libreoffice/4.4.3/LibreOffice.app/Contents/Resources/extensions`
or
`/usr/bin/tar -C <path-to-libreoffice> -xjf <path-to-tarball> touch <path-to-libreoffice><installed-extension>`
where <path-to-libreoffice> is determined by a depends_on :cask
and <path-to-tarball> is given by the location of the dmg and the Content of the App
and <installed-extension> is given by the way LibreOffice is packaged.

Now my assumption is that this could be coded into a homebrew-version package, but I'm not so sure what the coding guidelines say about this....

**Comment by vitorgalvao** [comment]
This won’t be done anytime soon, and at that time hombrew-cask will likely look very different. Closing for consideration at a later time.
