### ISSUE TITLE
How to handle DMG agreements?

### ISSUE THREAD

**Issue by phinze** [caskroom/homebrew-cask#720]
Over in #452 the issue came up that with our current implementation, when a DMG with a required license agreement is opened by homebrew-cask, all you get is a contextless `Agree? (Y/N)` prompt.

One question was whether we have a legal requirement to display said license before the prompt. IANAL (I'd love to have one chime in!) but I'm actually inclined to go the other direction entirely and do the work necessary to skip all required user interaction. As I've mentioned before, I am strongly in favor of supporting unattended/automated operation of homebrew-cask as much as we can.

Here's what I propose as far as behavior goes:

* Extract the EULA and store it alongside the installed application in the Caskroom
* Display a notification that by using this particular Cask, you are agreeing to the thing stored at `$PATH`
* Provide an option for more conservative users like `--prompt-for-dmg-agreements`.

The more research I do on this, the more I find consensus that if an app really wants a license agreement to be accepted, the place to do so is at app launch, not in the package manager. Of course we can't control the way people are going to distribute their apps, but I think it's perfectly reasonable to automate away the prompt and notify the user that on this particular Cask they are responsible for reviewing and accepting the license agreement that we've conveniently pointed them to.

If this strategy makes people squeamish, I'm willing to discuss flipping the default and having the optional behavior be skip and the default behavior be prompt. But this is where I'm at - we'll see what other people say.

**Comment by vitorgalvao** [comment]
Closed in favour of https://github.com/caskroom/homebrew-cask/issues/13593.
