### ISSUE TITLE
cask java, homebrew r: javareconf fails to find jni.h

### ISSUE THREAD

**Issue by mpodell** [caskroom/homebrew-cask#7340]
Running Yosemite 10.10

upon `brew upgrade` to R v3.1.2 I get the message:

> To enable rJava support, run the following command:
>  R CMD javareconf JAVA_CPPFLAGS=-I/System/Library/Frameworks/JavaVM.framework/Headers
> If you've installed a version of Java other than the default, you might need to instead use:
>  R CMD javareconf JAVA_CPPFLAGS='-I/System/Library/Frameworks/JavaVM.framework/Headers -I/Library/Java/JavaVirtualMachines/jdk<version>.jdk/'
>  (where <version> can be found by running `java -version` or `locate jni.h`)

with cask java 1.8.0_25 installed both suggestions fail to find jni.h and with Apple's system java 1.6.0_65 installed both suggestions fail to find jni.h using jdk1.8.0_25.jdk and jdk1.6.0_65.jdk respectively.

any suggestions as to how to fix this?

**Comment by vitorgalvao** [comment]
Is this still an issue, @mpodell?

**Comment by mpodell** [comment]
Sorry for the late response. Was not a problem last time I updated R.
