### ISSUE TITLE
gitx-rowanj symlink does not work

### ISSUE THREAD

**Issue by psibre** [caskroom/homebrew-cask#7419]
The cask `gitx-rowanj` links
```
/usr/local/bin/gitx -> /opt/homebrew-cask/Caskroom/gitx-rowanj/latest/GitX.app/Contents/Resources/gitx
```
but the binary executable inside the app differs in case:
```
/opt/homebrew-cask/Caskroom/gitx-rowanj/latest/GitX.app/Contents/MacOS/GitX
```
As a result, on a case-sensitive file system, running `gitx` does not work:
```
$ gitx
Unable to open GitX.app
```

**Comment by vitorgalvao** [comment]
Closing. Please comment back if the problem persists, @psibre.
