### ISSUE TITLE
Inkscape won't open after install

### ISSUE THREAD

**Issue by tlnagy** [caskroom/homebrew-cask#7464]
Under Yosemite 10.10.1, running `brew cask install inkscape` installs Inkscape, but running the app fails. An Inkscape menu is shown for a split second and then disappears. No error prompts or anything. I have x11 v1.0.1 installed. Any suggestions? 

I seem to remember it needing xquartz under recent versions of OS X. Is this still the case?

**Comment by ponychicken** [comment]
This issue can be closed since the cask now depend on x11 being installed.
