### ISSUE TITLE
DSL: improving support for binary artifacts

### ISSUE THREAD

**Issue by ndr-qef** [caskroom/homebrew-cask#7519]
As part of our work toward an acceptable, mostly stable DSL 1.0, we should address several issues around our support for “naked” binary casks. As this is a matter of general interest for the project, I invite both @caskroom/maintainers and general users to voice their opinions. 

We are currently limited to our `binary` stanza ([doc](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#at-least-one-artifact-stanza-is-also-required)), which links a single file into /usr/local/bin. This behavior is insufficient for much precompiled software.

@rolandwalker mentioned that extensions to `binary` should be backward-compatible; we can also introduce new forms if need be.

The most obvious extension, cosmetic in purpose, would be to allow `binary` to take an array of artifacts:

```ruby
binary 'artifact'
binary ['artifact1' .. 'artifactn']
```
This would improve packages which include a copious number of /bin artifacts, as exemplified by [terraform](https://github.com/caskroom/homebrew-cask/blob/f0f15f7b0c1efec886d7214f983a65e36ed1208a/Casks/terraform.rb).

More importantly, binary distributions often include material which must be linked elsewhere. Our kludge of choice is `artifact`, as used in [cargo](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cargo.rb).

Ideally, the most common materials and their destinations should be supported with simple keywords. It might also be desirable to link everthing in a folder recursively, instead of specifying every individual file. For example:

```ruby
binary :bin => … # artifact, array, or folder/wildcard
       :lib => 'caskname/lib/*'
       :share => …
       …
```

**Comment by ardecvz** [comment]
Hello,

Have you reached a consensus regarding the generic way to install Library artifacts?

Personally, I'm interested in adding to the formulae some SIMBL plugins which should be placed in ```~/Library/Application Support/SIMBL/Plugins``` to work (symlinks are OK, too). At first glance, these plugins could greatly benefit from cask as they are usually distributed without any installer or centralized way to control their installation.

As far as I know, there are around 10-20 SIMBL plugins in the wild so this amount could justify a new ```simbl``` stanza implementation (comparing with <10 ```colorpicker```s or =1 ```screensaver``` and =1 ```input_method```). But I'm little confused with the fact that SIMBL is proprietary and it's not a built-in function of OS X (through it's [open-sourced](https://github.com/norio-nomura/EasySIMBL)). Also, it seems that a further addition of new install stanzas are leading to an unnecessary mess...

Is it OK to add ```simbl``` stanza? Or is it more appropriate to use standard ```artifact``` with ```depends_on :easysimbl```?

Or is it better to move to a more generic way to install Library artifacts? If so, is there any further need to have separate stanzas to install a single screensaver, input_method and so on (and please keep in mind that in the future we would need one more stanza to install solely #6387)?

Thank you!

**Comment by rolandwalker** [comment]
Hi!

Unfortunately, we haven't made any progress on the interface for a generic Library interface.  

However, as there are several SIMBL plugins, and as they follow a standard, we should support them with a specific stanza.

It would be best to file a separate issue for that.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This isn’t really a problem now, and can be revisited later.
