### ISSUE TITLE
download cache improvements

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#7571]
- [ ] `brew cask uninstall --force` should also clean file associated with the given distributions from the download cache, per conversation in IRC
- [x] `brew cask cleanup` should accept arguments which target only some distributions for cleanup (current default should stay the same)
- [x] smarter treatment for `:latest` Casks (known bug; open issue since #6087)

**Comment by jawshooah** [comment]
> smarter treatment for :latest Casks (known bug; open issue since #6087)

Addressed in #15900.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/29805
