### ISSUE TITLE
pdftk cask messes up permissions on /usr/local

### ISSUE THREAD

**Issue by albcorp** [caskroom/homebrew-cask#7707]
After running

    brew cask install pdftk

the group ownership of '/usr/local' changes from 'admin' to 'wheel', and the group write bit is removed.

This is a very serious bug, because it causes the next run of `brew update` to fail in weird and wonderful ways.  The workaround is to recursively set the ownership and group write permission on '/usr/local' and run the brew cleanup commands suggested by brew doctor

    sudo chown -R root:admin /usr/local
    sudo chmod -R g+wX /usr/local
    cd /usr/local/Library
    git stash
    git clean -d -f

After that Homebrew can be safely updated

regards

Andrew

**Comment by jvenator** [comment]
@albcorp did you ever get a response from the PDFtk developer?

And perhaps not the right place to discuss it, but what install process did you adopt in the absence of the brew-cask option? I had a bunch of user permissions issues on a machine, and I'm now thinking this may have been the culprit.

**Comment by michelschinz** [comment]
@jvenator Personally I installed pdftk by hand, by doing roughly the following:
  1. I downloaded the `.pkg` from pdftk's web site,
  2. I manually extracted its contents, using `xar` (first level) and `cpio` (second level),
  3. I created a directory in `/usr/local/Cellar` called `pdftk` and then a sub-directory for the version (`2.02` in my case), in which I put the various files where Homebrew expects them,
  4. I ran `brew link` to create links from `/usr/local/...` to the various files (e.g. the `pdftk` binary) I had just copied.

Here is what I now get when I run `brew list pdftk`:
```
/usr/local/Cellar/pdftk/2.02/bin/pdftk
/usr/local/Cellar/pdftk/2.02/lib/libgcc_s.1.dylib
/usr/local/Cellar/pdftk/2.02/lib/libgcj.11.dylib
/usr/local/Cellar/pdftk/2.02/lib/libiconv.2.dylib
/usr/local/Cellar/pdftk/2.02/lib/libstdc++.6.dylib
/usr/local/Cellar/pdftk/2.02/share/man/man1/pdftk.1
```

There's some work involved, but I think it's the easiest solution given the current problems.

**Comment by evils** [comment]
@michelschinz Your solution looks good, I would love to see a homebrew working like this as I heavily rely on pdftk in some of my CI routines.

**Comment by jawshooah** [comment]
@evils Working on it.

**Comment by jvenator** [comment]
Having never gone through process of manually installing and breaking apart a `.pkg` app, I ran into some noob bumps along the way attempting to follow the recommended approach above. So I put together a thorough list of exact steps and dropped them into a public gist. Thanks for the initial help @michelschinz !

[Installing PDFtk Server edittion on your Mac](https://gist.github.com/jvenator/9672772a631c117da151)

**Comment by vitorgalvao** [comment]
@jvenator [Fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) could help keep the gist more organised, as opposed to having a bunch of commands on the same line, some with `&&`, some not (and why are some between parenthesis?).

Commenting here because Github does not warn on Gist comments.

**Comment by jvenator** [comment]
@vitorgalvao thanks, fixed. The parenthesis were to maintain the current directory prior to the command, which I thought was helpful initially ([found in this cpio question](http://serverfault.com/questions/47998/how-to-get-cpio-gnu-rhel-4-to-extract-to-a-specified-directory)). However, it ended up not mattering the way everything was written.

As far as breaking out the larger `&&` commands into their individual single commands, it was to provide clarity around what was actually being done. As a novice in many areas myself, I often piggyback on the work of others, copy/paste, without always understanding what's going on. I always appreciate when someone takes the time to explicitly breakout what's taking place.

**Comment by vitorgalvao** [comment]
I actually meant that instead of doing

`mkdir /usr/local/Cellar/pdftk` `mkdir /usr/local/Cellar/pdftk/2.02`

or

```
mkdir /usr/local/Cellar/pdftk
mkdir /usr/local/Cellar/pdftk/2.02`

**Comment by vitorgalvao** [comment]
I actually meant that instead of doing

`mkdir /usr/local/Cellar/pdftk` `mkdir /usr/local/Cellar/pdftk/2.02`

or

`mkdir /usr/local/Cellar/pdftk`
`mkdir /usr/local/Cellar/pdftk/2.02`

or even

`mkdir /usr/local/Cellar/pdftk && mkdir /usr/local/Cellar/pdftk/2.02`

you could do

```
mkdir /usr/local/Cellar/pdftk
mkdir /usr/local/Cellar/pdftk/2.02
```

which is clearer and still allows users to copy and paste all the commands without a hitch.

**Comment by evils** [comment]
@jvenator Is this becoming a brew cask formula in the future?

**Comment by vitorgalvao** [comment]
@albcorp Any luck contacting the developer?

**Comment by rusterholz** [comment]
+1 for finding a permanent solution to this.

**Comment by 100ideas** [comment]
@michelschinz's technique above of [unpacking the official installer](https://github.com/caskroom/homebrew-cask/issues/7707#issuecomment-70789122) and copying the files into the cellar manually worked for me. 

[How unpack and pack pkg file?](http://stackoverflow.com/a/11299907) helped me figure out how to unpack the cpio.gz archive of the pdftk package.

I got pdftk v.2.02, so moved the relevant files to `/usr/local/Cellar/pdftk/2.02/bin/pdftk` etc.

Then `brew switch pdftk 2.02` to [link it](http://stackoverflow.com/a/17103753/957984).

Just what worked for me in case anyone else wants to try this route.

**Comment by vitorgalvao** [comment]
Closing in favour of #11351, where the developer is being contacted.

**Comment by gaming-hacker** [comment]
i just extracted the contents of the file and moved to where i wanted.  i almost never let a pkg install.
