### ISSUE TITLE
Safari extensions feature request

### ISSUE THREAD

**Issue by jeffrbauer** [caskroom/homebrew-cask#7710]
Is there a way to install Safari extensions using homebrew-cask? I did not find any previous examples of this being done. 

One extension that I would like would be AdBlock which can be found at https://getadblock.com.
I also did not attempt to make a new cask with this extension.

A user could download from this URL:
https://data.getadblock.com/safari/AdBlock.safariextz

Then homebrew-cask would install:
AdBlock.safariextz

**Comment by bcomnes** [comment]
What about just tracking the plugins as formulas, downloading them and then opening then and letting safari handle the installation? I know that defeats the purpose of the hands off installation, but at least it captures the hands off tracking and downloading of specific plugins.

**Comment by vitorgalvao** [comment]
@bcomnes It’s part of the goal of homebrew-cask to never call a GUI, so that is no good.

**Comment by danielbayley** [comment]
+1 for this if possible.

**Comment by vitorgalvao** [comment]
@danielbayley Unlikely it’ll happen.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is definitely non-urgent, and can be revisited later.

**Comment by eivindml** [comment]
Would love to see a feature like this.

**Comment by vitorgalvao** [comment]
@eivindml Then you’ll have to implement it yourself (or pay someone to do it) because there’s not enough return of having the team spend their time on this.
