### ISSUE TITLE
Create "binarydir" (/usr/local by default) automatically & check permissions/ownership

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-cask#7750]
Homebrew can be installed in different locations, although it may not happen very often and I'd personally discourage people from doing so, it happens in [`boxen`](https://github.com/boxen/puppet-homebrew/blob/153bcc9f7c1245471e45e3a5f6cfa7f8f91fb348/lib/puppet/provider/package/homebrew.rb#L18).

<del>This causes issues for Cask, because</del> it expects existence of [`binarydir`](https://github.com/caskroom/homebrew-cask/blob/master/lib/cask/locations.rb#L80) and existence of the parent dir - `/usr/local` which **doesn't exist by default** in a fresh OS X installation.

```
Debug: Executing 'brew cask install sourcetree'
Error: Execution of 'brew cask install sourcetree' returned 1: ==> Downloading https://downloads.atlassian.com/software/sourcetree/SourceTree_2.0.3.dmg
==> Symlinking App 'SourceTree.app' to '/Users/vagrant/Applications/SourceTree.app'
Error: Permission denied - /usr/local
==> Symlinking Binary 'stree' to '/usr/local/bin/stree'
```

It seems that there were only some historical reasons behind the exotic homebrew location and [it should be fixed](https://github.com/boxen/puppet-homebrew/issues/68), but I think that **Cask should not rely on the default location anyway**.

I would send a fix that will check existence of default `binarydir` + tries `mkdir -p` before even trying to symlink casks into it (either with any cask installation or on homebrew-cask installation), if you agree?

**Comment by radeksimko** [comment]
So it turned out that this is more of a permission problem. I will run a few more tests on my VMWare/boxen setup to double check I'm right and then probably move onto testing/fixing the permissions problem.

**Comment by salimane** [comment]
@radeksimko thanks

**Comment by radeksimko** [comment]
@salimane Just FYI, I tested the whole provided list of casks above - installed them, launched each and then uninstalled. Both `/usr/local` and `/usr/local/bin` still have the same (correct) permissions so this conflict was either caused by something you installed outside of brewcask or by manually using/updating any app of that list or by boxen itself or any of its modules.

Either way I think, that brewcask could run `stat` on these directories each time user installs/uninstalls any cask and if the process changes anything, encourage the user to report such cask here. This way we can at least make sure that it's never caused by (un)installation process.

btw. the "correct" permissions given after installing homebrew & cask are following:

```
drwxrwxr-x root admin /usr/local
drwxr-xr-x %USER% admin /usr/local/bin
```

**Comment by halo** [comment]
Just wanted to mention how I experienced this on a fresh installation of El Capitan with a fresh homebrew installed in a custom location (in my home dir).

The first thing I tried was to install the `VLC` cask, which [apparently has a binary](https://github.com/caskroom/homebrew-cask/blob/0471a556ca2b564da827e2ba45e4d86e56d4bed2/Casks/vlc.rb#L15) it would like to place into `/usr/local/bin` which, as mentioned before, does not exist.

So it just plainly fails. I might be missing something, but had expected that the (apparently optional) executable is simply skipped. Instead of trying to create that directory.

I also wanted to point out [Apple's SIP](https://support.apple.com/en-us/HT204899) which states about the `/usr` directory:

> System Integrity Protection is designed to allow modifications of these protected parts only by processes that are signed by Apple...

Not sure whether that affects the desired implementation, but I thought I just mention it.

This is the output, just in case.

```
$ HOMEBREW_CASK_OPTS="--caskroom=/Users/me/caskroom --appdir=/Users/me/Applications" \ 
  /Users/me/homebrew/bin/brew cask install vlc

Downloading https://get.videolan.org/vlc/2.2.3/macosx/vlc-2.2.3.dmg
  ==> Verifying checksum for Cask vlc
  ==> Symlinking App 'VLC.app' to '/Users/me/Applications/VLC.app'
  ==> Symlinking Binary 'vlcwrapper' to '/usr/local/bin/vlc'

Error: Permission denied - /usr/local/bin
Most likely, this means you have an outdated version of homebrew-cask... (etc...)
```

```bash
$ brew cask list
Warning: nothing to list
```

```bash
$ stat -f '%Sp %Su %Sg' /usr/local
drwxr-xr-x root wheel
```

```bash
$ stat -f '%Sp %Su %Sg' /usr/local/bin
stat: /usr/local/bin: stat: No such file or directory
```

**Comment by vitorgalvao** [comment]
Since we’ll be merging with Homebrew, we should actually close this and just read whatever directory homebrew uses. Will open a discussion.
