### ISSUE TITLE
factor.rb: binary stanza does not work

### ISSUE THREAD

**Issue by mcandre** [caskroom/homebrew-cask#7766]
#7754 created a bug:

```
$ factor
Cannot open image file: /usr/local/bin/factor.image
No such file or directory
```

I suspect that the `factor` binary makes the mistake of assuming its data are in the same directory as itself.

As a workaround, I think we can put a symlink in /usr/local/bin/ instead of the actual binary.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/7791.

@mrjbq7 Do you know when can we expect version `0.98`?

**Comment by mrjbq7** [comment]
@vitorgalvao we're working on it! We have a
contributor working on some UI improvements to modernize the UI that we want to include. 

Should be able to release in the next month I would guess.
