### ISSUE TITLE
[Suggestion] new install/update mechanism

### ISSUE THREAD

**Issue by xu-cheng** [caskroom/homebrew-cask#7816]
I recommend a new install/update mechanism for this project. Homebrew now allows the external commands living in the `cmd` folder in the taps. So instead of installing by Formula, we can install and update homebrew-cask by this:

* Install: `brew tap caskroom/homebrew-cask`
* Update: `brew update`

This simplifies the user experience, reduces the redundant files in the system and makes update much easier (`brew upgrade brew-cask` is no longer needed). However, it requires users to uninstall the old version homebrew-cask to avoid the conflict. You can find more information on [homebrew-livecheck](https://github.com/youtux/homebrew-livecheck) who has switched to this new mechanism.

**Comment by vitorgalvao** [comment]
We’re in talks of merging the two projects, so this would become irrelevant.
