### ISSUE TITLE
React to non-200 HTTP status codes

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-cask#7883]
The [current implementation of both GET & POST downloads](https://github.com/caskroom/homebrew-cask/blob/master/lib/cask/download_strategy.rb) allows downloading response, which is not `2xx`. If there's SHA2 check in place for a cask, then it ends up in confusing error with SHAsum mismatch (not even noticing anything about original HTTP code).
I'm not sure what will happen in case of `:no_check` casks... tries of mounting HTML files like dmg or moving HTML file to `~/Applications`? :)

I'm not entirely sure whether it should be limited to `200` only, but it should definitely react to codes like `5xx` (e.g. 503).

The current implementation basically uses Curl with `-f` parameter, but as even the manual says _"This  method is not fail-safe and there are occasions where non-successful response codes will  slip  through"_.

```
-f, --fail
              (HTTP) Fail silently (no output at all) on server  errors.  This
              is  mostly done to better enable scripts etc to better deal with
              failed attempts. In normal cases when an HTTP  server  fails  to
              deliver  a  document,  it  returns  an  HTML document stating so
              (which often also describes why and more). This flag  will  pre-
              vent curl from outputting that and return error 22.

              This  method is not fail-safe and there are occasions where non-
              successful response codes will  slip  through,  especially  when
              authentication is involved (response codes 401 and 407).
```

It will react with meaningful messages to traditional error status codes like `404`, but I just ran a test with `503` and it really downloads the remote page and stops on SHA2 mismatch. It shouldn't even get to any SHA2 checks at the first time.

Related: https://github.com/caskroom/homebrew-cask/issues/7882

Maybe we can run a simple/quick `HEAD` request via `curl -I -L` first and check the HTTP code or are there any different/better plans for this?

Any suggestions about acceptable HTTP codes except `200`?

**Comment by vitorgalvao** [comment]
Closing.

We’ll be merging with Homebrew, so this type of logic belongs there. Also, I’ve built a number of scripts that are in use to manage casks and other operations, and those also check the status code. Not every server responds to those requests, and while a good indicator to have when developing, it’s not good enough to use in production (i.e to affect the user). It is also not a common occurrence, and our usual methods of detection work fine.
