### ISSUE TITLE
console messages from `launchctl unload` during `uninstall`

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#7931]
The uninstall code needs review:
  * `launchctl unload` may be incorrect here
  * `launchctl unload` may have been intended to support pathname values for `uninstall :launchctl`.
  * the console messages may have always been emitted, but suppressed

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/11972.
