### ISSUE TITLE
depends_on :java

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-cask#7993]
I like the idea of [`depends_on :cask => 'cask-name'`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#depends_on-stanza-details), but I feel, that it may not work well with the current naming convention in `caskroom/homebrew-versions`, especially not with Java.

It would has to allow some complicated combinations like:

```
:depends_on :cask => or('java6', 'java7', 'java')
:depends_on :cask => and('java', 'x11')
```
which I don't see as a bad idea, but probably not for Java casks.

I'm not sure if it's something that the actual stanza should be solving or whether we should rather think about better naming convention and more functional metadata - e.g. `brew cask install java -v 7`

Either way we already have many casks (IntelliJ IDEs including [Android Studio](https://github.com/caskroom/homebrew-cask/pull/7921)), that depends on Java, but in reality it's usually **any java**, not a particular version.

I'm just opening discussion here to get some feedback and eventually get to some suggestions/solutions.

**Comment by tsparber** [comment]
Homebrew has a working `depends_on :java` in [java_requirement.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/java_requirement.rb) (So this issue might also benefit from https://github.com/caskroom/homebrew-cask/issues/14384)

**Comment by vitorgalvao** [comment]
@tsparber They do, but it’s no use to use. The only thing it does is exit with an error and tell you java ins’t present but is needed. The first solution is a recommendation to install via homebrew-cask. We need something that actually installs it.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/16383.
