### ISSUE TITLE
require fully-qualified token for operations on unofficial Casks

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#8027]
So this todo item doesn't get lost.  Current behavior is that unofficial must be explicitly Tapped, after which there is no indication which Casks originate in unofficial.

Example:
```bash
$ brew cask install unofficial/bughub
```
Refs https://github.com/caskroom/homebrew-cask/pull/7785#issuecomment-65823501

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/18828
