### ISSUE TITLE
Handling eid casks (location and token)

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#8033]
This was initially a comment on #8026, but it grew so much it’s likely better suited as its own issue.

[`eid-mw.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/eid-mw.rb) could have a better token/name. Looking at it, it seems to be the belgian equivalent to [`cartao-de-cidadao.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cartao-de-cidadao.rb) (portuguese). I’m not sure how widespread this is worldwide, so for those who are not familiar with it, it’s a piece of software designed to allow the user (with an accompanying piece of hardware) to perform a number of (typically government-related) tasks directly with their ID card, right from home (like starting a company).

Installing `eid-mw`, we get an `eID Viewer` app, so that would already be preferable as a name.
![](http://i.imgur.com/nneNeCm.png)

However, it concerns me that other countries might use a similar application with an identical name, and that could cause some confusion and require some changes when it happens.

It does seem to identify itself as `Belgium Identity Card` when installing, which is definitely a clearer and more descriptive name.
![](http://i.imgur.com/tV8cuoO.png)

This type of software should become gradually more popular and useful, at least in Europe, and I really like the idea of allowing users to install it via homebrew-cask (as well as uninstalling it completely, for when you don’t need it anymore). I see two good next steps, here:

+ We set `eid-mw` to something like `eid-be`, and `cartao-de-cidadao` (“citizen’s card”, in portuguese) to `eid-pt`. We possibly create [a new alternate tap](https://github.com/caskroom/homebrew-cask/blob/master/doc/alternate_cask_taps.md#alternate-cask-taps-maintained-by-users) for these, so they’re all neatly organised and we reduce friction in adding the rest of them. It also means they’ll have predictable names, which is good. If we go this route, I volunteer to keep the tap, in case we don’t do it officially. I like this solution because it’s hard to add all of these on our own due to different languages (and lack of knowledge of how each country distributes their respective software). In most cases we should need citizens to add these, and having a different tap with this sole goal could be helpful in publicising this possibility. It also precludes us from having to create yet another specific naming rule on the main repo.
+ We keep everything as is except changing this cask’s token to `belgium-identity-card`, which is more descriptive and easier to know what it is. It also prevents the hypothetical naming conflict reference above.

It should be clear I’m advocating the first solution, but I’m not sure it’s a valuable idea overall, so I’d like some opinions, @caskroom/maintainers.

**Comment by vitorgalvao** [comment]
[This repo is now a reality](https://github.com/caskroom/homebrew-eid).

**Comment by jeroenj** [comment]
Nice. :+1:
