### ISSUE TITLE
Quickcast link no longer updated

### ISSUE THREAD

**Issue by phinze** [caskroom/homebrew-cask#8201]
The link we have has lagged as the Mac AppStore version has continued.

I started a conversation with them on Twitter:

https://twitter.com/phinze/status/545241005159485440

They were planning on only supporting the MAS, but I asked if they'd reconsider. We'll track what happens in this issue, which will result in either an updated link or a removal of the quickcast cask. Here's hoping for the former! :grinning:

**Comment by vitorgalvao** [comment]
@petetak Do you still plan on providing the link and keeping it updated? Asking because I [unrelatedly](https://github.com/caskroom/homebrew-cask/pull/8661), and would like to know how to take care of the cask.
