### ISSUE TITLE
Amethyst cask does not install, retry fails

### ISSUE THREAD

**Issue by eflee** [caskroom/homebrew-cask#8580]
Installing the Amethyst cask stalls on the initial try and then fails on retry with error "no implicit conversion of nil into String"

> (17:23:26) eflee@efleeMac.:~
> % brew cask install amethyst
> ==> Downloading http://ianyh.com/amethyst/versions/Amethyst-0.9.4.zip
> ######################################################################## 100.0%
> ^C
> (17:36:15) eflee@efleeMac.:~
> % brew cask install amethyst
> ==> Downloading http://ianyh.com/amethyst/versions/Amethyst-0.9.4.zip
> Already downloaded: /Library/Caches/Homebrew/amethyst-0.9.4.zip
> Error: no implicit conversion of nil into String
> Please report this bug:
>     https://github.com/caskroom/homebrew-cask/issues
>     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
>     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
>     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
>     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:41:in `block in _check_sums'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:39:in `each'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:39:in `_check_sums'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:32:in `perform'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:72:in `download'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:49:in `install'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `each'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `install_casks'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:6:in `run'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
>     /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
>     /usr/local/bin/brew-cask.rb:42:in `<top (required)>'
>     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>     /usr/local/Library/brew.rb:59:in `require?'
>     /usr/local/Library/brew.rb:142:in `<main>'
>     (17:36:17) eflee@efleeMac.:~

**Comment by ndr-qef** [comment]
You are encountering #7946, an issue which only affects outdated versions of Homebrew-cask. Upgrading should fix it:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by eflee** [comment]
Thanks for the help, that issue and your advice helped me solve the problem
