### ISSUE TITLE
Can't install polyphone

### ISSUE THREAD

**Issue by adius** [caskroom/homebrew-cask#8592]
I have create a new cask for polyphone like this:
```
cask :v1 => 'polyphone' do
  version :latest
  sha256 :no_check
  
  url 'http://sourceforge.net/projects/polyphone/files/latest/download'
  name 'Polyphone'
  homepage 'http://polyphone.fr'
  license :gpl

  app 'Polyphone.app'
end
```

Downloading works, but then I get this error:

```
Error: It seems the symlink source is not there:
'/opt/homebrew-cask/Caskroom/polyphone/latest/Polyphone.app'
```

`/Library/Caches/Homebrew/polyphone-latest` is a zip file which contains the source code of the project.
When I open the cask-url directly, however, it downloads the right `.dmg` file.
Any ideas?

**Comment by rolandwalker** [comment]
Hi!

One issue is that `app` accepts a relative path into the archive, so
```ruby
app 'Polyphone/Polyphone.app'
```

I also had trouble with the `url` above; not sure why.  The following worked better for me:
```ruby
url 'http://downloads.sourceforge.net/project/polyphone/polyphone%20releases/1.5/polyphone-1.5.dmg'
```

If you use the versioned `url`, you should also change `version` and `sha256` to match
```ruby
version '1.5'
sha256 '2eab21617a7cd35252ded1ae0d25404dab8d03a865f6495b61f8990747d1ea20'
```

**Comment by adius** [comment]
The path for app seemed to be ok, but I couldn't get the "latest"-url working.
Maybe somebody should update the wiki: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#sourceforge-urls or was this a polyphone specific problem?

**Comment by vitorgalvao** [comment]
I’ve seen problems crop up with a few sourceforge latest casks, lately. Perhaps something changed on their end. We should keep an eye on it.
