### ISSUE TITLE
busycal (un)installer: does not exit, leaves app behind

### ISSUE THREAD

**Issue by ndr-qef** [caskroom/homebrew-cask#8597]
Refer to https://github.com/caskroom/homebrew-cask/pull/8582#issuecomment-68533044. Reproduced on Mavericks.

Cask `busycal` is a pkg suffering from a variety of (seemingly minor) issues. The installer:
- does not quit post-install. Brew-cask appears to complete the installation successfully, but a dangling `Installer.app` CoreService is left running with an active “open file” dialog.
- opens a Finder window at `/Applications`, which is undesirable from the perspective of a brew-cask as a CLI utility.

The uninstaller:
- appears to succeed, but leaves an empty `BusyCal.app` bundle in `/Applications`. Possibly a defective BOM?
- may require additional steps to complete (refer to [BusyCal Support](https://support.busymac.com/help/35109-how-to-uninstall-busycal)).

**Comment by vitorgalvao** [comment]
Can anyone confirm this is still the case?

**Comment by jawshooah** [comment]
Confirmed that an Installer.app process is left running and a Finder window opened to `/Applications` post-install. Not sure what we can do about that.

Checking now to see if additional steps are required for uninstall.
