### ISSUE TITLE
Error with brew cask install fiji

### ISSUE THREAD

**Issue by nerduno** [caskroom/homebrew-cask#8601]
When attempting to install fiji using brew cask install fiji, I receive the following error:

brew cask install fiji
==> Downloading http://jenkins.imagej.net/job/Stable-Fiji-MacOSX/lastSuccessfulBuild/artifact/fiji-macosx.dmg
######################################################################## 100.0%
Error: undefined method `extname' for 0:Fixnum
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container/criteria.rb:43:in `extension'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container/pkg.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:50:in `block in for_path'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:48:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:48:in `find'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:48:in `for_path'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:83:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:50:in `install'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'

**Comment by ndr-qef** [comment]
Hello @nerduno. You are encountering #7946, which affects outdated versions of `brew-cask`. Upgrading should fix the issue:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

If it does not, let me know.
