### ISSUE TITLE
failed due to bad configuration with Adobe AIR Application Installer.

### ISSUE THREAD

**Issue by wkentaro** [caskroom/homebrew-cask#8606]
I'm creating new cask named `hagaki-design-kit.rb`.
https://github.com/wkentaro/homebrew-cask/blob/hagaki-design-kit/Casks/hagaki-design-kit.rb

It needs download zip file and execute the extracted installer with Adobe AIR Application Installer.
I have error below, could you please help me if you know how to solve this?
```
$ brew cask install hagaki-design-kit
==> Satisfying dependencies
complete
==> Downloading http://img.yubin-nenga.jp/dkit/design_kit.zip
######################################################################## 100.0%
==> Extracting nested container design_kit.air
Error: Command failed to execute!

==> Failed command:
["#<Pathname:/Applications/Utilities/Adobe AIR Application Installer.app/Contents/MacOS/Adobe AIR Application Installer>", "-silent", "-location", "#<Pathname:/opt/homebrew-cask/Caskroom/hagaki-design-kit/8.0.0>", "#<Pathname:/opt/homebrew-cask/Caskroom/hagaki-design-kit/8.0.0/design_kit.air>"]

==> Output of failed command:
failed due to bad configuration


==> Exit status of failed command:
#<Process::Status: pid 75111 exit 9>
```

**Comment by jawshooah** [comment]
I've checked out your `hagaki-design-kit` branch, and it worked for me on the first try. I can only reproduce the error by using `brew cask install --force hagaki-design-kit` when the Cask is already installed. If you have `はがきデザインキット.app` installed somewhere, try uninstalling it first.

**Comment by ndr-qef** [comment]
Adobe Air installers fail with exit 9 when the application is already installed on the system. ([Ref.](http://help.adobe.com/en_US/air/redist/WS485a42d56cd19641-70d979a8124ef20a34b-8000.html#WS485a42d56cd19641-70d979a8124ef20a34b-7ff9))

It is true that ex novo installations will work, but this is still a bug in our handling of `:air` containers. @rolandwalker, it should fairly easy to fix this with the arh utility (described in the documentation linked above, previously discussed in #3421), but that does not ship by default with Adobe Air..

**Comment by rolandwalker** [comment]
Hi @wkentaro !  Thanks!

In principle it is OK to fail when an app has already been installed by some method other than a Cask.  But the error message is unacceptably cryptic.

**Comment by ndr-qef** [comment]
As it seems, my earlier statement about using arh to check for existing installations was too optimistic. arh needs an `appid` which cannot be directly extracted from the AIR installer package.

Regardless, using arh would offer no tangible benefit over merely wrapping the failed command with an error of our own.
