### ISSUE TITLE
brew cask audit - bug

### ISSUE THREAD

**Issue by peterespinosa** [caskroom/homebrew-cask#8617]
```bash
$ brew cask audit        
Error: <main>: syntax error, unexpected tCONSTANT, expecting :: or '[' or '.'
class 010Editor < Cask
               ^
<main>:11: syntax error, unexpected keyword_end, expecting end-of-input while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/010-editor.rb'
```

**Comment by vitorgalvao** [comment]
How long has it been since you ran `brew update`? Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

**Comment by peterespinosa** [comment]
That solved the problem. Thank you very much and sorry about that.

**Comment by ndr-qef** [comment]
Glad the problem is solved. Generally, syntax errors or nil-related woes are caused by the `brew cask` command getting out of sync with the locally stored definition files, and upgrading will fix the issue.
