### ISSUE TITLE
undefined method `any?' for ".":String

### ISSUE THREAD

**Issue by disenchant** [caskroom/homebrew-cask#8630]
As soon as I'm using cask, I'm getting the following error message:

    $ brew cask search test
    Error: undefined method `any?' for ".":String
    Please report this bug:
        http://git.io/brew-troubleshooting
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1394:in `contains_requirable_file?'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:865:in `block in find_inactive_by_path'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find_inactive_by_path'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:175:in `try_activate'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    /usr/local/Library/brew.rb:59:in `require?'
    /usr/local/Library/brew.rb:118:in `<main>'

The same goes for any (even invalid) command that has the form of ```brew cask xyz```. I've already tried ```brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup```. My version of Homebrew is _0.9.5_ and my brew-cask version is _0.52.0_.

And for the sake of completeness:

    $ brew doctor
    Your system is ready to brew.
    $ sw_vers # my OS X version
    ProductName:    Mac OS X
    ProductVersion: 10.10.1
    BuildVersion:   14B25

Maybe this is an issue within Homebrew itself but as it only affects me when trying to use brew-cask, I think this is the right place to get this investigated :smiley:

**Comment by vitorgalvao** [comment]
What’s the output of `brew cask doctor`?

**Comment by disenchant** [comment]
It's the same error message:

    $ brew cask doctor
    Error: undefined method `any?' for ".":String
    Please report this bug:
        http://git.io/brew-troubleshooting
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1394:in `contains_requirable_file?'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:865:in `block in find_inactive_by_path'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find_inactive_by_path'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:175:in `try_activate'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    /usr/local/Library/brew.rb:58:in `require?'
    /usr/local/Library/brew.rb:117:in `<main>'

**Comment by rolandwalker** [comment]
Hi!

This error is occurring 100% in Homebrew's code, not ours, so even if we figured out the cause, we could not fix it.

I do suggest that you try each of
```bash
$ brew uninstall brew-cask
$ brew cleanup
$ brew prune
```

to try to clear up whatever is the problem on your system.  It could be related to something like a dead symlink for the no-longer-used `brew-cask.rb`.  Though that's still a bug, because Homebrew shouldn't raise.

After that, you should make a report to the link http://git.io/brew-troubleshooting as suggested in the error message.

**Comment by ndr-qef** [comment]
The cause appears to be beyond our control. From https://github.com/Homebrew/homebrew/issues/35566:

> It seems like you have a gem that has its require_paths set to a string rather than an array.
> […] it's not a Homebrew bug.
> […] it can also be fixed by upgrading rubygems.
