### ISSUE TITLE
List of officially abandoned apps

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#8638]
This list is likely incomplete.

These apps are all officially abandoned, and may or may not work on newer versions of OS X. They should be checked, and possibly moved to the appropriate repos.

- [ ] [candybar.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/candybar.rb)
- [ ] [google-notifier.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-notifier.rb)
- [ ] [handbrakebatch.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/handbrakebatch.rb)
- [ ] [flow.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/flow.rb)
- [x] ~~[meerkat.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/meerkat.rb)~~ (still works in Mavericks)
- [ ] [milkmaid.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/milkmaid.rb)
- [ ] [panic-unison.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/panic-unison.rb)
- [ ] [perian.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/perian.rb)
- [ ] [rightzoom.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rightzoom.rb)
- [x] ~~[scrup.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/scrup.rb)~~ (still works in Mavericks)
- [ ] [sensiolabsdesktop.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sensiolabsdesktop.rb)
- [x] [sparrow.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sparrow.rb)
- [ ] [temperature-monitor.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/temperature-monitor.rb)
- [ ] [yasu.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yasu.rb)

**Comment by iggyvolz** [comment]
Would depends_on :macos => '< 10.10' or something of the like be appropriate for these casks?

**Comment by vitorgalvao** [comment]
Not necessarily. These might still work perfectly fine on the latest OS X version, in which case they should be left alone. There isn’t a blanket solution for all of them, hence the checklist.

**Comment by Amorymeltzer** [comment]
`meerkat` and `scrup` both seem to work fine for me on 10.9.5

**Comment by pudgereyem** [comment]
It seems like Sparrow is no longer available to download.
At least not from sparrowapp.com.

**Comment by vitorgalvao** [comment]
@pudgereyem Finally down. Thank you.

**Comment by vitorgalvao** [comment]
Closing this as it hasn’t got much traction, and I believe #9255 to be a much better solution (it will also allow for this checklist to be recovered much more reliably in the future, and with more apps).
