### ISSUE TITLE
Can't start cask installed app with Alfred

### ISSUE THREAD

**Issue by thamas** [caskroom/homebrew-cask#8646]
I installed Skype via cask. It is ok, works and I can start it using spotlight search or launchpad etc. However my preferred method to start applications is simple type their name into Alfred's search bar. However it seems, Alfred does not know anything my cask installed Skype, it does not appear in the app list.
Do you have any ideas how to fix this issue?

**Comment by ndr-qef** [comment]
Does `brew cask alfred link` work for you? If not, the most immediate solution would be to open the Alfred preferences GUI and manually add your Cask staging location (defaults to `/opts/homebrew-cask/Caskroom/`) to the search scope.

**Comment by thamas** [comment]
`brew cask alfred link` does not work for me:
`Error: Alfred 2.4+ detected, but local preferences file not found. Try running Alfred first.`
However manually adding Cask staging location resolved my problem!
Thanks for your support!
