### ISSUE TITLE
xbmc not find

### ISSUE THREAD

**Issue by arcticlion** [caskroom/homebrew-cask#8648]
MasterMac:~/ $ brew cask install xbmc                                [20:12:16]
==> Downloading http://mirrors.kodi.tv/releases/osx/x86_64/xbmc-13.2-Gotham-x86_

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'xbmc' with message: Download failed: http://mirrors.kodi.tv/releases/osx/x86_64/xbmc-13.2-Gotham-x86_64.dmg

**Comment by vitorgalvao** [comment]
`xbmc` is now [`kodi`](https://github.com/caskroom/homebrew-cask/blob/0dc0e2375d719d4ed2810a9f19929b6ec5b4da92/Casks/kodi.rb). You should `brew update && brew cask install kodi`.
