### ISSUE TITLE
Cask installing cacoo-ninja failed

### ISSUE THREAD

**Issue by sim4life** [caskroom/homebrew-cask#8649]
I tried to install Cacoo-ninja using homebrew cask but it is failing with this error message:
`Unable to download runtime installer without -allowDownload`
Any clue?

**Comment by vitorgalvao** [comment]
Have you installed `adobe-air` (`brew cask install adobe-air`), like the caveat suggests? Trying to install `cacoo-ninja` without `adobe-air` gives me the error you mention, but installing it with it present works.

You [shouldn’t need to do it manually from now on](https://github.com/caskroom/homebrew-cask/pull/8652).

**Comment by vitorgalvao** [comment]
Closing this. If my solution doesn’t work, please report back and we’ll reopen it.
