### ISSUE TITLE
brew update : Failed to update tap: caskroom/cask, local changes would be overwritten by merge

### ISSUE THREAD

**Issue by jonathanpa** [caskroom/homebrew-cask#8650]
By doing a brew update, I have a problem with Cask. Below the trace:

```
error: Your local changes to the following files would be overwritten by merge:
	Casks/010-editor.rb
	Casks/0ad.rb
	Casks/0xdbe-eap.rb
	Casks/33-rpm.rb
	Casks/4k-video-downloader.rb
        ...
	Casks/shapes.rb
	Casks/simplifyextras.rb
	Casks/smart-scroll.rb
	Casks/spamsieve.rb
	Casks/the-tagger.rb
	Casks/thrustshell.rb
	Casks/yourkit-java-profiler.rb
	lib/vendor/plist.rb
Please move or remove them before you can merge.
Aborting
Error: Failed to update tap: caskroom/cask
Already up-to-date.
```

Please note that I use `Homebrew` with 2 users on my machine, but by setting the permissions wisely, normally I don't have problems.

Thanks

**Comment by iggyvolz** [comment]
If you changed the permissions on the files, that will show as a change to git.

You can tell git to ignore these permissions by running:
```bash
git config core.filemode false
```
from your homebrew cask prefix (I believe it's /usr/local/Library/Taps/homebrew-cask by default but I'm not positive).
You may run into some problems in the future if permissions change to Homebrew Cask.  In that case, you'll want to run:
```bash
git config core.filemode true
git stash
git pull
git stash apply
git config core.filemode false
```
You may have to fix merge conflicts on git stash apply.

**Comment by iggyvolz** [comment]
The directory is /usr/local/Library/Taps/caskroom/homebrew-cask/, not /usr/local/Library/Taps/homebrew-cask/.

**Comment by rolandwalker** [comment]
Hi @jonathanpa!

The message you are getting lists Cask files as being out of date, but the command `brew update` is not our code (it is Homebrew's).  We can help you try to diagnose, but in the end we cannot make any changes to our code that would address the issue.

Homebrew uses git to perform its updates.  The warning originates from git itself.  Git is warning that the files on your disk are out of whack with the changes it wants to make to sync up the repo.  Specifically, the repo at `/usr/local/Library/Taps/caskroom/homebrew-cask/`.

I would try to reset the whole Caskroom Tap, which is easy:
```bash
$ brew untap caskroom/cask
$ ls /usr/local/Library/Taps/caskroom/homebrew-cask/          # this dir should be gone now
$ brew tap caskroom/cask
$ ls /usr/local/Library/Taps/caskroom/homebrew-cask/          # this dir should be back
```

After that, you should be able to run `brew update`.  If you can't, you may need to file an issue with Homebrew.

**Comment by Amorymeltzer** [comment]
@jonathanpa I had this same issue, I think??? it's from a partial/incomplete update on homebrew's part.  Doing the following solved it for me:

````
cd /usr/local
git add .
git fetch origin
git reset --hard origin/master
```

H/T http://stackoverflow.com/q/14113427/2521092 and https://github.com/Homebrew/homebrew/issues/2906#issuecomment-26847664

**Comment by jonathanpa** [comment]
Hi @rolandwalker and @Amorymeltzer !

@Amorymeltzer thanks for your suggestions but it didn't work for me. And `brew untap` `brew tap` did the trick thanks to @rolandwalker.

**Comment by maxadolfsson** [comment]
+1 for `brew untap` + `brew tap`! :+1: 

---

My problem was with `caskroom/versions`:
```
$ brew update
Error: Failed to update tap: caskroom/versions
Already up-to-date.
```

And the following solved it:
```
$ brew untap caskroom/versions
$ brew tap caskroom/versions
```

Thanks @rolandwalker!

**Comment by gnarl** [comment]
Ran into the same issue maxadolsson had with `caskroom/versions`.  Another +1 for use of `brew untap` + `brew tap`!
