### ISSUE TITLE
Wrong number of arguments when installing Firefox

### ISSUE THREAD

**Issue by Blacktiger** [caskroom/homebrew-cask#8669]
---- Begin output of sudo -u martzm /usr/local/bin/brew cask install --appdir=/Applications firefox ----
STDOUT: Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:5:in `name'
<main>:5:in `<class:Firefox>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask.rb:127:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/firefox.rb'
---- End output of sudo -u martzm /usr/local/bin/brew cask install --appdir=/Applications firefox ----

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

**Comment by Blacktiger** [comment]
Ah, thanks.
