### ISSUE TITLE
Firefox Developer Edition

### ISSUE THREAD

**Issue by ccorcos** [caskroom/homebrew-cask#8692]
https://www.mozilla.org/en-US/firefox/developer/

**Comment by ndr-qef** [comment]
Unstable releases generally belong to our [versions tap](https://github.com/caskroom/homebrew-versions). Firefox Developer Edition is already available there as [firefoxdeveloperedition](https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefoxdeveloperedition.rb), and can be installed directly with `brew cask install caskroom/versions/firefoxdeveloperedition`.
