### ISSUE TITLE
Error: undefined method `extname' for 0:Fixnum

### ISSUE THREAD

**Issue by StephenZhuang** [caskroom/homebrew-cask#8715]
```
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container/criteria.rb:43:in `extension'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container/pkg.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:50:in `block in for_path'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:48:in `each'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:48:in `find'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:48:in `for_path'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/installer.rb:83:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/installer.rb:50:in `install'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

**Comment by exaptic** [comment]
Same thing I believe:

➜  Downloads  brew cask install fission
==> Downloading http://neutral.rogueamoeba.com/mirror/files/Fission.zip
######################################################################## 100.0%
Error: undefined method `extname' for 0:Fixnum
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/container/air.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/container.rb:40:in `block in for_path'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/container.rb:38:in `each'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/container.rb:38:in `find'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/container.rb:38:in `for_path'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/installer.rb:67:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/installer.rb:34:in `install'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'

**Comment by ndr-qef** [comment]
You are running an outdated version of Homebrew-cask, which is affected by #7946. Upgrading should fix the issue:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by brotherbain** [comment]
Consider adding a reminder to update in the error message (I know it's fundamental, and many of us should remember, but we all find ourselves the common-sense exception from time to time - I was just now).  This would heighten usability and reduce duplicate submissions.  I love Cask!  Keep up the awesome work!

**Comment by ndr-qef** [comment]
We did add a reminder to upgrade `brew-cask` before reporting… but users will not see it until they upgrade to the first version where it is present, alas!

**Comment by brotherbain** [comment]
aha!  touche!  what a delightful catch-22!  =)
