### ISSUE TITLE
Rename music-manager to google-music-manager

### ISSUE THREAD

**Issue by OliverJAsh** [caskroom/homebrew-cask#8729]
I had trouble finding this cask because of the name’s ambiguity.

**Comment by vitorgalvao** [comment]
We have [strict token rules](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md) in place, for a variety of [reasons](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md#purpose). [A `name` will be added to it](https://github.com/caskroom/homebrew-cask/pull/8730), which should make searching easier, in the future.
