### ISSUE TITLE
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/flash.rb'

### ISSUE THREAD

**Issue by smandava** [caskroom/homebrew-cask#8774]
<main>:5:in `name'
<main>:5:in `<class:Flash>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `eval'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `rescue in load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:69:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask.rb:78:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/list.rb:52:in `list_installed'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/list.rb:10:in `run'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'

**Comment by Andre-487** [comment]
+1 But the same error in `adobe-reader.rb`

**Comment by ndr-qef** [comment]
You are encountering #7946, which can be solved by upgrading to the latest version of homebrew-cask:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

@Andre-487, I am assuming you are experienced the same issue. If the above solution does not work for you, let us know.

**Comment by Andre-487** [comment]
Yes, it works. Thanks!

**Comment by yzwind** [comment]
Thanks!
