### ISSUE TITLE
Error with installing Java: wrong number of arguments

### ISSUE THREAD

**Issue by ttecon** [caskroom/homebrew-cask#8795]
```shell
$ brew cask install java
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/java.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:8:in `name'
<main>:8:in `<class:Java>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask.rb:127:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by ttecon** [comment]
Actually I did update everything and tested multiple times before asking. I now noticed that doing `brew upgrade brew-cask` does not actually work for me. I use OS 10.9.5. and this is what I get:

```
Error: No available formula for brew-cask
```

**Comment by vitorgalvao** [comment]
Your version is very old, though, so the best way to fix it would likely be to uninstall, untap, and retap. `brew update ; brew uninstall brew-cask ; brew untap caskroom/cask ; brew tap caskroom/cask ; brew install brew-cask`.

**Comment by ttecon** [comment]
Thanks. Now I still get an error with this cask. THe new error is:

```
brew cask install java
$HOME/.rvm/scripts/functions/rvmrc_project: line 283: rvm_saved_env: unbound variable
cannot resolve: '/usr/local/bin'
```

**Comment by ttecon** [comment]
Let me know if I should open a new issue for this or not. Thanks!

**Comment by vitorgalvao** [comment]
That’s not a homebrew-cask error, that’s RVM. We don’t touch that; so it’s something on your ruby setup.

**Comment by ttecon** [comment]
This happens on both of my machines. I have Ruby 2.1.0 from RVM. There's nothing unusual. It must be the interaction between RVM and brew cask since brew works fine for me and brew cask used to work. Do you have any suggestion of what this may be?

**Comment by vitorgalvao** [comment]
No, but since this is a new issue, yes, please open a new one, and be sure to post the output of `brew doctor` and `brew cask doctor`.
