### ISSUE TITLE
Script to remove existing apps and replace with cask versions

### ISSUE THREAD

**Issue by johntrandall** [caskroom/homebrew-cask#8820]
Hello. I'm late to the game and just discovered cask. It's awesome thank you. 

Over the years, I've installed lots of apps. There they sit in my applications folder. I've love to switch them all to the brew-cask system. Doing them one-by-one is time-consuming and tedious. I'd love it if there was a way for brew-cask to scan my Applications folder for cask-available apps and 1) build a list of the intersection of what I have and what is available, and then 2) give me the option to batch process the 'delete then reinstall with brew cask' process.

**Comment by johntrandall** [comment]
... and now I've hit the github rate limit from too much 'brew cask search'-ing. :(

**Comment by vitorgalvao** [comment]
@exherb made [a script for that](https://github.com/exherb/homebrew-cask-replacer).

**Comment by johntrandall** [comment]
Thanks @exherb. Your script was very helpful.

I just read the other open tickets on this issue. I posted this on #310. Reposting here.

This task of batch replacement was called 'trivial' on #280. I wouldn't call this trivial at all, and would ask that the devs reconsider. It's actually a pretty time-consuming task. The user must first: (1) take inventory of their installed applications, (2) figure out the app naming convention cask uses and be sure that they are using 'airserver' rather than 'air-server' or whatever, (3) cross reference those installed applications with what is available via cask. This involves either using the website or the command line, and searching a lot on the command line eventually leads to hitting the github API limits. The user must then (4) delete the applications that are going to be replaced, which requires quite a leap of faith. Most new users won't do this, but will instead test a few first. Then the user must (5) install each app and check the results for the occasionally needed manual followup.

For 'power-users' (forgive me for the use of the phrase) that are comfortable enough to use the command line, but live in GUI-app space, Cask is a god-send. But converting everything over to cask installs can be a multi-hour endeavor. Its a major roadblock to adoption of cask. I've been chipping away at this task when I have 10 min here and there for weeks now.

Finally, thanks for developing cask. I'm a very green programmer. I hope to be able to contribute once I have the chops.

**Comment by lorenzk** [comment]
If, like me, you are having trouble with the python tool. Try my ruby version that has no dependencies: https://github.com/lorenzk/brew-cask-replacer
