### ISSUE TITLE
Eclipse casks overwrite each other's symlinks.

### ISSUE THREAD

**Issue by LeoJweda** [caskroom/homebrew-cask#8841]
Since all Eclipse installations have the exact same name "eclipse.app", when a second eclipse cask is installed it overwrites the previous symlink.

**Comment by vitorgalvao** [comment]
We’re aware of it, but that’s an upstream problem, really. Why do they all have the same name to begin with? What do people usually do with them?

We can’t simply start renaming them, as that can break expectations to users.

**Comment by LeoJweda** [comment]
What if instead of renaming the symlinks you just place them in subfolders? It won’t fix the Launcher problem (there will still be only one eclipse) but at least they will be usable by navigating to the Applications folder or using Spotlight. Before I started using Cask I used to just put the different eclipse installations in the Applications directory and open them from there or have them pinned to the dock (another way to use eclipse if the symlinks are in subfolders).

Leo Jweda

**Comment by ndr-qef** [comment]
> We’re aware of it, but that’s an upstream problem, really. Why do they all have the same name to begin with? What do people usually do with them?
>
> We can’t simply start renaming them, as that can break expectations to users.

We do rename the symlink for [scala-ide](https://github.com/caskroom/homebrew-cask/blob/master/Casks/scala-ide.rb), which is part of the Eclipse family of IDEs. While we should add a caveat to notify the user, I feel that this is an acceptable workaround.

**Comment by vitorgalvao** [comment]
> It won’t fix the Launcher problem

I don’t know about other launchers, but in Alfred renaming symlinks wouldn’t solve the issue anyway, as it doesn’t follow them.

> Before I started using Cask I used to just put the different eclipse installations in the Applications directory

They’d still have the same name, so there’s a step you’re skipping, there.

> What if instead of renaming the symlinks you just place them in subfolders?

> I feel that this is an acceptable workaround.

Very much agreed, although #5101 would be a better fit (but that could take a while to happen, if ever). If you submit a PR, we can discuss it better. Taking `eclipse-jee` as the example, something like `app 'eclipse/Eclipse.app', :target => 'eclipse-jee/Eclipse.app'` should be a good starting point.

> We do rename the symlink for scala-ide

But that one also has the weight of having inconsistent branding, so renaming the app bundle’s link is a workaround that also prevents confusion. Putting the other ones in subfolders seems more appropriate.

**Comment by vitorgalvao** [comment]
@LeoJweda Do you intend to submit a PR with the idea?

**Comment by vitorgalvao** [comment]
Seems like there’s no interest in this. Closing.
