### ISSUE TITLE
Says intellij-idea-ce not installed but it is

### ISSUE THREAD

**Issue by samthebest** [caskroom/homebrew-cask#8847]
I do have Intellij Idea 13 installed and I did use brew cask.

```
> brew cask uninstall intellij-idea-ce
Error: intellij-idea-ce is not installed
```

Now since I cannot use the usual "move to trash" way of uninstalling applications, I'm stuck with it! ~~It's existence I think is also stopping me from upgrading to 14.~~

**Comment by vitorgalvao** [comment]
Known issue. We’re working on it. Add `--force` to uninstall it (`brew cask uninstall --force intellij-idea-ce`)

**Comment by samthebest** [comment]
So before you responded I ran `brew cask install intellij-idea-ce`, which then successfully installed Intellij 14.  So now I have two versions, if I where to run `brew cask uninstall --force intellij-idea-ce` I want it to uninstall only Intellij 13.  Is there any way to ensure that?

**Comment by vitorgalvao** [comment]
No, not currently. You’ll have to do it manually.
