### ISSUE TITLE
No symlinks for VirtualBox command line executables

### ISSUE THREAD

**Issue by qtfk** [caskroom/homebrew-cask#8883]
Would it be appropriate for cask to manage the creation (and subsequent deletion upon uninstall) of symlinks to VirtualBox command line executables in /Applications/VirtualBox.app/Contents/MacOS/, including VBoxManage and VBoxHeadless? i.e.:

    ln -s /Applications/VirtualBox.app/Contents/MacOS/VBoxManage /usr/local/bin/VBoxManage
    ln -s /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless /usr/local/bin/VboxHeadless

Another question: does cask check whether the filesystem is case-sensitive? and if so, can it perform additional tasks? such as lowercase equivalents as well:

    ln -s /Applications/VirtualBox.app/Contents/MacOS/VBoxManage /usr/local/bin/vboxmanage
    ln -s /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless /usr/local/bin/vboxheadless

Of course, the uninstall process should include:

    rm -f /usr/local/bin/VBoxManage
    rm -f /usr/local/bin/VBoxHeadless
    rm -f /usr/local/bin/vboxmanage
    rm -f /usr/local/bin/vboxheadless

**Comment by jawshooah** [comment]
Sure! This kind of functionality is supported out of the box:
```ruby
binary '/Applications/VirtualBox.app/Contents/MacOS/VBoxManage', :target => 'vboxmanage'
binary '/Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless', :target => 'vboxheadless'
```
Add those lines, submit a pull request and you're on your way!

**Comment by jawshooah** [comment]
Never mind, it was a quick change so I went ahead and did it myself.

**Comment by ndr-qef** [comment]
For simple app bundles, we symlink included binaries regularly (e.g. [skim](https://github.com/caskroom/homebrew-cask/blob/master/Casks/skim.rb), [vmware-fusion](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vmware-fusion.rb)); symlinks are always converted to lowercase (e.g. [diffmerge](https://github.com/caskroom/homebrew-cask/blob/master/Casks/diffmerge.rb)).

Installers do not offer the convenience of a dedicated stanza, but arbitrary pre- and post-install commands can be set with [`postflight` and `preflight`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#postflight-stanza-details). We use them sparingly, but I would be amenable to recover simple behavior available to other artifacts.

**Comment by jawshooah** [comment]
@ndr-qef Why would `preflight` and `postflight` be necessary here when `binary` will do?

**Comment by ndr-qef** [comment]
`binary` represents an artifact, meaning that it must be available prior to installation. (The stanza expects a path relative to the downloaded archive, albeit absolute paths will also work.) There is no guarantee that `binary` artifacts will be symlinked after the `pkg` installer completes.

**Comment by ndr-qef** [comment]
@qtfk, the binaries are now symlinked. For case-sensitive filesystems, would you find lowercase preferrable?

**Comment by qtfk** [comment]
I would, but would still suggest creating both, as on other systems.
