### ISSUE TITLE
External commands in developer/examples don't work

### ISSUE THREAD

**Issue by Amorymeltzer** [caskroom/homebrew-cask#8889]
I've been in non-computer land for nearly a month, so apologies for not tracking this down to a specific time or release, but none of the scripts in `developer/examples` work for me when called from homebrew-cask.  I personally care about `doutdated.rb` but as an example `showargs` is a simpler case.

With `brewcask-showargs` on my path, running `brew cask showargs foo` just produces the standard error message
````
!!
!! no command verb: showargs
!!
````

I presume(?) it has something to do with the recent move to `Hbc::` namespace in #8575 but that might be just because it's big and new.

**Comment by rolandwalker** [comment]
Welcome, traveller!

These both work fine for me, if I either ensure that the subcommand is on the PATH, or invoke it directly:
```bash
$ PATH="${PATH}:/usr/local/Library/Taps/caskroom/homebrew-cask/developer/examples/" brew cask showargs foo
foo
$ brew cask /usr/local/Library/Taps/caskroom/homebrew-cask/developer/examples/showargs foo
foo
```

It is true that the transition to the `Hbc::` namespace is still a work-in-progress.  However, for this specific case, I tend to suspect #8089 for changing subtle things about the invocation environment.

**Comment by Amorymeltzer** [comment]
I was about to say that I'd done both those and still failed, @rolandwalker, but those *exact* examples actually worked - it's something to do with my use of `~` in my `$PATH`.  I was placing and using these commands in `~/bin` (`~/bin` symlinks to `~/dotfiles/bin` which has a symlink to the `examples` folder); `~/bin` was added to path via `.bash_profile`.  That addition was the only part of my path using `~`, and placing the scripts elsewhere in my `$PATH` work fine.  When I changed `~/bin` to `$HOME/bin` in `.bash_profile` the external commands worked again.  So thanks!

I'll have to dig deeper into #8089 for why, but I also recently went from `bash-4.3.30` to `bash-4.3.33` so perhaps the subtle change in path-handling is on that end.

**Comment by rolandwalker** [comment]
Ah, good report.  It's not #8089 but one of the many followons to that, which I ought to have crossreferenced. (For reference, most are listed under release [v0.52.0](https://github.com/caskroom/homebrew-cask/releases/tag/v0.52.0)).

Your issue looks to be caused by #8561, in which I apparently [dropped an `expand_path`](https://github.com/caskroom/homebrew-cask/pull/8561/files#diff-f6746790db8480b7ae30d3f428faa897L72).
