### ISSUE TITLE
Error from cask audit

### ISSUE THREAD

**Issue by sngliwei** [caskroom/homebrew-cask#8890]
Got this when I tried to do an audit:

$ brew cask audit
Error: <main>: syntax error, unexpected tCONSTANT, expecting :: or '[' or '.'
class 010Editor < Cask
               ^
<main>:12: syntax error, unexpected keyword_end, expecting end-of-input while loading '/usr/local/homebrew/Library/Taps/caskroom/homebrew-cask/Casks/010-editor.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `eval'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `rescue in load'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:69:in `load'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/source/tapped.rb:33:in `load'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask.rb:78:in `load'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/scopes.rb:8:in `block in all'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/scopes.rb:8:in `map'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/scopes.rb:8:in `all'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/cli/audit.rb:40:in `casks_to_audit'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/cli/audit.rb:23:in `run'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/cli/audit.rb:7:in `run'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/homebrew/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/homebrew/Library/brew.rb:58:in `require?'
/usr/local/homebrew/Library/brew.rb:142:in `<main>'

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by sngliwei** [comment]
Thanks, I though I did that already but must have missed a command somewhere :) Works now!
