### ISSUE TITLE
Enhance araxis-merge cask to link command line utilities

### ISSUE THREAD

**Issue by RogerThiede** [caskroom/homebrew-cask#8899]
http://www.araxis.com/merge/documentation-os-x/installing.en recommends optional instructions to install the merge command line utilities:
> Ensure that the Utilities folder within the Araxis Merge application bundle is part of your command-line shell’s search path.

**~/Applications/Araxis Merge.app/Contents/Utilities/**
* araxisgitdiff
* araxisgitmerge
* araxishgmerge
* araxisopendiff
* araxisp4diff
* araxisp4winmrg
* araxissvndiff
* araxissvndiff3
* araxissvnmerge
* compare
* compare2

Instead of modifying the user's PATH environment variable, enhance the araxis-merge cask to create sym-links for each command line utility in $(brew --prefix)/bin pointing to the Araxis Merge application bundle path.  Curiously, the application bundle path may have been modified such as with HOMEBREW_CASK_OPTS="--appdir=/Applications"

I believe the cask binary stanza would suffice for this:
`binary 'Araxis Merge.app/Contents/Utilities/araxisgitdiff', :target => 'araxisgitdiff'`

**Comment by ndr-qef** [comment]
Symlinks added in 065a5ec.
