### ISSUE TITLE
scansnap-manager is only for the SV600

### ISSUE THREAD

**Issue by bronson** [caskroom/homebrew-cask#8938]
Hi, Fujitsu releases a different version of scansnap-manager for many of its scanners.  This Cask, which installs version 6.2L10, is only correct for the SV600 and IX500.  All other ScanSnap devices require a different version of the manager.

You can see the problem on this page: http://www.fujitsu.com/global/support/computing/peripheral/scanners/software/

- the SV600 requires version 6.2L10   (the ScanSnap Manager included in this cask)
- the S1100i requires V6.3L21
- S1100: V3.2L31
- S1300i:  V6.2L22
- S1300: V3.2L31
- S300: V4.2L14
- S300M: V2.2L11
- and so on...  what a nightmare.

Does it make sense to make a separate cask for each scanner?  scansnap-manager-sv600, scansnap-manager-s1300i, scansnap-manager-s300m, etc?

If not, maybe deleting this cask is the correct thing to do?  Right now it's pretty misleading.

**Comment by vitorgalvao** [comment]
I wouldn’t be opposed to removing it entirely.

[Having said that](http://youtu.be/ENHVQ2gslp8), we could certainly create one for each of them, and put them all in [caskroom/versions](https://github.com/caskroom/homebrew-versions) (including the one present here now). Either way, the one in the main repo should be removed.

**Comment by vitorgalvao** [comment]
@mbrgm is starting made a first step towards the second proposed solution in https://github.com/caskroom/homebrew-versions/pull/703. Letting you know in case you’d be interested in collaborating to get the rest of them there.

**Comment by vitorgalvao** [comment]
@mbrgm made a first step towards the second proposed solution in https://github.com/caskroom/homebrew-versions/pull/703. Letting you know in case you’d be interested in collaborating to get the rest of them there.

Not pressuring any of you to do it, naturally, just pointing out there might be a common interest in having this done.

**Comment by mbrgm** [comment]
I think I'll start by renaming the existing casks to reflect the matching scanner model, i.e. `scansnap-manager-s1300`, `scansnap-manager-sv600` etc.

**Comment by vitorgalvao** [comment]
Sounds good; makes sense to me.

**Comment by mbrgm** [comment]
Is there some way to 'symlink'/alias a cask? Some versions are for multiple models, so I would create an alias for every model. Another solution would be to name it according to the models, i.e. `scansnap-manager-s300-s500m-s510`. I think our goal should be to help the user decide which version she needs for her model. She will most likely know the model name but not the version number of the software needed. Thoughts?

**Comment by vitorgalvao** [comment]
> Is there some way to 'symlink'/alias a cask?

There is not, though [there may be in the future](https://github.com/caskroom/homebrew-cask/issues/8492).

> Another solution would be to name it according to the models, i.e. `scansnap-manager-s300-s500m-s510`.

Agreed. Seems like the best solution. Inside the cask itself we could leverage `name` to make explicit that the same cask works for those models:

```ruby
name 'ScanSnap Manager for model S300'
name 'ScanSnap Manager for model S500M'
name 'ScanSnap Manager for model S510'
```

Searching by `name` ins’t yet possible, but being worked on.

**Comment by mbrgm** [comment]
Agreed. I took a look at the metacask proposal. Sounds promising. In the meantime, the naming will be a convenient solution. We can refactor this later, when metacasks are available.

**Comment by bronson** [comment]
Sounds like a decent direction given the limitations.  @mbrgm tell me if you can use help/testing for the S1300i.

**Comment by mbrgm** [comment]
@bronson You can take a look at the changes I made in caskroom/homebrew-versions#703 if you want. Maybe you could add the S1300i in a similar fashion.

**Comment by vitorgalvao** [comment]
Done in https://github.com/caskroom/homebrew-versions/pull/703 by @mbrgm.
