### ISSUE TITLE
Lingon-X uninstaller does not remove Global Daemons

### ISSUE THREAD

**Issue by johntrandall** [caskroom/homebrew-cask#8949]
Lingon-X uninstaller does not remove Global Daemon. 

I can remove them using the launchctrl GUI tool, but I don't know how to do it programatically- so I don't know how to fix it. :(

**Comment by vitorgalvao** [comment]
There are [scripts](https://github.com/phinze/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/phinze/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) geared for that.

You can take a look and see what you can manage. Feel free to ask for help if you get stuck.

**Comment by johntrandall** [comment]
Thanks. 

Nevermind - it doesn't seem as though those daemons are used or added by current versions. This was from legacy Lingon 1.0 stuff. My mistake.
