### ISSUE TITLE
NoMachine install fails sha256 check

### ISSUE THREAD

**Issue by johntrandall** [caskroom/homebrew-cask#8950]
$  brew cask install nomachine
    ==> Downloading http://download.nomachine.com/download/4.3/MacOSX/nomachine_4.3.30_4.dmg    
    ######################################################################## 100.0%
    ==> Note: running "brew update" may fix sha256 checksum errors
    Error: sha256 mismatch
    Expected: d2a84877f3e3ebd4ea935b3de52ebffc3e4fcb6e2f3e9ff3d2bfca441915784b
    Actual: dd2298882557699617dae3a224012ab70f7bf7e015759682482be8ff82c76c40
    File: /Library/Caches/Homebrew/nomachine-4.3.30_4.dmg
    To retry an incomplete download, remove the file above.

**Comment by rishirdua** [comment]
Getting the error again


Error: sha256 mismatch
Expected: 66a96316387833217c12452abdc78fdc1bbda698857fc8b6d2d26b5f474cc8b0
Actual: 60988b21e8c41dc35d50aa1748d367cb5bbc58db17bfc36bca036969267086b9
File: /Library/Caches/Homebrew/nomachine-4.6.4_28.dmg
To retry an incomplete download, remove the file above.
rishidua-macbookpro:~ rishidua$

**Comment by vitorgalvao** [comment]
@rishirdua You need to `brew update`, first.

**Comment by rishirdua** [comment]
Thanks @vitorgalvao 

The following helped

```
#run this if brew update fails (http://stackoverflow.com/a/20138806/1866159)

cd `brew --prefix`
git fetch origin
git reset --hard origin/master


#update brew
brew update


#retry
brew cask install nomachine
```
