### ISSUE TITLE
Host the files on Github

### ISSUE THREAD

**Issue by littlebang** [caskroom/homebrew-cask#8975]
googlecode.com always broken in China,could you host the files on Github,so we can install it...

Thanks

**Comment by vitorgalvao** [comment]
The files are hosted on github (where you are now). If you are referring to the casks in the casks themselves, I’m sorry but we can’t help you — we don’t host the software, we just link to the official download links given by the authors. If you need them to be hosted somewhere else, you’ll need to talk to the developers of each specific software.

**Comment by littlebang** [comment]
@vitorgalvao :+1:
