### ISSUE TITLE
pdfsam namechange

### ISSUE THREAD

**Issue by Amorymeltzer** [caskroom/homebrew-cask#9061]
@vitorgalvao pdfsam was just updated from 2.2.2 to 2.2.4 in #9049, but the creators saw fit to change the name of the application to `PDFsam Basic 2.2.4.app`, which results in:

`Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/pdfsam/2.2.4/pdfsam.app'`

There is an "enhanced version" (http://www.pdfsam.org/enhanced-version/) hence the name change.

**Comment by vitorgalvao** [comment]
Thank you for the heads-up. I’ve only checked the app had a new version. Will fix soon.
