### ISSUE TITLE
Please add privacy_services_manager + management-tools

### ISSUE THREAD

**Issue by MoOx** [caskroom/homebrew-cask#9068]
I just found those 2 greats libraries

https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager
https://github.com/univ-of-utah-marriott-library-apple/management_tools

They are offered as dmg, so maybe it would be nice to have them around :)

**Comment by vitorgalvao** [comment]
@jawshooah is taking care of these. [One merged](https://github.com/caskroom/homebrew-cask/pull/9077), [the other](https://github.com/caskroom/homebrew-cask/pull/9078) should be soon.

**Comment by MoOx** [comment]
You are awesome guys!
