### ISSUE TITLE
error cask install java

### ISSUE THREAD

**Issue by yeluolei** [caskroom/homebrew-cask#9069]
I have already updated to the latest taps, and got the following error when try to run 

[code]$ brew cask install java[/code]

Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/java.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:8:in `name'
<main>:8:in `<class:Java>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'

**Comment by yeluolei** [comment]
see issue #8795

**Comment by devth** [comment]
@rolandwalker if it's a duplicate, what is it a duplicate of?

**Comment by iggyvolz** [comment]
#8795.

>You’re using an old version of homebrew-cask. Please brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup and try again.

**Comment by devth** [comment]
@iggyvolz thx
