### ISSUE TITLE
Error symlinking Temperaturemonitor

### ISSUE THREAD

**Issue by MalcolmK** [caskroom/homebrew-cask#9181]
Hey I've got this error:

`Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/temperaturemonitor/latest/TemperatureMonitorLite.app'`

According to other issues, it seems this is app related? Can I fix this myself?

**Comment by vitorgalvao** [comment]
> According to other issues, it seems this is app related? Can I fix this myself?

Yes to both questions. What this means is there were some structural changes to the package, meaning either `TemperatureMonitorLite.app` no longer exists inside the dmg or it was moved to somewhere else (inside a sub-directory), or had its name changed. If you find which, correcting it is trivial. I’ll be waiting for your Pull Request. If you have any question in the process, feel free to ask.

**Comment by MalcolmK** [comment]
Okay, and how can I determine this? Do I have to download the normal app? I have done some searching, and it seems this product is end of life. So I guess it's not wise to use it anymore, due to the fact it is not maintained anymore.

**Comment by vitorgalvao** [comment]
> Do I have to download the normal app?

Yes. Just as you’d do if adding a new cask. Regarding it being discontinued, it’ll be added to #8638, but as long as it works, it should remain.

**Comment by MalcolmK** [comment]
Okay, well I actually wanted to download this app just to see what it does. So I'm sorry to say, but I don't need it that desperately that I can afford to take so much time for it. I'm sorry :(

**Comment by vitorgalvao** [comment]
#9219.

This is a simple issue. It took less than two minutes to identify and solve (literally, I looked at the clock); it can be done in less time than it took you to search before opening the issue, and certainly less time than it took to figure out it’s no longer maintained.

Only thing to do was download the dmg and open it; you don’t even have to copy them apps out.
![](http://i.imgur.com/xDU9ecG.png)

I really don’t understand how you though this would take any significant amount of time. Was my explanation inadequate? Were any of the steps unclear? I’m asking in all honesty: helping with this issues is something I spend a lot of time on, so if I was unclear I’d like to know, as that’ll benefit future resolutions.

**Comment by MalcolmK** [comment]
Well I don't know. I thought is was a way more work. And to be honest, it is still not clear to me what you have done :$

FYI: it still doesn't seem to work :)

![image](https://cloud.githubusercontent.com/assets/2427717/5892921/b6041ba0-a4d1-11e4-9bcf-0a77feb4d7c8.png)

**Comment by vitorgalvao** [comment]
Had another look at it, and this one was actually a bit more complex (not much more, but still required use of a Terminal). It was a similar case to [this](https://github.com/caskroom/homebrew-cask/pull/3838#issuecomment-40745553). Should be fixed now.
