### ISSUE TITLE
Referencing staged_path in installer stanza

### ISSUE THREAD

**Issue by ncliang** [caskroom/homebrew-cask#9183]
Hi there,

I am trying to write a cask for an application with a custom installer. The installer allows for passing the installation location on the command line in unattended installs. If not set, it defaults to install into /Applications.

I can get things working if I hardcode the installation path to /opt/homebrew-cask/Caskroom/..., but what I'd really like is to access staged_path like this: 

```ruby
  installer :script => 'JProfiler Installer.app/Contents/MacOS/JavaApplicationStub',
            :args => ['-q', '-dir', "#{staged_path}"]
```

When I do that, I get a warning and the directory ends up an empty string:

```
Warning: Unexpected method 'staged_path' called on Cask jprofiler.
...
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/jprofiler/8.1.2/JProfiler Installer.app/Contents/MacOS/JavaApplicationStub>", "-q", "-dir", ""]
```

Is this behavior expected? How should I tell the installer to install into the staging path instead of /Applications? Any help will be greatly appreciated.

Disclaimer: I've never used Ruby before, nor written any casks.

**Comment by vitorgalvao** [comment]
`#{staged_path}` [is only available in blocks](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#caveats-as-a-string). [This comment](https://github.com/caskroom/homebrew-cask/pull/7843#issuecomment-65914302) might explain better.

[There is a PR meant to fix it](https://github.com/caskroom/homebrew-cask/pull/8887) but it hasn’t been looked at, yet.
