### ISSUE TITLE
Request: Adobe Flash Pepper Player

### ISSUE THREAD

**Issue by wfdd** [caskroom/homebrew-cask#9193]
NPAPI support has finally been removed from Chromium trunk (v42). Would we consider providing a second, PPAPI cask? The latest PPAPI installer can be found [here](https://get.adobe.com/flashplayer/otherversions/).

**Comment by vitorgalvao** [comment]
Yes, why not? As `pepper-flash`, it’d make sense.

**Comment by wfdd** [comment]
Can we not use the full installer? The web downloader throws an "Application Initialization error" after it's been unpacked.
