### ISSUE TITLE
Don't overwrite existing binary symlinks by default

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#9202]
Continuing the conversation started in #9199, as this is a better place for it.

We should not be overwriting existing symlinks in the user's `binarydir` by default. We should use `readlink` to ensure that the existing symlink points back to the cask or a previous version of it.

The user could then force overwriting by adding a `--force-overwrite` flag or something similar.

**Comment by jawshooah** [comment]
The `conflicts_with` stanza, once implemented, will alleviate the need for this restraint for the most part, as most conflicts will likely come from Homebrew formulae. However, it is entirely possible that the user will have installed third-party binaries to that directory as well, and we should be careful not to overwrite those unless the user asks us to.

**Comment by jawshooah** [comment]
On a related note, I'd be happy to write up an implementation of `conflicts_with` if no one is assigned yet.

**Comment by vitorgalvao** [comment]
[Seems like no one is](https://github.com/caskroom/homebrew-cask/issues/4497).

**Comment by jawshooah** [comment]
Any chance I could be added as a collaborator so it can be assigned to me?

**Comment by vitorgalvao** [comment]
I think we’re not currently looking to expand the team, but I’ll look into it in the next few days and give you a definite answer. In the meantime, I’ll post a comment to the relevant issue stating you wish to work on the feature.

**Comment by vitorgalvao** [comment]
> Any chance I could be added as a collaborator so it can be assigned to me?

Took a while (too long), but I’m pleased to say the answer is finally “yes”. Assigning you now.

**Comment by vitorgalvao** [comment]
On second thought, since that was only pertaining the DSL and not the feature itself, I’ll close that one and open a new one for the feature.

**Comment by vitorgalvao** [comment]
Marking as `ready to implement`.

**Comment by reitermarkus** [comment]
This is now implemented. The installation will fail if a binary already exists and revert all previous steps (if there were any).
