### ISSUE TITLE
Should shim scripts be implemented?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#9203]
This issue surfaces from time to time: a cask, after installed, has some limitation on its CLI tools, caused either by some choice from upstream or the nature of how we install things (linking).

Many times this can be resolved (read “worked around”) by a small shell script only a few lines long. So far we have restrained from accepting such solutions, and to an extent that is a good thing. [Sometimes upstream takes notice and fixes the problem](https://github.com/caskroom/homebrew-cask/issues/7766#issuecomment-65533593) but those cases are clearly the minority. In the other cases it could be [convenient](https://github.com/caskroom/homebrew-cask/pull/9101), [provide consitency](https://github.com/caskroom/homebrew-cask/pull/8860), [fix cases that don’t play well with links](https://github.com/caskroom/homebrew-cask/issues/4188), or outright [facilitate installs and unintalls](https://github.com/caskroom/homebrew-cask/pull/8279).

The more I look at it, the less I think it’s a good idea to not support such a capability. Speaking in purely practical terms, I see this as analogous to using `:no_check` with versioned casks — we *can* live without it, but it is a worse experience than living with it. Similarly, I do think it should be used sparingly and only as a last resort.

**Comment by jawshooah** [comment]
:+1: Agreed on all points. We would probably want to provide convenience methods like Homebrew's [`write_exec_script`](https://github.com/Homebrew/homebrew/blob/b07847607480e478565f4e7616252c6611cc4354/Library/Homebrew/extend/pathname.rb#L354), [`write_env_script`](https://github.com/Homebrew/homebrew/blob/b07847607480e478565f4e7616252c6611cc4354/Library/Homebrew/extend/pathname.rb#L371), and/or [`write_jar_script`](https://github.com/Homebrew/homebrew/blob/b07847607480e478565f4e7616252c6611cc4354/Library/Homebrew/extend/pathname.rb#L392).

**Comment by phinze** [comment]
Also agreed on all points!

@vitorgalvao is this mainly a PR acceptance policy question or mainly a feature question?

Re the latter - It'd be nice if we could provide some basic convenience methods, but I'd worry about going too deep down that rabbit hole to the point where we accidentally encourage shims where they are unnecessary. We should make sure any convenience methods we support properly communicate the "should be used sparingly" part.

**Comment by vitorgalvao** [comment]
> is this mainly a PR acceptance policy question or mainly a feature question?

Mainly about accepting such PRs. However, I agree in full with your comment and do think an officially supported way should exist. The current way to do it is hacky (well, maybe the word should be “inelegant”), and an official solution would go a long way towards readability and maintainability.

> We should make sure any convenience methods we support properly communicate the "should be used sparingly" part.

As [we do with `:target`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#target-should-only-be-used-in-select-cases), a comment on why the script is needed with a link back to the discussion seems like a must.

**Comment by phinze** [comment]
Cool cool - sounds like we're on the same page about the acceptance policy.

Then we just need to decide what the shim script API would look like. @jawshooah gave us a few starting points. Any other ideas on this?

**Comment by ndr-qef** [comment]
Quoth @rolandwalker: https://github.com/caskroom/homebrew-cask/issues/4188#issuecomment-45935786.

**Comment by radeksimko** [comment]
:+1: Agreed with all points and yes, there should be a decent API to make such things less hacky.

**Comment by rolandwalker** [comment]
My preferred interface would involve the word "method".  Once we refactor symlink/hardlink out of the artifact code, we can think of at least these methods for activating a staged artifact:
* symlink
* hardlink
* dir-hardlink
* copy
* shim

I don't know how it would look, exactly, because sometimes an artifact type has an inherent preferred method, sometimes a Cask will want to override the method, and it would be ideal if the user could also
```bash
$ brew cask install --method=copy google-chrome
```

We don't need to do any of those things to implement shims.  It's just nice to think generally and be consistent with other desired future functionality.

Homebrew's interface is a mismatch for these goals.

**Comment by phinze** [comment]
Ooo I like that a lot @rolandwalker - the other word that comes to mind is "strategy". I'll think more on this and get back to you.

**Comment by rolandwalker** [comment]
"Strategy" is also agreeable because it is abstract.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/18809.
