### ISSUE TITLE
hashcat installing problem

### ISSUE THREAD

**Issue by Drewshg312** [caskroom/homebrew-cask#9236]
$ brew cask install hashcat
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
unar ... done
complete
==> Downloading https://hashcat.net/files/hashcat-0.48.7z
######################################################################## 100,0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 39fee1757b33b3e7232ce3797f0be024fa784dbbd0939b475b5b1ea7462cec5e
Actual: 66292c06478386b1bfdd46ef4b59e52445235b3e723281e65e9c4d1db867da0b
File: /Library/Caches/Homebrew/hashcat-0.48.7z
To retry an incomplete download, remove the file above.

**Comment by Drewshg312** [comment]
So what should I do with this?

**Comment by vitorgalvao** [comment]
Nothing, it’s fixed. Just `brew update` and try again.

**Comment by vitorgalvao** [comment]
Nothing, it’s fixed. Just `brew update` and try again. Thank you for reporting the problem.

**Comment by Drewshg312** [comment]
oh, ok! Thank you!
