### ISSUE TITLE
The checksum of "munki" may be incorrect

### ISSUE THREAD

**Issue by JasonGao180** [caskroom/homebrew-cask#9271]
```
$ brew install Caskroom/cask/munki
==> brew cask install Caskroom/cask/munki
==> Downloading https://github.com/munki/munki/releases/download/v2.0.1/munkitools-2.0.1.2253.pkg
Already downloaded: /Library/Caches/Homebrew/munki-2.0.1.pkg
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: f4b586c254fcd47f54d4b58ea7c43308ee1472b41f03e7b59ceb9fd6605a54b8
Actual: 126700a36f54d0427e62102be9c1b2faadd4460a293758d6ea1a0f22e3e736a8
File: /Library/Caches/Homebrew/munki-2.0.1.pkg
To retry an incomplete download, remove the file above.
```

I downloaded the https://github.com/munki/munki/releases/download/v2.0.1/munkitools-2.0.1.2253.pkg manually, the sha256 checksum is really 126700a36f54d0427e62102be9c1b2faadd4460a293758d6ea1a0f22e3e736a8.

Could someone verify it?

**Comment by Amorymeltzer** [comment]
Hi @JasonGao180, thanks for the catch!  I get the same thing, but it's out of date anyhow - munki's latest release is 2.1.1.2352.  I've gone and filed a PR to fix this, thanks again!

**Comment by exherb** [comment]
@andrewoke still need me to submit a PR to fix this or have you already done it?
