### ISSUE TITLE
Wrong number of arguments when brew cask install telegram

### ISSUE THREAD

**Issue by ifosch** [caskroom/homebrew-cask#9280]
Hi!

I'm trying to install telegram with cask, but I get:

    Error: wrong number of arguments (1 for 0) while loading '/Users/ifosch/src/github.com/mxcl/homebrew/Library/Taps/caskroom/homebrew-cask/Casks/telegram.rb'
    Please report this bug:
        https://github.com/caskroom/homebrew-cask/issues
    <main>:6:in `name'
    <main>:6:in `<class:Telegram>'
    <main>:in `<main>'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `eval'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `rescue in load'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:52:in `load'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/source/tapped.rb:28:in `load'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask.rb:127:in `load'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:19:in `block in install_casks'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `each'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `install_casks'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:6:in `run'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
    /Users/ifosch/src/github.com/mxcl/homebrew/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
    /usr/local/bin/brew-cask.rb:42:in `<top (required)>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /Users/ifosch/src/github.com/mxcl/homebrew/Library/brew.rb:58:in `require?'
    /Users/ifosch/src/github.com/mxcl/homebrew/Library/brew.rb:141:in `<main>'

I'm not sure, but I think I might have something outdated. I tried with `brew update` and `brew cask update`, but it didn't helped.
Anyone had this before?

Thank you so much

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by ifosch** [comment]
Ok, thank you so much, sorry, I just got redirected to the issues page directly, from the terminal link.

**Comment by vitorgalvao** [comment]
Yes, the message on how to upgrade was added in a later version.
