### ISSUE TITLE
brew cask alfred link reports "no command verb: alfred"

### ISSUE THREAD

**Issue by welly** [caskroom/homebrew-cask#9299]
Trying to resolve the issue with Alfred not finding cask installed applications with the suggested brew cask alfred link. Unfortunately every time it fails reporting: no command verb: alfred and then displays the commands available.

Any ideas?

Thanks!

**Comment by vitorgalvao** [comment]
Alfred support [was removed](https://github.com/caskroom/homebrew-cask/pull/8840) since it’s [no longer needed](https://github.com/caskroom/homebrew-cask/issues/8052#issuecomment-69560606). If you installation precedes this, you may need to add the directory manually.
