### ISSUE TITLE
qt-creator expired SSL certificate - curl throws error

### ISSUE THREAD

**Issue by DanTheColoradan** [caskroom/homebrew-cask#9336]
This might resolve itself once they have a new certificate, but as of right now, I can't install qt-creator since qt's certificate is expired. Curl throws an error about it.

Maybe I'm missing something though.

```
brew cask install Caskroom/cask/qt-creator
==> Downloading https://download.qt-project.org/official_releases/qtcreator/3.3/3.3.0/qt-creator-opensource-mac-x86_64-3.3.0.dmg

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Download failed on Cask 'qt-creator' with message: Download failed: https://download.qt-project.org/official_releases/qtcreator/3.3/3.3.0/qt-creator-opensource-mac-x86_64-3.3.0.dmg
```

**Comment by vitorgalvao** [comment]
The immediate solution would be to `brew cask edit qt-creator`; delete the `s` from `https`; save and retry.

That works, and we could change the cask, but I think we should wait two or three days to see if they fix it.

**Comment by DanTheColoradan** [comment]
That did the trick. I forgot there was a way to easily edit brew / brew-cask formulas. Thank you!

I’m not sure if this issue should be closed or not. I can keep an eye the expired certificate if you’d like.

**Comment by vitorgalvao** [comment]
> I can keep an eye the expired certificate if you’d like.

Yes, please. Lets keep this open a few days and see. If they don’t correct it, we might as well change it to `http` here and close the issue.

**Comment by DanTheColoradan** [comment]
Just an update. It looks like their certificate is still invalid.

**Comment by vitorgalvao** [comment]
Thank you for checking back. Let’s change it, then. I’ll do it in a few minutes.
