### ISSUE TITLE
Can't localize LibreOffice

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#9352]
LibreOffice installed from cask can't be localized because user can't select LibreOffice path in official localization installer. LibreOffice localization packs is wrapped in app (and dmg obviously) that installs required files in LibreOffice.app. They have broken something in recent release so installer is asking for app path even if you install it in official way, but it does not recognize symlinks. So to localize the brewed version one needs to navigate to /opt/... but it is hidden by default.

**Comment by Yann-R** [comment]
Hello,
Did something change very recently inside the lastly released versions?
Two weeks ago I personally managed to localize (with the little tool from libreoffice.org) the last release of LibreOffice (4.4.0) that I installed with `brew cask`.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is definitely non-urgent, and can be revisited later. There is some restructuring planned that should make cases like more of a possibility, in the future.
