### ISSUE TITLE
Slack shown under `cask list` but uninstall says not installed

### ISSUE THREAD

**Issue by jasonkarns** [caskroom/homebrew-cask#9383]
`brew cask list` includes slack, but `brew info slack` says not installed, and `brew cask uninstall slack` also says it's not installed. However, slack is definitely in the Caskroom (under `/opt/homebrew-cask/`).

How do I uninstall/remove slack?

**Comment by vitorgalvao** [comment]
Duplicate of https://github.com/caskroom/homebrew-cask/issues/2988.

Uninstall by passing the `--force` flag.

**Comment by jasonkarns** [comment]
thanks
