### ISSUE TITLE
TextWrangler Wrong Number of Arguments (1 for 0) While loading textwrangler.rb

### ISSUE THREAD

**Issue by weems** [caskroom/homebrew-cask#9439]
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/textwrangler.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:7:in `name'
<main>:7:in `<class:Textwrangler>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `eval'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `rescue in load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:69:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/tapped.rb:33:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask.rb:78:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'

**Comment by Amorymeltzer** [comment]
Hi @weems, you're using an outdated version of homebrew-cask, upgrading via the following should set you straight:
`brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`
