### ISSUE TITLE
Brackets install - Error: Broken pipe

### ISSUE THREAD

**Issue by thesbros** [caskroom/homebrew-cask#9448]
When running `brew cask install brackets` or `brew cask install --force brackets`, the following error shows up:
```bash
▶ brew cask install --force --verbose brackets
==> Downloading https://github.com/adobe/brackets/releases/download/release-1.1/Brackets.Release.1.1.dmg
Already downloaded: /Library/Caches/Homebrew/brackets-1.1.dmg
Error: Broken pipe

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/system_command.rb:14:in `write'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/system_command.rb:14:in `puts'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/system_command.rb:14:in `block in run'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/system_command.rb:14:in `each'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/system_command.rb:14:in `run'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/container/dmg.rb:34:in `mount!'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/container/dmg.rb:13:in `extract'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/installer.rb:103:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/installer.rb:62:in `install'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli.rb:78:in `run_command'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli.rb:118:in `process'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
```
I ran `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and it still happens.

**Comment by phinze** [comment]
Hmm that's not good! Let me see if I can repro over here.

**Comment by ndr-qef** [comment]
I am unable to reproduce in either Yosemite or Mavericks.

**Comment by phinze** [comment]
Yeah unfortunately same here - installs AOK for me.

Looks like the command that failed is:

```
hdiutil mount -plist -nobrowse -readonly -noidme -mountrandom /tmp  /Library/Caches/Homebrew/brackets-1.1.dmg
```

You can try running that by itself to see if it spits out a useful error message.

You could also try a just opening `/Library/Caches/Homebrew/brackets-1.1.dmg` to see if that shed any additional light.

**Comment by thesbros** [comment]
Odd, now when I run it it's giving me:
```bash
▶ brew cask install brackets
==> Downloading https://github.com/adobe/brackets/releases/download/release-1.1/
Already downloaded: /Library/Caches/Homebrew/brackets-1.1.dmg
==> This subcommand requires root privileges: bsexec
Error: Empty plist input
```

**Comment by rolandwalker** [comment]
Hm.  This could be related to #9364.

Fairly recently, we started using `:bsexec` to mount disk images (#7957).  Apple *has* been changing how `:bsexec` works recently.  There could be new changes, and it could be that `:bsexec` doesn't give us all the needed capabilities anymore.

**Comment by phinze** [comment]
> This subcommand requires root privileges: bsexec

Good point @rolandwalker - ^^ this message sounds sort of suspicious - like they might have required sudo for all bsexec commands

**Comment by rolandwalker** [comment]
@thesbros thanks for reporting this.  It is potentially very bad news if this is changing in 10.10.3.  We can fix it, of course, but there will be a *lot* of duplicate bug reports from people who don't upgrade homebrew-cask.

I cannot duplicate the problem in 10.10.1 or 10.10.2, so it is not possible to work on it at the moment.  One of us probably needs to get 10.10.3 going in a VM.

**Comment by thesbros** [comment]
@rolandwalker Alright, let me know if there's anything I can do or test to help.

**Comment by phinze** [comment]
We've gotten corroboration of the `bsexec` issues in 10.10.3

#9491 implements a quick fix by pulling `bsexec` from mounts. will cut a bugfix release when it lands

**Comment by phinze** [comment]
OK can you pull down the bugfix release I just cut [v0.53.1](https://github.com/caskroom/homebrew-cask/releases/tag/v0.53.1) and see if it solves your problem?

**Comment by thesbros** [comment]
@phinze Works!

**Comment by phinze** [comment]
Hooray! I'll go ahead and close for ya. :wave:
