### ISSUE TITLE
macfusion: SSHFS does not work due to broken bundled library

### ISSUE THREAD

**Issue by psibre** [caskroom/homebrew-cask#9450]
![macfusion](https://cloud.githubusercontent.com/assets/1278639/6076569/92e73c2a-ade5-11e4-8e6b-348dd110fdf1.png)

**Comment by psibre** [comment]
This is known issue, a workaround is documented at https://github.com/osxfuse/osxfuse/wiki/SSHFS#macfusion

**Comment by phinze** [comment]
Whoa great research and fix! Are you going to send a09f0d9b50d6a0061f463c2b7cd2b165554ac550 in as a PR?

**Comment by jawshooah** [comment]
SSHFS is also available as a [cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/sshfs.rb), which lists `osxfuse` as a dependency. Might it be better to reverse that dependency rather than depending on the Homebrew formula?

**Comment by jawshooah** [comment]
Either way, we're being opinionated regarding the installation medium. Since the user is installing `macfusion` as a cask, should we assume that they would prefer the cask version of `sshfs`?

**Comment by psibre** [comment]
Oops, I hadn't noticed the casks for `sshfs` and `osxfuse`...
After [reading up](7002) [on the](7421) [debate](http://apple.stackexchange.com/questions/125468/what-is-the-difference-between-brew-and-brew-cask#comment180274_125471) I guess it makes sense to prefer the casks.
Incidentally, the bottle argument falls over when we consider that the casks support Leopard and later, while the brew bot only builds bottles for Mountain Lion and newer.

@phinze Thanks! I've opened PR #9457.
