### ISSUE TITLE
enable `args` for uninstall stanza

### ISSUE THREAD

**Issue by guyzmo** [caskroom/homebrew-cask#9474]
in the [mplabx][0] cask, I need to give an argument to avoid showing a GUI dialog for the uninstallation of the cask. If the `args` argument was implemented for the `uninstall` stanza, it would be really nice:

    uninstall :script => 'Uninstall_MPLAB_X_IDE_v2.30.app/Contents/MacOS/installbuilder.sh',
              :args => ['--mode', 'unattended']

[0]:https://github.com/caskroom/homebrew-cask/pull/9461/files

**Comment by phinze** [comment]
It works already! @guyzmo and I just figured this out in IRC:

```ruby
uninstall :script => {
  :executable => 'Uninstall_MPLAB_X_IDE_v2.30.app/Contents/MacOS/installbuilder.sh',
  :args => ['--mode', 'unattended']
}
```
