### ISSUE TITLE
New Calibre version: 2.19.0

### ISSUE THREAD

**Issue by mcandre** [caskroom/homebrew-cask#9476]
Please point the Calibre recipe to the new 2.19.0 version.

**Comment by vitorgalvao** [comment]
Calibre always points to the latest version. We don’t support updating yet, though, so the best way for you to do it is via `brew cask install --force calibre`.

**Comment by mcandre** [comment]
Hmm, this is odd.

I ran `brew uninstall calibre && brew cask update && brew install calibre`, and it installed the same version I was using before.

**Comment by vitorgalvao** [comment]
Yes, that’s because the cache wasn’t cleared, so as far as homebrew-cask was concerned, you had already downloaded the file, when it was in fact an old version. That’s something that needs to be addressed.

**Comment by mcandre** [comment]
Do you know if this would be my local Homebrew/Cask cache, or a remote
cache?

On Mon, Feb 9, 2015 at 9:34 AM, Vítor Galvão <notifications@github.com>
wrote:

> Yes, that’s because the cache wasn’t cleared, so as far as homebrew-cask
> was concerned, you had already downloaded the file, when it was in fact an
> old version. That’s something that needs to be addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caskroom/homebrew-cask/issues/9476#issuecomment-73528380>
> .
>



-- 
Cheers,

Andrew Pennebaker
www.yellosoft.us

**Comment by vitorgalvao** [comment]
Your local cache. You can get rid of it with `rm -rf "$(brew --cache)"`.

**Comment by mcandre** [comment]
Thank you!

Would `brew clean` do this as well?

On Mon, Feb 9, 2015 at 5:41 PM, Vítor Galvão <notifications@github.com>
wrote:

> Your local cache. You can get rid of it with rm -rf "$(brew --cache)".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caskroom/homebrew-cask/issues/9476#issuecomment-73615370>
> .
>



-- 
Cheers,

Andrew Pennebaker
www.yellosoft.us

**Comment by vitorgalvao** [comment]
It shouldn’t, no.
