### ISSUE TITLE
Failures with brew cask info ...

### ISSUE THREAD

**Issue by dwkns** [caskroom/homebrew-cask#9481]
```
$ brew cask info dropbox - works as expected.
```
```
$ brew cask info sublime-text3
==> Failed command:
["/usr/bin/find", "#<Pathname:/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065>", "-type", "f", "-not", "-name", ".DS_Store", "-print0"]
```
```
$ brew cask info things - works as expected.
```
```
$ brew cask info omnigraffle
==> Failed command:
["/usr/bin/find", "#<Pathname:/opt/homebrew-cask/Caskroom/omnigraffle/latest>", "-type", "f", "-not", "-name", ".DS_Store", "-print0"]
```

I'm not sure why some are working and some are not. Any ideas?

**Comment by phinze** [comment]
Hey sorry this is giving you trouble. Are you all upgraded?

The upgrade command we usually recommend is

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by dwkns** [comment]
Yep.

    $ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
    ==> Already up-to-date.
    ==> Error: brew-cask 0.53.0 already installed

Have also tried a complete clean up and reinstall. 

    $ sudo rm -rf /usr/local 
    $ sudo rm -rf /opt/homebrew-cask 
    $ sudo rm -rf /Library/Caches/Homebrew

Bit extreme but I wanted to be sure. 

Then :
    
    $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    ...
    ==> Installation successful!
    ==> Next steps
    Run `brew doctor` before you install anything
    Run `brew help` to get started
    
    $ brew doctor
    ==> Your system is ready to brew.
   
    $ brew install caskroom/cask/brew-cask
    ...

    $ brew tap caskroom/versions
    ...

    $ brew cask install  --appdir="/Applications" sublime-text3
    ==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
    ==> We'll set permissions properly so we won't need sudo in the future
    Password:
    ==> Caveats
    Cask sublime-text3 installs files under "/usr/local".  The presence of such
    files can cause warnings when running "brew doctor", which is considered
    to be a bug in homebrew-cask.

    ==> Downloading http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203065.dmg
    ######################################################################## 100.0%
    ==> This subcommand requires root privileges: bsexec
    Error: Empty plist input

And the cask doesn't get installed. Have checked this with a couple of casks sublime-text3, dropbox & google-chrome. I get the same error. 

If I try : 

    $  sudo brew cask install  --appdir="/Applications" sublime-text3

The install succeeds but (as before)
    
    $ brew cask info sublime-text3 - fails with...
    ==> Failed command:
    ==> ["/usr/bin/find", "#", "-type", "f", "-not", "-name", ".DS_Store", "-print0"]

I should note that I'm running 10.10.3 (14D72i)

**Comment by rolandwalker** [comment]
Hi!  Thanks for the report!

This bug likely arises from our separation from Homebrew on the backend (#8089), or one of the many subsequent adjustments.

The clue is the `#` character: `/usr/bin/find #` makes no sense.  The `#` comes from an incorrect stringification of a Pathname object (see also #8113).

We will be able to fix it based on your description above.

**Comment by dwkns** [comment]
What about the failure to install a cask if you don't specify `sudo` and get this error message : 

    ==> This subcommand requires root privileges: bsexec
    Error: Empty plist input

I was under the impression that you didn't need `sudo` to install a cask. Is this a bug?

**Comment by phinze** [comment]
@dwkns we're discovering that Apple changed the behavior of bsexec in 10.10.3 to suddenly require root privileges. not cool apple! I'll cook up a fix for this today.

**Comment by phinze** [comment]
Ok can you pull down the bugfix release I just cut [v0.53.1](https://github.com/caskroom/homebrew-cask/releases/tag/v0.53.1) and see if it solves your problems?

**Comment by dwkns** [comment]
Yep, solves both issues. 
1) casks now install without requiring `sudo`
2) `brew cask info ... ` doesn't bomb out with : 

    ==> Failed command:
    ["/usr/bin/find", "#<Pathname: ...

Nice work. Thanks.

**Comment by phinze** [comment]
Hooray!

**Comment by delitescere** [comment]
Still happening :(

brew 0.9.5
brew-cask 0.53.3
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

It fails on a machine that previously did not have the virtualbox cask installed, and was installed with the above.

```bash
$ brew cask info virtualbox
Error: Command failed to execute!

==> Failed command:
["/usr/bin/find", "#<Pathname:/opt/homebrew-cask/Caskroom/virtualbox/4.3.22-98236>", "-type", "f", "-not", "-name", ".DS_Store", "-print0"]

==> Output of failed command:
/opt/homebrew-cask/Caskroom/virtualbox/4.3.22-98236/.background/vbox_folder.tiff/opt/homebrew-cask/Caskroom/virtualbox/4.3.22-98236/UserManual.pdf/opt/homebrew-cask/Caskroom/virtualbox/4.3.22-98236/VirtualBox.pkg/opt/homebrew-cask/Caskroom/virtualbox/4.3.22-98236/VirtualBox_Uninstall.tool
```

On a machine that previously had the virtualbox cask installed (by older versions), `brew cask info virtualbox` works fine.

```bash
$ brew cask info virtualbox
virtualbox: 4.3.22-98236
VirtualBox
http://www.virtualbox.org
/opt/homebrew-cask/Caskroom/virtualbox/4.3.22-98236 (4 files, 110M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox.rb
==> Contents
  /Applications/VirtualBox.app/Contents/MacOS/VBoxManage (binary)
  /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless (binary)
  VirtualBox.pkg (pkg)
```

More importantly, `install --force` and `remove` now fail too (because of the `#Pathname` stringification problem.
