### ISSUE TITLE
Can not install google-cloud-sdk

### ISSUE THREAD

**Issue by tp** [caskroom/homebrew-cask#9494]
```
=> brew install Caskroom/cask/google-cloud-sdk
==> brew cask install Caskroom/cask/google-cloud-sdk
Warning: Unexpected method 'caskroom' called on Cask google-cloud-sdk.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

Error: undefined method `join' for nil:NilClass
```

Version:
```
=> brew -v
Homebrew 0.9.5
```

Earlier I got this warning (but I'm not sure if that poses a problem):

```
Warning: Could not create link for caskroom/cask/brew-cask, as it
conflicts with phinze/cask/brew-cask. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install caskroom/cask/brew-cask
```

**Comment by iggyvolz** [comment]
Yes, that definitely caused this problem.  From the looks of it, you installed cask back when it was owned by phinze (it has now been moved to its own organization).  If you're not interested in saving your settings, installed casks, et cetera, you can run:
```bash
brew uninstall phinze/cask/brew-cask && brew untap phinze/cask && brew link brew-cask
```
This will uninstall phinze's brew-cask (which no longer exists) and link the new one.

If you want to save everything when you move, you might have to perform a backup of your installed casks and install them when you upgrade.  If you're looking only for a simple re-install of all casks, brew cask list>(some file) then re-installing then running brew cask install `cat (some file)` should do the trick.

**Comment by iggyvolz** [comment]
Another point - brew version does not equal brew cask version.  They are two separate projects (brew is on 0.9.5, cask is on 0.53.1).

**Comment by tp** [comment]
Thanks for your help. With you tips and reinstalling cask via `brew install caskroom/cask/brew-cask` I was able to get this working.

Since I just added `phinze/cask/brew-cask` yesterday (based on a comment in a Homebrew bug report), is there any way that new installations of phinze's cask fail, such that no more people will use the old repo?

**Comment by tp** [comment]
#9503 is probably related.

**Comment by phinze** [comment]
Hey folks, sorry for the trouble. Refactor over the weekend broke this. Cutting a release which should fix now.

**Comment by phinze** [comment]
Ok want to give it another shot with v0.53.2 and see if it works?

**Comment by rolandwalker** [comment]
Hi @iggyvolz, I have previously contacted you by email about how the maintainers process incoming issues.  Please check your gmail account, or contact me privately at my publicly listed email address.

**Comment by risaacson** [comment]
I am still having this issue.

```
brew cask install google-cloud-sdk
Warning: Unexpected method 'caskroom' called on Cask google-cloud-sdk.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

Error: undefined method `join' for nil:NilClass
```

```
brew info brew-cask
brew-cask: stable 0.53.2, HEAD
https://github.com/caskroom/homebrew-cask/
/usr/local/Cellar/brew-cask/0.53.2 (2417 files, 9.5M) *
  Built from source
From: https://github.com/caskroom/homebrew-cask/blob/master/brew-cask.rb
```

**Comment by phinze** [comment]
@risaacson would you mind giving the fix that's on master a try?

```
brew update && brew reinstall brew-cask --HEAD
```

You can revert to the released version with:

```
brew reinstall brew-cask
```

**Comment by ndr-qef** [comment]
This latest fix works for me.

**Comment by phinze** [comment]
Alright good enough for me. Here comes bugfix release number 2! :bug: :gun:

**Comment by phinze** [comment]
OK `v0.53.3` out now!

**Comment by iggyvolz** [comment]
Sorry about that @rolandwalker ... email has gotten a bit out of hand lately and it got buried.

**Comment by risaacson** [comment]
I was just able to test and it works for me now also.

Thank you much!

**Comment by phinze** [comment]
Hooray we did it!

**Comment by tp** [comment]
A simple brew update didn't find the update.

But after updating with `brew reinstall caskroom/cask/brew-cask` I could successfully install the google-cloud-sdk.
