### ISSUE TITLE
Issue with reinstall qlmarkdown

### ISSUE THREAD

**Issue by atechnicolorskye** [caskroom/homebrew-cask#9503]
Hi,

I am running Yosemite and have issues reinstalling qlmarkdown with the following errors:

arning: Unexpected method 'caskroom' called on Cask qlmarkdown.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

Error: undefined method `join' for nil:NilClass

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/dsl/base.rb:20:in `caskroom_path'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/dsl/base.rb:24:in `staged_path'
<main>:14:in `block in <class:KlassPrefixQlmarkdown>'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/artifact/preflight_block.rb:9:in `instance_eval'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/artifact/preflight_block.rb:9:in `block in install_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/artifact/preflight_block.rb:8:in `install_phase'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/installer.rb:117:in `each'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/installer.rb:117:in `install_artifacts'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/installer.rb:66:in `install'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.53.1/rubylib/brew-cask-cmd.rb:18:in `<main>'

Thanks for all the help!

**Comment by bharadwaj6** [comment]
Facing the same issue on my Yosemite too. Issue persists even after re-installing brew-cask.

Here's the full trace: https://gist.github.com/bharadwaj6/fc78ddb6528978299f4d

**Comment by phinze** [comment]
Hey there! Looks like the result of a refactoring I did over the weekend. Let me dig in and get this fixed quickly.

**Comment by phinze** [comment]
Ok want to give it another shot with v0.53.2 and see if it works?

**Comment by atechnicolorskye** [comment]
Hi Paul,
It works! Thanks for all the help :)
Sky

Date: Mon, 9 Feb 2015 07:52:04 -0800
