### ISSUE TITLE
undefined method `release' for OS::Mac:Module

### ISSUE THREAD

**Issue by metalmini** [caskroom/homebrew-cask#9504]
Don't know if this is already addressed but the cli told me to report this bug ;-)

`brew cask info libreoffice     
Error: undefined method `release' for OS::Mac:Module
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:1:in `<class:Libreoffice>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask.rb:123:in `load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/info.rb:7:in `block in run'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/info.rb:5:in `each'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/info.rb:5:in `run'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'`

**Comment by Amorymeltzer** [comment]
Hi there, you're using an outdated version of homebrew-cask, upgrading via the following should set you straight:
`brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`
