### ISSUE TITLE
Error: wrong number of arguments (1 for 0) while loading ...

### ISSUE THREAD

**Issue by fabiantheblind** [caskroom/homebrew-cask#9524]
When running:  

    $ brew cask install vivaldi

I get this error message:

    Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/vivaldi.rb'
    Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
    <main>:5:in `name'
    <main>:5:in `<class:Vivaldi>'
    <main>:in `<main>'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `eval'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:52:in `load'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/tapped.rb:28:in `load'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask.rb:124:in `load'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `each'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `install_casks'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:6:in `run'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
    /usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
    /usr/local/bin/brew-cask.rb:42:in `<top (required)>'
    /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /usr/local/Library/brew.rb:58:in `require?'
    /usr/local/Library/brew.rb:141:in `<main>'

I'm running:  

- ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
- OSX 10.10.2
- Homebrew 0.9.5

 I get a similar error when running:  

    brew cask list

**Comment by phinze** [comment]
Hey there! Looks like you're on 0.46.0 and we're up at 0.53.3 - you just need an upgrade fix this.

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by fabiantheblind** [comment]
Thanks. Worked like a charm.
