### ISSUE TITLE
Issue with pulled qlstephen

### ISSUE THREAD

**Issue by atechnicolorskye** [caskroom/homebrew-cask#9527]
Hi,

The qlstephen plugin that cask currently clones from causes Finder to hang when viewing file properties from certain types of files like .jar and .torrent. Please refer to https://github.com/whomwah/qlstephen/issues/34. You might want to switch to https://github.com/bestwnh/qlstephen as the creator is too busy to maintain it for now.

**Comment by vitorgalvao** [comment]
The repo you link to seems to be just as inactive, and actually has updates behind the main one.
