### ISSUE TITLE
Getting "wrong number of arguments" for brew info adium

### ISSUE THREAD

**Issue by colund** [caskroom/homebrew-cask#9529]
$ brew cask info adium
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/adium.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues

So I report this

**Comment by Amorymeltzer** [comment]
Hi @colund could you try running the following command and seeing if that clears everything up for you?  It's likely your `homebrew-cask` installation is out of date.
````bash
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
````

**Comment by colund** [comment]
That did the trick! Thanks!
