### ISSUE TITLE
issue uninstalling blender

### ISSUE THREAD

**Issue by felixkosmalla** [caskroom/homebrew-cask#9555]
brew cask uninstall blender
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/blender.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:5:in `name'
<main>:5:in `<class:Blender>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask.rb:120:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/uninstall.rb:8:in `block in run'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/uninstall.rb:6:in `each'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/uninstall.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'

**Comment by Amorymeltzer** [comment]
Hi there!  Your `homebrew-cask` installation is out of date, running the following should set you straight:
````
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
````
