### ISSUE TITLE
Error: wrong number of arguments (1 for 0) pdftotext.rb

### ISSUE THREAD

**Issue by mrjcleaver** [caskroom/homebrew-cask#9568]
When doing:
````
brew cask install pdftotext
````

Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/pdftotext.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:5:in `name'
<main>:5:in `<class:Pdftotext>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask.rb:120:in `load'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'

**Comment by phinze** [comment]
Hi there!  Your `homebrew-cask` installation is out of date, running the following should set you straight:
````
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
````

**Comment by ndr-qef** [comment]
@mrjcleaver, since this is a well-known issue (#7946), I am closing this under the assumption that @phinze's suggestion worked. If there are still problems, by all means, let us know and we will reopen.
