### ISSUE TITLE
Edit pkg insallation procedure

### ISSUE THREAD

**Issue by iStopped** [caskroom/homebrew-cask#9575]
Some .pkg installations have the option to edit the installation procedure ("Ad Hoc"), the user should be able to perform this edits via homebrew-cask.

Esample: osxfuse during the installation allow to enable the MacFuse compatibility layer, but homebrew-cask deny this.

**Comment by rolandwalker** [comment]
Hi!

Yes, there is already an issue for this (#2751). Everye agrees this s desirable functionality, but nobody has worked on it.  I'm closing this as a duplicate, but feel free to continue the discussion on the main issue.
