### ISSUE TITLE
Allow defining choices for pkg installer

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-cask#9578]
I realised this feature would be really helpful for RealVNC which by default installs VNC server & viewer and in my case, I usually don't need/want to install server for remote control SW when I only use it to control other machines.

It may not be that difficult to code. Here's the part of code that needs some tuning I guess:

```ruby
  def run_installer(pkg_description)
    load_pkg_description pkg_description
    ohai "Running installer for #{@cask}; your password may be necessary."
    ohai "Package installers may write to any location; options such as --appdir are ignored."
    source = @cask.staged_path.join(pkg_relative_path)
    unless source.exist?
      raise Hbc::CaskError.new "pkg source file not found: '#{source}'"
    end
    args = [
      '-pkg',    source,
      '-target', '/'
    ]
    args << '-verboseR' if Hbc.verbose
    args << '-allowUntrusted' if pkg_install_opts :allow_untrusted
    @command.run!('/usr/sbin/installer', {:sudo => true, :args => args, :print_stdout => true})
  end
```

So next to `-verboseR` and `-allowUntrusted` it would also need support for `-applyChoiceChangesXML`.

I don't think it's a good idea to create whole XML per cask, I'd rather see these XMLs being build on-the-fly based on provided options.
I (maybe blindly) believe that there could be some common patterns for these XMLs.

**Comment by rolandwalker** [comment]
Agreed on all points.

**Comment by vitorgalvao** [comment]
Closing for lack of interest.
