### ISSUE TITLE
It seems the symlink source is not there when installing Crush FTP

### ISSUE THREAD

**Issue by dschinkel** [caskroom/homebrew-cask#9582]
I am running Yosemite.

When I do:

```
brew cask install crushftp
```

I get:

```
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/crushftp/latest/CrushFTP6_OSX/CrushFTP7.app'
```

![errorshowninterminal](https://cloud.githubusercontent.com/assets/338798/6194448/13b5af68-b38a-11e4-8e3d-1117772756cc.png)

**Comment by Amorymeltzer** [comment]
Looks like the full app path didn't get update last time.  #9583 should fix this.
