### ISSUE TITLE
suspicious-package - `pkg` => `xip`

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#9584]
Hello,

Suspicious package formula is currently installing from the official package (.pkg). 
Wouldn't it be possible to avoid delegating the install to this installer and use the files from the alternative official archive? As documented as a second possibility on their web site:
http://www.mothersruin.com/software/SuspiciousPackage/download.html

>Want to avoid a package?
>[...]
>Download Suspicious Package as a XIP archive.

This would have some advantages:
- the install wouldn't be located in `/Library/QuickLook` but could be in `~/Library/QuickLook/` as the majority of the other QuickLook plugins installed with `brew cask` (e.g. qlcolormode qlmarkdown qlstephen...)
- then the plugin would not be enabled by default for all users: it could be enabled per user on multi-user systems
- the install process wouldn't require entering the admin password

What do you think of this alternative?

P.S. Moreover, while the download site displays version `2.0.1`, currently the version in formula is only set as `latest`. Wouldn't it break the possibility for users to easily/automatically upgrade with `brew cask install suspicious-package`? (usually this command installs the newer version if available).

**Comment by radeksimko** [comment]
Hi,
all the mentioned advantages are reasonable and it makes sense to install it as an actual QL plugin.
:+1:

> P.S. Moreover, while the download site displays version 2.0.1, currently the version in formula is only set as latest. Wouldn't it break the possibility for users to easily/automatically upgrade with brew cask install suspicious-package? (usually this command installs the newer version if available).

Generally speaking about `latest`, we're in a process of implementing a proper update/upgrade solution for cask, keep watching https://github.com/caskroom/homebrew-cask/issues/4678

Currently the only way you can upgrade any existing cask is `brew cask install %name% --force`.

Speaking about compatibility between current cask (`pkg`) and suggested (`xip`), I can't say exactly what it would mean for users which already installed the `pkg` version, but the aim is obviously to allow users to easily upgrade to `xip` version if possible.

There might be another maintainer having more experience with QL plugins which will be able to tell what's possible regarding the upgrade process.

**Comment by Yann-R** [comment]
Thank you very much for your positive answer.
You are right, there might be consequences to foresee with that evolution of the formula. I must admit I totally under-estimate it since I was just suggesting the idea... without being able to implement a formula for QuickLook plugins.

> Currently the only way you can upgrade any existing cask is brew cask install %name% --force.

I agree only when there is no version number in the formula.
The forthcoming `brew cask upgrade` would be a great enhancement. 
But meantime, when a cask formula keeps a version numbering when changing, I observed that
`brew cask install %name%`:
- outputs a warning and does nothing if the version is already installed (=> Warning: A Cask for suspicious-package is already installed.)
- installs the new version otherwise

So, for the moment, having a version number seems to do the trick as workaround for a not-so-bad upgrade command: `brew cask install` \``brew cask list`\`

Thanks again for the reference to the discussion about update/upgrade. I'll keep watching!

**Comment by vitorgalvao** [comment]
Yes, we should change it for the `xip` version. I thing we don’t currently support `xip` packages, though.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is definitely not urgent and can be revisited at a later date.

**Comment by vigo** [comment]
El Capitan issue

    $ brew cask install --verbose suspicious-package
    ==> Satisfying dependencies
    ==> Installing Formula dependencies from Homebrew
    unar ... already installed
    complete
    ==> Downloading http://www.mothersruin.com/software/downloads/SuspiciousPackage.xip
    Already downloaded: /Library/Caches/Homebrew/suspicious-package-latest.xip
    Error: Command failed to execute!

    ==> Failed command:
    ["#<Pathname:/usr/local/bin/unar>", "-q", "-D", "-o", "/var/folders/w9/3cyf9psx3s3661j8z56yfzf80000gn/T/d20151020-34180-14cg4xa", "--", "#<Pathname:/Library/Caches/Homebrew/suspicious-package-latest.xip>"]

    ==> Output of failed command:
    /Library/Caches/Homebrew/suspicious-package-latest.xip: 

    ==> Exit status of failed command:
    #<Process::Status: pid 34213 SIGSEGV (signal 11)>

**Comment by yanokwa** [comment]
I believe the problem here is that suspicious-package-latest.xip has been quarantined by OS X. 

Try downloading the XIP from http://www.mothersruin.com/software/downloads/SuspiciousPackage.xip using your browser and run `/usr/bin/xattr -l  ~/Downloads/SuspiciousPackage.xip`, you'll see com.apple.metadata:kMDItemWhereFroms and com.apple.quarantine tags that mark the file as safe. 

If you run the same command on the brew cached file with `/usr/bin/xattr -l /Library/Caches/Homebrew/suspicious-package-latest.xip` you won't see those tags. And it looks like unar segfaults if the file has been quarantined, so that's where the error is coming from.

My quick workaround was to copy the manually downloaded file into my cache with `cp ~/Downloads/SuspiciousPackage.xip /Library/Caches/Homebrew/suspicious-package-latest.xip` then run the install.

I propose we go back to the pkg format. What do you think @cprecioso?
