### ISSUE TITLE
qlmarkdown keeps ZIP download archive?

### ISSUE THREAD

**Issue by Yann-R** [caskroom/homebrew-cask#9585]
Hello,

Currently, after `brew cask install qlmarkdown`, the Caskroom keeps `QLMarkdown.qlgenerator.zip` along with unarchived folder `QLMarkdown.qlgenerator` (see in `.../homebrew-cask/Caskroom/qlmarkdown/`)

Is it necessary to keep this ZIP just needed during the install stage?
(other similar QuickLook plugins installations avoid it, like qlstephen, qlcolorcode...)

**Comment by vitorgalvao** [comment]
It isn’t, no, but it remains [due to a known problem](https://github.com/caskroom/homebrew-cask/blob/0ad977001c4dba60495a442e24ecdb7bc1edb2b5/Casks/qlmarkdown.rb#L10-12), and adding the extra step to remove it doesn’t offer much advantage. The issue itself should be fixed.

**Comment by Yann-R** [comment]
OK, thanks for the precision. 
It's in progress, perfect!
