### ISSUE TITLE
Enforce installing apps within some sort of Cellar whenever possible

### ISSUE THREAD

**Issue by guyzmo** [caskroom/homebrew-cask#9590]
Following my cask PR #9461, @rolandwalker is pointing out that the caskroom directory, within `/opt/homebrew-cask/Caskroom/<app>/<ver>` is intended to receive only files written by HBC, because that hierarchy is HBC's database, which afaict, means that's looking at that path that HBC checks whether an app is installed. Which is why he's commented that I should not make the installer script write to the caskroom directory, and that it's fine that apps install else where, wherever it wants.

But I do believe that's quite wrong.

First of all, I believe that homebrew's choice of having a Cellar where it keeps all installed applications, and populate the system with symlinks using `brew link`/`brew unlink` is one of the strong features of the app. It gives more control over deployment of applications, and we can even have multiple versions of the same app installed, and deployable on demand (like the `HEAD` and stable version). It's also not tampering the system, so we can keep control over what's in `/Applications`, `~/Applications` etc…

Then current behaviour of HBC is not homogeneous: if you do install a `.app`, the `.app` gets deployed within the caskroom, and a link to it is being created within `~/Applications`. If you install a pkg, the `pkg` does whatever it wants, polluting `Library`, `/Applications` etc… however it likes. 

If you install using an installer script, then the behaviour is not even normalized in the documentation, shall it deploy to `/Applications`? or in `/opt`? or in `/usr/local`? And where shall the uninstall script go? 
And then, why keep an empty caskroom directory, except for the sake of keeping track of the install status, which might be wrong? If the user decides to move `/Applications/MyApp`, or `/opt/MyApp` some place else, HBC looses the ability to call a possible uninstall script (or remove the app data), because it cannot know where the app has moved.

In the end, unlike homebrew, HBC does not successfully create consistency in a world of inconsistent application deployment schemes. For sure there will be a few exceptions that will be painful, expecting that all application data stays within `/Applications` or somewhere else. But given that OSX development guideline is enforcing statically linked and self-contained applications, those apps should be very rare, if there are any.

But for all the others, I do believe that all efforts shall be made to enforce deployment/install of all the application/bundle/package/installer data within the caskroom directory. That then the user can link/unlink an app at any time using a `brew cask link`/`brew cask unlink` command.

And it can be done for most of the apps:

 - `.app` can be kept anywhere, and linked wherever we want,
 - `.pkg` can be installed within a given volume, or even might be installable within a path [cf installer manpage](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/installer.8.html)
 - installer scripts most of the time can specify a path, or can be patched or even jailed to enforce installation within a directory.

I might try to do a branch and try to enforce that on all existing casks, or at least all the edgy ones, but it might take me some time as I'm pretty busy and not as efficient in Ruby as in the other languages I know. 

This is why I'm raising that point for discussion first.

**Comment by guyzmo** [comment]
for .pkg installed all contained in a single directory, here's a way to achieve that (all in shell):

```shell
PKGFILE=/opt/homebrew-cask/Caskroom/eagle/7.2.0/eagle-7.2.0.pkg
PKGSIZE=$(installer -showChoicesXML -pkg $PKGFILE | xpath '//integer[preceding-sibling::key/text()="choiceSizeInKilobytes"]/text()' 2>&1 | tail -1)
PKGSIZE=$(( ($PKGSIZE + 8192) *2 )) # add a bit more than the needed size and 4k for the HFS+
RAMDISK=diskutil erasevolume HFS+ "ramdisk" `hdiutil attach -nomount ram://$PKGSIZE` | grep ramdisk | awk '{print $4}'
sudo installer -target /Volumes/ramdisk -pkg $PKGFILE
sudo cp -a /Volumes/ramdisk/* /opt/homebrew-cask/Caskroom/eagle/
sudo rm -rf $PKGFILE
hdiutil detach $RAMDISK
```

and then, just need to list what files we want to link in the target directories!

**Comment by guyzmo** [comment]
from IRC discussion with @rolandwalker, here are some related issues: #6369 #5442 and PR #5622 #8275

**Comment by vitorgalvao** [comment]
> In the end, unlike homebrew, HBC does not successfully create consistency in a world of inconsistent application deployment schemes.

Correct.

> First of all, I believe that homebrew's choice of having a Cellar where it keeps all installed applications, and populate the system with symlinks using `brew link`/`brew unlink` is one of the strong features of the app.

It’s not. It’s one of it’s biggest mistakes, and should be changed (plans are being made for it). In part for what you mention above (inconsistencies), but also because it cause a ton of issues with a ton of apps. GUI apps are simply not prepared for that treatment, and we’re having to build so many workarounds on top of workarounds to support this broken model, the whole of homebrew-cask suffers.
