### ISSUE TITLE
Update navicat family

### ISSUE THREAD

**Issue by shipstar** [caskroom/homebrew-cask#9618]
It looks like navicat-for-sql-server was [updated recently](https://github.com/caskroom/homebrew-cask/pull/9468), but not the rest of the family. (I'm specifically experiencing a SHA256 mismatch on navicat-for-postgresql.)

Is there a better way to ensure that all products in a suite are updated in unison, or does it happen infrequently enough that it's better to deal with it on a case-by-case basis?

**Comment by rolandwalker** [comment]
Hi!

Updates happen regularly to this entire suite, but there are very few other sets of Casks that follow the same pattern.

Usually we just depend on maintainer knowledge to check all the navicat Casks when we see one change.

**Comment by fro** [comment]
Another mismatch apparently:

    MBP-de-Francois:playground francois$ brew cask install navicat-for-postgresql
    ==> Downloading http://download.navicat.com/download/navicat111_pgsql_en.dmg
    ######################################################################## 100,0%
    ==> Note: running "brew update" may fix sha256 checksum errors
    Error: sha256 mismatch
    Expected: 2666cf0137f55b1101549244cc5c36898460d9b2ea8ed278606c17b9e02b5b14
    Actual: 229904a26361df76157e618f4b2858db9cd4b48c79bf5b00d4f2b03afb74f312
    File: /Library/Caches/Homebrew/navicat-for-postgresql-11.1.9.dmg
    To retry an incomplete download, remove the file above.
