### ISSUE TITLE
brew cask install burn -- curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by Drewshg312** [caskroom/homebrew-cask#9622]
When running `brew cask install burn` getting:
```     
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'burn' with message: Download failed: http://downloads.sourceforge.net/project/burn-osx/Burn/2.5.1/burn251.zip    ```

**Comment by rolandwalker** [comment]
Hi!

It would appear that you have some kind of local network connectivity problem.  I cannot duplicate this or the duplicate issues #9621 and #9620.

To see the `curl` command that fails, try running `brew cask install` with the `--debug` flag:
```bash
$ brew cask install --debug burn
```
