### ISSUE TITLE
hashcat dependency (unar) installation problem

### ISSUE THREAD

**Issue by Drewshg312** [caskroom/homebrew-cask#9623]
when running `brew cask install hashcat` getting this:
```    
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
unar ... Error: Command failed to execute!

==> Failed command:
["#<Pathname:/usr/local/bin/brew>", "install", "unar"]

==> Output of failed command:
==> Downloading https://theunarchiver.googlecode.com/files/unar1.8.1_src.zip
Already downloaded: /Library/Caches/Homebrew/unar-1.8.1.zip
==> xcodebuild -project ./XADMaster/XADMaster.xcodeproj -target XADMaster SYMROOT=../ -configuration Release
    CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/clients.o libxad/clients.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/all.o libxad/all.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/emulation.o libxad/unix/emulation.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/init.o libxad/unix/init.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)

**Comment by ndr-qef** [comment]
The failure is happening in the Homebrew command `brew install unar`. (It can be quite confusing, but Homebrew and homebrew-cask are separate projects.)

A failure in `xcodebuild` is quite suspicious. I suggest to see if `brew doctor` reports any obvious problem about your setup; if it does not, and you cannot find a way to make `brew install unar` work, you should search for similar problems in the [Homebrew](https://github.com/Homebrew/homebrew) issue tracker.

**Comment by Drewshg312** [comment]
lol I've already written to there but they redirected me here and closed the issue... Strange...

**Comment by ndr-qef** [comment]
I am sorry for the juggling. Unfortunately, it is all too frequent for our interdependency and conflated names to cause confusion.

To clarify: if `brew install unar` alone fails, that is what should be reported to Homebrew — they will rightfully disregard issues with `brew cask` commands. If `brew cask install hashcat` fails, but `brew install unar` works, then it is our problem to solve.

**Comment by Drewshg312** [comment]
I know thanx... `brew install unar ` fails so that's what did first - written to homebrew room and after they redirected me I've created this issue(just in case)... Now I've created another on there and waiting for their answer. Thank you anyways!!!

**Comment by ndr-qef** [comment]
Please note that, in https://github.com/Homebrew/homebrew/issues/36884, you should report the output of the failed `brew install unar` command, not that of `brew cask`. You should also verify that there are no underlying problems with your Homebrew setup by running `brew doctor` before reporting individual problems — I suspect there may be.

I hope you will find a solution soon.

**Comment by Drewshg312** [comment]
yeah! thank you I've done all this!
