### ISSUE TITLE
Cask errors

### ISSUE THREAD

**Issue by blacRose** [caskroom/homebrew-cask#9627]
~ brew cask audit
	Error: <main>: syntax error, unexpected tCONSTANT, expecting :: or '[' or '.'
	class 010Editor < Cask
	               ^
	<main>:12: syntax error, unexpected keyword_end, expecting end-of-input while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/010-editor.rb'
	Please report this bug:
	    https://github.com/caskroom/homebrew-cask/issues
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `eval'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `rescue in load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:52:in `load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/tapped.rb:28:in `load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask.rb:127:in `load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:8:in `block in all'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:8:in `map'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:8:in `all'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/audit.rb:40:in `casks_to_audit'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/audit.rb:23:in `run'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/audit.rb:7:in `run'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
	/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/Library/brew.rb:58:in `require?'
	/usr/local/Library/brew.rb:141:in `<main>'

----

	~ brew cask install mpv
	Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/mpv.rb'
	Please report this bug:
	    https://github.com/caskroom/homebrew-cask/issues
	<main>:6:in `name'
	<main>:6:in `<class:Mpv>'
	<main>:in `<main>'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `eval'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `rescue in load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:52:in `load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/tapped.rb:28:in `load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask.rb:127:in `load'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:19:in `block in install_casks'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `each'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `install_casks'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:6:in `run'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
	/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
	/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/Library/brew.rb:58:in `require?'
	/usr/local/Library/brew.rb:141:in `<main>'

**Comment by ndr-qef** [comment]
This is #7946, a problem with old versions of `brew cask`. Upgrading should fix the issue:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by blacRose** [comment]
~ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
	Already up-to-date.
	Error: No available formula for brew-cask

----

	~ brew tap
	caskroom/cask
	homebrew/binary
	homebrew/versions
	josegonzalez/php
	mpv-player/mpv
	ravenac95/sudolikeaboss

**Comment by ndr-qef** [comment]
Ah, that occasionally happens, but the cause is unknown.

It is sufficient to reinstall homebrew-cask.
```
brew uninstall brew-cask && brew untap caskroom/cask && brew install caskroom/cask/brew-cask
```

**Comment by blacRose** [comment]
Yep, worked. I didn't do the untap, though, still worked fine. Then no problem reinstalling mpv.
