### ISSUE TITLE
Racket doesn't link binaries in `bin` to `/usr/local/`

### ISSUE THREAD

**Issue by girvo** [caskroom/homebrew-cask#9642]
As the title says, the binaries found in the Racket cask aren't linked to `/usr/local` -- I've added the `/Applications/Racket v6.1.1/bin/` folder to my `$PATH` currently, but that won't work when it gets updated :(

**Comment by rolandwalker** [comment]
Hi!

Good idea.  I added everything in the `bin` directory, though we may end up trimming that down later if another Cask distributes *eg* `slatex`.
