### ISSUE TITLE
How to add an app fork (slug problem) ?

### ISSUE THREAD

**Issue by MoOx** [caskroom/homebrew-cask#9648]
Hi guys,

I'am using Slate.app (window manager) for a while now. But main project seems [completely abandoned](https://github.com/jigish/slate/issues/437) (last commit date, numbers or PR and issue without response).
So a nice fork got some update and I would like to use cask to install this.
How do you think we should handle this kind of issue? My main problem is "what slug to choose".

Any idea on this ?

**Comment by ndr-qef** [comment]
Nothing fancy: we accept forks as standard casks, but prefixed with the vendor's name. For example, [rowanj-gitx](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rowanj-gitx.rb).

**Comment by MoOx** [comment]
Ok so mattr-slate will do the thing. Thanks !
