### ISSUE TITLE
Slack.app fails to link into /Applications

### ISSUE THREAD

**Issue by mcandre** [caskroom/homebrew-cask#9658]
Could we please have the slack recipe automatically link Slack.app into /Applications, to integrate with Mac better?

Example use case: Another application raises an Open With... dialog, and I forget where exactly brew-cask placed Slack.app. Linking into /Applications would solve this problem.

**Comment by vitorgalvao** [comment]
You can [set it with `--appdir`](https://github.com/caskroom/homebrew-cask/blob/0ae2edd70729e8c8c198c476ad7274cf4e70d806/USAGE.md#options).
