### ISSUE TITLE
Alfred integration doesn't seem to work out of the box.

### ISSUE THREAD

**Issue by c4milo** [caskroom/homebrew-cask#9685]
So, as a result I Alfred can't find my casks :/

**Comment by c4milo** [comment]
It doesn't seem to be adding /opt/homebrew-cask/Caskroom to alfred's scopes.

**Comment by c4milo** [comment]
ah, I believe this happened because I installed homebrew cask first, then Alfred. I guess that would make this issue invalid...

**Comment by phinze** [comment]
Hi there! Are you using the latest version of Alfred and/or were you importing old Alfred settings? Alfred should [ship with the Caskroom location enabled as a default search scope](https://github.com/caskroom/homebrew-cask/issues/8052#issuecomment-69560606) in recent versions.

**Comment by c4milo** [comment]
If 2.6 (374) is the latest version then yes. I didn't import old settings. It was a setup from scratch on a new macbook pro.

**Comment by phinze** [comment]
Hmm... interesting. Reopening to investigate further.

**Comment by AndrewAlexMac** [comment]
I can also confirm this with Alfred v2.6 (374) installed after Cask on a fresh Yosemite install.

**Comment by AndrewAlexMac** [comment]
I was going to add them manually, but spotted something kinda interesting. If you click on the 'reset' button just above the search scope box, the Cask entries appear! I didn't type those, but there they are.
![screenshot 2015-03-06 12 43 08](https://cloud.githubusercontent.com/assets/689377/6525536/64814c34-c3fe-11e4-8dda-d43ff57801f2.png)

**Comment by phinze** [comment]
@preppeller ^^ does this look like expected behavior to you? If so we can probably just update our documentation to match.

**Comment by preppeller** [comment]
They should be in there automatically but I borked this a little in 2.6 so you have to hit reset to get them there. Once 2.6.1 is out (hopefully in a few weeks), this will work as expected on a fresh install and they will be there by default.

Sorry about that!

**Comment by AndrewAlexMac** [comment]
No problem! Big fan of Alfred, so I don't mind helping out at all :D

**Comment by JaredSartin** [comment]
Can this be closed, or should we wait for the fix in Alfred?

**Comment by AndrewAlexMac** [comment]
If @prepeller says it's already fixed in 2.6.1 due in a few weeks, might be worth keeping open until then.

**Comment by flemdizzle** [comment]
@AndrewAlexMac that does it!

**Comment by themiurgo** [comment]
I had the same issue and I manually added /opt/homebrew-cask/Caskroom. However my Apps would be listed after other similarly named entries. Resetting as @AndrewAlexMac advised fixed the issue.

**Comment by AndrewAlexMac** [comment]
@themiurgo I think you can drag the entries up and down to change the search priority/order.
