### ISSUE TITLE
USB PL2303 driver: pkg source file not found

### ISSUE THREAD

**Issue by ferrisoxide** [caskroom/homebrew-cask#9694]
First try using cask. Looks pretty cool, but not had success as yet. Having issues with installing the pl2303 driver on a OS X 10.9.5 machine. Ran the following using brew installed cask version 0.53.3:

`brew cask install pl2303`

but this error was returned: 

```
Error:  pkg source file not found: '/opt/homebrew-cask/Caskroom/pl2303/1.5.1/PL2303_MacOSX_v1_5_1.pkg'
```
Have run `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and tried reinstalling, as per instructions. But no luck.

Any advice appreciated.

**Comment by ferrisoxide** [comment]
Spotted it. The zip file downloaded contains the file `PL2303_MacOSX_v1.5.1.pkg`, not `PL2303_MacOSX_v1_5_1.pkg` as per the source. Will do a PR if I can, but have to switch to another project at the moment.

**Comment by ndr-qef** [comment]
Thanks for looking into the problem. I pushed a fix for the package name, along with other improvements. Let me know if there are any problems.
