### ISSUE TITLE
add support for ipass

### ISSUE THREAD

**Issue by ssbarnea** [caskroom/homebrew-cask#9711]
Installing iPass via cask would be a great addition

http://www.ipass.com/download-mobile-client/
http://moreinfo.ipass.com/redir.html?target=http://www.ipass.com/misc/sw_downloads/Open-Mobile-Mac-V2.3.1.183.dmg

**Comment by rolandwalker** [comment]
Sure!  Here's what the Cask looks like:

* https://github.com/rolandwalker/homebrew-cask/blob/c30a91c56accda985e09da09dd895051a01db9a9/Casks/ipass-open-mobile.rb

**Comment by ssbarnea** [comment]
Thank you, now I will know how to add others. I am wondering there are any kind of informations regarding existing casks, their description and analytics regarding their usage. 

It would great to find out which ones are more popular and obviously to have some kind of directory where we can search for them. Maybe I am looking for an app that is doing xxx but I have no idea if someone already added one that does.

Now the cask homepage is a single page with a counter of casks, not even a link to those, a simple html table would be more than useful.

**Comment by rolandwalker** [comment]
Yes, it would be great to have analytics, but unfortunately it is not possible due to the way Homebrew Taps are propagated.

**Comment by ssbarnea** [comment]
I think we may use the Google Analytics for this, using the Analytics for Apps instead of for Web pages. Brew Cask can be considered the application.
