### ISSUE TITLE
cask install chrom on OSX yosemite

### ISSUE THREAD

**Issue by jrake-revelant** [caskroom/homebrew-cask#9728]
Hi,

brew cask install google-chrome fails on OSX Yosemite 10.10.2

 brew cask install google-chrome
==> Caveats
The Mac App Store version of 1Password won't work with a Homebrew-Cask-linked Google Chrome. To bypass this limitation, you need to either:

  + Move Google Chrome to your /Applications directory (the app itself, not a symlink).
  + Install 1Password from outside the Mac App Store (licenses should transfer automatically, but you should contact AgileBits about it).

==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
######################################################################## 100,0%
Error: undefined method `extname' for 0:Fixnum
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container/criteria.rb:43:in `extension'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container/pkg.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:50:in `block in for_path'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:48:in `each'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:48:in `find'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/container.rb:48:in `for_path'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/installer.rb:83:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/installer.rb:50:in `install'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'

**Comment by rolandwalker** [comment]
Hi!

This happens because you are running an old version of Homebrew-cask, which is conflicting with newer versions of Homebrew.  The following command should bring you up to date:

```bash
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by jrake-revelant** [comment]
Awesome, thanks for the help. It was difficult to me to locate the error with the exception I got.
