### ISSUE TITLE
Freefilesync url isn't valid anymore

### ISSUE THREAD

**Issue by FlorianLoch** [caskroom/homebrew-cask#9734]
Seems like the developer doesn't host built version on sourceforge anymore. The download link (following the link to the official mirror from the official website) seems to be: http://ffs.winsoftware-forum.de/FreeFileSync_6.14_Mac_OS_X_64-bit.zip...
Or one might take a big, reputable German provider: http://download.heise.de/software/3f6073a265015efac57ee889a169c4c1/54eb5331/143599/freefilesync_6.14_mac_os_x_64-bit.zip

If see, this isn't that elegant for follow-up version - but at least it would work right now.
If you like I can do a pull request.

**Comment by rolandwalker** [comment]
Hi!  Thanks for the info.

As they've moved to FossHub, and as FossHub doesn't permit automation, we will have to remove the Cask.  A shame.  We will save the Cask in the [boneyard repo](https://github.com/caskroom/homebrew-boneyard) in case the developers decide to provide an automatable official download.
