### ISSUE TITLE
hashcat 0.49 cask - could not identify primary container?

### ISSUE THREAD

**Issue by SuperHenkie** [caskroom/homebrew-cask#9763]
`brew cask install hashcat` gives me this:

> Error: Uh oh, could not identify primary container for '/Library/Caches/Homebrew/hashcat-0.49.7z'

Already did `brew update` and `brew cask update`, no difference. I'm fairly new to brew and cask, so I'm not really sure what to do about this..?

**Comment by rolandwalker** [comment]
Hi!

`brew cask update` is just a synonym for `brew update` to catch typos.  To reliably upgrade Homebrew-cask (which you should do), the following ridiculous sequence is recommended:

```bash
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

After you try that, we should look at the fact that `hashcat` is distributed in a `7z` container, which is unusual.  Recognizing it depends on having a working `unar` installed from Homebrew.  The Cask attempts to install `unar` for you.  Still, to be sure/debug the problem, you might try
```bash
$ brew uninstall unar; brew install unar
```

**Comment by vitorgalvao** [comment]
Closing as solved. If you still have issues, @SuperHenkie, please report back.

**Comment by SuperHenkie** [comment]
Thanks for your feedback, and sorry for the late reply. 

I still couldn't get it to work at first, but after updating my Xcode to v6.2 (through the App store), installing unar, and afterwards also hashcat, worked.
