### ISSUE TITLE
'Warning: Legacy Top Path' on running 'brew doctor'

### ISSUE THREAD

**Issue by btburton42** [caskroom/homebrew-cask#9770]
When running `brew doctor` the output specifies the alternate phinze/homebrew cask as being a `legacy top path`. However, it looks like phinze is managing several of my brew casks. What's the recommended way forward or is this error a false positive?

I'm also receiving an error in my `Default Tap Cask Count`, which might or might not be related.

```
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-versions
/usr/local/Library/Taps/phinze/homebrew-cask (Warning: legacy tap path)
==> Homebrew-cask Default Tap Cask Count:
0 (Error reading /usr/local/Library/Taps/caskroom/homebrew-cask)
```

**Comment by vitorgalvao** [comment]
You should untap `phinze/homebrew-cask` and use `caskroom/homebrew-cask` exclusively.

**Comment by btburton42** [comment]
Any suggestions about the handful of brew-casks that are only available on the `phinze` tap? stuff like 'hipchat', 'gitter', 'iterm2', 'sourcetree'? any path to getting them in the new caskroom?

**Comment by phinze** [comment]
Hi there! Sorry for the trouble.

We just migrated, so everything should be in the new repo:

 * hipchat - https://github.com/caskroom/homebrew-cask/blob/master/Casks/hipchat.rb
 * gitter - https://github.com/caskroom/homebrew-cask/blob/master/Casks/gitter.rb
 * iterm2 -https://github.com/caskroom/homebrew-cask/blob/master/Casks/iterm2.rb
 * sourcetree - https://github.com/caskroom/homebrew-cask/blob/master/Casks/sourcetree.rb

So you should be able to just reinstall stuff after you've cleaned up the taps.

**Comment by btburton42** [comment]
No worries. That's life in dev land. Thanks for the pointers, guys!
