### ISSUE TITLE
Remove CCMenu?

### ISSUE THREAD

**Issue by EvanHahn** [caskroom/homebrew-cask#9785]
Current and future versions of [CCMenu](http://ccmenu.org/) are Mac App Store only. I saw the discussion in #9779, which makes me think that we should move the Cask to *caskroom/homebrew-versions* or the boneyard.

Should I submit a PR for this?

**Comment by rolandwalker** [comment]
Sure!  The versions repo makes sense if there is an old version that still works without the App store; the boneyard repo otherwise.

**Comment by mence** [comment]
Does this still apply if CCMenu is free on the App Store and the [release](https://github.com/erikdoe/ccmenu/releases) is also available from Github? Or is the rule that anything available on the App Store should be sourced from the App Store? #9779 was discussing Pixelmator, which is a paid product.

**Comment by vitorgalvao** [comment]
@mence If an app exists outside the MAS in its full form (meaning it’s not just a trial) it can still be included here. However, that is not the case with CCMenu. Only their pre-releases are on github, not the full version.

**Comment by mence** [comment]
@vitorgalvao great, that makes more sense. Thanks for clearing that up!
