### ISSUE TITLE
Trying to make a cask for Tuxera NTFS

### ISSUE THREAD

**Issue by jiridj** [caskroom/homebrew-cask#9802]
Hi,

Trying to make my first cask contribution. I chose a tough one to start with it seems. :-)

I want to install Tuxera NTFS for Mac with a cask. I have created a cask with the following ruby block:
```
cask :v1 => 'tuxera-ntfs' do
  version '2014'
  sha256 '808423a1246a3a9cfa03d4ada3b10cd7958e88dbb34bb0c044741d3266202514'

  url 'https://www.tuxera.com/mac/tuxerantfs_2014.dmg'
  name 'Tuxera NTFS'
  homepage 'http://www.tuxera.com/products/tuxera-ntfs-for-mac/'
  license :closed

  pkg 'Install Tuxera NTFS.app'
end
```
When I run "brew cask install taxer-ntfs" it fails with the following error.
```
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/tuxera-ntfs/2014/Install Tuxera NTFS.app>", "-target", "/"]
```

I used the flash cask as an example because the manual installation procedure seemed similar. Main difference seems to be that this installer is an .app while the flash one is a .pkg.

Does anyone know how to get around this problem?

Thanks!

Jiri

**Comment by jiridj** [comment]
Sorry ... forgot to include the output of the failed command.
```
==> Output of failed command:
installer: Error the package path specified was invalid: '/opt/homebrew-cask/Caskroom/tuxera-ntfs/2014/Install Tuxera NTFS.app'.
```

**Comment by phinze** [comment]
Hey Jiri,

That `Pathname` in the output looks suspiciously like a bug we've fixed. Can you make sure you have the latest version of brew cask with:

``` 
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

Your `brew cask --version` should report `0.53.3`

**Comment by ndr-qef** [comment]
The line `pkg 'Install Tuxera NTFS.app'` instructs the cask to install a `pkg`, but the actual artifact appears to be a [manual `.app` installer](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#installer-manual).

**Comment by jiridj** [comment]
@phinze: Cask is up to date and at 0.53.3

@ndr-qef: Indeed, this is a .app file. 

The installer wizard does nothing but make you agree with the EULA and ask for the admin password. While I would expect this to be a .pkg file, Tuxera packages it as a .app file. There is no way to have the installer execute automatically? If not this defeats the purpose of creating a cask for it.

**Comment by phinze** [comment]
Hey @jiridj, sorry about the misread on the error message.

Because this project is focused on being a scriptable CLI tool, we have a policy of not accepting installers that require a GUI popup. The good news is that I took a look at Tuxera NTFS and it seems its GUI is just a thin wrapper around a standard `mpkg`.

They also provide a nice uninstaller script to boot.

Want to take this version of the Cask out for a spin and if it works, make the modifications? I tested locally but it would be nice to have you verify.

```
cask :v1 => 'tuxera-ntfs' do
  version '2014'
  sha256 '808423a1246a3a9cfa03d4ada3b10cd7958e88dbb34bb0c044741d3266202514'

  url 'https://www.tuxera.com/mac/tuxerantfs_2014.dmg'
  name 'Tuxera NTFS'
  homepage 'http://www.tuxera.com/products/tuxera-ntfs-for-mac/'
  license :closed

  pkg '.packages/Flat/Install Tuxera NTFS.mpkg'
  uninstall :script => '/System/Library/Filesystems/fusefs_txantfs.fs/Support/uninstall-package.sh'
end
```

**Comment by jiridj** [comment]
Thanks @phinze!

That did it. I had not gotten around to investigating the uninstall, but that works as you suggested above.
