### ISSUE TITLE
Gephi is failing to start

### ISSUE THREAD

**Issue by nemonik** [caskroom/homebrew-cask#9806]
I installed gephi

    ➜  brew cask info gephi
    gephi: 0.8.2-beta
    gephi
    http://gephi.org//opt/homebrew-cask/Caskroom/gephi/0.8.2-beta (2081 files, 74M)
    https://github.com/caskroom/homebrew-cask/blob/master/Casks/gephi.rb
    ==> Contents
      Gephi.app (app)

It starts with the startup panel centered on the screen, goes for a bit informing you it is "loading cached objects" and then fails throwing to the system log:

    2/27/15 3:01:23.801 PM com.apple.xpc.launchd[1]: (org.gephi.109372[4012]) Service exited with abnormal code: 2

**Comment by rolandwalker** [comment]
Hi!  Thanks for the report!

Could you verify that the problem is not with Gephi itself?  For example, install Gephi by a different method than Homebrew-cask, and see if you get the same bug.

**Comment by nemonik** [comment]
Yeah, it appears to be this glitch.

http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/

They have some work on their end to resolve.
