### ISSUE TITLE
Failed to install brew-cask v0.53.3, Error: No such file or directory - brew-cask

### ISSUE THREAD

**Issue by vinc386** [caskroom/homebrew-cask#9807]
brew-cask just suddenly stopped working…

    Error: No such file or directory - brew-cask

I tried re-installing brew-cask, and even homebrew itself, but after all that I am still getting this same error:

![screen shot 2015-02-27 at 4 30 08 pm](https://cloud.githubusercontent.com/assets/199069/6421646/deb92784-be9e-11e4-8d28-210f92bd13db.png)

Please let me know what other info I can provide to help debug this.
Thanks in advance!

**Comment by phinze** [comment]
That's not good!

Thanks for the report... feels upstreamy... going to try repro locally. Stand by!

**Comment by phinze** [comment]
Ok I verified sanity locally, so let's see what's going on over on your side. Can you check to see if your executable works if you address it directly?

```
/usr/local/Cellar/brew-cask/0.53.3/bin/brew-cask
```

**Comment by vinc386** [comment]
This is what I got…

     $ /usr/local/Cellar/brew-cask/0.53.3/bin/brew-cask
     zsh: /usr/local/Cellar/brew-cask/0.53.3/bin/brew-cask: bad interpreter: /bin/bash^M: no such file or directory

my zsh version:

    zsh 5.0.2 (x86_64-apple-darwin13.0)

and, running that inside iTerm2.

**Comment by vinc386** [comment]
Not sure where it got the `/bin/bash^M` from, however `/bin/bash` is actually there and I believe it is the bash-3.2 that comes with my version of OS X

**Comment by phinze** [comment]
Hmmm .... sounds like git might be configured to clone things with windows line endings?

Can you move your ~/.gitconfig out of the way and retry?

**Comment by vinc386** [comment]
![screen shot 2015-02-27 at 6 02 22 pm](https://cloud.githubusercontent.com/assets/199069/6422802/ddd69c28-beaa-11e4-8f14-f2499bd60176.png)

**Comment by phinze** [comment]
Dang! So weird! :disappointed: 

Well you can manually repair that executable by removing the `^M` character(s) from it.

I still suspect it's git related - you could try to see if there are any other git configs sneaking line ending settings in there. A good starting point on learning about git's line-ending support is here: https://help.github.com/articles/dealing-with-line-endings/

**Comment by vinc386** [comment]
Thanks! Changing the EOL characters in that executable fixed the issue for me, but surely this is a very weird issue.
