### ISSUE TITLE
`brew cask uninstall ''` uninstalls everything

### ISSUE THREAD

**Issue by szhu** [caskroom/homebrew-cask#9828]
`brew cask uninstall ''` uninstalls everything.

I don't think this is documented behavior, and I just accidentally uninstalled everything.

**Comment by phinze** [comment]
Ouch! Sorry about that! Yeah we'll definitely get this cleaned up.

**Comment by szhu** [comment]
No worries, [I got it all backed up](https://github.com/szhu/important-things/blob/master/install/brew-cask.txt) :)

**Comment by adityadalal924** [comment]
No longer seems to be an issue:

```
[.../caskroom/homebrew-cask] > brew cask list
    {app list}
[.../caskroom/homebrew-cask] > brew cask uninstall ''
[.../caskroom/homebrew-cask] > brew cask list
    {same app list}
```
