### ISSUE TITLE
Installing vagrant hangs

### ISSUE THREAD

**Issue by pavelm** [caskroom/homebrew-cask#9903]
It downloads successfully, but then nothing happens. Just hangs.

```
brew cask install vagrant
==> Downloading https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2.dmg
######################################################################## 100.0%
```

**Comment by phinze** [comment]
Hi there! Could it be network related? Does this happen repeatably?

**Comment by pavelm** [comment]
Yes, every time. Network is good. The file is there in the cache when I try
again. I removed the file in the cache and tried again. Same exact issue. I
don't see any CPU or memory activity either.

**Comment by phinze** [comment]
I had somebody recently report a fishy entry in `/etc/sudoers` that was causing trouble.

Do you have any lines mentioning `installer` in that file?

```
sudo grep installer /etc/sudoers
```

**Comment by pavelm** [comment]
Nope, returns nothing.

**Comment by phinze** [comment]
Alright that's one thing ruled out!

Can you [gist](https://gist.github.com) the output with `--debug` flag?

**Comment by pavelm** [comment]
https://gist.github.com/pavelm/5522ac96403eab2ec007

**Comment by phinze** [comment]
Well one thing that the debug output tells me is that your cask installation is pretty old.

Can you upgrade with:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

And see if the issue persists?

**Comment by pavelm** [comment]
Seems to be working! Thanks!

I should've tried upgrading brew-cask first. Sorry about that.
