### ISSUE TITLE
Add ability to download digits from upstream 

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#9910]
For example get [mac/en-US/Firefox 37.0b2.dmg](http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/37.0b2/mac/en-US/Firefox%2037.0b2.dmg) and verify it with corresponding checksum from [SHA512SUMS](http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/37.0b2/SHA512SUMS), which is previously verified by [SHA512SUMS.asc](http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/37.0b2/SHA512SUMS.asc). And of course set the public part of gpg key is saved in formulae or some variable like ${mozilla-release-key}

Same [issue in brew](https://github.com/Homebrew/homebrew/issues/37441)

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This can be revisited later.
