### ISSUE TITLE
feature: accelerate brew cask downloads with a download accelerator

### ISSUE THREAD

**Issue by ssbarnea** [caskroom/homebrew-cask#9914]
Most casks do download big packages via curl or wget and we could speed up to time needed for a download considerably (2-3x) by performing the downloads using a download accelerator.

One such example is axel. Maybe we could use a wrapper for wget/curl that is using axel when this is available on there are no additional command line options (like `wget URL`).

**Comment by vitorgalvao** [comment]
[Already been discussed](https://github.com/caskroom/homebrew-cask/issues/5552).
