### ISSUE TITLE
Linter/style checker integration

### ISSUE THREAD

**Issue by jawshooah** [caskroom/homebrew-cask#9921]
What do you all think about integrating a static analysis tool like [RuboCop](https://github.com/bbatsov/rubocop) into the project? It's exceedingly useful for enforcing style conventions, checks for a number of logical errors, and is completely configurable. It could be added to the Travis build so PR submitters know to fix something without maintainer intervention.

I've already started working on this in [my own branch](https://github.com/jawshooah/homebrew-cask/tree/feature/rubocop-integration), and am currently using RuboCop in conjunction with [Overcommit](https://github.com/causes/overcommit) and other tools for all of my personal projects.

Does this sound like something you guys would like to pursue?

**Comment by phinze** [comment]
I personally think this would be _AMAZING_ because we could toss it into Travis and automate a ton of the common maintainer tasks that are manual today. :+1:

**Comment by jawshooah** [comment]
I thought so :smile: I'm happy to do a lot of the legwork here if everyone agrees it's a good idea.

**Comment by phinze** [comment]
...though I'm curious as to what you're thinking RuboCop would be useful for that we couldn't just implement as a normal Rspec test? It seems like RuboCop and Overcommit are sort of big libraries to pull in out of the gate - perhaps there's a smaller set of goals we can flesh out here before we decide on tooling?

**Comment by jawshooah** [comment]
RuboCop is useful in addition to RSpec for the same reason that [JSHint](https://github.com/jshint/jshint) is useful in addition to [Nodeunit](https://github.com/caolan/nodeunit), or [Checkstyle](https://github.com/checkstyle/checkstyle) in addition to [JUnit](http://junit.org/), or [Scalastyle](http://www.scalastyle.org) in addition to [ScalaTest](http://scalatest.org), or any other combination of linters and testing frameworks: style matters.

RSpec is awesome for verifying correctness, but it tells you nothing about the quality of the implementation. [Style guides](https://github.com/bbatsov/ruby-style-guide) exist for many reasons, and tools like RuboCop exist to enforce adherence to those style guides, or whatever modified version thereof you have decided is right for your repository.

Just to give you an idea, running RuboCop with the default configuration against the current `master` returns [over 200 offenses](https://gist.github.com/jawshooah/c1321612f3c11e080fd4) with just the linter errors enabled. Counting style errors, it's [over 13,000](https://gist.github.com/jawshooah/ade7c50ce2684df70ee1).

Obviously these numbers would go down after tweaking the configuration to match the current style. For example, about 3000 of those are `Metrics/LineLength`, 1000 are `Style/CommentAnnotation`, 4000 are `Style/HashSyntax`, 600 are `Style/IndentArray` and 700 are `Style/FileName`.

The point is that using a tool like RuboCop will help us to minimize unsafe or ugly code and maintain a consistent style throughout the project.

Overcommit was just an example of a way that I'm using RuboCop, among other linters and style checkers, to ensure that I never push dirty code in the first place :wink:

**Comment by phinze** [comment]
Ahhh okay I was originally picturing something that would run just over Casks.

I did a RuboCop integration for a project recently, and it's great for consistency, but it's got a metric buttload of opinions. I'd be cool to pull it in if we could do it verrrry gently.

What do you think about trying to do an initial config w/ `Include` / `Exclude`rules such that it only applied to Casks at first? Then we could slowly opt-in until we had the whole code base covered.

**Comment by jawshooah** [comment]
Absolutely! We could start of with a very minimal config with almost everything disabled.

RuboCop comes with a handy `--auto-gen-config` flag that generates a `.rubocop_todo.yml`, which lists all rules currently being violated, along with how many violations for each. Adding the line `inherit_from: .rubocop_todo.yml` to `.rubocop.yml` disables all those rules, so you can slowly add them in as you clean up the codebase.

**Comment by jawshooah** [comment]
@phinze I've added a minimal initial config in #9922, feel free to take a look and let me know what you think!

**Comment by phinze** [comment]
Cool - the machinery is in now.

So now it's a matter of selecting the first few cops to enable.

**Comment by jawshooah** [comment]
Here are my initial thoughts. Keep in mind that most of these can be fixed for us using `rubocop --auto-correct`:

- [`AssignmentInCondition`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L634): The only violation here is the line `while line = pipe.gets`, which could be better written as `pipe.each do |line|`. Enable it.
- [`BlockAlignment`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L816): Only violation is an `end` that was over-indented. Enable it.
- [`DeprecatedClassMethods`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L835): One use of the deprecated `File.exists?` rather than `File.exist?`. Enable it.
- [`LineLength`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L611): Disable for Casks. URLs can be an arbitrary length, so there's no point in setting a limit.
- [`AlignHash`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L53): There are several configuration options here. The style currently used in most Casks appears to be `table`, so I say fix the exceptions and enable it.
- [`AlignParameters`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L116): All but 6 Casks follow the `with_first_parameter` style, so fix the exceptions and enable it.
- [`AndOr`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L135): There's only one offense here; the Cask author mistakenly used `or` in a conditional expression, which means they likely were not aware of the [differences](http://devblog.avdi.org/2014/08/26/how-to-use-rubys-english-andor-operators-without-going-nuts/) between `and`/`or` and `&&`/`||`. Fix and enable this cop with `EnforcedStyle: conditionals`.
- [`BarePercentLiterals`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L145): The style throughout the repository seems to be `percent_q`, so change the configuration and enable it.
- [`CommentAnnotation`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L216): All of these 1000+ errors are caused by `todo` being in lowercase rather than all-caps. I'm guessing you guys are happy with the current lack of capitalization, so we should probably disable it.
- [`CommentIndentation`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L143): These are the result of comments in arrays being aligned with the elements of the array, which are indented only 1 space. As this seems to be the accepted style, I say disable.
- [`Documentation`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L162): These are undocumented `Utils` modules. Probably not worth fixing.
- [`ElseAlignment`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L180): Just an overindented `else`. Quick fix and enable.
- [`EmptyElse`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L235): These are all `# Unusual case: there is no fall-through.` These `else` clauses are intentionally left empty, so disable for Casks.
- [`EmptyLinesAroundBlockBody`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L248): 30 Casks have empty lines after `cask 'v1' => 'cask' do`. Not sure whether it's worth it to enable this.
- [`FileName`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L276): Definitely disable this for Casks, as they don't use snake_case.
- [`HashSyntax`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L320): Casks are currently still using the old rocket syntax, but the newer colon syntax is used in the application code. So we need to either make them consistent or disable this rule for Casks.
- [`IndentArray`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L299): The style guide recommends 2 spaces for array indentation, but Casks currently use just 1, so we should probably disable this for Casks.
- [`IndentHash`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L337): As with `IndentArray`, we're using 1 space for indentation here rather than 2. Disable for Casks.
- [`IndentationConsistency`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L290): There's a single under-indented line in an `else` block in `tuneinspector.rb`. Fix and enable.
- [`IndentationWidth`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L332): Just a few lines indented with 1, 3, or 4 spaces. Fix and enable.
- [`MultilineIfThen`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L366): There's a single redundant `then` in a multiline `if` expression. Fix and enable.
- [`PercentLiteralDelimiters`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L402): `%w` literals are delimited by both `{}` and `[]` in existing Casks. Up to you guys to pick which you want, or whether you care.
- [`RegexpLiteral`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L496): "Use `%r` only for regular expressions matching more than 1 `/` character." Currently `%r` is used regardless of `/` characters. I don't know if this matters.
- [`SingleSpaceBeforeFirstArg`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L537): Lots of instances of `zap :delete` where `:delete` is spaced out to align with the `uninstall` stanza. Maybe disable for Casks?
- [`SpaceAfterComma`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L548): These are all instances of `version.sub(foo,bar)`. Should probably add the space for readability and enable this.
- [`SpaceAroundOperators`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L494): Just one offense here: no space before `=>` in `zap :delete=>`. Fix and enable.
- [`SpaceBeforeComma`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L580): Just a couple offenses here. Fix and enable.
- [`SpaceInsideBrackets`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L622): Just a few offenses here as well. Fix and enable.
- [`StringLiterals`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L470): We already ask submitters to use single quotes unless string interpolation is needed, so we should fix these and enable the cop.
- [`Tab`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L671): There's a single hard tab somewhere. Gross. Fix it and enable.
- [`TrailingComma`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L534): Bunch of trailing commas after the last item of arrays and hashes. Fix and enable.
- [`TrailingWhitespace`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L686): Gross. Fix and enable.

**Comment by jawshooah** [comment]
Just out of curiosity, why are array and hash elements currently indented only 1 space from the opening bracket? I haven't seen that style used elsewhere.

**Comment by vitorgalvao** [comment]
> Just out of curiosity, why are array and hash elements currently indented only 1 space from the opening bracket? I haven't seen that style used elsewhere.

@jawshooah Likely we just started doing it and then stuck with it. Either way is fine, as long as we’re consistent (and we’re not fully, yet), so feel free to change it.

In addition, feel free to take up this issue however you’d like (even assign yourself, if you wish). I’ll label it `travis bug` (even though it’s not really a bug simply because it’s Travis-related, and there’s not much point in creating an individual label for a single issue.

**Comment by jawshooah** [comment]
RuboCop integration was added in #9922, #9936, and #9940, so this can be closed.
