### ISSUE TITLE
Calibre host unreliable and slow - undo last change.

### ISSUE THREAD

**Issue by JaredSartin** [caskroom/homebrew-cask#9934]
I was doing a fresh update on my Mac today and when it got to Calibre, it took over 35 minutes to download. Its only ~75mb in size, a mere 2 minute download using the github release link (as it was previously).

The latest commit on that file (d622c31d4aef7ad35ffe18a6b131a63202a1d963) uses the main mirror for the download, which is terribly slow on ATT UVerse in Los Angeles, CA and Comcast and Charter in Grand Rapids, MI. The github mirror is always fast, load balancing, and serving from CDNs closer to the download location.

I am not upset that the link was changed to what seems to be the better location (when looking at the download page), but it is unbearably slow.

**Comment by vitorgalvao** [comment]
Done in #9942.
