### ISSUE TITLE
balsamiq-mockups fails to install, returning 403

### ISSUE THREAD

**Issue by vinc386** [caskroom/homebrew-cask#9965]
![screen shot 2015-03-09 at 11 26 39 am](https://cloud.githubusercontent.com/assets/199069/6557914/22d0e738-c64f-11e4-9d6b-cd8773abbb05.png)

in addition to that…

    brew cask audit balsamiq-mockups
    audit for balsamiq-mockups: passed

**Comment by vitorgalvao** [comment]
Fixed. Please `brew update` and try again.

**Comment by vinc386** [comment]
Thanks, I can get the `dmg` now, however, I get this error when it ties to install the app: 
![screen shot 2015-03-09 at 1 00 03 pm](https://cloud.githubusercontent.com/assets/199069/6559858/2ec304d8-c65c-11e4-9f2f-fd75c2b25777.png)

**Comment by vitorgalvao** [comment]
Should be fixed.
