### ISSUE TITLE
Staged Installs

### ISSUE THREAD

**Issue by dschinkel** [caskroom/homebrew-cask#9974]
I installed webstorm before installing Java 6.  Should have installed Java6 first and then webstorm.  So I went back to install Java 6 using brew cask install caskroom/homebrew-versions/java6.  Then I went back to for install webstorm again and it says the install is "staged".

What does that mean?  Obviously the install isn't done, because I don't have a webstorm shortcut in OSX yet.  What do I need to do?  Why didn't it install it but staged it?

![screen shot 2015-03-09 at 11 51 49 pm](https://cloud.githubusercontent.com/assets/338798/6569391/72bd2e42-c6b7-11e4-8830-c89a72253f6f.png)

**Comment by dschinkel** [comment]
Nevermind I guess it's installed, there is a shortcut, just weird that when I searched for "webstorm" in the spotlight search like I normally do after installing an app from Homebrew it didn't show up in the search, I had to manually go to the applications folder to get to the shortcut that homebrew installed for webstorm.

**Comment by ladislas** [comment]
I've had the same issue with several casks in the last two days. don't know what is happening. sometimes the apps are installed, sometimes not...

**Comment by ladislas** [comment]
Once more while installing Mailbox App

![screenshot 2015-03-15 16 19 03](https://cloud.githubusercontent.com/assets/2206544/6656611/1ead7786-cb2f-11e4-9360-d560ffad4e84.png)

![screenshot 2015-03-15 16 18 54](https://cloud.githubusercontent.com/assets/2206544/6656613/2461513e-cb2f-11e4-8f6c-86bc3622a7c4.png)
